### ISSUE TITLE
Readme links lead to 404

### ISSUE THREAD

**Issue by webdude21** [SAP/ui5-webcomponents#1]
The following links lead to 404 (not found). They're probably internal links.
- [UI5 Web Components](https://sap.github.io/ui5-webcomponents)
- [UI5 Web Components - Playground and API Reference](https://sap.github.io/ui5-webcomponents/playground.html)

The [OpenUI5 Community Slack](https://slackui5invite.herokuapp.com) application seems to be broken too.

**Comment by petermuessig** [comment]
Hi @webdude21 ,

the repository will be setup today and the links should work this evening. We will close the ticket once the setup is completed...

Cheers,
Peter

**Comment by petermuessig** [comment]
Alternative OpenUI5 Community Slack invite: https://ui5-slack-invite.cfapps.eu10.hana.ondemand.com/

**Comment by RandomByte** [comment]
http://slackui5invite.herokuapp.com got renamed to https://join-ui5-slack.herokuapp.com (see https://github.com/SAP/ui5-tooling/commit/e2b8479c56d0aa5376f68fcc5544b7aef352a5ad#diff-04c6e90faac2675aa89e2176d2eec7d8)

I think we also tried https://ui5-slack-invite.cfapps.eu10.hana.ondemand.com/ but it was unreliable as well 😕

**Comment by adrian-bobev** [comment]
Now the links should work:

[https://sap.github.io/ui5-webcomponents/](https://sap.github.io/ui5-webcomponents/)
[https://sap.github.io/ui5-webcomponents/playground.html](https://sap.github.io/ui5-webcomponents/playground.html)
