### ISSUE TITLE
Dialog: Dialog content alignment issue with zoom

### ISSUE THREAD

**Issue by saurabhmehta02** [SAP/ui5-webcomponents#10000]
### Describe the bug

We have developed UI components using the <Dialog> web component and these are also used in mobile app.
In mobile devices for accessibility purpose, user can use dynamic font size setting and increase the font size.
If we increase the base font by 1.5x or 2x (base font size at html root is 24px or 32px) then <Dialog> web components sets left position in negative in mobile view.
For example:
if base font size is 30px then styles becomes: left: -85px
if base font size is 32px then styles becomes: left: -105px

Because of this left style, the dialog content isn't aligned in mobile resolution with higher font size.

### Reproduction steps

Navigate to https://sap.github.io/ui5-webcomponents-react/v1/?path=/story/modals-popovers-dialog--with-content&args=stretch:!true
Open chrome dev tools and enable mobile view
Set base font size to above 24px or higher and you can notice inline style is added at the dialog level and because of which the dialog content isn't aligned 

### UI5 Web Components for React Version

1.24.0

### UI5 Web Components Version

1.21.0

### Browser

Chrome, Safari

### Operating System

iOS and Android

### Organization

SAP Labs

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by NHristov-sap** [comment]
Hello @SAP/ui5-webcomponents-topic-rd, 

Please check if this is valid use case.

Best Regards,
Nikolay Hristov

**Comment by LidiyaGeorgieva** [comment]
Hello @saurabhmehta02 ,

Kindly provide more detailed steps for reproducing the issue along with a screenshot. Also, there seems to be a discrepancy between the title and the description: the title mentions "zoom," while the description refers to "Set base font size to above 24px or higher..."

Best Regards,
Lidiya

**Comment by saurabhmehta02** [comment]
Dialog rendering when base font size is 16px:
<img width="322" alt="image" src="https://github.com/user-attachments/assets/a980f7ec-24cf-459d-b5a6-c225977f0ae4">

Dialog rendering when base font size is 28px:
<img width="326" alt="image" src="https://github.com/user-attachments/assets/bf85fe1f-c1e5-4de8-8310-e22960a62edc">

Left position value:
<img width="731" alt="image" src="https://github.com/user-attachments/assets/eb54d9ba-7af5-4696-a22d-aec5b0e0877e">

Dialog rendering when base font size is 32px:
<img width="715" alt="image" src="https://github.com/user-attachments/assets/b14b60da-d46e-4b81-bd41-91a3853ec7ba">

@LidiyaGeorgieva I hope above screenshots are enough for you to understand the issue.
Also, its easily reproducible in the web components demo too as shared in the reproduce steps.

We are using the web module creating using the dialog component in mobile app, its zoom in the mobile device (for accessible users). The font size in the web module is adjusted dynamically according to the zoom level on the mobile device.

**Comment by LidiyaGeorgieva** [comment]
Hello @saurabhmehta02 ,

Please be more specific how you "Set base font size to above 24px or higher"?
If I set "font-size: 30px" to the HTML element I see no issue:
<img width="959" alt="{3D298A13-DD32-454F-B411-FCF2527B6D9E}" src="https://github.com/user-attachments/assets/786a0f78-a850-4fd6-afe1-4c4d42967a5e">

Best Regards,
Lidiya

**Comment by saurabhmehta02** [comment]
Hi @LidiyaGeorgieva 
Setting font-size here in the dev tools won't reflect for all the components.
I am updating font size at the html root using below code in JavaScript:
`document.documentElement.style.fontSize = "32px";`

As I mentioned previously, in our use case the web module is being used in the mobile app too.
When user is changing font-size in the mobile device, we set font-size for the web module as well using the code I shared.
This will ensure the base font size is changed for all the elements.

Thanks,
Saurabh

**Comment by saurabhmehta02** [comment]
@LidiyaGeorgieva If you want to reproduce in the component demo page, please use dev tools and open the dialog component in mobile view (which have done already) and then in the console run following script:
`document.documentElement.style.fontSize = "32px";`

Thanks,
Saurabh

**Comment by LidiyaGeorgieva** [comment]
Hello @saurabhmehta02 , 

After following your steps, the dialog appears fine and I don't see any issues:
<img width="957" alt="{5C4EA8DB-BD90-4D59-8EC2-3A79458E7678}" src="https://github.com/user-attachments/assets/44d1f19b-1476-482e-9c3e-05c281c1f968">

Please provide an isolated, reproducible example of the problem, or we’ll need to close the ticket.

Best Regards,
Lidiya

**Comment by saurabhmehta02** [comment]
@LidiyaGeorgieva I am attaching the sample react app and two recordings.
In first recording, I am sharing steps to reproduce the issue in the web component demo page itself.
In the 2nd recording, I have reproduced the issue in the sample react app.

Steps to run the app:
node version 18.x.x
npm install --legacy-peer-deps
npm run start

It should ideally run on port 3000 so URL should be localhost:3000.
[sample_repo.zip](https://github.com/user-attachments/files/17364465/sample_repo.zip)

https://github.com/user-attachments/assets/20574ca8-ee9e-4f77-b186-07bf661d80c9


https://github.com/user-attachments/assets/ca059383-ecaa-4423-9ec7-66bcee82e0f7

**Comment by saurabhmehta02** [comment]
Hi @LidiyaGeorgieva 
We use react web components in our project - https://sap.github.io/ui5-webcomponents-react 
Has the fix been delivered for react web components as well?
Kindly update.

Thanks,
Saurabh

**Comment by LidiyaGeorgieva** [comment]
@Lukas742 , could you help here? 
The fix is  included in version v2.5.0-rc.1 of ui5-webcomponents

**Comment by Lukas742** [comment]
Hi @saurabhmehta02 

Starting with version 2.4.0 of `@ui5/webcomponents-react`, all ui5wcr packages now align their minor version with `@ui5/webcomponents`. However, pre-release versions, such as the current release candidate, are not supported out of the box. This is because when a new feature (like a component, property, etc.) is added, our wrapper needs to be updated as well. 

For bug fixes, you can likely still test the RC version, but new features that require "wrapping" won't be available as React props, components, etc., and you will most likely encounter peer-dependency errors, which must be ignored.
