### ISSUE TITLE
[SF_ACC][Label][Select]: Label "for" property not associated with Select

### ISSUE THREAD

**Issue by ksblklu02** [SAP/ui5-webcomponents#10003]
### Bug Description

Label "for" property not working for Select

### Affected Component

ui5-label

### Expected Behaviour

The label text should be announced when the associated Select component get focused

### Steps to Reproduce

1. Go to https://sap.github.io/ui5-webcomponents/components/Select/
2. Set label for Select component and tab to focus on the Select
3. See the label for Select component is not announced

<img width="1675" alt="image" src="https://github.com/user-attachments/assets/dfc8c3df-b08b-4d05-a72d-39c038d8d45b">

### Priority

Medium

### UI5 Web Components Version

2.3.0

### Browser

Chrome

### Organization

SAP SuccessFactors

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ilhan007** [comment]
Hi @ksblklu02 

For the time being you can use the available Select's acc APIs: 
```ts
/**
	 * Defines the accessible ARIA name of the component.
	 * @since 1.0.0-rc.9
	 * @public
	 * @default undefined
	 */
	@property()
	accessibleName?: string;

	/**
	 * Receives id(or many ids) of the elements that label the select.
	 * @default undefined
	 * @public
	 * @since 1.0.0-rc.15
	 */
	@property()
	accessibleNameRef?: string;
```

```html
<ui5-label id="myLabel">my text</ui5-label>
<ui5-select accessible-name-ref="myLabel"></ui5-select>
```

**Comment by ilhan007** [comment]
Hi @ksblklu02 did you try using  the suggestion above, does it work for you?
