### ISSUE TITLE
[table]: Popin behavior incorrect when some values are right aligned

### ISSUE THREAD

**Issue by Neeeko** [SAP/ui5-webcomponents#10017]
### Bug Description

Fiori guidelines require developers to right-align numeric values.

Still, when the column goes in popin mode, these values shouldn't be right aligned anymore as they're displayed inline. However, that's not the case in the new table version:
<img width="809" alt="Screenshot 2024-10-14 at 1 58 49 PM" src="https://github.com/user-attachments/assets/287fa346-203c-43ae-92f8-290f58c8176e">
**Note how the Dimensions column is incorrectly right aligned** 
<img width="353" alt="Screenshot 2024-10-14 at 1 58 55 PM" src="https://github.com/user-attachments/assets/9d8dc325-5601-4ac4-851f-8000351897a4">

====================
See the behavior in the [Fiori Guidelines for the Responsive Table](https://experience.sap.com/fiori-design-web/responsive-table/):
<img width="505" alt="Screenshot 2024-10-14 at 1 59 02 PM" src="https://github.com/user-attachments/assets/5e756d85-a2bc-48d4-8c77-5f69c3a33feb">

Or in SAPUI5, the Weight column is properly aligned:
<img width="1728" alt="Screenshot 2024-10-14 at 1 59 42 PM" src="https://github.com/user-attachments/assets/6eb82dad-70bf-48ed-94cb-e00f9f9251d8">
<img width="521" alt="Screenshot 2024-10-14 at 1 59 33 PM" src="https://github.com/user-attachments/assets/0e7c187f-f48b-4b3e-aabb-5e2e4f7072c8">

### Affected Component

ui5-table

### Expected Behaviour

Even if a column is right aligned, this state shouldn't be maintained when the table goes in popin mode.

### Isolated Example

https://sap.github.io/ui5-webcomponents/play/#eyJpbmRleC5odG1sIjp7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuPCFET0NUWVBFIGh0bWw-XG48aHRtbCBsYW5nPVwiZW5cIj5cblxuXG5cbjxoZWFkPlxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG4gICAgPC9zdHlsZT5cblxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG4gICAgPC9zdHlsZT5cblxuICAgIDxtZXRhIGNoYXJzZXQ9XCJVVEYtOFwiPlxuICAgIDxtZXRhIG5hbWU9XCJ2aWV3cG9ydFwiIGNvbnRlbnQ9XCJ3aWR0aD1kZXZpY2Utd2lkdGgsIGluaXRpYWwtc2NhbGU9MS4wXCI-XG4gICAgPHRpdGxlPlNhbXBsZTwvdGl0bGU-XG48L2hlYWQ-XG5cbjxib2R5IHN0eWxlPVwiYmFja2dyb3VuZC1jb2xvcjogdmFyKC0tc2FwQmFja2dyb3VuZENvbG9yKVwiPlxuICAgIDxkaXYgY2xhc3M9XCJzZWN0aW9uXCI-XG48IS0tIHBsYXlncm91bmQtZm9sZC1lbmQgLS0-XG5cdFx0PHVpNS1zbGlkZXIgaWQ9XCJzbGlkZXJcIiBtaW49XCIwXCIgbWF4PVwiMTAwXCIgc3RlcD1cIjFcIiB2YWx1ZT1cIjEwMFwiIGxhYmVsLWludGVydmFsPVwiMFwiPjwvdWk1LXNsaWRlcj5cblx0XHQ8dWk1LXRhYmxlIGlkPVwidGFibGVcIiBvdmVyZmxvdy1tb2RlPVwiUG9waW5cIj5cblx0XHRcdDx1aTUtdGFibGUtaGVhZGVyLXJvdyBzbG90PVwiaGVhZGVyUm93XCI-XG5cdFx0XHRcdDx1aTUtdGFibGUtaGVhZGVyLWNlbGwgaWQ9XCJwcm9kdXRDb2xcIj48c3Bhbj5Qcm9kdWN0PC9zcGFuPjwvdWk1LXRhYmxlLWhlYWRlci1jZWxsPlxuXHRcdFx0XHQ8dWk1LXRhYmxlLWhlYWRlci1jZWxsIGlkPVwic3VwcGxpZXJDb2xcIj5TdXBwbGllcjwvdWk1LXRhYmxlLWhlYWRlci1jZWxsPlxuXHRcdFx0XHQ8dWk1LXRhYmxlLWhlYWRlci1jZWxsIGlkPVwiZGltZW5zaW9uc0NvbFwiIGhvcml6b250YWwtYWxpZ249XCJSaWdodFwiIGltcG9ydGFuY2U9XCItMVwiIG1pbi13aWR0aD1cIjMwMHB4XCI-RGltZW5zaW9uczwvdWk1LXRhYmxlLWhlYWRlci1jZWxsPlxuXHRcdFx0XHQ8dWk1LXRhYmxlLWhlYWRlci1jZWxsIGlkPVwid2VpZ2h0Q29sXCIgbWluLXdpZHRoPVwiMTAwcHhcIj5XZWlnaHQ8L3VpNS10YWJsZS1oZWFkZXItY2VsbD5cblx0XHRcdFx0PHVpNS10YWJsZS1oZWFkZXItY2VsbCBpZD1cInByaWNlQ29sXCIgbWluLXdpZHRoPVwiMjIwcHhcIj5QcmljZTwvdWk1LXRhYmxlLWhlYWRlci1jZWxsPlxuXHRcdFx0PC91aTUtdGFibGUtaGVhZGVyLXJvdz5cbjwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuXHRcdFx0PHVpNS10YWJsZS1yb3c-XG5cdFx0XHRcdDx1aTUtdGFibGUtY2VsbD48dWk1LWxhYmVsPjxiPk5vdGVib29rIEJhc2ljIDE1PC9iPjxicj5IVC0xMDAwPC91aTUtbGFiZWw-PC91aTUtdGFibGUtY2VsbD5cblx0XHRcdFx0PHVpNS10YWJsZS1jZWxsPjx1aTUtbGFiZWw-VmVyeSBCZXN0IFNjcmVlbnM8L3VpNS1sYWJlbD48L3VpNS10YWJsZS1jZWxsPlxuXHRcdFx0XHQ8dWk1LXRhYmxlLWNlbGw-PHVpNS1sYWJlbD4zMCB4IDE4IHggMyBjbTwvdWk1LWxhYmVsPjwvdWk1LXRhYmxlLWNlbGw-XG5cdFx0XHRcdDx1aTUtdGFibGUtY2VsbD48dWk1LWxhYmVsIHN0eWxlPVwiY29sb3I6ICMyYjdjMmJcIj48Yj40LjI8L2I-IEtHPC91aTUtbGFiZWw-PC91aTUtdGFibGUtY2VsbD5cblx0XHRcdFx0PHVpNS10YWJsZS1jZWxsPjx1aTUtbGFiZWw-PGI-OTU2PC9iPiBFVVI8L3VpNS1sYWJlbD48L3VpNS10YWJsZS1jZWxsPlxuXHRcdFx0PC91aTUtdGFibGUtcm93PlxuXHRcdFx0PHVpNS10YWJsZS1yb3c-XG5cdFx0XHRcdDx1aTUtdGFibGUtY2VsbD48dWk1LWxhYmVsPjxiPk5vdGVib29rIEJhc2ljIDE3PC9iPjxicj5IVC0xMDAxPC91aTUtbGFiZWw-PC91aTUtdGFibGUtY2VsbD5cblx0XHRcdFx0PHVpNS10YWJsZS1jZWxsPjx1aTUtbGFiZWw-U21hcnRjYXJkczwvdWk1LWxhYmVsPjwvdWk1LXRhYmxlLWNlbGw-XG5cdFx0XHRcdDx1aTUtdGFibGUtY2VsbD48dWk1LWxhYmVsPjI5IHggMTcgeCAzLjEgY208L3VpNS1sYWJlbD48L3VpNS10YWJsZS1jZWxsPlxuXHRcdFx0XHQ8dWk1LXRhYmxlLWNlbGw-PHVpNS1sYWJlbCBzdHlsZT1cImNvbG9yOiAjMmI3YzJiXCI-PGI-NC41PC9iPiBLRzwvdWk1LWxhYmVsPjwvdWk1LXRhYmxlLWNlbGw-XG5cdFx0XHRcdDx1aTUtdGFibGUtY2VsbD48dWk1LWxhYmVsPjxiPjEyNDk8L2I-IEVVUjwvdWk1LWxhYmVsPjwvdWk1LXRhYmxlLWNlbGw-XG5cdFx0XHQ8L3VpNS10YWJsZS1yb3c-XG5cdFx0XHQ8dWk1LXRhYmxlLXJvdz5cblx0XHRcdFx0PHVpNS10YWJsZS1jZWxsPjx1aTUtbGFiZWw-PGI-Tm90ZWJvb2sgQmFzaWMgMTg8L2I-PGJyPkhULTEwMDI8L3VpNS1sYWJlbD48L3VpNS10YWJsZS1jZWxsPlxuXHRcdFx0XHQ8dWk1LXRhYmxlLWNlbGw-PHVpNS1sYWJlbD5UZWNobm9jb208L3VpNS1sYWJlbD48L3VpNS10YWJsZS1jZWxsPlxuXHRcdFx0XHQ8dWk1LXRhYmxlLWNlbGw-PHVpNS1sYWJlbD4zMiB4IDIxIHggNCBjbTwvdWk1LWxhYmVsPjwvdWk1LXRhYmxlLWNlbGw-XG5cdFx0XHRcdDx1aTUtdGFibGUtY2VsbD48dWk1LWxhYmVsIHN0eWxlPVwiY29sb3I6ICMyYjdjMmJcIj48Yj4zLjc8L2I-IEtHPC91aTUtbGFiZWw-PC91aTUtdGFibGUtY2VsbD5cblx0XHRcdFx0PHVpNS10YWJsZS1jZWxsPjx1aTUtbGFiZWw-PGI-Mjk8L2I-IEVVUjwvdWk1LWxhYmVsPjwvdWk1LXRhYmxlLWNlbGw-XG5cdFx0XHQ8L3VpNS10YWJsZS1yb3c-XG48IS0tIHBsYXlncm91bmQtZm9sZC1lbmQgLS0-XG5cdFx0PC91aTUtdGFibGU-XG48IS0tIHBsYXlncm91bmQtZm9sZCAtLT5cblx0PC9kaXY-XG4gICAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwibWFpbi5qc1wiPjwvc2NyaXB0PlxuPC9ib2R5PlxuXG48L2h0bWw-XG48IS0tIHBsYXlncm91bmQtZm9sZC1lbmQgLS0-XG4ifSwibWFpbi5qcyI6eyJuYW1lIjoibWFpbi5qcyIsImNvbnRlbnQiOiIvKiBwbGF5Z3JvdW5kLWhpZGUgKi9cbmltcG9ydCBcIi4vcGxheWdyb3VuZC1zdXBwb3J0LmpzXCI7XG4vKiBwbGF5Z3JvdW5kLWhpZGUtZW5kICovXG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMvZGlzdC9UYWJsZS5qc1wiO1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzL2Rpc3QvVGFibGVIZWFkZXJSb3cuanNcIjtcbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L1RhYmxlSGVhZGVyQ2VsbC5qc1wiO1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzL2Rpc3QvTGFiZWwuanNcIjtcbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L0lucHV0LmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMvZGlzdC9TbGlkZXIuanNcIjtcblxuY29uc3QgdGFibGUgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZChcInRhYmxlXCIpO1xuY29uc3Qgc2xpZGVyID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoXCJzbGlkZXJcIik7XG5zbGlkZXIuYWRkRXZlbnRMaXN0ZW5lcihcImlucHV0XCIsIChlKSA9PiB7XG5cdHRhYmxlLnN0eWxlLndpZHRoID0gYCR7ZS50YXJnZXQudmFsdWV9JWA7XG59KTsifX0

### Steps to Reproduce

1. Go to the attached link (or in any table, add `horizontal-align="Right"` to any `ui5-table-header-cell`)
2. Reduce the table width to trigger popin mode
3. See that the column is still right aligned in popin mode

### Priority

Medium

### UI5 Web Components Version

2.3.0

### Browser

Chrome, Edge, Firefox, Safari

### Organization

SuccessFactors

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by PetyaMarkovaBogdanova** [comment]
Hi colleagues,
can you, please, why this misalignment happen, when using popin overflow mode of the table?
Best regards,
Petya Markova.
(UI5 Dispatcher)

**Comment by simlin** [comment]
Internal Incident DINC0298345
