### ISSUE TITLE
[dynamic-page]: Scrolling behavior isn't smooth when header snaps

### ISSUE THREAD

**Issue by Neeeko** [SAP/ui5-webcomponents#10011]
### Bug Description

When you scroll and the header content snaps, the page content gets scroll down lower than where the user initial was.
For example, in the recording attached, we can see that right before the header content snaps, I was looking at the table header. However as soon as the header content snaps, the scroll goes to the third row.

https://github.com/user-attachments/assets/a39006c3-d402-4036-b1e9-445ff9af7c8e

### Affected Component

ui5-dynamic-page

### Expected Behaviour

When the header content snaps, the main content scroll should remain the same.

### Isolated Example

https://sap.github.io/ui5-webcomponents/components/fiori/DynamicPage/

### Steps to Reproduce

Can be reproduced by scrolling in the example of the Dynamic Page: https://sap.github.io/ui5-webcomponents/components/fiori/DynamicPage/

### Priority

Medium

### UI5 Web Components Version

2.3.0

### Browser

Chrome, Edge, Firefox, Safari

### Operating System

macOS

### Organization

SuccessFactors

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by PetyaMarkovaBogdanova** [comment]
Hi colleagues,
can you, please, check whether this behaviour of the DP snap on scroll is as designed or it is a problem?
Best regards,
Petya Markova.
(UI5 Web Components Dispatcher)
