### ISSUE TITLE
[dynamic-page]: Hover state of the header is incorrectly activated

### ISSUE THREAD

**Issue by Neeeko** [SAP/ui5-webcomponents#10019]
### Bug Description

When you use the Expand/Collapse buttons ("v", "^") of the Dynamic Page, the hover state of the Header stays activated (grey) although it shouldn't be.

See the following recording:

https://github.com/user-attachments/assets/c627ada2-7016-4968-b24b-26b4ea5f64f4

### Affected Component

ui5-dynamic-page

### Expected Behaviour

The hover state should only be active when the mouse if hovering the header, but not when interacting with other elements.

### Isolated Example

https://sap.github.io/ui5-webcomponents/components/fiori/DynamicPage/

### Steps to Reproduce

1. Go to the documentation: https://sap.github.io/ui5-webcomponents/components/fiori/DynamicPage/
2. Click multiple times on the "v", "^" button to expand/collapse the header

### Priority

Medium

### UI5 Web Components Version

2.3.0

### Browser

Chrome, Edge, Firefox, Safari

### Organization

SuccessFactors

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by PetyaMarkovaBogdanova** [comment]
Hi colleagues,
can you, please, take a look on why the hover class is remaining after multiple expand/collapse by the button?
Best regards,
Petya.
