### ISSUE TITLE
[Slider | UI5 | a11y]: Slider grey line is having color contrast issue

### ISSUE THREAD

**Issue by lateefsofi** [SAP/ui5-webcomponents#10021]
### Bug Description

Slider grey line is having color contrast issue even with white background
![image](https://github.com/user-attachments/assets/284475a2-41fe-41d9-a2a4-ccbeceb11e5f)

### Affected Component

Slider

### Expected Behaviour

Component should not have any a11y issue https://sap.github.io/ui5-webcomponents/v1/components/Slider/

### Steps to Reproduce

1.
2.
3.
...

### Priority

High

### UI5 Web Components Version

1.24.11

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by PetyaMarkovaBogdanova** [comment]
Hi colleagues from @SAP/ui5-webcomponents-topic-rl ,
I did internal testing with Color Contrast Checker tool and it ended with same results, when removed the gray background:
<img width="1725" alt="image" src="https://github.com/user-attachments/assets/a1a53f2e-d42a-4e0f-972e-9577cc250246">
Can you, please, check?
Best regards,
Petya Markova.
(UI5 Dispatcher)

**Comment by Okiana** [comment]
Hello colleagues and @lateefsofi

Thank you for reporting the contrast issue with the slider component. Based on the feedback from our design team, I would like to clarify the decision taken regarding this matter.

The slider axis design requires a 3:1 contrast ratio between the active (blue) part and the non-active (light gray) part. To ensure the end of the axis is perceived with the necessary contrast, a dark gray dot was added at the end. The contrast ratio between the dot and the gray background is compliant with accessibility requirements. ![Image](https://github.com/user-attachments/assets/40431a8d-b8dc-4966-a034-cc7b6e6b9ee7)


Achieving a 3:1 contrast ratio between the blue and gray parts of the axis, while also maintaining the contrast between the gray axis and the background, is mathematically impossible. Therefore, the design decision was made to use the contrasted dot, which was reviewed and approved by an accessibility expert at the time of the component's design. ![Image](https://github.com/user-attachments/assets/022c6015-8f8a-46f6-a70e-498920ac0a5a)


Please let us know if you have any further questions or need additional clarifications.

Kind regards,
Evdokia
