### ISSUE TITLE
[TableGrowing]: Button is displayed even when type is "Scroll"

### ISSUE THREAD

**Issue by limenet** [SAP/ui5-webcomponents#10045]
### Bug Description

Up until v2.1.2 `<ui5-table-growing type="Scroll">` did not show a "More" button. Starting with v2.2.0 it does.

### Affected Component

TableGrowing

### Expected Behaviour

Unless `type="Button"` (or e.g. a hypothetical `show-button="true"`), the "More" button should not be shown.

### Isolated Example

https://sap.github.io/ui5-webcomponents/play/#eyJpbmRleC5odG1sIjp7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuPCFET0NUWVBFIGh0bWw-XG48aHRtbCBsYW5nPVwiZW5cIj5cblxuXG48aGVhZD5cbiAgICBcbiAgICA8c3R5bGU-XG4gICAgICAqOm5vdCg6ZGVmaW5lZCkge1xuICAgICAgICBkaXNwbGF5OiBub25lO1xuICAgICAgfVxuICAgIDwvc3R5bGU-XG5cbiAgICA8bWV0YSBjaGFyc2V0PVwiVVRGLThcIj5cbiAgICA8bWV0YSBuYW1lPVwidmlld3BvcnRcIiBjb250ZW50PVwid2lkdGg9ZGV2aWNlLXdpZHRoLCBpbml0aWFsLXNjYWxlPTEuMFwiPlxuICAgIDx0aXRsZT5TYW1wbGU8L3RpdGxlPlxuPC9oZWFkPlxuXG48Ym9keSBzdHlsZT1cImJhY2tncm91bmQtY29sb3I6IHZhcigtLXNhcEJhY2tncm91bmRDb2xvcilcIj5cbiAgICA8ZGl2IGNsYXNzPVwic2VjdGlvblwiIHN0eWxlPVwiaGVpZ2h0OiAxMDBweDsgb3ZlcmZsb3c6IGF1dG87XCI-XG48IS0tIHBsYXlncm91bmQtZm9sZC1lbmQgLS0-XG5cdFx0PHVpNS10YWJsZSBpZD1cInRhYmxlXCI-XG5cdFx0XHQ8dWk1LXRhYmxlLWdyb3dpbmcgaWQ9XCJncm93aW5nXCIgdHlwZT1cIlNjcm9sbFwiIHNsb3Q9XCJmZWF0dXJlc1wiPjwvdWk1LXRhYmxlLWdyb3dpbmc-XG48IS0tIHBsYXlncm91bmQtZm9sZCAtLT5cblx0XHRcdDx1aTUtdGFibGUtaGVhZGVyLXJvdyBzbG90PVwiaGVhZGVyUm93XCI-XG5cdFx0XHRcdDx1aTUtdGFibGUtaGVhZGVyLWNlbGwgaWQ9XCJwcm9kdXRDb2xcIj48c3Bhbj5Qcm9kdWN0PC9zcGFuPjwvdWk1LXRhYmxlLWhlYWRlci1jZWxsPlxuXHRcdFx0XHQ8dWk1LXRhYmxlLWhlYWRlci1jZWxsIGlkPVwic3VwcGxpZXJDb2xcIj5TdXBwbGllcjwvdWk1LXRhYmxlLWhlYWRlci1jZWxsPlxuXHRcdFx0XHQ8dWk1LXRhYmxlLWhlYWRlci1jZWxsIGlkPVwiZGltZW5zaW9uc0NvbFwiPkRpbWVuc2lvbnM8L3VpNS10YWJsZS1oZWFkZXItY2VsbD5cblx0XHRcdFx0PHVpNS10YWJsZS1oZWFkZXItY2VsbCBpZD1cIndlaWdodENvbFwiPldlaWdodDwvdWk1LXRhYmxlLWhlYWRlci1jZWxsPlxuXHRcdFx0XHQ8dWk1LXRhYmxlLWhlYWRlci1jZWxsIGlkPVwicHJpY2VDb2xcIj5QcmljZTwvdWk1LXRhYmxlLWhlYWRlci1jZWxsPlxuXHRcdFx0PC91aTUtdGFibGUtaGVhZGVyLXJvdz5cblx0XHRcdDx1aTUtdGFibGUtcm93IHJvdy1rZXk9XCIwXCI-XG5cdFx0XHRcdDx1aTUtdGFibGUtY2VsbD48dWk1LWxhYmVsPjxiPk5vdGVib29rIEJhc2ljIDE1PC9iPjxicj5IVC0xMDAwPC91aTUtbGFiZWw-PC91aTUtdGFibGUtY2VsbD5cblx0XHRcdFx0PHVpNS10YWJsZS1jZWxsPjx1aTUtbGFiZWw-VmVyeSBCZXN0IFNjcmVlbnM8L3VpNS1sYWJlbD48L3VpNS10YWJsZS1jZWxsPlxuXHRcdFx0XHQ8dWk1LXRhYmxlLWNlbGw-PHVpNS1sYWJlbD4zMCB4IDE4IHggMyBjbTwvdWk1LWxhYmVsPjwvdWk1LXRhYmxlLWNlbGw-XG5cdFx0XHRcdDx1aTUtdGFibGUtY2VsbD48dWk1LWxhYmVsIHN0eWxlPVwiY29sb3I6ICMyYjdjMmJcIj48Yj40LjI8L2I-IEtHPC91aTUtbGFiZWw-PC91aTUtdGFibGUtY2VsbD5cblx0XHRcdFx0PHVpNS10YWJsZS1jZWxsPjx1aTUtbGFiZWw-PGI-OTU2PC9iPiBFVVI8L3VpNS1sYWJlbD48L3VpNS10YWJsZS1jZWxsPlxuXHRcdFx0PC91aTUtdGFibGUtcm93PlxuXHRcdFx0PHVpNS10YWJsZS1yb3cgcm93LWtleT1cIjFcIj5cblx0XHRcdFx0PHVpNS10YWJsZS1jZWxsPjx1aTUtbGFiZWw-PGI-Tm90ZWJvb2sgQmFzaWMgMTc8L2I-PGJyPkhULTEwMDE8L3VpNS1sYWJlbD48L3VpNS10YWJsZS1jZWxsPlxuXHRcdFx0XHQ8dWk1LXRhYmxlLWNlbGw-PHVpNS1sYWJlbD5TbWFydGNhcmRzPC91aTUtbGFiZWw-PC91aTUtdGFibGUtY2VsbD5cblx0XHRcdFx0PHVpNS10YWJsZS1jZWxsPjx1aTUtbGFiZWw-MjkgeCAxNyB4IDMuMSBjbTwvdWk1LWxhYmVsPjwvdWk1LXRhYmxlLWNlbGw-XG5cdFx0XHRcdDx1aTUtdGFibGUtY2VsbD48dWk1LWxhYmVsIHN0eWxlPVwiY29sb3I6ICMyYjdjMmJcIj48Yj40LjU8L2I-IEtHPC91aTUtbGFiZWw-PC91aTUtdGFibGUtY2VsbD5cblx0XHRcdFx0PHVpNS10YWJsZS1jZWxsPjx1aTUtbGFiZWw-PGI-MTI0OTwvYj4gRVVSPC91aTUtbGFiZWw-PC91aTUtdGFibGUtY2VsbD5cblx0XHRcdDwvdWk1LXRhYmxlLXJvdz5cblx0XHRcdDx1aTUtdGFibGUtcm93IHJvdy1rZXk9XCIyXCI-XG5cdFx0XHRcdDx1aTUtdGFibGUtY2VsbD48dWk1LWxhYmVsPjxiPk5vdGVib29rIEJhc2ljIDE4PC9iPjxicj5IVC0xMDAyPC91aTUtbGFiZWw-PC91aTUtdGFibGUtY2VsbD5cblx0XHRcdFx0PHVpNS10YWJsZS1jZWxsPjx1aTUtbGFiZWw-VGVjaG5vY29tPC91aTUtbGFiZWw-PC91aTUtdGFibGUtY2VsbD5cblx0XHRcdFx0PHVpNS10YWJsZS1jZWxsPjx1aTUtbGFiZWw-MzIgeCAyMSB4IDQgY208L3VpNS1sYWJlbD48L3VpNS10YWJsZS1jZWxsPlxuXHRcdFx0XHQ8dWk1LXRhYmxlLWNlbGw-PHVpNS1sYWJlbCBzdHlsZT1cImNvbG9yOiAjMmI3YzJiXCI-PGI-My43PC9iPiBLRzwvdWk1LWxhYmVsPjwvdWk1LXRhYmxlLWNlbGw-XG5cdFx0XHRcdDx1aTUtdGFibGUtY2VsbD48dWk1LWxhYmVsPjxiPjI5PC9iPiBFVVI8L3VpNS1sYWJlbD48L3VpNS10YWJsZS1jZWxsPlxuXHRcdFx0PC91aTUtdGFibGUtcm93PlxuPCEtLSBwbGF5Z3JvdW5kLWZvbGQtZW5kIC0tPlxuXHRcdDwvdWk1LXRhYmxlPlxuPCEtLSBwbGF5Z3JvdW5kLWZvbGQgLS0-XG5cdDwvZGl2PlxuICAgIDxzY3JpcHQgdHlwZT1cIm1vZHVsZVwiIHNyYz1cIm1haW4uanNcIj48L3NjcmlwdD5cbjwvYm9keT5cblxuPC9odG1sPlxuPCEtLSBwbGF5Z3JvdW5kLWZvbGQtZW5kIC0tPiJ9LCJtYWluLmpzIjp7Im5hbWUiOiJtYWluLmpzIiwiY29udGVudCI6Ii8qIHBsYXlncm91bmQtaGlkZSAqL1xuaW1wb3J0IFwiLi9wbGF5Z3JvdW5kLXN1cHBvcnQuanNcIjtcbi8qIHBsYXlncm91bmQtaGlkZS1lbmQgKi9cbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L1RhYmxlLmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMvZGlzdC9UYWJsZUdyb3dpbmcuanNcIjtcbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L1RhYmxlSGVhZGVyUm93LmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMvZGlzdC9UYWJsZUhlYWRlckNlbGwuanNcIjtcbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L0xhYmVsLmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMvZGlzdC9JbnB1dC5qc1wiO1xuXG5jb25zdCBNQVhfR1JPVyA9IDIwO1xuXG5jb25zdCB0YWJsZSA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKFwidGFibGVcIik7XG5jb25zdCBncm93aW5nID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoXCJncm93aW5nXCIpO1xuXG5sZXQgY291bnRlciA9IDA7XG5cbmdyb3dpbmcuYWRkRXZlbnRMaXN0ZW5lcihcImxvYWQtbW9yZVwiLCAoKSA9PiB7XG5cdGZvciAobGV0IGkgPSAwOyBpIDwgNTsgaSsrKSB7XG5cdFx0Y29uc3QgbmV3Um93ID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudChcInVpNS10YWJsZS1yb3dcIik7XG5cdFx0bmV3Um93LnNldEF0dHJpYnV0ZShcImtleVwiLCB0YWJsZS5yb3dzLmxlbmd0aCArIGkpO1xuXHRcdG5ld1Jvdy5pbm5lckhUTUwgPSBgXG5cdFx0XHQ8dWk1LXRhYmxlLWNlbGw-PHVpNS1sYWJlbD48Yj5Ob3RlYm9vayBCYXNpYyAkezE4ICsgdGFibGUucm93cy5sZW5ndGggKyBpfTwvYj48YnI-SFQtMTAwJHsyICsgdGFibGUucm93cy5sZW5ndGggKyBpfTwvdWk1LWxhYmVsPjwvdWk1LXRhYmxlLWNlbGw-XG5cdFx0XHQ8dWk1LXRhYmxlLWNlbGw-PHVpNS1sYWJlbD5UZWNobm9jb208L3VpNS1sYWJlbD48L3VpNS10YWJsZS1jZWxsPlxuXHRcdFx0PHVpNS10YWJsZS1jZWxsPjx1aTUtbGFiZWw-MzIgeCAyMSB4IDQgY208L3VpNS1sYWJlbD48L3VpNS10YWJsZS1jZWxsPlxuXHRcdFx0PHVpNS10YWJsZS1jZWxsPjx1aTUtbGFiZWwgc3R5bGU9XCJjb2xvcjogIzJiN2MyYlwiPjxiPjMuNzwvYj4gS0c8L3VpNS1sYWJlbD48L3VpNS10YWJsZS1jZWxsPlxuXHRcdFx0PHVpNS10YWJsZS1jZWxsPjx1aTUtbGFiZWw-PGI-Mjk8L2I-IEVVUjwvdWk1LWxhYmVsPjwvdWk1LXRhYmxlLWNlbGw-XG5cdFx0YDtcblx0XHR0YWJsZS5hcHBlbmRDaGlsZChuZXdSb3cpO1xuXHR9XG5cblx0Y291bnRlcisrO1xuXHRpZiAoY291bnRlciA-PSBNQVhfR1JPVykge1xuXHRcdGdyb3dpbmcuZGlzYWJsZWQgPSB0cnVlO1xuXHRcdHJldHVybjtcblx0fVxufSk7XG4ifX0

### Steps to Reproduce

1. Create a `<ui5-table>`
2. Add `<ui5-table-growing type="Scroll">`
3. Observe the visible "More" button

### Priority

Low

### UI5 Web Components Version

2.3.0

### Browser

Chrome

### Operating System

Windows

### Additional Context

https://github.com/SAP/ui5-webcomponents/commit/08aabacced4b632aba4cf9b609dea105b37bba59#diff-a7f30f355e413a0bc8fd84fed201f6dae0a0ed04481967f496c5b4cfefbaed72 might be the commit that changed this behavior.

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by PetyaMarkovaBogdanova** [comment]
Hi team @SAP/ui5-webcomponents-topic-core ,
can you, please, take a look at why is the More button showing in scrolling grow type of the Table.
There is a commit that is suggested as an introduction to the regeression.
Best regards,
Petya Markova.
(UI5 Web Components Dispatcher)

**Comment by ilhan007** [comment]
Hello @petya the Table from the main package is owned by the @SAP/ui5-webcomponents-table team.

@SAP/ui5-webcomponents-table  could you take a look, the same can be seen in the samples:  https://sap.github.io/ui5-webcomponents/components/TableGrowing/#growing-with-scrolling

**Comment by DonkeyCo** [comment]
Internal Incident: DINC0308037

We will follow up with you as soon as we can.
