### ISSUE TITLE
Playground and API link in the README not working

### ISSUE THREAD

**Issue by hristop** [SAP/ui5-webcomponents#1005]
In the README file the link is:
[https://sap.github.io/ui5-webcomponents/playground/](https://sap.github.io/ui5-webcomponents/playground**/**) (forward slash at the end) which probably worked before, but it does not now.

The link without slash is working:
(https://sap.github.io/ui5-webcomponents/playground)

**Comment by fifoosid** [comment]
Fixed and deployed.
