### ISSUE TITLE
[ui5-OverflowToolbar]: focus outline is clipped

### ISSUE THREAD

**Issue by MahendraSai024** [SAP/ui5-webcomponents#10057]
### Bug Description

When selected/clicked on the currentLocationText of the Breadcrumbs. The Focus is not on all sides of the UI.

Visible in the Sample: 
https://sdk.openui5.org/entity/sap.m.Table/sample/sap.m.sample.TableBreadcrumb
In Page.view.xml, Ln14, replace it with Breadcrumbs id="breadcrumb" currentLocationText="Document" 
(currentLocationText="Document" is added to the Breadcrumbs)
<img width="1135" alt="image" src="https://github.com/user-attachments/assets/f7121440-8121-45cd-bcd6-7fc14efc81fd"><img width="171" alt="image" src="https://github.com/user-attachments/assets/f3b2fd1d-b17d-4915-885a-272c9e006fa2">

The above image shows that the boundary/focus outline is clipped. 
The issue doesn't occur when Breadcrumbs is used with Toolbar. Instead, it happens when using the OverflowToolbar.

### Affected Component

ui5-breadcrumbs

### Expected Behaviour

The focus outline must be adequately visible on all sides, as shown in the image below.

![image](https://github.com/user-attachments/assets/8e7daf48-eac5-40ac-bd53-ea08ea198698)

![image](https://github.com/user-attachments/assets/3de70e1c-20d8-4a2b-98d7-cf158f595658)

When replacing the OverflowToolbar with the Toolbar, it works as expected. 

### Steps to Reproduce

1. Go to the sample application: https://sdk.openui5.org/entity/sap.m.Table/sample/sap.m.sample.TableBreadcrumb
2. Open the Page.view.xml file and change the Line 14 by < Breadcrumbs id="breadcrumb" currentLocationText="Click Here" />
3. Just added currentLocationText to the <Breadcrumbs> 
4. Click on the "Click Here" located at the header section of the table in the application UI which is running in parallel
5. The Focus is not adequately visible on all sides

### Log Output, Stack Trace or Screenshots

https://github.com/user-attachments/assets/86d84336-32b3-4898-96fe-abe332e4250b

### Priority

Medium

### UI5 Web Components Version

latest

### Browser

Chrome

### Operating System

Mac OS

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by PetyaMarkovaBogdanova** [comment]
Hi @MahendraSai024,
thank you for sharing. This is the Web Components Github repository, and it seems you want to report a problem regarding sap.m.Breadcrumbs inside sap.m.OverflowToolbar UI5 controls, so can I, kindly, ask you to move the issue [here](https://github.com/SAP/openui5/issues).
Thank you!
Best regards,
Petya Markova.
(UI5 Web Components dispatcher)
