### ISSUE TITLE
IDE extension for autocompletion support

### ISSUE THREAD

**Issue by blackjyn** [SAP/ui5-webcomponents#10069]
Im struggle as VSCode can't do autocompletion for any UI5 Webcomponent's item. 
the completion is working nice on the playground, but not in the local development.

Do we have IDE extension for autocompletion support? 
im using vanilla js with vite.

thanks

**Comment by nnaydenow** [comment]
Hi @blackjyn,

We provide this information for custom element, but IDE doesn't understand it automatically and you'll need to do manually step as described in: https://github.com/SAP/ui5-webcomponents/pull/8405

I also noticed that we need to add section for this inside our documentation.

Regards,
Nayden
