### ISSUE TITLE
[Date Picker]: Open DatePicker from different component not working

### ISSUE THREAD

**Issue by sebastian-kraemer** [SAP/ui5-webcomponents#10063]
### Describe the bug

Since openPicker and closePicker are no longer available in v2, opening with a state variable only works once when closing the DatePicker Popover with ESC or by clicking outside the Popover. There is no callback when the Popover is closed if not selecting a value.

### Isolated Example

https://stackblitz.com/edit/github-3vdyel?file=package.json

### Reproduction steps

1. Click Button => DatePicker Popover opened
2. Click outside of Popover or hit ESC => Popover closes
3. Click Button => DatePicker Popover is not opening anymore because open is still true

### Expected Behaviour

Event is triggered when Popover was closed to update local state variable.

### UI5 Web Components for React Version

2.3.0

### UI5 Web Components Version

2.3.0

### Browser

Edge

### Operating System

Windows

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Valkanister** [comment]
Hello @SAP/ui5-webcomponents-topic-b,
Please take a look at this issue regarding opening a DatePicker and the "open" state indication. 

Kind regards, 

GV

SAPUI5 | SAP Development Support
