### ISSUE TITLE
[SF][ui5-input][suggestion]: Missing an event when suggestion item is actually selected (clicked/pressed)

### ISSUE THREAD

**Issue by zhangliangyi** [SAP/ui5-webcomponents#10099]
### Bug Description

I noticed that the `suggestion-item-select` event is removed in version 2.x. But when I am leveraging the input suggestion feature in either `ui5-input` or `ui5-multi-input`, I would like to update my data model when some suggestion item is actually clicked or pressed.

Right now when I navigate the suggestion items via keyboard arrow keys, the `selection-change` would be fired every time and my data model update callback would be called every time as well which is not the expected behavior.
And I cannot find any alternative in current implementation to capture this press action.

### Affected Component

ui5-input, ui5-multi-input

### Expected Behaviour

Please restore the `suggestion-item-select` event or provide an equivalent event when suggestion item is actually pressed or clicked. Or only triggering `selection-change` when item is actually pressed instead of triggering it during arrow key navigation.

### Steps to Reproduce

1.
2.
3.
...

### Priority

Very High

### UI5 Web Components Version

2.3.0

### Browser

Edge

### Organization

SF

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by dimovpetar** [comment]
Hello @zhangliangyi ,

There is an alternative for your case, described in the `UI5 WebComponents 2.0` Migration Guide. Please check if it works for you: https://sap.github.io/ui5-webcomponents/docs/migration-guides/to-version-2/#ui5-input.

Best regards,
Petar

**Comment by zhangliangyi** [comment]
@dimovpetar 
Thanks for pointing it out, I will have a try on this with both `ui5-input` and `ui5-multi-input` with `token`.
