### ISSUE TITLE
[ui5-toolbar]: Overflow always open on last item with spacer

### ISSUE THREAD

**Issue by Nils-Schiwek** [SAP/ui5-webcomponents#10104]
### Bug Description

I noticed, that when I use a spacer in a toolbar, the last button behind a spacer is always pushed into the overflow state (... menu) even though there is enough space.
![{5D87F45D-F149-403F-9CC8-1B9A09DC520E}](https://github.com/user-attachments/assets/d8ee1d47-5b79-4935-99b7-1771b70592f6)

Here is an [example from your documentation](https://sap.github.io/ui5-webcomponents/play/#eyJpbmRleC5odG1sIjp7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuPCFET0NUWVBFIGh0bWw-XG48aHRtbCBsYW5nPVwiZW5cIj5cblxuPGhlYWQ-XG4gICAgXG4gICAgPHN0eWxlPlxuICAgICAgKjpub3QoOmRlZmluZWQpIHtcbiAgICAgICAgZGlzcGxheTogbm9uZTtcbiAgICAgIH1cbiAgICA8L3N0eWxlPlxuXG4gICAgPG1ldGEgY2hhcnNldD1cIlVURi04XCI-XG4gICAgPG1ldGEgbmFtZT1cInZpZXdwb3J0XCIgY29udGVudD1cIndpZHRoPWRldmljZS13aWR0aCwgaW5pdGlhbC1zY2FsZT0xLjBcIj5cbiAgICA8dGl0bGU-U2FtcGxlPC90aXRsZT5cbjwvaGVhZD5cbjxib2R5IHN0eWxlPVwiYmFja2dyb3VuZC1jb2xvcjogdmFyKC0tc2FwQmFja2dyb3VuZENvbG9yKTtoZWlnaHQ6IDI1MHB4O1wiPlxuICAgIDwhLS0gcGxheWdyb3VuZC1mb2xkLWVuZCAtLT5cblxuPHVpNS10b29sYmFyPlxuICAgIDx1aTUtdG9vbGJhci1idXR0b24gaWNvbj1cImFkZFwiIHRleHQ9XCJQbHVzXCIgZGVzaWduPVwiRGVmYXVsdFwiPjwvdWk1LXRvb2xiYXItYnV0dG9uPlxuICAgIDx1aTUtdG9vbGJhci1idXR0b24gaWNvbj1cImVtcGxveWVlXCIgdGV4dD1cIkhpcmVcIj48L3VpNS10b29sYmFyLWJ1dHRvbj5cbiAgICA8dWk1LXRvb2xiYXItc2VwYXJhdG9yPjwvdWk1LXRvb2xiYXItc2VwYXJhdG9yPlxuICAgIDx1aTUtdG9vbGJhci1idXR0b24gaWNvbj1cImFkZFwiIHRleHQ9XCJBZGRcIj48L3VpNS10b29sYmFyLWJ1dHRvbj5cbiAgICA8dWk1LXRvb2xiYXItYnV0dG9uIGljb249XCJkZWNsaW5lXCIgdGV4dD1cIkRlY2xpbmVcIj48L3VpNS10b29sYmFyLWJ1dHRvbj5cbiAgICA8dWk1LXRvb2xiYXItc3BhY2VyPjwvdWk1LXRvb2xiYXItc3BhY2VyPlxuICAgIDx1aTUtdG9vbGJhci1idXR0b24gaWNvbj1cImFkZFwiIHRleHQ9XCJBcHBlbmRcIj48L3VpNS10b29sYmFyLWJ1dHRvbj5cbjwvdWk1LXRvb2xiYXI-XG48IS0tIHBsYXlncm91bmQtZm9sZCAtLT5cbiAgICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCJtYWluLmpzXCI-PC9zY3JpcHQ-XG48L2JvZHk-XG48L2h0bWw-XG48IS0tIHBsYXlncm91bmQtZm9sZC1lbmQgLS0-XG5cbiJ9LCJtYWluLmpzIjp7Im5hbWUiOiJtYWluLmpzIiwiY29udGVudCI6Ii8qIHBsYXlncm91bmQtaGlkZSAqL1xuaW1wb3J0IFwiLi9wbGF5Z3JvdW5kLXN1cHBvcnQuanNcIjtcbi8qIHBsYXlncm91bmQtaGlkZS1lbmQgKi9cbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L1Rvb2xiYXIuanNcIjtcbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L1RpdGxlLmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMvZGlzdC9Ub29sYmFyQnV0dG9uLmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMvZGlzdC9Ub29sYmFyU2VsZWN0LmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMvZGlzdC9Ub29sYmFyU3BhY2VyLmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMvZGlzdC9Ub29sYmFyU2VwYXJhdG9yLmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMvZGlzdC9Ub29sYmFyU2VsZWN0T3B0aW9uLmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMtaWNvbnMvZGlzdC9kZWNsaW5lLmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMtaWNvbnMvZGlzdC9hZGQuanNcIjtcbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy1pY29ucy9kaXN0L2VtcGxveWVlLmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMtaWNvbnMvZGlzdC9kZWNsaW5lLmpzXCI7In19)

Interestingly, if you add another button in this setup, the button will now be rendered and again the last button behind the spacer is pushed into the overflow.

### Affected Component

ui5-toolbar

### Expected Behaviour

All ToolbarButtons should be visible (given there is enough space) when a ToolbarSpacer is added.

### Steps to Reproduce

1. Use a Toolbar with 2 ToolbarButtons
2. Add a Toolbar Spacer between them
3. Notice the last Button is hidden behind the overflow menu.

### Priority

Medium

### UI5 Web Components Version

2.3.0

### Browser

Edge

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by dimovpetar** [comment]
Hello @SAP/ui5-webcomponents-topic-p ,

This issue is reproducible.

Best regards,
Petar
