### ISSUE TITLE
[Input]: V2 Input Component's valueState Display Incorrect Popover When ValueState Set to Empty or Undefined

### ISSUE THREAD

**Issue by mrmabo** [SAP/ui5-webcomponents#10115]
### Bug Description

When the `valueState` property of the `Input` component is set to an empty string or undefined, an incorrect valueState message popover appears.
However, When the `valueState` porperty is set to "None", the incorrect popover won't display.  

### Affected Component

Input

### Expected Behaviour

 If `valueState` is set to undefined or an empty string, it should default to "None" to prevent the incorrect popover from appearing.

### Isolated Example

https://stackblitz.com/edit/github-pzlhay-jzepmf?file=src%2FApp.tsx,package.json

### Steps to Reproduce

1. Use the Input component.
2. Set the valueState property to "" (empty string) or undefined.
3. Observe the valueState message popover that appears.
4. Set the valueState property to "None", and note that the popover does not appear.

### Log Output, Stack Trace or Screenshots

![Screenshot 2024-10-30 at 1 57 10 PM](https://github.com/user-attachments/assets/055251d7-a5ba-4548-9cbc-7a1e2e419e00)

### Priority

Very High

### UI5 Web Components Version

2.3.0

### Browser

Chrome, Edge, Firefox, Safari

### Organization

SF

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by dimovpetar** [comment]
Hello @ui5-webcomponents-topic-rl,

An empty popover opens if the set `value-state` is not part of the ValueState enum. Can be observed [here ](https://sap.github.io/ui5-webcomponents/play/#eyJpbmRleC5odG1sIjp7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuPCFET0NUWVBFIGh0bWw-XG48aHRtbCBsYW5nPVwiZW5cIj5cblxuXG5cblxuPGhlYWQ-XG4gICAgXG4gICAgPHN0eWxlPlxuICAgICAgKjpub3QoOmRlZmluZWQpIHtcbiAgICAgICAgZGlzcGxheTogbm9uZTtcbiAgICAgIH1cbiAgICA8L3N0eWxlPlxuXG4gICAgXG4gICAgPHN0eWxlPlxuICAgICAgKjpub3QoOmRlZmluZWQpIHtcbiAgICAgICAgZGlzcGxheTogbm9uZTtcbiAgICAgIH1cbiAgICA8L3N0eWxlPlxuXG4gICAgXG4gICAgPHN0eWxlPlxuICAgICAgKjpub3QoOmRlZmluZWQpIHtcbiAgICAgICAgZGlzcGxheTogbm9uZTtcbiAgICAgIH1cbiAgICA8L3N0eWxlPlxuXG4gICAgPG1ldGEgY2hhcnNldD1cIlVURi04XCI-XG4gICAgPG1ldGEgbmFtZT1cInZpZXdwb3J0XCIgY29udGVudD1cIndpZHRoPWRldmljZS13aWR0aCwgaW5pdGlhbC1zY2FsZT0xLjBcIj5cbiAgICA8dGl0bGU-U2FtcGxlPC90aXRsZT5cbjwvaGVhZD5cblxuPGJvZHkgc3R5bGU9XCJiYWNrZ3JvdW5kLWNvbG9yOiB2YXIoLS1zYXBCYWNrZ3JvdW5kQ29sb3IpOyBoZWlnaHQ6IDE1MHB4O1wiPlxuICAgIDwhLS0gcGxheWdyb3VuZC1mb2xkLWVuZCAtLT5cblxuICAgIFxuICAgIDx1aTUtaW5wdXQgdmFsdWUtc3RhdGU9XCJcIj48L3VpNS1pbnB1dD5cbiAgICA8dWk1LWlucHV0IGlkPVwid2l0aFVuZGVmaW5lZFZhbHVlU3RhdGVcIj48L3VpNS1pbnB1dD5cbiAgICA8dWk1LWlucHV0IHZhbHVlLXN0YXRlPVwiaW52YWxpZFwiPjwvdWk1LWlucHV0PlxuICBcbiAgICA8dWk1LWlucHV0IHZhbHVlLXN0YXRlPVwiTmVnYXRpdmVcIj48L3VpNS1pbnB1dD5cbiAgICA8dWk1LWlucHV0IHZhbHVlLXN0YXRlPVwiQ3JpdGljYWxcIj48L3VpNS1pbnB1dD5cbiAgICA8dWk1LWlucHV0IHZhbHVlLXN0YXRlPVwiUG9zaXRpdmVcIj48L3VpNS1pbnB1dD5cbiAgICA8dWk1LWlucHV0IHZhbHVlLXN0YXRlPVwiSW5mb3JtYXRpb25cIj48L3VpNS1pbnB1dD5cbiAgICA8dWk1LWlucHV0IHZhbHVlLXN0YXRlPVwiTm9uZVwiPjwvdWk1LWlucHV0PlxuICBcbiAgICA8c2NyaXB0PlxuICAgICAgZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoXCJ3aXRoVW5kZWZpbmVkVmFsdWVTdGF0ZVwiKS52YWx1ZVN0YXRlID0gdW5kZWZpbmVkO1xuICAgIDwvc2NyaXB0PlxuICAgIDwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuICAgIDxzY3JpcHQgdHlwZT1cIm1vZHVsZVwiIHNyYz1cIm1haW4uanNcIj48L3NjcmlwdD5cbjwvYm9keT5cblxuPC9odG1sPlxuPCEtLSBwbGF5Z3JvdW5kLWZvbGQtZW5kIC0tPlxuIn0sIm1haW4uanMiOnsibmFtZSI6Im1haW4uanMiLCJjb250ZW50IjoiLyogcGxheWdyb3VuZC1oaWRlICovXG5pbXBvcnQgXCIuL3BsYXlncm91bmQtc3VwcG9ydC5qc1wiO1xuLyogcGxheWdyb3VuZC1oaWRlLWVuZCAqL1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzL2Rpc3QvSW5wdXQuanNcIjtcbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L1N1Z2dlc3Rpb25JdGVtLmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMvZGlzdC9mZWF0dXJlcy9JbnB1dFN1Z2dlc3Rpb25zLmpzXCI7In19).
This includes empty string and undefined values. To my understanding, in this case the input should behave as if the `value-state` is set to `None`.

Best regards,
Petar

**Comment by pskelin** [comment]
This is how enums in UI5 components are designed to work - they do not work with undefined or values outside of the Enum (unless undefined is specified in the docs).

For the input, the docs clearly state what the accepted values for `valueState` are:
<img width="729" alt="Screenshot 2024-10-31 at 10 59 04" src="https://github.com/user-attachments/assets/62bbd16f-34c1-4646-ae5b-eae46fa07656">

empty string and undefined are not part of the supported values. Note that if you use the component without providing a valueState, there is a default which is "None". This is not the same as removing the valueState. If you don't want unspecified behaviour, you should set the value state to "None".

This is also modelled in typescript, if I get a reference to an input, I cannot assign `""` or `undefined` and get the corresponding error.
<img width="816" alt="Screenshot 2024-10-31 at 11 01 36" src="https://github.com/user-attachments/assets/eedb59e4-9a0e-45f4-b5c7-8878930c0c5c">

In the end, the only accepted values are the ones in the docs. If you don't want a popover to appear, just set the `valueState` to `"None"` instead ot `""` or `undefined`
