### ISSUE TITLE
[ui5-segmented-button] Pressed and Disabled items do not appear on fiori_3 / 1.24

### ISSUE THREAD

**Issue by vladitasev** [SAP/ui5-webcomponents#10112]
### Bug Description

set "pressed" and "disabled" on the same item, change theme to fiori_3_* 

### Affected Component

ui5-segmented-button

### Steps to Reproduce

1.
2.
3.
...

### Priority

High

### UI5 Web Components Version

1.24

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by hinzzx** [comment]
Hello,

The issue is fixed with this [PR](https://github.com/SAP/ui5-webcomponents/commit/4c1014c33e83b207da53ec53f86c515476ffcb85), therefore we're closing the issue.

Best Regards,
Stoyan
