### ISSUE TITLE
[Feature Request]: error handling when a component is used but not defined in the bundle.esm.js

### ISSUE THREAD

**Issue by koeppel** [SAP/ui5-webcomponents#10119]
### Feature Request Description

We're working on our own webcomponents library and I've noticed that there is no error logging etc. when I'm trying to use a new component that is not imported in the bundle.esm.js.

### Proposed Solution

Log an error in the console that the used component is not defined?

### Priority

Low

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by dimovpetar** [comment]
Hello @koeppel ,

Do you mean that there is no error if you use custom element that is not included in the library's bundle.esm,js, **in an html page**?

Best regards,
Petar
