### ISSUE TITLE
[ColorPicker]: Cannot set the color picker width

### ISSUE THREAD

**Issue by annakjc** [SAP/ui5-webcomponents#10117]
### Bug Description

Hello,
I'm trying to set a width of 12 rem to the Color Picker however there are not shadow parts exposed and I cannot overwrite the hardcoded .ui5-color-picker-main-color {
    width: 16rem;
    height: 16rem;
}
Are there any suggestions or workarounds that i can perform?

### Affected Component

Color Picker

### Expected Behaviour

expected to be able to change the width of the color picker.

### UI5 Web Components Version

2.3.0

### Browser

Chrome

- [X] I’m not disclosing any internal or sensitive information.

**Comment by dimovpetar** [comment]
Hello @annakjc ,

The ColorPicker dimensions are defined this big by the visual designers. What is the use of having smaller ColorPicker? This will also affect the other parts of the ColorPicker, such as the sliders, the current color and the RGB, which are not prepared for smaller width.

Best regards,
Petar
