### ISSUE TITLE
Warning: "The provided item is not managed by ItemNavigation" when hovering over nested ui5-menu-items

### ISSUE THREAD

**Issue by fanaaa** [SAP/ui5-webcomponents#10120]
### Bug Description

When hovering over `ui5-menu-item` that contain nested `ui5-menu-item` (to create a submenu structure), a warning appears in the console: "The provided item is not managed by ItemNavigation". 

This warning is also visible on the official UI5 Web Components documentation page for `ui5-menu` under the "Submenu" example (https://sap.github.io/ui5-webcomponents/components/Menu/).

### Affected Component

ui5-menu, ui5-menu-item

### Expected Behaviour

No warning message should appear in the console when hovering over `ui5-menu-item` components with nested submenus. The submenu functionality should work without any warnings, as this is a documented and supported feature.

### Isolated Example

The issue can be observed directly on the UI5 Web Components menu documentation page under the "Submenu" example: https://sap.github.io/ui5-webcomponents/components/Menu/

### Steps to Reproduce

1. Go to the UI5 Web Components documentation page for the Menu component (https://sap.github.io/ui5-webcomponents/components/Menu/).
2. Scroll to the "Submenu" example.
3. Hover over the menu items "Open" or "Save" (the items with nested submenus).
4. Open the browser console and observe the warning message: "The provided item is not managed by ItemNavigation".

### Log Output, Stack Trace or Screenshots

<img width="1509" alt="Bildschirmfoto 2024-10-31 um 11 49 32" src="https://github.com/user-attachments/assets/12c42675-8ccc-4817-9324-4c4e24ad8db3">

### Priority

None

### UI5 Web Components Version

2.3

### Browser

Chrome

### Operating System

macOs

### Additional Context

The issue can be observed directly on the official documentation page, so no isolated example is provided.

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by dimovpetar** [comment]
Hello @SAP/ui5-webcomponents-topic-b ,

Looks like `"_request-tabindex-change"` event incorrectly bubbles to the ItemNavigation of the list of the root MenuItem, thus producing this warning.

Best regards,
Petar
