### ISSUE TITLE
[patchPopup] [UI5WC 1.24.x / UI5WC4R 1.29.x Upgrade] console error on U.prototype.onFocusEvent,

### ISSUE THREAD

**Issue by warmwind3** [SAP/ui5-webcomponents#10129]
### Bug Description

Issue is found during testing in SAC with updated version of ui5 and ui5wc.
More details can be found at: https://jira.tools.sap/browse/FPA18-16463
Similar issue reported by FPA30: https://jira.tools.sap/browse/FPA30-16921
Version update change cherry picked: https://git.wdf.sap.corp/c/orca_cloud/+/6305517
1. Use model ACT_ANA_income
2. In ode story, try to add a story filter
3. From dimension list, select Location_2, open filter by member, filter by condition fly out menu
4. Now attempt to click on Country_Code2, saw console error library-preload.js:688 Uncaught TypeError: Cannot read properties of undefined (reading 'id')
5. 
![image](https://github.com/user-attachments/assets/79e90e00-b85a-4212-a4b6-803fdece8e46)
_

### Steps to Reproduce

1.
2.
3.
...

### Priority

None

### UI5 Web Components Version

1.24

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by TeodorTaushanov** [comment]
Fixed with #10128
