### ISSUE TITLE
[CardHeader]: CardHeader Outlines When Clicked Even If Not Interactive

### ISSUE THREAD

**Issue by zinia94** [SAP/ui5-webcomponents#10132]
### Bug Description

We have a bug ticket: [INSIGHTS-9844](https://jira.tools.sap/browse/INSIGHTS-9844). When the CardHeader is clicked, it receives a border outline even when the interactive property is set to false.

![image](https://github.com/user-attachments/assets/c38cd2e3-9a5e-4687-ab0a-532c96ad3d7f)

### Affected Component

CardHeader

### Expected Behaviour

When the CardHeader is not clickable (i.e., not interactive), the expected behavior is that clicking it will not result in a border outline. According to the documentation:

<img width="888" alt="image" src="https://github.com/user-attachments/assets/43bab086-1628-488f-a360-428ea8b8000d">

### Steps to Reproduce

Click on the CardHeader of a card that is not clickable (i.e., not interactive).

### Priority

Medium

### UI5 Web Components Version

v2.3.3

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Todor-ads** [comment]
Hello @SAP/ui5-webcomponents-topic-rd 
Could you look into this issue? This issue has been discussed with Petar D.

Regards,
Todor

**Comment by dimovpetar** [comment]
Hello @zinia94 ,

It is intended that the card header gets focus outline regardless of its `interactive` property. You can find explanation here https://github.com/SAP/ui5-webcomponents/issues/2486#issuecomment-734863350. 
I will update the description of this property.

Best regards,
Petar
