### ISSUE TITLE
[theming]: "setTheme" cannot be used during "boot phase"

### ISSUE THREAD

**Issue by MFel0123** [SAP/ui5-webcomponents#10147]
### Bug Description

Our UI5 Webcomponents App is embedded in an iFrame. It should take over the theming from the embedding application. Therefore we handover this surrounding theme as a parameter to our app. Then during the start in the root component of our app we use the general "setTheme" to apply the theme that we get from the embedding application via an own parameter. This worked in the past (at least for a while). But now - probably with this correction: 
![image](https://github.com/user-attachments/assets/6be343a9-da03-49f7-9da9-5fa554a10559)
it does not work anymore. Here the parameter "booted" returns `true `in our case (via "`isBooted`() - see PR). And then the new current theme seems to be changed but not applied. Isn't this a bug? (The theme does not change afterwards when we try it in the beginning).

If we try the same after the UI elements are is already displayed - then it works. But this is too late for us since we want to set the theme in the beginning.

### Expected Behaviour

If this is a bug - please correct it  - if not, please could you offer an alternative for us. How to set the theme in the starting phase of our app.

### Steps to Reproduce

1.
2.
3.
...

### Priority

None

### UI5 Web Components Version

>= 1.19.0 (also 1.21.0) - Correction mentioned (see above)

### Browser

Chrome, Edge, Firefox, Safari

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ilhan007** [comment]
Hello @MFel0123 

Did you try the [following](https://sap.github.io/ui5-webcomponents/docs/advanced/other-framework-level-APIs/#executing-code-on-boot):

## Executing Code on Boot

```js
import { attachBoot } from "@ui5/webcomponents-base/dist/Boot.js";
```

The `attachBoot` function allows you to execute custom code when the framework has finished booting.

Example:

```js
attachBoot(() => {
	console.log("Framework booted");
});
```

**Comment by MFel0123** [comment]
Hi @ilhan007,
yes, thank you,I think that should work for us.
