### ISSUE TITLE
[MultiComboBox / NotificationListItem]: Unnecessary Event Bubbling for onOpen / onClose 

### ISSUE THREAD

**Issue by wvudako** [SAP/ui5-webcomponents#10146]
### Bug Description

MultiComboBox onOpen
NotificationListItem onClose
both bubble and should not because e.g. when using them in a Dialog these events might (or likely will) do things for the dialog and therefore have to be stopped from propagating

The same issue was fixed for MultiComboBox onClose in
https://github.com/SAP/ui5-webcomponents/issues/10006

The reproducer and all the information from that information can be adapted for these use cases quite easily

Workaround is to stop the event from propagating

### Affected Component

MultiComboBox / NotificationListItem

### Expected Behaviour

These event should not bubble

### Priority

Medium

### UI5 Web Components Version

2.x

### Browser

Chrome

### Operating System

Windows 11

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Todor-ads** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,
Could you please look into the mentioned issue with onOpen (MultiComboBox)?

Regards,
Todor
