### ISSUE TITLE
[SF][RatingIndicator]: [Rating Star should be able to be set size and some other issues]

### ISSUE THREAD

**Issue by tandan0813** [SAP/ui5-webcomponents#10155]
### Describe the bug

1. RatingIndicator component can't set size, while UI5 version can set;
![image](https://github.com/user-attachments/assets/4b3d6cf1-4d28-4903-8898-404d353110fd)

2. In a display-only form, the half rating will show a hollow star style, while the Fiori doc shows a solid one and it seems more consistant.
React: 
![image](https://github.com/user-attachments/assets/25f804d5-6c5e-4099-9c12-581a73520236)
Doc:
![image](https://github.com/user-attachments/assets/7f8b8a20-bce7-4ea1-8f59-0f775c091034)

3. 

### Reproduction steps

1.
2.
3.
...

### UI5 Web Components for React Version

2.4.0

### UI5 Web Components Version

2.4.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Todor-ads** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,
The mentioned issue with the half-empty star is reproducible in the [playground](https://sap.github.io/ui5-webcomponents/play/#eyJpbmRleC5odG1sIjp7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhLS0gcGxheWdyb3VuZC1oaWRlIC0tPlxuPCFET0NUWVBFIGh0bWw-XG48aHRtbCBsYW5nPVwiZW5cIj5cblxuXG5cbjxoZWFkPlxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG5cbiAgICBodG1sIHtcbiAgICAgIGZvcmNlZC1jb2xvci1hZGp1c3Q6IG5vbmU7XG4gICAgfVxuICAgIDwvc3R5bGU-XG5cbiAgICBcbiAgICA8c3R5bGU-XG4gICAgICAqOm5vdCg6ZGVmaW5lZCkge1xuICAgICAgICBkaXNwbGF5OiBub25lO1xuICAgICAgfVxuXG4gICAgaHRtbCB7XG4gICAgICBmb3JjZWQtY29sb3ItYWRqdXN0OiBub25lO1xuICAgIH1cbiAgICA8L3N0eWxlPlxuXG4gICAgPG1ldGEgY2hhcnNldD1cIlVURi04XCI-XG4gICAgPG1ldGEgbmFtZT1cInZpZXdwb3J0XCIgY29udGVudD1cIndpZHRoPWRldmljZS13aWR0aCwgaW5pdGlhbC1zY2FsZT0xLjBcIj5cbiAgICA8dGl0bGU-U2FtcGxlPC90aXRsZT5cbjwvaGVhZD5cblxuPGJvZHkgc3R5bGU9XCJiYWNrZ3JvdW5kLWNvbG9yOiB2YXIoLS1zYXBCYWNrZ3JvdW5kQ29sb3IpXCI-XG4gICAgPCEtLSBwbGF5Z3JvdW5kLWhpZGUtZW5kIC0tPlxuICAgIDx1aTUtcmF0aW5nLWluZGljYXRvciB2YWx1ZT1cIjQuNVwiIG1heD1cIjdcIiBzdHlsZT1cImZvbnQtc2l6ZTogM3JlbTtcIj48L3VpNS1yYXRpbmctaW5kaWNhdG9yPjwvYnI-XG4gICAgPHVpNS1yYXRpbmctaW5kaWNhdG9yIHZhbHVlPVwiNC41XCIgbWF4PVwiN1wiIHJlYWRvbmx5IHN0eWxlPVwiZm9udC1zaXplOiAycmVtO1wiPjwvdWk1LXJhdGluZy1pbmRpY2F0b3I-PC9icj5cbiAgICA8dWk1LXJhdGluZy1pbmRpY2F0b3IgdmFsdWU9XCI0LjVcIiBtYXg9XCI3XCIgZGlzYWJsZWQgc3R5bGU9XCJmb250LXNpemU6IDFyZW07XCI-PC91aTUtcmF0aW5nLWluZGljYXRvcj5cbiAgICA8IS0tIHBsYXlncm91bmQtaGlkZSAtLT5cbiAgICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCJtYWluLmpzXCI-PC9zY3JpcHQ-XG48L2JvZHk-XG5cbjwvaHRtbD5cbjwhLS0gcGxheWdyb3VuZC1oaWRlLWVuZCAtLT4ifSwibWFpbi5qcyI6eyJuYW1lIjoibWFpbi5qcyIsImNvbnRlbnQiOiIvKiBwbGF5Z3JvdW5kLWhpZGUgKi9cbmltcG9ydCBcIi4vcGxheWdyb3VuZC1zdXBwb3J0LmpzXCI7XG4vKiBwbGF5Z3JvdW5kLWhpZGUtZW5kICovXG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMvZGlzdC9SYXRpbmdJbmRpY2F0b3IuanNcIjsifX0) . Could you please take a look?
Regards,
Todor

**Comment by elenastoyanovaa** [comment]
Hello @tandan0813 ,

The first issue will be considered as a feature request. The second issue is fixed with the fix linked to this PR.

@hristop as discussed internally we need to provide a `part` for the icons in order for the apps to change the size of the icons.

Kind Regards,
Elena
