### ISSUE TITLE
[DynamicPageTitle]: `subheading` now only spreads to half of the `titleArea` width

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#10161]
### Bug Description

Before v2.3.0 the `subheading` spread to the full width of the `DynamicPageTitle`, now it only takes up half the width:

v2.2.0:
<img width="977" alt="image" src="https://github.com/user-attachments/assets/ed327fda-4313-4663-a4e3-79ea3f59a5b3">
https://stackblitz.com/edit/ui5wc-dynamic-page-rcr7gc?file=index.html,main.js,package.json

v2.4.0:
<img width="899" alt="image" src="https://github.com/user-attachments/assets/c0cf1402-6998-4ea8-afe9-f37e56807cd5">

### Affected Component

DynamicPageTitle

### Expected Behaviour

The `subheading` slot should use the full width of the `DynamicPageTitle`.

### Isolated Example

https://stackblitz.com/edit/ui5wc-dynamic-page-rcr7gc?file=index.html,main.js,package.json (v2.2.0), https://stackblitz.com/edit/ui5wc-dynamic-page-mfcnxc?file=index.html,main.js,package.json (v2.4.0)

### Steps to Reproduce

1. Go to StackBlitz [example v2.2.0](https://stackblitz.com/edit/ui5wc-dynamic-page-rcr7gc?file=index.html,main.js,package.json) and [example v2.4.0](https://stackblitz.com/edit/ui5wc-dynamic-page-mfcnxc?file=index.html,main.js,package.json)
2. See differences

### Priority

None

### UI5 Web Components Version

2.4.0

### Browser

Chrome

### Additional Context

Related public Slack message: https://openui5.slack.com/archives/CSQEJ2J04/p1730895222517669

### Organization

UI5WCR

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Todor-ads** [comment]
Hello @SAP/ui5-webcomponents-topic-p ,
 Could you please review this behavior?

Regards,
Todor

**Comment by NakataCode** [comment]
Hello colleagues,

Thank you for raising this issue. The subheading is now set to utilize 100% of the width. However, as per the UX design, this area is intended primarily for short, supportive text related to the title, not for elements that require full-width expansion.

Please feel free to reach out if you have any further questions or need additional clarification.

Best regards,
Nikola
