### ISSUE TITLE
[ui5-badge & ui5-tag]: Incorrect / missing hover background color

### ISSUE THREAD

**Issue by HerzogIgzorn** [SAP/ui5-webcomponents#10164]
### Bug Description

The background-color for the following WebComponents is incorrect when using color-scheme="9" and design="Set2":
- ui5-tag
- ui5-badge

```
<ui5-tag design="Set2" color-scheme="9" interactive="true">
    Color Scheme 9
</ui5-tag>
```

The issue is due to missing CSS in [Tag-parameters.css](https://github.com/SAP/ui5-webcomponents/blame/73f82abe5e9a61d88919f4c45df9435be850eb2f/packages/main/src/themes/base/Tag-parameters.css#L101). According to the [Tag Design Spec](https://www.figma.com/design/SILcWzK5uFghKun9jx6D7c/SAP-Web-UI-Kit?m=auto&node-id=159886-3732&t=vrhreASVgHgQH3HY-1), the correct color would be #F2F2F2.  As you can see in the Tag-parameters.css of the base theme, the following definitions are missing but similar definitions exist for all other color-schemes (except 9):

```
--ui5-tag-set2-color-scheme-9-hover-background: var(--sapIndicationColor_9b_Hover_Background);

--ui5-tag-set2-color-scheme-9-active-color: var(--sapIndicationColor_9_Active_TextColor);
--ui5-tag-set2-color-scheme-9-active-background: var(--sapIndicationColor_9_Active_Background);
--ui5-tag-set2-color-scheme-9-active-border: var(--sapIndicationColor_9_Active_BorderColor);
```
![f5acdada-88ff-40c6-bf01-db9b1b905d97](https://github.com/user-attachments/assets/7b0c796f-e2cd-4a6f-b69b-a8c4c2fb20ce)

### Affected Component

ui5-tag

### Expected Behaviour

The missing CSS needs to be added for color-scheme="9" and design="Set2". This has to be done for the ui5-tag component in version 2.x as well as for the ui5-badge component in version 1.x

### Isolated Example

[WebComponent Playground](https://sap.github.io/ui5-webcomponents/play/#eyJpbmRleC5odG1sIjp7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuPCFET0NUWVBFIGh0bWw-XG48aHRtbCBsYW5nPVwiZW5cIj5cblxuXG5cbjxoZWFkPlxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG5cbiAgICBodG1sIHtcbiAgICAgIGZvcmNlZC1jb2xvci1hZGp1c3Q6IG5vbmU7XG4gICAgfVxuICAgIDwvc3R5bGU-XG5cbiAgICBcbiAgICA8c3R5bGU-XG4gICAgICAqOm5vdCg6ZGVmaW5lZCkge1xuICAgICAgICBkaXNwbGF5OiBub25lO1xuICAgICAgfVxuXG4gICAgaHRtbCB7XG4gICAgICBmb3JjZWQtY29sb3ItYWRqdXN0OiBub25lO1xuICAgIH1cbiAgICA8L3N0eWxlPlxuXG4gICAgPG1ldGEgY2hhcnNldD1cIlVURi04XCI-XG4gICAgPG1ldGEgbmFtZT1cInZpZXdwb3J0XCIgY29udGVudD1cIndpZHRoPWRldmljZS13aWR0aCwgaW5pdGlhbC1zY2FsZT0xLjBcIj5cbiAgICA8dGl0bGU-U2FtcGxlPC90aXRsZT5cbjwvaGVhZD5cblxuPGJvZHkgc3R5bGU9XCJiYWNrZ3JvdW5kLWNvbG9yOiB2YXIoLS1zYXBCYWNrZ3JvdW5kQ29sb3IpXCI-XG4gICAgPCEtLSBwbGF5Z3JvdW5kLWZvbGQtZW5kIC0tPlxuXG4gICAgPGRpdiBzdHlsZT1cImRpc3BsYXk6IGZsZXg7IGZsZXgtZGlyZWN0aW9uOiBjb2x1bW47IGFsaWduLWl0ZW1zOiBzdGFydDsgZ2FwOiAxcmVtXCI-XG4gICAgICAgIDx1aTUtdGFnIGRlc2lnbj1cIlNldDJcIiBjb2xvci1zY2hlbWU9XCIxXCI-XG4gICAgICAgICAgICBDb2xvciBTY2hlbWUgMVxuICAgICAgICA8L3VpNS10YWc-XG4gICAgICAgIDx1aTUtdGFnIGRlc2lnbj1cIlNldDJcIiBjb2xvci1zY2hlbWU9XCIyXCI-XG4gICAgICAgICAgICBDb2xvciBTY2hlbWUgMlxuICAgICAgICA8L3VpNS10YWc-XG4gICAgICAgIDx1aTUtdGFnIGRlc2lnbj1cIlNldDJcIiBjb2xvci1zY2hlbWU9XCIzXCI-XG4gICAgICAgICAgICBDb2xvciBTY2hlbWUgM1xuICAgICAgICA8L3VpNS10YWc-XG4gICAgICAgIDx1aTUtdGFnIGRlc2lnbj1cIlNldDJcIiBjb2xvci1zY2hlbWU9XCI0XCI-XG4gICAgICAgICAgICBDb2xvciBTY2hlbWUgNFxuICAgICAgICA8L3VpNS10YWc-XG4gICAgICAgIDx1aTUtdGFnIGRlc2lnbj1cIlNldDJcIiBjb2xvci1zY2hlbWU9XCI1XCI-XG4gICAgICAgICAgICBDb2xvciBTY2hlbWUgNVxuICAgICAgICA8L3VpNS10YWc-XG4gICAgICAgIDx1aTUtdGFnIGRlc2lnbj1cIlNldDJcIiBjb2xvci1zY2hlbWU9XCI2XCI-XG4gICAgICAgICAgICBDb2xvciBTY2hlbWUgNlxuICAgICAgICA8L3VpNS10YWc-XG4gICAgICAgIDx1aTUtdGFnIGRlc2lnbj1cIlNldDJcIiBjb2xvci1zY2hlbWU9XCI3XCI-XG4gICAgICAgICAgICBDb2xvciBTY2hlbWUgN1xuICAgICAgICA8L3VpNS10YWc-XG4gICAgICAgIDx1aTUtdGFnIGRlc2lnbj1cIlNldDJcIiBjb2xvci1zY2hlbWU9XCI4XCI-XG4gICAgICAgICAgICBDb2xvciBTY2hlbWUgOFxuICAgICAgICA8L3VpNS10YWc-XG4gICAgICAgIDx1aTUtdGFnIGRlc2lnbj1cIlNldDJcIiBjb2xvci1zY2hlbWU9XCI5XCIgaW50ZXJhY3RpdmU9XCJ0cnVlXCI-XG4gICAgICAgICAgICBDb2xvciBTY2hlbWUgOVxuICAgICAgICA8L3VpNS10YWc-XG4gICAgICAgIDx1aTUtdGFnIGRlc2lnbj1cIlNldDJcIiBjb2xvci1zY2hlbWU9XCIxMFwiPlxuICAgICAgICAgICAgQ29sb3IgU2NoZW1lIDEwXG4gICAgICAgIDwvdWk1LXRhZz5cbiAgICA8L2Rpdj5cbiAgICA8IS0tIHBsYXlncm91bmQtZm9sZCAtLT5cbiAgICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCJtYWluLmpzXCI-PC9zY3JpcHQ-XG48L2JvZHk-XG5cbjwvaHRtbD5cbjwhLS0gcGxheWdyb3VuZC1mb2xkLWVuZCAtLT5cbiJ9LCJtYWluLmpzIjp7Im5hbWUiOiJtYWluLmpzIiwiY29udGVudCI6Ii8qIHBsYXlncm91bmQtaGlkZSAqL1xuaW1wb3J0IFwiLi9wbGF5Z3JvdW5kLXN1cHBvcnQuanNcIjtcbi8qIHBsYXlncm91bmQtaGlkZS1lbmQgKi9cbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L1RhZy5qc1wiO1xuIn19)

### Steps to Reproduce

1. Open the sample
2. Hover over the tag "Color Scheme 9"

### Priority

Medium

### UI5 Web Components Version

1.x & 2.x & nightly

### Browser

Chrome, Edge, Firefox, Safari

### Operating System

Windows 11, MacOS, iOS, Android

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by dobrinyonkov** [comment]
Hello @SAP/ui5-webcomponents-topic-rd,

the hover and active (down) states of the tag in design "Set2" seems to not be according to the visual specification, could you please take over?

Kind Regards,
Dobrin
