### ISSUE TITLE
[SF_ACC][DynamicPage]: Aria role of header is not appropriate

### ISSUE THREAD

**Issue by i323808** [SAP/ui5-webcomponents#10175]
### Bug Description

Aria role of DynamicPage header is not appropriate.
<img width="1735" alt="dynamicPage_header_a11y" src="https://github.com/user-attachments/assets/c1b24338-02bf-4272-a5c4-b0eab248ae59">

### Steps to Reproduce

1. navigate to https://sap.github.io/ui5-webcomponents/components/fiori/DynamicPage/ 
2. scan page using axe DevTools

### Priority

None

### UI5 Web Components Version

2.4.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by dobrinyonkov** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

the axe tool indeed reports an error with the role. Please check with the acc specification and acc experts on the correct role for this expandable area.

Kind Regards,
Dobrin
