### ISSUE TITLE
[SF_ACC][Breadcrumbs]: ARIA dialog and alertdialog nodes should have an accessible name

### ISSUE THREAD

**Issue by i323808** [SAP/ui5-webcomponents#10176]
### Bug Description

Popover of breadcrumbs should have an accessible name.
<img width="1726" alt="breadcrumbs_a11y" src="https://github.com/user-attachments/assets/333cbd16-7b45-4d72-8ea5-c28c19a4d3b1">

### Steps to Reproduce

1. navigate to https://sap.github.io/ui5-webcomponents/components/Breadcrumbs/#overflow
2. open popover
3. scan page using axe DevTools

### Priority

None

### UI5 Web Components Version

2.4.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by dobrinyonkov** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

the axe tool reports an error for the dropdown menu of the breadcrumbs.
If I remember correctly the specification here would be a re-use of the select accessibility spectification. Please check the spec of the two controls whether an accessible label is needed.

Kind Regards,
Dobrin
