### ISSUE TITLE
[ui5-tree]: item-click event won't be fired when check/uncheck the item checkbox under multiple selection mode 

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents#10184]
### Bug Description

item-click event won't be fired when check/uncheck the item checkbox under multiple selection mode

### Affected Component

ui5-tree

### Expected Behaviour

item-click event should be fired when check/uncheck the item checkbox under multiple selection mode

### Steps to Reproduce

1. open https://stackblitz.com/edit/github-hlyj8c?file=src%2FApp.tsx
2. check/uncheck the checkbox in the tree item, check the console log
3. you can't find the log "tree item was clicked!"

### Priority

High

### UI5 Web Components Version

2.4.0

### Browser

Chrome, Edge

### Additional Context

SF has upcoming release window within two weeks, please fix this issue as high priority.

### Organization

SAP SuccessFactors

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by dobrinyonkov** [comment]
The tree component is using `ui5-list` so, this issue will be checked with #10183. Closing as duplicate.
