### ISSUE TITLE
[ui5-table]: busy indicator is not placed correctly

### ISSUE THREAD

**Issue by nnaydenow** [SAP/ui5-webcomponents#10189]
### Bug Description

Busy indicator is not placed over whole content

![image](https://github.com/user-attachments/assets/94bf75d9-ab19-45b3-be9e-b88eb3266cd5)

### Steps to Reproduce

1. Open this[ example
](https://sap.github.io/ui5-webcomponents/play/#eyJpbmRleC5odG1sIjp7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuPCFET0NUWVBFIGh0bWw-XG48aHRtbCBsYW5nPVwiZW5cIj5cblxuXG5cbjxoZWFkPlxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG5cbiAgICBodG1sIHtcbiAgICAgIGZvcmNlZC1jb2xvci1hZGp1c3Q6IG5vbmU7XG4gICAgfVxuICAgIDwvc3R5bGU-XG5cbiAgICBcbiAgICA8c3R5bGU-XG4gICAgICAqOm5vdCg6ZGVmaW5lZCkge1xuICAgICAgICBkaXNwbGF5OiBub25lO1xuICAgICAgfVxuXG4gICAgaHRtbCB7XG4gICAgICBmb3JjZWQtY29sb3ItYWRqdXN0OiBub25lO1xuICAgIH1cbiAgICA8L3N0eWxlPlxuXG4gICAgPG1ldGEgY2hhcnNldD1cIlVURi04XCI-XG4gICAgPG1ldGEgbmFtZT1cInZpZXdwb3J0XCIgY29udGVudD1cIndpZHRoPWRldmljZS13aWR0aCwgaW5pdGlhbC1zY2FsZT0xLjBcIj5cbiAgICA8dGl0bGU-U2FtcGxlPC90aXRsZT5cbjwvaGVhZD5cblxuPGJvZHkgc3R5bGU9XCJiYWNrZ3JvdW5kLWNvbG9yOiB2YXIoLS1zYXBCYWNrZ3JvdW5kQ29sb3IpXCI-XG4gICAgPGRpdiBjbGFzcz1cInNlY3Rpb25cIj5cbjwhLS0gcGxheWdyb3VuZC1mb2xkLWVuZCAtLT5cblx0XHQ8dWk1LXRhYmxlIGlkPVwidGFibGVcIiBvdmVyZmxvdy1tb2RlPVwiU2Nyb2xsXCIgbG9hZGluZz5cblx0XHRcdDx1aTUtdGFibGUtaGVhZGVyLXJvdyBzbG90PVwiaGVhZGVyUm93XCI-XG5cdFx0XHRcdDx1aTUtdGFibGUtaGVhZGVyLWNlbGwgaWQ9XCJwcm9kdXRDb2xcIiB3aWR0aD1cIjMwMHB4XCI-PHNwYW4-UHJvZHVjdDwvc3Bhbj48L3VpNS10YWJsZS1oZWFkZXItY2VsbD5cblx0XHRcdFx0PHVpNS10YWJsZS1oZWFkZXItY2VsbCBpZD1cInN1cHBsaWVyQ29sXCIgd2lkdGg9XCIyMDBweFwiPlN1cHBsaWVyPC91aTUtdGFibGUtaGVhZGVyLWNlbGw-XG5cdFx0XHRcdDx1aTUtdGFibGUtaGVhZGVyLWNlbGwgaWQ9XCJkaW1lbnNpb25zQ29sXCIgbWluLXdpZHRoPVwiMzAwcHhcIj5EaW1lbnNpb25zPC91aTUtdGFibGUtaGVhZGVyLWNlbGw-XG5cdFx0XHRcdDx1aTUtdGFibGUtaGVhZGVyLWNlbGwgaWQ9XCJ3ZWlnaHRDb2xcIiB3aWR0aD1cIjEwMHB4XCI-V2VpZ2h0PC91aTUtdGFibGUtaGVhZGVyLWNlbGw-XG5cdFx0XHRcdDx1aTUtdGFibGUtaGVhZGVyLWNlbGwgaWQ9XCJwcmljZUNvbFwiIG1pbi13aWR0aD1cIjIyMHB4XCI-UHJpY2U8L3VpNS10YWJsZS1oZWFkZXItY2VsbD5cblx0XHRcdDwvdWk1LXRhYmxlLWhlYWRlci1yb3c-XG48IS0tIHBsYXlncm91bmQtZm9sZCAtLT5cblx0XHRcdDx1aTUtdGFibGUtcm93PlxuXHRcdFx0XHQ8dWk1LXRhYmxlLWNlbGw-PHVpNS1sYWJlbD48Yj5Ob3RlYm9vayBCYXNpYyAxNTwvYj48YnI-SFQtMTAwMDwvdWk1LWxhYmVsPjwvdWk1LXRhYmxlLWNlbGw-XG5cdFx0XHRcdDx1aTUtdGFibGUtY2VsbD48dWk1LWxhYmVsPlZlcnkgQmVzdCBTY3JlZW5zPC91aTUtbGFiZWw-PC91aTUtdGFibGUtY2VsbD5cblx0XHRcdFx0PHVpNS10YWJsZS1jZWxsPjx1aTUtbGFiZWw-MzAgeCAxOCB4IDMgY208L3VpNS1sYWJlbD48L3VpNS10YWJsZS1jZWxsPlxuXHRcdFx0XHQ8dWk1LXRhYmxlLWNlbGw-PHVpNS1sYWJlbCBzdHlsZT1cImNvbG9yOiAjMmI3YzJiXCI-PGI-NC4yPC9iPiBLRzwvdWk1LWxhYmVsPjwvdWk1LXRhYmxlLWNlbGw-XG5cdFx0XHRcdDx1aTUtdGFibGUtY2VsbD48dWk1LWxhYmVsPjxiPjk1NjwvYj4gRVVSPC91aTUtbGFiZWw-PC91aTUtdGFibGUtY2VsbD5cblx0XHRcdDwvdWk1LXRhYmxlLXJvdz5cblx0XHRcdDx1aTUtdGFibGUtcm93PlxuXHRcdFx0XHQ8dWk1LXRhYmxlLWNlbGw-PHVpNS1sYWJlbD48Yj5Ob3RlYm9vayBCYXNpYyAxNzwvYj48YnI-SFQtMTAwMTwvdWk1LWxhYmVsPjwvdWk1LXRhYmxlLWNlbGw-XG5cdFx0XHRcdDx1aTUtdGFibGUtY2VsbD48dWk1LWxhYmVsPlNtYXJ0Y2FyZHM8L3VpNS1sYWJlbD48L3VpNS10YWJsZS1jZWxsPlxuXHRcdFx0XHQ8dWk1LXRhYmxlLWNlbGw-PHVpNS1sYWJlbD4yOSB4IDE3IHggMy4xIGNtPC91aTUtbGFiZWw-PC91aTUtdGFibGUtY2VsbD5cblx0XHRcdFx0PHVpNS10YWJsZS1jZWxsPjx1aTUtbGFiZWwgc3R5bGU9XCJjb2xvcjogIzJiN2MyYlwiPjxiPjQuNTwvYj4gS0c8L3VpNS1sYWJlbD48L3VpNS10YWJsZS1jZWxsPlxuXHRcdFx0XHQ8dWk1LXRhYmxlLWNlbGw-PHVpNS1sYWJlbD48Yj4xMjQ5PC9iPiBFVVI8L3VpNS1sYWJlbD48L3VpNS10YWJsZS1jZWxsPlxuXHRcdFx0PC91aTUtdGFibGUtcm93PlxuXHRcdFx0PHVpNS10YWJsZS1yb3c-XG5cdFx0XHRcdDx1aTUtdGFibGUtY2VsbD48dWk1LWxhYmVsPjxiPk5vdGVib29rIEJhc2ljIDE4PC9iPjxicj5IVC0xMDAyPC91aTUtbGFiZWw-PC91aTUtdGFibGUtY2VsbD5cblx0XHRcdFx0PHVpNS10YWJsZS1jZWxsPjx1aTUtbGFiZWw-VGVjaG5vY29tPC91aTUtbGFiZWw-PC91aTUtdGFibGUtY2VsbD5cblx0XHRcdFx0PHVpNS10YWJsZS1jZWxsPjx1aTUtbGFiZWw-MzIgeCAyMSB4IDQgY208L3VpNS1sYWJlbD48L3VpNS10YWJsZS1jZWxsPlxuXHRcdFx0XHQ8dWk1LXRhYmxlLWNlbGw-PHVpNS1sYWJlbCBzdHlsZT1cImNvbG9yOiAjMmI3YzJiXCI-PGI-My43PC9iPiBLRzwvdWk1LWxhYmVsPjwvdWk1LXRhYmxlLWNlbGw-XG5cdFx0XHRcdDx1aTUtdGFibGUtY2VsbD48dWk1LWxhYmVsPjxiPjI5PC9iPiBFVVI8L3VpNS1sYWJlbD48L3VpNS10YWJsZS1jZWxsPlxuXHRcdFx0PC91aTUtdGFibGUtcm93PlxuPCEtLSBwbGF5Z3JvdW5kLWZvbGQtZW5kIC0tPlxuXHRcdDwvdWk1LXRhYmxlPlxuPCEtLSBwbGF5Z3JvdW5kLWZvbGQgLS0-XG5cdDwvZGl2PlxuICAgIFxuICAgIDxzY3JpcHQgdHlwZT1cIm1vZHVsZVwiIHNyYz1cIm1haW4uanNcIj48L3NjcmlwdD5cbjwvYm9keT5cblxuPC9odG1sPlxuPCEtLSBwbGF5Z3JvdW5kLWZvbGQtZW5kIC0tPlxuIn0sIm1haW4uanMiOnsibmFtZSI6Im1haW4uanMiLCJjb250ZW50IjoiLyogcGxheWdyb3VuZC1oaWRlICovXG5pbXBvcnQgXCIuL3BsYXlncm91bmQtc3VwcG9ydC5qc1wiO1xuLyogcGxheWdyb3VuZC1oaWRlLWVuZCAqL1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzL2Rpc3QvVGFibGUuanNcIjtcbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L1RhYmxlSGVhZGVyUm93LmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMvZGlzdC9UYWJsZUhlYWRlckNlbGwuanNcIjtcbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L0xhYmVsLmpzXCI7In19)
2. Scroll to right
3.
...

### Priority

Low

### UI5 Web Components Version

nightly

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by dobrinyonkov** [comment]
Hello colleagues, 

could you please check this issue following the reproduction steps? Shrink the width so a horizontal scroll appears.

Thanks and Best Regards,
Dobrin

**Comment by DonkeyCo** [comment]
Internally tracked with DINC0343582

**Comment by aborjinik** [comment]
Could you please check with the nightly version. I cannot reproduce the issue

**Comment by nnaydenow** [comment]
Hi @aborjinik,

Yes, it is not reproducible on the nightly deploy of the playground.
