### ISSUE TITLE
[Custom Webcomponent]: npm scripts fail for Javascript based custom webcomponent in V2

### ISSUE THREAD

**Issue by akshil-verma** [SAP/ui5-webcomponents#10209]
### Bug Description

NPM start and build scripts fail when one tries to create/migrate a `Javascript` based custom ui5-webcomponent in v2.4.0. The error received is:
```
The script called "prepare.typescript" which runs "tsc" failed with exit code 1 https://github.com/sezna/nps/blob/master/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
The script called "prepare" which runs "cross-env UI5_TS=true nps clean prepare.all  copyProps prepare.typescript generateAPI" failed with exit code 1 https://github.com/sezna/nps/blob/master/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
The script called "build" which runs "nps prepare lint build.bundle" failed with exit code 1 https://github.com/sezna/nps/blob/master/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
node:child_process:965
    throw err;
    ^

Error: Command failed: npx nps "build"
    at checkExecSyncError (node:child_process:890:11)
    at Object.execSync (node:child_process:962:15)
    at Object.<anonymous> (/Users/I341668/Workspace/Actions/AP-AC-Products-Services/Actions-WebComponents/node_modules/@ui5/webcomponents-tools/bin/dev.js:16:15)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 18279,
  stdout: null,
  stderr: null
}
```
The scripts from `nps.js` require `Typescript` although `options.typescript = false` in `package-script.js`. Even if `Typescript` is added as a dependency/devdependency, the npm scripts still fail.

### Affected Component

Custom webcomponent

### Expected Behaviour

NPM scripts should execute successfully without relying on `Typescript` as a dependency for JS based custom webcomponents.

### Steps to Reproduce

1. Create a custom webcomponent using the command `npm init @ui5/webcomponents-package`.
2. Select project type as `Javascript` and create the project.
3. Update ui5-webcomponents based dependencies to `2.4.0`.
4. Run `npm i`.
5. Run `npm start` or `npm build`.

### Log Output, Stack Trace or Screenshots

<img width="1727" alt="Screenshot 2024-11-19 at 5 28 34 PM" src="https://github.com/user-attachments/assets/7a0203f3-1940-458e-bce9-1da1523700e1">

### Priority

High

### UI5 Web Components Version

2.4.0

### Browser

Chrome

### Operating System

MacOS

### Organization

SAP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by akshil-verma** [comment]
Hi @nnaydenow,

You were right for the creation part, with the `latest` tag I was able to create a project that works properly.

However, my main use case is to migrate my existing Javascript based webcomponents project from 1.x to 2.x. I see that the with the `latest` tag during creation, I do not get an option of choosing Javascript or Typescript. Does this mean that I need to migrate my project to Typescript from Javascript?

Best regards,
Akshil Verma

**Comment by nnaydenow** [comment]
Hi @akshil-verma,

Javascript based webcomponents were deprecated and TypeScript components become default ones. With that `typescript` flag in package-script is no longer working and supported. It was replaced with `legacy`.

I've created JavaScript project with version 1.24 and migrated it to version 2.0 and setting that flag works as expected.

```diff
const options = {
	port: 8080,
-	typescript: false,
+	legacy: true,
};
```

Here you can also find our migration guide: https://sap.github.io/ui5-webcomponents/nightly/docs/migration-guides/to-version-2/

Hope this resolve your problem.

Regards,
Nayden

**Comment by akshil-verma** [comment]
Thanks @nnaydenow, it's working now. Can you also let me know till when will you continue the support of Javascript based webcomponents? (so that I can plan out my project's migration to Typescript)

**Comment by nnaydenow** [comment]
For comparability reasons it won’t be removed with version 2 but our guidance is to migrate as soon as you have capacity.
