### ISSUE TITLE
[ui5-shellbar]: avatar initials font-size

### ISSUE THREAD

**Issue by jarrettwchan** [SAP/ui5-webcomponents#10217]
### Bug Description

The Avatar font-size when embedded in Shellbar was changed.
In 1.20.x the embedded Avatar initials font-size was 0.75rem from Shellbar css.
In 1.24.x (and 2.3.x) the embedded Avatar initials uses the Avatar's font-size (XS for 1rem).

This change in the font-size makes a number of two-letter initials trigger the fallback icon.
Before, only "W" was problematic, and some 3-letter combinations worked.
Now, "M" is also problematic, others like "O", "D", "Q", "U", "G" can be more than half the available space, and 3-letter combinations require two "I"s to work.

### Affected Component

ui5-shellbar

### Expected Behaviour

Reduce the font-size for XS a bit so more of the 2 letter scenarios are visible.
Or dynamically subtract 1px from the font-size until it fits.

### Priority

Low

### UI5 Web Components Version

1.24.8

### Browser

Chrome

### Organization

SuccessFactors

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ivoplashkov** [comment]
Hello colleagues,

The isse could be reproduced in the playground. When you add initials="OD" and size="XS" the components triggers the fallback icon.

        <ui5-shellbar primary-title="Corporate Portal" secondary-title="Secondary title">
            <ui5-avatar initials="OD" slot="profile" size="XS"></ui5-avatar>
            <img slot="logo" src="https://sap.github.io/ui5-webcomponents/images/sap-logo-svg.svg" />
            <ui5-button icon="nav-back" slot="startButton"></ui5-button>
        </ui5-shellbar>
        
Could you please have a look?

Regards,
Ivaylo
