### ISSUE TITLE
[component name | framework | build | icons | theming | localization | i18n | typescript]:Input

### ISSUE THREAD

**Issue by Garima123639** [SAP/ui5-webcomponents#10231]
### Bug Description

onSelect event handler doesn't work as expected. It should ideally be fired when the user selects the element from the suggested items in the dropdown through either the keyboard enter or click but its not fired. Also onSelectionChange is fired everytime you press any keydown in the suggested dropdown so that could not be used. onSelect should be able to do the same task as onSuggestionItemSelect from the previous version but its not doing

### Affected Component

Input

### Expected Behaviour

 onSelect should be able to do the same task as onSuggestionItemSelect from the previous version but its not doing

### Steps to Reproduce

1. Use Input component with onSelect and having showSuggestions set to true.
2. Select something from the suggestions either through keyboard down key and press enter or directly mouse click
3. the handler assigned to onSelect is not fired appropriately
...

### Priority

None

### UI5 Web Components Version

Version 2

### Browser

Chrome, Edge, Firefox, Safari

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ivoplashkov** [comment]
Hello @Garima123639,

Thank you for reporting the issue. 

We would like to clarify the behavior of the events:

1. `select`: This is an event triggered when the user selects text within the input field. It is not intended for handling dropdown item selection.  - https://sap.github.io/ui5-webcomponents/components/Input/#select
2. `selection-change`: This is triggered whenever the user navigates through suggestions (e.g., using arrow keys). It is designed for previewing items and is not equivalent to final selection. - https://sap.github.io/ui5-webcomponents/components/Input/#selection-change

For detecting the final selection of a dropdown item (via Enter or click), please use `input` event. This will provide the desired behavior, as the event is fired when the value of the component changes at each keystroke, and when a **suggestion item has been selected.**

Hope this helps!

Best regards,
Ivaylo
