### ISSUE TITLE
ui5-switch is not aligned vertically

### ISSUE THREAD

**Issue by brodo** [SAP/ui5-webcomponents#1024]
**Describe the bug**
ui5-switch should be aligned vertically with all other input components

**To reproduce**
1. Go to https://codesandbox.io/embed/ui5-webcomponents-l8n3f

**Isolated example**
https://codesandbox.io/embed/ui5-webcomponents-l8n3f

**Expected behavior**
ui5-switch should be at the same level as the other components.

**Screenshots**
![Screenshot 2019-12-06 at 09 01 29](https://user-images.githubusercontent.com/377911/70306400-0d961a00-1807-11ea-921d-c7069a9d18d0.png)

**Context**
- UI5 Web Components version 1.0.0-rc.5
- OS/Platform: Mac Os
- Browser *(if relevant)*: Firefox Developer Edition 72

**Affected components** 
ui5-switch

**Comment by rkl1994** [comment]
Hi, I am also facing the same issue. So, I'd like to know if there is any workaround before this bug be fixed? 
Thank you.

**Comment by ilhan007** [comment]
Using display="flex" to center the items for example:

```html
<div style="display: flex; align-items: center">
    <ui5-button>Press me</ui5-button>
    <ui5-switch></ui5-switch>
</div>
```

**Comment by ilhan007** [comment]
Closing the issue, we won't take any actions on the issue as there is a standard way for cantering and aligning elements.

```html
<div style="display: flex; align-items: center">
    <ui5-button>Press me</ui5-button>
    <ui5-switch></ui5-switch>
</div>
```
