### ISSUE TITLE
ui5-checkbox is not aligned vertically

### ISSUE THREAD

**Issue by brodo** [SAP/ui5-webcomponents#1025]
**Describe the bug**
ui5-checkbox should be aligned vertically with all other input components

**To reproduce**
1. Go to https://codesandbox.io/embed/ui5-webcomponents-l8n3f

**Isolated example**
https://codesandbox.io/embed/ui5-webcomponents-l8n3f

**Expected behavior**
ui5-chckbox should be at the same level as the other components.

**Screenshots**
![Screenshot 2019-12-06 at 09 08 34](https://user-images.githubusercontent.com/377911/70306799-07546d80-1808-11ea-8142-486df00e70de.png)

**Context**
- UI5 Web Components version 1.0.0-rc.5
- OS/Platform: Mac Os
- Browser *(if relevant)*: Firefox Developer Edition 72

**Affected components** 
ui5-checkbox

**Comment by ilhan007** [comment]
Closing the issue, we won't take any action about the issue as there is a standard way for cantering and aligning elements.

```html
<div style="display: flex; align-items: center">
    <ui5-button>Press me</ui5-button>
    <ui5-checkbox></ui5-checkbox>
</div>
```
