### ISSUE TITLE
[Button]: Using the enter key and keep down will causing endless onClick events fired

### ISSUE THREAD

**Issue by JWandrocke** [SAP/ui5-webcomponents#10299]
### Bug Description

Using the keyboard enter key and keep down on a button will cause the onClick event to be fired forever until the key is released.

### Expected Behaviour

Only get the onClick event on keyUp

### Priority

High

### UI5 Web Components Version

2.4.0

### Browser

Chrome

### Organization

SAP Joule team

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by pskelin** [comment]
Thats how the native button works too, see a sample here:
[button click on enter key sample](https://sap.github.io/ui5-webcomponents/play/#eyJpbmRleC5odG1sIjp7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuPCFET0NUWVBFIGh0bWw-XG5cbjxoZWFkPlxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG5cbiAgICBodG1sIHtcbiAgICAgIGZvcmNlZC1jb2xvci1hZGp1c3Q6IG5vbmU7XG4gICAgfVxuICAgIDwvc3R5bGU-XG5cbjwvaGVhZD5cblxuPGJvZHkgc3R5bGU9XCJiYWNrZ3JvdW5kLWNvbG9yOiB2YXIoLS1zYXBCYWNrZ3JvdW5kQ29sb3IpOyBjb2xvcjogdmFyKC0tc2FwVGV4dENvbG9yKTtcIj5cbiAgPCEtLSBwbGF5Z3JvdW5kLWZvbGQtZW5kIC0tPlxuXG4gIDxidXR0b24-ZW5kbGVzcyBjbGljayBvbiBlbnRlciAtIHNlZSBjb25zb2xlPC9idXR0b24-XG4gIDwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCJtYWluLmpzXCI-PC9zY3JpcHQ-XG48L2JvZHk-XG5cbjwhLS0gcGxheWdyb3VuZC1mb2xkLWVuZCAtLT5cbiJ9LCJtYWluLnRzIjp7Im5hbWUiOiJtYWluLnRzIiwiY29udGVudCI6ImltcG9ydCBcIi4vcGxheWdyb3VuZC1zdXBwb3J0LmpzXCI7XG5kb2N1bWVudC5xdWVyeVNlbGVjdG9yKFwiYnV0dG9uXCIpLmFkZEV2ZW50TGlzdGVuZXIoXCJjbGlja1wiLCAoKSA9PiBjb25zb2xlLmxvZyhcImJ1dHRvbiBjbGlja2VkXCIpKSJ9fQ)

The common pattern if you want to do the action just once, is to set the button to disabled when the first click arrives and return it to enabled whenever the operation is finished.

**Comment by nnaydenow** [comment]
Hi @JWandrocke,

Specification of the button says that it has to fire click event while the Enter key is pressed (while you keep the key down) and only once when the Space key is released. As Petar mentioned this is how the native button works as well.

**Comment by hinzzx** [comment]
Hi @JWandrocke ,

The reported case was discussed within our team, and the button's behaviour as it is now - is working as expected.

Best Regards,
Stoyan
