### ISSUE TITLE
Popover methods section not readable

### ISSUE THREAD

**Issue by hristop** [SAP/ui5-webcomponents#1029]
Hi,

Can you please check the methods section of the [Popover page in the playground](https://sap.github.io/ui5-webcomponents/playground/components/Popover/)?
The section seem a bit unordered and the "openBy" method is missing.

<img width="1996" alt="Screenshot 2019-12-09 at 11 25 12" src="https://user-images.githubusercontent.com/14230119/70423651-96ff5380-1a76-11ea-9231-6705cb6ab679.png">

**Comment by MWFIAE** [comment]
Popover is also missing the default slot in the documentation.
