### ISSUE TITLE
Feature Request: Select all text on focus in the Input component

### ISSUE THREAD

**Issue by mrmabo** [SAP/ui5-webcomponents#10307]
### **Description**
**Background**
The current requirement is that when a user focuses on an Input component, if the input contains a default value (e.g., "Not Selected") or  any characters , the UI should automatically select all the text in the input field, mimicking a "Select All" operation.

**Problem**
Currently, the @ui5/webcomponents-react Input component does not provide built-in support for this behavior (e.g., through a configuration option or method). I would like to explore if there's a solution for implementing this functionality or if there are plans to support it natively.

![image](https://github.com/user-attachments/assets/8ae7925b-a564-4c82-877e-cb7b27fbad3c)

### Describe the solution you'd like

Could there be an option or method to support this behavior, such as:

- Adding a boolean property selectOnFocus that, when set to true, enables this auto-select feature.

- Providing a method that developers can call to achieve this functionality.

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by hinzzx** [comment]
Hi colleagues @SAP/ui5-webcomponents-topic-rl,

Could you please take a look at that feature request ?

Best Regards,
Stoyan

**Comment by mrmabo** [comment]
After discuss with our UX, we don't need additional user interaction. Hence closing this ticket.
