### ISSUE TITLE
Typo in ui5-webcomponents/packages/main/src/Icon.ts

### ISSUE THREAD

**Issue by bachlge** [SAP/ui5-webcomponents#10301]
### **Issue Description**

Module `ui5-webcomponents/packages/main/src/Icon.ts`:

Incorrect descriptive text: [@ui5/webcomponents-icons-icons-business-suite](https://www.npmjs.com/package/@ui5/webcomponents-icons-business-suite).

--> remove the second `icons-`

### **Issue Type**

- [ ] Documentation is unclear
- [x] Documentation is incorrect
- [ ] Documentation is missing
- [ ] Other

**Comment by hinzzx** [comment]
Hi colleagues @SAP/ui5-webcomponents-topic-p ,

There is a typo in the documentation of the `Icon.ts` file, could you please have a look,

Regards,
Stoyan
