### ISSUE TITLE
ItemNavigation: Focus lost when navigating between different views

### ISSUE THREAD

**Issue by tsanislavgatev** [SAP/ui5-webcomponents#1031]
**Describe the bug**
Focus lost when navigation between last and second last months in daypicker.

**To reproduce**
1. Go to december 9999
2. Go to november 9999 with keyboard
3. Go back to december and the focus is lost

**Isolated example**
https://sap.github.io/ui5-webcomponents/playground/components/DatePicker/

**Expected behavior**
Focus stays on last focusable element.

**Screenshots**

**Context**
- UI5 Web Components version - master

**Affected components** *(if known)*
Datepicker
**Log output / Any errors** in the console
None

**Comment by fifoosid** [comment]
Issue is resolved!
