### ISSUE TITLE
[AvatarGroup]: component breaks if imported before `Avatar`

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#10328]
### Bug Description

If the `AvatarGroup` is imported before the `Avatar` the component breaks. We unfortunately only noticed it now, but it seems to be broken since v2.3.0.

2.3.0: https://stackblitz.com/edit/github-sbebi7-qdbsxt?file=index.html,main.js,package.json
2.5.0: https://stackblitz.com/edit/github-sbebi7?file=index.html,main.js,package.json

```sh
@ui5_webcomponents_dist_AvatarGroup__js.js?v=972856ec:1002 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'Group')
    at @ui5_webcomponents_dist_AvatarGroup__js.js?v=972856ec:1002:69
    at Array.forEach (<anonymous>)
    at AvatarGroup2._prepareAvatars (@ui5_webcomponents_dist_AvatarGroup__js.js?v=972856ec:995:16)
    at AvatarGroup2.onBeforeRendering (@ui5_webcomponents_dist_AvatarGroup__js.js?v=972856ec:936:10)
    at AvatarGroup2._render (chunk-BG6ITDOG.js?v=31aeb8c2:1202:12)
    at renderImmediately (chunk-ONOVPAGF.js?v=31aeb8c2:375:16)
    at AvatarGroup2.connectedCallback (chunk-BG6ITDOG.js?v=31aeb8c2:786:5)
```

This affects our [Storybook](https://sap.github.io/ui5-webcomponents-react/v2/?path=/docs/data-display-avatargroup--docs) as well.

### Isolated Example

https://stackblitz.com/edit/github-sbebi7?file=index.html,main.js,package.json

### Steps to Reproduce

1. Go to [StackBlitz](https://stackblitz.com/edit/github-sbebi7?file=index.html,main.js,package.json)
2. See error in console.
3. Reorder the imports.
4. Works as intended.

### Priority

High

### UI5 Web Components Version

2.5.0 (probably since 2.3.0)

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by nnaydenow** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

Could you please check?
