### ISSUE TITLE
[FileUploader]: throws error on click

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#10329]
### Bug Description

When a `FileUploader` is used without additional properties or components, it throws an error when clicked. I didn't test this extensively, but I didn't find that the functionality is affected by this, so I'll mark this issue with low prio. Please adjust it if necessary.

```sh
@ui5_webcomponents_dist_FileUploader__js.js?v=1d8aeac2:7887 Uncaught TypeError: Cannot read properties of undefined (reading 'matches')
    at FileUploader2._onclick (@ui5_webcomponents_dist_FileUploader__js.js?v=1d8aeac2:7887:30)
    at EventPart.handleEvent (@ui5_webcomponents_dist_FileUploader__js.js?v=1d8aeac2:2622:29)
```

### Affected Component

FileUploader

### Isolated Example

https://stackblitz.com/edit/github-sbebi7-pir2ag?file=index.html,main.js,package.json

### Steps to Reproduce

1. Go to [StackBlitz](https://stackblitz.com/edit/github-sbebi7-pir2ag?file=index.html,main.js,package.json)
2. Click on `FileUploader`.
3. See error in console.

### Priority

Low

### UI5 Web Components Version

2.5.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by nnaydenow** [comment]
Hi @SAP/ui5-webcomponents-topic-b,

Could you please check?
