### ISSUE TITLE
[UserMenu]: provide `close` event

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#10332]
### Feature Request Description

In React it's typical controlling the `open` property via a React state. Currently this is not possible, as the `open` property/attribute can be changed by the component, but there is no way to register to these changes. So, this feature request describes basically the same issue as this one: https://github.com/SAP/ui5-webcomponents/issues/10063

In case you need more context, please let me know.

### Proposed Solution

Expose the `close` event of the popover.

### Organization

UI5WCR

### Priority

None

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-skr 
could you evaluate this request by UI5 Web Components 4 React colleagues.

**Comment by adrian-bobev** [comment]
Hello Lukas,

the issue should be fixed with this PR:
https://github.com/SAP/ui5-webcomponents/pull/10363
