### ISSUE TITLE
[UserMenu]: no pointer cursor when hovering list items

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#10331]
### Bug Description

When hovering the interactive list items of the `UserMenu`, only the standard cursor is displayed.

https://github.com/user-attachments/assets/f2ff28d5-2b1d-4d58-b8aa-5c188615217f

### Expected Behaviour

The cursor should use the pointer design.

### Isolated Example

https://sap.github.io/ui5-webcomponents/components/fiori/UserMenu/

### Steps to Reproduce

1. Go to your [playground](https://sap.github.io/ui5-webcomponents/components/fiori/UserMenu/).
2. Hover over one of the list items.
3. See that the default cursor is used.
...

### Priority

Low

### UI5 Web Components Version

2.5.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ilhan007** [comment]
Helo @SAP/ui5-webcomponents-topic-b the UserMenuItem, which is extending MenuItem does not show `cursor: pointer` on hover. I checked the the Menu [basic sample](https://sap.github.io/ui5-webcomponents/components/Menu/#basic-sample) and it's the same - no pointer cursor when hovering the items, although the type is Active by default
