### ISSUE TITLE
[ui5-dynamic-page-title]: cannot fire click event for elements inside DynamicPageTitle

### ISSUE THREAD

**Issue by ksblklu02** [SAP/ui5-webcomponents#10347]
### Bug Description

For none interactive elements(e.g. ui5-label) inside DynamicPageTitle, click event will fallback to the "title-toggle" event of DynamicPage, event binding to ui5-label cannot be triggered.

### Affected Component

ui5-dyanmic-page-title

### Expected Behaviour

ui5-label click event should be able to triggered inside DynamicPageTitle

### Isolated Example

https://stackblitz.com/edit/github-cbs6vz-xbhby9pg?file=src%2FApp.tsx

### Steps to Reproduce

1. Go to https://stackblitz.com/edit/github-cbs6vz-xbhby9pg?file=src%2FApp.tsx 
2. Click on page subheading 
3. The click event of subheading label to open a popover cannot be triggered
<img width="1312" alt="image" src="https://github.com/user-attachments/assets/1b90503d-86c8-4bf8-ac1b-1601fd0cd071">

### Priority

High

### UI5 Web Components Version

2.5.0

### Browser

Chrome

### Additional Context

Before upgrading ui5 to 2.x, we are using DynamicPage implemented by @ui5/webcomponents-react repo. After replace it to ui5/webcomponents DynamicPage, the click events for elements like ui5-label inside DynamicPageTitle cannot be triggered. This change have impact to our page, some existing feature cannot work anymore.

### Organization

SAP SuccessFactors

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by plamenivanov91** [comment]
Hello @SAP/ui5-webcomponents-topic-rd,

It seems that the Label is not registering click event and the event is passed to the DynamicPageTitle which results in collapsing it.
This doesn't happen when Label is switched with Button for example.

I am not really sure if there should be click event on the Label since, it's not focusable element.
Reporter claims that his code worked fine on the previous WC version (1.**).

Could you please look into it?

Regards,
Plamen Ivanov

**Comment by s-todorova** [comment]
Hi @SAP/ui5-webcomponents-topic-p,

The Label component is working as expected: compare playground examples in versions [1.x](https://sap.github.io/ui5-webcomponents/v1/play/#eyJpbmRleC5odG1sIjp7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuPCFET0NUWVBFIGh0bWw-XG48aHRtbCBsYW5nPVwiZW5cIj5cblxuXG5cbjxoZWFkPlxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG4gICAgPC9zdHlsZT5cblxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG4gICAgPC9zdHlsZT5cblxuICAgIDxtZXRhIGNoYXJzZXQ9XCJVVEYtOFwiPlxuICAgIDxtZXRhIG5hbWU9XCJ2aWV3cG9ydFwiIGNvbnRlbnQ9XCJ3aWR0aD1kZXZpY2Utd2lkdGgsIGluaXRpYWwtc2NhbGU9MS4wXCI-XG4gICAgPHRpdGxlPlNhbXBsZTwvdGl0bGU-XG48L2hlYWQ-XG5cbjxib2R5IHN0eWxlPVwiYmFja2dyb3VuZC1jb2xvcjogdmFyKC0tc2FwQmFja2dyb3VuZENvbG9yKVwiPlxuICAgIDwhLS0gcGxheWdyb3VuZC1mb2xkLWVuZCAtLT5cblxuPHVpNS1sYWJlbCBvbmNsaWNrPVwidGVzdCgpXCI-U2ltcGxlIExhYmVsPC91aTUtbGFiZWw-PGJyPlxuPHNjcmlwdD5cbiAgZnVuY3Rpb24gdGVzdCgpIHtcbiAgIGNvbnNvbGUubG9nKFwidGVzdFwiKTsgXG4gIH1cbjwvc2NyaXB0PlxuICAgIDwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuICAgIDxzY3JpcHQgdHlwZT1cIm1vZHVsZVwiIHNyYz1cIm1haW4uanNcIj48L3NjcmlwdD5cbjwvYm9keT5cblxuPC9odG1sPlxuPCEtLSBwbGF5Z3JvdW5kLWZvbGQtZW5kIC0tPlxuIn0sIm1haW4uanMiOnsibmFtZSI6Im1haW4uanMiLCJjb250ZW50IjoiLyogcGxheWdyb3VuZC1oaWRlICovXG5pbXBvcnQgXCIuL3BsYXlncm91bmQtc3VwcG9ydC5qc1wiO1xuLyogcGxheWdyb3VuZC1oaWRlLWVuZCAqL1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzL2Rpc3QvTGFiZWwuanNcIjtcbiJ9fQ) and [2.x](https://sap.github.io/ui5-webcomponents/play/#eyJpbmRleC5odG1sIjp7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuPCFET0NUWVBFIGh0bWw-XG48aHRtbCBsYW5nPVwiZW5cIj5cblxuXG5cbjxoZWFkPlxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG5cbiAgICBodG1sIHtcbiAgICAgIGZvcmNlZC1jb2xvci1hZGp1c3Q6IG5vbmU7XG4gICAgfVxuICAgIDwvc3R5bGU-XG5cbiAgICBcbiAgICA8c3R5bGU-XG4gICAgICAqOm5vdCg6ZGVmaW5lZCkge1xuICAgICAgICBkaXNwbGF5OiBub25lO1xuICAgICAgfVxuXG4gICAgaHRtbCB7XG4gICAgICBmb3JjZWQtY29sb3ItYWRqdXN0OiBub25lO1xuICAgIH1cbiAgICA8L3N0eWxlPlxuXG4gICAgPG1ldGEgY2hhcnNldD1cIlVURi04XCI-XG4gICAgPG1ldGEgbmFtZT1cInZpZXdwb3J0XCIgY29udGVudD1cIndpZHRoPWRldmljZS13aWR0aCwgaW5pdGlhbC1zY2FsZT0xLjBcIj5cbiAgICA8dGl0bGU-U2FtcGxlPC90aXRsZT5cbjwvaGVhZD5cblxuPGJvZHkgc3R5bGU9XCJiYWNrZ3JvdW5kLWNvbG9yOiB2YXIoLS1zYXBCYWNrZ3JvdW5kQ29sb3IpXCI-XG4gICAgPCEtLSBwbGF5Z3JvdW5kLWZvbGQtZW5kIC0tPlxuXG48dWk1LWxhYmVsIG9uY2xpY2s9XCJ0ZXN0KClcIj5TaW1wbGUgTGFiZWw8L3VpNS1sYWJlbD48YnI-XG48c2NyaXB0PlxuICBmdW5jdGlvbiB0ZXN0KCkge1xuICAgY29uc29sZS5sb2coXCJ0ZXN0XCIpOyBcbiAgfVxuPC9zY3JpcHQ-XG4gICAgPCEtLSBwbGF5Z3JvdW5kLWZvbGQgLS0-XG4gICAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwibWFpbi5qc1wiPjwvc2NyaXB0PlxuPC9ib2R5PlxuXG48L2h0bWw-XG48IS0tIHBsYXlncm91bmQtZm9sZC1lbmQgLS0-XG4ifSwibWFpbi5qcyI6eyJuYW1lIjoibWFpbi5qcyIsImNvbnRlbnQiOiIvKiBwbGF5Z3JvdW5kLWhpZGUgKi9cbmltcG9ydCBcIi4vcGxheWdyb3VuZC1zdXBwb3J0LmpzXCI7XG4vKiBwbGF5Z3JvdW5kLWhpZGUtZW5kICovXG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMvZGlzdC9MYWJlbC5qc1wiOyJ9fQ) - the click event is registered normally on both.
Therefore it seems that the issue might be related to the DynamicPage component instead.
Could you please investigate further?

Best regards,
Siyana
