### ISSUE TITLE
[ui5-side-navigation]: overflow popover broken

### ISSUE THREAD

**Issue by LidiyaGeorgieva** [SAP/ui5-webcomponents#10378]
### Bug Description

Overflow popover is broken.

### Steps to Reproduce

1. open: https://sap.github.io/ui5-webcomponents/nightly/packages/fiori/test/pages/SideNavigationOnly.html?sap-ui-theme=sap_horizon 
2. collapse the side navigation
3. click on "..." to open the overflow popover

### Log Output, Stack Trace or Screenshots

![Image](https://github.com/user-attachments/assets/e70ae137-1a63-488a-96e6-c301dae11b62)

### Priority

High

### UI5 Web Components Version

latest

### Browser

Chrome

### Declaration

- [x] I’m not disclosing any internal or sensitive information.

**Comment by LidiyaGeorgieva** [comment]
Hello @SAP/ui5-webcomponents-core ,

Please have a look.

Best Regards,
Lidiya

**Comment by nnaydenow** [comment]
Fixed with https://github.com/SAP/ui5-webcomponents/pull/10379
