### ISSUE TITLE
[Carousel]: HideNavigationArrows prop is not respected in touch screens

### ISSUE THREAD

**Issue by amdev138** [SAP/ui5-webcomponents#10383]
### Bug Description

Hi team,

Recent change was made to always show the navigation arrows in the content areas for touch screens. This causes an issue when the consumer defines hide-navigation-arrows, in order to implement their own navigation arrows. This was done via, [ui5-webcomponents/commit/8072baff0](https://github.com/SAP/ui5-webcomponents/commit/8072baff08f6a4cc67988aecaaf115f968fcc4de). This will cause two sets of navigation buttons to be rendered and they can easily become out of sync. The expected behavior would be if the consumer declares they want to hide the navigation arrows, then they will be hidden on all screens.
Please see:
<img width="332" alt="Image" src="https://github.com/user-attachments/assets/5a14d630-8280-472b-a2fd-0fe28d1e6274" />

### Affected Component

Carousel

### Expected Behaviour

The hideNavigationArrows property should be honored.

### Isolated Example

https://stackblitz.com/edit/js-rjg6uwjq?file=index.js,index.html

### Steps to Reproduce

1. Open the stackblits provided in a mobile device
2. See the two navigation arrows even when consumer has defined the ones in the content to be hidden.
...

### Priority

Medium

### UI5 Web Components Version

version 2.3.0 and greater

### Browser

Chrome, Edge, Firefox, Safari

### Declaration

- [x] I’m not disclosing any internal or sensitive information.

**Comment by TeodorTaushanov** [comment]
The issue is fixed in the main branch.
