### ISSUE TITLE
[MultiInput][Tokenizer]: [Unable to display custom element in the more item popover]

### ISSUE THREAD

**Issue by missyii** [SAP/ui5-webcomponents#10386]
### Describe the bug

We are using the multi input to implement the following functionality based on ux design like folling:
<img width="1087" alt="Image" src="https://github.com/user-attachments/assets/1d48eda3-a276-47bd-a3a5-ebffac3220b7" />

But I fund that I can not add custom element to Token, so I added custom element to the tokens of MultiInput, but custom elements will show blank in the more item popover list. 

### Isolated Example

https://stackblitz.com/edit/github-b3bzxd-4jwtfek5?file=src%2FArrayEnum.tsx,src%2FApp.tsx

### Reproduction steps

1.
2.
3.
...

### Expected Behaviour

Display my custom element in the more item popover Normally.

### Screenshots or Videos

<img width="565" alt="Image" src="https://github.com/user-attachments/assets/e34b11bd-89d2-4203-9515-3d94421b245d" />

### UI5 Web Components for React Version

18.3.1

### UI5 Web Components Version

2.4.0

### Browser

Chrome

### Relevant log output

```shell

```

### Organization

SAP DEV

### Declaration

- [x] I’m not disclosing any internal or sensitive information.

**Comment by Valkanister** [comment]
Hello @missyii, 

Your sample has some issues in regards to how the MultiInput is populated with tokens. 
We expect an array of Tokens (that implement the IToken interface): 
https://sap.github.io/ui5-webcomponents/components/MultiInput/#tokens
You are providing a Tokenizer, which itself holds tokens or styled Links. 
In our implementation adding Links this way is not possible. 

Kind regards, 

Georgi

SAP Development Support

**Comment by missyii** [comment]
Hello @Valkaniste,
You mean that only supporting Token for tokens field in MultiInput? Do not support custom element, right? 
But in the document I saw here said support custom element if add slot prop: <img width="799" alt="Image" src="https://github.com/user-attachments/assets/5c1c6f3c-acf9-4c43-9f4f-5a4f6938965c" />

**Comment by Lukas742** [comment]
Hi @missyii 

this is a note added by our React wrapper (`@ui5/webcomponents-react`). Passing a custom React component still requires the expected web component/s (in this case `ui5-token`) to be rendered. We'll improve our docs to make this clearer.

**Comment by missyii** [comment]
@Lukas742 @Valkanister ok, thanks you for help explain my confuse, I need to implement an my own tokenizer component. Hope in the future, Token can support custom html element, but not only accept a string text.

**Comment by Valkanister** [comment]
Hello @missyii, 

As the issue seems clarified, I will close it. 

Kind regards, 
Georgi
