### ISSUE TITLE
[ui5-dynamic-page]: DynamicPageHeader can still be interactive when loading

### ISSUE THREAD

**Issue by ksblklu02** [SAP/ui5-webcomponents#10399]
### Bug Description

When DynamicPage is wrapped in ui5-busy-indicator, the header area can still be interactive when busy status set to active.

### Affected Component

ui5-dynamic-page

### Expected Behaviour

DynamicPage header area should not be interactive when wrapped in active busy indicator.

### Isolated Example

https://stackblitz.com/edit/github-gafhlvhg?file=src%2FApp.tsx

### Steps to Reproduce

1. Go to https://stackblitz.com/edit/github-gafhlvhg?file=src%2FApp.tsx 
2. Click on the "set loading" button
3. See the DynamicPage header is still interactive when loading
<img width="1235" alt="Image" src="https://github.com/user-attachments/assets/0ce2051f-b22c-4e0e-813e-a509abe21a2a" />

### Priority

High

### UI5 Web Components Version

2.5.0

### Browser

Chrome

### Operating System

MacOS

### Additional Context

When the whole page is loading, interactive page header is not expected. Because in some cases the loading is triggered from the page header, if user clicks on the page header elements during loading would duplicate the loading action and cause performance or other potential issue.

### Organization

SAP SuccessFactors

### Declaration

- [x] I’m not disclosing any internal or sensitive information.

**Comment by ilhan007** [comment]
Hi @ksblklu02 would this [workaround](https://stackblitz.com/edit/github-gafhlvhg-ej5hjtoh?file=src%2FApp.tsx) fine with you - it's resetting the z-index of the dynamic page, when "loading" is true.

**Comment by ksblklu02** [comment]
Hi @ilhan007 
Many thanks for your quick support and this workaround looks good. And we also want to confirm will @ui5/webcomponents provide internal fix in the future? Or the current z-index for the DynamicPage header is expected behavior?

**Comment by Valkanister** [comment]
"Hello @SAP/ui5-webcomponents-topic-p, take a look of this issue with the DynamicPage."
