### ISSUE TITLE
[documentation]: samples are empty

### ISSUE THREAD

**Issue by LidiyaGeorgieva** [SAP/ui5-webcomponents#10393]
### Bug Description

https://sap.github.io/ui5-webcomponents/nightly/components/fiori/NavigationLayout/#basic-sample
![Image](https://github.com/user-attachments/assets/a50ce309-f6b8-4f1c-9919-e46e7d801bb8)

Not reproducible when I switch to version 2.5.0

### Priority

Medium

### UI5 Web Components Version

nightly

### Browser

Chrome

### Declaration

- [x] I’m not disclosing any internal or sensitive information.

**Comment by LidiyaGeorgieva** [comment]
Hello @SAP/ui5-webcomponents-topic-core ,

Please have a look at this issue.

Best Regards,
Lidiya

**Comment by ilhan007** [comment]
Thank you @LidiyaGeorgieva, it's a known issue, we are already working on it.
