### ISSUE TITLE
[DynamicPage]: footerArea is not displayed

### ISSUE THREAD

**Issue by rvsia** [SAP/ui5-webcomponents#10404]
### Bug Description

footerArea of DynamicPage is not displayed

Accept button is missing:

![Image](https://github.com/user-attachments/assets/dd2cbb8e-5ecf-430a-8fde-8785d57acc6a)

### Affected Component

dynamicPage

### Expected Behaviour

footerArea is displayed

### Isolated Example

https://sap.github.io/ui5-webcomponents-react/v2/?path=/docs/layouts-floorplans-dynamicpage--docs

### Steps to Reproduce

1. check the official documentation, floating bar is missing

### Priority

Very High

### UI5 Web Components Version

v2

### Browser

Chrome

### Operating System

MacOS

### Organization

SAP Signavio

### Declaration

- [x] I’m not disclosing any internal or sensitive information.

**Comment by nnaydenow** [comment]
Hi @rvsia,

As it was suggested in slack channel with version 2 you need to set `showFooter` property to `true` in order to display the footer.

You can check:
https://sap.github.io/ui5-webcomponents-react/v2/?path=/docs/migration-guide--docs#dynamicpage

Regards,
Nayden
