### ISSUE TITLE
UI5 v2 is not compatible with the low version firefox

### ISSUE THREAD

**Issue by I569110** [SAP/ui5-webcomponents#10401]
### Bug Description

Reproduced browser: firefox 
browser version: 116.0.3

Hi team, We found the the ui5 v2 components are compatible with the low version firefox. Take component messagebox as example, when clicking on the cancel button of the messagebox, it is not closing the messagebox as expected. This issue is causing our App being blocked by closing the messagebox. Can ui5 v2 fix this issue to make it compatible with lower firefox version?
<img width="322" alt="Image" src="https://github.com/user-attachments/assets/ec2cf152-ef6a-477f-bfba-ce9617676400" />

### Isolated Example

https://sap.github.io/ui5-webcomponents/components/Dialog/#basic-sample
![Image](https://github.com/user-attachments/assets/d7a3ead5-5330-47f6-b50a-df1b879a49f5)

### Steps to Reproduce

1.
2.
3.
...

### Priority

Very High

### UI5 Web Components Version

v2

### Browser

Firefox

### Declaration

- [x] I’m not disclosing any internal or sensitive information.

**Comment by petyabegovska** [comment]
Hi @I569110,

The UI5 Web Components project supports the latest two stable browser releases, as outlined here: [Browser Support](https://github.com/SAP/ui5-webcomponents?tab=readme-ov-file#browser-support).

The Firefox version you mentioned, 116.0.3, is quite outdated—it was released to the stable channel on August 16, 2023. For your reference, you can find a list of the latest Firefox versions here: [Firefox Release Notes](https://www.mozilla.org/en-US/firefox/releases/).

Is it an option for you to update to latest Firefox?

Best regards,
Petya
