### ISSUE TITLE
[SF][List > ListItemGroup]: Ensure elements with an ARIA role that require child roles contain them

### ISSUE THREAD

**Issue by Natesan** [SAP/ui5-webcomponents#10412]
### Describe the bug

List subcomponent ListItemGroup has issues on accessibility scans where the Axe DevTools for example is throwing the following error on the ListItemGroup (https://sap.github.io/ui5-webcomponents-react/v2/?path=/story/data-display-list--list-item-group-story)

### Reproduction steps

1. Navigate to https://sap.github.io/ui5-webcomponents-react/v2/?path=/story/data-display-list--list-item-group-story
2. Open Axe DevTools and run a full page scan 
3. Observe the error listed there

### Expected Behaviour

Ensure elements with an ARIA role that require child roles contain them

### Screenshots or Videos

<img width="1669" alt="Image" src="https://github.com/user-attachments/assets/a1ad3d4f-8fb1-49c8-b05e-0a00fc2d76e7" />

### UI5 Web Components for React Version

2.5.0

### UI5 Web Components Version

2.5.0

### Browser

Chrome

### Operating System

MacOS

### Relevant log output

```shell

```

### Organization

SF

### Declaration

- [x] I’m not disclosing any internal or sensitive information.

**Comment by yanaminkova** [comment]
Hello @Natesan,

Thank you for bringing this issue to our attention.
We’d like to let you know that it has already been reported (https://github.com/SAP/ui5-webcomponents/issues/10297) and will be handled as a backlog item.(Internal reference: BGSOFUIPIRIN-6285)

We appreciate your patience and understanding!

Kind regards,
Yana
