### ISSUE TITLE
Enhance Mobile Support for Input like components

### ISSUE THREAD

**Issue by MapTo0** [SAP/ui5-webcomponents#1087]
Most of the Input like components open a Dialog on mobile Device. This is the target design based on the Fiori guidelines and should be implemented in:

- [ ] Input (with Suggestions)
- [ ] MultiComboBox (with Suggestions)
- [ ] DatePicker (with Suggestions)

https://openui5nightly.hana.ondemand.com/entity/sap.m.MultiComboBox/sample/sap.m.sample.MultiComboBox

![image](https://user-images.githubusercontent.com/5821279/71174590-43f38080-226e-11ea-922c-e060392de925.png)
![image](https://user-images.githubusercontent.com/5821279/71174607-4c4bbb80-226e-11ea-89b6-88d66af07704.png)

**Comment by vladitasev** [comment]
Implement ResponsivePopover and refactor all of the relevant components with it.
