### ISSUE TITLE
[Text-Area][Bug] NPE if provided value is null

### ISSUE THREAD

**Issue by mehdijouan** [SAP/ui5-webcomponents#1094]
Using a text area, if the value is null, the replace function called will fail.

Here is the stacktrace of the console:
```
TextArea.js?afc7:330 Uncaught TypeError: Cannot read property 'replace' of null
    at HTMLElement._tokenizeText (TextArea.js?afc7:330)
    at HTMLElement.onBeforeRendering (TextArea.js?afc7:264)
    at HTMLElement._render (UI5Element.js?64a9:425)
    at renderWebComponents (RenderScheduler.js?cdc5:80)
```

**Comment by fifoosid** [comment]
Hi @mehdijouan 

Could you provide reproducible example in [CodeSandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html)?
By null you probably mean empty string?

Best regards,
Filip

**Comment by mehdijouan** [comment]
I cannot reproduce it in codesanbox. As I user Vue.js (forgot to mention it) it may be due to binding issue.

I'll close the issue until I'm able to reproduce it.

Thanks,
Mehdi.
