### ISSUE TITLE
Process Flow Component

### ISSUE THREAD

**Issue by nyellapu** [SAP/ui5-webcomponents#1097]
There is no standard or equivalent component for Fiori Process Flow which gives a very good overview and status of the document flow. This is very much used in a lot of SAP Fiori standard apps and this features is dearly missed in the UI5 web components

https://sapui5.hana.ondemand.com/#/entity/sap.suite.ui.commons.ProcessFlow/sample/sap.suite.ui.commons.sample.ProcessFlow

**Comment by ilhan007** [comment]
Hello @nyellapu thanks for your request.

We discussed your request and unfortunately such kind of component is not in our road map. We focus on providing more standard components, the building blocks of an app.

Best,
ilhan
