### ISSUE TITLE
ui5-datepicker weeks rendering

### ISSUE THREAD

**Issue by fifoosid** [SAP/ui5-webcomponents#1100]
**To reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/DatePicker/
2. Select any date in December 2019 (the datepicker closes)
3. Open the datepicker again

**Expected behavior**
All weeks should have days.(Check week 2 of 2020)
Moreover, I am not sure whether any weeks that are out of the current month should be shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/16850339/71616115-4bdfe880-2bbd-11ea-976b-9cdfb81b2651.png)

**Comment by tsanislavgatev** [comment]
Fixed with the following PR: https://github.com/SAP/ui5-webcomponents/pull/2224
