### ISSUE TITLE
Add custom theming support

### ISSUE THREAD

**Issue by vladitasev** [SAP/ui5-webcomponents#1108]
Users should have an easy way to create and set a custom theme

**Comment by vladitasev** [comment]
The technical prerequisite: https://github.com/SAP/ui5-webcomponents/pull/1109

**Comment by vladitasev** [comment]
1) The user wants to create a custom theme for the existing `main` and `fiori` UI5 Web Components:

The easiest way would be to base the theme on an existing theme, in this example `sap_fiori_3` for the package-specific CSS Vars (which are mostly margins/paddings/borders) and only redefine the colors for the `theme-base` CSS Vars.

```
import { registerThemeProperties } from "@ui5/webcomponents-base/dist/AssetRegistry.js";
import fiori3main from "@ui5/webcomponents/dist/assets/generated/themes/sap_fiori_3/parameters-bundle.css.json";
```

and then:

```
registerThemeProperties("@ui5/webcomponents-main", "my_theme", fiori3main);
registerThemeProperties("@ui5/webcomponents-theme-base", "my_theme", ":root{ CUSTOM VALUES HERE}");
```

**Comment by codefactor** [comment]
@vladitasev ,

Is it necessary that we call `registerThemeProperties` synchronously?

In our case, we may have some JSONP or other API call to fetch the string `":root{ CSS VARS }"` from the server; however, it might also be possible for the initial payload HTML output to define this string inside the content of a <meta> tag so that the Javascript could read that string synchronously.

**Comment by vladitasev** [comment]
@codefactor ,

About having to call registerThemeProperties sync:
Yes, currently the idea is that you call this method in your app's bundle while configuring rollup/webpack to use a JSON plugin that will fetch the file over the network, if requested (as there might be many themes and at build time we don't know which one will be loaded, and we don't want them all inlined in the JS bundle). Your use case however seems to differ a bit in a sense that you only have one theme and this will be the only theme the customer will use.

If you did not call registerThemeProperties in advance, at boot the framework will default to the "sap_fiori_3" theme. The reason is, as you guessed, that we don't want to run the .define() methods of the web components unless a theme has been loaded. We can easily change that to better suit you, if you're fine with loading components first and applying the theme next. We can also have an API to tell the framework to use a specific `script` tag as a source of theme parameters, but we haven't had such a use case yet.
