### ISSUE TITLE
Timeline component background color defaults to parent

### ISSUE THREAD

**Issue by maitefdupont** [SAP/ui5-webcomponents#1118]
**Is your feature request related to a problem? Please describe.**
My application contains different panels with white background. In one of these panels I'd like to render a Timeline component, but it comes with a gray background and there's no other way to remove/replace but accessing the shadow dom manually.

**Describe the solution you'd like**
I'd like Timeline component to inherit it's parent background color, so it'll be 'transparent' or will allow me to pass it a different background color through style="".

**Describe alternatives you've considered**
First I tried passing a style property like so `style="background-color: white"`, which gets applied to the web component but not to the `.ui5-timeline-root` div, which already has it's own background color.
My workaround was to use `shadowRoot.querySelector('.ui5-timeline-root').style.backgroundColor` to change the background color.

**Additional context**
I'd suggest to update Timeline.css, replacing `background-color: var(--sapBackgroundColor);` with `background-color: inherit;`

**Comment by ilhan007** [comment]
Hello @maitefdupont 
It turns out that the timeline component should not set a background at all, so we decided to remove the background style. Now it will depend on the background of its parent as required by you.

Change: https://github.com/SAP/ui5-webcomponents/pull/1119

Thanks for reporting!
