### ISSUE TITLE
ui5-list: manual setting of select not working

### ISSUE THREAD

**Issue by tamiarah** [SAP/ui5-webcomponents#1150]
**Describe the bug**
Hi,
When you want to set the selected status of a list item manually to false, it is not getting deselected properly. The blue background disappears, but the checkbox is still checked. Furthermore I am not sure, if this item then still counts into the selectedItems property of the list. I tried this with setting the list item manually to selected = false, but I think it is also the other way around.

**To reproduce**
See attached example. Select three items. The third one should be set to selected = false, so the blue background should disappear and the checkbox should be empty. Furthermore this item should not count into the selectedItems of the list.

**Isolated example**
Example: 
https://codesandbox.io/s/ui5-webcomponents-i5wjl?fontsize=14&hidenavigation=1&theme=dark

**Expected behavior**
See above.

**Context**
- UI5 Web Components version: 1.0.0-rc.5
- OS/Platform: Mac OS

**Affected components** 
ui5-list with standardListItem

Thanks!
Christina

**Comment by MapTo0** [comment]
Hello @tamiarah 

Thanks for reporting!

We are currently looking into the issue!
As a workaround you can use requestAnimationFrame API: https://codesandbox.io/s/ui5-webcomponents-kv5ww

Regards,
Martin

**Comment by fifoosid** [comment]
Hello @tamiarah, 

This issue has been resolved. You can manually set the selection.

Best regards,
Filip
