### ISSUE TITLE
List component documentation is missing "itemPress"

### ISSUE THREAD

**Issue by danielliu1117** [SAP/ui5-webcomponents#1170]
List component documentation is missing "itemPress"

**Comment by ilhan007** [comment]
Hello @danielliu1117 

we removed the "itemPress" event as part of the API  and it has been replaced by "itemClick". 

However, the "itemPress" event is still being fired, but we will remove it at some point, so we recommend using the "itemClick" as described in the public API:
https://sap.github.io/ui5-webcomponents/playground/components/List/
