### ISSUE TITLE
ui5-li: There is no way to disable the checkbox of a list item, type="Inactive" probably should do that

### ISSUE THREAD

**Issue by codefactor** [SAP/ui5-webcomponents#1171]
**Describe the bug**
A StandardListItem, or `<ui5-li>` tag supports a checkbox, but there is no way to disable that checkbox. I thought setting `type="Inactive"` would do that, but it doesn't work, the checkbox is fully active.

**To reproduce**

```
<ui5-list mode="MultiSelect">
  <ui5-li type="Inactive">Disabled List Item</ui5-li>
  <ui5-li type="Active">Enabled List Item</ui5-li>
</ui5-list>
```

**Isolated example**
Codesandbox is not working for me right now, but you can easily copy paste the above HTML and try it yourself. Each list item shows a checkbox which can be checked or unchecked. However, the Disabled list item should not be allowed to change state.

**Expected behavior**
MultiSelect mode Lists which internally display checkboxes should be disabled whenever the list item has `type="Inactive"`; otherwise, there should be some way to do it.

NOTE: We can work around this to use a custom list item and then define a <ui5-checkbox> inside which we control the disabled property on that one.

**Screenshots**
![image](https://user-images.githubusercontent.com/730310/73504275-ae2a3580-4383-11ea-88ec-b5906682c3a7.png)

**Context**
- UI5 Web Components version: 1.0.0-rc.5

**Comment by codefactor** [comment]
The use case is, by the way, a list of checkboxes where the user is only allowed to select up to 4 checkboxes.

**Comment by ilhan007** [comment]
Hello @codefactor 
Thanks for reporting!

The inactive list item has no hover and pressed down effects, otherwise equal to the active list item.

We will consider your use case and get back to you.

Best regards,
ilhan

**Comment by ilhan007** [comment]
Hello @codefactor,

we decided to go for the behavior you expect - the inactive items would not change the selection any more (see the linked change)

Best,
ilhan
