### ISSUE TITLE
Wizard component

### ISSUE THREAD

**Issue by andresfelipe66** [SAP/ui5-webcomponents#1173]
**Is your feature request related to a problem? Please describe.**
It's no related to a problem, Its a request for new functionality in the framework.

**Describe the solution you'd like**
I'd like to have something similar to openui5 Wizard. https://openui5.hana.ondemand.com/api/sap.m.Wizard#overview

**Describe alternatives you've considered**
We are trying to implement other Wizards available on the Web (Bootstrap), but I'm trying to validate if it's possible to have something related to Fiori.

**Additional context**
We are implementing a solution with different Wizards (Process step by step) (In our architecture we are using Ui5 web components and Fiori fundamentals). And, off course we like to have the SAP Fiori User Experience.

**Comment by ilhan007** [comment]
Closed as it will be tracked with https://github.com/SAP/ui5-webcomponents/issues/2368
