### ISSUE TITLE
react-create-app and unit testing.

### ISSUE THREAD

**Issue by bahrus** [SAP/ui5-webcomponents#1176]
**Describe the documentation issue**

- [ ] Documentation is unclear
- [ ] Documentation is incorrect
- [x ] Documentation is missing
- [ ] Other

**Description of the issue**
I created a [stackoverflow question](https://stackoverflow.com/questions/60028689/how-do-i-import-es6-module-within-a-create-react-app-without-causing-tests-to-fa) for the same issue.

This issue isn't unique to ui-5 components, so really I'm fishing for the right answer wherever I can find it.  I think it's a fair question given your documentation.  I know you have a separate library, but I suspect the same issue will be there with Angular's unit testing, as it also relies on Jest.

I'm a big fan of your components, by the way.

**Comment by MarcusNotheis** [comment]
Hi, you can try to add the snippet from https://github.com/SAP/ui5-webcomponents-react/issues/150#issuecomment-581719278 to your package.json if you are using create-react-app. This will most likely solve the compiler error and you should be able to test snapshots at least

**Comment by bahrus** [comment]
Well, I tried following the advice and not seeing any change of behavior after adding:

```JSON
  "jest": {
    "transformIgnorePatterns": [
      "node_modules/(?!(@ui5|lit-html)).*\\.js$"
    ]
  }
```

to my package.json

I get the error when I run npm test or npm run test

**Comment by MarcusNotheis** [comment]
Are you running a "standard" create-react-app setup or did you eject the application? Could you please share the error you are facing?

**Comment by bahrus** [comment]
I used the standard [create-react-app](https://reactjs.org/docs/create-a-new-react-app.html)

I'm afraid I didn't detect that the error had changed in my previous comment, and it was now reporting that customElements was undefined.  After updating Jest, that issue is resolved (hooray!).  

It has now moved on to more specific UI5 errors:  
 

> You need to import @ui5/webcomponents/dist/json-imports/i18n.js with a build tool that supports JSON imports.

I suspect this probably has ready made solutions, but as it is no longer blocking what I was trying to do, nothing urgent.

I do still suggest documenting whatever steps are needed, but that's of course your call.

Thanks so much for your help, feel free to close.

**Comment by MarcusNotheis** [comment]
Hi @bahrus 

quick update on testing at is now possible thanks to the latest release of jsdom:
What you have to do is the following:
1. Install the `jest-environment-jsdom-sixteen` dependency to your project by running `npm install jest-environment-jsdom-sixteen --save-dev` or `yarn add jest-environment-jsdom-sixteen -D`
2. Add the `jest` snippet to your `package.json`:
   https://github.com/MarcusNotheis/test-setup-ui5-webcomponents-react/blob/master/package.json#L36-L40
3. Modify the `test` script by adding an additional parameter `--env jest-environment-jsdom-sixteen`
   https://github.com/MarcusNotheis/test-setup-ui5-webcomponents-react/blob/master/package.json#L18

Then you should be good to run tests. We will also add this to the documentation

**Comment by MarcusNotheis** [comment]
Hi @bahrus 
finally we have deployed the documentation on how to setup tests in create-react-app:
https://sap.github.io/ui5-webcomponents-react/?path=/docs/1-welcome-test-setup--page
