### ISSUE TITLE
Icons are still missing after following migration guide 1.0.0-rc.4 to 1.0.0-rc.5

### ISSUE THREAD

**Issue by maitefdupont** [SAP/ui5-webcomponents#1187]
**Describe the bug**
I have upgraded the ui5-webcomponents version I'm using to 1.0.0-rc.5 and followed the migration guide to adapt the icons. However, my application still doesn't show them when I load it (I'm using the react wrapper). 

Debugging the error, what I found is that two instances of SVGIconRegistry are loaded, one from @ui5/webcomponents-base/dist and other from @ui5/webcomponents-icons/node_modules/@ui5/webcomponents-base/dist. This causes all icons to be registered and then the registry is re-initialized and is empty when the icons are requested by the application.

**To reproduce**
I'm not sure exactly how to reproduce it, since I followed the instructions on the migration guide and it's still not working. 

**Expected behavior**
I'd like some help identifying a fix for this, or if this is an actual bug of ui5-webcomponents.

**Screenshots**
In my package.json, under dependencies I have this:
![image](https://user-images.githubusercontent.com/1753795/73946419-a9f69e80-48d4-11ea-9540-9dbc15f7430c.png)

Icon is missing:
![image](https://user-images.githubusercontent.com/1753795/73944104-c42e7d80-48d0-11ea-8463-8b5a70c1c4b4.png)

The project has two SVGIconRegistry files:
![image](https://user-images.githubusercontent.com/1753795/73944057-a9f49f80-48d0-11ea-82f5-d4e75175eb2a.png)

One file initializes the registry and is used for loading the icons
![image](https://user-images.githubusercontent.com/1753795/73944298-1d96ac80-48d1-11ea-97db-987b06a2c2b2.png)

The other file initializes another registry and is used for retrieving the icons
![image](https://user-images.githubusercontent.com/1753795/73944364-33a46d00-48d1-11ea-9e11-65cc827a03fc.png)

**Context**
- UI5 Web Components version: 1.0.0-rc.5
- OS/Platform: Windows
- Browser *(if relevant)*: Chrome

**Log output / Any errors** in the console
```
Required icon is not registered. You can either import the icon as a module in order to use it e.g. "@ui5/webcomponents/dist/icons/search.js", or setup a JSON build step and import "@ui5/webcomponents-icons/dist/json-imports/Icons.js".
```

**Comment by ilhan007** [comment]
Hello @maitefdupont 
Thanks for reporting.

Take a look of the following repo https://github.com/ilhan007/rollup-wc
The @ ui5/webcomponents and @ ui5/webcomponents-icons are declared as deps in the package.json (1.0.0-rc.5). The react wrapper is not used and this set up is working for me.

 Can you try it, so we can conclude that the combination with react wrapper leads to this?

- Clone
- npm install
- npm run start
- localhost:5000


Best,
ilhan

**Comment by maitefdupont** [comment]
Hi @ilhan007, yes, the presented playground works fine for me.

**Comment by ilhan007** [comment]
Hi @maitefdupont Do you have this application deployed to use it for debugging and producing a fix?

**Comment by maitefdupont** [comment]
@ilhan007 yes, it's deployed internally. Do you have any suggestions?

**Comment by ilhan007** [comment]
Hi @maitefdupont Yes, to give us a URL, so we can debug and provide a fix right away.

**Comment by maitefdupont** [comment]
@ilhan007 I'm not comfortable sharing this information here, so I have mailed you.

**Comment by maitefdupont** [comment]
@ilhan007 I am doing as you suggested, and removed node_modules and package-lock.json from the project. I am currently re-installing dependencies using yarn this time, so I can later use `yarn why`.

You are correct that we include the webcomponents-icons dependency twice (directly and through webcomponents-react), but that's because we need to import each icon we are going to use `import '@ui5/webcomponents-icons/dist/icons/resize';` from the *-icons package, and we can't do that if it's not a dependency of our project...

**Comment by ilhan007** [comment]
Hello Maite,
great, you can write me later if the re-installing the deps helped or still the having the issue.

Best,
ilhan

**Comment by maitefdupont** [comment]
Hi @ilhan007 I just now finished re-installing the dependencies, and apparently everything works as expected!
Thanks for your support!

**Comment by ilhan007** [comment]
@Maite, thanks for using the ui5 webcomponents, I looked you app and  it looks great,|
you can also try integrating the ui5-textarea instead of native one and the ui5-busyindicator.

**Comment by maitefdupont** [comment]
@ilhan007 we are using the Busy Indicator! The text area we are not because we need some specific features in it that we can't implement when using the ui5 version. In fact we are currently researching how to replace the native text area by a more flexible option so we can implement markup etc.

Thanks again!
