### ISSUE TITLE
ShadowRoot content disappearing after navigation

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents#1201]
**Describe the bug**
In some rare cases, the content of the `shadowRoot` **all** web components, e.g. a label text is disappearing after navigation.
The only way to solve that is to manually run `_updateShadowRoot()` on the element.

**To reproduce**
1. Setup a app with routing and 2 pages
2. Render a `<ui5-label>My Label Text</ui5-label> on both pages
3. Navigate a couple times between those pages. At some point in time the label will disappear, but if you look it up in the elements panel and run `_updateShadowRoot()` it will appear again.

This is quite hard to reproduce as it only occurs very seldom but every now and then it is appearing in our apps.

**Isolated example**
Please provide an isolated example if possibile, by forking [CodeSandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html)
**Link not working at the moment**

**Expected behavior**
Shadow root should always be renderd

**Screenshots**
--> Everything empty

**Context**
- UI5 Web Components version: 1.0.0-rc.5
- OS/Platform: Both Mac and Windows
- Browser *(if relevant)*: Chrome

**Affected components** *(if known)*
All UI5 Web Components. I made the example with the `label` but it applies to all components (and all components will crash at the same time)

**Comment by fifoosid** [comment]
Hi @MarcusNotheis 

Could you provide a github repository with the isolated example you have mentioned in order for us to debug it.(The code for the CodeSandbox sample has nothing to do with this bug as much as I can see)

Best regards,
Filip

**Comment by MarcusNotheis** [comment]
Hi @fifoosid 
actually I wasn't able to reproduce the issue right now, but I showed it to @MapTo0 when we were at DKOM. I granted him access to the application where it happens, so maybe you can look into that one?
In the meantime I'll continue to try to find a repro 😄

**Comment by MarcusNotheis** [comment]
Closing this for now until I can find a reproducible example
