### ISSUE TITLE
Popup.js onfocusin still existing

### ISSUE THREAD

**Issue by ignipae** [SAP/ui5-webcomponents#1211]
**Describe the bug**
I would like to report that in the popup.js file, still the onfocusin function is being used. In the past we had an initiative where all those "standard" functions have been replaced. This was necessary for rebundled applications like angular and so on. Due to the fact, that the dialog has this still inside, it cannot be used accordingly.

https://github.com/SAP/ui5-webcomponents/blob/e7e99ecd1443625723260676a76bf1a005f86a09/packages/main/src/Popup.js#L388

This seems to be valid for the latest release.

Thank you & best regards,
Julian

**Comment by vladitasev** [comment]
Will be fixed with: https://github.com/SAP/ui5-webcomponents/pull/1213

Thanks for reporting!

Regards,
Vladi
