### ISSUE TITLE
Unclear how to make themes avialable in Angular

### ISSUE THREAD

**Issue by Smux2** [SAP/ui5-webcomponents#1218]
Currently it is not clear for me how to make theming available for ui5 web components within my Angular application. Just importing the scripts with the theme configuration in the index.html does not work as well as just adding the theming parameter.
I tested and googled a little bit and stumbled upon this import:
`import '@ui5/webcomponents/dist/json-imports/Themes.js';`

With this import it works. 

Can you give me any advice what is the official supported way?

Thank you so much!

**Comment by MapTo0** [comment]
Hey @Smux 

Are you using the Fiori package?
If yes, you should import

`import '@ui5/webcomponents-fiori/dist/json-imports/Themes.js'; `

**Comment by Smux2** [comment]
Yes I am using the fiori package as well. Can you tell me what the difference is between those two files?

**Comment by MapTo0** [comment]
Each package contains its own css variables for different themes. Therefore you need to import such module for all the ui5 libraries you are using.

**Comment by Smux2** [comment]
Thansk!
Right now I am using the following packages:
`  "@ui5/webcomponents": "^1.0.0-rc.5",
        "@ui5/webcomponents-fiori": "^1.0.0-rc.5",
        "@ui5/webcomponents-icons": "^1.0.0-rc.5",`

Does this mean I need to apply 3 imports each for one package?

**Comment by MapTo0** [comment]
The icon package has no styling, it contains only svg definitions. Shouldn’t be required for it.

**Comment by Smux2** [comment]
Perfect, thanks for the information! :)
