### ISSUE TITLE
Don't shim jQuery

### ISSUE THREAD

**Issue by MWFIAE** [SAP/ui5-webcomponents#1232]
Hello everyone, 

**Describe the bug**
I encountered a problem while using the ui5webcomponents with vue and vuedraggable.
vuedraggable uses sortable.js which in turn uses the jQuery element selector and clone function if jQuery is detected, which aren't available as ui5webcomponents uses a own lightweight jQuery shim with only 3 Properties. 

**To reproduce**
1. Create a new vue project
2. Install ui5webcomponents
3. Install vuedraggable
4. Make a view with a ui5 webcomponent and vuedraggable and try to drag and drop something
5. Look at the error in the console

**Expected behavior**
There should be no jQuery shim with a reduced function set that isn't compatible with other libraries.

**Screenshots**
![image](https://user-images.githubusercontent.com/6072971/75024674-1effd180-549a-11ea-9c5a-a46f31ca5c18.png)

**Context**
- UI5 Web Components version: 1.0.0-rc.5
- Vue: 2.6.10
- vuedraggable: 2.32.2

**Affected components** 
(unknown, probably every component causes the error)

**Log output / Any errors** in the console
```
sortable.esm.js?aa47:601 Uncaught TypeError: $ is not a function
    at clone (sortable.esm.js?aa47:601)
    at Sortable._onDragStart (sortable.esm.js?aa47:1744)

```

**Comment by vladitasev** [comment]
Hello,

Fixed with: https://github.com/SAP/ui5-webcomponents/pull/1263

Regards,
Vladi
