### ISSUE TITLE
Dialog: Dialog component is not behaving as a dialog in Angular 8

### ISSUE THREAD

**Issue by sunnyyadav100** [SAP/ui5-webcomponents#1238]
**Describe the bug**
Dialog web component is not behaving as dialog in Angular 8.

**To reproduce**
Followed sample provided in https://sap.github.io/ui5-webcomponents/playground/components/Dialog/. 

<img width="204" alt="image" src="https://user-images.githubusercontent.com/9139037/75132065-8e283080-56fb-11ea-8b88-4519121b0688.png">

I tried to create a stackblitz but it is giving `HTMLElement constructor: 'new' is required`
https://stackblitz.com/edit/angular-w6yffp?file=src%2Fapp%2Fapp.component.html

This issue is specific to angular.

**Isolated example**
Please provide an isolated example if possibile, by forking [CodeSandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html)

**Expected behavior**

**Screenshots**

**Context**
- UI5 Web Components version
- OS/Platform: {...}
- Browser *(if relevant)*: {...}
- Other information: {...}

**Affected components** *(if known)*

**Log output / Any errors** in the console
```
{...}
```

**Comment by MapTo0** [comment]
Hey @sunnyyadav100 

Did you try running that locally? I tested using latest Angular version + CLI and everything was OK.

**Comment by sunnyyadav100** [comment]
Yes, screenshot from my local. 
Let me re-check, closing this issue.

**Comment by sunnyyadav100** [comment]
I tried with a new Angular 8.2.14 project and "@ui5/webcomponents": "^1.0.0-rc.5" dependency - 
Other components are working fine but the dialog component - 

<img width="509" alt="image" src="https://user-images.githubusercontent.com/9139037/75219041-bf6b3400-57c1-11ea-9a65-66f37ded4881.png">

<img width="629" alt="image" src="https://user-images.githubusercontent.com/9139037/75219186-1e30ad80-57c2-11ea-8097-865846227e49.png">
 
Do I need to add other ui5 webcomponent dependency?
