### ISSUE TITLE
Need theme sap_belize_hcw

### ISSUE THREAD

**Issue by alex-zhang** [SAP/ui5-webcomponents#1241]
Need theme sap_belize_hcw

Hi,  The A11 standard about hcw and hcb,  so we need a sap_belize_hcw theme  here.

**Comment by MapTo0** [comment]
Hello @alex-zhang 

We already have the `hcw` theme in the master code line you can check it [here](https://sap.github.io/ui5-webcomponents/master/playground/components/Button/?sap-ui-theme=sap_belize_hcw). Expect it publicly available in the next release.

**Comment by alex-zhang** [comment]
ok, nice job and thanks for ur response.
