### ISSUE TITLE
Feature Request: Slider Component

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents#1245]
**Is your feature request related to a problem? Please describe.**
The library does not have a slider implementation.

**Describe the solution you'd like**
I'd like for an implementation of Slider based on the [Fiori specifications](https://experience.sap.com/fiori-design-web/slider/).

**Describe alternatives you've considered**
Using an Input box. (not a visually appealing)

**Additional context**
None.

Original Issue: https://github.com/SAP/ui5-webcomponents-react/issues/322

**Comment by MarcusNotheis** [comment]
Sorry, I don't have the capacity to work on this as of now. As I didn't make much progress to be honest please feel tree to start a new implementation.

**Comment by vladitasev** [comment]
Requirements:
1. First of all, analyze and compare **Slider** and **RangeSlider**. Assess:
 - should it be one component
 - should it be 2 completely separate components
 - should RangeSlider extend Slider.
Ideally the solution with the least code that does the job should win.

2. Propose an API (properties/slots/events) for both **Slider** and **RangeSlider**. This should be complete API, including support for custom values. We must make sure that whichever way we decide to go, there will be a clear path to implement RangeSlider next.

3. Implement Slider with all features but custom values. However, it should be relatively easy to add custom values, so the API should be compatible (see point 2)
*Note:* Implement KBH and ACC too.

4. (Optional) Implement custom values, if there is enough capacity.

5. Next steps - RangeSlider (either as a new component or enhancement of this one, as decided in point 1).
