### ISSUE TITLE
Table: App Background Color applies to first row

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents#1273]
**Describe the bug**
When I set a background color on the app, this color is applied to (only) the first row of a table.

**To reproduce**
1. Render a Table
2. Set a background color the `body` tag

**Isolated example**
Please provide an isolated example if possibile, by forking [CodeSandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html)
https://codesandbox.io/s/loving-breeze-e3rv9

**Expected behavior**
1st TableRow should have the same color as other rows

**Screenshots**
![image](https://user-images.githubusercontent.com/8775211/76318906-acd31d80-62de-11ea-8134-de0197521455.png)

**Context**
- UI5 Web Components version: 1.0.0-rc.5
- OS/Platform: MacOS
- Browser *(if relevant)*: Chrome 80

**Affected components** *(if known)*
Table
TableRow

Original Issue:
https://github.com/SAP/ui5-webcomponents-react/issues/337

**Comment by ilhan007** [comment]
Hello @Marcus Can you try it with the @next version, I think we fixed that some time ago.

**Comment by ilhan007** [comment]
https://github.com/SAP/ui5-webcomponents/pull/1156

**Comment by MarcusNotheis** [comment]
hi @ilhan007 ,
the next version is working fine, thanks.
Are there any plans when it will be released?

**Comment by ilhan007** [comment]
Hi @MarcusNotheis,
we did not plan it as specific date or something. 

I think we will release until the end of the month, but when we plan it, I will let you know.
Best,
ilhan
