### ISSUE TITLE
UI5 Table sorting

### ISSUE THREAD

**Issue by pthd** [SAP/ui5-webcomponents#1290]
**Is your feature request related to a problem? Please describe.**
Current SAPUI5 table supports sorting.
In order to migrate a current project from ui5 to web comp it would be necessary to get sorting on columns as well

**Describe the solution you'd like**
Same sorting capabilities as ui5 is providing it

Is this somehow achievable already?

**Comment by vladitasev** [comment]
Hello @pthd 

Filtering, sorting, etc... are characteristics of data-driven tables. The one we currently provide is a general-purpose table, not a grid table, therefore such features don't make sense for it.

It's up to the application to implement that, if necessary. You could add sort buttons to the headers of the columns and reorder the rows, as you would do with an HTML table.

Regarding our stance on having a grid table, please see the explanation in this issue:
https://github.com/SAP/ui5-webcomponents/issues/1654

Regards,
Vladi
