### ISSUE TITLE
MultiInput

### ISSUE THREAD

**Issue by softshipper** [SAP/ui5-webcomponents#1295]
Hi all 

Any Plan to provide MultiInput like https://openui5.hana.ondemand.com/entity/sap.m.MultiInput?  

Thanks

**Comment by sunnyyadav100** [comment]
We are also looking for MultiInput component focusing on 'MultiInput with Value Help' https://openui5.hana.ondemand.com/entity/sap.m.MultiInput/sample/sap.m.sample.MultiInputValueHelp as per this feature request.

**Comment by deathctalker** [comment]
Hi,
When to expect implementation? How to increase priority?

**Comment by ilhan007** [comment]
Hello, good news, the component is currently under development.
You can track the issue: https://github.com/SAP/ui5-webcomponents/issues/1852

BR,
ilhan
