### ISSUE TITLE
Localization - Package unavailable in NPM

### ISSUE THREAD

**Issue by nitish-mehta** [SAP/ui5-webcomponents#1302]
**Describe the documentation issue**

- [ ] Documentation is unclear
- [X ] Documentation is incorrect
- [ ] Documentation is missing
- [ ] Other

**Description of the issue**

Link to Localization NPM package (https://www.npmjs.com/package/@ui5/webcomponents-localization) is either incorrectly maintained in README or the package is unavailable in npm

![image](https://user-images.githubusercontent.com/15953522/76708969-0db88680-6721-11ea-8adb-e60f31face49.png)

**Comment by ilhan007** [comment]
Hello @nitish-mehtat 

the localization module is not released yet, sorry for the confusion. It will be part of the next rc.6 version and we plan to make it available in 2 weeks.

Best,
ilhan

**Comment by nitish-mehta** [comment]
> Hello @nitish-mehtat
> 
> the localization package is not released yet, sorry for the confusion. It will be part of the next rc.6 version and we plan to make it available in 2 weeks.
> 
> Best,
> ilhan

Thanks @ilhan007 for the swift response. Will look forward to that  👍

**Comment by ilhan007** [comment]
heHello @nitish-mehta version RC 6 WebComponents has been released:

Localization package is available
https://www.npmjs.com/package/@ui5/webcomponents-localization
