### ISSUE TITLE
about ui5-busyindicator's size when set  it's height to 100%

### ISSUE THREAD

**Issue by alex-zhang** [SAP/ui5-webcomponents#1305]
i need to add a loading status for page loading.

ui5-busyindicator is an element of page(height is 100%), it also has height 100%, but the busyindicator can't cover the page height size, it's only cover the size that children's measure size.

or any other solutions?

**Comment by ilhan007** [comment]
Can you send us URL to explore the issue or at least code snippet we can take a look?

**Comment by alex-zhang** [comment]
thanks for your reply.


```javascript
<div style="height=100%">
  <ui5-busyindicator active style="height=100%">
           <p>Text</p>
 </ui5-busyindicator>
</div>
```

`busyindicator` should cover the container size, not the measured child's size.

**Comment by ilhan007** [comment]
Currently the indicator shows over its content. Could you try the following:

```html
<div style="height:100%;">
	<p>Text</p>
</div>
<ui5-busyindicator active class="busy" size="Large"></ui5-busyindicator>
```

```css
.busy {
	position: fixed;
	left: 0;
	right: 0;
	top: 0;
	bottom: 0;
}
```

**Comment by alex-zhang** [comment]
ok, thanks again.

BTW, i also can use the addCustomCSS function.

`addCustomCSS(
  'ui5-busyindicator',
  `
  :host(.${blockCssName}__loading) .ui5-busyindicator-root {
    width: 100%;
    height: 100%;
  }
  `
);`

have a nice day~

**Comment by ilhan007** [comment]
Welcome,

just a note about the "addCustomCSS", you can use it, but keep in mind that it might be removed at some point, that`s why we don`t encourage using it if possible.

Best,
ilhan
