### ISSUE TITLE
Full text does not get showed

### ISSUE THREAD

**Issue by softshipper** [SAP/ui5-webcomponents#1310]
Hi all 
I am using UI5 webcomponents as follows: 

```
<ui5-label id="myLabel" for="myInput" required show-colon>First name</ui5-label>
<ui5-input id="myInput" aria-required="true" aria-labelledby="myLabel" placeholder="Enter your name"></ui5-input>
<ui5-label id="myLabel2" for="myDP" required show-colon>Date of birth</ui5-label>
<ui5-datepicker id="myDP" aria-labelledby="myLabel2" aria-required="true"></ui5-datepicker>
<ui5-label id="myLabel3" for="mySelect" required show-colon>Job</ui5-label>
<ui5-select id="mySelect" aria-required="true" aria-labelledby="myLabel3">
    <ui5-option>Manager</ui5-option>
    <ui5-option>Sales</ui5-option>
    <ui5-option selected>Developer</ui5-option>
</ui5-select>
<ui5-label id="myLabel4" for="myTextArea" required show-colon>Description label test</ui5-label>
<ui5-textarea id="myTextArea" aria-labelledby="myLabel4" aria-required="true" placeholder="Type as much text as you wish"></ui5-textarea>
<ui5-label for="myRB" required show-colon>Gender</ui5-label>
<ui5-radiobutton id="myRB" group="a" text="Choice 1"></ui5-radiobutton>
<ui5-radiobutton id="myRB2" group="a" selected text="Choice 2"></ui5-radiobutton>
<ui5-label for="myCB" required show-colon>Accept terms of use</ui5-label>
<ui5-checkbox id="myCB"></ui5-checkbox>
```  
The output is: 
![Screenshot from 2020-03-18 07-36-58](https://user-images.githubusercontent.com/56756949/76932494-56bc3680-68eb-11ea-922d-5feacfa738c0.png)

Why it does not show the full label text?  
Why can the radio button be marked twice?  

The packages, that I have imported are: 

```
import '@ui5/webcomponents/dist/Button';
import '@ui5/webcomponents/dist/Input';
import '@ui5/webcomponents/dist/Label';
import '@ui5/webcomponents/dist/Select';
import '@ui5/webcomponents/dist/Option';
import '@ui5/webcomponents/dist/DatePicker';
import '@ui5/webcomponents/dist/TextArea';
import '@ui5/webcomponents/dist/RadioButton';
import '@ui5/webcomponents/dist/CheckBox';
```
What am I doing wrong?  

Thanks

**Comment by ilhan007** [comment]
Hello @softshipper 

What is the version of ui5 webcomponents in use?

The RadioButton has property "name", not "group" at least with the latest implementation.

Best,
ilhan

**Comment by ilhan007** [comment]
Actually you can see the same sample in:
https://sap.github.io/ui5-webcomponents/master/playground/components/Label/

Notice the "master" part in the URL, this is the master version of the playground
and both the issues you described are fixed.

Best,
ilhan

**Comment by softshipper** [comment]
Thanks for fast response. 
I am using "@ui5/webcomponents": "^1.0.0-rc.5". Look at the simple example: 

```
<ui5-label required>Required Label</ui5-label>
<br/>
<ui5-label id="myLabel" for="myInput" required show-colon>First name</ui5-label>
<ui5-input id="myInput" aria-required="true" aria-labelledby="myLabel" placeholder="Enter your name"></ui5-input>
<br/>
```

The output: 

![Screenshot from 2020-03-18 08-14-00](https://user-images.githubusercontent.com/56756949/76934990-891c6280-68f0-11ea-996a-266d193ad3bb.png)

As you can see, the label is not marked as required. 

Why? 

Thanks

**Comment by ilhan007** [comment]
Because there was a bug in rc.5 ,that has been fixed later.
