### ISSUE TITLE
ui5-input suggestions do not properly support GroupHeaderListItem

### ISSUE THREAD

**Issue by codefactor** [SAP/ui5-webcomponents#1313]
**Describe the bug**
The BizX shellbar needs to show multiple types of search results separated by GroupHeaderListItems. In the release candidate version, those are supported; however, in 0.0.0-c6d8872f3, they are not supported.

**To reproduce**
Add <ui5-li> and <ui5-li-groupheader> to the <ui5-input> as the "searchField" slot of the <ui5-shellbar>. The group headers appear as normal items and are not styled any differently that other items.

**Isolated example**
https://codesandbox.io/s/ui5-webcomponents-cpw59
I wasn't able to get this to work right - maybe you can fix it.

**Expected behavior**
The <ui5-li-groupheader> items should be styled like a group header item, and not a standard <ui5-li>

**Screenshots**
![image](https://user-images.githubusercontent.com/730310/76990490-431dc980-6905-11ea-831b-b2ef834d9044.png)

The screenshot shows 2 types of search results: Actions, and People - the "Actions" and "People" tems should be showing up as group header items.

**Context**
- UI5 Web Components version
- OS/Platform: {...}
- Browser *(if relevant)*: {...}
- Other information: {...}

**Affected components** *(if known)*

**Log output / Any errors** in the console
```
{...}
```

**Comment by ilhan007** [comment]
Hello @codefactor 

After we release "next" or "rc.6", you should import and use the `@ui5/webcomponents/dist/SuggestionItem.js` module and use it in the following way:

```html
<ui5-input id="myInput2" show-suggestions >
        <ui5-suggestion-item group text="group 1"></ui5-suggestion-item>
	<ui5-suggestion-item text="Cozy"></ui5-suggestion-item>
	<ui5-suggestion-item text="Compact"></ui5-suggestion-item>
	<ui5-suggestion-item text="Condensed"></ui5-suggestion-item>
</ui5-input>
```

To have a group item, you need to set the "group" property.
