### ISSUE TITLE
ui5-input in the ui5-shellbar, pressing "tab" key causes a fatal exception

### ISSUE THREAD

**Issue by codefactor** [SAP/ui5-webcomponents#1314]
**Describe the bug**
Using ui5-shellbar, click on the search button and then press "tab" key - this throws a fatal uncaught exception (which in react based pages in dev mode causes the page to disappear to show the error).

**To reproduce**
1. use 0.0.0-c6d8872f3 of ui5-webcomponents-fiori
2. have a ui5-shellbar with a ui5-input slotted inside
3. click the search button, focus is on the input, press "tab" key
4. see the error in the logs

**Isolated example**
https://codesandbox.io/s/ui5-webcomponents-cpw59
Couldn't get it to work

**Expected behavior**
Pressing tab key should just move focus to the body of the page.

**Screenshots**

**Context**
- UI5 Web Components version
- OS/Platform: {...}
- Browser *(if relevant)*: {...}
- Other information: {...}

**Affected components** *(if known)*

ui5-shellbar, ui5-input

**Log output / Any errors** in the console
```
Input.js:471 Uncaught TypeError: Cannot read property 'contains' of null
    at HTMLElement._onfocusout (Input.js:471)
    at EventPart.handleEvent (parts.ts:505)
    at HTMLDivElement.EventPart.__boundHandleEvent (parts.ts:463)
```

**Comment by fifoosid** [comment]
Hi @codefactor 

This issue is already resolved in master branch with my latest [PR](https://github.com/SAP/ui5-webcomponents/pull/1272/files#diff-65742b68484e472412ccef21a5128f98R471)

Best regards,
Filip
