### ISSUE TITLE
MultiComboBox: Provide API to remove all selections

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents#1326]
Hi colleagues,

we received the following issue in the React-wrapper project (original author @gabrielrossetto):

**Describe the bug**
I have a `MultiComboBox`, populated with `StandardListItem`. Since this component is a filter, I want to clear the selection always when any button is triggered but the component does provide nothing like: `clearSelection()` or `removeAllSelectedItems()` (as described in MultiComboBox UI5 documentation https://sapui5.hana.ondemand.com/#/api/sap.m.MultiComboBox%23methods/Summary)

**To Reproduce**
1. Create a `MultiComboBox` (create an id for this component to access by DOM after) and populate it with some `StandardListItem`;
2. Create any component in order to clear the `MultiComboBox` selection. Suggestion: `Button`.
3. Create `onClick()` for the component above;
4. On the function created, try to set the selected items in order the clean the component.

**Expected behavior**
It should have an option to clear the selection.

**Screenshots**
Not applicable.

**UI5 Web Components for React Information**
@ui5/webcomponents-react version: 0.9.0-rc.1
@ui5/webcomponents version: 1.0.0-rc.5

**Additional context**
Suggested code to test:

```
  const onCleanFilterClick = () => {
    const test = document.getElementById('companyIndustryFilterId');
    //test.removeAllSelectedItems()
  };
  return (
    <>
        <Button onClick={() => onCleanFilterClick()}>Clear MultiComboBox selection</Button>
        <MultiComboBox id="companyIndustryFilterId">
              <StandardListItem id="1" key="1">1</StandardListItem>
              <StandardListItem id="2" key="2">2</StandardListItem>
              <StandardListItem id="3" key="3">3</StandardListItem>
        </MultiComboBox>
    </>
  );
```

Original Issue: https://github.com/SAP/ui5-webcomponents-react/issues/368

**Comment by ilhan007** [comment]
Hello @gabrielrossetto

is this good enough for you:

```js
const onCleanFilterClick = () => {
    const test = document.getElementById('companyIndustryFilterId');
 
     Array.from(test.children).forEach((item) => {
         item.selected = false;
     });
};
```

**Comment by MapTo0** [comment]
In addition of @ilhan007 

IMO, I would expect that the selection will always be saved in your store (being it a redux or whatever) and you don't really want to do any manual updates of the components / DOM during user interaction. In case you do - you should again sync the DOM and the store in order to prevent any unexpected errors, right?

**Comment by ilhan007** [comment]
Hello @gabrielrossetto

Closing as no response and solution provided

```js
const onCleanFilterClick = () => {
    const test = document.getElementById('companyIndustryFilterId');
 
     Array.from(test.children).forEach((item) => {
         item.selected = false;
     });
};
```

**Comment by gabrielrossetto** [comment]
Hello,

Thanks, it worked for me!
