### ISSUE TITLE
Button: Control Icon Size

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents#1327]
HI colleagues - we received the following issue on the React wrapper:

Original Issue: https://github.com/SAP/ui5-webcomponents-react/issues/365
Original Author: @isaqueha

**Description**
I would like to control the size of an Icon inside a Button.

**Is your feature request related to a problem? Please describe.**
I was developing a feature where a Button with a big Icon was needed, but there is no simple way to achieve that.

**Describe the solution you'd like**
I would like a property inside the Button component to control the Icon size through CSS or so.

**Describe alternatives you've considered**
I tried to alter several different CSS properties in the Button component so the Icon would be affected. No result so far.
Some ideas:
- https://sapui5.hana.ondemand.com/#/api/sap.ui.core.Icon
- https://sap.github.io/ui5-webcomponents/playground/components/Icon (see Customized Icons)

**Additional context**
As seen in the screenshot below, I wanted to make the `sys-cancel` Icon inside the Button as big as the `search` Icon in the left of the Bar:

![image](https://user-images.githubusercontent.com/13629975/77176503-f53ec800-6aa2-11ea-8f65-902cc9f02668.png)

The `search` Icon size was controlled with the `width: 1.5rem` CSS property.

**Comment by ilhan007** [comment]
Hello @isaqueha,

is that good enough for you:

```html
<ui5-button design=“Negative” style=“height: 3rem”>
    <ui5-icon style=“color:inherit; width: 3rem; height:3rem” name=“add”></ui5-icon>
</ui5-button>
```

<img width="128" alt="Screenshot 2020-03-23 at 3 14 30 PM" src="https://user-images.githubusercontent.com/15702139/77320333-098bfa80-6d19-11ea-9a2f-82db494fe4d1.png">


Best,
ilhan

**Comment by isaqueha** [comment]
Hi @ilhan007,

This is a good solution, yes, but not applicable in my case.
The thing is that I need this exact same functionality, but in the `ui5-webcomponents-react` library.
Today, the Icon there is controlled by a simple `string`, and I don't have access to the inner Icon Component.

Please check this in the `ui5-webcomponents-react` sandbox:
https://sap.github.io/ui5-webcomponents-react/?path=/docs/4-ui5-web-components-button--generated-default-story

Hi @MarcusNotheis, maybe we need to change this issue back to https://github.com/SAP/ui5-webcomponents-react/issues/365, right?
This way, we will have the React Library implementing the correct functionality of the base `ui5-webcomponents` library.

**Comment by ilhan007** [comment]
Hello @MarcusNotheis,
We don't prevent it, it looks strange, so I can't say that this is something recommended, but rather a workaround, until we find a better way of styling the icon. I would say don't update your typings.
We have a slot, called "avatar" in the Card to display image or icon (in the master version at least).

**Comment by isaqueha** [comment]
Thanks, @MarcusNotheis, @ilhan007 
Your suggestions worked using the React Components!

Code:

![image](https://user-images.githubusercontent.com/13629975/77357974-cdac6180-6d27-11ea-9dd3-fe4980c59d51.png)

Design:

![image](https://user-images.githubusercontent.com/13629975/77358009-e452b880-6d27-11ea-905d-3ab355ffb860.png)

@MarcusNotheis, will this "implicit Component" approach work similarly in other React Components when needed?

This workaround is enough for us right now 😄
Unless you want to keep it open for the feature suggestion, I believe we can close this issue.

**Comment by MarcusNotheis** [comment]
Hi @isaqueha, I think it should work with all components that are accepting the `children` prop. But whenever the typing says it's a string or another primitive value it has to be handled with care 😄 
I would rather recommend this approach as "last resort" in case nothing else helps.
