### ISSUE TITLE
The BusyIndicator looks blurry

### ISSUE THREAD

**Issue by akirichev** [SAP/ui5-webcomponents#1337]
**Describe the bug**
The animation of the BusyIndicator make the dots to look blurry when scaled.

**To reproduce**
1. Go to 'https://sap.github.io/ui5-webcomponents/playground/components/BusyIndicator/

**Expected behavior**
The circles should look crisp and sharp

**Screenshots**
![Screenshot 2020-03-24 at 9 46 24](https://user-images.githubusercontent.com/606333/77401006-cf703680-6db4-11ea-971a-731350209dca.png)

**Context**
- UI5 Web Components version
- OS/Platform: MacOS

**Affected components** *(if known)*
ui5-busyindicator

**Comment by ilhan007** [comment]
Do you experience the same here:
https://sap.github.io/ui5-webcomponents/master/playground/components/BusyIndicator/

*This is the master version, note the "master" word in the url.

**Comment by akirichev** [comment]
Yes, it is still blurry in the Master branch.

![Screenshot 2020-03-24 at 10 27 00](https://user-images.githubusercontent.com/606333/77404191-0ac13400-6dba-11ea-9155-7cf1809139b3.png)

**Comment by MapTo0** [comment]
Looks good on my side.

We can switch to svgs if needed but I don't really see any problems.

![image](https://user-images.githubusercontent.com/5821279/77405263-92f40900-6dbb-11ea-9eb6-7cc9c7cf99d0.png)

**Comment by akirichev** [comment]
It seems that this is a browser related, because I just tested it in Chrome and it actually looks fine. Initially I was testing in Safari and I guess you also see the blurry circles in the screenshot.

**Comment by MapTo0** [comment]
Okay, I see the issue with Safari :D
