### ISSUE TITLE
Single Combo Box / Select With Text Input

### ISSUE THREAD

**Issue by m1trix** [SAP/ui5-webcomponents#1348]
**Is your feature request related to a problem? Please describe.**
We want to have the combo box experience everywhere in the UI. The multi combo box is great but it allows the selection of multiple values. For some use-cases, we need to limit the selection to just a single value.

**Describe the solution you'd like**
We need either one of:
* Single Combo Box - combo box where you are limited to a single value;
* Select With Text Input - a normal select element but with the possibility to write text to narrow down the options.

**Describe alternatives you've considered**
One alternative would be to do something custom on top of the multi combo box to disallow multiple values but we prefer an official component.

Another alternative is the input with suggestions - it's great if you know what to search for, but we still need to have the option to list all options.

**Additional context**
It's up to you to choose the best look & feel but I think that this needs to look like the multi combo box.

**Comment by ilhan007** [comment]
Can you try the ComboBox we are about to release as rc.6, it is currently available in our "next" tag versions, that includes the latest development:

https://sap.github.io/ui5-webcomponents/master/playground/components/ComboBox/

*Note: the "master" word in the URL.

**Comment by m1trix** [comment]
This seems is exactly what we need. We will try it out.

Thank you!
