### ISSUE TITLE
ui5-select success state incorrect

### ISSUE THREAD

**Issue by MapTo0** [SAP/ui5-webcomponents#1356]
Select state of ui5-select has a wrong border width 

https://sap.github.io/ui5-webcomponents/master/playground/components/Select/

OpenUI5: https://openui5nightly.hana.ondemand.com/entity/sap.m.Select/sample/sap.m.sample.SelectValueState

**Comment by ilhan007** [comment]
Actually, the Success State border is thinner than the borders of other semantic states. A Success State is just a positive reinforcement, demanding less action from a customer than e.g., a Warning State. It is, therefore, also made visually less prominent than other semantic states.
