### ISSUE TITLE
ui5-button: falsy text value doesn't update in React

### ISSUE THREAD

**Issue by ee92** [SAP/ui5-webcomponents#1377]
**Describe the bug**
If the ui5-button is initially created with a falsy value such as an empty string, it does not respect React updating that value. This was previously not an issue.

**To reproduce**
1. Go to https://codesandbox.io/s/dazzling-wiles-5kul8.
2. Click 'update the buttons above' button.
3. Notice the html button text is updated, while the ui5-button text is not updated.
4. Replace `initialText` with a non-empty string and refresh the sandbox browser.
5. Click 'update the buttons above' button.
6. Notice both html and ui5 buttons update properly.
(next steps to prove it works in latest release)
7. Replace `initialText` with an empty string again.
8. Switch ui5-wecomponents version to 0.0.0-rc.5 and refresh the sandbox browser.
9. Click 'update the buttons above' button.
10. Notice both html and ui5 buttons update properly.

**Isolated example**
https://codesandbox.io/s/dazzling-wiles-5kul8

**Expected behavior**
The ui5-button should behave the same as an html button. (And the same as it does in latest release)

**Context**
- Framework: React
- UI5 Web Components version:  0.0.0-2567beaa3 (current @next version)
- OS/Platform: Mac/Windows
- Browser: Chrome/Firefox

**Affected components** 
ui5-button

**Comment by ilhan007** [comment]
Hello @ee92 

can you try it with rc.6, we have a release from today,

we addressed the issue just before releasing.
