### ISSUE TITLE
ui5-datepicker: Cannot specify valueStateMessage in Datepicker

### ISSUE THREAD

**Issue by zhangliangyi** [SAP/ui5-webcomponents#1385]
Hi colleague,

I am from Web Experience team in SAP Successfactors.

While applying the new rc6 version to the project, I found the valueStateMessage in Datepicker cannot be specified. It seems to use the default valueStateMessage from the inner Input component when the valueState is set to Error and no slot is provided for the modification.

Adding a `valueStateMessage` slot in Datepicker just the same as Input would be perfect.

So far I have not found any workaround for this issue.

Thanks

**Comment by fifoosid** [comment]
Implemented
