### ISSUE TITLE
UI5 Icons automatic download only when used

### ISSUE THREAD

**Issue by boyetp123** [SAP/ui5-webcomponents#1389]
**Is your feature request related to a problem? Please describe.**
We are trying to improve load performance for our page, 
we are currently importing  @ui5/webcomponents-icons/dist/json-imports/Icons which downloads all the Icons, most of it are not use
To mitigate the issue,  we have to import individual Icons that we only use

**Describe the solution you'd like**
Maybe there way to do this so that we don't have to specify each icon we need, that will only download the Icons the we use, If not, Can you add this feature for the future release.

**Comment by MapTo0** [comment]
The only way I see this to be implemented is to do a single request for each icon when used, which would have a bad performance as well.

We totally agree that no one needs all the icons, therefore we recommend using single imports. Is there any other icon library you have been using and behaves like that?

**Comment by MapTo0** [comment]
I am closing this as I don't really see any possible action on our side. With single imports for icons you can optimize your bundle performance quite good.

Regards,
Martin
