### ISSUE TITLE
Inject All Theme Designer Parameters

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents#1394]
**Is your feature request related to a problem? Please describe.**
The UI5 Web Components for React wrapper is relying on the CSS Variables from SAP Theme Designer.
Unfortunately, UI5 Web Components is not injecting all parameters which leads to missing colors on our side.

**Describe the solution you'd like**
Inject all Theme Designer Parameters (or even rely on the `@sap-theming/theming-base-content` package).

**Describe alternatives you've considered**
We could inject the missing variables ourselves but that feels hacky and somehow not determinisic.

**Additional context**
I've created a CodeSandBox showing which parameters are present, missing and have an unexpected value.
https://codesandbox.io/s/black-pond-6886p

**Comment by alex-zhang** [comment]
same issue.

**Comment by ilhan007** [comment]
Hello @alex-zhang  The names are the same, but we provide a subset (just the ones we use) of all parameters that the theme designer can generate and that's why you might not find some. 
You can share one parameter you are missing and I can check why you can't find it.

**Comment by alex-zhang** [comment]
thanks for ur reply.

eg. sapUiFontHeader1Size

@MarcusNotheis  also give the example https://codesandbox.io/s/black-pond-6886p

**Comment by MapTo0** [comment]
I guess we can close one of these as duplicate? https://github.com/SAP/ui5-webcomponents/issues/1396

**Comment by ilhan007** [comment]
> thanks for ur reply.
> 
> eg. sapUiFontHeader1Size
> 
> @MarcusNotheis also give the example https://codesandbox.io/s/black-pond-6886p

Note: sapUiFontHeader1Size is not a base parameter, the ThemeDesigner do not provide  any "sapUi" prefix parameters, the base parameter is "sapFontHeader1Size" and this is what will be available.
