### ISSUE TITLE
Use all SAP CSS Variables

### ISSUE THREAD

**Issue by vladitasev** [SAP/ui5-webcomponents#1396]
1. Find out which of our variables are not present in https://github.com/SAP/theming-base-content
and refactor them.

2. Use https://github.com/SAP/theming-base-content as node_modules/ dependency to generate CSS files

3. Assess benefits/drawbacks

**Comment by MarcusNotheis** [comment]
List of used variables which are not present in Theme Designer:
|UI5 Web Components| Theme Designer Replacement|
|---|---|
|`sapFontMediumSize `|`sapFontSize`|

feel free to edit and expand this list 😄
