### ISSUE TITLE
Theming with React with RC.6 is not possible

### ISSUE THREAD

**Issue by DLaskov** [SAP/ui5-webcomponents#1403]
There's no clear documentation about theming in React application.
Also from RC.6 onwards themeing stopped working for me.

Is this the right way to set a theme?

```
import {setTheme} from '@ui5/webcomponents-base/dist/config/Theme.js';

setTheme(themeName)
```

On RC.5 it's working fine, but with RC.6 suddenly it stopped working... 

I've tried to do `import '@ui5/webcomponents/dist/json-imports/Themes.js';` but still no luck.

**Comment by ilhan007** [comment]
Try

```js
import "@ui5/webcomponents/dist/Assets.js";
import "@ui5/webcomponents-fiori/dist/Assets.js"; //  if you use @ui5/webcomponents-fiori
```
and then

```js
import { setTheme } from "@ui5/webcomponents-base/dist/config/Theme.js";
setTheme("sap_belize_hcb");
```

**Comment by Thanh-Bao** [comment]
thanks
