### ISSUE TITLE
ui5-li, ui5-li-custom: adding a "disabled" property/attribute

### ISSUE THREAD

**Issue by agauyeung** [SAP/ui5-webcomponents#1405]
**Is your feature request related to a problem? Please describe.**
There is no way to prevent `ui5-li` and `ui5-li-custom` from being select-able in a `ui5-list`.

**Describe the solution you'd like**
Add a disabled property/attribute to `ui5-li` and `ui5-li-custom` to prevent them from being selected in a `ui5-list`. (SingleSelect and MultiSelect)

**Describe alternatives you've considered**
I've considered just not including a list item that I don't want to be select-able, but it is still useful to have the list item visible even if not select-able.

**Comment by ilhan007** [comment]
Try setting type="Inactive"

```html
<ui5-li type="Inactive"
```

**Comment by agauyeung** [comment]
> 
> 
> Hello @agauyeung
> 
> Try setting type="Inactive":
> 
> ```
> <ui5-li type="Inactive"></ui5-li>
> ```

Hi @ilhan007 
Unfortunately, I have tried this but it does not work that way. "Inactive" only causes the list item to not respond to hover.
Please see the example below:
https://codesandbox.io/s/ui5-webcomponents-dwhw1

Please reopen this ticket if possible.

**Comment by ilhan007** [comment]
Hello @agauyeung

Can you use rc.6?

**Comment by agauyeung** [comment]
Hi @ilhan007 
Thank you! I am using the following ui5-webcomponent dependencies in my local but can't seem to get it `Inactive` working. Which other packages do I need to upgrade?

    "@ui5/webcomponents": "^1.0.0-rc.6",
    "@ui5/webcomponents-base": "^0.19.0",
    "@ui5/webcomponents-icons": "^1.0.0-rc.6",
    "@ui5/webcomponents-theme-base": "^1.0.0-rc.6",
    "@ui5/webcomponents-tools": "^1.0.0-rc.5",
    "@ui5/webcomponents-fiori": "0.0.0-aadaf0b2a",
