### ISSUE TITLE
ui5-button with overflow icon vertical align is not middle

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents#1406]
**Describe the bug**
ui5-button with overflow icon. The vertical-align of the overflow icon is bottom, not the middle.

**To reproduce**
`<ui5-button icon="overflow"></ui5-button>`

**Expected behavior**
The vertical-align of the icon should be middle.

**Screenshots**
![ui5-button-icon-vertical-align](https://user-images.githubusercontent.com/13098801/78093027-e097f380-7403-11ea-8d6a-e6553d194ace.png)

**Context**
- UI5 Web Components version 1.0.0 rc6
- OS/Platform: {macos}
- Browser *(if relevant)*: {chrome/edge}
- Other information: {...}

**Comment by vladitasev** [comment]
Fixed with: https://github.com/SAP/ui5-webcomponents/pull/1777
