### ISSUE TITLE
Popovers do not open when button/link is not entire on the screen

### ISSUE THREAD

**Issue by leoratzlaff** [SAP/ui5-webcomponents#1416]
**Describe the bug**
Popovers do not open when the button/link is not entirely on the screen. We identified this issue during an automated test where the page, after a small scroll, tried to access the user menu at the ShellBar clicking on the avatar and the popover did not open.

**To reproduce**
1. Go to 'https://sap.github.io/ui5-webcomponents-react/?path=/docs/4-ui5-web-components-popover--default-story';
2. Scroll until some part of the button 'Open Popover' is no longer available at the screen;
3. Click on it. (The popover won't open)

**Expected behavior**
The popover should open and show its options.

**Screenshots**
https://imgur.com/a/uRPSU2T

**Context**
- UI5 Web Components version: 1.0
- OS/Platform: Any
- Browser Chrome and Firefox (only two tested)
- Other information: {...}

**Affected components** *(if known)*
Popover
ShellBar

**Comment by ilhan007** [comment]
Hello @leoratzlaff 

Thank you for reporting, but please open the issue in https://github.com/SAP/ui5-webcomponents-react as the ui5-webcomponents-react is the correct project for your issue.

best,
ilhan
