### ISSUE TITLE
ui5-shellbar: Menu Items get duplicated when updating ShellBar

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents#1441]
**Describe the bug**
When updating the ShellBar, e.g. toggle `show-notifications` and having the `menuItems` slot populated, the Menu Items in the Popover are getting duplicated.

**To reproduce**
1. Render a ShellBar, place one menuItem `ui5-li` in there
2. Open the Menu Items Popover, toggle a property, e.g. `show-notifications`
3. Repeat step 2 a couple of times
4. You will now see that every time there are more menu items in the popover.

**Isolated example**
https://codesandbox.io/s/friendly-meninsky-fypz7
Please download and run locally, for some reason not working in CodeSandBox

**Expected behavior**
Shell Bar should not duplicate Menu Items (and maybe other slots as well?)

**Screenshots**
![image](https://user-images.githubusercontent.com/8775211/78683029-0daa4180-78ef-11ea-885e-cc034a717816.png)

**Context**
- UI5 Web Components version: 1.0.0-rc.6
- OS/Platform: MacOS Catalina 10.15.4
- Browser *(if relevant)*: Chrome 80.0.3987.163

**Affected components** *(if known)*
ShellBar

**Comment by MarcusNotheis** [comment]
Might be related to https://github.com/SAP/ui5-webcomponents/issues/1442 as well?

**Comment by vladitasev** [comment]
Thanks, will fix asap.

**Comment by vladitasev** [comment]
https://github.com/SAP/ui5-webcomponents/pull/1456

**Comment by ilhan007** [comment]
Closed with: #1456
