### ISSUE TITLE
ui5-button: ':focus' pseudo-class is not working

### ISSUE THREAD

**Issue by rama1990br** [SAP/ui5-webcomponents#1452]
**Describe the bug**
:focus psuedo-class when added to a ui5-button does not apply the corresponding styles to the button when it is focused.

**To reproduce**
**Steps to reproduce the behavior:**

1. Go to https://sap.github.io/ui5-webcomponents/playground/components/Button/
2. Add ':focus' to any of the buttons and add the style 'background-color:green'
3. Tab over to that button such that the focus is on the button
4. Notice that the button does not have a green background.

**Expected behavior**
Adding ':focus' pseudo-class to the button should add the corresponding styles to the button when focused on, i.e., the button should have a green background when it is focused on.

**Comment by fifoosid** [comment]
Hi @rama1990br 

If you wish to style the focused button you can use the focused attribute which we are setting internally:

```css
ui5-button[focused] {
   background-color: green;
}
```

Best regards,
Filip

**Comment by rama1990br** [comment]
Hi @fifoosid,
The solution proposed by you works. Thanks for the quick response!

Thanks,
Rama
