### ISSUE TITLE
ui5-dialog: Header and Footer accessibility with default banner and contentinfo landmarks

### ISSUE THREAD

**Issue by lormanlau** [SAP/ui5-webcomponents#1466]
The https://github.com/SAP/ui5-webcomponents/blob/master/packages/main/src/Popup.hbs is using header and footer tags but has a default value of banner and content info when using screen readers such as NVDA or JAWS. https://www.w3.org/TR/wai-aria-practices/examples/landmarks/HTML5.html.

Suggestion is to wrap the whole dialog component in a sections tag instead of the span being used.

**Comment by ilhan007** [comment]
Hello @lormanlau

In openui5 the header and the footer are inside `<div>` (not in section), could you check if you face the same issue with the sap.m.Dialog
https://openui5.hana.ondemand.com/entity/sap.m.Dialog/sample/sap.m.sample.Dialog

Of course we will reconsider using  the `span` tag, but if the sap.m.Dialog is fine with `div`, there might be other aria attrs missing, so can you check it please.

Best,
ilhan
