### ISSUE TITLE
Value help dialog - basic

### ISSUE THREAD

**Issue by sunnyyadav100** [SAP/ui5-webcomponents#1474]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
https://sapui5.hana.ondemand.com/sdk/#/entity/sap.ui.comp.valuehelpdialog.ValueHelpDialog/sample/sap.ui.comp.sample.valuehelpdialog.basic

**Describe alternatives you've considered**

**Additional context**

**Comment by ilhan007** [comment]
Hello @sunnyyadav100 we decided not to implement a value help dialog component.

At the end this is a dialog with header with some title, arbitrary content and footer with OK and Cancel buttons. 
And, this can be implemented on top of the standard Dialog component and using its default, header and footer slots, positioning the buttons at the right side of the footer and listening to their click events.

BR, ilhan

**Comment by sunnyyadav100** [comment]
Thanks @ilhan007 , the actual concern was to handle selected values as tokens and its overflow behavior. I saw the MultiInput component has built to handles the behavior of tokens. A dialog can be constructed as you stated.
