### ISSUE TITLE
Tab Container. Selected

### ISSUE THREAD

**Issue by urielrodriguezusma** [SAP/ui5-webcomponents#1479]
Hi. It is possible to select any tab through the code. I know it has the attribute selected, but I'm looking for something I can dynamically do in my component and can choose which tab will be selected.

Thanks for your help.

**Comment by ilhan007** [comment]
Hello @urielrodriguezusma 

I imagine that you would have some data model that represent the state of each tab, and the view should be bind to this model.

```js
// initial state
tabs: [
tab1: false,
tab2: false,
tab3: true, // third tab is selected
tab4: false
];

// do some dynamic work
(previousState, action) => nextState // [tab1: true, tab: false, tab3: false, tab4: false]

// your component is re-rendered with the new state and another tab is selected
```

**Comment by urielrodriguezusma** [comment]
Hello @ilhan007.Tthanks for your feedback. I'll try to implement this solution.
