### ISSUE TITLE
[ Feature Request ] UI5-TabContainer:  Support for customizing tab content

### ISSUE THREAD

**Issue by Hubery-Shen** [SAP/ui5-webcomponents#1480]
**Is your feature request related to a problem? Please describe.**
hi,
we need to customize the tab content for business requirement.
So, is there any possibility to open the slot in order to customize the tab content ? 
![image](https://user-images.githubusercontent.com/63704163/79311516-21c5f280-7f30-11ea-828e-ced3a0d4e278.png)

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/63704163/79312110-fd1e4a80-7f30-11ea-87dd-0643678544cc.png)
I think it is make sense to support user defined content of the tab.

**Related Issues**
https://github.com/SAP/ui5-webcomponents/issues/1453

**Comment by vladitasev** [comment]
Please track the progress here:
https://github.com/SAP/ui5-webcomponents/issues/1490
