### ISSUE TITLE
Re-iterate on event marking

### ISSUE THREAD

**Issue by vladitasev** [SAP/ui5-webcomponents#1489]
Background: currently there is the `isMarked` property that components such as `ui5-button` set on events, so that other components, such as `ui5-li` know that something was clicked by the user and this isn't actually row selection (the event should just be ignored).

Think of a more robust way to achieve the same. Document how it can be done for arbitrary events/conmponents.

@MarcusNotheis

**Comment by ilhan007** [comment]
Resolved with: https://github.com/SAP/ui5-webcomponents/pull/6106
