### ISSUE TITLE
ui5-messagestrip: maybe error for information type color

### ISSUE THREAD

**Issue by alex-zhang** [SAP/ui5-webcomponents#1496]
hi, 

I am from Web Experience team in SAP Successfactors.

**Describe the bug**

ui5-messagestrip: Error Background Color for Information.

As the wiki describe: https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2036840833#MessageStrip(Fiori3)-Semanticvariations

Information
Background: @sapUiInformationBGBorder
Border: @sapUiInformationBorder
Icon: @sapUiInformativeElement

It's should be looks like below

![image](https://user-images.githubusercontent.com/4457451/79728696-e5740700-8320-11ea-9038-0a208b83d467.png)

Not this one 

![image](https://user-images.githubusercontent.com/4457451/79728731-f755aa00-8320-11ea-9e66-02c387d0522b.png)

But i also find the fiori link  https://experience.sap.com/fiori-design-web/message-strip, it's seems it's correct in ui5-webcomponent. but the fiori expert told me, follow the wiki. pls help me to confirm that, 
thanks.

```

**Comment by ilhan007** [comment]
Hello @alex-zhang 

according to the latest design for Quartz Light theme (Fiori 3) our Information type has wrong background color, it should look like as on your first image and we prepared a fix for that. It will be merged in the next few days. Also, we found that the colors if the icons in the beginning of the message strip are wrong, they should not be grey, but in the respective semantic color.

You can look at the fix here:
https://github.com/SAP/ui5-webcomponents/pull/1498

best,
ilhan

**Comment by alex-zhang** [comment]
That's great. And thanks for ur quick reply.
