### ISSUE TITLE
ui5-combobox: OK and "x" buttons do the same on mobile

### ISSUE THREAD

**Issue by vladitasev** [SAP/ui5-webcomponents#1526]
Whenever you type, the selection changes immediately, so the OK and close buttons have exactly the same effect.

Either remove one of them, or make the close button revert the selection, whichever is by spec.

**Comment by vladitasev** [comment]
Same for multicombobox

**Comment by fifoosid** [comment]
This is the expected behaviour for both ComboBox and MultiComboBox.
