### ISSUE TITLE
Input components - keyboard handling

### ISSUE THREAD

**Issue by vladitasev** [SAP/ui5-webcomponents#1534]
This is an epic to track the progress on keyboard handling for all input elements:

- [x] Select
- [x] Combobox
- [x] MultiCombobox
- [x] MultiInput
- [x] Input
- [x] Input suggestions
- [ ] Date Picker
- [x] Date Time Picker
- [ ] Date Range Picker
- [x] Duration Picker
- [x] Time Picker
- [x] File Uploader
- [x] Textarea

**Comment by vladitasev** [comment]
Team Balkan: Please review if the following components implement the full keyboard specification and fill the gaps, wherever necessary:
 - DatePicker
 - TimePicker / DurationPicker (same spec as TimePicker)
 - DateTimePicker

**Comment by ilhan007** [comment]
ComboBox: https://github.com/SAP/ui5-webcomponents/pull/2073

**Comment by ilhan007** [comment]
The following components will planned in TEAM RILA

MultiCombobox
MultiInput
