### ISSUE TITLE
ui5-tabcontainer interaction

### ISSUE THREAD

**Issue by vladitasev** [SAP/ui5-webcomponents#1540]
- [x]  no animation when collapsing/expanding the content - done

- [x] no animation when selecting an item from the overflow menu ( the tab should animate, going to that particular item) - N/A

- [x] no drag capability on mobile so the user can only tap the arrows - done

**Comment by ilhan007** [comment]
about the first bullet - I created a PR

about the 2nd bullet, the drag capability - currently I can drag the tabstrip to left/right and select any tab without using the arrows. I think this is not sth missing, might be implemented at some point

**Comment by ilhan007** [comment]
- [x]  no animation when collapsing/expanding the content - done

- [x] no animation when selecting an item from the overflow menu ( the tab should animate, going to that particular item) - N/A

- [x] no drag capability on mobile so the user can only tap the arrows - done
