### ISSUE TITLE
ui5-shellbar rendering issues

### ISSUE THREAD

**Issue by vladitasev** [SAP/ui5-webcomponents#1545]
Full bundle:
![image](https://user-images.githubusercontent.com/15844574/80359440-81a08f80-8886-11ea-99dc-a606016a04e8.png)

Only shellbar imported (plus all icons) :
![image](https://user-images.githubusercontent.com/15844574/80359552-a72d9900-8886-11ea-91db-176e0bc1f7e3.png)

The profile functionality seems bugged.

**Comment by ilhan007** [comment]
Did you import the Avatar as in the pages an ui5-avatar is used as external slot for the profile?

**Comment by vladitasev** [comment]
You're right, that was it!
