### ISSUE TITLE
ui5-tree: new component

### ISSUE THREAD

**Issue by Hubery-Shen** [SAP/ui5-webcomponents#1550]
Hi UI5 WebComponent Team ,

I am from Web Experience Team in SAP SuccessFactors.

**Feature Request**
There is no a tree component available in ui5 web component library.
We need a tree component to go on our development.
The tree component is looks like: 

[https://sapui5.hana.ondemand.com/#/entity/sap.m.Tree/sample/sap.m.sample.Tree](https://sapui5.hana.ondemand.com/#/entity/sap.m.Tree/sample/sap.m.sample.Tree)

![image](https://user-images.githubusercontent.com/63704163/80372798-a9174c80-88c6-11ea-8f4c-de3cbd17142b.png)

**Addition**
And we can define the DOM structure that will be displayed in tree. ( for example: CheckBox )

Thank you.

**Comment by vladitasev** [comment]
Hi @Hubery-Shen 

We'll implement this component sometime next month, hopefully in the next 2 weeks.

**Comment by vladitasev** [comment]
Consider sample API:

```html
<ui5-tree show-checkboxes>
	<div slot="header">Optional header<div>
	
	<ui5-tree-item expanded text="Tree 1" icon="paste" checked>
		<ui5-tree-item expanded text="Tree 1.1">
			<ui5-tree-item text="Tree 1.1.1"></ui5-tree-item>
			<ui5-tree-item text="Tree 1.1.2"></ui5-tree-item>
		</ui5-tree-item>
	<ui5-tree-item>
	
	<ui5-tree-item text="Tree 2"></ui5-tree-item>
	
</ui5-tree>
```

**Comment by Hubery-Shen** [comment]
Hi @vladitasev 
Thank you for your quick reply and strong support.
The ui5-tree component looks cool and will meet our needs.

I read the sample api and have some questions:
for this code:
```
<ui5-tree-item text="Tree 1.1.2"></ui5-tree-item>
```

**can we define the content of ui5-tree-item ?** 
for example :

```
<ui5-tree-item text="Tree 1.1.2">
     <ui5-checkbox text="Chocolate" checked></ui5-checkbox>
</ui5-tree-item>
```

**Comment by vladitasev** [comment]
@Hubery-Shen We are going to provide another API for the checkbox, we'll demonstrate it tomorrow. If this is not enough, they we can surely make one more slot for the content.
