### ISSUE TITLE
Component Request: DateRangePicker

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents#1558]
**Is your feature request related to a problem? Please describe.**
Required for selecting date ranges

**Describe the solution you'd like**
A new component similar to UI5's [sap.m.DateRangeSelection](https://sapui5.hana.ondemand.com/#/entity/sap.m.DateRangeSelection). Or a flag for the the existing date picker of (`type="range"`).

**Describe alternatives you've considered**
Placing two date pickers next to each other, but that is not as convenient as having a dedicated component for that.

**Comment by MarcusNotheis** [comment]
Originally requested by https://github.com/SAP/ui5-webcomponents-react/issues/455

**Comment by vladitasev** [comment]
Hi, @MarcusNotheis 

We'll try to allocate resource for this in one of the control teams in the near future

**Comment by vladitasev** [comment]
@tsanislavgatev Tsani, could you please roughly estimate the scope of this task

**Comment by ggfer** [comment]
Our projects also need the date pick of `range`, could you please give a rough estimation, and we can take appropriate action on the current project. thank you very much!

**Comment by vladitasev** [comment]
Hello @ggfer 
Work will start now, we'll have an estimation soon.

**Comment by ilhan007** [comment]
DateRangePicker is available with 1.0.0-rc.8
