### ISSUE TITLE
Button keeps 'pressed' state when holding the Space key and then pressing TAB

### ISSUE THREAD

**Issue by pascalwentz** [SAP/ui5-webcomponents#156]
**Describe the bug**
Pressed state doesn't get handled properly

**To reproduce**
1. Go to 'https://sap.github.io/ui5-webcomponents/playground/components/Button/'
2. Move the focus into a not pressed button
3. Hold Space down, press TAB

**Expected behavior**
The Button loses it's pressed state after Tab is pressed

**Screencast**
[Button keeps pressed state when holding the Space key and then pressing TAB.zip](https://github.com/SAP/ui5-webcomponents/files/2945863/Button.keeps.pressed.state.when.holding.the.Space.key.and.then.pressing.TAB.zip)

**Context**
- UI5 Web Components version: 0.8.0
- OS/Platform: {Win 10/Desktop}
- Browser *(if relevant)*: {Chrome latest}
- Other information: {N/A}

**Affected components** *(ui5-button)*

**Log output / Any errors** in the console
```
{N/A}
```

**Comment by MapTo0** [comment]
Looks like a browser issue [jsbin](https://jsbin.com/zununahuka/edit?html,output)
We can handle this in the js code, so it could be fixed.

P.S. I did not manage to reproduce it on FF and Safari.
