### ISSUE TITLE
Research how to implement safety-net tests

### ISSUE THREAD

**Issue by vladitasev** [SAP/ui5-webcomponents#1565]
We need higher-level integration tests on app level. Research how we can advance this topic.

**Comment by vladitasev** [comment]
We'll start with building some apps.

**Comment by ilhan007** [comment]
Several years later we can reflect on this item - it hasn't been a real need of safety-net and there are no plans to pick this up. The existing tests (UI5 Web Components and UI5 Web Components 4 React have good coverage and we did not get any major degradations caught on consumer side).
