### ISSUE TITLE
ShellBar search field positioning

### ISSUE THREAD

**Issue by vladitasev** [SAP/ui5-webcomponents#1570]
When the shellbar is collapsed with search open, the search field is absolutely positioned and gets on top of everything:

![image](https://user-images.githubusercontent.com/15844574/80704836-004b3600-8aee-11ea-81a3-22f8ea182c68.png)

**Comment by ilhan007** [comment]
will be tracked with the following issue: https://github.com/SAP/ui5-webcomponents/issues/2044

The change that is attached to the issue does not work in IE
