### ISSUE TITLE
Feature Request: Progress Bar

### ISSUE THREAD

**Issue by Martotko** [SAP/ui5-webcomponents#1574]
Is your feature request related to a problem? Please describe.
The library does not have a progress bar implementation.
It could be something like https://www.w3schools.com/w3css/w3css_progressbar.asp

Describe the solution you'd like
I'd like an implementation of Progress bar.

Describe alternatives you've considered
Using w3school progress bar.

Additional context
None.

**Comment by ilhan007** [comment]
Hello @Martotko 

We already planned a Progress Indicator component, that would cover the features of the existing sap.m.ProgressIndicator. 

There is an issue already created:
https://github.com/SAP/ui5-webcomponents/issues/1392

I think it would full-fill your request, but in case it would not - feel free to reopen the issue.

Best,
ilhan

**Comment by Martotko** [comment]
> Hello @Martotko
> 
> We already planned a Progress Indicator component, that would cover the features of the existing sap.m.ProgressIndicator.
> 
> There is an issue already created:
> #1392
> 
> I think it would full-fill your request, but in case it would not - feel free to reopen the issue.
> 
> Best,
> ilhan

Thanks for the updateIlhan.
