### ISSUE TITLE
Object page section component

### ISSUE THREAD

**Issue by sunnyyadav100** [SAP/ui5-webcomponents#1577]
**Describe the solution you'd like**

Feature request for object page section - 
https://sapui5.hana.ondemand.com/sdk/#/entity/sap.uxap.ObjectPageSection/sample/sap.uxap.sample.ObjectPageSection

**Describe alternatives you've considered**

**Additional context**

**Comment by vladitasev** [comment]
Hello,

It is possible that we will implement ObjectPageLayout in the future, but it is not planned for the short or medium term. If you need to use ObjectPageLayout, have you considered using OpenUI5?

**Comment by MarcusNotheis** [comment]
In case you are using React as UI Framework, you might also checkout the Object Page from [UI5 Web Components for React](https://sap.github.io/ui5-webcomponents-react/?path=/docs/components-objectpage--render-demo)

**Comment by ignipae** [comment]
Hi @ilhan007 Thanks for your answer! Fine for me - was just hoping. :)
We have a lit-element based application; therefore the react library was not of use.

**Comment by ilhan007** [comment]
Nothing changed, the component is out of our scope and I would even close the issue as "won't fix"
