### ISSUE TITLE
ui5-shellbar support for Transitive search

### ISSUE THREAD

**Issue by codefactor** [SAP/ui5-webcomponents#1588]
**Is your feature request related to a problem? Please describe.**
The UI5 shellbar doesn't have a place to put the transitive search selection. A transitive search is where you've searched for an action, and after you've selected the action you need to do a second search for the object when you want to perform this action. The first selection is the transitive verb, example "View home address for..." and then the search is now limited to the objects which are appropriate for this transitive verb (e.g. people).

**Describe the solution you'd like**
It would be nice to have a new attribute on the ui5-shellbar to specify some text to display next to the search that is both accessible and mobile friendly and also works for the global design team. I don't really know if this is a common thing that other apps would like to do, but SuccessFactors supports this today in the UI5 version of the header and we would like to replace that with the Web Component standard one.

**Describe alternatives you've considered**
Extending the ui5-input

**Additional context**

![image](https://user-images.githubusercontent.com/730310/81462963-e99a8400-916a-11ea-985f-31ab410b57ce.png)

**Comment by ilhan007** [comment]
As we discussed we made a change in the Input that you can make use of by extending the Input and reuse its template. The change is merged. It is not yet released, but we will let you know when we create a next release.
