### ISSUE TITLE
ui5-combobox: does not work on IE in all scenarios

### ISSUE THREAD

**Issue by vladitasev** [SAP/ui5-webcomponents#1611]
You can use the test page:
http://localhost:8080/test-resources/pages/combobox.html
Chaning the combobox selection works only the first time.
Set to "Argentina", then try to set "Austria" -> nothing happens.

**Comment by ilhan007** [comment]
No longer reproducible on the master version both locally and on github
http://localhost:8080/test-resources/pages/ComboBox.html
https://sap.github.io/ui5-webcomponents/master/playground/main/pages/ComboBox/
