### ISSUE TITLE
ui5-list - onItemClick: item info is lagging one render cycle when not clicking checkbox

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents#1615]
**Describe the bug**
When using a `List` Component in selection mode `MultiSelect`, the `item`-detail of the `itemClick` event always lags one render cycle if you don't select it via the CheckBox.

**To reproduce**
1. Open the CodeSandBox and open the console.
2. Select the first item via the checkbox, you'll see that is is selected in both events (onItemClick and onSelectionChange)
3. Deselect it again via the checkbox, now both events state that the selection is clear.
4. Select the first item again via e.g. the text or the whitespace
5. You can now see that `onItemClick` states that the item isn't selected (wrong) but `onSelectionChange` states that the item is selected (correct).

(Step 2 and 3 are optional)

**Isolated example**
Please provide an isolated example if possibile, by forking [CodeSandbox]https://codesandbox.io/s/ui5-webcomponents-jrvot?file=/index.html

**Expected behavior**
All events of the list should provide the correct item state

**Screenshots**
![image](https://user-images.githubusercontent.com/8775211/81938728-9b1b3880-95f5-11ea-8dce-7f1bb55e21ec.png)

**Context**
- UI5 Web Components version: 1.0.0-rc.7
- OS/Platform: macOS Catalina 10.15.4
- Browser *(if relevant)*: Chrome 81.0.4044.138

**Affected components** *(if known)*
List

**Comment by MarcusNotheis** [comment]
Additional information can be found in this slack thread: https://openui5.slack.com/archives/CSQEJ2J04/p1589356022009200

**Comment by ilhan007** [comment]
Hello @MarcusNotheis unlike the selectionChange, which is fired when the selections finishes,  the itemPress and itemClick events are fired before the selection.
