### ISSUE TITLE
ui5-popover: Inconsistent closing behaviour with multiple instances

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents#1628]
**Describe the bug**
If you have multiple instances of a popover on your screen the closing behaviour of the popovers are inconsistent.
It works fine if you close then in the opposite order as you have opened them:
open 1 --> open 2 --> close 2 --> close 1.
But if you close the one first that was opened first, both popovers are gone:
open 1 --> open 2 --> close 1. Now both popovers are gone.

**To reproduce**
1. Open the provided code sandbox. There is a script that "autoplays" that behaviour built in.

**Isolated example**
https://codesandbox.io/s/cool-gould-gqeqp?file=/index.html

**Expected behavior**
The close method of each popover should only close the popover it was called on.

**Context**
- UI5 Web Components version: 1.0.0-rc.7
- OS/Platform: macOS Catalina 10.15.4
- Browser (if relevant): Chrome 81.0.4044.138

**Affected components** *(if known)*
- ui5-popover

**Comment by ilhan007** [comment]
Thanks  @MarcusNotheis  
I found the root cause: the code thinks that the second popover is opened from the first popover and it is closed together with the 1st. With user interaction you can not open two separate popovers with two openers, but you can programatically - this is not handled.

**Comment by MarcusNotheis** [comment]
Hi @ilhan007,
I think it also possible to build that with user interaction. Imagine you want to show a popover on hover that closes itself after some time. I just updated the sandbox with that example:
https://codesandbox.io/s/cool-gould-gqeqp?file=/src/index.js

Just try to hover the first link and then (with a slight delay) the second link.
