### ISSUE TITLE
yarn start command doesn't open the playground in the browser window

### ISSUE THREAD

**Issue by unazko** [SAP/ui5-webcomponents#1629]
Hello,

In the documentation of setting up the SAP Web Components project under section "Develop"
it is said that "yarn start" command will open the playground in the web browser. The command is
starting a local web server, but doesn't open the playground in the browser. Also a guiding message
in the console that the server is up and running and listening for requests could be helpful.

1. Execute "yarn start" command in the console

Current behavior:
The playground isn't open in the browser.

Expected behavior:
As stated in the documentation under section "Develop "at the following UR:
https://github.com/SAP/ui5-webcomponents
this command should open the Playground page in the browser.

Context:
- UI5 Web Components version: last
- OS/Platform: Windows

Best Regards:
Boyan Rakilovski

**Comment by ilhan007** [comment]
Hello @unazko thanks for reporting. Previously it was like described. Now you have to do the following:

To install Playground specific dependencies (only one time)
```js
cd packages/playground
yarn install:dependencies
```

To start the Playground app, you can execute the following from the project root
```js
yarn start:playground
```

To open it on open http://localhost:4000/

We also updated the docs with the PR:  https://github.com/SAP/ui5-webcomponents/pull/1631/
