### ISSUE TITLE
[query] What about Grid Table?

### ISSUE THREAD

**Issue by sosoba** [SAP/ui5-webcomponents#1654]
Is a Grid Table (cell-oriented) analogous to Sapui5 planned in the ui5-webcomponents controls?

**Comment by vladitasev** [comment]
Hi @sosoba ,

We have discussed this and decided we're not going to add a data-driven table, such as the https://ui5.sap.com/#/entity/sap.ui.table.Table/sample/sap.ui.table.sample.Basic
for the time being.

The main reason is that this is a huge undertaking, requiring several layers, most notably model layers around different models for different frameworks, and UI5 Web Components is model-agnostic and framework-agnostic for the most part.

I could see us having a low-level "virtual scrollbar table" component in the medium-long run, that can be used by library authors to create their own data-driven tables, but nothing planned for the moment.

We realize this is a fairly often requested feature and we'll do our best to provide something in the future, even if not the full-blown solution for the future, but at least enough to cover most needs.
