### ISSUE TITLE
Migrate all events to kebab-case style

### ISSUE THREAD

**Issue by MapTo0** [SAP/ui5-webcomponents#1655]
In order to stay consistent with how attributes and properties are mapped, it would be good to follow the kebab-case style for event names as well.

E.g. 
- `selectionChange` => `selection-change`
- `beforeOpen` => `before-open`
- `itemToggle` => `item-toggle`

**Consider backward compatibility** - _one release with warning?_

**Comment by ilhan007** [comment]
Closed with: https://github.com/SAP/ui5-webcomponents/pull/1692
