### ISSUE TITLE
ui5-calendar: how to set selected day in standalone mode

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents#1677]
The API description of the `ui5-calendar` says that this component can be used standalone although its' main use case is to be displayed as part of the `ui5-datepicker` component.
While setting `min-date` and `max-date` works perfectly fine, I found no way of setting the selected day.

There is a property `selectedDates` but this feels more like a helper that can be accessed via Javascript (or how should I pass an array as attribute?). I also tried to set the `timestamp` property but it had no effect either.

Sample:
```html
<ui5-calendar 
    min-date="2020-01-01" 
    max-date="2020-06-30" 
    timestamp="1588464000"
></ui5-calendar>
```

**Comment by vladitasev** [comment]
Hi @MarcusNotheis ,

Indeed, `ui5-calendar` is intended to be a lower-level component, mainly used by other components. Therefore its API is not as user-friendly.

UI5 Web Components metadata entities of type `Object` or of `multiple: true` (hence `Array`) cannot be passed via attributes, but only via HTML properties. You can't bind them declaratively via React, only with JS.

```js
myCalendar.selectedDates = [1588464000];
```

is what would work.

But if you have a strong case, we can redo the calendar to have calendar date items or something of that sort that you can pass as children.

Regards,
Vladi
