### ISSUE TITLE
UI5 WebComponents - Ability to Customize the URL for i18n messages 

### ISSUE THREAD

**Issue by codefactor** [SAP/ui5-webcomponents#1680]
**Is your feature request related to a problem? Please describe.**
SuccessFactors has special requirements to support customer specific translations for all of the messages that are displayed on the page, for example a particularly picky customer not like a particular term (e.g. "Employee" should be "Associate" instead). We would like to be able to support a configuration which can customize which URL that the UI5 web components uses to download the JSON formatted message bundle from. The URL will be dynamically generated, unique to the locale ID + company ID + some other unique ID - which allows the URL to be cacheable on the browser much like a static file typically would be. The servlet will take care to read the JSON file from UI5 Web Components; however, any customer customizations to that JSON file will take precedence and overwrite the out of the box translations that came from UI5 web components library.

**Describe the solution you'd like**
Currently, the only solution we have is to call a function with the final set of translations. But we cannot make this call synchronously. We can either provide a Promise object to deliver the messages at some point during page startup, or we can provide a URL for UI5 web components to use if/when any request is needed.

**Describe alternatives you've considered**
Write the desired translations as a JSON on the initial payload with a global variable with an inline script; however, this will block rendering of the page and the messages would not be cacheable by the browser.

**Additional context**

**Comment by vladitasev** [comment]
Hello @codefactor ,

Each package comes with its own assets, f.e. `@ui5/webcomponents`:
`@ui5/webcomponents/dist/Assets.js`:

```js
import "@ui5/webcomponents-localization/dist/Assets.js"; // CLDR
import "@ui5/webcomponents-theme-base/dist/Assets.js"; // Theming

// own main package assets
import "./generated/json-imports/Themes.js";
import "./generated/json-imports/i18n.js";
```

There, the last line is responsible for the `i18n` assets, so if you open this particular file:
`@ui5/webcomponents/dist/generated/json-imports/i18n.js`:
you can see there is a call to:

`registerI18nBundle("@ui5/webcomponents", bundleMap);`

where `bundleMap` is an object with keys - the languages, and values - the translations.

What you need to do is, after the import of
`@ui5/webcomponents/dist/Assets.js`, 
respectively
`@ui5/webcomponents-fiori/dist/Assets.js`,

call `registerI18nBundle` with your own data.

Let me know if you could make it work.

Regards,
Vladi

**Comment by codefactor** [comment]
@vladitasev ,

No, I should have mentioned that we already considered this. The function you mentioned allows to override the translations that UI5 will use assuming that I currently have the translations synchronously before the web components try to read the messages and make its own async request to download the assets JSON file from a URL that can’t be customized.

By the time our response for customized JSON data to call registerI18nBundle with, it will be too late to avoid the web components make the wrong request.

Does `registerI18nBundle` accept a Promise for the bundle JSON data, or maybe a URL to fetch it from?

**Comment by vladitasev** [comment]
Yes, `registerI18nBundle` accespts URLs as well as objects with the actual translations. This will already work with no new implementation:

```js
import { registerI18nBundle } from "@ui5/webcomponents-base/dist/asset-registries/i18n.js";
registerI18nBundle("@ui5/webcomponents", {
	en: "./lang/en.json",
	es: "./lang/es.json",
});
```

However, there are 2 bugs, that are to be addressed with the linked PR:
 - This doesn't work for the default language, as there is an optimization in our code, preventing it
 - calling the method like in the example below will not just override these 2 languages, but will also remove the keys for all other languages from the i18n registry

**Comment by stoehr** [comment]
@vladitasev, thanks, this will be very useful.  As we discussed offline recently, it would be really beneficial to also support the "\*.properties" file format (besides the "\*.json" format) for projects that need to integrate with i18n backend systems that can only output dynamic "\*.properties" instead of "\*.json".

**Comment by vladitasev** [comment]
@stoehr Yes, we'll track this separately: https://github.com/SAP/ui5-webcomponents/issues/1725
