### ISSUE TITLE
Fixed width property for ui5-button

### ISSUE THREAD

**Issue by Neeeko** [SAP/ui5-webcomponents#1685]
**Is your feature request related to a problem? Please describe.**
We have a list of buttons each composed of a label of various length on the left and an icon on the right.
Designers require the width of the buttons to be identical so that all the icons can be aligned properly, and to crop the button label if it's too long (ellipsis).

**Describe the solution you'd like**
Here's what it'd ideally looks like:
<img width="228" alt="Screen Shot 2020-05-26 at 11 44 15" src="https://user-images.githubusercontent.com/7316793/82886274-98e6a180-9f46-11ea-93f2-3e91a157d88a.png">

```
<ui5-button icon="icon" width="100px">My Button with long text</ui5-button>
<ui5-button icon="icon" width="100px">My Button</ui5-button>
<ui5-button icon="icon" width="100px">My Button with longer text</ui5-button>
```

**Additional context**
I can understand that you may not want to add this feature to your components. If that's the case, would you have any suggestions on how to implement this?

Thanks!!

**Comment by vladitasev** [comment]
Hello, `ui5-button` can by styled with CSS as any other HTML element, therefore properties that directly mimic CSS are not needed:

```html
<ui5-button icon="icon" style="width: 100px;">My Button with long text</ui5-button>
```

Regards

**Comment by ilhan007** [comment]
Hello @Neeeko

For such kind of design more suitable is to use List with list items, the items can have a text on the left and icon on the right, and the alignment comes out of the box. 

```html
<ui5-list>
	<ui5-li selected icon="map" icon-end>My Item with long text</ui5-li>
	<ui5-li icon="map" icon-end>My Item</ui5-li>
	<ui5-li icon="map" icon-end>>My Item with longer text</ui5-li>
</ui5-list>
```

If you should use Button, you can set width on the Button in standard way with CSS. The only problem is that the text and the icon would be centred, instead being on both ends.
For overcoming this you can use the  part="button" that is present on the "ui5-button-root" element inside the Shadow Dom of the ui5-button and add the following style;

```css
ui5-button::part(button) {
  justify-content: space-between;
}
```

The "::part" syntax is called CSS Shadow part selector and would work in all browsers but Internet Explorer.


Best,
ilhan

**Comment by Neeeko** [comment]
Hey @ilhan007, thanks for suggestions!
