### ISSUE TITLE
DateTimePicker and TimePicker display inaccurately selected time

### ISSUE THREAD

**Issue by kostadin-kar** [SAP/ui5-webcomponents#1694]
**Describe the bug**
We are using angular 7 and when we add DateTimePicker or TimePicker, the scrolls on the hours/minutes/seconds do not show the actual selected value. The box can highlight the space between the values, whereas in the examples on the ui5 webcomponents web page you can only select/scroll between the provided boxes. If we start from 00 and scroll down, under the hood, the element is selected accurately, for example 9. But the wheel displays the selection box between 3 and 4.

**To reproduce**
Import, add the corresponding html tag and open DateTimePicker/TimePicker. We are not sure if it's an Angular problem or something in our project.

**Isolated example**
We are using Angular, but could not set up completely an isolated example. Here is where we got to and we are missing the styles
https://codesandbox.io/s/falling-voice-ztw9r?file=/src/app/app.component.ts

**Expected behavior**
When you scroll/select the time pickers, it should show you the provided boxes and not in between.

**Screenshots**
![image](https://user-images.githubusercontent.com/32493838/83121228-b2b8ed80-a0da-11ea-913d-a4359c874e91.png)

![image](https://user-images.githubusercontent.com/32493838/83121344-d8de8d80-a0da-11ea-8ae5-11501c68b054.png)

**Context**
- UI5 Web Components version 1.0.0-rc.7
- OS/Platform: Mac
- Browser *(if relevant)*: Chrome, Mozila - all
- Other information: Angular 7 project

**Affected components** *(if known)*
DateTimePicker TimePicker

**Log output / Any errors** in the console
None

**Comment by fifoosid** [comment]
Hello @kostadin-kar 

This issue is resolved in RC8. I tested it out with Angular 7.2.1 and it works as expected.
If you keep experiencing the issue, don't hesitate to reopen the issue.

Best regards,
Filip
