### ISSUE TITLE
ui5-table: add possibility to add a vertical align property to table rows/cells

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents#1701]
Original Issue from https://github.com/SAP/ui5-webcomponents-react/issues/547 by @rkl1994:

> **Is your feature request related to a problem? Please describe.**
> When using the component 'table', find that content for each cell is not 'vertical-align=middle', and the display doesn't tidy while there is a button in the row.
> 
> If I do it by setting a css class, I have to add this classname to every
> 
> **Describe the solution you'd like**
> Add 'vertical-align=middle' to table rows
> 
> **Additional context**
> After 'adding vertical-align=middle', button and label are in the same line
> <img alt="Screen Shot 2020-05-29 at 2 32 47 PM" width="1129" src="https://user-images.githubusercontent.com/5527455/83228809-7a3c1100-a1b9-11ea-858e-d358fb6b7b40.png">
> 
> Otherwise, they are not in the same line.
> <img alt="Screen Shot 2020-05-29 at 2 35 33 PM" width="1116" src="https://user-images.githubusercontent.com/5527455/83228948-a9eb1900-a1b9-11ea-8d82-b06a193a6581.png">

**Comment by vladitasev** [comment]
I think that's already possible:
https://github.com/SAP/ui5-webcomponents/issues/1626

**Comment by vladitasev** [comment]
Please see: https://sap.github.io/ui5-webcomponents/master/playground/main/pages/TableCustomStyling/

**Comment by ilhan007** [comment]
@MarcusNotheis Hello, there is a solution via CSS Shadow parts, linked in the previous comments that you can try already. If you need IE support, we will make additional change to make it work on IE as well.

**Comment by MarcusNotheis** [comment]
@rkl1994: do you need IE11 support?

**Comment by rkl1994** [comment]
1. Thanks for your reply. I think I need IE11 support.
By the way, I find that this functionality is tagged with RC8 label, so which means it can be used until ui5-web-components 1.0.0-rc8 released?
<img width="402" alt="Screen Shot 2020-06-03 at 9 53 04 AM" src="https://user-images.githubusercontent.com/5527455/83586865-2bf38d00-a580-11ea-981b-cd8b4286c71f.png">

**Comment by ilhan007** [comment]
@rkl1994

It will be part of rc.8, not available in rc.7. But, you can use the "next" tag in npm to get the latest development and includes this feature.

npm install @ui5/webcomponents@next

**Comment by ilhan007** [comment]
Hello @rkl1994 we have publish RC.8 so you can try out the Shadow parts solution we have for this use case

PR: #1626
Example: https://sap.github.io/ui5-webcomponents/master/playground/main/pages/TableCustomStyling/

BR,
ilhan

**Comment by dfenerski** [comment]
The link is broken guys, and while the sample does show the same idea [(link)](https://sap.github.io/ui5-webcomponents/playground/components/Table/), the styles cannot be seen there, the only way rn seems to be to check the [PR directly](https://github.com/SAP/ui5-webcomponents/pull/1627/commits/faa40ae98f8f3908e82453208bf4870d710a0567)
