### ISSUE TITLE
ui5-file-uploader: unable to upload the same file twice

### ISSUE THREAD

**Issue by vladitasev** [SAP/ui5-webcomponents#1709]
We need a way to reset the native file input, otherwise it will never fire a change event if the user tries to upload the same file twice.

**Comment by evangeline-fjy** [comment]
We found that the current version still couldn't handle this problem in Chrome. It would of course be nice, if you can take a look at it again.

We have for now a simple workaround, which seems to work:
- have a ref to this file-uploader element
- force to reset the value after finishing
`    if (fileInputRef.current?.value) {
      fileInputRef.current.value = "";
    }
`

But just as said, I think it would be if ui5 web components could handle this ;)
