### ISSUE TITLE
TimePicker 12PM resets to 12AM

### ISSUE THREAD

**Issue by KoenStraten** [SAP/ui5-webcomponents#1714]
**Describe the bug**
If 12 noon (12:00) is selected, it automatically resets to 12 midnight (00:00) using the 24-hour clock. After opening the timepicker again, the selected value is 12 midnight (00:00).

**To reproduce**
1. Import the time-picker as usual
2. set format-pattern to HH:mm
3. select 12 noon

**Isolated example**
Please provide an isolated example if possibile, by forking [CodeSandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html)

**Expected behavior**
If 12 noon is selected, it should not reset to 12 midnight. 

**Screenshots**
Selection:
![image](https://user-images.githubusercontent.com/27766698/83509175-56cfd980-a4cb-11ea-8da2-46f59b974b59.png) 
Note: 11 is the previously selected value.

Result: 
![image](https://user-images.githubusercontent.com/27766698/83509103-31db6680-a4cb-11ea-852d-3fc188098ce2.png)

Opening the timepicker shows:
![image](https://user-images.githubusercontent.com/27766698/83509475-c80f8c80-a4cb-11ea-9ef7-7e333427fccd.png)

**Context**
- UI5 Web Components version v1.0.0-rc.6
- OS/Platform: { Windows 10 }
- Browser *(if relevant)*: { Chrome }
- Other information: {...}

**Affected components** *(if known)*

**Log output / Any errors** in the console
```
{...}
```

**Comment by ilhan007** [comment]
Reproducible with rc.7 and master, when the format is either HH:mm, or HH:mm:ss (HH defines 24 hours clock). For hh:mm and hh:mm:ss it works fine
