### ISSUE TITLE
ValueStateMessage Property in Multiple Controls

### ISSUE THREAD

**Issue by mathlizee** [SAP/ui5-webcomponents#1720]
Hello,

Currently, many control have a `ValueState` property to display a different state to the user. However, according to the documentation, only the `Input` control currently has a `ValueStateMessage` property to set the text displayed to the user when the `ValueState` is not None.

Would it be possible for all controls having the `ValueState` property to also have a `ValueStateMessage` property (ex: `ComboBox`, `DatePicker`, `TimePicker`, `TextArea`, ...)?

Also, when setting the `ValueStateMessage` property on the `Input` control, the text must be in a HTML `<div/>`. It would be nice if we could use a string directly to set the property. [Here](https://codesandbox.io/s/input-valuestatemessage-ivt6l) is a sample showing the issue. Of course, the new `ValueStateMessage` property of the other controls should have the same behaviour.

Thanks!
Mathieu

**Comment by MarcusNotheis** [comment]
Hey @mathlizee,

as those components are all developed by our UI5 Web Components colleagues, I've forwarded this issue to their repository :)

**Comment by ilhan007** [comment]
Hey @mathlizee,

Have a look of that URL, it shows the latest development (note the "master" word in the URL)
https://sap.github.io/ui5-webcomponents/master/playground/

The TextArea, DatePicker, DateTimePicker, TimePicker all have valueStateMessage slot.
The ComboBox and MultoiComboBox do not have the slot.

**Comment by ilhan007** [comment]
Closing this as it is already existing as issue:
https://github.com/SAP/ui5-webcomponents/issues/1086

**Comment by mathlizee** [comment]
Hello @ilhan007,

Thanks for the reply! There is however one thing that was not addressed in my first post. Here it is:

> Also, when setting the ValueStateMessage property on the Input control, the text must be in a HTML `<div/>`. It would be nice if we could use a string directly to set the property. Here is a sample showing the issue. Of course, the new ValueStateMessage property of the other controls should have the same behaviour.

You can see from [this ](https://codesandbox.io/s/input-valuestatemessage-ivt6l) sample what I mean by using a string instead of a HTML `<div/>`. Would it be possible to have such a feature?

Thanks!
Math

**Comment by MarcusNotheis** [comment]
Hey @mathlizee,
yes, once the new version of UI5 Web Components is released (most of the valueStateMessage slots will come with 1.0.0-rc.9) we will update our wrapper as well :) 

Best regards,
Marcus
