### ISSUE TITLE
ui5-combobox : custom filter

### ISSUE THREAD

**Issue by Vasu-p** [SAP/ui5-webcomponents#1735]
**Is your feature request related to a problem? Please describe.**
Currently there are three filters to choose from. It can be restricting if we wanna implement something else which doesn't fit with those.
For example, I would like to generate the options of the combobox dynamically by filtering over a list of json objects. And I might want to show one of the fields of the object but allow user to filter also by typing other non-visible fields. This is currently not possible as the drop down only shows those options which match the current filter settings.

**Describe the solution you'd like**
an option for passing our own custom function to the `filter` prop.

**Comment by MapTo0** [comment]
Hey @Vasu-p 

We introduced a `None` filter to the ComboBox so application can filter items using the input event of the combobo/multicombobox.
