### ISSUE TITLE
Create an SCP demo app to showcase a UI5 Web Components end-to-end scenario

### ISSUE THREAD

**Issue by vladitasev** [SAP/ui5-webcomponents#1736]
The goal of this task is to present the product in a larger scope in the SAP ecosystem.

Create an application, ideally representing one of the common Fiori business screens, comprising of:
 - Frontend with UI5 Web Components
 - A framework of choice, f.e. React
 - A data layer of choice
 - Backend

**Comment by ilhan007** [comment]
No longer needed, ui5 web components are now used in many Fiori business screens.
