### ISSUE TITLE
ui5-timepicker: width can't be changed via css class or style

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents#1738]
**Describe the bug**
I want the `ui5-timepicker` control to take the full available width of it's parent.
Therefore I have created a CSS class `.fullWidth { width: 100%; }` and applied it to the `ui5-timepicker` but it had no effect. Same applies if an inline-style is used.

**To reproduce**
1. Open the code sandbox
2. `ui5-timepicker` should take the full width but it doesn't

**Isolated example**
https://codesandbox.io/s/ui5-webcomponents-df4x5?file=/index.html

**Expected behavior**
`ui5-timepicker` should respect the width set by class or inline-style.

**Screenshots**
![image](https://user-images.githubusercontent.com/8775211/83938769-a538ed00-a7d7-11ea-9cda-bd5f4061d859.png)

**Context**
- UI5 Web Components version: 1.0.0-rc.7
- OS/Platform: MacOS Catalina 10.15.4
- Browser *(if relevant)*: Chrome

**Affected components** *(if known)*
- `ui5-timepicker`

**Comment by ilhan007** [comment]
Already fixed with: https://github.com/SAP/ui5-webcomponents/pull/1669

And you can see it here:
https://sap.github.io/ui5-webcomponents/master/playground/main/pages/TimePicker/
