### ISSUE TITLE
button for "forms and dates" to clearing input value

### ISSUE THREAD

**Issue by kamych1916** [SAP/ui5-webcomponents#1744]
**Is your feature request related to a problem? Please describe.**
Hello team of UI5 Web Components! If you guys add in new realese, buttons for forms and dates to cleaning inpute value, it will be wevy greatfull

**Describe the solution you'd like**
Somithing like this:

-  Forms input (input, combobox and multi-combobox)

![](https://i.stack.imgur.com/51yyI.png)

-  Dates input (date-picker and date-time-picker)
![](https://i.imgur.com/apwzR2X.png)

Thanks for your attention!

**Comment by ilhan007** [comment]
Hello @kamych1916 

The <ui5-input> has a slot "icon", so for the Inout this can be implemented already. 

```html
<ui5-input>
	<ui5-icon slot="icon" name="decline" style="padding: 0 8px"></ui5-icon>
	<ui5-icon slot="icon" name="search" style="padding: 0 8px"></ui5-icon>
</ui5-input>
```

<img width="236" alt="Screenshot 2020-06-08 at 5 18 38 PM" src="https://user-images.githubusercontent.com/15702139/84041107-1fba6600-a9ac-11ea-922e-82a51f3ebbf8.png">

For the rest of the components it is not currently possible, we will discuss  your request and let you know.
