### ISSUE TITLE
ui5-popover will move 1px after first time open up

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents#1755]
Hi colleague, 
I am from SAP SuccessFactors team. Please help to take a look at this issue.

**Describe the bug**
In compact mode, some Status Drop Down popover and Action popover will move about 1px after the first time open up. 
This issue can only be reproduced in compact mode.

**To reproduce**
1. Go to  [GoalCardContainer](https://github.wdf.sap.corp/pages/xweb/goalmanagementx/iframe.html?id=goal-components-goalcardcontainer--default)
2. Click More Actions button on the top right of Card
3. Click Status Drop Down button on the bottom left of Card

**Isolated example**
![PopoverMove](https://user-images.githubusercontent.com/13098801/84117701-800cde80-aa64-11ea-9454-ecb09d4a3003.gif)

**Expected behavior**
Popover shouldn't move after open up.

**Context**
- UI5 Web Components version: 1.0.0-rc7
- OS/Platform: {macos}
- Browser *(if relevant)*: {Chrome/Edge}
- Other information: {...}

**Comment by vladitasev** [comment]
Hello @GongRichard ,

I was unable to reproduce the issue with our latest version on our test pages.
I notice you're using an old version: RC7
https://github.wdf.sap.corp/xweb/goalmanagementx/blob/master/package.json

Maybe that's the problem? There is a much newer version, maintained specifically for SFSF
0.21.1 (soon we'll release 0.21.2).

Could you try migrating to:
"@ui5/webcomponents": "0.21"

Regards,
Vladi

**Comment by GongRichard** [comment]
Hi @vladitasev ,

Yes, I have tried 0.21 in my local. This issue can't be reproduced. I am closing this ticket.

Thanks,
Richard

**Comment by GongRichard** [comment]
Hi @vladitasev ,

This issue shows again, we use wc version 0.21.10.
You can check page https://github.wdf.sap.corp/pages/xweb/goalmanagementx/app.html?mock&sap-ui-content-density=compact#/goal-list?templateType=tgm&templateId=22 to reproduce.

Thanks,
Richard

**Comment by GongRichard** [comment]
Hi @ilhan007 and @vladitasev,

Would you please take a look at this issue first as we need to release our product next week?

Thanks,
Richard

**Comment by ilhan007** [comment]
Hello @GongRichard is it still reproducible with 0.27.3?

**Comment by GongRichard** [comment]
Hi @ilhan007,

This issue still is reproducible with 0.27.3, you can use the same URL to check the issue.
https://github.wdf.sap.corp/pages/xweb/goalmanagementx/app.html?mock&sap-ui-content-density=compact#/goal-list?templateType=tgm&templateId=22
The version of that page is 0.27.3.

Thanks,
Richard

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-rd please have a look into this issue.

BR,
ilhan
