### ISSUE TITLE
Safari caret position in input component is duplicated

### ISSUE THREAD

**Issue by kostadin-kar** [SAP/ui5-webcomponents#1761]
**Describe the bug**
When using Safari browser and Input component, after entering some text and changing the caret position with arrows or mouse, you see the caret current and previous position before the movement.

**To reproduce**
Open Safari and add Input component
Start typing
Move caret somewhere
Observed behaviour is reproduced

**Isolated example**
N/A

**Expected behavior**
Caret position is where entered input ends

**Screenshots**
![image](https://user-images.githubusercontent.com/32493838/84165385-51026700-aa7c-11ea-8469-f8863b4a035c.png)

**Context**
- Browser *(if relevant)*:  Safari

**Affected components** *(if known)*
Input component

**Log output / Any errors** in the console
N/A

**Comment by ilhan007** [comment]
Hello @kostadin-kar  Is it reproducible all the time? 

I tried with Safari 13.1.1 (macOS 10.15.5), started typing letters and then move the cursor with LEFT/RIGHT arrow keys,
but could not duplicate the caret. 

I used the following test page (it uses the latest development):
https://sap.github.io/ui5-webcomponents/master/playground/main/pages/Input/

Can you give it a try, if you are still able to reproduce it, please add the Safari and macOS versions you have.

BR,
ilhan

**Comment by kostadin-kar** [comment]
I should have probably mentioned the Safari version: 13.1 (15609.1.20.111.8) and macOS: 10.15.4 (19E287). In the suggested playground page, the caret position works fine, however the insertion problem persists. When you move to the middle of the word and start typing, the first letter is inserted properly, but the following are appended at the end of the text. Hope this helps
Best regards,
Kostadin
