### ISSUE TITLE
ui5-li-custom: SuccessFactors Issue: does not render in IE11

### ISSUE THREAD

**Issue by agauyeung** [SAP/ui5-webcomponents#1766]
**Describe the bug**
`ui5-li-custom` works properly in Chrome but does not display in IE11

**To reproduce**
Please see the **Isolated example** below.

**Isolated example**
Unfortunately, codesandbox.io doesn't work in IE11.
```
<ui5-list mode="MultiSelect">
  <ui5-li>Standard</ui5-li>
  <ui5-li-custom>Custom</ui5-li-custom>
</ui5-list>
```

**Expected behavior**
`ui5-li-custom` should render properly in IE11 as well.

**Screenshots**
_Chrome:_
![image](https://user-images.githubusercontent.com/8508119/84304905-10ebc480-ab0e-11ea-9352-f7df22098d25.png)
_IE11:_
![image](https://user-images.githubusercontent.com/8508119/84305015-311b8380-ab0e-11ea-8010-e5cf781383d4.png)

**Context**
- UI5 Web Components version: ^0.21.1
- OS/Platform: Windows
- Browser *(if relevant)*: IE11

**Affected components** *(if known)*
`ui5-li-custom`

**Log output / Any errors** in the console
None

**Comment by vladitasev** [comment]
Fixed by: https://github.com/SAP/ui5-webcomponents/pull/1773
