### ISSUE TITLE
ComboBox and MultiComboBox display popup menu when clicked

### ISSUE THREAD

**Issue by kostadin-kar** [SAP/ui5-webcomponents#1774]
It would be great if you could have the combo box and multi combo box components open their popup menu when you click somewhere inside the field, not only on the arrow in the right.

**Describe the solution you'd like**
When you click/focus in, the menu with options should open the suggestions. For example, if you are tabbing along inputs, the suggestions should open for the corresponding input, then close and open the next focused one. The experience would be great if it works like in mobile - when you focus in, it opens, but when you focus out, it should close the menu.

**Describe alternatives you've considered**
Working around the component with tweaks to get the desired behaviour.

**Comment by fifoosid** [comment]
Hi @kostadin-kar,

The current behaviour of both ComboBox and MultiComboBox is defined by the Fiori design concept. This is the reason why they behave exactly like this. As UI5 Web Components follow strictly Fiori, we cannot implement this on our side.

On the other hand, although I would not recommend, this can be done inside your application. You can attach an event listener to the focusin event and open the suggestions by yourself.

Best regards,
Filip
