### ISSUE TITLE
ui5-dialog cannot be rendered on mobile simulator

### ISSUE THREAD

**Issue by Knightofhonour** [SAP/ui5-webcomponents#1776]
**Describe the bug**
[https://webclient430mdkdavid10344sampl-x0z1n26k24.dispatcher.int.sap.eu2.hana.ondemand.com/?hc_commitid=6a4f3952248316def660640fed1038c2155c6d95](url)
There are no issues on a desktop browser but error messages are produced on any mobile browser (both ios and android emulator) when contents of ui5-dialog are rendered
**To reproduce**
1. Open the link on both a desktop browser and a mobile emulator
2. Click on the Hello World button. 

**Expected behavior**
Contents of ui5-dialog should be rendered in the same way in both the desktop and mobile browsers

**Screenshots**
![image](https://user-images.githubusercontent.com/48403373/84473848-564df480-acbc-11ea-8cc7-f4a1515ac6d3.png)

**Context**
- UI5 Web Components version 0.0.0-934b4df24

**Affected components** *(if known)*
- ui5-dialog

**Log output / Any errors** in the console
- As attached

**Comment by Knightofhonour** [comment]
https://webclient430mdkdavid10344sampl-x0z1n26k24.dispatcher.int.sap.eu2.hana.ondemand.com/?hc_commitid=6a4f3952248316def660640fed1038c2155c6d95

URL if the above does not work.

**Comment by vladitasev** [comment]
Hello, @Knightofhonour 

Thanks very much for your report! We'll look into this.

How to reproduce (the URL above gives 403 Forbidden to me)

https://sap.github.io/ui5-webcomponents/master/playground/main/pages/Dialog/
Use chrome simulator
Open the **stretched** dialog (first button).

**Comment by vladitasev** [comment]
Hello again,

Actually I was wrong, we still can't reproduce it:
![image](https://user-images.githubusercontent.com/15844574/84506918-b5b20180-acc8-11ea-9296-de4d37e952fd.png)

Please open the test page in your simulator:
https://sap.github.io/ui5-webcomponents/master/playground/main/pages/Dialog/

and try the dialogs on the page.

Regards,
Vladi

**Comment by Knightofhonour** [comment]
Hi @vladitasev,

https://github.com/Knightofhonour/ui5-dialog
Could you try this link instead?

How to reproduce:
1. git clone the repo
2. unzip the node modules zip file
3. run command parcel src/index.html
4. check local host on both a mobile simulator and on desktop browser

It should work fine on a desktop browser. The problem lies on the mobile simulator where the ui5-dialog is not rendered properly. Thank you!

**Comment by Knightofhonour** [comment]
Hi @fifoosid , understand that you have already merged a fix. On my end, it still seems that the problem persists. May I know how to update to get the fix?

Thank you!
