### ISSUE TITLE
ui5-messagepage component

### ISSUE THREAD

**Issue by codefactor** [SAP/ui5-webcomponents#1805]
**Is your feature request related to a problem? Please describe.**
SuccessFactors WC version of the header sometimes shows a side panel which contains a MessagePage which is a Fiori pattern. This pattern might make sense to build inside the ui5-webcomponents.

**Describe the solution you'd like**
Something like this:
https://openui5.hana.ondemand.com/entity/sap.m.MessagePage/sample/sap.m.sample.MessagePage

This supports a few attributes and some aggregations - for SuccessFactors we only need the icon, and 2 lines of text under the icon (like the sample linked above) and a button.

**Describe alternatives you've considered**
Manually styling the MessagePage ourselves using the `<ui5-icon>` and plain `<div>`

**Comment by vladitasev** [comment]
Hello @codefactor ,

This OpenUI5 component serves 2 purposes:
 - to center the things
 - to apply the right colors.

It makes sense as an OpenUI5 control since the user has no DOM access at all (or at least is not supposed to), but for a webcomponent, it might be too little.

We'll make a snippet and paste it in this thread, showing how to get the correct fiori design for this, and based on it, we can get your feedback if this is something you're comfortable doing on your own.

**Comment by vladitasev** [comment]
Please see the linked PR.
CSS:
```
        .ui5-message-page {
            display: flex;
            flex-direction: column;
            align-items: center;
            width: 30rem;
            margin: auto;
        }

        .ui5-message-page-icon {
            width: 6rem;
            height: 6rem;
        }

        .ui5-message-page-title {
            font-family: var(--sapFontFamily);
            font-size: var(--sapFontHeader2Size);
            color: var(--sapTextColor);
            margin: 1rem;
        }

        .ui5-message-page-description {
            font-family: var(--sapFontFamily);
            font-size: var(--sapFontLargeSize);
            color: var(--sapNeutralColor);
        }
```

HTML:
```html
<div class="ui5-message-page">
    <ui5-icon class="ui5-message-page-icon" name="filter"></ui5-icon>
    <div class="ui5-message-page-title">No matching items found.</div>
    <div class="ui5-message-page-description">Check the filter settings.</div>
</div>
```

Does this solve your issue?

Regards,
Vladi

**Comment by codefactor** [comment]
@vladitasev ,

Thanks for providing most of the code already. I suppose we could copy this into our own custom library from here and provide it within our group only.
