### ISSUE TITLE
Message Toast opening only every secound time

### ISSUE THREAD

**Issue by felix9607** [SAP/ui5-webcomponents#1810]
**Describe the bug**
The MessageToast opens only every secound time.
It seems like it's not correctly changing its state.
Show() method is called inside an Promise catch method, might have sth to do with that

**To reproduce**
1. Use VueJS framework. 
2.
```
 let toast = document.getElementById('msgToast')
    console.log(toast._state.open) // false
    toast.show() // not showing up
    console.log(toast._state.open) // true
    toast.show() // showing up correctly
```

**Expected behavior**
Show up on every method call

**Context**
- Browser: Chrome, Safari etc.

**Comment by fifoosid** [comment]
Hello @felix9607 

I was not able to reproduce the issue on my side. I tested it out just like you explained VueJS + UI5 Web Components, inside the catch of a Promise:
![image](https://user-images.githubusercontent.com/16850339/84756228-332c8900-afcb-11ea-9334-5adc8815b56a.png)

Versions:
VueJS: 2.5.21
UI5 Web Components: Latest next release(0.0.0-1b568f22b)

If your still experience the issue, please create an isolated example via [CodeSandBox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html)
