### ISSUE TITLE
ui5-multi-combo-box: Changes width on selection change in some cases

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents#1812]
**Describe the bug**
When using the `ui5-multi-combobox` in a Form-like display mode (label on the left) it changes it's own width when there is an at least one active selection. If no item is selected, the width seems to be fine.

**To reproduce**
1. Open the provided sandbox
2. Deselect the selected item (MCB gets smaller)
3. Select another item (MCB grows again)

**Isolated example**
https://codesandbox.io/s/ui5-webcomponents-lt2k9?file=/index.html

**Expected behavior**
I would expect that the MCB does not change its total width.

**Screenshots**
![Screen-Recording-2020-06-16-at-10 54 18](https://user-images.githubusercontent.com/8775211/84753907-e7281700-afbf-11ea-8e0a-b20ed30bfe2e.gif)

**Context**
- UI5 Web Components version: 1.0.0-rc.7
- OS/Platform: MacOS
- Browser *(if relevant)*: Chrome

**Affected components** *(if known)*
- ui5-multi-combobox

**Log output / Any errors** in the console
Other input components like the select is working fine.

**Comment by MarcusNotheis** [comment]
Original issue: https://github.com/SAP/ui5-webcomponents-react/issues/564

**Comment by MarcusNotheis** [comment]
Might be related to #1719 as well?

**Comment by MapTo0** [comment]
Well ... to be honest I am not sure how we can resolve that issue without setting a fixed width of the combobox.
To me this looks like a flexbox question here is a similar question: https://stackoverflow.com/questions/21406397/width-ignored-on-flexbox-items

Try adding `flex-shrink: 0;` to the parent (`display: flex`) container.
