### ISSUE TITLE
UI-5-rating-indicator, has accessibility issues.

### ISSUE THREAD

**Issue by crollioac** [SAP/ui5-webcomponents#1819]
**Describe the bug**
Axe an a11y tool is giving error from the WC. 
Axe checks for this "Ensures every ARIA input field has an accessible name" but not succeeding.

**Expected behavior**
Not to have any a11y issues.

**Screenshots**
<img width="954" alt="rating_indicator_a11e" src="https://user-images.githubusercontent.com/4299153/84770664-97fcd900-aff5-11ea-8e0e-26848affc950.png">

**Context**
- UI5 Web Components version: 0.21.1
- OS/Platform: Windows
- Browser *(if relevant)*: chrome
- Other information: {...}

**Affected components** *(if known)*

**Log output / Any errors** in the console
```
{...}
```

**Comment by crollioac** [comment]
We are using wC version 0.21.5. The issue still persists in this version. Please let us know if it is fixed ?

**Comment by ilhan007** [comment]
1. You can now set aria-label on the component and should get the error

2. There should be a title attribute in the shadowDom, the axe tool suggested to have suchattr  to fix the issue?
