### ISSUE TITLE
Problem rendering <ui5-link>, no link rendered.

### ISSUE THREAD

**Issue by matheus510** [SAP/ui5-webcomponents#182]
**Describe the bug**
Im using ui5-webcomponents on our enterprise application, using LitElement/Polymer as base.

Using ```<ui5-link>``` inside a ```<ui5-li>``` informing a href, target, no link is rendered. The style of active is added, almost everything is happening as expected, except the link.
```html
<ui5-li id="test" type="Active" icon="sap-icon://navigation-right-arrow" icon-end>
    <ui5-link href="/test" target="_self">test</ui5-link>
</ui5-li>
```
**To reproduce**
Use a ```<ui5-link>``` inside a ```<ui5-li>```.

**Expected behavior**
I expected to have browsers URL changed, but this does not happen. If this is correct, pardon me for my bug report.

**Screenshots**

**Context**
- UI5 Web Components version: 0.8.0
- OS/Platform: macOS mojave
- Browser: Chrome

**Affected components** *(if known)*
```html
<ui5-link>
```

**Comment by ilhan007** [comment]
The ui5-li does not support children, such as ui5-link and similar.
The content of this ui5-li is interpreted as text and shown to the user. All HTML Elements inside the Web Component are ignored - only their text is used.
The proper usage of ui5-li would be:

<ui5-li id="test" type="Active" icon="sap-icon://navigation-right-arrow" icon-end>
   Some text
</ui5-li>

There is ui5-li-custom that might be used as container for arbitrary content, such as ui5-link,
but it does not have properties such as description, icon.

The proper usage of ui5-li-custom would be:
<ui5-li-custom>
     <ui5-link>Click me</ui5-link>
</ui5-li-custom>


All this is described in https://sap.github.io/ui5-webcomponents/playground/components/List/
You might need to scroll a bit.

Best regards,
ilhan

**Comment by ilhan007** [comment]
Hello @matheus510,

I am closing the issue, but if my answer is not sufficient or you need more information,

feel free to reopen it.

Thank you,
ilhan
