### ISSUE TITLE
Popup.styles is too specific to Popups which are styled like a Dialog/Popover

### ISSUE THREAD

**Issue by codefactor** [SAP/ui5-webcomponents#1836]
**Is your feature request related to a problem? Please describe.**
Popup.js is a nice parent class to use for new Popups; however, the styles that it defines apply too many styles to the ":host" selector which only apply to Popups that are positioned and styled similar to Dialog/Popover.

See:
https://github.com/SAP/ui5-webcomponents/blob/master/packages/main/src/themes/Popup.css

This CSS defines many rules which do not apply to the Card Popup. To summarize, the :host for this card popup is transparent, the header/button are placed directly onto the block layer and have white color. The other CSS rules are not applicable as well - the only thing we really need is the `:host {display: none}` and everything else is not needed. 

**Describe the solution you'd like**
Perhaps the Popup.css can be broken up, and the CSS the applies to all Popups would go to this CSS and everything else moved to a different CSS which Dialog.js and Popover.js (or any other Popup child class inside @ui5/webcomponents) would opt-in to use.

**Describe alternatives you've considered**
So for this case, we don't use the Popup.styles at all for this particular child class of Popup, which doesn't feel right.

**Additional context**

**Comment by vladitasev** [comment]
Hi @codefactor ,

I've discussed the issue with @MapTo0 and we could try extracting a lower level class that feels more generic and could better fit your use case. We'll check your code for the details.

On a general note, `Popup.js` was intended to centralize the common functionality between `Popover.js` and `Dialog.js`, but seeing your requirements, it probably makes more sense to make it more general. 

We'll see what we can do and get back to you with suggestions.

**Comment by codefactor** [comment]
Maybe we could handle this with #1837
