### ISSUE TITLE
ui5-popup or similar idea for generic popups with view completely defined by the slot

### ISSUE THREAD

**Issue by codefactor** [SAP/ui5-webcomponents#1837]
**Is your feature request related to a problem? Please describe.**
We are using React, and in our React project we are using UI5 Web Components, but we needed to create our own custom Popup class for displaying cards.

**Describe the solution you'd like**
It might be nice to have a <ui5-popup> which will give us all the things we need from a typical child class of a Popup, but without needing to define our own custom Popup child class. It might look like this:

```
<ui5-custom-popup id="popup" modal="true" autoClose="true">
  <div>
    <h1>Hello World</h1>
    <p>
      <ui5-button onclick="document.getElementById('popup').close()">test</ui5-button>
    </p>
  </div>
</ui5-custom-popup>
```

See the following:
https://codesandbox.io/s/ui5-webcomponents-xns2q?file=/src/CustomPopup.js

The above is a simple implementation of the CustomPopup which works well.

A few things:
1. The focus should go immediately to the first focusable thing when the popup is opened
2. The block layer should be added only when it is modal
3. The shadow DOM would probably just have a <div> around the <slot> with the div having position: relative; and z-index
4. The escape key to close the Popup can be enabled or disabled through an attribute

**Describe alternatives you've considered**
1. Custom Popups would need a new Web Component that extends from Popup.
2. Use or create a custom React implementation of a Popup

**Comment by vladitasev** [comment]
@codefactor ,

Currently `Popup.js` is abstract (does not define a tag). If I understand the requirement correctly, your idea would be to make it a real physical component `ui5-popup` which would act like a low-level dialog. Is that correct?

**Comment by codefactor** [comment]
@vladitasev ,

Not necessarily to make `Popup.js` to define it's own tag -- I wouldn't want to impact Dialog and Popover or any other child class for that matter. Or if we do make Popup.js it's own tag - maybe Dialog and Popover would would use the Popup tag internally -- rather than extending Popup.

This latter idea might be good because if I'm not mistaken, in the Web Components the idea of "class extending" is generally frowned upon. So maybe this might mean you would no longer need to maintain the "Popup protected API" so that child classes can have a stable parent class?

**Comment by vladitasev** [comment]
One more dependency for this story: https://github.com/SAP/ui5-webcomponents/issues/1859

**Comment by vladitasev** [comment]
Sample repo: 
https://github.com/vladitasev/custom-popup
