### ISSUE TITLE
Issues with Popup forwardToLast forwardToFirst

### ISSUE THREAD

**Issue by codefactor** [SAP/ui5-webcomponents#1838]
**Describe the bug**
There were 2 issues here, which we fixed both already using a work around, but we want to document them here and get a more elegant solution.

1. The custom popup did not get any focus at all when opening, and the focus is not restricted to the Popup (user can focus to things "underneath" the Popup).
2. The custom popup did not focus onto the correct first or last focusable thing in the focus loop (only applicable if we apply a hack fix for item 1)

**To reproduce**
1. Press the button that says "Open popup noFix"
2. Press `Tab` or `Shift+Tab` to see where the focus takes you
3. Close popup
4. Press the button "Open popup withFix"
5. Focus around (now only restricted in the Popup) first using `Tab` a few times and then again with `Shift+Tab` a few times -- there is a difference in which elements get focused.

**Isolated example**
https://codesandbox.io/s/ui5-webcomponents-uo052?file=/index.html

**Expected behavior**
1. Both buttons should behave the same
2. Pressing `tab` key or `shift+tab` key should restrict the focus inside the dialog in a focus loop
3. The header button should be included in the focus loop regardless if using `Tab` or `Shift+Tab`

**Actual Behavior**
1. The button that says "noFix" does not work at all with the focus loop
2. Pressing tab key will skip the header button, but `shift+tab` does not skip it.

**Engineering Notes**
1. The isNodeVisible function is returning false because the offsetWidth/height are both 0
2. The findFocusableElement is not considering any focusable things outside the `<slot>` in the shadowRoot

**Screenshots**
![image](https://user-images.githubusercontent.com/730310/85052910-91ce4000-b14e-11ea-8c8e-75baaae60e9c.png)

**Context**
- UI5 Web Components version : 0.21.3
- OS/Platform: {...}
- Browser *(if relevant)*: {...}
- Other information: {...}

**Affected components** *(if known)*
Popup

**Comment by vladitasev** [comment]
This is a consequence of the fact that `Popup.js` was intended to work with Popover/Dialog only. In the case that we manage to extract a lower-level self-sufficient component, this would have to be handled naturally.

Let's tackle this as part of the `ui5-popup` story: https://github.com/SAP/ui5-webcomponents/issues/1837

**Comment by codefactor** [comment]
@vladitasev ,
You're right, probably both #1838 #1836 could be equally handled through #1837 if that's the direction we want to take.
