### ISSUE TITLE
Overflow icon not vertically centered

### ISSUE THREAD

**Issue by ee92** [SAP/ui5-webcomponents#1839]
This is the same issue as https://github.com/SAP/ui5-webcomponents/issues/1763, however after the fix it still seems to not be centered correctly.

**Describe the bug**
The dots in overflow icon should be centered vertically based on this https://sapui5.hana.ondemand.com/sdk/test-resources/sap/m/demokit/iconExplorer/webapp/index.html#/overview/SAP-icons/?tab=grid&search=overflow&icon=overflow but the svg rendered by the ui5-icon components makes the dots aligned closer to the top of the container.

**To reproduce**

1. Go to https://codesandbox.io/s/ui5-webcomponents-uwkx9
2. The first first button shows how the icon currently looks, and the second one shows what it should look like. (pixels might not be exact)

**Context**
UI5 Web Components version: 0.21.3
Affected components (if known)
<ui5-icon>

This is a minor issue, but fix would be appreciated :)

**Comment by ilhan007** [comment]
Hello @ee92

Instead of slotting an icon

```js
<ui5-button id="openButton" name="overfl">
      <ui5-icon name="overflow" />
</ui5-button>
```

use the "icon" property:

```js
<ui5-button id="openButton" icon="overflow"></ui5-button>
```
