### ISSUE TITLE
[FeatureRequest] FlexibleColumnLayout

### ISSUE THREAD

**Issue by alex-zhang** [SAP/ui5-webcomponents#1851]
hi, in our project there is a requirement that needs the  FlexibleColumnLayout component.but there is  a little different. it's a simple one  as below.

fiori-design-web:  https://experience.sap.com/fiori-design-web/flexible-column-layout/
 ui5 samples: http://veui5infra.dhcp.wdf.sap.corp:8080/demokit/index.html#/entity/sap.f.FlexibleColumnLayout/sample/sap.f.sample.FlexibleColumnLayoutWithTwoColumnStart

for pc mode:

Expanded

![image](https://user-images.githubusercontent.com/4457451/85378695-79ef2580-b56d-11ea-802c-f2c85ca69ee1.png)

Collapsed

![image](https://user-images.githubusercontent.com/4457451/85262905-fe27a700-b4a0-11ea-836b-7459e1d7e330.png)

for mobile mode:

Expanded&Collapsed

![image](https://user-images.githubusercontent.com/4457451/85382273-5ded8300-b571-11ea-9139-a01734ecdfea.png)

is there any plan for support the FlexibleColumnLayout for that situation.

**Comment by alex-zhang** [comment]
hi,@fifoosid 

thanks for ur quick action.

i'm not sure you ready to  support  it or not.  please let me know.

**Comment by ilhan007** [comment]
Yes, we plan to implement the component.
