### ISSUE TITLE
[FeatureRequest] Tooltips for ShellBar icons

### ISSUE THREAD

**Issue by mihaela96** [SAP/ui5-webcomponents#1854]
Hello :) 
I'm working on a react project with ui5-web components. When we start implementing accessibility standard, we find that there is no way additing tooltip for icons in ShellBar.
![shellbarIcon](https://user-images.githubusercontent.com/11721482/85370656-b4d66680-b537-11ea-96ea-f7de66540518.png)

Is there any plan for support tooltips for components with icons only ? :)

**Comment by ilhan007** [comment]
After we merge and release the [PR](https://github.com/SAP/ui5-webcomponents/commit/3935633772b053ff9421b2c3d87ec02954505557) you will be able to set "title" on the ui5-shellbar-item. Additionally we set tooltips for the built-in ones, such as: overflow, profile, notifications, search, product-switch

```html
<ui5-shellbar>
	<ui5-shellbar-item icon="accelerated" text="Hello World!" title="Schedule"></ui5-shellbar-item>
	<ui5-shellbar-item icon="accept" text="Hello World!" title="Approve"></ui5-shellbar-item>
	<ui5-shellbar-item icon="alert" text="Hello World!" title="Warning"></ui5-shellbar-item>
	<ui5-shellbar-item icon="discussion" text="Hello World!" count="42" title="42 Messages"></ui5-shellbar-item>
</ui5-shellbar>
```
