### ISSUE TITLE
[ui5-tabcontainer] component  a11 issue(must have sufficient color contrast) under Belize theme

### ISSUE THREAD

**Issue by alex-zhang** [SAP/ui5-webcomponents#1870]
hi,  

i'm not sure it's as design.  

Elements must have sufficient color contrast 224 under Belize theme

![image](https://user-images.githubusercontent.com/4457451/85569979-940c2f00-b665-11ea-9fa9-f69eafe07dfd.png)

and i also check the ui5 version. there is no selected text color. i'm not sure of that now in ui5-webcomponent is as design.

http://veui5infra.dhcp.wdf.sap.corp:8080/demokit/index.html#/entity/sap.m.TabContainer/sample/sap.m.sample.TabContainer

![image](https://user-images.githubusercontent.com/4457451/85573953-e7cc4780-b668-11ea-8e5b-07c187930b7f.png)

**Context**
- UI5 Web Components version: Current version: 1.0.0-rc.7
- OS/Platform: All
- Browser *(if relevant)*: All

**Comment by vladitasev** [comment]
Hi @alex-zhang 

The `sap_belize` theme is legacy, to the point that for some UI5 Controls (such as ShellBar) don't even have a visual specification for belize and they appear "as they are" with just changed colors. Do you really have a business case to support this theme? We've even considered removing it altogether.

Regards,
Vladi

**Comment by alex-zhang** [comment]
yes, we have.  For SuccessFactors Bizx Project which also support sap_belize theme.
