### ISSUE TITLE
Custom ui5 textarea property

### ISSUE THREAD

**Issue by kostadin-kar** [SAP/ui5-webcomponents#1879]
**Is your feature request related to a problem? Please describe.**
The textarea component allows multiline values to be entered, which is pretty useful. We would really like it if there could be a possibility to add a button inside the textarea control. It would switch from textarea view and one that minifies the content and looks like the input webcomponent with a button on the right.

**Describe the solution you'd like**
It would look like this:

<img width="465" alt="Screenshot 2020-06-29 at 18 12 13" src="https://user-images.githubusercontent.com/32493838/86023327-35afc980-ba34-11ea-8ad2-9feae0d94d92.png">

<img width="450" alt="Screenshot 2020-06-29 at 18 12 23" src="https://user-images.githubusercontent.com/32493838/86023335-38aaba00-ba34-11ea-9aae-94e7047b9f55.png">

**Describe alternatives you've considered**
Encoding the text inside the control does the job, but does not look user friendly.

**Comment by m1trix** [comment]
Hello,

We either need the possibility to add buttons at the right-most column of the text area (no text overlapping shall happen). Other option would be to have a HDS hook where we can plug the buttons ourselves.

Best regards,
Teodor

**Comment by vladitasev** [comment]
There is a demo project, showing how one can extend the textarea:
https://github.com/vladitasev/custom-textarea

Note: the partial is not released yet, so the demo project is still WIP. Once we've released the partial with the @next NPM release, we'll also update this demo project to show how you can elegantly import the original template and just implement the partial (as currently the original template is copy/pasted mostly).
