### ISSUE TITLE
DatePicker: The popover cannot show due to small z-index

### ISSUE THREAD

**Issue by SunnyWind** [SAP/ui5-webcomponents#1883]
**Describe the bug**
The popover containing the calendar cannot show when the background has a large z-index.

**Isolated Example**
https://498fm.csb.app/

**Screenshots**
The button is pressed, but the popover doesn't show.
![image](https://user-images.githubusercontent.com/4338219/86088420-e66fa480-bad8-11ea-9cc8-b8fa6746056b.png)

**Comment by MarcusNotheis** [comment]
As the DatePicker is developed by our colleagues from UI5 Web Components, I'll forward this issue to their repository.

Best regards,
Marcus

**Comment by ilhan007** [comment]
@SunnyWind sure but is this is a real scenario that you need z-index bigger than 100, the popover starts from z-index: 100

**Comment by ilhan007** [comment]
Hello @SunnyWind I am closing the issue due to inactivity, don't hesitate to reopen it anytime.

**Comment by SunnyWind** [comment]
> Hello @SunnyWind I am closing the issue due to inactivity, don't hesitate to reopen it anytime.

Hi @ilhan007 ,

The product I'm working on set the z-index of the modal dialog to 1000+. I admit it's not a good practice. However, it's an old and large project, and I cannot modify the code rashly, which may cause a regression on other UI.

Is it possible that the component provides an interface to change the z-index of the popover?

Thanks
