### ISSUE TITLE
accessibility Issue: “Ensures every ARIA input field has an accessible name” - for UI5 web components (ui5-list). 

### ISSUE THREAD

**Issue by riteshfsd** [SAP/ui5-webcomponents#1886]
**Describe the bug**
I am facing an issue related to accessibility tests for UI5 web components (ui5-list). Issue description: “Ensures every ARIA input field has an accessible name”

**To reproduce**
1. I am wrapping divs with ui5-list component
2. I have given these attributes for ui5-list (shouldRenderH1 header-text="Test" ariaLabelledBy="label-test")

**Expected behavior**
I Should not get the error "Ensures every ARIA input field has an accessible name"

**Screenshots**
![image](https://user-images.githubusercontent.com/55354366/86123212-b636fe80-baf6-11ea-89ab-7a0631469b55.png)
![image](https://user-images.githubusercontent.com/55354366/86123309-de266200-baf6-11ea-9ebd-8a1bc140000b.png)

**Context**
- UI5 Web Components version
- OS/Platform: {}
- Browser *(if relevant)*: {...}
- Other information: {...}

**Affected components** *(if known)*

**Log output / Any errors** in the console
```
{...}
```

**Comment by ilhan007** [comment]
Hi @riteshfsd 

Just few notes:

**shouldRenderH1** is not an attribute or property of the List, it is a private read-only getter that calculates if the list 
should render internal header in case there is no external one. So shouldRenderH1 is obsolete, does nothing and should be removed.

**header-text** is a public API, but from the code you attached I can see that slot="header" is used. And, the slot takes precedence over the "header-text" and the List does not render internal header, but displays the one set with the slot="header".

If you remove the <div slot="header", you will see the internal header and aria-labelledby pointing to it:

<img width="979" alt="Screenshot 2020-07-01 at 8 45 52 AM" src="https://user-images.githubusercontent.com/15702139/86207480-4f0d5e80-bb77-11ea-96ea-cedcd9208f82.png">


! The support of setting aria-labelledBy="label-test" on the ```<ui5-list>``` is missing and we are going to provide it in regards to this issue.!

**Comment by ilhan007** [comment]
Hello @rimasirich 
after we release this fix you will be able to set aria-label or aria-labelledby on ui5-list.

The change: https://github.com/SAP/ui5-webcomponents/pull/1899

Also,
read my previous comment where I explain the role of shouldRenderH1 and header-text.
