### ISSUE TITLE
[FeatureRequest] Card status Enhancement

### ISSUE THREAD

**Issue by alex-zhang** [SAP/ui5-webcomponents#1913]
hi,

we need to add a custom button in new status position. 

so we need a status slot for customization?  

Here is our design for this requirement.

![image](https://user-images.githubusercontent.com/4457451/86728998-8b512b00-c05f-11ea-9bc6-3190f3048fb0.png)

and i also check the design for an other team's requirement, they has the same requirement.

![image](https://user-images.githubusercontent.com/4457451/86729256-da975b80-c05f-11ea-9af4-e2ed49e6ce94.png)

so, i think here is common requirement.

**Comment by ilhan007** [comment]
Provides a new slot, called "action", displayed in the right most part of the header
to enable users add an action, in most cases single button. When the action slot is used, the status text would not be displayed (if present):

```html
<ui5-card heading="Linked activities (5)">
	<ui5-button icon="add" slot="action" design="Transparent">Add activity</ui5-button>
</ui5-card>
```


<img width="622" alt="Screenshot 2020-07-07 at 3 41 24 PM" src="https://user-images.githubusercontent.com/15702139/86782919-55fd0b00-c068-11ea-8a01-e3d307667806.png">

**Comment by alex-zhang** [comment]
@ilhan007  thanks for ur reply and amazing quick action.
