### ISSUE TITLE
ui5-combobox: popover is not dismissed automatically when there's no item matching the input

### ISSUE THREAD

**Issue by 2bno1** [SAP/ui5-webcomponents#1920]
**Describe the bug**
If I input the word which does not match any of the item, a popover with blank is still there.

**To reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/ComboBox/
2. Type '4' in the first combobox input

**Expected behavior**
Popover should be dismissed automatically if there's no items matching the input

**Screenshots**
![1594173387306](https://user-images.githubusercontent.com/1751846/86866596-d886d880-c103-11ea-8a8f-60710760ff65.jpg)

**Context**
- UI5 Web Components version: 1.0.0-rc.7
- OS/Platform: macOS 10.15.4
- Browser: Chrome 83.0.4103.116

**Comment by ilhan007** [comment]
We have merged a fix, that will be available with rc.8 (in two/three weeks) and sooner with our "next" tag releases (1 week).

BR,
ilhan
