### ISSUE TITLE
[Discussion] List with infinite-scroll

### ISSUE THREAD

**Issue by alex-zhang** [SAP/ui5-webcomponents#1935]
hi, 

we decided to use the behavior of List with infinite-scroll. just like below picture show.

![image](https://user-images.githubusercontent.com/4457451/87011273-431a4000-c1fa-11ea-8ced-27565cfb27c3.png)

Here  is a use case:

There are 100 items for the list and each pagination size is 20 count.  For the initial items request, i got the first 20 count
But the list height is big than the 20 count items total height, so there is no scroll behavior, also the 'loadMore' Event didn't dispatch again. Finally the  result is list has the error behavior.

so, any suggestion of this use case?

**Comment by ilhan007** [comment]
Can you set a fixed hight to the list (one item is 5rem if it has heading and description, and 3 rem if it is single line) for 20 items in this range 60 to 100 rem.

**Comment by alex-zhang** [comment]
so ur suggestion is i need to calculate first request pagination size  according the list capacity size first?   

But for dynamic size it will not work right ?  

So,  if list viewport height  is big than content height, there is a loadMore event happened?

**Comment by ilhan007** [comment]
In general if the list is bigger than the content and all the items fit, there is no overflow and there is no scrollbar and the load-more event will not be fired as it is fired on scroll.

My suggestion was to set a fix height to the List, for example 500px, to ensure that 20 items would not fit. In this case, there will be a scrollbar and if the user scrolls to the end, the loadmore event would be fired.

But if you need theese 20 items to be entirely visible without scrolling, setting smaller height is not a solution. In this case we might need to introduce load more button at the bottom of list, that can trigger the loadmore functionality on click.

What do you think?

**Comment by vladitasev** [comment]
@alex-zhang @ilhan007 

I also believe that an absolute prerequisite for the "infinite scroll" feature is that all the items don't fit, else there won't be a scrollbar, and if there is no scrollbar, there is no way to trigger the event.

Regarding the "load more" button approach, I think it makes a lot of sense, especially as a slot that we render at the bottom of the list. Then you can put whatever you need inside the slot (f.e. a "Load More" button) and then normally process its click event - set the busy mode to the list, fetch some more items, append.

What do you think?

**Comment by alex-zhang** [comment]
@ilhan007  @vladitasev 

OK，thanks for ur quick reply.  i also talk to our ux first and than give the feedback.

**Comment by alex-zhang** [comment]
hi,  

finally, we fix the height for the list and make sure we have the expected behavior.

Thanks again @ilhan007  @ilhan007 for helping me to  discuss about the topic.
