### ISSUE TITLE
Allow automatic rotation in carousel

### ISSUE THREAD

**Issue by paolaweirich** [SAP/ui5-webcomponents#1938]
**Is your feature request related to a problem? Please describe.**
I would like to keep the images rotating automatically in the carousel component (given a time, eg: 10s).

**Describe the solution you'd like**
I would like to setup a timer in seconds in which the images should be displayed and update to the next one. 

**Describe alternatives you've considered**
No built-in alternative.

**Comment by ilhan007** [comment]
Hello @paolaweirich thanks for the issue. See the suggested solution below:

```html
<ui5-carousel id="carouselRotating" cyclic>
        <ui5-button>Button 1</ui5-button>
        <ui5-button>Button 2</ui5-button>
        <ui5-button>Button 3</ui5-button>
        <ui5-button>Button 4</ui5-button>
        <ui5-button>Button 5</ui5-button>
</ui5-carousel>
```

```js
// Set up your own timer and call navigateRight or navigateLeft to keep the carousel rotating and
// make sure the cyclic property is set
setInterval(() => {
  carouselRotating.navigateRight(); //  carouselRotating.navigateLeft(); for the opposite direction
}, 2000);
```


BR,
ilhan
