### ISSUE TITLE
Toggle panel when clicking label

### ISSUE THREAD

**Issue by selevt** [SAP/ui5-webcomponents#194]
**Describe the bug**
To collapse / expand a ui5-panel, it is currently required to click/touch the chevron icon. Clicking the label (header-text) has no effect.

**To reproduce**
1. Try clicking on the panel label on https://sap.github.io/ui5-webcomponents/playground/components/Panel/

**Expected behavior**
When clicking the label, the panel is toggled the same way as clicking the chevron.

I.e. this should be similar to a radio button, where clicking the label also selects the option.

**Comment by ilhan007** [comment]
Hello @selevt,

thank you for creating the issue.

As this is the initial interaction design (to toggle the panel via the icon only), I would label the issue as feature request, rather than a bug.

We will discuss the behaviour you expect and get back to you with a statement.

Best regards,
ilhan

**Comment by ilhan007** [comment]
Hello @selevt, 

The header is now clickable and can be used to toggle the panel between expanded and collapsed state.

The feature would be available via NPM with the next release.

In the playground, it would be available in few hours 
https://sap.github.io/ui5-webcomponents/playground/components/Panel/

Best regards,
ilhan
