### ISSUE TITLE
Dialog: escPressed never is 'true'

### ISSUE THREAD

**Issue by paolaweirich** [SAP/ui5-webcomponents#1941]
**Describe the bug**
When setting a dialog with the function 'onBeforeClose' that receives the boolean 'escPressed', this boolean value never comes with 'true', even when esc is actually pressed before.

**Isolated Example**
```typescript
export const generatedDefaultStory = () => {
  const dialogRef = useRef();
  const onButtonClick = useCallback(() => {
    dialogRef.current.open();
  }, [dialogRef]);
​
  const onCloseClick = () => {
    dialogRef.current.close();
  }
​
  return (
    <>
      <Button onClick={onButtonClick}>Open Dialog</Button>
      <Dialog
        ref={dialogRef}
        stretch={boolean('stretch', false)}
        headerText={text('headerText', 'Dialog Header Text')}
        initialFocus={text('initialFocus', '')}
        footer={<Button onClick={onCloseClick}>Close</Button>}
        header={null}
        onAfterClose={action('onAfterClose')}
        onAfterOpen={action('onAfterOpen')}
        onBeforeClose={(event) => console.log(event.detail)}
        onBeforeOpen={action('onBeforeOpen')}
      >
        Some Content
      </Dialog>
    </>
  );
};
```

**To Reproduce**
1. Check the video with examples or check the onBeforeClose on the dialog storybook.

**Expected behavior**
When esc is pressed the escPressed var should be 'true'

**Screenshots**

[Issue Esc Dialog.mov.zip](https://github.com/SAP/ui5-webcomponents-react/files/4899669/Issue.Esc.Dialog.mov.zip)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.0.0-rc7
`@ui5/webcomponents-react` version: 0.10-rc6
Operating System: MacOS
Browser: Firefox, chrome, edge...

**Comment by ilhan007** [comment]
Hello @MarcusNotheis and @paolaweirich this is fixed in the master.

You can test it here:
https://sap.github.io/ui5-webcomponents/master/playground/components/Dialog/

Through npm, with our preview version: 0.0.0-78035f8e7
```js
npm i @ui5/webcomponents@0.0.0-78035f8e7
// or using the 'next' tag
npm i @ui5/webcomponents@next

```

We plan to realese RC.8 around 20th of July!

BR,
ilhan
