### ISSUE TITLE
Input: Cannot select all(ctrl+A) for 'input' in Firefox

### ISSUE THREAD

**Issue by rkl1994** [SAP/ui5-webcomponents#1951]
**Describe the bug**
Input fields cannot be selected by no matter ctrl+a or 'right click then select all' in Firefox, but in Chrome and Safari, everything works fine.
<img width="280" alt="Screen Shot 2020-07-14 at 4 05 05 PM" src="https://user-images.githubusercontent.com/5527455/87400766-ccab8280-c5eb-11ea-8a62-27fd339af49b.png">

**Isolated Example**
*Please provide an isolated example if possible by forking 
https://codesandbox.io/s/bold-feather-kcc1g?file=/src/App.js

**To Reproduce**
1. Go to codesand box
2. Type any words in input fields
3. Press ctrl+a
4. cannot select

**Expected behavior**
Text in input fields should be selected

**UI5 Web Components for React Information**
`@ui5/webcomponents` version:1.0.0-rc.7
`@ui5/webcomponents-react` version:0.10.0-rc.2
Operating System:
Browser: FireFox Version 78.0.1

**Comment by ilhan007** [comment]
It is not that that the text can't be selected, the selection background color and color are not set properly. We used to set wrong CSS Variables, but In Chrome and Safari these values fallback to the defaults, whereas in FF, they become unset and there is no visual response when you press CTR+A or CMD+A.

Fix has been merged, but you have to wait for 1/2 weeks to be released in npm.
