### ISSUE TITLE
Popover inside dialog has incorrect position

### ISSUE THREAD

**Issue by ee92** [SAP/ui5-webcomponents#1960]
**Describe the bug**
When a popover is inside a dialog, it does not open in the correct position

**To reproduce**
1. Go to https://codesandbox.io/s/ui5-webcomponents-hg6ef
2. click 'Open Dialog'
3. in the dialog, click 'Open Popover'
4. notice the popover is positioned incorrectly (not next to 'Open Popover' button)

**Isolated example**
https://codesandbox.io/s/ui5-webcomponents-hg6ef

**Expected behavior**
The popover should be positioned the same way as it would if it was not inside a dialog. It should be positioned next to the element that it is passed to openBy().

**Screenshots**
![Screen Shot 2020-07-16 at 1 06 14 PM](https://user-images.githubusercontent.com/24360164/87717389-25525b00-c765-11ea-8a5c-10b84aaa3f43.png)

**Context**
- UI5 Web Components version 0.21.x

**Affected components** *(if known)*
ui5-popover

**Comment by MapTo0** [comment]
I would suggest you to render the Popover as a top level, not nested inside a Dialog. And to be more specific, not inside an element that creates its own stacking context.

In react there is a concept called [Portals](https://reactjs.org/docs/portals.html) and you can try to use it for each popup based control.

In case we fix this issue, by calculating level of nesting another issue will come up - stacking contexts.
In case we decide to change the positioning using CSS - Popups will be cut when placed inside an `overflow: hidden` containers.

Will moving popovers outside of the dialog cause some issues to you?

**Comment by ee92** [comment]
@MapTo0 Thanks for the explanation, we were able to fix the problem using portals as you recommended.
