### ISSUE TITLE
microfronted ui5

### ISSUE THREAD

**Issue by deathctalker** [SAP/ui5-webcomponents#1963]
Hi UI5 WebComponents team

I want to make a web application using microfronted technology (single-spa.org), angular (for microapp) and ui5 libraries.

Creating 2 microapp:
    • microapp1 use ui5 version 1.0.0-rc.6
    • microapp1 use ui5 version 1.0.0-rc.7

When I start the application, I get the error: Skipping definition of tag ui5-label, because it was already defined by another instance of ui5-webcomponents..

The problem is related to window.customElements.define(tag, this). Tags are registered in a global object. This is correct.

But still, are there any options to register tags in a local scope so that you can run microapps with the same tags, but with different implementations

**Comment by vladitasev** [comment]
Hi @deathctalker ,

No, not at this point unfortunately. Scoped custom element registries are still in the draft phase and nowhere near to browser adoption. Here's the official PR for them: https://github.com/w3c/webcomponents/issues/716

Therefore, having several runtimes side by side requires:
1. Either to bundle the code twice (as in your example) and have the first to register custom elements win
2. Or create a common bundle with all webcomponents, not part of the apps' build and load this centrally or on-demand (i.e. app2 only loads it if app1 hasn't already).

Regards,
Vladi
