### ISSUE TITLE
Passing getSelectedRowIds withn object without an index key throws error

### ISSUE THREAD

**Issue by stsander07** [SAP/ui5-webcomponents#1968]
**Describe the bug**
When using an AnalyticalTable and passing in something for the `getSelectedRowIds` prop with an object without an index as key, we receive an error. This does not cause a problem if the keys of the objects in the array are indexe.

**To reproduce**
1. Create an AnalyticalTable
2. Pass in this prop

`selectedRowIds={{
          ["test"]: true
        }}`
3. error is thrown

**Isolated example**
https://codesandbox.io/s/wispy-dew-qlcu7

**Expected behavior**
I would expect this to not throw an error. especially if you pass in a custom `getRowId` method to `reactTableOptions`. The keys of the object in `selectedRowIds` are not always an index because of this, it might be a custom string.

**Screenshots**

**Context**
    "@ui5/webcomponents": "1.0.0-rc.7",
    "@ui5/webcomponents-fiori": "1.0.0-rc.7",
    "@ui5/webcomponents-react": "0.10.0-rc.9",
    "react": "16.13.1",

**Affected components** *(if known)*

**Log output / Any errors** in the console
```
{...}
```

**Comment by fifoosid** [comment]
Hello @stsander07 

As much as I can see, the issue is regarding the AnalyticalTable, which is part of the [UI5 Web Components for React](https://github.com/SAP/ui5-webcomponents-react).

I think that @MarcusNotheis can help out on this issue.

**Comment by stsander07** [comment]
My bad, I intended to create this in the React repo as I had already talked to Marcus about it. Anyway, I already received a response so I can close this issue
