### ISSUE TITLE
[ Feature request ] new component RichTextEditor

### ISSUE THREAD

**Issue by alex-zhang** [SAP/ui5-webcomponents#1973]
hi,

There's a new requirement that needs the RichTextEditor(Below).

![image](https://user-images.githubusercontent.com/4457451/88150402-ebd19200-cc33-11ea-9deb-f6ac5fb62996.png)

The user can edit the **Description** field by RichTextEditor.

And the PM also give the priority(from high to low).

1. Bold
2. Italic
3. Underline
4. Font
5. Font size
6. Font color
7. Bullet
8. Numbering
9. Align text
10. left align
11. right align
12. center align
13. Indent
14. Hyperlink
15. Strikethrough

Here is the ui5 document [link](https://ui5.sap.com/#/topic/d4f3f1598373452bb73f2120930c133c) and example [link](https://ui5.sap.com/#/entity/sap.ui.richtexteditor.RichTextEditor/sample/sap.ui.richtexteditor.sample.RichTextEditor)

![image](https://user-images.githubusercontent.com/4457451/88151542-6c44c280-cc35-11ea-9331-e919ff2478fa.png)

**Comment by vladitasev** [comment]
Hi @alex-zhang 

This has been requested before, but unfortunately we cannot create a tinyMCE open-source component for legal reasons.

Regards,
Vladi

**Comment by alex-zhang** [comment]
hi @vladitasev 

Thanks for your reply. 

What's the legal reason. I'm not sure why ui5 can use the tinyMCE why can not in ui5 web-component.
