### ISSUE TITLE
Chinese language code support

### ISSUE THREAD

**Issue by vladitasev** [SAP/ui5-webcomponents#1976]
Currently "zh" does not work, only:    "zh_CN",  "zh_TW" do.

**Comment by vladitasev** [comment]
After an investigation, it turned out this is by design. We cannot favor "zh_CN" over "zh_TW" or the other way round by mapping one of them to "zh".

Instead, users/apps are expected to explicitly request Chinese Traditional or Chinese Taiwanese. If you intend to use the "zh" code in your app's code, that's fine, but you should map it to one of these for interactions with UI5 Web Components.

Regards,
Vladi

**Comment by MarcusNotheis** [comment]
Hey @vladitasev,
for me it looks like that chinese fonts aren't loaded at all.
Example on master playground:
https://sap.github.io/ui5-webcomponents/master/playground/components/DurationPicker/?sap-ui-language=zh_CN
If you open the DurationPicker, there is still the `hours` heading. If you change the language e.g. to `ar` everything is fine.
Or am I missing something here?
