### ISSUE TITLE
[IE11] FCL arrows not centered

### ISSUE THREAD

**Issue by vladitasev** [SAP/ui5-webcomponents#1998]
http://localhost:8081/test-resources/pages/fcl.html

![image](https://user-images.githubusercontent.com/15844574/88535525-bac9d680-d012-11ea-924b-27d99fa8f002.png)

**Comment by ilhan007** [comment]
It is a limitation/bug in the Button, if you have 
```html
<ui5-button style="min-width: 1.5rem; width: 1.5rem"
```
the icon is not in the center
