### ISSUE TITLE
[All] Shellbar search field positioning

### ISSUE THREAD

**Issue by vladitasev** [SAP/ui5-webcomponents#2000]
All browsers
http://localhost:8081/test-resources/pages/ShellBar.html

If you open the search and resize, it goes over the other buttons.

![image](https://user-images.githubusercontent.com/15844574/88536586-bf8f8a00-d014-11ea-9098-f752546f88ae.png)

**Comment by ilhan007** [comment]
will be tracked with the following issue: https://github.com/SAP/ui5-webcomponents/issues/2044
