### ISSUE TITLE
[IE11] List: Double focus in Delete mode

### ISSUE THREAD

**Issue by nnaydenow** [SAP/ui5-webcomponents#2016]
**Describe the bug**
When delete icon is reached with Tab key double focus appear.

![image](https://user-images.githubusercontent.com/31909318/88547198-0e91eb00-d026-11ea-94f5-72a6d8fcdd2b.png)

**Comment by fifoosid** [comment]
This issue is no longer reproducible. Focus is working as expected on IE11.
