### ISSUE TITLE
Recommendation to use kebab-case for event names

### ISSUE THREAD

**Issue by maltenorstroem** [SAP/ui5-webcomponents#2030]
All UI5 web components emit camelCased events. If you now want to listen to an event with a kebab-cased version, this has no effect.

Unlike components and props, event names will never be used as variable or property names in JavaScript, so there’s no reason to use camelCase or PascalCase. Additionally, v-on event listeners inside DOM templates will be automatically transformed to lowercase (due to HTML’s case-insensitivity), so v-on:myEvent would become v-on:myevent – making myEvent impossible to listen to.

For these reasons, we recommend you always use kebab-case for event names.

**Comment by ilhan007** [comment]
Hi and thanks for the info. We already switched to kebab-case event names. They will be available with RC.8 and already available with our preview "next" tag versions in npm.

Best,
ilhan
