### ISSUE TITLE
<ui5-shellbar> search box overlaps other icons when the window is resized

### ISSUE THREAD

**Issue by codefactor** [SAP/ui5-webcomponents#2044]
**Describe the bug**
The search box in the shellbar is not properly positioned on the screen when the window is resized

**To reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/master/playground/components/ShellBar/
2. Click the search button
3. Resize the window horizontally
4. Notice how the search box does not move position horizontally

**Expected behavior**
The search box should reposition itself according to the dimensions of the screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/730310/88999716-28436480-d2aa-11ea-9db5-5413c8a6085f.png)

**Context**
- UI5 Web Components version
- OS/Platform: {...}
- Browser *(if relevant)*: {...}
- Other information: {...}

**Affected components** *(if known)*

**Log output / Any errors** in the console
```
{...}
```

**Comment by ilhan007** [comment]
We have that issue from our latest exloratory testing: https://github.com/SAP/ui5-webcomponents/issues/2000

But it is ok we can keep yours.

**Comment by jdichev** [comment]
Hello, this issue will be looked into with in one of the team's next sprints.
Internal reference: 4905
