### ISSUE TITLE
Node module doesn't include Side Navigation

### ISSUE THREAD

**Issue by null-saad** [SAP/ui5-webcomponents#2054]
**Describe the bug**
The node bundle does not include couple of components. 
For eg.
[ProductSwitch](https://sap.github.io/ui5-webcomponents/playground/components/ProductSwitch/)
[Side Navigation](https://sap.github.io/ui5-webcomponents/playground/components/SideNavigation/)

**To reproduce**
1. Follow https://sap.github.io/ui5-webcomponents/playground/tutorials/vue/
2. Try using/importing any of the above mentioned components
3. Components does not exist.

**Expected behavior**
The mentioned components should be available.

**Context**
- UI5 Web Components version
- OS/Platform: Windows 10 
- Other information: UI5 Version : @ui5/webcomponents@1.0.0-rc.8

**Affected components** *(if known)*
[ProductSwitch](https://sap.github.io/ui5-webcomponents/playground/components/ProductSwitch/)
[Side Navigation](https://sap.github.io/ui5-webcomponents/playground/components/SideNavigation/)

**Log output / Any errors** in the console
Cannot resolve dependency '@ui5/webcomponents/src/SideNavigation'

**Comment by ilhan007** [comment]
Hello @null-saad 

These components are part of our "fiori" package, so you have to install it in addition: 

```js
"@ui5/webcomponents": "^1.0.0-rc.8",
"@ui5/webcomponents-fiori": "1.0.0-rc.8", - // SideNavigation, ProductSwitch, FlexibleColumnLayout, etc..
```

We will add it to the tutorial to avoid confusion, but the important thing is that they are published and available.

Best,
ilhan
