### ISSUE TITLE
Mobile size screens show Company Logo in place of selected module

### ISSUE THREAD

**Issue by codefactor** [SAP/ui5-webcomponents#2061]
**Describe the bug**
The ui5-shellbar web component when displayed on a mobile screen is showing the company logo in the top left corner rather than the currently selected module.

**To reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/master/playground/components/ShellBar/
2. Emulate phone in chrome dev tools

**Expected behavior**
The selected module should be preferred over the company logo.

**Screenshots**
<img width="373" alt="Screen Shot 2020-08-03 at 1 15 30 PM" src="https://user-images.githubusercontent.com/730310/89223389-8ebad200-d58b-11ea-8746-370a0b9e2569.png">

Screenshot from the following page:
https://ux.wdf.sap.corp/fiori-design-web/shell-bar/#responsiveness

<img width="1092" alt="Screen Shot 2020-08-03 at 1 18 59 PM" src="https://user-images.githubusercontent.com/730310/89223650-ff61ee80-d58b-11ea-8fbc-6cda3ea955f5.png">

**Context**
- UI5 Web Components version
- OS/Platform: {...}
- Browser *(if relevant)*: {...}
- Other information: {...}

**Affected components** *(if known)*

**Log output / Any errors** in the console
```
{...}
```

**Comment by ilhan007** [comment]
Thanks for reporting this. We found out that the same behaviour is implemented in the ui5 control, so we will contact the team, developing the sap.f.ShellBar to ask why they go for the current behavior. As far as I know there were some discussions about it, but once we know more we will get back to you.

**Comment by ilhan007** [comment]
Hello,

we contacted the designers about it, so basically this is the older version of the S size appearance.
When we start implementing a new control we use an internal WIKI for the visual spec where the design looks like:
![E8118D5A-43B8-4CAB-91FE-83160E41CE78](https://user-images.githubusercontent.com/15702139/89548230-6e02ae80-d80f-11ea-8206-dc1a893cd7da.jpeg)

https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2052690369

Both the sap.f.Shellbar  ontrol and our web component are implemented by the latest Fiori 3 design.

The designers now know about the difference between these two sources and they should update the content in https://ux.wdf.sap.corp/fiori-design-web/shell-bar/#responsiveness
