### ISSUE TITLE
ui5-dialog: block layer blocks dialog in OpenUI5

### ISSUE THREAD

**Issue by DonkeyCo** [SAP/ui5-webcomponents#2069]
**Describe the bug**
When opening a `ui5-dialog` in OpenUI5 the block layer blocks the actual dialog. If you have controls inside of it, you can still navigate and interact with your keyboard, but you cannot target it with your mouse.

**To reproduce**
1. Create a UI5 library, which implement a custom control for the dialog. 
2. Import the library into the UI5 app.
3. Use custom control in view.
4. Write a controller, which opens the dialog. 

**Isolated example**
[Code Sandbox Example](https://codesandbox.io/s/ui5-webcomponents-in-ui5-16g4b)

**Expected behavior**
The dialog should be in front of the block layer and you should be able to interact with it by using your mouse.

**Screenshots**
![Example App - Dialog Opened](https://imgur.com/zfX1dLj.png)
[More Examples on imgur](https://imgur.com/a/zX4EQts)

**Context**
- UI5 Web Components version: 1.0.0-rc.8 (latest version)
- OS/Platform: Windows
- Browser *(if relevant)*: {...}
- Other information: 
  - UI5 version: 1.80.0 (latest)

**Affected components** *(if known)*

**Log output / Any errors** in the console
no error messages

**Comment by ignipae** [comment]
Hi,
I can confirm this as well. Basically, this happens as soon as the dialog is created from within the xml view. When creating the dialog within a javascript function, it works.

**Comment by Smux** [comment]
**We also found out that this issue occurs as well when you want to open a UI5 web component dialog while a SAPUI5 dialog is opened. T**he UI5 Web component dialog is opening but we are not able to focus it via cursor. We assume that the block layer of the SAPUI5 dialog is causing this issue. Note: This also happens when opening the UI5 Web component dialog via JS and not XML.

**Comment by lava12chenna** [comment]
Hi,

We also face the same issue, please let me know if anyone found resolution for it.


![block layer issue](https://user-images.githubusercontent.com/55983074/96027069-f9826680-0e74-11eb-9cf9-e53236cc3f02.PNG)

**Comment by MisherLiu** [comment]
I also face this issue, when this will be resolved?

**Comment by MisherLiu** [comment]
When this issue can be fixed?

**Comment by lucasheim** [comment]
Hi people, we had the same problem, this happens whenever the button you use to open the dialog is inside another component. By following these instructions of the documentation you should be able to fix this behavior: https://sap.github.io/ui5-webcomponents-react/?path=/docs/modals-popovers-dialog--default-story#using-dialogs-inside-other-components

**Comment by luizcarlospedrosogomes** [comment]
problem in dialog inside Page: https://codesandbox.io/s/charming-nobel-n9kvc

**Comment by luizcarlospedrosogomes** [comment]
resolved using createPortal

**Comment by cpf-hse** [comment]
Hello @ilhan007 
we have this issue as well in one of our apps.
I have made a simple reference app using latest openui5 version (1.117.0)

https://github.com/cpf-hse/openui5-wc-bugs/tree/WC-Dialog-Bug

Would be nice if this could get back on the roadmap.

Kind regards
Christian

**Comment by tnurmi82** [comment]
We have an app using ui5-webcomponents and also ui5-webcomponents-react. This issue is happening with <MessageBox> React component as well.

I'm experimenting with a CSS workaround:
`ui5-static-area-item {
   display: none !important;
}`

**Comment by vladitasev** [comment]
Hello,

In **version 2.0** we no longer use a static area / static area items, but rather the native browser Popover API, which solves all fundamental issues such as stacking context concurrency, the need to use portals, etc.

Therefore, closing this issue. Please let us know if you still need support

BR,
Vladi
