### ISSUE TITLE
MultiComboBox allowCustomValues not working

### ISSUE THREAD

**Issue by vinniimiranda** [SAP/ui5-webcomponents#2076]
When i type a "option" that is not present on the the MultiComboBox the component doesn't allow me to add this new option, even with allowCustomValues passed.

```
<FlexBox direction={FlexBoxDirection.Column}>
   <Label required>Grupos</Label>
    <MultiComboBox required
       style={{
           width: "96%"
       }}
        ref={groupsRef}
         allowCustomValues
         onSelectionChange={({ detail }) => setGroups(detail.items.map((item: any) => item.text))}
      >
         {groupsOptions.map(group => (
           <MultiComboBoxItem key={group} text={group} selected={customer?.groups.includes(group)} />
          ))}
     </MultiComboBox>
</FlexBox>
```
![Gravar_2020_08_06_16_42_17_220](https://user-images.githubusercontent.com/33462844/89575358-098e2200-d804-11ea-9d00-76cdf5e40b9c.gif)

**Comment by ilhan007** [comment]
Hello @vinniimiranda  You have to set the attribute as allow-custom-values.

**Comment by MarcusNotheis** [comment]
Short addition from my side:
the react-wrapper is replacing all `kebab-case-naming` to `camelCaseNaming`

**Comment by vinniimiranda** [comment]
Thank you guys, i will try to implment this on my side as Marcus said above.
