### ISSUE TITLE
Ui5-list: selected options not read as selected

### ISSUE THREAD

**Issue by vladitasev** [SAP/ui5-webcomponents#2078]
1. List with mode=MultiSelect => selected options not read as selected

**Comment by ilhan007** [comment]
This is a known issue with JAWS and the “aria-selected” attribute.
It can even be reproduced in the “best practice” example on www.w3.org:
https://www.w3.org/TR/wai-aria-practices/examples/listbox/listbox-rearrangeable.html#ex2_label

*Works fine with VoiceOver, Chrome on Mac.

BR,
ilhan
