### ISSUE TITLE
lazily applied addCustomCSS not accepted

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents#2079]
**Describe the bug**
We have a scenario where we load an app extension (components) from another URL. The components from this URL are containing e.g. a `ui5-select` and a `addCustomCSS` call. Although the `addCustomCSS` call is executed and the style is registered in the `customCSSFor` map in `CustomStyle.js`, the styles are not applied.
I also tried to force a rerender using `_invalidate()` or `_updateShadowRoot()` on the `ui5-select` but it had no effect.

**To reproduce**
1. Open the codesandbox
2. Press apply styles and rerender
3. Nothing happens (I would have expected that the select background is now red.
4. Optional - if you move the `addCustomCSS` outside of the callback everything works as expected.

**Isolated example**
https://codesandbox.io/s/epic-heyrovsky-q4m0j?file=/src/index.js

**Expected behavior**
I would expect that custom styles are applied when components are rerendered. (Updating the affected components can be in the responsibility of the user IMO, but would be nice if the framework could do that as well).

**Context**
- UI5 Web Components version: 1.0.0-rc.8

**Comment by vladitasev** [comment]
Hi @MarcusNotheis ,

We have identified the issue and are working on a fix. However, we're considering this a feature - making custom CSS dynamic.

Regards,
Vladi
