### ISSUE TITLE
Dialog draggable and resizable

### ISSUE THREAD

**Issue by stevetsanders** [SAP/ui5-webcomponents#2082]
**Is your feature request related to a problem? Please describe.**
I want to be able to drag and resize a dialog.

**Describe the solution you'd like**
When my mouse is hovering over one of the corners of the dialog, I would like my mouse icon to change and indicate that I can resize the dialog. Once I click and drag the corner, I want the dialog to resize.

When my mouse is hovering over the header of the dialog, I would like my mouse icon to change and indicate that I can drag the dialog. Once I click and drag with my mouse, I want the dialog to move along with it.

**Describe alternatives you've considered**

**Additional context**
I believe this is already available functionality in the standard UI5 library. In order to achieve more feature parity, I think this would be an important step.

**Comment by ilhan007** [comment]
Will be planned in Team Rodopi with medium priority

**Comment by ilhan007** [comment]
API changes

- New property "resizable": Defines whether the Dialog is resizable. If this property is set to true, the Dialog will have a resize handler in its bottom right corner. 

- New property "draggable": Defines whether the Dialog is draggable by its header. 
<b>Note:</b> This property has a default value false. The Dialog can be draggable only in desktop mode..

**Comment by ilhan007** [comment]
Tasks:

- [ ] draggabe #2269 
- [ ] resizable
