### ISSUE TITLE
Missing reference for SideNavigation.js from npm dist folder

### ISSUE THREAD

**Issue by bahrus** [SAP/ui5-webcomponents#2096]
It seems that the npm folder @ui5/webcomponents/dist is missing some of the elements with the "new" indicator on the documentation site.  Maybe the documentation site is just a little ahead of what's actually available?  Or is there an expected name used for this file?

1. In package.json, "dependencies" section, add "@ui5/webcomponents": "1.0.0-rc.8",
2. On a windows 10 OS, node version 12.13.0, npm verion 6.14.7 run npm install
3. Examine contents of node_modules/@ui5/webcomponent/dist

**Expected behavior**
A file with a name like SideNavigation.js

**Context**
- UI5 Web Components version: {1.0.0.rc.8}
- OS/Platform: {Windows 10}

**Comment by ilhan007** [comment]
You need the "fiori" packages. We have two packages "main" - @ui5/webcomponents and  "fiori" - @ui5/webcomponents-fiori. The "fior" package includes components that are FIori 3 UX specific.


Just install "@ui5/webcomponents-fiori": "1.0.0-rc.8"

BR,
ilhan
