### ISSUE TITLE
ui5-input: [a11y] customized valueStateMessage from slot is not read correctly

### ISSUE THREAD

**Issue by zhangliangyi** [SAP/ui5-webcomponents#2106]
Dear colleague,

I am from Successfactors web experience Shanghai team.

**Describe the bug**
In NVDA screen reader, the customized valueStateMessage is not correctly read.

In error state, the output from screen reader is always `Invalid entry`.
In warning state, the output is `Warning issued`.

**To reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/Input/
2. Move the section `Input with Suggestions and Value State message`
3. Focus to the second input field and check the screen reader output

**Expected behavior**
Screen reader should output the customized valueStateMessage, "This is an error message. Extra long text used as an error message."

**Context**
- UI5 Web Components version: 0.23.0
- OS/Platform: macOS 10.15.6
- Browser *(if relevant)*: Microsoft Edge

**Other user input components have the same issue, such as `ui5-textarea` and `ui5-datepicker`**

Thanks
Jacob

**Comment by ilhan007** [comment]
The PR (https://github.com/SAP/ui5-webcomponents/pull/2120) addresses the ui5-input and ui5-datepicker components.

**Comment by ilhan007** [comment]
The PR (https://github.com/SAP/ui5-webcomponents/pull/2122) fixes the ui5-textarea
