### ISSUE TITLE
ui5-textarea: [a11y] provide aria-label or aria-labelledby property in ui5-textarea

### ISSUE THREAD

**Issue by zhangliangyi** [SAP/ui5-webcomponents#2107]
Dear colleague,

I am from Successfactors Web Experience Shanghai team.

**Describe the bug**
As the id defined in `for` property of ui5-label takes no effect to the inner input element in shadow DOM, the `aria-label` or `aria-labelledby` property is required for screen reader to identify the linked label.

But so far neither `aria-label` nor `aria-labelledby` is exposed from the component.

**To reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/Label/
2. Go to section `Label 'for'`
3. Focus to the ui5-textarea and check the output of screen reader.

**Expected behavior**
When focus to the datepicker, select or textarea, the linked label should be read.

**Context**
- UI5 Web Components version: 0.23.0
- OS/Platform: macOS 10.15.6
- Browser *(if relevant)*: Microsoft Edge
- Other information: Screen Reader - NVDA

**Affected components** *(if known)*
- ui5-textarea
- ui5-datepicker
- ui5-select

Thanks
Jacob

**Comment by ilhan007** [comment]
Provided aria-label or aria-labelledby property for th following components: ui5-textarea, ui5-datepicker and ui5-select

https://github.com/SAP/ui5-webcomponents/pull/2126
https://github.com/SAP/ui5-webcomponents/pull/2125
https://github.com/SAP/ui5-webcomponents/pull/2124

Best,
ilhan
