### ISSUE TITLE
ui5-popover: [BUG] ui5-popover displays error when Left is set to horizontalAlign attribute

### ISSUE THREAD

**Issue by Hubery-Shen** [SAP/ui5-webcomponents#2111]
Dear colleagues,

I am from Successfactors web experience Shanghai team.

**Describe the bug**
ui5-popover displays error when Left is set to horizontalAlign attribute
![popover](https://user-images.githubusercontent.com/63704163/90588879-4c41f800-e20f-11ea-81ef-621b49dddf65.png)

**Context**
UI5 Web Components version: 0.23.0
OS/Platform: macOS 10.15.6
Browser (if relevant): Microsoft Edge
Other information: screen reader - NVDA

Thanks
Hubery Shen

**Comment by ilhan007** [comment]
Hello @Hubery-Shen 

is it possible to send us URL where we can look at the issue or create a small example in codesandbox?

BR,
ilhan

**Comment by Hubery-Shen** [comment]
Hi @ilhan007 ,

sure, I will write a quick example for it later.
thanks for your support.

BR
Hubery Shen

**Comment by Hubery-Shen** [comment]
Hi @ilhan007 ,

I have created a quick example for this issue: [ui5-popover bug](https://github.com/Hubery-Shen/UI5-WebComponent-Examples)

**snapshot:**
![Screen Shot 2020-08-20 at 9 52 46 AM](https://user-images.githubusercontent.com/63704163/90708229-df406800-e2cb-11ea-838f-0201489c0159.png)

**code is:**

```
// Import React Framework
import React, { useEffect, useRef } from "react";

// Import UI5 libs
import "react-app-polyfill/stable";
import "@ui5/webcomponents/dist/Assets.js";
import "@ui5/webcomponents-icons/dist/Assets.js";

// Import Tested Component
import "@ui5/webcomponents/dist/Popover.js";

// Import CSS
import "./App.css";

function App() {
  const targetRef = useRef(null);
  const popoverRef = useRef(null);
  useEffect(() => {
    popoverRef.current && popoverRef.current.openBy(targetRef.current);
  }, []);
  return (
      <div className="App">
        <div ref={targetRef} id="target" style={{ width: "100%", height: "100px", background: "lightblue" }} />
        <div className="snippet">
          <ui5-popover ref={popoverRef} horizontal-align="Left" id="hello-popover" header-text="Newsletter subscription">
            <div className="popover-content">
              <div className="flex-column">
                <ui5-label htmlFor="emailInput">Email:</ui5-label>
                <ui5-input id="emailInput" className="samples-margin-top" placeholder="Enter Email" />
              </div>
            </div>
            <div slot="footer" className="popover-footer">
              <div style={{ flex: 1 }} />
              <ui5-button id="closePopoverButton" design="Emphasized">
                Subscribe
              </ui5-button>
            </div>
          </ui5-popover>
        </div>
      </div>
  );
}

export default App;
```
