### ISSUE TITLE
Wrong Import statement for Side Navigation

### ISSUE THREAD

**Issue by sassito** [SAP/ui5-webcomponents#2115]
**Describe the documentation issue**

- [ ] Documentation is unclear
- [X] Documentation is incorrect
- [ ] Documentation is missing
- [ ] Other

**Description of the issue**

In the documentation of the new Side Navigation the import statement is **import @ui5/webcomponents/dist/SideNavigation.js"**. But it's located in webcomponents-fiori.
(https://sap.github.io/ui5-webcomponents/playground/components/SideNavigation/)

So it has to be: **import @ui5/webcomponents-fiori/dist/SideNavigation.js"**

**Comment by ilhan007** [comment]
Already fixed:
see the "master" version of the documentation here:
https://sap.github.io/ui5-webcomponents/master/playground/components/SideNavigation/
