### ISSUE TITLE
About Title level

### ISSUE THREAD

**Issue by alex-zhang** [SAP/ui5-webcomponents#2134]
hi,

we use the title component in our component message-box.

I set  title level to 2 for a11y. but the UX told me, i make the wrong font size. 

![image](https://user-images.githubusercontent.com/4457451/91007341-4765b580-e60e-11ea-98ad-549f95e6b7e5.png)

but if i set the title level to 5, i got the correct font-size  it will cause the a11y  issue. (a11y should from h1 to h2, not h5 directly)

so i also to check the ui5 source code. i found that the message-box in ui5, also the tile component. but here it use the  **TitleLevel.Auto** which has the h2 tag and the correct font-size. 

https://sapui5.hana.ondemand.com/#/api/sap.ui.core.TitleLevel

![image](https://user-images.githubusercontent.com/4457451/91007498-b9d69580-e60e-11ea-8bce-ba32fd90d10a.png)

**Comment by ilhan007** [comment]
Yes, I see. You need level="H2", but with font-size of level="H5". Indeed, in openui5 there is TitleLevel.Auto that renders a div with aria-level="2" and font-size="1rem".

Would be also acceptable for you to set level="H2" (or nothing as H2 is by default) 
and in addition set a font-size of your choice?

For example:
```html
<ui5-title level="H2" style="font-size: var(--ui5_title_level_5Size)"
<ui5-title level="H2" style="font-size: 1rem"
```

This is not possible at the moment, but I just considering different solutions.


BR,
ilhan

**Comment by alex-zhang** [comment]
thanks. @ilhan007
