### ISSUE TITLE
label for should work for all input components

### ISSUE THREAD

**Issue by pskelin** [SAP/ui5-webcomponents#215]
**Describe the bug**
The "for" attribute of the label focuses correctly the associated element, but it should correctly point to the inner-most DOM element for the screen reader to work for all components besides the ui5-input

**To reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/Input/
2. Scroll to the section "Input with Label"
3. The label "for" attribute points to the internal input of ui5-input

**Expected behavior**
It should work for all kinds of input controls besides ui5-input.

**Context**
- UI5 Web Components version: master

**Comment by ilhan007** [comment]
Hello @pskelin,

I find them pretty much working

[Label_For_Input_Components.zip](https://github.com/SAP/ui5-webcomponents/files/2985434/Label_For_Input_Components.zip)
