### ISSUE TITLE
Side navigation bar for 2 elements is bigger than it should

### ISSUE THREAD

**Issue by arcanist123** [SAP/ui5-webcomponents#2156]
**Describe the bug**

I have defined a side navigation bar with 2 elements

<ui5-side-navigation>
  <ui5-side-navigation-item text="Recipes" icon="home"></ui5-side-navigation-item>
  <ui5-side-navigation-item text="Shopping list" icon="group"></ui5-side-navigation-item>
</ui5-side-navigation>

the line of navigation bar is too long
![image](https://user-images.githubusercontent.com/8202327/91653351-33073a00-eaa0-11ea-8202-e5481657cb66.png)

**To reproduce**
1. Create a new angular project
2. install webcomponents
3. set the app with the following content
<ui5-shellbar
  primary-title="Recipes">
</ui5-shellbar>

<ui5-side-navigation>
  <ui5-side-navigation-item text="Recipes" icon="home"></ui5-side-navigation-item>
  <ui5-side-navigation-item text="Shopping list" icon="group"></ui5-side-navigation-item>
</ui5-side-navigation>
4. run the project

**Isolated example**
Please provide an isolated example if possibile, by forking [CodeSandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html)

**Expected behavior**
The line should not be that long

**Screenshots**
![image](https://user-images.githubusercontent.com/8202327/91653351-33073a00-eaa0-11ea-8202-e5481657cb66.png)

**Context**
- UI5 Web Components version 1.0.0-rc.8
- OS/Platform: {windows}
- Browser *(if relevant)*: {chrome}
- Other information: {...}

**Affected components** *(if known)* side navigation bar

**Log output / Any errors** in the console N/A
```
{...}
```

**Comment by fifoosid** [comment]
Hello @arcanist123 

By design, the ```ui5-side-navigation``` should fill 100% of the height of its parent. The reason for this bug to happen is simple: the parent element of the Side Navigation doesn't have its height set. In order to fix this issue, try setting the height of the parent element.

Note: If the parent element is not DOM element, but Angular component(like app-root), you will have to set a position property as well.
