### ISSUE TITLE
How to include our UI5 webcomponent bundle by legacy UI5 code?

### ISSUE THREAD

**Issue by codefactor** [SAP/ui5-webcomponents#2168]
**Is your feature request related to a problem? Please describe.**
When we are on a UI5 legacy page, we were thinking to use UI5 to load the bundle at runtime lazily, to do so we have established a "fake" UI5 package like this:
```
window['sap-ui-config'] = {
  resourceRoots: {
    'xweb.common-webcomponents': '/verp/vmod_x/ui/common-webcomponents/resources_1.0.0-rc.26/dist/resources'
  }
};
```
Then if ever a UI5 file needs to run the bundle file, it simply needs to run something like this:
```
sap.ui.require(['xweb/common-webcomponents/bundle.esm'], function() {
  // do something
});
```
But this does not work, because `sap.ui.require` does not support es6 module script tags. It will work, though, if we use `es5` or some other thing like `iife` to bundle the file, but those come along with other issues because they are not optimal for modern browsers.

**Describe the solution you'd like**
Investigate if there is any better solution than the one described in the alternatives section.

**Describe alternatives you've considered**
```
// there might be a function that already exists that does this in UI5/jQuery somewhere
async function includeScript(src) {
  /* include a script tag, return promise for when the script is done loading. */
}
if (/* browser supports es6 modules */) {
  includeScript(sap.ui.resource('xweb/common-webcomponents', 'bundle.esm.js'));
} else {
  includeScript(sap.ui.resource('xweb/common-webcomponents', 'bundle.es5.js'));
}
```

**Comment by codeworrior** [comment]
The module `sap/ui/dom/includeScript` might be, what you're looking for:

```javascript
sap.ui.require(["sap/ui/dom/includeScript"], function(includeScript) {
    ...
    includeScript({
        // url: sap.ui.require.toUrl('sap/ui/integration/thirdparty/webcomponents/bundle.esm.js'),
        url: sap.ui.require.toUrl('xweb/common-webcomponents/bundle.esm.js'),
        attributes: {
            type: "module"
        }
    }).then(() => {
       // bundle has been loaded
    }, (err) => {
       // an error occurred
    });
});
```

**Comment by ilhan007** [comment]
Hello @codefactor 
did you try what Frank suggested, the `sap/ui/dom/includeScript` module?

BR,
ilhan

**Comment by ilhan007** [comment]
Closing the issue due to inactivity for more than 15 days, you can reopen the issue any time.

BR,
ilhan
