### ISSUE TITLE
Force all languages to download i18n files from server (including default language)

### ISSUE THREAD

**Issue by codefactor** [SAP/ui5-webcomponents#2169]
**Is your feature request related to a problem? Please describe.**
We need all i18n messages to be served through some dynamic back-end response in which all messages are generated dynamically and can contain tentant/company specific translations. Currently the i18n solution has the following issues:

1. It does not try to download anything for the default language (english) because it is built-in
2. It does not have a clean solution to identify a dynamic subdirectory where all the translations for a library should come from

**Describe the solution you'd like**
It might look something like this:

```
import { setMessageBundlePath } from "@ui5/webcomponents/path/to/file";

setMessageBundlePath("@xweb/common-webcomponents", "/messagebundle/BizXTest/vmod_1234/verp/ui/common-webcomponents/resources_1.0.0-rc.26/dist/resources")
```
Perhaps something like the above can already be done if we have implemented the solution to the issue https://github.com/SAP/ui5-webcomponents/issues/2167

But keep in mind that this path for the messagebundle in particular is slightly different than the normal "/resources" directory -- because the prefix includes "/messagebundle/BizXTest/vmod_1234/" which is a special prefix that redirects through a servlet that then downloads the last part of the url "/verp/ui/common-webcomponents/resources_1.0.0-rc.26/dist/resources/XXX.json" on the server side and then parses the file and re-translates it with customer-specific translations.

The above might not out of the box tell the i18n code to also download the messagebundle for the default language, but should at least tell when it does need to download the messagebundle it should do so starting from the above directory. Something else might need to be done to force the default language to download rather than going to the i18n-default.js which has hard coded english messages inside.

**Describe alternatives you've considered**
Already we have bypassed the i18n code in ui5/webcomponents entirely and implemented our own solution to getting messages. This works for us, but it would be great if we could use the out of the box UI5 web component library rather than utilizing our own i18n solution.

**Additional context**

**Comment by ilhan007** [comment]
Hi Scott, 

Regarding point 1 - It does not try to download anything for the default language:
with this #2175, the default language will be fetched over the network.

And, we will continue with point 2 - option to identify a dynamic subdirectory where all the translations for a library should come from.
