### ISSUE TITLE
Retro fit of UI5 Web Components into UI5 classic - initial setup

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents#2171]
We would like to have a reuse of UI5 Web Components into classic UI5 in the form of a library of UI5 controls that uses under the hood UI5 Web Components.

- [x] create a feature branch in openui5
- [x] create a new library within openui5
- [x] load and run the UI5 Web Components bundle
- [x] identify missing integration points

**Comment by vladitasev** [comment]
Current topics:
 - [] split the runtime into several groups
 - [] use UIArea for events?
 - [] how to access public APIs from OpenUI5?
 - [] test configuration synchronization more, implement common theme/language/etc... change logic

**Comment by ilhan007** [comment]
The initial set up for creating control wrappers + 3 new libraries of web components wrappers has been merged into OpenUI5 under the experimental flag and will be available with UI5 1.93.0 version:

- sap.ui.webc.commons
- sap.ui.webc.main (the control wrappers of UI5 Web Components "main" package - Button, Label, etc.)
- sap.ui.webc.fiori (the control wrappers of UI5 Web Components "fiori" package - FCL, ShellBar, etc.)
