### ISSUE TITLE
NotificationListItem doesn't follow Fiori Design Guideline

### ISSUE THREAD

**Issue by lenient** [SAP/ui5-webcomponents#2176]
**Describe the bug**
If you look at the [sample of NotificationListItem](https://sap.github.io/ui5-webcomponents/playground/components/NotificationListItem/) and compare it with the [description of Notifications of Fiori Design Guideline](https://experience.sap.com/fiori-design-web/notification-center/#types), you see that there are a few different places.

- The position of `Operation` isn't aligned with the `Headline`.
- There's no vertical indicator on the left for `Priority` property.
- There isn't a horizontal line between the `Headline` and `Subtitle` of NotificationListItem, but it's there from the mockup of the Fiori Guideline.

**Isolated example**
Refer to [sample of NotificationListItem](https://sap.github.io/ui5-webcomponents/playground/components/NotificationListItem/)

**Expected behavior**
The `NotificationListItem` should follow the description of the Fiori Design Guideline.

**Screenshots**
![image](https://user-images.githubusercontent.com/3073402/92066030-80064b80-edd3-11ea-92f6-d29955e44edf.png)

**Context**
- UI5 Web Components version: v1.0.0-rc.8

**Comment by ilhan007** [comment]
Hello @lenient 

- There's no vertical indicator on the left for Priority property.
_Actually the vertical line is the older design, it is replaced by icon indicator, place on the left side of the heading._

You can refer to the sample of the openui5 equivalent control:
https://openui5nightly.hana.ondemand.com/entity/sap.m.NotificationListItem/sample/sap.m.sample.NotificationListItem

The newest VD suggests (unfortunately the https://experience.sap.com/ has not been updated):

<img width="380" alt="Screenshot 2020-09-03 at 7 28 23 AM" src="https://user-images.githubusercontent.com/15702139/92071396-46274c00-edb7-11ea-84ac-e9c30a21e1c1.png">


- There isn't a horizontal line between the Headline and Subtitle
_Same_

- The position of Operation (I guess you men the action) isn't aligned with the Headline.

If you hover the button, you will notice that it is aligned perfectly, as it is bigger than the X you see.
<img width="417" alt="Screenshot 2020-09-03 at 7 37 31 AM" src="https://user-images.githubusercontent.com/15702139/92071840-791e0f80-edb8-11ea-9e52-bc21756fa97f.png">

**Comment by lenient** [comment]
@ilhan007 I'm fine with the first two items. But for the #3, as an end-user, I just see the Close button is lower than the `Headline`.

**Comment by ilhan007** [comment]
@lenient would not you see the button misaligned when you hover and press it from end user perspective. I will forward you feedback anyway to the reaponsible Visual Design team, but currently it is by design.
