### ISSUE TITLE
[IE]Button text will be truncated in IE

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents#2177]
**Describe the bug**
Button text will be truncated in IE. After the first time click, the text will fully show.

**To reproduce**
1. Use IE11 open page https://sap.github.io/ui5-webcomponents/playground/components/Button/
2. check below first image
3. click the truncated button, check below second button

**Screenshots**
<img width="1278" alt="BeforeClick" src="https://user-images.githubusercontent.com/13098801/92075801-d54e5700-edeb-11ea-9787-8f6dbf6c693b.png">
<img width="958" alt="AfterClick" src="https://user-images.githubusercontent.com/13098801/92075805-d8e1de00-edeb-11ea-9abf-3be07fbaa0e1.png">

**Context**
- UI5 Web Components version
- OS/Platform: {win10}
- Browser *(if relevant)*: {IE11}
- Other information: {...}

**Comment by ilhan007** [comment]
This issue might be related, has to be checked, whenever this one is processed:
https://github.com/SAP/ui5-webcomponents/issues/1999
