### ISSUE TITLE
Add other icon families

### ISSUE THREAD

**Issue by vladitasev** [SAP/ui5-webcomponents#2189]
Currently only `SAP-icons` are available. Start supporting other families such as TNT icons:
 - create the big JSON file from the original OpenUI5 icons
 - create a new package for each new icon family / or try to add them to the current icons package, but mind the implications, such as i18n, directory structure in the dist, .json file, etc...
- add missing icons from SAP icons family

**Comment by lohitghongadi** [comment]
Is there anyway to add icons from TNT namespace until the support comes out-of-box from ui5-webcomponents?
