### ISSUE TITLE
[BUG][RTL][Panel] The direction of arrow is error when the page is in RTL mode

### ISSUE THREAD

**Issue by Hubery-Shen** [SAP/ui5-webcomponents#2191]
**Dear colleagues,**
I am from SuccessFactors Web Experience Shanghai team.

**Bug Description**
1. The direction of arrow is error when the page is in RTL mode
<img width="686" alt="BUG  Panel RTL" src="https://user-images.githubusercontent.com/63704163/92448850-ca306800-f1eb-11ea-896d-acf5cefc3663.png">

**Comment by fifoosid** [comment]
Turned out that this is a Playground issue

**Comment by Milo-Shen** [comment]
Hi @fifoosid 
This is not only the playground issue but also the issue if we use this component in our project

**Comment by gmkv** [comment]
@Milo-Shen would you open a new issue if you still encounter this problem?
