### ISSUE TITLE
ui5-datepicker: does not handle some timezones and DST correctly

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#2202]
**Describe the bug**
The Datepicker selects the wrong year in some timezones.

**To reproduce**
1. Set your local timezone to PDT.
2. Go to https://sap.github.io/ui5-webcomponents/playground/components/DatePicker/
3. Inside the first Datepicker, type: `01.01.2020`
4. The Datepicker has selected the 01.01.2019 instead of 01.01.2020.

<img width="396" alt="Screenshot 2020-09-09 at 06 06 10" src="https://user-images.githubusercontent.com/9749730/92602133-95abc300-f262-11ea-8975-caffc3eb1f65.png">

For other timezones like CEST it is working as expected.
<img width="364" alt="Screenshot 2020-09-09 at 15 10 06" src="https://user-images.githubusercontent.com/9749730/92602546-1ec2fa00-f263-11ea-851f-a2bf3b6f93b1.png">

**Expected behavior**
The Datepicker should select the correct time in all timezones

**Affected components** *(if known)*
ui5-datepicker

**Original Issue**
https://github.com/SAP/ui5-webcomponents-react/issues/674

**Comment by Lukas742** [comment]
I just noticed that there is already a similar issue open for the `ui5-daterange-picker` (https://github.com/SAP/ui5-webcomponents/issues/2182). If it has the same source of the problem (what I suspect), please feel free to close this one.

**Comment by fifoosid** [comment]
This issue is still relevant.
