### ISSUE TITLE
Allow SAP-icons to be loaded from another location

### ISSUE THREAD

**Issue by vladitasev** [SAP/ui5-webcomponents#2205]
All .json resources
 - icons
 - CLDR
 - message bundles

**Comment by vladitasev** [comment]
Duplicate of: https://github.com/SAP/ui5-webcomponents/issues/2167

**Comment by jagadish-kb** [comment]
@vladitasev  #2167 talks only about configuring a different folder location within same origin. It does not mention about the location being a different origin. Can you please enhance the description of that issue to highlight that the source of the resources can even be an absolute URL hosted on an all-together different resource server.
