### ISSUE TITLE
Input field not read out by screen reader

### ISSUE THREAD

**Issue by pajakoo** [SAP/ui5-webcomponents#2206]
**Describe the bug**
Input field not read out by screen reader.

**To reproduce**
1. Run windows Narrator
2. Tab through components in the example

**Isolated example**
https://codesandbox.io/s/ui5-webcomponents-forked-rklef?file=/index.html

**Expected behavior**
When accessing any input field, the aria-label should read out.

**Context**
- UI5 Web Components version 1.0.0-rc.7
- OS/Platform: {...}
- Browser *(if relevant)*: {Chrome}
- Other information: {...}

**Affected components** *ui5-input*

**Comment by ilhan007** [comment]
Hello @pajakoo thanks for reporting and providing a sample.

We support the latest Jaws version (as a screen reader tool) and Chrome combination. 
Also our latest version is 1.0.0-rc.8 and we support our latest version only.

If you face the issue in 1.0.0-rc.8 on Chrome with Jaws, please reopen the issue and we will take over.

Best,
ilhan
