### ISSUE TITLE
ui5-table-column with attr "slot" error

### ISSUE THREAD

**Issue by FnEsc** [SAP/ui5-webcomponents#2207]
**Describe**
"\<ui5-table-column\>" with attr "slot" error in @vue/cli 4.5.4

**example**
```html
<ui5-table-column v-for="column of action.columns" :key="column.key" slot="columds">
              <div>
                <ui5-label>{{ column.name }}</ui5-label>
              </div>
          </ui5-table-column>
```

**Error**
Vue shows:
"error  `slot` attributes are deprecated  vue/no-deprecated-slot-attribute"

**Comment by fifoosid** [comment]
Hi FnEsc,

Could you provide the exact version of the following deps:
```
"vue"
"@vue/cli-plugin-babel"
"@vue/cli-plugin-eslint"
"@vue/cli-service"
```

**Comment by FnEsc** [comment]
Hi fifoosid, much appreciated and very nice to meet you. My versions look like as following below:

```shell

 npm ls vue
 -- vue@3.0.0-rc.10

 npm ls @vue/cli-plugin-babel
 -- @vue/cli-plugin-babel@4.5.4

 npm ls @vue/cli-plugin-eslint
 -- @vue/cli-plugin-eslint@4.5.4

 npm ls "@vue/cli-service
 -- @vue/cli-service@4.5.4
```

**Comment by ilhan007** [comment]
This is an eslint configuration in in Vue.js 2.6.0+
https://eslint.vuejs.org/rules/no-deprecated-slot-attribute.html

The docs suggests using "v-slot"
https://vuejs.org/v2/api/#slot-deprecated

Can you check it - it seems the issue is related entirely to Vue.

BR,
ilhan
