### ISSUE TITLE
The Component 'sap-ui-content-density' behavior is not correct in IE.

### ISSUE THREAD

**Issue by alex-zhang** [SAP/ui5-webcomponents#2211]
**Describe the bug**

The Component 'sap-ui-content-density' behavior is not correct in IE.

**Expected behavior**
The Component should have correct 'sap-ui-content-density' behavior in IE.

**Screenshots**
![image](https://user-images.githubusercontent.com/4457451/93033929-e197a700-f66a-11ea-9ac2-d64c11a7b01e.png)

**Context**
- UI5 Web Components version:  1.0.0-rc.8

**Comment by ilhan007** [comment]
Hello @alex-zhang 

yes, the compact size cant be applied in IE, it is currently a limitation. 

It is related to the fact that in IE CSS Variables definition works only when defined on the ":root" context and no other.
And for the content density we change the CSS Variables values (heights, widths, margins, paddings) when the class .ui5-content-density-compact is added, but this does not take effect in IE and the sizes remain the same (the cozy ones as they are defined on the :root).

this is working:
```css
:root {
  --input-height: 3rem;
}
```

but this does not:
```css
.ui5-content-density-compact {
  --input-height: 2rem;
}
```


we will keep the issue open and discuss a possible solution.


BR,
ilhan

**Comment by alex-zhang** [comment]
ok, thanks.
