### ISSUE TITLE
[Discussion]  Custom ListItem inner Button how to prevent the item-click event

### ISSUE THREAD

**Issue by alex-zhang** [SAP/ui5-webcomponents#2213]
hi, 

we used custom list item which has an inner button. when tab focus to the inner button, press space key. we expect only the the button click event is emitted and no item-click event.

we try to prevent the event stream by use `stopPropagation` in button event bubble phase. but it doesn't work.

below is the interactive demo:
 
![captured (4)](https://user-images.githubusercontent.com/4457451/93064545-3575b080-f6aa-11ea-9a25-e6fa41847875.gif)

below is the example link

https://github.wdf.sap.corp/pages/xweb/goalmanagementx/app.html?mock#/goal-detail?targetUserId=[object%20Promise]&templateType=cdp&templateId=583&id=17285

**Comment by ilhan007** [comment]
Hello @alex-zhang 

Did you try the followimg:
```js
myBtn.addEventListener("keyup", function(e) {
  e.stopPropagation();
});
		
myBtn.addEventListener("keydown", function(e) {
  e.stopPropagation();
});
```

It works on my side at least, so give it a try and get back to us.

BR,
ilhan

**Comment by alex-zhang** [comment]
hi, thanks for your reply.

yes, the new version is fine for these feature for keyboard. I test it in chrome, firefox , and safari.

But it cause a new issue, only in safari.  the chrome, firefox is fine.

![p3gj8-1h6l4](https://user-images.githubusercontent.com/4457451/139824833-78466b13-6879-4b0c-95e5-e40ac81dde19.gif)
