### ISSUE TITLE
Support for Server Side Rendering

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents#2240]
**Is your feature request related to a problem? Please describe.**
It would be awesome if the UI5 Web Components could support Server Side Rendering with popular frameworks like `Next.js`. We have received a [similar issue in the UI5 Web Components](https://github.com/SAP/ui5-webcomponents-react/issues/194) for React wrapper.

**Describe the solution you'd like**
I would like the use the UI5 Web Components in e.g. `Next.js` without the need of applying workarounds. Therefore, some APIs around `document` would need an abstraction to make sure they are not crashing during SSR and will be hydrated on the client.

**Describe alternatives you've considered**
It would be possible to use the UI5 Web Components already in Next.js when you are watching out very carefully where you are importing the components. Importing the `ui5-button` e.g. in a `useEffect` will enable you to render the button. But if you are now importing an `Icon`, it will crash because the icon import is accessing the `SharedElementRegistry` which is accessing `document` which is not defined during SSR.

**Additional context**
I played a bit around in the wrapper library in the [feat/support-ssr](https://github.com/SAP/ui5-webcomponents-react/tree/feat/support-ssr) branch.

**Comment by jmoors** [comment]
Looking at the roadmap it seem there is a plan to support for server-side rendering in Q4, is this still on track? With the advent of Next.js and Remix.run the ability to support SSR would be really useful.

**Comment by luizcarlospedrosogomes** [comment]
news?

**Comment by MarcusNotheis** [comment]
The [Declarative Shadow DOM](https://web.dev/declarative-shadow-dom/) API sounds promising, but is unfortunately only supported in Chromium browsers at the moment: https://caniuse.com/declarative-shadow-dom

**Comment by ilhan007** [comment]
Closing the issue in favour of https://github.com/SAP/ui5-webcomponents/issues/6626
