### ISSUE TITLE
DatePicker enhancements - part 2

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents#2244]
- [x] When min & max date are set, the arrows of the year picker should be disabled when the min/max year is reached.
- [x] When min & max date are set, the arrows of the month picker should disable when the min/max year is reached and without cycling the years.
- [x] When month picker is opened, in the CalendarHeader only one button should be present - button for the year

**Comment by tsanislavgatev** [comment]
First two are done with #2307
