### ISSUE TITLE
[IE]Button text still was truncated in IE 

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents#2245]
Describe the bug
Button text will be truncated in IE. 

To reproduce

Use IE11 open page https://github.wdf.sap.corp/pages/xweb/goalmanagementx/app.html?mock#/goal-detail
<img width="1791" alt="2020-09-25_16-25-53" src="https://user-images.githubusercontent.com/13098801/94244714-de929580-ff4b-11ea-8abe-fd7a5520e573.png">

**Context**
UI5 Web Components version 0.23.2
OS/Platform: {win10}
Browser (if relevant): {IE11}
Other information: {...}

**Comment by fifoosid** [comment]
Hello @GongRichard 

What you are experiencing currently is an IE 11 bug that is related to
```css
display: flex;
width: auto;
```

In order to make your use case work, you can set
```css
flex: 100%
```
Or if you prefer
```css
flex: 1 1 100%;
```
to the wrapping div, which already has ```display: flex```.
