### ISSUE TITLE
Overflow Toolbar

### ISSUE THREAD

**Issue by lateefsofi** [SAP/ui5-webcomponents#2249]
**Describe the solution you'd like**
It would be great if Overflow toolbar is implemented here. It would be helpful for responsive layout.
You can find the same functionality in [UI5 Overflow toolbar](https://sapui5.hana.ondemand.com/#/entity/sap.m.OverflowToolbar/sample/sap.m.sample.OverflowToolbarSimple) which we expect to be implemented in web components.

**Comment by ilhan007** [comment]
Hello @lateefsofi we already have a request for the Overflow Toolbar, it is considered and mostly likely implemented in future, but not short or mid term.

The issue that you can keep tracking is: https://github.com/SAP/ui5-webcomponents/issues/333

BR,
ilhan
