### ISSUE TITLE
i18n for Vue: translated text not loaded

### ISSUE THREAD

**Issue by miyasuta** [SAP/ui5-webcomponents#2250]
**Describe the documentation issue**

- [X] Documentation is unclear
- [ ] Documentation is incorrect
- [ ] Documentation is missing
- [ ] Other

**Description of the issue**
I'm new to UI5 Web Components and Vue.
I'm trying to implement i18n functionality by following the document below .
https://sap.github.io/ui5-webcomponents/playground/docs/i18n/
I have cloned the sample project for Vue and added config as described in the document.
https://github.com/SAP-samples/ui5-webcomponents-sample-vue

[Here](https://github.com/miyasuta/webcomponents-test) is my github repo.

The issue is, the console shows "PLEASE_WAIT", instead of the corresponding text (Please wait).
![image](https://user-images.githubusercontent.com/39408125/94360553-1420b580-00e9-11eb-94ca-dbdf0c3238b5.png)

I debugged getText function and found the variable "bundle" was receiving below html message.

`sorry but ui5-webcomponents-sample-vue doesn't work properly without JavaScript enabled. Please enable it to continue.`

![image](https://user-images.githubusercontent.com/39408125/94360545-053a0300-00e9-11eb-9fc8-d1bbeb16967d.png)

The app runs on Chrome and for Chrome, JavaScript is enabled.
Maybe some settings are missing for my project? 

Regards,
Mio

**Comment by fifoosid** [comment]
Hi @miyasuta 

[Here](https://vuejs-templates.github.io/webpack/static.html) you can check the Vue docs related to static assets.

What you can do in order to fix your problem is make the following file structure(in the above link it is explained why your dependencies should be in the ```src``` folder)
![image](https://user-images.githubusercontent.com/16850339/95962195-b8576b80-0e0e-11eb-8eb9-5eb42d84593e.png)

In your App.vue file add the following lines in order to load translations correctly:
```js
registerI18nBundle("myApp", {
				de: "./i18n/messagebundle_de.properties",
				en: "./i18n/messagebundle_en.properties",
			});

			await fetchI18nBundle("myApp");

			const bundle = getI18nBundle("myApp");

			const pleaseWait = bundle.getText("PLEASE_WAIT");
			console.log("Please wait in the current language is: ", pleaseWait);
```

**Comment by miyasuta** [comment]
Hi @fifoosid .

Thank you for your comment.
I tried your solution, but the still the same result.
I have updated my GitHub repo. https://github.com/miyasuta/webcomponents-test
If you have a working example, could you share the source?

Regards,
Mio

**Comment by fifoosid** [comment]
Hi @miyasuta 

I have uploaded your code [here](https://github.com/fifoosid/ui5-vue-translations). You can check the last commit in order to see how the translations are implemented.

**Comment by miyasuta** [comment]
Hi Hi @fifoosid 

Thanks for the code.
I could see the translation working!
