### ISSUE TITLE
Module not found: Error: Can't resolve '@ui5/webcomponents/dist/MultiInput'

### ISSUE THREAD

**Issue by mjhidalgo** [SAP/ui5-webcomponents#2251]
**Describe the bug**
It seems like the mentioned component is not available on the last version installed (8)

It can be officially found in the documentation, which is oddly confusing:
https://sap.github.io/ui5-webcomponents/master/playground/components/MultiInput/

**To reproduce**
1. Add the import to the desire page or component where must be used (import "@ui5/webcomponents/dist/MultiInput")
2. Run your project with the command of your preference (npm start, etc)
3. The error appears

**Comment by ilhan007** [comment]
The link shows the what is merged in the "master" branch
https://sap.github.io/ui5-webcomponents/master/playground/components/MultiInput/

This is the link that shows what is available in our public releases (currently latest version is 1.0.0-rc.8)
https://sap.github.io/ui5-webcomponents/playground/

The MultiInput will be part of the upcoming RC.9 release. To use the MultiInput you can use our @ next tag releases in npm.

You can lear more about our different versions here:
https://github.com/SAP/ui5-webcomponents/projects

BR,
ilhan

**Comment by mjhidalgo** [comment]
Thanks man!

**Comment by mjhidalgo** [comment]
@ilhan007 It wasn't clear enough for me if there's a way to use a beta or early version that includes the MultiInput, what do you mean by @ next tag releases? -Or should I just wait for the next release?

Thanks in advance!
