### ISSUE TITLE
[ui5-multi-combobox] not align vertically

### ISSUE THREAD

**Issue by nnaydenow** [SAP/ui5-webcomponents#2259]
**ui5-multi-combobox** is not vertically centered to other input controls.

![image](https://user-images.githubusercontent.com/31909318/94434446-77225300-01a2-11eb-8da7-5073504f638f.png)

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-rl I am forwarding this old issue to you, just FYI.

**Comment by d3xter666** [comment]
Hi @nnaydenow ,

Could you provide a snippet with this sample?

Cheers

**Comment by nnaydenow** [comment]
HI @d3xter666,

The issue is reproducible in this sample:
https://codesandbox.io/s/ui5-webcomponents-forked-2ykyt?file=/index.html

Also in the test page of the MultiInput if the components are placed inline.

**Comment by d3xter666** [comment]
Hi colleagues,

As it seems, this is not tightly related to the ComboBox but is valid for all the controls which have CSS flexbox elements nested. 
From that perspective, it would be good to do this as something for the whole framework.

Cheers
