### ISSUE TITLE
[ui5-multi-multicombobox] unnecessary space

### ISSUE THREAD

**Issue by nnaydenow** [SAP/ui5-webcomponents#2260]
Unnecessary space between last token and more button.

**Exptect:**
More button should be placed right to the last visible token
![image](https://user-images.githubusercontent.com/31909318/94434783-f9127c00-01a2-11eb-8f44-a774b071fe75.png)

**Comment by Martotko** [comment]
Тime should be set aside for this.

**Comment by nikolay-kolarov** [comment]
Hi,

I am closing this one, as it is not reproducible anymore:
![image](https://user-images.githubusercontent.com/17043004/161911123-c81691d0-e1e1-4cc1-b5f1-421e92c34454.png)

Best Regards,
Nikolay
