### ISSUE TITLE
Dialog is covered by blocking layer

### ISSUE THREAD

**Issue by m-ignatov** [SAP/ui5-webcomponents#2264]
**Describe the bug**
When a UI5 dialog is a child of a UI5 Popover, opening the dialog results in a blocking layer over it.

**Isolated example**
[CodeSandbox](https://codesandbox.io/s/ui5-webcomponents-forked-7f9lv?file=/index.html)

**Screenshots**
![image](https://user-images.githubusercontent.com/36794374/94440417-5bbb4600-01aa-11eb-8a28-3851463810af.png)

**Context**
- UI5 Web Components version: 1.0.0-rc.8

**Comment by fifoosid** [comment]
Hello @m-ignatov 

As you can read in our [docs](https://github.com/SAP/ui5-webcomponents/blob/master/packages/main/src/Dialog.js#L101), nesting popups is not recommended.

A solution to this issue would be to have the ```ui5-popover``` and ```ui5-dialog``` on the same level as shown in this [example](https://codesandbox.io/s/ui5-webcomponents-forked-bv3tg?file=/index.html). This way you will keep the desired functionality, but the issue will not be present.
