### ISSUE TITLE
Users should be able to set icons with the unicode ID too

### ISSUE THREAD

**Issue by vladitasev** [SAP/ui5-webcomponents#2271]
https://openui5.hana.ondemand.com/test-resources/sap/m/demokit/iconExplorer/webapp/index.html#/overview/SAP-icons/?tab=grid&icon=accept

Icons from the icon explorer have a name and a unicode ID:
![image](https://user-images.githubusercontent.com/15844574/94652221-55d87880-0302-11eb-9ed2-f1e6651fa819.png)

Some existing apps have user-defined content, where users have configured the icons by unicode IDs and not names. These apps need a way to support this with `ui5-icon`.

Add a `unicode` field to `SAP-icons.json` and allow passing the unicode ID as the value of the `name` property of `ui5-icon`.

**Comment by ilhan007** [comment]
It was decided not to support unicodes within the ui5-icon. Custom solution at stakeholder site would be planned and donee instead.
