### ISSUE TITLE
Allow users to set a custom z-index on popups

### ISSUE THREAD

**Issue by vladitasev** [SAP/ui5-webcomponents#2306]
If a page has defined its own z-indices such as 1000 or 10000, dialogs appear below them. So it makes sense for apps to be able to somehow define the initial z-index of the static area, or z-index per popup.

Explore solutions.

**Comment by oscargong** [comment]
Do we have any update on this?

**Comment by heshiweij** [comment]
Hello UI5 Team:

I am from the SAP Workzone team and we have encountered an issue while using @ui5/webcomponents. We are unable to set a custom z-index on popups. Our own dialog already has a z-index of 1000, which is causing us to be unable to use the Select component from @ui5/webcomponents on the dialog. We had to implement our own Select component. I would greatly appreciate it if you could fix this issue.

BR,
Shiwei(shiwei.he01@sap.com)

**Comment by oscargong** [comment]
Hi, this is Oscar from SAP Ariba Sourcing team. This issue is also critical for our product. In Guided Sourcing, the global dialog z-index is `1000` too.

Also, @heshiweij , here is the workaround we used. Hope it is helpful.

![Oscar ScreenCapture 2023-08-21 at 12 26@2x](https://github.com/SAP/ui5-webcomponents/assets/7035787/1464ce37-5c99-4120-8f59-d3cd8bf10b66)

Best,
Oscar (o.gong@sap.com)

**Comment by ilhan007** [comment]
Hi colleagues @oscargong @heshiweij thank you for your input, we are raising the priority of the issue. We will touch it probably next week to discuss a possible API for controlling the z-index.

**Comment by I543348** [comment]
Hi Team, Could you pls provide some updates by when can we expect the fix for this one?
Thanks much
cC: @oscargong

**Comment by vladitasev** [comment]
Hello colleagues,

1. For the "two-part" components that have an "input" part and a "static area" part (Select, ComboBox, DatePicker, etc...) you can add for example the following CSS to your page already today:

```css
ui5-static-area {
  position: relative;
  z-index: 1001;
}
```

So, if your own popup has a z-index of 1000, the static area will be with a higher z-index, and all select/datepicker/etc. menus will appear on top, because even though they all have z-index values, they are all grouped up in the static area, and if you create a stacking context for the static area itself (with CSS similar to the one above), you can basically manipulate all static area content at once.

2. However, for components such as `ui5-toast`, or `ui5-popover` that don't have 2 parts, but rather just a "popup" part, and don't use the static area, we currently don't provide a solution to that problem. There are several ways to go about it, all having pros and cons.

We have however prioritized this and will discuss how we want to proceed at our regular round tomorrow. I'll get back to you once we've settled on a solution.

Regards,
Vladi

**Comment by vladitasev** [comment]
Please check the following example:
https://codesandbox.io/s/ui5-webcomponents-forked-n7pv9j

Also, edited the previous comment with more info on 2.

Regards,
Vladi

**Comment by vladitasev** [comment]
This issue is now obsolete. Since version `2.0.0` UI5 Web Components switched to the Popover API:
 - all of our popups now appear above all other elements on the page natively, by order of appearance, no extra work is needed by the app
 - if you are also using non-native popups (not based on the Popover API), in addition to the UI5 Web Components-based popups, and want them to appear above UI5 Web Components-based popups, the only possibility is to make the third party popups also use the Popover API
 
How to make a third-party popup use the Popover API:
 -  After you open it, set the `popover` attribute to `manual` on the top-level element of the said popup
 -  Call `showPopover()` on the element you set the `popover` attribute to
 - Optionally, you might need to set the `:popover-open { inset: unset; }` CSS selector on your page, depending on the coordinate system, used by the third-party popup for positioning
