### ISSUE TITLE
DatePicker Enhancements - Part 3

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents#2313]
- [ ] When year picker is opened, in the CalendarHeader only one label should be present - label with the first - last shown year & arrows to navigate within years

**Comment by ilhan007** [comment]
Blocked as the team  @SAP/ui5-webcomponents-topic-b expects further UX input

**Comment by DMihaylova** [comment]
To be tracked [here](https://github.com/SAP/ui5-webcomponents/issues/3200) where the same is requested.
