### ISSUE TITLE
ui5-dialog: Dialog footer border disappears on high contrast themes

### ISSUE THREAD

**Issue by mihaela96** [SAP/ui5-webcomponents#2333]
Hi :) 
So our team are currently implementing switching theme functionality and we are facing some issues.
In all dialogs, footer border disappears when we change a theme to high contrast (black or white). Also we noticed that buttons are not right-aligned (As they are required from sap fiori guidelines). In addition, we put our button for footer in div  with slot='footer' as in example.

Here is a dialog from ui5-components playground ->
![dialog1](https://user-images.githubusercontent.com/11721482/95586212-094f1480-0a49-11eb-9c03-683cf41e501c.PNG)
And here is the example design we want to achieve -> 
![dialog2](https://user-images.githubusercontent.com/11721482/95586272-2257c580-0a49-11eb-9f0d-5f6652afc23e.PNG)

Are you planning to fix this ? :) 

Thanks,
Best regards, Mihaela.

**Comment by ilhan007** [comment]
The footer is a public slot that you can add arbitrary content and it is up to you to align the buttons according to the desired design. If you need to have them on the right, use <div style="display: flex: justify-content: flex-end" or other CSS approach to align childs in a container.

The footer separator line is a bug and this will be fixed.

**Comment by gmkv** [comment]
Hello. The footer separator line bug turned out to be a issue in the [theming library](https://github.com/SAP/theming-base-content) we use for color parameters. The corrected colors will be included in version 11.2.24 of the theming library, which we'll upgrade to once it gets released.

**Comment by gmkv** [comment]
@mihaela96 Timeline suggests this fix would be included with ui5-webcomponents release candidate 11.
