### ISSUE TITLE
AncorTab, Ghost button type, Slider 

### ISSUE THREAD

**Issue by mihaela96** [SAP/ui5-webcomponents#2336]
Hi :) 
I want to ask are there any plans for adding these new components (AncorTab and Slider) and properties (Ghost button type).
Here is the corresponding sap ui5 elements:

AncorTab -> https://openui5.hana.ondemand.com/entity/sap.uxap.ObjectPageLayout/sample/sap.uxap.sample.AnchorBar
Ghost button type -> https://openui5.hana.ondemand.com/api/sap.m.ButtonType#properties
Slider -> https://openui5.hana.ondemand.com/entity/sap.m.Slider/sample/sap.m.sample.Slider

Best regards,
Mihaela

**Comment by ilhan007** [comment]
The Slider (RangeSlider will be also implemented mid term) is planned and already started: https://github.com/SAP/ui5-webcomponents/issues/1245

The AnchorBar - not planned short or mid-term, but it's possible to develop it

The Ghost type - no, we try to keep the set of types straightforward, the same goes for  "Up", "Back', "Unstyled"
Maybe we will add one or two more, but if so - it will be  one of these: "Success", "Critical" or "Warning".

The following styles make from the default button a "ghost" one:
ui5-button.ghost:not([active]) {
  background: transparent;
}
ui5-button.ghost {
 border-color: rgba(8,84,160,0.5); // the --sapButton_BorderColor(#0854a0) faded
}

**Comment by mihaela96** [comment]
Hi,
Thanks! Sounds perfect for the slider and thanks for the tips how we can achieve the “ghost” look of the button.
Regarding the “Anchor” tab bar, we need it for few reasons:
We have an onboarding wizard for our customers when they use our tool for the first time and need to provide some information, in order to configure it. However, we can’t achieve the complete look & feel of the UI5 wizard without this anchor tab bar and use simple tabs instead.
We recently added the User Settings dialog. Currently it contains only the themes, but in the future we plan to add other settings as well and we follow the visual specifications described here and again the anchor tab bar is needed: https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2104434679
We also use this pattern in other more complex dialogs
 
Any help from you would be welcome :)
Thanks!
