### ISSUE TITLE
ui5-Avatar is not working on mobile simulator

### ISSUE THREAD

**Issue by Knightofhonour** [SAP/ui5-webcomponents#2337]
**Describe the bug**
The ui5-Avatar shows up perfectly as intended on a desktop web browser. However, it is not displayed when rendered on a mobile simulator web browser

**To reproduce**
https://github.com/Knightofhonour/ui5-Avatar
git clone the repo
unzip the node modules zip file
run command parcel src/index.html
check local host on both a mobile simulator and on desktop browser

**Isolated example**
Please provide an isolated example if possibile, by forking [CodeSandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html)

**Expected behavior**
The ui5-Avatar should be rendered on the mobile browser

**Screenshots**
![image](https://user-images.githubusercontent.com/48403373/95697349-059dd680-0c71-11eb-98fc-a626b5a9da7c.png)
![image](https://user-images.githubusercontent.com/48403373/95697360-12222f00-0c71-11eb-9704-c3e070285fdd.png)

**Context**
- UI5 Web Components version
- OS/Platform: {...}
- Browser *(if relevant)*: {...}
- Other information: {...}

**Affected components** *(if known)*

**Log output / Any errors** in the console
```
{...}
```

**Comment by ilhan007** [comment]
Hello @Knightofhonour 
thanks for the issue and steps.

I followed the steps and I opened the index.html,
but the "index.html" does not have an avatar. 

However, I added one, referencing "map_icon.png" (image that I found):
```html
<ui5-avatar image="./map_icon.png"></ui5-avatar>
```
but the avatar does not show on desktop as well, I guess this is something related to the server not serving the images with the expected paths


<img width="977" alt="Screenshot 2020-10-12 at 10 06 46 AM" src="https://user-images.githubusercontent.com/15702139/95715493-a5a82f80-0c72-11eb-8ccd-88030ec0a64e.png">


Best,
ilhan

**Comment by Knightofhonour** [comment]
Hi @ilhan007 ,

For my side, even if an invalid image is used, a blue circle will appear where the avatar should be (for Desktop). In the mobile simulator, this blue circle does not appear at all, which leads me to think that its an issue of desktop vs mobile.

Is this meant to be an intended output?

Thank you,
David Ong

**Comment by ilhan007** [comment]
No, not intended, the avatar should be displayed both on desktop and phone. 
The thing is that when I run the referenced project, I can not see anything on desktop tool. I will create a condesandbox sample to check if there is such issue.

**Comment by ilhan007** [comment]
Hello @Knightofhonour 

can you access this codesandbox emaxple:
https://b8km3.csb.app/

It shows an avatar and it is visible on both desktop and Chrome phone emulator.

The code is [here](https://codesandbox.io/s/ui5-webcomponents-forked-b8km3?file=/index.html).

**Comment by Knightofhonour** [comment]
Hi @ilhan007 ,

Although it works in sandbox, I am unable to replicate it locally. Attached are some screenshots of my code and output.
![image](https://user-images.githubusercontent.com/48403373/95725883-c9876780-0caa-11eb-8df7-4b19fbd5f763.png)
![image](https://user-images.githubusercontent.com/48403373/95725929-d6a45680-0caa-11eb-94a2-10175f258602.png)
![image](https://user-images.githubusercontent.com/48403373/95725963-e459dc00-0caa-11eb-8310-4b656413460e.png)
![image](https://user-images.githubusercontent.com/48403373/95726009-f20f6180-0caa-11eb-8ef0-7a543b9499ee.png)

Are you able to advise a solution for this?

Thank you,
David Ong
