### ISSUE TITLE
Content associated with a ui5-messagestrip read out twice by the screenreader

### ISSUE THREAD

**Issue by rama1990br** [SAP/ui5-webcomponents#2348]
**Describe the bug:**
Content associated with a ui5-messagestrip read out twice by the screenreader

**Steps to reproduce the behavior:**
Go to https://sap.github.io/ui5-webcomponents/playground/components/MessageStrip/
Start up the screenreader (NVDA/Jaws)
Tab over to the close button on any of the message strips on the page
Notice that the content associated with the message strip is read out twice (as can be seen in the screenshot below)

<img width="1680" alt="ui5-messagestrip" src="https://user-images.githubusercontent.com/32254036/95784641-10646580-0c89-11eb-8c2c-098dd7cbc7ed.png">

**Expected behavior**
The content should only be read out once and not repeated.

**Comment by stoehr** [comment]
@rama1990br filed this issue for SuccessFactors, so can the "SF" label be added to this issue?
