### ISSUE TITLE
DatePicker crashes when dealing with future years

### ISSUE THREAD

**Issue by stevetsanders** [SAP/ui5-webcomponents#2353]
**Describe the bug**
DatePicker crashes when dealing with future years

**To reproduce**
Click on the datepicker in the codesandbox

**Isolated example**
https://codesandbox.io/s/wonderful-hooks-ip6r5?file=/src/App.js

**Expected behavior**
I expect the datepicker not to crash.

**Screenshots**

**Context**
- UI5 Web Components version: 1.0.0-rc.9
- OS/Platform: windows
- Browser *(if relevant)*: edge (chromium)
- Other information: {...}

**Affected components** *(if known)*

**Log output / Any errors** in the console
```
{...}
```

**Organization:** *(if applicable)*

**Priority:** *(optional)* *(Low, Medium, High or Very High)*

Setting priority would indicate the importance of the issue
and would help the process of dispatching and processing.

To set the appropriate priority, you need to consider the impact
and if the issue:
- Breaks entire application or system - High and Very High
- Is accessibility one (Screan Reader, Keyboard Handling) - Medium and High
- Is functional one and makes a single component unusable - Medium and High
- Is visual, styling one - Low and Medium

Note: the priority would be re-evaluated by the issue processors, according to the project internal criterias

**Business impact:** very high (dealing with future years is a common use case for us). Can't upgrade to latest version if this is not fixed for us.

**Comment by ilhan007** [comment]
Hello @stevetsanders
thanks for reporting this.

It seems the bug appears when the maxDate is not set and it is later fixed with: https://github.com/SAP/ui5-webcomponents/pull/2307
However, the pull request is merged few days after the RC.9 release
and it is part of the last "next" tag release (0.0.0-f9b9eadb8)

BR,
ilhan

**Comment by stevetsanders** [comment]
Thanks @ilhan007 ,

Is there any planned date for a next "latest" release?

**Comment by ilhan007** [comment]
Hello @stevetsanders 

RC.10 should be released in the first week of November, the next one - start of December, eg monthly
