### ISSUE TITLE
TabContainer: Tab height is not 100%

### ISSUE THREAD

**Issue by mathlizee** [SAP/ui5-webcomponents#2354]
Hi,

When using a TabContainer, I can't find a way to center vertically the content of a tab. [Here ](https://codesandbox.io/s/tab-height-0bbyk?file=/src/App.js)is a sample to demonstrate the issue.

From what I've found, in previous versions of the web components, the tab's height was as big as possible, taking all available space inside the TabContainer. It seems that in the new version of the web components (1.0.0-rc9), it is no longer the case and the tab's height is now defined by its content.

To center the content of the tab vertically, the tab's height needs to fill the TabContainer. However, even when I try to set the tab's height to 100%, I am not able to achieve the wanted behavior.

Could you provide a fix or a work-around?

Thank you!
Math

**Comment by ilhan007** [comment]
Hello @MarcusNotheis @mathlizee,

I tracked down when that change happened:
the "height: 100%" has been removed with this PR https://github.com/SAP/ui5-webcomponents/pull/2148 that fixes the following issue https://github.com/SAP/ui5-webcomponents/issues/2144, reported by @MarcusNotheis - "ui5-tabcontainer: Scrollbars on empty container".

The solution with "addCustomCSS", adding '"ui5-tc__contentItem { height: 100%; }" CSS is a good workaround, that will work for your case as it brings back the style, removed by the mentioned PR.

From our side, we can think of another solution to fix the current issue and keep the old fixed at the same time (ui5-tabcontainer: Scrollbars on empty container).

BR,
ilhan
