### ISSUE TITLE
Implementation of <ui5-select> does not seem to be compliant with w3c norms for a listbox for accessibility

### ISSUE THREAD

**Issue by rama1990br** [SAP/ui5-webcomponents#2358]
**Describe the bug:**
Implementation of \<ui5-select\> does not seem to be compliant with w3c norms for a listbox for accessibility. 
1) The list boxes behave like button menus ie role "button" is announced when these list boxes are in focus. However when the menu opens by activating spacebar, the role "listbox" is not heard because aria-roledescription "select" has been used. Hence the expanded/collapsed state change is also not recognized.

![image](https://user-images.githubusercontent.com/32254036/96055266-6deae480-0e38-11eb-9b4a-3fceee976b2f.png)

2) Everytime any action is performed such as closing the list boxes, opening list boxes or removing selections, the role "modal dialog" is heard again which could be quite confusing to screen reader users

![image](https://user-images.githubusercontent.com/32254036/96055288-7f33f100-0e38-11eb-94dd-242f2b9732ea.png)

**Expected behavior:**
Ref: https://w3c.github.io/aria-practices/examples/listbox/listbox-collapsible.html

![image](https://user-images.githubusercontent.com/32254036/96055307-94a91b00-0e38-11eb-81bc-cbc4a84701ad.png)

In this implementation of button menu, as seen in the screenshot above
1) the role "button menu" must be heard when the list boxes are in focus
2) when the menu opens, the role of "listbox" must be heard so a screen reader user can infer that the list has opened
3) Once a selection has been made, the selected list item along with the label of the field (as its in focus again now)
must be announced

**Steps to reproduce the behavior:**
Go to https://sap.github.io/ui5-webcomponents/playground/components/Select/
Start up the screenreader (NVDA/Jaws)
Tab over to any of the select boxes on the page
The behaviour is as described in the points in the 'Describe the bug' section above

**Comment by stoehr** [comment]
@rama1990br filed this issue for SuccessFactors, so can the "SF" label be added to this issue?

**Comment by ilhan007** [comment]
> @rama1990br filed this issue for SuccessFactors, so can the "SF" label be added to this issue?

Sure, I added it

**Comment by jdichev** [comment]
Hello, the issue is being worked on.
Internal reference: 4888
