### ISSUE TITLE
[Avatar]: Image not loading

### ISSUE THREAD

**Issue by mathlizee** [SAP/ui5-webcomponents#2359]
Hello,

I'm trying to use an avatar and setting its image using an URL. However, the Avatar control throws a 404 error when trying to fetch the image, even if the URL is correct.

Here is the URL of my image: [https://s.gravatar.com/avatar/17b0ec16ebafd9b487da2f65ff235c17?s=480&r=pg&d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Fpa.png](https://s.gravatar.com/avatar/17b0ec16ebafd9b487da2f65ff235c17?s=480&r=pg&d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Fpa.png)

And here's a [sample ](https://codesandbox.io/s/avatar-image-source-1vn88?file=/src/App.js)of an avatar that uses this URL. As you can see, the image does not load. 

I'm using the latest version of the library. I know that I'm also using the React wrapper of the UI5 components, but since the Avatar control is developped by your team, I thought I should create an issue in this repo.

Could this be fixed? I know it used to work in a previous version, but I can't tell which one...

Thank you!
Math

**Comment by ilhan007** [comment]
Hello @mathlizee 

the real URL of the image is https://i0.wp.com/cdn.auth0.com/avatars/pa.png?ssl=1
and I changed the "image" property to point to that one. 

with ui5-avatar
<img width="780" alt="Screenshot 2020-10-15 at 8 06 40 AM" src="https://user-images.githubusercontent.com/15702139/96079433-6de0f800-0ebd-11eb-8175-bb8369d470cd.png">

with Avatar wrapper
<img width="772" alt="Screenshot 2020-10-15 at 8 11 55 AM" src="https://user-images.githubusercontent.com/15702139/96079749-3161cc00-0ebe-11eb-8652-46ac0cd43f99.png">

When I open the one you provided: 
https://s.gravatar.com/avatar/17b0ec16ebafd9b487da2f65ff235c17?s=480&r=pg&d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Fpa.png

the URL changes in the URL bar and also if you use "copy img address", you get:
https://i0.wp.com/cdn.auth0.com/avatars/pa.png?ssl=1

There is no issue from ui5-avatar or the Avatar wrapper.

BR,
ilhan
