### ISSUE TITLE
Combobox flickers continuous when you open the drop-down 

### ISSUE THREAD

**Issue by f-zou** [SAP/ui5-webcomponents#2365]
**Describe the bug**

Combobox flickers when you open the drop-down 

**To reproduce**
1. use Combobox :
<ui5-combobox placeholder="Enter value">
	<ui5-cb-item text="Item 1"></ui5-cb-item>
	<ui5-cb-item text="Item 2"></ui5-cb-item>
	<ui5-cb-item text="Item 3"></ui5-cb-item>
</ui5-combobox>

**Expected behavior**
the drop-down can be open by clicking arrow or by pressing f4. 
but not. the drop-down list flickers continuous.

**Context**
- UI5 Web Components version "1.0.0-rc.9",
- OS/Platform: {macos} 
- Browser *(if relevant)*: {chrome} 
- Other information: {...}

**Affected components** *(if known)*

**Log output / Any errors** in the console
```
{...}
```

**Organization:** *(furo.pro)*

**Priority:** *(optional)* *(Low, Medium, High or Very High)*

Setting priority would indicate the importance of the issue
and would help the process of dispatching and processing.

To set the appropriate priority, you need to consider the impact
and if the issue:
- Breaks entire application or system - High and Very High
- Is accessibility one (Screan Reader, Keyboard Handling) - Medium and High
- Is functional one and makes a single component unusable - Medium and High
- Is visual, styling one - Low and Medium

Note: the priority would be re-evaluated by the issue processors, according to the project internal criterias

**Business impact:** *(mandatory for "Very High")*

**Comment by ilhan007** [comment]
Hello @f-zou 

It does not happen at least on https://sap.github.io/ui5-webcomponents/playground/main/pages/ComboBox/
I can't see steps to reproduce the issue, could you add some more info how to observe this flickering.

Best,
ilhan

**Comment by f-zou** [comment]
Hallo @ilhan007 
your example has no shadowdom. 
wen you use ui5-combobox als webComponent in a shadowRoot. There is the problem. 
I have check the source code of the combobox.js. on line 424 'this.focused = this === document.activeElement;' 
that means the combobox will never be foucused by opening dropdown. because "If your shadow DOM has focusable elements internal to it, and one of those elements currently has focus, document.activeElement (like all other selectors) will not be able to point directly to it. What it will point to is the first element in the document that includes a shadow DOM. "
https://dev.to/open-wc/mind-the-document-activeelement-2o9a

therefor "this.focused" is false and "shouldClosePopover" in combobox is alway true. there is the flickering.  

could you please use  the combobox  in a lit component and check it again? thanks.

`import { LitElement, html } from 'lit-element';
class Example extends FBP(LitElement) { 

  render() {
    // language=HTML
    return html`
      <ui5-combobox placeholder="Enter value">
        <ui5-cb-item text="Item 1"></ui5-cb-item>
        <ui5-cb-item text="Item 2"></ui5-cb-item>
        <ui5-cb-item text="Item 3"></ui5-cb-item>
      </ui5-combobox>
    `;
  }
}`

Best,
fan

**Comment by ilhan007** [comment]
@f-zou thanks for the explanation but to forward the issue to the responsible team I need an snippet or app that the flickering reproduces. Use the example code in https://codesandbox.io/ i am sure it would not take long time to do it.

Best,
ilhan

**Comment by f-zou** [comment]
@ilhan007 
i have created a example:
https://codesandbox.io/s/objective-newton-ynqx5?file=/src/index.js
You should press the refresh button on left of location bar in the embed browser after the first loading. otherwise there are SyntaxError. 

Best,
Fan
