### ISSUE TITLE
ui5-textarea: Required field is not informed when keyboard tab focus is set on Activity Name field

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents#2374]
**Describe the bug**
Required field is not informed when keyboard tab focus is set on Activity Name field

**To reproduce**

1. Go to https://github.wdf.sap.corp/pages/xweb/goalmanagementx/app.html?mock#/goal-list
2. click 'Skip Tour' button
3. click more actions button on the top right of Goal Card
4. click 'Create Activity' button
5. With JAWS ON, using keyboard tab key navigate the contents of modal window

**Actual Results**
When focus is set on 'Activity Name' textarea with tab key, JAWS doesn't announce it as required field.
Note : In forms mode, with arrow keys navigation the field is announced as required. aria-required="true" is used.

**Expected behavior**
When form fields are navigated using keyboard tab key, the Activity Name input field which is mandatory field should be announced as required by JAWS.

Tested with other screen reader NVDA and NVDA does announce input form field as 'required'. Please find the attached recording for NVDA and JAWS screen reader.

 The textarea tag along with required and aria-required was tested in w3.org and JAWS was announcing the required field correctly with TAB key. Please find the attached screenshot.

Suggestion :  Instead of using both attributes 'required' and' aria-required' try using only one and test with JAWS.

**Screenshots**
<img width="1785" alt="2020-09-21_20-01-36 (1)" src="https://user-images.githubusercontent.com/13098801/96549720-759c0480-12e2-11eb-93d3-a9edb68a0102.png">
![Example on w3 org](https://user-images.githubusercontent.com/13098801/96549753-7e8cd600-12e2-11eb-843d-59afaf2dce2d.png)
![JAWS required input field](https://user-images.githubusercontent.com/13098801/96549777-88163e00-12e2-11eb-812e-cd93005b9315.png)
![Required field announced in Virtual PC mode](https://user-images.githubusercontent.com/13098801/96549808-92383c80-12e2-11eb-9ee3-67e69aba1171.png)
![Tab key required attribute issue](https://user-images.githubusercontent.com/13098801/96549812-95332d00-12e2-11eb-9096-f35dad41ed78.png)

**Context**
- UI5 Web Components version: 0.23.2
- OS/Platform: {...}
- Browser *(if relevant)*: {...}
- Other information: {...}

**Organization:** 
SF

**Priority:** 
Medium

**Comment by niyap** [comment]
Dear @GongRichard,
Thanks for the detailed description!

Unfortunately , I am not able to access your application.

I checked the described issue in the available samples:
1. [https://sap.github.io/ui5-webcomponents/master/playground/main/pages/TextArea/](https://sap.github.io/ui5-webcomponents/master/playground/main/pages/TextArea/)
2. [https://sap.github.io/ui5-webcomponents/playground/components/TextArea/](https://sap.github.io/ui5-webcomponents/playground/components/TextArea/) - adding "required" to the first sample
and I am not able to reproduce the issue. In both samples "required" is read out.

For testing purposes, I used JAWS19 + Chrome, navigating via TAB (virtual cursor off)

Could you please check once again if the issue still persist from your side and if so, please reopen the incident and allow access to your application.

Regards,
Niya

**Comment by GongRichard** [comment]
@niyap , this issue still can be reproduced by SF A11Y team, please have a check. The above page can access now.

Hello Richard,

I revalidated and issue still exist and JAWS does not announce 'required' when focused with TAB key. Many screen reader user do navigate page with TAB key so this issue needs to be taken into consideration.

For reference - I edited the html code, just added required inside <textarea> and JAWS did announced as 'required'.

Please find attached screenshot for reference.

By adding 'required' inside the <textarea> element may resolve the issue.

 

Thanks,

Preeti DEshmukh

![Still an issue WEF-3842](https://user-images.githubusercontent.com/13098801/105186157-5f654500-5b6c-11eb-8c0e-a62b74b01e71.png)
![Edited WEF-3842](https://user-images.githubusercontent.com/13098801/105186170-655b2600-5b6c-11eb-9e6a-5b3fd204f4a5.png)

**Comment by niyap** [comment]
Hello @GongRichard,

I am a little bit confused. Now, the application is accessible but I was not able to reproduce the issue.
I check the ui5-textarea within "Create Activity" dialog, as well as the one in "Create Goal" but the issue is not reproducible from my side. "Required" is always announced.
I checked with JAWS19 + Chrome, then I tried with JAWS18 as well. I checked both with virtual cursor and without, but without result.

Could you please give me detailed information, how do you manage to reproduce it?
Please, specify JAWS and Chrome versions and step by step description how to reproduce the issue in order to be able to support you.

Thank you in advance!

Kind Regards,
Niya

**Comment by GongRichard** [comment]
@niyap this was tested by SF A11Y quality team. What's your sap internal email address? I send email to you and our SF QA.

**Comment by niyap** [comment]
Hello @GongRichard,

My email is: nia.peeva@sap.com

Kind Regards,
Niya

**Comment by GongRichard** [comment]
Niya has confirmed with SF QA, this is not an issue.
