### ISSUE TITLE
ui5-date-picker: no information within icon to guide users on how to open date picker for keyboard user

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents#2377]
**Describe the bug**
no information within icon to guide users on how to open date picker for keyboard user

**To reproduce**

1. Go to https://github.wdf.sap.corp/pages/xweb/goalmanagementx/app.html?mock#/goal-list
2. click 'Skip Tour' button
3. click more actions button on the top right of Goal Card
4. click 'Create Activity' button
5. select a new satus 'low'
6. user keyboard to focus 'Achieved On'

**Actual Results**
The date picker widget opens with 'Fn+F4' on windows but there is no hint or information provided to sighted or non-sighted users on how to interact with the date picker widget. By default, keyboard users use Tab key to navigate to interactive elements. 

**Expected behavior**
Will it be possible to provide tooltip or information within icon to guide users on how to open date picker widget?

**Context**
- UI5 Web Components version: 0.23.2
- OS/Platform: {...}
- Browser *(if relevant)*: {...}
- Other information: {...}

**Comment by Todor-ads** [comment]
Hi @GongRichard,
I have synced your request with our accessibility experts.

In UI5 we avoid adding explicit tutorial messages and leave those to be handled by the screen reader, unless a certain functionality is very custom. You can see that JAWS isn't announcing F4 messages for neither the HTML combobox role (https://veui5infra.dhcp.wdf.sap.corp/snippix/#24712), nor native HTML "select" tags (https://www.w3schools.com/tags/tag_select.asp). As F4 is considered one of the basic keyboard interactions, we won't be adding such message in our controls.

Best Regards,
Todor
