### ISSUE TITLE
SideNavigation: In SideNavigationItem, default icon color is different with standard UI5

### ISSUE THREAD

**Issue by rkl1994** [SAP/ui5-webcomponents#2382]
**Describe the bug**
In ui5-webcomponents-react version '0.11.0', the default color for icon in SideNavigationItem is black, however, in SAP standard UI5(https://sapui5.hana.ondemand.com/#/entity/sap.tnt.SideNavigation/sample/sap.tnt.sample.SideNavigation), the color is blue. 

By the way, the font-size seems a bit larger than the standard one.

**Isolated Example**
<img width="273" alt="Screen Shot 2020-10-22 at 2 36 24 PM" src="https://user-images.githubusercontent.com/5527455/96834082-f807fe00-1473-11eb-8453-d46062865419.png">

<img width="249" alt="Screen Shot 2020-10-22 at 2 36 35 PM" src="https://user-images.githubusercontent.com/5527455/96834097-fe967580-1473-11eb-9811-13f5b1450918.png">

**To Reproduce**
Please see the snapshot.

**Expected behavior**
Should be the same with standard UI5

**UI5 Web Components for React Information**
"@ui5/webcomponents": "1.0.0-rc.9",
"@ui5/webcomponents-fiori": "1.0.0-rc.9",
"@ui5/webcomponents-react": "0.11.0",

**Comment by ilhan007** [comment]
Sync the icon color and font-size of the side navigation item with latest FIori 3 spec and apply the correct design.

**Comment by GerganaKremenska** [comment]
Hello @rkl1994,

[sap.tnt.SideNavigation](https://sapui5.hana.ondemand.com/#/entity/sap.tnt.SideNavigation/sample/sap.tnt.sample.SideNavigation) will go under redesign and will look like Side Navigation web component. This was discussed with our design team. And the wanted design in the end is of Side Navigation WC.
