### ISSUE TITLE
Null is rendered as textarea placeholder

### ISSUE THREAD

**Issue by fifoosid** [SAP/ui5-webcomponents#2384]
**Describe the bug**
If a textarea has a placeholder, once the placeholder is removed the value that is rendered is null

**To reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/master/playground/components/TextArea/
2. Remove the placeholder property of any textarea from the DOM or with JS
3. Observe the behaviour

**Expected behavior**
Nothing will be rendered as placeholder.

**Affected components** *(if known)*
```ui5-textarea```

**Priority:** *(optional)* *Medium*

Setting priority would indicate the importance of the issue
and would help the process of dispatching and processing.

**Comment by nnaydenow** [comment]
Issue seems to be fixed with #2448
