### ISSUE TITLE
"Selected" being read out while navigating through Responsive Popover options can be confusing for screen-reader users

### ISSUE THREAD

**Issue by rama1990br** [SAP/ui5-webcomponents#2391]
**Describe the bug:**
`selected` attribute is added in the `ui5-li-suggestion-item`(https://github.com/SAP/ui5-webcomponents/blob/master/packages/main/src/InputPopover.hbs#L97) each time an option is focussed on in the Popover which is causing the screen-reader to announce that that particular option has been selected. This can be confusing for screen-reader users since it can given the impression that the option is being selected each time they move to a new option, which is not the case. 

**Expected behavior:**
Given below is an example of how this has been implemented in w3.org, and it can be seen that there is no "selected" announcement while navigating through the options and even after making a selection. However, "collapsed" state change followed by the selected option is announced.
![combobox_jaws](https://user-images.githubusercontent.com/32254036/96934935-f50f0c80-1477-11eb-8eb3-7ab796a3a7b9.jpg)

**Steps to reproduce the behavior:**
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/Input/
2. Start up the screenreader (NVDA/Jaws)
3. Type 'a' in the input box under "Input With Suggestions"
4. Key down to the first option.
5. The screen-reader reads out "List item 6 of 6 Australiatravel the world Is Selected" instead of just "List item 6 of 6 Australiatravel the world"
![image](https://user-images.githubusercontent.com/32254036/96937627-6dc49780-147d-11eb-85db-e32c7e2ce2d8.png)

**Comment by rama1990br** [comment]
I have filed this issue for SuccessFactors, so can the "SF" label please be added to this issue?

**Comment by hristop** [comment]
Hi @rama1990br ,

When you start traversing the list with the arrow keys, each time you move up or down through the list, the Input's text is updated and the item you have moved to is indeed being selected. 
In this context, JAWS pronouncing "Selected" after the items text is correct and we do not see issue here.

This was also confirmed by our ACC expert.

Best Regards,
Hristo
