### ISSUE TITLE
[Feature Request][ui5-button][icon only button] set tooltip and aria-label to inner svg

### ISSUE THREAD

**Issue by Hubery-Shen** [SAP/ui5-webcomponents#2393]
Dear colleagues,
I am from SuccessFactors Web Experience Shanghai team.

Component:
The component is ui5-button ( icon only button ), this icon i passed is : message-error icon

Feature request:
1. I want to set the show-tooltip attribute's value by myself ( value: true / false )
2. I want to custom the aria-label value for inner SVG
3. I want to change the title inside the SVG

![WX20201023-102944](https://user-images.githubusercontent.com/63704163/96950302-8e8ffa00-151c-11eb-9940-8b3a5db4c5bd.png)

**Comment by fifoosid** [comment]
Hi @Hubery-Shen 

I assume that you are using ```ui5-button``` with no text(icon only). This means that you need to set the aria-label and title properties to the ```ui5-button```. Why do you need to set them to the inner SVG?

The same logic applies to the tooltip as well. If you set the tooltip to the icon, if you hover the button between the border and the icon, no tooltip will be shown. Do you need a tooltip for the whole button?

**Comment by Hubery-Shen** [comment]
Hi @fifoosid 

1. 
> I assume that you are using ui5-button with no text(icon only). This means that you need to set the aria-label and title properties to the ui5-button. Why do you need to set them to the inner SVG?

I found that this issue has been resolved in 0.23.6

2. 
>The same logic applies to the tooltip as well. If you set the tooltip to the icon, if you hover the button between the border and the icon, no tooltip will be shown. Do you need a tooltip for the whole button?

Yes, I need a tooltip for the whole button. I don't want to show the tooltip of icon

Thanks
