### ISSUE TITLE
ui5-button css::part() does not work on older version

### ISSUE THREAD

**Issue by Knightofhonour** [SAP/ui5-webcomponents#2395]
**Describe the bug**
In css stylesheets, ::part() is sometimes used. For ui5-button, this fails to work properly in older Android versions (API 28 and before). It can only work for API 29 and 30, even though all versions from 23 and after should support css. It is suspected this issue is not isolated to ui5-buttons but to all webcomponents

**To reproduce**
1. Git clone https://github.com/Knightofhonour/ui5-part
2. run command parcel src/index.html
3. run localhost on Android Emulator API 28 and 30

**Screenshots**
![image](https://user-images.githubusercontent.com/48403373/97143770-46800a00-179e-11eb-895e-e34e233e76b4.png)
![image](https://user-images.githubusercontent.com/48403373/97143812-5697e980-179e-11eb-86cb-7611385d171b.png)
The first image shows an Android emulator running on API 28, while the second image is running API 30. The second image shows the intended output, which cannot be reproduced on the first image.

**Affected components** *(if known)*
ui5-button

**Comment by fifoosid** [comment]
Hello @Knightofhonour 

Can you provide the following information for both working & not working scenarios:
- exact Android version
- browser that is used
- exact version of the used browser

**Comment by Knightofhonour** [comment]
Hi @fifoosid , this was done on Android 28 and 30, and on Google Chrome 83.0.4103.44 as the browser

**Comment by fifoosid** [comment]
Hi @Knightofhonour 

Closing the issue since the Android 9 is out of support.
