### ISSUE TITLE
ui5-textarea: Activity Name label is announced twice

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents#2398]
**Describe the bug**
Activity Name label is announced twice

**To reproduce**
1. Go to https://github.wdf.sap.corp/pages/xweb/goalmanagementx/app.html?mock#/goal-list
2. click 'Skip Tour' button
3. click more actions button on the top right of Goal Card
4. click 'Create Activity' button
5. With JAWS on, navigate to input field Activity name

**Actual Results**
The label Activity Name is announced twice by the screen reader hence there is repetitive announcement of label.
Label 'Activity name' is used under tag <label> and also with aria-label.

**Expected behavior**
Only once currently focused element's accessible name must be announced.

**Screenshots**
![Activity Name announced twice](https://user-images.githubusercontent.com/13098801/97261803-92908480-185a-11eb-8de3-f26145ad9195.png)
![reopened WEF-3896](https://user-images.githubusercontent.com/13098801/97261810-96240b80-185a-11eb-82e8-c33289b7cf4c.png)

**Context**
- UI5 Web Components version: 0.23.2
- OS/Platform: {...}
- Browser *(if relevant)*: {...}
- Other information: {...}

**Comment by fifoosid** [comment]
Hi @GongRichard 

I cannot reproduce the issue on my side. As you can see from the attached screenshot, everything is read correctly.
![image](https://user-images.githubusercontent.com/16850339/97293807-d634bf80-1855-11eb-8cab-6842317989b4.png)

If you still reproduce the issue on your side, don't hesitate to reopen the issue with isolated example in CodeSandbox
