### ISSUE TITLE
Popover arrow for notifications shellbar not positioned correctly

### ISSUE THREAD

**Issue by m-ignatov** [SAP/ui5-webcomponents#2401]
**Describe the bug**
Popover arrow for notifications shellbar is not positioned correctly when the following popover attributes are set: ```placement-type="Bottom" horizontal-align="Right"```

**Isolated example**
[CodeSandbox](https://codesandbox.io/s/ui5-webcomponents-forked-57wbr?file=/index.html)

**Actual** (1.0.0-rc.9)
![image](https://user-images.githubusercontent.com/36794374/97279248-6e757900-1843-11eb-928d-afad3697b9ed.png)

**Expected** (1.0.0-rc.8)
![image](https://user-images.githubusercontent.com/36794374/97279544-cc09c580-1843-11eb-949d-b3c3ac486692.png)

**Context**
- UI5 Web Components version: 1.0.0-rc.9

**Comment by fifoosid** [comment]
Hi @m-ignatov 

If you want to position the popover correctly in this use case, you should remove the ```horizontal-align="Right"``` attribute.

**Comment by m-ignatov** [comment]
Hi @fifoosid 

Thanks, I understand that. 

However, this is still a visual bug when the popover horizontal align property is:
`horizontal-align="Right"` or `horizontal-align="Left"`.

Please, consider reopening this issue.

Thanks :)
