### ISSUE TITLE
A11y - CPM Activity Integration with Goals - ARIA attributes - Invalid use of aria attribute

### ISSUE THREAD

**Issue by maybetosure** [SAP/ui5-webcomponents#2426]
**Describe the bug**
A11y - CPM Activity Integration with Goals - ARIA attributes - Inavalid use of aria attribute

**To reproduce**
1. Login to instance
2. Navigate to More actions button and select Create Activity
3. Navigate to title of card and navigate to Linked Activities page.

**Isolated example**
https://qacand.lab-rot.ondemand.com/sf/goals?bplte_company=TALH2TGMM1&_s.crb=hDRuAXSOfGzcIpnPW7T%252bu8Fndty5meXZK1JoOqvFYiw%253d#/goal-detail?targetUserId=cgrant1&templateType=tgm&templateId=831&id=21308
**Expected behavior**
Ensures all ARIA attributes have valid values.
 
 Note : aria-label and aria-labelledby are robustly supported for interactive elements such as links and form controls including the many input types. Aria-label, aria-labelledby are ignored on all static content unless it has a an interactive role, img role, or  nabv, main, search roles.

**Screenshots**
![image](https://user-images.githubusercontent.com/38159212/97688566-3e450900-1ad5-11eb-83a9-019515424c8c.png)

**Context**
- UI5 Web Components version
- OS/Platform: {...}
- Browser *(if relevant)*: {...}
- Other information: {...}

**Affected components** *(if known)*

**Log output / Any errors** in the console
```
{...}
```

**Organization:** *(if applicable)*

**Priority:** *(optional)* *(Low, Medium, High or Very High)*

Setting priority would indicate the importance of the issue
and would help the process of dispatching and processing.

To set the appropriate priority, you need to consider the impact
and if the issue:
- Breaks entire application or system - High and Very High
- Is accessibility one (Screan Reader, Keyboard Handling) - Medium and High
- Is functional one and makes a single component unusable - Medium and High
- Is visual, styling one - Low and Medium

Note: the priority would be re-evaluated by the issue processors, according to the project internal criterias

**Business impact:** *(mandatory for "Very High")*

**Comment by nikolay-kolarov** [comment]
Hi,

I checked the issue:
When the Card does not have a subheading, there is still a reference in the aria-labelledby "*ID*-subheading", but such element does not exist. In this case, this id reference has to be removed from the aria-labelledby.

Best Regards,
Nikolay

**Comment by ilhan007** [comment]
FYI @SAP/ui5-webcomponents-topic-rd please have in mind this Card component ACC issue and the comment by @nikolay-kolarov.
