### ISSUE TITLE
Card: Event for headerPress

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents#243]
**Is your feature request related to a problem? Please describe.**

I would like to use the `Card` Web Component as a navigation trigger to another page. When hovering the header, there is also visual feedback (background gets darker), but there is no event fired.

**Describe the solution you'd like**

I would like to have an event `headerPress` (or any other name you prefer) that is fired when the header section of the Card gets pressed.

**Describe alternatives you've considered**

None.

**Additional context**
<img width="696" alt="Screenshot 2019-03-25 at 11 53 38" src="https://user-images.githubusercontent.com/8775211/54914194-afcdd600-4ef4-11e9-8c40-6d7e38047145.png">

**Comment by ilhan007** [comment]
Hello @MarcusNotheis 

you can see the active header of the ui5-card in the sample section here:
https://sap.github.io/ui5-webcomponents/playground/components/Card/

The header is focusable, it can be activated by Space and Enter as well 
and you can test that "headerPress" event is fired  in the browser console by:

`
yourUi5Card.addEventListener("headerPress",  callback)
`
Note:
The feature will be available through npm with the next release.

**Comment by MarcusNotheis** [comment]
Awesome, thank you @ilhan007!
