### ISSUE TITLE
FileUploader: prop "accept" is invalid.

### ISSUE THREAD

**Issue by ggfer** [SAP/ui5-webcomponents#2435]
**Describe the bug**
set prop `accept="png,jpg"`, but it doesn't work when files upload window pop up.

**Code snippets**
```
            <FileUploader className={classes.formDialogContentItemIcon}
              accept="png,jpg"
              disabled={false}
              hideInput={true}
              multiple={false}
              name={undefined}
              value={null}
              valueState="None"
              onChange={(e) => { onImageChange(e, data.id) }}
            >
              {data.icon ? <img className={classes.iconUpload} src={data.icon} /> : <Icon className={classes.iconUpload} name={"background"} tooltip="213123a" interactive={false} showTooltip={false} />}
            </FileUploader>
```

**Expected behavior**
file type excluded should have been disabled.

**Screenshots**
![image](https://user-images.githubusercontent.com/19473701/97938487-7e013e80-1dbc-11eb-942c-ff4167f1c3c3.png)
nothing is disabled.

**UI5 Web Components for React Information**
    "@ui5/webcomponents": "^1.0.0-rc.9",
    "@ui5/webcomponents-react": "^0.11.0",
Operating System: macos
Browser: Chrome Version 86.0.4240.111 (Official Build) (x86_64)

**Comment by ilhan007** [comment]
Hello @ggfer could you try  adding the "." in front of the file extenstions - **accept=".png,.jpg"**.

**Comment by ggfer** [comment]
> Hello @ggfer could you try adding the "." in front of the file extensions - **accept=".png,.jpg"**.

 thank you. It works.

**Comment by MarcusNotheis** [comment]
Hey @ilhan007, I just added a PR (https://github.com/SAP/ui5-webcomponents/pull/2438) which adds the description as well, wasn't clear for me as well that `.`s are required.
