### ISSUE TITLE
Input: onChange is triggered after onSubmit

### ISSUE THREAD

**Issue by eleminsoda** [SAP/ui5-webcomponents#2436]
**Describe the bug**
When there is a change in the input field and press enter, onChange event is triggered after the onSubmit, while the order should be reversed/

**Isolated Example**
https://codesandbox.io/s/strange-vaughan-czv2b

**To Reproduce**
1. Open the console of the sandbox. 
2. Go to the input field and enter something. There should be 'Input' in the console.
3. press enter
4. In the console, 'submitted' is triggered before 'changed'

**Expected behavior**
'submitted' should be triggered after 'changed'

**Screenshots**
![image](https://user-images.githubusercontent.com/27283476/97978366-6f407900-1e08-11eb-96ad-cc0837544188.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.0.0-rc.8
`@ui5/webcomponents-react` version: 0.10.3
Operating System: macOS
Browser: chrome

**Additional context**

**Comment by MarcusNotheis** [comment]
Hey @eleminsoda,
as the Input component is developed by our UI5 Web Components colleagues, I have forwarded this issue to the corresponding repository.

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-rl the "submit" event of the Input is currently fired before the "change" event, but we should fire the "change" event first and then the "submit" event. Please change the order and add a test.

**Comment by ndeshev** [comment]
Hello,

We removed the 'submit' event from the Input component in #2855 because it is an event of the native 'form' element.

From now on the 'submit' functionality must be added with a custom handler for the standard "keydown" event that checks if ENTER key is pressed to submit the form containing the input component.
