### ISSUE TITLE
Positioning for enterprise applications

### ISSUE THREAD

**Issue by bsrdjan** [SAP/ui5-webcomponents#2446]
Which framework should be used for enterprise applications? The README suggests UI5:

> OpenUI5 is an open source JS framework that lets you build enterprise-ready web applications
> ... the best choice for building complete enterprise-ready and responsive web applications

The [documentation](https://sap.github.io/ui5-webcomponents) is advertising ui5-webcomponents as enterprise ready too:

> The UI5 Web Components share fundamental UI5 qualities with others to provide enterprise-grade features ...
> Includes all enterprise standards, such as accessibility, i18n, theming, etc

If both frameworks are enterprise ready, what makes the ui5 the first choice?

**Comment by ilhan007** [comment]
OpenUI5 is a full featured framework that comes with a programming model, data binding support, routing, OData support hundreds of enterprise ready controls and more features.

UI5 Web Components does not enforce a programming model, has nothing to do with data binding, routing and so on, but it provides enterprise ready components that can be used with any application framework such as React, Angular, Vue, etc.

Therefore, UI5 Web Components are good for
- web applications which already use a different web framework
- static web sites built without web frameworks, to just add a few interactive UI elements

**Comment by ilhan007** [comment]
@bsrdjan Perhaps if you share more details about your use case, what are you trying to achieve, we can tell what is more suitable for you.

**Comment by bsrdjan** [comment]
Thank you, only testing for now, trying to understand possible use-cases.
