### ISSUE TITLE
Slow under Firefox

### ISSUE THREAD

**Issue by EdorianDark** [SAP/ui5-webcomponents#2447]
I looked at the [examples](https://sap.github.io/ui5-webcomponents/playground/components/Badge/) 
and noticed, that the icons take a long time to be visible.
I took a recording and after the loading of the page it took 1.7 seconds to show the badges!
https://share.firefox.dev/3phjAJ4

This seems to be a general problem as also other components take quite a while to show.

**To reproduce**
Using Firefox and go to https://sap.github.io/ui5-webcomponents/playground/components/Badge/
1. Switch to the button example.
2. Switch to the badges example-

**Expected behavior**

**Screenshots**
Loading:
![image](https://user-images.githubusercontent.com/5777938/98446705-960bf180-211f-11eb-89ee-3bedd55e977b.png)
Loaded:
![image](https://user-images.githubusercontent.com/5777938/98446713-a0c68680-211f-11eb-9878-8233a1e9d937.png)

**Comment by vladitasev** [comment]
Hi @EdorianDark 

I had a quick look and it seems it's the playground app's search function initialization that takes longer under FF.
The webcomponents themselves look fine.

The "standalone" Badge test page:
https://sap.github.io/ui5-webcomponents/master/playground/main/pages/Badge/
loads just fine.

Regards
