### ISSUE TITLE
ui5-bagde does not allow overriding CSS letter-spacing

### ISSUE THREAD

**Issue by rajatmtalwar** [SAP/ui5-webcomponents#2451]
**Describe the bug**
ui5-badge text is not affected by global styles like
`* {
    line-height:1.5 !important;
    letter-spacing:0.12em !important;
    word-spacing:0.16em !Important;
}`

A similar issue was reported for ui5-button for your reference: https://github.com/SAP/ui5-webcomponents/issues/2390

**To reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/Badge/
2. Using devtools, add the following CSS rule to the page:

`* {
    line-height:1.5 !important;
    letter-spacing:0.12em !important;
    word-spacing:0.16em !Important;
}`

3. Notice that letter-spacing is not applied to the Badge text

**Isolated example**
Please provide an isolated example if possible, by forking [CodeSandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html)

**Expected behavior**
According to the SAP accessibility wiki, all text should adapt to custom spacing. (https://wiki.wdf.sap.corp/wiki/display/Acc/ACC-283+Details)

**Screenshots**
![image](https://user-images.githubusercontent.com/4739468/98539065-b966a600-22b1-11eb-9dab-cb797d54912a.png)

**Affected components**
ui5-badge

**Organization:**
SuccessFactors

**Priority:** 
Medium

**Comment by ilhan007** [comment]
Already fixed, will be released with the next release - RC.10

Try the preview:
https://sap.github.io/ui5-webcomponents/master/playground/main/pages/Badge/

**Comment by rajatmtalwar** [comment]
We still have a problem with letter-spacing. It has hard-coded value.

![image](https://user-images.githubusercontent.com/4739468/99508933-2a414880-29ab-11eb-8181-ba3be28503d0.png)
