### ISSUE TITLE
ui5-date-picker: previous and next button cannot be focused with tab key

### ISSUE THREAD

**Issue by sleric1024** [SAP/ui5-webcomponents#2453]
**Describe the bug**
The ui5-date-picker control doesn't support the next and back button to be focused with Tab key.

**To reproduce**
https://sap.github.io/ui5-webcomponents/playground/components/DatePicker/
Click date picker control, and with Tab key we can focus on the month button, year button and date button. While the next and back button cannot be focused.

**Expected behavior**
The focus should come to the next and previous button.

**Screenshots**
![image](https://user-images.githubusercontent.com/5724592/98640899-d52b8400-2365-11eb-9512-a7e3e962a718.png)

**Context**
- UI5 Web Components version

**Organization:** *SuccessFactors*

**Comment by ilhan007** [comment]
Hello @sleric1024 

this is not a bug, but intended, it's done by the accessibility (more specifically, keyboard handling) spec, you can refer to the sap.m.DatePicker, it behaves the same
https://openui5nightly.hana.ondemand.com/entity/sap.m.DatePicker/sample/sap.m.sample.DatePicker

BR,
ilhan

**Comment by sleric1024** [comment]
Hi @ilhan007 
Thanks for your reply.

I checked the UI5 control **sap.m.DatePicker**, it can not be reached by **Tab key.** While for accessibility side, we can use **page-up** and **page-down** key to reach the back and next button for alternative, which can not be supported by UI5-WebComponent now. So, could you please help to check if this can be an accessibility feature to be added. Thanks.

BR,
Eric
