### ISSUE TITLE
Non-interactive star rating which receives focus

### ISSUE THREAD

**Issue by saorabhkr** [SAP/ui5-webcomponents#2461]
**Describe the bug**

**A11y issues with Star Rating**

Start rating with readOnly property is receiving focus from a mouse/keyboard even though this is not interactive and it's only used for display purposes. 

In our use-case, we have to display the "aggregate rating for an entity". 

Considering this is only for display purpose, and as it has a role slider, which means when a screen reader is receiving focus by default screen reader announces the instruction to use arrow keys to increase or decrease the rating for the "slider" role which would mislead screen reader users.

Below a screenshot can be found with the outline when it receives fouces from keybord/mouse,

<img width="391" alt="Screen Shot 2020-11-11 at 11 45 53 AM" src="https://user-images.githubusercontent.com/5204425/98784253-db326b00-2420-11eb-91dc-6a1c8ad3fd67.png">

**Implementation**

`<ui5-rating-indicator value={3} readOnly role="slider"></ui5-rating-indicator>`

**To reproduce**
1. Running screen reader on this URL https://sap.github.io/ui5-webcomponents/playground/components/RatingIndicator/ to observe behavior. 

**Expected behavior**

As it is not interactive and being used just for display purpose it should not receive focus from a keyword/mouse.

**Context**
UI5 Web Components version: 0.23.5
OS/Platform: All
Browser (if relevant): All
Other information: Screen reader NVDA

**Affected components** 
ui5-rating-indicator

**Comment by ilhan007** [comment]
This is by design

- readonly means  "not editable", it is interactive and should receive focus
- disabled means "not interactive", it does not receive focus (and in addition is not editable)

If you use "disabled", the opacity of the component will be reduced, but you can change it with standard css on the tag
```css
ui5-rating-indicator {
   opacity: 1
}
```
