### ISSUE TITLE
internationalization typings support from @ui5/webcomponents-base

### ISSUE THREAD

**Issue by nazarkulyk** [SAP/ui5-webcomponents#2470]
Hi,

i build my react app with internationalization support from @ui5/webcomponents-base. And it works great, but i am missing typings. Not sure i have to file this feature request here or on @ui5/webcomponents project self.

What i am doing:

```js
import { registerI18nBundle } from '@ui5/webcomponents-base/dist/i18nBundle.js';

registerI18nBundle('myApp', {
    de: './assets/messagebundle_de.json',
    en: './assets/messagebundle_en.json'
  });
```

I have added types in to my /types/index.d.ts by myself.

Would be great to have typings in react or in webcomponents-base for that.

```js
import { registerI18nBundle } from '@ui5/webcomponents-react';

registerI18nBundle('myAppb', {
    de: './assets/messagebundle_de.json',
    en: './assets/messagebundle_en.json'
  });
```

**Comment by MarcusNotheis** [comment]
Hey @nazarkulyk,
thanks for reporting! As this feature request is indeed related to the UI5 Web Components base project, I'll forward this issue to the corresponding repository.
As far as I know, @ilhan007 is already working on something here :)

**Comment by ilhan007** [comment]
Hello @nazarkulyk Typescript definitions for all public APIs of the "base" package will be tracked with this issue: https://github.com/SAP/ui5-webcomponents/issues/4337

It starts now and should be available in the end of Q3.

**Comment by ilhan007** [comment]
Hello @nazarkulyk 
Edit: the "base" package (the mentioned registerI18nBundle API is part of it) is already migrated to TS, but not yet released as we want to do more internal validation before releasing. We expect that release to happen January, when all framework parts will be in TS and the majority of the components as well.
