### ISSUE TITLE
[Feature request] for 'NavContainer' component

### ISSUE THREAD

**Issue by alex-zhang** [SAP/ui5-webcomponents#2482]
**Is your feature request related to a problem? Please describe.**

hi, I am from SAP Success factors team.  we have a feature needs to NavContainer to achieve the target.

Below is our our ux design,

![image](https://user-images.githubusercontent.com/4457451/99238355-964d7080-2834-11eb-9826-365a93a3a646.png)

The People list has two layer, the top layer is the manager people list and the bottom layer is child employee people list.

When the user click the the list item then, the user can see the child employee people list which under the manager.

so, I think the 'NavContainer' component (UI5 link  https://ui5.sap.com/#/entity/sap.m.NavContainer/sample/sap.m.sample.NavContainer) can achieve the target.

or here any suggestion?

Thanks 
BR.

**Comment by ilhan007** [comment]
Hello @alex-zhang 

Usually that can be achieved by having a route, let's say "/managers"  that will display the "manager list" 
and upon item click you can navigate to another/child route "/managers/:id" to load the list of employees for the given manager. Does it sound doable?

**Comment by alex-zhang** [comment]
yes, we're the react project that is on top of 'ui5-webcomponents'. 

For the target i mentioned above, we can use the 'react-motion', 'react-spring', etc. or pure css to achieve the target.

But we think it's a common behavior for the ux which can be good standardized.

**Comment by ilhan007** [comment]
Hello @alex-zhang 

I will discuss it internally with the team to get some feedback and get back to you.

**Comment by ilhan007** [comment]
Hello @alex-zhang we discussed the request for NavContainer. It does not have rendering, styling, basically the only logic would be to show some "page" with an animation. As this something relatively easy to achieve, we think it does not worth to create a component. I will close the request, feel free to reopen it, if you have additional input or comments.
