### ISSUE TITLE
A11y - CPM Activity Integration with Goals - Linked Activities card header receives tab key focus

### ISSUE THREAD

**Issue by maybetosure** [SAP/ui5-webcomponents#2486]
**Describe the bug**
The card header should not receive a focus.
The ‘Linked Activities()’ in goal detail page is a heading and non-actionable element,  it should not receive a focus.  Only actionable and interactive elements like buttons or links  should receive the focus. 

**To reproduce**
1. Go to instance
2. Click a goal in goal list and Navigate to goal detail page.
3. Using keyboard Tab key, observe the focus order

**Isolated example**
https://qacand.lab-rot.ondemand.com/sf/goals?bplte_company=TALH2TGMM1&_s.crb=4SpbgEcIXQ05r1UUfQ6WnJSUI%252f%252fY%252fjOd%252fUZwHfydBqU%253d#/goal-detail?targetUserId=cgrant1&templateType=tgm&templateId=540&id=21258

User Name: cgrant
Password: Pwd1

**Expected behavior**
the header ‘Linked Activities()’ should not receive a focus. Only ‘+Create Activity’ should receive a focus.

**Screenshots**
![image](https://user-images.githubusercontent.com/38159212/99340570-3ce05280-28c3-11eb-8aa7-2e87833d220f.png)
![image](https://user-images.githubusercontent.com/38159212/99340604-49fd4180-28c3-11eb-86d0-fe3bddb318bc.png)

**Context**
- UI5 Web Components version
- OS/Platform: {...}
- Browser *(if relevant)*: {...}
- Other information: {...}

**Affected components** *(if known)*

**Log output / Any errors** in the console
```
{...}
```

**Organization:** *(if applicable)*

**Priority:** *(optional)* *(Low, Medium, High or Very High)*

Setting priority would indicate the importance of the issue
and would help the process of dispatching and processing.

To set the appropriate priority, you need to consider the impact
and if the issue:
- Breaks entire application or system - High and Very High
- Is accessibility one (Screan Reader, Keyboard Handling) - Medium and High
- Is functional one and makes a single component unusable - Medium and High
- Is visual, styling one - Low and Medium

Note: the priority would be re-evaluated by the issue processors, according to the project internal criterias

**Business impact:** *(mandatory for "Very High")*

**Comment by ilhan007** [comment]
Hello @maybetosure 

this is intended, we followed the Card's acc spec, the card header should get focus.
Also, the sapui5/openui5 equivalent https://openui5nightly.hana.ondemand.com/entity/sap.f.Card/sample/sap.f.sample.Card
get focused the same way.

Nevertheless, @SAP/ui5-webcomponents-topic-rd could you confirm that the card header area should get the focus and this is done by the spec.

**Comment by maybetosure** [comment]
Hi @ilhan007 

 I told QA the behavior http://veui5infra.dhcp.wdf.sap.corp:8080/demokit/index.html#/entity/sap.f.Card/sample/sap.f.sample.Card, but they said this is also a issue needs to be fixed. You can see more details via https://jira.successfactors.com/browse/WEF-4002.
For card control this is the expected behavior : https://confluence.successfactors.com/pages/viewpage.action?spaceKey=UX&title=SF+Fiori+and+Accessibility+Design+Updates
• Mouse users: Whole card is clickable, with state visually indicating it is clickable.
• Keyboard users: Focuses on content as primary action (not whole card). Use a link or button to achieve this.
• Secondary actions can be: View all, Mark as read, view details
• Button action- can expand or bring up a dialog. When closing the dialog, focus goes back to the card

**Comment by alexandar-mitsev** [comment]
Hello @maybetosure,

**Comment by alexandar-mitsev** [comment]
Hello @maybetosure ,

The interaction design and ACC specification for the Fiori 3 integration cards on which our implementation is based are quite different from what you describe. Here is what we have as a specification:
- The full header is an active element, it can be clicked and is used as navigation to the card's application
- Focus of the card goes on the header
- The content is not an active element on its own. It is not clickable (with some exceptions like Analytical Card)
- Content may contain active elements like list items
- Once the header is focused you can press TAB to go to the first active element inside the content

**Comment by fifoosid** [comment]
Hello @maybetosure 

There is indeed a bug in ```ui5-card```. By default the header of the card should not be focusable. It should be focusable only if the property ```header-interactive``` is set. In the mentioned scenario, it is not set, which means that the whole header should not be focusable.(Only the button should be).

The issue will be resolved on our side.

**Comment by ilhan007** [comment]
Hello @alexandar-mitsev 

The ui5-card can be considered equivalent of the sap.f.Card with the following difference:
the presence of  "headerInteractive" property that adds hover effect on the header and the Card fires an event when the header is clicked with the mouse or activated with  ENTER or SPACE keys.

- headerInteractive = false (default): the header is focusable
- headerInteractive = true: the header is focusable, has hover effect and the Card fires an event ("header-click") on click, ENTER and SPACE.

Currently **the card header always gets focused**, with or without headerInteractive being set. To have the complete answer, could you discuss internally the following option, that also seems reasonable:
Can we remove the focus of the card header, when headerInteractive is false (I expect to loose some screen reader announcements) and make it focusable only if the headerInteractive is true?

From our side, we are fine to remove the focus when headerInteractive = false, but we want to make sure that from ACC point of view it is fine as well.

BR,
ilhan

**Comment by alexandar-mitsev** [comment]
Hello @maybetosure , @ilhan007 ,

After further consultation with our ACC experts, the behavior of having the focus on the card header is always correct. Even if the property headerInteractive is false.

This is recommended for two reasons:

1. The ARIA standard allows for inactive elements to be focusable in some contexts. Especially inside of composite widgets. In the case of the card header it is actually recommended, because if the header is not focusable, it will hide its presence from the screen reader users. As @ilhan007 says - we will loose some screen reader announcements. This is described in more details in this part of the [ARIA documentation](https://www.w3.org/TR/wai-aria-practices/#kbd_disabled_controls).
2. A common usage of the cards is to have several of them on a single page - like a dashboard. If you have a mix of cards which are interactive and cards which are not interactive next to each other, we still want to be consistent in where the focus lands. This will make it easier for people with disabilities to navigate.

If you have further questions please reopen the issue.

Best Regards,
Alexandar Mitsev
