### ISSUE TITLE
DatePicker: remove the option to focus input on open

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents#2495]
**Goal**
Remove the following implementation `dp.openPicker({ focusInput: true });` 
Currently, the "openPicker" method allows an option to force focusing the input field after picker opens,
But, this contradicts the Fiori 3 UX and accessibility specs. It was implemented for one and specific use-case in the past and we agreed to remove it.

**Describe the solution you'd like**
Remove the **focusInput** option implementation, usage in test pages, and related tests (if exist) everywhere in the project.

**Comment by ilhan007** [comment]
FYI @SAP/ui5-webcomponents-topic-b

**Comment by vladitasev** [comment]
fixed by: https://github.com/SAP/ui5-webcomponents/pull/2598
