### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by softshipper** [SAP/ui5-webcomponents#2502]
Hi all  

Does ui5-webcomponents support Typescript?   

Thanks

**Comment by fifoosid** [comment]
Hi @softshipper 

Currently, UI5 Web Components don't support TypeScript.

PS: Recently we received this [feature request](https://github.com/SAP/ui5-webcomponents/issues/2470), which is about ts typings. Soon, we will evaluate if we have the required capacity to work on this topic.
