### ISSUE TITLE
SuccessFactors: UI5 List: "Single and Multi-Select" Mode

### ISSUE THREAD

**Issue by agauyeung** [SAP/ui5-webcomponents#2510]
**Is your feature request related to a problem? Please describe.**
There are cases where a list would need both single and multi-select _at the same time_. For example, in the [Fiori Design Guidelines for Table Personalization Dialog](https://experience.sap.com/fiori-design-web/table-personalization-dialog/), selecting columns for display means that the user needs to click into the checkbox for each desired list item. However, if the user wants to reorder a particular list item, the user must click the row itself (not the checkbox) to "single" select that row, then click one of the arrows to reorder the list. The behavior is detailed in the [link](https://experience.sap.com/fiori-design-web/table-personalization-dialog/) or as quoted below:

> **Show or Hide Columns**
> To show or hide columns, the user only needs to select or deselect the checkbox of a column (list item).
> (1) Columns are visible in the table.
> (2) Columns are hidden in the table.
> 
> **Move Column Up**
> (1) Select a column (by clicking on the list item).
> (2) Use the Move Column Up button to move the column to the left in the table.

**Describe the solution you'd like**
I would like another selection option to be introduced to allow for this use-case.

**Describe alternatives you've considered**
An alternative would be to have a ui5-webcomponents implementation of the Table Personalization dialog as its own component.

**Additional context**
![image](https://user-images.githubusercontent.com/8508119/100028018-c9e34a00-2da2-11eb-9f35-aad0cb2670bd.png)

**Comment by ilhan007** [comment]
Hello @agauyeung sorry for not processing the issue so far. Here we should follow up as with the recent request you have here https://github.com/SAP/ui5-webcomponents/issues/2634. Could you open a request to the design team ( as you did for the https://github.com/SAP/ui5-webcomponents/issues/2634), because this is specified for the Personalisation Dialog, but not  for the List.

**Comment by agauyeung** [comment]
Hi @ilhan007, I've created it here: https://sapjira.wdf.sap.corp/browse/FIORITECHE1-5177

**Comment by ilhan007** [comment]
Hello @agauyeung, looked at the design request and as it's rejected I am also closing the issue.
