### ISSUE TITLE
ui-wizard and ui5-button issues

### ISSUE THREAD

**Issue by BodhiHu** [SAP/ui5-webcomponents#2523]
**Describe the bug**

1. The ui5-wizard component is behaving/looking different from sap.m.Wizard
2. The ui5-button not showing some UI5 icons (like "share", ...etc)

**To reproduce**

Please see **Screenshots**

**Isolated example**
NA

**Expected behavior**

1. The ui5-wizard component should behave/look the same as sap.m.Wizard
2. The ui5-button should show all UI5 icons

**Screenshots**

![Wizard content has extra 4rem bottom space and background color not set the same as sap m Wizard](https://user-images.githubusercontent.com/3882561/100438595-53fe1c00-30dd-11eb-9c77-a985274be491.jpg)

![Some UI5 icons not showing on ui5-button](https://user-images.githubusercontent.com/3882561/100438604-582a3980-30dd-11eb-808b-f3b45370bed3.jpg)

![On Mobile, Wizard nav header steps different from sap m Wizard (should be collapsed, and show step title)](https://user-images.githubusercontent.com/3882561/100438606-595b6680-30dd-11eb-9c8f-8de28d52bad6.jpg)

**Context**
- UI5 Web Components version: 0.23.6
- OS/Platform: Mac
- Browser *(if relevant)*: Chrome
- Other information: NA

**Affected components** *(if known)*
NA

**Log output / Any errors** in the console
NA

**Organization:** *(if applicable)*
SF

**Priority:** *(optional)* *(Low, Medium, High or Very High)*
Medium

**Business impact:** *(mandatory for "Very High")*

**Comment by BodhiHu** [comment]
Hi friends,
When developing with ui5-webcomponents, we found above issues,
can you please help take a look ?

Thanks & Best Regards

**Comment by ilhan007** [comment]
Hello @BodhiHu 

2. Showing or not showing icons in buttons or standalone has nothing to do with the Wizard itself.
Check your imports and if everything is correct - create a another issue about the Button or Icon

3. Wizard nav header header issue
We agreed that the responsive behaviour will be nor part of the initial delivery.
It is currently developed -> https://github.com/SAP/ui5-webcomponents/issues/2441

**Comment by ilhan007** [comment]
Hello @BodhiHu 

I look at the issue with the padding, but could you provide url, steps, credentials, etc in order to reproduce it and investigate further.

**Comment by BodhiHu** [comment]
Hi @ilhan007 ,

1. For the extra bottom padding issue, I have created a codesandbox, please have a look:
https://codesandbox.io/s/ui5-webcomponents-playground-qgwcz

2. For the icons issue, just noticed we need to import the referenced icons first to use them : D

Thank you

**Comment by ilhan007** [comment]
Hello @BodhiHu

I want to clarify sth  about the background color. 
Currently there is no background color set, I am about to add the sapBackgroundColor which results in #f7f7f7 in Quartz light (sap_fiori_3) theme. This color will correspond to the openui5 [Wizard's Standard](https://openui5nightly.hana.ondemand.com/entity/sap.m.Wizard/sample/sap.m.sample.Wizard) bg-color, but it has also several additional options - List(#fff) and Solid (#edeff0). You expect to have darker background for the content from what I read, so  is #f7f7f7 fine or?

**Comment by ilhan007** [comment]
Hi @SAP/ui5-webcomponents-topic-rl there is a PR addressing author's feedback: https://github.com/SAP/ui5-webcomponents/pull/2547

**Comment by BodhiHu** [comment]
Hi @ilhan007 , sorry for late response, from the fixing PR, I think setting the bg color to --sapBackgroundColor should be fine : D

**Comment by ilhan007** [comment]
Hello @BodhiHu 

we have just closed the following feature request, regarding the responsive behaviour of the Wizard nav header https://github.com/SAP/ui5-webcomponents/issues/2441

And It will be soon released released (1-2 weeks) in version 0.29.1
