### ISSUE TITLE
TabContainer: Not applying sapUiResponsiveContentPadding

### ISSUE THREAD

**Issue by leoratzlaff** [SAP/ui5-webcomponents#2529]
**Describe the bug**
The ShellBar uses this responsive padding by dafault. I'm importing the variable sapUiResponsiveContentPadding to make my content respect the same example.

**Expected behavior**
The TabContainer should align the content with ShellBar's (and other componentes) content.

**Screenshots**
![TabContainer](https://user-images.githubusercontent.com/11520118/100474873-7170bd00-30c0-11eb-96f3-6069eed19712.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.0.0-rc.8
`@ui5/webcomponents-react` version: 0.10.2
Operating System: macOS BigSur 11.0.1
Browser: Chrome 87

**Comment by TeodorTaushanov** [comment]
Hi @leoratzlaff,

Can you prepare us a simple example like here:
https://codesandbox.io/s/ui5-webcomponents-forked-7l2ee

so we can investigate the issue easily?

Best,
Teo

**Comment by leoratzlaff** [comment]
Hi @TeodorTaushanov,
Here it is: https://codesandbox.io/s/ui5-webcomponents-forked-zs44o

**Comment by ilhan007** [comment]
Hello @leoratzlaff you can keep track of your issue in this one: https://github.com/SAP/ui5-webcomponents/issues/2539
