### ISSUE TITLE
MultiComboBox focusout issue

### ISSUE THREAD

**Issue by fifoosid** [SAP/ui5-webcomponents#2535]
**Describe the bug**
There is a problem when the ```ui5-multi-combobox``` loses focus. What happens depends on the exact interaction with the multicombobox.  Underneath, I have explained the exact steps & the issues that are happening.

**To reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/MultiComboBox/
2. Click on the arrow of a multicombobox in order to open its popover
3. Click on any item in the popover in order to select it (on the text of the item, so the popover could be closed)
4. The focus is lost
**EXPECTED BEHAVIOUR**: The focus should remain in the input of the multicombobox

5.  Click on the arrow of a multicombobox in order to open its popover again
6. Click somewhere on the page, out of the combobox or the popover
7. The focus remains in the multicombobox
**EXPECTED BEHAVIOUR**: The focus should not be in the multicombobox

**Context**
- UI5 Web Components version RC10
- OS/Platform: MACOS
- Browser *(if relevant)*: Chrome

**Affected components** *(if known)*
```ui5-multi-combobox```

**Comment by TeodorTaushanov** [comment]
@SAP/ui5-webcomponents-topic-rl, can you check this issue?
