### ISSUE TITLE
Dialog: initial focus not applied on open

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents#2537]
**Describe the bug**
The focus does not go to the focusable element in the dialog when it opens.
**Note**: The bug is not reproducible in our examples.

**To reproduce**
1. Go to https://mobile-development-kit-mobile-qa-nsblrmdkwebtestapp-approuter.cfapps.ap11.hana.ondemand.com/nsBLRMDKWebTestApp/index.html
2. Use your corporate mail and windows/macOS password to log in
3. Click the last item from the list "PLT Format Support"
4. Click "FormCell test cases"
5. Find the input field (ui5-textarea) with value "UPPER CASE IN WEB"
6. Type any letter - f.e "a"
7. Dialog opens upon typing, but the focus remains in the input field and you can continue typing, which will open other instances of Dialog

**Comment**
The "applyFocus" method is called before the Shadow DOM of the Dialog is ready, as consequence no focusable
element is found. We have to ensure that the Dialog is really open, the DOM is ready, and then call "applyFocus".

I also asked the app developer (from where the issue origins) to check if calling "applyFocus" "onAfterRendering" would fix the issue.

```js
// Popup.js
onAfterRendering() {
      this.applyInitialFocus();
}
```
<img width="706" alt="Screenshot 2020-12-02 at 10 11 23 AM" src="https://user-images.githubusercontent.com/15702139/100846270-fb38d580-3486-11eb-88ae-82a1947d1d78.png">

As you can see the time the applyFocus is called, the footer is not displayed, seems it is about to be slotted by the browser.
Using setTimeout resolves the issue.
```js
onAfterRendering() {
    setTimeout(() => {
          this.applyInitialFocus();
     }, 0);
}
```

**Video**
[Screen Recording 2020-11-25 at 3.15.40 PM.mov.zip](https://github.com/SAP/ui5-webcomponents/files/5623467/Screen.Recording.2020-11-25.at.3.15.40.PM.mov.zip)

**Expected behavior**
The button in the Dialog's footer should be the element on focus after the Dialog opens

**Context**
- UI5 Web Components version: latest
- OS/Platform: {...} MacOS
- Browser *(if relevant)*: {...} Chrome
- Other information: {...}

**Affected components** *(if known)* ui5-dialog (Popup)

**Comment by ilhan007** [comment]
FYI @SAP/ui5-webcomponents-topic-rd

**Comment by ilhan007** [comment]
Hello @alexandar-mitsev 

After upgrading the test system with version that includes the fix, the MDK colleagues found out that the issue is still present - the focus does not apply as expected.

The steps to reproduce are the same. 
The web components are bundled in "web-ui~46a5c7d5.bundle.js" where you can see that the app has the fix:


<img width="639" alt="Screenshot 2021-01-14 at 7 12 38 AM" src="https://user-images.githubusercontent.com/15702139/104547873-3eff2d00-5638-11eb-8e8e-f666b8f14d53.png">

BR,
ilhan

**Comment by gmkv** [comment]
Awaiting system to be updated to last release of ui5-webcomponents to check if #2679 fixes with the problem.

**Comment by gmkv** [comment]
Hi @ilhan007, the system running on the latest version of ui5-webcomponents no longer observes the reported bug.
