### ISSUE TITLE
TabContainer: implement latest Fiori 3 UX

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents#2540]
**Is your feature request related to a problem? Please describe.**
The UX of TabContainer has been updated significantly in terms of the overflow behavior of the tab strip.
We would like to catch up wit the latest UX.

Currently we have this left and right scrolling of the tabs on small sizes and all tabs are duplicated within the overflow menu, while in the latest UX, there is no such scrolling and only the hidden tabs are displayed in the overflow menu.

**Comment by ilhan007** [comment]
FYI @SAP/ui5-webcomponents-topic-rd

**Comment by olannyv** [comment]
Important Note: the new design of UI5 IconTabBar brought some changes (like tab reordering, when in the overflow) which happen to be a problem in some apps that were using (conceptually wrongly) the ITB as 'wizard'-style control (where the order of the tabs is crucial). 
So here on, again, is better to also consider early on also this case (or be clear that wc.TabContainer shall never be used as a wizard)

**Comment by ilhan007** [comment]
Hello @olannyv I see your point. I suggest postponing this refactoring for he time being as there is no stakeholder request for that.

**Comment by gmkv** [comment]
To achieve the latest Fiori 3 UX we have split this task into three BLI which will be done in the following order:
 1. Align and adjust paddings and focuses.
 2. Implement sap.m.TabsOverflowMode-like feature.
 3. Implement nesting of tabs.
