### ISSUE TITLE
DatePicker unable to select minimum date in certain timezones

### ISSUE THREAD

**Issue by nacydee** [SAP/ui5-webcomponents#2542]
**Describe the bug**
minDate is provided in format "yyyy-MM-dd", there seem to be some date conversions happening that block the minimum date from being selected in certain time zones. For example when minDate is "2021-01-01", a user with Mumbai (GMT+5:30) timezone will be unable to select 2021-01-01, but the minimum date they are able to select is 2021-01-02. At the same time a user in the Pacific Timezone will be able select 2021-01-01, but they will also have the option to select 2020-12-31 although the date will be invalidated. 

**To reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/DatePicker/
2. Change the browsers timezone to Mumbai (GMT+5:30). In Chrome you can open devtools select Menu “⋮” > More tools > Sensors > Change location to Mumbai. Check timezone has been changed.
3. Scroll to the third example where min-date="1/1/2020". The earliest date you can select is 1/2/2020. Unable to select 1/1/2020.

**Isolated example**

**Expected behavior**
The minimum date should be available to select regardless of the timezone user is in.

**Screenshots**
<img width="692" alt="Screen Shot 2020-12-02 at 9 29 27 AM" src="https://user-images.githubusercontent.com/75345457/100909137-56ec7880-34f2-11eb-9e0e-c46286b2e6f0.png">

**Priority:** *(optional)* *(Low, Medium, High or Very High)*
Medium

**Comment by TeodorTaushanov** [comment]
@SAP/ui5-webcomponents-topic-b, the issue is reproducible. Can you check it?
