### ISSUE TITLE
ui5-list: disabled attribute for ui5-li element

### ISSUE THREAD

**Issue by sunnyyadav100** [SAP/ui5-webcomponents#2560]
**Is your feature request related to a problem? Please describe.**
I have created a wrapper for the context menu by using the ui5-list. Based on the business scenario few menu items are disabled. Looking for a solution to make a ui5-li element disabled.

**Describe the solution you'd like**
A disabled attribute to make a list item disabled.

**Describe alternatives you've considered**

**Additional context**
<img width="425" alt="image" src="https://user-images.githubusercontent.com/9139037/101635617-396a6200-3a50-11eb-927a-2f4908ea2f46.png">

**Comment by nnaydenow** [comment]
Internal reference: BGSOFUIPIRIN-5517

**Comment by ilhan007** [comment]
Hello @sunnyyadav100 as Nayden mentioned above, we lack design support at the moment.  This is a temporary situation, but we don't know for how long it will continue. Unfortunately, for the time being we can't apply changes that are not already specified in the Fiori design guidelines and the current request is a something that is not specified.

**Comment by tonitone** [comment]
Hey, just an idea:
If you introduce an attribute, e.g. disabled="true" and when its set you render the `ui5-li-tree`-Element with the attribute disabled="disabled" it would get the native disabled visual style.
Best Toni
