### ISSUE TITLE
Icon only doesn't set its own attribute icon-only

### ISSUE THREAD

**Issue by fifoosid** [SAP/ui5-webcomponents#2567]
**Describe the bug**
Icon only button not always sets its own attribute icon-only.

**To reproduce**
1. Add the following code to an HTML page:
```html
<ui5-button icon="message-information" title="Cool title"></ui5-button>

<ui5-button icon="message-information" title="Cool title">
</ui5-button>
```
2. When you load the HTML page you can see that:
- The first button is rendered correctly with the arrtibute ```icon-only``` and the tooltip is correct
- The second button is not rendered correctly(the attribute ```icon-only``` is not present) and you can see that the tooltip of the inner icon is different from the tooltip of the whole button

**Expected behavior**
Both scenarios should behave consistently.

**Explanation**
The problem is in the isIconOnly getter.

**Context**
- UI5 Web Components version
- OS/Platform: {...}
- Browser *(if relevant)*: {...}
- Other information: {...}

**Affected components** ```ui5-button```

**Comment by NHristov-sap** [comment]
Hi colleagues,

The issue is reproducible, see here: [](https://codesandbox.io/s/ui5-webcomponents-forked-vdyv2?file=/index.html)

Please take care of this.

Best Regards,
Nikolay Hristov
GitHub Dispatcher
