### ISSUE TITLE
ui5-list-busy-row should not display when list busy is false

### ISSUE THREAD

**Issue by SherrySherry123** [SAP/ui5-webcomponents#2568]
Hi colleague,
I am from Successfactors team, please help to fix this issue.

**Describe the bug**
Issue: ui5-list-busy-row always display no matter if list is busy or not. And  ui5-list-busy-row is empty with 2rem height.
Expect: ui5-list-busy-row should not display

**To reproduce**
1. Create List with busy and infiniteScroll 

**Expected behavior**
When busy is true, display ui5-list-busy-row;
When busy is false, ui5-list-busy-row should set display as none;

**Screenshots**
![image](https://user-images.githubusercontent.com/30891905/101873185-773ac800-3bc1-11eb-9566-240854f95d76.png)

**Comment by NHristov-sap** [comment]
Hi @SherrySherry123 ,

Can you please give a isolated sample that demonstrates the issue in [CodeSandBox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html)?

Best Regards,
Nikolay Hristov
GitHub Dispatcher

**Comment by SherrySherry123** [comment]
Hi @NHristov-sap,
Here is the sample. Please let me know if you have further question.
https://codesandbox.io/s/ui5-webcomponents-forked-m0207?file=/index.html
![image](https://user-images.githubusercontent.com/30891905/102965232-6591e280-4528-11eb-95c8-761c86aeca40.png)
Regards,
Sherry

**Comment by SherrySherry123** [comment]
Hi @Martotko and @NHristov-sap ,
Is there anyone looking at this issue? 

Regards,
Sherry

**Comment by nnaydenow** [comment]
Hi @SherrySherry123,

The busy-row is added when infinity-scroll attribute or busy attribute are set otherwise it is not visible. You could remove the attribute if you are not using this behavior or when the last item is loaded. Seems to be not bug.

Regards,
Nayden

**Comment by SherrySherry123** [comment]
Hi @nnaydenow ,

Actually we need the infinity-scroll attribute, we need to load more items when the list is long;
As the list items is returned from backend, the list items count maybe 100, or may 1;

So there are two cases for me:
1. When the list is long, when scroll down to the busy-row area, it will show the busy indicator and load more items;
- <img width="983" alt="case1" src="https://user-images.githubusercontent.com/30891905/104562157-f3be3c00-5682-11eb-8e2c-892ca55c90d6.png">

2. When the list is short, as there is no more items and no scroll, we expect the busy-row not display; As it breaks the ui layout in this case, as busy-row display nothing, but occupy an empty space with width and height;
- <img width="966" alt="case2" src="https://user-images.githubusercontent.com/30891905/104562167-f7ea5980-5682-11eb-9dab-6c702820e1b4.png">

- <img width="1029" alt="case2 busy-row" src="https://user-images.githubusercontent.com/30891905/104562502-692a0c80-5683-11eb-8b8b-5c99b16731c6.png">

You can see the heigh marked with purple is different for case1 and case2, because the case2 display busy-row;
Please help to fix that, as our goal uxr project depends on it, and we need to deliver user friendly ui;

**Comment by ilhan007** [comment]
Hello @SherrySherry123 
we started working on a solution.

**Comment by SherrySherry123** [comment]
Great, thank you @ilhan007 for the quick action.
