### ISSUE TITLE
Wizard component implemented not fully

### ISSUE THREAD

**Issue by Kalita-Roman** [SAP/ui5-webcomponents#2588]
I see initial implementation of Wizard component has two render modes: **page** and **scroll** https://sapui5.hana.ondemand.com/#/api/sap.m.WizardRenderMode%23overview 
However current Wizard component has no mentioning about these modes (https://github.com/SAP/ui5-webcomponents-react/blob/master/packages/main/src/webComponents/Wizard/index.tsx)
It would be great to have the render mode as pages

**Comment by ilhan007** [comment]
Hello @Kalita-Roman 
unfortunately we don't have plans to support page mode for now. But, if the demand for the feature raises we will  reconsider our decision.

We will keep the request open and update you if the plan changes.

BR,
ilhan

**Comment by ilhan007** [comment]
There is a duplicate issue, closing this and keeping the other: https://github.com/SAP/ui5-webcomponents/issues/3777
