### ISSUE TITLE
New Control: SearchField

### ISSUE THREAD

**Issue by vbersch** [SAP/ui5-webcomponents#259]
Could you please implement a SearchField control as a UI5 Web Component?

**Comment by ilhan007** [comment]
Hello @vbersch ,
thank you for you request.

You can use the ui5-input to create a 'search field'.

(1) Using of the ui5-input "icon" slot
The ui5-input provides "icon" slot, so you can set any of our built-in icons set, in your case - search icon.
`
<ui5-input id="searchInput" placeholder="Enter search criteria ...">
	<ui5-icon id="searchIcon" data-ui5-slot="icon" src="sap-icon://search" class="inputIcon"></ui5-icon>
</ui5-input>
`
(2) Using one or both of the following events.

The ui5-icon has press event (fired the icon is clicked), you can bind for it and perform your search.
The ui5-input has 'submit' event (fired on Enter key when the focus is in the input field),  you can bind for it and perform your search.

And, there is an example ("Input as Search Field"), that you can explore:
https://sap.github.io/ui5-webcomponents/playground/components/Input/

Best,
ilhan

**Comment by vbersch** [comment]
perfect, thank you!
