### ISSUE TITLE
ui5-tree-item checkbox not dependant of ui5-tree

### ISSUE THREAD

**Issue by rchrdchn** [SAP/ui5-webcomponents#2601]
**Is your feature request related to a problem? Please describe.**
Single `ui5-tree-item` cannot have checkbox unless all `ui5-tree` component have checkboxes

**Describe the solution you'd like**
Have an option for a single `ui5-tree-item` to have checkbox without being dependant of checkboxes being at the top of the `ui5-tree`

**Additional context**
Current state of the `ui5-tree` and `ui5-tree-item` component

![Screen Shot 2020-12-18 at 15 37 06](https://user-images.githubusercontent.com/11576789/102672879-f2aef300-4146-11eb-9c81-8b115ec97842.png)

Feature request

![Screen Shot 2020-12-18 at 15 25 28](https://user-images.githubusercontent.com/11576789/102672940-1a9e5680-4147-11eb-83cb-aaf108b1fac1.png)

**Comment by rchrdchn** [comment]
Hi @ilhan007 - could you please add the SuccessFactors label as well? Thanks!

**Comment by ilhan007** [comment]
Hello @rchrdchn did you find this behaviour in the standard sap.m.Tree or in the Fiori 3 guidelines, because I could not.
If not - you will need to raise a request to the the Visual Design team to spec this. I sent you an email with the details.

**Comment by rchrdchn** [comment]
Hi @ilhan007  - please feel free to close this request for now as we have implemented a customized component for the time being. Thank you!
