### ISSUE TITLE
ui5-avatar-group: overflow button is styled like an active button.

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#2611]
**Describe the bug**
The overflow-button of the `AvatarGroup` component is styled like an aktive element (button). However, no overflow menu is implemented yet, so this button has no effect.

**Isolated example**
https://codesandbox.io/s/ui5-webcomponents-forked-luz1s?file=/index.html

**Expected behavior**
The button should be active (change color on hover/active, cursor: pointer, etc.) only if the overflow menu is implemented or a custom event can be applied.

**Screenshots**
![2020-12-21_16-43-08 (1)](https://user-images.githubusercontent.com/9749730/102794789-29397780-43ac-11eb-9f73-f9f49899d08f.gif)

**Context**
- UI5 Web Components version: 1.0.0-rc.11

**Affected components** *(if known)*

- AvatarGroup

**Comment by Martotko** [comment]
Hello @SAP/ui5-webcomponents-topic-p  I am forwarding this issue to you for a statement what should be done in this case.

**Comment by nnaydenow** [comment]
Hi @Lukas742,

Button is acting like active button because it is supposed to have menu implementation. Could you please tell us your use case so we can discuss it?

Regards,
Nayden

**Comment by Lukas742** [comment]
Hi @nnaydenow 

I wasn't aware that the menu implementation has to be done by the user. Sorry for the confusion.

Is there any particular reason not to offer this behavior out of the box? To be honest, the way it is currently implemented is not very intuitive for me. Especially as you need to first calculate the number of the hidden avatars and then clone them to display them in your popover.

**Comment by nnaydenow** [comment]
Hi @Lukas742,

There is no strict Fiori 3 design about the content of the <code>ui5-popover</code> and what should be the behavior when the button is pressed. Some users may have custom navigation inside it or to open different control than <code>ui5-popover</code>. This is the reason why the implementation is left in the hands of the developers. 

Regards,
Nayden
