### ISSUE TITLE
ui5-avatar-group: add possibility to change the shape of the overflow-button

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#2612]
**Is your feature request related to a problem? Please describe.**
There is no option to change the shape of the overflow button, so when the avatars are in square shape, the overflow-button is still a circle.
https://codesandbox.io/s/ui5-webcomponents-forked-f6h05?file=/index.html

**Describe the solution you'd like**
I'm not 100% sure if this request is in line with the guidelines, because I didn't find any specs for the overflow-button with square avatars, but personally I would prefer a prop where I can control the shape of the overflow-button.

**Screenshots**
<img width="710" alt="Screenshot 2020-12-21 at 16 58 27" src="https://user-images.githubusercontent.com/9749730/102795921-c2b55900-43ad-11eb-8c0c-50d6dd820f78.png">

**Comment by ilhan007** [comment]
Hello @Lukas742 this is not present in the current spec, so the Visual Design team has to receive a feature request for this, evaluate and implement such before we start implementation. I will contact you offline with more details.

**Comment by ilhan007** [comment]
As discussed offline, for now we will document that  the "Circle" shape is the one Fiori 3 suggests and meant to be used. 
We wont't add an option to change the shape of the overflow button. But, if more demand for the Square shape occurs we will reconsider this.
