### ISSUE TITLE
ColorPalette (ui5-color-palette): New component

### ISSUE THREAD

**Issue by fifoosid** [SAP/ui5-webcomponents#2615]
**Is your feature request related to a problem? Please describe.**
A color palette component should be implemented. Reference: https://sapui5.hana.ondemand.com/#/entity/sap.m.ColorPalette/sample/sap.m.sample.ColorPalette

**Additional context**
The current use case: this component will be used in responsive popover

![image](https://user-images.githubusercontent.com/16850339/102879519-88ea5e00-4452-11eb-9f96-f82463ea8085.png)

**Comment by ilhan007** [comment]
**Background**
We need a color palette component to be used in the TextEditor (RichTextEditor) we are currently building
to allow users select text's color and text's background-color. Later can be used to build ColorPalettePopover if we decide is necessary and find it useful.

**Reference**
https://sapui5.hana.ondemand.com/#/entity/sap.m.ColorPalette/sample/sap.m.sample.ColorPalette

**Main Use-Case**
The palette will be mainly used inside a ui5-popover or ui5-responsive-popover

**Restrictions**
As in openui5, we would like to display up to 15 coloured squares as part of the palette.

**API**

1. Definition of the colors the user clack select of, either via property, or via slot

```js
// Variant 1: string property of comma separated CSS colors:
properties: {
  colors: {
     type: String
  }
}
```

```html
<ui5-color-palette colors="darkblue, #444444, white, black, rgb(0,0,0), hsla(50%,10%,30%,0.5), #fff, green">
```


```js
// Variant 2: with abstract element as a slot

slots: {
   colors: {
       type: HTMLElement
   }
}
```

```html
<ui5-color-palette> 
 <ui5-color-palette-entry value="darkblue">
 <ui5-color-palette-entry value="#333">
 <ui5-color-palette-entry value="#444">
</ui5-color-palette> 
```

2. We need to fire an event when the users interacts/clicks the coloured squares (SPACE, ENTER as well)

```js
Events: {
    click: {
       details: {
          color: {
              type: "String"
           }
       }
    }
}
```

**Keyboard handling**
By the existing spec - at least ArrowKeys navigation + ENTER and SPACE

**Screen Reader**
By the existing spec

**Playground Sample**
