### ISSUE TITLE
ui5-input: passing `null` to the value property has no effect

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#2616]
**Describe the bug**
Resetting the `value` of the `Input` by setting it to `null` is not possible. Only when passing it an empty string, the value is changed.

**Isolated example**
https://codesandbox.io/s/ui5-webcomponents-forked-3n28i?file=/index.html

**Screenshots**
![2020-12-22_16-23-53 (2)](https://user-images.githubusercontent.com/9749730/102904754-73852c00-4472-11eb-800b-352b4aa36196.gif)

**Context**
- UI5 Web Components version: 1.0.0-rc.11

**Original Issue**
https://github.com/SAP/ui5-webcomponents-react/issues/1115

**Comment by Martotko** [comment]
Hello @ui5-webcomponents-topic-rl I am forwarding this issue to you, because it's reproducible.
