### ISSUE TITLE
Compatibility with vue 3

### ISSUE THREAD

**Issue by tudorels** [SAP/ui5-webcomponents#2621]
**Is your feature request related to a problem? Please describe.**
I'm trying to use web components with vue 3, but is not working. Ex. for ui5-table event @row-click is not working with vue 3 latest.

**Describe the solution you'd like**
Add compatibility with vue 3.

**Comment by gmkv** [comment]
Hi @tudorels 

Can you check this [example](https://codesandbox.io/s/sad-newton-jumq6?file=/src/App.vue)?
Clicking on a row of the `ui5-table` fires a row-click event for me.

Would you be able to provide a sample where we could reproduce the issue?

Regards,
Georgi

**Comment by tudorels** [comment]
Your example is working on CodeSandbox, but on my computer is not working, @row-click is not fired. How can I debug this?, with vue 2 is working and with vue 3 is not ... What should I check?
Thank you very much!

**Comment by gmkv** [comment]
Sorry, I'm not sure. Try reaching out to the Vue.js community.
