### ISSUE TITLE
ui5-label: Text alignment does not work with wrap

### ISSUE THREAD

**Issue by jurajbak** [SAP/ui5-webcomponents#2624]
**Describe the bug**
Text alignment does not work if _wrap_ attribute is set.
It's caused by missing _width_ CSS setting in shadow DOM if wrap attribute is set.

**To reproduce**
1. Create ui5-label with set text-align by CSS and wrap attribute.

**Isolated example**
```
<ui5-label style="width: 300px; text-align: right;">Aligned right as expected.</ui5-label><br>
<ui5-label wrap style="width: 300px; text-align: right;">Not aligned.</ui5-label>
```

**Expected behavior**
Text alignment will work according to CSS set to root element.

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/10481182/103447182-11090880-4c88-11eb-8134-5518e0d1f5e8.png)

**Context**
- UI5 Web Components version: 1.0.0-rc.11

**Affected components** *(if known)*
ui5-label

**Comment by a-z-ivanov** [comment]
Hello @ui5-webcomponents-topic-rd,

The wrapping element with class ui5-label-root has width of 100% only when the wrap property is set on the control. Without it, the control does not respect the provided width of 300px.
See here packages/main/src/themes/Label.css

**Comment by jurajbak** [comment]
> The wrapping element with class ui5-label-root has width of 100% only when the wrap property is set on the control. Without it, the control does not respect the provided width of 300px.

Yes, exactly. That's the point. Is there a reason why is `width` binded to wrap attribute?

All ui5-label-root attributes, except `white-space: nowrap;` can be assigned to label regardless wrap attribute.
I would recommend to change CSS definition
```
:host(:not([wrap])) .ui5-label-root {
	width: 100%;
	font-weight: inherit;
	display: inline-block;
	white-space: nowrap;
	cursor: inherit;
	overflow: hidden;
}
```
to this:
```
.ui5-label-root {
	width: 100%;
	font-weight: inherit;
	display: inline-block;
	cursor: inherit;
	overflow: hidden;
}
:host([wrap]) .ui5-label-root {
	white-space: nowrap;
}
```
