### ISSUE TITLE
SuccessFactors: ui5-tree-item counter

### ISSUE THREAD

**Issue by agauyeung** [SAP/ui5-webcomponents#2633]
**Is your feature request related to a problem? Please describe.**
The ui5-tree-item does not support the counter as described in the [Fiori documentation](https://experience.sap.com/fiori-design-web/tree/#components),

**Describe the solution you'd like**
Please add support for a counter like how [ListItem](https://sap.github.io/ui5-webcomponents/playground/components/List/) supports `info`.

**Describe alternatives you've considered**
Unsure of any.

**Additional context**
See the info attribute for `ui5-list-item` below:
![image](https://user-images.githubusercontent.com/8508119/103817099-e8339b00-501a-11eb-984a-a5752a1e8356.png)

**Comment by ilhan007** [comment]
Hello @agauyeung 

The feature request has been evaluated and approved. As soon as the issue is planned for development, we will update you on the timelines.

**Comment by nnaydenow** [comment]
Internal reference: 5003
