### ISSUE TITLE
Multi Combo box additional text is not visible

### ISSUE THREAD

**Issue by sunnyyadav100** [SAP/ui5-webcomponents#2637]
**Describe the bug**

**To reproduce**
1. add ui5-mcb-item as <ui5-mcb-item text="My text" additional-text="some info"></ui5-mcb-item>
2. Additional text information is not propagated to ui5-li component https://github.com/SAP/ui5-webcomponents/blob/master/packages/main/src/MultiComboBoxPopover.hbs#L70 

**Isolated example**

**Expected behavior**

The additional text should be displayed

**Screenshots**

**Context**
- UI5 Web Components version: 1.0.0-rc.11
- OS/Platform: {...}
- Browser *(if relevant)*: {...}
- Other information: {...}

**Affected components** *(if known)*
Multi Combox box

**Log output / Any errors** in the console
```
{...}
```

**Organization:** *(if applicable)*
SAP Ariba

**Priority:** *(optional)* *(Low, Medium, High or Very High)*
Medium

**Comment by ilhan007** [comment]
Hello @sunnyyadav100

The additionalText would be displayed properly once the fix is released with RC 12 at the end of January
