### ISSUE TITLE
Input Suggestions are not shown in Dialog on first focus.

### ISSUE THREAD

**Issue by lateefsofi** [SAP/ui5-webcomponents#2652]
**Describe the bug**
<ui5-input show-suggestions ></ui5-input> controls is not showing suggestion in a dialog first time.
If ui5-input is the first control in a dialog and is auto focused then suggestions are not shown. When focus is moved out first and 
then focus ui5-input back, then the suggestions are showing up.

**To reproduce**
1. Go to https://codesandbox.io/s/ui5-webcomponents-forked-6elmf?file=/index.html
2. Click "Open Dialog"
3. When dialog opens, focus will be on the input element, type "ca" and see no suggestions is shown.
4. Now click outside ui5-input box and click back to ui5-input.  Once you get focus back to ui5-input, type "ca", you should see suggetions

**Isolated example**
[CodeSandbox](https://codesandbox.io/s/ui5-webco mponents-forked-6elmf?file=/index.html)

**Expected behavior**
Once user open Dialog and ui5-input field is auto focused, then the suggestions should be shown.

**Context**
- UI5 Web Components version: 0.29.0
- OS/Platform: any
- Browser *(if relevant)*: any
- Other information: Input suggestion was working with version v0.23.6 as expected, but with latest versions(0.27.0 and above) it is not working

**Organization:** *(if applicable)*
Success Factors

**Priority:** *(optional)* *High*

**Comment by nnaydenow** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

The issue is reproducible. Seems that the to comes from the applying of focus when dialog is open. Suggestions are unusable the focus leaves and returns the input or when the input is clicked with mouse.

Regards,
Nayden
