### ISSUE TITLE
ui5-date-picker: default date is not right for US timezone

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents#2655]
**Describe the bug**

**To reproduce**

1. Go to https://github.wdf.sap.corp/pages/xweb/goalmanagementx/app.html?mock#/goal-list
2. click 'Skip Tour' button
3. click more actions button on the top right of Goal Card
4. click 'Create Activity' button
5. select a new satus 'low'
6. open date picker for 'Achieved On'
7. The default date is not right for us timezone 

![ChineseTimezone](https://user-images.githubusercontent.com/13098801/104278205-2cbfaa80-54e3-11eb-8cbd-55fb54e65217.jpg)
![USTimezone](https://user-images.githubusercontent.com/13098801/104278207-2e896e00-54e3-11eb-965e-8c81c0bcce07.jpg)

**Expected behavior**
The default date should be today for different timezone.

**Context**
- UI5 Web Components version: 0.27.3
- OS/Platform: {...}
- Browser *(if relevant)*: {...}
- Other information: {...}

**Comment by ilhan007** [comment]
Hello @GongRichard first of all we stopped supporting 0.27, you should upgrade to 0.29.

We recently performed a significant refactoring in the date-time components, that also addresses issues with the timezone, no we might already have the solution - https://github.com/SAP/ui5-webcomponents/pull/2598

You can see this change and the issues it resolves

@vladitasev can you check if the change will resolve this issue and if yes - do you see any problems/risks to cherry pick the change in the 0.29 branch.

**Comment by vladitasev** [comment]
The mentioned change fixes the wrong `value` but not the wrong `today` date.

I'll address this separately.

**Comment by GongRichard** [comment]
@vladitasev ,

This issue will be fixed in which version? 0.29.1?

Thanks,
Richard

**Comment by GongRichard** [comment]
@vladitasev and @ilhan007 ,
This issue still exists, please check https://github.wdf.sap.corp/pages/xweb/goalmanagementx/app.html?mock#/goal-list,
The WC version is 0.29.4

**Comment by vladitasev** [comment]
Hi Richard,

I've pushed a fix to the 0.29 branch, so please test with the next release `0.29.5` and let me know if it worked.

Regards,
Vladi

**Comment by mydavidzhang** [comment]
@vladitasev , 
There is still one issue that when set value and max-date same date then it will show "0001" year. If set max-date bigger than value then it can show year correctly.
![Screen Shot 2021-03-04 at 3 19 20 PM](https://user-images.githubusercontent.com/10460331/110044908-c4c95b80-7cfe-11eb-8f44-cf6e81cf67e6.png)
![Screen Shot 2021-03-04 at 3 15 48 PM](https://user-images.githubusercontent.com/10460331/110044912-c5fa8880-7cfe-11eb-9309-173f185f6cd3.png)
