### ISSUE TITLE
On behalf of SuccessFactors : UploadCollection could not show full text of no-data-description and no-data-text

### ISSUE THREAD

**Issue by mydavidzhang** [SAP/ui5-webcomponents#2672]
**Describe the bug**
When set long text for no-data-description and no-data-text of UploadCollection they are shown "ellipsis" at end. User could not see the full texts.

**To reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/UploadCollection/
2. Chrome dev tool to inspect elements of no-data-description and no-data-text for no data UploadCollection case, then change texts to longer ones.
3. ellipsis shown for both texts at end

**Isolated example**
https://sap.github.io/ui5-webcomponents/playground/components/UploadCollection/ inspect element and change text to long ones.

**Expected behavior**
no-data-description and no-data-text should wrap the text the new line so that user could see full text.

**Screenshots**
UI5 Web Component
![Screen Shot 2021-01-12 at 8 43 25 AM](https://user-images.githubusercontent.com/10460331/104346118-e69f2280-54b3-11eb-9556-742e9d01073b.png)

SAP UI5 UploadCollection behavior is wrapping text (remove all items in the list) https://sapui5.hana.ondemand.com/#/entity/sap.m.UploadCollection/sample/sap.m.sample.UploadCollection
![Screen Shot 2021-01-12 at 8 41 36 AM](https://user-images.githubusercontent.com/10460331/104346365-2e25ae80-54b4-11eb-85cf-ebd567a20354.png)

**Context**
- UI5 Web Components version : 0.29.0 (SuccessFactors is using this version)
- OS/Platform: Any
- Browser *(if relevant)*: Any

**Affected components** *(if known)*
UploadCollection

**Organization:** *(if applicable)*
SuccessFactors

**Priority:** *(optional)* *(Low, Medium, High or Very High)*
High - SuccessFactors is using this component to deliver feature.

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-rd could you take a look of the issue?

It seems the noDataText and noDataDescrciption should wrap, instead of truncating. Could you confirm that and review possible solution: https://github.com/SAP/ui5-webcomponents/pull/2674
