### ISSUE TITLE
Input maxlength field not working when setting input Type

### ISSUE THREAD

**Issue by Wint81** [SAP/ui5-webcomponents#2680]
**Describe the bug**
In react, when using Input with the property type set to Number, the maxlength property is being ignored

**Expected behavior**
User shall not be able to enter more than the maxlength property set.

**Context**
- UI5 Web Components version ->RC11
- OS/Platform: {...}->Mac OS Big sur
- Browser *(if relevant)*: {...} -> Chrome
- Other information: {...}

**Priority:**
Medium

**Comment by nnaydenow** [comment]
Hello @Wint81,

As you can see in the documentation of the input (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input), input with type=Number doesn't support maxlength attribute.

Regards,
Nayden
