### ISSUE TITLE
For SuccessFactors : File name link is truncated in UploadCollectionItem component 

### ISSUE THREAD

**Issue by mydavidzhang** [SAP/ui5-webcomponents#2693]
**Describe the bug**
In UploadCollection component when item  (UploadCollectionItem) attribute file-name-clickable is true and has a long file name it will be truncated at end.

**To reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/UploadCollection/
2. Check "UploadCollection With File Renaming Enabled" section.
3. Change to long file name for both
4. First item (file name clickable) file name has been truncated.
5. Second item (file name not clickable) file name is wrapped.

**Isolated example**
https://sap.github.io/ui5-webcomponents/playground/components/UploadCollection/

**Expected behavior**
Below two UIs are acceptable for the clickable file name. Please check Fiori design to make decision.

1. Show "..." at end instead of just truncate word.
2. Wrap file name.

Questions:

1. Need set a max length when display name?
2. Should keep wrapping behavior consistent between clickable file name and not clickable file name?

**Screenshots**
![Screen Shot 2021-01-15 at 10 36 19 AM](https://user-images.githubusercontent.com/10460331/104766413-5e24ba00-571f-11eb-9e75-1d1e84707e88.png)

**Context**
- UI5 Web Components version 0.29.0
- OS/Platform: MacOS
- Browser *(if relevant)*: Tested in Chrome. Same issue for all browsers.

**Affected components** 
UploadCollection
UploadCollectionItem

**Organization:**
SuccessFactors

**Priority:** 
High
b2105 release depends on this issue fixing

**Comment by nnaydenow** [comment]
Hello @SAP/ui5-webcomponents-topic-rd,

When the file name is too long and clickable it is not truncated.

The issue is reproducible in this sample:
https://codesandbox.io/s/ui5-webcomponents-forked-6582d

Regards,
Nayden
