### ISSUE TITLE
Unexpected 2px "padding" in Dialog

### ISSUE THREAD

**Issue by pavelkornev** [SAP/ui5-webcomponents#2694]
**Describe the bug**
When there is no `headerText` and there is nothing inside `header` slot, then 2px padding remains at the top of the dialog.

**To reproduce**
1. Create dialog without `headerText` and without `header` slot
2. Check the resulting rendering (see sandbox link below)

**Isolated example**
https://codesandbox.io/s/ui5-webcomponents-forked-gclih?file=/index.html

**Expected behavior**
`ui5-popup-header-root` is set to `display: none` when there is no `headerText` and there is nothing inside `header` slot 
https://github.com/SAP/ui5-webcomponents/blob/bf8caaf2eb71156e6bbda3c1492022519fe25bf7/packages/main/src/Dialog.hbs#L4-L13

**Screenshots**
![Screen Shot 2021-01-16 at 21 04 52](https://user-images.githubusercontent.com/748043/104821939-b3f08380-583f-11eb-9187-8e53e2107c28.png)

**Affected components** 
* Dialog
* Popover

**Organization:** SAP Graph

**Priority:** Medium

**Comment by nnaydenow** [comment]
Hello @SAP/ui5-webcomponents-topic-rd,

As @pavelkornev mention header ui5-popup-header-root is still visible even it is empty and this leads to visual misalignments.

The issue is reproducible in:
https://codesandbox.io/s/ui5-webcomponents-forked-gclih?file=/index.html

Regards,
Nayden
