### ISSUE TITLE
Dialog unexpectedly renders overlay when it is actually closed

### ISSUE THREAD

**Issue by pavelkornev** [SAP/ui5-webcomponents#2696]
**Describe the bug**
While having a Dialog component in closed state, if we trying to get a dom ref of the overlay, the overlay gets rendered (this is fine), but it also becomes unexpectedly visible with a closed dialog at the same time.

**Isolated example**
https://codesandbox.io/s/ui5-webcomponents-forked-r5wfq?file=/src/index.js
As it shown in this example, I try to get a `staticAreaItemDomRef` via public API:
https://github.com/SAP/ui5-webcomponents/blob/master/packages/base/src/UI5Element.js#L896-L901
In order to attach listener on the overlay to close `Dialog` component on click. It's unexpected that overlay is shown when dialog is actually closed.

**Expected behavior**
`hidden` attributed should not be removed from the overlay when getting its DOM reference.

**Screenshots**
![Screen Shot 2021-01-16 at 22 56 39](https://user-images.githubusercontent.com/748043/104823964-6891a180-584e-11eb-82ab-0d555572e0f6.png)

**Affected components**
* Dialog

**Organization:** SAP Graph

**Priority:** Medium

**Comment by Martotko** [comment]
Hi @pavelkornev,

I've checked the example and on it's not reproducible. The overlay is rendered with the "hidden" class when the dialog is in a closed state.
<img width="1274" alt="Screen Shot 2021-01-18 at 10 51 57" src="https://user-images.githubusercontent.com/16964129/104892925-709b2f80-597b-11eb-8598-705fec0f9e89.png">

Please explain in details how to reproduce it.

Best regards,
Martin

**Comment by pavelkornev** [comment]
@Martotko in order to reproduce it, you need just open the provided link.

Once you open it — the grey transparent background is an overlay which should not be visible since dialog is not open.

**Comment by Martotko** [comment]
Hello @ui5-webcomponents-topic-rd, I am forwarding this issue to you, because the issue is caused by the following code:

  dialog.getStaticAreaItemDomRef().then((overlayRef) => {
    overlayRef.addEventListener("click", () => dialog.close());
  });

The overlay is visible initially with this code in place and everything behind the dialog button is gray.

Best regards,
Martin
