### ISSUE TITLE
Incorrect Popover placement (sticks to browser window edge)

### ISSUE THREAD

**Issue by pavelkornev** [SAP/ui5-webcomponents#2697]
**Describe the bug**
When opening a Popover with property `placement-type="Bottom"` at the element which is close to the right border of the screen, the opened Popover sticks to the browser edge. On the other hand, if it opens on the left side of the browser there is a `~5px` margin.

**To reproduce**
1. Go to sandbox example below
2. Click "Open Popover"

**Isolated example**
https://codesandbox.io/s/ui5-webcomponents-forked-r8vvw?file=/index.html

**Expected behavior**
Popover has a margin from browser window edge like on the left side (see screenshots below).

**Screenshots**
![Screen Shot 2021-01-16 at 23 16 44](https://user-images.githubusercontent.com/748043/104824371-641ab800-5851-11eb-96e6-999e47d3fd27.png)
![Screen Shot 2021-01-16 at 23 17 49](https://user-images.githubusercontent.com/748043/104824378-6a109900-5851-11eb-9ae5-803511b2198e.png)

**Affected components**
* Popover

**Organization:** SAP Graph

**Priority:** Medium

**Comment by nnaydenow** [comment]
Hello @SAP/ui5-webcomponents-topic-rd,

Could you please take a look?

Regards,
Nayden

**Comment by pavelkornev** [comment]
@fifoosid, which release is this going to be available?

**Comment by ilhan007** [comment]
Hi @pavelkornev - with 1.0.0-rc.13
