### ISSUE TITLE
MultiComboBox: Multiple MultiComboBox in one page will have the same id.

### ISSUE THREAD

**Issue by eleminsoda** [SAP/ui5-webcomponents#2698]
**Describe the bug**
As titled,  multiple MultiComboBox in one page will have the same id.

**Isolated Example**
https://codesandbox.io/s/jovial-bhaskara-vxltg?file=/src/App.js

**To Reproduce**
Inspect the two input of the MultiComboBox, you will find them with the same id="ui5-multi-combobox-input"

**Expected behavior**
Each element should have different id

**Screenshots**

![image](https://user-images.githubusercontent.com/27283476/104881015-933d4080-599b-11eb-859b-f8458561ca98.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.0.0
`@ui5/webcomponents-react` version: 0.10.3
Operating System: MacOS
Browser: Chrome

**Additional context**

**Comment by MapTo0** [comment]
Hey @eleminsoda ,

I could not identify any issue with having identical IDs in separate shadow roots. This is actually a feature of the Web Components standard. Could you please tell us more about your issue? Why do you need that, what you need to be achieved? 


https://stackoverflow.com/questions/56023322/are-duplicate-ids-allowed-in-separate-shadow-roots/56024664#56024664

Regards.
Martin

**Comment by gmkv** [comment]
The same element IDs exist in seperate documents, so this would not be an problem in terms of invalid HTML. You can read more about this in my colleague Martin's comment.

I will close the issue.
If you have questions or something is unclear, feel free to reopen this issue or create a new one.
