### ISSUE TITLE
Custom setting the locale for the UI5 Web Components (not only according to the locale of the browser) 

### ISSUE THREAD

**Issue by f-zou** [SAP/ui5-webcomponents#2708]
current ui5 components use the cldr according to the locale of the browser. 
is it possible to use the locale from somewhere else ?  
e.g a user has defined the language and the region in his user profile in the system (e.g. de_CH). But the Setting in the Browser is en_GB. 
So the ui5 components should use cldr of de_CH instead of en_GB.  is this possible?

**Comment by f-zou** [comment]
have read through the document. 
this config should work:
  <script data-ui5-config type="application/json">
    {
      "language": "de_CH"
    }
  </script>

**Comment by ilhan007** [comment]
Yes, use setLanguage if you have use cases to make dynamic changes, otherwise the script is enough for one time configuration.
