### ISSUE TITLE
MessageBox inside other component fails

### ISSUE THREAD

**Issue by Wint81** [SAP/ui5-webcomponents#2713]
**Describe the bug**
Hello,
I am trying to use the message box control in one of my components but I'm getting the following error:
![image](https://user-images.githubusercontent.com/77397740/105213293-d4298680-5b4e-11eb-8395-983ec8d7500e.png)

**To reproduce**
In my component I have the following code:
`{ReactDom.createPortal(<MessageBox
                actions={[
                    'OK',
                    'A custom action',
                    'Cancel'
                ]}
                onClose={function noRefCheck() {
                }}
            >
                Press "Escape" to close the MessageBox.
            </MessageBox>
            , document.body)}`
I had used the same approach for the use of the Dialog component and got no issue at all.

**Context**
- UI5 Web Components version: 1.0.0-rc.11
- OS/Platform: macOS Big sur
- Browser : Chrome

**Priority:** *(optional)* *(Low, Medium, High or Very High)*
High

**Comment by ilhan007** [comment]
Hello @Wint81 please provide a sample to reproduce the issue. 
You can use CodeSandbox to create a sample, perhaps you can use [this codesanbox sample](https://codesandbox.io/s/small-cloud-rrxn2?file=/src/App.js:335-355) as a base - it uses ui5 webcomponents + ui5-webcomponents-react.

FYI @MarcusNotheis

**Comment by MarcusNotheis** [comment]
Which version of ui5/webcomponents-react are you using? Can you please try upgrading to our latest version 0.13.4? We fixed this issue in some of our recent releases.

**Comment by Wint81** [comment]
Hello @MarcusNotheis and @ilhan007,
Updating to 0.13.4 helped indeed, thanks a lot for the help
Best regards
