### ISSUE TITLE
ui5-responsive-popover: error on opening

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents#2717]
**Describe the bug**
When I try to open a `ui5-responsive-popover` with two `ui5-list` as children, I get the following error:
```
List.js:595 Uncaught TypeError: Cannot read property 'id' of null
    at HTMLElement.isForwardElement (List.js:595)
    at HTMLElement._onfocusin (List.js:561)
    at EventPart.handleEvent (parts.ts:512)
    at HTMLDivElement.EventPart.__boundHandleEvent (parts.ts:470)
    at HTMLElement.applyFocus (Popup.js:290)
    at async HTMLElement.applyInitialFocus (Popup.js:274)
```

**To reproduce**
1. open the playground: https://codesandbox.io/s/late-cookies-gdgj4?file=/src/App.js
2. Click on "Open Popover"
3. See the error

**Isolated example**
https://codesandbox.io/s/late-cookies-gdgj4?file=/src/App.js

**Expected behavior**
I would expect that the popover opens without an error

**Screenshots**

**Context**
- UI5 Web Components version: 1.0.0-rc.11
- OS/Platform: macOS
- Browser: Chrome

**Affected components**
- ui5-responsive-popover
- ui5-list

**Log output / Any errors** in the console
```
List.js:595 Uncaught TypeError: Cannot read property 'id' of null
    at HTMLElement.isForwardElement (List.js:595)
    at HTMLElement._onfocusin (List.js:561)
    at EventPart.handleEvent (parts.ts:512)
    at HTMLDivElement.EventPart.__boundHandleEvent (parts.ts:470)
    at HTMLElement.applyFocus (Popup.js:290)
    at async HTMLElement.applyInitialFocus (Popup.js:274)
```

cc @stevetsanders

**Comment by Martotko** [comment]
Hello @ui5-webcomponents-topic-p I am forwarding this issue to you, because the "isForwardElement" methodof the List is not working properly in some cases.

Best regards,
Martin

**Comment by stevetsanders** [comment]
hello colleagues, thank you for the quick fix on this issue! Is there any ETA on when it will be released? This is currently blocking our production release in our app

**Comment by ilhan007** [comment]
Hello @stevetsanders can you share more details about your app and release plan?
Our release plan can be seen here https://github.com/SAP/ui5-webcomponents/projects

The next RC will be released on 11 Feb. But, there is an option to provide you a "master" version, that includes the very latest development. The version would look like 0.0.0-commit_id and can be installed with the "next" tag
```sh
npm install @ui5/webcomponents@next
```

<img width="374" alt="Screenshot 2021-01-22 at 9 26 02 PM" src="https://user-images.githubusercontent.com/15702139/105536073-75a00c00-5cf8-11eb-93a2-7e5be558d788.png">

**Comment by stevetsanders** [comment]
Hi @ilhan007 , Actually I spoke wrongly. It doesn't impact our production release, but we did want to update our libraries with a couple of new features available.

Thanks a lot for the info, I'll try to install the version for the specific commit and see if it works out.

**Comment by stevetsanders** [comment]
hi @ilhan007 , any chance you could provide another 'next' version so we could try it out?
