### ISSUE TITLE
Table Column minWidth property documentation unclear/incorrect

### ISSUE THREAD

**Issue by Lettucez** [SAP/ui5-webcomponents#2727]
- [x] Documentation is unclear
- [x] Documentation is incorrect (possibly?)

The documentation states "The responsive behavior of the Table is determined by this property. As an example, by setting minWidth property to 40em ..." however the minWidth column is typed as a number. 

How can you use a value of "40em"?

Thanks.

**Comment by Lukas742** [comment]
Hi @Lettucez 

I guess this description is a remnant of an older implementation of the `Table`.

I will transfer this issue to the ui5-webcomponents team, as this component is developed by them.

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-rl  could you take a look?
