### ISSUE TITLE
HTML Form support

### ISSUE THREAD

**Issue by samba2** [SAP/ui5-webcomponents#273]
**A little feedback**
I am impressed by UI5 Web Components and advertise them heavily as "the future is here" in my work environment. Keep up the good work!

**My idea/ suggestion**
At work we use two different styles of web apps. For highly interactive applications we build SPAs (currently with OpenUI5 or Angular). For small, more workflow based applications we use classic server side rendering as you could do it e.g. with _express_ in node.js. The latter style is well described by the ROCA pattern: https://roca-style.org/

Using UI5 Web Components for SPAs is straightforward and very well demonstrated by the three example Todo apps (good job!). However, we'd love to use at least a subset of UI5 Web Components also for server-side generated pages.

When working with server-side generated pages you exchange data between client and server using classic HTML forms since most of the modern action-based server frameworks support automatic data binding for form data. 

After doing some reading I understand that a Web Component need to explicitly support HTML forms.  This is usually done by a more or less [ugly hack using a hidden form element](https://stackoverflow.com/questions/38623176/how-can-i-create-a-web-component-that-acts-like-a-form-element).

From an API perspective I could imagine to enable HTML form support explicitly:
```html
<form>
  Name: <ui5-input value="Input" insideForm="true"></ui5-input>
  <ui5-button type="Default" insideForm="true">Submit</ui5-button>
</form>
```
My attribute name `insideForm` is of course up for discussion ;-)

What do you think?

**Comment by pskelin** [comment]
Hi @samba2,
thanks for the encouraging words and also for sharing your thoughts.

This definitely sounds like a good idea. We have previously discussed usage of webcomponents inside forms, but always suggested the app developers create the hidden element themselves and keep it in sync.

What was stopping us from creating the hidden element in the light dom was the fact that if a framework (like react) is managing the light dom, we should not be modifying it from the components. Seeing your use case however, it makes sense that whenever someone wants to use the components in a form, a UI framework is not involved.

How does such an API sound to you?
```html
<form>
  <ui5-input value="Input" name="first-name"></ui5-input>
<form>
```

setting a `name` attribute is the equivalent of your proposal `insideForm="true"` and indicates to the component that a hidden input needs to be added and kept in sync. The created dom will look like this afterwards:

```html
<form>
  <ui5-input value="Input" name="first-name">
    <input data-autogenerated hidden value="Input" name="first-name"/>
  </ui5-input>
<form>
```

The native input will be created only if you pass a name attribute to the ui5-input and it will have the same name and the value will be kept in sync (the ui5-input will render a different input in its shadowdom, the data-autogenerated one is only there for the form). The intention then is that apps using frameworks don't set the name attribute, but instead bind to the value and submit forms programatically.

We also have to think about the submit button. Not sure how this can work with an additional button and firing an event for it. We'll give it a try but I assume from the example you also need the ui5-button for the form submit?

Does that sound like it will solve your case? We will consider some other use cases as well and keep the issue open, so feel free to share any additional ideas.

**Comment by samba2** [comment]
Hi pskelin,

This looks really good to me. So you would render the hidden tag just on request. I still don't know which components are good candidates to be "form enabled". At the end it is the usual suspects:
- input (plain + password)
- text box
- buttons
- radio + check boxes
- sometimes file upload

As I said we use forms on the lower end of interaction. As soon as something like a filtering table is required I would opt for a SPA approach.

**Comment by vladitasev** [comment]
Hi @samba2 

We added form support for:
- ui5-input
- ui5-textarea 
- ui5-datepicker 
- ui5-checkbox 
-ui5-radiobutton
which now automatically create and maintain hidden inputs whenever a "name" property is supplied.

...and in addition:
 - ui5-button
can act as a form submit button now, when a "submits" boolean property is supplied.

In order to activate the form support feature, add the following import to your application:
import InputElementsFormSupport from "./dist/InputElementsFormSupport.js";
(Note: this will require all form-relevant web components.)

Regards,
Vladislav
