### ISSUE TITLE
ui5-icon should work with message bundles from the actual icons package

### ISSUE THREAD

**Issue by pskelin** [SAP/ui5-webcomponents#2739]
right now, the ui5-icon component is fetching translations from the main package like this:
`fetchI18nBundle("@ui5/webcomponents");`

this also means that the icons package contains a message bundle that no one uses, and the main package contains texts that do not belong there.

this feature should include:
- [ ] the icon component should load message bundles from the relevant icon package - example icon `tnt/workflow-editor` should look up texts from `@ui5/webcomponents/icons-tnt`
- [x] the texts for icons should be removed from the main package

**Comment by vladitasev** [comment]
https://github.com/SAP/ui5-webcomponents/pull/2816
