### ISSUE TITLE
MultiInput RTL Issues

### ISSUE THREAD

**Issue by agauyeung** [SAP/ui5-webcomponents#2749]
**Describe the bug**
For ui5-multi-input, a user can view all tokens in a dropdown if the number of tokens exceed the width of the multi input. In RTL, the button to view the dropdown does not appear. Even if it does, it appears with the token names in the dropdown left-aligned.

**To reproduce**
1. RTL
2. Enter tokens until they exceed the width of the multi input
3. **Issue: ** The <n> more button does not appear most of the time.
4. Even if it does,...click the "<n> more" to view the token dropdown
5. **Issue: ** The token names are improperly aligned in the dropdown

**Isolated example**
https://codesandbox.io/s/ui5-webcomponents-forked-q1455?file=/index.html

**Expected behavior**
"<n> more should appear" when tokens exceed width.
Token names in the dropdown should be right-aligned.

**Screenshots**
![image](https://user-images.githubusercontent.com/8508119/106211142-0b1a2080-617d-11eb-94cf-256532175b50.png)
![image](https://user-images.githubusercontent.com/8508119/106210152-22580e80-617b-11eb-8830-2880f579d221.png)

**Context**
- UI5 Web Components version "1.0.0-rc.11"

**Organization:** SuccessFactors

**Priority:** High - Is functional one and makes a single component almost unusable under certain circumstances.

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-rl could you look into RTL appearance of the MultiInput. It is reproducible [here](https://codesandbox.io/s/ui5-webcomponents-forked-q1455?file=/index.html) and in our test pages

Open https://sap.github.io/ui5-webcomponents/master/playground/main/pages/MultiInput/ 
set dir="rtl" to the body
