### ISSUE TITLE
 [Feature request]  Busy State For SAPUI5 control

### ISSUE THREAD

**Issue by alex-zhang** [SAP/ui5-webcomponents#2750]
hi, 

For most of all cases, we need a busy when api request. 

And we found that we add this feature ourself more frequently for now.  i think it's a common case. and suggest that add this to ui5 wc libaray.

![image](https://user-images.githubusercontent.com/4457451/106224302-08bbd300-621e-11eb-816a-23b5f7d9c25d.png)

and also i found the ' Fiori Design Guidelines' also mentioned this point.

https://experience.sap.com/fiori-design-web/busy-state/

somtimes, we need a button busy, but for now, we can't do that until the busy-state.

**Comment by ilhan007** [comment]
Hello @alex-zhang for most of the cases wrapping content inside the ui5-busyindicator tag should be sufficient. is there particular use-case that you can't achieve this way?

**Comment by alex-zhang** [comment]
hi,

The picture above is hard for us to achieve  the target,  we have to  wrap the content and set the action buttons to disabled.

Yes,  maybe the result (that means we add the the ui5-busyindicator  by ourself in every case) is acceptable for us, but 
the case the very common,  because the api request is in evey where, and we need the loading process. 
full screen loading, button loading, container loading. There for, i guess we need a common solution for Component level.

**Comment by ilhan007** [comment]
Hi @alex-zhang 
it's a valid feedback, we had a brief discussion with the team about it.

Currently we have "busy" properties in the List and the ComboBox (although here it is named "loading", we will rename it to "busy") and we will have soon "busy" for the Table with this [change](https://github.com/SAP/ui5-webcomponents/pull/2593) to assist the growing on scroll functionality. 
For these kind of components and features we already accepted that we would need such state and handle the busy indication on component level. However, to have it for all components is something that we currently don't see as a must. Of course, if you encounter an important use-case that can't be done with what we currently have, then we will once more consider the request.

Best,
ilhan

**Comment by xpr0gamers** [comment]
Hello @ilhan007,

first of all, I think the busy indicator is a must have in the table component. It is nice to hear, what it will be soon available there. Is the busy indicator also available in the new page component? I think, it’s a must have for the page component! 

Best regards
Maxi

**Comment by ilhan007** [comment]
Hi @Nxpr0gamers, no the Page component does not have busy property, but you can wrap the whole page content in ui5-busyindicator and make it work.
