### ISSUE TITLE
[Tree]: Second level item is not expanding/collapsing

### ISSUE THREAD

**Issue by fifoosid** [SAP/ui5-webcomponents#2752]
**Describe the bug**
Tree second level item is not expanding/collapsing

**To reproduce**
1. Go to http://localhost:8080/test-resources/pages/Kitchen.html in Safari
2. Focus item  with text "Tree 1.1"
3. Press arrow left/right or click the arrow icon
4. The tree item is not toggled

**Expected behavior**

**Context**
- UI5 Web Components version
- OS/Platform: MACOUS
- Browser *(if relevant)*: Safari
- Other information: {...}

**Priority:** Medium

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-p I am forwarding the issue to you.

**Comment by fifoosid** [comment]
This issue is no longer reproducible in master branch
