### ISSUE TITLE
ui5-avatar-group: background color of avatar item is unsuitable

### ISSUE THREAD

**Issue by JosephineSu** [SAP/ui5-webcomponents#2753]
**Describe the bug**
When displaying image in avatar group，setting imageFitType of avatar with "contain", the background color is filled in blank space. It's not good. 
**To reproduce**
1. Go to https://qacand.lab-rot.ondemand.com/sf/goals?mock&_s.crb=NaW0pQA0eTNOcHBBwW8PShLET01T%252bFfiFppV2C6eH10%253d#/goal-detail?targetUserId=V2-PVGFCEF7uVBEA/EO+F6nUQ==&templateType=tgm&templateId=583&id=11001 
username：cgrant
pwd：Pwd1
2. ...In goal Detail page，there is a goal Align Down section where avatar-group is used. The avatar in align down section should be displayed like align up avatar，no background when image src exist.
![image](https://user-images.githubusercontent.com/38159212/106271385-683fd000-626a-11eb-9194-6a34e4db5786.png)

**Isolated example**

**Expected behavior**

**Screenshots**

**Context**
- UI5 Web Components version
- OS/Platform: {...}
- Browser *(if relevant)*: {...}
- Other information: {...}

**Affected components** *(if known)*

**Log output / Any errors** in the console
```
{...}
```

**Organization:** *(if applicable)*

**Priority:** *(optional)* *(Low, Medium, High or Very High)*

Setting priority would indicate the importance of the issue
and would help the process of dispatching and processing.

To set the appropriate priority, you need to consider the impact
and if the issue:
- Breaks entire application or system - High and Very High
- Is accessibility one (Screan Reader, Keyboard Handling) - Medium and High
- Is functional one and makes a single component unusable - Medium and High
- Is visual, styling one - Low and Medium

Note: the priority would be re-evaluated by the issue processors, according to the project internal criterias

**Business impact:** *(mandatory for "Very High")*

**Comment by kskondov** [comment]
Hello @JosephineSu,
I was unable to login with the provided credentials, can you please recheck them in order for me to further investigate the issue, thanks and
Best Regards,
@kskondov

**Comment by JosephineSu** [comment]
Hi @kskondov ,
Please use following info and try it again:
url: https://qacand.lab-rot.ondemand.com/sf/goals?mock&_s.crb=NaW0pQA0eTNOcHBBwW8PShLET01T%252bFfiFppV2C6eH10%253d#/goal-detail?targetUserId=V2-PVGFCEF7uVBEA/EO+F6nUQ==&templateType=tgm&templateId=583&id=11001
company: TALH2TGMM1
username: cgrant
password: Pwd1
 If you go to home page, navigate to Goals:
![image](https://user-images.githubusercontent.com/38159212/106565839-6592f280-656a-11eb-9fbc-22b14a526f6e.png)

Click one of goal cards, jump to goal detail page.
![image](https://user-images.githubusercontent.com/38159212/106566202-f538a100-656a-11eb-8a8d-1e67fd8fd1de.png)

Please feel free to contact me if you have any problem.

**Comment by IlianaB** [comment]
Hello @JosephineSu ,
I can't see an Avatar Group web component in the goal detail page:

![avatargroup-web-component](https://user-images.githubusercontent.com/10456158/107196449-4decbb80-69fb-11eb-9989-f0496897e71d.jpg)

Can you make a small sample using [codesandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html)?

Thanks and regards,
Iliana

**Comment by JosephineSu** [comment]
Hi @IlianaB,
I'm sorry for the late reply. I have tried to use codesanbox, but fail to reproduce this instance. Since our code are released, you can go to following url: https://qacand.hcm.ondemand.com/sf/goals?bplte_company=TALH2TGMM1&_s.crb=%2bdx7IIrKOwtiHksI%2fNSTsw5j%2fW29oPNqDtVyJq7eBjg%3d#/goal-detail?targetUserId=V2-4IqQhjnz9srFv7woXnPTcQ==&templateType=tgm&templateId=565&id=21705
company: TALH2TGMM1
username：cgrant
pwd：pwd1

<img width="652" alt="Screen Shot 2021-03-15 at 10 23 11 AM" src="https://user-images.githubusercontent.com/38159212/111095565-ac680500-8578-11eb-9073-210bd2538eff.png">

**Comment by JosephineSu** [comment]
If there are no goalAlignment section, please use mock data. 
The url is: https://qacand.hcm.ondemand.com/sf/goals?mock&bplte_company=TALH2TGMM1&_s.crb=a73P9OGDNRBKO4e%2b3nTraAAtkFVB4ywWMJJ%2fS8P9ixs%3d#/goal-detail?targetUserId=V2-0CnPmh/s1nd7tJFDK4thJQ==&templateType=tgm&templateId=583&id=11

**Comment by d3xter666** [comment]
Hi @JosephineSu ,

According to the documentation, this is expected behaviour. Please check the avatar's [background-color property](https://sap.github.io/ui5-webcomponents/playground/components/Avatar/). Its default value is **Accent6**

**Comment by JosephineSu** [comment]
Work as expected.
