### ISSUE TITLE
Tile component in SAPUI5

### ISSUE THREAD

**Issue by Dingyj3178** [SAP/ui5-webcomponents#2756]
Hi,

Do you have any plan for the tile component in SAPUI5?
It's useful while creating a launch page.
https://sapui5.hana.ondemand.com/#/entity/sap.m.StandardTile/sample/sap.m.sample.TileContainer

*I understand that I can create a tile-like box by using buttons and other components.

**Comment by ilhan007** [comment]
Hello @Dingyj3178 

thanks for the interest in our web components, not pans currently, because Tile component was never requested.

However, I can bring it for a discussion. Do you have a specific need / business case at the moment for such component or you are just curious.

Best Regards,
ilhan

**Comment by Dingyj3178** [comment]
Hi @ilhan007 

We are creating a Fiori-like Demo App to show side by side extension solution in a Non-SCP environment. (AWS etc.) We got the requirement of a launchpad screen.  It would be helpful if you want to create a Fiori-like launchpad in AWS so we can integrate other apps and utilize KPI tile for different systems.

Now it looks like this. But still missing a lot of functions like loading status. 
![image](https://user-images.githubusercontent.com/19564695/106544710-5b153080-654b-11eb-9ce4-9f0ddacf3671.png)

Best Regards,
Ding

**Comment by ilhan007** [comment]
Hello @Dingyj3178

currently we have ui5-card component, that can display header and content part, and also ui5-busyindicator component to represent a loading state. Combining both you can achieve the following:
<img width="215" alt="Screenshot 2021-02-04 at 9 42 26 AM" src="https://user-images.githubusercontent.com/15702139/106860620-5082a480-66cd-11eb-8473-2366192cbe2b.png">


```html
<ui5-busyindicator active size="Medium">
		<ui5-card
			id="card"
			status="in progress"
			heading="Title"
			subheading="subtitle">
				<div>your content</div>
		</ui5-card>
</ui5-busyindicator>
```

We don't plan to introduce Tile component for the time being
I hope the Card and BusyIndicator helps for you use-case. 

Best,
ilhan
