### ISSUE TITLE
ui5-wizard: the phone style is different with SAP UI5 Wizard phone style

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents#2763]
**Describe the bug**
The phone style is different with SAP UI5 Wizard phone style

**To reproduce**
1. Use mobile phone to open page https://sap.github.io/ui5-webcomponents/playground/components/Wizard/
2. Use mobile phone to open page https://sapui5.hana.ondemand.com/#/entity/sap.m.Wizard/sample/sap.m.sample.Wizard
3. compare the style, they are totally different.

**Expected behavior**
The phone style of ui5-wizard should be the same as sap.m.wizard.

**Screenshots**
![ui5-wizard](https://user-images.githubusercontent.com/13098801/106470986-2322d480-64dc-11eb-860d-2dd103b05c7f.jpg)
![sap m wizard](https://user-images.githubusercontent.com/13098801/106470995-261dc500-64dc-11eb-88b5-de09eedb00e0.jpg)

**Context**
- UI5 Web Components version
- OS/Platform: {...}
- Browser *(if relevant)*: {...}
- Other information: {...}

**Comment by ilhan007** [comment]
The responsive navigation step header is not yet released, it will be part of RC.12, while you are looking the RC.11 playground.

You can see this page, showing the master:
https://sap.github.io/ui5-webcomponents/master/playground/components/Wizard/
