### ISSUE TITLE
DateTimePicker: The AM/PM in German should be vormittags/nachmittags

### ISSUE THREAD

**Issue by SunnyWind** [SAP/ui5-webcomponents#2765]
**Describe the bug**
It's an I18N issue. In the time format of German, commonly the am/pm should be translated to vormittags/nachmittags

Reponce from https://ui5.sap.com/1.60.2/resources/sap/ui/core/cldr/de.json:
![image](https://user-images.githubusercontent.com/4338219/106561559-e00c4400-6563-11eb-82a3-11f43ac7eec4.png)

Also, in Russian, am/pm should be translated to утра/вечера

**Context**
- UI5 Web Components version: 1.0.0-rc.7

**Affected components** 
ui5-datetime-picker

**Organization:**
SAP

**Comment by unazko** [comment]
Hello colleagues,

Seems that this is an issue as according to the standard we are following:
https://www.unicode.org/reports/tr35/tr35-dates.html#Date_Field_Symbol_Table

"Even for countries where the customary date format only has a 24 hour format, both the am and pm localized strings must be present and must be distinct from one another. Note that as long as the 24 hour format is used, these strings will normally never be used, but for testing and unusual circumstances they must be present."

The issue could be reproduced at the following URL:
https://sap.github.io/ui5-webcomponents/playground/components/DateTimePicker/?sap-ui-language=de_De

Best Regards,
Boyan

**Comment by tsanislavgatev** [comment]
Hello @SunnyWind,

We consider this as a technical information about the date period. And we use only the AM/PM visualisation. And also they might be upper or lower case based on the locale of the user, as stated in the Date_Field_Symbol_Table: https://www.unicode.org/reports/tr35/tr35-dates.html#Date_Field_Symbol_Table
Support of this kind of translation might also affect the UI and the UX, as this will affect the size of the fields and also the input validation and input value change. We support the most commonly known one(the abbreviated -  AM/PM) as they are also supported in native html inputs.

Thanks and Best Regards,
Tsanislav
