### ISSUE TITLE
Duplicate font files are being loaded by ui-webcomponents

### ISSUE THREAD

**Issue by rama1990br** [SAP/ui5-webcomponents#2771]
**Describe the bug**
Duplicate font files being loaded by ui-webcomponents in the Continuous Feedback page in the qacand environment in IE.

**To reproduce**
1. Go to https://qacand.lab-rot.ondemand.com (Company instance: ESSRIOLGA, username: jkincaid, password: Welcome) in IE browser (not Chrome)
2. In the module picker, click on Continuous Feedback
3. Open the Networks tab
4. Reload the page
5. We see that "72-Regular-full.woff" and "72-Bold-full.woff" fonts are being loaded from "https://ui5.sap.com/sdk/resources/sap/ui/core/themes/sap_fiori_3/fonts/72-Regular-full.woff?ui5-webcomponents" and "https://ui5.sap.com/sdk/resources/sap/ui/core/themes/sap_fiori_3/fonts/72-Bold-full.woff?ui5-webcomponents" respectively as can be seen in the attached screenshots. This is unnecessary since those fonts are also being loaded from the qacand domain. Please help remove these duplicate fonts.

**Expected behavior**
Please help remove the duplicate fonts being loaded from ui5-webcomponents

**Screenshots**
![image](https://user-images.githubusercontent.com/32254036/106696255-2a57ea00-6591-11eb-8fbd-93023f13a1e5.png)
![image](https://user-images.githubusercontent.com/32254036/106696281-393e9c80-6591-11eb-9c1d-1c2df7285b96.png)

**Context**
- Browser *(if relevant)*: For some reason, this issue occurs only in IE and not in Chrome

**Comment by rama1990br** [comment]
I have filed this issue for SuccessFactors, so please add the "SF" label to this issue.

**Comment by vladitasev** [comment]
Hi @rama1990br 

The UI5 Web Component framework creates 2 font style tags: one for the override font, and one for the standard font. They are marked with special data attributes: `[data-ui5-font-face]` and `[data-ui5-font-face-override]` respectively. The framework **only creates them if they don't exist**.

The application has therefore control over the fonts this way. You can load your own fonts and as long as you put a `[data-ui5-font-face]` attribute on the style tag, the framework code won't create it again.

```html
<style data-ui5-font-face></style>
``` 

This is what it creates right now:
![image](https://user-images.githubusercontent.com/15844574/106875094-f559ad80-66de-11eb-9e67-6ba8f0a0f457.png)

If you don't want any of these fonts, create the tag yourself with just the ones you want (or empty tag if you want none), as long as you keep the attribute, the framework will do nothing.

Regards,
Vladi

**Comment by MR-Sharifi** [comment]
Hi everyone.

Despite the fact that official documentation suggested a way for using custom fonts and @vladitasev approved that in this issue, I'm still having problem with using my custom fonts in my Vue 3 app that uses UI5 web components!

I tried both `data-ui5-font-face` and `data-ui5-font-face-override` and none of them worked!

I have downloaded the `72-Regular.woff2` font and store it in `src/assets/`. Also added following code snippet in the `<head>` section of my `index.html`.

```html
<style type="text/css" data-ui5-font-face>
    @font-face {
        font-family: "72";
        font-style: normal;
        font-weight: 400;
        src: local("72"),
        url(src/assets/72-Regular.woff2) format("woff2");
    }
</style>
```

As you can see in the image below, the fonts are load via request and custom fonts are not considered!!!

![image](https://user-images.githubusercontent.com/29632708/188332234-7c123ac5-9c95-4b3f-9104-e5628075f8aa.png)

I sincerely accept any suggestion.
Thank you all.

**Comment by sajadabs** [comment]
Hi everyone.
The solutions suggested in this issue and official documentation does not work for me, too! 
But instead, I override CSS variables that related to fonts; the following snippet load my custom fonts and prevent loading SAP default fonts : 

```css
 :root {
  --sapFontFamily: "YOUR CUSTOM FONT", Arial, Helvetica, sans-serif !important;
  --sapFontLightFamily: var(--sapFontFamily) !important;
  --sapFontBoldFamily: var(--sapFontFamily) !important;
  --sapFontSemiboldFamily: var(--sapFontFamily) !important;
  --sapFontSemiboldDuplexFamily: var(--sapFontFamily) !important;
  --sapFontBlackFamily: var(--sapFontFamily) !important;
  --sapFontHeaderFamily: var(--sapFontFamily) !important;
}
```

Please update documentation to help others with this issue.
