### ISSUE TITLE
ui5-radiobutton: Unable to focus via keyboard if all are unselected. 

### ISSUE THREAD

**Issue by rajatmtalwar** [SAP/ui5-webcomponents#2774]
**Describe the bug**
When none of the ui5-radiobuttons is selected in a group. We can not focus on it via keyboard. It skips the radio buttons in tab flow.

**To reproduce**
1. Go to https://codesandbox.io/s/ui5-webcomponents-forked-7hqbl?file=/index.html
2. In the preview, focus on datepicker
3. Navigate via tab. 
4. Notice that it skips radio.

**Isolated example**
https://codesandbox.io/s/ui5-webcomponents-forked-7hqbl?file=/index.html

**Expected behavior**
It should not skip radio button.

**Affected components** *(if known)*
ui5-radiobutton

**Organization:** *(if applicable)*
SuccessFactors
**Priority:** *(optional)* *(Low, Medium, High or Very High)*
High

**Business impact:** *(mandatory for "Very High")*
Keyboard user will not be able to access radio buttons.

**Comment by ilhan007** [comment]
Hi @rajatmtalwar 
thanks for reporting, the behavior you describe is reproducible.

Can you tell us what is your use-case to use radio buttons in a group with none of them selected, usually radio buttons are used to always represent single option as selected.

BR,
ilhan

**Comment by rajatmtalwar** [comment]
Hi @ilhan007,

We have a use-case where we do not want to select an option by default. It is similar to 
https://experience.sap.com/fiori-design-web/radio-button/#exceptional-case-no-preselection-by-default

Regards,
Rajat

**Comment by ilhan007** [comment]
Hello @rajatmtalwar thanks for the input. Indeed, It seems it is a valid UX, we will work on it.
