### ISSUE TITLE
[BUG][ui5-wizard]Incorrect calculation of current step position

### ISSUE THREAD

**Issue by Hubery-Shen** [SAP/ui5-webcomponents#2784]
Dear colleagues,
**I am from SuccessFactors Web Experience Shanghai team.**

**Bug Description**
Version: 0.29.0

The ui5-wizard calculate the current wizard step position incorrectly.

**Reproduce step:**
1. go to website: [https://github.wdf.sap.corp/pages/xweb/goalmanagementx/app.html?mock#/goal-list?targetUserId=undefined&templateId=22&templateType=tgm](https://github.wdf.sap.corp/pages/xweb/goalmanagementx/app.html?mock#/goal-list?targetUserId=undefined&templateId=22&templateType=tgm)

2. click "skip tour button" to close the first time guidance dialog
3. click "Cascade to Me" button to open cascading dialog
4. select some goals in select goal list, and then click the next button
5. click one of selected goal in edit goal dialog to enter into form mode
6. slide down the scroll bar
7. you will find the ui5-wizard will highlight setup one tab first then highlight the current step two tab 

**Expected behavior**
When we slide down the scroll bar, because the current step is always step two, ui5-wizard should not highlight the step one first and then highlight the current step two. it should always highlight the current step two

![2021-02-05_11-11-48 (1)](https://user-images.githubusercontent.com/63704163/106986335-1fc26e00-67a6-11eb-9ef0-b1189b332b80.gif)

**Comment by ilhan007** [comment]
Hi @Hubery-Shen 
is it possible to update to 0.29.1 and check if the issue still occures.

BR,
ilhan

**Comment by Hubery-Shen** [comment]
Hi @ilhan007 

Yes, this bug is available in both 0.29.1 and 0.29.0
