### ISSUE TITLE
Dynamic Side Content

### ISSUE THREAD

**Issue by agauyeung** [SAP/ui5-webcomponents#2793]
**Is your feature request related to a problem? Please describe.**
Dynamic Side Content has not been implemented as a UI5 Web Component.

**Describe the solution you'd like**
Requesting the implementation of Dynamic Side Content as defined in the [Fiori Documentation](https://experience.sap.com/fiori-design-web/dynamic-side-content/).

**Describe alternatives you've considered**
Tried using a column from Flexible Column Layout, but the pixel breakpoints are different.

**Additional context**
This is a SuccessFactors request.

**Comment by ilhan007** [comment]
Hello @agauyeung thanks for the request. Can you add more details about your use-case? I imagine you trying to display two areas of content side by side and hide the less important one when certain breakpoints are reached. Would these areas (main and side content) be part of the normal page flow or part of dialog/popover.

I prepared a simple example, could this be sufficient for your use-case:
https://jsbin.com/notoduzizu/edit?html,output

**Comment by agauyeung** [comment]
hi @ilhan007 yes we are displaying some filters on the left side of a table. After hitting a particular breakpoint, the filters would be hidden. toggling it back into view in the smaller screen using a button would display it taking the full width of the screen.

**Comment by ilhan007** [comment]
Hi @agauyeung thanks, I see.

Did you look at the example in previous reply, do you think you can do it with pure html and css?

**Comment by agauyeung** [comment]
Hi @ilhan007 yep I did take a look. Thanks for the example 😊. While I believe it is certainly possible to achieve dynamic side panel behavior without a component, I do think there is some benefit to having this implemented as a web component. This would help to standardize breakpoints and such, as well as including show/hide animations.

**Comment by ilhan007** [comment]
Hello @agauyeung, sorry for the delay.

Do you have an example of the show/hide animation?
 I checked the public samples of the  [DynamicSideContent](https://openui5nightly.hana.ondemand.com/api/sap.ui.layout.DynamicSideContent), also checked the API, but I  could not see any animations.
Regarding the standard Fiori 3 breakpoints, you can think of exposing them or provide other convenient API to react when certain breakpoint is reached. 
But, let's first clarify the animation part and then we will decide how to continue - could you show us an example of DynamicSideContent, supporting animations.

BR,
ilhan

**Comment by agauyeung** [comment]
hi @ilhan007 you are right, I don't see the animation either. I misremembered :)

**Comment by ilhan007** [comment]
Hello @agauyeung 

the feature request can be tracked here:
https://github.com/SAP/ui5-webcomponents/issues/3170
The feature request is added to the responsible team's backlog (not planned yet, but will be at some point).

Please have a look at the description and if you miss any functionality feel free to comment.

BR,
ilhan
