### ISSUE TITLE
ShellBarItem: Popovers assigned to ShellBarItem do not open

### ISSUE THREAD

**Issue by toadslop** [SAP/ui5-webcomponents#2796]
**Describe the bug**
I want to make a popover open on clicking a ShellBarItem. However, the Popover simply opens and then closes again instantly.

**Isolated Example**
```
function App() {
  const popoverRef = useRef(null);

  const handleClick = e => {
    console.log(e.target);
    popoverRef.current.openBy(e.target);
  };

  const handleAfterOpen = () => {
    console.log('Opened');
  };

  const handleAfterClose = () => {
    console.log('Closed');
  };

  return (
    <div>
      <ShellBar>
        <ShellBarItem icon="globe" onItemClick={handleClick}></ShellBarItem>
      </ShellBar>
      <Popover onAfterClose={handleAfterClose} onAfterOpen={handleAfterOpen} ref={popoverRef}>
        Hi
      </Popover>
    </div>
  );
}
```

**To Reproduce**
1. Create an empty page with an empty div.
2. Add an empty ShellBar.
3. Add a ShellBarItem as a child of the ShellBar.
4. Create popover and associated popover ref.
5. Create handleClick method on the ShellBarItem and call popoverRef.current.openBy(e.target)
6. Popover will open and then immediately close.

**Expected behavior**
When clicking, the popover should open and remain open until the user clicks outside the popover.
Instead, it immediately closes.

**Screenshots**
Before clicking:
![image](https://user-images.githubusercontent.com/31160338/107133788-3e07a580-692f-11eb-8ab7-e59ef8417929.png)
After clicking:
(Note: console logs were added in the onAfterOpen and onAfterClose of the popover to prove that both events actually occurred; I also console logged e.target to show we have the correct element)
![image](https://user-images.githubusercontent.com/31160338/107133811-81621400-692f-11eb-938d-206a17fc9dc3.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.0.0-rc.11
`@ui5/webcomponents-react` version: ^0.13.8
Operating System: Windows
Browser: Google Chrome

**Additional context**
I tried doing this on code sandbox and the behavior was completely different.
There was a default icon displayed in the ShellBarItem though I did not define it.
When clicking the ShellBarItem before I had even defined any functionality, a popover would simply open.
This is does not happen on my local machine.

**Comment by Lukas742** [comment]
Hi @toadslop 

I was able to reproduce this issue with [ui5-webcomponents-react](https://codesandbox.io/s/nostalgic-hopper-9y4nd?file=/src/App.js) and also with pure [ui5-webcomponents](https://codesandbox.io/s/ui5-webcomponents-forked-c25jy?file=/src/index.js). (the links contain codesandboxes)

As this component is developed by the ui5-webcomponents team, I forwarded this issue to their repo.

One more thing though, I'm not really sure what you mean by that paragraph:

> I tried doing this on code sandbox and the behavior was completely different.
> There was a default icon displayed in the ShellBarItem though I did not define it.

If this has something to do with the problem you mentioned above, could you elaborate a bit more on that?

**Comment by toadslop** [comment]
@Lukas742, thanks for checking that for me so fast!

Sorry for the incomplete explanation. I tried reproducing this issue in the code sandbox, but in code sandbox I was able to open a popover without even defining a popover first. I just wanted to clarify that in the code sandbox one probably can't reproduce the issue.

**Comment by ilhan007** [comment]
Hello @toadslop @Lukas742 

I used the pure [ui5-webcomponents](https://codesandbox.io/s/ui5-webcomponents-forked-c25jy?file=/src/index.js) exmaple

The popup will open if you replace 
`popover.openBy(e.target);`
with
`popover.openBy(e.detail.targetRef);`

This is described in the API reference:
https://sap.github.io/ui5-webcomponents/playground/components/ShellBar/

ShellBarItem Events section
<img width="998" alt="Screenshot 2021-02-08 at 11 37 07 AM" src="https://user-images.githubusercontent.com/15702139/107201818-29e0a880-6a02-11eb-90f7-40e95e05e9e7.png">

**Comment by toadslop** [comment]
@ilhan007 Thanks for your response! That solved the problem. Would it be possible to add that detail to the react components documentation for ShellBarItem?

**Comment by ilhan007** [comment]
@Lukas742 do we have to do sth on our side so the ShellbarItem event detail is shown in ui5-webcomponents-react API Ref

**Comment by Lukas742** [comment]
@ilhan007 no, there is nothing from your side needed, I just used the wrong syntax (I feel a bit dumb about that). When replacing `e.target` with `e.detail.targetRef` it is also working with ui5-webcomponents-react.

We will improve our documentation to also include this.

Thanks and sorry for the confusion.

**Comment by Lukas742** [comment]
@toadslop we've updated our [documentation](https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-shellbar--with-customizable-shell-bar-item#recipe-how-to-open-a-popover-on-shellbaritem-click) to also include the `targetRef` property. Also the `targetRef` is now mentioned in the JSDoc comment of the `onItemClick` prop.
