### ISSUE TITLE
Input: Error typing(Cannot type Chinese in Input) while using IME( input method editor) for Chinese

### ISSUE THREAD

**Issue by rkl1994** [SAP/ui5-webcomponents#2797]
**Describe the bug**
While using the `Input` components for typing Chinese words(or other words using IME such as Japanese or Korean), the behavior becomes weird in Safari, but it works fine in Chrome.

**Isolated Example**
*Please provide an isolated example if possible: 
[Here is the link](https://codesandbox.io/s/jolly-hoover-8j1w2)
Please try it both in Çhrome and Safari. Chrome works well, but Safari not.

This is snapshot for Chrome
![chrome-input](https://user-images.githubusercontent.com/5527455/107186508-61aa1900-6a1f-11eb-8d6c-a623822b773f.gif)

This is snapshot for Safari
![safari-input](https://user-images.githubusercontent.com/5527455/107187551-26104e80-6a21-11eb-87dd-a81b3b47d37d.gif)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.0.0-rc.11
`@ui5/webcomponents-react` version: 0.13.4
Browser: 
Chrome: Version 88.0.4324.150
Safari: Version 14.0.2 (15610.3.7.1.10, 15610)

**Additional context**
I found some related information from React official, maybe useful: 
[Here is the link](https://github.com/facebook/react/issues/3926)

**Comment by ilhan007** [comment]
Just in case: see if it is connected or the same as https://github.com/SAP/ui5-webcomponents/issues/2632

**Comment by rkl1994** [comment]
We are also facing the same issue as mentioned in #2632 when typing in English.
However, in my case, besides what mentioned, we also face the problem that IME(for Chinese input) cannot be triggered.
Like the GIF show in the second picture.

**Comment by IlianaB** [comment]
Hello @SAP/ui5-webcomponents-topic-rl ,
I am forwarding this issue to you, as it seems there is a problem with the Input web component, when trying to write Chinese (Japanese too), using MS-IME.
I have tested with Saucelabs on Safari and I cannot even see what I am typing in the Input. Chinese words suggestions appear but they are not populated in the Input. Suggestions are also shifted a little down. For a comparison - if you test on Chrome, you will see that suggestions appear and on space key press the word is chosen and populated in the Input.
When testing, make sure you are in Chinese mode.

Regards,
Iliana

**Comment by Martotko** [comment]
There is a backlog item for this.
