### ISSUE TITLE
Use hbs comments

### ISSUE THREAD

**Issue by vladitasev** [SAP/ui5-webcomponents#2802]
We currently use HTML comments inside .`hbs` files

We should rather use Handlebars comments. See: https://handlebarsjs.com/examples/comments.html

TODO:
 - investigate the hbs2lit script's handling of comments
 - add support for hbs comments, if necessary
 - use hbs comments everywhere (fix all current templates)

**Comment by ilhan007** [comment]
Resolved with: https://github.com/SAP/ui5-webcomponents/pull/4681
