### ISSUE TITLE
Select: Text color is different than other form components

### ISSUE THREAD

**Issue by marceloschreiber** [SAP/ui5-webcomponents#2803]
**Describe the bug**
The Select components have a different text color than other form components.

**Isolated Example**
[CodeSandbox example](https://codesandbox.io/s/ancient-glade-syc5v)

**To Reproduce**
It happens by default without any modification in CSS.

**Expected behavior**
Expected the text color of the Select component to be the same for other form elements (Input, ComboBox, etc). I'm not sure if this is a mistake or if it's the intended behavior. I noticed this behavior also happens at [ui5-webcomponents' StoryBook](https://sap.github.io/ui5-webcomponents/playground/components/Select/), but since I'm using React I decided to open the issue here.

**Screenshots**
<img width="436" alt="Screen Shot 2021-02-10 at 09 24 25" src="https://user-images.githubusercontent.com/13343185/107509824-d9905480-6b81-11eb-985a-7a86c19b9f9d.png">

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.0.0-rc11
`@ui5/webcomponents-react` version: 0.13.9
Operating System: macOS Big Sur 11.2
Browser: Google Chrome 88.0.4324.96 (Official Build) (x86_64)

**Comment by IlianaB** [comment]
Hello @SAP/ui5-webcomponents-topic-p ,
I am forwarding this issue to you, because it seems a wrong color for Select component is used. Currently, it's --sapContent_LabelColor, while it should be  --sapField_TextColor.
