### ISSUE TITLE
Dialog - Draggable and Resizable Dialog documentation is missing

### ISSUE THREAD

**Issue by yogananda-muthaiah** [SAP/ui5-webcomponents#2810]
**ui5 scripts missing for clicking and javascript within pane is missing**

- [ ] Documentation is unclear
- [ ] Documentation is incorrect
- [ X] Documentation is missing
- [ ] Other

**Description of the issue**
Attached video, sample scripts to execute is missing in the documentation

https://www.loom.com/share/4f868355312642318f3f991cb31826d8

**Comment by ilhan007** [comment]
The other examples already show how to open a dialog. This sample section emphasise on the draggable and resizable attributes. We omitted the script to make the content as short as possible and not duplicate the same scrip as the script in the previous example.

```html
<ui5-button id="dialogOpener">Open</ui5-button>
<ui5-dialog id="dialog"></ui5-dialog>
```

```js
dialogOpener.addEventListener("click", function() {
		dialog.open();
});
```
