### ISSUE TITLE
v0.29.3 Multi-Input breaks on Input

### ISSUE THREAD

**Issue by agauyeung** [SAP/ui5-webcomponents#2825]
**Describe the bug**
Typing into the multi-input breaks and results in console errors.

**To reproduce**
1. Go to https://codesandbox.io/s/ui5-webcomponents-forked-kfbuq
2. Type into the multi-input
3. Observe that an error is thrown:
![image](https://user-images.githubusercontent.com/8508119/108118390-26c56800-7053-11eb-8e2e-f6af722ef21b.png)

**Isolated example**
https://codesandbox.io/s/ui5-webcomponents-forked-kfbuq

**Expected behavior**
The input should not break.

**Screenshots**
See above.

**Context**
- UI5 Web Components: 0.29.3
- OS/Platform: Windows

**Affected components**
- MultiInput

**Log output / Any errors** in the console
```
39.65ba0f9e.chunk.js:formatted:17277 Uncaught (in promise) TypeError: Cannot read property 'value' of null
    at HTMLElement._handleInput (39.65ba0f9e.chunk.js:formatted:17277)
_handleInput @ 39.65ba0f9e.chunk.js:formatted:17277
async function (async)
_handleInput @ 39.65ba0f9e.chunk.js:formatted:17272
handleEvent @ 39.65ba0f9e.chunk.js:formatted:11107
__boundHandleEvent @ 39.65ba0f9e.chunk.js:formatted:11083
```

**Organization:** *SuccessFactors*

**Priority:** *High*
- Is functional one and makes a single component unusable

Note: the priority would be re-evaluated by the issue processors, according to the project internal criterias

**Comment by ilhan007** [comment]
Hello @agauyeung 

This PR should fix the issue:
https://github.com/SAP/ui5-webcomponents/pull/2790

We will downport it into the the 0.29 branch.
