### ISSUE TITLE
ui5-datepicker: typing while picker is open changes the date before hitting enter

### ISSUE THREAD

**Issue by pskelin** [SAP/ui5-webcomponents#2827]
the DatePicker test used to fail very often for the following interaction:
```
datepicker.openPicker();
datepicker.input.click();
browser.keys("May 3, 2100");
browser.keys("Enter");
```

The problem is that the date gets change as soon as the `May 3, 2` is entered and the year is filled out as 2002.
For the test, the keys are probably entered faster and this sometimes passes the test and other times fails.

The correct behaviour (as in openui5) s to change the date only after hitting enter.

**Comment by TeodorTaushanov** [comment]
Hello @SAP/ui5-webcomponents-topic-b, can you check this issue?
