### ISSUE TITLE
Outdated i18n documentation

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents#2835]
**Describe the documentation issue**

- [ ] Documentation is unclear
- [x] Documentation is incorrect
- [ ] Documentation is missing
- [ ] Other

**Description of the issue**
The `i18n` documentation is outdated and does not work with rc.12.
Maybe you can copy some stuff from our docs if needed :) 
https://github.com/SAP/ui5-webcomponents-react/blob/main/docs/5-Internationalization.stories.mdx

**Comment by ilhan007** [comment]
Hi @MarcusNotheis I think this PR will address this:
https://github.com/SAP/ui5-webcomponents/pull/2829

**Comment by pskelin** [comment]
fixed with #2829
