### ISSUE TITLE
DatePicker: Missing locale crashes application

### ISSUE THREAD

**Issue by goodefroi** [SAP/ui5-webcomponents#2836]
**Describe the bug**
Expanding a `DatePicker` component causes the app to crash (in development) when the browser is set to a locale that is not provided.

**Isolated Example**
[Isolated example on `codesandbox.io`](https://codesandbox.io/s/jolly-spence-4rd7y?file=/src/App.js).

**To Reproduce**
1. Add a `DatePicker` component.
2. Click on it to open the date selection calendar.
3. Enjoy fireworks

**Expected behavior**
Yeah, not this. Fall back to `en_US` or some other generic locale.

**Screenshots**
![image](https://user-images.githubusercontent.com/27777253/108374980-d0e2f280-7201-11eb-9c9c-414dd05732fc.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: `1.0.0-rc.12`
`@ui5/webcomponents-react` version: `0.14.0`
Operating System: `macOS 11.2.1`
Browser: `Chrome 88`

**Comment by goodefroi** [comment]
> Hey @goodefroi,
> thanks for reporting. As a workaround you can import the Assets in your index file:
> 
> ```js
> import '@ui5/webcomponents/dist/Assets';
> import '@ui5/webcomponents-fiori/dist/Assets';
> import '@ui5/webcomponents-react/dist/Assets';
> ```
> 
> These assets are now dynamic and loaded when required, so it won't bloat your bundlesize like before when importing them.
> I'll also reach out to the Web Components Team in order to give you a better answer here.

Dear @MarcusNotheis, thank you very much for your help. I really appreciate the quick reaction times of you and your team whenever I submitted an issue in the past.

**Comment by pskelin** [comment]
> As a workaround you can import the Assets in your index file:
> 
> ```js
> import '@ui5/webcomponents/dist/Assets';
> import '@ui5/webcomponents-fiori/dist/Assets';
> import '@ui5/webcomponents-react/dist/Assets';
> ```
> 

@MarcusNotheis  That's the right approach, yes. It is also not a workaround as it is necessary for productive usage anyway.

The development work case should not crash however, and a change with a warning and a fallback option is in preparation.
