### ISSUE TITLE
ui5-dialog: Accessibility: using header slot causes broken aria-labelledby reference

### ISSUE THREAD

**Issue by agauyeung** [SAP/ui5-webcomponents#2838]
**Describe the bug**
The outermost `<section>` element in the `ui5-dialog`'s shadow DOM has `aria-labelledby="ui5-popup-header"`. When using the `ui5-dialog`'s `header` slot instead of `header-text`, any elements could be placed inside `ui5-popup-header`. Simply referring to the header container in this scenario would render `aria-labelledby` as useless.

**To reproduce**
1. Add `ui5-dialog` to the DOM
2. Use `header` slot with `ui5-button` and `ui5-title`
3. Note that `ui5-popup-header` in the `ui5-dialog`'s shadow DOM refers to the header container, not the actual element containing the header text.

**Isolated example**
https://codesandbox.io/s/ui5-webcomponents-forked-rosol?file=/index.html

**Expected behavior**
Not sure if this is the most elegant solution, but it might be good to expose an `aria-label` value as a parameter so that the developer can pass in a string as the screenreader label.

**Screenshots**
![image](https://user-images.githubusercontent.com/8508119/108427847-9cb40580-71f2-11eb-8578-34d4cfecf354.png)
![image](https://user-images.githubusercontent.com/8508119/108428317-38de0c80-71f3-11eb-82f4-c556e5c922b3.png)

**Context**
- UI5 Web Components version: 0.29.4
- OS/Platform: Windows

**Affected components** `<ui5-dialog>`

**Log output / Any errors** in the console: None

**Organization:** *SuccessFactors*

**Priority:** Medium
- Is accessibility one (Screen Reader, Keyboard Handling)

**Comment by ivoplashkov** [comment]
Hi @agauyeung,

Thanks for reporting this issue!
I have discussed the issue with our accessibility expert, therefore I am forwarding it to the coresponding team.

Regards,
Ivaylo

**Comment by agauyeung** [comment]
hi @GerganaKremenska  any update on this?

**Comment by GerganaKremenska** [comment]
No, working on it

**Comment by agauyeung** [comment]
Hi @GerganaKremenska any update?

**Comment by ilhan007** [comment]
Hello @agauyeung are you still using the 0.29 branch?

We provided a solution, should we downport it to 0.31.X only or you need it in 0.29.X as well?

**Comment by ilhan007** [comment]
Hello @agauyeung The fix is released with 0.29.15
