### ISSUE TITLE
ui5-icon display:none does not work in IE11

### ISSUE THREAD

**Issue by gurkirpalgill** [SAP/ui5-webcomponents#2839]
**Describe the bug**
ui5-icon does not pick the display value in IE11.

**To reproduce**
set class to hideIcon on ui5-icon element.
```
.hideIcon {
  display: none;
  color:red;
}
<ui5-icon class="hideIcon" slot="icon" name="decline" />
```
while IE11 picks color property, it ignores the display value in IE11. display value is overwritten to value `flex` as you can see in the screenshot. It works fine in Chrome.

**Expected behavior**
It should hide the icon when display is set to none

**Screenshots**
<img width="1483" alt="Screen Shot 2021-02-18 at 3 19 50 PM" src="https://user-images.githubusercontent.com/65705637/108435099-a131eb80-71fd-11eb-987d-3af838fb9adb.png">

**Context**
- UI5 Web Components version: 0.29.4
- OS/Platform: Mac OS
- Browser *(if relevant)*: IE11

**Affected components** *(if known)*
ui5-icon

**Priority:** *(optional)* *(Medium)*

**Comment by ilhan007** [comment]
Hi @gurkirpalgill 
can you try setting "hidden" to the Icon - `<ui5-icon hidden name="add"></ui5-icon>`.
