### ISSUE TITLE
ui5-input: number input doesn't lose value

### ISSUE THREAD

**Issue by zhangliangyi** [SAP/ui5-webcomponents#2841]
Number input cannot clear value with backSpace key

Once the value is deleted in the number input, the value will be reverted to the old one after the blur action.

**Isolated example**
https://codesandbox.io/s/ui5-webcomponents-forked-spzg3?file=/index.html

**Expected behavior**
The value should be cleared with backSpace key.

Per my investigation, in line
https://github.com/SAP/ui5-webcomponents/blob/263fb8b8591ac2f704a40c5bf2945e8e4c5afb10/packages/main/src/Input.js#L712
the `event` object does not contain `key` or `keyCode` property, so the `isBackSpace` function will always return false.

As a result, the `input` component will not fire the `input` event with the empty value.

**Comment by ivoplashkov** [comment]
Hi @zhangliangyi,

Thanks for reporting this issue.
I was able to reproduce the issue and indeed this check might be causing it, however I am forwarding the issue to the coresponding team for further investigation.

Regards,
Ivaylo

**Comment by zhangliangyi** [comment]
Hi @ivoplashkov 

Thanks for the quick reply. This issue would have a critical impact to our new release delivery in SAP Successfactors. Please fix it in next release if possible.

**Comment by ilhan007** [comment]
Hello @zhangliangyi we will look into the issue with high priority.

**Comment by ilhan007** [comment]
Hello @zhangliangyi a fix is prepared: https://github.com/SAP/ui5-webcomponents/pull/2864

Once it is reviewed, we are going to merge it. Which SF branch are you using, 0.29 or ? so that we know where to downport it.

BR,
ilhan

**Comment by zhangliangyi** [comment]
@ilhan007 
We are now using 0.29.4. It would be great if the fix can be released in next 0.29.x release as discussed.

**Comment by zhangliangyi** [comment]
@ilhan007 
Just wonder when the fix will be merged and released, it is close to our official release window.

**Comment by ilhan007** [comment]
Hello @zhangliangyi during the code review we found the fix opens another issue, so it's just not ready.

**Comment by ilhan007** [comment]
Hello @zhangliangyi the fix has been released with 0.29.12, could you try it?
