### ISSUE TITLE
a11y issue: Focus gets trapped in ui5-li-custom list

### ISSUE THREAD

**Issue by lateefsofi** [SAP/ui5-webcomponents#2849]
**Describe the bug**
Focus gets trapped within ui5-li-custom List when navigating through keyboard.

**To reproduce**
1. Go to https://codesandbox.io/s/ui5-webcomponents-forked-d7dp3
2. Press tab key to navigate through list items.
3. While navigation through last element of the list, focus gets back to first element.

**Isolated example**
https://codesandbox.io/s/ui5-webcomponents-forked-d7dp3

**Expected behavior**
User should be able to navigate to next element on pressing tab in the list. Behaviour should be same like StandardListItem.

**Screenshots**
NA

**Context**
- UI5 Web Components version: 0.29.3
- OS/Platform: {...}
- Browser *(if relevant)*: {...}
- Other information: {...}

**Affected components**
List and CustomListItem

**Log output / Any errors** in the console
```
NA
```

**Organization:**
Success Factors

**Priority:** *(optional)* *(Low, Medium, High or Very High)*
High

**Comment by TeodorTaushanov** [comment]
Hi @SAP/ui5-webcomponents-topic-p, can you check this issue?
