### ISSUE TITLE
DateRangePicker failed to parse format "yyyy-MM-dd"

### ISSUE THREAD

**Issue by grigorzyapkov** [SAP/ui5-webcomponents#2851]
**Describe the bug**
DateRangePicker does not parse the input dates correctly in version v1.0.0-rc.12 when the specified `format-pattern` is equal to `yyyy-MM-dd`. Both firstDateValue and lastDateValue are invalid in the fired event. I guess the problem is related to the delimiter and the logic for splitting the input value.

**To reproduce**
1. Create `DateRangePicker` with `format-pattern` equal to `yyyy-MM-dd`
2. Select a date range in the calendar
3. An error state message will be displayed

**Context**
- UI5 Web Components version: v1.0.0-rc.12 version

**Affected components**
DateRangePicker

**Priority:** High

**Comment by TeodorTaushanov** [comment]
Hello @SAP/ui5-webcomponents-topic-b, can you check this issue?
