### ISSUE TITLE
interactive ui5-icon: two click events fired for one click action

### ISSUE THREAD

**Issue by BennyHuang** [SAP/ui5-webcomponents#2857]
**Describe the bug**
interactive ui5-icon fires two 'click' event on one click action. One is fired with CustomEvent and another one is fired with native MouseEvent (bubbled from internal svg).

**To reproduce**
The event hander is attached in either 
`<ui5-icon onClick={handler}></ui5-icon>`
or
`icondom.addEventListener('click', handler)`

Upon clicking on the icon, the handler is executed twice. If focusing and entering Space, the handler is executed only once with the CustomEvent.

If the event handler is attached to noConflict event, the handler is executed only once as expected.
`icondom.addEventListener('ui5-click', handler)`

**Expected behavior**
ui5-icon should fire click event once with CustomEvent upon clicking on the icon.

**Context**
UI5 Web Components version: 0.29.1

**Affected components (if known)**
ui5-icon

**Comment by ilhan007** [comment]
Hello @BennyHuang  thanks for reporting this issue. A fix is prepared: https://github.com/SAP/ui5-webcomponents/pull/2858
