### ISSUE TITLE
what the relations with ` SAPUI5`

### ISSUE THREAD

**Issue by xkx9431** [SAP/ui5-webcomponents#2863]
**Describe the documentation issue**

as  a  SAP developer ,  I  want know what's relations and  differences with [ SAP UI5 ](https://sapui5.hana.ondemand.com/)?

And if this `ui5-webcomponents` is single a  UI layer, can it integrated with the [ SAP UI5 ](https://sapui5.hana.ondemand.com/).

I just see in SAP ui5 we using the *.XML to mock up views and if  the view layer can be substituted with the `ui5-webcomponents` ?

or if not , and what the data/status management  solution should be  adapted together with this  `ui5-webcomponents`?

this is  not a bug, I just some one can give me some topics here. Please close this issue if need.

thanks. Kevin

- [ ] Documentation is unclear
- [ ] Documentation is incorrect
- [ ] Documentation is missing
- [x] Other

**Description of the issue**
A clear and concise description.

**Comment by ilhan007** [comment]
Hello @xkx9431 and thank you for the interest in [SAPUI5](https://openui5.org/) and [UI5 Web Components](https://github.com/SAP/ui5-webcomponents/).

Well, the [Readme](https://github.com/SAP/ui5-webcomponents#ui5-web-components) of the project answers part of the questions, but maybe to highlight the most important points:

SAPUI5 (or Openui5 - its open source version) **is a full fledged framework**, offering programming model, data binding, routing, layer that handles OData requests, hundreds of UI controls, e.g. everything to build an application.

UI5 Web Components **are not built on top of UI5**, they are independent UI elements, implementing the Fiori UX, based on the [Web Components standard](https://www.webcomponents.org/introduction) and **can be used with any current or future web development framework** (React, Angular, Vue, etc...). UI5 Web Components **does not offer a programming model**, data binding, routing, etc. 

**UI5 Web Components is not a replacement of SAPUI5, but a complementary offering.**

The integration with SAPUI5 is an important topic. Currently we are working on **reuse of the UI5 Web Components  in SAPUI5 controls rendering layer.** In other words, to enable SAPUI5 controls to use the web components internally and render them. We would keep the XML views for defining UI, but rather plug in the web components into the SAPUI5 Controls. It's important to note that we are not going to refactor and change the existing SAPUI5 control libraries, but this effort will result in new libraries with new controls inside.
