### ISSUE TITLE
a11y issue: ui5-combobox selected item announces "Item unselected" after selecting from dropdown

### ISSUE THREAD

**Issue by rchrdchn** [SAP/ui5-webcomponents#2867]
**Describe the bug**
Screen reader announces "Item unselected" after selecting item from dropdown ui5-combobox

**To reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/ComboBox/
2. Turn on NVDA or VoiceOver
3. Open up dropdown via keyboard
4. Select item from dropdown
5. Listen / read screen reader assistant text

**Isolated example**
https://sap.github.io/ui5-webcomponents/playground/components/ComboBox/

**Expected behavior**
Screen reader announces "Item selected" after selecting item from dropdown ui5-combobox

**Screenshots**
![Screen Shot 2021-02-24 at 14 52 16](https://user-images.githubusercontent.com/11576789/109076921-3c203f00-76b0-11eb-9db8-fa754cd0e0f7.png)

**Context**
- UI5 Web Components version v1.0.0-rc.6
- OS/Platform: MacOS Catalina
- Browser *(if relevant)*: Chrome Version 88.0.4324.192 (Official Build) (x86_64)
- Other information: {...}

**Affected components** *(if known)*

**Log output / Any errors** in the console
```
{...}
```

**Organization:** *SuccessFactors*

**Priority:** *(optional)* *Medium*

Setting priority would indicate the importance of the issue
and would help the process of dispatching and processing.

To set the appropriate priority, you need to consider the impact
and if the issue:
- Breaks entire application or system - Low
- Is accessibility one (Screen Reader, Keyboard Handling) - High
- Is functional one and makes a single component unusable - Low
- Is visual, styling one - Low

Note: the priority would be re-evaluated by the issue processors, according to the project internal criterias

**Business impact:** *(mandatory for "Very High")*

**Comment by TeodorTaushanov** [comment]
Hello @SAP/ui5-webcomponents-topic-rl, can you check this issue?

**Comment by MapTo0** [comment]
Looks like Voice Over handles all text selections as "selected", once an enter is clicked, the _typed-ahead_ text is set as value of the combobox and gets unselected. I am not sure what we can do in this case ... Seems like "selected / unselected" term in voice over world stands for text selection instead of performing an option selection. I will have a look with ACC experts again.

**Comment by elenastoyanovaa** [comment]
Hello @rchrdchn ,

As @MapTo0 mentioned the selected/unselected speech output is related to the text selection in the input field of the combobox. You can reproduce it with a simple ui5-input here https://sap.github.io/ui5-webcomponents/playground/components/Input/ and also with native html input element. This is expected. 

The output information regarding the selected item is currently not present, but a feature request for this is already present https://github.com/SAP/ui5-webcomponents/issues/2654

Kind Regards,
Elena
