### ISSUE TITLE
ui5-wizard: Navigation area selected step may be incorrect on step change

### ISSUE THREAD

**Issue by todormikov** [SAP/ui5-webcomponents#2876]
**Describe the bug**
When moving to a step by setting its 'selected' property to true, the step highlighted in the navigation area of the wizard may be incorrect.

**To reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/Wizard/
2. Click the `Step 2` button in the sample Wizard
3. Toggle the `5 years guarantee included` button to make the `Step 3` button appear
4. Click the `Step 3` button
5. The wizard will scroll to the third step, but the second step will be selected in the navigation area
6. Click the `Medium` button to make the `Step 4` button appear
7. Click the `Step 4` button
8. The wizard will scroll to the fourth step, but the third step will be selected in the navigation area

**Isolated example**
https://sap.github.io/ui5-webcomponents/playground/components/Wizard/

**Expected behavior**
When going to a step by setting its 'selected' property to true, the navigation area of the wizard should display the correct step as selected

**Context**
- UI5 Web Components version: v1.0.0-rc.12 version
- Browser: Not reproducible on Firefox

**Affected components**
Wizard

**Comment by TeodorTaushanov** [comment]
Hello @SAP/ui5-webcomponents-topic-rl, 

I'm able to reproduce the issue on a small screen size and there is a scrollbar inside the Wizard content.

**Comment by ilhan007** [comment]
Hello @todormikov

I used Chrome, but did not catch the described issue. Did I performed the steps correctly?

https://user-images.githubusercontent.com/15702139/109517251-b89c8e80-7ab1-11eb-912d-f48ad8a14e56.mov

**Comment by todormikov** [comment]
Hello @ilhan007 
You performed the steps correctly.
My guess is that the issue might only be present on Windows, since I couldn't reproduce it on Linux.
I have not tested Mac.

**Comment by ilhan007** [comment]
I will ask someone from the team that has Windows to test it as well, thanks for the video.

**Comment by ilhan007** [comment]
Hello @unazko can you check the issue.
 I could not reproduce it with Mac + Chrome, according to the author it might happen only on Windows + Chrome. 
 here are videos attached for both setups (Mac + Chrome and Windows + Chrome) that illustrates the behaviour. 
 
 If you are able to reproduce it, please forward it to @SAP/ui5-webcomponents-topic-rl for further investigation.

**Comment by todormikov** [comment]
I checked today and could not reproduce the error on Chrome or Edge. I suppose this issue was resolved by another fix in the webcomponents or those browsers.
