### ISSUE TITLE
ui5-wizard: Navigation area color not affected by theme

### ISSUE THREAD

**Issue by todormikov** [SAP/ui5-webcomponents#2877]
**Describe the bug**
The color of the navigation area does not change with themes. It is always white.

**To reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/Wizard/
2. Change the theme to Quartz Dark from the cogwheel button on the right of the page
3. The color of the navigation area on the sample wizard remains white

**Isolated example**
https://sap.github.io/ui5-webcomponents/playground/components/Wizard/

**Expected behavior**
When the overall theme is changed, the color of the navigation area should change accordingly.

**Screenshots**
![image](https://user-images.githubusercontent.com/79699783/109309800-6ad31c80-784c-11eb-8c6b-5e6f7024c5b1.png)

**Context**
- UI5 Web Components version: v1.0.0-rc.12 version

**Affected components**
Wizard

**Comment by TeodorTaushanov** [comment]
Hello @SAP/ui5-webcomponents-topic-rl, can you check this issue?
