### ISSUE TITLE
[BUG][SF][ui5-list] load-more event does not work, if I only set max-height to ui5 list

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents#2882]
**Dear colleagues,**
I am from SuccessFactors Web Experience Shanghai team. My name is hubery and this account is our team account

**Bug Description**
**Version: 0.29.4**
If I only set max-height to ui5 list, load-more event does not work. ( I have already set infinite-scroll attribute to io5-list )
![Screen Shot 2021-03-01 at 10 43 11 AM](https://user-images.githubusercontent.com/78520316/109453993-41093800-7a8e-11eb-9856-d80f03c86bda.png)

**Expected** 
If only max-height attribute is set to ui5-list, the load-more event can still work according to the actual height of ui5-list itself

**Comment by ilhan007** [comment]
Hello @sfsf-xweb-sh is it possible to use an absolute height for the time being. 
Actually this behaviour is known to us, we implemented it this way. The overflow behavior, and the load-more functionality depends on setting height to the List. Changing this would require bigger refactoring. 

When do you need the fix at the latest?

**Comment by sfsf-xweb-sh** [comment]
Hi @ilhan007 

Thanks for your reply and solution.
But our UX spec need us set max-height to ui5-list to finish our feature. 

Best Regards
