### ISSUE TITLE
ui5-list: in Mode=Delete, add possibility to render a disabled button instead of no button

### ISSUE THREAD

**Issue by gmkv** [SAP/ui5-webcomponents#2884]
The ui5-upload-collection component utilizes ui5-list and ui5-list-item.
The [Fiori UX spec](https://experience.sap.com/fiori-design-web/upload-collection/#when-to-showdeactivatehide-actions) suggests to show a button as disabled if a particular file cannot be deleted.
Currently, the ui5-list-item doesn't expose a way to set its 'ModeDelete' button to disabled, so as a temporary solution, we have overriden the modeDelete getter to just hide the button.

Would you add a way to set the ModeDelete button to disabled?

**Comment by fifoosid** [comment]
Currently the design spec can be interpreted in a couple of ways, so before we implement a solution, we have to make sure we are going to the right direction.
