### ISSUE TITLE
ui5-input in ui5-dialog focus loop issue

### ISSUE THREAD

**Issue by ee92** [SAP/ui5-webcomponents#2894]
**Describe the bug**
When a ui5-dialog has an ui5-input as the first or last focusable element, that input does not get focused properly. It will receive the input cursor but will not have the focus outline and the `.focused` property will be false.

**To reproduce**
1. Go to https://codesandbox.io/s/ui5-webcomponents-forked-24esz?file=/src/index.js 
2. Follow the steps in the sandbox

**Expected behavior**
When the ui5-input is the first focusable element in the ui5-dialog, it should receive the input cursor, have a focus outline, and have the `.focused` property be set to true. 
It should do the same upon tabbing through the focusable elements in the ui5-dialog and being looped back to the first.
The same if using Shift+Tab and the ui5-input is the last focusable element in the ui5-dialog.

**Screenshots**
![Screen Shot 2021-03-01 at 9 15 17 AM](https://user-images.githubusercontent.com/24360164/109533091-b533e380-7a6e-11eb-9f83-556a41e625ec.png)

**Context**
- UI5 Web Components version: 0.29.0

**Affected components** 
ui5-input

**Organization:** 
SuccessFactors

**Priority:** *(optional)* 
Medium

Thank you for looking into it :)

**Comment by fifoosid** [comment]
Hi @ee92 

This issue is resolved in version 0.29.4. Once you update the version you will no longer experience this issue

**Comment by ee92** [comment]
@fifoosid what was the change that fixed the issue? 

We have a component that extends ui5-input, and it still has the issue after upgrading to 0.29.4 
Maybe we need to make the same change also

Thanks
