### ISSUE TITLE
TabContainer doesn't pass data-help-id to the buttons used to select the tabs

### ISSUE THREAD

**Issue by Rabuske** [SAP/ui5-webcomponents#2899]
**Describe the bug**
We are using the TabContainer component to separate parts of the application in different tabs. However, we could not find a way to attach attributes to the buttons of the tab. More specifically, we need to be able to attach the attribute _data-help-id_ so the help tool can identify the selector as a hotspot for documentation:

```
      <TabContainer>
        <Tab icon="personnel-view" selected text="Personal Information" data-help-id="tabPersonal">
          <Label>Personal Tab</Label>
        </Tab>
        <Tab icon="key" text="Logon Data" data-help-id="tabLogon">
          <Label>Logon Tab</Label>
        </Tab>
      </TabContainer>
```
Given this code, I would expect the `data-help-id` attribute to be passed to the "buttons":

![image](https://user-images.githubusercontent.com/10622097/109654263-c3523480-7b40-11eb-8af5-b37d5723c738.png)

However, it is being passed to the container of the tab itself instead:

![image](https://user-images.githubusercontent.com/10622097/109654493-014f5880-7b41-11eb-947b-bd0c0711e3c1.png)

**Isolated Example**
https://codesandbox.io/s/sparkling-browser-jh3u2?file=/src/App.js

**To Reproduce**

1. Access the isolated code example
2. Inspect the tab buttons, you'll see that the _data-help-id_ attribute is not available there
3. Inspect the content of the tab and the _data-help-id_ attribute is there

**Expected behavior**
I expect the _data-help-id_ to be available in the selectors of the tabs instead of in their content. Alternatively, I expect to have another way to add attributes specificaly to the selectors/buttons.

**Screenshots**

**UI5 Web Components for React Information**
    "@ui5/webcomponents-base": "0.26.0",
    "@ui5/webcomponents-fiori": "1.0.0-rc.10",
    "@ui5/webcomponents-icons": "1.0.0-rc.10",
    "@ui5/webcomponents-react": "0.12.0",
    "@ui5/webcomponents-react-base": "0.12.0",
    "@ui5/webcomponents-theme-base": "1.0.0-rc.10",

Operating System: Windowas
Browser: Chrome/Edge Chromium 

**Additional Context**
This is necessary for the InApp help application provided by SAP.

**Comment by Rabuske** [comment]
Just an update: I noticed that there is the data-ui5-stable that could be used to get WebAssistant to find the buttons. We are going to proceed with this approach. However, it might still be a good idea to repass custom attributes to the content of the shadow dom.

**Comment by terezamch** [comment]
Hello @Rabuske ,

First of all thanks for the feedback!

As the ui5-tab-container is a complex component, the ui5-tab is actually representing the content part. Its title, icon, etc. are rendered by the tab container. This is done to improve the developer experience when writing plain HTML markup and using the ui5-tab-container and its children components. 

The usual use case is to click on a tab, then the app developer receives an event with a reference to the tab from which the data attributes can be read.

As you have managed to solve your scenario, I am closing the ticket.

Best regards,
Tereza
