### ISSUE TITLE
<ui5-shellbar> - option to hide primary title dropdown

### ISSUE THREAD

**Issue by ignipae** [SAP/ui5-webcomponents#290]
First of all, I would like to express my gratitude for the SAPUI5 web-components. I have the feeling, that this is a great addition to use and I am happy, to use those inside my applications.

**Is your feature request related to a problem? Please describe.**
I would like to use the ui5-shellbar component as some kind of page header, whereas I would only use the primary-title property (maybe some others) to show the title to the end-user.
Unfortunately, the primary-title has always this dropdown arrow assigned, even if it has no functionality:
![image](https://user-images.githubusercontent.com/4704905/55242555-ca2de980-523d-11e9-9720-bc36e8288d7e.png)

**Describe the solution you'd like**
I would like to have the possibility to "enable" this dropdown functionality. I would think of a new boolean property, which will show/hide it and make the title clickable respectively.

**Describe alternatives you've considered**
There is no other "page header" component. Therefore the only suitable solution would be to use plain css, which I would like to avoid. Especially, when there is a header component.

**Comment by ignipae** [comment]
Another way of implementing this could be that you would introduce a new data-slot called "title-menu" or something, which could then be the list:

```
<ui5-list separators="None" data-ui5-slot="title-menu">
		<ui5-li type="Active">Application 1</ui5-li>
		<ui5-li type="Active">Application 2</ui5-li>
		<ui5-li type="Active">Application 3</ui5-li>
		<ui5-li type="Active">Application 4</ui5-li>
		<ui5-li type="Active">Application 5</ui5-li>
</ui5-list>
```

If this data-slot is not filled, the arrow is not shown. However I am not sure, if this fits with your strategy. 

Basically, I really like the idea of doing the click and then inside the event, whatever I want -> like opening the popover. Maybe it could also be connected to the "titlePress" event. If it is not provided, no arrow will be shown.

So I see those two possibilities:
- new data-ui5-slot -> if this slot is provided, the arrow will be shown and the (automatically opened) popover will contain the content of the slot
- the arrow visibility is connected to the titlePress event -> if its not provided, the arrow is not there

That way we will not have a new boolean property and instead reuse our existing ones.

**Comment by ilhan007** [comment]
Hello @ignipae,
thanks for your feedback.

The request is reasonable and we will address it soon
and we will also consider your latest input.

Best regards,
ilhan

**Comment by MapTo0** [comment]
Hey @ignipae,

Do you expect to have a clickable title without the arrow down? Similar to a button with a text?

**Comment by ignipae** [comment]
Hi @MapTo0 
Thank you for coming back to me.
Actually, it would make sense (in my opinion), if the title was not clickable at all, if the developer decides not to show the arrow.

So I would expect that, as soon as the arrow is gone, the title would be pure text.
But maybe you have other use cases in mind, where this might make sense. However I have the feeling that one of the most used scenario would be, that the title is pure text.

Best regards,
Julian

**Comment by MapTo0** [comment]
Hi @ignipae 

We are currently reviewing and discussing these features in https://github.com/SAP/ui5-webcomponents/pull/317

Feel free to give some feedback if the new API would fit for your use case.

Regards!

**Comment by ignipae** [comment]
Thanks @MapTo0 !
I like the approach you have chosen. This will help to use the shellbar more often and more flexible.
