### ISSUE TITLE
[SF][Urgent][ui5-list][ui5-li][ui5-li-custom] add disabled attribute to ui5-li element and ui5-li-custom element inside ui5-list ( MultiSelect mode)

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents#2901]
**Dear colleagues,**
I am from SuccessFactors Web Experience Shanghai team. My name is Hubery Shen and this account is our team account.

**Feature request**
Add disabled attribute to ui5-li and ui5-li-custom element inside ui5-list component ( MultiSelect mode )

**Expected API**
```
<ui5-list id="myList1" mode='MultiSelect' header-text="Multiple selection is possible">
	<ui5-li disabled="true">Pineapple</ui5-li>
	<ui5-li selected>Orange</ui5-li>
</ui5-list>
```

and 

```
<ui5-list id="myList1" mode='MultiSelect' header-text="Multiple selection is possible">
	<ui5-li-custom disabled="true">Pineapple</ui5-li-custom >
	<ui5-li-custom selected>Orange</ui5-li-custom >
</ui5-list>
```

<img width="951" alt="Screen Shot 2021-03-03 at 8 18 40 PM" src="https://user-images.githubusercontent.com/78520316/109805742-c8a5a100-7c5e-11eb-8996-d4397beefc78.png">

**Comment by ilhan007** [comment]
Hi @sfsf-xweb-sh 

isn't this the same as that issue  https://github.com/SAP/ui5-webcomponents/issues/1405 filed by SF in the past.

BR,
ilhan

**Comment by sfsf-xweb-sh** [comment]
Hi @ilhan007 

It works according to issue 1405, thanks !
I will close this issue
