### ISSUE TITLE
TextArea displays warning in console if used with name property

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#2902]
**Describe the bug**
The `TextArea` displays a warning inside the console of the dev tools, when the `name` property is added. The necessary import of `InputElementsFormSupport` is also added. 

**To reproduce**
1. Implement a `TextArea`
2. Add the import: `import "@ui5/webcomponents/dist/features/InputElementsFormSupport";`
3. Add the `name` property to the `TextArea`
4. See a console warning

```sh
Unknown slotName: formSupport, ignoring <input type=​"hidden" data-ui5-form-support slot=​"formSupport" name=​"text-area" value>​ Valid values are: valueStateMessage
```

**Isolated example**
[CodeSandbox](https://codesandbox.io/s/ui5-webcomponents-forked-vf8fz?file=/index.html)

**Context**
- UI5 Web Components version: 1.0.0-rc.12

**Comment by Dingyj3178** [comment]
This warning is also found in following compoennt.
- input
- TexArea
- Date picker
- Select

For now I comment out following code of each component in node_module.
```
const FormSupport = getFeature("FormSupport");
		if (FormSupport) {
			FormSupport.syncNativeHiddenInput(this);
		} else if (this.name) {
			// console.warn(`In order for the "name" property to have effect, you should also: import "@ui5/webcomponents/dist/features/InputElementsFormSupport.js";`); // eslint-disable-line
		}
	}
```
