### ISSUE TITLE
DateTimePicker : On selection shows a different date and time in chrome based browsers like Chromium based browser like Chrome, Edge, Brave and Vivaldi etc

### ISSUE THREAD

**Issue by userujala** [SAP/ui5-webcomponents#2904]
**Describe the bug**
I am using the DateTimePicker in states from the UI5 web component.
When i am trying to select the date and time in my Chrome browser , on selection it shows a different date and time.
The same issue i have identified in Edge Browser. It generally happen in all chromium browsers
This works fine in Firefox Browser

**To reproduce**
1. Go to application : https://smartops-dev.cfapps.sap.hana.ondemand.com/commerce/outagesearch
2. Click on the date time picker filed and select a date time
3. This will show with a different date time

**Isolated example**
Please provide an isolated example if possible, by forking [CodeSandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html)

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/13817415/109914592-583a6680-7cd6-11eb-9897-59b93b3b2eb0.png)
![image](https://user-images.githubusercontent.com/13817415/109914632-6be5cd00-7cd6-11eb-8f9b-ab1d08587745.png)

**Context**
- UI5 Web Components version
-     "@ui5/webcomponents-base": "0.26.0",
    "@ui5/webcomponents-fiori": "1.0.0-rc.10",
    "@ui5/webcomponents-icons": "^1.0.0-rc.10",
    "@ui5/webcomponents-react": "0.12.1",
    "@ui5/webcomponents-react-charts": "0.10.8"
- OS/Platform: SAP Cloud Platfrom (CF)
- Browser *Checked on Chrome ( 87.0.4280.67 (Official Build) (x86_64)) , Firefox (v 86)
- Other information: {...}

**Organization:** *(if applicable)*

**Priority: High

**Comment by fifoosid** [comment]
Hi @userujala 

I am using Chrome 88.0.4324.192 (Official Build) (x86_64) and I am not able to reproduce your issue on my side.

Can you provide some more information like what time zone do you experience the issue in?

**Comment by userujala** [comment]
HI @fifoosid :

when i am trying this in the sandbox with minimal properties it works fine : 
https://codesandbox.io/s/practical-cohen-ebkuq?file=/src/App.js 

but is it quite difficult to provide the complete issue details directly in the sandbox.
By any means is it possible to have a quick call to see the issue directly.

Let me know.

Best Regards
Ujala

**Comment by userujala** [comment]
Hi @fifoosid 

I have shared one video for the issue.
https://web.microsoftstream.com/video/1b7d44e3-f6dd-41f6-9112-46fb72d9e2c0 

Best Regards
Ujala

**Comment by userujala** [comment]
@fifoosid :
As suggested we will updated the web component packages to the new ones and verify if it is working or not 
in case of the issue still persist i will update you

Best Regards
Ujala

**Comment by fifoosid** [comment]
Sound good @userujala 

If you still experience the issue, feel free to reopen this issue
