### ISSUE TITLE
Retrofit: Create ui5-text component

### ISSUE THREAD

**Issue by vladitasev** [SAP/ui5-webcomponents#2905]
This component will be relevant for the retrofit, because in OpenUI5 one cannot set text inside other components such as table headers, table cells etc... Therefore if someone tries to create an app with webcomponents libraries only, they would not be able to. They would need a text component and would need to fetch another library.

Initial scope:
 - no properties
 - default slot (type: Node) which is intended to accept text by design
 - will be styled out of the box in terms of font family, font style, font size, etc...

**Comment by MarcusNotheis** [comment]
When you develop this Text component, would it be possible to be feature compatible with our UI5 Web Components React Text?
https://github.com/SAP/ui5-webcomponents-react/blob/main/packages/main/src/components/Text/index.tsx#L8-L21

I know that your `boolean` props handling is different, but it would be good for our users in the new text component would have the same features as the old text when we replace it.

**Comment by vladitasev** [comment]
We've discussed this many times in different rounds, and for the time being the overall opinion is that we'll use normal CSS classes for this. Text will be tackled under the "Common CSS" topic.
