### ISSUE TITLE
sidebar navigation icons are not centered when collapsed

### ISSUE THREAD

**Issue by sachinbhutani** [SAP/ui5-webcomponents#2911]
**Describe the bug**
when sidebar is collapsed, icons are displayed left aligned instead of center aligned. 
![image](https://user-images.githubusercontent.com/6120010/110066473-61532400-7d26-11eb-8bf9-ad9e208d1510.png)

**To reproduce**
1. Go to 'https://sap.github.io/ui5-webcomponents/playground/components/SideNavigation/?sap-ui-theme=sap_belize&isrtl=false'
2. click the #startbutton to collapse the sidebar in the example.
3. icons move to the left, leaving uneven spacing on the right of each icon.

**Isolated example**
Please provide an isolated example if possible, by forking [CodeSandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html)

**Expected behavior**
the icons should align with the #startButton

**Screenshots**
![image](https://user-images.githubusercontent.com/6120010/110066473-61532400-7d26-11eb-8bf9-ad9e208d1510.png)
**Context**
- UI5 Web Components version
- OS/Platform: {...}
- Browser *(if relevant)*: {...}
- Other information: {...}

**Affected components** *(if known)*
<ui5-side-navigation>

**Log output / Any errors** in the console
```
{...}
```

**Organization:** *(if applicable)*

**Priority:** *(optional)* *(Low, Medium, High or Very High)*

Setting priority would indicate the importance of the issue
and would help the process of dispatching and processing.

To set the appropriate priority, you need to consider the impact
and if the issue:
- Breaks entire application or system - High and Very High
- Is accessibility one (Screan Reader, Keyboard Handling) - Medium and High
- Is functional one and makes a single component unusable - Medium and High
- Is visual, styling one - Low and Medium

Note: the priority would be re-evaluated by the issue processors, according to the project internal criterias

**Business impact:** *(mandatory for "Very High")*

**Comment by terezamch** [comment]
Hello colleagues,

There is a visual issue with the Side Navigation, it is reproducible in the WC Playground. You can refer the description above. 

Regards,
Tereza

**Comment by ilhan007** [comment]
FYI @SAP/ui5-webcomponents-topic-rd

**Comment by dimovpetar** [comment]
Hello @SAP/ui5-webcomponents-topic-p ,

This looks like a problem with TreeListItem when the private property "_minimal" is set. See https://codesandbox.io/s/ui5-webcomponents-forked-ssqty?file=/index.html . When set, the icon is very close to the left without any padding.
Can you please check?

Best regards,
Petar
