### ISSUE TITLE
ui5-li-notification: Contents are displaced if description cannot wrap

### ISSUE THREAD

**Issue by todormikov** [SAP/ui5-webcomponents#2920]
**Describe the bug**
When the description of the notification contains an unwrappable line that is longer than its width and the close button or avatar are displayed, the contents of the notification are displaced to the left.

**Isolated example**
[CodeSandbox](https://codesandbox.io/s/ui5-webcomponents-forked-0vsp8?file=/index.html)

**Expected behavior**
The contents should not be able to exceed the width of the notification when a long description and close button/avatar are present.

**Screenshots**
![image](https://user-images.githubusercontent.com/79699783/110312029-3eb65900-800d-11eb-8c3f-c56241ba576b.png)

**Context**
* UI5 Web Components version: 1.0.0-rc.12

**Comment by PetyaMarkovaBogdanova** [comment]
Hi colleagues from @SAP/ui5-webcomponents-topic-rd,
there is a visual issue, concerning **ui5-li-notification**.
It is reproducible when you add a long text without whitespaces.
You can refer to the description and the example in the playground below.

Kind regards,
Petya Bogdanova.
