### ISSUE TITLE
Page Not Found for "Creating a custom UI5 Web Components package" link in the FAQ

### ISSUE THREAD

**Issue by stoehr** [SAP/ui5-webcomponents#2923]
**Describe the documentation issue**

- [ ] Documentation is unclear
- [ ] Documentation is incorrect
- [ ] Documentation is missing
- [x] Other

**Description of the issue**

The "_Q: Can I create my own UI5 Web Components?_" FAQ in https://sap.github.io/ui5-webcomponents/playground/docs/faq/ has a "_Creating a custom UI5 Web Components package_" link, but the resulting https://sap.github.io/ui5-webcomponents/playground/docs/faq/dev/Creating%20UI5%20Web%20Components%20Packages.md link URL returns an HTTP 404.  But presumably, this link URL should show a version of the https://github.com/SAP/ui5-webcomponents/blob/master/docs/dev/Creating%20UI5%20Web%20Components%20Packages.md document, and not an HTTP 404.

**Comment by PetyaMarkovaBogdanova** [comment]
Hi colleagues,
can you, please, take a look at the broken link?
Thank you!

Kind regards,
Petya.
