### ISSUE TITLE
Focus is missing for the icon of ui5-multi-input 

### ISSUE THREAD

**Issue by SherrySherry123** [SAP/ui5-webcomponents#2928]
**Describe the bug**
Focus is missing for the icon of ui5-multi-input, can not operate it through keyboard.

**To reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/MultiInput/
2. Select one ui5-multi-input with **show-value-help-icon**
3. Tab through to focus on the value-help-icon, focus is missing;

**Expected behavior**
The icon of ui5-multi-input should be focused. User can operate it through keyboard

**Actual behavior**
focus is missing for value-help-icon;

**Screenshots**

**Affected components** *(if known)*
ui5-multi-input 

**Organization:** *Successfactors*

**Priority:** *(optional)* *Medium*

Setting priority would indicate the importance of the issue
and would help the process of dispatching and processing.

To set the appropriate priority, you need to consider the impact
and if the issue:
- Is accessibility one (Screan Reader, Keyboard Handling) - Medium and High

**Comment by SherrySherry123** [comment]
<img width="994" alt="ui5-multi-input" src="https://user-images.githubusercontent.com/30891905/110449461-2b82b680-80fd-11eb-8928-7a490e7e594c.png">

**Comment by PetyaMarkovaBogdanova** [comment]
Hi @SherrySherry123 ,
by specification, the show-value-help-icon is not supposed to recieve a focus.
So in this case this behavior is the correct one.
The opening of the Value help dialog should be accomplished through key combination,
which by this moment is not implemented, so I will direct the issue to the responsible team.

Best regards,
Petya Bogdanova.

**Comment by PetyaMarkovaBogdanova** [comment]
Dear colleagues from @SAP/ui5-webcomponents-topic-rl,
can I ask you to take a look at this Feature request.

We need to implement keayboard handlig for the show-value-help-icon, which provides opening of the
value-help-dialog.

Kind regards,
Petya Bogdanova.

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-rl 

As a user, 
I would like to be able to trigger the value-help trough the keyboard.

Could you add this keyboard handling enhancement?

**Comment by zhangliangyi** [comment]
I suppose the keyboard handling is already supported in multi-input. Check https://github.com/SAP/ui5-webcomponents/issues/2143

**Comment by ilhan007** [comment]
Hi @zhangliangyi yes indeed, thanks for pointing this out, I forgot about this change, it is in place. 

The value-help-trigger event is fired when the value help icon is pressed and F4 or ALT/OPTION + ARROW_UP/ARROW_DOWN keyboard keys are used.

Nothing to be addressed here.
