### ISSUE TITLE
ui5-input: text spacing not applied to input text

### ISSUE THREAD

**Issue by BennyHuang** [SAP/ui5-webcomponents#2936]
**Describe the bug**
The text spacing not applied to input text.

**To reproduce**
Using Stylus chrome extension, apply text spacing settings to the input playground page https://sap.github.io/ui5-webcomponents/playground/components/Input/
(See test method details here - https://wiki.wdf.sap.corp/wiki/display/Acc/ACC-283+Details#ACC283Details-TestMethods)
Observe that the text spacing is applied to the input text. It seems to be the customized line-hight does not heighten the input box.

Expected behavior
Text spacing should be applied to the input text.

Context
UI5 Web Components version: 0.29.6

Affected components (if known)
ui5-input

Organization: (if applicable)
SAP SuccessFactors

Priority: (optional) (Low, Medium, High or Very High)
Low

**Comment by fifoosid** [comment]
Hi @BennyHuang 

I am unable to access the wiki page as it is down, but I have tried to reproduce the issue in this [CodeSandbox](https://codesandbox.io/s/ui5-webcomponents-forked-zxvus?file=/index.html) and as much as I can see, in version 0.29.6 you can set ```letter-spacing```, ```word-spacing``` and ```line-height``` to the ```ui5-input```.
PS: When setting ```line-height```, you need the set ```height``` to the input as well.(As in the provided sample)
