### ISSUE TITLE
ui5-avatar: click event triggler twice when it's interactive 

### ISSUE THREAD

**Issue by JosephineSu** [SAP/ui5-webcomponents#2943]
**Describe the bug**
When using avatar, setting the value of interactive prop to "true" directly in avatar component, it always triggler twice. In our app, we want to open another tab in window once user click avatar. But actually it will open two new tabs. 
**To reproduce**
1. Go to "Goals"
2.select instance: "MLT - Demo for target-baseline and tb buildin" 
3. select goal:  "test cgrant"
4. click avatar in "AlignUp" in the lower right conner.

**Isolated example**
company: TALH2TGMM1
username：cgrant
pwd：pwd1
https://qacand.hcm.ondemand.com/sf/goals?bplte_company=TALH2TGMM1&_s.crb=a73P9OGDNRBKO4e%252b3nTraAAtkFVB4ywWMJJ%252fS8P9ixs%253d#/goal-detail?targetUserId=V2-PVGFCEF7uVBEA/EO+F6nUQ==&templateType=tgm&templateId=565&id=21711

 or url using mock data:
https://qacand.hcm.ondemand.com/sf/goals?mock&bplte_company=TALH2TGMM1&_s.crb=a73P9OGDNRBKO4e%2b3nTraAAtkFVB4ywWMJJ%2fS8P9ixs%3d#/goal-detail?targetUserId=V2-0CnPmh/s1nd7tJFDK4thJQ==&templateType=tgm&templateId=583&id=11
**Expected behavior**

**Screenshots**

**Context**
- UI5 Web Components version
- OS/Platform: {...}
- Browser *(if relevant)*: {...}
- Other information: {...}

**Affected components** *(if known)*

**Log output / Any errors** in the console
```
{...}
```

**Organization:** *(if applicable)*

**Priority:** *(optional)* *(Low, Medium, High or Very High)*

Setting priority would indicate the importance of the issue
and would help the process of dispatching and processing.

To set the appropriate priority, you need to consider the impact
and if the issue:
High
- Breaks entire application or system - High and Very High
- Is accessibility one (Screan Reader, Keyboard Handling) - Medium and High
- Is functional one and makes a single component unusable - Medium and High
- Is visual, styling one - Low and Medium

Note: the priority would be re-evaluated by the issue processors, according to the project internal criterias

**Business impact:** *(mandatory for "Very High")*
Hign

**Comment by JosephineSu** [comment]
Hi @d3xter666 ,
May I know when will this issue be resolved?

**Comment by ilhan007** [comment]
Hi @JosephineSu the issue is dispatched to the responsible team. They are processing the issues by priority
For example, these issues, also filed by SFSF, are before the current one
https://github.com/SAP/ui5-webcomponents/issues/2880
https://github.com/SAP/ui5-webcomponents/issues/2910

When you file an issue, a bug, nobody can say when the issue will be resolved, however we make our best to fix them as soon as possible. It's just that this is not the only issue.

@SAP/ui5-webcomponents-topic-p could you take a look of the issue.

**Comment by JosephineSu** [comment]
Ok, got it. Thank you.

**Comment by ilhan007** [comment]
Hi @JosephineSu the issue will be included in 0.29.10 and 0.31.2 on 29-30 March

**Comment by JosephineSu** [comment]
thanks, Nicely done!
