### ISSUE TITLE
ui5-table: pressing blank key or enter key can't trigger row-click event

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents#2944]
**Describe the bug**
Pressing blank key or enter key can't trigger row-click event.

**To reproduce**
1. Go to page https://github.wdf.sap.corp/pages/xweb/goalmanagementx/app.html?mock#/goal-detail?targetUserId=undefined&templateType=tgm&templateId=583&id=11003
2. click +12 avatar on the right bottom of Goal Alignment section of the page
3. use tab key to select one table row, then pressing blank or enter key. It won't trigger row-click event.
    If you use mouse to click the table row, it will trigger row-click event.

**Expected behavior**
pressing blank key or enter key should trigger row-click event.

**Context**
- UI5 Web Components version: 0.29.7
- OS/Platform: {...}
- Browser *(if relevant)*: {...}
- Other information: {...}

**Comment by d3xter666** [comment]
According to the documentation, it is fired when a row is **clicked**.

This should be handled as a feature request for adding a semantic press event
