### ISSUE TITLE
ui5-dialog: [AXE] ARIA dialog and alertdialog nodes must have an accessible name

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents#2946]
**Describe the bug**
AXE issue: ARIA dialog and alertdialog nodes must have an accessible name

**To reproduce**

1. Go to page https://github.wdf.sap.corp/pages/xweb/goalmanagementx/app.html?mock#/goal-detail?targetUserId=undefined&templateType=tgm&templateId=583&id=11003
2. click +12 avatar on the right bottom of Goal Alignment section of the page
3. use AXE browser plugin to scan the page, it will show one serious error related with ui5-dialog.
     
Actually the dialog already defines aria-labelledby property, I don't know why AXE still reports this error.
BTW, all the dialogs in our project have this issue.

**Screenshots**
![2021-03-15_16-05-32](https://user-images.githubusercontent.com/13098801/111122007-61fe7c80-85a8-11eb-96f5-7b4cb41913da.jpg)

**Context**
- UI5 Web Components version: 0.29.7
- OS/Platform: {...}
- Browser *(if relevant)*: {...}
- Other information: {...}

**Comment by d3xter666** [comment]
There is aria-labelledby, but the tool does not detect it

**Comment by ilhan007** [comment]
Hello @GongRichard  we released a fix with 0.29.13 can you re-check
