### ISSUE TITLE
ui5-shellbar: primary title menu does not close on item selection

### ISSUE THREAD

**Issue by goodefroi** [SAP/ui5-webcomponents#2948]
**Describe the bug**
When selecting an item from the primary title menu of the Shellbar, the menu does not close by default.

**To reproduce**
1. Take `ui5-shellbar` and and populate `menuItems`.
2. Click on Shellbar title to open menu.
3. Click on any of the items.

**Minimal Example**
[`codesandbox.io`](https://codesandbox.io/s/ui5-webcomponents-forked-wv0rh?file=/index.html)

**Expected behavior**
The menu closes unless `event.preventDefault()` is called in a `menu-item-click` event handler (compare docs).

**Screenshots**
![image](https://user-images.githubusercontent.com/27777253/111308149-a0547400-865a-11eb-9238-ad4ba2ec5b9b.png)

**Version information**
`@ui5/webcomponents` & `@ui5/webcomponents-fiori` at `1.0.0-rc.12`.

**Priority:** Low

**Business impact:** None

**Comment by d3xter666** [comment]
Hi colleagues,

This seems more like a sample coding. I guess it's something with List's configuration.

Cheers

**Comment by goodefroi** [comment]
Hi @d3xter666, sorry; I was in a hurry and didn't set up a minimal example. I want to emphasise that this behaviour is _not specific to the playground sample_ - see link in edited comment above.

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-p could you check the ShellBar's menu behaviour. Upon clicking a list item, it does not close, should it close, please check and align with the spec? The docs states that it should close unless event.prevendDefault is called. So, be aware of this and update the docs if needed.
