### ISSUE TITLE
a11y: Delete button of ui5-list is not available in buttons list of JAWS(Screen reader)

### ISSUE THREAD

**Issue by lateefsofi** [SAP/ui5-webcomponents#2964]
**Describe the bug**
When we try to see the list of interactive button available on the page with JAWS(Shortcut keys) buttons list, none of the delete button of the list is present.
![image](https://user-images.githubusercontent.com/18447407/111588313-5fd73080-87e9-11eb-83fa-028f1f335076.png)

**To reproduce**
1. Go to 'https://codesandbox.io/s/ui5-webcomponents-forked-tznt5?file=/index.html'
2. Turn on JAWS screen reader
3. Press Insert + F3
4. Now select Buttons List
5. There is only 1 button but there should be more.

**Isolated example**
https://codesandbox.io/s/ui5-webcomponents-forked-tznt5?file=/index.html

**Expected behavior**
Delete buttons of the list should also be available in JAWS Buttons List,

**Screenshots**
![image](https://user-images.githubusercontent.com/18447407/111588313-5fd73080-87e9-11eb-83fa-028f1f335076.png)

**Context**
- UI5 Web Components version: V0.29.6
- OS/Platform: {...}
- Browser *(if relevant)*: {...}
- Other information: {...}

**Affected components** *(if known)*
ui5-list

**Organization:** *(if applicable)*
Success Factors

**Priority:** *(optional)* *(Low, Medium, High or Very High)*
High

**Comment by d3xter666** [comment]
Hi colleagues,

Indeed, buttons are not sown, however, this is a list with buttons and I'm not quite sure if this is a valid scenario.

**Comment by nnaydenow** [comment]
Hi @lateefsofi,

Sorry for late reply. The button should not be accessible with keyboard by specification so it is expected to not be visible in the buttons list. If you want to delete item through keyboard you can use your Delete key. This functionality was enabled with #3226 .

Best regards,
Nayden

**Comment by ej612** [comment]
Hi @nnaydenow,

UX is not happy with this behavior and would like the button to be accessible by keyboard, since this is more intuitive than pressing DEL, which will not be the first choice of users.

Could we get you to reconsider?

Thanks!

Organisation: SAC

**Comment by kgogov** [comment]
Hello @ej612,

We have updated the `List` component to better align with the current accessibility requirements as part of the following change: https://github.com/UI5/webcomponents/pull/13411.

With this update, the delete button is now properly accessible and included in the tab chain when the list is in “Edit” mode. You can enter this mode by using the `F2` / `F7` keys. Once inside, you can navigate to the internal interactive elements of the individual list items using `Tab` / `Shift + Tab`.

The `Delete` key remains supported as well, so the existing keyboard interaction is preserved.

Based on these latest changes, we consider the reported issue resolved and will proceed with closing it. If you still experience any related problems, or if you have any questions or concerns, please don’t hesitate to reach out to us again.

Best regards,  
Konstantin

**Comment by ej612** [comment]
Hi @kgogov, thank you very much for the fix and sorry for the delay. Would it be possible to get a backport to v1 for this (SAC)?

**Comment by kgogov** [comment]
Hello @ej612, sorry, I'm just seeing this message now, and thanks for reaching out.

We'll discuss this within the team and analyze the request from a technical perspective to evaluate what would be involved in backporting it to v1. Once we've had a chance to assess it, we'll get back to you with an update.

Thanks for your patience!

**Comment by kgogov** [comment]
Hi @ej612, thanks for the patience and for coming back on this.

We looked into what a v1 backport would actually require, and want to share the findings before we take a position — it's more involved than it may look from the outside.

The behavior you're asking for comes from two v2 PRs, [#12700](https://github.com/UI5/webcomponents/pull/12700) (F7 with position memory + cross-item Arrow Up/Down) and [#13411](https://github.com/UI5/webcomponents/pull/13411) (F2 + edit-mode Tab flow). Combined they touch ~14 core files, ~2,100 lines of production code and ~1,000 lines of tests. What makes this hard isn't the volume — it's that those PRs land on top of a v2 codebase whose foundations have moved on from v1.

Unfortunately, we won't be able to take this backport on. It isn't a bug fix but a new accessibility feature, and bringing it into v1.24.x would mean changing how Tab forwarding, focus management, and edit-mode state work at the base of the List, then re-validating every consumer that depends on those semantics (`Tokenizer`, `UploadCollectionItem`, `NotificationListItem`, `TreeItem*`, `MenuItem` / `SideNavigation`, the compat `Table`). The test coverage would also need to be re-authored against v1's harness. That's beyond what the v1 maintenance track is scoped to deliver.

The path we can recommend is **upgrading to v2.x**, where the full behavior is available today and is now documented ([#13900](https://github.com/UI5/webcomponents/pull/13900)). This is where the accessibility investment lives going forward.

If a v2 migration isn't on the table right now, v1 does still support the `Delete` key shortcut on a focused list item — it's keyboard-accessible, just not the Tab-through-edit-mode UX the newer Fiori spec prescribes.

If you have any questions, please feel free to get back to us.

Best regards,
Konstantin

**Comment by ej612** [comment]
Hi @kgogov,

Thank you very much for your response and for looking into a possible backport. Being a dev myself, I completely understand the difficulties and your resulting decision and will communicate this stance to our management.

Best regards,
ej612

**Comment by kgogov** [comment]
Hi @ej612,

Thanks again for your understanding on the v1 backport question.
With the original a11y concern fully addressed in v2 (via #13411 and #12700), and now that we've had a chance to align on the backport question, we're comfortable calling this one wrapped up and will gently close it for now.

If new requirements come up later or any further questions arise, please feel free to reopen — we're happy to pick it back up.

Best regards,
Konstantin
