### ISSUE TITLE
ShellBar: Inconsistent Event Handler

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents#297]
**Describe the bug**
According to the documentation, the events `notificationsPress`, `productSwitchPress`, `profilePress` and `titlePress` should all have the detail `iconRef`.
This seems not the be the case at the moment.

Current Content of `event.detail`:
- titlePress: iconRef ✅ 
- productSwitchPress: detail
- profilePress: iconRef ✅ 
- notificationsPress: null

**To reproduce**
1. Open the playground URL: https://sap.github.io/ui5-webcomponents/playground/components/ShellBar/
2. Open the development tools and insert the following snippet:
   ```javascript
   var shellbar = document.querySelector('#shellbar');
   shellbar.addEventListener('notificationsPress', (e) => console.log(e.type, e.detail))
   shellbar.addEventListener('productSwitchPress', (e) => console.log(e.type, e.detail))
   shellbar.addEventListener('profilePress', (e) => console.log(e.type, e.detail))
   shellbar.addEventListener('titlePress', (e) => console.log(e.type, e.detail))
   ```
3. Click on the respective icons in the first Shell bar and look at the console output:
   ```javascript
   productSwitchPress {detail: ui5-icon#__el26-item4..sapWCShellBarIconButton.sapWCShellBarIconProductSwitch}
   profilePress {iconRef: div#__el26-item-3..sapWCShellBarImageButton.sapWCShellBarIconButton}
   notificationsPress null
   titlePress {iconRef: button.sapWCShellBarMenuButton}
   ```

**Expected behavior**
I would expect all details to contain `iconRef`

**Context**
- UI5 Web Components version: 0.9.0
- OS/Platform: macOS 10.14.4
- Browser *(if relevant)*: Chrome 73.0.3683.86
- Other information: {...}

**Affected components** *(if known)*
`ui5-shellbar`

**Comment by MapTo0** [comment]
Hello @MarcusNotheis 

While fixing this gap I was thinking that it would be good if we define better names for ref parameter in in these events. Such as `targetRef` or something like that.

In the end it is not always an icon clicked there.

What do you think?

**Comment by MarcusNotheis** [comment]
Hi @MapTo0,

yes, totally see your point. 
`targetRef` sounds good to me.

Thanks for looking into that!

**Comment by MarcusNotheis** [comment]
If you are changing the ShellBar anyways it would be really nice if you could add events for `logoPress` and `coPilotPress` too.
