### ISSUE TITLE
Console shows "loadCldr is no a function"

### ISSUE THREAD

**Issue by hans-helmut** [SAP/ui5-webcomponents#2975]
**Console shows "loadCldr is no a function"**
I experienced the sandbox and also in my new code using [Elm](http://elm-lang.org)

**To reproduce**
1. Go to 'https://sap.github.io/ui5-webcomponents/'
2. Click button "Start coding in your browser (CodeSandbox)"
3. Browser switches to 'https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html'
4. Wait a few seconds
5. The Error "CLDR data for locale de is not loaded!" is displayed
6. Click "Console"
7. Console shows "loadCldr is no a function"

**Expected behavior**
Well, at least the simple example should work.

**Screenshots**
![ui5_loadCldr](https://user-images.githubusercontent.com/17592400/111907015-c19ad300-8a53-11eb-8470-183b8de211ce.png)

**Context**
- UI5 Web Components version: 1.0.0-rc.12 I assume)
- OS/Platform: Linux/Debian 10
- Browser *(if relevant)*: Firefox 78.8.0esr or Chromium 88.0.4324.182

**Comment by kskondov** [comment]
@SAP/ui5-webcomponents-team can you please check this issue it is reproducible when the locale is changed to another i.e. de or bg

**Comment by fifoosid** [comment]
Hi @hans-helmut 

This issue is already resolved in our master branch and will be released in rc13.
In the meantime, you can use our @ next version available on npm: ```0.0.0-5ffbbd9fe```.

Link to a working sample: https://codesandbox.io/s/ui5-webcomponents-forked-sbb6r?file=/src/index.js
