### ISSUE TITLE
Flexible Column Layout responsive behavior issue

### ISSUE THREAD

**Issue by lateefsofi** [SAP/ui5-webcomponents#2976]
**Describe the bug**
There is responsive behavior discrepancy in Flexible column layout as per its documentation. Up to 900px only 1 column should be visible but there are 2 columns visible with the latest version. Older version of Flexible column was respecting this behavior mentioned in documentation.

**To reproduce**
1. Go to 'https://codesandbox.io/s/ui5-webcomponents-forked-wktsi?file=/package.json'
2. Try to resize the screen and see the behaviour.

**Isolated example**
Current behavior: https://codesandbox.io/s/ui5-webcomponents-forked-wktsi?file=/package.json
Older version behavior:  https://codesandbox.io/s/ui5-webcomponents-forked-1i8i9?file=/package.json

**Expected behavior**
There should be a single column visible up to 900px; 

**Context**
- UI5 Web Components version: 0.29.6

**Affected components** *(if known)*
ui5-flexible-column-layout

**Organization:** *(if applicable)*
Success Factors

**Priority:** *(optional)* *(Low, Medium, High or Very High)*
High

**Comment by ilhan007** [comment]
Hello @lateefsofi 
we did change the breakpoints with this change: https://github.com/SAP/ui5-webcomponents/pull/1984
to match the fiori design https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2038570628

```
  S: '(max-width: 599px)',

  M: '(min-width: 600px) and (max-width: 1023px)',

  L: '(min-width: 1024px) and (max-width: 1439px)',

  XL: '(min-width: 1440px)'
```

But it seems we did not update to docs - we will fix that.
Now, one column should be visible up to 599px and two columns up to 1023px.

**Comment by ilhan007** [comment]
DOCS Updated https://github.com/SAP/ui5-webcomponents/pull/2977
