### ISSUE TITLE
ui5-table: there is no bottom border of last data row

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents#2981]
**Describe the bug**
There is no bottom border of the last data row.

**To reproduce**
1. Go to 'https://sap.github.io/ui5-webcomponents/playground/components/Table/'
2. check Basic Table example, there is no bottom border of the last data row.

**Expected behavior**
Please check below fiori samples, there should have bottom border of the last data row.
https://wiki.wdf.sap.corp/wiki/display/visualcore/Table+%28Fiori+3%29+-+Navigation+Indication
https://sapui5.hana.ondemand.com/#/entity/sap.m.Table/sample/sap.m.sample.Table

**Context**
- UI5 Web Components version: 0.29.7
- OS/Platform: {...}
- Browser *(if relevant)*: {...}
- Other information: {...}

**Comment by kskondov** [comment]
Hello "@SAP/ui5-webcomponents-topic-rl"  I am forwarding this issue to you, to review if the sample should be updated to be in compliance with sap.m.Table specifications

**Comment by ilhan007** [comment]
This fix will be delivered with 0.29.12 (and 0.31.3) on 30 March at latest
