### ISSUE TITLE
List: Keyboard trap found within the List component

### ISSUE THREAD

**Issue by sleric1024** [SAP/ui5-webcomponents#2982]
**Describe the bug**
Using arrow keys get to the last item of list  -> observe that on subsequent tabs after the last button of the last item -> the focus goes back to the first bookmark list item once again.

**Isolated Example**
https://zk8jr.csb.app/

**To Reproduce**
1. Open https://zk8jr.csb.app/
2. Using 'tab' key to get the first line to be focused.
3. Press tab to get the buttons to be focused 
3. Subsequent tabs after the last button, the focus will go to the next item

**Expected behavior**
https://ui5.sap.com/#/entity/sap.m.NotificationListItem/sample/sap.m.sample.NotificationListItem

Arrow keys moves focus through the listbox, Pressing Tab will take the focus to the interactive elements within each listbox item, Pressing Tab from the last interactive element within a list item will exit the list box.

**Screenshots**
![image](https://user-images.githubusercontent.com/5724592/111949487-c88d1880-8b1b-11eb-9ccd-b5483f564c6f.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: current version
`@ui5/webcomponents-react` version: current version
Operating System: Mac OS
Browser: Chrome

**Additional context**
I am from Successfactors

**Comment by kskondov** [comment]
Hello @ui5-webcomponents-topic-p can you please review this focus issue within the List component

**Comment by dobrinyonkov** [comment]
Hello @sleric1024,

this issue is related with #2849 and fixed with #2870.

Kind Regards,
Dobrin

**Comment by ilhan007** [comment]
Hello @sleric1024 which version do you use?

**Comment by ilhan007** [comment]
Hi @dobrinyonkov the fix #2870 is released with 0.29.5. The author is using 0.29.9 that should also include the fix.

@sleric1024 could you provide a link to the code editing view of the sample app?

**Comment by sleric1024** [comment]
@ilhan007 , thanks for your detail information. You may try https://codesandbox.io/s/quizzical-euler-zk8jr?file=/src/App.js:1151-1270.

**Comment by dobrinyonkov** [comment]
Hi @sleric1024, 

after setting the versions in the codesandbox, the example looks to work fine:
- v0.29.9 for ui5-webcomponents
- v0.129.9 for ui5-webcomponent-react

https://codesandbox.io/s/affectionate-lumiere-719tp?file=/package.json

Could you please test again on your side ?

**Comment by sleric1024** [comment]
Hi @dobrinyonkov,
It had been fixed. Thanks for your quick response.
