### ISSUE TITLE
Rating Indicator announce "To increase or decrease use the arrow keys." when readonly is on.

### ISSUE THREAD

**Issue by mrmabo** [SAP/ui5-webcomponents#2989]
**Describe the bug**
1. Navigating to Rating Indicator causes Jaws to announce "To increase or decrease use the arrow keys." 
2. User is then unable to use the arrow keys to increase or decrease the rating. 

**To reproduce**
1. Go to https://codesandbox.io/s/ui5-webcomponents-forked-bkucb?file=/index.html
2. Turn on screen reader and Navigate to Rating Indicator
3. Rating Indicator announce "To increase or decrease use the arrow keys."

**Isolated example**
https://codesandbox.io/s/ui5-webcomponents-forked-bkucb?file=/index.html

**Expected behavior**
Not announce "To increase or decrease use the arrow keys." when rating indicator set readonly.

**Context**
- UI5 Web Components version 0.29.6
- OS/Platform: NA
- Browser *(if relevant)*: Chrome Version 89.0.4389.82 (Official Build) (64-bit)
- Other information: NA

**Affected components** 
ui5-rating-indicator

**Organization:** *(if applicable)*
Success Factors

**Priority:** 
High

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-rl is it expected to have the default announcement "To increase or decrease use the arrow keys." for readonly RatingIndicator as well.

**Comment by niyap** [comment]
Hello @mrmabo,

Thanks for sharing your findings!

The mentioned announcement comes from the element's role and the screenreader, so we do not have any influence over it.
I have isolated the described issue with native HTML, in order to demonstrate that the speech output is the same: https://jsbin.com/xevarifafi/1/edit?html,js,output

**Comment by mrmabo** [comment]
@niyap 
Thanks for your example.
However, we have to remove the mentioned announcement. Is there any way to change the role for Rating Indicator component?
