### ISSUE TITLE
Passive Listeners to improve performance on scroll

### ISSUE THREAD

**Issue by vladitasev** [SAP/ui5-webcomponents#2995]
Check the framework and components and find out if passive event listeners can be used for some of the scroll events.

**Comment by ilhan007** [comment]
Original issue:
https://github.com/SAP/ui5-webcomponents/issues/3874

**Comment by guedes4g** [comment]
Hi colleagues, is there any progress on this issue?

**Comment by fifoosid** [comment]
Hi @guedes4g 

The issue is resolved and should be released with our next version.
