### ISSUE TITLE
Missing rounded corners in <ui5-popover>

### ISSUE THREAD

**Issue by pavelkornev** [SAP/ui5-webcomponents#30]
**Describe the bug**
On https://sap.github.io/ui5-webcomponents/playground.html#/components/Popover
When opening the popover, the top corners are rounded and the bottom not:
<img width="316" alt="ui5 web components - playground 2019-02-12 22-12-35" src="https://user-images.githubusercontent.com/748043/52668512-10401f80-2f14-11e9-97e2-291629b2fecd.png">

I assume it might be a design decision to round only top corners, but it doesn't look so because in such scenarios the contrast is normally higher (e.g. 3-5 time bigger border-radius, example — https://i.stack.imgur.com/srHXl.png).

**Expected behavior**
all 4 corners should be rounded or not, or have an explicit contrast.

**Comment by pavelkornev** [comment]
And there is also the accessibility issue in this example (click on label doesn't bring focus on the field):
![screencast 2019-02-12 22-24-21](https://user-images.githubusercontent.com/748043/52668975-4631d380-2f15-11e9-93f2-6d9836a7b02f.gif)

**Comment by ilhan007** [comment]
Hello @pavelkornev.

The accessibility issue is addressed with 
https://github.com/SAP/ui5-webcomponents/pull/33

And, regarding the rounding of the popover corners, we will raise the question to the designers and get back to you.

**Comment by ilhan007** [comment]
Hello @pavelkornev, we rounded the bottom borders.
