### ISSUE TITLE
SF: ui5-file-uploader - file explorer dialog doesn't open using keys like spacebar or enter.

### ISSUE THREAD

**Issue by Brahmansh** [SAP/ui5-webcomponents#3001]
Description:
In File Uploader component, file explorer dialog doesn't open using keys like spacebar or enter.
And there is no description regarding keyboard handling on the component page.

1. Go to https://sap.github.io/ui5-webcomponents/playground/components/FileUploader/
2. Navigate using keyboard and go to "Upload images" button
3. Try 'Enter' key or 'Spacebar' key to open file explorer dialog, nothing happens.

Expected behavior:
File Uploader should be keyboard accessible.

Context:
- UI5 Web Components version: 0.29.8
- OS/Platform: {...}
- Browser *(if relevant)*: {...}
- Other information: {...}

**Comment by kskondov** [comment]
Hello @SAP/ui5-webcomponents-topic-b  I am forwarding this issue to you, as owners of the ui5-file-uploader, can you please take a look at how to access the uploader via keyboard

**Comment by ilhan007** [comment]
Hello @Brahmansh the fix will be released in few days - the next 0.29.13 will include it.

**Comment by ilhan007** [comment]
Hello @Brahmansh the fix is released with 0.29.13
