### ISSUE TITLE
SF: ui5-title - currently there is no property to change level (for accessibility purpose) without changing level for styling

### ISSUE THREAD

**Issue by Brahmansh** [SAP/ui5-webcomponents#3003]
Description
Currently, there is no property in ui5-title component to support aria level without changing style. e.g. we want to keep styling of H5 but accessibility level of H3. 
In https://sapui5.hana.ondemand.com/#/api/sap.m.Title%23controlProperties there was two separate properties to handle this scenario - level & titleStyle.

To reproduce
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/Title/
2. There is only one property 'level' to set the styling of title.

Expected behavior
Expectation is to have two separate properties to control level (for accessibility purpose) and title style

Context
- UI5 Web Components version: 0.29.8
- OS/Platform: {...}
- Browser *(if relevant)*: {...}
- Other information: {...}

**Comment by ilhan007** [comment]
Hello @Brahmansh

to to keep styling of H5 but accessibility level of H3, you can define 1 line of CSS
```css
.titleH5 {
   font-size: 1rem /* or font-size: var(--ui5_title_level_5Size) */
}
```

and apply  it to the Title (using level H3 for a11y reasons)

```html
<ui5-title level="H3" class="titleH5">Title ACC level 3</ui5-title>
```

Is it working for you?
