### ISSUE TITLE
Link: Unable to activate Link through ENTER key press

### ISSUE THREAD

**Issue by 2bno1** [SAP/ui5-webcomponents#3007]
**Describe the bug**
Per [document](https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-link--default-story), onClick should be "Fired when the Link is triggered either with a mouse/tap or by using the Enter key."
However, onClick is not called by using Enter Key when it's focused.

**Isolated Example**
https://codesandbox.io/s/sad-faraday-voiil?file=/src/App.js

**To Reproduce**
1. Go to https://codesandbox.io/s/sad-faraday-voiil?file=/src/App.js
2. Press `Tab` key to focus on the Link: 'Focus me and press Enter'
3. Press `Enter` key
4. The `onClick` is not fired

**Expected behavior**
The `onClick` of the Link component should be fired by pressing Enter key

**Screenshots**

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 0.29.8 (@sf)
`@ui5/webcomponents-react` version: 0.129.8 (@sf)
Operating System: macOS Version 11.2.3
Browser: Chrome Version 89.0.4389.90

**Additional context**
N/A

**Comment by fifoosid** [comment]
Hi guys,

As you can read in our [docs](https://sap.github.io/ui5-webcomponents/playground/components/Link/), the ```ui5-link``` should fire click event either with a mouse/tap or by using the Enter key. Moreover, you can try to add click eventlistener to any of the links on the page and you can observe that the event is actually thrown.

**Comment by MarcusNotheis** [comment]
Looks like this is somehow connected to the presence of the `href` attribute: https://codesandbox.io/s/nice-rhodes-508hc?file=/src/App.js

**Comment by 2bno1** [comment]
> Hi @2bno1
> 
> you need to add the corresponding key event for this to work. [Example](https://codesandbox.io/s/happy-hill-9wxgf?file=/src/App.js)

@Lukas742 Thanks, the example works.
However, as ENTER key press is the standard keyboard activation key for links. Is there any plan to enhance this ui5-link component to handle ENTER key automatically?

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-p 

The link component should behave same as the openui5 Link. The ui5-link should fire the onClick event after pressing the Enter key, currently does not.
