### ISSUE TITLE
In Calendar need months property like sap.ui.unified.Calendar

### ISSUE THREAD

**Issue by gopusrikanth04** [SAP/ui5-webcomponents#3011]
**Is your feature request related to a problem? Please describe.**
In Calendar there is no months property and not having any alternate solution. 

sap.ui.unified.Calendar and sap.ui.unified.CalendarLegend

**Describe the solution you'd like**

![calendar](https://user-images.githubusercontent.com/47174113/112434547-baccd280-8d69-11eb-92cb-ff607468546b.png)

     <u:Calendar id="calendarTab"
            legend="legend1"
            months="12"
            showWeekNumbers="false"
            singleSelection="false"
            width="100%"
            select="handleCalendarSelect" />
        <u:CalendarLegend id="legend1"/>

**Comment by DMihaylova** [comment]
Hello @gopusrikanth04,

We're currently working on providing the Legend component. 
Speaking for months property, do you mean that you need similar functionality like "months" property in sap.ui.unified.Calendar?
https://ui5.sap.com/#/api/sap.ui.unified.Calendar%23controlProperties

Thanks & Regards,
Diana

**Comment by DMihaylova** [comment]
Hi @gopusrikanth04,

The brand new Calendar Legend component is now ready and there are also special calendar dates introduced in the Calendar.
Is your months property request still valid and do you refer the same functionality like in sap.ui.unified.Calendar's "months" property?
https://ui5.sap.com/#/api/sap.ui.unified.Calendar%23controlProperties

**Comment by DMihaylova** [comment]
Since it's currently not clear whether months property is needed, I'm closing this issue.
The 1.23 milestone is regarding the newly introduced Calendar Legend component.
