### ISSUE TITLE
Dialog: RTL is not working

### ISSUE THREAD

**Issue by 2bno1** [SAP/ui5-webcomponents#3013]
**Describe the bug**
RTL is not working as expected for ui5-dialog

**To reproduce**
1. https://codesandbox.io/s/naughty-vaughan-txwbf?file=/src/App.js
2. Please notice the paragraph `This is paragraph` layouts as expected
3. Please notice the elements in ui5-dialog do not layout as expected

**Isolated example**
https://codesandbox.io/s/naughty-vaughan-txwbf?file=/src/App.js

**Expected behavior**
The elements in ui5-dialog layout as RTL as expected

**Screenshots**
![image](https://user-images.githubusercontent.com/1751846/112444765-5d487e00-8d89-11eb-936e-d556b6251289.png)

**Context**
- UI5 Web Components version: 0.29.8
- OS/Platform: macOS Version 11.2.3
- Browser: Chrome Version 89.0.4389.90

**Comment by kskondov** [comment]
Hello @SAP/ui5-webcomponents-topic-rd, RTL is not affecting dialog and popups when set in the html. Possible partial solution for the content might be to use dir="{{effectiveDir}}" in the popup template.
Best Regards,
Konstantin

**Comment by TeodorTaushanov** [comment]
Hi @SAP/ui5-webcomponents-team, is there any way to set RTL globally, so each ui5 webcomponents are in rtl mode?

**Comment by ilhan007** [comment]
There used to be a config field, we removed it. RTL is now set via the dir attribute.

```html
<body dir="rtl"
```

If you need to change from LTR to RTL and vice versa dynamically at runtime, you  have to use 
the `applyDirection` method, so rtl/ltr specific styles get effect.
```js
import applyDirection from "@ui5/webcomponents-base/dist/locale/applyDirection.js";
```


It is explained here: https://github.com/SAP/ui5-webcomponents/blob/master/docs/Configuration.md#rtl

**Comment by ilhan007** [comment]
@TeodorTaushanov
if you inspect the shadow DOM of the Dialog,
 you will notice that the dir is "ltr", although "rtl" is set on the body.

In Popup.hbs

Instead of
```html
<section dir="{{dir}}"
```

you might have to use 

```html
<section dir="{{effectiveDir}}"
```
