### ISSUE TITLE
[SF][BUG][UI5-Dialog][Resizable Mode] The inside ui5-icon displays error in RTL mode

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents#3029]
**Dear colleagues,**
I am from SuccessFactors Web Experience Shanghai team.
My name is Hubery Shen and this account is our team account.

**Bug Description:**
The inside ui5-icon displays error in RTL mode
Link: [https://sap.github.io/ui5-webcomponents/playground/components/Dialog/?sap-ui-theme=sap_fiori_3&isrtl=true](https://sap.github.io/ui5-webcomponents/playground/components/Dialog/?sap-ui-theme=sap_fiori_3&isrtl=true)
<img width="632" alt="Screen Shot 2021-03-29 at 2 02 04 PM" src="https://user-images.githubusercontent.com/78520316/112794286-3778ed00-9099-11eb-84f0-16ebae642927.png">

**Comment by fifoosid** [comment]
Hi @sfsf-xweb-sh 

In which version do you need this bug fixed?

**Comment by GongRichard** [comment]
@fifoosid,

Please put this fix to 0.31.X version.

Thanks,
Richard
