### ISSUE TITLE
ColorPalette: history swatch section is missing/not definable

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#3049]
**Describe the bug**
When using a `ColorPalette` there are no empty swatches which can be populated by selecting a color in the palette or by using the "More Colors" button.

**Isolated example**
https://codesandbox.io/s/ui5-webcomponents-forked-7qwnd?file=/index.html

**Expected behavior**
It should be possible to create the component according to the UX Guidelines.
[Example](https://sapui5.hana.ondemand.com/#/entity/sap.m.ColorPalette/sample/sap.m.sample.ColorPalettePopover)

I could think of two options to solve this:

1. Implement the empty swatches below the optional "More Colors" button and set them to the corresponding color the user chose in the palette/color picker.
![image](https://user-images.githubusercontent.com/9749730/113000874-880f4980-9170-11eb-991c-d4156eaf9164.png)

2. Add a `click/change` event and a prop for disabling interaction to the `ColorPaletteItem` so users can implement this behavior themselves. Currently it's not possible to get the selected color of an `ColorPaletteItem` outside of the `ColorPalette`. (see [codesandbox](https://codesandbox.io/s/ui5-webcomponents-forked-7qwnd?file=/index.html))

**Screenshots**
Empty swatches below "More Colors" button
![image](https://user-images.githubusercontent.com/9749730/113001485-23082380-9171-11eb-98a9-417a1dc4d354.png)

**Context**
- UI5 Web Components version: v1.0.0-rc.13

**Affected components** *(if known)*
- ColorPalette
- ColorPaletteItem

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-b 

With RC.13 we already introduced "more-colors" property that displays a "More colors" button below the color set
<img width="203" alt="Screenshot 2021-03-31 at 17 21 48" src="https://user-images.githubusercontent.com/15702139/113160158-e8bc8600-9245-11eb-950b-1e26ebb13d1a.png">


To complete the whole picture, now we would like to have also a row of empty swatches,
rendered right below the "More Colors" button, so the app developers can define them at some point. Usually, they represent the last used colors.
There is already a change event on ColorPalette level, so the app developer can use the event to update those swatches with the colors he/she decides.
<img width="334" alt="Screenshot 2021-03-31 at 17 25 51" src="https://user-images.githubusercontent.com/15702139/113160419-27ead700-9246-11eb-90ed-85ce25531485.png">


**Technically,**  a solution would be to introduce a new slot "recentColors" and treat them the same way as  the default "colors" slot.

```js
"recentColors": {
	type: HTMLElement,
	invalidateOnChildChange: true,
	individualSlots: true,
},
