### ISSUE TITLE
Successfactor: IE11 window.fetch polyfill should also includes window.Headers window.Request window.Response

### ISSUE THREAD

**Issue by mydavidzhang** [SAP/ui5-webcomponents#3052]
**Describe the bug**
In IE11 when import "@ui5/webcomponents-base/dist/features/browsersupport/IE11.js";, when try to use window.Headers to handle batch response. IE will throw error "Headers" is undefined.
https://github.com/SAP/ui5-webcomponents/blob/master/packages/ie11/src/features/IE11.js#L33
https://github.com/SAP/ui5-webcomponents/blob/master/packages/ie11/src/thirdparty/fetch.js#L1 
Only window.fetch is polyfilled.
Other library for example whatwg-fetch: https://github.com/github/fetch/blob/master/fetch.js#L602 will include window.Headers window.Request window.Response also.

**To reproduce**
On IE import "@ui5/webcomponents-base/dist/features/browsersupport/IE11.js";
Then in console type "window.Headers"
Will see js error "Headers" is undefined.

**Isolated example**

**Expected behavior**
Provide one new file @ui5/webcomponents-base/dist/features/browsersupport/IE11WithoutFetch.js so that could be used to include all functions needed for window.fetch. window.Headers window.Request window.Response should be polyfilled.

**Context**
- UI5 Web Components version 0.29.12
- Browser IE11

**Organization:**
Successfactors.

**Comment by ilhan007** [comment]
Hi @mydavidzhang 

in 0.29.13 you can find  the following module  `@ui5/webcomponents-base/dist/features/browsersupport/IE11WithoutFetch.js`
that includes the IE11 support without the "fetch".
