### ISSUE TITLE
Example without framework

### ISSUE THREAD

**Issue by dfenerski** [SAP/ui5-webcomponents#3057]
Is there an example around for usage without any framework, just raw HTML and JS?

- [ ] Documentation is unclear
- [ ] Documentation is incorrect
- [x] Documentation is missing
- [x] Other

My use case needs a couple of HTML templates that follow the Fiori design guidelines, so I thought that ui5-webcomponents might be the way to do it. After some digging, however, I am unable to find a proper 'framework-less' example, nor a CDN I can include in such template. 

Our main project uses OPENUI5 with a grunt build, so we don't have npm or node_modules for the frontend, that's why I ask for a CDN.

I cannot add a view to the UI5 application for this, it is mounted on different path.
I am looking for a way to utilize the res.sendFile() function (Express).

Is this possible? 

Thanks in advance.

**Comment by ilhan007** [comment]
Hello @dfenerski 

We don't provide a CDN, you have to create a bundle (pretty much like own CDN), it might be a separate project where you install the UI5 Web Components and import the components you need. Of course, you will need bundlers like rollup and webpack for the purpose. Then, you just need to host the produced bundle and refer to it as a CDN.

You can refer to this project to help you create your own bundle with rollup:
https://github.com/ilhan007/rollup-wc

You can refer to these blogs for usage without any framework:
https://blogs.sap.com/2020/12/30/using-ui5-web-components-without-any-framework/
https://blogs.sap.com/2019/04/01/the-fastest-way-to-get-started-with-ui5-web-components/

You can use the bundle, that we use for our documentation [website](ttps://sap.github.io/ui5-webcomponents/), as CDN, but it includes all the components, all the icons and all the features and I doubt you need everything, still:
https://sap.github.io/ui5-webcomponents/assets/js/ui5-webcomponents/bundle.esm.js

**Comment by dfenerski** [comment]
Thanks!
