### ISSUE TITLE
ui5-wizard: ui5-wizard not works in iPhone Safari browser

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents#3060]
**Describe the bug**
 ui5-wizard does not work in the iPhone Safari browser.

**To reproduce**
1. Use iPhone safari to open page 'https://sap.github.io/ui5-webcomponents/playground/components/Wizard/'
2. It shows not right.
3. Only can go to step 2 and can't go forward.

**Isolated example**
![IMG_0036](https://user-images.githubusercontent.com/13098801/113109245-62e60e00-9238-11eb-9ef8-8a6237a38de2.PNG)

**Expected behavior**
Works well in Andorid browser
![WechatIMG396](https://user-images.githubusercontent.com/13098801/113109223-5f528700-9238-11eb-8ebb-cb77bab057a2.jpeg)

**Context**
- UI5 Web Components version: 0.29.11
- OS/Platform: {IOS 13.3/ iphone 7 plus}
- Browser *(if relevant)*: {Sarari}
- Other information: {...}

**Comment by fifoosid** [comment]
Hi @GongRichard 

I tested out the sample in the playground and works fine on IOS 14.4.2/Iphone 11 Pro.(*Note: * the playground is currently showing RC13 version).

As much as I can see you have described that this issue occurs in 0.29.11, if so please share a link where we can reproduce the issue.

**Comment by GongRichard** [comment]
Hi @fifoosid ，
I used IOS 13.3/ iPhone 7 plus, so maybe it caused by the lower ios version. I closed it first and will use the latest iPhone to test again.
