### ISSUE TITLE
Strange Tree behavior when Text overflows

### ISSUE THREAD

**Issue by MaxRumpf** [SAP/ui5-webcomponents#3069]
Hey ui5-webcomponents-Team,

We have used your Tree-Component in our React Web App.
What we noticed is that if the items are too long to be displayed in one line, there is a "..." added to the end of the text. But then they get shifted to the left, therefore making the impression that the items coming after it are children of the the one shifted to the left. This also gets worse the smaller the browser window is.
Please see the attached screenshots. These are all root-level items, there is no nesting visible, so they should all be aligned.
<img width="428" alt="TreeFailure" src="https://user-images.githubusercontent.com/4653567/113158061-bd349e00-923b-11eb-99a5-f64ade6b5279.PNG">
<img width="208" alt="TreeFailure2" src="https://user-images.githubusercontent.com/4653567/113158058-bc9c0780-923b-11eb-9ec5-fa7684295020.PNG">

Thanks in advance 😃

**Comment by unazko** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

The issue is reproducible with the following snipped:
https://codesandbox.io/s/busy-flower-p6y3v?file=/index.html

Could you please process the issue further.

Best Regards,
Boyan
