### ISSUE TITLE
UploadCollectionItem - display progress incorrect

### ISSUE THREAD

**Issue by knuspertante** [SAP/ui5-webcomponents#3080]
**Describe the bug**
UploadCollectionItem doesn't update the progressbar correctly if property is set. 

On the gif you can see, that the progress should be going forward (look at console or just right next to the start button)

**Isolated example**
https://codesandbox.io/s/litelement-typescript-forked-tcs1x?file=/src/file-upload.ts
Unfortunately I don't get it working there but in this example you can see the code. 

**Expected behavior**

**Screenshots**
![Example](https://user-images.githubusercontent.com/32802753/113285087-d21c3a80-92ea-11eb-82d7-d3fe92926e96.gif)

**Affected components**
UploadColelctionItem
ProgressIndicator

**Priority:**
For me it's high ;-) but I don't think all will share this opinion so therby its Medium

**Comment by ilhan007** [comment]
Hello @knuspertante

Unfortunately we can't scale if we debug every sample and app, please make it work so it's easily reproducible and then we will forward the issue to the responsible team to investigate it.

BR,
ilhan

**Comment by knuspertante** [comment]
> Hello @knuspertante
> 
> Unfortunately we can't scale if we debug every sample and app, please make it work so it's easily reproducible and then we will forward the issue to the responsible team to investigate it.
> 
> BR,
> ilhan

Hey @ilhan007,

I was able to do that ;-) So done. Pls have a Look now ;-) Thx for your time and your awsome work so far.

**Comment by unazko** [comment]
Hello @SAP/ui5-webcomponents-topic-rd,

I've put a "bug" label, but it might be a consultation as well.
I've reproduced an issue with the progress indication update of upload collection component in the provided snippet:
https://codesandbox.io/s/litelement-typescript-forked-tcs1x?file=/src/file-upload.ts

Steps to reproduce:
1) Select any file
2) Press the "Start" button

On my machine the progress indicator didn't update at all (0%).

I don't think that this is a problem with the ProgressIndicator component as in the provided snippet there is no value other than 0% given as input to that component.

I've tried to adjust the provided snipped so the progress indicator would update properly, but I couldn't.
Could you please review as well.

Best Regards,
Boyan

**Comment by knuspertante** [comment]
Hello @SAP/ui5-webcomponents-topic-rd,

I've updated the example and add a html progressbar at the bottom (under the ui5-upload component), to see the issue. 

Is it possible that the bug could be in context with fast changing progress? 
e. g. ui5-component can't upgrade so fast?

Because now the progress will be updated every ms with 0,1 %

If the code is changed to: 
`function addProgress() {
    progress.loaded += 10;
    if (progressCallback) {
      if (typeof progressCallback === 'function') {
        progressCallback(progress);
      } else {
        console.log(
          'progressCallback should be a function, not a ' +
            typeof progressCallback,
        );
      }
    }
    setTimeout(addProgress, 300);
  }`

everything is fine

**Comment by gmkv** [comment]
Hi @knuspertante 
I don't see the sample being updated, could you check?
I also tried to reproduce the issue with this [minimal example](https://codesandbox.io/s/ui5-webcomponents-forked-lhvdz?file=/src/index.js), but I couldn't. 
Looks to me like you can indeed update the progress bar quickly, with `setTimeout(callback, 1)`.

Are you also sure that changing the private property _files will cause LitElement to automatically rerender your element? Maybe it's worth looking into that.

**Comment by knuspertante** [comment]
Hi @gmkv 
yes I update [my example](https://codesandbox.io/s/litelement-typescript-forked-tcs1x?file=/src/file-upload.ts). 

I also could reproduce the error in your [minimal example](https://codesandbox.io/s/ui5-webcomponents-forked-vu20l?file=/src/index.js). Pls have a look there. 

Is it possible, that attributes only accepts Integers?

In your example also the ProgressBar do not work with floating numbers but in my example it does?! .. 

Yeah I tried to call LitElement's requestUpdate method in after every assigning. But I think this is not necessary because I reassign this._files in _updateFileStatus method. 

Thx for your time!

**Comment by gmkv** [comment]
Yes, it only accepts integers.
You can also read more about all the available attributes in the [Playground](https://sap.github.io/ui5-webcomponents/playground/components/UploadCollection/).
In your example, you use `....progress="${file.progressInPercent}"...` calculated as `file.progressInPercent = (loaded / total) * 100;` which indeed doesn't result in a round number.
Let me know if it works after you changed your progressCallback to calculate in round numbers/integers.

**Comment by knuspertante** [comment]
Ok nice, Integer was really the problem. 👍👌

But I was confused, because the ui5-progress-indicator works as well with floating numbers, as you can see in my example. 

Really nice and thx for your time! Awesome work you did with this lib!
