### ISSUE TITLE
ui5-date-picker: month navigator does not take effect in some case

### ISSUE THREAD

**Issue by zhangliangyi** [SAP/ui5-webcomponents#3083]
**Describe the bug**
In some case, when clicking the month navigator in the calendar popover, the calendar will not switch to the previous month until another clicking.

**To reproduce**
1. Open the example link below
2. Open the calendar popover of the date-picker component
3. Click the month navigator to previous month

**Isolated example**
https://codesandbox.io/s/ui5-webcomponents-forked-o09i9?file=/index.html

**Expected behavior**
The calendar should switch to the previous month.

**Context**
- UI5 Web Components version: 0.29.12
- OS/Platform: Mac OS
- Browser *(if relevant)*: Edge
- Other information: {...}

**Affected components** *(if known)*
ui5-date-picker

**Organization:** SF

**Priority:** Medium

**Comment by ilhan007** [comment]
@SAP/ui5-webcomponents-topic-b this is for you.

**Comment by ilhan007** [comment]
Hi @zhangliangyi f

fix has been merged and will be available with 0.29.15 until the end of the week. We will let you know when the patch is released.

**Comment by zhangliangyi** [comment]
@ilhan007 thanks for quick fix.
This fix will also be available in the next 0.31.x release, right?

**Comment by ilhan007** [comment]
Hello @zhangliangyi 

The implementation of the DatePicker in 0.31 is different than 0.29, we can't apply the exact same code/fix. 

In fact, in the master the issue does not reproduce at all. We introduced a fix in 0.29 because you stated that this is the version in use ("UI5 Web Components version: 0.29.12")

We will check if the issue is reproducible in 0.31 and will perform perhaps another change as the same code can't be downported.

Do you plan to upgrade to 0.31?, because then it's kind of waste that we fixed the issue in 0.29.

**Comment by zhangliangyi** [comment]
@ilhan007 
We plan to apply the fix in our next release and in the next release, we also plan to upgrade ui5-wc to 0.31.x. So if you confirm this issue is only in 0.29.x and not able to be replicated in 0.31.x, I agree with you that there is no need to add it in next 0.29.x.

**Comment by ilhan007** [comment]
The thing is that, no matter we release it or not, we already worked on the issue in 0.29 and we merged a fix in 0.29.
That's already a waste.

I discussed with the assigned processor to check 0.31. We don't know what is the state there, we will let you know soon.

**Comment by tsanislavgatev** [comment]
@zhangliangyi  
Hello, I've just checked and the issue is NOT reproducible in version 0.31.

Best Regards,
Tsanislav

**Comment by zhangliangyi** [comment]
Thanks @tsanislavgatev
Sounds good for me.

@ilhan007 I will add additional information when we are close to the time slot of major version switch. Hope this will avoid this kind of case.

**Comment by ilhan007** [comment]
Hi @zhangliangyi yes it would be great if you make clear when you plan to update to avoid fixing something specifically for older version that will no longer be used after short period. Thank you.
