### ISSUE TITLE
ui5-date-picker does not dispatch change event when set programmatically

### ISSUE THREAD

**Issue by ranielzed** [SAP/ui5-webcomponents#3084]
**Is your feature request related to a problem? Please describe.**
I need to react when the date-picker has been set programmatically.
For example, I have a read-only age field that computes the age based on the selected date.
Interacting with it manually does fine with change and input events but it doesn't when set programmatically

**Describe the solution you'd like**
dispatch an event to notify that the value has been changed

**Comment by ilhan007** [comment]
Hay @ranielzed 

The components fire events when they change their state due to user interaction. When the app developers change the state of the components, they already know and usually don't need an event. 
When you set the a new value to he DatePicker, you already know the value, right? Can you elaborate a bit, may I am missing the point.

BR,
ilhan

**Comment by ranielzed** [comment]
Thanks @ilhan007 for your response.
Basically I have two fields, the Date of Birth Datepicker field and another read-only input named age.
These are in a dialog where I open when I edit information. I can set the data on the DatePicker like how you described but since I don't store the age -- since can be computed from the Date of Birth.

So when setting the value of the Date of Birth, I'm hoping there's an event that could also trigger to compute the value of the age field.

**Comment by ilhan007** [comment]
Hello @ranielzed still can't understand the need for an event

At the point you do this "So when setting the value of the Date of Birth", you can compute the age, without waiting for an event.

I am closing the issue, but if you want you can re-create your scenario here to show-case what is preventing you from implementing it
https://codesandbox.io/s/71r1x5o51q
