### ISSUE TITLE
Components API Review

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents#3107]
The goal is to go trough all the [components](https://sap.github.io/ui5-webcomponents/master/playground/components) API and check:
- if the naming could be better
- if the property/event/slot make sense at all
- if we should go with a slot, instead of property or the opposite
- if the event parameters are fine
- other

**Comment by fifoosid** [comment]
Avatar:

- image property -> image slot (Currently people can't pass properties to the img tag. That's why we decided to to add one CSS property: ```image-fit-type```)
- icon property -> icon slot & initials property -> initials slot(If we have slots only as an external API, then we can get rid of the properties ```background-color```, ```size``` and ```shape```, which are CSS properties as well)

Avatar Group:
- is ```avatarSize``` needed? The size can be set on each item passed in the default slot.

**Comment by ilhan007** [comment]
Button
- iconSize public to private, or if really needed - perhaps we need to introduce a slot

ColorPalette
- now we have more-colors and show-recent-colors - either we should name both with "show-" or without "show-"

**Comment by nnaydenow** [comment]
AvatarGroup

- Think about replacing **ui5-avatar** with **ui5-avatar-group-item** (or something else). To many properties were introduced into the API of **ui5-avatar** so it can have correct interaction and accessibility behavior so it can fit as item in **ui5-avatar-group**. Previously it was display only control.

**Comment by a-z-ivanov** [comment]
Button

The disabled showcase is part of the design property example.

==========

Bar

There is no default slot. I would expect middleContent. Or at least the documentation should be corrected.

Unless targeting the default slot, use the slot attribute to define the destination slot for each child.
Text, along with HTML Elements with no slot attribute, goes the the default slot.


==========

ColorPaletteItem

What is stableDomRef? Like id, right?

==========

DatePicker

openPicker, closePicker, isOpen - the last one is inconsistent
Same for the DateRangePicker, DateTimePicker, DurationPicker

==========

DateRangePicker

firstDateValue,
lastDateValue

The naming suggests there are multiple single moments in time, in reality a date range is continues and has a start and an end.

==========

DurationPicker

There should not be any relation between value and hide-minute, hide-seconds, hide-hours. Now the later options even change the value.

==========

SegmentedButton

Button is changed with item, haven’t looked at the new implementation.
Event selection-change, why not camel case?

==========

Switch

The state is called ‘checked’ everywhere, but the text options are called textOn, textOff

==========

Timeline, TimelineItem

itemName, itemNameClickable, titleText, subtitleText - there are conflicts with the HTMLElement attributes, right?

**Comment by MarcusNotheis** [comment]
A couple of months ago we also had a mail thread about changing opening/closing behaviour of all popups (Dialog, Popover, etc) from an imperative way (`.open()` methods) to a declarative way (`open` attribute).

If I remember correctly our latest proposal was:

**Dialog**:
```html
<ui5-dialog open />
```
(or even follow the [HTMLDialogElement Spec](https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement))

**Popovers**:
```html
<ui5-button id="info">Info</ui5-button>
<ui5-popup for="info" opened></ui5-popup>
```

This would then also be related (and fix) https://github.com/SAP/ui5-webcomponents-react/issues/1101.

**Comment by gmkv** [comment]
The names of the properties which act to prevent/disable some behaviour could be improved. We noted the following:

- Upload collection item: noDelete, noRetry, noTerminate. 
- Popover: noArrow

Please also review/remove the feature "tabs-placement" for Tab container, because it has implications for usability and accessibility.

**Comment by ilhan007** [comment]
## Carousel 

- add `visibleItemsIndexes` public readonly getter returning an array
- add `navigateTo(itemIndex)` public method that navigates to an item (bringing it at the start of the current page if possible)
- make `"selectedIndex"` private

```js

const items = 10;
carousel.itemsPerPageS = 2;

// initially
carousel.visibleItemsIndexes; // [0, 1] - page 0

carousel.navigateTo(1);
carousel.visibleItemsIndexes; // [1, 2] - page 1
```


```

**Comment by ilhan007** [comment]
# Leftovers

## Card
-  **Discussion:** Introduce a `header` slot, remove the `action` slot
- [ ]  **Solution:** 

## ColorPalette
-  **Discussion:** Achieving the sap.m.ColorPalettePopover is not so easy, isn't better to introduce `ColorPalettePopover` component and remove the show-more-colors/show-recent-colors from ColorPalette
- [ ]  **Solution:** 

## Framework
-  **Discussion:** Possibly replace `data-ui5-stable` with `part` (the downside is that we would allow styling from outside)

**Comment by ilhan007** [comment]
Component API Review has been completed.

Moreover, most of the required changes (~60+) are already merged (2 in review at the of writing) and 1 still not started: https://github.com/SAP/ui5-webcomponents/issues/3519

You can track all the breaking changes, that are result from the major API Review here:
https://github.com/SAP/ui5-webcomponents/pulls?q=is%3Apr+is%3Aopen+label%3ABREAKING_CHANGE
