### ISSUE TITLE
Support for Adaptive Card

### ISSUE THREAD

**Issue by jyguyomarch** [SAP/ui5-webcomponents#3116]
I would like the UI5 Adaptive Card concept supported by UI5 Web Component if it is not already: https://ui5.sap.com/test-resources/sap/ui/integration/demokit/cardExplorer/webapp/index.html#/explore/adaptive

Ideally Adaptive Cards would be fully supported with all their different flavors

No alternatives I can think of.

Looking into using Adaptive Card for our SAP Conversational AI Web Client. Example: https://output.jsbin.com/yuzocenida

![image](https://user-images.githubusercontent.com/3885578/113947356-57a65b80-97bf-11eb-84a6-ad8dedcb0b5f.png)

**Comment by ilhan007** [comment]
FYI @nikolay-kolarov

**Comment by ilhan007** [comment]
Hello @jyguyomarch 
could you give us more details regarding the state of the SAP Conversational AI Web Client.

Are you currently using [OpenUI5](https://github.com/SAP/openui5) Controls and the OpenUI5 [Adaptive Card](https://ui5.sap.com/test-resources/sap/ui/integration/demokit/cardExplorer/webapp/index.html#/explore/adaptive), because as far I can see from the [official docs ](https://cai.tools.sap/blog/new-release-of-sap-conversational-ai-enables-seamless-integration-of-chatbots/)states that the Web Client adheres to the SAP Fiori Design guidelines?

**Comment by jyguyomarch** [comment]
Hey @ilhan007,

We are using [UI5 React Web Component](https://github.com/SAP/ui5-webcomponents-react). And yes we are adhering to the SP Fiori Design Guidelines 👍 

BR - JYves

**Comment by ilhan007** [comment]
Hi @jyguyomarch 

I assume you already considered using OpenUI5 Adaptive Card? Could you share why it's not working for you and you need another solution. OpenUI5 and UI5 Web Components (and UI5 Web Components for React) can work together.

Also, if it is possible, could you give us а contact person, responsible for product related questions, so we can get in touch and discuss the requirement.

BR,
ilhan

**Comment by nikolay-kolarov** [comment]
Hi @jyguyomarch,

You can use the integration cards directly by loading a minimalistic UI5 Core.
It is explained here (Consumption in HTML): https://ui5.sap.com/test-resources/sap/ui/integration/demokit/cardExplorer/webapp/index.html#/integrate/usage
And here is a sample: https://jsbin.com/vefolifawi/1/edit?html,output
Could you please give it a try?

Thanks and Best Regards,
Nikolay

**Comment by jyguyomarch** [comment]
Thx @ilhan007 and @nikolay-kolarov. Will try your recommendation. In terms of contact for product requirement discussion I will be the one.

**Comment by ilhan007** [comment]
Hello @jyguyomarch great, let us know in case you need some help.

**Comment by linhuang0405** [comment]
![photo_2022-03-29_14-38-08](https://user-images.githubusercontent.com/15170301/160549057-a125aca9-19ec-413b-a90d-831e4befe48b.jpg)
hello， do you happen this error？

**Comment by nikolay-kolarov** [comment]
Hello @linhuang0405,

Could you please open a new issues, providing all the needed info, so that we can have a look and comment?

Thanks,
Nikolay
