### ISSUE TITLE
ui5-shellbar, empty string value in attribute 'notification-count' should hide the badge

### ISSUE THREAD

**Issue by maltenorstroem** [SAP/ui5-webcomponents#3121]
If show-notifications and notification-count are used in the ui5-shellbar, the notification badge remains even though notification-count is empty.

**To reproduce**
1. `<ui5-shellbar
	id="shellbar"
	primary-title="Corporate Portal"
	secondary-title="secondary title"
	notification-count="99+"
	show-notifications`></ui5-shellbar>
2. set notificaton-count to empty string 
2. badge still remains

**Isolated example**
https://sap.github.io/ui5-webcomponents/playground/components/ShellBar/

**Expected behavior**
If the attribute "notification-count" is empty, the counter badge should no longer be displayed.

![Screenshot 2021-04-09 at 08 00 41](https://user-images.githubusercontent.com/9052672/114135737-f9d25a80-9909-11eb-9aac-03df19f3e5f2.png)

**Context**
- UI5 Web Components version: master

**Affected components**
@ui5/webcomponents-fiori ui5-shellbar

**Priority:** Medium

**Comment by ilhan007** [comment]
Hi @maltenorstroem thanks for reporting, we address the issue with https://github.com/SAP/ui5-webcomponents/pull/3123
