### ISSUE TITLE
SAP logo not loading in Playground

### ISSUE THREAD

**Issue by gmkv** [SAP/ui5-webcomponents#3126]
**Describe the documentation issue**

- [ ] Documentation is unclear
- [ ] Documentation is incorrect
- [ ] Documentation is missing
- [x] Other

**Description of the issue**
The SAP logo at the bottom of the pages is not loading.

![image](https://user-images.githubusercontent.com/22086365/114159292-4e87cc80-992e-11eb-94c2-1e6758153b0b.png)

See [here](https://sap.github.io/ui5-webcomponents/playground/components/Avatar/) or any other page under the Components section in the Playground.

**Comment by himanshu007-creator** [comment]
hi ! i would like to work on this issue.

**Comment by ilhan007** [comment]
Hi @himanshu007-creator

I suggest going through these steps to get the Playground app running locally:

https://github.com/SAP/ui5-webcomponents#project-structure-development-and-build
https://github.com/SAP/ui5-webcomponents#how-to-run-the-project-locally
