### ISSUE TITLE
DateRangePicker switches to current month on first date selection

### ISSUE THREAD

**Issue by codingfabi** [SAP/ui5-webcomponents#3129]
**Describe the bug**
If is select the first date of a date range that differs from the current month with the DateRangePicker, the calendar selection switches back to the current month. This is especially unexpected if the date lays many month in the future or past because I have to navigate to the month I want to select the date from once more. 

It is possible that this is wanted behavior, I would just expect the component to behave differently. So if this is on purpose, just let me know :)

**To reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/DateRangePicker/
2. Open the first Basic DateRangePicker
3. Select a date 2 or 3 months from the current date
4. -> the picker jumps back to the current month ( in my case, april)

**Expected behavior**
I would expect the picker to stay at the month I picked the first date from.

**Context**
- UI5 Web Components version: 1.0.0-rc.8
- OS/Platform: any

**Affected components**
DateRangePicker

**Comment by yanaminkova** [comment]
Hello @SAP/ui5-webcomponents-topic-b,

I am forwarding this issue to you as it is in relation with the DateRangePicker component.

On the first date selection, DateRangePicker switches back to the current month.

Steps to reproduce the behavior:

1. Go to: https://sap.github.io/ui5-webcomponents/playground/components/DateRangePicker/
2. Open the first Basic DateRangePicker
3. Select a date at least one month from the current date -> the picker jumps back to the current month 

Could you have a look?

Regards,
Yana
