### ISSUE TITLE
Input does not accept SPACE in TabContainer

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents#313]
**Describe the bug**
When used within a TabContainer, the Input Component does not accept the `SPACE` and this keystroke is ignored.

**To reproduce**
1. Render a `ui5-input` in a `ui5-tab`:
   ```html
   <ui5-tabcontainer selected-index="0">
    <ui5-tab text="Tab 1">
        <ui5-input value="Input" />
    </ui5-tab>
   </ui5-tabcontainer>
   ```
2. Select the input field and start typing. The space key is ignored.

**Expected behavior**
I would expect that the Input accepts all keystrokes.

**Screenshots**

**Context**
- UI5 Web Components version: `0.9.0`
- OS/Platform: macOS 10.14.4
- Browser *(if relevant)*: Chrome 73.0.3683.103

**Affected components** *(if known)*
`ui5-input` in combination with `ui5-tabcontainer`/`ui5-tab`

**Comment by MapTo0** [comment]
I think @adrian-bobev is currently fixing this

**Comment by adrian-bobev** [comment]
@MarcusNotheis, thanks for the issue. We did a major refactoring of the TabContainer and in next release (0.10.0) this issue will be fixed.
