### ISSUE TITLE
Combobox popover overflows input

### ISSUE THREAD

**Issue by fifoosid** [SAP/ui5-webcomponents#3131]
**To reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/master/playground/components/ComboBox/
2. Section Lazy loading
3. Type "Arg" in the input
4. Select Argentina from the popover using your mouse(The popover closes)
5. Click on the arrow down of the combobox
6. The popover is opened, but it is overflows on top of the input field

**Context**
- UI5 Web Components version 1.0.0-rc.14
- OS/Platform: MACOS
- Browser *(if relevant)*: Chrome

**Organization:** *(if applicable)*

**Priority:** *(optional)* Low

**Comment by ilhan007** [comment]
@SAP/ui5-webcomponents-topic-rl fyi
