### ISSUE TITLE
[BUG][UI5-AvatarGroup]: onClick event fired twice when use keyboard enter

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents#3133]
Hi colleague，

When using AvatarGroup, the onClick event always fired twice by using enter key. Please take a look.

Steps to reproduce:
1.  Go to goalDetails page:  https://github.wdf.sap.corp/pages/xweb/goalmanagementx/app.html?mock#/goal-detail?targetUserId=undefined&templateType=tgm&templateId=583&id=11004

2. Tab to GoalAlignment Aligned Down section:
    
  - Focus on avatar then click enter or space, it will open two tabs.  

  - Focus on overflow button then click enter, it will open two tabs.

![image](https://user-images.githubusercontent.com/78520316/114355347-f0fbb600-9ba1-11eb-8465-d3fd0260cc68.png)

**Business impact:** *(mandatory for "Very High")*
Hign

**Comment by MapTo0** [comment]
Hello @sfsf-xweb-sh 

I could not reproduce the issue outside your application.
Could you please help me improving that jsbin so we can forward to responsible team? 

[jsbin](https://jsbin.com/zuxujaxegi/edit?html,output)

if you want to change the version - change unpkg imports.

Regards,
Martin
Github Dispatcher

**Comment by sfsf-xweb-sh** [comment]
Hi @MapTo0 

You can use console.log instead of window.open to reproduce it. 
BTW, we now use 0.29.13  and this issue is similar to  https://github.com/SAP/ui5-webcomponents/issues/2943.

**Comment by MapTo0** [comment]
Hey @sfsf-xweb-sh 

Thanks for improving the jsbin!

---- Team Pirin ----

The issue is that click event of the AvatarGroup is fired twice.
Once from [_onkeydown](https://github.com/SAP/ui5-webcomponents/blob/master/packages/main/src/AvatarGroup.js#L344-L346) and once from [_onClick](https://github.com/SAP/ui5-webcomponents/blob/master/packages/main/src/AvatarGroup.js#L370-L378)

**The issue can not be reproduced using break points on event handler**

Regards,
Martin
Github Dispatcher

**Comment by sfsf-xweb-sh** [comment]
Hi @PetyaMarkovaBogdanova 
Could it be possible to fix it in next release? There is an overflow  button in avatar group, which will  open a dialog once clicked.  If this issue exist, user is not able to see the dialog because it will be closed immediately.

Thanks a lot

**Comment by GongRichard** [comment]
Hi @PetyaMarkovaBogdanova and @fifoosid ,

Please include this fix in 0.29.16, we need to patch it.

Thanks,
Richard

**Comment by ilhan007** [comment]
Hello @GongRichard it will be part of 0.29.16  within the next 1-2 days

**Comment by ilhan007** [comment]
Hello @GongRichard the fix is included with 0.29.16
