### ISSUE TITLE
[object Object] in subheading

### ISSUE THREAD

**Issue by brampurnot** [SAP/ui5-webcomponents#3134]
Hi all,

I'm trying to embed a component in the subheading of a card. The component is basically to format a number and more information can be found here:
https://www.npmjs.com/package/react-number-format

When I try to do this, I'm seeing [object Object] on the UI. This the example code: 
`
<Card
   subheading={<NumberFormat value={totalProducts} displayType={'scrapd'} thousandSeparator={true} />}
>
`

And here is what I see on the UI:
<img width="376" alt="Screenshot 2021-04-10 at 14 04 19" src="https://user-images.githubusercontent.com/17197669/114269263-561aa480-9a06-11eb-96ba-51fafff94398.png">

Any reason why this is not supported or is this a bug? 

Bram

**Comment by fifoosid** [comment]
Hi @brampurnot 

UI5 Web Components will cast anything that is passed to a string property unless a string is passed, so basically you can't bind an object to a string property.

As much as I can read from the docs of ```react-number-format```, you can bind to the ```value``` property of the object that you already have(the value property is String, so everything should be fine)
