### ISSUE TITLE
A11y - Landmark issue in Flexible column layout with Aria labelledby

### ISSUE THREAD

**Issue by kushalkaranjkar** [SAP/ui5-webcomponents#3135]
**Describe the bug**
We are using FlexibleColumnLayout component in nested fashion in our Successfactors (SAP) application.
We see Axe Dev tool, giving accessibility error about "Landmarks must have a unique role or role/label/title (i.e. accessible name) combination"

**To reproduce**
1. Create Nested FlexibleCoumnLayout . (see attached html source for reference" 

**Isolated example**

**Expected behavior**
Landmark error should not show up for Aria-labelledby for FlexibleColumnLayout div

**Screenshots**
![Landmark_accessibility_issue_AXE_Dev_tool](https://user-images.githubusercontent.com/845448/114472133-9153d980-9ba6-11eb-8206-dac75bd65dee.JPG)

![Nested_flexible_column_layout_Elements](https://user-images.githubusercontent.com/845448/114472160-99ac1480-9ba6-11eb-9f29-85ee8f5b141a.JPG)

**Context**
- OS/Platform: {Windows 10}
- Browser *(if relevant)*: {Google Chrome}

**Affected components** *(if known)*
FlexibleColumnLayout

**Organization:** *(if applicable)*
Successfactors (SAP)

**Priority:** *(optional)* *(Low, Medium, High or Very High)*
Medium

**Business impact:** *(mandatory for "Very High")*

**Comment by MapTo0** [comment]
Hello @kushalkaranjkar ,

Can we clarify what is not unique in this case?
I can not understand the problem.

Regards,
Martin
Github Dispatcher

**Comment by kushalkaranjkar** [comment]
Hi Martin,

Based on image and error shown above in AXE Dev tool, Its complaining about aria-labelledby property. Its complaining about  the highlighted rows 
#mainFlexibleColumnLayout div[aria-labelledby="ui5wc_51-startColumnText"]
#applicationListContainer div[aria-labelledby="ui5wc_52-startColumnText"]

Somehow Axe Dev tool not able to identify difference in the 2 strings here. 
For fixing the issue, suggestion is to change aria-labelledby (aria-label) on line #applicationListContainer div[aria-labelledby="ui5wc_52-startColumnText"].

**Comment by MapTo0** [comment]
Hello @kushalkaranjkar 

That sounds like a bug in the AXE Dev Tool ... I am not sure that we should fix this.
We are implementing the aria standard, not implementing the product for a specific tool.

Is it really a big problem for your product to live with that issue?
In case it causes some major problems we can change it but in this case I think it is not.

Regards,
Martin
Github Dispatcher

**Comment by kushalkaranjkar** [comment]
Hi Martin,

I think the issue occur because the "ui5-hiddenText" element which has id as "aria-labelledby" has same text "First Column" for the #mainFlexibleColumnLayout div[aria-labelledby="ui5wc_51-startColumnText"] & 
#applicationListContainer div[aria-labelledby="ui5wc_52-startColumnText"] . 

I am attaching new image to explain issue properly. 

![aria_issue_element](https://user-images.githubusercontent.com/845448/114763392-95ebcf80-9d17-11eb-8bfd-4b3ae0a14eee.png)

Regards,
Kushal

**Comment by MapTo0** [comment]
Hello,

I am still not really sure why this should be an issue ...
It's the first column of the second FCL. 
What would you expect to be there as text?

Regards,
Martin

**Comment by kushalkaranjkar** [comment]
Hi Martin,

In order to achieve the UI that we want using web-component for react, we have to do this nesting. However, we do not see any  documentation which says not to do this kind of nesting for FCL. 

To solve this issue, Can we have new property in FCL to provide the aria-labelledby or hidden text for screen reader ? 

Regards,
Kushal

**Comment by alexandar-mitsev** [comment]
Hello @kushalkaranjkar ,

Since version v1.0.0-rc.11 there is a property `accessibilityTexts` in [FlexibleColumnLayout](https://sap.github.io/ui5-webcomponents/playground/components/FlexibleColumnLayout/) which allows you to change the `startColumnAccessibleName`. You can do this for the inner nested FCL and this should solve the issue with duplicate landmarks in AXE.

Regards,
Alexandar Mitsev

**Comment by kushalkaranjkar** [comment]
@alexandar-mitsev  @MapTo0, we cannot use this v1.0.0-rc.11 version.  Which Webcomponent release version this Fix has ? 

We use webcomponent for React with below version at this time. 
 "@ui5/webcomponents": "^0.29.7",
 "@ui5/webcomponents-react": "^0.129.7",
 
for ui5/webcomponents Is it part of 0.29.x or 0.31.x ?
