### ISSUE TITLE
Carousel: Behavior improvement

### ISSUE THREAD

**Issue by sleric1024** [SAP/ui5-webcomponents#3136]
**Describe the bug**
Some behavior are not the same as UI5 Carousel control

**Isolated Example**
https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-carousel--default-story

**To Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-carousel--default-story

**Expected behavior**
Expect the same behavior as UI5
1. When mouse move out of the carousel area, the navigation button should be hidden.
2. Padding of navigation button suppose to be the same as UI5 Carousel control
3. Need property support to hide the pagination.
https://sapui5.hana.ondemand.com/#/entity/sap.m.Carousel/sample/sap.m.sample.CarouselWithDisplayOptions

**Screenshots**
![image](https://user-images.githubusercontent.com/5724592/114484824-797b6480-9c3d-11eb-8829-b33628f4cf13.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: Currently Version
`@ui5/webcomponents-react` version: Currently Version
Operating System: Mac OS
Browser: Chrome

**Additional context**
I am from SuccessFactors, and current we are using Carousel to build project feature while the behavior are not the same as UI5 control.

**Comment by ilhan007** [comment]
Hi @sleric1024 could you extract the feature request from the issues and file it as separate GitHub issue
and update the current one keeping the issues only.

Entries 1 and 2 are issues:

1. When mouse move out of the carousel area, the navigation button should be hidden.
2. Padding of navigation button suppose to be the same as UI5 Carousel control

while the 3rd entry is a feature request:

3. Need property support to hide the pagination.
https://sapui5.hana.ondemand.com/#/entity/sap.m.Carousel/sample/sap.m.sample.CarouselWithDisplayOptions

**Comment by ilhan007** [comment]
Hi @SAP/ui5-webcomponents-topic-rd could you check these two issues (the 3rd entry, if not removed, is a feature request and will be filed separately, so focus on these two):

1. When mouse move out of the carousel area, the navigation button should be hidden.
2. Padding of navigation button suppose to be the same as UI5 Carousel control

* You will find details in the issue description

**Comment by sleric1024** [comment]
@ilhan007, thank you for your information.
Please refer to the 3rd one as a feature request https://github.com/SAP/ui5-webcomponents/issues/3158
Best Regards,
Eric

**Comment by ilhan007** [comment]
Hello @sleric1024 The fix is released with 0.29.15
