### ISSUE TITLE
StepInput default value conflicts with placeholder prop

### ISSUE THREAD

**Issue by CPTN021** [SAP/ui5-webcomponents#3139]
**Describe the bug**
The Steplnput component has a value prop which is set to O by default. The component has also a placeholder prop in case no initial value is provided. However because the initial value is always set to O by default, the placeholder becomes obsolete and can never be used/seen. There is also na possibillty to overrider/delete the default value, not even by setting the value prop to "undefined" or "null". 

**To reproduce**
1. Import Steplnput component 
2. Set a placeholder prop 
3. The placeholder text won't be visible, even if there is no initial value is provided 
4. Any attempt to override/delete the default value will be ignored by the component 

**Isolated example**
https://codesandbox.io/s/ui5-webcomponents-forked-s36x0?file=/index.html

**Expected behavior**
Placeholder value should be visible.

**Screenshots**

**Context**
UI5 Web Components version:
- @ui5/webcomponents: 1.0.O-rc.14 
- @ui5/webcomponents-react: 0.15.2 

**Affected components** *(if known)*
StepInput

**Organization:** *(if applicable)*
Web Components React

**Comment by MapTo0** [comment]
Hello @CPTN021 

Unfortunately, that requirement is not following the specification for the component.

https://experience.sap.com/fiori-design-web/step-input/#default-value

Regards,
Martin
(Github Dispatcher)

**Comment by CPTN021** [comment]
Hi @MapTo0 , 

thanks for the quick response. In this casse is there any reason why the placeholder property is provided at all, when it will never be visible in the UI? 

Thanks and best regards,
Behrad

**Comment by MapTo0** [comment]
Hello @CPTN021 

I didn't realise that it is a property.
I think this should be deleted from the component documentation.
I am forwarding to responsible team.

Regards,
Martin

**Comment by tsanislavgatev** [comment]
Hello @CPTN021,

The placeholder is only visible when you manually delete the content from the StepInput. Yes initially it's not visible and the value is automatically set to 0, but if you delete the 0, you will see the placeholder. In this case it works as suggestion.

Regards,
Tsanislav
