### ISSUE TITLE
<ui5-select> - multi select option

### ISSUE THREAD

**Issue by LenaStrifler** [SAP/ui5-webcomponents#314]
**Is your feature request related to a problem? Please describe.**
It would be great to have a web component that provides the possibility to select multiple items from a predefined list. Currently the ui5-select component only supports the selection of one item. 

**Describe the solution you'd like**
I would like to use the ui5-select component to select single or also **multiple** items. I would think of a new boolean property, which enables/disables the multi-select. If multi-select is enabled the change event has to be adjusted in such a way that you get a list of the selected items.

**Describe alternatives you've considered**
Instead of a new boolean property, which enables/disables the multi-select functionality, a "mode" property could maybe be introduced in order to support the requested feature.

**Additional context**
The ui5-list web component already supports single and multiple selection. I would think of a similar functionality for the select.
Please let me know if you have any additional questions/comments regarding my request. :-)

**Comment by ilhan007** [comment]
Hello @LenaStrifle,
thank you for your request.

We have one additional question to your request for enabling multiple selection within the ui5-select component. As the ui5-select shows the selected item text, what do you expect to be displayed when more items are selected - f.e. full items texts, separated by comma or something else?
Could you share your thoughts with us?

Best,
ilhan

**Comment by LenaStrifler** [comment]
Hi @ilhan007, sure I am happy to share my thoughts. I would expect that the texts of the selected items are either displayed separated by comma or e.g. like they are displayed in ui5: 
![image](https://user-images.githubusercontent.com/37621087/55724143-10880300-5a0b-11e9-8b65-5dde5c4f0b30.png)
![image](https://user-images.githubusercontent.com/37621087/55724148-1382f380-5a0b-11e9-9693-b27060b3993c.png)

**Comment by ilhan007** [comment]
Thanks @LenaStrifler , so you want component similar to the ui5 MultiComboBox control.

We will discuss it internally and come back with a statement.

best,
ilhan

**Comment by MapTo0** [comment]
Hey @LenaStrifler,

We are working hard on the implementation of this story. In order to make it better for your consumers we would like to hear some expectations for the API of the component.

We are considering to expose few properties for the initial release of the component and have it enhanced later, therefore any input for the initial features from your side will be appreciated!

Regards,
Martin

**Comment by LenaStrifler** [comment]
Hi @MapTo0,
Thanks a lot for the update, I am really looking forward to the new feature. I am glad to give my input: 
I would expect to have a new boolean property e.g. "multi-select" and another new property that holds the selected items/keys. Additionally I would expect to get an array of selected item**s** via the change event, if multi-select is enabled. 
I hope that's helpful input you were looking for.
Best regards, 
Lena
