### ISSUE TITLE
Missing space in Card with Timeline documentation

### ISSUE THREAD

**Issue by schmelto** [SAP/ui5-webcomponents#3140]
**Describe the bug**

`John Smithcalled` should be `John Smith called` there is a missing space

**To reproduce**
1. Go to 'https://sap.github.io/ui5-webcomponents/playground/components/Card/'
2. Card with Timeline

**Screenshots**
![image](https://user-images.githubusercontent.com/30869493/114544691-4051ed00-9c5b-11eb-8e9b-bd86106a2cc0.png)

**Comment by fifoosid** [comment]
This issue is about the API of the TimeLineItem. It is addressed [in this comment](https://github.com/SAP/ui5-webcomponents/issues/3107#issuecomment-815879872)

**Comment by schmelto** [comment]
Ok. Than I/you can close this issue?

**Comment by fifoosid** [comment]
It is a good idea to close this issue and keep track of it in #3107
