### ISSUE TITLE
Wrong numbering in Angular Getting Started Doc

### ISSUE THREAD

**Issue by schmelto** [SAP/ui5-webcomponents#3141]
**Describe the bug**
Wrong numbering

**To reproduce**
1. Go to 'https://sap.github.io/ui5-webcomponents/playground/tutorials/angular/'

**Screenshots**
![image](https://user-images.githubusercontent.com/30869493/114553175-a6437200-9c65-11eb-924d-82aaf99da00f.png)

**Comment by MapTo0** [comment]
Dear Colleagues,

MDs look good, looks like some problem with docs copy to playground folder.

https://github.com/SAP/ui5-webcomponents/blob/master/docs/Angular-tutorial.md#two-way-data-binding

Regards,
Martin
