### ISSUE TITLE
Retrofit: Some components modify their own styles

### ISSUE THREAD

**Issue by vladitasev** [SAP/ui5-webcomponents#3149]
`Popup.js` (base class), `Dialog`, `Popover`, `ResponsivePopover`, `ColorPicker` and `SegmentedButton` modify their own styles (on the host element). 

This is problematic for the OpenUI5 renderer which doesn't know of these styles and removes them on  re-render.

There are 2 possibilities:
 - modify the renderer
 - modify our components to only set styles on the shadow root top-level element.

Research whether it's possible to set all these styles on the shadow root top level element and not on the host.

**Comment by ilhan007** [comment]
Completed.
