### ISSUE TITLE
[UI5-Wizard][BUG][SF][Urgent] should focus to the first ui5-wizard-tab when wizard is opened

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents#3151]
**Dear colleagues,**
I am from SuccessFactors Web Experience Shanghai team. 

**Bug Description**
Version: 0.29.13
When we open the ui5-wizard, the wizard should focus to the first 

**Expected behavior**
When we open the ui5-wizard, the wizard should focus to the first ui5-wizard-tab automatically.

Reproduce step:
1. go to website: https://github.wdf.sap.corp/pages/xweb/goalmanagementx/app.html?mock#/goal-list
2. click "skip tour button" to close the first time guidance dialog
3. click "Cascade Goal" button to open cascading dialog

You can see that, when the cascading goal dialog is opened, the first ![Screen Shot 2021-04-15 at 11 13 00 AM](https://user-images.githubusercontent.com/78520316/114808989-e593cf00-9ddb-11eb-93fb-0700b4569237.png) can not be focused automatically.

**This issue can also be reproduced in:  https://sap.github.io/ui5-webcomponents/playground/components/Wizard/**
![Screen Shot 2021-04-15 at 11 15 43 AM](https://user-images.githubusercontent.com/78520316/114809183-4b805680-9ddc-11eb-99fe-6a054a795ce9.png)

**Comment by MapTo0** [comment]
Dear @sfsf-xweb-sh 

I am trying to process that issue. Could you please try to add source maps to your applications in order to have them processed faster in the future.

Thank you!
Martin

**Comment by MapTo0** [comment]
Seems like this is related with the `ui5-dialog` conditional rendering on the page.
Could you please add source maps to the application.

Debugging transpiled react + ui5 webcomponents code without source maps is really a pain.
You can also try to reproduce in jsbin or codesandbox

[JSBIN](https://jsbin.com/sewiputoga/1/edit?html,output)

That one is also related https://github.com/SAP/ui5-webcomponents/issues/3152

**Comment by sfsf-xweb-sh** [comment]
Hi @MapTo0 

Thanks for your quick reply
I will send you the email with this repo

**Comment by alexandar-mitsev** [comment]
Hi,

It is very likely that this issue is the same as #3181 related to the busy indicator which is wrapping the ui5-wizard.
Still it is important to have the source maps.

Regards,
Alexandar Mitsev

**Comment by sfsf-xweb-sh** [comment]
Hi @alexandar-mitsev & @MapTo0 

It Is hard to give the source map in public GitHub page.
Can you access our project's repo ?

**Comment by sfsf-xweb-sh** [comment]
Hi @alexandar-mitsev @ilhan007 @fifoosid

You can see this demo link:https://github.wdf.sap.corp/pages/xweb/goalmanagementx/app.html?mock#/goal-list
I have submitted the source-map to it

**Comment by fifoosid** [comment]
Hi @sfsf-xweb-sh 

This issue is related to the application logic, which is overwriting the default behaviour of the dialog.

You are manually focusing the Select All checkbox, which leads to moving the initial focus from the first focusable element(the wizard step) to the Select All checkbox.

If you want to stick with the default behaviour, you should remove the manual focusing of that checkbox

**Comment by Milo-Shen** [comment]
Hi @fifoosid 
I will try it, thanks
