### ISSUE TITLE
Carousel: Need property support to hide the pagination

### ISSUE THREAD

**Issue by sleric1024** [SAP/ui5-webcomponents#3158]
**Is your feature request related to a problem? Please describe.**
Feature request separated from issue https://github.com/SAP/ui5-webcomponents/issues/3136 

**Describe the solution you'd like**
Need property to support hiding the pagination indicator.

![image](https://user-images.githubusercontent.com/5724592/115025128-8cb75a00-9ef3-11eb-8f99-d043e1a238ed.png)

Feature Request from SuccessFactors.

**Comment by MapTo0** [comment]
Dear Colleagues,

This is a feature request for adding `showPageIndicator` like property to the carousel.

Regards,
Martin
Github Dispatcher

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-rd

 this is a feature request for an API to  show/hide the page indicator of the Carousel. We would like to display it by default,  so we would have to name the property `hidePageIndicator`.
