### ISSUE TITLE
Expose shadow-dom  using parts

### ISSUE THREAD

**Issue by Berhell** [SAP/ui5-webcomponents#3159]
Hello 👋

It would be very helpful if you could expose the shadow-dom of the components using `parts`, so one could fine tune some css properties

Thank you ✌️

**Comment by fifoosid** [comment]
Hi @Berhell 

We have exposed some CSS parts that make sense to us. If you have some specific parts that you need, please attach them in this issue, so that we can take a look and decide if we are going to implement them. In the meantime, you can use the ```addCustomCSS``` method as described above

**Comment by Berhell** [comment]
The `addCustomCSS(tag, css)` would be enough for now. Thanks for the tip 😉
