### ISSUE TITLE
ui5-label: ui5-label with required symbol is truncated in Safari

### ISSUE THREAD

**Issue by zhangliangyi** [SAP/ui5-webcomponents#3164]
**Describe the bug**
In Safari, the ui5-label with required symbol is truncated.

**To reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/Label/ via Chrome/Edge, check `Required Label` section.
2. Go to https://sap.github.io/ui5-webcomponents/playground/components/Label/ via Safari, check `Required Label` section.
3. In Safari, the label text is truncated but not in Chrome/Edge.

**Expected behavior**
The text should not be truncated in Safari.

**Context**
- UI5 Web Components version: 0.31.5
- OS/Platform: MacOS
- Browser *(if relevant)*: Safari 14.0.3
- Other information: N/A

**Affected components** ui5-label

**Organization:** SF

**Priority:** *(optional)* Medium

Setting priority would indicate the importance of the issue
and would help the process of dispatching and processing.

To set the appropriate priority, you need to consider the impact
and if the issue:
- Breaks entire application or system - High and Very High
- Is accessibility one (Screen Reader, Keyboard Handling) - Medium and High
- Is functional one and makes a single component unusable - Medium and High
- Is visual, styling one - Low and Medium

Note: the priority would be re-evaluated by the issue processors, according to the project internal criterias

**Business impact:** *(mandatory for "Very High")*

**Comment by alexandar-mitsev** [comment]
Hello @SAP/ui5-webcomponents-topic-rd ,

The issue is reproducible on Safari on Mac. When the label is required - the text gets truncated. See attached screenshot.
![LabelTruncatedSafari](https://user-images.githubusercontent.com/2347042/115413213-aad7cf80-a1fd-11eb-9853-7548ae3f0446.png)

Regards,
Alexandar Mitsev

**Comment by zhangliangyi** [comment]
@fifoosid 
Seems the fix is not involved in the latest 0.31.8 release. Please add this in next 0.31.x release.

**Comment by ilhan007** [comment]
Hello @zhangliangyi sorry about that, now the fix has been downported and will be released next week
