### ISSUE TITLE
[UI5-CheckBox][Bug][SF][Urgent] The focus function of ui5-checkbox does not always work

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents#3171]
**Dear colleagues,**
I am from SuccessFactors Web Experience Shanghai team.

**Bug Description**
Version: 0.29.13
When I call the focus function of ui5-checkbox, it does not always work. Sometimes the ui5-checkbox can be focused, sometimes can't.

**Expected behavior**
If the focus function be called, the ui5-checkbox can always be focused.
I will send the email to give the website to reproduce this issue

![2021-04-21_10-03-08 (1)](https://user-images.githubusercontent.com/78520316/115486547-76a9f080-a289-11eb-89b9-4984dae61e04.gif)

**Comment by fifoosid** [comment]
Hi @sfsf-xweb-sh

I was not able to reproduce the issue in a standalone sample. It works every time: https://codesandbox.io/s/ui5-webcomponents-forked-775ny?file=/index.html

It seems to me that there is some application logic that prevents the checkbox from receiving the focus. Are you sure that when ```checkbox.focus()``` is invoked, the busyindicator is not blocking the focus?

**Comment by sfsf-xweb-sh** [comment]
Hi @fifoosid 
I am not sure whether the busyindicator will blocking the focus. 
But I called the `checkbox.focus() ` function after the list is loaded in which time busyindicator's status was not loading. 
So I think the busy indicator should not block the focus. Did I unstop right ?

**Comment by fifoosid** [comment]
Hi @sfsf-xweb-sh 

Can you provide an isolated example via [CodeSandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html), recreating you scenario, so that we can debug it.

**Comment by sfsf-xweb-sh** [comment]
Hi @fifoosid 
You can see this demo link:https://github.wdf.sap.corp/pages/xweb/goalmanagementx/app.html?mock#/goal-list
I have submitted the source-map to it

**Comment by fifoosid** [comment]
Hi @sfsf-xweb-sh 

As we agreed on our meeting last week, we will need a [isolated sample in CodeSandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html) in order to continue working on this issue.

**Comment by gmkv** [comment]
Hi @sfsf-xweb-sh 
This issue has been inactive for quite a while. I am closing it.
