### ISSUE TITLE
ui5-dialog focus issues with ui5-busyindicator

### ISSUE THREAD

**Issue by ee92** [SAP/ui5-webcomponents#3181]
**Describe the bug**
If a ui5-dialog has a ui5-button inside it, upon opening, the focus will go to the button. However if the button is wrapped in a ui5-busyindicator, the button will not get focus. Additionally, this will allow the focus to go outside the dialog.

**To reproduce**
1. Go to https://codesandbox.io/s/ui5-webcomponents-forked-p1zqo
2. open the dialog an notice the buttons are not initially focused
3. click one of the buttons to force the focus on it
4. tab through the buttons and notice the focus is allowed to leave the dialog
5. remove the ui5-busyindicator wrapper and reload the sandbox to see that this behavior can not be reproduced without it.

**Expected behavior**
The focus should go to the ui5-button even if it is inside a ui5-busyindicator. Also the focus should stay trapped inside the dialog and not be allowed to leave.

**Context**
- UI5 Web Components version 0.29.13

**Affected components**
ui5-dialog
ui5-busyindicator

**Organization:**
SuccessFactors

**Priority:**
Medium

Thanks for taking a look

**Comment by alexandar-mitsev** [comment]
Hello @SAP/ui5-webcomponents-topic-rd ,

This is a reproducible issue with busy indicator and dialog.
Most likely the same issue causes the problem for #3152 and #3151.

Regards,
Alexandar Mitsev

**Comment by ilhan007** [comment]
The fix is released with 0.29.15
