### ISSUE TITLE
Select Dialog with Search Bar

### ISSUE THREAD

**Issue by jcailan** [SAP/ui5-webcomponents#3190]
**Is your feature request related to a problem? Please describe.**
I'm looking for SelectDialog equivalent from SAPUI5.
https://sapui5.hana.ondemand.com/#/entity/sap.m.SelectDialog/sample/sap.m.sample.SelectDialog

**Describe the solution you'd like**
A SelectDialog inside a popover with a search field.

![image](https://user-images.githubusercontent.com/27951983/116207480-84241680-a772-11eb-9b43-7e9e353587b0.png)

**Describe alternatives you've considered**
If there's none, then I will be forced to implement the component on my own.

**Additional context**
I'm working on an SAP product that relies heavily on Web Component technology and our primary choice of library is UI5 web components.

**Comment by ilhan007** [comment]
Hello @jcailan 

thanks for your interest in using the UI5 Web Components.

First of all, could you provide more details regarding the SAP product you mentioned?

Regarding the request, we will internally discuss it, but on first glance we would rather suggest combining the Dialog, Input, List and Button components to build the Select Dialog.

**Comment by jcailan** [comment]
Hi @ilhan007 

Thanks for the quick response!

I'm working with Business Network Collaboration (BNC) team, and on the high level, we are working on a Geospatial Visualization solution where customers have the flexibility to use their existing Map Service provider and still get the SAP functionalities out of the box (with minimal customizing and/or development on their side). One of the key enablers for UI consistency of the solution is brought by UI5 web components.

As of now, we are working on a prototype using Mapbox as the Map Service with SAP business functionalities on top which is backed by UI5 web components. And there are a couple more Map Service to support that is planned in the road map.

I guess we will need to build our own SelectDialog for now as you have suggested. But if there's a plan for this component to be available, we would be happy to switch to the standard solution.

**Comment by alexandar-mitsev** [comment]
Hi @jcailan ,

After further discussion we think it is good if the building of such a select dialog remains in your hands.
Since it is a straight forward combination of few other controls - input, list and buttons, we don't see real benefit of providing a dedicated web component for this. At the same time you get all the flexibility which you may need.

So for now we don't plan the implementation of this web component.

If you have already succeeded in building it for you - that is good. But if you did struggle to achieve it or if you didn't succeed at all - you can reopen the issue and let us know.

Best Regards,
Alexandar Mitsev

**Comment by jkra** [comment]
a select component with search bar for filtering the available options after each new character -> that is what is needed ... it would be great, if ui5-webcomponents could provide this ... :)

**Comment by alexandar-mitsev** [comment]
Hi @jkra ,

We have the ComboBox component which has this feature. You can check it at https://sap.github.io/ui5-webcomponents/nightly/components/ComboBox/

**Comment by jkra** [comment]
> Hi [@jkra](https://github.com/jkra) ,
> 
> We have the ComboBox component which has this feature. You can check it at https://sap.github.io/ui5-webcomponents/nightly/components/ComboBox/

great ... I did not realize that... thanks!
