### ISSUE TITLE
ShellBar: VD issues

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents#3199]
**Describe the bug**
ShelBar's Menu Button:

1. MenuButton – the distance between text and arrow should be 6px, not 8px as it is now

2. ManuButton – Since ShellBar should always stick to Cozy mode, its inner height should be 36px(1.625rem) now it is 26px (COMPACT).

3. ManuButton - It should have 44px / 2.75rem touch area. With the current padding of 0.25rem top and bottom, the menu button height would be 2.25rem.

**Tester**
@PetyaMarkovaBogdanova 

**Responsible Team**
@SAP/ui5-webcomponents-topic-p 
```

**Comment by nnaydenow** [comment]
Hi @ilhan007,

Only first reported issue is fixed.

Other two issues are not breaking visual representation and control behavior. They have to be marked as refactoring which seems to be bigger than expected. We will make it in the future .

**Comment by ilhan007** [comment]
Hi @nnaydenow  I see

you can see the newly created issue:
https://github.com/SAP/ui5-webcomponents/issues/3289
