### ISSUE TITLE
Calendar: wrong month view in multi-selection mode

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents#3202]
**Describe the bug**
Every month with at least 1 selected day is displayed as selected within the "Month" view of the Calendar in multi-selection mode. This differs from the Calendar in SAPUI5 - check and fix the component if needed.

**To reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/master/playground/components/Calendar/
2. Use the "Calendar with Selection Mode Multiple" calendar
2. Select a day in the current month, go to another month and make the same. 
3. Go to the month picker - every month with at least 1 selected day is selected. Not the case in SAPUI5.

**Version**
master

**Responsible Team**
@SAP/ui5-webcomponents-topic-b

**Comment by tsanislavgatev** [comment]
Hello,

Currently there is a discussion if this is the expected behavior and if we should update the openui5 calendar. In upcoming meeting this question will be discussed with designers and we will update the issue.

Best Regards,
Tsanislav

**Comment by tsanislavgatev** [comment]
Hello,

I spoke with our design colleagues and they said that the correct behaviour is the one in the WebComponents project. Similar issue will be open about the openui5 framework to align the behaviour.

Best Regards,
Tsanislav
