### ISSUE TITLE
Cannot read property 'getHours' of null

### ISSUE THREAD

**Issue by uweku** [SAP/ui5-webcomponents#3204]
**Describe the bug**
"Cannot read property 'getHours' of null" is raised by DateTimePicker

**To reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/DateTimePicker/
2. Go to section "DateTimePicker with format-pattern"
3. Clear & enter "123" into first input field (invalid timestamp)
4. Pick a valid time stamp from date picker

**Expected behavior**
Manual timestamp selection shall not fail

**Screenshots**
![image](https://user-images.githubusercontent.com/4712909/116793882-c5495d00-aac9-11eb-8702-da73ae33518d.png)

**Context**
- Chrome Browser
- current version of https://sap.github.io/ui5-webcomponents/playground/components/DateTimePicker/

**Comment by fifoosid** [comment]
Hello @SAP/ui5-webcomponents-topic-b,

The issue can be reproduced in the playground & with the latest master version.
