### ISSUE TITLE
Select All / Deselect All checkbox on `List`

### ISSUE THREAD

**Issue by jcailan** [SAP/ui5-webcomponents#3215]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like have a select all / deselect all checkbox functionality on `List` component (on the left side of column header) so that it is easy to work with several line items on a `List`. See screenshot below:

![image](https://user-images.githubusercontent.com/27951983/117742674-d0be2600-b237-11eb-99b0-64d1746b6abe.png)

**Describe alternatives you've considered**
None as of the moment

**Additional context**
This feature request is similar to the functionality found on [Grid Table](https://sapui5.hana.ondemand.com/#/entity/sap.ui.table.Table/sample/sap.ui.table.sample.Selection) in SAP UI5

Thanks and regards,
Jhodel

**Comment by petyabegovska** [comment]
Hi @jcailan,

Is the feature still valid or you implemented it with additional list item? 

Best regards,
Petya
