### ISSUE TITLE
How to disable focus trap for a  dialog? 

### ISSUE THREAD

**Issue by vran848115** [SAP/ui5-webcomponents#3216]
We are using openui5/sapui5 dialog controls and they have inherited focus trap.
Our requirement is to disable the focus trap of dialog and let the focus move to browser controls on last Tab of the tab-able element of the dialog.

We have made background screen elements  non-tabable by setting tabindex=-1 on all the lements having tabindex attribute assigned to them.

I know that is against the standard but still this is the requirement as per our internal accessibility team.
Please help/advise.

**Comment by vran848115** [comment]
I am attaching my dummy code repo.
Focus trap on fragment as dialog triggered on + button click.
[CDM_SItePlant-2.zip](https://github.com/SAP/ui5-webcomponents/files/6458941/CDM_SItePlant-2.zip)

**Comment by niyap** [comment]
Hello @vran848115 ,

I am a little bit confused. In the attachment provided, there is no UI5 Web Components used. The sample shows the usage of OpenUI5. If you want to report an issue for OpenUI5, that is not the correct repository. Here is a link: https://github.com/SAP/openui5/issues 
If I am not right and you want to report an issue regarding the UI5 Web Components, please provide us a relevant sample showing your use case.

Kind Regards,
Niya
