### ISSUE TITLE
CheckBox: support "Success" state

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents#3239]
**Is your feature request related to a problem? Please describe.**
Currently the "Success" state is missing and we would like to have it.

**Describe the solution you'd like**
New enum entry "Success", implemented by the FIori 3 design. Use the sap.m.CheckBox for reference.

**Comment by nnaydenow** [comment]
Hi @ilhan007,

Can we close that issue since it is the same as #3198?

**Comment by ilhan007** [comment]
Yes, sorry it's a duplicate
