### ISSUE TITLE
Wizard component missing title

### ISSUE THREAD

**Issue by SVendittelli** [SAP/ui5-webcomponents#3250]
**Is your feature request related to a problem? Please describe.**
According to the Fiori design guidelines, the [Wizard floorplan](https://experience.sap.com/fiori-design-web/wizard/) should have a title above the wizard steps.

**Describe the solution you'd like**
The ability to _optionally_ add a title above the steps of the wizard in the `ui5-wizard`.

**Describe alternatives you've considered**
I have tried putting a title component above the wizard but then padding and backgrounds need to be handled manually.

**Comment by ilhan007** [comment]
The Wizard Floorplan is not the same as Wizard component, in the floorplan you see a header bar at the top, but it does not mean the Wizard should have that as well. The Floorplan suggests combining certain components to a bigger logical whole. One thing you try is adding a container above the Wizard with the available Title web component inside to display a title?

**Comment by ilhan007** [comment]
Hello @SVendittelli 

Take a look of this sample:
https://codesandbox.io/s/ui5-webcomponents-forked-v0jcm?file=/index.html


Basically
```html
<section>
       <header class="header">
              <ui5-title>New Sales Order</ui5-title>
       </header>

      <ui5-wizard></ui5-wizard>
</section>
```
```css
 .header {
        padding: 1rem;
        background-color: var(--sapObjectHeader_Background);
}
```

**Comment by SVendittelli** [comment]
Thanks @ilhan007, I am in fact using the `ui5-webcomponents-react` wrapper but I have implemented something similar to your suggestion with that. While not ideal it will do for now, thanks for your help!
