### ISSUE TITLE
Calendars to support secondary calendar type

### ISSUE THREAD

**Issue by allen138** [SAP/ui5-webcomponents#3264]
**Is your feature request related to a problem? Please describe.**
This enhancement will help to improve support for Islamic Calendars. Some dates throughout an application might be in Gregorian. For a user who prefers an Islamic Calendar, it might be confusing which date is correct. Having a Calendar with a Primary type=Islamic and a Secondary type=Gregorian will help the user to see the correlation between the two dates. 

**Describe the solution you'd like**
This type of enhancement is currently available with sap.ui.unified.Calendar. Please see: [sapui5 sample](https://sapui5.hana.ondemand.com/#/entity/sap.ui.unified.Calendar/sample/sap.ui.unified.sample.CalendarCalendarType) It would be nice to have this same feature be available for the ui5-calendar as well as the ui5-date-picker

**Additional context**
Please reach out via slack or comment below if you have any question. 
Thanks,
Allen

**Comment by ilhan007** [comment]
FYI @DMihaylova: you can find this feature request in the Planning section

**Comment by fifoosid** [comment]
The feature request is implemented

**Comment by petyabegovska** [comment]
The feature is not available for ui5-date-picker yet so I reopen the issue until we have it there.

**Comment by fifoosid** [comment]
Thanks for the headsup @petyabegovska. Now both ```ui5-calendar``` & ```ui5-datepicker``` expose the ```secondaryCalendarType``` property
