### ISSUE TITLE
ShellBar: Fiori 3 visual alignment

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents#3289]
**Describe the bug**
Some visual deviations from SAP Fiori 3 spec have been discovered in regards to the Menu Button size and touch area,
that might require some internal refactoring and enhancement of the DOM structure.

- ManuButton – Since ShellBar should always stick to Cozy mode, its inner height should be 36px(1.625rem) now it is 26px (COMPACT).

- ManuButton - It should have 44px / 2.75rem touch area. With the current padding: 0.25rem top and bottom, the menu button height would be 2.25rem.

**Tester**
@PetyaMarkovaBogdanova 

**Responsible Team**
@SAP/ui5-webcomponents-topic-p 
```

**Comment by nnaydenow** [comment]
Seems to be fixed meanwhile. Currently issues are not reproducibl.e
