### ISSUE TITLE
[ui5-table][SF][Urgent] Support sorting function for table column

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents#3303]
**Dear colleagues,**
I am from SuccessFactors Web Experience Shanghai team.

**Feature request**
Add Sorting function to ui5-table column
You can see this link: https://sapui5.hana.ondemand.com/#/entity/sap.ui.table.Table/sample/sap.ui.table.sample.Sorting

**Comment by tonyh1982** [comment]
We need this for our project as well. Should be a basic feature of a table, being able to sort by a single column by using the column header.

Regards,
Tony

**Comment by sfsf-xweb-sh** [comment]
Hi @tsanislavgatev 

Is there any progress about this feature request ?

**Comment by ilhan007** [comment]
Hi @sfsf-xweb-sh no, there is no progress. 

The feature you are pointing is part of the sap.ui.table.Table control, while our ui5-table web component is equivalent to the sap.m.Table. If you check the UX of the sap.m.Table control, you will notice that the sorting concept is not carried out by an icon in the columns header + popover, but completely outside, via settings dialog: 
https://experience.sap.com/fiori-design-web/responsive-table/#view-settings-sort-filter-and-group
https://openui5nightly.hana.ondemand.com/entity/sap.m.Table/sample/sap.m.sample.TableViewSettingsDialog

Providing a sorting icon will contradict the specs, this we can't do.


If you take a look of this example, the sorting is done completely outside the table, even the buttons are separate `div` placed over the `ui5-table`:
https://ilhan007.github.io/ui5con-app/#/detail

<img width="986" alt="Screenshot 2021-06-02 at 09 17 20" src="https://user-images.githubusercontent.com/15702139/120432963-58084080-c383-11eb-8d7a-4165da146f95.png">

What do you think about that?

**Comment by sfsf-xweb-sh** [comment]
Hi @ilhan007 

Thanks you for your help and great demo
I will discuss with PM about your suggestion
