### ISSUE TITLE
[ui5-table][SF][Urgent - Within 2 Weeks] Support sorting dialog for table

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents#3304]
**Dear colleagues,**
Support sorting dialog for table

![Screen Shot 2021-05-25 at 9 59 18 AM](https://user-images.githubusercontent.com/78520316/119428723-06870280-bd40-11eb-918a-c4a6f0c815df.png)

**Comment by ilhan007** [comment]
Hello @sfsf-xweb-sh 

I think this is relatively easy to implement such a dialog with the Dialog, RadioButton and Button web components. Do you have any concerns doing it manually so to say? We can also come up with a sample if would be helpful for you.

Best,
ilhan

**Comment by tonyh1982** [comment]
Hi ilhan,

downside of your approach is that everybody who needs a sorting dialog in a table (quite some usages) would be required to build an own dialog with potential slightly different styling or behavior. As we need a table sorting functionality for our project as well, I would be happy to have this feature available.

Building the dialog on our own would be the last option - an example is always helpful in this case.

Regards,
Tony

**Comment by sfsf-xweb-sh** [comment]
Hi @ilhan007 

I agreed with @tonyh1982.

This feature is very common in our development, if it can be provided as a common component, every one can benefit from it.

Thanks you for your support

**Comment by sfsf-xweb-sh** [comment]
Hi @ilhan007 
Thanks you for your help

1. The OpenUI5 equivalent is indeed the ViewSettingsDialog
2. filtering and grouping is not needed for the time being
3. The example you given me works for me

**Can you extract the given example as a individual component for us ? so that it can be reused by others**

**Comment by ilhan007** [comment]
Hello @sfsf-xweb-sh 
we decided to implement a sorting dialog as a web component.
I already spoke with the team that is going to implement the component and based on their capacity and commitments it could not be delivered in a couple of weeks. **Raw timeline would be 10 weeks from now** as the development could not be started immediately due to other already committed items and maintenance load.

Do you think the [temporary solution](https://codesandbox.io/s/ui5-webcomponents-forked-mn380?file=/index.html) that I provided earlier  could be used until we provide a web component.

BR,
ilhan

**Comment by ilhan007** [comment]
Scope: Sorting functionality of ViewSettingsDialog

Structure
- Predefined header (based on the design - the title is on the left I think, while the Dialog's header text is displayed in the center - should be checked)
- List web component in the Dialog's content for Sort Order (the list has selection-change to keep track on the user selection)
- List web component in the DIalog's content for Sort By (the list has selection-change to keep track on the user selection)
- Predefined footer (two buttons right aligned - Ok and Cancel)

API
Event for pressing Cancel
Event for pressing OK (+ details what is selected by the user in Sort By/Order lists)

**Comment by sfsf-xweb-sh** [comment]
Hi @ilhan007 

> Do you think the temporary solution that I provided earlier could be used until we provide a web component.
Yes, this could be used.

For APIs:
I have some another feature requests
For text ( Sort, Sort Order, Sort By, Sort, Cancel ), we want these text can be customized by developer to meet the need with i18n. We want 5 parameters to customize these texts which have colored red in the below screenshot

![image](https://user-images.githubusercontent.com/78520316/122351592-d9b1be00-cf80-11eb-8840-d8f7ec91cc77.png)

**Comment by sfsf-xweb-sh** [comment]
Hi @ilhan007 

We want to add a reset button to this component,
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/78520316/122518352-aab05080-d043-11eb-9d08-42a83d163e12.png)

**Comment by DMihaylova** [comment]
Hello @sfsf-xweb-sh,

We planned to deliver the sorting functionality and the target is within the next month.
The scope includes both lists (Sort Order/Sort By), OK/Cancel buttons, Reset. The customisable text will not be part of it.

Regards,
Diana

**Comment by ilhan007** [comment]
Hello @sfsf-xweb-sh npm the component will be available in 0.31.15 (9-10 Aug)

**Comment by ilhan007** [comment]
Hello @sfsf-xweb-sh the component has been released with 0.31.15
