### ISSUE TITLE
Module not found: Error: Can't resolve '@ui5/webcomponents/dist/MultiComboBox'

### ISSUE THREAD

**Issue by harishkrishnan24** [SAP/ui5-webcomponents#3305]
### **Bug Description**
I have a angular shared library that is compiled using gulp-typescript. When I try to import MultiComboBox as given in documentation getting the error **Module not found: Error: Can't resolve '@ui5/webcomponents/dist/MultiComboBox'**

Is there any workarounds for this ?

**Comment by pskelin** [comment]
Can you check whether you have `@ui5/webcomponents` as a dependency? Did you do
`npm install @ui5/webcomponents --save` (or yarn equivalent)? You should have `@ui5/webcomponents` both in `package.json` and in the `node_modules` folder. Please verify this and reopen the issue if this is done and you still get the error.

**Comment by harishkrishnan24** [comment]
Yes, I have done and also I could see the folder in the npm_modules directory. I am using gulp to build. I have attached the config for reference.


`const gulp = require('gulp'),
    sass = require('node-sass'),
    runSequence = require('run-sequence'),
    sourcemaps = require('gulp-sourcemaps'),
    tsc = require('gulp-typescript'),
    embedTemplates = require('gulp-inline-ng2-template');

function sassImporter(url, file, done) {
    if (url.indexOf('~com.sap.cre.core.fiori') === 0) {
        return done({ file: __dirname + '/node_modules/' + url.substr(1,url.length) });
    } else {
        return done({ file: url });
    }
}

function styleProcessor(path, ext, file, callback) {
    sass.render({
        data: file,
        importer: sassImporter
    }, (error, processed) => {
        if (error) {
            callback(error, null);
        } else {
            const css = processed.css.toString();
            callback(null, css);
        }
    });
}

// Typescript compilation including sourcemaps and template embedding
gulp.task('tsc', gulp.series(function() {
    // loading typings file
    const tsProject = tsc.createProject('tsconfig.json');

    return gulp.src(['src/**/*.ts', '!src/**/*.spec.ts'])
        .pipe(embedTemplates({
            base: '/src',
            useRelativePaths: true,
            styleProcessor
        }))
        .pipe(tsProject())
        .once('error', function () { this.once('finish', () => process.exit(1)); })
        .pipe(sourcemaps.init())
        .pipe(sourcemaps.write('./'))
        .pipe(gulp.dest('dist'));
}));

// Build steps
gulp.task('build', gulp.series('tsc'));`

**Comment by pskelin** [comment]
Can you check your other imports? Not sure if this is the fault, but technically, you should always add a `.js` file extension in the imports. Some build tools seem to check for existing extensions, so this is something to check. Just compare with your other imports and try it like this:
`@ui5/webcomponents/dist/MultiComboBox.js`

**Comment by harishkrishnan24** [comment]
@pskelin I have tried that as well and it shows the same error. But when I give path from node_modules/@ui5 it is picking up, but again the components inside use similar imports starting with @ui5/* and hence it fails again saying it could not find.

But we have other libraries like d3 installed and have imported with syntax import * as d3 from 'd3' and it seems to work fine. Also, to further note, all other external libraries have typings file.

And I am not sure whether the issue is caused by the side-effect import style, as it tries to execute code and we are trying to use this through npm install as shared library in another Angular project.

**Comment by harishkrishnan24** [comment]
@pskelin never mind. I think the issue might be in the way we manage the dependencies. Thanks for your help. Will close the issue
