### ISSUE TITLE
Make UI5 Web Components more cypress-friendly

### ISSUE THREAD

**Issue by vladitasev** [SAP/ui5-webcomponents#3311]
To avoid the "ResizeObserver loop limit exceeded" error when using Cypress, consider this solution:
https://stackoverflow.com/questions/49384120/resizeobserver-loop-limit-exceeded/58701523#58701523

for both UI5 Web Components and Tab Shellbar.

**Comment by ilhan007** [comment]
This workaround has been recommended by the Cypress project and for now at least seems to be sufficient without making fixes on our side. If the issue continue emerging, we can think for a solution once again.

```js
const resizeObserverLoopErrRe = /^ResizeObserver loop limit exceeded/
 
Cypress.on('uncaught:exception', (err) => {
  if (resizeObserverLoopErrRe.test(err.message)) {
    // returning false here prevents Cypress from
    // failing the test
    return false
  }
})
```
