### ISSUE TITLE
ShellBar: Web component processed too many times this task, max allowed is: 10

### ISSUE THREAD

**Issue by JackieWei** [SAP/ui5-webcomponents#3312]
**Describe the bug**
This is a random bug, which also hard to reproduce. The general idea is: when you leave the tab for a long time(before it auto redirect to any other page, in our case if session expired, it will auto redirect to login), and you will suddenly get a "Web component processed too many times this task" error, and because of the error, many button actions are not working after that. You can take a look at the screen shot and stack trace, I guess it's caused by resize too many times in one render cycle.

**Isolated Example**
NO

**To Reproduce**
1. Have a ShellBar instance
//2. Leave page idle for a relative long time - No need
//3. Switch back and page is freezed, many button/expand icon not working - No Need
2. Just resize the page (view port) like crazy, may be using a devtool panel to help do resize,
3. Open dev tools, you will find following
I will attach a video for you in comments.
RenderQueue.js:61 Uncaught Error: Web component processed too many times this task, max allowed is: 10
    at RenderQueue.process (RenderQueue.js:61)
    at Render.js:60
process @ RenderQueue.js:61
(anonymous) @ Render.js:60
requestAnimationFrame (async)
(anonymous) @ Render.js:57
scheduleRenderTask @ Render.js:56
renderDeferred @ Render.js:23
_invalidate @ UI5Element.js:44
set @ UI5Element.js:955
_handleBarBreakpoints @ ShellBar.js:578
_overflowActions @ ShellBar.js:646
ShellBar._handleResize @ ShellBar.js:450
async function (async)
ShellBar._handleResize @ ShellBar.js:447
(anonymous) @ ResizeHandler.js:9
(anonymous) @ ResizeHandler.js:9
(anonymous) @ ResizeHandler.js:7

**Expected behavior**
Idle or any other condition will not caused processed too many times bug.

**Screenshots**

**UI5 Web Components for React Information**
`@ui5/webcomponents` version:1.0.0-rc.14
`@ui5/webcomponents-react` version:0.15.4
Operating System: Mac OS Big Sur, 11.3.4
Browser: Chrome 90.0.4430.212 (Official Build) (x86_64)

**Additional context**
The stack trace starts from Resize Handler.js
const getResizeObserver = () => {
  if (!resizeObserver) {
    resizeObserver = new window.ResizeObserver(entries => {
      entries.forEach(entry => {
        const callbacks = observedElements.get(entry.target);
        callbacks.forEach(callback => callback());
      });
    });
  }

  return resizeObserver;
};

What if the resize event is hang for serval times, as this browser tab process not in frontend of user, and user switch back to the tab, is it possible user will get serveal times of resize in one time, and then cause the render too many times error?

And then the stack trace goes to handleResize of ShellBar, ShellBar.js
   this._handleResize = async event => {
      await this._getResponsivePopover();
      this.overflowPopover.close();

      this._overflowActions();
    };
And then it goes to _overflowActions,
and then it goes to _handleBarBreakpoints
and then it goes to UI5Element to call the render queue

The only explain for me now is that line 9 in ResizeHandler.js
callbacks.forEach(callback => callback());
This have too much same callback

**Comment by JackieWei** [comment]
@MarcusNotheis  Thanks you. And for UI5 Web Components Colleagues, I can reproduce it now. Just resize the window like crazy, it will show, every time.
![image](https://user-images.githubusercontent.com/437693/119642806-b1391700-be4d-11eb-9efe-b0aa55ec6b2e.png)

**Comment by JackieWei** [comment]
Please refer to following video to see the reproduce steps. And basically I think it caused by resize to many times and handle it in one deal.

https://user-images.githubusercontent.com/437693/119643778-bf3b6780-be4e-11eb-9867-cf679b62ce93.mp4

**Comment by JackieWei** [comment]
And more of the stack trace, I think this maybe you have some knowledge already on the limit.
![Uploading image.png…]()

**Comment by nnaydenow** [comment]
Hi @JackieWei ,

Internal item was created with reference: 5272. We will take a look at the issue.

Regards,
Nayden

**Comment by dobrinyonkov** [comment]
duplicated: #3022
