### ISSUE TITLE
[ui5-table] support grouping by table column content

### ISSUE THREAD

**Issue by tonyh1982** [SAP/ui5-webcomponents#3319]
### **Feature Request Description**
We are currently developing a new SAP angular app and picked UI5 WC to build it. Therefore, we need to be able to group the table rows by column content.

### **Proposed Solution**
Similar to what is available for Responsive Table of Fiori Design Guideline. Would be ok without a dialog to select from as first version...should be able to set a column to group for in the coding as first step.

### **Additional Context**
Example from: https://experience.sap.com/fiori-design-web/responsive-table/
![Group-headers-1-800x512](https://user-images.githubusercontent.com/76096491/119666913-16810e00-be36-11eb-89a3-af823ceef845.png)

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

We are in the middle of development and currently try to implement the screens based on mockups, by using UI5 WC features.

### **Stakeholder Info** (if applicable)

- Organization: SAP
- Bussiness impact: lower usability

**Comment by ilhan007** [comment]
FYI @SAP/ui5-webcomponents-topic-rl I think this feature request makes sense

[new feature request] Table: grouping rows
UX: https://experience.sap.com/fiori-design-web/responsive-table/#group
Possible Solution: new child element `ui5-table-group-row` (smaller in height, not interactive, bold texts)
