### ISSUE TITLE
Improve JSDOC plugin

### ISSUE THREAD

**Issue by fifoosid** [SAP/ui5-webcomponents#3322]
### **Feature Request Description**
We need:
1. a way to hide inherited properties/methods from the docs
2. a way to know if appendedDocs have ```@since``` tag

### **Proposed Solution**
We need to:
1. create a tag like ```@ignore``` for example, which will hide the docs for the given property/method.
2.  For the second issue, we can have two approaches:
2.1. Read the ```@since``` tag of component whose docs are nested in order to show it
2.2 Change our concept of showing the documentation of such components(Add separate pages, rather than appending it to the "mother" component)

Related info

1. Related to
- #3107 (Hide the inherited open method of the responsive popover)
- #3258 (Hide the inherited properties of SegmentedButtonItem)
2. Related to
- https://github.com/SAP/ui5-webcomponents/pull/346(show ```@since``` tag for components with appended docs)

**Comment by ilhan007** [comment]
Instead of improving the JS Doc plugin we will integrate TS Doc in future as we are migrating all the codebase to TS.
New issue will be created.
