### ISSUE TITLE
Overflow Toolbar

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents#333]
**Is your feature request related to a problem? Please describe.**
Are there any plans to add a component like the "classic" SAPUI5 OverflowToolbar? This would help us e.g. building an ObjectPageLayout on top of the `ui5-webcomponents`.

**Describe the solution you'd like**
I would like to have an Overflow Toolbar like in SAPUI5: https://sapui5.hana.ondemand.com/#/entity/sap.m.OverflowToolbar

**Describe alternatives you've considered**
none

**Additional context**

**Comment by vladitasev** [comment]
Still under consideration - whether to add it and if yes, to which package. To discuss with @petermuessig

**Comment by ilhan007** [comment]
Requested also by @lateefsofi with https://github.com/SAP/ui5-webcomponents/issues/2249

**Comment by ilhan007** [comment]
Hi @MarcusNotheis is planned for research and later for development.

The scope and features of the OverflowToolbar web component are under discussion. The web component won't match the sap.m.OverflowToolbar in terms of functionality, but the goal is to support the use-case of the actions overflow in the Dynamic Page Header.

Hi @dobrinyonkov once when you have clarity on the timelines you can update the milestone and move the item into planned/in-progress ect.

BR,
ilhan

**Comment by dobrinyonkov** [comment]
Internal reference: BGSOFUIPIRIN-6088

**Comment by vladitasev** [comment]
# Overflow Toolbar challenges

## The problems:
 - Web components use slots (physical, not logical, browser-level mechanism) to render children. Therefore, a component's children can only be rendered by the component itself (`<slot>` its own shadow root), or by another component (transitive `<slot>`). However, OTB would require a static area for the popup to avoid visual glitches, as all other similar components do. It is not possible technically to render the slotted items from the toolbar to the static are item of the toolbar, as these are completely independent parts of the DOM, and you can't render a `<slot>` in the static area item for content that is in another part of the DOM (OTB itself).
 - OTB performs transformations/overstyling. For example, a segmented button is displayed as a select in the overflow menu. The app will attach an event listener to the segmented button, but if it overflows, the user will never click it, the user will instead click a select that is meant to represent the segmented button). Thus, the original event will never be fired. We would need to manually fire events on the segmented button.

## Possible solutions:

1. [My preferred] We do it like the MDK Overflow Toolbar - it has abstract items (ui5-otb-button, ui5-otb-select, ui5-otb-checkbox, etc...). Thus, we do not render the slotted abstract items, but rather their representations in the static area. This is how all other similar components work (ui5-select, ui5-combobox, etc).
Pros: we completely bypass the "slotting-to-static-area" problem; we control the transformations (segmented button -> select in the menu; design changes such as button transparency etc...) and we can enforce good design.
Cons: users can't pass whatever they like, but only whatever we allow with our limited list of abstract items.

2. We clone slotted content to the static area (as in the years-old prototype). We can't slot the content, but we can clone it and keep it synchronized.
Pros: users can pass everything they want
Cons: performance impact from synchronizing cloned content, event bubbling complications, limitations to the usage as HTML elements that you passed to the OTB won't be the same instances in the menu, but rather clones. This could cause logical issues in the app. Events, bound to buttons passed to the OTB, will actually bubble from within the static area. Overall - technially very complex.

3. We don't use a static area for OTB and document this as a limitation. We render the popup in the same template as the OTB itself.
Pros: users can pass everything they want; and at the same time there will be no complications from cloning, mutation observers, event bubbling.
Cons: the OTB will be prone to visual glitches such as "overflow:hidden" on itself, or one of its parents, cutting off parts of the menu; or issues with CSS transforms bugging the popup position. This would be inconsistent to all other components that show popups (as they all use the static area and thus avoid similar issues). Another issue will be that when thera are transformations (f.e. segemented button -> select), people will bind event listeners to the segmented button and will get events from the select. We would still need to somehow proxy the events.

3.
