### ISSUE TITLE
ui5-tree-item: no support for title attribute

### ISSUE THREAD

**Issue by agauyeung** [SAP/ui5-webcomponents#3331]
### **Bug Description**
`ui5-tree-item` does not support the `title` attribute even though it is supported in the SAPUI5 implementation.
https://sapui5.hana.ondemand.com/#/api/sap.m.StandardTreeItem%23overview

### **Expected Behavior**
Hovering over the tree item should show a tooltip with the text defined as the value for the `title` attribute.

### **Steps to Reproduce**
1. Add ui5-tree and a ui5-tree-item within it.
2. Add `title` attribute with a value.
3. Hover over the tree item; no tooltip appears.

### **Isolated Example**
https://codesandbox.io/s/ui5-webcomponents-forked-23bmc?file=/index.html

### **Context**
- UI5 Web Components version: ^0.29.15
- OS/Platform: Windows
- Browser: Chrome
- Affected component: Tree Item

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

### **Stakeholder Info** (if applicable)

- Organization: SuccessFactors
- Business impact: Require tooltip to provide additional permission information about the tree item.

**Comment by tsanislavgatev** [comment]
Hello @SAP/ui5-webcomponents-topic-p ,
Can you take a look why the tooltip is not present?
I see that there's a text property that can be used, but no tooltip was shown on hover.

Thanks and Best Regards,
Tsanislav

**Comment by nnaydenow** [comment]
Hi @dobrinyonkov ,

Can you check this issue?

**Comment by ilhan007** [comment]
Hi @dobrinyonkov @nnaydenow 

The tooltip is not present because the `ui5-tree-item ` is an abstract element, I suggest creating a private prop "title" to make use of the HTML title attribute and forward its value to the real item, that has been rendered.
