### ISSUE TITLE
BusyIndicator: add `delay` property

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents#3340]
### **Feature Request Description**
Currently there is no functionality to control when the loading indication should start.
In the Fiori 3 guidelines is  recommended to start the loading animation  1000 ms after the action (while now it is done immediately).

### **Proposed Solution**
A new property, called `delay` on  BusyIndicator component with defaultValue: 1000ms 

### **Reference**
Similar to the UI5 Core property
`busyIndicatorDelay` | 1000ms	|The delay in milliseconds, after which the busy indicator will show up for this control.

### **Priority**
- [ ] Low
- [ ] Medium
- [X] High
- [ ] Very High

### **Stakeholder Info**

- Organization: {...} SFSF

**Comment by gmkv** [comment]
This issue is solved by PR #3419
