### ISSUE TITLE
ui5-dialog: page scrolls up if more than one dialog open

### ISSUE THREAD

**Issue by ee92** [SAP/ui5-webcomponents#3355]
### **Bug Description**
When a dialog is opened on top of another dialog, the whole page scrolls up to the top. 

### **Expected Behavior**
The page should not scroll when a dialog is opened.

### **Steps to Reproduce**
1. Go to https://codesandbox.io/s/ui5-webcomponents-forked-2qpvx
2. scroll down
3. open dialog
4. click close to open a confirmation dialog
5. notice that the page scrolled back to the top

### **Context**
- UI5 Web Components version: 0.31.7

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### **Stakeholder Info**

- Organization: SuccessFactors

Thanks

**Comment by dobrinyonkov** [comment]
Hello @ee92,

As the dialog has a mechanism to restore the focus after closing itself, it makes sense to close the dialogs in the order of opening.
Changing the order of closing the dialogs on your CodeSandbox example, fixed the issue on my side.
https://codesandbox.io/s/ui5-webcomponents-forked-6p40b?file=/src/index.js

Kind Regards,
Dobrin

**Comment by ee92** [comment]
@dobrinyonkov thanks that helps,

However the page jumping in the background is still an issue for us. Is it possible to fix it?

**Comment by dobrinyonkov** [comment]
Hello @SAP/ui5-webcomponents-topic-rd,

When the second dialog is opened the page in the background is scolled to the top.
![CPT2106031010-476x418](https://user-images.githubusercontent.com/22766569/120602771-04b1f300-c454-11eb-9bb9-e71795cbe80f.gif)

It is also reproducible in the test page with the `Open Prevent closing Dialog` dialog example: 
https://sap.github.io/ui5-webcomponents/master/playground/main/pages/Dialog/

Kind Regards,
Dobrin
