### ISSUE TITLE
List : A11y ARIA issue (Ensures every ARIA input field has an accessible name)

### ISSUE THREAD

**Issue by sleric1024** [SAP/ui5-webcomponents#3368]
**Describe the bug**
Ensures every ARIA input field has an accessible name

**Isolated Example**
https://xs8c4.csb.app/

**To Reproduce**

1. Go to https://xs8c4.csb.app/
2. Run chrome axe DevTool plugin

**Expected behavior**
No A11y issues in the following cases:
1. headerText property is set
2. header property is set

**Screenshots**

**UI5 Web Components for React Information**
@ui5/webcomponents version: 0.31.6
@ui5/webcomponents-react version: 0.131.4
Operating System:
Browser: Max OS

**Additional context**
I am from SuccessFactors

**Comment by dobrinyonkov** [comment]
Hi @sleric1024,

Thanks for reporting this!
Unfortunately I don't see how we can fix this warnning as the element is actually labelled by a valid id. You can see it (the `header` element) just one element above the `ul`.

![image](https://user-images.githubusercontent.com/22766569/120278690-4446d680-c2be-11eb-8491-c138f371c6ec.png)

I have tested it with screen readers and it's working fine. The header is read out upon focusing the listbox.
Also, tested it with other a11y validators and such error was not reported.

Still, if you suspect an issue coming from AXE, please verify that there is an actual ACC problem at hand, provide your assessment and the real user impact.

Kind Regards,
Dobrin
