### ISSUE TITLE
[SF][ComboBox with grouping][Urgent - WithIn 3 Weeks] support comboBox with grouping

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents#3371]
**Dear colleagues,**
I am from SuccessFactors Web Experience Shanghai team.

support comboBox with grouping

![Screen Shot 2021-06-02 at 10 16 45 AM](https://user-images.githubusercontent.com/78520316/120413968-ca7d1e80-c38b-11eb-9fc1-c2956631119d.png)

We can refer to this page: https://sapui5.hana.ondemand.com/#/entity/sap.m.ComboBox/sample/sap.m.sample.ComboBoxGrouping

**Comment by ilhan007** [comment]
FYI, new feature request for the ComboBox @SAP/ui5-webcomponents-topic-rl

**Comment by sfsf-xweb-sh** [comment]
Hi @ilhan007 

Is there a timeline for this component ?
Can this component be finished in a month ?

**Comment by nikolay-kolarov** [comment]
Hello @sfsf-xweb-sh,

We have planned to start the work on the feature for the current sprint and we will keep you up to date on the execution.

Best Regards,
Nikolay

**Comment by ndeshev** [comment]
Hello, 
The requested functionality is implemented and merged with #3469

Kind Regards,
Nikolay

**Comment by sfsf-xweb-sh** [comment]
> Hello,
> The requested functionality is implemented and merged with #3469
> 
> Kind Regards,
> Nikolay



> Hello @sfsf-xweb-sh,
> 
> We have planned to start the work on the feature for the current sprint and we will keep you up to date on the execution.
> 
> Best Regards,
> Nikolay

Thanks very much

**Comment by ilhan007** [comment]
Hello @sfsf-xweb-sh released with 0.31.12
