### ISSUE TITLE
New Component: Illustrated Messages

### ISSUE THREAD

**Issue by pavelkornev** [SAP/ui5-webcomponents#3376]
### **Feature Request Description**
Integrate illustrated images into UI5 Web Components framework that they can be easily consumed while building applications.

See UI5 integration: https://openui5nightly.hana.ondemand.com/entity/sap.f.IllustratedMessage/sample/sap.f.sample.IllustratedMessageInPage

### **Proposed Solution**
Create a Web Component:
```<ui5-illustrated-message name="NoData" />```

will render:
![ii](https://user-images.githubusercontent.com/748043/120485718-aa158a00-c3b4-11eb-9572-39310062a4b5.png)

### **Proposed Alternatives**
N/A

### **Additional Context**
N/A

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

### **Stakeholder Info** (if applicable)

- Organization: SAP Graph
- Business impact: better UX

**Comment by ilhan007** [comment]
Initial Scope (IllustratedMessage web component, `ui5-illustrated-message`)

- theming of the SVG image
- set of Illustration Types (BeforeEach, NoData, etc..)
- support for i18n title and subtitle + the optional actions at the bottom
- **Note:** for the initial implementation we skip the responsive behaviour (changing the SVG icons on resize)

Example API
- property for the illustration type (f.e `name`)
- property for title (`title-text`) and subtitle (`subtitle-text`)
- slot for the optional actions ("actions")

@nnaydenow @jdichev
