### ISSUE TITLE
ColorPalette: mobile design to follow visual spec

### ISSUE THREAD

**Issue by DMihaylova** [SAP/ui5-webcomponents#3381]
### **Feature Request Description**
According to the visual design spec, on mobile the [ColorPalette's](https://sap.github.io/ui5-webcomponents/nightly/playground/?path=/story/main-colorpalette--basic) swatches have to be bigger and when placed in a popover - to be displayed in a Dialog.
For example - the corresponding [UI5 ColorPalette control](https://sapui5untested.int.sap.eu2.hana.ondemand.com/#/entity/sap.m.ColorPalette/sample/sap.m.sample.ColorPalettePopover).
Currently in the component the swatches are with the same size as on desktop. On top of that when in a popover, it stays a popover on mobile while it has to be in a Dialog as the design suggests.

### **Screenshots**
Visual design
<img width="422" alt="Screenshot 2021-06-02 at 18 45 01" src="https://user-images.githubusercontent.com/12519096/120511016-a5f86500-c3d2-11eb-88e4-b8ed4bc8645b.png">

Currently in the ColorPalette Web Component
<img width="357" alt="Screenshot 2021-06-02 at 18 50 40" src="https://user-images.githubusercontent.com/12519096/120511833-7007b080-c3d3-11eb-9c6f-fce00ebc7ecb.png">

**Comment by tsanislavgatev** [comment]
fixed with: https://github.com/SAP/ui5-webcomponents/issues/3381
