### ISSUE TITLE
Select "cannot read property 'textContent' of null"

### ISSUE THREAD

**Issue by d3nergy** [SAP/ui5-webcomponents#339]
**Describe the bug**

When dynamically changing the StandardListItems of a Select and in addition setting the selected prop this error occurs. Also the text inside the Select does not update with the selected prop.

**To reproduce**

- have a select which items are coming via ...map( i => StandardListItem)
- change array to map over by state-update
- again set selected prop for each StandardListItem

**Expected behavior**

- Select renders correct StandardListItems and set selected if provided

**Screenshots**

<img width="558" alt="Bildschirmfoto 2019-04-17 um 16 13 39" src="https://user-images.githubusercontent.com/13339537/56294854-0ca36180-612c-11e9-8494-b8a0f4558ea6.png">

**Context**
- UI5 Web Components version
- OS/Platform: {...}
- Browser *(if relevant)*: {...}
- Other information: {...}

**Affected components** *(if known)*

Select, StandardListItem
**Log output / Any errors** in the console
```
{...}
```

**Comment by ilhan007** [comment]
Hello @d3nergy  we started exploring the issue, thanks for reporting.

I wanted to ask you, if you have a url or snippet that we directly can reproduce the issue.

If you can`t provide such - it`s ok.

Best,
ilhan

**Comment by ilhan007** [comment]
Hello @d3nergy just a short update, 
that we are working on the issue, we were able to reproduce the issue and soon we will have a fix.

Thank you for your patience.

ilhan
