### ISSUE TITLE
getEffectiveContentDensity method doesn't always work as expected

### ISSUE THREAD

**Issue by fifoosid** [SAP/ui5-webcomponents#3399]
### **Bug Description**
The ```getEffectiveContentDensity``` method doesn't always work as expected.

### **Expected Behavior**
The ```getEffectiveContentDensity``` should always return the cozy or compact

### **Steps to Reproduce**
1. Go to https://codesandbox.io/s/ui5-webcomponents-forked-1kbyv?file=/index.html
2. Place a breakpoint on line 104 in ```WheelSlider.js``` (onAfterRendering).
3. Interact with the instantiated timeSelection component and check what the method returns.
4. Open the duration picker and see that the method returns empty string
**Note**: The return value is empty string only the first time the component rerenders itself. After that it starts working correctly.

### **Priority**
- [x] Low
- [ ] Medium
- [ ] High
- [ ] Very High

**Comment by nnaydenow** [comment]
Seems the issue is not reproducible anymore.
