### ISSUE TITLE
ui5-tree-item: icon should be on the right

### ISSUE THREAD

**Issue by agauyeung** [SAP/ui5-webcomponents#3400]
### **Bug Description**
The icon is placed before the item label, but it should be placed at the end of the item.

### **Expected Behavior**
Please see the Fiori documentation:
https://experience.sap.com/fiori-design-web/tree/
![image](https://user-images.githubusercontent.com/8508119/120865366-c5160480-c542-11eb-833d-9708ee11f50a.png)

### **Isolated Example**
https://sap.github.io/ui5-webcomponents/playground/components/Tree/

### **Context**
- UI5 Web Components version: 0.29.15
- OS/Platform: Windows
- Browser: Chrome
- Affected component: `ui5-tree-item`

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### **Stakeholder Info** (if applicable)
- Organization: SuccessFactors

**Comment by elenastoyanovaa** [comment]
Hello @agauyeung ,

The image you are referring is only for the 'details' treeitem/listitem type, which additionally renders an edit icon on the right.

> Edit: Use the “Detail” item type (sap.m.TreeItem / sap.m.ListItemBase, property: type, value: sap.m.ListType.Detail). This places an Edit   icon at the end of the corresponding items.

 What is more, this item type is not available in the web components. 

As you can see in the guidelines you shared all other icons are rendered before the item text, as implemented in the web components. Additionally, you can check the UI5 Tree Control example, showing the same https://sapui5.hana.ondemand.com/#/entity/sap.m.Tree/sample/sap.m.sample.TreeIcon

Kind Regards,
Elena
