### ISSUE TITLE
Incorrect vertical alignment of text inside <ui5-button /> component

### ISSUE THREAD

**Issue by pavelkornev** [SAP/ui5-webcomponents#3401]
### **Bug Description**
If page has a custom `line-height` style and `<ui5-button/>` component is used among some text nodes, the text inside the button implicitly affected and leads to misalignment vertically (jumps 1-2 pixels up):
![Screenshot 2021-06-06 at 01 30 55](https://user-images.githubusercontent.com/748043/120908034-e2dc8a00-c666-11eb-8dee-7ab78991c871.png)

### **Expected Behavior**
Outside styles should not affect rendering of inner nodes of button component:
![Screenshot 2021-06-06 at 01 32 53](https://user-images.githubusercontent.com/748043/120908074-318a2400-c667-11eb-8d3c-d4af2b23d587.png)

### **Proposed solution**
Add `line-height` property for button component, e.g.:
```
<ui5-button icon="add" style="line-height: 100%;">
  Add Comment
</ui5-button>
```
In our opinion, this property should be included in the implementation of this component rather than in the application code.

### **Steps to Reproduce**
See example below.

### **Isolated Example**
https://codesandbox.io/s/ui5-webcomponents-forked-j0spo?file=/index.html

### **Context**
- UI5 Web Components version: 1.0.0-rc.14
- OS/Platform: macOS
- Browser: Chrome 90.0.4430.212
- Affected component: `<ui5-button />`

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### **Stakeholder Info** (if applicable)

- Organization: SAP Graph
- Business impact: UX

**Comment by ilhan007** [comment]
Hello colleagues @SAP/ui5-webcomponents-topic-b could you take a look of the issue.

**Comment by tsanislavgatev** [comment]
Hello @pavelkornev ,

I've opened the example but i see the expected behavior. Can you please check the example, and if we have to add something to reproduce the issue, please update us.

Thanks and Best Regards,
Tsanislav

**Comment by ilhan007** [comment]
Hi @pavelkornev I re-checked the [codesanbox](https://codesandbox.io/s/ui5-webcomponents-forked-j0spo?file=/index.html) example above (thanks for providing one)
and keep setting line-height: 32px (48px) to the body (tried on to wrapping div as well) but it applied only over the text somehow - could not see a difference with the Button's text alignment. Could you help me on this?

These are snapshots from your code sandbox example without line-height and with 48px line-height, but could not see a difference in the Button's alignment 

## no line-height

<img width="545" alt="no_line_height" src="https://user-images.githubusercontent.com/15702139/121515847-4b748f80-c9f6-11eb-994f-01500ecf3b19.png">

## with 48px line-height
<img width="635" alt="with_48px_lineheight" src="https://user-images.githubusercontent.com/15702139/121515852-4d3e5300-c9f6-11eb-8f51-6c09edb37945.png">

**Comment by pavelkornev** [comment]
Hi,
we had a call with Ilhan this morning, here is an updated example: https://codesandbox.io/s/ui5-webcomponents-forked-j0spo?file=/index.html

![Screenshot 2021-06-11 at 08 52 42](https://user-images.githubusercontent.com/748043/121649526-f178d600-ca98-11eb-9e08-597a14dc998d.png)

Top button: has a problem - text is positioned one 1px up.
Bottom button: has a fixed `line-height` and therefore text is properly centered.
