### ISSUE TITLE
ui5-tree-item: tree items are misaligned when the text is very long

### ISSUE THREAD

**Issue by agauyeung** [SAP/ui5-webcomponents#3415]
### **Bug Description**
When the text for a tree item is very long, and there are nested items within the tree, the tree item can become misaligned with the other items.

### **Expected Behavior**
The tree items should all be aligned no matter the text length.

### **Steps to Reproduce**
Please see the isolated example.
Note the misaligned checkboxes:
![image](https://user-images.githubusercontent.com/8508119/121282824-ff5b0b00-c88e-11eb-80ce-2eb6e8e3a781.png)

### **Isolated Example**
https://codesandbox.io/s/ui5-webcomponents-forked-8ogsr?file=/index.html:1058-1062

### **Context**
- UI5 Web Components version: 0.29.18
- OS/Platform: Windows
- Browser: Chrome
- Affected component: `<ui5-tree-item>`

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### **Stakeholder Info** (if applicable)

- Organization: SuccessFactors

**Comment by elenastoyanovaa** [comment]
Hello @SAP/ui5-webcomponents-topic-p ,

There is some misalignment, between different type of tree items - nested items, regular, group. The same is not present if you check the UI5 Tree. Could you please have a look?

Kind Regards,
Elena

**Comment by agauyeung** [comment]
Hi, when can we expect this to be released in v0.29.x?

**Comment by nnaydenow** [comment]
Hi @ilhan007,

Can you take a look at this?

**Comment by ilhan007** [comment]
Hello @agauyeung later today 21 June, we will release 0.29.x patch, including the change

**Comment by ilhan007** [comment]
Hello @agauyeung 0.29.19 is available
