### ISSUE TITLE
[SF] Support checkbox group

### ISSUE THREAD

**Issue by 2bno1** [SAP/ui5-webcomponents#3417]
**Is your feature request related to a problem? Please describe.**
Now, the library provides a Checkbox component which is useful for the scenario that user can check/uncheck the option.
However, many of the scenarios are that users have multiple options for a specified input and he can check several options among them. Checkbox does not provide a convenient way supporting such scenarios. 

**Describe the solution you'd like**
I'd like to have a component (like named CheckboxGroup) out-of-box supporting:
1. multiple options for user to check.
2. initial values indicates which options are checked by default
3. onChange callback passes checked values in argument

**Describe alternatives you've considered**
Write a wrapper component which composes of multiple Checkbox instances.

**Additional context**
This is a sample of the scenarios that user has multiple options to check.
<img width="202" alt="WeChatd0082496e74d930fd6e0233314e965e8" src="https://user-images.githubusercontent.com/1751846/120983361-33a9cb00-c7ac-11eb-895e-8282d83a4e17.png">

**Comment by fifoosid** [comment]
Hi @2bno1 

The current feature request is not part of the Fiori Design Language and therefore will not be implemented in UI5 Web Components as it doesn't bring much of benefit for the developers.

Moreover, it is not difficult to implement using standalone checkboxes as in the example above provided by @Lukas742 

Best regards,
Filip
