### ISSUE TITLE
TabContainer and Tab is collapsed when select it in first time

### ISSUE THREAD

**Issue by ericwdq** [SAP/ui5-webcomponents#3423]
**Describe the bug**
TabContainer and Tab is collapsed when select it at the first time, it's a random issue, not everytime.

**Isolated Example**
```
<TabContainer
          collapsed={false}
          onTabSelect={(e) => {
            setCurrentTab(e.detail.tabIndex);
          }}
        >
          {metadata.map((meta, index) => (
            <Tab
              key={`Tab-${meta.authObject}`}
              selected={index === currentTab}
              semanticColor="Default"
              text={ObjectsMap[meta.authObject] || meta.authObject}
            >
              <Table
                data={meta.items}
              />
            </Tab>
          ))}
        </TabContainer>

```
**To Reproduce**
1. Switch tabs
2. Click tab to select it at the first time

**Expected behavior**
Tab is always expanded when click it at the first time
![image](https://user-images.githubusercontent.com/1897893/121529135-ae821880-ca2e-11eb-9330-36526c1fd1ee.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/1897893/121504636-bf259500-ca14-11eb-9f03-97c2a95d640b.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.0.0-rc.14
`@ui5/webcomponents-react` version: 0.16.3
Operating System: Mac OS
Browser: Chrome - Version 91.0.4472.77 (Official Build) (x86_64)

**Additional context**

**Comment by elenastoyanovaa** [comment]
Hello @ericwdq ,

In order to analyse the issue, we would need some information and a reproducible example.

Please fill the following information: 

**Steps to Reproduce**
1. Go to '...'
2. ...
3. ...

**Isolated Example**
If possible, please provide an isolated example by forking [CodeSandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html).

**Context**
- UI5 Web Components version: {...}
- OS/Platform: {...}
- Browser: {...}
- Affected component: {...}

Kind Regards,
Elena

**Comment by ericwdq** [comment]
> Hi @ericwdq
> 
> since the `Tab` and the `TabContainer` component are developed by our UI5 Web Components colleagues, I'll transfer this issue to their repo.

Thanks @Lukas742 . Sounds great!

**Comment by ericwdq** [comment]
> Hello @ericwdq ,
> 
> In order to analyse the issue, we would need some information and a reproducible example.
> 
> Please fill the following information:
> 
> **Steps to Reproduce**
> 
> 1. Go to '...'
> 2. ...
> 3. ...
> 
> **Isolated Example**
> If possible, please provide an isolated example by forking [CodeSandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html).
> 
> **Context**
> 
> * UI5 Web Components version: {...}
> * OS/Platform: {...}
> * Browser: {...}
> * Affected component: {...}
> 
> Kind Regards,
> Elena

@elenastoyanovaa Thanks for your reply! I put the sample codes and update some information in comments, please check.

**Comment by ericwdq** [comment]
https://user-images.githubusercontent.com/1897893/121537777-ceb5d580-ca36-11eb-8a62-f430cad7f6c6.mov

**Comment by gmkv** [comment]
Hi @ericwdq 
I tried to reproduce this issue with the provided code in this [CodeSandbox example](https://codesandbox.io/s/gifted-dan-uv319?file=/src/App.js), but it's still working for me. Would you be able to extend the linked example with your code to get the bug to appear?

**Comment by ericwdq** [comment]
Hi @gmkv, thanks for your information! Can you please try the TabContainer and Tab inside Dialog? you can see the whole user interaction in attached video.

**Comment by gmkv** [comment]
Hi, I edited the [sample](https://codesandbox.io/s/gifted-dan-uv319?file=/src/App.js) to use a dialog, but it still works for me. I reached out to you on Slack.

**Comment by ericwdq** [comment]
I set the fixed={true} in tab container:
`<TabContainer
          collapsed={false}
          _**fixed={true}**_`
The issue has been resolved, so I’m going to close this issue.
