### ISSUE TITLE
ui5-file-uploader is not clickable when it is in a ui5-dialog that is showed on top of another ui5-dialog

### ISSUE THREAD

**Issue by thomaszang** [SAP/ui5-webcomponents#3426]
ui5-file-uploader is not clickable when it is in a ui5-dialog that is showed on top of another ui5-dialog, please see the screenshot below,

<img width="1358" alt="Screenshot 2021-06-14 at 9 06 19 AM" src="https://user-images.githubusercontent.com/31717922/121827893-6265fb00-ccf0-11eb-8038-f858526c7b6f.png">

**Comment by ilhan007** [comment]
As discussed offline @thomaszang could you add more details so we can process the issue

### **Steps to Reproduce**
1. Go to '...'
2. ...
3. ...

### **Isolated Example**
If possible, please provide an isolated example by forking [CodeSandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html).

**Comment by thomaszang** [comment]
The issue can be reproduced when,
1. open an ui5-dialog A,
2. click something in ui5-dialog A to open an ui5-dialog B that has a ui5-file-uploader in it, then you can see the ui5-file-uploader in ui5-dialog B is not clickable in this case.

**Comment by gmkv** [comment]
Hi @thomaszang 
I created a [CodeSandbox example](https://codesandbox.io/s/ui5-webcomponents-forked-jm8es?file=/index.html) with what you described, but I couldn't reproduce your problem.

As you have discussed with Ilhan, could you provide more details about the issue so that we can investigate?

**Comment by thomaszang** [comment]
@gmkv, @ilhan007, the difference between your CodeSandbox example and our code is we are implementing a customized ui5-component that contains the second ui5-dialog containing an ui5-file-uploader, you can see the issue using https://lcap-static-server-debug.cfapps.sap.hana.ondemand.com/index.html, and clicking 'Go to settings' icon and then 'Create Document' button.

**Comment by gmkv** [comment]
Hello @thomaszang 
I see the issue in your app. Which version of the ui5-webcomponents library are you using?
Can you provide an isolated example with the component in question?
If you are unable to do that, could you also provide source maps to the application to aid in debugging this issue?

**Comment by thomaszang** [comment]
Hi @gmkv, 
We are using ui5-webcomponents library 0.0.0-201dc9cbe, we have managed to reproduce this issue in the codesanbox example below.
https://codesandbox.io/s/ui5-webcomponents-forked-xtb6m

**Comment by thomaszang** [comment]
@GerganaKremenska , 

May I know the current status of this issue?

Regards,
Thomas

**Comment by GerganaKremenska** [comment]
Hello @thomaszang,

After reviewing the application i found out that there is nesting of the <ui5-dialog> inside a container which has a z-index lower that the block layer of the dialog. the <ui5-dialog> has the corrected z-index calculated to be visible. The issue is the z-index on the div wtih class="Page-module_staticlayout__1duNU".  
z-index is relative to the siblings within the same parent. Since the dialog is inside a div with lower z-index, we do not have control over that, the issue is with the applciation.

We also have in the documantation that we do not recoment on nesting of dilogs.

I have also prepared a pull request with an update of the documentation so it is more clear. 

Best Regards,
Gergana

**Comment by thomaszang** [comment]
@GerganaKremenska,@ilhan007,  we can reproduce this issue even using one ui5-dialog, please see it in the code example below, can you reopen this ticket and look at this issue again? if this really can't be fixed, can you let us know how to render an ui5 component that is used by our custom ui5 component hbs file into body DOM tree instead of #shadow-root?

https://codesandbox.io/s/ui5-webcomponents-forked-xtb6m?file=/index.html

**Comment by ilhan007** [comment]
Hi @thomaszang as we spoke offline, one thing that you can try is to calculate and set the proper z-index, considering the z-index number our popus have reached, using:

```js
import { getNextZIndex } from "@ui5/webcomponents-base/dist/util/PopupUtils.js";
```
