### ISSUE TITLE
Theme synchronaziton between Fiori page and ui5-webcomponents

### ISSUE THREAD

**Issue by MingZhang860612** [SAP/ui5-webcomponents#343]
**Is your feature request related to a problem? Please describe.**
I have a fiori-launchpad, and develop some page based on UI5 technology. Now some partner build his webcomponents using ui5 webcomponents, and plug his webcomponents into my fiori app page.
It works, however, when my fiori app is changed to another theme. The look and feel of partner's webcomponents is not changed.
I guess it is because the fiori app doesn't communication with the ui5 webcomponents to sync the theme.

**Describe the solution you'd like**
I hope fiori page can raise theme change event using browser standard event emitter, and all ui5 webcomponents listen to the event and change its theme accordingly.

**Describe alternatives you've considered**
Or ui5 webcomponents to provide a API to change its theme. Partner's webcomponent can listen to the theme change event, and invoke the ui5 webcomponents's API later on.

**Additional context**
![image](https://user-images.githubusercontent.com/20200532/56347076-227d5900-61f6-11e9-93cf-9480abe31d39.png)

**Comment by pskelin** [comment]
Hi @MingZhang860612 ,
thank you for reaching out with this issue.

At the moment, ui5-webcomponents do not actively integrate with FLP or openui5, but with a few additional method calls it can easily be wired together.

First, the application of the partner (which has knowledge that it runs inside FLP) has to listen for the theme change event fired by openui5. Here is the documentation for it:
http://veui5infra.dhcp.wdf.sap.corp:8080/demokit/#/api/sap.ui.core.Core/methods/attachThemeChanged
Basically, you will need something like:
```javascript
// App code
sap.ui.getCore().attachThemeChanged(function (event) {
  console.log("theme name:", event.getParameters().theme);
});
// called by FLP
sap.ui.getCore().applyTheme("sap_fiori_3")
// [output] theme name: sap_fiori_3
```

Next, within this theme changed handler, the app has to instruct the webcomponents runtime to change the theme. This can be done by the following import:
```javascript
import { setTheme } from '@ui5/webcomponents-base/src/sap/ui/webcomponents/base/Theming';
setTheme("sap_belize_hcb");
```

you can find a fully functioning theme change example here: https://stackblitz.com/edit/ui5-webcomponents-theme-change

Please bear in mind that the application is responsible for setting the background color of its container. The example above shows how this is done for the HCB theme.

As a standard disclaimer, we are still working on making the theming easier, so keep an eye on the release notes for breaking changes as we plan to adjust these APIs.

PLease let me know in case you need more information.
Regards,
Petar

**Comment by MingZhang860612** [comment]
Hi @pskelin 
Thank you very much! It is already a clear and very helpful answer !
