### ISSUE TITLE
Card: A11y issue

### ISSUE THREAD

**Issue by ericchan1983** [SAP/ui5-webcomponents#3439]
### **Bug Description**
axe devtool reports an issue for Card component.
- Ensures role attribute has an appropriate value for the element

### **Expected Behavior**
axe devtool should not report a11y issues for the Card component.

### **Steps to Reproduce**
1. Install axe devtool (https://chrome.google.com/webstore/detail/axe-devtools-web-accessib/lhdoppojpmngadmnindnejefpokejbdd)
2. Go to https://y005t.csb.app/
3. Run automatic scan using axe devtool

### **Isolated Example**
https://codesandbox.io/s/awesome-shadow-y005t?file=/src/App.js

### **Context**
- UI5 Web Components version: 0.31.6
- OS/Platform: macOS
- Browser: Chrome
- Affected component: Card

### **Log Output / Stack Trace / Screenshots**
![image](https://user-images.githubusercontent.com/1614528/122362860-0ec30e00-cf8b-11eb-997e-62e2976b6b04.png)

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by gmkv** [comment]
Hi @SAP/ui5-webcomponents-topic-rd 

There's an accessibility concern with the ui5-card's role="group" on the content slot.
In the wiki pages, it is specified that the section element, should indeed have role="group", but this AXE tool reports it as "not allowed". Could you take a look?

https://codesandbox.io/s/ui5-webcomponents-forked-olxxq?file=/index.html

Regards,
Georgi
