### ISSUE TITLE
Button: A11y issues

### ISSUE THREAD

**Issue by ericchan1983** [SAP/ui5-webcomponents#3441]
### **Bug Description**
axe devtool reports two issues for Button component.
1. Ensure interactive controls are not nested
2. Elements of role none or presentation should be flagged

### **Expected Behavior**
axe devtool should not report a11y issues for the Button component.

### **Steps to Reproduce**
Install axe devtool (https://chrome.google.com/webstore/detail/axe-devtools-web-accessib/lhdoppojpmngadmnindnejefpokejbdd)
Go to https://eq9dj.csb.app/
Run automatic scan using axe devtool

### **Isolated Example**
https://codesandbox.io/s/confident-snowflake-eq9dj?file=/src/App.js

### **Context**
UI5 Web Components version: 0.31.6
OS/Platform: macOS
Browser: Chrome
Affected component: Button

### **Log Output / Stack Trace / Screenshots**
![image](https://user-images.githubusercontent.com/1614528/122365128-feac2e00-cf8c-11eb-92a0-a2ba46f26358.png)

![image](https://user-images.githubusercontent.com/1614528/122365033-e50ae680-cf8c-11eb-8504-33dc9190af6c.png)

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by gmkv** [comment]
Hi @SAP/ui5-webcomponents-topic-b 
There are accessibility concerns about the ui5-button.
Report shows it has to do with the svg element in the shadow dom having tabindex="-1".
Could you take a look?

https://codesandbox.io/s/ui5-webcomponents-forked-de724?file=/index.html

Regards,
Georgi

**Comment by unazko** [comment]
Hi @SAP/ui5-webcomponents-topic-b,

Our accessibility expert should have a look on those issues.

Best Regards,
Boyan
