### ISSUE TITLE
MessageStrip enhancement for hiddenText and close button messages.

### ISSUE THREAD

**Issue by lormanlau** [SAP/ui5-webcomponents#3447]
### **Feature Request Description**
1) The meaning of "Negative closable" announcement along with the message strip contents is not clear

### **Proposed Solution**
1) The "negative closable" part of the announcement must be removed as that is not meaningful to screen reader users.

2) The accessible name (aria-label/aria-labelledby) of the "close" button should be "close message strip"

### **Proposed Alternatives**
Make it possible to configure the labels for this messageStrip

### **Additional Context**
This is a request from the a11y team at SAP SuccessFactors 

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: SAP SuccessFactors
- Bussiness impact: Low

**Comment by elenastoyanovaa** [comment]
Hello @lormanlau ,

Thanks for the feedback. We are currently discussing announcement improvements with our accessibility experts. 

Kind Regards,
Elena

**Comment by nikolay-kolarov** [comment]
Hi,

At the moment, we are in clarification about the announcement with the acc team and we expect this to be clarified soon.
@elenastoyanovaa  - Could you please describe what we discussed as optimization for the close button, so that we can move forward the fix?

Thanks,
Nikolay

**Comment by niyap** [comment]
Hello Colleagues,

The fix is done with the following change for version 0.31: https://github.com/SAP/ui5-webcomponents/pull/4423
It will be available with the next patch release.

Kind Regards,
Niya

**Comment by ilhan007** [comment]
Hello @lormanlau the fix is released with  0.31.27 patch.
