### ISSUE TITLE
[ui5-dialog for Filter][SF][Urgent] Support Filter dialog

### ISSUE THREAD

**Issue by rchrdchn** [SAP/ui5-webcomponents#3451]
### **Feature Request Description**
This is a common key feature for current and future SF projects along with Sorting dialog (https://github.com/SAP/ui5-webcomponents/issues/3304). Please inform what would be a realistic estimate to have this component ready?

This Filter dialog comes from the [SAP UI5 ViewSettingsDialog](https://sapui5.hana.ondemand.com/#/entity/sap.m.ViewSettingsDialog/sample/sap.m.sample.ViewSettingsDialog)

### **Priority**
- [ ] Low
- [ ] Medium
- [ ] High
- [x] Very High

<img width="359" alt="Screen Shot 2021-06-21 at 15 10 04" src="https://user-images.githubusercontent.com/11576789/122815015-cc027e00-d289-11eb-8ece-33ad4537763e.png">
<img width="358" alt="Screen Shot 2021-06-21 at 15 10 10" src="https://user-images.githubusercontent.com/11576789/122815020-cd33ab00-d289-11eb-9d61-5d97d1c31f28.png">
<img width="359" alt="Screen Shot 2021-06-21 at 15 10 20" src="https://user-images.githubusercontent.com/11576789/122815024-ce64d800-d289-11eb-8232-071f0c47b3ef.png">

**Comment by ilhan007** [comment]
FYI @DMihaylova @SAP/ui5-webcomponents-topic-b

**Comment by rchrdchn** [comment]
Hi @ilhan007 -

Could you please let us know your plan and timeline on this feature? When would it be completed? We are delivering a project that is depending on this feature.

Thank you.

**Comment by DMihaylova** [comment]
Hello @rchrdchn,

We planned to firstly deliver the sorting functionality and the target is within the next month.
Right afterwards we'll start with the filtering panel. Have in mind that our initial scope excludes the Select All and Show only selected functionalities. Will you need them on top as part of next enhancement once we complete the initial scope?

Thanks & Regards,
Diana

**Comment by rchrdchn** [comment]
Hey @DMihaylova -

We need the basic functionalities:
- Header text
- Reset link/button
- List of filters options
- Transition to filters options similar to [View Settings Dialog](https://sapui5.hana.ondemand.com/#/entity/sap.m.ViewSettingsDialog/sample/sap.m.sample.ViewSettingsDialog)
- Footer OK and Close buttons

For the following text: Filter, Reset, Filter By, OK, Close – we would like to have these to be customizable by developers to meet i18n needs and standards. Ideally, these would be 5 customizable parameters (boxed in red color in screenshots below). Similar to [Sorting dialog's request](https://github.com/SAP/ui5-webcomponents/issues/3304#issuecomment-863002391).

Thank you!

![Screen Shot 2021-06-30 at 15 12 28](https://user-images.githubusercontent.com/11576789/124038469-08368c80-d9b6-11eb-820b-b7be86c888a6.png)
![Screen Shot 2021-06-30 at 15 12 39](https://user-images.githubusercontent.com/11576789/124038471-0967b980-d9b6-11eb-8b94-b29f4b6808aa.png)

**Comment by DMihaylova** [comment]
Hello @rchrdchn,

We'd like to keep the API as simple as possible. Therefore we'd stick to the list of basic functionalities mentioned by you.

Thanks & Regards,
Diana

**Comment by ilhan007** [comment]
Hello @fifoosid 
we would like to enhance the View Settings Dialog with the support of "Filtering"

The scope of the task is the following:
- Display a switch between Sorting and Filtering views (as per Fiori 3)
- Display Filter view , that consists of a list of filters options, that are actiona
- Display Secondary Filter view and handle the transition from the Filter view and Secondary Filter view
- make sure the Confirmation, Cancel and Reset buttons work for both the Sorting and Filtering views

Note: The "Secondary Filter" view does not include the "Search", "Select All" and "Show only selected" features, but only a List of filter options in Multi Selection mode.

Use the [View Settings Dialog](https://sapui5.hana.ondemand.com/#/entity/sap.m.ViewSettingsDialog/sample/sap.m.sample.ViewSettingsDialog) for reference

**Comment by fifoosid** [comment]
This feature request will be available in our next stable version as well as in the next 0.31 release.
