### ISSUE TITLE
[ui5-timeline][SF][Urgent]Horizontal View Timeline

### ISSUE THREAD

**Issue by BennyHuang** [SAP/ui5-webcomponents#3452]
### **Feature Request Description**
We have the requirement to show the timeline horizontally. But there is no property or attribute available for such kind of customization.  Please help to provide a way to make the timeline be horizontal and it can be scrolled horizontally to view more items (ideally in the way like Carousel). 

![image](https://user-images.githubusercontent.com/1995447/122816285-61ead880-d28b-11eb-8344-5f34d8d1abf6.png)

These a counterpart component available in SAPUI5 that supports horizontal view https://sapui5.hana.ondemand.com/#/entity/sap.suite.ui.commons.Timeline/sample/sap.suite.ui.commons.sample.TimelineScrolling

### **Priority**
- [ ] Low
- [ ] Medium
- [ ] High
- [x] Very High

### **Stakeholder Info** (if applicable)

- Organization: {SAP SuccessFactors}

**Comment by BennyHuang** [comment]
Hello @ilhan007 @DMihaylova 

Could you please let us know your plan on this feature? When could it be completed? As we are delivering a feature that is kind of depending on it. 

Thanks
Benny

**Comment by DMihaylova** [comment]
Hello @BennyHuang,

We have triggered internal discussions and for a rough estimation I could update you on Wednesday this week.

Thanks and Regards,
Diana

**Comment by BennyHuang** [comment]
Hello @DMihaylova 

What I mean is user can click on the arrow keys to scroll right or left to see more content if the width does not fit for the whole timeline. And from our UX perspective, it is alternative to have a horizontal scroll bar and the scroll bar is only shown when hovering on the timeline.

Thanks
Benny

**Comment by DMihaylova** [comment]
Hello @BennyHuang,

We planned to provide a one sided horizontal view with a default scroll bar in the Timeline component.
The target is within the next month.

Regards,
Diana

**Comment by ilhan007** [comment]
Hello @BennyHuang the feature has been released with 0.31.14
