### ISSUE TITLE
WizardStep [SF]: Custom icon prop

### ISSUE THREAD

**Issue by 2bno1** [SAP/ui5-webcomponents#3453]
### **Feature Request Description**
We have a requirement that display number of the steps (1,2...) in the header of wizard followed by step name.
However, the icon prop of WizardStep only accepts string which represents the name of the icon in sap-icons. 

### **Proposed Solution**
Make icon props customizable.

### **Additional Context**
![image](https://user-images.githubusercontent.com/1751846/122855711-35e15d00-d348-11eb-97ce-06f44d684000.png)

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: {SAP SuccessFactors}

**Comment by ilhan007** [comment]
FYI @nikolay-kolarov @SAP/ui5-webcomponents-topic-rl

**Comment by ilhan007** [comment]
Hello @2bno1 first you mentioned that you need to display the number "1,2," then you mentioned the icons,
but you can either have an icon,  or the number 

<img width="193" alt="Screenshot 2021-06-30 at 11 30 04" src="https://user-images.githubusercontent.com/15702139/123928404-8daa4480-d996-11eb-93db-126403801f62.png">

<img width="217" alt="Screenshot 2021-06-30 at 11 20 07" src="https://user-images.githubusercontent.com/15702139/123927244-512a1900-d995-11eb-868f-cc956a10e0ea.png">

Let's clarify what you need, I guess an API to display your own icon or image within the circle of a step, where currently only SAP icons are allowed?

If this is what you need, you have to consider the contrast ratio: with the built-in icons, the contrast ration between the icon color and the selected/non-selected background of the circle is always guaranteed across all themes, but in case you use something custom, you will need to ensure the contrast ratio yourself.

**Comment by 2bno1** [comment]
@ilhan007 Thanks for your reply.
My requirement is that I can show a number instead of a SAP icon within the circle of a step. 
If the ui5-wizard component can provide a prop like `show-step-number` and show the number if the code looks like `<ui5-wizard show-step-number={true}>...</ui5-wizard>`. That should be fine to me. But this probably is not general enough. So I requested to make `icon` prop of ui5-wizard-step customizable. But what I really need for now is just showing step number in this circle.

**Comment by nikolay-kolarov** [comment]
Hi @2bno1,

If you do not provide icons of the wizard steps, it will render their numbers.
So, there is no need for additional property and this functionality is already available.
Could you please give it a try and confirm that this is what you need?

The opening of the API for a general icon support is something, which we want to avoid, as this can have impact on different things, e.g the contrast and theming (as mentioned by Ilhan).

Thanks and Best Regards,
Nikolay

**Comment by 2bno1** [comment]
@nikolay-kolarov I tried and yes the component will render number by default. Thank you for your reply.
