### ISSUE TITLE
[ComboBox] [SF] add onScrollToEnd props

### ISSUE THREAD

**Issue by 2bno1** [SAP/ui5-webcomponents#3455]
**Is your feature request related to a problem? Please describe.**
We have a requirement that whenever user types in input box, it triggers a call to API to fetch the options which match the text the user inputs. Considering the count of the matched options is huge, the result of the API is paginated. So initially, the user will see the 1st page of all the matched options, and the expected behavior is that when user scroll downs the option list, it will call the API to fetch the matched options of next page, and so on. 

**Describe the solution you'd like**
The ComboBox can add a onScrollToEnd props (or another better name), which will be called when user scroll down to end of ComboBoxItem list (similar to onSuggestionScroll of Input component https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-input--default-story, but only be called when it reached to the end of the list)

**Comment by 2bno1** [comment]
@ilhan007 Is there any plan when this feature can be added? As this is quite critical and urgent for our 2111 release. Thanks.

**Comment by ilhan007** [comment]
Hello @2bno1 tomorrow we will go trough the requirement and discuss it with the ComboBox owners (FYI @nikolay-kolarov ). We will probably have an update in a week.

The 2111.4 internal release is 16 Aug right?

BR, ilhan

**Comment by nikolay-kolarov** [comment]
Hello @2bno1,

The ComboBox is designed to have up to 200 items and your requirement is contradicting to the Fiori guidelines: https://ux.wdf.sap.corp/fiori-design-web/combo-box/

For such scenarios, the recommendation is to use the Input. Could you please check if you can use the Input instead?

Thanks,
Nikolay

**Comment by 2bno1** [comment]
@nikolay-kolarov Thanks for your feedback.
I tried the Input component, it looks similar to ComboBox but I have two concerns:
1. It doesn't support auto complete which is supported by ComboBox. (It automatically pick the 1st matched item when user input)
2. It has a onSuggestionScroll props, but it's fired each time suggestion scrolls.
If these two issues can be addressed, I think Input is a good choice.

**Comment by nikolay-kolarov** [comment]
Hi @2bno1,

1. The auto-complete/type-ahead functionality of the Input is something that we can look into. And I see it rather as enhancement, and not something critical for your current integration. Could you please create another request, specifically for this, so we can keep track of it?
2. Yes, the idea of this event is to be generic and it was developed exactly for a scenario like yours as part of https://github.com/SAP/ui5-webcomponents/issues/1846. You have information in the event about the current scroll position and the container (and e.g its scrollHeight), so you can use them to load the data in the appropriate time:

input.addEventListener("suggestion-scroll", function (event) {
                console.log("scroll", { scrollTop: event.detail.scrollTop, container: event.detail.scrollContainer });
});

Thanks and Best Regards,
Nikolay

**Comment by 2bno1** [comment]
@nikolay-kolarov Thanks for your reply. I'll create another request for the auto-complete/type-ahead functionality added to Input component.

**Comment by nikolay-kolarov** [comment]
Hi @2bno1,

Thanks, in this case, I will close this one.
If you see challenges with using the suggestion scroll, you can reopen the issue.

Best Regards,
Nikolay
