### ISSUE TITLE
ui5-bar does not center

### ISSUE THREAD

**Issue by vladitasev** [SAP/ui5-webcomponents#3456]
The only purpose this component exists is to provide an absolutely centered middle part, so even if the content on the left is more than the content on the right, or vice versa, the center stays centered. 

Currently ui5-bar does not work that way. Please investigate and fix.

**Comment by ilhan007** [comment]
When implementing the bar, @SAP/ui5-webcomponents-topic-b stated that the design expects to center the title in remaining space between the start and end content.

@tsanislavgatev could you check if this is still true and perhaps provide the statement in the Fiori 3 spec (I think it was there)

**Comment by tsanislavgatev** [comment]
The requirements in the implementation issue stated that the middle content should be centered in the available space between the left and the right area.
https://github.com/SAP/ui5-webcomponents/issues/2434

Also by specification in openui5 we have "An area centered in the available space between the left and the right area. This are might not always be centered in the entire bar."

@vladitasev I understand your point of view, but these are the requirements and specifications provided.

**Comment by vladitasev** [comment]
This is an example from the OpenUI5 Demokit App itself:
![image](https://user-images.githubusercontent.com/15844574/123065556-ebc7ac80-d417-11eb-8b25-7c6be92f49af.png)

The sap.m.Bar is used to center the title. See how many buttons there are on the right, and yet the title is centered. If it doesn't center, it doesn't do anything since this is display: flex with no additional benefits for the user.

The sap.m.Bar has a complex implementation and really adds value, because having the middle part centered is not trivial.

Regards,
Vladi

**Comment by ilhan007** [comment]
Hello @tsanislavgatev @SAP/ui5-webcomponents-topic-b could you take a look of the sample above, provided by Vladi:
https://openui5nightly.hana.ondemand.com/entity/sap.m.Carousel/sample/sap.m.sample.Carousel

The sap.m.Bar is used to show the Demo kit samples, and from what I see for:
- large screens: the the title is absolutely centered in the container
- small screens: the title  centered in the available space between the start/end content

If the above is the correct behaviour, we have to fix the Bar component as it always centers the middle content in the available space between the star/end content.

Could you please have a look?

BR,
ilhan
