### ISSUE TITLE
ui5-step-input fires 2 change events when 0 is cleared

### ISSUE THREAD

**Issue by agauyeung** [SAP/ui5-webcomponents#3457]
### **Bug Description**
The step input component fires 2 change events when the 0 is manually cleared to empty.

### **Expected Behavior**
The number should still change back to 0 but no change event should be fired.

### **Steps to Reproduce**
1. Go to the code sandbox below.
2. Highlight the `0` inside the step input and delete it.
3. Click outside of the step input.
4. **Issue:** A change event is fired.
5. **Issue:** A second change event is fired.
6. `0` is automatically placed back into the step input box.

### **Isolated Example**
If possible, please provide an isolated example by forking [CodeSandbox](https://codesandbox.io/s/ui5-webcomponents-forked-6mh42?file=/src/index.js).

### **Context**
- UI5 Web Components version: 0.29.19
- OS/Platform: Windows
- Browser: Chrome
- Affected component: Step Input

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)
- Organization: SuccessFactors

**Comment by NHristov-sap** [comment]
Hello @SAP/ui5-webcomponents-topic-b,

The issue is reproducible, please take care of it.

Best Regards,
Nikolay Hristov
