### ISSUE TITLE
Dialog: Not able to select text inside it

### ISSUE THREAD

**Issue by AndrianStoikov** [SAP/ui5-webcomponents#3466]
**Describe the bug**
When text is rendered inside MessageBox the user is not able to select it with the mouse.

**Isolated Example**
https://codesandbox.io/s/charming-herschel-tex8y?file=/src/App.js

**To Reproduce**
1. Open the sandbox
2. Click the "MessageBox" button
3. Try to select the text using your mouse

**Expected behavior**
Users should be able to select the text using their mouse. I would expect that the MessageBox will behave the same way as in openui5 - [here](https://openui5.hana.ondemand.com/entity/sap.m.MessageBox/sample/sap.m.sample.MessageBox)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: "1.0.0-rc.14"
`@ui5/webcomponents-react` version: "0.16.4"
Operating System: Windows 10 20H2
Browser: Microsoft Edge - Version 91.0.864.54 (Official build) (64-bit)

**Additional context**
The bug also happens in the Dialog component. Can be seen in Storybook. I tried rendering the component in a portal, it does not fix the issue.

**Comment by NHristov-sap** [comment]
Hi @SAP/ui5-webcomponents-topic-rd,

The issue is reproducible, please take care of it.

Best Regards,
Nikolay Hristov

**Comment by AndrianStoikov** [comment]
Hello,

Just wanted to add to the issue that on mobile I am able to select the text with a long press but unable to deselect it.

Tested on Samsung Note 10 Plus, Chrome 91.0.4472.101.

Best regards,
Andy

**Comment by gmkv** [comment]
Reproducible in test pages with Chrome: https://sap.github.io/ui5-webcomponents/master/playground/main/pages/Dialog/ (Open wide dialog)
Works on Firefox and Safari.

**Comment by codefactor** [comment]
Any time line to look at this one? We use the Dialog for version information in SuccessFactors so it is important that the user be able to select text and copy paste that to a support ticket. Is there any work around?

The text we get is markup from the back-end, so it is not easy to put the important version info into a text area for copy purpose. That was the only solution I could think. Also text area might change experience a little bit. Anyway, if need be I could track down the backend code and change it to produce markup with text area around the lines of text the user typically need to copy paste.

**Comment by ilhan007** [comment]
Hello @AndrianStoikov 

the fix has been released with 1.0.0-rc.15.

Note: there were a lot of breaking changes that have to be adopted before upgrading to rc.15
See the BREAKING_CHANGE section:  https://github.com/SAP/ui5-webcomponents/releases/tag/v1.0.0-rc.15
