### ISSUE TITLE
ui5-responsive-popover: `showAt` method should accept `preventInitialFocus` parameter

### ISSUE THREAD

**Issue by zhangliangyi** [SAP/ui5-webcomponents#3473]
### **Bug Description**
So far in `ui5-responsive-popover`, the `open` ("showAt" in the master) method only accept `opener` as the method parameter. In the desktop or tablet mode, the `open` will call the `openBy` method of the popover element with `opener` passed previously.

But the `openBy` method of popover component, there is another parameter `preventInitialFocus` could be passed to it. Without this parameter, I cannot migrate `ui5-popover` to `ui5-responsive-popover` to fix responsive issue.

### **Expected Behavior**
The `open` method should also accept `preventInitialFocus` as the second parameter.

### **Steps to Reproduce**
Here is the code location of this `open` method.
https://github.com/SAP/ui5-webcomponents/blob/7f6e3c97215a959e4705265380094c4343e187b8/packages/main/src/ResponsivePopover.js#L119

### **Context**
- UI5 Web Components version: 0.31.11
- OS/Platform: MacOS
- Browser: Edge
- Affected component: ui5-responsive-popover

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very  #High

- Organization: SF

Also I noticed that there is a breaking change of the APIs in ui5-responsive-popover #3363 , which change the `open` method to `openBy`.

Just wonder if the change will be applied to 0.31.x release in the future.

**Comment by ilhan007** [comment]
Hello @zhangliangyi,
thank you for the feature request.

Could you let us know what is the use case to prevent the initial focus?
Did you consider the accessibility side of this, without having the focus applied on an element within the popover, certain announcement by screen readers would not be possible, or perhaps you would like to focus something on your own?

BR,
ilhan

**Comment by zhangliangyi** [comment]
Btw, I noticed that the `open` method in `ui5-responsive-popover` is renamed to `openBy` in the master branch. 
I think it is good to keep the APIs consistent. So just wonder if this change will be added into later 0.31.x release.

**Comment by ilhan007** [comment]
Hello @zhangliangyi yes in the master branch we renamed the ResponsivePopover's method  to "openBy", so in both Popover and ResponsivePopover the method is now called "openBy". This is one of the  ~60 Breaking Changes since RC.14 and 0.31.X. It's quite a change, as all input based components  (DatePicker, ComBobox..) are using ResponsivePopover internally and it's a bit risky to do that, but we will what would be the best approach.

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-rd this is a feature request related to the Responsive Popover omponent, the author would like to have a parameter in the "openBy" method to prevent the Responsive Popover from applying an initial focus - "preventInitialFocus".

The use case is the following: "Actually we have some case need to prevent the auto focus in popover component, and the focus action would be controlled by outside opener. And to avoid a11y issue, we also add announcement to notify user that the popover is opened, and can be focused via some keyboard action."

Could you evaluate the requirement?

**Comment by ilhan007** [comment]
Hello @zhangliangyi the feature is going to be released with 0.31.15 (9-10 Aug)

**Comment by ilhan007** [comment]
Hello @zhangliangyi
the enhancement (new param to prevent the auto focus on open is added) is released with 0.31.15

**Comment by zhangliangyi** [comment]
Thanks, @ilhan007
