### ISSUE TITLE
change focus of options on keypress

### ISSUE THREAD

**Issue by Grytolle** [SAP/ui5-webcomponents#3476]
In a vanilla select/option, I can press for instance F to go to the first item that starts with F... This would be a nice improvement for <ui5-select>.

**Comment by ilhan007** [comment]
@jdichev @nnaydenow could you check this requirement

**Comment by nnaydenow** [comment]
Hi @ilhan007, 

This requirement is already implemented in OpenUI5 but we don't have good example there.

**Comment by nnaydenow** [comment]
Internal reference: 5323
