### ISSUE TITLE
Dependency not found: "@ui5/webcomponents/dist/ShellBar"

### ISSUE THREAD

**Issue by joaopereirawd** [SAP/ui5-webcomponents#3484]
This module **@ui5/webcomponents/dist/ShellBar**  does not exist in  **node_modules/@UI5**

**Comment by ilhan007** [comment]
Hi @joaopereirawd 

Can you install and try the fiori package ( as the ShellBar is part of it)
@ui5/webcomponents-fiori/dist/ShellBar.js
