### ISSUE TITLE
@ui5/webcomponent-tools: watch.bundle Allocation failed - JavaScript heap out of memory 

### ISSUE THREAD

**Issue by codefactor** [SAP/ui5-webcomponents#3487]
### **Feature Request Description**
Rollup is given the default NodeJS max allocation for heap space, which our project can easily run out of space after a few seconds of running the server. There should be a way to customize an environment variable to increase the amount of heap space.

### **Proposed Solution**
Update the following file (and downport to SF's branch):
https://github.com/SAP/ui5-webcomponents/blob/5e3f3912751b3ab9e6ded4054c570550ab6f2479/packages/tools/components-package/nps.js

Update any usages of "rollup" to have an environment variable usage

before:
```
es5: 'rollup --config config/rollup.config.js -w --environment ES5_BUILD,DEV,DEPLOY_PUBLIC_PATH:/resources/'
```

after (suggestion):
```
const ROLLUP_CONFIG = process.env.ROLLUP_CONFIG || '';
// ...
  es5: `node ${ROLLUP_CONFIG} ./node_modules/rollup/dist/bin/rollup --config config/rollup.config.js -w --environment ES5_BUILD,DEV,DEPLOY_PUBLIC_PATH:/resources/`
```

Then in our package.json we could have something like this:
```
"scripts": {
  "start": "cross-env ROLLUP_CONFIG=--max-old-space-size=4096 wc-dev start"
```

Another option is to just accept the rollupConfig as an option when calling `getScripts()` the caller could pass the rollup config as an input to that function.

### **Proposed Alternatives**
No known alternatives, our server runs out of memory and its because we cannot customize the heap size of the node process running rollup. I can only manually change the nps.js file in my node_modules folder after running `npm install` to prevent the server from crashing due to out of memory.

### **Additional Context**
You can try to run `npm run start` from the `@xweb/shellbar` project to see the issue.

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

This is a productivity impacting bug; however, I can locally work around the issue.

### **Stakeholder Info** (if applicable)

- Organization: SuccessFactors Experience Web team
- Bussiness impact: productivity local testing is impacted.

**Comment by pskelin** [comment]
You can modify the default nps commands in your own `package-scripts.js` file. For example here in the package `main`:
https://github.com/SAP/ui5-webcomponents/blob/master/packages/main/package-scripts.js#L9

Before re-exporting, you can modify a part of the object like this:
```
scripts.watch.bundle.es5 = `your_needed_command_here`;
```

Would that work for you?

**Comment by codefactor** [comment]
This might work, but it is not as flexible due due to breaking encapsulation by needing to know which scripts to modify, since we use `start` which then kicks off other scripts internally. This means when we upgrade versions we will need to maintain the overridden script. It is certainly a better workaround than what I've already used, though.

Is there an issue with the proposed change to support customizing the node process configuration via environment variable?

**Comment by plamenivanov91** [comment]
Hello Colleagues,

Can you please verify if a change is feasible for just the use case of the reporter?

Regards,
Plamen Ivanov

**Comment by codefactor** [comment]
I think I have a solution that will eliminate the encapsulation issue as mentioned in my previous comment - so the work around is a little more robust now.

```javascript
/* global module */ // (For ESLint...)

const getScripts = require("@ui5/webcomponents-tools/components-package/nps.js");

const rollupConfig = "--max-old-space-size=4096";
const options = {
	port: 8081,
};

const updateRollup = (config) => {
	Object.keys(config).forEach((k) => {
		const v = config[k];
		if (typeof v === 'string') {
			config[k] = v.replace(/^rollup (.*)$/, `node ${rollupConfig} ./node_modules/rollup/dist/bin/rollup $1`);
		} else if (v && typeof v === 'object') {
			updateRollup(v);
		}
	});
	return config;
};

const scripts = updateRollup(getScripts(options));

module.exports = {
	scripts,
};
```

**Comment by pskelin** [comment]
Hi @codefactor 
this just doesn't seem right, so I looked around and found an article that suggests how to set an option for nodejs such that it applies to forked nodejs processes as well.
https://support.circleci.com/hc/en-us/articles/360009208393-How-can-I-increase-the-max-memory-for-Node-

```
The flag can be difficult to ensure is being used. Especially when node processes are forked.
The best way to ensure this setting will be picked up by all node processes within the environment
is to apply this setting directly to an environment variable, which can be done using Node. 8 or higher


NODE_OPTIONS=--max_old_space_size=4096
```

Could you please give it a try before we implement anything?

**Comment by codefactor** [comment]
@pskelin ,
I think this is working, thanks this is good enough for me.

**Comment by pskelin** [comment]
thanks for the confirmation @codefactor
