### ISSUE TITLE
[Input] [SF] add auto-complete/type-ahead functionality to Input component

### ISSUE THREAD

**Issue by 2bno1** [SAP/ui5-webcomponents#3488]
### **Feature Request Description**
I submitted an [issue](https://github.com/SAP/ui5-webcomponents/issues/3455) for adding onScrollToEnd event callback to ComboBox component so we can use it to loading more items in ComboBox, however, @nikolay-kolarov replied that showing more than 200 items breaks the Fiori guidelines. And Input component is recommended for this scenario. However, we also need to auto-complete/type-ahead functionality provided by ComboBox.

### **Proposed Solution**
Add auto-complete/type-ahead functionality to Input component.

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: SAP Successfactors

**Comment by nikolay-kolarov** [comment]
Hi @2bno1,

Thanks for raising this request.
Could you please comment on the priority and why this is so urgent? What are the expected timelines from your side?
It is an enhancement, which will facilitate the data input, but I do not see it as something critical.

Thanks in advance!

Best Regards,
Nikolay

**Comment by 2bno1** [comment]
@nikolay-kolarov I discussed with PM and she said the auto-complete functionality is a nice-to-have feature. I changed the priority to Medium. Thanks.
