### ISSUE TITLE
[BUG][SF][UI5-Dialog][High priority] The head and bottom height of ui5-dialog component are not correct 

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents#3497]
**Dear colleagues,**
I am from SuccessFactors Web Experience Shanghai team.

**Bug Description:**
The head and bottom height of ui5-dialog component are not correct.

**Current Behavior:**
The head height of ui5-dialog now is 48px in both cozy and compact mode.
The footer height of ui5-dialog now is 43px in compact mode and 53px in cozy mode

**Expected Behavior:**
Both the head height and footer height of ui5-dialog should be 40px in compact mode
Both the head height and footer height of ui5-dialog should be 44px in cozy mode

**Comment by gmkv** [comment]
Hi @SAP/ui5-webcomponents-topic-rd 
The header that comes with the dialog's property "header-text" has incorrect height in Cozy/Compact. Should be 40px in compact and 44px in cozy.

https://codesandbox.io/s/ui5-webcomponents-forked-qgg1d?file=/index.html

Regarding the slots for header and footer, @sfsf-xweb-sh , they will be sized to whatever elements you provide them with. They are not set with one particular height. In the linked sample above, I've shown that you can set text in the footer, and the footer will be only as tall as the containing elements. You would have to style the elements that you provide yourself.

**Comment by sfsf-xweb-sh** [comment]
Hi @gmkv 

cozy 44x compact 40px should be the feature of ui5-dialog component.
You can see this link: https://sapui5.hana.ondemand.com/#/entity/sap.m.Dialog/sample/sap.m.sample.Dialog

**Comment by gmkv** [comment]
Hi @sfsf-xweb-sh 

We will fix the height for Cozy/Compact when the property `header-text` is used. In that case, the dialog provides its own "internal" header and we can know for sure what is the content inside of that header, and we can style it safely.

However, when using slots - we wouldn't know for certain what elements you provide in this slot, so we can't assume a specific height/size. The styling of the slots header/footer then should be done by the application developer.

Regards,
Georgi

**Comment by sfsf-xweb-sh** [comment]
Hi @gmkv 
Thanks !
