### ISSUE TITLE
`<ui5-responsive-popover placement-type="Top">` visual issue with pointer

### ISSUE THREAD

**Issue by codefactor** [SAP/ui5-webcomponents#3500]
### **Bug Description**
The pointer is in the wrong place when placement-type is Top for `<ui5-responsive-popover>`

### **Expected Behavior**
The pointer should be on the bottom

### **Steps to Reproduce**
1. https://codesandbox.io/s/ui5-webcomponents-forked-kvegi?file=/index.html
2. Click the button
3. See pointer at the top of the popover instead of the bottom

### **Isolated Example**
https://codesandbox.io/s/ui5-webcomponents-forked-kvegi?file=/index.html

### **Context**
- UI5 Web Components version: 0.31.x and newest one
- OS/Platform: {...}
- Browser: {...}
- Affected component: {...}

### **Log Output / Stack Trace / Screenshots**
![image](https://user-images.githubusercontent.com/730310/125550514-919db4b0-5980-42dd-8296-80d9dcb2c128.png)

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SuccessFactors
- Bussiness impact: {...}

**Comment by alexandar-mitsev** [comment]
Hello @SAP/ui5-webcomponents-topic-rd ,

This is a reproducible issue with ui5-responsive-popover.

Regards
