### ISSUE TITLE
`<ui5-shellbar>` company logo display issues

### ISSUE THREAD

**Issue by codefactor** [SAP/ui5-webcomponents#3501]
### **Bug Description**
The `<ui5-shellbar>` supports a logo slot, where we can put some custom HTML with an image tag. At various screen sizes the following issues can be noticed:

1. The `primary-title` is unnecessarily reduced in size, though there is available space for the text to be displayed
2. The logo chevron icon is not always displayed properly
3. The logo itself is unnecessarily cropped

NOTE: The fact that the "co-pilot" icon is not enabled is probably contributing to this issue. It appears that the co-pilot icon is take up space though it is not being used.

### **Expected Behavior**
1. If there is enough space to show the entire text of the `primary-title` then it should be displayed
1. When the primary-title is removed and only the logo is visible, the entire logo should always be displayed, and the chevron icon should appear next to it.

### **Steps to Reproduce**
1. Go to https://codesandbox.io/s/ui5-webcomponents-forked-9wo51?file=/index.html

### **Isolated Example**
https://codesandbox.io/s/ui5-webcomponents-forked-9wo51?file=/index.html

### **Context**
- UI5 Web Components version: all, but please downport to 0.31.x
- OS/Platform: {...}
- Browser: {...}
- Affected component: {...}

### **Log Output / Stack Trace / Screenshots**
![image](https://user-images.githubusercontent.com/730310/125560430-68513d3d-3af3-4d16-a387-9d28410bf161.png)
![image](https://user-images.githubusercontent.com/730310/125560447-9f79e606-30b2-4d7b-aafe-3fee851d4270.png)
![image](https://user-images.githubusercontent.com/730310/125560464-368c1844-95d8-4a8b-902b-016e891cbbf7.png)

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SuccessFactors
- Bussiness impact: {...}

**Comment by alexandar-mitsev** [comment]
Hi @SAP/ui5-webcomponents-topic-p ,

The bug which I see in this issue is that the co-pilot takes space when it is not visible.
Other change which can be considered is if the left side should be allowed to take more than 50% of the shell bar.

@codefactor If the co-pilot does not take the space, this will still not fix the problem. The logo is too large and it will always be kind of problematic I think.

Regards,
Alexandar Mitsev

**Comment by codefactor** [comment]
@alexandar-mitsev ,
While, yes, the large logo might still have issues at smaller resolutions; however, we need to support logos of this size (they are uploaded by customer and out of our control generally speaking) and therefore we should do our best to utilize the amount of space that is available. I suspect that if you solve the co-pilot issue the display issues will reduce greatly, and we will be able to have a usable header at many other resolutions.

The logo that is displayed in this sample, by the way, is the default successfactors logo that we would display if the customer did not upload any logo.
