### ISSUE TITLE
[URGENT][BUG][UI5-Table][UI5-List][Badge]Inner ui5-hidden-text element will result the error rendering of ui5-table, ui5-list in RTL mode

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents#3503]
**Dear colleagues,**
I am from SuccessFactors Web Experience Shanghai team.

Bug Description:
Inner ui5-hidden-text element in Badge and ui5-li-groupheader will lead to the error rendering of **ui5-table and ui5-list** component in RTL mode. **ui5-table and ui5-list** will render the unnecessary scroll bar in RTL mode

Expected Behavior:
**ui5-table and ui5-list** will not render the unnecessary scroll bar in RTL mode 

Reproduce step:
1. goto [https://github.wdf.sap.corp/pages/xweb/assignment/app.html?mock&sap-ui-rtl=true#/assignment-detail/ao/2](https://github.wdf.sap.corp/pages/xweb/assignment/app.html?mock&sap-ui-rtl=true#/assignment-detail/ao/2)
2. switch to Applicants panel
3. this website contains the source map

![Screen Shot 2021-07-14 at 5 30 34 PM](https://user-images.githubusercontent.com/78520316/125599439-d2c957b5-e787-46dc-b958-d37e7cf72c9d.png)

![Screen Shot 2021-07-14 at 1 30 52 PM](https://user-images.githubusercontent.com/78520316/125598135-7d546488-3ddd-491a-8f00-eba7d494bdfd.png)

**Comment by vladitasev** [comment]
Hello @sfsf-xweb-sh 

Just opened the page and I can see no horizontal scrollbar:
![image](https://user-images.githubusercontent.com/15844574/125737609-c81149a3-030e-4fc6-a7f2-62c7317f6749.png)

I tried resizing or opening on phone, still I get no horizontal scrollbar.

Regards,
Vladi

**Comment by alexandar-mitsev** [comment]
Hi @SAP/ui5-webcomponents-team ,

I could reproduce the issue on Chrome on Windows.
The scroll really seems to appear because of the ui5-hidden-text styles. Specifically the left: -1000px. If replaced with right: -1000px for rtl the scroll is gone.

Regards,
Alex

**Comment by sfsf-xweb-sh** [comment]
Hi @vladitasev @alexandar-mitsev 

You can reproduce this bug on chrome

**Comment by ilhan007** [comment]
Fixed with 0.31.18
