### ISSUE TITLE
ui5-panel: expose expand/collapse animation speed as a configurable attribute

### ISSUE THREAD

**Issue by agauyeung** [SAP/ui5-webcomponents#3505]
### **Feature Request Description**
Currently, the ui5-panel has its own internal setting for animation speed when expanding or collapsing. This is not configurable by developers using this web component.

### **Proposed Solution**
I would like to propose exposing the animation speed so that it can be configured by developers.

### **Proposed Alternatives**
No alternatives as this is internal to the web component.

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)
- Organization: SuccessFactors

**Comment by ilhan007** [comment]
FYI @SAP/ui5-webcomponents-topic-rl 
 
The UX team of SFSF initially requested the animation speed of Panel collapsing/expanding to be configurable, but the animation speed is something strictly defined in Fiori 3 and defined in such way to be consistent with the animations of other components. And this is what we discussed offline with the author of the issue.

For now, the issue will remain open until the author communicates the above with the SFSF UX team.

Meanwhile, @SAP/ui5-webcomponents-topic-rl  could you please check and confirm that the animation speed is as specified?

BR,
ilhan

**Comment by hristop** [comment]
Hi @agauyeung ,

The animations in UI5 and in the web components are based on a central specification which thrives for similar experience and consistency throughout the framework. 
Can you please provide us more details about your use case and how and where this setting will be beneficial. 

For now we do not see need to expose such a property and making this particular setting configurable. 

Best Regards,
Hristo

**Comment by agauyeung** [comment]
Hi @hristop , our team's UX will be reaching out soon regarding this. Thanks!

**Comment by stoehr** [comment]
@hristop and @ilhan007, we see for the [UI5 framework's Panel](https://openui5.hana.ondemand.com/api/sap.m.Panel) implementation that there exists an `expandAnimation` boolean property which, when `false`, will turn off the animation.  Can the UI5 WC's Panel have a similar property, so that there is similar support between the UI5 framework and the UI5 WC?

**Comment by ilhan007** [comment]
Hello @stoehr today together with @hristop we will go trough this requirement for a new  property  `expandAnimation` in the ui5-panel web component (similar to sap.m.Panel) and update you afterwards.

FYI @nikolay-kolarov @SAP/ui5-webcomponents-topic-rl

**Comment by ilhan007** [comment]
Hello @stoehr 
we had a brief discussion on the topic with @hristop and we find the feature request reasonable.
The item will be presented to the team according to the team's plan/development process and dev capacity.

We will keep you updated on the next steps.

**Comment by stoehr** [comment]
Thanks @ilhan007 and @hristop!

**Comment by ilhan007** [comment]
Hi @stoehr there is a new property, called noAnimation and it will be available with the next 0.31 patch, we will update you once it's in npm. Most probably next Mon or Tue.

With the new property, you will be able to turn on/off the Panel's toggle animation as requested.

Thank you @hristop and @niyap for the quick implementation of the feature.

BR, ilhan

**Comment by stoehr** [comment]
Thanks!
