### ISSUE TITLE
The link to the theme designer is broken

### ISSUE THREAD

**Issue by thedrow** [SAP/ui5-webcomponents#3515]
### **Issue Description**
The [link](https://sap.github.io/ui5-webcomponents/playground/docs/customtheming/) in the documentation to the theme designer is broken.

Is there any documentation on how to theme UI5 manually?

### **Issue Type**

- [ ] Documentation is unclear
- [x] Documentation is incorrect
- [ ] Documentation is missing
- [ ] Other

**Comment by ilhan007** [comment]
Hello @thedrow, unfortunately the Theme Designer does not provide a free version. 
We will update the whole section and most probably we will provide a light-weight tool to generate custom themes.

In general, this is the list of CSS Vars, used inside the components:
https://github.com/SAP/theming-base-content/blob/master/content/Base/baseLib/sap_fiori_3/css_variables.css

If you load a separate style tag in the head with these CSS vars, with changed values, you will be able to change the appearance of the components.

**Comment by untoldbyte** [comment]
bump

**Comment by thomas-br** [comment]
@untoldbyte & @thedrow 
For the time being you could make use of the SAP BTP trial, where you should be able to try out the Launchpad Service, which includes the Theme Designer.

https://help.sap.com/viewer/09f6818d8e064537973102d6289e2aca/LATEST/en-US/26c100668d0047af9db9141ab1d92571.html
