### ISSUE TITLE
[SF][ComboBox]:Missing  Padding Between ComboBoxGroupItem and separate line

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents#3522]
**Describe the bug**
Hi team,
Padding of comboBoxGroupItem is not proper in compact theme, Could you take a look and fix it in next release if possible.
![image](https://user-images.githubusercontent.com/78520316/126250066-a1a7597b-830e-4e48-9839-067b37f37068.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents-react` version: 0.31.12

Expect behavior:
![Screen Shot 2021-07-20 at 9 56 04 AM](https://user-images.githubusercontent.com/78520316/126250510-eb5a31a4-8bc4-44f8-9a53-fbbed746a736.png)

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-rl could you check if you need to update the padding for the ComboBoxGroupItem text in compact?

**Comment by sfsf-xweb-sh** [comment]
Hi @Lukas742 
The version you post are right, thanks for correcting me.
