### ISSUE TITLE
DatePicker tooltip issue

### ISSUE THREAD

**Issue by ghristanov** [SAP/ui5-webcomponents#3534]
Hello colleagues,

we received the following incident, which was reported in the openui5 project:
https://github.com/SAP/openui5/issues/3303

Controls inheriting from the DatePicker have this issue as well.

Best regards,
Georgi

**Comment by tsanislavgatev** [comment]
Hello colleagues,

This is behaviour that we inherit from the input component. Can you please take a look?
It's reproducible in the following scenario:
<ui5-input style="width: auto" id="input-disabled" placeholder="Disabled one ..." title='name two'>
	<ui5-icon slot="icon" name="appointment-2" accessible-name="name one" show-tooltip input-icon></ui5-icon>
</ui5-input>

Best Regards,
Tsanislav

**Comment by MapTo0** [comment]
Dear colleagues,

Based on [Fiori Design Guidelines for using tooltips](https://experience.sap.com/fiori-design-web/using-tooltips/) tooltips should no be attached to elements that can be labeled. Based on that info I would suggest you to fix datepicker's example and notify reported that such usage of title attribute is not recommended linking our general accessibility guidelines.

Regards,
Martin
