### ISSUE TITLE
[URGENT][SF][ui5-responsive-popover][ui5-table-column] The ui5-responsive-popover can not render correctly with ui5-table-column

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents#3536]
**Dear colleagues,**
I am from SuccessFactors Web Experience Shanghai team.

**Bug Description:**
The ui5-responsive-popover can not render correctly with ui5-table-column.
ui5-responsive-popover cannot completely cover ui5-table-column
<img width="456" alt="Screen Shot 2021-07-26 at 11 40 53 AM" src="https://user-images.githubusercontent.com/78520316/126930440-22d8bb52-ad40-44cc-8b62-c7d5587235cd.png">

**Reproduce Step**
1. goto [https://github.wdf.sap.corp/pages/xweb/assignment/app.html?mock#/assignment-detail/ao/2](https://github.wdf.sap.corp/pages/xweb/assignment/app.html?mock#/assignment-detail/ao/2)
2. click applicants tab
3. click the '?' icon in Match column
4. you will see the bug

**Comment by yanaminkova** [comment]
Hello @SAP/ui5-webcomponents-topic-rd,

I am forwarding this issue to you, because it is related with ui5-responsive-popover.
Would you please have a look at it?

Regards,
Yana

**Comment by gmkv** [comment]
Hi @SAP/ui5-webcomponents-topic-rd 
This issue is caused by the table cell component, which has `z-index: 99` set to it.
Because of that, any children will inherit the parent's z-index, regardless of what z-index value is later set to the children - the popover will have higher z-index, but it won't work.
This issue is similar to #3426 - check the proposed solution in it.

**Comment by MapTo0** [comment]
Dear reporter,

Popups like Popover, Dialog and Responsive Popover should not be nested inside other components.
Best practice is to render them as top level component.
In some frameworks such as React there are concepts to help you build that.
You can check [React Portals](https://reactjs.org/docs/portals.html) API.

Regards,
Martin

**Comment by sfsf-xweb-sh** [comment]
Hi @MapTo0 
This issue should be fixed inside component

**Comment by ilhan007** [comment]
Hello @sfsf-xweb-sh did you try the proposal from @MapTo0 above and render the popup top-level, this way it's going to be displayed over the page's content as expected.

**Comment by sfsf-xweb-sh** [comment]
Hi @ilhan007 
I have tried render the ui5-responsive-popover at top-level and it works
