### ISSUE TITLE
TabContainer: box shadow behavior

### ISSUE THREAD

**Issue by davischmitz** [SAP/ui5-webcomponents#3548]
**Is your feature request related to a problem? Please describe.**

I'm trying to upgrade the ui5-webcomponents-react to the latest version in our project but I'm facing an issue with the TabContainer's box-shadow. 

In the previous version that we used (ui5-webcomponents v1.0.0-rc.10 and ui5-webcomponents-react v0.12.0), the TabContainer didn't seem to have a box-shadow at the top. This way I was able to integrate a Bar component and a TabContainer without any dividing lines just by removing the Bar's box-shadow. This is shown in this [CodeSandbox](https://codesandbox.io/s/doms9?file=/src/App.js).

![image](https://user-images.githubusercontent.com/11902967/127150079-c592dbbb-ebeb-45db-af18-e2813e295b27.png)

Using the latest version of webcomponents-react, the TabContainer seems to have a box-shadow at the top, so I cannot integrate it with the Bar component without a line appearing. Tried to pass a css class to the TabContainer to remove the box-shadow but it didn't have any effect. Example in this [CodeSandbox](https://codesandbox.io/s/intelligent-hertz-b3pmt?file=/src/App.js).

![image](https://user-images.githubusercontent.com/11902967/127150125-67f04470-50eb-4a25-8340-9f90a2aaa46f.png)

**Describe the solution you'd like**
I'd like a way to configure the box shadow of the TabContainer and possibly remove it so that I'm able to achieve the result in the first CodeSandbox. If there's already a way maybe I'm missing it.

**Comment by yanaminkova** [comment]
Hello @ilhan007 , could you please have a look at this feature request?

**Comment by ilhan007** [comment]
Hello @davischmitz 
the box-shadow implemented by design, however there are ways to change it. The box-shadow is defined with this style,
applied in the TabContainer's ShadowDOM:

```css
.ui5-tc__header {
	box-shadow: var(--sapContent_HeaderShadow);
}
```

To change the box-shadow, you can:

- overwrite the CSS variable

This is the original value:
```css
--sapContent_HeaderShadow: 0 0 0.25rem 0 rgba(0,0,0,0.15), inset 0 -0.0625rem 0 0  var(--sapObjectHeader_BorderColor)
```

you can overwrite it
```html
<ui5-tabcontainer  style="--sapContent_HeaderShadow: 0 0 0 0;">
```


- use the "addCustomCSS" method to insert styles
```js
import { addCustomCSS } from "@ui5/webcomponents-base/dist/Theming.js";
```

```js
addCustomCSS("ui5-tabcontainer", ".ui5-tc__header { box-shadow: none; } ");

```
BR,
ilhan
