### ISSUE TITLE
Tooltip missing if Side Navigation is collapsed

### ISSUE THREAD

**Issue by asoahc** [SAP/ui5-webcomponents#3549]
### **Feature Request Description**
If you are using Side Navigation for navigation then you can expand the component to see icon and text of your navigation target. If you want to navigate via a collapsed Side Navigation you only see the icon. It might be great if a tooltip of the text attribute will be displayed if the Side Navigation is collapsed and an entry will be hovered.

### **Proposed Solution**
While the Side Navigation is expanded nothing needs to be changed.
If the Side Navigation is collapsed an tooltip with the defined text attribute will be displayed als tooltip. 

It could be possible to define a new attribute like 'show-tooltip' to display tooltips at the collapsed state.
Or the value of the text attribute will be automatically displayed as tooltip if the Side Navigation is collaped.
If the Side Navigation is expaned, the tooltip is not necessary.

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by yanaminkova** [comment]
Hello @ilhan007 , could you please have a look at this feature request?

**Comment by olannyv** [comment]
Internal team jira backlog item # 2619 is created to follow up according priority and capacity
