### ISSUE TITLE
ui5-wizard shows aria text

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents#3551]
### **Bug Description**
The Wizard is showing an aria text (e.g. `To activate press space bar or enter`)
<img width="644" alt="Screenshot 2021-07-27 at 13 33 43" src="https://user-images.githubusercontent.com/8775211/127146966-4dcc7405-9f0a-4e88-a736-af0fccda6940.png">

### **Expected Behavior**
Aria Texts should not be visible to end users

### **Steps to Reproduce**
1. Open https://sap.github.io/ui5-webcomponents/master/playground/components/Wizard/

### **Isolated Example**
https://sap.github.io/ui5-webcomponents/master/playground/components/Wizard/

### **Context**
- UI5 Web Components version: master branch (1.0.0-rc.15 candidate)

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-rl could you take a look of this issue. The invisible text is actually visible.
Perhaps missing "@import "./InvisibleTextStyles.css";" in the Wizard.css

**Comment by ilhan007** [comment]
The hidden text is added with this PR
https://github.com/SAP/ui5-webcomponents/pull/3443

but the required styles are not imported.

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-rl could you review the following fix: https://github.com/SAP/ui5-webcomponents/pull/3552 for this issue.
