### ISSUE TITLE
Calendar: Accessibility Issue

### ISSUE THREAD

**Issue by angelzbg** [SAP/ui5-webcomponents#3555]
### Description
The Calendar's Month(Year) view not opening on pressing SPACE.

### Observed behavior: 
The month picker and year picker views do not open with the ‘SPACE’ (with ENTER it works fine.)

### Expected Behavior: 
The month picker and year picker views should open via both the ‘SPACE’ and ‘ENTER’ keys.
For reference check the Calendar in OpenUI5:
https://openui5nightly.hana.ondemand.com/entity/sap.ui.unified.Calendar/sample/sap.ui.unified.sample.CalendarSingleDaySelection

The full description of the issue (URL, credentials, steps) can be read here:
[ACC-270.6_Central Business Configuration 2108_Button_ Activation](https://support.wdf.sap.corp/sap/bc/contentserver/001/ACC-270?get&pVersion=0046&contRep=CRMORDER&docId=0090FAE68F161EDBBBE92D5557688113&compId=ACC-270.6_Central%20Business%20Configuration%202108_Button_%20Activation%20issue%20month%20and%20year%20picker%20button.docx&accessMode=r&authId=CN%3DBCS&expiration=20210728124052&secKey=MIHxBgkqhkiG9w0BBwKggeMwgeACAQExCzAJBgUrDgMCGgUAMAsGCSqGSIb3DQEHATGBwDCBvQIBATATMA4xDDAKBgNVBAMTA0JDUwIBADAJBgUrDgMCGgUAoF0wGAYJKoZIhvcNAQkDMQsGCSqGSIb3DQEHATAcBgkqhkiG9w0BCQUxDxcNMjEwNzI4MTA0MDUyWjAjBgkqhkiG9w0BCQQxFgQUvLd8LUZJmVLT7i9LzW1pS3muV1IwCQYHKoZIzjgEAwQuMCwCFERqVOJsHWUWSLEcLejBAmy4GkDvAhQ4h0dTe4oVVx2QJl5glsRkWj%2FNbQ%3D%3D
)

### Additional Context
While reproducing the issue I've found that **onSelectedDatesChange** function is being called when the Enter key is pressed when the month pickers are focused. When Spacebar key is pressed in the same scenario it doesn't - works as expected.

### Steps to reproduce
1. https://sap.github.io/ui5-webcomponents/master/playground/components/Calendar/
2. Tab until focus on on Month (Year) button in the Calendar header
3. Press SPACE
4. The Month (Year) view is opened and closed immeadiately

### Context
UI5 Web Components version: master
Browser (if relevant): {...} Chrome
Affected components (if known) ui5-calendar

**Comment by yanaminkova** [comment]
Hello @SAP/ui5-webcomponents-topic-b,

I am forwarding this issue to you, because it is related with ui5-calendar.
The month picker and year picker buttons, does not open their corresponding dialogs on space down.

Could you please have a look at it?

Best regards,
Yana
