### ISSUE TITLE
ShellBar: The focus indication provided for the ‘SAP’ Logo covers only 3 sides

### ISSUE THREAD

**Issue by angelzbg** [SAP/ui5-webcomponents#3567]
### Description
The focus indication provided for the ‘SAP’ Logo covers only 3 sides (top, bottom, and right side)
https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-shellbar--default-story

### Expected Behavior: 
A strong focus indication covering all 4 sides must be provided for all the UI elements so that end user can easily identify the place of focus on the screen.

### Steps to reproduce
1. Go to https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-shellbar--default-story
2. Tab until focus on ShellBar Logo
3. All 4 sides are not covered

### Context
Browser (if relevant): {...} Chrome

[ACC-271.1_Central Business Configuration 2108_Logo_focus indication does not cover all sides](https://support.wdf.sap.corp/sap/bc/contentserver/001/ACC-271?get&pVersion=0046&contRep=CRMORDER&docId=0090FAE68E561EDBBBC66EFF2222810F&compId=ACC-271.1_Central%20Business%20Configuration%202108_Button_focus%20indication%20does%20not%20covers%20all%20sides.docx&accessMode=r&authId=CN%3DBCS&expiration=20210729150736&secKey=MIHxBgkqhkiG9w0BBwKggeMwgeACAQExCzAJBgUrDgMCGgUAMAsGCSqGSIb3DQEHATGBwDCBvQIBATATMA4xDDAKBgNVBAMTA0JDUwIBADAJBgUrDgMCGgUAoF0wGAYJKoZIhvcNAQkDMQsGCSqGSIb3DQEHATAcBgkqhkiG9w0BCQUxDxcNMjEwNzI5MTMwNzM2WjAjBgkqhkiG9w0BCQQxFgQUm44gvTrLrehmVVTe4aqhKx1534swCQYHKoZIzjgEAwQuMCwCFHRa0WoCzSFS0qnPg1BTfyHb1p0QAhQyZH2L5eGYFRV77whmOyj%2FdYZ77g%3D%3D)

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-p it's also reproducibble within our Playground
https://sap.github.io/ui5-webcomponents/master/playground/components/ShellBar/

<img width="778" alt="Screenshot 2021-07-29 at 20 48 46" src="https://user-images.githubusercontent.com/15702139/127540551-3fe56627-c0d5-4900-add1-99907a5dbf95.png">
