### ISSUE TITLE
RadioButton : Radio Button_Group label not read and required information not conveyed

### ISSUE THREAD

**Issue by kolew96** [SAP/ui5-webcomponents#3569]
Description
On accessing the radio buttons, the group label is not associated.
If the radio buttons are marked as required that should be conveyed to the user.
https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-radiobutton--default-story

Observed behavior:
On accessing the radio buttons, the group label is not associated.
When the radio buttons are marked as required which is not conveyed to the user.

Expected Behavior:
On accessing the radio buttons, the group label should be associated.
When the radio buttons are marked as mandatory fields should be conveyed as required to the user.

Steps to reproduce
Go to https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-radiobutton--default-story
Tab until focus on the radio button
The radio button is not associated with its group label

Context
Browser (if relevant): {...} Chrome

Additional Context
[ACC-264.1_Central Business Configuration 2108_Radio Button_Group label not read and required information not conveyed.docx](https://github.com/SAP/ui5-webcomponents-react/files/6900528/ACC-264.1_Central.Business.Configuration.2108_Radio.Button_Group.label.not.read.and.required.information.not.conveyed.docx)

**Comment by plamenivanov91** [comment]
Hello @kolew96 ,

After I navigate to the problematic view described in the word document (https://cbc-corp-master-000.master.cbc.corp.one.only.sap/sap/public/x4/bc/pe/index.html#/catalog (you forgot the catalog at the end)), there is a modal with empty data.

Could you please stabilize the application so we could investigate your exact use case further?

Also it might be useful to isolate the problematic use case in a similar snippet https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html .

Regards,
Plamen Ivanov

**Comment by kolew96** [comment]
Hello @plamenivanov91 ,

Our systems are stabilized already so you could investigate.

Regards,
Krasimir Kolev

**Comment by gmkv** [comment]
FYI @SAP/ui5-webcomponents-topic-rd

**Comment by TeodorTaushanov** [comment]
Hi @kolew96,

When the radio buttons are in group, they need to have the following structure, so they can be read correctly by the screen readers:
```
<div aria-labelledby="radioGroupTitle1" role="radiogroup">
	<ui5-title id="radioGroupTitle1">Title</ui5-title>
	<ui5-radio-button id="testRbtn1" text="Male" name="test"></ui5-radio-button>
	<ui5-radio-button id="testRbtn2"text="Female" name="test"></ui5-radio-button>
</div>
```

We updated our radio button examples.

Best,
Teo
