### ISSUE TITLE
ProgressIndicator Improvement: Split up "value" property into two separate properties "percentValue" and "displayValue" again

### ISSUE THREAD

**Issue by xqtion** [SAP/ui5-webcomponents#3573]
### **Feature Request Description**
Due to changes of the ProgressIndicator's properties, it is not possible to fill the indicator with words anymore. There used to be two properties _percentValue_ and _displayValue - now there is only _value_ which replaced both of them. The problem that arises now is that only numeric values are accepted for _value_ and it will be automatically used to fill the indicator with "_value_ %".

### **Proposed Solution**
I would suggest to split up the value property into two again, so the old behaviour can be recreated again.

### **Proposed Alternatives**
Discussions with Product Owner led to the need to have the progress indicator containing details within the bar. It's also possible to split up this information into two different components (one being ProgressIndicator the other being a text field), but this is not desired, as the old version already introduced a proper working "detailed" progress indicator.

### **Additional Context**
Add other context or screenshots related to the feature request here.
![Screen Shot 2021-07-30 at 13 30 59](https://user-images.githubusercontent.com/16004264/127655854-0cd690f6-906b-47a2-b5ce-2c0fcd345142.png)

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: SAP CBC
- Business impact: Customers cannot see the detailed operating status of the progress indicator (see Screenshot).

**Comment by nnaydenow** [comment]
Internal reference: 5369
