### ISSUE TITLE
Fix InvisibleMessage.js

### ISSUE THREAD

**Issue by vladitasev** [SAP/ui5-webcomponents#3582]
This PR:
https://github.com/SAP/ui5-webcomponents/pull/3192

breaks the project on IE11. The reason is that it accesses the DOM before the framework is  known to have booted. This works by chance with `<script type="module"` but completely breaks the project on IE11 with a normal script tag.

Please create a fix asap. See my comments for more info

Regards,
Vladi

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-rl could you please take a look of this issue and the inline comments in the 
#3192 PR, that caused the issue.
