### ISSUE TITLE
ui5-li-groupheader: no bottom space in compact mode

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents#3606]
### **Bug Description**
There is no bottom space for group header text in compact mode.

### **Expected Behavior**
There should have bottom space for group header text in compact mode.

### **Steps to Reproduce**
1. Go to 'https://github.wdf.sap.corp/pages/xweb/goalmanagementx/app.html?mock&noFirstTimeGuidance'
2. Check group header text in the left panel of page

![2021-08-06_10-37-29](https://user-images.githubusercontent.com/13098801/128448639-735d3494-b750-407e-a264-dcaa714d6241.jpg)

### **Context**
- UI5 Web Components version: {0.31.12}
- OS/Platform: {Mac OS}
- Browser: {Chrome}
- Affected component: {ui5-li-groupheader}

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### **Stakeholder Info** (if applicable)

- Organization: {SAP SuccessFactors}

**Comment by elenastoyanovaa** [comment]
Hello @SAP/ui5-webcomponents-topic-p ,

There seems to be an issue with the alignment of the group header list item in compact mode. As a reference in UI5, the group header list item results in 44px, but in the web components, the height is 31px. Could you please check?

Kind Regards,
Elena

**Comment by ilhan007** [comment]
Hello @GongRichard  the fix is going to be released with 0.31.15 (9-10 Aug)

**Comment by ilhan007** [comment]
Hello @GongRichard Fix is released with 0.31.15
