### ISSUE TITLE
[SF] [ValueState] - The vertical padding of value state is not consistent

### ISSUE THREAD

**Issue by 2bno1** [SAP/ui5-webcomponents#3611]
### **Expected Behavior**
The vertical padding of the value state of ui5-input with suggestion item is consistent to ui5-select which is 0.5625rem (or 9px)

### **Steps to Reproduce**
1. https://codesandbox.io/s/ui5-webcomponents-forked-on84c?file=/index.html
2. Check the vertical padding of the value state of both the ui5-input and ui5-select.

### **Isolated Example**
https://codesandbox.io/s/ui5-webcomponents-forked-on84c?file=/index.html

### **Context**
- UI5 Web Components version: 0.31.14
- OS/Platform: macOS
- Browser: Chrome
- Affected component: ui5-input

### **Log Output / Stack Trace / Screenshots**
![image](https://user-images.githubusercontent.com/1751846/128595025-4c360015-07be-4f4b-ad72-3afe65b149a4.png)
![image](https://user-images.githubusercontent.com/1751846/128595055-08363c2d-3c81-439d-882b-98fa1976e092.png)
### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

- Organization: SuccessFactors

**Comment by GerganaKremenska** [comment]
Hello @ui5-webcomponents-topic-p,
 I am forwarding this issue to you, because there is a diffrence in styling of the value state of Input and Select component.
Check the design and sync the implementation.

**Comment by nnaydenow** [comment]
Hello @SAP/ui5-webcomponents-topic-rl ,

Both components are not align to the spec. From our side ui5-select is fixed with #3655 which is under review.

I'm sending this issue to you to align ui5-input.

Regards,
Nayden

**Comment by ilhan007** [comment]
fixed with 0.31.18
