### ISSUE TITLE
IllustratedMessage: BTPX Illustrations

### ISSUE THREAD

**Issue by AndrianStoikov** [SAP/ui5-webcomponents#3613]
### **Feature Request Description**
Hello we are currently using a custom implementation for `IllustratedMessage` and in some places we are using illustrations from  BTPX. Is it possible to extend the current implementation so we can switch all our illustrations to webcomponents?

### **Proposed Solution**
We would like to have the [BTPX illustrations](https://pages.github.tools.sap/btp-design/fiori-moments-tnt/) in the `IllustratedMessage`

### **Additional Context**
The exact illustrations that we need are `NoApplications` `SessionExpiring` `SessionExpired` `UnsuccessfulAuth`

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: RBSC
- Bussiness impact: {...}

**Comment by nnaydenow** [comment]
Hi @AndrianStoikov,

You can check the linked PR for more information regarding your feature request.

BR,
Nayden
