### ISSUE TITLE
 Third state of the Tree Item

### ISSUE THREAD

**Issue by gabrielRosa** [SAP/ui5-webcomponents#3618]
### **Feature Request Description**
Would you like to provide support for а third state of the Tree Item like Check Box feature?

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

Thanks and regards,
Gabriel

**Comment by GerganaKremenska** [comment]
Hello @gabrielRosa,

We will need more information.
What is your use case for this feature request?
Have you seen it in some othere components?

**Comment by gabrielRosa** [comment]
Hello @GerganaKremenska,

We have some tree with some children pre-selected. However I can not set the parent as selected.

![image](https://user-images.githubusercontent.com/19877645/129370212-226ed74d-2b74-4b4a-8c99-b7f15fa146ff.png)

I saw the feature in this component  https://sapui5.hana.ondemand.com/#/entity/sap.m.CheckBox/sample/sap.m.sample.CheckBoxTriState.

**Comment by nnaydenow** [comment]
Internal reference: BGSOFUIPIRIN-5516
