### ISSUE TITLE
Playground app: issue with styles when switching to RTL

### ISSUE THREAD

**Issue by gmkv** [SAP/ui5-webcomponents#3624]
### **Bug Description**
In RTL, tabs with icons have the text too close to the icon.

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/master/playground/components/TabContainer/?sap-ui-theme=sap_fiori_3&isrtl=true

### **Context**
- UI5 Web Components version: master

### **Log Output / Stack Trace / Screenshots**
![image](https://user-images.githubusercontent.com/22086365/128911386-0234178e-a198-4848-bcf7-38b4b6bec3ff.png)

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by ilhan007** [comment]
Hello @gmkv seems to work now in the master playground

<img width="1165" alt="Screenshot 2021-11-19 at 22 48 38" src="https://user-images.githubusercontent.com/15702139/142689845-670ae498-6c23-484a-b76c-173131c37985.png">
ed

**Comment by gmkv** [comment]
It's still reproducible. Load https://sap.github.io/ui5-webcomponents/master/playground/components/TabContainer/, then change the text direction to RTL from the settings menu on the Playground app.

**Comment by gmkv** [comment]
If it helps tracking down the bug, clicking on the tabs will "fix" the issue.

**Comment by ilhan007** [comment]
Thanks, @gmkv now I could reproduce it!

**Comment by fifoosid** [comment]
This issue is resolved in the master branch. The issue was indeed in the way the Playground was setting RTL
