### ISSUE TITLE
splitter layout?

### ISSUE THREAD

**Issue by alumni** [SAP/ui5-webcomponents#364]
Are any plans to support a splitter layout in ui5-webcomponents? I'm looking for something in the 
lines of sap.ui.layout.ResponsiveSplitter or sap.f.FlexibleColumnLayout from UI5.

**Comment by ilhan007** [comment]
Hello @alumni,
unfortunately we do not plan to provide ResponsiveSplitter, FlexibleColumnLayout or other layout components, at least in the near future.

Our plan is to leave the layouts to the application developers and to provide them the building blocks,
such as: buttons, inputs, datepicker, list, select, etc.

Best,
ilhan
