### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by MisherLiu** [SAP/ui5-webcomponents#3647]
### **Issue Description**
I am wondering how to implement accessibility using UI5 Web Component.
Is there such document developers can reference?
Does UI5 web components cover these accessibility such as screen reader support, high-contrast theming and keyboard handling.

### **Issue Type**
Documentation is missing

**Comment by ilhan007** [comment]
Hello @MisherLiu 

The Accessibility is one of the most important features of the UI5 Web Components.
We implement the Web Content Accessibility Guidelines 2.1 Level AA with both Screen Reader support and Keyboard Handling support.The components have the required ARIA attributes to form the required speech output and although we try to support as many as possible screen readers, we officially support the Chrome + Jaws 2021 environment.

Regarding the Keyboard Handling, if you go to the overview section of the component, you can read what keyboard handing it has, for example:
https://sap.github.io/ui5-webcomponents/master/playground/components/DatePicker/
<img width="1145" alt="Screenshot 2021-08-13 at 08 50 10" src="https://user-images.githubusercontent.com/15702139/129311022-18e6a99a-7e0e-40c7-9ed2-8a916227ef07.png">

We provide several built-in themes, including High Contrast Black and High Contrast White.
To switch the theme you can use `script` configuration or `method call`, you can learn about this here:
https://sap.github.io/ui5-webcomponents/master/playground/docs/configuration/

You can also try out the themes by the settings dialog at the right side of the page
https://sap.github.io/ui5-webcomponents/master/playground/components/DatePicker/
<img width="1374" alt="Screenshot 2021-08-13 at 08 53 52" src="https://user-images.githubusercontent.com/15702139/129311309-c7c53f93-5613-4a04-b233-bef8ac56a39f.png">

We also have specs for each component, that developers use when implementing a component, but the specs are internal. Perhaps a page in the Documentation section about the Accessibility support would be nice, I will check with the colleagues. Nevertheless, you can be sure that the Accessibility support of the UI5 Web Components is a very good level and we constantly invest efforts on improving it.

**Comment by ilhan007** [comment]
Hi @MisherLiu 
we created a dedicated issue for creating an Accessibility page.
https://github.com/SAP/ui5-webcomponents/issues/3652

You can track the progress within the new issue. It will be forwarded to the responsible colleagues to process it.
Closing this one.


BR,
ilhan
