### ISSUE TITLE
ui5-datepicker and ui5-input events` names are inconsistent

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents#365]
**Describe the bug**
The ui5-datepicker fires "liveChange", while the ui5-input fires "input" event, which is a bit misleading/confusing for app developers and looks inconsistent.

**Expected behaviour**
To make the events` names consistent.

**Context**
https://github.com/SAP/ui5-webcomponents-sample-vue/pull/14

**Comment by pskelin** [comment]
While on the same topic, let's discuss if the input event of the composed element should be stopped. Otherwise the user of the datepicker will receive two input events - one from ui5-datepicker and one from the composed ui5-input.
