### ISSUE TITLE
ui5-table: setting min-width without demand-popin should hide data and headers

### ISSUE THREAD

**Issue by pskelin** [SAP/ui5-webcomponents#3659]
### **Bug Description**
Check the example below: a table, two of the columns have `min-width="320"`, but no `demand-popin`. Resize below 320px. Headers disappear, but the data columns remain. If `demand-popin` is set, they correctly drop and are not separate columns.

### **Expected Behavior**
If a `min-width` is set, and `demand-popin` is not present, both header and data should disappear.

### **Isolated Example**
https://codesandbox.io/s/ui5-webcomponents-forked-3gwo5?file=/index.html

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-rl could you take over
