### ISSUE TITLE
Combobox: autocompletion on second keystroke

### ISSUE THREAD

**Issue by d3xter666** [SAP/ui5-webcomponents#3666]
### **Bug Description**
The ComboBox autocompletion does not work properly on the second and following keystroke(s).

### **Expected Behavior**
If the entered text matches some of the items, there should be an autocomplete and highlighting

### **Steps to Reproduce**
1. https://sap.github.io/ui5-webcomponents/master/playground/components/ComboBox/
2. On the first ComboBox start typing, first "I" -> The autocompletion works properly
<img width="233" alt="Screenshot 2021-08-16 at 11 27 23" src="https://user-images.githubusercontent.com/3379948/129534445-05ba3125-6d2e-4557-9753-c15876f96ef3.png">
3. ... then type "t" -> the autocompletion breaks
<img width="230" alt="Screenshot 2021-08-16 at 11 28 12" src="https://user-images.githubusercontent.com/3379948/129534520-3a495c57-94bb-4928-a88b-80cbbfb68252.png">

**Comment by ndeshev** [comment]
Fixed with #3495
