### ISSUE TITLE
Combobox: Cannot select item from filtered list

### ISSUE THREAD

**Issue by d3xter666** [SAP/ui5-webcomponents#3667]
### **Bug Description**
When a user types something in the input field of the combobox, he/she is not able to select an item from the list via keyboard.

### **Expected Behavior**
The user should be able to select items from the List freely.

### **Steps to Reproduce**
1. https://sap.github.io/ui5-webcomponents/master/playground/components/ComboBox/
2. Scroll to **_Filters (StartsWithPerTerm(default), StartsWith, Contains)_** section
3. In the first ComboBox type "Bu"
4. Try to navigate with the keyboard to select "Bulgaria" from the list.
<img width="225" alt="Screenshot 2021-08-16 at 11 33 46" src="https://user-images.githubusercontent.com/3379948/129535175-679c9f59-6583-4173-9600-e021894efa3a.png">

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-rl as @d3xter666 Yavor suggests, the issue seems severe, could you take this  one with priority.

**Comment by ndeshev** [comment]
Fixed with #3495
