### ISSUE TITLE
MultiComboBox: Tokenizer cuts the last token

### ISSUE THREAD

**Issue by d3xter666** [SAP/ui5-webcomponents#3672]
### **Bug Description**
When there are multiple items selected in the MultiComboBox, in some cases the last tokenized item might be cut and impossible to fully be read.

### **Expected Behavior**
A clear and concise description of what you expect to happen.

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/master/playground/components/MultiComboBox/
2. Scroll to **_MultiComboBox with Value State_**
3. For the first MultiComboBox select all the items
4. Focus out
5. Focus in the input 
6. Start navigating through items (arrow left/right) with the keyboard only
7. The last token "Success" is cut and could not be displayed fully
<img width="305" alt="Screenshot 2021-08-16 at 12 03 13" src="https://user-images.githubusercontent.com/3379948/129539261-8c946fb4-ea15-4513-8e33-f4067c9204c4.png">

**Comment by niyap** [comment]
Hello Colleagues,

There is a BLI in progress which includes fixing the reported issue as well.
As a result, I am closing the incident!

Kind Regards,
Niya
