### ISSUE TITLE
Feature request: Time Picker

### ISSUE THREAD

**Issue by sunnyyadav100** [SAP/ui5-webcomponents#3678]
### **Feature Request Description**
SAP Fiori compliant Time Picker - https://ui5.sap.com/#/entity/sap.m.TimePicker/sample/sap.m.sample.TimePicker
### **Proposed Solution**
https://ui5.sap.com/#/entity/sap.m.TimePicker/sample/sap.m.sample.TimePicker

### **Additional Context**
Add other context or screenshots related to the feature request here.

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: SAP Ariba
- Bussiness impact: Medium

**Comment by unazko** [comment]
Hello @sunnyyadav100,

You want to use same design for ui5-time-picker as in the OpenUi5 project, where there was new design introduced,
so that time picker popover displays clocks instead of sliders?

Best Regards,
Boyan

**Comment by sunnyyadav100** [comment]
Yes, that is correct.

**Comment by petyabegovska** [comment]
What remains: After the initial redesign of the Time Picker component, we need to enhance the mobile view in the scenario where the input is clicked and a popover opens with standalone inputs for time, minutes, seconds (depending on the case). The reason behind that is in that way a numeric keyboard will be shown.

**Comment by DMihaylova** [comment]
In order to have the correct milestones of the different parts, I'm closing this one (implemented as part of 1.14) and the mobile enhancement could be tracked here: https://github.com/SAP/ui5-webcomponents/issues/7382
