### ISSUE TITLE
UI5-elements: 2108 CBC: Unable to create stable locator for element located in shadow root

### ISSUE THREAD

**Issue by sap-dzmitrybutsko** [SAP/ui5-webcomponents#3679]
### **Bug Description**
There are no stable IDs for the elements located in shadow roots on the CBC project

### **Steps to Reproduce**
1. Go to the CBC system https://tenant-1.dev-local-test1-ui-e2e-regression.cbc.only.sap/sap/public/ap/smeui/repository/SAP_UI/HTMLOBERON5/client.html?sap-b-automation=true
2. Login with user ID "tester" and password "Welcome1"
3. Open PE page https://tenant-1.dev-local-test1-ui-e2e-regression.cbc.only.sap/sap/public/x4/bc/pe/index.html#/
4. Inspect any tab element
![tabs](https://user-images.githubusercontent.com/89077146/129715550-6bd1a0ed-9701-4cc5-84e5-a68eaf263d16.png)
5. Observe the tag and its attributes related to the element

### **Actual Behavior**
All the elements are located in the shadow roots. And these elements don't have any unique, stable IDs or attributes related to the elements. IDs displayed in the shadow root are auto-generated with random numbers. The only way, for now, is to get the attribute with the element number in the list (f.e. 1,2,3, etc.), but this approach is very unstable and will a lot of problems in the future. As for now, all the places where shadow roots are presented it's unable to create a stable locator for the test automation:
![no unique Ids in shadow roots](https://user-images.githubusercontent.com/89077146/129715448-df9fd58f-1298-4e8b-beb7-3ef4655f10e4.png)

### **Expected Behavior**
All the elements with interaction on the system should have stable IDs or any other stable attributes (f.e. button elements, elements in dropdowns, list, etc.). We should have a solution to manage this problem as it makes some parts of the application untestable

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

### **Stakeholder Info** (if applicable)

- Organization: {SAP}
- Project {CBC}
- Business impact: {Inability to write stable UI tests for the system. As a result, the system is become untestable after adding UI-5 components}

**Comment by unazko** [comment]
Hello @SAP/ui5-webcomponents-topic-rd,

The ui5-tabcontainer list item IDs are autogenerated, unique in the current shadow root and they are not stable,
which obstructs creating of a stable locator for them and therefore stable automation testing of the application.

Best Regards,
Boyan

**Comment by kskondov** [comment]
Hello @sap-dzmitrybutsko,

For the tab components in ui5-tabcontainer there is a property "stableDomRef" of type string which can be set by the app developer for example <ui5-tab stable-dom-ref="products-dom-ref" text="Products"> and later accessed from the tab container by `getStableDomRef("products-dom-ref")`. And this can be used for automated tests as well.

I will close this issue now but if this solution is not suitable for you or if you have any question you can re-open it.

Best Regards,
Konstantin

**Comment by fifoosid** [comment]
Hi @sap-dzmitrybutsko 

We are currently reworking the stableDomRef concept in this #3539 & recently the API might be changed in order to be easier for consumption.
