### ISSUE TITLE
Please report on bundle size

### ISSUE THREAD

**Issue by bcullman** [SAP/ui5-webcomponents#368]
**Describe the documentation issue**
bundlephobia can report on package size, if your package.json has a entry point defined. this package currently does not. See:
https://bundlephobia.com/result?p=@ui5/webcomponents

when working proerly, it will produce something like this:

https://bundlephobia.com/result?p=react-datepicker

Once this is fixed, you can add a badge to the readme that can provide  live packagesize info

**Comment by pskelin** [comment]
Hi @bcullman,

thanks for reaching out. It would be nice to have more background why you need this. Are you interested in importing web components via the package name, or are you only interested in the bundle size?

If this is about the bundle size only - we have deliberately chosen to not ship UI5 web components as a bundle, but as individual ES6 modules instead.

Shipping a bundle for a component library has proven problematic in the past:
- the bundle only grows in size as more components and features are added.
- applications only ever use a fraction of the bundle.

Shipping ES6 modules means every application can create a bundle of only what is actually used.

If you are curious about the size of all web components with all possible features, we do build a bundle for our playground and you can check its size either in the build logs or in the network trace. Currently it is 131 KBs minified and zipped (with room for improvement).
If you are curious about the smallest web component you can bundle, we have built a bundle containing only the ui5-checkbox and ui5-label and it was around 12 KB. The "framework" part for web components is around 10 KB, with each component adding 3-5 KBs on top depending on features and complexity. The most complex components like date picker, shellbar and tab container are naturally bigger.

If this is about importing web components via the package name - we are planning on adding a `module` entry in the `package.json`, but this is purely for having improved API ergonomics:

modules now:
```javascript
import "@ui5/webcomponents/dist/Button"
```

vs package import when we impement this:
```javascript
import { Button } from "@ui5/webcomponents";
Button.define();
```

The latter one will have an additional inconvenience of calling a method, as a named export with a side effect will prevent tree shaking (apps importing one component will get all of them unless the define method call is separated like above).
Adding this form of imports will most likely show up on bundlephobia, with the disclaimer that it does not represent what an application will get when they create their optimised bundle as described in the first point.

I would be really glad to hear your oppinion on the two aspects of the `module` field in `package.json`.
Regards,
Peter
