### ISSUE TITLE
[Safari] ComboBox: autocompletion does not work correctly

### ISSUE THREAD

**Issue by d3xter666** [SAP/ui5-webcomponents#3680]
### **Bug Description**
Autocomplete for **_starts with per term_** breaks on Safari. It completes the whole word without highlighting it.
Any further typing adds letters to the completed result making it invalid

### **Expected Behavior**
If autocomplete works, it needs to highlight the autocompleted part, so the user could continue typing without breaking it.

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/master/playground/components/ComboBox/
2. Scroll to section **Filters (StartsWithPerTerm(default), StartsWith, Contains)**
3. Start typeing "King"

It should initially reveal United Kingdom and Kazakhstan on the letter "K". On the next letter, the autocompletion fills in "Kazakhstan" and just appends it.

### **Context**
- OS/Platform: Mac
- Browser: Safari

**Comment by niyap** [comment]
The issue is reproducible on iOS in Safari as well. In chrome it works as expected.
