### ISSUE TITLE
Table Personalization feature for Responsive Table

### ISSUE THREAD

**Issue by kartikc13** [SAP/ui5-webcomponents#3682]
Hello Colleagues,

As per UX guidelines an important table must have the personalization dialog available with it to handle column visibility, column ordering, etc. This was achieved in existing UI5/Fiori library using the following elements:
https://sapui5.hana.ondemand.com/#/api/sap.m.TablePersoDialog
https://sapui5.hana.ondemand.com/#/api/sap.m.TablePersoController
https://sapui5.hana.ondemand.com/#/api/sap.m.TablePersoProvider

An example of table personalization can be found here: https://sapui5.hana.ondemand.com/#/entity/sap.m.Table/sample/sap.m.sample.TablePerso

When can we expect such a feature enabled for Responsive Table control in ui5-webcomponents-react library?

**Comment by ilhan007** [comment]
Hello @kartikc13 thank you for your request.

Although such a control is present in SAPUI5/OpenUI5, it is not in our plans to deliver it as a web component. 
What I can suggest is to compose it yourself by using other web components such as the Dialog, List and Button similar to this example: https://codesandbox.io/s/ui5-webcomponents-forked-w24gz?file=/index.html

If more and more users would like this as a web component, we might reconsider and put it in the backlog, but for the time being I suggest going with the sample above. You can wrap it as a react component of yours and reuse it in your app.

BR,
ilhan
