### ISSUE TITLE
ViewSettingsDialog (v1.0.0-rc.16) is not available in npm

### ISSUE THREAD

**Issue by hkshetry** [SAP/ui5-webcomponents#3684]
### **Feature Request Description**

ViewSettingsDialog is not available in npm . It is documented in https://sap.github.io/ui5-webcomponents/playground/components/ViewSettingsDialog/ but  v1.0.0-rc.16 not  available in npm

### **Proposed Solution**
release ViewSettingsDialog in npm  so it can  be consumed

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

### **Stakeholder Info** (if applicable)

- Organization: SuccessFactor
- Bussiness impact: This feature is needed for sorting card

**Comment by ilhan007** [comment]
Hi @hkshetry the component is available in 0.31.15
https://github.com/SAP/ui5-webcomponents/releases/tag/v0.31.15

This is the version that most of the SFSF projects are using. What version do you currently use?

And, yes it will be part of the RC.16, which will be released in September, so you see a preview. But for SFSF we 
released the component in 0.31.15.

BR,
ilhan

**Comment by hkshetry** [comment]
Hi @ilhan007, 

Thank you for the information. We are using 0.31.14 and now will update to 0.31.15 to get vieWSettingsDialog.
