### ISSUE TITLE
Wizard: Clicking on Step in NavigationArea does not trigger onStepChange

### ISSUE THREAD

**Issue by thomas-br** [SAP/ui5-webcomponents#3685]
**Describe the bug**
Clicking on a non-disabled step in the Navigation Area of the Wizard does not lead to an onStepChange event, as internal evaluation of internal method `changeSelectionByStepAction` fails with not finding any focusable child.

```
Uncaught (in promise) TypeError: Cannot read property 'focus' of null
    at HTMLElement.changeSelectionByStepAction (Wizard.js:670)
```

**Isolated Example**
https://codesandbox.io/s/youthful-silence-3ip7l

**To Reproduce**
1. Go to https://codesandbox.io/s/youthful-silence-3ip7l
2. Click on second (Bar) step
3. Observe console error instead of console.log of the expected event

**Expected behavior**
Event `onStepChange` of the Wizard is properly triggered

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.0.0-rc.15
`@ui5/webcomponents-react` version: 0.18.4
Operating System: MacOS
Browser: Chrome

**Additional context**
Same behavior observable in official storybook:
https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-wizard--default-story

**Comment by unazko** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

The issue is reproducible via the described by the author steps.

Regards,
Boyan Rakilovski
