### ISSUE TITLE
UI5-elements: 2108 CBC: There is no way to get dropdown element by unique attribute

### ISSUE THREAD

**Issue by C5320779** [SAP/ui5-webcomponents#3688]
### **Bug Description**
There is no way to get the dropdown element by unique attribute. Therefore, we have to use locators based on the sequence numbers of the elements like //ui5-static-area-item[2]. This approach makes our testing unstable. 

### **Steps to Reproduce**
1. Go to the CBC system [https://tenant-1.dev-local-test1-ui-e2e-regression.cbc.only.sap/sap/public/ap/smeui/repository/SAP_UI/HTMLOBERON5/client.html?sap-b-automation=true](https://tenant-1.dev-local-test1-ui-e2e-regression.cbc.only.sap/sap/public/ap/smeui/repository/SAP_UI/HTMLOBERON5/client.html?sap-b-automation=true)
2. Login with user ID "tester" and password "Welcome1"
3. Open PE page [https://tenant-1.dev-local-test1-ui-e2e-regression.cbc.only.sap/sap/public/x4/bc/pe/index.html#/](https://tenant-1.dev-local-test1-ui-e2e-regression.cbc.only.sap/sap/public/x4/bc/pe/index.html#/)
4. Click "Open" button in Define Scope activity
5. Click "Select Countries/Regions" button or dialog "Select Countries/Regions" will appear automatically
6. Open dropdown in dialog
7. Inspect any item from the opened dropdown
![dropdown](https://user-images.githubusercontent.com/86964186/129974306-7a0acace-b575-4654-807e-e9f615621ddc.png)

### **Actual Behavior**
There is no way to get dropdown element by unique attribute because class attribute value changes after a page refresh (see the element_before_reload.png and element_after_reload.png screenshots). 

ui5-static-area-item class value before reload:
![element_before_reload](https://user-images.githubusercontent.com/86964186/129974311-0ad0446d-5518-4c81-b35c-f22cacc94e77.png)

ui5-static-area-item class value after reload:
![element_after_reload](https://user-images.githubusercontent.com/86964186/129974309-843889be-52ed-4d57-870a-0097b4d39e09.png)

### **Expected Behavior**
ui5-static-area-item with underlined class value on the screenshots should have a unique attribute(like data-automation-id)
All the elements with interaction on the system should have stable IDs or any other stable unique attributes (f.e. button elements, elements in dropdowns, list, etc.). We should have a solution to manage this problem as it makes some parts of the application untestable

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

### **Stakeholder Info** (if applicable)

Organization: {SAP}
Project {CBC}
Business impact: {Inability to write stable UI tests for the system. As a result, the system testing is become unstable after adding UI-5 components}

**Comment by unazko** [comment]
Hello @SAP/ui5-webcomponents-team,

The issue is about control having ID which isn't stable.
In relation to the following task: https://github.com/SAP/ui5-webcomponents/issues/2361

Best Regards,
Boyan

**Comment by fifoosid** [comment]
Hi @C5320779

As much as I can see you are using ```ui5-multicombobox```. MultiComboboxItem currently has ```stableDomRef``` property which can be used for this exact purpose.

How to use it:

In your html file:
```html
<ui5-multi-combobox placeholder="Choose your countries" id="countriesmcb">
	<ui5-mcb-item selected text="Argentina" stable-dom-ref="Argentina"></ui5-mcb-item>
	<ui5-mcb-item text="Bulgaria"></ui5-mcb-item>
	<ui5-mcb-item text="Denmark"></ui5-mcb-item>
	<ui5-mcb-item text="England"></ui5-mcb-item>
	<ui5-mcb-item text="Albania"></ui5-mcb-item>
	<ui5-mcb-item text="Morocco"></ui5-mcb-item>
	<ui5-mcb-item text="Portugal"></ui5-mcb-item>
	<ui5-mcb-item text="Germany"></ui5-mcb-item>
	<ui5-mcb-item text="Philippines"></ui5-mcb-item>
	<ui5-mcb-item text="Paraguay"></ui5-mcb-item>
</ui5-multi-combobox>
```

And in your js file:
```js
document.getElementById("countriesmcb").getStableDomRef("Argentina");
```

**_Note:_** In order to access the actual DOM reference, you should open the multicombobox first.

HEADSUP: We are currently refactoring the stableDomRef concept in #3539. When we merge & release this change, you might have to refactor the usage of it in your app.
