### ISSUE TITLE
UI5-elements: 2108 CBC: Web element in the header changes depending on the page

### ISSUE THREAD

**Issue by C5320779** [SAP/ui5-webcomponents#3689]
### **Bug Description**
There is no way to get the label element by unique attribute since it changes depending on the page. Therefore, we have to use locators based on the sequence numbers of the elements or move to another page to check this element. This approach makes our testing unstable.

### **Steps to Reproduce**
1. Go to the CBC system [https://tenant-1.rc2-ui-e2e-regression.cbc.only.sap/sap/public/ap/smeui/repository/SAP_UI/HTMLOBERON5/client.html?sap-b-automation=true](https://tenant-1.rc2-ui-e2e-regression.cbc.only.sap/sap/public/ap/smeui/repository/SAP_UI/HTMLOBERON5/client.html?sap-b-automation=true)
2. Login with user ID "tester" and password "Welcome1"
3. Open PE page [https://tenant-1.dev-local-test1-ui-e2e-regression.cbc.only.sap/sap/public/x4/bc/pe/index.html#/](https://tenant-1.dev-local-test1-ui-e2e-regression.cbc.only.sap/sap/public/x4/bc/pe/index.html#/)
4. Inspect the ui5-label status element like on screenshot 
![activities_status_label](https://user-images.githubusercontent.com/86964186/129981208-1158ec95-1f9d-4c64-87cb-18db8cba2fd0.png)
5. Click on Configuration Activities tab
6. Inspect the same ui5-label status element like on screenshot
![conf_activities_status_label](https://user-images.githubusercontent.com/86964186/129981376-d8452e78-ba93-4738-85f1-1a60a540ca98.png)

### **Actual Behavior**
There is no way to get the label element by unique attribute since this element changes depending on the page. In this case data-automation-id attribute has dissapeared after moving to another tab.

### **Expected Behavior**
The same elements on each page should have the same unique attributes values like data-automation-id. All the elements with interaction on the system should have stable IDs or any other stable unique attributes (f.e. button elements, elements in dropdowns, list, etc.). We should have a solution to manage this problem as it makes some parts of the application untestable.

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

### **Stakeholder Info** (if applicable)

Organization: {SAP}
Project {CBC}
Business impact: {Inability to write stable UI tests for the system. As a result, the system testing is become unstable after adding UI-5 components}

**Comment by unazko** [comment]
Hello @SAP/ui5-webcomponents-team,

The issue is about control having ID which isn't stable.

Best Regards,
Boyan

**Comment by fifoosid** [comment]
Hi @C5320779 

For this exact use case you can use the ```stableDomRof``` property of the tab. You can use it like this:

```html
<ui5-tabcontainer id="tabcontainer" show-overflow>
	<ui5-tab text="Tab 1" stable-dom-ref="tab1">
		<ui5-label>Quibusdam, veniam! Architecto debitis iusto ad et, asperiores quisquam perferendis reprehenderit ipsa voluptate minus minima, perspiciatis cum. Totam harum necessitatibus numquam voluptatum.</ui5-label>
	</ui5-tab>
	<ui5-tab icon="activities" text="Tab 2" selected>
		<ui5-label>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga magni facere error dicta beatae optio repudiandae vero, quidem voluptatibus perferendis eum maiores rem tempore voluptates aperiam eos enim delectus unde.</ui5-label>
	</ui5-tab>
	<ui5-tab icon="add" text="Tab 3">
		<ui5-label>Dignissimos debitis architecto temporibus doloribus reiciendis libero rem nemo, nobis quidem dolor praesentium, beatae voluptatum iste eveniet, nam voluptatem obcaecati ducimus dolore.</ui5-label>
	</ui5-tab>
	<ui5-tab icon="calendar" text="Tab 4">
		<ui5-label>Possimus ipsa eos impedit aut nisi repellendus recusandae, temporibus ducimus, necessitatibus tenetur facere, minima vero fugit rem reiciendis natus ratione quia numquam?</ui5-label>
	</ui5-tab>
	<ui5-tab-separator></ui5-tab-separator>
	<ui5-tab icon="action-settings" text="Tab 5">
		<ui5-label>Explicabo laboriosam ab consequuntur, qui dignissimos inventore sapiente ullam quaerat ratione libero vero, beatae laudantium! Aperiam numquam tempore, laudantium perferendis recusandae autem.</ui5-label>
	</ui5-tab>
</ui5-tabcontainer>
```

And in your js file:
```js
console.log(document.getElementById("tabcontainer").getStableDomRef("tab1"));
```

HEADSUP: We are currently refactoring the stableDomRef concept in #3539. When we merge & release this change, you might have to refactor the usage of it in your app.
