### ISSUE TITLE
ui5-dialog: scrolling is blocked when dialog is closed with `Esc` key

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents#3690]
### **Bug Description**
If a `ui5-dialog` is closed with the `Escape` key, it seems like it doesn't remove the scroll blocking. If you close if the the `close()` method, the scroll blocking gets removed as expected.

### **Expected Behavior**
Scroll Blocking should be removed when closing the dialog via `Esc`, like in `1.0.0-rc.14`.

### **Steps to Reproduce**
1. Open: https://codesandbox.io/s/thirsty-bouman-cb80u?file=/src/App.js
2. Scroll through the page, everything is working fine.
3. Click `Open Dialog`, close it with the `close` button in the footer, try to scroll again. --> Still works fine
4. Click `Open Dialog` again, then press `Esc` and try to scroll again. --> Scrolling is now blocked
5. _Optional: open the dialog again and press the close button, scrolling works fine again_

### **Isolated Example**
https://codesandbox.io/s/thirsty-bouman-cb80u?file=/src/App.js

### **Context**
- UI5 Web Components version: 1.0.0-rc.15
- OS/Platform: macOS
- Browser: Chrome 92.0.4515.131
- Affected component: `ui5-dialog`, maybe even the base class `ui5-popup`?

### **Priority**
- [ ] Low
- [ ] Medium
- [X] High
- [ ] Very High

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SAP Customer Advisory / UI5 Web Components for React

**Comment by unazko** [comment]
Hello @SAP/ui5-webcomponents-topic-rd,

The issue is reproducible via the provided steps.

Regards,
Boyan
