### ISSUE TITLE
Focus indication is not provided for complete cards highlighted in red within Flow chart when cards are accessed.   Focus is provided only for card headers. 

### ISSUE THREAD

**Issue by ivaylo-stoilov** [SAP/ui5-webcomponents#3693]
### **Bug Description**
Focus indication is not provided for complete cards highlighted in red within Flow chart when cards are accessed.  
Focus is provided only for card headers. 

### **Expected Behavior**
Ideally, focus indication should be provided for complete cards when accessed.  

### **Steps to Reproduce**
open https://codesandbox.io/s/29l34
use the code above
<Card
    header={<CardHeader status="3 of 5" subtitleText="Direct Reports" titleText="TeamSpace"/>}
 >
   <Text>Sample Text for body</Text>
[</Card>]

### **Isolated Example**
If possible, please provide an isolated example by forking [CodeSandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html).

### **Context**
- UI5 Web Components version: {
[ACC-271.1_Flow chart_ Focus issue.docx](https://github.com/SAP/ui5-webcomponents/files/7012931/ACC-271.1_Flow.chart_.Focus.issue.docx)
0.15}

### **Log Output / Stack Trace / Screenshots**
```
{...}
```
### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Bussiness impact: {...}

**Comment by unazko** [comment]
Hello @ivaylo-stoilov,

I was having trouble reproducing the issue by following the steps provided in the attached document.
Could you provide a sample similar to the following one:
https://codesandbox.io/s/wizardly-ishizaka-zm1ch?file=/src/App.js
so we could reproduce the issue.

Best Regards,
Boyan

**Comment by gmkv** [comment]
Hi @ivaylo-stoilov 

There is no focus outline on the whole card by design.
From what I see in, you're misusing the ui5-card component to fit your case.

I suggest you plain div element with tabindex="0" to achieve what you need.

Kind regards,
Georgi
