### ISSUE TITLE
Combobox: inner ComboBoxItem components can't be switched with arrow keys when the Narrator is on

### ISSUE THREAD

**Issue by kolew96** [SAP/ui5-webcomponents#3703]
**Bug Description**
Combobox options (ComboBoxItem) can't be switched with arrow keys when the Narrator is on
https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-combobox--default-story

**Observed behavior**
Combobox options (ComboBoxItem) can't be switched with arrow keys when the Narrator is on

**Expected Behavior**
Combobox options (ComboBoxItem) should be switchable with arrows when the Narrator is on

**Steps to Reproduce**
1. Go to [https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-combobox--default-story](url)
2. Tab until go to the first Combobox example
3. Turn on the Narrator
4. Press F4 to open the combobox options and press the arrow down/up

**Context**
Browser (if relevant): {...} Chrome

**Additional Context**
Item count is not read out when list items within combo box are accessed. 
[ACC-264.1_Combo box _ Item count is not read.docx](https://github.com/SAP/ui5-webcomponents/files/7020662/ACC-264.1_Combo.box._.Item.count.is.not.read.docx)

**Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Criteria**
- Accessibility issue

**Comment by unazko** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

The issue is reproducible via the provided steps and snipped.

Best Regards,
Boyan

**Comment by elenastoyanovaa** [comment]
Hello @kolew96 ,

Scan mode is enabled by default. Scan mode is equivalent to Virtual PC cursor mode of JAWS. You can toggle the mode with CAPS LOCK + SPACE. Then you will be able to interact with the component

Regards,
Elena
