### ISSUE TITLE
List: List items are read twice (accessibility issue)

### ISSUE THREAD

**Issue by angelzbg** [SAP/ui5-webcomponents#3706]
### Description
The list items are read twice when navigated with keyboard.
https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-list--default-story

### Expected Behavior
The list items shoud be read once.

### Steps to reproduce
1. Open windows narrator, JAWS Screen reader
1. Go to https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-list--default-story
2. Tab until focus on list
3. Select items with arrow up/down
4. List items are read twice

### Context
Browser (if relevant): {...} Chrome
JAWS   2021.2105.53 ILM 64bit for Windows
Windows Narrator 2020

**Comment by unazko** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

The referenced sample doesn't best showcase the accessibility features of the ui5-list component as there are no
meaningful data in the list item texts.

I've tested with windows Narrator and there, list item texts are read twice. 
If those items didn't have "list item" as text, the Narrator wouldn't announce "list item" at all
and it should as it is related to the `role="option"`.

With Jaws 2021 the list items texts aren't red twice as it should.
First announcement of "List item" should come from  the `role="option"` and the second
announcement of "List item" should come from the text of the list item in the current example.

As a conclusion:
- the sample could be improved with more meaningful list title and list item texts.
- there is no announcement, which would indicate that we navigated into a list item for both Jaws 2021 and windows Narrator
screen readers.
- windows Narrator reads list item texts twice.

Best Regards,
Boyan

**Comment by dobrinyonkov** [comment]
Hello @angelzbg,

By default Narrator starts in Scan mode, which is its reading mode. In scan mode the speech output is more verbose and when you focus an item from the lists it automatically starts to read its content. You can see the blue cursor that jumps from one word to another. **To disable "Scan" mode - press CapsLock(or Insert) + SpaceBar**. Then the speech output should be OK.

Like Boyan said, this is not reproducible with JAWS as its reading mode work a bit different.

Kind Regards,
Dobrin
