### ISSUE TITLE
Add Support to Busy Indicator

### ISSUE THREAD

**Issue by gustavokath** [SAP/ui5-webcomponents#371]
Are there any plans to support the BusyIndicator? Like the current one sap.m.BusyIndicator so when something is loading we can show this to the user.

**Comment by vladitasev** [comment]
Hello,

We're currently evaluating this proposal internally and we'll get back to you a.s.a.p.

Regards,
Vladi

**Comment by fifoosid** [comment]
Hi @gustavokath,

The Busy Indicator should be available in the next release.

Best Regards,
Filip

**Comment by gustavokath** [comment]
@fifoosid Thanks 👍

**Comment by ignipae** [comment]
Hi @fifoosid 
Thanks for implementing the busy indicator functionality.
From within the samples I see that it can be placed somewhere, which is good.

Will it also work to place it "on top of" another control? 
Like if I would like to make a list busy or such.

If this would be possible by placing it (a list or such) into the body of the busy indicator, this would be great. 
And if this is already possible, maybe adding this into the samples would clarify this a lot also for others.

**Comment by MapTo0** [comment]
Hey, we've been discussing improvement of the API.
We are going in the direction of:

```
<ui5-busyindicator target="my-list" active size="Large"></ui5-busyindicator>

<ui5-list id="my-list">
	<ui5-li>Item 1</ui5-li>
	<ui5-li>Item 2</ui5-li>
	<ui5-li>Item 3</ui5-li>
</ui5-list>
```

What do you think from consumer point of view? Does it fit your needs?
If you have any comments or point of improvements feel free to express them.

**Comment by MapTo0** [comment]
Hey all,

We discussed the usage and the best proposal so far is the following:

```html
<ui5-busyindicator size="Medium" active>
  <ui5-list>
    <ui5-li>Item 1</ui5-li>
    <ui5-li>Item 2</ui5-li>
    <ui5-li>Item 3</ui5-li>
  </ui5-list>
</ui5-busyindicator>
```

![image](https://user-images.githubusercontent.com/5821279/59039869-4c5e0e00-887e-11e9-87d3-4eb4efdbd113.png)

What do you think?
