### ISSUE TITLE
No keyboard alternative to resize the Edit library dialog window

### ISSUE THREAD

**Issue by kilgharsap** [SAP/ui5-webcomponents#3715]
### **Bug Description**

User can resize the Edit library dialog window by using only mouse and there is no keyboard only alternative for keyboard only users to change the window size.

### **Expected Behavior**

Any action that can be performed using mouse must be accessible through keyboard also. 
Suggestion -There can be custom keyboard implementation for keyboard only users to change the size of dialog window.

### **Context**
- UI5 Web Components version: {...}
- OS/Platform: {...}
- Browser: {...}
- Affected component: {...}

### **Log Output / Stack Trace / Screenshots**
```
{...}
```
### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Bussiness impact: {...}

**Comment by IlianaB** [comment]
Hello @kilgharsap,
Just to assure I understand you correctly. Your suggestion is the user to be able to resize the resizable Dialog (like the second one here: https://sap.github.io/ui5-webcomponents/playground/components/Dialog/)  using only the keyboard? 

Regards,
Iliana

**Comment by kilgharsap** [comment]
this is create by mistake
