### ISSUE TITLE
Rating Indicator: In RTL mode not round values are incorrectly visualised 

### ISSUE THREAD

**Issue by niyap** [SAP/ui5-webcomponents#3723]
### **Bug Description**
In RTL mode not rounded values are incorrectly visualised.

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/master/playground/main/pages/RatingIndicator/
2. Set dir="rtl" to the body
3. Check the fifth sample where the value is not round or change the value of any other instance.

<img width="256" alt="Screenshot 2021-08-25 at 9 06 59" src="https://user-images.githubusercontent.com/38278268/130736044-7ba677fb-a2fc-4c61-88e5-b22b43875e94.png">

### **Context**
- UI5 Web Components version: v1.0.0-rc.16

- OS/Platform: MAC OS, iOS
- Browser: Chrome/Safari
- Affected component: ui5-rating-indicator

**Comment by elenastoyanovaa** [comment]
Reproducible also on iPad on Safari.

**Comment by ndeshev** [comment]
Reproducible also on Chrome, Edge & Firefox on Windows.
