### ISSUE TITLE
[SF][Card][A11y]: Ensure landmarks of card content are unique 

### ISSUE THREAD

**Issue by ericchan1983** [SAP/ui5-webcomponents#3730]
**Describe the bug**
If there are multiple card components on the page, the Axe A11y tool report the issue below:
Ensure landmarks are unique.

section[role="group"][aria-label="Card\ Content"]

**Isolated Example**
*Please provide an isolated example if possible by forking [this codesandbox](https://codesandbox.io/s/ui5-webcomponents-react-template-29l34).*

**To Reproduce**

**Expected behavior**
A property is needed to configure the aria-label for the card content section.

**Screenshots**
![image](https://user-images.githubusercontent.com/1614528/130788891-05884545-c046-443e-b468-0196adfecf05.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version:0.31.14
`@ui5/webcomponents-react` version: 0.131.13
Operating System: macOS Big Sur 11.5
Browser: Chrome Version 92.0.4515.159 (Official Build) (x86_64)

**Additional context**

**Comment by IlianaB** [comment]
Hello , this seems like a new feature request for enabling the configuration of the aria-label for the card content section. The accessibility issue can be observed in the PlayGround, using the Axe Tool: https://sap.github.io/ui5-webcomponents/playground/components/Card/

Regards,
Iliana
