### ISSUE TITLE
Add additional illustrations for ui5-illustrated-message

### ISSUE THREAD

**Issue by allen138** [SAP/ui5-webcomponents#3739]
### **Feature Request Description**
Hi team,
I see there is a new component ui5-illustrated-message. SF currently has some internal implementations of these fiori moments, but would like to utilize the ones from ui5-webcomponents. There are a few illustrations we are using, but I do not see listed as the ones supported by this component. These illustrations include:
success-balloon
success-high-five
success-checkmark

![image](https://user-images.githubusercontent.com/38701667/131038704-e11be80e-5edf-4ec4-95c4-b905407cf061.png)

Thanks,
Allen

### **Proposed Solution**
Please help to add support for the above mentioned illustrations.

### **Additional Context**
I added a link in our slack channel as a reference to the resource I am referring to.

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by sunnyyadav100** [comment]
I am from SAP Ariba, we are also looking for more illustrative message support in the UI5 illustrative message component.
SAP fiori moments -  https://pages.github.tools.sap/sap-design-ops/fiori-moments/all-illustrations.html. We are looking for support of -  
#sapIllus-Spot-NoData
#sapIllus-Dialog-NoData

**Comment by BennyHuang** [comment]
HI @nnaydenow @ilhan007 
Is it possible to add `No activities - Alt` for scene? Or we have no way to support alt illustrations.

Thanks
Benny

**Comment by nnaydenow** [comment]
Hi @BennyHuang ,

Resources of illustrations containing alt in their name are not fully completed. We will add them once they are ready.

Regards,
Nayden
