### ISSUE TITLE
Slider: Handle's active state color not applied

### ISSUE THREAD

**Issue by niyap** [SAP/ui5-webcomponents#3745]
### **Bug Description**
When active, the handle's active color is not applied.

### **Expected Behavior**
Please, check the visual specification for Quartz and update it accordingly

### **Steps to Reproduce**
1. Go to  https://sap.github.io/ui5-webcomponents/master/playground/main/pages/Slider/?sap-ui-theme=sap_fiori_3
2.  Mouse down over a handle

**Comment by niyap** [comment]
Hello Colleagues,

After deeper analysis, I found out that down state over the handle (active) is never implemented.
Since, it has to be implemented and then all the themes to be adjusted according to their visual specification, we took the decision to handle it as a backlog item.
The Backlog Item should include implementation of handle's active state, as well as covering all the visual requirements for active state in each supported theme.

Kind Regards,
Niya

**Comment by hristop** [comment]
Internal BLI was created: BGSOFUIRILA-3687
