### ISSUE TITLE
ui5-li-notification-group: console warning when selecting item

### ISSUE THREAD

**Issue by JarrettChan** [SAP/ui5-webcomponents#3749]
### **Bug Description**
When clicking or using arrow keys to navigate inner `ui5-li-notification` within a `ui5-li-notification-group`, it prints a console warn: "The provided item is not managed by ItemNavigation ... "

### **Expected Behavior**
No console warning.

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/NotificationListGroupItem/
2. Click on a `ui5-li-notification` within a `ui5-li-notification-group`
3. See console warning

### **Context**
- UI5 Web Components version: 
- OS/Platform: macOS
- Browser: Chrome
- Affected component: ui5-li-notification-group

### **Priority**
- [x] Low
- [ ] Medium
- [ ] High
- [ ] Very High

**Comment by gmkv** [comment]
FYI @SAP/ui5-webcomponents-topic-rd

**Comment by LidiaBobeva** [comment]
Hello,

The issue is reproducible with nested list.
You can see the isolated example: https://codesandbox.io/s/ui5-webcomponents-forked-odwde?file=/index.html
The error comes from ItemNavigatio.js when the user clicks on some of the nested items.

Best Regards,
Lidiya
