### ISSUE TITLE
dialog overlay hides page content when there is a message-strip

### ISSUE THREAD

**Issue by pskelin** [SAP/ui5-webcomponents#375]
**Describe the bug**
Opening a dialog causes the whole page content behind the overlay to disappear

**To reproduce**
1. Go to https://codesandbox.io/s/p9m5w08q80
2. Click the open button
3. The open button disappears

**Expected behavior**
the open button should be visible behind the overlay. If the message strip is removed from the page the button stays as expected, so this behaviour is influenced by the message strip shomehow.

**Screenshots**

**Context**
- UI5 Web Components version: 0.10.1
- OS/Platform: MacOS
- Browser *(if relevant)*: Chrome
- Other information: {...}

**Affected components**
ui5-dialog
ui5-messagestrip

**Comment by ilhan007** [comment]
That is because the message strip has height 100%;

the body grows when the dialog is opened, the message strip takes the whole height and the button disappears (although  it`s just bellow the message strip), as the message strip takes the full view port).
