### ISSUE TITLE
IllustratedMessage - NoData: title-text is not in SAP 72 font

### ISSUE THREAD

**Issue by sunnyyadav100** [SAP/ui5-webcomponents#3751]
### **Bug Description**
The title text of 'No data' illustrated message is not in SAP 72 font

<img width="376" alt="image" src="https://user-images.githubusercontent.com/9139037/131286834-a0293b3c-b143-461c-bcbb-0e6760067040.png">

### **Expected Behavior**
Title text should be in SAP 72 font.

### **Steps to Reproduce**
Use No-data illustrative message.

### **Isolated Example**
If possible, please provide an isolated example by forking [CodeSandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html).

### **Context**
- UI5 Web Components version: {...} RC15
- OS/Platform: {...}
- Browser: {...}
- Affected component: {...}

### **Log Output / Stack Trace / Screenshots**
```
{...}
```
### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...} SAP Ariba
- Bussiness impact: {...}

**Comment by nnaydenow** [comment]
Hi @sunnyyadav100,

I preprared codesandbox example with rc-15 and everything seems to work correctly:
https://codesandbox.io/s/ui5-webcomponents-forked-gukzk?file=/index.html

Best regards,
Nayden

**Comment by nnaydenow** [comment]
When the cache is cleared the issue appears.
