### ISSUE TITLE
InputElementsFormSupport: inputs don't fire `submit` event on ENTER press

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#3755]
### **Bug Description**
All input like components don't fire the `submit` event when used inside a form and with `InputElementsFormSupport` imported.

### **Expected Behavior**
When input like web-components are used inside a form and the user focuses the element and then presses the ENTER key, the form should be validated, submitted and the `onsubmit` event should be called.

Additionally, select like components should only open the popover by pressing SPACE. ([UI5 Example](https://sapui5.hana.ondemand.com/#/entity/sap.m.Select/sample/sap.m.sample.Select)) The ENTER key is apparently reserved for the form handling.

__Note:__ The issue with the `Button` is already mentioned [here](https://github.com/SAP/ui5-webcomponents/issues/3752), since this issue is affecting all input components, I didn't add it there.

### **Steps to Reproduce**
1. Go to [codeSandbox](https://codesandbox.io/s/ui5-webcomponents-forked-vlw4c?file=/index.html) and open dev tools
2. Focus each element and press ENTER
3. See that only the HTML elements are firing the submit event

### **Isolated Example**
https://codesandbox.io/s/ui5-webcomponents-forked-vlw4c?file=/index.html

### **Context**
- UI5 Web Components version: 1.0.0-rc.15

**Comment by henriquemattos** [comment]
Having the same problem here - and also the one linked #3752
