### ISSUE TITLE
MultiComboBox : Limited selection items property to limit the selected items.

### ISSUE THREAD

**Issue by Arora05** [SAP/ui5-webcomponents#3756]
Following features are not found in the MultiComboBox control currently:

- We cannot set a limit only up to which the item selection is permitted.

**Proposed Solution**
To have a property that accepts the upper limit up to which only the item selection would be permitted and disables the rest of the unselected items once a limit is reached but items can be seen in the drop-down menu.
One implementation of the same would be: https://ej2.syncfusion.com/react/demos/multi-select/selection-limit/

**Proposed Alternatives**
An alternative to this would be disable/enable property for MultiComboBoxItem which defines that if an item is available for selection but does not disappear from the list.
As the enabled property is there in https://sapui5.hana.ondemand.com/#/api/sap.ui.core.Item

**Comment by nikolay-kolarov** [comment]
Hello @Arora05 ,

There is not such implementation in UI5 and respectively design, so we cannot handle this at the moment.
I think this can be handled with application logic - to remove all non-selected items once the application limit is reached.
Please give it a try and also consider the accessibility aspect - one idea might be to change the value state if the user wants to type more items.

Best Regards,
Nikolay
