### ISSUE TITLE
HTML Sanitizer deletes whole head section including <style> tag

### ISSUE THREAD

**Issue by MFel0123** [SAP/ui5-webcomponents#3757]
### **Bug Description**
I refer to the following request: https://github.com/SAP/ui5-webcomponents/issues/3427.
The new HTML Sanitizer with rc.15 basically works: We can make use of it and make it work on our HTML.
But: It turned out that it just eliminates the whole HEAD Section of a given HTML string including the style tag.
This leads to the behavior, that the whole HTML can not really be displayed since the styling information with all the CSS Classes (that is not the inline styling at the tags) is gone.

### **Expected Behavior**
The HTML Sanitizer should also work for complete HTML Strings with given headers especially including styling information
Very simple Example (without any security risk) is given in the steps to reproduce

### **Steps to Reproduce**
1. Take the following (very simple)  HTML example and format it as one String.

```
<!DOCTYPE html>
<html>

<head>
<style>
body {background-color: blue;}
h1   {color: blue;}
p    {color: red;}
</style>
</head>

<body>
<h1>This is a heading</h1>
<p>This is a paragraph.</p>
</body>
</html>
```

2. Let the current samitizeHTML function (from rc.15) work on it
3. Check the result

### **Isolated Example**
If possible, please provide an isolated example by forking [CodeSandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html).

### **Context**
- UI5 Web Components version: {...}
- OS/Platform: {...}
- Browser: {...}
- Affected component: {...}

### **Log Output / Stack Trace / Screenshots**
```
{...}
```
### **Priority**
- [ ] Low
- [] Medium
- [x] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SAP

**Comment by gmkv** [comment]
Hi @SAP/ui5-webcomponents-topic-core 

Sample: https://codesandbox.io/s/ui5-webcomponents-forked-y3ohs?file=/src/index.js
Can you have a look?

Kind regards,
Georgi

**Comment by vladitasev** [comment]
Hello colleagues,

Please see this codesandbox for the proposed solution:
https://codesandbox.io/s/ui5-webcomponents-forked-4o4gq

Basically, the thirdparty we use for HTML sanitization (Google's Caja HTML Sanitizer) does not allow `body`, `head`, `html` and notably `style` tags, for security reasons.
Caja HTML Sanitizer allows users to pass a custom tag policy to allow some forbidden tags, but this policy is not applied for `html`, `head` and `body`, as these are always skipped by default. Therefore this solution can only allow for `style` to not be stripped.

Therefore, I'm offering you a simpler and more powerful solution. Caja defines the following bit flags to describe every HTML tag:
```js
html4.eflags = {
	OPTIONAL_ENDTAG: 1,
	EMPTY: 2,
	CDATA: 4,
	RCDATA: 8,
	UNSAFE: 16,
	FOLDABLE: 32,
	SCRIPT: 64,
	STYLE: 128
};
```

And having seen these flags, let's check how some tags are defined in Caja:
```js
html4.ELEMENTS = {
....
'html': 49, //OPTIONAL_ENDTAG, UNSAFE, FOLDABLE
'head': 49, //OPTIONAL_ENDTAG, UNSAFE, FOLDABLE
'head': 49, //OPTIONAL_ENDTAG, UNSAFE, FOLDABLE
'style': 148, //CDATA, UNSAFE, STYLE
'br': 2, //EMPTY
'button': 0,
...
}
```

For example, the `br` tag is defined as being able to be empty, the `button` tag has no special properties, and all 4 tags we're interested in have the `UNSAFE` flag. Additionally, `html`, `head` and `body` have the `FOLDABLE` flag, which basically tells the sanitizer that these tags must be skipped regardless of custom policy (as the intention is to create some HTML content that will be embedded in the current HTML page, not create a new page).

Therefore, all it takes for the sanitizer to allow these 4 tags is to remove the `UNSAFE` and `FOLDABLE` flags from their flags value. And this is the proposed solution:

```js
const elements = window.html4.ELEMENTS;
const flags = window.html4.eflags;

elements.html = flags.OPTIONAL_ENDTAG;
elements.head = flags.OPTIONAL_ENDTAG;
elements.body = flags.OPTIONAL_ENDTAG;
elements.style = flags.CDATA + flags.STYLE;
```

If you run this code before `sanitizeHTML`, it will work as you would expect - it would allow these 4 tags, but will still strip harmful attributes from them, and it will also parse CDATA content - f.e. the one inside `style`. 

Optionally, after you run `sanitizeHTML`, you could restore the configuration to exactly how it used to be, in order for the sanitizer to be strict again:

```js
elements.html = flags.OPTIONAL_ENDTAG + flags.UNSAFE + flags.FOLDABLE;
elements.head = flags.OPTIONAL_ENDTAG + flags.UNSAFE + flags.FOLDABLE;
elements.body = flags.OPTIONAL_ENDTAG + flags.UNSAFE + flags.FOLDABLE;
elements.style = flags.CDATA + flags.STYLE + flags.UNSAFE;
```

Again, you can see the full example at:
https://codesandbox.io/s/ui5-webcomponents-forked-4o4gq

Regards,
Vladi
