### ISSUE TITLE
[Android] ComboBox with lazy loading not displaying the fetched data in the dialog

### ISSUE THREAD

**Issue by hristop** [SAP/ui5-webcomponents#3759]
### **Bug Description**
When the items for the ComboBox with lazy loading are fetched, they are not displayed in the opened dialog.
Instead the user should type more or close and reopen the dialog.

### **Expected Behavior**
When the items are fetched they should be displayed in the dialog without the need of any other user interaction.

### **Steps to Reproduce**

1.  Go to https://sap.github.io/ui5-webcomponents/master/playground/components/ComboBox/
2. Scroll to section Lazy loading
3. Click on the ComboBox
4. Type "M" in the input field. 

### **Context**
- UI5 Web Components version: master
- OS/Platform: Android
- Browser: Chrome
- Affected component: ComboBox

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by elenastoyanovaa** [comment]
Reproducible also on iPad on Safari. If you focus out and then focus again, the values will be loaded.

**Comment by niyap** [comment]
Reproducible on iPhone in Chrome and Safari as well.

**Comment by niyap** [comment]
After a discussion with the team, we decided that the "lazy loading" functionality should be handled as a BLI, since deeper analysis is needed, in order to find the best solution.
Here is a reference to the created BLI: https://github.com/SAP/ui5-webcomponents/issues/4483

Kind Regards,
Niya
