### ISSUE TITLE
[Android] MultiComboBox auto closes the keyboard on each key press

### ISSUE THREAD

**Issue by hristop** [SAP/ui5-webcomponents#3761]
### **Bug Description**
When the user tries to filter the values of the MultiComboBox, the keyboard is hidden after each key press. This makes it extremely difficult to search on phone. 

### **Expected Behavior**
The keyboard is not hidden but and the user can type uninterrupted. 

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/master/playground/components/MultiComboBox/
2. Clock on the first MultiComboBox
3. Truy entering "UI5"

### **Context**
- UI5 Web Components version: master
- OS/Platform: Android 10
- Browser: Chrome
- Affected component: MultiComboBox

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

**Comment by niyap** [comment]
The issue is reproducible on iOS in Chrome and Safari
