### ISSUE TITLE
[Android] MultiComboBox's filter selected values button does nothing

### ISSUE THREAD

**Issue by hristop** [SAP/ui5-webcomponents#3762]
### **Bug Description**
When the user has something selected in the MultiComboBox, opens the picker and presses on the "Filter selected items" button (in the top right), nothing happens - all available items are still shown.

### **Expected Behavior**
The button should hide the unselected items and leave only the selected ones.

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/master/playground/components/MultiComboBox/
2. Click on the MultiComboBox with items
3. Toggle the "Filter selected items" button - nothing happens

### **Context**
- UI5 Web Components version: master
- OS/Platform: Android 10
- Browser: Chrome
- Affected component: MultiComboBox

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by niyap** [comment]
The issue is reproducible on iOS in Chrome and Safari as well.
