### ISSUE TITLE
[Android] Value state in MultiComboBox's picker dialog looks odd

### ISSUE THREAD

**Issue by hristop** [SAP/ui5-webcomponents#3763]
### **Bug Description**
The value state does not start from the left most part of the picker dialog of the MultiComboBox web component.
![Screenshot_20210830-170415_Chrome](https://user-images.githubusercontent.com/14230119/131354801-3e1158e5-60b2-4690-aa25-878e58b7f5a3.jpg)

### **Expected Behavior**
Value state should start the whole width of the picker.

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/master/playground/components/MultiComboBox/
2. Click on the first MultiComboBox
3. Enter something invalid ("k" for example).
3a. Or just go down to the MultiComboBox with value state examples.

### **Context**
- UI5 Web Components version: master
- OS/Platform: Android 10
- Browser: Chrome
- Affected component: MultiComboBox

### **Priority**
- [x] Low
- [ ] Medium
- [ ] High
- [ ] Very High

**Comment by niyap** [comment]
The issue is reproducible on iOS in Chrome and Safari as well, but just on the samples in the playground, in the test page it looks as expected. In the playground samples, not just the value state is odd, but also the input field and the button next to it.
