### ISSUE TITLE
[SF][A11y][UploadCollection]: Incorrect implementation of heading for no data text

### ISSUE THREAD

**Issue by ericchan1983** [SAP/ui5-webcomponents#3766]
**Describe the bug**
The no data text is implemented with title of H2, which is incorrect.
"No files found" text is implemented as a heading which is wrong because it is just a normal text and does not look like a heading.

**Isolated Example**
*Please provide an isolated example if possible by forking [this codesandbox](https://codesandbox.io/s/ui5-webcomponents-react-template-29l34).*

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/1614528/131454275-3bf41fee-8d4f-4a8e-b70a-760849c33059.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version:0.31.15
`@ui5/webcomponents-react` version:0.131.15
Operating System:macOS Big Sur 11.5
Browser: Google Chrome Version 92.0.4515.159 (Official Build) (x86_64)

**Additional context**

**Comment by Shtilianova** [comment]
Hello @ericchan1983,
Please provide an isolated example via [codesandbox](https://codesandbox.io/s/ui5-webcomponents-react-template-29l34).
Regards, Diana

**Comment by ericchan1983** [comment]
Hi @Shtilianova,

You can verify this issue on the storybook below:
https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-uploadcollection--default-story
![image](https://user-images.githubusercontent.com/1614528/131944070-d93fc20a-0a57-4133-a9d7-53473b05a5e9.png)

Regards,
Eric Chen

**Comment by fifoosid** [comment]
Hi @ericchan1983 

There is a [spec](https://wiki.wdf.sap.corp/wiki/display/visualcore/UploadCollection+%28Fiori+3%29+-+No+Data) for the control, and it is currently implemented by that spec.

**Comment by ericchan1983** [comment]
![image](https://user-images.githubusercontent.com/1614528/132612850-8d2af73e-f5e6-4f01-918f-b13b2f11b3d3.png)
https://sapui5.hana.ondemand.com/#/entity/sap.m.UploadCollection/sample/sap.m.sample.UploadCollectionForPendingUpload

As the screenshot shown, the no-data text in the UI5 demo is not implemented as H2 title.

**Comment by fifoosid** [comment]
FYI @SAP/ui5-webcomponents-topic-rd 

There is a use case, where the h2 tag is not correct: If the uploadCollection component is in a dialog, the dialog tilte is H2, and the no-data text is also H2

**Comment by ilhan007** [comment]
Fixed with 0.31.18
