### ISSUE TITLE
[SF][A11y][FileUploader]:  Upload files button does not get activated with Enter/Space key with screen reader ON

### ISSUE THREAD

**Issue by ericchan1983** [SAP/ui5-webcomponents#3767]
**Describe the bug**
 "Upload file" button does not get activated with Enter/Space key with screen reader ON. When the screen reader is OFF, the Enter/Space works. 

**Isolated Example**
*Please provide an isolated example if possible by forking [this codesandbox](https://codesandbox.io/s/ui5-webcomponents-react-template-29l34).*
https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-fileuploader--default-story

**To Reproduce**
1. Go to the File Uploader
2. Open the NVDA screen reader
3. Tab on the "Upload File" button
4. Press Enter

**Expected behavior**
The system file explorer should be opened.

**Screenshots**
![image](https://user-images.githubusercontent.com/1614528/131455543-9a910359-04c0-461d-b138-4bedb283ab5f.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version:0.31.15
`@ui5/webcomponents-react` version:0.131.15
Operating System:macOS Big Sur 11.5
Browser: Google Chrome Version 92.0.4515.159 (Official Build) (x86_64)

**Additional context**

**Comment by Shtilianova** [comment]
Hello @ericchan1983 ,
When NVDA is on the Enter/Space could be used from it. Please check NVDA settings.
Regards, Diana

**Comment by ericchan1983** [comment]
Hi @Shtilianova,

With the same NVDA setting, the upload button of UI5 demo page works with Enter/Space.
https://sap.github.io/ui5-webcomponents-react/?path=/story/getting-started--page

Regards, 
Eric Chen

**Comment by ericchan1983** [comment]
Hi @Shtilianova,

Since it's a critical issue that blocking user to interact on the file upload feature with Keyboard, can I have the ETA when can fix this issue, please?

Regards,
Eric Chen

**Comment by fifoosid** [comment]
FYI @SAP/ui5-webcomponents-topic-rd

**Comment by gmkv** [comment]
Hi @SAP/ui5-webcomponents-topic-b 
The File Uploader component is part of your topic.

Regards,
Georgi

**Comment by ilhan007** [comment]
released with 0.31.18
