### ISSUE TITLE
Custom Tooltips for each control with icon

### ISSUE THREAD

**Issue by asoahc** [SAP/ui5-webcomponents#3771]
### **Feature Request Description**
I would like to define a custom description to an button with icon-only.
But it is not possible to define custom tooltip to buttons or to icons.

### **Proposed Solution**
I have a defined attribute like "tooltip" or "label" where I can set a text and it will be displayed as tooltip if I hover the control.

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by fifoosid** [comment]
Hi @asoahc 

If you want to add a tooltip to the button you should use the ```title``` property.

**Comment by asoahc** [comment]
Hi @fifoosid ,

unfortunately, the title property does not work for a button within file-uploader.

![2021-09-02 08_24_09-Window](https://user-images.githubusercontent.com/22494340/131793339-acb4737f-5ab2-42b8-82d5-0fff128ceb29.png)
![2021-09-02 08_26_47-Window](https://user-images.githubusercontent.com/22494340/131793352-a73c4534-69a9-460e-bfbb-2540589c835e.png)

**Comment by asoahc** [comment]
It does not work for <ui5-icon>
![2021-09-02 08_29_04-Window](https://user-images.githubusercontent.com/22494340/131793663-7aca8466-9ef8-4c9d-9457-1ad0bee83491.png)
![2021-09-02 08_29_28-Window](https://user-images.githubusercontent.com/22494340/131793722-050f7b49-279f-4bb0-b95f-da6b94a87fc8.png)
