### ISSUE TITLE
Feature request: Wizard RenderMode Page

### ISSUE THREAD

**Issue by Fwnag** [SAP/ui5-webcomponents#3777]
### **Feature Request Description**
The wizard is currently only available in scroll mode. For a guided wizard, it should be poosible to navigate the individual steps seperatly as a single page in addition to scrolling.
### **Proposed Solution**
Extend the webcomponents with a render mode see documentation here:
**https://ui5.sap.com/#/api/sap.m.Wizard%23methods/getRenderMode**
**https://ui5.sap.com/#/api/sap.m.WizardRenderMode%23overview**

### **Proposed Alternatives**
No alternative for now.

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by ChewbaccaCookie** [comment]
Hi, is there an update on the topic? We're also missing this feature, since with a lot of content the overview suffers greatly.

**Comment by nikolay-kolarov** [comment]
Hi @ChewbaccaCookie,

We have plans to work on this and look into it until the mid of next year.
Still, there are other high prio topics that might affect this and delay it.

Best Regards,
Nikolay

**Comment by ilhan007** [comment]
Hi @Fwnag 
closed with https://github.com/SAP/ui5-webcomponents/pull/7006 and released with 1.14.0
