### ISSUE TITLE
[Android] Wizard - no step titles are shown when selecting from the active steps

### ISSUE THREAD

**Issue by hristop** [SAP/ui5-webcomponents#3782]
### **Bug Description**
When the user tries to select a step from the active steps on mobile device, there are no step titles, only icons are shown. 
![Wizard](https://user-images.githubusercontent.com/14230119/131644354-7c7a0f7f-cf37-4563-a999-63575509dc04.gif)

### **Expected Behavior**
The step titles should be shown in the picker.

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/master/playground/components/Wizard/
2. Activate few steps
3. When steps are stacked try selecting something from the stack.

### **Context**
- UI5 Web Components version: master
- OS/Platform: Android 10
- Browser: Chrome
- Affected component: Wizard

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by elenastoyanovaa** [comment]
The bug is also reproducible on iPad on Safari. The expected content in the dialog should include the step number and title. As a reference you can check the UI5 Wizard control.

**Comment by xpr0gamers** [comment]
solved by  #3839

**Comment by niyap** [comment]
Fixed with #3895
