### ISSUE TITLE
Buttons lost hover effect

### ISSUE THREAD

**Issue by vlad-ti** [SAP/ui5-webcomponents#3783]
ui5-button does no longer change its color when you hover over it with a mouse on a Desktop PC. Is it really intended? Or is it a new bug, e.g. due to https://github.com/SAP/ui5-webcomponents/pull/2968 ?

**Comment by fifoosid** [comment]
Hi,

```ui5-button``` behaves as it is expected:
![image](https://user-images.githubusercontent.com/16850339/131667158-bb63b081-37f0-410e-950d-40f15a1ce951.png)

As you can see it has its hovered effect.

If you still experience this issue, please give more specific information as project version, browser, OS and reopen the issue

**Comment by vlad-ti** [comment]
Hey,
I am still experiencing the issue on my Windows 10 using Chrome (92.0.4515.159) and MS Edge (92.0.902.84).
The issue is present on the UI5 Sample as well: https://sap.github.io/ui5-webcomponents/playground/components/Button/?sap-ui-theme=sap_fiori_3&isrtl=false

**Comment by fifoosid** [comment]
Can you try cleaning your cache. On my side it works just fine with your link.

**Comment by vlad-ti** [comment]
Still the same, in MS Edge, Chrome and Firefox. But I might have a suspicion on the problem cause. I use Lenovo ThinkPad P1 which has a touchscreen, like many other modern PC notebooks. Considering https://github.com/SAP/ui5-webcomponents/pull/2968, especially 
`:host(:not([active]):not([non-interactive]):not([_is-touch]):hover)`
this might be the issue, or? The hovering on some other applications which run on older ui5 webcomponents version do not cause such issues for me.

**Comment by fifoosid** [comment]
If you are using a touch device, this is the reason for sure!

**Comment by vlad-ti** [comment]
Is there any plan or wish to address that? There are many notebooks out there which are used like Desktop PCs, but got a touchscreen as an additional poppycock which is rarely used. On SAPUI5 the button hovering works as expected for me: https://sapui5.hana.ondemand.com/#/entity/sap.m.Button/sample/sap.m.sample.Button

**Comment by gmkv** [comment]
Hi @SAP/ui5-webcomponents-topic-b 
The Button component does not have a hover effect when using a computer which also has a touchscreen (combi device).

https://sap.github.io/ui5-webcomponents/playground/components/Button/?sap-ui-theme=sap_fiori_3&isrtl=false

Kind regards,
Georgi
