### ISSUE TITLE
[iPad][Safari] Components do not detect tablet usage

### ISSUE THREAD

**Issue by elenastoyanovaa** [SAP/ui5-webcomponents#3788]
### **Bug Description**
When on iPad on Safari browser, web components behave as on mobile phone. Detected issues:
- when you TAB all inputs with suggestions, mobile dialog shows instead of popover
- ui5-input:Input with Suggestions sample: type "h", nothing happens; then focus out; focus in -> dialog opens, with h typed in the input, with Hungary loaded
- ui5-multicombobox - Trying to delete a token via x icon, results in opening a dialog; when closing the dialog the token is deleted
- ui5-wizard - navigation action sheet opens as a dialog

Note: The following is not reproducible in Chrome on iPad.

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by vladitasev** [comment]
Please provide the user agent string for the used device.

The one I tested with was: `Mozilla/5.0 (iPad; CPU OS 14_7_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Mobile/15E148 Safari/604.1`

**Comment by niyap** [comment]
I have tested the reported issue using Xcode Simulator, the issue is reproducible and checking the user agent via Safari Developer Tools for Simulator, it is:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1 Safari/605.1.15

**Comment by elenastoyanovaa** [comment]
Hello @vladitasev ,

Sorry for the delay. On my iPad Pro on Safari the user agent string is the same as the one from the Safari Developer Tools for Simulator:

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15
