### ISSUE TITLE
[Android] ComboBox typeahead not working after second entered letter

### ISSUE THREAD

**Issue by hristop** [SAP/ui5-webcomponents#3791]
### **Bug Description**
On a tablet, when the user starts typing in the ComboBox component, the first letter will autocomplete the first matching item, however if the user continues to type, the auto-complete no longer works.
![ComboBox1](https://user-images.githubusercontent.com/14230119/131690970-c56afb1e-f93e-471e-bdef-fec590fcc5f3.gif)

### **Expected Behavior**
The type ahead feature should still work after the second, third, etc input, in case the typed in letter match the text of an item in the list.

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/master/playground/components/ComboBox/
2. Scroll to the example with "Starts with per term", though it is reproducible in the other ComboBoxes as well.
3. Type "a", the type ahead works as expected and "ustria" is added to the already typed in letter.
4. Type "u" - the type ahead no longer works

### **Context**
- UI5 Web Components version: master
- OS/Platform: Android 11, Samsung Galaxy Tab S7+; Reproducible on MacOS + Chrome as well.
- Browser: Chrome
- Affected component: ComboBox

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by ndeshev** [comment]
Fixed with #3495
