### ISSUE TITLE
ui5-flexible-column-layout: set role="main" to mid column content will cause AXE error

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents#3796]
### **Bug Description**
For our application, the mid column is the main content, so we set role="main" to the mid-column slot. Then it will get AXE error as there has role="region" for the mid column root element.

### **Expected Behavior**
Would you please provide an interface for us to customize the mid column aria role?

### **Steps to Reproduce**
1. Go to https://github.wdf.sap.corp/pages/xweb/goalmanagementx/app.html?mock&noFirstTimeGuidance
2. Run AXE plugin
3. There has a moderate error "Main landmark should not be contained in another landmark".

### **Context**
- UI5 Web Components version: {0.31.12}
- OS/Platform: {MacOS}
- Browser: {Chrome}
- Affected component: {ui5-flexible-column-layout}

### **Log Output / Stack Trace / Screenshots**
![2021-09-02_13-38-08](https://user-images.githubusercontent.com/13098801/131788301-2d5698f4-b4c4-40de-915f-86b6f4dc9e94.jpg)
![2021-09-02_13-42-59](https://user-images.githubusercontent.com/13098801/131788470-0ebb02a4-9f66-4195-8524-07b5a9f6d8ea.jpg)

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {SAP Successfators}

**Comment by dobrinyonkov** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

this is a feature request for API to set custom roles to the `ui5-flexible-column-layout` columns.

Similar feature was added recently to the FLC in ui5 (landmarkInfo aggregation).

Kind Regards,
Dobrin

**Comment by nnaydenow** [comment]
Internal reference: BGSOFUIPIRIN-5514

**Comment by ilhan007** [comment]
Closed with https://github.com/SAP/ui5-webcomponents/pull/4446, will be available with 1.1.0 by 21 Jan
