### ISSUE TITLE
ui5-flexible-column-layout: [AXE error] All page content should be contained by landmarks

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents#3804]
### **Bug Description**
For our application, the mid column is the main content, so we set role="main" to the mid-column slot. So there is no landmark for the arrow button and some hidden text.

### **Expected Behavior**
All page content should be contained by landmarks.

### **Steps to Reproduce**
1. Go to https://github.wdf.sap.corp/pages/xweb/goalmanagementx/app.html?mock&noFirstTimeGuidance
2. Run AXE plugin
3. There has four moderate errors "All page content should be contained by landmarks"

### **Context**
- UI5 Web Components version: {0.31.12}
- OS/Platform: {MacOS}
- Browser: {Chrome}
- Affected component: {ui5-flexible-column-layout}

### **Log Output / Stack Trace / Screenshots**
![2021-09-02_15-42-16](https://user-images.githubusercontent.com/13098801/131803209-a478f905-aea9-4361-bc59-9b43b9539497.jpg)
![2021-09-02_15-43-06](https://user-images.githubusercontent.com/13098801/131803316-7c7347cf-96c7-4d5d-9b63-59ee0f0db9ad.jpg)

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {SAP Successfators}

**Comment by dobrinyonkov** [comment]
Hello, we discussed this on our accessibility sync and we will add the role region to the arrow button containers.

**Comment by ilhan007** [comment]
@nnaydenow I guess you need to move the item to "Approved"

**Comment by dobrinyonkov** [comment]
Hi @GongRichard, 

Would it be enough for you if we set a role region on the arrow buttons containers or would you prefer if we offer an API to be able to customise the roles? 

Also, setting a landmark roles on those containers would also require them to have an unique labels. Would you prefer to be able to set custom labels? We will further discuss the default labels with our UX team but let us know if you prefer any default values.

**Comment by GongRichard** [comment]
@dobrinyonkov It's better to provide API to customize roles and labels.

**Comment by ilhan007** [comment]
Hello @GongRichard the issue will be resolved with 1.1.0 - will be available by the end of the day
