### ISSUE TITLE
Reset "X" button for input box

### ISSUE THREAD

**Issue by yashh97** [SAP/ui5-webcomponents#3808]
Currently there's no way to add a reset button "X" to an input field which is to be used as a search field. There's nothing available out of the box for the same. Attached a sample UI5 search input box for reference.
![input](https://user-images.githubusercontent.com/42205352/131828850-368e35e0-bc5c-45d6-b281-3e893ea943b4.png)

**Comment by fifoosid** [comment]
Hi @yashh97 

You can achieve this by using the ```icon``` slot. [Example](https://codesandbox.io/s/ui5-webcomponents-forked-r51t0?file=/index.html)

**Comment by yashh97** [comment]
Is it conventional to use in React, the way it's done in the example? Should it not be a part of ui5-webcomponents-react like the Input is?

**Comment by Lukas742** [comment]
Hi @yashh97 

sorry, I wasn't aware that it's possible to pass multiple icons to the input component. 
Here you can find examples on how to do this with React: [codeSandbox](https://codesandbox.io/s/festive-jones-zqxdb?file=/src/App.js)

@fifoosid I created a PR (https://github.com/SAP/ui5-webcomponents/pull/3825) which fixes the incorrect JSDoc type of the `input` slot.

**Comment by fifoosid** [comment]
Thanks for the PR @Lukas742! Looks like our docs were not clear about this.
