### ISSUE TITLE
Input, ComboBox: Values in Warning and Error inputs are cut off in RTL mode in HC* themes

### ISSUE THREAD

**Issue by elenastoyanovaa** [SAP/ui5-webcomponents#3810]
### **Bug Description**
The values are cut off at the end for warning and error inputs, when RTL mode is turned on in High Contrast themes.

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/master/playground/components/ComboBox/?sap-ui-theme=sap_fiori_3_hcb&isrtl=true
In the first sample, see that the values of are cut off, regardless of the zoom.

Note:  Please check all other inputs.

### **Priority**
- [x] Low
- [ ] Medium
- [ ] High
- [ ] Very High

**Comment by niyap** [comment]
The issue is also reproducible on macOS in Safari,Chrome and Firefox. On iOS as well
