### ISSUE TITLE
Tokens: Strange X icon in Dark Themes

### ISSUE THREAD

**Issue by elenastoyanovaa** [SAP/ui5-webcomponents#3813]
### **Bug Description**
For HCB and Dark themes, the X icon of the token differs from the one in light themes and in UI5.

### **Expected Behavior**
https://sap.github.io/ui5-webcomponents/master/playground/components/MultiComboBox/ should be the same as the one in Quartz Light

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/master/playground/components/MultiComboBox/?sap-ui-theme=sap_fiori_3_dark&isrtl=false

### **Priority**
- [x] Low
- [ ] Medium
- [ ] High
- [ ] Very High

**Comment by niyap** [comment]
The issue is fixed as part of SAP Horizon theme implementation with the following change: #4222
