### ISSUE TITLE
[iPad][Safari] ui5-multicombobox: Readonly input field could not be focused

### ISSUE THREAD

**Issue by elenastoyanovaa** [SAP/ui5-webcomponents#3815]
### **Bug Description**
On iPad, the readonly input could not be focused, when the user taps the input field. Only the tokens could be focused.

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/master/playground/components/MultiComboBox/

### **Priority**
- [x] Low
- [ ] Medium
- [ ] High
- [ ] Very High

**Comment by niyap** [comment]
The issue is reproducible on iOS in Chrome and Safari as well. As stated above, the tokens in readonly mode could be focused, but there is also an issue, because they are focused on the second tap over.
