### ISSUE TITLE
ui5-multiinput: NMore popup wrong rendering

### ISSUE THREAD

**Issue by elenastoyanovaa** [SAP/ui5-webcomponents#3816]
### **Bug Description**
On iPad and on desktop with reduced size, the NMore popup has a wrong rendering - it renders separately from the input.

<img width="537" alt="Screenshot 2021-09-02 at 14 43 33" src="https://user-images.githubusercontent.com/11913394/131837759-aeec4f4e-a5ee-4767-b794-fa806b0b2f42.png">

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/master/playground/components/MultiInput/
2. Shrink the width. Try to refresh, the issue still occurs.

### **Isolated Example**
If possible, please provide an isolated example by forking [CodeSandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html).

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by niyap** [comment]
The issue is reproducible on iOS in Chrome and Safari as well
