### ISSUE TITLE
ui5-combobox: Double and triple focus when suggestion is selected

### ISSUE THREAD

**Issue by ndeshev** [SAP/ui5-webcomponents#3836]
### **Bug Description**
Depending on the selected suggestion the focus and pseudo-focus are either on the input and the selected suggestion, or on the input, selected suggestion and the first suggestion starting with the first typed character  - all at the same time.

### **Expected Behavior**
The visible focus should be only at one place.

### **Steps to Reproduce**
Double focus:
1. Go to the ComboBox test  page and type "B" in the first ui5-combobox.
2. Press Enter to select the suggestion (Bahrain).
3. Press the dropdown arrow to open the suggestions popover again - there are 2 visible focus outlines.

Triple focus:
1. Go to the ComboBox test  page and type "B" and then "E" in the first ui5-combobox.
2. Press Enter to select the suggestion (Belgium).
3. Press the dropdown arrow to open the suggestions popover again - there are 3 visible focus outlines.

### **Context**
- UI5 Web Components version: Latest RC
- OS/Platform: WinOS
- Browser: All

![combo-tripple-focus](https://user-images.githubusercontent.com/1590151/132117812-5079deb8-9010-4da0-8651-3a76e30fa0c4.JPG)

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by niyap** [comment]
The issue is reproducible on MacOS Chrome and FireFox - triple focus as presented in the screenshots. In Safari the whole behaviour is different when following the step to reproduce the issue but the result is double focus again.

**Comment by ndeshev** [comment]
Fixed with #3970
