### ISSUE TITLE
[SF][UI5-link][Safari]-No underline style when adding "text-decoration: underline" for ui5-link component

### ISSUE THREAD

**Issue by herlinsong** [SAP/ui5-webcomponents#3837]
**Describe the bug**
This issue only happened in Safari. I want to add link hover style "text-decoration: underline" for ui5-link when hovering on it's parent's node, but the underline of the ui5-link is not shown in Safari.
The underline of the ui5-link is shown in Chrome/Firefox/Edge/IE.

**Defect demo**
https://uvgbg.csb.app/

**UI5 WC Demo**
https://sap.github.io/ui5-webcomponents/playground/components/Link/

**To Reproduce**
1. Define "text-decoration: underline" for "linkHover" className
2. When hovering on the parent node, will add "linkHover" className for ui5-link

**Expected behavior**
The link has underline style
![image](https://user-images.githubusercontent.com/81735931/132208995-c96dee41-4329-47f1-b813-ac0c77d21d76.png)

**UI5 Web Components Information**
@ui5/webcomponents version: Current Version
Operating System: macOS Big Sur
Browser: Safari Version 14.1.1 (16611.2.7.1.4)

**Comment by gmkv** [comment]
Hi @SAP/ui5-webcomponents-topic-b 
The Link component has a bug in Safari where specifying `text-decoration: underline` doesn't work.

Regards,
Georgi

**Comment by ilhan007** [comment]
Fixed with 0.31.18
