### ISSUE TITLE
[ui5-popover]: Value State popover not positioned correctly on mobile

### ISSUE THREAD

**Issue by niyap** [SAP/ui5-webcomponents#3847]
### **Bug Description**
On mobile, usually the value state message is not correctly positioned.

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/master/playground/main/pages/TextArea/
2. Open the sample on mobile device

### **Isolated Example**
![textarea_mobile](https://user-images.githubusercontent.com/38278268/132315458-12155a48-dd72-46a6-a312-2bf36d8f9acb.jpeg)

### **Context**
- UI5 Web Components version: v1.0.0-rc.16
- OS/Platform: iOS
- Browser: Safari/Chrome

**Comment by ndeshev** [comment]
Hello team,

It seems like the positioning of the ValueState Message is calculated by the Popover component, we are only setting its placement-type and horizontal-аlign properties.

It has issues with the positioning on mobile devices, both on opening and scrolling.

Kind Regards,

Nikolay
