### ISSUE TITLE
Token: Icon is not correct is SAP Quartz Dark/HCB/HCW themes

### ISSUE THREAD

**Issue by niyap** [SAP/ui5-webcomponents#3861]
### **Bug Description**
Wrong icon is used in SAP Quartz Dark/HCB/HCW themes.

### **Expected Behavior**
The icon should be the same as the one in SAP Quartz Light theme. You can check the visual specification as well: https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2029205698

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/master/playground/main/pages/MultiInput/?sap-ui-theme=sap_fiori_3_dark

<img width="230" alt="Screenshot 2021-09-08 at 1 22 14" src="https://user-images.githubusercontent.com/38278268/132418057-22d11a5d-afd2-4979-9375-4aa898a24e48.png">

**Comment by stbodurov** [comment]
This issue has been fixed with #4222 and is no longer reproducible.
