### ISSUE TITLE
MultiInput: When single suggestion is selected and then deleted, the suggestion are no more visible

### ISSUE THREAD

**Issue by niyap** [SAP/ui5-webcomponents#3865]
### **Bug Description**
If you select a suggestion and then delete its corresponding token, entering a character after that, does not show the suggestions again. If more than one suggestion is selected, before deleting a token, the issue is not reproducible. In Safari, when there is a single suggestion selected and its corresponding token is deleted, the focus of the input field is lost as well.

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/master/playground/main/pages/MultiInput/?sap-ui-theme=sap_fiori_3
2. Navigate to 'Tokens + Suggestions' sample
3. Type "A" and select a suggestion
4. Delete the created token via press over its delete icon
5. Type "A" again -> nothing happens

**Comment by niyap** [comment]
Hello Colleagues,

As I can see, the issue is not reproducible anymore. So, I am closing the incident.

Kind Regards,
Niya

**Comment by gregorwolf** [comment]
Maybe this issue is related to #4425?
