### ISSUE TITLE
MultiInput/MultiComboBox: Value State message is not visible in FF in SAP Quartz Dark/HCB/HCW themes

### ISSUE THREAD

**Issue by niyap** [SAP/ui5-webcomponents#3866]
### **Bug Description**
Value State message is not visible in Firefox in SAP Quartz Dark/HCB/HCW themes

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/master/playground/main/pages/MultiInput/?sap-ui-theme=sap_fiori_3_dark
2. Click in the input field with value state warning or error
3. Notice that the value state message is not presented. Open the sample in another browser(Chrome, Safari) and compare.
The same behaviour is presented for the other mentioned themes.

### **Isolated Example**
<img width="262" alt="Screenshot 2021-09-08 at 9 27 09" src="https://user-images.githubusercontent.com/38278268/132457426-643aca42-1b81-446b-8d48-9d6976889307.png">

### **Context**
- UI5 Web Components version: v1.0.0-rc.16
- OS/Platform: macOS
- Browser: Firefox
- Affected component: ui5-multi-input

**Comment by gmkv** [comment]
FYI @SAP/ui5-webcomponents-topic-rl

**Comment by MapTo0** [comment]
Not reproducible

**Comment by niyap** [comment]
The issue is fixed as part of the following change: https://github.com/SAP/ui5-webcomponents/pull/3888
