### ISSUE TITLE
RTL: Strings containing numeric characters are broken

### ISSUE THREAD

**Issue by elenastoyanovaa** [SAP/ui5-webcomponents#3868]
### **Bug Description**
When a string contains numeric characters, when on RTL mode, the string is broken. For example:

1. TextArea
https://sap.github.io/ui5-webcomponents/master/playground/components/TextArea/?sap-ui-theme=sap_fiori_3&isrtl=true
Check the remaining characters string
2. Table
https://sap.github.io/ui5-webcomponents/master/playground/components/Table/?sap-ui-theme=sap_fiori_3&isrtl=true
Check the Load More items button

### **Expected Behavior**
Add dir="auto" to the element containing the text. See that it looks okay now.

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by ilhan007** [comment]
Hello @elenastoyanovaa  Not sure how to tackle all cases at once, so I would suggest going step by step and fix these two in the components, you can use "<bdi>" tags around the texts in question.

**Comment by niyap** [comment]
Hello Colleagues,

That is not an issue in the specific component. Using language like English (not RTL), the browser does not know how to arrange the text correctly. If you check both the text from the ui5-textarea or ui5-table as a value of a native HTML element with attribute dir="rtl", you will notice the same result.
We have checked the behaviour in Aribic and it works as expected.

Kind Regards,
Niya
