### ISSUE TITLE
ColorPicker: color picker does not allow to pick color after blue

### ISSUE THREAD

**Issue by an-grotesque** [SAP/ui5-webcomponents#3875]
Reproducible even in storybook.

1. Go to [UI5-Storybook](https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-colorpicker--default-story)
2. Click on color stripe somewhere after blue. Pink for example.
3. Click anywhere in color shade box.
4. See your selection in color stripe reset to the beginning.

**Expected behavior**
Selection in color shade box retained

**Screenshots**
![Case2_color_palette_is_reset_when_select_bright_colors](https://user-images.githubusercontent.com/90375787/132635280-d6cca606-2d13-49b9-9879-c8dcfd9aad39.gif)

**UI5 Web Components for React Information**
Reproduced on latest version available on storybook.
Operating System: Win10
Browser: Chrome

**Comment by gmkv** [comment]
Hi @SAP/ui5-webcomponents-topic-b 

This is a strange buggy interaction with the Color Picker component. 
To reproduce, pick a hue and then click on the pane. The result is that the hue will get changed, so you end up with a completely different color.

https://codesandbox.io/s/ui5-webcomponents-forked-v0k91?file=/index.html

Regards,
Georgi

**Comment by Todor-ads** [comment]
Hi @an-grotesque and @Lukas742,
The issue is fixed and the fix is available on the master branch. This fix will be delivered with rc 16

Regards,
Todor
