### ISSUE TITLE
ui5-shellbar injects empty h2 for secondary title is not provided

### ISSUE THREAD

**Issue by gurkirpalgill** [SAP/ui5-webcomponents#3889]
### **Bug Description**
ui5-shellbar is used without secondary title e.g.
`<ui5-shellbar id="shellbar" ui5-shellbar="" with-logo="" breakpoint-size="XXL" primary-title="Onboarding">`

Its injecting empty h2 tag :
`<h2 class="ui5-shellbar-secondary-title"><!----><!----></h2>`

This create axe devtools warning that `Headings should not be empty`

### **Expected Behavior**
If `secondary-title` attribute is not used, it should not inject empty h2 tag.

### **Steps to Reproduce**
Use ui5-shellbar without providing secondary title e..g.
`<ui5-shellbar id="shellbar" ui5-shellbar="" with-logo="" breakpoint-size="XXL" primary-title="Onboarding">`

### **Context**
- UI5 Web Components version: 0.31.16
- OS/Platform: MacOS
- Browser: Chrome
- Affected component: ui5-shellbar

### **Log Output / Stack Trace / Screenshots**

![Empty heading](https://user-images.githubusercontent.com/65705637/132738148-48731690-fff6-4c30-8f66-f2cb00a5b9a5.jpg)
<img width="1910" alt="Screen Shot 2021-09-09 at 10 48 44 AM" src="https://user-images.githubusercontent.com/65705637/132738179-9291dc72-1083-405e-8e58-6ff69a14703d.png">

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by ilhan007** [comment]
Hi @gurkirpalgill do you really use **0.31.16**
because this is a duplicate of: https://github.com/SAP/ui5-webcomponents/issues/3698
that has been fixed with https://github.com/SAP/ui5-webcomponents/pull/3737 which avoids rendering the **h2 tag** if **secondary-title** attribute is not set and released with **0.31.16**

**Comment by gurkirpalgill** [comment]
this is still an issue. we are using 0.31.16
```
    "@ui5/webcomponents": "~0.31.16",
    "@ui5/webcomponents-base": "~0.31.16",
    "@ui5/webcomponents-fiori": "~0.31.16",
    "@ui5/webcomponents-icons": "~0.31.16",
    "@ui5/webcomponents-react": "^0.131.16",
```
<img width="1894" alt="Screen Shot 2021-09-13 at 6 33 01 PM" src="https://user-images.githubusercontent.com/65705637/133180274-90c0301b-aa8d-4e8f-9641-a8b3ac2f6697.png">

**Comment by ilhan007** [comment]
Hello @gurkirpalgill can you provide a reproducible sample

I created a sample using 0.31.17 the latest 0.31 patch: https://codesandbox.io/s/ui5-webcomponents-forked-nk1cl
and the "h2" tag is not rendered.


BR,
ilhan

**Comment by gurkirpalgill** [comment]
we upgraded to use 0.31.17. issue is resolved after the upgrade.
