### ISSUE TITLE
No Data Text for Table Component

### ISSUE THREAD

**Issue by gustavokath** [SAP/ui5-webcomponents#389]
In the table component, I'm missing the ability to set a specific text when there is no data to be loaded. Like in the UI5 we have the property `noDataText` for the component `sap.m.Table` or others like it. The current behavior is letting an empty table, that might not clarify what is going on to the user.

I've tried also to use only one `ui5-table-row` with a `ui5-table-cell` inside it and change its colspan and other properties to fill all header spaces I have in my table. But it does not work, It does not render right the table component. 

So I want to rise this to you and discuss what would be the best approach to this issue.

**Comment by MapTo0** [comment]
Hey @gustavokath 

As much as I understand your issue, there are two things reported here:
- feature request for noDataText
- Some layouting issue with the row and cell

I would suggest that we collaborate and discuss these two.

**No Data Text**
Sounds good to me. Do you expect some default text or you want to have it always outside the component as an API?

**Issue**
Could you please help us and provide your use case as an example?
Starting point: https://glitch.com/~merciful-continent (click remix this)

**Comment by gustavokath** [comment]
Hi @MapTo0 

For the request for `noDataText` what I think that would be the best solution to me is to provide a way to pass a string to a component attribute where I can inform the string I expect. 

The issue, came present when I tried to make an workaround the add one cell line in table the fills the full row. I'll add what I've tried to do in the link you provided me.

**Comment by gustavokath** [comment]
Hi @MapTo0 
I've made a suggested solution in PR #402.
Let me know if this proposed solution would be a good feature to add to the `ui5-table` component.
Also, feel free to add any feedbacks
