### ISSUE TITLE
ui5-badge:  Text color and border color are wired when set  color schema to  8

### ISSUE THREAD

**Issue by sleric1024** [SAP/ui5-webcomponents#3923]
### **Bug Description**
Incorrect color of ui5-badge

### **Expected Behavior**
Color should be correct.

### **Steps to Reproduce**
1. Go to https://codesandbox.io/s/ui5-webcomponents-forked-ut5uh?file=/index.html
2. Color of badge is not correct.

### **Isolated Example**
https://codesandbox.io/s/ui5-webcomponents-forked-ut5uh?file=/index.html

### **Context**
- UI5 Web Components version: 0.31.17
- OS/Platform: MacOS
- Browser: Chrome

### **Log Output / Stack Trace / Screenshots**
![image](https://user-images.githubusercontent.com/5724592/133266709-1e6bbc3e-b87f-42d7-b11b-2fdb5c8809fe.png)

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: Successfactors
- Bussiness impact: {...}

**Comment by terezamch** [comment]
Hello colleagues @SAP/ui5-webcomponents-topic-rd,

The badge with color-scheme="8" has lost it's greenish color.
https://sap.github.io/ui5-webcomponents/master/playground/components/Badge/

Could you please take action?

Thanks,
Tereza

**Comment by gmkv** [comment]
Hi @sleric1024 
This is intended.
The visual design of `color-scheme=8` of the Badge component was recently updated due to color contrast concerns.
I won't post internal links here, but if you are interested, contact me on Teams or Slack for more info.

Best regards,
Georgi Minkov

**Comment by ilhan007** [comment]
released with 0.31.18
