### ISSUE TITLE
[BUG][SF][Urgent - Expect WithIn One Week][UI5-List] Ensure interactive controls are not nested 

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents#3927]
**Dear colleagues,**
I am from SuccessFactors Web Experience Shanghai team.
we use NVDA to test a11y issues in our project

**Reproduce Step:**
Open https://github.wdf.sap.corp/pages/xweb/assignment/app.html?mock#/assignment-detail/ao/2
Click the applicants tab

**Bug Description**
`Ensure interactive controls are not nested ` reported by `axe-core `
![nested control issue](https://user-images.githubusercontent.com/78520316/133362785-d74e7dda-ca06-45b9-a719-20140c9544e8.png)

**Comment by fifoosid** [comment]
FYI @SAP/ui5-webcomponents-topic-rd

**Comment by ilhan007** [comment]
Fixed with 0.31.18
