### ISSUE TITLE
It should be possible to import all web components as standard ES6 modules

### ISSUE THREAD

**Issue by pskelin** [SAP/ui5-webcomponents#393]
**Is your feature request related to a problem? Please describe.**
Currently, components that have dynamic assets (like translations or the cldr data) express that relation via the ES6 import statements, although the assets are in json format. This is non-standard behaviour and breaks when importing from browsers that can import modules, when using unpkg.com or with a multitude of build and dev tools that do not have a json plugin configured.

**Describe the solution you'd like**
While the json import is convenient for app developers that use a webpack based rich build configuration, the alternative of importing standard modules and loading the assets individually should also be offered.

**Describe alternatives you've considered**
Both approaches should be possible.

**Additional context**
related: #272

**Comment by MapTo0** [comment]
As of https://github.com/SAP/ui5-webcomponents/pull/479 everything should work :)
