### ISSUE TITLE
[SF][Badge]: color of badge is override when header bar loaded

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents#3934]
### **Bug Description**
When set color scheme to 8, color of badge is override after header loaded, It should keep black instead of green.
Please help check it. 

### **Steps to Reproduce**
 Go to https://qacand.hcm.ondemand.com/sf/ompassignment?action=create#/assignment-detail/ao/9361?source=omp_manage .

### **Isolated Example**
Before header bar load: 
<img width="1310" alt="Screen Shot 2021-09-16 at 3 55 44 PM" src="https://user-images.githubusercontent.com/78520316/133573373-be52c96e-54d2-472f-a0c8-0c51f9b66cea.png">

After  header bar loaded: 
![image](https://user-images.githubusercontent.com/78520316/133572743-4448c450-5124-4780-bbbc-141902dbc905.png)

More details: 
https://user-images.githubusercontent.com/78520316/133574066-c77529c2-a493-461a-944f-37a983ac7234.mov

### **Context**
- UI5 Web Components version: {0.31.17}
- Browser: {chrome}

High Prio

Please let me know if you need any information to logon qacand page.

**Comment by terezamch** [comment]
Hello @sfsf-xweb-sh,

A Badge with color scheme 8 results in greenish component. Please refer to https://sap.github.io/ui5-webcomponents/playground/components/Badge/ 

Also, I cannot log into the system for some reason. Could you please provide the credentials?

Best regards,
Tereza

**Comment by fifoosid** [comment]
Hi @SAP/ui5-webcomponents-topic-rd 

The bug can be reproduced here: https://codesandbox.io/s/ui5-webcomponents-forked-t58r5?file=/src/index.js
Steps to reproduce: 
1. Try commenting out the import of the ```ui5-shellbar```
2. Check that the colours of the ```ui5-badge``` changes. When the Shellbar is imported, the badge is green, when it is not- the badge is black


@sfsf-xweb-sh in order for your tickets to be processed faster, please add an isolated sample using [codesanbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html)

**Comment by gmkv** [comment]
The fix for this will be included with the next release of v0.31.XX.

**Comment by sfsf-xweb-sh** [comment]
Hi @terezamch，
I left the credentials on slack https://sap-successfactors.slack.com/archives/CTHEMAZ8C/p1631842772047900?thread_ts=1631582945.038200&cid=CTHEMAZ8C. Please take a look.
Thanks.

Josephine

**Comment by fifoosid** [comment]
Issue is resolved with #3926
