### ISSUE TITLE
DateTimePicker Icon not accessible by keyboard

### ISSUE THREAD

**Issue by lormanlau** [SAP/ui5-webcomponents#3945]
### **Bug Description**
Navigation with the keyboard is not possible to the calendar icon in the DateTimePicker component and the accessibility message does not match.

### **Expected Behavior**
A clear and concise description of what you expect to happen.
Use should be able to navigate to the DateTimePicker calendar icon using keyboard

### **Steps to Reproduce**
1. Focus on the DateTimePicker component.
2. Try using keyboard to navigate to the calendar icon to open the popover with no success

### **Isolated Example**
If possible, please provide an isolated example by forking [CodeSandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html).
https://sap.github.io/ui5-webcomponents/playground/components/DateTimePicker/

### **Context**
- UI5 Web Components version: 1.0.0-rc.15
- OS/Platform: Mac OS 11.5.2
- Browser: Google Chrome Version 93.0.4577.63 (Official Build) (x86_64)
- Affected component: DateTimePicker

### **Log Output / Stack Trace / Screenshots**
<img width="1190" alt="Screen Shot 2021-09-16 at 5 54 50 PM" src="https://user-images.githubusercontent.com/12117112/133706877-e73caa03-1c2a-4919-a63b-4a3c25ea1a62.png">

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SAP SuccessFactors
- Bussiness impact: Medium

**Comment by ilhan007** [comment]
Hello @lormanlau the DatePicker's (and DateTimePicker) icon can't be reached via keyboard by design. There are other means to open the popup - F4., ALT+UP, ALT+DOWN.
