### ISSUE TITLE
Axe Issue: Block Layer for Popups has a tabindex=1

### ISSUE THREAD

**Issue by codefactor** [SAP/ui5-webcomponents#3955]
### **Bug Description**
This is a breakout issue from https://github.com/SAP/ui5-webcomponents/issues/3933

#### 4. Elements should not have tabindex greater than zero

_The ui5 block layer maybe should have tabindex=0?_

This one comes up for popups that have a block layer underneath - for some reason the tabindex=1 for this layer, maybe it should be 0?

### **Expected Behavior**
Opened dialogs should not have Axe errors

### **Steps to Reproduce**
See https://github.com/SAP/ui5-webcomponents/issues/3933 for more info on axe
Run the axe dev tools on shellbar and open a popover like the account menu, and then run the tool. It should complain about this tabindex greater than 0

### **Isolated Example**
If possible, please provide an isolated example by forking [CodeSandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html).

### **Context**
- UI5 Web Components version: {...}
- OS/Platform: {...}
- Browser: {...}
- Affected component: {...}

### **Log Output / Stack Trace / Screenshots**
```
{...}
```
### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Bussiness impact: {...}

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-rd could you check if "Elements should not have tabindex greater than zero" is an accessibility rule that we break by setting tabindex=1 on the pop's block layer.

**Comment by GerganaKremenska** [comment]
Hello @ilhan007, 

We have comunicated this with the accessibility experts and there statement is that if something is not meant to recieve focus  it shoudl not have a tabindex grater that 0.
Do we expect the block layer at some point to recieve focus?
If not, can we remove the the tabindex from the blocklayer?

**Comment by codefactor** [comment]
@ilhan007 ,

We need to come to a conclusion on this ticket if possible. It sounds like we need to remove the tab index from the block layer?

**Comment by gmkv** [comment]
Hi @codefactor 

This issue is solved by the linked PR #4324 and the fix will be available with the next release of the webcomponents library - v1.1.0 around the 21st of January.

Regards,
Georgi
