### ISSUE TITLE
`<ui5-list>` Axe Issues

### ISSUE THREAD

**Issue by codefactor** [SAP/ui5-webcomponents#3957]
### **Bug Description**
This is a break out issue from the following:
https://github.com/SAP/ui5-webcomponents/issues/3933

#### 5. Document should not have more than one banner landmark

_maybe the `<ui5-list>` should put a role onto the `<header>` so it doesn't think that's a "banner" landmark?_

This one comes up for any `<ui5-list>` element when there is also a `<ui5-shellbar>` because the ui5-list adds a `<header>` element and so it complains that there are 2 banners - one is the shellbar with `<div role="banner">` and one for the `<header>` for the `<ui5-list>`. You'd need to have a page with both to see this.

#### 7. ARIA input fields must have an accessible name

_maybe there needs to be an aria-label or aria-labeledby for the `<ul>` of a `<ui5-list>`?_

This is related to the `<ul>` output from the `<ui5-list>` tag, it is complaining that it doesn't have any sort of label but since it has a role="listbox" it needs a label or to be labeled by something.

### **Expected Behavior**
The `<ui5-list>` should never have Axe issues.

### **Steps to Reproduce**
See https://github.com/SAP/ui5-webcomponents/issues/3933 for help to set up Axe Dev tools

### **Isolated Example**
If possible, please provide an isolated example by forking [CodeSandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html).

### **Context**
- UI5 Web Components version: {...}
- OS/Platform: {...}
- Browser: {...}
- Affected component: {...}

### **Log Output / Stack Trace / Screenshots**
```
{...}
```
### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Bussiness impact: {...}

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-p could you please take a look of this ACC issues, related to the List

**Comment by dobrinyonkov** [comment]
Hello @codefactor,

in regards to the second observation (7. ARIA input fields must have an accessible name), with a recent change (#3952) we changed the default role of the `ui5-list` to list, so accessible name is no longer required. However, the `ui5-list` component provides a property called accessibleName in case the application needs to set one in the context of the use case.

I will further investigate the case with the landmark role issue.

Kind Regards,
Dobrin

**Comment by dobrinyonkov** [comment]
Hello @codefactor,

In regards to the first observation - "5. Document should not have more than one banner landmark".

When used as a ‘top’ level element, the `<header>` is a landmark and signifies the ‘banner’ area of a page – typically containing the logo, site name, and maybe the primary navigation etc. Note that `<header>` elements can also be used inside other sectioning elements. The `<header>` element is not treated as a landmark when it is a descendant of the following HTML sectioning elements:

- article
- aside
- main
- nav
- section

The `ui5-list` behaves as expected in both cases. When used as a top level element the role is of the header is mapped to `banner` and if used inside a `<main>` for example, it is mapped to `header` as а non-landmark.

If applications still find this to not be suitable, the `header` slot can be used to set a custom element.

Kind Regards,
Dobrin
