### ISSUE TITLE
ValueStateHeader: Align the visualisation according to the specification among all input components 

### ISSUE THREAD

**Issue by niyap** [SAP/ui5-webcomponents#3964]
### **Bug Description**
The value state header is differently visualised among the components:
**ui5-input** When suggestions drop down has a vertical scrollbar, vertical white lines are presented on the left and right side of the value state header.
**ui5-combobox** When suggestions drowdown has a  vertical scrollbar presented, it covers the value state header as well. Something more, it depends on the resolution but in some cases two dimensional scrollbar is presented, which is totally incorrect according to the accessibility standard. Horizontal scrollbar should never be presented. 
That issue is also presented in **ui5-multi-combobox** component
**ui5-multiinput** Text in value state header is not centered, but it will be handled as part of another issue.

### **Expected Behavior**
Check the specification as well as can compare the visualisation with UI5.

### **Steps to Reproduce**
1. Go to the test page of each mentioned component
2. Check the samples where value state header is used

### **Context**
- UI5 Web Components version: v1.0.0-rc.16
- OS/Platform: macOS
- Browser: Safari/Chrome

**Comment by niyap** [comment]
After a discussion within the team, we decided to handle that issue as a backlog item, so I am moving it to the Planning board.

Kind Regards,
Niya

**Comment by hristop** [comment]
Hi @niyap ,

Could you please check if this is still relevant after the Horizon implementation? 
It is not something urgent. 

Best Regards,
Hristo

**Comment by hristop** [comment]
Internal BLI was created: FIORITECHP1-28785

**Comment by nikoletavnv** [comment]
Visual appearance of value state header message for mobile devices has been aligned with the components visual design specifications.
