### ISSUE TITLE
ComboBox: Suggestions dropdown is closed on click over the value state header

### ISSUE THREAD

**Issue by niyap** [SAP/ui5-webcomponents#3966]
### **Bug Description**
Suggestions dropdown is closed on click over the value state header.

### **Expected Behavior**
Suggestions dropdown remains open

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/master/playground/main/pages/ComboBox/
2. Open the suggestion dropdown of the first sample with value state error
3. Click over the value state header

The issue is not reproducible in the other input components (ui5-input, ui5-multi-combobox)

### **Context**
- UI5 Web Components version: v1.0.0-rc.16
- OS/Platform: macOS
- Browser: Chrome/Firefox/Safari
- Affected component: ui5-combobox

**Comment by ndeshev** [comment]
Fixed with #3970
