### ISSUE TITLE
3rd applications can navigate outside of Dialog.

### ISSUE THREAD

**Issue by lormanlau** [SAP/ui5-webcomponents#4001]
### **Bug Description**
When using a screen reader / 3rd party application, user is able to navigate outside the dialog area.

### **Expected Behavior**
A clear and concise description of what you expect to happen.
User should only stay inside of the dialog box. https://sapui5.hana.ondemand.com/sdk/#/entity/sap.m.Dialog/sample/sap.m.sample.Dialog does not have this issue.

### **Steps to Reproduce**
1. Launch JAWS 2020
2. Launch a UI5 Web Components Dialog from https://sap.github.io/ui5-webcomponents/playground/components/Dialog/
3. Click on the heading of the dialog
4. Press the H key, for navigating to headings a few times and then tab.
5. Observe that you are able to focus outside the Dialog.

### **Isolated Example**
https://sap.github.io/ui5-webcomponents/playground/components/Dialog/

### **Context**
- UI5 Web Components version: 1.0.0-rc.15
- OS/Platform: Windows 10
- Browser: Google Chrome
- Affected component: Dialog

### **Log Output / Stack Trace / Screenshots**
<img width="2032" alt="Screen Shot 2021-09-24 at 2 05 11 PM" src="https://user-images.githubusercontent.com/12117112/134740011-317149a0-0ef3-46ef-ae88-b2ef60b9883d.png">

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SAP SuccessFactors
- Bussiness impact: Medium

**Comment by Todor-ads** [comment]
Hello @lormanlau,
Thank you for sharing this finding.
Can you check if this problem persist? I tried to reproduce it, but I failed. It is not possible to focus anything outside of Dialog.
Regards,
Todor

**Comment by lormanlau** [comment]
Hi @Todor-ads this problem still persists, using Insert + F6 (list all headings) can also take you out of the dialog.

**Comment by ilhan007** [comment]
Hello @lormanlau can you try with the latest version, notice the "master" in the path of the URL:

https://sap.github.io/ui5-webcomponents/master/playground/components/Dialog/

**Comment by TeodorTaushanov** [comment]
Hi,

This is not a valid condition when JAWS (or any other screen reader) is used, as there is no mouse click in that case. 

Best,
Teo
