### ISSUE TITLE
ui5-shellbar profile button title override

### ISSUE THREAD

**Issue by JarrettChan** [SAP/ui5-webcomponents#4009]
### **Feature Request Description**
We currently can not provide the profile button with our title.
https://github.com/SAP/ui5-webcomponents/blob/master/packages/fiori/src/ShellBar.hbs#L163
SuccessFactors header has been providing a title for the profile button such as `Account Navigation for Alan Chin ‎(achin)‎` by passing along a parameter for the user, so we can't just replace it in the messagebundle.

The other button titles are either new or not significantly different from the SF ones.

Please provide a hook on the ui5-shellbar for this.

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### **Stakeholder Info** (if applicable)

- Organization: SuccessFactors

**Comment by JarrettChan** [comment]
Hi @ilhan007 

That would work. Can you provide an estimate of when this could be implemented?

**Comment by codefactor** [comment]
This can work for the short term, but wouldn't all users of Shellbar WC need to customize the tooltip for the Profile button?

Is there any problem accepting the tooltip as an optional attribute on the shellbar?

**Comment by codefactor** [comment]
On second thought, being able to override the button entirely might be beneficial if we ever needed to customize the button for other reasons. In know our customers have been complaining a lot about not showing any visual indicator when they are a proxy. I suspect we might want to add something to the button to show that.

So maybe we could use the online thing in the future for other reasons but for now we only need to customize the title. But I feel this would be something lots of users might benefit from being able to do that without extending the shellbar.

We have no problem from our end, though, to extend the shellbar, if that's what we need to do.
