### ISSUE TITLE
Fast navigation using F6 for UI5 WC library

### ISSUE THREAD

**Issue by saorabhkr** [SAP/ui5-webcomponents#4013]
### **Feature Request Description**

Fast navigation via F6 is supported by SAPUI5 controls and it is not there for the web components. Can we have this feature for content block switching via F6 or any alternative for fast navigation techniques for web components control, so for the users, it's easy to navigate also avoid a11y errors. 

### **Proposed Solution**
Block switching for SAPUI5 controls
https://openui5.hana.ondemand.com/topic/d23e2cf618a44382a203691e8a0baef4

### **Additional Context**

For course home, while A11y testing we got this ticket WEF-13301 where we got an issue reported by experts that for the page block switching is missing via F6.

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### **Stakeholder Info** (if applicable)

Organization: SuccessFactors

**Comment by ilhan007** [comment]
Hello @saorabhkr thank you for your request. I am registering it and will be discussed in the next 1-2 weeks then I will get back to you with a statement from our side.

**Comment by ilhan007** [comment]
Hello @saorabhkr the issue has been divided to 4 issues, linked above as the components are distributed in 4 areas/topics 
you can follow the progress there:

https://github.com/SAP/ui5-webcomponents/issues/4349
https://github.com/SAP/ui5-webcomponents/issues/4350
https://github.com/SAP/ui5-webcomponents/issues/4351
https://github.com/SAP/ui5-webcomponents/issues/4352

**Comment by don-obrien** [comment]
@ilhan007 , we are seeing an issue with F6 group skipping on ui-tab-container in one of our pages.
Is the support there for this, and does it work in other places?

**Comment by ilhan007** [comment]
Hello @don-obrien can you give us an example, TabContainer should have F6 working.
