### ISSUE TITLE
Dialog backdrop covers the complete screen when used inside of an element which ancestors have set the z-index

### ISSUE THREAD

**Issue by veith** [SAP/ui5-webcomponents#4014]
### **Bug Description**
The complete viewport is covered by the ui5-block-layer when the dialog resides inside a ui5-page. The z-indexes of the dialog and the backdrop are correct. 

The error itself is caused by any parent element which have set a z-index.

### **Expected Behavior**
The dialog should not be covered with the backdrop.

### **Steps to Reproduce**
Click on the open dialog button in the isolated example

### **Isolated Example**
live: https://e9o4l.csb.app/
source: https://codesandbox.io/s/ui5-dialog-error-e9o4l?file=/index.html

### **Context**
- UI5 Web Components version: 1.0.0-rc.15, 0.33.0
- OS/Platform: macOs
- Browser: safari, chrome latest
- Affected component: webcomponents/dist/Dialog.js

### **Priority**
- [x] Low
- [ ] Medium
- [ ] High
- [ ] Very High

**Comment by plamenivanov91** [comment]
Hello @veith ,

The problem is that in your implementation, the Dialog is a child of the Page and therefore the Dialog's z-index is no longer relevant.

I recommend implementing the Dialog outside of the Page like so:
https://codesandbox.io/s/ui5-dialog-error-forked-rnlkd

I don't see any reason that the Dialog should be a child of the Page, I think it's okay if it's on the level of the Page.

Is this solution good enough for you ?

Regards,
Plamen Ivanov

**Comment by veith** [comment]
@plamenivanov91 I have build an isolated example to show the cause. 
We have a lot of nested components from different teams, which decide themself, if they need to show a dialog. The component themself can not know if they are inside of a component which have a z-index (like Ui5Page) set.  

FYI Meanwhile we have a simple solution which consists of 2 components. One for the "dialog" content with the same API like Ui5Dialog and one which resides in the application root, which *displays* the dialog. 

The `show` method triggers a bubbling and composed event which is catched by the first display component. The display component then moves the dialog dom node in to its parent where it can be sure that no z-index was set. If no display component is defined, the component behaves like a Ui5Dialog.

The issue was meant *informative* because i thought, that sooner or later, someone else will run in to the same problem.

**the extended dialog**
```js
class FuroUi5Dialog extends Dialog {
  show() {
    // only register once
    if(!this._furoDialogRegistered){
      const customEvent = new Event('register-furo-ui5-dialog', {composed: true, bubbles: true});
      customEvent.detail = this
      this.dispatchEvent(customEvent)
      this._furoDialogRegistered = true
    }
    super.show();
  }
}
```

**the display component**
```js
class FuroUi5DialogDisplay extends (LitElement) {
  connectedCallback() {
    this.parentNode.addEventListener('register-furo-ui5-dialog', e => {
      e.stopPropagation(); // the first display handles the dialog
      this.parentNode.appendChild(e.detail);
    });
  }
}
window.customElements.define('furo-ui5-dialog-display', FuroUi5DialogDisplay);
```

**Comment by veith** [comment]
Maybe a hint or note  in the documentation of the `Dialog` component would be nice.

**Comment by veith** [comment]
@plamenivanov91 It is mentioned in the documentation that using dialog in components with z-index do not work. But as a note on the *ES6 Module Import*.
