### ISSUE TITLE
[ResponsivePopover]: it is no way to styling pointer

### ISSUE THREAD

**Issue by gagarin880120** [SAP/ui5-webcomponents#4056]
**Describe the bug**
When I try to style ResponsivePopover component, styles are not applied to pointer. When I try to style elements, which are under shadow-root (try to style exactly pointer via styled-components), I couldn't do this.

**Isolated Example**
*Please provide an isolated example if possible by forking [this codesandbox](https://codesandbox.io/s/ui5-webcomponents-react-template-29l34).*
https://codesandbox.io/s/confident-mountain-c494j?file=/src/App.js

**Expected behavior**
Pointer should match the border and shadow as the rest of the popover

**Screenshots**
![image](https://user-images.githubusercontent.com/44781670/135614625-156eb7b1-b3d1-46c9-8448-f60889fed9e3.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.0.0-rc.15
`@ui5/webcomponents-react` version: 0.18.9
Operating System: Windows10
Browser: Google Chrome

**Additional context**

**Comment by TeodorTaushanov** [comment]
Hi @gagarin880120, 

In the Popover we're using the box-shadow, so in your case you can override the "--sapContent_Shadow2" css parameter like:

```
"--sapContent_Shadow2": "0 0 0 0.0625rem red, 0 0.625rem 1.875rem 0 rgba(0,0,0,0.3)"
```


https://codesandbox.io/s/runtime-bird-ffqglo?file=/src/App.js

Best,
Teo
