### ISSUE TITLE
[MultiComboBox] value state popover is not correct

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents#4096]
### **Bug Description**
The MultiCombobox value state popover when value-state="Information" does not seem to be correct ("Warning" and "Error" work fine).  There is a popover, but something a bit strange, not the regular "Informative entry" value state popover.

### **Expected Behavior** 
I expect to see the regular "Informative entry" value state popover.

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/master/playground/main/pages/Input/
2. Find the MultiCombobox with value-state="Information" (you will have to scroll a bit - see the screenshot to find the MultiComboBox in question) or just set value-state="Information" to any MultiCombobox.
3. Focus the text field.
4. Observe the displayed pop up (see the screenshot below).

### **Context**
- UI5 Web Components version: master
- OS/Platform: MacOS
- Browser: Chrome
- Affected component: ui5-multi-combobox

### **Log Output / Stack Trace / Screenshots**

<img width="900" alt="Screenshot 2021-10-08 at 14 18 16" src="https://user-images.githubusercontent.com/15702139/136547698-24b83357-4ee9-4821-9674-46b175f60970.png">
<img width="575" alt="Screenshot 2021-10-08 at 14 12 19" src="https://user-images.githubusercontent.com/15702139/136547717-b1665f25-b307-4cdd-97e8-b1f56ef177a9.png">

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

**Comment by niyap** [comment]
Hello Colleagues,

The issue is fixed as part of the following pull request: #4222
