### ISSUE TITLE
[View Settings Dialog]: confirming dialog only provides UI-visible strings of selected item

### ISSUE THREAD

**Issue by tonyh1982** [SAP/ui5-webcomponents#4110]
### **Bug Description**
This is rather an improvement request. Currently, when confirming the View Settings Dialog, you only get the UI-visible string of the selected element, which not always equals the string that needs to be send to the service. Furthermore, the string is not stable as it could be translated whereas the string in the service must not be translated. Of course I could dig in the source element but this is quite some effort.

### **Expected Behavior**
I would prefer a solution where I could also specify a technical ID for each ui5-sort-item that additionally is passed when confirming the dialog. Or is there a nice solution that I'm not aware of?

### **Context**
- UI5 Web Components version: next

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by DMihaylova** [comment]
For better tracking I'm closing this item and progress of the task could be followed in a duplicate one:
https://github.com/SAP/ui5-webcomponents/issues/7579
