### ISSUE TITLE
[SF] [MessageBox] [A11y] Title and text content not getting announced automatically by screen reader

### ISSUE THREAD

**Issue by 2bno1** [SAP/ui5-webcomponents#4135]
**Describe the bug**
The title and text content of popup message box is not getting announced automatically by screen reader.

**Isolated Example**
https://sap.github.io/ui5-webcomponents-react/?path=/docs/modals-popovers-messagebox--default-story

**To Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents-react/?path=/docs/modals-popovers-messagebox--default-story
2. Click on 'Open messagebox'button
3. Check whether the title and text of the popup message box is announced automatically by screen reader.

**Expected behavior**
Title and text content of popup message box is getting announced automatically by screen reader

**Screenshots**
![image](https://user-images.githubusercontent.com/1751846/132486592-07459330-286d-4bba-8425-792c27e79292.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 0.31.16
`@ui5/webcomponents-react` version: 0.131.18
Operating System: Windows
Browser: Chome

**Comment by nnaydenow** [comment]
Hi @2bno1 ,

Could you share which version of NVDA screen reader you are using?

With the latest everything seems to be read out correctly.

Regards,
Nayden

**Comment by 2bno1** [comment]
@Lukas742 Sorry for late reply. From [code](https://github.com/SAP/ui5-webcomponents-react/pull/2208/files#diff-1d83b7b33e82b2b02cd431bc9109b9e8f07c25464d20b33b4753c33743e058b5R353),  the content of message box is appended to `accessibleName` only when it is raw text. If the content is wrapped in another element like `div`, it would not be added into `accessibleName` and would not be announced by screen reader.

I tested [sample](https://codesandbox.io/s/reverent-tereshkova-d2d6h?file=/src/App.js) by NVDA version of 20221.2, and the content is not be announced.

<img width="1305" alt="Screen Shot 2021-11-02 at 9 39 04 AM" src="https://user-images.githubusercontent.com/1751846/139772937-83b34c31-1974-41c9-b9dc-02de40505ea5.png">

**Comment by Lukas742** [comment]
Hi @2bno1 

as mentioned in the docs, only text (`strings`) is supported by the `children` prop. 

> Although this prop accepts HTML Elements, it is strongly recommended that you only use text in order to preserve the intended design and a11y capabilities.

**Comment by LidiyaGeorgieva** [comment]
Hello @Lukas742 ,
> Hi @nnaydenow, in the example I provided it's read out correctly only because I added the `accessibleName` prop to the `Dialog` itself. My question was if that's the right approach or if it's possible to add aria-labels or some custom property to the header or content, to make it more distinguishable. Without the `accessibleName` non focusable text is not read out in NVDA version 2021.2 (latest).

Yes, using accessibleName is the right approach.

@2bno1 , are there any open questions or the issue is clarified?

Best Regards,
Lidiya
