### ISSUE TITLE
TextArea: max length text is cut short when using rows=1, required field has no effect

### ISSUE THREAD

**Issue by rchrdchn** [SAP/ui5-webcomponents#4142]
**Describe the bug**

**Isolated Example**
https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-textarea--default-story

**To Reproduce**
1. Go to `ui5-webcomponents-react` [TextArea playground](https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-textarea--default-story)
2. Change the following properties: `rows='1'` and `maxlength='100'`
3. See how `100 characters remaining` text is cut short

**Expected behavior**
Max length to be fully displayed height-wise

**Screenshots**
<img width="1017" alt="Screen Shot 2021-10-20 at 15 16 54" src="https://user-images.githubusercontent.com/11576789/138180517-fe791aa0-2371-4bed-9132-03217f94cb1e.png">

**UI5 Web Components for React Information**
`@ui5/webcomponents-react` version: @ui5/webcomponents-react - v0.18.11

**Comment by d3xter666** [comment]
Hi @rchrdchn ,

Could you elaborate on that? What is your expectation for a working ``required`` attribute?

Cheers

**Comment by rchrdchn** [comment]
Hi @d3xter666 - the `TextArea` field does not display any error handling warning/message when the field is empty on a form/dialog that has the `required` property on the component.

**Comment by Lukas742** [comment]
Hi @rchrdchn @d3xter666 

the issue with the `required` property could be related to this issue: https://github.com/SAP/ui5-webcomponents/issues/3498

**Comment by d3xter666** [comment]
Hi @rchrdchn ,

I believe this should be somehow application logic.
Probably you mean that `` formElement.checkValidity() `` does not work as expected?

@vladitasev Could you help a bit with the `` required `` property? Is it something that needs to be handled by app developers or by the framework? Am I missing something here?

Cheers

**Comment by rchrdchn** [comment]
> the issue with the required property could be related to this issue: #3498

Yes, thanks! It seems like they are related with one difference that https://github.com/SAP/ui5-webcomponents/issues/4142 is for `TextArea`, while https://github.com/SAP/ui5-webcomponents/issues/3498 is for `Input`

**Comment by rchrdchn** [comment]
Hi @Lukas742 - just wanted to follow-up on this issue and wondering what's the ETA for fixing this issue. Thank you!

![Screen Shot 2021-12-01 at 15 44 28](https://user-images.githubusercontent.com/11576789/144332394-df301ee1-9eec-4df8-ba2a-3882fad35703.png)

**Comment by Lukas742** [comment]
Hi @rchrdchn 

I'm not part of the UI5 Web Components team, so I can't really answer this question, but since this issue has just been closed and the linked PR has already been merged, I would assume that the fix should be available with the next release. 

@d3xter666 am I correct in my assumption?

**Comment by niyap** [comment]
Hello Colleagues,

The issue is fixed in the master and the change is merged. Also, change for version 0.31 is prepared and is in validation phase. As soon as possible, it will be available in 0.31 as well.

Kind Regards,
Niya

**Comment by rchrdchn** [comment]
Thank you @Lukas742 and @niyap! Our team will made changes accordingly when it's available on `0.31`.

**Comment by niyap** [comment]
Hello @rchrdchn,

The solution is now available in 0.31. Here is a reference to the change: https://github.com/SAP/ui5-webcomponents/pull/4417

Kind Regards,
Niya

**Comment by ilhan007** [comment]
Hello @rchrdchn,

the fix is downported to the 0.31 branch, but not released, next patch will be available next week

**Comment by ilhan007** [comment]
Hello @rchrdchn
the fix released is released - use the 0.31.27 version.
