### ISSUE TITLE
ui5-switch: not able to add aria tags to inner component for screen readers

### ISSUE THREAD

**Issue by lormanlau** [SAP/ui5-webcomponents#4147]
### **Bug Description**
Adding the aria-label, aria-describedby, aria-labelledby to the component will not add the tags to the inner shadow-root component for screen readers.

### **Expected Behavior**
A clear and concise description of what you expect to happen.
switch component when focus should announce with description

### **Steps to Reproduce**
1. Click on or focus on the switch component

### **Isolated Example**
If possible, please provide an isolated example by forking [CodeSandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html).
https://codesandbox.io/s/hungry-sun-s7o0m?file=/src/index.js

### **Context**
- UI5 Web Components version: 1.0.0-rc.15
- OS/Platform: MacOS 11.6 and Windows 10
- Browser: Google Chrome Version 94.0.4606.81 (Official Build) (x86_64)
- Affected component: UI5-Switch

### **Log Output / Stack Trace / Screenshots**
```
N/A
```

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SAP SuccessFactors
- Bussiness impact: Medium

**Comment by ilhan007** [comment]
Hello @lormanlau with this https://github.com/SAP/ui5-webcomponents/pull/4735 the Switch now has "accessibleName" property ("accessibleNameRef" is already available). The property will be released with 1.2.0 by the end of Feb.

**Comment by lormanlau** [comment]
@ilhan007 the issue still exists when using 1.2.1 the switch does not read the accessibleNameRef or accessibleName when using JAWS screen reader https://codesandbox.io/s/infallible-bird-9dvn9i?file=/src/index.js
