### ISSUE TITLE
List: loadMore event is unstable

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents#4185]
### **Bug Description**
One of the List's test started failing, currently skipped with this change https://github.com/SAP/ui5-webcomponents/pull/4184

**Comment by vladitasev** [comment]
This test is already enabled by: https://github.com/SAP/ui5-webcomponents/pull/8576

The list is now in Topic - B and no longer in the framework team. Closing this issue, if the test is unstable often, the responsible team should open a new one.
