### ISSUE TITLE
ui5-card: issues found from mobile exploratory testing iOS

### ISSUE THREAD

**Issue by kskondov** [SAP/ui5-webcomponents#4200]
### **Bug Description**

1)  The card with table sample is cut off on the right 
2) In RTL header and subheader doesn't seem to match the direction and padding is not correct

### **Steps to Reproduce**
1. On iOS device go to https://sap.github.io/ui5-webcomponents/master/playground/components/Card/

### **Context**
- UI5 Web Components version: master

### **Log Output / Stack Trace / Screenshots**
1. 
![image](https://user-images.githubusercontent.com/6640019/139069437-72bf1739-c5e1-4784-9a88-7ad75b7f8559.png)
2.
![image](https://user-images.githubusercontent.com/6640019/139069267-6aee24e7-9cbe-4389-b4ef-746ac52a4cd5.png)

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by LidiyaGeorgieva** [comment]
Regarding the **second** issue:
The "li" element (inside "ui5-li") doesn't receive its dir="rtl" attribute when the sample loads.
When user clicks on the list item the "dir" appears and the styles are correct.

The behaviour is the same for the List sample in RTL: https://sap.github.io/ui5-webcomponents/playground/components/List/?sap-ui-theme=sap_fiori_3&isrtl=true

Possibly related to #3624
