### ISSUE TITLE
ui5-carousel: issue found from mobile exploratory testing iOS

### ISSUE THREAD

**Issue by kskondov** [SAP/ui5-webcomponents#4201]
### **Bug Description**

1)	Carousel with arrow placement and cyclic navigation not fully visible

### **Steps to Reproduce**
1. On iOS device go to https://sap.github.io/ui5-webcomponents/master/playground/components/Carousel/

### **Context**
- UI5 Web Components version: master

### **Log Output / Stack Trace / Screenshots**
![image](https://user-images.githubusercontent.com/6640019/139070476-da13e3be-6f0f-4a7d-9037-1ba3f2148806.png)

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by dimovpetar** [comment]
On Android there is almost the same problem, but the Carousel is above the code snippet:
![image](https://user-images.githubusercontent.com/32839090/140080351-7ba5487c-8496-4893-8073-e0a0730ead34.png)
