### ISSUE TITLE
ui5-popover doesn't close on scroll, when placementType is Right

### ISSUE THREAD

**Issue by dimovpetar** [SAP/ui5-webcomponents#4208]
### **Bug Description**
When the page is scrolled so that the opener of the popover is hidden, the popover is still open.

### **Expected Behavior**
The popover is closed.

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/master/playground/main/pages/Popover/
2. Press on the "Opens modal popover with no block layer!" button
3. The popover should have opened to the right of the button
4. Scroll down the page, so that the button is not visible anymore
5. The popover remains opened

### **Context**
- UI5 Web Components version: master branch
- OS/Platform: Windows
- Browser: Chrome
- Affected component: ui5-popover

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### Additional Information
We should consider whether popover should remain open after scroll in general. In OpenUI5 it closes.

**Comment by TeodorTaushanov** [comment]
This popover is "modal" and the block layer is hidden. That's why it doesn't close automatically.
