### ISSUE TITLE
Request to provide components which can handle ui5 images

### ISSUE THREAD

**Issue by akshaykmr080** [SAP/ui5-webcomponents#422]
Currently i am not able to find any components which can handle images. 
A component which makes an image look like an ui5 image.

A component which implements the styles of .sapMImage css class

**Comment by MapTo0** [comment]
Hey @akshaykmr080,

`.sapMImage` has not really much of styles.
Could you please tell us more about your use case?
I would recommend you to use the normal `<img />` tag for your application.

[Image.less (openui5)](https://github.com/SAP/openui5/blob/master/src/sap.m/src/sap/m/themes/base/Image.less)
[Image.less (fiori_3 - openui5](https://github.com/SAP/openui5/blob/master/src/themelib_sap_fiori_3/src/sap/m/themes/sap_fiori_3/Image.less)

**Comment by MapTo0** [comment]
I am closing the issue as I don't really know what is the expected output of us. Feel free to reopen if you have a specific feature request with a realistic use case.

Regards,
Martin
