### ISSUE TITLE
Width of Input is not going below some fixed size

### ISSUE THREAD

**Issue by Bilal3120** [SAP/ui5-webcomponents#4248]
### **Bug Description**
The width of the Input field is not going below 10rem.

### **Expected Behavior**
The Input should adapt the width set using style property

### **Steps to Reproduce**
1. Import Input from @ui5/webcomponents-react
2. Set width as 5rem
3. The width is not reflected on the UI.

### **Isolated Example**
The issue is reproduced here [CodeSandbox](https://codesandbox.io/s/loving-hertz-drkj6)

### **Context**
- UI5 Web Components version: 1.0.0-rc.15
- OS/Platform: Mac Os Bigsur
- Browser: Microsoft edge

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by LidiyaGeorgieva** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

There is a question regarding the width of the Input.
There is min-width (13.125rem), but I can't see any information in the documentation: https://sap.github.io/ui5-webcomponents/playground/components/Input/

Best Regards,
Lidiya

**Comment by MapTo0** [comment]
Dear @Bilal3120 

You can set the `min-width` of the host element by adding a CSS.
We set default `min-width` but it can be changed from the application by adding a style.

`<Input style={{ minWidth: "5rem" }} />` will do the job.

Regards,
Martin

**Comment by Bilal3120** [comment]
Using minWidth is not setting the width below 13.125rem.
```<Input style={{ minWidth: "5rem" }} />```
Can you please check and update.

**Comment by sherpal** [comment]
@Bilal3120 You have to set *both* `min-width` and `width` style property for this to work. (At least it works with raw webcomponents but I imagine it will also for React based ones.)
The following in the DOM
![Screenshot 2022-05-14 at 08 06 23](https://user-images.githubusercontent.com/25351619/168413136-c62190d2-7a5d-4449-9450-9567279fffd7.png)
produces
![Screenshot 2022-05-14 at 08 06 42](https://user-images.githubusercontent.com/25351619/168413143-57890796-a895-41e7-b33a-381d45a45c01.png)

(The `_input-width=100` is set automatically, I'm guessing by some ui5 internals.)

**Comment by Bilal3120** [comment]
Hi @sherpal Thanks for the solution. It is working as expected now.

Regards,
Bilal Ahmed Pasha

**Comment by wulinjie122** [comment]
Do you know how to set input width to 100% fit table cell width ?
