### ISSUE TITLE
Update `addCustomCSS` so that it uses a shared resource

### ISSUE THREAD

**Issue by codefactor** [SAP/ui5-webcomponents#4270]
### **Feature Request Description**
We would like to be able to use `addCustomCSS` for the purpose of defining override styles or CSS variables for things like emergency fixes. For example, there is a feature in the button that we want to support theming the hover text color, which does not seem possible today, so we can use the addCustomCSS as a quick fix to that issue. Any time we use this, though, it is not going to be consistently working on every manifestation of ui5 webcomponents because the current framework doesn't use `getSharedResource` to use the eventProvider and the storage of the tag/css value for the custom css.

In short, the addCustomCSS should use a shared resource.

### **Proposed Solution**

See:
https://github.com/SAP/ui5-webcomponents/pull/4269

### **Proposed Alternatives**
Don't use addCustomCSS at all and ask UI5 web components team to fix these issues. Or just don't have the functionality that we want. But we like the idea of having "addCustomCSS" as a fallback solution to really customize the web components to our best ability.

### **Additional Context**
ui5-buttons have a CSS variable for the text color, background color, and hover background color. But it does not seem to use a variable for the hover text color. In SuccessFactors customers can theme all 4 of these colors to their heart's content, but because the ui5-button doesn't support us to differentiate the button text color when the button is hovered, it is very possible that the hover text color and hover background color will not be distinguishable (e.g. black on black).

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Bussiness impact: {...}

**Comment by codefactor** [comment]
@LidiyaGeorgieva ,
@vladitasev ,
Can you give us some idea if this can be included in the 1.0.0 release and down-ported to release-0.31?

We would like to make use of this feature that already exists, but due to the minor problem that it does not utilize a shared resource the existing functionality is broken in certain use cases when there are multiple "ui5-webcomponent cores" on the page (I don't know the right terminology).

**Comment by codefactor** [comment]
Also, keep in mind that I've already done the work in the following PR:
https://github.com/SAP/ui5-webcomponents/pull/4269

Please help to get this reviewed/merged - I don't think it will take much effort from the team assuming the feature is generally agreed to.

**Comment by ilhan007** [comment]
I think this is resolved by #4269 right, and it's pending release

**Comment by ilhan007** [comment]
Hello @codefactor The corresponding change has been released with 0.31.23
