### ISSUE TITLE
document available keyboard interactions for each component

### ISSUE THREAD

**Issue by pskelin** [SAP/ui5-webcomponents#428]
**Describe the documentation issue**

- [ ] Documentation is unclear
- [ ] Documentation is incorrect
- [ ] Documentation is missing
- [x] Other

**Description of the issue**
The ui5-datepicker component sample doesn't list the available keyboard interactions, while the ui5-select does:
https://sap.github.io/ui5-webcomponents/playground/components/Select/

Add a keyboard handling section to each component that provides it. Take ui5-select as template.

**Comment by MapTo0** [comment]
This issue is also valid for the ui5-multi-combobox
