### ISSUE TITLE
Segmented-button low performance on rendering in table rows

### ISSUE THREAD

**Issue by JeeOpp** [SAP/ui5-webcomponents#4316]
### **Bug Description**
Segmented-button low performance on  rendering in table rows (10 seconds) for 50 table rows.

### **Expected Behavior**
Segmented-button performance on rendering in table rows increased at least 1-2 second for 50 table rows.

### **Steps to Reproduce and Example**
I am using table and in the same moment inside each row segmented-button exists. 

When count of rows less than 10 everything is fine.
But if count of rows more than 20-30 then rendering performance become decrease.

**FYI**: 50 rows inside table (8 columns) with segmented-button inside each row render 8-10 seconds.
**FYI-2**: If I remove segmented button and left only toggle-button, then performance become perfect. So I can say that issue inside segmented-button (may be it takes a lot of time to link toggle-buttons inside segmented-button).
**FYI-3**: Radio-buttons performance much faster than segmented-button. (But only segmented-button fits my requirements :D ).
**FYI-4**: Even empty segmented-button component with toggle-button without any logic has performance is low.

### **Context**
- UI5 Web Components version: 1.0.0-rc.14
- OS/Platform: SAP CP
- Browser: Google Chrome
- Affected component: segmented-button and toggle-button

### **Log Output / Stack Trace / Screenshots**
UI example:
![image](https://user-images.githubusercontent.com/32600299/141277313-b6f07190-9b18-4d92-8e2e-0903d2a8aa30.png)
HTML example:
![image](https://user-images.githubusercontent.com/32600299/141277324-9bbe2828-c340-496d-8749-37f5d01d268e.png)

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### **Stakeholder Info** (if applicable)

- Organization: SAP

**Comment by unazko** [comment]
Hello @JeeOpp,

With the latest version of UI5 Web Components version the performance is better:
https://codesandbox.io/s/dank-wind-erfhk?file=/index.html
compared to the described slow rendering on rc.14: 
https://codesandbox.io/s/gifted-rain-0gff3?file=/index.html

I would recommend to use the latest version of UI5 Web Components version as transporting fixes to older versions is not part of the regular process.

Best Regards,
Boyan

**Comment by JeeOpp** [comment]
Thank you for your reply, @unazko 

I'll try to update sapUI components version.

Best Regards,
Andrei

**Comment by awolfish** [comment]
There is no any response from the reporter since quite a while.
That's why I am closing it now. If the issue still persists, don't hesitate to reopen it.
