### ISSUE TITLE
inputs: `valueStateMessage` is displayed in `readonly` mode.

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#4317]
### **Bug Description**
When using an input component in `readonly` mode and applying a `valueState` and a `valueStateMessage`, the message is displayed when focusing.

### **Expected Behavior**
The `valueStateMessage` should not be displayed when inputs are set as `readonly`.

### **Steps to Reproduce**
1. Go to [codeSandbox](https://codesandbox.io/s/ui5-webcomponents-forked-q4ero?file=/index.html)
2. Focus one of the input fields.
3. See that the border remains in the same color (expected) but the message is displayed (unexpected).

### **Isolated Example**
https://codesandbox.io/s/ui5-webcomponents-forked-q4ero?file=/index.html

### **Context**
- UI5 Web Components version: 1.0.1

![image](https://user-images.githubusercontent.com/9749730/141277154-c8199e9c-5ec1-4f29-94d3-665096cac49c.png)

**Comment by unazko** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

The issue is reproducible with the steps and snipped provided by @Lukas74.
Could you please take over.

Best Regards,
Boyan
