### ISSUE TITLE
button group

### ISSUE THREAD

**Issue by chenshuichao** [SAP/ui5-webcomponents#4322]
![image](https://user-images.githubusercontent.com/77186544/141396341-ea9cbd65-eea6-4d4c-9f5c-d2a91be7bb3e.png)

https://medium.com/eightshapes-llc/and-you-thought-buttons-were-easy-26eb5b5c1871

**Comment by unazko** [comment]
Hello @chenshuichao,

Could you please explain in more detail, did you find an issue or this is a feature request?

Best Regards,
Boyan

**Comment by chenshuichao** [comment]
This is a feature request.

**Comment by petyabegovska** [comment]
Hello @chenshuichao,

Button with icon and icon only buttons are already available: [https://sap.github.io/ui5-webcomponents/playground/components/Button/](url)

Group button is available as Segmented button: [https://sap.github.io/ui5-webcomponents/playground/components/Button/](url)

For menu button we already have a feature request: [https://github.com/SAP/ui5-webcomponents/issues/1436](url)
The menu button would have a split button mode as well. 

Is this fulfil your requirements?

Best Regards,
Petya

**Comment by DMihaylova** [comment]
Hello @chenshuichao,

As of v.1.1.0 there is also a [Split Button](https://sap.github.io/ui5-webcomponents/nightly/playground/?path=/docs/main-splitbutton--docs ) available.
A decision has been made to not introduce a Menu Button on top of that unless there's a scenario which could not be covered by the Split Button and the [regular button that opens a Menu](https://sap.github.io/ui5-webcomponents/nightly/playground/?path=/docs/main-menu--docs).

Therefore I'm closing the issue.

Thanks & Regards,
Diana
