### ISSUE TITLE
Dev EXP: Improve project starting time

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents#4335]
### **Description**
This is an "epic" issue that aim to improve the development experience by speeding up the project starting time. The `yarn:start` command is slow, it takes too much time and we would like to change that.

### **Objective**
**Investigate the current build process and define points of improvements**

For example:
- Currently we have 3 separate rollup config for base, main and fiori that can be combined to decrease the starting time. 
- Copying files also seems to be among the time consuming operations and is a point to revise. 
- other

**Comment by vladitasev** [comment]
Related to: https://github.com/SAP/ui5-webcomponents/pull/4111

**Comment by ilhan007** [comment]
Related to: https://github.com/SAP/ui5-webcomponents/pull/5380

**Comment by ilhan007** [comment]
Addressed with: https://github.com/SAP/ui5-webcomponents/pull/5152
