### ISSUE TITLE
Playground: rebuild the app to make it more lightweight

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents#4336]
### **Feature Request Description**
We would like to rebuild the playground app, so we can get rid of the ruby and Jekyll dependencies. Currently building the playground is very heavy, and often developers are experiencing various issues to run it locally, especially OS update.

### **Objective**
Investigate lightweight solutions (NodeJS based) to show the UI5 Web Components documentation

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by aurora** [comment]
I don't know, if this was brought up before: 

when you rebuild the playground app, it would be very nice, if you could also improve the examples to show all necessary parts (javascript, tags, etc.) of a specific example. I noticed, that the examples are often incomplete. For example: at the moment i am trying to figure out how the busy-indicator works for the growing table component. It would be helpful, to see where `busyIndicator` is coming from, but there are many more incomplete examples in the playground.

**Comment by ilhan007** [comment]
**Re-implement the Playground and:**
- use the current structure, design and features (settings, search, etc..)
- get rid of the ruby, Jekyll, Sass dependencies -  it should be NodeJS based
- make it easy to run/update locally
- [on 2nd iteration] implement the [Visual Design](https://www.figma.com/file/LEN0RAKmR8eA8WMaNqxe3g/UI5_WebComponents_Redesign?node-id=406%3A9918)

**Tools to research**
- 11ty
- Storybook

**Comment by dobrinyonkov** [comment]
- [ ] Integrate Storybook (add library, serve and build scripts, storybook/builder-vite)
- [ ] Make scripts to generate documentation.mdx files from .md (Getting Started, Theming, Accessibility, Table of contents, etc.)
- [ ] Valid DOM elements inside jsDocs (<br> => </br>, etc.)
- [ ] Make script and extract sample logic from old .sample.html and generate .stories.mdx
- [ ] Add to canvas theme change select, RTL and Compact/Cozy switch
- [ ] Add theming for the whole storybook
- [ ] Check and propose better samples for Pirin components
- [ ] Add to build process and integrate with current landing page

**Comment by ilhan007** [comment]
Hi @dobrinyonkov I think we can close this issue, for now I will move it to 1.13.0 (1.12 has been released) and let you decide.

**Comment by dobrinyonkov** [comment]
Closed with #5831
