### ISSUE TITLE
NumberInput: Deleting Number Via Del => wrong value onChange

### ISSUE THREAD

**Issue by texttechne** [SAP/ui5-webcomponents#4340]
**Describe the bug**
Prerequisites:
* `<input type="Number" value="123" />`

Use Case:
When the whole number is selected & deleted via the "DEL" key, then onChange will report the old value.
Deleting the number via Back Space works as expected: onChange will report an empty string as value.

**Isolated Example**
[Example](https://codesandbox.io/s/optimistic-framework-z55qm?file=/src/App.js)

**To Reproduce**
1. Select the complete number
2. Delete it via "DEL" button on keyboard
3. Leave the field by clicking or pressing on TAB
4. Alert will appear, reporting that the value is the old one, not the empty string

**Expected behavior**
OnChange will have the empty string as value instead of the old value.

**Comment by IlianaB** [comment]
Hello @SAP/ui5-webcomponents-topic-rl  I am forwarding this issue to you, because when selecting and deleting the number via "DEL" key, the onChange event reports the old value, not an empty string, as opposed to deleting with Back Space.

Regards,
Iliana

**Comment by d3xter666** [comment]
Hello,

This issue is related to https://github.com/SAP/ui5-webcomponents/issues/4340
It'd be taken into account and fixed there.

Cheers
