### ISSUE TITLE
Popup adds `ui5-popup-scroll-blocker` which can interrupt the style

### ISSUE THREAD

**Issue by codefactor** [SAP/ui5-webcomponents#4347]
### **Bug Description**
WorkZone is using SuccessFactors widget, which loads UI5 WC Dialog, which then makes the content of the page left aligned losing the "letter box" margin on left/right to center the content.

### **Expected Behavior**
Opening a Dialog should not interrupt the layout of the page.

### **Steps to Reproduce**
1. https://codesandbox.io/s/ui5-webcomponents-forked-ee7g8?file=/index.html
2. press the dialog button
3. see the content moves to the left while the dialog is opened

### **Isolated Example**
[If possible, please provide an isolated example by forking [CodeSandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html).](https://codesandbox.io/s/ui5-webcomponents-forked-ee7g8?file=/index.html)

### **Context**
- UI5 Web Components version: all
- OS/Platform: all
- Browser: all
- Affected component: Popup / Dialog

### **Log Output / Stack Trace / Screenshots**
N/A

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Bussiness impact: {...}

**Comment by codefactor** [comment]
@ilhan007 can you take a look at this? The WorkZone UI is not under SF control. In this case the `width: auto!important` on the body is probably not required but it does not seem normal that adding UI5 WC Dialog would cause such a disruption. I will in parallel ask if this style can be removed because it doesn't seem like it adds anything to the UI; meanwhile, it would be good to investigate this and see if there is a clean solution to this sort of issue.

**Comment by IlianaB** [comment]
Hello @codefactor ,

I think you should better add width: 100% to the body: https://codesandbox.io/s/ui5-webcomponents-forked-t08qx
Anyway, tagging @ilhan007 to advice if a change in the Dialog is needed.

Regards,
Iliana

**Comment by codefactor** [comment]
@IlianaB ,

Yes, that might fix the issue; however, in the real scenario SuccessFactors code is running on a different stack as a "Widget" and therefore we do not control the CSS on the page. We need to ask the owner to make that change and it's not clear why they have set width to auto on the body.

The premise of having a Dialog web component is that it should be able to run on any page with any CSS applied and work without interrupting the page styles. So that is why I have opened this defect in the hopes that there is a cleaner solution for the Dialog that would work even if the page has width auto applied to the body.

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-rd  can you take a look of this issue.
