### ISSUE TITLE
[SF] List - allow user to confirm before changing selected item

### ISSUE THREAD

**Issue by 2bno1** [SAP/ui5-webcomponents#4348]
### **Feature Request Description**
We have a requirement that after user clicks a different item in the list, before actually selecting the new item, user has a chance to confirm or cancel this action. For example, a confirm dialog pops up to ask user whether he want to change the selected item. If he clicks 'OK', then it changes the selected item. Otherwise, it still keep the previous item.

### **Proposed Solution**
Give a chance in `item-click` event handler to preventing changing the selected item.

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

- Organization: SuccessFactors

**Comment by nnaydenow** [comment]
Internal reference: BGSOFUIPIRIN-5518
