### ISSUE TITLE
Cоmponents of Topic P: Fast navigation using F6 for UI5 WC library

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents#4350]
### **Feature Request Description**
Fast navigation using F6 for UI5 WC library
 
Issue origin: https://github.com/SAP/ui5-webcomponents/issues/4013

Fast navigation via F6 is supported by SAPUI5 controls and it is not there for the web components. Can we have this feature for content block switching via F6 or any alternative for fast navigation techniques for web components control, so for the users, it's easy to navigate also avoid a11y errors. 

### **Proposed Solution**
Block switching for SAPUI5 controls
https://openui5.hana.ondemand.com/topic/d23e2cf618a44382a203691e8a0baef4

### **Additional Context**

For course home, while A11y testing we got this ticket WEF-13301 where we got an issue reported by experts that for the page block switching is missing via F6.

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

### **Stakeholder Info** (if applicable)

Organization: SuccessFactors

**Comment by dobrinyonkov** [comment]
Pressing F6 should move the focus through the following elements: 

`FlexibleColumnLayout`
- element in first column
- arrow btn start
- element in middle column
- arrow btn end
- element in end column

(from spec)
- `[F6]` Forward navigation:
Move focus to next group element. The layout toggle button is part of the grouping, so it is embedded into group navigation.
- `[SHIFT]+[F6]` Backward navigation:
Move focus to previous group element. The layout toggle button is part of the grouping, so it is embedded into group navigation.

---

`ShellBar` 
- No matter, where the focus resides within the Shell, move it to the first element in the tab chain of the next/previous F6- group
- When entering the Shell Bar again, restore previous focus position.

--- 
`List` 
- If leaving the List, no matter, where the focus resides within the List, move it to the first element in the tab chain of the next/prev F6-group.
- If the List gets the focus via F6, move the focus to the item or interactive element which had the focus before. Initial focus: First visible item. Should be changeable by app.


If needed, we can further discuss these during implementation.

**Comment by fifoosid** [comment]
Thanks for the information. The F6 Navigation for those controls will be implemented with #4490
