### ISSUE TITLE
Cоmponents of Topic RD: Fast navigation using F6 for UI5 WC library

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents#4351]
### **Feature Request Description**
Fast navigation using F6 for UI5 WC library
 
Issue origin: https://github.com/SAP/ui5-webcomponents/issues/4013

Fast navigation via F6 is supported by SAPUI5 controls and it is not there for the web components. Can we have this feature for content block switching via F6 or any alternative for fast navigation techniques for web components control, so for the users, it's easy to navigate also avoid a11y errors. 

### **Proposed Solution**
Block switching for SAPUI5 controls
https://openui5.hana.ondemand.com/topic/d23e2cf618a44382a203691e8a0baef4

### **Additional Context**

For course home, while A11y testing we got this ticket WEF-13301 where we got an issue reported by experts that for the page block switching is missing via F6.

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

### **Stakeholder Info** (if applicable)

Organization: SuccessFactors

**Comment by olannyv** [comment]
For Rodopi Team places where F6 is defined (in the ACC [KBD spec|https://wiki.wdf.sap.corp/wiki/display/Acc/Fiori+Keyboard+Interaction]) : 
* Carousel 
* Side Navigation (according to the KBD spec - should be supported, but it is not currently implemented)

**Comment by fifoosid** [comment]
Thanks for the information. The F6 Navigation for those controls will be implemented with #4490
