### ISSUE TITLE
Badge: text is not vertically aligned

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents#4358]
### **Bug Description**
The text of the Badge is shifted upwards from the vertical center - see the screenshot. The finding is true for all the themes.

### **Expected Behavior**
By design the text should be vertically centered within the container.

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/master/playground/components/Badge/
2. Observe the text vertical position
3. ...

### **Isolated Example**
[If possible, please provide an isolated example by forking [CodeSandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html).](https://sap.github.io/ui5-webcomponents/master/playground/components/Badge/)

### **Context**
- UI5 Web Components version: master
- OS/Platform: {...} MacOS
- Browser: {...} Chrome
- Affected component: {...} ui5-badge

### **Log Output / Stack Trace / Screenshots**

<img width="107" alt="Screenshot 2021-11-18 at 07 14 10" src="https://user-images.githubusercontent.com/15702139/142356211-8755a418-4de6-4512-a71b-70a4895786d0.png">

<img width="107" alt="Screenshot 2021-11-18 at 07 14 24" src="https://user-images.githubusercontent.com/15702139/142356215-a7e05b7b-6db2-4ae9-b98b-ae5adcc24af7.png">

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by ilhan007** [comment]
FYI @SAP/ui5-webcomponents-topic-rd

**Comment by LidiyaGeorgieva** [comment]
Hello @ilhan007 , 

Could you please check if you have zoom different than 100% set for your OS?
This could cause similar issue (at least for Windows).
I couldn't reproduce the issue on Windows or Mac.

Best Regards,
Lidiya

**Comment by ilhan007** [comment]
Hello Lidiya, It seems it depends on some settings indeed, I could fine a zoom set, but I checked with my teammate Filip and it looks better on his side, and as you can't reproduce it - I will close it.
