### ISSUE TITLE
MultiComboBox: DOM nodes leak

### ISSUE THREAD

**Issue by AndrianStoikov** [SAP/ui5-webcomponents#4364]
**Describe the bug**
When the MultiComboBox is mounted and unmounted there are unmounted nodes left in the memory which leads to memory leaks

**Isolated Example**
[codesandbox](https://codesandbox.io/s/xenodochial-swanson-emoiu?file=/src/App.js).

**To Reproduce**
1. Open the codesandbox in a new window
2. Open the Chrome DevTools and observe the Performance Monitor and the DOM nodes
2. Click on the "Toggle" button multiple times
3. Garbage collect the memory
4. See the number of nodes

**Expected behavior**
Mounting and unmounting elements should not cause memory leaks

**Screenshots**
Initial number of nodes
![image](https://user-images.githubusercontent.com/21200806/142583958-e881b779-3dc9-4cd5-b195-aae33f8cb05a.png)

After multiple clicks and garbage collection
![image](https://user-images.githubusercontent.com/21200806/142584161-6daa5e55-151f-4439-951f-3253325870da.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 0.20.0
`@ui5/webcomponents-react` version: 1.0.1
Operating System: Windows 10
Browser: Microsoft Edge, Version 95.0.1020.53 (Official build) (64-bit)

**Additional context**
Make sure that you have disabled react devtools because they might interfere with the garbage collection

**Comment by IlianaB** [comment]
Hello @AndrianStoikov ,

We have performed several performance testings, but no DOM nodes leakage was detected. We can see the very same Nodes count at the start and end points of the measurement:
![startPoint](https://user-images.githubusercontent.com/10456158/142633969-3cfd8bec-cf1e-4f92-a968-509231d1bfbb.jpg)
![endPoint](https://user-images.githubusercontent.com/10456158/142633991-adc4ecff-16fe-4962-b802-d0cefbb947b9.jpg)

Regards,
Iliana

**Comment by AndrianStoikov** [comment]
Hi Iliana,

Indeed after checking with the Performance capture the nodes seem correct. Looks like the Performance Monitor shows some weird results. Thanks for checking that.

Best regards,
Andy
