### ISSUE TITLE
[SF] ViewSettingsDialog - Display of header options (Sort and Filter)

### ISSUE THREAD

**Issue by Vir-Mittal** [SAP/ui5-webcomponents#4371]
### **Feature Request Description**
In the ViewSettingsDialog component, the header always contains two buttons to switch between sorting and filtering, even if the content for one of those options is left empty.

<img width="365" alt="Screen Shot 2021-11-21 at 11 08 27 PM" src="https://user-images.githubusercontent.com/36656306/142799938-7d1d03f6-c4f4-4eba-8e84-6dff915288eb.png">

### **Proposed Solution**
In the header, do not show the filter button if the content has been left empty.
Example - 

![image](https://user-images.githubusercontent.com/36656306/142800297-7354f9e7-e847-499e-a57a-9e820bdc838c.png)

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

- Organization: SuccessFactors

**Comment by niyap** [comment]
Hello Colleagues,

Could you please check the description of the issue and analyse whether the requirement is a valid proposal for an enhancement of ui5-view-settings-dialog component?

Kind Regards,
Niya

**Comment by ilhan007** [comment]
Hello @Vir-Mittal the issue is resolved in the master and will be available on 21 Jan 2022 with 1.1.0
