### ISSUE TITLE
do we provide more layout options for developer?

### ISSUE THREAD

**Issue by superwangnan** [SAP/ui5-webcomponents#4374]
Hi team,
As we release 1.0 version, I found there is only master detail layout component in our library. In ui5, we have some flexbox, grid layout component. Do we have any plan to provide more layout options for developer?

Thanks ~

**Comment by niyap** [comment]
Hello @superwangnan,

If you have a specific enhancement in mind, please provide more information about what exactly do you need.
In case of general questions, you can use OpenUI5's slack #webcomponents.

Kind Regards,
Niya
