### ISSUE TITLE
Question: Draft Mode and Web Components

### ISSUE THREAD

**Issue by tamiarah** [SAP/ui5-webcomponents#4383]
Hi colleagues,
 
For evaluation purposes we want to rebuild an existing Fiori Elements application into an Angular app using the UI5 Web Components with a CAP backend.
We would like to understand if there are any specific functionalities, which are not particularly available, e.g.
- Draft handling
- Multiuser support (lock mechanism if another user is working on a business entity)
 
We were wondering, if the Web Components are assisting such functionalities or if we will have to develop such features completely on our own as the available documentation is not hinting it.

Thank you in advance!

Best regards,
Christina

**Comment by niyap** [comment]
Hello @SAP/ui5-webcomponents-team,

Could you please check the question?

Thank you in advance!

Kind Regards,
Niya

**Comment by fifoosid** [comment]
Hello @tamiarah 

UI5 Web Components is a library of UI components which you can use to build your UI. 

Both functionalities that are described are part of the business logic of the application and how it should behave in different user scenarios. This means that both of these functionalities should be implemented by the application developers.

Best regards,
Filip
