### ISSUE TITLE
Checkbox: Inconsistent Cursor Style

### ISSUE THREAD

**Issue by texttechne** [SAP/ui5-webcomponents#4386]
### **Bug Description**
Cursor style within the checkbox  is set / overwritten to "default", while label and wrapper around the input are set to cursor style "pointer". Additionally, for disabled checkboxes  the cursor style is still set to "pointer".

### **Expected Behavior**
Disabled state: checkbox  including their label, wrapper and what have you are all set to cursor style "default" to indicate, that there is nothing to do for the user.

Any other state: checkbox  including their label & wrapper are all set to cursor style "pointer".

### **Isolated Example**
[Playground Example: Checkbox](https://sap.github.io/ui5-webcomponents/playground/components/CheckBox/)

### **Priority**
- [x] Low
- [ ] Medium
- [ ] High
- [ ] Very High

**Comment by niyap** [comment]
Hello @texttechne,

As I can see, the issue is not reproducible for the ui5-radio-button component. Here, you can check: https://sap.github.io/ui5-webcomponents/master/playground/components/RadioButton/
We will proceed with the issue in ui5-checkbox component.

Kind Regards,
Niya

**Comment by niyap** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

There is an issue with ui5-checkbox component. When the mouse cursor is over the checkbox, it is the default one and when over the label, it is pointer.
In openUI5 the cursor is always pointer.
Could you please check?

Thank you in advance!

Kind Regards,
Niya

**Comment by texttechne** [comment]
Hi @niyap,

let's meet half way ;-) 
* for non-disabled radio buttons the cursor style is consistent
* BUT for disabled radio buttons the cursor style is set to pointer, while it should be default

**Comment by niyap** [comment]
Hello @texttechne,

May I ask you to create a separate issue for that, because we could not handle them both here, as the affected components are different.

Thank you in advance!

Kind Regards,
Niya

**Comment by niyap** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

Please check the cursor used when the ui5-checkbox is disabled as well. If necessary, please clarify with the responsible visual designers, whether we should use the default cursor or not.
As a reference, in OpenUI5 the default cursor is used, when the control is disabled.

Kind Regards,
Niya

**Comment by texttechne** [comment]
Hey @niyap,

since you didn't communicate the issue with the disabled style to the topic-p guys: Do you accept that, when the checkbox is disabled, that the cursor style should be set to "default" instead of "pointer"?

Here's the UI5 example for the checkbox, which behaves like I've expected this:
https://ui5.sap.com/#/entity/sap.m.CheckBox/sample/sap.m.sample.CheckBox

**Comment by niyap** [comment]
Hello @texttechne, 

I added a comment for that as well :)

Kind Regards,
Niya

**Comment by texttechne** [comment]
Hey @niyap,

ahh, you were 1 minute faster regarding the comment :-)

And here is the other ticket for the radio button: #4387
Interestingly this bug is also present in OpenUI5, so radio button and checkbox behave differently regarding disabled state there.
