### ISSUE TITLE
Radio Button: wrong cursor style for disabled state

### ISSUE THREAD

**Issue by texttechne** [SAP/ui5-webcomponents#4387]
### **Bug Description**
When a radio buttton is disabled, the cursor style is still set to "pointer" indicating that the user can perform an action here, while in fact she can't. It should be set to "default".

In UI5 the radio button behaves the same way - so also using the pointer style -  [as can be seen in this example](https://ui5.sap.com/#/entity/sap.m.RadioButtonGroup/sample/sap.m.sample.RadioButtonGroup)
However, the checkbox behaves as I would expect it, [as can be seen here](https://ui5.sap.com/#/entity/sap.m.CheckBox/sample/sap.m.sample.CheckBox)

### **Expected Behavior**
Cursor style is set to "default", when the radio button is disabled.

Radio Button & Checkbox behave the same way regarding disabled style.

### **Isolated Example**
Playground example of radio button shows the issue.

### **Priority**
- [x] Low
- [ ] Medium
- [ ] High
- [ ] Very High

**Comment by niyap** [comment]
Hello @SAP/ui5-webcomponents-topic-rd,

Please check the cursor used when the ui5-radio-button component is disabled. Currently, we use "pointer" when the component is disabled.
 If necessary, please clarify with the responsible visual designers, whether we should change it to the default cursor.
As a reference, you can check the sap.m.Checkbox control in OpenUI5 when disabled.

Kind Regards,
Niya

**Comment by gmkv** [comment]
Hi @texttechne 
The linked PR solves the issue in ui5-webcomponents. I've also made a similar change in the OpenUI5 repo as well: https://github.com/SAP/openui5/commit/9194f87aebc3fad19469c116d01db79f476af0f2
Thanks for reporting this.
