### ISSUE TITLE
Broken links in Web Components theming docu

### ISSUE THREAD

**Issue by akudev** [SAP/ui5-webcomponents#4389]
### **Issue Description**

Hi,
https://sap.github.io/ui5-webcomponents/playground/customizing/theme/

has the following link:
"For more on configuring themes, see [Configuration](https://sap.github.io/ui5-webcomponents/playground/customizing/theme/Configuration.md)"

which leads to:
https://sap.github.io/ui5-webcomponents/playground/customizing/theme/Configuration.md

which doesn’t exist:
"Page not found"

Further up, the same page has the link
[Demo Theme Designer](https://themedesigner-themedesignerdemo.dispatcher.eu2.hana.ondemand.com/index.html)

which leads to
https://themedesigner-themedesignerdemo.dispatcher.eu2.hana.ondemand.com/index.html

which at least for me results in:
HTTP Status 403 - Forbidden

### **Issue Type**

- [ ] Documentation is unclear
- [ ] Documentation is incorrect
- [ ] Documentation is missing
- [x] Other

**Comment by niyap** [comment]
Hello @SAP/ui5-webcomponents-team,

Could you please check Andreas's findings?
Thank you in advance!

Kind Regards,
Niya
