### ISSUE TITLE
[ui5-input] "X" button enhancement

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents#4395]
### **Feature Request Description**

hi, according to Fiori 3 Specification https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2060056990 
There is a component SearchField 

![image](https://user-images.githubusercontent.com/78520316/143685792-7fe5cc4a-cd8b-4219-920c-3c61ee582a7d.png)

which has a clear button at the end of input.

For now, we can use the ui5-input with the icon slot  to add this icon. but I think maybe there is a11y issue for it, because these icons can not be focused and clickable.

In our UX design for b2205 there is a requirement that needs the clear button feature in ui5-input component. 

### **Proposed Solution**

Can we do some enhancement for the ui5-input component which allow button or icon with slot name "icon" for it?

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

**Comment by nikolay-kolarov** [comment]
Hi,

Thanks for raising this request.
To be concrete, you want it only for the ui5-input at the moment, right?
Also, what are the expected timelines, where you would expect to receive this feature?

Thanks,
Nikolay

**Comment by mastanshaikk** [comment]
@nikolay-kolarov In general SF has a commitment for A11y related tickets to resolved by Jan 2021, It would be great if this can be addressed by then. Thanks!

**Comment by sfsf-xweb-sh** [comment]
hi, @nikolay-kolarov 

Thanks for reply.

I think it's a very common features, yes, I mark it as hight priority.   
For now We need to find the A11y issue as soon as possible. So,  please help to support it as soon as possible. and thanks for it.

**Comment by nikolay-kolarov** [comment]
Hi,

Thanks for the input. I will prioritize it accordingly.

Best Regards,
Nikolay

**Comment by nikolay-kolarov** [comment]
Hi @sfsf-xweb-sh,
Hi @mastanshaikk,

Could you please provide information what is the accessibility issue for which you are talking about?

Thanks,
Nikolay
