### ISSUE TITLE
[ui5-table] header height of 48px is hardcoded

### ISSUE THREAD

**Issue by rathlukas** [SAP/ui5-webcomponents#4398]
### **Feature Request Description**
Hi, I'm currently searching for a way to resize the .ui5-table-header-row element as it seems a bit huge with the compact density enabled, but there is a hardcoded 48px style inside Table.js (it styles the thead > tr element).

### **Proposed Solution**
Make the Header Height configurable via properties or adapt to the compact density.

### **Priority**
- [x] Low
- [ ] Medium
- [ ] High
- [ ] Very High

**Comment by gmkv** [comment]
Hi @SAP/ui5-webcomponents-topic-rl 
This is a request to be able to customise the height for cozy/compact.
There's also a bug: The table's header is too tall - it's 48px in height, while it is specified to be 44px in both display densities.

Would you have a look?
Regards,
Georgi
