### ISSUE TITLE
RadioButton & Checkbox: discrepancies of cursor styles for disabled/read-only mode

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#4404]
### **Bug Description**
When hovering over the text of a `CheckBox` which is in disabled/read-only mode the `pointer` cursor is displayed.

When hovering over a `RadioButton` which is in disabled/read-only mode the `pointer` cursor is displayed.

### **Expected Behavior**
I'm not 100% sure what the expected behavior is, but from this [documentation](https://experience.sap.com/fiori-design-web/ui-element-states/) I would guess that a `pointer` should be displayed when in `read-only` mode and the default cursor when in `disabled` mode.  Other than that, the cursor for the checkbox and associated text should be consistent.

### **Steps to Reproduce**
1. Go to [codeSandbox](https://codesandbox.io/s/ui5-webcomponents-forked-spls9?file=/index.html)
2. See that the checkboxes have the default cursor, but the text has the `pointer` cursor.
3. See that radio-buttons have the `pointer` cursor.

### **Isolated Example**
https://codesandbox.io/s/ui5-webcomponents-forked-spls9?file=/index.html

### **Context**
- UI5 Web Components version: 1.0.2

### **Priority**
- [x] Low
- [ ] Medium
- [ ] High
- [ ] Very High

**Comment by gmkv** [comment]
Hi @Lukas742 
This was fixed a few days ago with #4393. The Radio Button had the inconsistent cursor styles.
Regards,
Georgi

**Comment by gmkv** [comment]
Actually the Checkbox' square is also inconsistent here.

**Comment by gmkv** [comment]
The issue with Checkbox is already solved in #4386. You can see for yourself in the [playground, on the main branch](https://sap.github.io/ui5-webcomponents/master/playground/components/CheckBox/).
