### ISSUE TITLE
MessageStrip: Screen reader for Message Strip close button announces twice

### ISSUE THREAD

**Issue by bonniegso** [SAP/ui5-webcomponents#4406]
**Describe the bug**
When the close button on the Message Strip is focused, the text "message strip close" is announced twice. This issue is observed when using the MessageStrip component from ui5-webcomponents-react. The message isn't read twice if using ui5-webcomponents message strip directly.

**Isolated Example**
Code Sandbox Example: https://8ngbr.csb.app/

**To Reproduce**
1. Go to 'https://8ngbr.csb.app/'
2. Turn on your screen reader (JAWS or VoiceOver)
3. Using your keyboard tab to the close button on the message strip
4. Observe that "message strip close" is announced twice

**Expected behavior**
"Message strip close" should only be announced once.

**Screenshots**
![message strip close repetitive announcement](https://user-images.githubusercontent.com/68353216/144097084-30023622-da7f-438a-9672-728a3765081f.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 0.31.15
`@ui5/webcomponents-react` version: 0.131.15
Operating System: MacOS/Windows 10
Browser: VoiceOver/JAWS 2020

**Comment by gmkv** [comment]
Hi @SAP/ui5-webcomponents-topic-rl 
The MessageStrip close button gets announced twice.
Issue can be reproduced with JAWS or VoiceOver here: https://codesandbox.io/s/ui5-webcomponents-forked-eh034?file=/index.html 

Would you have a look?
Regards,
Georgi
