### ISSUE TITLE
ui5-shellbar customize logo title

### ISSUE THREAD

**Issue by JarrettChan** [SAP/ui5-webcomponents#4426]
### **Feature Request Description**
Similar to https://github.com/SAP/ui5-webcomponents/pull/4377, please provide an override for _logoText
https://github.com/SAP/ui5-webcomponents/blob/master/packages/fiori/src/ShellBar.js#L1123
And downport to 0.31

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### **Stakeholder Info** (if applicable)

- Organization: SuccessFactors
- Business impact: Logo title is something we customize, needed for when we re-enable the Shellbar for customers in a few weeks at the earliest (but probably longer).

**Comment by terezamch** [comment]
Hello colleagues,

Could you please handle this feature request?

Best regards,
Tereza
