### ISSUE TITLE
UI5 Web Components Enablement in OpenUI5: ensure `Busy Indication` works for UI5 Control wrappers

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents#4434]
**Background**
As part of the Retrofit topic, we aim to reuse the UI5 Web Components as UI5 Controls.
In order to do this, we need to ensure that all UI5 concepts that apply to UI5 Controls will also work for the UI5 Controls that wrap UI5 Web Components.

**UI5 Concept - `Busy Indication`**
One of the major concepts is the `Busy Indication`.

**Task**
- Check if setting busy to UI5 Control wrappers works the same way as UI5 Controls, f.e.  for the Button, List, Table the loading indicator shows correctly, but for the Avatar, RatingIndicator- it is not visible at all. 
- Setup more complex scenario, parent-child controls (using the sap.m or sap.ui.webc.main as containers and sap.ui.webc.main for child controls) and set "busy" to all levels to ensure the busy indicators shows only once at the top.

Part of: https://github.com/SAP/ui5-webcomponents/issues/2925

**Comment by nnaydenow** [comment]
Internal reference: BGSOFUIPIRIN-5542
