### ISSUE TITLE
UI5 Web Components Enablement in OpenUI5: Demo Kit Samples and Test Pages

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents#4437]
**Background**
As part of the Retrofit topic we aim to reuse the UI5 Web Components as UI5 Controls,
we need to create proper test pages and Demo Kit samples

**Tasks**
- create test pages similar to OpenUI5 counterparts
- createDemo Kit samples similar to OpenUI5 counterparts

**Comment by petyabegovska** [comment]
Hi, **Topic B** samples are added.

Best regards,
Petya

**Comment by ilhan007** [comment]
Demo kit samples won't be needed for the moment as the approach for using that UI5 Web Components inside SAPUI5 has changed. Instead of having control wrappers as SAPUI5 libraries, the SAPUI5 framework will be enhanced so that UI5 Web Components can be used inside SAPUI5 Views seemingly without such wrappers.
