### ISSUE TITLE
MultiComboBox selection of item is inconsistent.

### ISSUE THREAD

**Issue by Arora05** [SAP/ui5-webcomponents#4441]
### MultiComboBox item's inconsistent selection behaviour 
This bug is related to the selection of MultiComboBoxItem selection in the MultiComboBox component.
If we click on the check box provided the dropdown option does not close but if we select an item by clicking on the text the dropdown will close automatically.

### **The behaviour expected should be like the dropdown window should not close even on clicking of text.**
There should not be any inconsistency in the selection of the MultiComboBox dropdown and it should work as expected.

### **Steps to Reproduce**
1. Go  to [codeSandbox](https://codesandbox.io/s/ecstatic-rain-8feuc?file=/src/App.js)
2. Click on the drop-down
3. select the checkbox of the item the dropdown will persist.
4. Now click on the text "Item 1".
5. The dropdown will close automatically

### **Priority**
- Low

**Comment by ndeshev** [comment]
Hello @Arora05,

The described interaction behaves as expected and it is aligned with the official Fiori user experience specifications. 

The user should be able to do both - chose one single item by clicking on it which will finish the interaction by closing the picker, or select multiple items before closing by clicking on the their checkboxes.

Kind regards
Nikolay
