### ISSUE TITLE
ui5-card: card with list issue

### ISSUE THREAD

**Issue by LidiyaGeorgieva** [SAP/ui5-webcomponents#4450]
### **Bug Description**
Rows are not positioned correctly (vertically)
![image](https://user-images.githubusercontent.com/7242508/145187452-a956ef5f-e928-47b1-a639-0b24419bbf8b.png)

### **Steps to Reproduce**
1. Go to ['playground'](https://sap.github.io/ui5-webcomponents/playground/components/Card/)
Reproducible for Desktop & Phone, in LTR

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by LidiyaGeorgieva** [comment]
Hello,

There is an issue with the custom list item.
It has height set, which causes issues when there is content on two or three rows inside.
It gets worse when there is Compact content density.
Example: https://jsbin.com/qemejimuqo/edit?html,output

Best Regards,
Lidiya

**Comment by gmkv** [comment]
FYI @SAP/ui5-webcomponents-topic-p
