### ISSUE TITLE
ui5-card: card header issue in RTL

### ISSUE THREAD

**Issue by LidiyaGeorgieva** [SAP/ui5-webcomponents#4451]
### **Bug Description**
Header elements are not correctly positioned inside the header.
![image](https://user-images.githubusercontent.com/7242508/145188388-6334518b-d107-430d-b50b-c3533305adbf.png)

![image](https://user-images.githubusercontent.com/7242508/145188401-54363671-7e26-49c0-9985-a52233010caf.png)

### **Steps to Reproduce**
1. Go to ['Playground'](https://sap.github.io/ui5-webcomponents/playground/components/Card/)
2. switch to **phone**
3. switch to **RTL**

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by LidiyaGeorgieva** [comment]
The "div" element with class "ui5-card-header" in the Playground doesn't receive dir="rtl". 
In the separate test samples this is not reproducible. 
If the "dir" is in place there is no issue:
![image](https://user-images.githubusercontent.com/7242508/145212190-34c00334-6c7e-4daa-b357-993a97396ddc.png)

Issue is possibly related to #3624

**Comment by gmkv** [comment]
Hi @SAP/ui5-webcomponents-topic-core 
This issue looks similar to #3624.
The Playground app has some odd behaviour when switching to RTL mode.

Regards,
Georgi
