### ISSUE TITLE
[SF][ActionSheet] "preventFocusRestore" property is supposed to be bound to each action button

### ISSUE THREAD

**Issue by i323808** [SAP/ui5-webcomponents#4453]
**Is your feature request related to a problem? Please describe.**
The "preventFocusRestore" property is supposed to be bound to each action button of ActionSheet. Because click events of each Button are different. Some need refocus the previously focused element, e.g. Bookmark action. Some need focus other elements, e.g. Apply action which will open a dialog. Currently, the "preventFocusRestore" property effects all buttons in ActionSheet.

**Describe the solution you'd like**
Each action button is supposed to have a "preventFocusRestore" property.

**Comment by terezamch** [comment]
Hello @Lukas742 ,

If I understand you correctly, from your point of view the focus cannot be changed in a callback just before closing the popover. Is that correct?

I have made a [jsbin sample](https://jsbin.com/yiyukisabu/1/edit?html,js,output) achieving just that. Could you please check it out and correct me if my understanding of the issue is wrong.

Thanks,
Tereza

**Comment by i323808** [comment]
Hi @Lukas742,

Thanks for your suggestion and it's a good workaround.

Thanks,
Jane

**Comment by i323808** [comment]
Hi @Lukas742 ,

Sorry to reopen this issue. After testing, we find the focus restore is also lost when press Esc key after setting "preventFocusRestore" true.   So we still need bind the "preventFocusRestore" prop to each button in ActionSheet instead of the whole ActionSheet. Is it possible to provide access to the close method of ResposivePopover which is on https://github.com/SAP/ui5-webcomponents-react/blob/main/packages/main/src/components/ActionSheet/index.tsx#L133?

Thanks,
Jane

**Comment by Lukas742** [comment]
Hi @i323808 

you can call the `close` method on the instance of the `ActionSheet`. ([Docs](https://sap.github.io/ui5-webcomponents-react/?path=/docs/modals-popovers-actionsheet--default-story#methods))

Could you elaborate what you mean with "the focus restore is lost" and maybe add an example preferably with codesandbox.

**Comment by i323808** [comment]
Hi @Lukas742 ,

Please go to https://sap.github.io/ui5-webcomponents-react/?path=/docs/modals-popovers-actionsheet--default-story and set "preventFocusRestore" true. Then the focus cannot return to "Open ActionSheet" button when press Esc key. The requirement is the focus return to "Open ActionSheet" when press Esc key or click some buttons in the popover(e.g. Accept button), and prevent the focus from returning to "Open ActionSheet" when click other buttons(e.g. Reject button).

BR,
Jane

**Comment by Lukas742** [comment]
In this case you will have to focus the element yourself. 

See [codeSandbox](https://codesandbox.io/s/jovial-bogdan-54cp8?file=/src/App.js)

**Comment by i323808** [comment]
Hi @Lukas742 ,

Thanks for your suggestion.

Many Thanks,
Jane
