### ISSUE TITLE
[Feature request] Table: horizontal scroll and sticky columns

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents#4461]
### **Feature Request Description**
There is a requirement by one of our stakeholders (MDK) regarding the Table Component to provide several additional features. MDK wants to display large set of data in many columns - the Table should be able to display multiple columns.
The real case scenario would be up to 20 columns. When the horizontal space is not enough, the table should show a horizontal scroll. Also, another important feature for MDK is the possibility to display some columns as sticky.
MDK plan to such scrollable Data Table for all 3 platforms i.e. iOS, Android(already done) and Web.For web, it's done via the UI5 Web Components.

Summary of the required features:
- [x] Allow horizontal scroll
- [x] Support Sticky column
- [x] Single/Multiple select (if we assume that we will inherit this from the ui5-table)
- [x] Row click/press (if we assume that we will inherit this from the ui5-table)

### BLI Origin
https://sapjira.wdf.sap.corp/browse/MDK-12883

### **UX Reference**
- https://sapui5untested.int.sap.eu2.hana.ondemand.com/#/entity/sap.ui.table.Table/sample/sap.ui.table.sample.TableFreeze
- https://experience.sap.com/fiori-design-android/data-table/
- https://experience.sap.com/fiori-design-ios/article/data-table/

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### **Stakeholder Info** (if applicable)

- Organization: SAP Mobile Development Kit (MDK)

**Comment by fifoosid** [comment]
All features are implemented .
