### ISSUE TITLE
[SF] [MultiComboBox] Customized value state message. 

### ISSUE THREAD

**Issue by ChristyFei** [SAP/ui5-webcomponents#4481]
### **Bug Description**
According to requirement, if there is no selected item in MultiComboBox, its status should be an error and display a customized message. If there is no filter result by keystroke, the default message - Invalid Entry is also required.

Sample code: https://codesandbox.io/s/multicomboboxs-value-state-iqdrf?file=/src/App.js   
 
If valueState and valueStateMessage are set by the selected length, one scenario that is no selected item and no filter is broken. While inputting the wrong keyboard, only "No item is selected." will be shown. Expected Behavior is that 'Invalid Entry' should be shown. 

So I add an onInput listener to change valueStateMessage according to the current value. One scenario is broken. 
Reproduce Steps: 
1. Focus MultiComboBox, "No item is selected." is shown.
2. Type 'q' which is no filter result, "Invalid entry" is shown. 
3. Type 'e' which is contained, 'Invalid entry' is still shown. 

### **Expected Behavior**
'Invalid entry' should not be shown. 
I'm not sure that I use MultiComboBox in the correct way. How customized messages can work with the default message properly?

### **Context**
@ui5/webcomponents version: 0.31.15
@ui5/webcomponents-react version: 0.131.16
Operating System:
Browser: Chrome

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

**Comment by PetyaMarkovaBogdanova** [comment]
Hi colleagues from @SAP/ui5-webcomponents-topic-rl,
can you, please, advice if this is the expected behaviour of ui5-multi-combobox in the situation described above?

Kind regards,
Petya Markova.
(Ui5 web components dispatcher)

**Comment by MapTo0** [comment]
The issues looks fixed in `v1.0.2` could you please confirm?

**Comment by ChristyFei** [comment]
> The issues looks fixed in `v1.0.2` could you please confirm?

Thanks a lot. It works fine. But here is a minor issue. 
Reproduced Step:
1. Goto https://codesandbox.io/s/multicomboboxs-value-state-iqdrf?file=/src/App.js 
2. Select one item
4. Type 'q', 'Invalid entry' will be shown. 
5. Type 'dw', 'No item is selected' will be shown. 
'Invaid entry' is expected. 

Would you please help check it? 

Thank you.
Christy
