### ISSUE TITLE
Rich Text Editor can not display base64 image

### ISSUE THREAD

**Issue by AisonBird** [SAP/ui5-webcomponents#449]
while create an image with base64 src, and give it to Rich Text Editor. There was nothing ...
how to show the image in Rich text editor?
check my following code

// controller
var template = {};
var image ="<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAA...">";
template.body = image;
var oViewModel = new JSONModel(template);
this.getView().setModel(oViewModel, "template");
//view
<rte:RichTextEditor id="rte" value="{template>/body}" editorType="TinyMCE4" customToolbar="true" showGroupFont="true" showGroupInsert="true"
showGroupLink="true" height="360px"/>

//inspector
an empty img element.
![image](https://user-images.githubusercontent.com/12046098/58448493-bf5adc80-813a-11e9-9bc7-670c462795e2.png)

//version
1.52.20

**Comment by ilhan007** [comment]
Hello @AisonBird 

we are responsible for the ui5 webcomponents.

You can create issue in
https://github.com/SAP/openui5

and the colleagues will take over.

Best,
ilhan
