### ISSUE TITLE
accessble-name-ref support for form elements Button, Switch in version of 1.0.1 web component

### ISSUE THREAD

**Issue by hkshetry** [SAP/ui5-webcomponents#4497]
### **Bug Description**
Currently, Button and  Switch in version of 1.0.1 web component does not have `accessble-name-ref `

### **Expected Behavior**
All form elements should have `accessble-name-ref` support ( formally `aria-labelledby`)

### **Context**
- UI5 Web Components version: 1.0.1
- OS/Platform: NA
- Browser:  NA
- Affected component:  Button, Switch

### **Log Output / Stack Trace / Screenshots**
```
{...}
```
### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SuccessFactor
- Bussiness impact:  apps are not accessible

**Comment by ilhan007** [comment]
Hello @hkshetry  thanks for reporting,

not sure if you know, but the components have different ownership.
Now, the issue dispatcher don't now to which team to assign the issue, as 3 diffrent teams are responsible
- Switch,  Button - topic B
- Checkbox - topic P 
- RadioButton - topic rd

You can see the ownership here:
https://wiki.wdf.sap.corp/wiki/display/UI/WebComponents+ownership+info

Please, file 3 issues (2 more) and you can copy paste the content
- one for - Switch,  Button -
- one for Checkbox
- one for RadioButton

In future keep in mind the ownership, to split the issues accordingly.

BR,
ilhan

**Comment by ilhan007** [comment]
Hello @hkshetry,

 I will keep the Button and Switch requests in this issue to forward the issue to one of the teams already.

**Comment by ilhan007** [comment]
Closed with https://github.com/SAP/ui5-webcomponents/pull/4472 and https://github.com/SAP/ui5-webcomponents/pull/4474, will be available with 1.1.0 by 21 Jan
