### ISSUE TITLE
ui5-link does not have accessible-name support

### ISSUE THREAD

**Issue by hkshetry** [SAP/ui5-webcomponents#4498]
### **Bug Description**
ui5-link does not have accessible-name support

### **Expected Behavior**
ui5-link need to support  `accessible-name`

The visible link text simply says “View details” which is not descriptive enough as to “what” details a screen reader can view when clicking on this link. Hence additional context is needed. “opens in a new tab or window” is added in addition to satisfy this criteria - https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/G201. Presenting this via a “title” attribute is not getting picked up by all screen readers and hence the need to include this in the aria label.

### **Context**
- UI5 Web Components version:  1.0.1
- OS/Platform: NA
- Browser: NA
- Affected component: `Link`

### **Log Output / Stack Trace / Screenshots**
```
{...}
```
### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

### **Stakeholder Info** (if applicable)

- Organization: SuccessFactor
- Bussiness impact: Link is not accessible

**Comment by hkshetry** [comment]
do we have any update for this ?

**Comment by hkshetry** [comment]
@ilhan007  when will be this fix available?

**Comment by ilhan007** [comment]
Before the end of Feb with 1.2.0
