### ISSUE TITLE
[ui5-tree/ui5-tree-item] - Add a SelectionMode attribute : just on checkbox or the entire item

### ISSUE THREAD

**Issue by lucianiz** [SAP/ui5-webcomponents#4502]
### **Feature Request Description**

We have a use case where we need to display hierarchically structured data with the option to select (MultiSelect) but the selection of an item and clicking on an item need to be disconnected. Clicking on the item displays additional information about the item and the selection is used to mark multiple items for various actions.

The depth can be more than 3 levels deep but the standard data entry usually has 3.

In summary what we need is that when a user clicks on the element but not on the checkbox, the checkbox should not be selected, 
![image](https://user-images.githubusercontent.com/42092424/146523963-94dc32d9-c341-4c2f-a6fc-6e4573bcce87.png)

When clicking on the checkbox directly, the checkbox should be marked:
![image](https://user-images.githubusercontent.com/42092424/146524568-c3a3e8f4-aa10-4d17-9bc1-931dcc965c2d.png)

I've noticed that currently the cursor changes when hovering over the checkbox as opposed to the rest of the tree-item.

### **Proposed Solution**

Have an additional attribute called SelectionMode with values "Item"(default) or "Checkbox".

There should also be another event added to distinguish between clicking on the Item or clicking on the Checkbox.

### **Proposed Alternatives**

Another option would be to add another value to the Mode attribute, called  "MultiSelectCheckbox" (or something like that)

I think the first option might be better since it could also be applied for the SingleSelect mode.

### **Additional Context**
Add other context or screenshots related to the feature request here.

### **Priority**
- [ ] Low
- [x] Medium
- [x ] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: rit-edv consulting
- Bussiness impact: This is currently blocking for us, we can try to make a workaround using ui5-list but it's a bit redundant since we need to display hierarchical data we need to convert the ui5-list into a tree so that would be basically almost re-implementation of the current ui5-tree .

**Comment by PetyaMarkovaBogdanova** [comment]
Hi team,
can you, please, consider if the described desired functionality is applicable for ui5-tree-item?

Kind regards,
Petya Markova.
(UI5 Web Components Dispatcher)

**Comment by nnaydenow** [comment]
Hi @lucianiz,

With #4708 we extended item-click event and now it can be prevented to execute default behavior (selection). If you have SingleSelect / MultiSelect mode it better to listen for selection-change event if you want to observe change in selected list items.

You can check this snippix to see how it works now:
https://codesandbox.io/s/ui5-webcomponents-forked-6i2n0k?file=/index.html

Regards,
Nayden
