### ISSUE TITLE
[SF] [MultiComboBox] Customized value state message issue - phase 2. 

### ISSUE THREAD

**Issue by ChristyFei** [SAP/ui5-webcomponents#4508]
Reproduced Step:
1. Goto https://codesandbox.io/s/multicomboboxs-value-state-iqdrf?file=/src/App.js 
2. Select one item
4. Type 'q', 'Invalid entry' will be shown. 
5. Type 'dw', 'No item is selected' will be shown. 
'Invaid entry' is expected. 

Would you please help check it? 

Thank you.
Christy

_Originally posted by @ChristyFei in https://github.com/SAP/ui5-webcomponents/issues/4481#issuecomment-997746280_

**Comment by MapTo0** [comment]
Hello,

First of all, I can't type `q` as there is not item starting with `q`.
But I guess you are pointing to the case where we:
- Select an item
- type e.g. `s` and the again `s`

This happens due to wrong application logic.

```
 onInput={(event) => {
  const value = event.target._state.value;
  console.log(value);

  if (value === "") {
    setStateMessage(null);
  } else {

    /* ---------- this hits as the value is not empty, it is "s" ------ */
    setStateMessage(<span>No item is selected.</span>);
  }
}}
```

Regards,
Martin
