### ISSUE TITLE
ui5-textarea: DOM structure refactoring

### ISSUE THREAD

**Issue by niyap** [SAP/ui5-webcomponents#4512]
Currently, the ui5-textarea component is hard to be stylish, because the component's structure is strange. The root element consist of the native textarea html element and the span representing the showExceededText when used.
In that way, it is hard to apply styles that should cover the whole textarea including the scrollbar, because styling the root element, the styles will cover the exceeding text as well, which is not expected. On the other hand, styling the native textarea, the styles does not cover the scrollbar.
For example, we can look in the SAP Horizon theme implementation, where not all from the target design is covered because of that limitations.
In UI5 for example, there is a wrapper element, over the textarea html element, which does not contain the exceeding text element. We could analyze where similar solution could be introduced in ui5-textarea Web Component as well.

Kind Regards,
Niya

**Comment by ivoplashkov** [comment]
Hello,

Issues these issues should be fixed as part of this refactoring: #4909, [#3843](https://github.com/SAP/ui5-webcomponents/issues/3843), [#4986](https://github.com/SAP/ui5-webcomponents/issues/4986)

Regards,
Ivaylo
