### ISSUE TITLE
MultiComboBox Item disable functionality not available

### ISSUE THREAD

**Issue by I516406** [SAP/ui5-webcomponents#4513]
### **Feature Request Description**

In MultiComboBox component, we don't have an option to disable some items in the list of items. 

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

I am attaching a code sandbox for the same - [CodeSandbox](https://codesandbox.io/s/nifty-estrela-rle9o?file=/src/App.js)

**Comment by MapTo0** [comment]
Hello @I516406 

Based on the Fiori Guidelines we should not disabled items in the ComboBoxes.
https://experience.sap.com/fiori-design-web/multi-combobox/#option-list1

Regards,
Martin
