### ISSUE TITLE
[SideNavigation, SideNavigationItem, SideNavigationSubItem]: extra block appear above SideNavigation with collapsed state set to true, when click on one of SideNavigationItem 

### ISSUE THREAD

**Issue by apryviazentsau** [SAP/ui5-webcomponents#4515]
**Describe the bug**
Extra block appear above SideNavigation component with ```collapsed``` set to ```true```, when you click on one of SideNavigationItem.

**Isolated Example**
[codesandbox](https://codesandbox.io/s/kind-nash-p3t9p?file=/src/App.js)

**Expected behavior**
There is no any extra block should appear above SideNavigation component

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.0.2
`@ui5/webcomponents-react` version: 0.20.4

**Comment by MapTo0** [comment]
Dear colleagues,

Static styles applied to the `static-area-item` break the layouting.
I tracked to this commit - https://github.com/SAP/ui5-webcomponents/pull/4240

Regards,
Martin

**Comment by dimovpetar** [comment]
Hello @apryviazentsau,

This issue is fixed with #4526.

Best regards,
Petar
