### ISSUE TITLE
ui5-date-picker: Delayed updated value property at onchange

### ISSUE THREAD

**Issue by hans-helmut** [SAP/ui5-webcomponents#4518]
### **Bug Description**
Getting the .value-property after an onchange event gives unexpected results 

### **Expected Behavior**
onchange and value should work like on the input-element. 

### **Steps to Reproduce**
1. Open the sandbox-example
2. Open the console
3. select a first date with the ui5-date-input
4. console shows *no date*
5. select a second date
6. console show the *first date*

### **Isolated Example**
If possible, please provide an isolated example by forking [CodeSandbox](https://codesandbox.io/s/ehx1g?fontsize=14&module=%2Findex.html).

### **Context**
- UI5 Web Components version: 1.0.2
- OS/Platform: Linux/Debian
- Browser: Firefox
- Affected component: ui5-date-picker

### **Log Output / Stack Trace / Screenshots**
```
ui5-date-picker:  
ui5-date-picker: Dec 22, 2021 
input (date): 2021-12-22 
```
### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by MapTo0** [comment]
Hey @hans-helmut 

Change event is native events for all input. In order to cover more functionality we prevent the native change and reimplement it. In order to to get the value of the DatePicker you should use the detatil property of the event's callback parameter

```
document.getElementById("myDatepicker1").addEventListener("change", event => console.log(event.detail.value))
```

Regards,
Martin

**Comment by hans-helmut** [comment]
I understand your reasons. Unfortunately I am working with ELM, so JavaScript can not applied easily.
