### ISSUE TITLE
BusyIndicator component is causing a fatal error in Jest tests

### ISSUE THREAD

**Issue by bonniegso** [SAP/ui5-webcomponents#4519]
### **Bug Description**
The following error occurs when the <BusyIndicator> component is used and Jest tests are ran.

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x100d78bad node::Abort() (.cold.1) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
 2: 0x10003ae85 node_module_register [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
 3: 0x10003b046 node::FatalTryCatch::~FatalTryCatch() [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
 4: 0x1001aa297 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
 5: 0x1001aa231 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
 6: 0x100599642 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
 7: 0x10059bd73 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
 8: 0x100597cee v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
 9: 0x100595b6d v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
10: 0x1005a2d95 v8::internal::Heap::AllocateRawWithLigthRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
11: 0x1005a2dff v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
12: 0x100571fe3 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
13: 0x100805efc v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
14: 0x230ca015bf3d 
15: 0x230ca015d2b0 

<--- Last few GCs --->

[80938:0x110008000]    18240 ms: Mark-sweep 1396.0 (1424.9) -> 1395.7 (1424.9) MB, 679.1 / 0.0 ms  (average mu = 0.091, current mu = 0.003) allocation failure scavenge might not succeed
[80938:0x110008000]    18919 ms: Mark-sweep 1396.4 (1424.9) -> 1396.1 (1425.4) MB, 676.4 / 0.0 ms  (average mu = 0.049, current mu = 0.004) allocation failure scavenge might not succeed

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x230ca015bf3d]
    1: StubFrame [pc: 0x230ca015d2b0]
Security context: 0x2a0a9e49e6c1 <JSObject>
    2: printComplexValue(aka printComplexValue) [0x2a0a0c3cab49] [/Users/i529647/SAPDevelop/xweb/youcalc-card-content/node_modules/@testing-library/dom/node_modules/pretty-format/build/index.js:~196] [pc=0x230ca03d3712](this=0x2a0ac48026f1 <undefined>,val=0x2a0a6da44fd1 <Subscription map = 0x2a0afaad73f1>,config=0x2a0aad...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x100d78bad node::Abort() (.cold.1) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
 2: 0x10003ae85 node_module_register [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
 3: 0x10003b046 node::FatalTryCatch::~FatalTryCatch() [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
 4: 0x1001aa297 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
 5: 0x1001aa231 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
 6: 0x100599642 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
 7: 0x10059bd73 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
 8: 0x100597cee v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
 9: 0x100595b6d v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
10: 0x1005a2d95 v8::internal::Heap::AllocateRawWithLigthRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
11: 0x1005a2dff v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
12: 0x100571fe3 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
13: 0x100805efc v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
14: 0x28865c5bf3d 

<--- Last few GCs --->

[80969:0x110008000]    18701 ms: Mark-sweep 1395.3 (1424.9) -> 1395.0 (1424.9) MB, 754.5 / 0.0 ms  (average mu = 0.092, current mu = 0.012) allocation failure scavenge might not succeed
[80969:0x110008000]    19419 ms: Mark-sweep 1395.7 (1424.9) -> 1395.4 (1425.4) MB, 714.0 / 0.0 ms  (average mu = 0.051, current mu = 0.005) allocation failure scavenge might not succeed

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x28865c5bf3d]
Security context: 0x3a036971e6c1 <JSObject>
    1: printComplexValue(aka printComplexValue) [0x3a03a20acc81] [/Users/i529647/SAPDevelop/xweb/youcalc-card-content/node_modules/@testing-library/dom/node_modules/pretty-format/build/index.js:~196] [pc=0x28865ed09cb](this=0x3a03553026f1 <undefined>,val=0x3a03621e0271 <Object map = 0x3a03c4b5f8a1>,config=0x3a03ec182251 <Object map = 0x3a03e710d259>,indentati...

### **Expected Behavior**
We expect the tests to pass without this error.

### **Steps to Reproduce**
1. Clone the project youcalc-card-content repo [link in slack channel]
2. Check out the branch feature/busyindicator
3. Run "npm run test"
4. Observe error in terminal.

### **Isolated Example**
PR #9 in youcalc-card-content repo [link in slack channel]

### **Context**
- UI5 Web Components version: Occurs in versions 0.31.7, 0.31.27, 1.0.1, 1.0.2
- OS/Platform: MacOS
- Browser: N/A
- Affected component: <BusyIndicator>

### **Log Output / Stack Trace / Screenshots**
```
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x100d78bad node::Abort() (.cold.1) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
 2: 0x10003ae85 node_module_register [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
 3: 0x10003b046 node::FatalTryCatch::~FatalTryCatch() [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
 4: 0x1001aa297 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
 5: 0x1001aa231 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
 6: 0x100599642 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
 7: 0x10059bd73 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
 8: 0x100597cee v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
 9: 0x100595b6d v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
10: 0x1005a2d95 v8::internal::Heap::AllocateRawWithLigthRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
11: 0x1005a2dff v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
12: 0x100571fe3 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
13: 0x100805efc v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
14: 0x230ca015bf3d 
15: 0x230ca015d2b0 

<--- Last few GCs --->

[80938:0x110008000]    18240 ms: Mark-sweep 1396.0 (1424.9) -> 1395.7 (1424.9) MB, 679.1 / 0.0 ms  (average mu = 0.091, current mu = 0.003) allocation failure scavenge might not succeed
[80938:0x110008000]    18919 ms: Mark-sweep 1396.4 (1424.9) -> 1396.1 (1425.4) MB, 676.4 / 0.0 ms  (average mu = 0.049, current mu = 0.004) allocation failure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x230ca015bf3d]
    1: StubFrame [pc: 0x230ca015d2b0]
Security context: 0x2a0a9e49e6c1 <JSObject>
    2: printComplexValue(aka printComplexValue) [0x2a0a0c3cab49] [/Users/i529647/SAPDevelop/xweb/youcalc-card-content/node_modules/@testing-library/dom/node_modules/pretty-format/build/index.js:~196] [pc=0x230ca03d3712](this=0x2a0ac48026f1 <undefined>,val=0x2a0a6da44fd1 <Subscription map = 0x2a0afaad73f1>,config=0x2a0aad...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x100d78bad node::Abort() (.cold.1) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
 2: 0x10003ae85 node_module_register [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
 3: 0x10003b046 node::FatalTryCatch::~FatalTryCatch() [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
 4: 0x1001aa297 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
 5: 0x1001aa231 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
 6: 0x100599642 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
 7: 0x10059bd73 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
 8: 0x100597cee v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
 9: 0x100595b6d v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
10: 0x1005a2d95 v8::internal::Heap::AllocateRawWithLigthRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
11: 0x1005a2dff v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
12: 0x100571fe3 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
13: 0x100805efc v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
14: 0x28865c5bf3d 

<--- Last few GCs --->

[80969:0x110008000]    18701 ms: Mark-sweep 1395.3 (1424.9) -> 1395.0 (1424.9) MB, 754.5 / 0.0 ms  (average mu = 0.092, current mu = 0.012) allocation failure scavenge might not succeed
[80969:0x110008000]    19419 ms: Mark-sweep 1395.7 (1424.9) -> 1395.4 (1425.4) MB, 714.0 / 0.0 ms  (average mu = 0.051, current mu = 0.005) allocation failure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x28865c5bf3d]
Security context: 0x3a036971e6c1 <JSObject>
    1: printComplexValue(aka printComplexValue) [0x3a03a20acc81] [/Users/i529647/SAPDevelop/xweb/youcalc-card-content/node_modules/@testing-library/dom/node_modules/pretty-format/build/index.js:~196] [pc=0x28865ed09cb](this=0x3a03553026f1 <undefined>,val=0x3a03621e0271 <Object map = 0x3a03c4b5f8a1>,config=0x3a03ec182251 <Object map = 0x3a03e710d259>,indentati...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x100d78bad node::Abort() (.cold.1) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
 2: 0x10003ae85 node_module_register [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
 3: 0x10003b046 node::FatalTryCatch::~FatalTryCatch() [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
 4: 0x1001aa297 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
 5: 0x1001aa231 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
 6: 0x100599642 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
 7: 0x10059bd73 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
 8: 0x100597cee v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
 9: 0x100595b6d v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
10: 0x1005a2d95 v8::internal::Heap::AllocateRawWithLigthRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
11: 0x1005a2dff v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
12: 0x100571fe3 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
13: 0x100805efc v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
14: 0x1ce9835bf3d 

<--- Last few GCs --->

[80978:0x110008000]    18202 ms: Mark-sweep 1395.9 (1425.4) -> 1395.4 (1425.9) MB, 736.4 / 0.0 ms  (average mu = 0.088, current mu = 0.007) allocation failure scavenge might not succeed
[80978:0x110008000]    18923 ms: Mark-sweep 1396.4 (1425.9) -> 1395.9 (1426.4) MB, 716.4 / 0.0 ms  (average mu = 0.049, current mu = 0.007) allocation failure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x1ce9835bf3d]
    1: StubFrame [pc: 0x1ce9835d2b0]
Security context: 0x0783f2c1e6c1 <JSObject>
    2: printComplexValue(aka printComplexValue) [0x7834e128e69] [/Users/i529647/SAPDevelop/xweb/youcalc-card-content/node_modules/@testing-library/dom/node_modules/pretty-format/build/index.js:~196] [pc=0x1ce985d64f2](this=0x07835a0026f1 <undefined>,val=0x07836be842f9 <Object map = 0x783c6402e09>,config=0x078328882251 <Obj...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x100d78bad node::Abort() (.cold.1) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
 2: 0x10003ae85 node_module_register [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
 3: 0x10003b046 node::FatalTryCatch::~FatalTryCatch() [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
 4: 0x1001aa297 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
 5: 0x1001aa231 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
 6: 0x100599642 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
 7: 0x10059bd73 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
 8: 0x100597cee v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
 9: 0x100595b6d v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
10: 0x1005a2d95 v8::internal::Heap::AllocateRawWithLigthRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
11: 0x1005a2dff v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
12: 0x100571fe3 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
13: 0x100805efc v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [/Users/i529647/.nvm/versions/node/v10.24.1/bin/node]
14: 0x2bea1dadbf3d 
15: 0x2bea1daa1e54 
16: 0x2bea1db21a74 
17: 0x2bea1dd3b64a 
18: 0x2bea1dd3cbed 
19: 0x2bea1dd3cbed 
20: 0x2bea1dd3cbed 
21: 0x2bea1dd3cbed 
22: 0x2bea1dd3cbed 
23: 0x2bea1dd3cbed 
24: 0x2bea1dd3cbed 
25: 0x2bea1dd3cbed 
26: 0x2bea1dd3cbed 
27: 0x2bea1dd3cbed 
28: 0x2bea1dd3cbed 
29: 0x2bea1dd3cbed 
30: 0x2bea1dd3cbed 
31: 0x2bea1dd3cbed 
32: 0x2bea1dd3cbed 
33: 0x2bea1dd3cbed 
34: 0x2bea1dd3cbed 
35: 0x2bea1dd3cbed 
36: 0x2bea1dd3cbed 
37: 0x2bea1dd3cbed 
38: 0x2bea1dd3cbed 
39: 0x2bea1dd3cbed 
40: 0x2bea1dd3cbed 
41: 0x2bea1dd3cbed 
42: 0x2bea1dd3cbed 
43: 0x2bea1dd3cbed 
44: 0x2bea1dd3cbed 
45: 0x2bea1dd3cbed 
46: 0x2bea1dd3cbed 
47: 0x2bea1dd3cbed 
48: 0x2bea1dd3cbed 
49: 0x2bea1dd49e95 
50: 0x2bea1da918d5 

<--- Last few GCs --->

[80987:0x108008000]    17278 ms: Mark-sweep 1395.6 (1424.9) -> 1395.3 (1424.9) MB, 681.6 / 0.0 ms  (average mu = 0.095, current mu = 0.013) allocation failure scavenge might not succeed
[80987:0x108008000]    18318 ms: Mark-sweep 1396.0 (1424.9) -> 1395.7 (1425.4) MB, 1036.4 / 0.0 ms  (average mu = 0.041, current mu = 0.003) allocation failure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x2bea1dadbf3d]
    1: StubFrame [pc: 0x2bea1daa1e54]
Security context: 0x33c477c1e6c1 <JSObject>
    2: slice [0x33c431285151](this=0x33c495f5a779 <JSArray[34]>)
    3: printComplexValue(aka printComplexValue) [0x33c42b176019] [/Users/i529647/SAPDevelop/xweb/youcalc-card-content/node_modules/@testing-library/dom/node_modules/pretty-format/build/index.js:~196] [pc=0x2bea1dd3b64a](this=0x33c4157826f1 <undefined>,val=0...

FAIL src/features/MiniApp/__test__/MiniApp.test.tsx
  ● Test suite failed to run

    Call retries were exceeded

      at ChildProcessWorker.initialize (node_modules/jest-worker/build/workers/ChildProcessWorker.js:193:21)
```
### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SAP Successfactors
- Bussiness impact: youcalc widget cannot use busy indicator

**Comment by MapTo0** [comment]
Hey @bonniegso 

I am not really sure what is reported here.
Is this a question how to setup a testing infrastructure or a bug in the component?

Regards,
Martin

**Comment by bonniegso** [comment]
Hi @MapTo0 ,
We believe that there is a bug in the component that is causing our unit tests to error out when the component is added to the page. For privacy reasons, I started this Slack thread https://sap-successfactors.slack.com/archives/CTHEMAZ8C/p1640206055276100 which includes a little more detail.

**Comment by vladitasev** [comment]
Hello colleagues,

I'll close this ticket, but please let me know if there is still an issue with the latest version of the packages, and if so, I'll reopen and investigate.

Regards,
Vladi
