### ISSUE TITLE
Inputs: Value state header in dialog

### ISSUE THREAD

**Issue by niyap** [SAP/ui5-webcomponents#4525]
### **Bug Description**
The value state header in dialog is not consistent and correctly visualised  among all input components.
**ui5-input:** The value state text is left aligned but bigger then expected as well as not horizontally centered.
**ui5-multi-combobox:** Overall looks good, but we could check the specification and the current implementation in order to ensure that it is correct.
**ui5-combobox** The value state message is center aligned because the styles valid for the ui5-dialog header are applied for each "row" (.ui5-responsive-popover-header .row) which is not correct. As well as the text is bigger than expected.

After the enhancement of the input components value state header, we should add the value state icon for SAP Horizon theme. For reference, you can check the ui5-multi-combobox, where it is already added.

### **Expected Behavior**
Enhance the value state header visualisation according to the specification.

Kind Regards,
Niya

**Comment by hristop** [comment]
Internal BLI was created: FIORITECHP1-28785

**Comment by nikoletavnv** [comment]
Visual appearance of value state header message for mobile devices has been aligned between the mentioned components.
