### ISSUE TITLE
Tree: selectedItems from selection-change event doesn't include collapsed items

### ISSUE THREAD

**Issue by eswortmaler** [SAP/ui5-webcomponents#4534]
### **Bug Description**
When `ui5-tree` in mode `MultiSelect` has selected items in collapsed parts of the tree, they don't  appear in `selectedItems` or `previouslySelectedItems` of the `selection-change` event.

### **Expected Behavior**
I would expect the `selectedItems` and `previouslySelectedItems` to include all selected and previously selected items even if they are in collapsed parts of the tree

### **Steps to Reproduce**
1. Create a `ui5-tree` in mode `MultiSelect` with one `ui5-tree-item` and another `ui5-tree-item` inside that one
```html
<ui5-tree id="tree" mode="MultiSelect">
   <ui5-tree-item text="root">
      <ui5-tree-item text="nested"></ui5-tree-item>
   </ui5-tree-item>
</ui5-tree>
```

2. Add an event-listener for the `selection-change` event on the tree to print out the `selectedItems`
```javascript
const tree = document.querySelector('#tree');
tree.addEventListener('selection-change', (event) => {
   console.log(event.detail.selectedItems);
});
```

3. Expand the tree and select the nested item
![grafik](https://user-images.githubusercontent.com/23629712/147672871-c29ce46c-5984-481b-bbfb-54a4c473b7a8.png)
The event-listener correctly logs the selection
![grafik](https://user-images.githubusercontent.com/23629712/147673015-4684a3e1-6d03-408b-8f55-01579c5fd392.png)

4. Collapse the tree again and select the root item
![grafik](https://user-images.githubusercontent.com/23629712/147673118-24bc9592-8701-40d2-8943-eb1b7cf25bfa.png)
The event-listener logs the array, but it only contains one item, even though two are selected
![grafik](https://user-images.githubusercontent.com/23629712/147673234-004b03f0-f17a-4870-807d-23375491f0c0.png)

5. Expand the tree again and toggle any item off and on again
![grafik](https://user-images.githubusercontent.com/23629712/147673382-47302095-24ea-4441-97a7-1f01cb3f8b24.png)
This time the event-listener logs both items
![grafik](https://user-images.githubusercontent.com/23629712/147673444-b050b826-de3d-4ca1-8dc7-7ee51a7bd0df.png)

### **Isolated Example**
https://codesandbox.io/s/ui5-webcomponents-forked-rjx7m?file=/index.html

### **Context**
- UI5 Web Components version: 1.0.2
- OS/Platform: Windows 10
- Browser: Firefox, Chrome, Edge
- Affected component: `ui5-tree`

### **Log Output / Stack Trace / Screenshots**
as described in the reproduction steps

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by TeodorTaushanov** [comment]
@SAP/ui5-webcomponents-topic-p, can you check this issue?

**Comment by nnaydenow** [comment]
Hi @eswortmaler,

We left this behaviour to application developers because there are so many cases about the selection of current selected child and its children. You can travers all children with event.detail.selectedItem[index].children and to do this selection by your side.

Regards,
Nayden
