### ISSUE TITLE
[SF] [ViewSettingsDialog] ViewSettingsDialog isn't internationalizable 

### ISSUE THREAD

**Issue by Neeeko** [SAP/ui5-webcomponents#4539]
### **Bug Description**
The current implementation of the [ViewSettingsDialog](https://sap.github.io/ui5-webcomponents/playground/components/ViewSettingsDialog/) won't work in internationalized applications as the only thing the `confirm` event returns is the **text attribute** related to the selected `ui5-sort-item` or `ui5-filter-item-option`.

For example, if I want to filter by "Name" in "Descending" order in English, the confirm event will return
```
{
    sortOrder: "Descending",
    sortBy: "Name"
}
```

while if the application is translated in French, it will return
```
{
    sortOrder: "Décroissant",
    sortBy: "Nom"
}
```

Thus, preventing us to make an API call with these criteria as the code isn't supposed to know that "Décroissant" means "Descending" and that the field we want to apply these filters to is "name" instead of "Nom".

### **Expected Behavior**
There are a few possible solutions:

1. As for SAPUI5 [ViewSettingsItem](https://sapui5.hana.ondemand.com/sdk/#/api/sap.m.ViewSettingsItem%23overview), you could add the ability to provide a `key` that will be returned alongside the item text attribute when firing the `confirm` event.
2. In the `confirm` event, instead of only returning the text attribute, you could also return the whole `HTMLElement` that has been selected (similar to the [List](https://sap.github.io/ui5-webcomponents/playground/components/List/)). This would allow developers to add whatever they want to the element `dataset`.

### **Context**
- UI5 Web Components version: 1.0.1
- Affected component: ViewDetailsDialog

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### **Stakeholder Info** (if applicable)

- Organization: SuccessFactors

**Comment by TeodorTaushanov** [comment]
@SAP/ui5-webcomponents-topic-b, can you check this one?
