### ISSUE TITLE
Error in UI5Metadata when inheriting a web component

### ISSUE THREAD

**Issue by Psidium** [SAP/ui5-webcomponents#454]
**Describe the bug**

When inheriting a UI5 Web Component, the `metadata` gets wrongly merged into the resulting component. The top-most prototype in the hierarchy will override any shared key of `properties`, `slots` and `events`.

**To reproduce**

Having this file inheriting the TableRow:

```js
import TableRow from "@ui5/webcomponents/dist/TableRow";

class SingleTableRow extends TableRow {
    static get metadata() {
        return {
            ...TableRow.metadata,
            tag: 'ui5-table-single-row',
            slots: {
                cells: {
                    type: Object,
                    multiple: true,
                    individualSlots: true,
                }
            }
        };
    }
}
SingleRow.define();
```

This class only redeclares the `metadata` to allow any div into a table, not just `ui5-table-cell`. 

When trying to add a div in this new object, there is an error, this error is thrown because of the `getMetadata()` method returns the content of the `TableRow`'s metadata instead of this class',

**Expected behavior**

The object extending the Component can override any property of the metadata property.

**Context**
- UI5 Web Components version: 0.11
- OS/Platform: Mac

**Affected components**

All

**Comment by MapTo0** [comment]
Unfortunately, our base project is not yet ready for public consumption and will evolve and change a lot in the future. We might somehow hack this but I would not recommend it. I hope that if we can achieve the referenced feature (https://github.com/SAP/ui5-webcomponents/issues/455) this can be skipped for now.
