### ISSUE TITLE
ColorPicker: color selection behaves weird

### ISSUE THREAD

**Issue by petermuessig** [SAP/ui5-webcomponents#4540]
### **Bug Description**
When entering the color `#0a6ed1` as hex value of the `ColorPicker` and then clicking on the color selection the picked result is a complete different color.

### **Expected Behavior**
Picker color should be a similar color

### **Steps to Reproduce**
1. Go to [Color Picker in playground](https://sap.github.io/ui5-webcomponents/playground/components/ColorPicker/)
2. Enter the color `0a6ed1` as hex value and press enter
3. Now click a bit to the left bottom and the color changes

### **Recording**

https://user-images.githubusercontent.com/1589419/147871126-d18d4223-ff0f-4c62-8d59-7c7533cd9096.mp4

### **Context**
- UI5 Web Components version: 1.0.1 
- OS/Platform: MacOS
- Browser: Chrome
- Affected component: ColorPicker

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by terezamch** [comment]
Hello @SAP/ui5-webcomponents-topic-b,

There is an issue in the ColorPicker, please refer to the reporters description.

Best regards,
Tereza
