### ISSUE TITLE
ColorPicker: color property not applied once the color slider was used

### ISSUE THREAD

**Issue by petermuessig** [SAP/ui5-webcomponents#4541]
### **Bug Description**
Open the ColorPicker example in the playground and enter the color `0854a0`. If you use the top color slider and shift the color e.g. to green and afterwards apply the color `0854a0` again, the color in the selection pane (picker area) stays green but the color shown below displays the expected `0854a0`.

### **Expected Behavior**
In any case, when user is changing the color of the color picker, all UI elements should be adopted: either via hex color input, alpha value input or the sliders or the picker. All should be synchronized.

### **Steps to Reproduce**
1. Go to [Color Picker in playground](https://sap.github.io/ui5-webcomponents/playground/components/ColorPicker/)
2. Enter the color `0854a0` as hex value and press enter
3. Now select a color in the color slider and re-enter the color `0854a0`
4. The color picker section and the color slider doesn't change anymore

### **Context**
- UI5 Web Components version: 1.0.1
- OS/Platform: MacOS
- Browser: Chrome
- Affected component: ColorPicker

### **Screenshots**
![image](https://user-images.githubusercontent.com/1589419/147871352-a3e77b95-c685-4bbc-9e49-2e5e32f62457.png)

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by terezamch** [comment]
Hello @SAP/ui5-webcomponents-topic-b,

There is an issue with the color picker, please refer to the reporters description.

Best regards,
Tereza
