### ISSUE TITLE
Option: element does not accept `title` attribute

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#4542]
### **Bug Description**
The `Option` component does not accept the `title` HTML attribute.

### **Expected Behavior**
`Option` should display a tooltip when `title` is set.

### **Steps to Reproduce**
1. Go to [codeSandbox](https://codesandbox.io/s/ui5-webcomponents-forked-ocxcr?file=/index.html)
2. Display the options inside the select component.
3. Hover over one of the `Option`s and see that the tooltip is never displayed, even though `title` is set.

### **Isolated Example**
https://codesandbox.io/s/ui5-webcomponents-forked-ocxcr?file=/index.html

### Additional Information

This issue was originally raised in [Slack](https://sap-ea.slack.com/archives/CAJJ53N00/p1640689289030600) (internal link)

**Comment by terezamch** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

When there is a title set to the ui5-option, it does not show on hover. It looks like the reason is that it is not passed to the inner ui5-li component. Steps for reproduction could be seen above.

Could you please have a look?

Best regards,
Tereza
