### ISSUE TITLE
MultiInput: Readonly Token shows the delete button on viewing all tokens in the drop down

### ISSUE THREAD

**Issue by mihirahlawat** [SAP/ui5-webcomponents#4543]
### **Bug Description**
On making a Token as "readonly" the 'x' to delete the token is removed but it still shows on the drop down of the view all tokens.

### **Expected Behavior**
There should not be any delete option for readonly tokens.

### **Isolated Example**
Please use the following link to reproduce the issue. https://codesandbox.io/s/cool-violet-hrk3f?file=/src/App.js

### **Screenshots**
![image](https://user-images.githubusercontent.com/38140078/148038632-be5d98b8-8d4f-47a6-9d32-af546649bde5.png)

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Comment by terezamch** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

When a token is in readonly mode, its' representation in the popover of the multi input still has "x" icon. The same can be seen in the openui5 project, but it seems wrong to me. Steps for reproduction and an isolated example can be seen above.

Could you please state if this behaviour is expected and why or fix the issue?

Thanks,
Tereza

**Comment by niyap** [comment]
Hello @mihirahlawat,

Аs we use ui5-list in "Delete" mode in order to present the tokens list, there is no way to have items with delete button and other without. But as there is an event fired on clear button press - "item-delete", you have the control to decide whether an item should be deleted or not.

Kind Regards,
Niya
