### ISSUE TITLE
Consulting: how to create an Expandable Row using ui5-table?

### ISSUE THREAD

**Issue by Psidium** [SAP/ui5-webcomponents#455]
This is what I was trying to achieve when I faced #454.

I'd like to create an Expandable Row, like this:

![](https://cdn-images-1.medium.com/max/1600/1*0E1UPRzvK4gaV8sZEwOxLQ.gif)

How can I create this using `ui5-table`? (I don't even know if sap.m.Table supports this)

I tried adding a new row that I would show or hide based on some rules, but I cannot create components that fill the whole row of the table.

**Comment by MapTo0** [comment]
I am not really sure if this can be achieved with the current API :/ 

I will give a try for it.
Looks like a feature request for merging cells of a row.

**Comment by Psidium** [comment]
Do you think we could tackle this now that we have a pre-release version of UI5 web components?

**Comment by MapTo0** [comment]
We plan to invest time for improvements of the table component, but I am not completely sure that this feature will be in the roadmap as it is not really a feature of the existing components from OpenUI5.

Anyway, I have it on my mind and we will try to make it feasible to implement with some minor effort in the application.

**Comment by vladitasev** [comment]
Hello,

After consulting the experts, we have determined that the kind of behavior you're trying to achieve is not according to the UX guidelines of the Table. Additional information, according to the latest UX trends, should be shown either in a popup, or by navigating to another page. Therefore at this point we do not plan to implement expandable rows.

Regards,
Vladislav

**Comment by fifoosid** [comment]
Hi @Psidium ,

Here I have created a working example of how you can create expandable rows by yourself: https://codesandbox.io/s/ui5-webcomponents-0881d

Hope it helps you!

Best Regards,
Filip

**Comment by Abhi0806** [comment]
Did anyone find any solution on how it can be achieved using sap.m or sap.ui table ? 
I see there is a blog which explains how it can be displayed under each row . 
https://blogs.sap.com/2019/04/02/sap-ui5-table-row-shift-expand/
But it is not working as expected for ui table or if i try to do any sort of table related tweaks.
Any suggestions on how the child table can be added as a custom control when an expand button is clicked ?

Thanks,
Abhinay
