### ISSUE TITLE
[SF][Table] Growing table on scroll does not work in Chrome 80.0.3987.149

### ISSUE THREAD

**Issue by QiuranHu** [SAP/ui5-webcomponents#4557]
### **Bug Description**
In Chrome 80.0.3987.149, scrolling to the bottom of the table cannot trigger growing. We use Table component in our project and enable growing table on scroll, which causes the script to crash and the page starts to behave strangely in Chrome 80.0.3987.149 . The error message is "Uncaught (in promise) TypeError: Failed to construct 'IntersectionObserver': member root is not of type Element."
![image](https://user-images.githubusercontent.com/55808904/148893388-dc8dd23a-3729-499b-98fe-722ebb1509e9.png)
![image](https://user-images.githubusercontent.com/55808904/148894668-fd70089b-8810-43a0-829d-8696dd2f68b6.png)

Since List with growing="Scroll" works fine in Chrome 80.0.3987.149, I compared the code between List and Table. I notice that the instantiations of IntersectionObserver are different in Table.js [Line 684](https://github.com/SAP/ui5-webcomponents/blob/master/packages/main/src/Table.js#L683-L687) and List.js [Line 1046](https://github.com/SAP/ui5-webcomponents/blob/master/packages/main/src/List.js#L1045-L1049). After modifying this line (https://github.com/SAP/ui5-webcomponents/blob/master/packages/main/src/Table.js#L684) to root: null (same as https://github.com/SAP/ui5-webcomponents/blob/master/packages/main/src/List.js#L1046) in my local environment, everything works like a charm in Chrome 80.0.3987.149. Is it possible for you to make this change?

### **Expected Behavior**
After using Table component and enabling growing table on scroll, scrolling to the bottom of the table should trigger growing without throwing any exceptions and causing script to crash.

### **Steps to Reproduce**
1. Download Chrome 80.0.3987.149
2. Open https://sap.github.io/ui5-webcomponents/playground/components/Table/ in Chrome 80.0.3987.149
3. Go to "Growing Table on Scroll" section.
4. Scrolling to the bottom of the table. The table cannot grow.
5. Check console. There will be a error with error message "Uncaught (in promise) TypeError: Failed to construct 'IntersectionObserver': member root is not of type Element."

### **Context**
- UI5 Web Components version: 1.0.2
- OS/Platform: Linux and windows 10
- Browser: Chrome 80.0.3987.149
- Affected component: Table

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

### **Stakeholder Info** 

- Organization: SAP SuccessFactors

**Comment by vladitasev** [comment]
Hi @QiuranHu 

Chrome ver. 80 is 2 years old. We only support the current versions of "evergreen" browsers.

Here's the table from the project's REAME:

![image](https://user-images.githubusercontent.com/15844574/148959574-041313a6-9fcd-4df9-8c78-d3af515740bc.png)

Regards,
Vladi
