### ISSUE TITLE
openui5-support: Promise returned from init method should be reused during boot of component

### ISSUE THREAD

**Issue by zhangliangyi** [SAP/ui5-webcomponents#4559]
### **Bug Description**
When importing `OpenUI5Support.js` for OpenUI5 integration, I found the `init` method from the feature registered always returns a separated promise instead of a singlton one.

This causes that every time a UI5 component calls the `boot` function, if OpenUI5 feature is registered, the `boot` function need to wait for this new created Promise. And the dependency loader of ui5 would be called multiple times when multiple components are called its `define` method. 

This causes the `boot` function of every component imported executes in a queue and it took 7-8s to define 30+ components.

See code here: https://github.com/SAP/ui5-webcomponents/blob/60d0dc1ad41544ce4afa07b71b8a23b9e821c22b/packages/base/src/features/OpenUI5Support.js#L21

### **Expected Behavior**
The promise returned by the `init` function should be a singleton one, just like:

```javascript
let initPromise;

const init = () => {
    const core = getCore();
    if (!core) {
        return Promise.resolve();
    }

    if (!initPromise) {
        initPromise = new Promise(resolve => {
            core.attachInit(() => {
	        window.sap.ui.require(["sap/ui/core/LocaleData", "sap/ui/core/Popup"], (LocaleData, Popup) => {
		    Popup.setInitialZIndex(getCurrentZIndex());
		    resolve();
		});
	    });
	});
    }

    return initPromise;
};
```

### **Context**
- UI5 Web Components version: 1.0.2
- OS/Platform: MacOS
- Browser: Edge
- Affected component: UI5Element

### **Log Output / Stack Trace / Screenshots**
<img width="1590" alt="2022-01-11_22-01-02" src="https://user-images.githubusercontent.com/1867889/148956924-78f5129c-8101-45aa-89f6-35c5f3227c79.png">

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SF
- Bussiness impact: High

**Comment by nnaydenow** [comment]
Hello @SAP/ui5-webcomponents-core,

Could you please check the issue? It is reproducible in OpenUI5 / SAPUI5 application where web components are used.

Regards,
Nayden

**Comment by zhangliangyi** [comment]
It works, thanks.
