### ISSUE TITLE
ui5-select set selected item via code

### ISSUE THREAD

**Issue by gustavokath** [SAP/ui5-webcomponents#456]
**Describe the bug**
I want to change the selected value of a `ui5-select` using javascript. The use case is this one:
I have a form with `ui5-select` with items inside it and I also have a "clear" button to empty all fields in the form. So I want to reset the `ui5-select` to the initial value or any specific value I want to.

When I update select attributes for for the `ui5-li` components in using javascript the value changes but the element in the screen is not re-render. 

Ps: I don't think the way I tried the make this work is the best one in terms of development experience. If possible having other ways to change that documented would be great.

**To reproduce**
1. See the code
```
<ui5-select id="select">
   <ui5-li selected>Item 1</ui5-li>
   <ui5-li>Item 2</ui5-li>
   <ui5-li>Item 3</ui5-li>   
</ui5-select>
```
2. Execute the following javascript code 
```
document.getElementById('select').children[0].selected = false
document.getElementById('select').children[1].selected = true
```
3. The attributes values for the children elements change but there is no efect in the screen

**Expected behavior**
There should be an way to update the selected element via javascript

**Screenshots**
![image](https://user-images.githubusercontent.com/6647241/58509359-c864a180-816c-11e9-87e8-42ca3df3de81.png)

**Context**
- UI5 Web Components version: 0.11.0
- OS/Platform: Windows
- Browser *(if relevant)*: Chrome

**Affected components**: ui5-select

**Comment by MapTo0** [comment]
Is this issue still on place after the `ui5-option` rework @gustavokath ?

**Comment by MapTo0** [comment]
I tried to reproduce this, but it seems like it has been fixed. Reopen in case I am wrong.
