### ISSUE TITLE
slot for ui5-button is deprecated 

### ISSUE THREAD

**Issue by minjungsung1994** [SAP/ui5-webcomponents#4560]
### **Bug Description**
https://sap.github.io/ui5-webcomponents/playground/components/ShellBar/
<ui5-button icon="nav-back" slot="startButton"></ui5-button>
is deprecated

### **Expected Behavior**
A clear and concise description of what you expect to happen.

### **Steps to Reproduce**
2. ...
3. ...

### **Isolated Example**
If possible, please provide an isolated example by forking [CodeSandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html).

### **Context**
- UI5 Web Components version: {...}
- OS/Platform: {...}
- Browser: {...}
- Affected component: {...}

### **Log Output / Stack Trace / Screenshots**
```
{...}
```
### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Bussiness impact: {...}

**Comment by nnaydenow** [comment]
Hi @minjungsung1994, 

Could you please provide more information regarding issue because with the provided information we can't process it?

Regards,
Nayden

**Comment by minjungsung1994** [comment]
Hello @nnaydenow,
I tried to use ui5-shellbar, and lots of examples included "slot"
`
<ui5-input **slot**="searchField"></ui5-input>
`
which is deprecated now. There are some ways to detour this, yet not really ideal though in my opinion.

**Comment by nnaydenow** [comment]
Hi @minjungsung1994,

Do you use ui5-webcomponents in combination with front-end framework such as React/Vue/Angular? I saw that Vue.js deprecate slot attribute and some eslint plugins catch this as error.

Regards,
Nayden

**Comment by ilhan007** [comment]
Dear @minjungsung1994

we are closing the current issue due to inactivity, but feel free to comment and provide the requested input and we are going to re-open the issue.

BR,
ilhan
UI5 Web Components Team
