### ISSUE TITLE
load-more of the ui5-list is not working when the page is scaled

### ISSUE THREAD

**Issue by Army-U** [SAP/ui5-webcomponents#4572]
### **Bug Description**
I found that the `load-more` event would not be fired while the page is scaled at 80% of the entire page. 

### **Expected Behavior**
`load-more` works well when the page is scaled at any range.

### **Steps to Reproduce**
1. Open https://7c2c8.csb.app/ in a **individual** (<span style="color: red;">**Important!**</span>) tab.
2. Scroll down to the bottom of the page.
3. `load-more` is fired.
4. Use the `cmd+-` shortcut to zoom out the page at 80%.
5. Scroll down to the bottom of the page again.
6. `load-more` is not fired.

### **Isolated Example**
https://codesandbox.io/s/infinite-scroll-of-list-7c2c8?file=/src/App.js

### **Context**
- UI5 Web Components version: 1.0.2
- OS/Platform: macOS Monterey 12.1
- Browser: Chrome/97.0.4692.71
- Affected component: ui5-list

### **Log Output / Stack Trace / Screenshots**
None

### **Priority**
- [x] Low
- [ ] Medium
- [ ] High
- [ ] Very High

### **Stakeholder Info** (if applicable)

- Organization: SAP CIC
- Business impact: None

**Comment by a-z-ivanov** [comment]
Hello, @SAP/ui5-webcomponents-topic-p,

Looks like the IntersectionObserver, used in the List, stops firing its callback when on 80% zoom level. Please, see if there is something to be done.

Regards,
Alex

**Comment by nnaydenow** [comment]
Hi @Army-U,

Could you provide sample code because I'm using the  **List with growing="Scroll"** sample from playground in this https://vpp0w.csb.app/ codesandbox snippix and it seems to work correctly?

Regards,
Nayden

**Comment by ilhan007** [comment]
Hello @Army-U 

we are closing the issue due to inactivity, 
but feel free to provide the requested input and we will re-open the issue.

BR,
ilhan
UI5 Web Components team
