### ISSUE TITLE
ui5-multi-combobox: example code snippet does not work properly

### ISSUE THREAD

**Issue by sammiee5311** [SAP/ui5-webcomponents#4579]
### **Issue Description**
I have tired to use `MultiComboBox with free text input` on [MultiComboBox](https://sap.github.io/ui5-webcomponents/playground/components/MultiComboBox/).

However, It did not work as I expected. 

As you can see, those code snippets are same on the [website](https://sap.github.io/ui5-webcomponents/playground/components/MultiComboBox/).

- **MultiComboBox with items**
``` javascript
<ui5-multi-combobox placeholder="Choose your countries">
	<ui5-mcb-item selected text="Argentina"></ui5-mcb-item>
        ...
</ui5-multi-combobox>
```

- **MultiComboBox with free text input**
``` javascript
<ui5-multi-combobox placeholder="Choose your countries">
	<ui5-mcb-item text="Argentina"></ui5-mcb-item>
        ...
</ui5-multi-combobox>
```

I think `MultiComboBox with free text input` should includes `allow-custom-values` in order to type free input text ?

For examples,

``` javascript
<ui5-multi-combobox allow-custom-values placeholder="Choose your countries">
	<ui5-mcb-item text="Argentina"></ui5-mcb-item>
        ...
</ui5-multi-combobox>
```

### **Issue Type**

- [ ] Documentation is unclear
- [x] Documentation is incorrect
- [ ] Documentation is missing
- [ ] Other

**Comment by nnaydenow** [comment]
Hi @sammiee5311,

Thanks for your finding! You are right, `allow-custom-values` attribute is used in the sample but it is not added in the code snippix.

Regards,
Nayden

**Comment by sammiee5311** [comment]
@nnaydenow no worries !
