### ISSUE TITLE
Input: type "Number" allow to input "+" and "-" in the middle and at the end

### ISSUE THREAD

**Issue by gagarin880120** [SAP/ui5-webcomponents#4580]
**Describe the bug**
Input type "Number" allow to input "+" and "-" in the middle and at the end, instead of allow to input only numbers.

**Expected behavior**
If it is expected behavior, please explain.

**Screenshots**
![image](https://user-images.githubusercontent.com/44781670/149469086-2bfacffc-98fb-4704-b632-ec2cc51bc2f0.png)
![image](https://user-images.githubusercontent.com/44781670/149469150-a0114d26-0852-4f75-bb7d-661bc392456e.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: latest
`@ui5/webcomponents-react` version: latest
Operating System: Windows 10
Browser: Chrome

**Additional context**

**Comment by Lukas742** [comment]
Hi @gagarin880120 

this is HTML Standard for the number input.

See:
- [Input number state](https://html.spec.whatwg.org/multipage/input.html#number-state-(type%3Dnumber))
- [valid floating point number](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#valid-floating-point-number)

**Comment by gagarin880120** [comment]
> Hi @gagarin880120
> 
> this is the HTML standard for the number input.
> 
> See:
> 
> * [input number state](https://html.spec.whatwg.org/multipage/input.html#number-state-(type%3Dnumber))
> * [valid floating point number](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#valid-floating-point-number)

Thank You!

**Comment by nnaydenow** [comment]
Hi @gagarin880120,

Based on the answer of @Lukas742 I'm closing this issue.

Regards,
Nayden
