### ISSUE TITLE
[SF][1.0.2][Input][BUG] Suggestion popup will not be displayed when trigger onInput at first time

### ISSUE THREAD

**Issue by i323808** [SAP/ui5-webcomponents#4585]
### **Bug Description**
There are 2 issues:
1. Suggestion popup will not be displayed when trigger onInput at first time;
2. Suggestion items will not be updated in time according to API's response.

### **Expected Behavior**
1. Popup suggestion when trigger onInput;
2. Suggestion items are supposed to be aligned with API's response.

### **Steps to Reproduce**
1. Please refer to https://codesandbox.io/s/input-with-suggestionitem-wqcyb?file=/src/SearchInput.js.

### **Isolated Example**
https://codesandbox.io/s/input-with-suggestionitem-wqcyb?file=/src/SearchInput.js

### **Context**
- UI5 Web Components version: 1.0.2
- OS/Platform: macOS Monterey
- Browser: Chrome Version 96.0.4664.110 (Official Build) (x86_64)
- Affected component: Input

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

**Comment by a-z-ivanov** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

I cannot reproduce the first issue, getting the suggestions popup every time. 

The second issue with the old suggestions is reproducible. It appears regardless of the data, it only depends on the timing of the suggestions update. When we trigger asynchronous suggestions update, the suggestions list is not updated. I checked the master branch, and modified the dynamic example to use setTimeout - the problem exists there also.

Regards,
Alex

**Comment by a-z-ivanov** [comment]
The original example's on input handler can be simplified a little:

const inputHandler = useCallback(async (e) => {
    //comment this and the problem disappears
    await fetchData(e.target.value);

    setSuggestion([Date.now()]);
  }, []);

As you can see, the data is irrelevant. Just this fetch above delays the update a little bit. Without it, suggestions are updated as expected.
