### ISSUE TITLE
Table height of the Analytical table isn't changing on using responsivepopin

### ISSUE THREAD

**Issue by I516406** [SAP/ui5-webcomponents#4588]
### **Bug Description**
I am using FlexibleColumnLayout in my application, and within the startColumn of FlexibleColumnLayout, I am using an Analytical Table. On click of any row in the AnalyticalTable, the midcolumn of Flexiblecolumn must expand and the startcolumn must show analyticaltable data in cards format. I have used responsivePopin property for the columns there. The card formation and layout changes are happening smoothly only, but the table height is not changing when we're expanding the midColumn. 
Suppose startColumn has 5 rows in the analyticalTable, and suppose the height of each row is 50 right now, when we click on any row, the startColumn shrinks and midColumn expands, making the rowHeight in startColumn to say 250. In that case, the height of the table should also expand, but it remains the same as before and we have to scroll through the table to view all the data. 

### **Expected Behavior**
Instead of what is happening currently, the table height must expand according to the row height and screen height both. 

### **Steps to Reproduce**
1. Go to [CodeSandbox](https://codesandbox.io/s/nifty-estrela-rle9o?file=/src/App.js)
2. Click on any row in the table

### **Log Output / Stack Trace / Screenshots**
<img width="1792" alt="screenshot_2022-01-06_at_2 09 25_pm" src="https://user-images.githubusercontent.com/54435646/149896991-d3db6f72-24d6-434e-b35b-8c68b2fb9365.png">

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

**Comment by a-z-ivanov** [comment]
Hi @I516406,

This is in another related project. Please, log an issue here:
https://github.com/SAP/ui5-webcomponents-react/issues

Regards,
Alex
