### ISSUE TITLE
[ui5-icon] aria-label added only for action-settings icon

### ISSUE THREAD

**Issue by dkris** [SAP/ui5-webcomponents#4590]
### **Bug Description**
Hi Team,

We've noticed a bug when using `action-settings` icon in <ui5-icon>. We've observed that when we use <ui5-icon> in this setting, 
```
<ui5-icon name="action-settings">
</ui5-icon><ui5-label>Settings</ui5-label>
``` 
an additional `aria-label` attribute is added and the role is set to `img`, whereas with any other `name` attribute the role is set to `presentation`.

The resulting SVG when using ui5-icon with the configuration above is as follows.

`<svg class="ui5-icon-root" viewBox="0 0 512 512" focusable="false" preserveAspectRatio="xMidYMid meet" xmlns="http://www.w3.org/2000/svg" tabindex="-1" dir="ltr" role="img" aria-label="Settings">...</svg>`

When a screen reader is used to navigate the application, the settings list item is announced twice as "Settings settings".
However, with any other icon configuration, we don't see the aria-label attribute being added.

For comparison a `ui5-icon` element with name set as `citizen-connect`, we don't see this attribute added and the role stays as presentation.

```
<ui5-icon name="citizen-connect"></ui5-icon>
<ui5-label>Proxy</ui5-label>
```

Here is the resulting SVG with citizen-connect icon name. 

`<svg class="ui5-icon-root" viewBox="0 0 512 512" focusable="false" preserveAspectRatio="xMidYMid meet" xmlns="http://www.w3.org/2000/svg" tabindex="-1" dir="ltr" role="presentation" aria-hidden="true">...</svg>`

During debug, we've observed that the registry entry for action-settings, contains value in accData field which is used to [set the effectiveAccessibleName attribute](https://github.com/SAP/ui5-webcomponents/blob/master/packages/main/src/Icon.js#L356) for ui5-icon component.

```
{
    "key": "SAP-icons/action-settings",
    "value": {
        "pathData": "...",
        "ltr": false,
        "accData": {
            "key": "ICON_ACTION_SETTINGS",
            "defaultText": "Settings"
        },
        "packageName": "@ui5/webcomponents-icons"
    }
}
```

### **Expected Behavior**
Labels should be announced only once when using screen reader to navigate within the application. 

### **Steps to Reproduce**
1. Go to https://codesandbox.io/s/proud-leaf-p4l2n?file=/index.html:236-321
2. Using screen reader, navigate through the screen

### **Context**
- UI5 Web Components version: 1.0.1
- OS/Platform: All
- Browser: All
- Affected component: ui5-icon

### **Priority**
- [ ] Low
- [ ] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SF
- Bussiness impact: Medium

**Comment by a-z-ivanov** [comment]
Hello, @SAP/ui5-webcomponents-topic-p,

I would agree with the author that it is an unpredictable behavior. Not all icons have it. In my opinion it would be better, if you allow the accessibleName property to be set to empty explicitly.

Regards,
Alex

**Comment by nnaydenow** [comment]
Hi @dkris,
 
By default every image should have text that describe it and that's why we add aria-label to every icon. As of version 1.1.0 we are introducing new accessibleRole which allows customisation of the role of each ui5-icon separately. If the the role is set to "presentation" aria-hidden attribute will be set to the SVG element.

Regards,
Nayden
