### ISSUE TITLE
FileUploader sending warn messages in the console

### ISSUE THREAD

**Issue by willianba** [SAP/ui5-webcomponents#4592]
### **Bug Description**
The `FileUploader` component is sending a `console.warn` message because the value-state message has an `Icon` with the `name` property null.

### **Expected Behavior**
No warnings are being thrown in the console.

### **Steps to Reproduce**
1. Use a FileUploader
2. Open the console in the browser and see the warning message

### **Isolated Example**
Since I'm using React, I tested this here: https://codesandbox.io/s/dark-sound-98krw?file=/src/App.js
But it's also happening in the playground: https://sap.github.io/ui5-webcomponents/playground/components/FileUploader/ - just open the console

### **Context**
- UI5 Web Components version: 1.0.2 (latest)
- OS/Platform: MacOS Monterey
- Browser: Safari, Chrome, and Firefox
- Affected component: FileUploader (I didn't test any other)

### **Log Output / Stack Trace / Screenshots**
![Screen Shot 2022-01-19 at 12 16 14](https://user-images.githubusercontent.com/26071084/150159648-2f705d11-e497-4ed2-ab0f-9c25efbcff26.png)

### **Priority**
- [x] Low
- [ ] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Bussiness impact: {...}

**Comment by a-z-ivanov** [comment]
Hello, @SAP/ui5-webcomponents-topic-b,

The FileUploaderPopover template renders the header and the icon unconditionally. This may be improved by checking for a valueStateMessage. And the icon won't be rendered if there is no need.

Look at InputPopover.hbs for a reference.

Regards,
Alex
