### ISSUE TITLE
shellbar-items are not getting the correct stable-dom-ref added to data-ui5-stable

### ISSUE THREAD

**Issue by codefactor** [SAP/ui5-webcomponents#4593]
### **Bug Description**
The shellbar supports passing a stable-dom-ref onto custom shellbar items using the `stable-dom-ref` attribute on the `<ui5-shellbar-item>` - this functionality is not working any longer in version 1.0.X

### **Expected Behavior**
The `<ui5-shellbar-item>` stable-dom-ref should be added to the `<ui5-button>` without being changed.

### **Steps to Reproduce**
1. https://codesandbox.io/s/ui5-webcomponents-forked-r4mxu?file=/index.html
2. Press the button "Check stable-dom-ref"

Expected: it should say "found: true"
Actual: it says "found: false"

Inspect the todo button top-right corner, and see that the stable-dom-ref is some generated ID and is not the expected value of "Todos" which is provided in the shellbar-item:

```html
<ui5-shellbar>
      <ui5-shellbar-item stable-dom-ref="Todos"></ui5-shellbar-item>
</ui5-shellbar>
```

### **Isolated Example**
https://codesandbox.io/s/ui5-webcomponents-forked-r4mxu?file=/index.html

### **Context**
- UI5 Web Components version: 1.0.2
- OS/Platform: any
- Browser: any
- Affected component: ui5-shellbar

### **Log Output / Stack Trace / Screenshots**
```
{...}
```
### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SuccessFactors
- Bussiness impact: Integration with EnableNow/WebAssistant/WalkMe

**Comment by codefactor** [comment]
Please add a unit test to validate the stable dom ref compatibility, these stable dom refs are very important and must be maintained from one version increase to the next.

**Comment by a-z-ivanov** [comment]
Hello, @SAP/ui5-webcomponents-topic-p,

I can see that `stable-dom-ref` doesn't have a setter anymore. Indeed, there is a stable id in the DOM, but it is generated. So, there should be another selector that identifies the DOM element related to the provided ui5-shellbar-item. Can you help, please.

Regards,
Alex

**Comment by fifoosid** [comment]
Hi @codefactor 

Instead of using the ```stable-dom-ref``` concept, you should call the ```getDomRef``` method on the element that you wish. For example:
```js
document.querySelector("ui5-shellbar-item").getDomRef();
```
will return the DOM ref of the element

**Comment by codefactor** [comment]
@fifoosid ,
The solution is unacceptable. Please re-open the ticket. I have also sent a high importance email and slacked you about this issue. Also, is it not common to wait for the confirmation from the opener of an issue that the proposed solution will work before closing the ticket with no changes?

**Comment by codefactor** [comment]
Linking to 2 other issues that are related:
https://github.com/SAP/ui5-webcomponents/issues/4130
https://github.com/SAP/ui5-webcomponents/issues/1840
