### ISSUE TITLE
[BUG][SF][Urgent][UI5-List][Input With Suggestions][Version: 1.0.2] When I click the input, the suggestion list can not pop up

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents#4596]
Dear UI5 team,

This is SuccessFactors Web Experience Shanghai team. 

**The version of ui5-webcomponent is 1.0.2**

**Bug Description**

UI5-List with suggestions items: When I click the input, the suggestion list can not pop up in version 1.0.1 & 1.0.2
But the ui5 list can pop up the suggestion list in version 0.31.x

Excepted Behavior
The ui5 list can pop up the suggestion list in version 1.0.x

**Comment by a-z-ivanov** [comment]
Hello, @SAP/ui5-webcomponents-topic-rl,

Versions 1.x.x are the more mature ones. Maybe this is the expected behavior?

Please, check our sample:
https://sap.github.io/ui5-webcomponents/playground/components/Input/

Regards,
Alex

**Comment by wzyyvonne** [comment]
Dear Team, 
I'm again want to provide some feedback from SuccessFactors. The focus for suggestion is also expected and reported by our customer. Would be very nice if we can include this feature.

**Comment by stbodurov** [comment]
Hi @sfsf-xweb-sh,
Hi @wzyyvonne,
Hi @2bno1

According to the Fiori Guidelines, the suggestions list should open only on typein.

As a workaround, you can use the `open` method of `InputSuggestions.js` on your own risk, as shown here: 
https://codesandbox.io/s/input-suggestions-on-focus-forked-sx3ib?file=/src/index.js

```js
<ui5-input id="myInput" show-suggestions placeholder="Focus to show suggestions"></ui5-input>
------
myInput.addEventListener("focus", async (event) => {
     await input.Suggestions.open();
});
```

https://github.com/SAP/ui5-webcomponents/blob/aa3ca7e6a656f3772d540de0e00de817dcfd8a0e/packages/main/src/features/InputSuggestions.js#L195

Best Regards,
Stanislav & Nikolay
