### ISSUE TITLE
Missing Docs for 1.1.0 release

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents#4608]
White upgrading UI5 Web Components for React to 1.1.0, I noticed that some parts of the documentation seem to be missing:

**SplitButton**
- [ ] `click` and `arrow-click` are not marked as public events, hence they don't appear in the docs and are missing in the react wrapper

**MediaGallery**
- [ ] the `@appendDocs` comment is missing for the `MediaGalleryItem`, hence the `MediaGalleryItem` is not documented

**Icon**
- [ ] `* @type {string}` comment is missing for `accessibleRole` attribute

**ColorPalettePopover**
- [ ] [`openPopover`](https://github.com/SAP/ui5-webcomponents/blob/master/packages/main/src/ColorPalettePopover.js#L176) is not marked as `@public`

**Comment by ilhan007** [comment]
Thank you @MarcusNotheis we will quickly fix these docs issues

**Comment by ilhan007** [comment]
The `openPopover` (which is not currently not marked as public by mistake) is not consistent with the public methods' names of the rest of the popus -it should be `showAt` @tsanislavgatev @fifoosid @vladitasev
