### ISSUE TITLE
ui5-select: input text gets truncated when it is too long

### ISSUE THREAD

**Issue by unazko** [SAP/ui5-webcomponents#4622]
### **Bug Description**
The ui5-select's input value gets truncated if it the corresponding text is too long. Sample applies for the list items in the
dropdown list. There is a fixed width added to the <code>:host</code> element, which isn't specified within the visual specification.

### **Expected Behavior**
The value in the select input field should not be truncated. Same applies for the list items in the drop downlist.

### **Steps to Reproduce**
1. Go to https://codesandbox.io/s/trusting-bush-vnxys?file=/package.json
2. Open the drop down list

### **Isolated Example**
https://codesandbox.io/s/trusting-bush-vnxys?file=/package.json

### **Context**
- UI5 Web Components version: {latest}
- OS/Platform: {Windows 10}
- Browser: {Chrome}
- Affected component: {ui5-select}

### **Log Output / Stack Trace / Screenshots**
ui5-select:
![select_truncation](https://user-images.githubusercontent.com/15860295/150823657-9d5b1f2b-c821-452f-a19e-c322f1da7fb6.png)
sap.m.Select:
![select_correct_behavior](https://user-images.githubusercontent.com/15860295/150824586-02676e49-cb11-4a43-8afc-9cc3efec0073.png)

![spec_row_heigh](https://user-images.githubusercontent.com/15860295/150824402-0551ccb3-2a23-4366-832b-45798ee01b7b.png)

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by unazko** [comment]
Hello @ui5-webcomponents-topic-p,

Could you take over this issue as it is related to the ui5-select component.

Best Regards,
Boyan

**Comment by nnaydenow** [comment]
Hi @unazko,

In OpenUI5 the default width of sap.m.Select is set to auto and this where the difference came from. You can change the width of ui5-select to auto and it will result in the same thing.

Regards,
Nayden
