### ISSUE TITLE
frameworks-vue: suggest to add vue3 Instance API

### ISSUE THREAD

**Issue by sammiee5311** [SAP/ui5-webcomponents#4637]
### **Issue Description**
Suggest to add **Vue3 Instance API** on `Step 4. Add UI5 Web Components to Vue ignoredElement.` ([framworks-vue](https://sap.github.io/ui5-webcomponents/playground/frameworks/vue#step-4-add-ui5-web-components-to-vue-ignoredelement))

Because `Vue.config.ignoredElements` is deprecated since Vue3.

You can check more in detail on this [website](https://v3.vuejs.org/guide/migration/global-api.html#config-productiontip-removed).

``` javascript
// Vue2
Vue.config.ignoredElements = [/^ui5-/]

// Vue3
const app = createApp({})
app.config.compilerOptions.isCustomElement = tag => tag.startsWith("ui5-")
```

> In Vue 3, the check of whether an element is a component or not has been moved to the template compilation phase, therefore this config option is only respected when using the runtime compiler. If you are using the runtime-only build, isCustomElement must be passed to @vue/compiler-dom in the build setup instead - for example, via the compilerOptions option in vue-loader (opens new window).

### **Issue Type**

- [ ] Documentation is unclear
- [ ] Documentation is incorrect
- [ ] Documentation is missing
- [x] Other

**Comment by LidiyaGeorgieva** [comment]
Hello @SAP/ui5-webcomponents-team, please have a look at this issue.
