### ISSUE TITLE
IllustratedMessage: warning is wrong for illustrations imported from `tnt` package

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#4639]
__Note:__ I edited the issue because I didn't see the note in the props description explaining when to use which import, so part of my previously raised issue wasn't actually an issue.

### **Issue Description**
When missing the import while still declaring a TNT illustration on the component, the warning is displaying the wrong path and filename:
```sh
Required illustration is not registered. You can either import the illustration as a module in order to use it e.g. "@ui5/webcomponents-fiori/dist/illustrations/TntUnsuccessfulAuth.js". 
```
As there is no "or" you can probably omit the "either" part there as well ;) 

### Example
[codeSandbox](https://codesandbox.io/s/ui5-webcomponents-forked-j2yq0?file=/src/index.js)

### Context
- UI5 Web Components version: 1.1.1
 

### **Issue Type**

- [x] Documentation is incorrect
- [x] Documentation is missing

**Comment by LidiyaGeorgieva** [comment]
Hello @SAP/ui5-webcomponents-topic-p, please have a look at this issue.
