### ISSUE TITLE
[webcomponents-icons] qr-code icon missing

### ISSUE THREAD

**Issue by Multisaft7** [SAP/ui5-webcomponents#4643]
Hey together,

i am missing the "qr-code" icon in the lastest @ui5/webcomponents-icons.
Can you check this and implement it in the next releases? In the Icon-Explorer the icon is present!

### **Context**
- UI5 Web Components version: 1.1.2

### **Priority**
- Low

Cheers 
Carsten

**Comment by LidiyaGeorgieva** [comment]
Hello @SAP/ui5-webcomponents-topic-p, could you please have a look at this issue.
