### ISSUE TITLE
[SF] [A11Y] [ui5-timeline] Add an accessibleName property to the Timeline

### ISSUE THREAD

**Issue by Neeeko** [SAP/ui5-webcomponents#4644]
### **Bug Description**
Currently, there's no way to pass an `accessible-name` to the Timeline to add an aria-label to the inner list of the component.

<img width="1023" alt="Screenshot 2022-01-26 at 17 50 20" src="https://user-images.githubusercontent.com/7316793/151208988-f38c30f4-119b-4721-bed2-3c05c0e6103a.png">

### **Expected Behavior**
As for many other existing ui5-components, it would be nice to have a `accessibleName` property which maps to the inner list (with class `ul-timeline-list`) in order to add our own aria-label.

### **Context**
- UI5 Web Components version: 0.31.17
- OS/Platform: Windows 10 (using NVDA as screen reader)
- Browser: Google Chrome
- Affected component: ui5-timeline

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### **Stakeholder Info** (if applicable)

- Organization: SuccessFactors

**Comment by LidiyaGeorgieva** [comment]
Hello @SAP/ui5-webcomponents-topic-b, please have a look at this issue.

**Comment by ilhan007** [comment]
Hello @Neeeko the requested `accessibleName` property has been added with this change https://github.com/SAP/ui5-webcomponents/pull/4721  and will be released with 1.2.0 by the end of Feb
