### ISSUE TITLE
treetable components

### ISSUE THREAD

**Issue by chenshuichao** [SAP/ui5-webcomponents#4659]
For example ,account tree table.
Is there any plan about this component?

**Comment by LidiyaGeorgieva** [comment]
Hello @SAP/ui5-webcomponents-team, the reporter is asking is there a plan to create ui5 Treetable web component.

**Comment by ilhan007** [comment]
Hello @chenshuichao,
unfortunately it's not on the Roadmap.

We don't offer a [sap.ui.table.Table](https://openui5nightly.hana.ondemand.com/entity/sap.ui.table.Table) yet and [TreeTable](https://openui5nightly.hana.ondemand.com/entity/sap.ui.table.TreeTable) should definitely come afterwards.

For the [sap.ui.table.Table](https://openui5nightly.hana.ondemand.com/entity/sap.ui.table.Table) the are some preliminary discussions going on and long-term it' likely to have such component. Then, we might extend it further and think about TreeTable, but we are too far from that point. 

BR,
ilhan
UI5 Web Components Core team
