### ISSUE TITLE
FlexibleColumnLayout: `accessibilityRoles` and `accessibilityTexts` shouldn't be part of the component metadata

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents#4671]
### **Bug Description**
This is a follow-up issue on https://github.com/SAP/ui5-webcomponents-react/issues/2544

The Flexible Column Layout has mentioned `accessibilityRoles` and `accessibilityTexts` as part of the component metadata:
https://github.com/SAP/ui5-webcomponents/blob/b641f8b4b815fcb0791da3835d9242b3d79f1634/packages/fiori/src/FlexibleColumnLayout.js#L87-L125

This gives the impression that both attributes can be set in a declarative way which is not true.

**In my opinion this affects all components that "accept" an object as attribute but it can only be set via JavaScript**

### **Expected Behavior**
I would expect that those two properties are removed from the component metadata and are rather implemented with a getter and setter in the component instance itself.
Having these object properties removed from the Component Metadata would also fix our Web Components React Prop Types.

### **Steps to Reproduce**
1. Declarative way doesn't work: https://codesandbox.io/s/flex-column-layout-t9z68?file=/src/App.js
2. Imperative way works: https://codesandbox.io/s/flex-column-layout-forked-hlo9e?file=/src/App.js

### **Isolated Example**
see steps to reproduce

### **Context**
- UI5 Web Components version: 1.1.2
- OS/Platform: macOS
- Browser: Chrome
- Affected component: Flexible Column Layout

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by MarcusNotheis** [comment]
cc @2bno1

**Comment by pskelin** [comment]
Hi @MarcusNotheis ,

attributes make no sense for properties of type object and the base class creates no attributes for such properties.
The documentation was wrong, but I fixed it to reflect the actual code:
`No attribute equivalent will be created for that property. Always true for properties of type Object.`

https://github.com/SAP/ui5-webcomponents/blob/master/docs/5-development/03-understanding-components-metadata.md?plain=1#L64

This should be sufficient for you to know which metadata entries are properties only. Not sure if you can set them directly from the wrapper code, but removing them from the metadata would not be correct as they are public and should cause a rerendering of the component.

**Comment by MarcusNotheis** [comment]
Hey @pskelin,
thanks for explaining - I guess the follow up issue you created makes perfect sense.
We'll then omit all properties in our wrapper that are of type `object`.
