### ISSUE TITLE
[ui5-li] Unable to set accessibleRole attribute for resulting ui5-icon when using icon property 

### ISSUE THREAD

**Issue by dkris** [SAP/ui5-webcomponents#4682]
### **Bug Description**
Hi Team,

When `icon` property for StandardListItem is set, there is no option to set the `accessibleRole` (https://github.com/SAP/ui5-webcomponents/pull/4548) property for the resulting ui5-icon. 

When we specify `action-settings` as the value for the `icon` parameter, the resulting `svg` image for this list item has a default `img` role set to it. 

```
<ui5-icon part="icon" class="ui5-li-icon" name="action-settings" ui5-icon="">
<svg class="ui5-icon-root" viewBox="0 0 512 512" focusable="false" preserveAspectRatio="xMidYMid meet" xmlns="http://www.w3.org/2000/svg" tabindex="-1" role="img" aria-label="Settings">...</svg>
</ui5-icon>

```
When a screen reader is used to navigate the application, the settings list item is announced twice as "Settings settings".

### **Expected Behavior**
accessibleRole should be a config option on the `ui5-li`, that can be passed down to `ui5-icon` when the `icon` property for StandardListItem is set. Labels should be announced only once when using screen reader to navigate within the application.

### **Steps to Reproduce**
1. Go to https://codesandbox.io/s/wonderful-burnell-m62vm?file=/index.html
2. Using screen reader, navigate through the screen

### **Context**
- UI5 Web Components version: 1.1.0
- OS/Platform: All
- Browser: All
- Affected component: ui5-li

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SF
- Bussiness impact: Medium

**Comment by Shtilianova** [comment]
Hello @dkris,
This is behavior is correct and it's happened because the icon name and the text are the same. For this reason the "settings" is announced twice. If you change the text to "apple" for example <ui5-li icon="action-settings">**apple**</ui5-li> it will announce "settings apple".
Regards, Diana

**Comment by ilhan007** [comment]
Hello Didi, actually this is a feature request, the author requests an API to define/control the accessible name of the ui5-icon that is rendered inside StandardListItem.

**Comment by ilhan007** [comment]
Hello @dkris can you make the following clear - do you need to predefine the accessible name of the internally rendered icon - to set it to some custom text. Or you filed the issue because of the repetition inn the reading?

**Comment by dkris** [comment]
> Hello @dkris from our offline discussions I know that you need to control/define the `accessibleRole ` of the internally rendered ui5-icon, rendered inside the StandardListItem. Is that all? Please comment if I miss something. Meanwhile, I will forward your request to the team.
> 
> Hello @SAP/ui5-webcomponents-topic-p it seems that our SF colleagues, that recently requested an API for the ui5-icon, are using the StandardListItem, where the icon is not accessible directly and they need to control the `accessibleRole ` of the ui5-icon, rendered inside the StandardListItem. We either need to expose a slot, or property. similar to the FCL, ShellBar, allowing to set aria attrs to the internals.

You're correct @ilhan007. Thank you for checking.

**Comment by dkris** [comment]
@ilhan007 Is this request going to be handled by @SAP/ui5-webcomponents-topic-p. Will we have an config option available to set the role of the icon within StandardListItem? 
I noticed that you closed the issue. Does this mean it's handled?

**Comment by ilhan007** [comment]
@dkris no, as far I understand this is the team's statement - the purpose of the icon in the StandardListItem is only decorative - it should have role="presentation" and aria-hidden="true". It's not meant to have different role.
@dobrinyonkov is my observation correct?

**Comment by dobrinyonkov** [comment]
I apologize for the misunderstanding. I meant that we need to add these attributes internally. Currently the role is 'img', which should be `presentation` and with `aria-hidden` according to OpenUI5 implementaiton of the List control.

@dkris, apart from excluding the icon from the acc tree do you need the API for any other use case?

**Comment by dkris** [comment]
@dobrinyonkov Excluding the icon from acc tree is the only use case for this API request.

**Comment by dobrinyonkov** [comment]
Hello, PR https://github.com/SAP/ui5-webcomponents/pull/4742 will add the role="presentation" and aria-hidden="true" attributes.
