### ISSUE TITLE
ui5-time-picker - required attribute support

### ISSUE THREAD

**Issue by elenastoyanovaa** [SAP/ui5-webcomponents#4685]
### **Feature Request Description**
The TimePicker components as all other inputs should support the required attribute. Expose a required attribute and map it internally to aria-required (check the implementation in other input fields), since required is not always read out.

### **Additional Context**
As we use the time picker component inside the UI5 Integration Cards of type Adaptive Card, we noticed that this is the only input components, which does not support required currently.

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by DMihaylova** [comment]
Hi @elenastoyanovaa,

Your request came first but because there is another from UI5 Web Components for React for having _required_ and _accessibleNameRef_, I'll close yours and the implementation could be tracked in https://github.com/SAP/ui5-webcomponents/issues/5895.

Thanks & Regards,
Diana
