### ISSUE TITLE
[SF][A11y][ui5-button] tooltip is announced twice when the button is focused

### ISSUE THREAD

**Issue by BennyHuang** [SAP/ui5-webcomponents#4689]
### **Bug Description**
The tooltip of ui-button is announced twice. I observe there is one title for ui5-button element and one title for button element. Maybe just one title is enough. 

### **Expected Behavior**
Focused button should be read once. Repetitive announcements should be avoided.

### **Isolated Example**
If possible, please provide an isolated example by forking https://codesandbox.io/s/affectionate-colden-6bt0t

### **Context**
- UI5 Web Components version: 1.0.2
- OS/Platform: Windows
- Browser: Chrome
- Affected component: ui5-button

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SAP Successfactors

**Comment by Shtilianova** [comment]
Thank you for your ticket. This is expected behavior because has been read both the icon and tooltip.

**Comment by elenastoyanovaa** [comment]
Hello @BennyHuang ,

We have analysed the issue again and the actual root cause of the repetitive speech output comes from setting the title attribute on 2 levels. Once the title attribute is set on the ui5-button, coming from the tooltip property. The second time we set it internally inside the shadow DOM to the native button element in order to make this button accessible by having an accessible name (via the title).

We will discuss the issue and inform you when we have a solution for it. Thank you for reporting!

**Comment by ilhan007** [comment]
Thank you @elenastoyanovaa 

Hello @SAP/ui5-webcomponents-topic-b as you can see from the screenshot the title attribute is set on the ui5-button and on the button tags, causing repetitive speech output:

<img width="494" alt="Screenshot 2022-02-03 at 16 01 01" src="https://user-images.githubusercontent.com/15702139/152357430-08d3c75b-21f3-4a60-9dff-9111f451c81c.png">

I suggest discussing this internally, some options that we already discussed with @elenastoyanovaa are removing the "title" attribute forwarding and exposing a `tooltip` property to avoid this duplication, or make use of the newly added `accesibilityAttributes` property.
Once you have a proposal, we can discuss it together.

**Comment by rchrdchn** [comment]
Thank you @ilhan007!
