### ISSUE TITLE
[SideNavigationItem] allow user to decide which SideNavigationItem to be selected based on 'selected' property

### ISSUE THREAD

**Issue by samanr** [SAP/ui5-webcomponents#4700]
**Is your feature request related to a problem? Please describe.**
Yes,

**Context--While implementing a data loss prompt.**
Side Navigation acts as a side panel menu where each side nav item corresponds to a page.
Let's assume user are on navItem1 (Green) and click on navItem2 (Yellow), selectedId is "Green". 

User have some unsaved data on page corresponds to 'Green' but User clicks navitem2 "Yellow"

Before moving on, user were able to block the page with a MessageBox Prompt and did not update the selectedId to "Yellow".

**Current Behavior:**
Since user have already clicked on 'Yellow' the navitem  is 'selected' and 'focused' even if the selectedId remains 'Green'. In this case 'Yellow' should not have been selected because the condition for selected property is not met.

SandBox: https://codesandbox.io/embed/sidenavigation-2e5qn?fontsize=14&hidenavigation=1&theme=dark

**Expected Behaviour:**
'Selected' property should decide which side navigation item should be selected and focused. This will give user control over what they need as selected.

**Comment by alexandar-mitsev** [comment]
Hi @Lukas742 , @samanr ,

For such scenario the regular behaviour which we implement is to allow e.preventDefault() of the event inside the onSelectionChange handler. So when the event is prevented it will not perform the selection.

This should perfectly cover your use case. Can you confirm however that you are ok with this solution and you don't see problems?

In the meantime we will work on implementing it.

Regards,
Alexandar Mitsev

**Comment by alexandar-mitsev** [comment]
Hello @SAP/ui5-webcomponents-topic-rd ,

I am forwarding this issue to you since it is related to Side Navigation.
Currently there is no way to prevent the default behaviour during a selection change by the user.
To allow this, the best solution is to not make the selection if e.preventDefault() is called inside the selection-change event handler.

Regards,
Alexandar Mitsev

**Comment by Lukas742** [comment]
Hi @alexandar-mitsev. 

I actually tried using `preventDefault` in both `click` and `selection-change` events, so it would have been my first idea to implement the behavior that way too :) 

@samanr would this approach be fine with you as well, or do you have any objections?

**Comment by samanr** [comment]
@Lukas742  @alexandar-mitsev  Thanks for suggestions, It does makes sense, however it did not work with our code base. I could not pin-point why.
I added it as the first statement of the onSelection event handler. The event defaultPrevented remains false.
Ultimately I had to resort to 
```
evt.detail.item.removeAttribute("selected");
document.querySelector(`#${selectedId}`).setAttribute('selected', true)
```

**Comment by alexandar-mitsev** [comment]
Hi @samanr , 

Sorry for the misunderstanding - we plan to make it work, it is not implemented now. Was just asking to be sure if it suits your use case.

Regards
