### ISSUE TITLE
UI5 elements: All CBC versions: There is no stable unique attribute for the ui5-static-area-item elements

### ISSUE THREAD

**Issue by sap-dzmitrybutsko** [SAP/ui5-webcomponents#4715]
### **Bug Description**
There is no way to get the particular ui5-static-area-item by unique attribute. Therefore, we have to use locators based on the sequence numbers of the elements like //ui5-static-area-item[5]. This approach makes our testing unstable. Over time, the number of such problems increasing with the test framework growth.

### **Steps to Reproduce**

1. Go to the CBC system https://tenant-1.dev01-ui-e2e-regression.cbc.only.sap/sap/public/ap/smeui/repository/SAP_UI/HTMLOBERON5/client.html?sap-b-automation=true
2. Login with user ID "tester" and password "Welcome1"
3. Open PE page https://tenant-1.dev01-ui-e2e-regression.cbc.only.sap/sap/public/x4/bc/pe/index.html#/
4. Create any project
5. Click "Open" button in Define Scope activity
6. Choose any countries
7. Open ChromeDevTools and search for ui5-static-area-item element

### **Actual Behavior**
There are several ui5-static-area-item elements with autogenerated class attributes. There is no possibility to make such elements unique. We talked to our developers and they said that we are unable to add something like StableDomRef in these high-level elements. They can only do it for elements inside shadow root but it's not the solution in our case.
<img width="1428" alt="image" src="https://user-images.githubusercontent.com/89077146/153088678-d124cc74-32a7-4764-b09d-1c6a624276af.png">

### **Expected Behavior**
ui5-static-area-item elements should have a unique attribute(like data-automation-id). Mostly, it would be great to have the possibility to add some StableDomRef or data-automation-ids or something stable and unique for such kind of elements

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### **Stakeholder** Info (if applicable)**
Organization: {SAP}
Project {CBC}
Business impact: {Inability to write stable UI tests for the system. As a result, the system testing is become unstable after adding UI-5 components}

**Comment by vladitasev** [comment]
Hello colleagues,

We recently addressed this with the following PR: https://github.com/SAP/ui5-webcomponents/pull/4485

Updating to the latest version (if not already using it) would give you the desired functionality.

Regards,
Vladi
