### ISSUE TITLE
DatePicker has unneeded scrollbars on Safari

### ISSUE THREAD

**Issue by LidiyaGeorgieva** [SAP/ui5-webcomponents#4724]
### **Bug Description**
DatePicker has unneeded scrollbars on Safari (on Chrome there are no scrollbars).

![image](https://user-images.githubusercontent.com/7242508/153359063-69dd50c9-1c48-44ef-8085-2a982ba6eb7d.png)

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/master/playground/main/pages/DatePicker/)
2. Pick a date

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by alexandar-mitsev** [comment]
Hi @ui5-webcomponents-topic-b ,

Forwarding the issue to you since it is related to Date Picker. Reproducible on Safari.

Regards,
Alexandar Mitsev
