### ISSUE TITLE
ViewSettingsDialog: unneeded horizontal scrollbar on Firefox

### ISSUE THREAD

**Issue by LidiyaGeorgieva** [SAP/ui5-webcomponents#4725]
### **Bug Description**
ViewSettingsDialog has unneeded horizontal scrollbar on Firefox (on Chrome is not there).

![image](https://user-images.githubusercontent.com/7242508/153367924-4cc90424-fe61-4d12-b9af-fb83203eee47.png)

### **Steps to Reproduce**
1. Open Firefox
2. Go to https://sap.github.io/ui5-webcomponents/master/playground/fiori/pages/ViewSettingsDialog/
2. Open any ViewSettingsDialog
3. Resize the screen vertically to show vertical scrollbar -> unneeded horizontal scrollbar appears

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by alexandar-mitsev** [comment]
Hi @SAP/ui5-webcomponents-topic-rl ,

Forwarding this ticket to you since it is related to the View Settings Dialog. Reproducible on Fireforx.

Regards,
Alexandar Mitsev

**Comment by niyap** [comment]
Hello @SAP/ui5-webcomponents-topic-b,

As the View Settings Dialog is owned by you, I think that the incident is forwarded  to our team by mistake.
Could you please look over the issue?

Thank you in advance!

Kind Regards,
Niya
