### ISSUE TITLE
Wizard: unnecessary scroll overflow on step 1 

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#4726]
### **Bug Description**
When only step 1 of the `Wizard` is selected, and the content is not overflowing the container, the content is unnecessarily going into scroll overflow. 

![image](https://user-images.githubusercontent.com/9749730/153369043-195545da-5e9a-4c73-ada7-653a5a0dff3f.png)

### **Expected Behavior**
When only the first step is selected and the content of that step doesn't overflow the container, then there should be no scrollbar rendered.

### **Steps to Reproduce**
1. Go to [playground](https://sap.github.io/ui5-webcomponents/playground/components/Wizard/) or [codeSandbox](https://codesandbox.io/s/ui5-webcomponents-forked-03ece?file=/src/index.js)
2. See that even though only step 1 of the WizardSteps is displayed, the container is still scrollable.

### **Isolated Example**
- https://sap.github.io/ui5-webcomponents/playground/components/Wizard/
- https://sap.github.io/ui5-webcomponents/master/playground/components/Wizard/
- https://codesandbox.io/s/ui5-webcomponents-forked-03ece?file=/index.html

### **Context**
- UI5 Web Components version: 1.1.2

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by alexandar-mitsev** [comment]
Hi @SAP/ui5-webcomponents-topic-rl ,

Forwarding this ticket to you since it is related to the Wizard. Reproducible in the playground on the latest version.

Regards,
Alexandar Mitsev
