### ISSUE TITLE
Slider & RangeSlider: handle is misaligned in compact mode 

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#4741]
### **Bug Description**
In compact mode when focusing a slider handle, the handle gets misaligned.

https://user-images.githubusercontent.com/9749730/153827434-0b950591-84c2-41fd-88ff-d8104770e957.mp4

### **Expected Behavior**
The handle should stay centered no matter what mode or state it's in.

### **Steps to Reproduce**
1. Go to [codeSandbox](https://codesandbox.io/s/ui5-webcomponents-forked-fh35b?file=/index.html) or Silder/RangeSlider playground
2. Focus one of the slider handles
3. See that the handle is misaligned

### **Isolated Example**
https://codesandbox.io/s/ui5-webcomponents-forked-fh35b?file=/index.html

### **Context**
- UI5 Web Components version: 1.1.2

**Comment by ivoplashkov** [comment]
Hello @SAP/ui5-webcomponents-topic-rl, the issue is reproducible as described.
Could you please have a look?

Thanks in advance,
Ivaylo
