### ISSUE TITLE
Documentation: TabContainer sample has wrong display

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents#4743]
### **Issue Description**
TabContainer's sample should be fixed. Currently they are two pairs of braces around the additional-text. 
It seems that the pair, defined in the sample is the one to remove:

<img width="568" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/15702139/153830792-a410349a-36b0-4f49-b11e-c283ff526380.png">

### **Issue Type**

- [ x ] Documentation is incorrect

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-rd I'm forwarding a small issue with one of the TabContainer samples

**Comment by ilhan007** [comment]
Hello @henriquemattos
what you say it makes sense to me. What I know is that this is somehow part of the component spec, but I agree that if the parenthesis () are removed internally it would give more freedom the app developers. I will let the owners of the component give their statement and decide what is best. 

@SAP/ui5-webcomponents-topic-rd , what do you thin? Would it be possible to make this more open by not adding auto parenthesis () and let that to the app. We can still add them in the samples as recommendation.

**Comment by TeodorTaushanov** [comment]
Hi @henriquemattos,

The "additional-text" is usually used to set some count value, so the result will be "Monitors (3)".

In your case you don't need to use the "additional-text" property. You can just use: 
`text="Monitors: Samsung"`

Best,
Teo
