### ISSUE TITLE
Support for highlighting dates in Calendar component

### ISSUE THREAD

**Issue by pavelkornev** [SAP/ui5-webcomponents#4756]
### **Feature Request Description**
Calendar component is missing a feature to highlight specific dates with a color like in UI5:
![calendar](https://user-images.githubusercontent.com/748043/154109630-32f9dbb0-2a48-4476-801b-447fcef93c78.png)

### **Proposed Solution**
Add support of highlighting days similar to UI5 feature.

### **Proposed Alternatives**
N/A

### **Additional Context**
N/A

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### **Stakeholder Info** (if applicable)

- Organization: CPA

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-b @petyabegovska consider this feature request by Pavel who is part of Cross Product Architecture team.

**Comment by DMihaylova** [comment]
Hello @pavelkornev,

The brand new Calendar Legend component is now ready and there are also special calendar dates introduced in the Calendar.

**Comment by pavelkornev** [comment]
Thanks for informing, though after 2 years of waiting it's no longer relevant.

**Comment by DMihaylova** [comment]
Due to prioritization reasons, it took longer than expected. We appreciate your understanding.
