### ISSUE TITLE
SAP Belize Deep Theme availability

### ISSUE THREAD

**Issue by Arora05** [SAP/ui5-webcomponents#4759]
Can we have SAP Belize Deep theme also available for selection

**Comment by ilhan007** [comment]
Hello @Arora05 unfortunately we don't have plans to add it. 

It's more likely to deprecate the existing Belize theme family belize, belize_hcb, belize_hcw. Currently we are working on new theme family  Fiori Next (Horizon)  - `sap_horizon, sap_horizon_dark, sap_horizon_hcw, sap_horizon_hcb`. Once we complete it we may deprecate Belize, so we can easily move forward and adhere to the new design concepts.

**Comment by Arora05** [comment]
Hello @ilhan007 , is there a timeline up to when we can expect these themes to be delivered.
Thanks, Kshitiz

**Comment by ilhan007** [comment]
Hello @Arora05 the timeline for the new sap_horizon_* theme family is by the end of April.
