### ISSUE TITLE
Feature request: ui5-analytical-table for vue3

### ISSUE THREAD

**Issue by sammiee5311** [SAP/ui5-webcomponents#4765]
### **Feature Request Description**
I'm building a webapp that uses a table by `vue3`. I know there is already an [AnalyticalTable](https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-analyticaltable--default-story) for react, however I hope there will be for vue3 too!

### **Proposed Solution**
To have an AnalyticalTable for `vue3`.

### **Proposed Alternatives**
To use react ?

### **Priority**
- [x] Low
- [ ] Medium
- [ ] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Bussiness impact: {...}

**Comment by ivoplashkov** [comment]
Hello @sammiee5311,

The AnalyticalTable is pure React component and is not part of the our bundle, therefore we are not responsible for it.
You can make yourself AnalyticalTable component using the SAP theming parameters. More information could be found in the [Github Repo](https://github.com/SAP/theming-base-content).

Hope this helps!
Best regards,
Ivaylo

**Comment by sammiee5311** [comment]
@ivoplashkov Thanks for information ! I will check the SAP theming.
