### ISSUE TITLE
Input: breaking change in event dispatch

### ISSUE THREAD

**Issue by AndrianStoikov** [SAP/ui5-webcomponents#4769]
### **Bug Description**
In version `1.0.2` the `Input` component fires `onChange` before the `onBlur` event. We depend on this behavior in order to properly validate our forms. By using the `onBlur` event we mark that the user has interacted with the input and after the `onChange` is fired we update the value that we track. 

Now in version `1.1.2` the `onBlur` event is triggered before the `onChange` which triggers the input validation before the value has been actually changed for this field and results in bad UX.

### **Expected Behavior**
I think the old behavior was actually correct and it should be 1. `onChange`, 2. `onBlur`.

This [sandbox](https://codesandbox.io/s/ui5-webcomponents-forked-xdurx4?file=/index.html) shows the native behavior of input and it is 1. `onChange`, 2. `onBlur`

### **Steps to Reproduce**
1. Go to [Sandbox 1](https://codesandbox.io/s/ui5-webcomponents-forked-kjs9tv?file=/index.html)
2. Check the console & observe behavior in 1.0.2
3. Go to [Sandbox 2](https://codesandbox.io/s/ui5-webcomponents-forked-303u2n?file=/index.html)
2. Check the console & observe behavior in 1.1.2

### **Isolated Example**
 [Sandbox 1](https://codesandbox.io/s/ui5-webcomponents-forked-kjs9tv?file=/index.html) - 1.0.2

[Sandbox 2](https://codesandbox.io/s/ui5-webcomponents-forked-303u2n?file=/index.html) - 1.1.2

### **Context**
- UI5 Web Components version: 1.1.2
- OS/Platform: Windows 10
- Browser: Microsoft Edge Version 98.0.1108.50
- Affected component: Input

### **Log Output / Stack Trace / Screenshots**
```
{...}
```
### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: RBSC
- Bussiness impact: {...}

**Comment by ivoplashkov** [comment]
Hello @AndrianStoikov ,

Unfortunatelly the blur event is not part of the provided API for the Input component, therefore we are unable to maitain such relation between the two events.
If you feel that there is a need for an additional event, in order to achieve desired behaviour, please consider making a feature request in order for us to review it.

Hope this helps!
Best regards,
Ivaylo
