### ISSUE TITLE
[SF][1.1.2][ui5-tabcontainer]: slot overflowButton will get runtime error

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents#4770]
### **Bug Description**

when we give a `ui5-button` for slot `overflowButton` and it will get a runtime error when resizing tabs to overflow.

### **Expected Behavior**

It's should has the same behavior with no `overflowButton` slot.

### **Steps to Reproduce**
/

### **Isolated Example**
/

### **Context**
- UI5 Web Components version:  1.1.2
- OS/Platform: Mac
- Browser: any
- Affected component: ui5-tabcontainer

### **Log Output / Stack Trace / Screenshots**

https://github.com/SAP/ui5-webcomponents/blob/234505653f4c55f11be5c10f946adf8f7b23f9af/packages/main/src/TabContainer.js#L906

this line will return a null element and  cause runtime error later.

<img width="812" alt="image" src="https://user-images.githubusercontent.com/78520316/154305877-3937b1fc-2992-43cd-a74d-d186ed9b4af5.png">

and below screenshots  is ok when  no `overflowButton` slot.

<img width="788" alt="image" src="https://user-images.githubusercontent.com/78520316/154307036-ccc80c6d-5614-4950-a0e5-c3d2067b577b.png">

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

we're closed to the end of b2205, so please help to take a look at this issue, and thx~

**Comment by ivoplashkov** [comment]
Hello @SAP/ui5-webcomponents-topic-rd,

In case of `ui5-button` for `overflowButton` slot, there is a runtime error.
Could you please have a look?

Best regards,
Ivaylo
