### ISSUE TITLE
[SF][1.1.2][ui5-icon][message-information][sap-horizon]: message-information icon displays wrong in sap horizon theme

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents#4771]
Dear colleagues,
I am from Shanghai WEF team

**Bug Description**
[SF][1.1.2][ui5-icon][message-information][sap-horizon]: message-information icon displays wrong in sap horizon theme.

In sap fiori 3 theme, the message information icon looks like:  ( this icon is hollow )
![Screen Shot 2022-02-17 at 2 59 45 PM](https://user-images.githubusercontent.com/78520316/154422525-18de3140-1b0f-4972-931e-18b2de95ae8f.png)

In sap horizon theme, the message information icon looks like: ( this icon is solid )
![Screen Shot 2022-02-17 at 2 59 17 PM](https://user-images.githubusercontent.com/78520316/154422589-a58a4cc4-c697-4698-8b1c-a202b418b78b.png)

**In sap horizon theme, the message-information icon becomes the information icon, this is not correct**

![Screen Shot 2022-02-17 at 3 03 27 PM](https://user-images.githubusercontent.com/78520316/154422975-b69e356f-64ae-4262-ba5a-abfdd01d0b68.png)

 **Expected Behavior**
**Keep the message-information icon correct in sap horizon theme**

**Comment by sfsf-xweb-sh** [comment]
Hi @ivoplashkov 
You can reproduce it on ui5 web-component playground page

1. open [https://sap.github.io/ui5-webcomponents/playground/components/Icon/](https://sap.github.io/ui5-webcomponents/playground/components/Icon/)
2. change the name of a ui5-icon to message-information

In fiori3, message-information icon looks like:
<img width="1293" alt="Screen Shot 2022-02-18 at 3 28 45 PM" src="https://user-images.githubusercontent.com/78520316/154642988-1278b11a-bc1a-4932-866f-b3ad07abaf54.png">

In sap horizon theme, it looks like:

<img width="1269" alt="Screen Shot 2022-02-18 at 3 42 54 PM" src="https://user-images.githubusercontent.com/78520316/154643394-536016ac-e3f5-42f0-bbcf-8545c5f37c69.png">


![](https://user-images.githubusercontent.com/78520316/154422975-b69e356f-64ae-4262-ba5a-abfdd01d0b68.png)

**Comment by ivoplashkov** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

I was not able to find any information related to appeareance of the message-information icon in Horizon theme, therefore this might be something to bring to our designers for their opinion.
You can reproduce it as described in the latest reply.

Best regards,
Ivaylo

**Comment by ilhan007** [comment]
Hello @sfsf-xweb-sh you get the same in OpenUI5
https://openui5nightly.hana.ondemand.com/entity/sap.ui.core.Icon/sample/sap.ui.core.sample.Icon

It seems in Horizon the message-information icon results in what you currently get. But, we will double check with the visual designers.

**Comment by ilhan007** [comment]
Hello @sfsf-xweb-sh 

We contacted the responsible designers and indeed it turns out to be a bug.
Th designers will have to fix this and update the icon font for horizon especially. They have no capacity to fix this in the current design sprint (overwhelmed with completing Horizon specs for the UI5 controls/components),
but they will be doing icon font bug fixes especially for horizon in the next design sprint U-2204.

When we have more info on more specific timeline I will update you.

**Comment by sfsf-xweb-sh** [comment]
Hi @ilhan007 

Thanks

**Comment by ilhan007** [comment]
Hello @sfsf-xweb-sh 

the icon being filled is actually intended for the horizon theme. This was clarified by the SAP design colleagues (Gerry Kean and Georg Cristoph). So, the current state is the target design and no changes will be made.
In case you have further comments, you can directly contact the SAP Design colleagues.

Best Regards,
ilhan
