### ISSUE TITLE
ui5-shellbar: set the role of the logo

### ISSUE THREAD

**Issue by JarrettChan** [SAP/ui5-webcomponents#4775]
### **Feature Request Description**
We use the ui5-shellbar focusable logo effectively as a link through using `@logoClick` to navigate.
Please provide a way to customize the role of the focusable logo.

### **Proposed Solution**
Provide a `Shellbar.accessibilityAttributes` (similarly to `Shellbar.accessibilityTexts`)
Then apply `Shellbar.accessibilityAttributes.logoFocusable.role` to the logo button through `Shellbar.accInfo.logoFocusable.role`.

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: SuccessFactors
- Business impact: Render the focusable logo button as a link for screen readers

**Comment by dobrinyonkov** [comment]
Internal reference: 5781
