### ISSUE TITLE
ui5-step-input layout issue using smaller width

### ISSUE THREAD

**Issue by hschaefer123** [SAP/ui5-webcomponents#4786]
### **Bug Description**
Using the StepInput with a small width, the inner controls are rendering to wide.

### **Expected Behavior**
Setting css style width:7rem, text-align:center on control for entering small values should be possible, but instead, inner controls overflow.

### **Context**
- UI5 Web Components version: 1.1.2
- Affected component: ui5-step-input

### **Log Output / Stack Trace / Screenshots**
![StepInputIssue](https://user-images.githubusercontent.com/2110971/154846166-74f88bd7-9274-4696-8e9c-89924f9c09d8.png)

Also text-align: center is no more working correct, because inner fields are wrongly calculated.

### **Priority**
- [x] Medium

- Organization: UNIORG Solutions GmbH
- Bussiness impact: docu site

Regards
Holger

**Comment by dobrinyonkov** [comment]
Hello @SAP/ui5-webcomponents-topic-b,

When the following styles are set to the ui5-step-input, the inner ui5-input is not rendered correctly: 
`width: 7rem`
`text-align: center`

The reason is that the ui5-input has a `min-width: 9.125rem` which makes it bigger than its host.

Regards,
Dobrin

**Comment by ilhan007** [comment]
Hello @hschaefer123 

You can inject custom css inside the StepInput's shadow DOM by using the `addCustomCSS` method. 
This is not encouraged, but might be useful as temporary quick solution. I did not try if your proposal works, just explaining how to inject a css into the Shadow dom.

```js
import { addCustomCSS } from "@ui5/webcomponents-base/dist/Theming.js";
addCustomCSS("ui5-step-input", ":host .ui5-step-input-input {min-width: calc(100% - 2 * 4rem);} ");
```

**Comment by hschaefer123** [comment]
Hi @ilhan007

fix works perfect!

Even `addCustomCSS("ui5-step-input", ":host .ui5-step-input-input {min-width: inherit;}");` does the job.

It is working live at
[http.s//btp.udina.de/service/udina/pricing.html#estimator-tool](https://btp.udina.de/service/udina/pricing.html#estimator-tool)

I will remove fix, if fixed update is available.

Thank you very much for the tip!

Regards
Holger

**Comment by ilhan007** [comment]
Hello @hschaefer123 welcome, the docs are nice. Are using only the ui5-step-input, do you depend on more web components, I did not check all the pages?

Regarding a real solution, the issue assignee @tsanislavgatev would update you.

**Comment by hschaefer123** [comment]
Hi @ilhan007,
the site
[UI5WC](https://btp.udina.de/development/ui5wc.html)
is showcasing the to-do list.

The whole estimator is a UI5 Web Components app (List, GroupHeader, Button, etc).

The introduction page
[SaaS]https://btp.udina.de/overview/cloudmodels.html#infrastructure-as-a-service-iaas)
uses the Tab control.

Regards
Holger

**Comment by tsanislavgatev** [comment]
Hello @hschaefer123 ,

We've fixed the issue with the focus, and we have updated the min width of the control in both cosy and compact.

The min widths are : 7.25rem for Cosy and 6 for compact, this is the lowest width that this control can get without the risk of losing information and conflicting with accessibility rules.

Best Regards,
Tsanislav

**Comment by hschaefer123** [comment]
Hi Tsanislav,
thanks.

Best Regards 
Holger
