### ISSUE TITLE
Input with SuggestionItem not resizing correctly on iPhone 12 Pro Chrome / Safari (works alright in Android)

### ISSUE THREAD

**Issue by miltonchandradas** [SAP/ui5-webcomponents#4794]
### **Bug Description**
Input with SuggestionItem not resizing correctly on iPhone Chrome (works alright in Android)

### **Expected Behavior**
Input with SuggestionItem should render correctly when typing in it
Input should be highlighted when clicking on it

### **Steps to Reproduce**
Try with the sample code provided here...
https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-input--with-suggestion-item
Deploy app to SAP Cloud Foundry
Run the app on iPhone 12 Pro Chrome / Safari browser

Click on the input field
New Select screen opens up - but not highlighted
You have to click on Input again to type
Type any letter
Screen width gets changed
Select an item
Note that the keypad still remains
Done button still remains
Screenshot of characters cut off attached

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

![input_screenshot](https://user-images.githubusercontent.com/47120473/155064608-02ca124b-bede-425c-9f9d-f56f896d1c15.jpeg)

**Comment by dobrinyonkov** [comment]
Hi @miltonchandradas,

this is a default browser behavior to zoom/scale the page. This should be prevented on application level with the following meta tag inside the `<head>`: 

`<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">`
