### ISSUE TITLE
[SF][1.1.2][ResponsivePopover][BUG][Expected within two weeks] Arrow going out of bounds

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents#4797]
Dear UI5 team,

This is SuccessFactors Web Experience Shanghai team. We found this issue in the process of upgrading to Fiori Next, the version we are using is `1.1.2`

### **Bug Description**
Responsive popover's arrow is going out of bounds, please see screenshot.
![Screen Shot 2022-02-22 at 5 57 16 PM](https://user-images.githubusercontent.com/78520316/155108326-a8fcab0a-c377-4167-a743-f4a6b1db3638.png)

### **Priority**
- [x] Medium

- Organization: SF

**Comment by dobrinyonkov** [comment]
Hi @gmkv,

as we talked, this might be an edge case not coverd by the fix #4581.

Also, with the change for the default paddings #4567, the misalignment is slightly less but still might need an investigation for a different solution.

Regards,
Dobrin

**Comment by gmkv** [comment]
Hi @sfsf-xweb-sh 

Is it possible to recreate this issue in an isolated example [here](https://codesandbox.io/s/wizardly-zeh-cxw4dg)?

**Comment by gmkv** [comment]
Issue occurs when the opener is a small element and the Popover's vertical align is set to align to the top/bottom of that opener.
