### ISSUE TITLE
[Bug][SF][1.1.2][UI5-List][sap-horizon] separators lines are missing in sap horizon theme

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents#4803]
Dear colleagues,
I am from Shanghai WEF team

**Bug Description**
In sap ui5 lib, you can see that the separator lines are available in horizon theme
link: [https://sapui5.hana.ondemand.com/#/entity/sap.m.List/sample/sap.m.sample.ListSelection](https://sapui5.hana.ondemand.com/#/entity/sap.m.List/sample/sap.m.sample.ListSelection)
![Screen Shot 2022-02-23 at 3 28 11 PM](https://user-images.githubusercontent.com/78520316/155282233-48ebdfa8-d1e3-4309-a66f-b541e24a00ab.png)

But in ui5 web-component lib, the separator lines are missing
[https://sap.github.io/ui5-webcomponents/playground/components/List/?sap-ui-theme=sap_horizon&isrtl=false](https://sap.github.io/ui5-webcomponents/playground/components/List/?sap-ui-theme=sap_horizon&isrtl=false)

![Screen Shot 2022-02-23 at 3 31 34 PM](https://user-images.githubusercontent.com/78520316/155282248-d8d8ff12-f983-49d2-8958-a109a7add530.png)

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-p it seems the List separators are missing in Horizon.
