### ISSUE TITLE
ui5-card-header: a11y - Provide option to specify header title as link

### ISSUE THREAD

**Issue by gurkirpalgill** [SAP/ui5-webcomponents#4814]
### **Bug Description**
The whole header should not receive the tab focus if there is no role announced for it. Rather the title of the tile should get the first focus which can have the "link" role , then on next tab the focus should go to next focusable element.

### **Context**
- UI5 Web Components version: 1.1.0
- OS/Platform: NA
- Browser: Chrome
- Affected component: ui5-card-header

### **Log Output / Stack Trace / Screenshots**
<img width="1853" alt="Screen Shot 2022-02-23 at 2 55 43 PM" src="https://user-images.githubusercontent.com/65705637/155424655-7322a64e-79a1-4868-8a50-8bf2f9fdd2dd.png">

```
{...}
```
### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by dobrinyonkov** [comment]
Hello @gurkirpalgill,

there was a discussion about this in the past. The reason to focus the whole header is to keep the consistancy between interactive and non-interactive cards. 
Please, checkoout the team's full statement here: https://github.com/SAP/ui5-webcomponents/issues/3642#issuecomment-897535975

If you have further questions please reopen the issue and we will forward to the component owners.

Best Regards,
Dobrin

**Comment by stes-acc** [comment]
We will evaluate the option to add "Interactive" as part of the Card Header aria-roledescription and update this when decided.

**Comment by anuvenkatesh1** [comment]
Thanks @stes-acc 
@dobrinyonkov   Could you kindly keep this ticket in open status until then as we have an internal issue that references this ticket and solution/fix based on any feature enhancement related to this.

Thanks

**Comment by gurkirpalgill** [comment]
@dobrinyonkov Central A11y is looking into enhancement/fix for this. Please re-open this ticket.
