### ISSUE TITLE
[SF][1.1.2][ResponsivePopover][BUG][Expected within two weeks] ShowAt methods runs with errors under mobile

### ISSUE THREAD

**Issue by ksblklu** [SAP/ui5-webcomponents#4833]
Dear UI5 team,

This is SuccessFactors Web Experience Shanghai team. We found this issue in the process of upgrading to Fiori Next, the version we are using is 1.1.2

### **Bug Description**
ResponsivePopover.showAt method run with error under mobile

### **Expected Behavior**
runs with no error when open the Popover Dialog

### **Steps to Reproduce**
/

### **Isolated Example**
/

### **Context**
- UI5 Web Components version: {1.1.2}
- OS/Platform: {mobile(iphone12Pro)}
- Browser: {any}
- Affected component: {ui5-responsive-popover}

### **Log Output / Stack Trace / Screenshots**

https://github.com/SAP/ui5-webcomponents/blob/dc070a12f5ce5860e013be052c8dc0fc5ca1f125/packages/main/src/ResponsivePopover.js#L133

this line will return a null element and cause runtime error later.

<img width="1199" alt="image" src="https://user-images.githubusercontent.com/27538066/156111693-8167afa7-d29b-4c02-b5f5-e8c3ad287412.png">

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

we're closed to the end of b2205, so please help to take a look at this issue, and thx~

**Comment by unazko** [comment]
Hello @ksblklu,

I couldn't reproduce the error.
Is it reproducible in the playground samples: https://sap.github.io/ui5-webcomponents/master/playground/components/ResponsivePopover/?sap-ui-theme=sap_fiori_3&isrtl=false
or perhaps in the following snipped: https://codesandbox.io/s/cranky-sun-eqshte?file=/index.html
If not could you please edit the snipped so the issue will be reproducible and describe the steps you use to reproduce.

Best Regards,
Boyan

**Comment by ksblklu** [comment]
This issue fixed in ver.1.2.1, thanks.
