### ISSUE TITLE
ViewSettingsDialog: padding is wrong for header and footer

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#4838]
### **Bug Description**
The dynamic padding is added to the internally set padding of the bars.

### **Steps to Reproduce**
1. Go to [playground (master)](https://sap.github.io/ui5-webcomponents/master/playground/components/ViewSettingsDialog/?sap-ui-theme=sap_fiori_3&isrtl=false)
2. See that the padding of the header and footer are off.

### **Isolated Example**
https://sap.github.io/ui5-webcomponents/master/playground/components/ViewSettingsDialog/?sap-ui-theme=sap_fiori_3&isrtl=false

<img width="389" alt="image" src="https://user-images.githubusercontent.com/9749730/156191077-c98d079f-8401-47ec-b350-4d3db20b274c.png">

### **Context**
- UI5 Web Components version: 1.2.0

### **Priority**
- [x] Low
- [ ] Medium
- [ ] High
- [ ] Very High

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-b could check this issue please?

**Comment by Todor-ads** [comment]
This issue is fixed with this change: #4867
