### ISSUE TITLE
webcomponents-website: make search results scrollable

### ISSUE THREAD

**Issue by sammiee5311** [SAP/ui5-webcomponents#4857]
### **Feature Request Description**
- This is the result that I added `max-height: 40rem; overflow: auto;` to make it scrollable so that I can see all the results  <img width="435" src="https://user-images.githubusercontent.com/56215891/156772713-23c3d2b1-af5c-48ed-84ee-403a5c9bb630.png">
- This is the original result. As you can see that you cannot see more results because it does not support scroll.
- <img height="500" src="https://user-images.githubusercontent.com/56215891/156773151-ca126f5c-1bb6-4793-b75c-97ee6689a17f.png">

### **Proposed Solution**
Add css style (overflow and max height maybe ?) on div which is [`js-search-results search-results-wrap`](https://github.com/SAP/ui5-webcomponents/blob/c23757355c0dc1d36e24b7e6c272e3b897cf241a/packages/playground/_layouts/default.html#L18)

### **Priority**
- [x] Low
- [ ] Medium
- [ ] High
- [ ] Very High

**Comment by PetyaMarkovaBogdanova** [comment]
Hi colleagues from @SAP/ui5-webcomponents-team,
can you, please, take a look at this issue?

Best regards,
Petya Markova.
(UI5 Dispatcher)
