### ISSUE TITLE
[SF][Panel] Allow expand/collapse button customization with a slot

### ISSUE THREAD

**Issue by Neeeko** [SAP/ui5-webcomponents#4859]
### **Feature Request Description**
Currently, there's no way to override the behavior of the expand/collapse button of the ui5-panel, to add specific attributes like aria-label, or to set the focus on the expand/collapse button only.

### **Proposed Solution**
Allowing the customization of this button through a slot would be helpful. We could still keep the existing button by default, but using the slot would allow customization (using our own ui5-button).

### **Additional Context**
In a very specific use case, we need to set the focus and additional aria-attributes to this button, or add a "keydown" event listener on it which is not possible currently.

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: SuccessFactors

**Comment by PetyaMarkovaBogdanova** [comment]
Hi colleagues from @SAP/ui5-webcomponents-topic-rl,
can you, please, consider this enhancement request regarding **ui5-panel** ?

Best regards,
Petya Markova.
(UI5 Dispatcher)

**Comment by nikolay-kolarov** [comment]
Hello @Neeeko,

I am interested in more details about the use case.
Could you please give more details about this specific use case, so taht we know the big picture?

Thanks,
Nikolay

**Comment by nikolay-kolarov** [comment]
Hello @Neeeko,

We had a discussion today with @elenastoyanovaa on the issue.

We can offer two solutions:
There is already an API to set the accessible name of the panel, and the value will be announced on entering the panel region. Looking at your use case I think it makes sense if you set the accessible name to the title used inside, as it is valid for the whole panel. Could you please give this a try?

If you want to have the button explicitly labelled, there is a private property, which can be used to transfer the accessible name from the panel to the expand/collapse button - useAccessibleNameForToggleButton/use-accessible-name-for-toggle-button.
Unfortunately, this will result in duplicated announcement on the entering in the panel.
If you use this, it will be on your own risk and you need to check if it still works after an update.

For me, the first solution shall be already sufficient, therefore I am closing the item. Feel free to reopen it, if you need to discuss it further or if you have an update on the keyboard handling topic.

Best Regards,
Nikolay
