### ISSUE TITLE
[SF] List: Pressing "Enter" on a list item opens and immediately closes the dialog its supposed to open

### ISSUE THREAD

**Issue by Vir-Mittal** [SAP/ui5-webcomponents#4861]
### **Bug Description**
When using an interactive List inside a Popover and pressing "Enter" on a list item, the dialog that the list item was supposed to open is opened and then immediately closed. This does not happen with the "Space" key or a mouse click (the dialog is opened and remains open for the user to see).

### **Expected Behavior**
The dialog that the list item is supposed to open should be opened and should remain open.

### **Steps to Reproduce**
1. Go to https://codesandbox.io/s/list-within-popover-xx6nde?file=/src/App.js
2. Click the "Open Popover" button to open the popover with the list
3. Press "Enter" to select one of the list items
4. The dialog that was supposed to open is opened and then closed.
5. Try again with a mouse key or by pressing "Space"
6. The dialog remains open

### **Isolated Example**
https://codesandbox.io/s/list-within-popover-xx6nde?file=/src/App.js

### **Context**
- UI5 Web Components version: 1.2.1

**Comment by PetyaMarkovaBogdanova** [comment]
Hi colleagues,
can you, please, take a look at the reported issue, regarding ui5-popover?

Kind regards,
Petya Markova.
(UI5 dispatcher)

**Comment by dimovpetar** [comment]
Hello @Vir-Mittal ,

For short-term solution you can use `setTimeout` to bypass the issue https://codesandbox.io/s/list-within-popover-forked-mtvz90?file=/src/App.js
We have started implementing a general fix for the problem with #4975, but it will take some time until we come up with a good solution. 
Thank you for your patience!

Best regards,
Petar
