### ISSUE TITLE
[SF] ColorPalettePopover "More Colors" option - add a way to receive the color in hex format

### ISSUE THREAD

**Issue by Vir-Mittal** [SAP/ui5-webcomponents#4862]
### **Feature Request Description**
Currently, the "More Colors" option of the ColorPalettePopover returns the selected color in rgba format.

### **Proposed Solution**
Is it possible to add an option to return the color in hex format instead?

### **Proposed Alternatives**
Add a function to convert rgba to hex to the existing color conversion file - "@ui5/webcomponents-base/dist/util/ColorConversion.js";

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by PetyaMarkovaBogdanova** [comment]
Hi team,
can you, please, take a look at this enhancement request?
When a color is picked for "More colors" its value is returned as a string in RGB format. Can it be a possibility for the consumer
to configure this option?

Best regards,
Petya Markova.
(UI5 Dispatcher)

**Comment by ilhan007** [comment]
Hello @Vir-Mittal the issues is resolved with: https://github.com/SAP/ui5-webcomponents/pull/5493
and available since 1.6.0 (1.7.1 is the latest stable)
