### ISSUE TITLE
[SF][Input] - input suggestion does not pop up by calling Suggestions.open()

### ISSUE THREAD

**Issue by 2bno1** [SAP/ui5-webcomponents#4879]
### **Bug Description**
After upgrading to 1.2.x, calling `Suggestions.open()` does not trigger suggestions pop.

### **Expected Behavior**
input suggestions can pop up by calling `Suggestion.open()`

### **Steps to Reproduce**
1. Go to https://codesandbox.io/s/ui5-input-suggestion-mvt09k?file=/src/index.js
2. Focus to the input

### **Isolated Example**
https://codesandbox.io/s/ui5-input-suggestion-mvt09k?file=/src/index.js

### **Context**
- UI5 Web Components version: 1.2.1
- OS/Platform: macOS
- Browser: Chrome
- Affected component: ui5-input

### **Log Output / Stack Trace / Screenshots**
```

https://user-images.githubusercontent.com/1751846/157585293-d4cd2d7c-a65b-423d-a657-5cc75e269173.mov


```
### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

**Comment by PetyaMarkovaBogdanova** [comment]
Hi colleagues, 
can you, please, check that issue? The suggestions popover seems to be showing up with verison < 1.2.0 (codesample opened in a new window).

Kind regards,
Petya Markova.
(UI5 Dispatcher)

**Comment by nikolay-kolarov** [comment]
Hi @2bno1,

As discussed this is a private API, which we cannot guarantee to work stable or be available in general.

Therefore, I am closing this issue.

Best Regards,
Nikolay
