### ISSUE TITLE
[SF][1.2.1][F6Navigation][BUG] F6 navigation does not work on Windows 10

### ISSUE THREAD

**Issue by i323808** [SAP/ui5-webcomponents#4880]
### **Bug Description**
F6 navigation does not work on **Windows 10**. By the way, it works fine on Mac.

### **Expected Behavior**
F6 navigation is supposed to work on Windows 10.

### **Steps to Reproduce**
1. Go to https://codesandbox.io/s/f6-fast-navigation-dnwr1n?file=/src/App.js
2. Focus on "item 1"
3. Press F6
4. Focus will skip to the url bar of browser

### **Isolated Example**
https://codesandbox.io/s/f6-fast-navigation-dnwr1n?file=/src/App.js

### **Context**
- UI5 Web Components version: 1.2.1
- OS/Platform: **Windows 10**
- Browser: Chrome Version 99.0.4844.51 (Official Build) (64-bit)
- JAWS 2022

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by PetyaMarkovaBogdanova** [comment]
Hi team,
can you, please, take a look at that issue with f6 navigation?

Kind regards,
Petya Markova.
(UI5 Developer)

**Comment by i323808** [comment]
Hi @fifoosid ,

This issue is reproducible again with ui5-webcomponents version 1.4.0 due to https://github.com/SAP/ui5-webcomponents/issues/5110. Could you please reopen this issue?

Thanks,
Jane

**Comment by ilhan007** [comment]
The original fix https://github.com/SAP/ui5-webcomponents/pull/5188 has been reverted as it caused degradations in other components, so we need to find another solution.
