### ISSUE TITLE
The default behavior of `change`,`selection-change` events should be preventable

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#4883]
### **Feature Request Description**
It often happens that you need to control the `selected` state of selectable components programatically. Currently for many components it's not possible to fully control the state by the user which then needs a hacky workaround (especially with React) to achieve the desired behavior. 

Some examples are:

- asynchronously setting the selected state - e.g. waiting for a data call to be finished and then toggling the respective selected state according to the result (error/success) 
- making an item non selectable - e.g. because the user has no authorities to select an entry but he should still know that it's available
- an item should always be selected - e.g. in a multi-select scenario, an entry is mandatory and should therefore always be selected

[Here's](https://codesandbox.io/s/adoring-roman-3sthuq?file=/src/App.js) an example of a workaround I tried to implement, unfortunately it's still not working (which seems like a bug to me). And [here](https://codesandbox.io/s/stupefied-montalcini-l8lrf6?file=/src/App.js) you can find an example that shows how I would like it to be working.

### **Proposed Solution**
It should be possible that the default selection behavior of the `selection-change` event is preventable by calling `event.preventDefault()`. (Similar to https://github.com/SAP/ui5-webcomponents/issues/4700)

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: UI5 Web Components for React

**Comment by PetyaMarkovaBogdanova** [comment]
Hi colleagues,
can you, please, review this enhancement request for selected state of selectable controls and selection-change event?
Thank you!

Kind regards,
Petya Markova.
(UI5 Dispatcher)

**Comment by ilhan007** [comment]
Hello @Lukas742 the request makes sense. Some of the components already provide preventable events related to selection. I assume that we will start gradually making these events preventable for all relevant component.

Do you have some specific component in mind that you prefer to get the desired enhancement, so we can start from it?

**Comment by Lukas742** [comment]
Thanks @ilhan007. :)  It would be great if this enhancement could be implemented for the `List` (we are currently using a workaround for this) and the MultiComboBox (a user asked about this in [Slack](https://openui5.slack.com/archives/CSQEJ2J04/p1646935282760829)) first.

**Comment by C3ntraX** [comment]
Hello @ilhan007,

if the TabContainer would get this enhancement, it would be very nice. Currently if you want to prevent the user to select a tab for example, if he has unsaved data, than I have to use a workaround.

**Comment by ilhan007** [comment]
CheckBox's change also preventable:
- issue - https://github.com/SAP/ui5-webcomponents/issues/5957
- change https://github.com/SAP/ui5-webcomponents/pull/6553

**Comment by ilhan007** [comment]
- [ ] TabContainer `tab-select` preventable  https://github.com/SAP/ui5-webcomponents/pull/5661
- [ ] SideNavigation `selection-change` preventablehttps://github.com/SAP/ui5-webcomponents/pull/4732
- [ ] CheckBox `change` https://github.com/SAP/ui5-webcomponents/pull/6553
- [ ] Switch `change` https://github.com/SAP/ui5-webcomponents/issues/5953
- [ ] MultiComboBox https://github.com/SAP/ui5-webcomponents/issues/5725
- [ ] List `selection-change` https://github.com/SAP/ui5-webcomponents/issues/6589

**Comment by C3ntraX** [comment]
Hello @ilhan007,

can you add Select to the list? There we have the same case.

BR C3ntraX

**Comment by ilhan007** [comment]
Hi @C3ntraX added it to the list, but I will close this issue as separate issues are present.
