### ISSUE TITLE
ui5-switch does not read the accessibleName or accessibleNameRef 

### ISSUE THREAD

**Issue by lormanlau** [SAP/ui5-webcomponents#4893]
### **Bug Description**
Using the accessibleName and accessibleNameRef does not read when pressing the switch on or off or when focused.

### **Expected Behavior**
A clear and concise description of what you expect to happen.
switch component when focus should announce with description

### **Steps to Reproduce**
1. Click on or focus on the switch component

### **Isolated Example**
If possible, please provide an isolated example by forking [CodeSandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html).
https://codesandbox.io/s/wizardly-dawn-3ws4nl?file=/src/index.js

### **Context**
- UI5 Web Components version: 1.2.1
- OS/Platform: MacOS 12.2.1 and Windows 10
- Browser: Google Chrome Version 99.0.4844.51 (Official Build) (x86_64)
- Affected component: UI5-Switch

### **Log Output / Stack Trace / Screenshots**
![Screen Shot 2022-03-11 at 12 10 37 PM](https://user-images.githubusercontent.com/12117112/157952918-9f062419-7b9f-4312-a56d-932612509696.png)

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SAP SuccessFactors
- Bussiness impact: Medium

This issue is the same issue as #4147 but after the update

**Comment by unazko** [comment]
Hello @lormanlau,

Thank you for sharing this finding,
I would suggest to close the current incident and track the progress via https://github.com/SAP/ui5-webcomponents/issues/4887 as @ndeshev pointed out there are about the same issue.

Best Regards,
Boyan Rakilovski
