### ISSUE TITLE
ACC: UI5-Checkbox doesn't read the associated label required field information

### ISSUE THREAD

**Issue by dp1704** [SAP/ui5-webcomponents#4895]
### **Bug Description**
On accessing the UI5-Checkbox component, it doesn't read out the required field information for the associated label to check Box

### **Expected Behavior**
On accessing the checkbox, the associated label which is marked as required should convey the required field information to the user.

### **Steps to Reproduce**
2. Login to instance -> Select Learning from module switcher
3. Under My Learning Assignments, enter "Reserved Seat Item" as course name
4. Select the course -> Click on See all available classes -> Select the sponsored class Click on Register button
5. Start JAWS -> Navigate to checkboxes on the page and observe screen reader announcement

### **Isolated Example**
If possible, please provide an isolated example by forking [CodeSandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html).

### **Context**
- UI5 Web Components version: {[1.2.1]}
- OS/Platform: {windows 10}
- Browser: {Chrome}
- Affected component: {ui5-checkbox}

### **Log Output / Stack Trace / Screenshots**
```
{...}
```
### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by ndeshev** [comment]
Hello @dp1704 , 

Please remove the internal system URL and credentials from the issue, as this is a public repository. Moreover I did not succeed to navigate to the correct point in the app where the problem occurs.  Could you please provide an isolated example in codesandbox for example.

Thanks.

**Comment by dp1704** [comment]
Hello @ndeshev ,

my bad. Removed the internal URL. Please find below the sandbox link to replicate the issue mentioned above:
https://codesandbox.io/s/romantic-wind-jnwfk8?file=/index.html

Let me know if you have any questions.

Thank you,
Dhruti

**Comment by nnaydenow** [comment]
Hi @dp1704,

Seems that the reported issue is missing functionality. After sync with our team accessibility expert we decide to implement that property to ui5-checkbox.

For workaround until the implementation is ready you can set aria-required attribute to the custom element.

Regards,
Nayden

**Comment by nnaydenow** [comment]
Internal reference: BGSOFUIPIRIN-5670
