### ISSUE TITLE
Button: role="link" will be announcing as LINK as well as BUTTON

### ISSUE THREAD

**Issue by sleric1024** [SAP/ui5-webcomponents#4898]
**Describe the bug**
Cann't edit the role for Button component.
This issue comes from A11y expert from Successfactors.
The case that this button will directly navigate to different page, and it need to support to change the role to be a link.

**Isolated Example**
https://codesandbox.io/s/broken-thunder-5em8id?file=/src/App.js

**To Reproduce**
1. Go to https://codesandbox.io/s/broken-thunder-5em8id?file=/src/App.js
2. Open NVDA
3. The button will be read as **button** and **link**

**Expected behavior**
if set as role="link", then only link will be read by screen readers

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.2.1
`@ui5/webcomponents-react` version: 0.22.2
Operating System: Windows
Browser: Chrome

**Additional context**
I am from Successfactores.

**Comment by ilhan007** [comment]
FYI @SAP/ui5-webcomponents-topic-b
