### ISSUE TITLE
ui5-bar slot content does not resize upon innerHTML changes

### ISSUE THREAD

**Issue by lormanlau** [SAP/ui5-webcomponents#4901]
### **Feature Request Description**
A clear and concise description of what feature is missing.
Is your feature request related to a problem? Please describe.
We are loading in translated messages for the content of the bar but after the content loads, the messages get truncated even though there is space in the bar element. 
https://codesandbox.io/s/ui5-webcomponents-forked-ydgntj?file=/src/index.js

### **Proposed Solution**
A clear and concise description of the solution you would like to have.
Have the handleResize() get called after the innerHTML element changes.

### **Proposed Alternatives**
Remove the slots extra when not in use.

### **Additional Context**
Add other context or screenshots related to the feature request here.
<img width="2032" alt="Screen Shot 2022-03-15 at 10 20 39 AM" src="https://user-images.githubusercontent.com/12117112/158435062-dee0ad5d-9a60-434b-8b1e-bf0c75863a39.png">

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: SAP SuccessFactors
- Business impact: Medium

**Comment by ndeshev** [comment]
Hello @lormanlau,

In the official documentation of the component is stated the following:

> The default slot will be centered in the available space between the startContent and the endContent areas, therefore it might not always be centered in the entire bar.

I will dispatch the issue to the dev team to further look into it and propose eventual solution or workaround.

Hello @SAP/ui5-webcomponents-topic-b,
When the content inside the `ui5-bar `component is changed programmatically the containing slot does not get resized to fit it.

Kind regards,
Nikolay

**Comment by petyabegovska** [comment]
Hi @lormanlau , 

The feature is implemented.

Cheers,
Petya
