### ISSUE TITLE
DateTimePicker: Shows false hours when open picker

### ISSUE THREAD

**Issue by dimalapeto** [SAP/ui5-webcomponents#4907]
**Describe the bug**
`DateTimePicker` component shows wrong hours (not for my timezone) when I open picker. But when I click to minutes or seconds inputs - hours input changes to real current hour value.

**Isolated Example**
Can not be provided

**To Reproduce**
1. Click on `Open picker` of `DateTimePicker` input
3. Picker opens
4. See current year, month, day, minutes, seconds but hour's value is wrong.

**Expected behavior**
Should show all values be equal to current user's time on the opening picker moment.

**Screenshots**
Current time is 12:59:26 PM 16 of March 2022 (on screenshot making moment)
![image](https://user-images.githubusercontent.com/18643415/158585240-ca9d640f-fb8b-498f-9b77-e3e1e8f04a8d.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: "1.0.0-rc.15"
`@ui5/webcomponents-react` version: "0.18.11"
Operating System: Windows 10 Pro 21H1 OS build 19043.1526
Browser: Google Chrome Version 99.0.4844.51 (Official Build) (64-bit)

**Additional context**
I can send screen recording in private messages.

**Comment by ndeshev** [comment]
Hello @dimalapeto 

I can't reproduce the issue on `DateTimePicker ` sample and context.
Can you provide more details about the case or some kind of similar isolated example?

Can you check if the problem occurs in the latest UI5 WebComponents version? (1.2.1)
Also, can you try switching the environment and see if the issue persist, for example, if you've observed it on localhost - to see it on a remote host?

Kind Regards,
Nikolay

**Comment by dimalapeto** [comment]
I have screen recording but I can't share it here because of NDA, but I can send you that recordings. Just give me the address.
I tried the latest UI5 WebComponents version (1.2.1) but it doesn't work for me.
The same problem on remote host (SAP DXP, Linux Ubuntu).

**Comment by gmkv** [comment]
Hi @dimalapeto 

If possible, please extend [this sample](https://codesandbox.io/s/ui5-webcomponents-forked-2mc6ds?file=/index.html) with something that resembles your case - for example, add any relevant event listeners and element attributes.
I've set it to version 1.0.0-rc15, but also try it with the very last release.
What's the locale in the OS on your machine?
Have you set a [configuration](https://sap.github.io/ui5-webcomponents/playground/advanced/configuration/)?

My email is georgi [dot] minkov [at] sap.com.

**Comment by stbodurov** [comment]
Hi @dimalapeto,

Just checking in whether you tried extending [the sample](https://codesandbox.io/s/ui5-webcomponents-forked-2mc6ds?file=/index.html) to match the use case of your app.

Could you check if the issue persists for you on the latest development: https://sap.github.io/ui5-webcomponents/master/playground/components/DateTimePicker/

As requested above, please let us know what the locale of your OS is and whether you have a [configuration](https://sap.github.io/ui5-webcomponents/playground/advanced/configuration/)?

Regards,
Stanislav

**Comment by ilhan007** [comment]
Hi @dimalapeto,
we are closing the issue due to inactivity, but feel free continue the discussion and we will re-open it.
