### ISSUE TITLE
Not able to use keyboard to activate help button on input component

### ISSUE THREAD

**Issue by leandrostavares** [SAP/ui5-webcomponents#4908]
### **Bug Description**

The input component in UI5 provides a attibute called **showValueHelp** that attaches a help button to the input:

![Screen Shot 2022-03-16 at 13 16 32](https://user-images.githubusercontent.com/20496510/158636899-7c296cac-cca3-4657-8cc7-91273c6f34d4.png)

This button needs to be focusable when navigating using "tab" key and should be activated when the user presses the "enter" key.

Currently this is configuring a UX compliance issue because users in need of screen readers have no way to execute the generated button.
 
### **Expected Behavior**
Users navigating through screen reader needs to able to execute the help button using only the keyboard.

### **Steps to Reproduce**
1. Here is a working example from documentation https://sap.github.io/ui5-webcomponents/playground/components/Input/
2. Go to **Input With Value Help Dialog** session
3. Click in the input and press tab key. 

The focus will not be set to the help buttom making impossible to open the dialog suggestions without a mouse

### **Context**
- UI5 Web Components version: sap.ui.version : 1.84.8
- OS/Platform: Macos Monterey 12.2.1
- Browser: chrome
- Affected component: ui5-input

### **Priority**
- [  ] Low
- [  ] Medium
- [x] High
- [  ] Very High

**Comment by ndeshev** [comment]
Hello @leandrostavares

I'm assigning the issue to the responsible team for implementation of the desired functionality.

Kind regards,
Nikolay

**Comment by leandrostavares** [comment]
Thanks @ndeshev !

**Comment by ndeshev** [comment]
Hi again @leandrostavares

Just want to further clarify, we will add F4 and Alt+Down key handling, as they are defined by our specifications.

That means the value help will be opened when pressing these key combinations, while the focus is on the input field. However, there will be no tab stop (focus) on the value help icon itself. 

Regards,

Nikolay

**Comment by hristop** [comment]
Hi @leandrostavares ,

After internal discussion in the team, we suggest that you use the ui5-multiinput component, which already has value help icon and the possibility to either add the text as token or leave it as text. 

As all the needed keyboard handling and eventing is there we do not believe that the same is needed in the ui5-input, thus we are closing this request.

Best Regards,
Hristo
