### ISSUE TITLE
[TextArea] - text in input field is not vertically centered (rows: 1; growingMaxLines:1; showExceededText:true; contentDensity:Compact)

### ISSUE THREAD

**Issue by rchrdchn** [SAP/ui5-webcomponents#4909]
### **Bug Description**
- text in input field is not vertically centered when there is only one line of text.
- scroll bar showing up

### **Expected Behavior**
text in input field to be vertically centered when there is only one line of text

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents-react/?path=/story/inputs-textarea--default-story&args=valueState:!undefined;required:true;maxlength:100;rows:1;growingMaxLines:1;showExceededText:true;growing:false&globals=theme:sap_horizon;contentDensity:Compact

### **Context**
- UI5 Web Components version: _latest_
- OS/Platform: _MacOS_ (not sure if Windows as well)
- Browser: _Chrome, Firefox, Safari_
- Affected component: _TextArea_

### **Log Output / Stack Trace / Screenshots**
![Screen Shot 2022-03-16 at 14 34 58](https://user-images.githubusercontent.com/11576789/158695742-45c25910-8074-40e1-8d77-1728f7a22f50.png)
![Screen Shot 2022-03-16 at 14 47 31](https://user-images.githubusercontent.com/11576789/158696699-e50cbf9f-65a1-4150-b318-87e5c5a2326f.png)
![Screen Shot 2022-03-16 at 15 26 27](https://user-images.githubusercontent.com/11576789/158701685-8c571993-a6ee-40c5-89e8-5e11378c08a1.png)

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - Low
- Accessibility issue - Medium
- Functional issue - Medium
- Visual issue - Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: _SuccessFactors_

Previous issue for ref: https://github.com/SAP/ui5-webcomponents/issues/4623

**Comment by ndeshev** [comment]
Hello team @SAP/ui5-webcomponents-topic-rl

When the `ui5-textarea` component is set to rows="1" the scrollbar is always displayed.
Also, the text is not vertically aligned on some themes and densities.

Kind regards,
Nikolay

**Comment by rchrdchn** [comment]
Hi team - following up on this issue. Any updates?

**Comment by ivoplashkov** [comment]
Hello,

Sorry for the delayed response and thank you for your patience!

Unfortunately we seem to have more a complex issue in the core of the component that requires a DOM structure refactoring and will be handled in a separate issue. You can track the progress here - #4512 

Best regards,
Ivaylo

**Comment by hristop** [comment]
Hi @rchrdchn ,

As mentioned by @ivoplashkov , we have targeted this for refactoring and will handle the issue with it.
I am closing the incident, please continue monitoring the progress on the topic here - #4512 

Best Regards,
Hristo
