### ISSUE TITLE
[SF][CustomListItem] Incorrect focus when Input is rendered in Custom List Item

### ISSUE THREAD

**Issue by Neeeko** [SAP/ui5-webcomponents#4916]
### **Bug Description**
When rendering a ui5-input inside a ui5-li-custom, the focus is displayed around both the input and the list item while it should be displayed on the input only.

![Screenshot 2022-03-17 at 17 03 58](https://user-images.githubusercontent.com/7316793/158842599-f6448498-1775-4c68-bae9-5f2e8eb030ad.png)

### **Expected Behavior**
Using the above screenshot as an example, when navigating using keyboard on a list with custom list items, the focus should first go to the list item, then when pressing TAB the focus should move to the "Test" button, and then to the input. The focus should only be displayed around the input but not the list item.

### **Steps to Reproduce**
1. Go to https://codesandbox.io/s/ui5-webcomponents-forked-c79y60?file=/index.html
2. Press TAB. The focus will go to the custom list item which is fine
3. Press TAB again. The focus will got to the button, which is fine
4. Press TAB one last time. The focus will go around both the list-item and the ui5-input which is incorrect

### **Context**
- UI5 Web Components version: 1.2.1
- OS/Platform: MacOS
- Browser: Chrome
- Affected component: ui5-li-custom

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SuccessFactors

**Comment by ndeshev** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

There is a duplicated focus when `ui5-input` is placed within a custom list item. It is reproducible with both keyboard navigation and mouse click.

Kind Regards,
Nikolay

**Comment by rchrdchn** [comment]
Hi team – the double focus issue is also happening when using the `AvatarGroup` component inside a `CustomListItem` component.

![Screen Shot 2022-03-21 at 14 42 56](https://user-images.githubusercontent.com/11576789/159368750-2134201f-8f00-491b-a9e1-c81bab397f8e.png)

Similar description, expected behavior, and steps to reproduce as above.

**Sandbox**
https://codesandbox.io/s/ui5-webcomponents-forked-9pw9cy?file=/index.html

**Comment by nnaydenow** [comment]
Hi @rchrdchn ,

I have just tested and the issue will be fixed with the linked pull request.

Regards,
Nayden
