### ISSUE TITLE
The 'change' event of TimePicker  is not fired if input by keyboard 

### ISSUE THREAD

**Issue by yaosheng79** [SAP/ui5-webcomponents#4918]
### **Bug Description**
change event should be fired when the text in the input field has changed and the focus leaves the input field.
but it is not fired, no matter press enter or lose focus after entering

### **Expected Behavior**
Key in new value into the TimePicker filed, then press enter or lose focus should trigger the change event

### **Steps to Reproduce**
1. test-resources/pages/TimePicker.html
2. in the TimePicker of 'Test "change" event' section, key in a new time
3. press enter or lose focus
nothing happen

### **Isolated Example**
test-resources of this repo is good enough to reproduce

### **Context**
- UI5 Web Components version: {...}
- OS/Platform: {...}
- Browser: {...}
- Affected component: {...}

### **Log Output / Stack Trace / Screenshots**
```
{...}
```
### **Priority**
- [ ] Low
- [] Medium
- [x] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {MOB-MDK-MDC-WEB}
- Business impact: {...}

**Comment by ndeshev** [comment]
Hello @SAP/ui5-webcomponents-topic-b,

When the time is updated without opening the picker and "Enter" key is pressed, or the input is focused out, change event is not fired.

Kind Regards,
Nikolay
