### ISSUE TITLE
Input: When input type is number and value is float, hitting backspace, cursor jumps forward to the beginning of value.

### ISSUE THREAD

**Issue by gurkirpalgill** [SAP/ui5-webcomponents#4932]
**Describe the bug**
For component, `Input` when attribute type is Number, Enter a float value e.g. 65.6 , press backspace, it deletes .6 but cursor jumps forward to the beginning of the value.
I also noticed sometimes double clicking just after the number auto increments/decrements the number as if user is pressing up/down arrow keys. This happens randomly and is not reproducible consistently.

**To Reproduce**
1. Go to 'https://sap.github.io/ui5-webcomponents-react/?path=/story/inputs-input--default-story&args=type:Number;valueState:!undefined'
2. Enter  '65.6'
3.Hit backspace
4. Cursor jumps forward to beginning.

**Expected behavior**
It should stay after 65

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.2.1
`@ui5/webcomponents-react` version: 0.22.1
Operating System: Mac OS
Browser: Chrome

**Comment by gmkv** [comment]
Hi @SAP/ui5-webcomponents-topic-rl 

Would you have a look at this? 
It seems like a fair assessment that deleting text within the input is inconsistent.
Please also check how the input handles deleting text in Firefox.
Additionally, for me, entering `123,12` and pressing backspace once deletes the whole string, while entering `123.12` deletes only one character.

Regards,
Georgi

**Comment by BennyHuang** [comment]
Hi team, what's the plan to fix it?
