### ISSUE TITLE
Button: `accessibilityAttributes` are applied to all `ui5-button` components

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#4933]
### **Bug Description**
When setting `accessibilityAttributes` to a single `ui5-button`, the shadow root `buttons` of all `ui5-buttons` receive these attributes as well.

### **Expected Behavior**
Only the button where the attributes are applied should receive them.

### **Steps to Reproduce**
1. Go to [codeSandbox](https://codesandbox.io/s/ui5-webcomponents-forked-lkeqp2?file=/src/index.js)
2. Open dev tools
3. Inspect the first button and navigate inside its shadow root to the native button element
4. See that the aria attributes `hasPopup` and  `expanded` are set --> expected
5. Inspect the shadow root button of the second `ui5-button`
6. See that the aria attributes are set as well --> wrong

### **Isolated Example**
https://codesandbox.io/s/ui5-webcomponents-forked-lkeqp2?file=/src/index.js

### **Context**
- UI5 Web Components version: 1.2.1

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: UI5 Web Components for React
- Business impact: Screen readers currently make false announcements of the [ActionSheet](https://sap.github.io/ui5-webcomponents-react/?path=/docs/modals-popovers-actionsheet--default-story) action buttons because of that.

**Comment by gmkv** [comment]
Hi @SAP/ui5-webcomponents-topic-b 

There's an a11y issue with the Button and Link components.
Definining the accessibilityAttributes property on one instance of a Button will also result in other buttons on the page to have that same value for accessibilityAttributes, when the other buttons don't have it defined.

To reproduce:
1. See the following [sample](https://codesandbox.io/s/ui5-webcomponents-forked-rprrrx?file=/index.html) and inspect the DOM.
2. All four of the rendered components will have accessibilityAttributes rendered but only two of them have such prop defined.

Regards,
Georgi

**Comment by ilhan007** [comment]
Hello @Lukas742 

we discussed the issue, it is reproducible, but we consider it misuse of the API.
The properties from type: Object, as the **accessibilityAttributes** should be used as follows, e.g. assigning a new object, 
```js
btn.accessibilityAttributes = {expanded : true};
```

This should avoid the described issue and will actually invalidate the component at any point of time (while the btn.accessibilityAttributes.expanded syntax would not cause invalidation and take effect after the initial rendering of the component). Perhaps it's a good idea to add a note to these kind of properties to explicitly describe how it's supposed to be used.

Anyway, do you have any problems with this syntax?
```js
btn.accessibilityAttributes = {expanded : true};
```

Best Regards,
ilhan

**Comment by Lukas742** [comment]
Hi @ilhan007 

I wasn't aware of that, thanks for pointing this out. Yes, a note about these implementation details would be very helpful in my opinion.

I have tested the syntax you provided and it works as expected 👍.
