### ISSUE TITLE
[ui5-date-picker] Does not pass Axe test

### ISSUE THREAD

**Issue by allen138** [SAP/ui5-webcomponents#4946]
### **Bug Description**
ui5-date-picker does not pass axe test. (Caused by https://github.com/SAP/ui5-webcomponents/pull/4706)

### **Expected Behavior**
date picker should pass axe test out of the box.

### **Steps to Reproduce**
1. Go to either playground or code sandbox and run axe.

### **Isolated Example**
[CodeSandbox](https://codesandbox.io/s/ui5-webcomponents-forked-c42791?file=/index.html).

### **Log Output / Stack Trace / Screenshots**
![image](https://user-images.githubusercontent.com/38701667/159593033-97c6080c-5801-40ae-8ca7-35277d46968d.png)

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SF
- Business impact:  Medium

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-b this is a known issue. Could you process it and close it with a statement.

**Comment by unazko** [comment]
Hello @allen138 and @ilhan007,

The mentioned aria-expanded attribute is no longer rendered into the ui5-datepicker DOM after the following PR:
https://github.com/SAP/ui5-webcomponents/pull/4866

However there are still some open questions regarding other aria-attributes like aria-controls, which is also flagged by the
AXE tool to be not in place as ui5-datepicker input is no longer considered a combobox element.

There is an ongoing discussion about this topic, which would result in accessibility specification update.
After the specification is updated we can adjust the invalid attributes so there is AXE tool reports for inaccurate DOM.

Expect updates soon.

Best Regards,
Boyan Rakilovski
