### ISSUE TITLE
[ui5-date-picker] Initial value get changed to empty string

### ISSUE THREAD

**Issue by allen138** [SAP/ui5-webcomponents#4958]
### **Bug Description**
Hi team,
When testing v1.2.3, I noticed if the date picker has an initial value, the input will display the placeholder instead of the value and the value will gets changed to empty string. This happens in the `onBeforeRendering` function when trying to normalize the value. Please see [pr 4693](https://github.com/SAP/ui5-webcomponents/commit/ec028556548fcef3d13fd5bfffa68f27c33768a3#diff-fa14cf5f431c3b7f2b565253b4e95d838bbef5c183281e1252f64cd204c808c3R418)

Thanks,
Allen

### **Expected Behavior**
The value should be respected and not replaced with an empty string. If there is a value it should display in the input field instead of the placeholder.

### **Steps to Reproduce**
https://codesandbox.io/s/ui5-webcomponents-forked-zbe00c?file=/index.html

![image](https://user-images.githubusercontent.com/38701667/160018823-c553c748-f170-4c7c-a5e0-b5044b075a5f.png)

before normalize...
![image](https://user-images.githubusercontent.com/38701667/160016552-35327a21-4ded-40e7-b790-3f607b9b4423.png)

after normalize...
![image](https://user-images.githubusercontent.com/38701667/160016669-760cad18-76aa-4537-bf57-74f69696cbb3.png)

### **Context**
- UI5 Web Components version: v >= 1.2.2

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SF
- Business impact: High

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-b could you look at the issue

**Comment by unazko** [comment]
Hello @allen138,

Thank you for sharing this finding,
you are absolutely right. Users should be able to set an invalid value to the ui5-date-picker.
Currently during the normalization of the value as you correctly pointed out the value gets clear if
the internal formatter wasn't able to parse it.
This issue should be fixed once the following PR gets merged:
https://github.com/SAP/ui5-webcomponents/pull/4967

Best Regards,
Boyan Rakilovski

**Comment by allen138** [comment]
Thanks @unazko , for a quick response. Just to point out that it does not necessarily have to be an invalid value. In some scenarios you may have the format-pattern coming from an i18n message bundle which needs to get fetched from a server, which will cause the initial format-pattern to fallback to the default (I believe its 'medium'), while the date string that has been passed in is already in the correct format for the pattern being fetched from the i18n bundle.
