### ISSUE TITLE
[ui5-date-time-picker] does not display dual calendar

### ISSUE THREAD

**Issue by allen138** [SAP/ui5-webcomponents#4959]
### **Bug Description**
The date pickers support dual calendars, but the hbs for the date time picker has not been updated with the `secondary-calendar-type` property and its value. Please see: [DateTimePickerPopover.hbs#L17-L35](https://github.com/SAP/ui5-webcomponents/blob/v1.2.1/packages/main/src/DateTimePickerPopover.hbs#L17-L35). 

### **Expected Behavior**
Date time picker should support dual calendar

### **Context**
- UI5 Web Components version: all
- Affected component: ui5-date-time-picker

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SF
- Business impact: High

**Comment by gmkv** [comment]
Hi @SAP/ui5-webcomponents-topic-b 

The DateTimePicker's property secondaryCalendarType does not work.
The property is described in the [documentation](https://sap.github.io/ui5-webcomponents/playground/components/DateTimePicker/) but setting it to any value has no effect.
