### ISSUE TITLE
Link open twice with href="#" when hitting enter on @ui5/webcomponents-react": "0.22.2",

### ISSUE THREAD

**Issue by kilgharsap** [SAP/ui5-webcomponents#4963]
### **Bug Description**
On this version of <Link />, when this Link has herf="#", and when pressing Enter key after the link is focused, it trigger click event twice. 

This issue doesn't happen on "@ui5/webcomponents-react": "~0.131.22",

### **Expected Behavior**
the link should be only alert once/ open target once 

### **Steps to Reproduce**
**Link instance has href="#"**
1. Go to ['https://iutyp6.csb.ap](https://iutyp6.csb.app/) 
2. focus on first link "Link opens with twice when Enter is pressed", hit enter key on keyboard, notice alert twice.
**Link instance doesn't have href="#"**
1. Go to ['https://iutyp6.csb.ap](https://iutyp6.csb.app/) 
2. focus on first link "Link opens with twice when Enter is pressed", hit enter key on keyboard, notice alert once as normal behavior 
### **Isolated Example**
If possible, please provide an isolated example by forking [CodeSandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html).

### **Context**
UI5  Link component : @ui5/webcomponents-react": "0.22.2",
- OS/Platform: {...}
- Browser: {...}
- Affected component: {...}](https://codesandbox.io/s/wonderful-leaf-iutyp6?file=/src/App.js)

### **Log Output / Stack Trace / Screenshots**
```
{...}
```
### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by MarcusNotheis** [comment]
Sandbox using plain UI5 Web Components: https://codesandbox.io/s/muddy-hill-f9frw7?file=/src/App.js

**Comment by gmkv** [comment]
Hi @SAP/ui5-webcomponents-topic-b 

There's an issue with the Link component where pressing enter will result in the click event being fired twice.

Regards,
Georgi
