### ISSUE TITLE
ui5-button width changes due to icon size difference

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents#498]
**Describe the bug**
The ui5-button grows a little in active/pressed state, caused by the different size of its active icon.

**To reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/ToggleButton/
2. Press the buttons in the "ToggleButton with Active Icon" section

**Comment by MapTo0** [comment]
as the `active-icon` property is removed I am closing this.
