### ISSUE TITLE
[SF][ui5-textarea] ValueState is displayed over the input with Horizon theme

### ISSUE THREAD

**Issue by Neeeko** [SAP/ui5-webcomponents#4986]
### **Bug Description**
The value state popup of the ui5-textarea is displayed over the border of the text area when using SAP Horizon theme.
<img width="392" alt="Screenshot 2022-03-30 at 15 51 54" src="https://user-images.githubusercontent.com/7316793/160850880-0525a0c5-1c1a-4de8-a42f-2a9fd769f6d4.png">

This is not the case when using the ui5-input:
<img width="246" alt="Screenshot 2022-03-30 at 15 23 46" src="https://user-images.githubusercontent.com/7316793/160845038-db2a4ff4-f189-42d3-95c7-7040a7cc7f8f.png">

**Expected behavior**
The value state message should be displayed below the ui5-textarea border, same as the ui5-input.

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/TextArea/?sap-ui-theme=sap_horizon&isrtl=false
2. On the second text area "TextArea with Maximum Length", enter more than ten characters
3. Notice that the value state message is misplaced.

### **Context**
- UI5 Web Components version: latest
- OS/Platform: MacOS
- Browser: Chrome
- Affected component: ui5-textarea

**Comment by Lukas742** [comment]
Thanks for reporting! I'll forward this issue to our UI5 Web Components Colleagues as the affected component is developed in their repository.

**Comment by Neeeko** [comment]
@Lukas742 You're right, sorry I tested using the ui5-input instead of the ui5-textarea.. I'll refine the description accordingly

**Comment by ilhan007** [comment]
@SAP/ui5-webcomponents-topic-rl could you check the value state popover placement, it shows over the bottom border as described in the issue and can be reproduced with the latest development https://sap.github.io/ui5-webcomponents/master/playground/components/TextArea/?sap-ui-theme=sap_horizon&isrtl=false

**Comment by jatinthaker** [comment]
Is the fix already available, if so what version of UI5WC?

**Comment by ilhan007** [comment]
> Is the fix already available, if so what version of UI5WC?

Hi @jatinthaker, the issue is still open, so I assume it's not fixed.

**Comment by jatinthaker** [comment]
> > Is the fix already available, if so what version of UI5WC?
> 
> Hi @jatinthaker, the issue is still open, so I assume it's not fixed.

Thanks @ilhan007, so in what UI5 version are we expecting the fix?

**Comment by nikolay-kolarov** [comment]
Hi @jatinthaker,

Although it looks like a small visual glitch the issue is not so trivial. We will need to refactor the dom structure of the component in order to solve this and several other issues.
We are currently looking in to this, but as this is a bug we cannot estimate how much it would take. Once we have more clarity we will update the issue.
Thanks for the understanding!

Best Regards,
Nikolay
