### ISSUE TITLE
ui5-tabcontainer: Highlight tab when hovered over.

### ISSUE THREAD

**Issue by Bilal3120** [SAP/ui5-webcomponents#4995]
### **Feature Request Description**
Request to highlight tabs when hovered over.

### **Proposed Alternatives**
Tab is highlighted only when we click it. Can we also have similar highlight when we hover over the tabs.

### **Additional Context**
Code sandbox - https://codesandbox.io/s/agitated-rgb-c8yrbv?file=/src/App.js

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

**Comment by tsanislavgatev** [comment]
Hello colleagues,

The behaviour can be inspected here: https://sap.github.io/ui5-webcomponents/playground/components/TabContainer/
We don't have any indication on hover.
But in openui5 we do: https://ui5.sap.com/#/entity/sap.m.TabContainer/sample/sap.m.sample.TabContainer

Can you please inspect the issue?

Best Regards,
Tsani

**Comment by gmkv** [comment]
FYI @SAP/ui5-webcomponents-topic-rd
