### ISSUE TITLE
Rework the hbs to lit compiler

### ISSUE THREAD

**Issue by vladitasev** [SAP/ui5-webcomponents#4997]
A lot of technical debt has accumulated in the hbs compiler.

TODO:
 - merge the `hbs2lit` and `hbs2ui5` libs (currently there is not enough logical separation to justify the existence of both)
 - delete unneeded files, rename files that end with `2`
 - overall restructure the code and improve readability
 - document better
 - enforce `eslint` and improve code quality
 - write tests

Eventually, even make this a standalone package in our repo with its own lifecycle and test system. Don't burden the tools package with this extra complexity and dependencies.

**Comment by vladitasev** [comment]
Fix the bug with `../` giving the root context instead of the one-level-up context.
Implement `@root` for getting the root context

**Comment by ilhan007** [comment]
We have replaced hbs templates in favour of TSX templates, so the current issue is not relevant anymore. We will keep the hbs to lit tooling for compatibility and remove it at some point
