### ISSUE TITLE
Selectoption with additionalText

### ISSUE THREAD

**Issue by C3ntraX** [SAP/ui5-webcomponents#4999]
### **Feature Request Description**
In OpenUI5 the Selectoption component has the property "additionalText". This property is missing in the component Option as part from the Select component. Similar components already have this property MultiComboBoxItem for example.

### **Proposed Solution**
Implement the "additionalText" property for the Option component to achieve the same properties for all components that include a dropdown to select one or more options.

### **Proposed Alternatives**
The questions is, how to display additional text information in an Option component.

### **Additional Context**
Add other context or screenshots related to the feature request here.

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by tsanislavgatev** [comment]
Hello colleagues,

Can you please review this improvement request?

Best Regards,
Tsanislav

**Comment by nnaydenow** [comment]
Internal reference: 5676
