### ISSUE TITLE
Filterbar with custom content

### ISSUE THREAD

**Issue by C3ntraX** [SAP/ui5-webcomponents#5000]
### **Feature Request Description**
The FilterBar component as an toolbar is nice, but it lacks in term of customization. 
The FilterBar takes up the space of a fully customizable toolbar. If you want to add additional clickable icons or text buttons, you have to define an additional toolbar. However, this takes up too much space overall, so that a search input with the customized components in the additional toolbar has to be combined in a single toolbar.

### **Proposed Solution**
The FilterBar component should have an additional property to add custom items to the toolbar. This items should be before or after the buttons on the right side. Maybe we need an additional property for this. In terms of missing space, the buttons should have an alternative presentation as icons.

### **Proposed Alternatives**
The question is how to avoid multiple toolbars in a column. That can be solved by combining the toolbars.

### **Additional Context**
Add other context or screenshots related to the feature request here.

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: Versino AG
- Business impact: {...}

**Comment by tsanislavgatev** [comment]
Hello @C3ntraX,

Can you please specify about which component you are proposing an enhancement?
In the full list of WebComponents we don't have a FilterBar component: https://sap.github.io/ui5-webcomponents/playground/components

Best Regards,
Tsanislav

**Comment by C3ntraX** [comment]
Hello @tsanislavgatev,

sry my fail. I work with react and have referenced the wrong component.
https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-filterbar--default-story.

So this topic is wrong listed, it should listed in the other repository.

Thank you for the advice.
Lg

**Comment by tsanislavgatev** [comment]
Hello @C3ntraX,

I will close the issue here then.

Thanks and Best Regards,
Tsanislav
