### ISSUE TITLE
findNodeOwner returns wrong result

### ISSUE THREAD

**Issue by vladitasev** [SAP/ui5-webcomponents#5001]
1. Open: 
http://localhost:8081/test-resources/pages/ViewSettingsDialog.html
2. Click the 3rd button (Show filter only ....)
3. Click any item from the list (f.e. Filter 2)

See the console:
AriaLabelHelper.js:27 Uncaught TypeError: Cannot read properties of undefined (reading 'querySelector')
    at AriaLabelHelper.js:27:25

The problem is that `findNodeOwner` returns the `ui5-dialog` instance instead of the document.

**Comment by nnaydenow** [comment]
Hi @vladitasev,

Seems that the findNodeOwner was replaced with its native alternative in this change #5520.
