### ISSUE TITLE
[Feature Request][Topic B] implement SAP Horizon theme family

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents#5009]
### **Feature Request Description**
Implement SAP Horizon updates and introduce SAP Horizon Dark, HCW and HCB themes

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

### **Components**

- [x] Button
- [x] Bar
- [x] Calendar 
- [x] Color Palette
- [x] Color Palette Popover 
- [x] Color Picker 
- [x] Date Picker
- [x] Date Range Picker
- [x] Date Time Picker 
- [x] Dynamic Side Content 
- [x] File Uploader
- [x] Link
- [x]  Menu
- [x] Segmented Button 
- [x]  Split Button
- [x] Step Input 
- [x] Switch 
- [x] Time Picker
- [x] Timeline 
- [x] Toggle Button

**Comment by petyabegovska** [comment]
Horizon implementation is completed. After linking all PRs, I will close the issue.
