### ISSUE TITLE
Implement something like InfoLabel from sap.tnt library

### ISSUE THREAD

**Issue by Smux** [SAP/ui5-webcomponents#501]
**Is your feature request related to a problem? Please describe.**
Currently there is no option to display status labels like it was provided in the sap.tnt library with the InfoLabel control

**Describe the solution you'd like**
It would be great to have the InfoLabel (or something similar) available within ui5 webcomponents. An example can be seen here:
![image](https://user-images.githubusercontent.com/19520637/58794086-b0bb6c00-85f7-11e9-9926-bc7df0eb1b7d.png)

The InfoLabel could display 9 different colors. To think about future use cases it would also be great to assign a custom color.

The color of the text (black/white) should be dependent on the background color.

**Comment by ilhan007** [comment]
Hello @Smux we merged a new component ui5-badge, which incorporates the design of the InfoLabel you referred to. The component would be part of the next release 0.12.0.

Preview is already available: https://sap.github.io/ui5-webcomponents/playground/components/Badge/

Best,
ilhan
