### ISSUE TITLE
[SF][1.2.1][ui5-table]Expecting ui5-table to have 12px border radius

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents#5010]
### **Feature Request Description**
UX designer found ui5-table has no border-radius, which is not consistent with wiki and ui5 documentation(will provide these links separately). Please update ui5-table accordingly. Thanks

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

Web Experience Shanghai team

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-rl 
I know that the SAP Horizon implementation is underway, we have updated specs or we wait for updates, so I don't know if the border-radius has been specified earlier and this is a bug, or this is something new and just not implemented yet. 
Anyway, please keep in mind this note from our stakeholders and make sure the border-radius has the correct value.

**Comment by ilhan007** [comment]
Related to: https://github.com/SAP/ui5-webcomponents/issues/5007

**Comment by ilhan007** [comment]
And, If the border-radius is coming with the newest specs, you can close the issue and point the author to the following issue: https://github.com/SAP/ui5-webcomponents/issues/5007.

**Comment by elenastoyanovaa** [comment]
Hello @sfsf-xweb-sh ,

The specification wiki does not specify that the table should be rounded. I have provided more information with exact wiki chapters included. The rounded borders are applied to the Table Header and the Table Footer. The ui5-table component currently does not have a table header, nor a table footer. The only thing available is a Column Header, which by specification should not have rounded borders. 

Kind Regards,
Elena
