### ISSUE TITLE
Label for radio button group not read in screen reader (accessibility issue)

### ISSUE THREAD

**Issue by BritPanzer** [SAP/ui5-webcomponents#5014]
### **Bug Description**
In the accessibility test for our solution we got the issue reported that the associated label for our radio buttons are not read out in a screen reader. The radio buttons are implemented using the radio button control from the UI5 Web Components for React.
According to the ACC test team only the direct radio button text is read but not the associated label text. 

### **Expected Behavior**
The associated label is read out as well so that the direct radio button text gets some meaning.

### **Steps to Reproduce**
As discussed via mail I will send a mail to Ilhan with the details and corresponding links.

### **Context**
- UI5 Web Components version: 1.0.0-rc.15
- UI5 Web Components for React: 0.18.4
- Affected component: Radio Button

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by nnaydenow** [comment]
Hi @BritPanzer,

Could you please check if this snippix illustrate your problem: https://codesandbox.io/s/ui5-webcomponents-forked-7qws3p?file=/index.html ?

If no, could you please extend it so we can investigate it?

Regards,
Nayden
