### ISSUE TITLE
Change layout and width of ui5-product-switch component

### ISSUE THREAD

**Issue by geokas7** [SAP/ui5-webcomponents#5016]
Hello,

We use 'ui5-panel' component and Golden-Layout. We create inside 2 'ui5-product-switch' components. We drag with the mouse the second 'ui5-product-switch'  next to the first in order to be visible too. When we resize the  'ui5-product-switch' with the splitter the content of  'ui5-product-switch' does not be resized, despite overflow. We tried to handle the width with " nameOfProductSwitch.width='300' in order to force the content (ui5-product-switch-item) to be vertical in the appropriate event, but the content stayed stable. Is there a way to handle the width and the layout (vertical or horizontal) of ui5-product-switch?

Best,
George

**Comment by nnaydenow** [comment]
Hi @geokas7,

ui5-product-switch has requirement to set layout based on screen size and items count. If there are more than 6 items in the largest screen we display 4 column layout until there is space for them then we switch to 3 column layout. In this case 1 column layout is set only when the screen size is smaller than 600px. If there are less than or equal to 6 items we display 3 colums layout at largest screen and 1 column layout when the screen size is smaller than 600 pixels. 

If you are going to use 1 column layout have you considered to check the ui5-list?

Regards,
Nayden

**Comment by stbodurov** [comment]
Hi @geokas7,

Just checking in if you have tried using ui5-list instead, perhaps you can share whether it fits your scenario.

Regards,
Stanislav

**Comment by ilhan007** [comment]
Hello @geokas7 
we are closing the issue due to inactivity,  but feel free continue the discussion and we will re-open it.
