### ISSUE TITLE
Implement file uploader

### ISSUE THREAD

**Issue by Smux** [SAP/ui5-webcomponents#502]
**Is your feature request related to a problem? Please describe.**
Currently it is not possible to use a file uploader that is designed in Fiori 3.

**Describe the solution you'd like**
It would be great to have a file uploader available as a UI5 Webcomponent.
I would expect a similar solution to the standard ui5 file uploader.

**Describe alternatives you've considered**
Currently the only way to upload files is using the native html file uploader.

**Comment by ignipae** [comment]
Hi,

I would also like this functionality. A further thought feature built upon this could also then be the upload collection.
But first of all, a ui5 flavoured uploader would be really nice!

**Comment by vladitasev** [comment]
Still under evaluation.

**Comment by fifoosid** [comment]
A quick update guys, the control is almost ready to be pushed in master branch 😊

**Comment by fifoosid** [comment]
Hi guys,

The component is implemented and has been merged in master branch(#1181)
