### ISSUE TITLE
Error: ResponsivePopover as dialog with toolbar: Clicking on overflowbutton of toolbar causes error

### ISSUE THREAD

**Issue by C3ntraX** [SAP/ui5-webcomponents#5028]
**Describe the bug**
The ResponsivePopover is in mobile view and is rendered as dialog. An toolbar is used and rendered with an overflow button. If you click on the overflow button, than you will see the following error:

Uncaught (in promise) TypeError: Cannot read properties of null (reading 'getBoundingClientRect')
    at Popover.shouldCloseDueToOverflow (Popover.js:381:1)
    at Popover.calcPlacement (Popover.js:522:1)
    at Popover._show (Popover.js:428:1)
    at Popover._open (Popup.js:465:1)
    at Popover.showAt (Popover.js:347:1)
    at HTMLElement.<anonymous> (OverflowPopover.js:29:1)

**Isolated Example**
https://codesandbox.io/embed/still-tdd-xpin9t?file=/src/App.js&codemirror=1
Separate browser: https://xpin9t.csb.app/

**To Reproduce**
1. Open the codeexample in separat window (standalone)
2. The code example should opened with an mobile device (DevTools IPhone SE for example)
3. In the Dialog click on the overflow button
4. The overflow button does not render the overflow context and throws an error see console

**Expected behavior**
The overflowbutton should render the context without an error

**Screenshots**
![image](https://user-images.githubusercontent.com/44802503/162163200-e02d7c17-dcdd-40ac-921c-78f26063e6c3.png)
![image](https://user-images.githubusercontent.com/44802503/162163230-a8c90035-7e04-4336-9812-5a09a4e972ad.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: latest
`@ui5/webcomponents-react` version: latest
Operating System: Windows
Browser: Chrome

**Additional context**
I think the error is caused, because the zIndex of the Dialog is higher than the popover.
Dialog zIndex: 132
Popover zIndex: 108

**Comment by C3ntraX** [comment]
Okay thanks, 
sometimes a bit hard for me who is responsible, but I try my best 👍

**Comment by nnaydenow** [comment]
Hello colleagues,

Could you please check the issue? Issue is reproduced when you open provided snippix in new window with emulator.

Isolated snippix without React: https://codesandbox.io/s/ui5-webcomponents-forked-qkmwwr?file=/index.html

Regards,
Nayden
