### ISSUE TITLE
FilerBar issue with Adding Multi-field

### ISSUE THREAD

**Issue by saran85** [SAP/ui5-webcomponents#5029]
### **Bug Description**
1. Unable to add multiple Element are component inside the filter bar. Outside HTML Elements are accept only inside of the "FilterGroupItem".
2. We can't add more filter bar inside the filterbar without broken style.
3. if use multi-filterbar the "Adapt filter" property is not showing a children fields. 
4. "onToggleFilters" event is not working(Expand and Collapse) 
### **Expected Behavior**
A clear and concise description of what you expect to happen.
We use multi time adding a filerbar, please check the image we need like this 
![image](https://user-images.githubusercontent.com/95576439/162191153-a9190ea3-8546-47a8-8fdc-a8ec7d7e9a38.png)
<FilterBar>
<FilterGroupItem>
{arg}
</FilterGroupItem>
</FilterBar>
<FilterGroupItem>
And also you can see the "Adapt Filterbar" with wrong value:
![image](https://user-images.githubusercontent.com/95576439/162192444-1f740104-b2ae-4534-84ef-64e21175ced5.png)

And We expecting Filterbar Collapse and Expand given below image refer
![06 04 2022_11 59 12_REC](https://user-images.githubusercontent.com/95576439/162192945-0df04ee9-4d1e-41d8-ad71-0bda5b5b2045.gif)

### **Steps to Reproduce**
6. ...
7. ...

### **Isolated Example**
If possible, please provide an isolated example by forking [CodeSandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html).

### **Context**
- UI5 Web Components version: {...}
- OS/Platform: {...}
- Browser: {...}
- Affected component: {...}

### **Log Output / Stack Trace / Screenshots**
```
{...}
```
### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by ilhan007** [comment]
Hello @saran85 
we don't provide an ObjectPage, FilterBar, etc. you need to file the issue in https://github.com/SAP/ui5-webcomponents-react - it's the React wrapper project for UI5 Web Components, which on top provides some more components.

UI5 Web Components (pure web components) - https://sap.github.io/ui5-webcomponents/playground/components
UI5 Web Components for React (React components) - https://sap.github.io/ui5-webcomponents-react/
