### ISSUE TITLE
[ui5-input|ui5-multi-input|ui5-combobox|ui5-multi-combobox]: adjust "min-width" and "margin" to VD spec

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents#5032]
### **Background**
We have identified a gap in the min-width implementation of the inputs. Another issue found was the missing top and bottom margin of the input components.

### **What**
Update the implementation of the min-width and margins of the ui5-input/ui5-multi-input/ui5-combobox/ui5-multi-combobox components to follow the design and match the one in UI5.

### **Acceptance Criteria**
The min-width and margins of the components are adjusted.

**Comment by hristop** [comment]
The issue was fixed with this pull request: https://github.com/SAP/ui5-webcomponents/pull/6044
