### ISSUE TITLE
Feature For Analytical Table - 'Title' font-weight changes

### ISSUE THREAD

**Issue by kcrystalchen** [SAP/ui5-webcomponents#5035]
### **Feature Request Description**

- In UI5-component react
- The Font-weight can not be changed for 'Title' in Analytical Table when it selected 'ui5-title', but the font-weight for the 'Title' can be modified by selecting 'ui5-title-root' which is under the shadow root.
- User does not know how to select the 'ui5-title-root' under the shadow root in order to add the font-weight bold for the Title.

### **Proposed Solution**
- To be able to modify the Font-weight on 'Title' in Analytical Table, it would be better to modify the font weight by selecting 'ui5-title' in the Analytical Table
- is it possible to use part attribute for the ::part pseudo element? Thank you!

### **Additional Context**

![Screen Shot 2022-04-07 at 9 59 03 PM](https://user-images.githubusercontent.com/39847471/162485816-772dd586-7c1b-4e0e-9d39-04463f4b3d33.png)

Add other context or screenshots related to the feature request here.
![Screen Shot 2022-04-07 at 10 01 05 PM](https://user-images.githubusercontent.com/39847471/162485835-6b279d34-5745-4814-9b4e-c20a6c5b5d4a.png)

### **Priority**
- [x] Low
- [ ] Medium
- [ ] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by stbodurov** [comment]
Hello @SAP/ui5-webcomponents-topic-rd,

Could you evaluate if it is possible to expose a `::part` for the title container `.ui5-title-root`?

Regards,
Stanislav

<br><br><br>

In the meantime, @kcrystalchen, you can try accessing the shadow DOM through React and appending a `style` element.

You can try my suggestion in plain JS by [clicking here](https://sap.github.io/ui5-webcomponents-react/iframe.html?viewMode=docs&id=data-display-analyticaltable--default-story), and pasting the following in the console:

```js:p
var tableTitle = document.querySelector("#story--data-display-analyticaltable--default-story ui5-title");
var style = document.createElement('style');
style.innerHTML = '.ui5-title-root { font-weight: bold !important; }';
tableTitle.shadowRoot.appendChild(style);
```

**Comment by Lukas742** [comment]
Hi @stbodurov 

wouldn't it be better to use `addCustomCSS` here to inject the styles into the shadow root?

E.g.:
https://codesandbox.io/s/small-river-ppitew?file=/src/App.js

**Comment by gmkv** [comment]
Hello @kcrystalchen 

For such needs of customisation, we provide the [slot `header`](https://sap.github.io/ui5-webcomponents/playground/components/Dialog/) where you can supply any elements you want.
Using slots is the most flexible way to achieve your target design.

Regards,
Georgi
