### ISSUE TITLE
Combobox typing badly misbehaves on mobile

### ISSUE THREAD

**Issue by Thristhart** [SAP/ui5-webcomponents#5039]
### **Bug Description**
The autocomplete matching is clashing with text input on a mobile device, causing text to duplicate and also refuse to be deleted.

### **Expected Behavior**
Similar behavior to desktop: as text is input, autocompletion occurs without interfering with or duplicating the input.

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/ComboBox/ on a mobile device
2. Attempt to type "Item 1" into the first combobox
3. Attempt to backspace the now-present "Ittem 1" text and observe that it's impossible

### **Isolated Example**
https://codesandbox.io/s/ui5-combobox-mobile-misbehavior-t4ktws?file=/index.html

### **Context**
- UI5 Web Components version: v1.2.4
- OS/Platform: Android
- Browser: Android Chrome
- Affected component: ComboBox

### **Log Output / Stack Trace / Screenshots**
![image](https://user-images.githubusercontent.com/43013/162670296-59165f19-510e-4f35-9493-bad3383b0f2c.png)

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

**Comment by stbodurov** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

Could you take a look at this bug. Seems like characters are skipped when using backspace, only on Android.

Regards,
Stanislav
