### ISSUE TITLE
Accessibility for Table and Table Title

### ISSUE THREAD

**Issue by samanr** [SAP/ui5-webcomponents#5043]
### **Feature Request Description**
As a user we require our application to be accessible with screen readers softwares for Windows and MacOs. Prominent softwares are JAWS (Windows) VoiceOver (MacOS ).

Requirements: 
1. The `Table` component should read table total rows and columns count using JAWS. With Mac VoiceOver this is read. (See screenshot).
2. The reader should specifically read the table title in this case 'MyTable' before it begins reading the table information.
In the ui5 react library, there is no provision to attach a 'title' to the table and therefore we have to obtain this behaviour by adding a <Title> tag, which allows the screen reader to skip it completely. 

### **Proposed Solution**
Library should provide accessibility and read the table rows and columns count out of the box by all allowed screen readers. 
Library should provide a table title property which would be accessible as well. For example Should read as "Entering 'My Table' table"

### **Proposed Alternatives**
As an alternative library should allow attaching title component to the table such that they can be read together.

### **Additional Context**
Screenshot: 
<img width="1792" alt="Screen Shot 2022-04-08 at 8 29 09 PM" src="https://user-images.githubusercontent.com/22089053/162785916-257b16b0-94f6-4356-a1b0-98c0cd562582.png">

Code Sandbox: 
You can reproduce this in the sandbox below.: https://codesandbox.io/s/exciting-johnson-siskby?file=/src/App.js

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by stbodurov** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

Would you mind evaluating this feature request regarding ui5-table?

Regards,
Stanislav

**Comment by nikolay-kolarov** [comment]
Hello @samanr,

For the first issue - I tested in your example with Jaws 2021 and Jaws 2022 on Edge and Chrome. The column and row count is announced when you navigate with the virtual cursor.
If you turn off the virtual cursor and navigate with the arrows it reads on which row you are and how many there are in total.
Maybe you miss this announcement on first focus in the table, but this is not something that we can influence and it is up to Jaws to read it (like in the virtual mode). 

Here is a part of the speech output in reading mode/virtual cursor:
-----------------------------------
heading level 2 My Table
table with 2 columns and 27 rows
Column 1
Column 2
-----------------------------------

For the second - We have recently introduced APIs for this with this request https://github.com/SAP/ui5-webcomponents/issues/3597, so you can use it to set your title.


@elenastoyanovaa  - FYI

Best Regards,
Nikolay
