### ISSUE TITLE
[SF][Input] 'input' event is fired unexpected when suggestion item is selected

### ISSUE THREAD

**Issue by 2bno1** [SAP/ui5-webcomponents#5046]
### **Bug Description**
When one suggestion item is selected, besides the 'change' event, 'input' event is also fired unexpectedly. 
Our application listens to the 'input' event of ui5-input and calls search API to fetch suggestion list matching the characters in the input. Now, when one suggestion item is selected, the 'input' event is fired, and search API is called with the whole text of that item. This results the returning suggestion list has only 1 item or even empty. This is unexpected.

### **Expected Behavior**
'input' event is not fired when suggestion item is selected, or provides option to prevent this default behavior.

### **Steps to Reproduce**
See the recording below.

https://user-images.githubusercontent.com/1751846/162900811-a3637807-a588-46d0-aced-aacd0efb75d7.mov

### **Isolated Example**
https://codesandbox.io/s/ui5-input-suggestion-forked-2g82od?file=/src/index.js

### **Context**
- UI5 Web Components version: 1.2.1
- OS/Platform: macOS
- Browser: chrome
- Affected component: ui5-input

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

**Comment by stbodurov** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

Please evaluate the drawbacks in removing the firing of the native input event in `selectSuggestion`:  https://github.com/SAP/ui5-webcomponents/blob/199d9741dce8987f5df476f6bf667fbf8213cf4f/packages/main/src/Input.js#L1094

If such are present, consider whether it's possible to provide an option to prevent this default behavior.

Regards,
Stanislav

**Comment by ivoplashkov** [comment]
Hello,

Actually, this is the intended behaviour of the "input" event.
The input event is fired every time the value of the element changes, therefore please adjust your application logic to this behavior.

Thank you in advance!
Best regards,
Ivaylo
