### ISSUE TITLE
SideNavigation: no text alternative in the form of tooltip provided for the ‘Expand/Collapse’ 

### ISSUE THREAD

**Issue by PriyaPowar** [SAP/ui5-webcomponents#5048]
Bug:*
The Expanded / Collapsed state of SideNavigationItem is not being showcased with a text alternative/ tooltip.

Steps to Reproduce:
1) open the react ui5 component wiki https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-sidenavigation--default-story
2) Hover over any sidenavigation item with subitem.

Only the title of sidenaigationitem is shown as tooltip. There is no information provided whether it is in expanded / collapsed state. This information is useful for accessibility. Accessibility Incident is raised for this issue in BCP.

**UI5 Web Components for React Information**
`@ui5/webcomponents` version:1.0.0-rc.14
`@ui5/webcomponents-react` version:0.15.2
Operating System: windows
Browser: chrome

**Comment by stbodurov** [comment]
Hello @PriyaPowar,

Closing the issue as the screen reader output includes the "expanded/collapsed" state and there are no accessibility concerns about the visual tooltip itself.

Regards,
Stanislav
