### ISSUE TITLE
ShellBar: Place holder text color contrast issue

### ISSUE THREAD

**Issue by PriyaPowar** [SAP/ui5-webcomponents#5050]
Bug: The placeholder text in search field available in ShellBar is not upto the expect color contrast ratio. The place holder text ‘Enter a term’ within the search field does not suffice the minimum color contrast ratio of 4.5:1 in default theme

### **Isolated Example**
https://codesandbox.io/s/keen-kate-3sb63u?file=/src/App.js

### **Context**
- UI5 Web Components version: "@ui5/webcomponents": "1.0.0-rc.14",
- OS/Platform: windows
- Browser: chrome
- Affected component: shellbar

### **Priority**
- [x] Low
- [ ] Medium
- [ ] High
- [ ] Very High

BCP incident is raised for this bug by accessibility team.

**Comment by stbodurov** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

There is an issue with the contrast ratio of the ui5-input placeholder, when placed in the searchField slot. While the slot can accept any HTMLElement, the recommended usage is to place ui5-input

This seems to be an issue specin Quartz Light. Currently ui5-input doesn't provide the ability to change the placeholder color with a :part, so the only possible solution is to access the shadowRoot through the script.

Could you please provide an answer and/or close the issue?

Regards,
Stanislav

**Comment by nnaydenow** [comment]
Hello colleagues,

Could you please check if we can add CSS part to the inner input defined in ui5-input? We have to overwrite the placeholder text color when it is used inside ui5-shellbar. Currently there is no way to change the placeholder at all.

Regards,
Nayden
