### ISSUE TITLE
ShellBar: Wrong UI type is read during accesibility testing

### ISSUE THREAD

**Issue by PriyaPowar** [SAP/ui5-webcomponents#5051]
### **Bug Description**
When the primary title of the shellbar is accessed in reading mode, UI type is read as ‘Button’ even though it is a static text. The issue is raised under accesibility testing.

### **Expected Behavior**
When no actions are written for title of shellbar, then the UI type should be label /title/text used instead of button 

### **Steps to Reproduce**
UI inspect on the primary title of shellbar shows it as button though it does not have any actions on clicking of it.

### **Context**
- UI5 Web Components version: "@ui5/webcomponents": "1.0.0-rc.14"
- OS/Platform:windows
- Browser: chrome
- Affected component: shellbar

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by stbodurov** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

Could you take a look at this bug? Seems like the primary title of ShellBar is rendered as a button even when no items are present.
You can use https://codesandbox.io/s/ui5-webcomponents-forked-ubhi3r?file=/index.html to reproduce.

Regards,
Stanislav

**Comment by PriyaPowar** [comment]
@nnaydenow , Can you please let me know under which library version would these changes be available?
We have updated the lib versions to following:
"@ui5/webcomponents": "^1.4.0",
"@ui5/webcomponents-fiori": "^1.4.0",
"@ui5/webcomponents-icons": "^1.4.0",
"@ui5/webcomponents-react": "^0.25.1",

**Comment by nnaydenow** [comment]
Hi @PriyaPowar,

Since it wasn't part of 1.4.0 (https://github.com/SAP/ui5-webcomponents/releases) release of UI5 webcomponents the fix will be available with next version.

Regards,
Nayden
