### ISSUE TITLE
FlexibleColumnLayout: Expand/collapse arrows option is not available if the screen width is reduced

### ISSUE THREAD

**Issue by PriyaPowar** [SAP/ui5-webcomponents#5053]
### **Bug Description**
When the screen width is reduced to any dimension width less than that of a desktop then the layout expand/collapse arrows get hidden and only 1 (middle) among the 3 layouts is seen. User is no where provided with an option to view other layouts. If all layouts dont fit the screen size, then atleast the arrows should be shown so that user can expand the left and right layouts, if needed.
![image](https://user-images.githubusercontent.com/90389521/162983988-621f687d-d660-480c-95d3-a45262ccf491.png)

### **Steps to Reproduce**
The issue can be reproduced using the react ui5 components wiki example too https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-flexiblecolumnlayout--default-story
Go to the above url and using 'toggle device toolbar' (F12 menu tab) user can change the width dimensions and check.

### **Context**
- UI5 Web Components version: latest version
- OS/Platform: windows
- Browser: chrome
- Affected component: flexible column layout

```
### **Priority**
- [ ] Low
- [] Medium
- [] High
- [x] Very High

**Comment by stbodurov** [comment]
Hello @PriyaPowar, @SAP/ui5-webcomponents-topic-p,

As far as I'm aware, in ui5-webcomponents the handling of user interaction such as switching to a given column or returning to a previous one on mobile is the app developer's responsibility.

The sample that you're pointing out simply doesn't have this navigation implemented, if you try the second sample on mobile you will see that there is a way to navigate in both directions, either by tapping on a list item or pressing the close button.

Regards,
Stanislav
