### ISSUE TITLE
MultiComboBox: Grouping feature is missing 

### ISSUE THREAD

**Issue by anfavretto** [SAP/ui5-webcomponents#5060]
### **Feature Request Description**

Following the [Fiori Guidelines of the Multi-Combo Box](https://experience.sap.com/fiori-design-web/multi-combobox/) we need the [grouping feature](https://experience.sap.com/fiori-design-web/multi-combobox/#grouping) available. 

### **Proposed Solution**
We need to be able to add the groups.

### **Additional Context**
Is possible to allow us to add a checkbox on the grouping as well? We need to be able to select the group, not only the items.

### **Priority**
- [ ] Low
- [ ] Medium
- [ ] High
- [x] Very High

It's very high because we need this feature to deliver an internal project to an external customer.

### **Stakeholder Info** (if applicable)

- Organization: CIM SLE
- Business impact: This feature is required to deliver a filter to the customer. As I mentioned we are using the webcomponents on an internal project and this feature is required to us deliver successfully to the customer.

**Comment by stbodurov** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

Please take a look at this feature request.

Regards,
Stanislav

**Comment by nikolay-kolarov** [comment]
Hello @anfavretto,

Thanks for creating this enhancement request.
We can work towards enabling the grouping in the MultiComboBox component in a similar way to how it is done in the ComboBox (https://sap.github.io/ui5-webcomponents/master/playground/components/ComboBox/).
Could you please provide more information about the expected timelines?

About the request to have a checkbox on group level as well, this is currently not specified in the UX and the fiori guidelines. So we cannot provide it at the moment.

Best Regards,
Nikolay

**Comment by anfavretto** [comment]
Hi Nikolay, 
We need this component until July 20th. 
Yes, about the checkbox on the group level we should handle it internally extending your component. Do you have any input on the best practices to extend your components?

**Comment by ilhan007** [comment]
Hi @FRicardi you are right, sorry for that - the release and the merge of the feature happened on the same day. Until now I thought hat it made into the 1.4.0 release, but did not. It will be in 1.5.0 coming 1st week of July.
