### ISSUE TITLE
Button: Tooltip is missing for disabled button

### ISSUE THREAD

**Issue by Bilal3120** [SAP/ui5-webcomponents#5083]
**Describe the bug**
Tooltip is missing for disabled button

**Isolated Example**
[Codesandbox](https://codesandbox.io/s/awesome-shirley-i5p7bh?file=/src/App.js)

**Expected behavior**
Tooltip is expected even when the button is disabled

Operating System: Mac os montery
Browser: Chrome

**Comment by niyap** [comment]
Hello Colleagues,

As described above, the issue is not reproducible in UI5. If you have disabled ui5-button and you have provided a tooltip, it is not visible if the component is disabled. The issue is reproducible in the sample page as well.

Could you please look over?

Kind Regards,
Niya
