### ISSUE TITLE
Where are css classes and other imports coming from in the documentation?

### ISSUE THREAD

**Issue by lastmjs** [SAP/ui5-webcomponents#5094]
Hi!

I'm enjoying getting to know the web components in my project right now, but I am having a very difficult time understanding where certain css classes are coming from in the documentation.

For example, take the dialog documentation: https://sap.github.io/ui5-webcomponents/playground/components/Dialog/

It uses css classes such as `login-form` and `dialog-footer` but there is no information that I can find on where those classes come from. Are they supposed to implemented by the developer consuming the web component? Are they from some ui5 css file? There is no import information or anything, and it's very confusing.

In addition to that, it would be very very nice to increase the code examples a bit to make them more complete. Please show all dependencies in the code examples so that we can see where things are imported from. Even though it's simple once you get used to it, finding some import paths can be very difficult. For example I didn't know that `ui5-li` was from the import `@ui5/webcomponents/dist/StandardListItem.js`. I had to rediscover that twice in the past day or two, it's kind of buried in the documentation.

**Comment by ilhan007** [comment]
Hello @lastmjs thank you for your interest in UI5 Web Components and the feedback.

Yes, these styles are supposed to be implemented by the consumers of the UI5 Web Components.
Previously they used to be inline styles, that everyone can simply see, but we had to start moving them to external css file to be CSP compliant. So most of the external styles set are no longer inline.

The classes can be found here https://sap.github.io/ui5-webcomponents/assets/css/api.css but you should not take  them as 
design guideline, it's just an example., you can do whatever fit you use-case.

And, I admit that it is not clear enough, when someone sees the following example if the login-form is something built-in or should be provided externally. We can think of something to make it better.
<img width="700" alt="Screenshot 2022-04-20 at 21 30 27" src="https://user-images.githubusercontent.com/15702139/164298574-da95cdec-335e-4052-9cfd-6f8cb93fa9ec.png">



The css for "login-form" is the following:
```css
.login-form {
	display: flex;
	flex-direction: column;
	justify-content: space-evenly;
	align-items: flex-start;
	margin: 3rem 6rem;
}
```

On the other question:
If you open the List sample page https://sap.github.io/ui5-webcomponents/playground/components/List/
and scroll down to the List Overview section (every component has Overview section where the required imports are listed), you will see the imports required for all types of list items:

<img width="799" alt="Screenshot 2022-04-20 at 21 17 57" src="https://user-images.githubusercontent.com/15702139/164296496-c5ad3695-f67b-454e-aebc-6eb4c81cec23.png">

In addition all the components are described by package
https://www.npmjs.com/package/@ui5/webcomponents
https://www.npmjs.com/package/@ui5/webcomponents-fiori

<img width="719" alt="Screenshot 2022-04-20 at 21 36 08" src="https://user-images.githubusercontent.com/15702139/164299546-a12ed21d-11f4-449b-a9d7-59d17fe73652.png">

**Comment by lastmjs** [comment]
Thank you for the clarification, I came to these conclusions after a while of figuring it out on my own. If this could all be made more explicitly clear to the developer that would be great.

My biggest recommendation on the imports issue is to have JS example right above or below the HTML examples, to show the imports being used in an example app using lit-html or LitElement or something like that. Even just a JS file with only the imports at the top (so you don't have to specify a framework) would be excellent. Combine that with a little CSS snippet and all of these issues could possibly go away.

**Comment by nnaydenow** [comment]
Hi @lastmjs,

We have new documentation and the samples part is enhanced. Now when you play with sample you have access to the full code of the sample like script, css, html files and you can see where everything comes from. You can check it: https://sap.github.io/ui5-webcomponents/components/Button/#basic-sample

Regards,
Nayden
