### ISSUE TITLE
Dialog not read correctly by JAWS screen reader

### ISSUE THREAD

**Issue by Bilal3120** [SAP/ui5-webcomponents#5100]
### **Bug Description**
In the screenshot attached the JAWS reader is reading "Title dialog" "dialog" but the title provided is "Title". 

### **Expected Behavior**
Should read the dialog title and the content correctly.

### **Isolated Example**
[Codesandbox](https://codesandbox.io/s/naughty-ully-14r4sp?file=/src/App.js) can be used to check the issue

### **Screenshot**
![MicrosoftTeams-image](https://user-images.githubusercontent.com/93638146/164165086-0468c544-1d82-4ece-99d2-fd84e607f06f.png)

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

**Comment by gmkv** [comment]
Hi @Bilal3120 
I see you're setting `role="dialog"` in your JSX but such property doesn't exist on the [react component Dialog](https://sap.github.io/ui5-webcomponents-react/?path=/docs/modals-popovers-dialog--default-story).
This is likely causing the double announcement of the word "dialog".

Regards,
Georgi
