### ISSUE TITLE
List: Scrollevent does not trigger scrolling and scrollTop of List ref doesn´t work

### ISSUE THREAD

**Issue by C3ntraX** [SAP/ui5-webcomponents#5103]
**Describe the bug**
1. The IntrinsicElement onScroll does not working with the List component. 
2. The corresponding scrollTop property from the List reference always lists 0, but should only list 0 if your scrollbar is on top of the list.

**Isolated Example**
https://codesandbox.io/s/nice-newton-ywc8gq?file=/src/App.js

**To Reproduce**
1. Open the Sandbox
2. Scroll within the list
3. See, that the event does not logging "Test" to console.
4. Scroll down in the list
5. Click a StandardListItem
6. See, that scrollTop always keep its 0 value.

**Expected behavior**
IntrinsicElements onScroll etc. should work with the List component and other components.
"scrollTop" should have the relative scollbar position.

**Screenshots**

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: Latest
`@ui5/webcomponents-react` version: Latest
Operating System: Windows
Browser: Chrome

**Additional context**
With the bugs, I'm not able to implement a PullToRefresh component which is currently missing in UI5 Webcomponents.

**Comment by ilhan007** [comment]
Hello @C3ntraX ,
the list.scrollTop returns always 0 as this is not the DOM element that is being scrolled. There is another element `<div class="ui5-list-scroll-container"` in the ShadowDOM that is really scrolling.
```js
li.addEventListener("click", () => {
  console.log(
    list.shadowRoot.querySelector(".ui5-list-scroll-container").scrollTop // will return the real scroll position
  );
});
```

Not use what the final goal is, but If you want add more items while the user scroll you can use the `growing` feature by setting `growing="Scroll"`.
```html
<ui5-list id="list" growing="Scroll" style="height: 200px;">
```

and listen to the `load-more` event
```js
list.addEventListener("load-more", () => {
  console.log("load-more");
});
```

**Comment by C3ntraX** [comment]
Hello @ilhan007,

I want to implement a PullToRefresh component which is currently missing in the libary see #5106.
I know the load-more property but this isnt what I want. I simply need a way to increase the mobile experience by pulling the list. If the list scrollTop is at position 0, the list scrollbar is on top and the user could refresh the list via pull down. 

Its interesting that scrollTop is working properly in your example, but this is not working the typical react way. Because of this, I thought it was a bug in @ui5/webcomponents-react.

**Comment by nnaydenow** [comment]
Hi @C3ntraX,

If you don't want to travers shadowDOM of ui5-list you can wrap ui5-list in another div and add the scroll listener to it. You can check this snippix: https://codesandbox.io/s/ui5-webcomponents-forked-zvgrd7?file=/index.html

**Comment by ilhan007** [comment]
Hello @C3ntraX it seems the sample, provided by @nnaydenow works for you - closing the issue, if nothing else from your side.
