### ISSUE TITLE
[SF]All the keyboard events are prevented after enabling F6Navigation

### ISSUE THREAD

**Issue by BennyHuang** [SAP/ui5-webcomponents#5110]
### **Bug Description**
All the keyboard events are prevented after enabling F6Navigation. We cannot type in Input/TextArea. We cannot moving focus when typing Tab key. It is related to the fix https://github.com/SAP/ui5-webcomponents/pull/4886/files.

### **Expected Behavior**
Keyboard events should work properly

### **Steps to Reproduce**
1. Go to  codesandbox https://codesandbox.io/s/eager-pond-mi5i0v?file=/src/App.js

### **Context**
- UI5 Web Components version: 1.3.0
- OS/Platform: Mac OS
- Browser: All
- Affected component: F6Navigation

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - High
- Functional issue -  High
- Visual issue - Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SF

**Comment by unazko** [comment]
Hello @SAP/ui5-webcomponents-team,

The issue is reproducible as described by @BennyHuang with the provided snipped.
Could you please take over as it is related to the global keyboard group navigation.

Best Regards,
Boyan Rakilovski
