### ISSUE TITLE
TextArea: warning label is not positioned correctly in SAP Horizon 

### ISSUE THREAD

**Issue by kilgharsap** [SAP/ui5-webcomponents#5115]
**Describe the bug**
The position of the warning label is incorrect in SAP Horizon theme

<img width="1009" alt="Screen Shot 2022-04-21 at 11 40 30 AM" src="https://user-images.githubusercontent.com/89424021/164531187-fa5dfcac-f902-441d-8928-b7e060123ae0.png">

**Isolated Example**
*Please provide an isolated example if possible by forking [this codesandbox](https://codesandbox.io/s/ui5-webcomponents-react-template-29l34).*

**To Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents-react/?path=/story/inputs-textarea--default-story&args=valueState:!undefined;maxlength:10;showExceededText:true&globals=theme:sap_horizon
2. Type more than 10 characters in the textarea, 
3. See error: warning will be overlapping with bottom border 

**Expected behavior**

The warning should be positioned as the below
<img width="976" alt="Screen Shot 2022-04-21 at 11 44 13 AM" src="https://user-images.githubusercontent.com/89424021/164531630-fdb75650-9336-4ec0-9e63-18fb90ca78b0.png">

Follow the reproducing step with this url https://sap.github.io/ui5-webcomponents-react/?path=/story/inputs-textarea--default-story&args=valueState:!undefined;maxlength:10;showExceededText:true

**Screenshots**

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: ^0.22.8
`@ui5/webcomponents-react` version:
Operating System:
Browser:

**Additional context**

**Comment by Lukas742** [comment]
I just noticed that this issue is a duplicate. Please follow the progress [here](https://github.com/SAP/ui5-webcomponents/issues/4986).
