### ISSUE TITLE
[date picker, calendar] clicking previous and next buttons in calendar with highlight other elements on the page

### ISSUE THREAD

**Issue by allen138** [SAP/ui5-webcomponents#5117]
### **Bug Description**
Hi team,
When using the 'previous' `<` and 'next' `>` buttons in the calendar, after one or two presses, other content on the page will being to become highlighted. Please see the following screenshots. 
![image](https://user-images.githubusercontent.com/38701667/164815409-b32bbd1e-e000-40b8-a885-557f2d97bd0b.png)
then press a couple times again,
![image](https://user-images.githubusercontent.com/38701667/164815449-241b585c-e53a-41d3-93da-a3c200f767f0.png)

Here is an example within the application:
![image](https://user-images.githubusercontent.com/38701667/164815943-efdff628-50a7-491e-b693-c664106f493b.png)

Issue will occur will calendar and date picker components. 

Thanks,
Allen

### **Expected Behavior**
Other elements on the page will not become highlighted when pressing any button in the calendar

### **Steps to Reproduce**
1. Go to ['ui5-webcomponents - calendar'](https://sap.github.io/ui5-webcomponents/playground/components/Calendar/)
2. toggle the next and previous buttons in the header of the calendar
3. notice the other content on the page is becoming highlighted.

### **Context**
- UI5 Web Components version: tested on 1.2.4, but reproducible on playground with I think is on latest
- Affected component: All calendar components.

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### **Stakeholder Info** (if applicable)

- Organization: SF
- Business impact: Medium

**Comment by unazko** [comment]
Hello @SAP/ui5-webcomponents-topic-b,

The issue is reproducible in the playground as described by @allen138.

Best Regards,
Boyan Rakilovski
