### ISSUE TITLE
FileUploader: when upload the same file again, it will not trigger the onChange callback

### ISSUE THREAD

**Issue by tqq123** [SAP/ui5-webcomponents#5118]
**Describe the bug**

when upload the same file again, it will not trigger the onChange callback

**Expected behavior**

it will trigger the onChange callback when upload the same file again.

**Screenshots**
<img width="375" alt="image" src="https://user-images.githubusercontent.com/19241167/165039401-ff465fad-b053-4dc0-a52c-6c103d6dec07.png">

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: "~1.1.2"
`@ui5/webcomponents-react` version: "^0.21.2"
Operating System: macOS 12.3.1
Browser: Chrome 100

**Comment by niyap** [comment]
Hello @tqq123,

As written in the documentation, "change" event is fired when the value of the file path has been changed. When updating the same file, the file path is not changed, so it is not expected to be fired.
Here is the documentation: https://sap.github.io/ui5-webcomponents/master/playground/components/FileUploader/
The behaviour is the same in the sap.ui.unified.FileUploader as well: https://sapui5untested.int.sap.eu2.hana.ondemand.com/demokit/#/api/sap.ui.unified.FileUploader%23events/change

Kind Regards,
Niya
