### ISSUE TITLE
[Calendar] Month translations in Slovak are incorrect

### ISSUE THREAD

**Issue by allen138** [SAP/ui5-webcomponents#5120]
### **Bug Description**
Hi team,
It has been brought to my attention that the months in the date-picker and calendar components have the wrong translation for Slovak locale. You can test this by going to the playground using the url param to force Slovak lang, https://sap.github.io/ui5-webcomponents/playground/components/DatePicker/?sap-ui-language=sk_SK. 

months displayed:
0: "januára"
1: "februára"
2: "marca"
3: "apríla"
4: "mája"
5: "júna"
6: "júla"
7: "augusta"
8: "septembra"
9: "októbra"
10: "novembra"
11: "decembra"

correct translation:
0: "január"
1: "február"
2: "marec"
3: "apríl"
4: "máj"
5: "jún"
6: "júl"
7: "august"
8: "september"
9: "október"
10: "november"
11: "december"

I noticed that the translations should come from a sk.json as part of the generated assets. In this json file there are months for 'ca-gregorian' and 'ca-buddhist'. The months for the Gregorian object are correct whereas the ones for Buddhist are not.

Thanks,
Allen

### **Expected Behavior**
A clear and concise description of what you expect to happen.

### **Steps to Reproduce**
1. Go to [DatePicker/?sap-ui-language=sk_SK.](https://sap.github.io/ui5-webcomponents/playground/components/DatePicker/?sap-ui-language=sk_SK)
2. Open any date picker, check the months

### **Context**
- UI5 Web Components version: all
- Browser: all
- Affected component: all calendar components

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### **Stakeholder Info** (if applicable)

- Organization: SF
- Business impact: Medium

**Comment by unazko** [comment]
Hello @SAP/ui5-webcomponents-topic-core,

The issue is easily reproducible in the provided by @allen138 samples.
As it is related to the message bundle translation I'm redirection this incident to the core team.

Best Regards,
Boyan Rakilovski

**Comment by ilhan007** [comment]
Hello @unazko @SAP/ui5-webcomponents-topic-b 

We have checked the CLDR data that is responsible for the moths name in sk_SK, but it's perfectly fine. We have checked the OpenUI5 implementation and the root cause seems to be the usage of `getMonths` in the MonthPicker. Exchanging it with `getMonthsStandAlone` (the method used in OpenUI5) resolves the issue.

Could you take a look the following PR: https://github.com/SAP/ui5-webcomponents/pull/5212
