### ISSUE TITLE
Theme falling back is not working as expected

### ISSUE THREAD

**Issue by yaosheng79** [SAP/ui5-webcomponents#5136]
### **Bug Description**
If the given theme does not exist, ui5 can not fall back to the default theme correctly.

### **Expected Behavior**
UI5 should fall back to the default theme automatically

### **Steps to Reproduce**
1. Navigate to: http://localhost:8082/test-resources/pages/
2. open any test page
3. append ```?sap-ui-theme=aaa``` to the url
4. in the console it says ```You have requested a non-registered theme - falling back to sap_fiori_3``` but the page is not rendered correctly

### **Isolated Example**
If possible, please provide an isolated example by forking [CodeSandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html).

### **Context**
- UI5 Web Components version: {...}
- OS/Platform: {...}
- Browser: {...}
- Affected component: {...}

### **Log Output / Stack Trace / Screenshots**
![image](https://user-images.githubusercontent.com/9492648/165677156-aa3a4fe8-9a2c-43e5-969f-7854f67d8cdc.png)

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {MOB-MDK-MDC-WEB}
- Business impact: {...}

**Comment by niyap** [comment]
Hello @SAP/ui5-webcomponents-topic-core,

There is a warning logged in the console that when the theme's name is invalid, we will fall back to Fiori 3 theme but that does not happen. Instead, the page is not rendered correctly.

Could you please look over the issue?

Thank you in advance!

Regards,
Niya
