### ISSUE TITLE
ui5-multiinput, ui5-multicombobox: Paste functionality

### ISSUE THREAD

**Issue by elenastoyanovaa** [SAP/ui5-webcomponents#5161]
After receiving a customer incident in UI5 we reviewed the existing handling of the paste functionality (pasting cells from Excel). We found that there are gaps in the implementation in both SAPUI5 and UI5 WC. Also, we checked that the paste functionality does not work at all for some cases in the components.

We should review the existing functionality, apply the enhancements made in UI5 and also implement what is currently missing in the ui5 web components.

Things to test:
- pasting a single cell from excel should result in pasting the value as a text, not a token
- copy two cells from one row, then paste
- copy two cells from one column, then paste
- copy multiple cells from different columns and rows, then paste
- copy cells with values and cells with no values, then paste

Windows and MacOS result in different clipboard data, so both of them should be tested.

**Comment by gregorwolf** [comment]
Hello @elenastoyanovaa,

will a solution to this topic solve the issue that when I currently test [MultiInput](https://sap.github.io/ui5-webcomponents/playground/components/MultiInput/) with the following values from Excel:

```
Argentina
Bulgaria
Germany
```

results in a combined token:

![Screenshot 2023-03-20 at 11 27 35](https://user-images.githubusercontent.com/2639535/226313391-3815ef65-9fee-4c54-aeba-37beb8e73d41.png)

But when I test this using [sap.m.sample.MultiInputValueHelp](https://ui5.sap.com/#/entity/sap.m.MultiInput/sample/sap.m.sample.MultiInputValueHelp) with the values:

```
Notebook Basic 17
Notebook Lock
```

It results in separated tokens:

![Screenshot 2023-03-20 at 11 29 35](https://user-images.githubusercontent.com/2639535/226313862-c7c10b7b-b496-4e35-bc57-06ec923d986e.png)

We have implemented the UI of a SAP BTP Partner Solution using UI5 Web Components for React and the [inputs-multiinput](https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-multiinput--docs) control which itself is based on the @ui5/webcomponents Multi Input. We need to follow the Fiori Design guidelines and also our customers requesting a working paste functionality. Can you say anything about the roadmap for realisation?

Best Regards
Gregor

**Comment by ivoplashkov** [comment]
Hello,

The functionality is now implemented in both `ui5-multicombobox` and `ui5-multi-input`. In the `ui5-multi-input` we have provided a sample in order to demonstrate how the application can handle the case on their side. In the `ui5-multicombobox` the functionality is implemented within the control and no further logic is required on the application side.

Best regards,
Ivaylo
