### ISSUE TITLE
item navigation: keyboard navigation is incorrect in RTL

### ISSUE THREAD

**Issue by gmkv** [SAP/ui5-webcomponents#5166]
### **Bug Description**
We use the ItemNavigation module in TabContainer and I noticed that the left/right arrow keys are behaving in reverse while in RTL mode.

### **Expected Behavior**
Arrow Left should focus the item to the left, regardless of the LTR/RTL language being loaded.
This applies for Arrow right key too.

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/TabContainer/?sap-ui-theme=sap_fiori_3&isrtl=true
2. Focus on a tab
3. Navigate with the arrow keys.

The example is showing a TabContainer, but this would apply to all users of ItemNavigation in RTL.

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by IlianaB** [comment]
Hello @SAP/ui5-webcomponents-topic-core I am forwarding this issue to you, because in RTL mode navigating with arrow keys (left/right) does not work as expected, but in the opposite way. It seems the problem comes from the ItemNavigation.

Could you take a look?

Regards,
Iliana
