### ISSUE TITLE
MultiComboBox: No AccessibleName property available

### ISSUE THREAD

**Issue by I516406** [SAP/ui5-webcomponents#5176]
**Describe the bug**
The MultiComboBox component doesn't have the AccessibleName property associated with it.

**Comment by IlianaB** [comment]
Hello @ui5-webcomponents-topic-rl I am forwarding this issue to you, because MultiComboBox does not provide an AccessibleName property.

Tested with Access Assistant:
This INPUT (role=combobox) does not have a mechanism that allows an accessible name value to be calculated

Best regards,
Iliana

**Comment by niyap** [comment]
Hello @I516406,

The issue is already reported #5019. I am closing the incident as a duplicate one. Please, follow the progress in the related incident.

Kind Regards,
Niya
