### ISSUE TITLE
StepInput: add `input` event

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#5177]
### **Feature Request Description**
Currently the `input` event is not passed to the internal `input` element. So in order to fire an event on every keystroke it needs a hacky workaround using `key` events.

See [codeSandbox](https://codesandbox.io/s/ui5-webcomponents-forked-binp9i?file=/src/index.js).

### **Proposed Solution**
Make the `input` event available on the web component.

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by IlianaB** [comment]
Hello @SAP/ui5-webcomponents-topic-b , take a look of this feature request.

Regards,
Iliana

**Comment by DMihaylova** [comment]
Internally tracked as BGSOFUIBALKAN-8865.
