### ISSUE TITLE
TabContainer: Only contents of first tab show up in Firefox

### ISSUE THREAD

**Issue by eswortmaler** [SAP/ui5-webcomponents#5178]
### TabContainer: Only contents of first tab show up in Firefox
Only the contents of the first tab are always shown when selected. The contents of the subsequent tabs are empty except if the tab is selected when the page is loaded, or if it is the second tab after switching from the first to the second tab. Clicking on an already selected tab to expand/contract it will crash the browser window if it is empty in this way.

### **Expected Behavior**
Whenever a tab gets selected the contents of that tab should be displayed

### **Steps to Reproduce**
Let's take the following HTML code that can demonstrate these issues:
```html
<ui5-tabcontainer>
   <ui5-tab text="Tab 1">
      <ui5-label>One</ui5-label>
   </ui5-tab>
   <ui5-tab text="Tab 2">
       <ui5-label>Two</ui5-label>
   </ui5-tab>
   <ui5-tab text="Tab 3" selected>
      <ui5-label>Three</ui5-label>
   </ui5-tab>
</ui5-tabcontainer>
```
1. Open the page using the latest Firefox (100.0 as of now)
The page looks like this:
![image](https://user-images.githubusercontent.com/23629712/166922610-cc4c3f5a-83ae-4a1b-9730-ef25d2ea04ad.png)
This is expected
2. Now after clicking on "Tab 2" it looks like this:
![image](https://user-images.githubusercontent.com/23629712/166922803-8500c1a1-7579-44aa-b11b-30e184b8ac19.png)
Tab 2 is shown empty, but it shoud say "Two"
3. After clicking back on "Tab 3" it is now also empty:
![image](https://user-images.githubusercontent.com/23629712/166923046-3f1e2150-f1f4-42dc-bf80-07970d2302f9.png)
4. Now clicking on "Tab 1" looks normal again:
![image](https://user-images.githubusercontent.com/23629712/166923187-b661a7e2-8d8f-45b6-b746-0c6301356a72.png)
5. Clicking on "Tab 2" after clicking on "Tab 1" first also looks as expected:
![image](https://user-images.githubusercontent.com/23629712/166923346-71f11a5b-6f9f-490d-a2be-353b993a8a65.png)
6. Clicking on "Tab 3" again will make it empty again:
![image](https://user-images.githubusercontent.com/23629712/166923549-6979055c-dd70-4cb2-a82a-8a4b60b0a314.png)
7. Now clicking on the empty "Tab 3" while it is already selected should contract the tab. Instead it crashes the browser tab.
![image](https://user-images.githubusercontent.com/23629712/166923833-2686b08d-c104-4ae0-a337-49f9fde57a77.png)

### **Isolated Example**
The issue can be seen in this example when viewed in Firefox (tested on 100.0 64-bit)
The same behavior can be seen both in version 1.3.0 and 1.3.1 of @ui5/webcomponents, but it works fine in version 1.2.4
https://codesandbox.io/s/ui5-webcomponents-forked-zst98e?file=/index.html

### **Context**
- UI5 Web Components version: {1.3.0 & 1.3.1}
- OS/Platform: {Windows 11}
- Browser: {Firefox 100.0 (64-bit)}
- Affected component: {ui5-tabcontainer}

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### **Stakeholder Info**

- Organization: rit-edv consulting
- Business impact: This breaks every instance of the TabContainer component with more than two tabs on Firefox

**Comment by IlianaB** [comment]
Hello @SAP/ui5-webcomponents-topic-rd I am forwarding this issue to you, because on FireFox browser selecting a tab of the TabContainer does not always show its content.

Could you have a look?

Best regards,
Iliana
