### ISSUE TITLE
[Petrobras] Maxlength on input doesnt work when type is Input Type is Number

### ISSUE THREAD

**Issue by biancamattosn** [SAP/ui5-webcomponents#5180]
**Describe the bug**
Hello colleagues,

I'm having an issue when adding maxlength to an Input type number, it is possible to add much more numbers passing the maxlength.

**Isolated Example**
https://codesandbox.io/embed/weathered-pond-3qeusx?fontsize=14&hidenavigation=1&theme=dark
```
<Input
maxlength={3}
type={InputType.Number} />
```

**Expected behavior**
Only able to add number not passing the maxlength.

**Screenshots**
Here I added 3 for maxlength and this was what I got
![image](https://user-images.githubusercontent.com/91496753/166929267-0e9d4f80-5fb8-463c-9435-2b77bdab084f.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: ^1.0.0
`@ui5/webcomponents-react` version: 0.22.4
Operating System: MacOs
Browser: Chrome

**Comment by ilhan007** [comment]
Hello @biancamattosn 
the `maxlength` in general is not valid for Input of type="Number", it's valid for text, search, url, tel, email, and password types. See the official docs https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#maxlength

Apart of that, our documentation must clearly state that. 

@SAP/ui5-webcomponents-topic-rl I assume maxlength is not supported for Input of type="Number". If this is the case could you update the Input maxlength API to state when the property takes effect and when ignored.
