### ISSUE TITLE
ui5-datetime-picker component footer strings not translated completely

### ISSUE THREAD

**Issue by agarwal-akash** [SAP/ui5-webcomponents#5181]
### **Bug Description**
We are using the ui5-datetime-picker component and the footer strings are not translated completely for languages like Bulgarian(bg) and French(fr).

### **Expected Behavior**
Footer strings of the component must be translated.

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/DateTimePicker/?sap-ui-language=bg_Bg 
2. On opening ui5-datetime-picker component. It is observed that footer string 'Cancel' along with strings for hours/min/sec are translated and displayed properly but not 'Ok' button. 

### **Isolated Example**
If possible, please provide an isolated example by forking [CodeSandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html).
This can be directly observed by adding sap-ui-language param to ui5 webcomponents documentation.

https://sap.github.io/ui5-webcomponents/playground/components/DateTimePicker/?sap-ui-language=bg_Bg

### **Context**
- UI5 Web Components version: {1.0.0-rc.15}
- OS/Platform: {macOs Monterey}
- Browser: {Chrome 100.00}
- Affected component: {ui5-datetime-picker}

### **Log Output / Stack Trace / Screenshots**
<img width="1535" alt="Screenshot 2022-05-06 at 2 41 29 PM" src="https://user-images.githubusercontent.com/12569493/167104435-0b5ee39a-5ea5-44bc-91d1-5ed3041e07fa.png">
<img width="1535" alt="DMS-17451-2" src="https://user-images.githubusercontent.com/12569493/167104464-df838933-2776-4e5c-b38a-af3c3b7555eb.png">

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {SAP Ariba}
- Business impact: {affects language testing}

**Comment by niyap** [comment]
Hello Colleagues,

For the first reported issue, the "OK" button text is "OK" in Bulgarian and French as well. I checked the translation files and the translation is "OK" both in Bulgarian and French, both in WebComponents and UI5. So, could you please check with the translation team whether that is the expected result or the translation is incorrect?

For the second reported issue, please check the screenshots provided. The label for AM/PM when translated in Bulgarian is cut off and not fully visible. Also, the arrow up is placed over it, which makes it difficult to be read out.
Both issues are reproducible in the Playground.

![Screenshot 2022-05-10 at 9 20 04](https://user-images.githubusercontent.com/38278268/167561268-c87c6f3f-dc86-4102-ba80-a7ccec836d86.png)


Could you please look over?

Kind Regards,
Niya

**Comment by janakikeerthi277** [comment]
Hi @niyap @tsanislavgatev ,

Is there any update on this issue?

Regards,
Janaki

**Comment by tsanislavgatev** [comment]
Hello @janakikeerthi277 ,

After consultation with our translation experts, the OK button is corectly translated to french and bulgarian as OK.
For the second issue we are looking for a suitable desing, to be able to hold labels this large.

Best Regards,
Tsanislav
