### ISSUE TITLE
Text of SuggestionItem always gets populated in input area while selecting a SuggestionItem

### ISSUE THREAD

**Issue by AslamAlt** [SAP/ui5-webcomponents#5182]
### **Bug Description**

According to the [Fiori guidelines for Multi Input](https://experience.sap.com/fiori-design-web/multiinput/#adding-tokens) clicking a SuggestionItem should add a token and be ready for the next input, i.e., the input area must be cleared of all text except for the tokens. 
Observed: Just text is getting added in the MultiInput input area.

Now I am able to populate the input field with tokens using the `onSuggestionItemSelect` prop. However I'm not able to clear the text using `event.preventDefault()` or similar.
✖️ 
![Screenshot 2022-05-06 at 10 18 33 PM](https://user-images.githubusercontent.com/36098039/167176853-377e6df5-9967-4fe1-8cef-92ea8271fa01.png)

### **Expected Behavior**
On selecting a SuggestionItem, `onSuggestionItemSelect` must be fired and any text in the input area must be cleared (or at least an option to have the text cleared via a prop to the MultiInput component).
🟢 
![Screenshot 2022-05-06 at 10 17 47 PM](https://user-images.githubusercontent.com/36098039/167176734-1420bb3d-44f3-4445-a8aa-0822d4feef54.png)

### **Isolated Example**
[CodeSandbox](https://codesandbox.io/s/focused-sutherland-f0mgn2?file=/src/App.tsx).

### **Context**
- UI5 React Web Components version: {0.22.4}
- OS/Platform: Any
- Browser: Any
- Affected component: `MultiInput`

### **Log Output / Stack Trace / Screenshots**
```
{...}
```
### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-rl can you take a look of this issue.

**Comment by AslamAlt** [comment]
Hi all, there is also another [Fiori design guideline](https://experience.sap.com/fiori-design-web/multiinput/#reviewing-tokens) being violated by the `MultiInput` component:
![Screenshot 2022-05-16 at 10 07 30 AM](https://user-images.githubusercontent.com/36098039/168520713-67a3a3bf-23df-4dd6-845d-c435f15825b3.png)

As mentioned above, when there's only one token in the input area, the token must be visible with the text truncated with an ellipsis. However right now, the token, if too long for the input area, becomes "1 More" on focussing out of the `MultiInput`. I've updated the first suggestionItem in the [CodeSandbox](https://codesandbox.io/s/focused-sutherland-f0mgn2?file=/src/App.tsx) to show this behaviour. If you do take this up as a bug, requesting you to provide a way to circumvent default behaviours as well; there might be someone who doesn't need their token text being truncated, in case of single token. Thank you!

**Comment by MapTo0** [comment]
Hey @AslamAlt 

Regarding the initial issue.

Creating or not a token is decided in the application as shown in this [example](https://sap.github.io/ui5-webcomponents/master/playground/components/MultiInput/#token-unique).
We don't really know if a token is crated or not so we can not clear the input, we have left that responsibility to the application.
We provided enough events so the application can react on any user interaction.

Clearing the value could be achieved by just setting the value property to "";

`event.target.value = "";`

Regarding issue 2:

This looks like a feature we have never implemented and I advice you to raise a feature request about that.
We will get it planned and implemented as stated in the guidelines.

Regards,
Martin
