### ISSUE TITLE
Component "ui5-select" no longer dynamically resize to fit the longer text.  

### ISSUE THREAD

**Issue by Shike-m** [SAP/ui5-webcomponents#5184]
### **Bug Description**
ui5-select only display part of longer text like below. The rest of the text is hidden.
![image](https://user-images.githubusercontent.com/39100533/167235435-072700d0-c8b4-4825-b950-c01916a87220.png)
But in previous ui5 version, the whole text will be shown like below screenshot.
![image](https://user-images.githubusercontent.com/39100533/167235483-950cd455-d483-42e8-8ebc-3d2d508c8088.png)

### **Expected Behavior**
Like before, ui5-select can dynamically resize to fit the longer text.

### **Steps to Reproduce**
1. Create a ui5-select like the basic Select in UI5 Web Components example like screenshot below:
![image](https://user-images.githubusercontent.com/39100533/167235763-eae423b4-9d37-48f4-a9ad-bf849dd333be.png)
2. Change the tablet text to longer text, the component only show part of the text.

### **Isolated Example**
If possible, please provide an isolated example by forking [CodeSandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html). 
Follow the above "Steps to Reproduce" in the CodeSandbox, import the Select component in src/index.js and copy the example code in github into the index.html. After making longer the any of the dropdown texts, the issue will happen on the right page of the Codesandbox.

### **Context**
- UI5 Web Components version: 1.3.1
- OS/Platform: Window 10 or MacOS 12.3.1
- Browser: Chrome 101.0.4951.54
- Affected component: ui5-select.

### **Log Output / Stack Trace / Screenshots**
Screenshots like above.

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SF.
- Business impact: Medium.

**Comment by hristop** [comment]
Hello @ui5-webcomponents-topic-p,

Can you please take a look at this issue?

Best Regards,
Hristo

**Comment by Shike-m** [comment]
Based on the customer push, I hoist the priority. Thank you.
