### ISSUE TITLE
DateTimePicker loading external resource CLDR data for locale gives CSP error

### ISSUE THREAD

**Issue by henriquemattos** [SAP/ui5-webcomponents#5189]
### **Bug Description**
When using DataTimePicker, the component tries to load CLDR data for locale (en) from https://ui5.sap.com/1.60.2/resources/sap/ui/core/cldr/en.json but **internal application's Content Security Policy (CSP) doesn't allow external resources** to be downloaded (this would also impact "offline applications"). How can we workaround?

### **Expected Behavior**
I would expected that NPM packages are "self-contained" and external dependencies would be included during NPM install.

### **Steps to Reproduce**
1. Try to load component DateTimePicker
```javascript
<ui5-datetime-picker
	id="myDateTimePicker"
	format-pattern="dd/MM/yyyy, hh:mm:ss aa"
	value="13/04/2020, 03:16:16 AM"
></ui5-datetime-picker>
```
2. Check console error from [asset-registries/LocaleData](https://github.com/SAP/ui5-webcomponents/blob/master/packages/base/src/asset-registries/LocaleData.js#L150):
```sh
Content Security Policy: The page’s settings observed the loading of a resource at https://ui5.sap.com/1.60.2/resources/sap/ui/core/cldr/en.json (“connect-src”). A CSP report is being sent.

Uncaught (in promise) Error: CLDR data for locale en is not loaded!
```

### **Isolated Example**
--

### **Context**
- UI5 Web Components version: 1.3.0
- OS/Platform: Any
- Browser: Any
- Affected component: DateTimePicker

### **Log Output / Stack Trace / Screenshots**
<img width="1512" alt="Screenshot 2022-05-09 at 18 40 34" src="https://user-images.githubusercontent.com/2782214/167457302-ada939cd-b55e-4f80-96e7-257f32a3cfa7.png">

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact:  {...}

**Comment by ilhan007** [comment]
Hello @henriquemattos 

Did you import the Assets as described in the following article:
https://sap.github.io/ui5-webcomponents/playground/getting-started/using-assets/
 
If you did not if for example you are using `@ui5/webcomponents`,
try importing `@ui5/webcomponents/dist/Assets.js` and this will import the localization assets.
 
 Best Regards,
 ilhan

**Comment by henriquemattos** [comment]
Hi, @ilhan007 . Thanks a lot for your answer. It seems to be working if I include the Assets.

Since the content is in the repository and it's a required dependency, wouldn't it be better to import it directly from DateTimePicker?

My assumption is that bundling everything with Node will have the same benefit as hosting some assets in a CDN, so I don't see the case where a developer would import DateTimePicker from node_modules but wants use a CDN to host LocaleData. What do you think?
