### ISSUE TITLE
Calendar Month Focus Issue

### ISSUE THREAD

**Issue by fifoosid** [SAP/ui5-webcomponents#5190]
### **Bug Description**
Calendar doesn't behave consistently when pressing the month button

### **Expected Behavior**
Every time you click the months button in order to select a month, the behaviour of the component should be consistent.

### **Context**
- UI5 Web Components version: master

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by tsanislavgatev** [comment]
Due to insufficient information, I am closing this issue.
