### ISSUE TITLE
Query regarding ShellBarItem in the element inspector

### ISSUE THREAD

**Issue by Bilal3120** [SAP/ui5-webcomponents#5206]
### **Bug Description**
The shell bar item in element inspector is taking to a newly created shadow root instead of the actual ShellBarItem tag. Adding testid to the ShellBarItem tag is not adding the same to the shadow root element.

### **Expected Behavior**
A testid should be added to shadow element created by the shell bar item.

### **Steps to Reproduce**
1. Go to [codesandbox](https://codesandbox.io/s/heuristic-jepsen-wdp4my?file=/src/App.js)
2. Inspect the "error" icon
3. data-testid is missing from the shadow element

### **Screenshots**
![41C37210-1E4B-4B75-ADE6-EF67A649D1E6_1_201_a](https://user-images.githubusercontent.com/93638146/168051356-d469cabe-e496-41e1-88d8-874d2f5276e6.jpeg)

 **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by hristop** [comment]
Hi @Bilal3120 ,

The ShellBarItem does not support such property and that is why there is no way to propagate it further. 
Can you please explain more about your use case so we can better understand it? 

Best Regards,
Hristo

**Comment by Bilal3120** [comment]
Hi @hristop,

We need to uniquely identify a ShellBarItem by inspecting on the UI. Is there a way we can identify particular ShellBarItem among others, any ID field or any other unique field to identify a particular ShellBarItem?

Thanks and regards,
Bilal Ahmed Pasha

**Comment by ilhan007** [comment]
Hello guys,
this might help https://github.com/SAP/ui5-webcomponents/pull/4604


Developers can set a `stable-dom-ref` attribute on an abstract item, this same value will be used for the `data-ui5-stable` value of its physical counterpart in the parent's shadow root.

**Example**:

Consider the following HTML:
```html
<ui5-shellbar>
	<ui5-shellbar-item icon="accelerated" text="Hello World!" stable-dom-ref="schedule"></ui5-shellbar-item>
</ui5-shellbar>
```

Then:
```js
document.querySelector("[ui5-shellbar]").shadowRoot.querySelector(`[data-ui5-stable="schedule"]`))
```

**Comment by hristop** [comment]
Hi @Bilal3120 ,

Do you think the proposition provided by iLhan007 will work for you? 

Best Regards,
Hristo

**Comment by Bilal3120** [comment]
Hi @hristop, @ilhan007 

Thanks for the solution. It is working in our scenario hence closing the issue.

Thanks and regards,
Bilal Ahmed Pasha
