### ISSUE TITLE
[SF] [List]: onItemClick event returns wrong selected status

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents#5213]
**Describe the bug**
This is an SAP SuccessFactors product issue.
For a MultiSelect mode list, when you click the item, the onItemClick event will return the wrong selected status.
But if click the checkbox of the list item, the onItemClick event will return the correct selected status.

**Isolated Example**
https://codesandbox.io/s/customlistitem-selectedissue-omxprm

**To Reproduce**
1. Go to 'https://codesandbox.io/s/customlistitem-selectedissue-omxprm'
2. Click on custom list item and check the console log, you will see the wrong selected status returned.
3. Click on the checkbox of custom list item and check the console log, you will see the correct selected status returned.

**Expected behavior**
Click on custom list item and Click on the checkbox of custom list item should return the same selected status.

**Screenshots**
N/A

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.3.1
`@ui5/webcomponents-react` version: 0.23.1
Operating System:
Browser:

**Additional context**
Please put this issue as high priority.

**Comment by nnaydenow** [comment]
Hi @GongRichard,

Item click and selection change are two different things. item-click event is fired when the user clicks over the list item, then we internally make selection request and when the request is completed ( default behaviour of item-click could be prevented ) then selection-changed event is fired. To observe the correct information about selected items we suggest to use selection-change event.

Regards,
Nayden

**Comment by GongRichard** [comment]
Hi @nnaydenow,

From consuming side, no matter click the item or click the checkbox, it all means item click, so I think you need return same selected status.

Thanks,
Richard
