### ISSUE TITLE
[SF][Urgent][1.3.1][UI5-Table][SAP Horizon] UI5 Table should have border radius in horizon theme

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents#5215]
Dear Colleagues
I am from SAP SuccessFactors Shanghai Team

**Version**
1.3.1

**Bug Description**
UI5 Table should have border radius in horizon theme, but now ui5 table does not have border radius in horizon theme

 **Priority**
High

**Comment by ilhan007** [comment]
Hello @sfsf-xweb-sh the issue has been raised by you a month ago
https://github.com/SAP/ui5-webcomponents/issues/5010

Unfortunately, the answer remains the same - the border radius is specified for the Table header and footer and the Table web component does not provide neither a header, nor a footer.
