### ISSUE TITLE
[SF]Link color is not correct

### ISSUE THREAD

**Issue by QiuranHu** [SAP/ui5-webcomponents#5218]
### **Bug Description**
Link color is not correct. In current version (1.3.1), if the link has not been visited, the color of the link is the default link color of chrome.

### **Expected Behavior**
Link color should be correct.

### **Steps to Reproduce**
1. Go to https://codesandbox.io/s/zealous-panka-qmzowj?file=/src/App.js
2. Check the link color.
![image](https://user-images.githubusercontent.com/55808904/168558720-3cbbe787-e17c-4b3c-abd2-4696209e66c7.png)

### **Isolated Example**
 https://codesandbox.io/s/zealous-panka-qmzowj?file=/src/App.js

### **Context**
- UI5 Web Components version: 1.3.1
- OS/Platform: Windows 10
- Browser: 101.0.4951.54 (Official Build) (64-bit)
- Affected component: Link

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### **Stakeholder Info** (if applicable)

- Organization: SAP SuccessFactors

**Comment by LidiyaGeorgieva** [comment]
Hello @SAP/ui5-webcomponents-topic-b, take a look of this bug.
