### ISSUE TITLE
Scrollbar appearing for Page and DynamicPage components without overflow

### ISSUE THREAD

**Issue by mihirahlawat** [SAP/ui5-webcomponents#5220]
### **Bug Description**
For Page and DynamicPage components, a scrollbar appears even when the Page/DynamicPage is not overflowing.

### **Expected Behavior**
The scrollbar should not appear at all.

### **Isolated Example**
https://codesandbox.io/s/silly-elgamal-8g97w?file=/src/App.js:318-344

<img width="370" alt="image" src="https://user-images.githubusercontent.com/38140078/168579550-52fe5615-099e-4af0-b96f-b3de3fec31a6.png">

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

**Comment by LidiyaGeorgieva** [comment]
Hello @ui5-webcomponents-topic-rl please have a look at this issue.
