### ISSUE TITLE
Do we have any property to control the size of the illustratedMessage icons.

### ISSUE THREAD

**Issue by Harshithagc18** [SAP/ui5-webcomponents#5221]
### **Feature Request Description**
Do we have any property to control the size of the illustratedMessage icons? By default size of illustratedMessage is somewhat big and we want to control the size of illustratedMessage icon based on UX design and fit the screen

 This is the exact issue. This card, icon is overlapping with the card header. Please see the below image for a better understanding

### **Additional Context**
Attached the screenshot for better understanding.
![image](https://user-images.githubusercontent.com/105646889/168591611-fcf835eb-1508-4f48-bbb1-4f525484ba50.png)

### **Priority**
- [x] Medium

**Comment by ilhan007** [comment]
Hello @Harshithagc18 
thank you for the request. As I asked offline what do you prefer?

- several predefined [sizes] as in OpenUI5 [sap.m.IllustratedMessage](https://openui5nightly.hana.ondemand.com/entity/sap.m.IllustratedMessage/sample/sap.m.sample.IllustratedMessageInCardNoActivities) offers several predefined sizes [IllustratedMessageSize](https://openui5nightly.hana.ondemand.com/api/sap.m.IllustratedMessageSize) that you can pick from - Base, Dialog, Scene, Spot.
- to set a custom size

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-p it seems like a feature request to control the size of the illustration, but first could you check if the illustration should have adapt and fit in the card as shown in the image.

**Comment by Harshithagc18** [comment]
Hi @nnaydenow, In our project. when there are two cards on one page then the card size is smaller. So illustratedMessage icon is going to the header section. The expected behavior should be icon should get fit inside the content width. Based on content width it should get fit inside that card content.
Please see the attached image. it should get fit inside that red section.
![image](https://user-images.githubusercontent.com/105646889/169014699-806332f3-c282-4bac-8824-ca9431d707b1.png)

**Comment by terezamch** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

Please, take a look of this feature request. The reporter needs the illustrated message to scale appropriately in height. 

Best regards,
Tereza

**Comment by nnaydenow** [comment]
Internal reference: 5746
