### ISSUE TITLE
[SF][ui5-avatar-group]: no title for custom overflowButton

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents#5224]
### **Bug Description**
The title of the custom overflow button won't be set.

### **Expected Behavior**
The tooltip of the custom overflow button should show when mouse over on it.

### **Steps to Reproduce**
1. Go to 'https://github.wdf.sap.corp/pages/xweb/goalmanagementx/app.html?mock&noFirstTimeGuidance#/goal-detail?targetUserId=undefined&templateType=tgm&templateId=583&id=11001'
2. mouse over on the Overflow Button of Avatar Group on the right bottom of the page, no tooltip will show
<img width="1143" alt="image" src="https://user-images.githubusercontent.com/13098801/168728078-0edd9237-7983-4c95-bf44-f0c33adc46a3.png">
3. check the dom, title attribute already be set on ui5-button, but not set in the shadow dom.
<img width="1567" alt="image" src="https://user-images.githubusercontent.com/13098801/168728468-9c741ff8-2604-46f0-8c15-9ecad02e66c7.png">

### **Context**
- UI5 Web Components version: {1.3.1}
- OS/Platform: {...}
- Browser: {...}
- Affected component: {ui5-avatar-group}

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### **Stakeholder Info** (if applicable)

- Organization: {SuccessFactors}

**Comment by LidiyaGeorgieva** [comment]
Hello @SAP/ui5-webcomponents-topic-p could you have a look?
