### ISSUE TITLE
date time picker

### ISSUE THREAD

**Issue by mehdijouan** [SAP/ui5-webcomponents#523]
Hello,

Thanks for the efforts you put in this major evolution of SAPUI5!
I would like to use a datetime picker but I only found the date one. Did I missed something ?
If no, do you plan to implement it like the [fiori 3 recommendation](https://experience.sap.com/fiori-design-web/datetime-picker/) ?

In order to wait for it, I'm going to use the date picker and an additional one for the time.

Thanks in advance for your help!

**Comment by ilhan007** [comment]
Hello @mehdijouan thanks for the words!
You did not miss anything, there is a ui5-datepicker.
And, currently we don't provide datetimepicker.

Honestly, It was not in the plans for 1.0.0 release,
but I will bring it to table and get back to you with more information.

Kind regards,
ilhan

**Comment by sachinbhutani** [comment]
is date range selection on the roadmap ? 
similar to https://openui5.hana.ondemand.com/#/entity/sap.m.DateRangeSelection

**Comment by ilhan007** [comment]
Hello @mehdijouan 

I would like to inform you that we have introduced DateTimePicker with the latest "next" tag release in npm. It will be later released with 1.0.0-rc.7

Fixed with: https://github.com/SAP/ui5-webcomponents/pull/1437

Best,
ilhan

**Comment by mehdijouan** [comment]
Thanks! I'm eager to try it!
