### ISSUE TITLE
[SF][ui5-bar][sap_horizon]: The shadow of hovered transparent button in the Bar is cut off when the Bar is shrinked

### ISSUE THREAD

**Issue by BennyHuang** [SAP/ui5-webcomponents#5231]
### **Bug Description**
With sap_horizon theme, the shadow of the hovered transparent button in the Bar is cut off when the Bar is shrinked.

### **Expected Behavior**
The shadow of the hovered button should not be cut off. 

### **Steps to Reproduce**
It can be reproduced in https://sap.github.io/ui5-webcomponents-react/?path=/story/layouts-floorplans-bar--with-custom-elements&globals=theme:sap_horizon. After opening the page, narrow the canvas to make the bar shrinked and hover on the Navigate Back button in the sample You will see the shadow is cut off. 

### **Context**
- UI5 Web Components version: 1.3.1
- Browser: latest chrome
- Affected component: ui5-bar

### **Log Output / Stack Trace / Screenshots**
<img width="1031" alt="image" src="https://user-images.githubusercontent.com/1995447/168938183-8b04905e-02d5-4489-9cc5-aa5935e6b8e5.png">

### **Priority**
- [x] Low
- [ ] Medium
- [ ] High
- [ ] Very High

### **Stakeholder Info** (if applicable)

- Organization: SF

**Comment by LidiyaGeorgieva** [comment]
Hello @SAP/ui5-webcomponents-topic-b please have a look at this issue.
