### ISSUE TITLE
load more button is off by a col when in MultiSelect mode [Table]

### ISSUE THREAD

**Issue by szabadkai** [SAP/ui5-webcomponents#5234]
### **Bug Description**
When using the table in multi select mode, the load more button is one col short, looking off.

### **Expected Behavior**
The load more button should span the whole row as in every other mode.

### **Steps to Reproduce**
![image](https://user-images.githubusercontent.com/5462129/169004245-af5b6ea5-827f-42a8-b513-b205344823aa.png)

### **Context**
- UI5 Web Components version: 1.0.2
- OS/Platform: {MacOS}
- Browser: {Chrome}
- Affected component: {Table}

### **Log Output / Stack Trace / Screenshots**
```
{...}
```
### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by LidiyaGeorgieva** [comment]
Hello @szabadkai ,

Please provide reproducible sample in https://codesandbox.io/ (for example)
In the Playground the button looks normal: https://sap.github.io/ui5-webcomponents/playground/components/Table/
![image](https://user-images.githubusercontent.com/7242508/169029678-6e265600-89ed-4732-8aa9-14d3c3530a90.png)

Best Regards,
Lidiya
