### ISSUE TITLE
ui5-table Dark Mode

### ISSUE THREAD

**Issue by geokas7** [SAP/ui5-webcomponents#5243]
Hello,

I use ui5-table component in multi select mode. I was wondering if i can change the table style to dark mode (change row and select button background color). 

Best,
George

**Comment by LidiyaGeorgieva** [comment]
Hello @geokas7, you can use "sap_fiori_3_dark" theme or you can create custom dark theme (more information here: https://sap.github.io/ui5-webcomponents/playground/customizing/theme/)
