### ISSUE TITLE
MultiInput : Can we have a property valueHelpOnly like in ui5 library 

### ISSUE THREAD

**Issue by Arora05** [SAP/ui5-webcomponents#5245]
**MultiInput : Can we have a property valueHelpOnly like in the ui5 library **
MultiInput: Can we have a property valueHelpOnly like in the ui5 library because in our use case we don't want multiInput with value help to be input enabled only data that can be inserted by the user should be in the form of tokens using value help dialog as shown in https://sapui5.hana.ondemand.com/#/api/sap.m.MultiInput%23controlProperties
![image](https://user-images.githubusercontent.com/89779778/169105229-6c71f81b-dfe6-4bda-b7f6-3d1f5fbea2f6.png)

**Comment by LidiyaGeorgieva** [comment]
Hello @SAP/ui5-webcomponents-topic-rl , have a look at this issue.

**Comment by nikolay-kolarov** [comment]
Duplicated with https://github.com/SAP/ui5-webcomponents/issues/5045.
Please check my comments for more details.
The feature is against usability and accessibility, so I cannot accept and implement it.
