### ISSUE TITLE
ui5-panel: cursor styling for the content is set to "pointer"

### ISSUE THREAD

**Issue by winterkind** [SAP/ui5-webcomponents#5248]
### **Bug Description**
The `cursor` style for the entire (non-fixed) panel is set to 'pointer'. Not sure if that is intended; I find it surprising, so I report it here for your review.

### **Expected Behavior**
I expect the cursor to be a pointer when hovering over the panel header. But hovering over the content, I expect it to be the default cursor.

### **Steps to Reproduce**
1. Go to [the documentation page for ui5-panel.](https://sap.github.io/ui5-webcomponents/playground/components/Panel/)
2. Hover the mouse over the first example, "Basic Panel".
3. Note that the cursor turns into a pointer not only over the panel header but also the panel content, even though that content is not interactive.

### **Isolated Example**
See above.

### **Context**
- UI5 Web Components version: 1.3.1
- OS/Platform: Win 10
- Browser: Chrome
- Affected component: ui5-panel

### **Priority**
- [x] Low
- [ ] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by LidiyaGeorgieva** [comment]
Hello @SAP/ui5-webcomponents-topic-rl, please have a look at this issue.
