### ISSUE TITLE
Vertically resizing window does not recenter the Dialog in 1.3.X

### ISSUE THREAD

**Issue by codefactor** [SAP/ui5-webcomponents#5259]
### **Bug Description**
The Dialog does not recenter if you resize the window vertically.

### **Expected Behavior**
The Dialog should recenter/resize when you resize the window.

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/Dialog/
2. Open the dialog
3. Resize the window, but only vertically

### **Isolated Example**
Not necessary - it's easily reproduced.

### **Context**
- UI5 Web Components version: 1.3.X

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SuccessFactors
- Business impact: {...}

**Comment by terezamch** [comment]
Hello @SAP/ui5-webcomponents-topic-rd,

When resizing the browser window vertically, the Dialog doesn't resize properly, which can be observed in the playground https://sap.github.io/ui5-webcomponents/playground/components/Dialog/.
When the window is resized to smaller than the Dialog size - the headers gets cut and hidden. When the window is resized back - the Dialog does not get to the initial position.

Best regards,
Tereza

**Comment by codefactor** [comment]
Any update on this?

This seems like a major regression issue to me.
