### ISSUE TITLE
Popover: Unwanted focus

### ISSUE THREAD

**Issue by I516406** [SAP/ui5-webcomponents#5261]
There is unwanted focus on the first button inside a popover.

[CodeSandbox](https://codesandbox.io/s/silly-brown-d7i4r3?file=/src/App.js).

**To Reproduce**
1. Go to [CodeSandbox](https://codesandbox.io/s/silly-brown-d7i4r3?file=/src/App.js).
2. Click on Add button
3. See that the first button - Supplier Group has a focus 

**Expected behavior**
The popover buttons should not have any focus. Specially in horizon theme, the focus is quite bold in nature and gives a wrong sense to the user that the option is pre selected.

**Comment by terezamch** [comment]
Hello @I516406 ,

This is the focus behaviour by design - when the popover is opened, the first focusable element gets focused. You can set the focus further using the initialFocus property of the component https://sap.github.io/ui5-webcomponents/playground/components/Popover/

Best regards,
Tereza
