### ISSUE TITLE
sap-icon://bookmark-2 not loading

### ISSUE THREAD

**Issue by lohitghongadi** [SAP/ui5-webcomponents#5263]
### **Bug Description**
The icon `sap-icon://bookmark-2` is not working properly

### **Expected Behavior**
When I use the `sap-icon://bookmark-2` icon, I should be able to see the mentioned icon.
<img width="286" alt="image" src="https://user-images.githubusercontent.com/50576445/169783175-ae862759-ca33-4cf4-bfad-60d587d6da3a.png">

### **Steps to Reproduce**
1. Use the `sap-icon://bookmark-2` as mentioned here- https://sap.github.io/ui5-webcomponents/playground/components/Icon/
2. It doesn't display anything

### **Isolated Example**
CodeSandbox - https://codesandbox.io/s/ui5-webcomponents-forked-dkdgv5?file=/index.html

### **Context**
- UI5 Web Components version: 1.3.1
- Browser: All browsers
- Affected component: @ui5/webcomponents-icons

### **Log Output / Stack Trace / Screenshots**
```
Required icon is not registered. Invalid icon name: bookmark-2 

```
### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SAP
- Business impact: {...}

**Comment by terezamch** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

It looks like icon with name "sap-icon://bookmark-2" is not rendered.
Please see https://sap.github.io/ui5-webcomponents/playground/components/Icon/ 
Probably there is something wrong with the d property of the path svg tag.

Could you please have a look?

Best regards,
Tereza
