### ISSUE TITLE
ui5-dialog: resizable dialog with footer can become too small

### ISSUE THREAD

**Issue by winterkind** [SAP/ui5-webcomponents#5265]
### **Bug Description**
When a dialog has a footer and is resizable, then the height of the dialog can become so small that the footer disappears. See steps to reproduce.

You could of course say that you cannot know what people put into the footer so that you do not know by what amount to increase the minimum height of a dialog if it has a footer. But then it would be great to have a sample in the documentation that shows how you recommend developers handle that case. E.g. setting a min-height to the ui5-dialog itself works today - but is that "safe" going forward? Using the CSS shadow part "footer" to set a minimum height did not work - the footer still disappears.

### **Expected Behavior**
One of the two options:
1. When a resizable dialog has a footer (and/or header), it should not be possible to resize the dialog "over" the footer.
2. The sample in the documentation should show how to safely manage such a case.

### **Steps to Reproduce**
1. Go to the [documentation of ui5-dialog](https://sap.github.io/ui5-webcomponents/playground/components/Dialog/).
3. Open the second sample dialog in section "Draggable and Resizable Dialog".
4. Make the dialog as small as possible by resizing it.
5. Note that the footer almost completely disappears.

### **Isolated Example**
See above.

### **Context**
- UI5 Web Components version: 1.3.1
- OS/Platform: Win 10
- Browser: Firefox
- Affected component: ui5-dialog

### **Log Output / Stack Trace / Screenshots**
```
{...}
```
### **Priority**
- [x] Low
- [ ] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by terezamch** [comment]
Hello @SAP/ui5-webcomponents-topic-rd,

When the dialog is resizable and there is a footer, the dialog can be resized to hide the footer. Can be reproduced in the [playground](https://sap.github.io/ui5-webcomponents/playground/components/Dialog/) with the second sample.

Please have a look,

Best regards,
Tereza
