### ISSUE TITLE
ui5-link color issues

### ISSUE THREAD

**Issue by ee92** [SAP/ui5-webcomponents#5267]
### **Bug Description**
ui5-link does not respect the color from inline styles
the change was introduced here: https://github.com/SAP/ui5-webcomponents/commit/ee44117ea11e6c0eec36ac9079fc90aa6356143d#diff-33a57c65c7633f6a842a56a7f7372857fcfd1c8144f0e1c295193b2735d809d8R60-R66

\* another change introduced is that the link color is no longer the same for all states, and now has a different color for visited links

### **Expected Behavior**
Expect the ui5-link to respect color from inline styles. 

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/Link/
2. Add attribute to ui5-link `style="color: green"`
3. Notice the link color is still blue

### **Context**
- UI5 Web Components version: 1.3.0
- Affected component: ui5-link

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### **Stakeholder Info** (if applicable)

- Organization: SuccessFactors
- Business impact: Blocking upgrade to ui5-webcomponents 1.3.x

**Comment by terezamch** [comment]
Hello @ee92 ,

I don't really see any difference in the visited link vs. not visited. Otherwise, I will forward the issue about the inline style to the responsible team.

Best regards,
Tereza

**Comment by terezamch** [comment]
Hello @SAP/ui5-webcomponents-topic-b,

When inline style like style="color: green" is added to the ui5-link tag, it does not get applied.
To reproduce, open the [playground](https://sap.github.io/ui5-webcomponents/playground/components/Link/) and add style="color: green" to one of the links. 

Please, have a look.

Best regards,
Tereza

**Comment by ee92** [comment]
@terezamch Thanks for looking into it! 

There is a difference however, which can be reproduced on the demo page:

![Screen Shot 2022-05-25 at 4 58 25 PM](https://user-images.githubusercontent.com/24360164/170388534-8f49ee16-ec5c-4a49-9a51-44db18b9b6b2.png)

![Screen Shot 2022-05-25 at 4 59 08 PM](https://user-images.githubusercontent.com/24360164/170388673-c1073fa2-bf1d-49cc-9b9e-051288214eb6.png)

css rule:
![Screen Shot 2022-05-25 at 5 00 27 PM](https://user-images.githubusercontent.com/24360164/170388756-76f44ea5-2588-4045-8540-b12209d1f10c.png)

It's not a huge deal, but does affect a lot of links, and with no way to change the color it is a blocker for us.
