### ISSUE TITLE
ui5-menu-item. Fired a function when an item is being clicked

### ISSUE THREAD

**Issue by geokas7** [SAP/ui5-webcomponents#5269]
Hello,

We created a ui5-menu component with ui5-menu-items. We would like to trigger a function when a ui5-menu-item is being clicked. We tried with Ui5ItemName.addeventlistener('click', functionName) but it did not work. We can not find any solution in the documentation. Could you provide us a solution to this issue?

Best,
George

**Comment by terezamch** [comment]
Hello @geokas7 ,

Have you tried the item-click event of the menu?
<code>menu.addEventListener("item-click", function(event) {
	// custom logic
});</code>

Best regards,
Tereza

**Comment by geokas7** [comment]
Hello,

I just tried it. It works. Thank you.

Best regards,
George
