### ISSUE TITLE
Tab is collapsed when select it in first time and then propagates to others even when they have worked before

### ISSUE THREAD

**Issue by mikolayek** [SAP/ui5-webcomponents#5274]
### **Bug Description**
For some reason random **Tab** is collapsed when select it in first time and then it make other **Tab** also empty. sometimes double click on tab header helps, but not always.

I have seen similar issue https://github.com/SAP/ui5-webcomponents/issues/3423 where making tab container `fixed` helped, but not here.

I browse from left to right tabs and on 3rd tab I get nothing. then it propagates to next tabs too. When I click on first tab it sometimes it filled sometimes not, but double clicking on 1st tab finally shows content.

### **Expected Behavior**
All tabs have content defined and whole content should be visible while browsing.

### **Steps to Reproduce**
1. Go to 'https://codesandbox.io/s/thirsty-goldwasser-us6yhf?file=/src/repo-tabs.js'
I browse from left to right tabs and on 3rd tab I get nothing. then it propagates to next tabs too. When I click on first tab it sometimes it filled sometimes not, but double clicking on 1st tab finally shows content.

### **Context**
- UI5 Web Components version: 1.3.1
- OS/Platform: Mac
- Browser: Firefox
- Affected component: ui5-tabcontainer & ui5-tab

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

**Comment by terezamch** [comment]
Hello @mikolayek ,

Could you please explain in more detail what should I done when I open the codesandbox in order to reproduce the issue?
I tried clicking on the tabs from left to right (without collapsing them) and double clicking on the tabs from left to right (which makes them collapse) and I don't see anything wrong.

FYI, it would be more useful for reproduction, when the given sample is as minimalistic as possible.

Best regards,
Tereza

**Comment by mikolayek** [comment]
Hi Tereza.
I have recorded movie.
1 & 2 tab looks ok
When I click to 3'rd tab, there is nothing (where should be!), then on 4, 5 is also empty. All tabs have content.

then when I go in reverse, again 3,4,5 tab are empty but on top of that 2 tab also looks empty

when I click 2x on tab header it finally show right content. 

https://youtu.be/zxUQGhYsSKI

**Comment by mikolayek** [comment]
same issue is reproducible on official documentation: https://sap.github.io/ui5-webcomponents/playground/components/TabContainer/

I have just been clicking on **Basic TabContainer**, which is first one on top from tab 1 -> ... -> tab5 and on tab 3 I got issues, which stayed on tab3,4,5

**Comment by terezamch** [comment]
Hello @mikolayek ,

This issue is reproducible only in FireFox and is already fixed in the latest version of the project https://sap.github.io/ui5-webcomponents/master/playground/components/TabContainer/ 

Best regards,
Tereza
