### ISSUE TITLE
[SF] make public of announce in @ui5/webcomponents-base/dist/util/InvisibleMessage.js

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents#5285]
### **Feature Request Description**
Please make method announce in @ui5/webcomponents-base/dist/util/InvisibleMessage.js as public.
Is your feature request related to a problem? Please describe.
In SF product, we have lots of interaction need to inform screen reader user. 
Take a below screen shot as example: after user successfully changed status, we need invisible message announcement for screen reader user. 
<img width="581" alt="2022-05-26_23-01-40" src="https://user-images.githubusercontent.com/13098801/170516097-74343d56-f11b-4abd-86ff-3b4388627592.png">

### **Proposed Solution**
There already has method announce in @ui5/webcomponents-base/dist/util/InvisibleMessage.js, please make it public.
And one thing you need improve. After announce to screen reader, it needs to clear the message. You can check below openui5 code.
https://github.com/SAP/openui5/blob/master/src/sap.ui.core/src/sap/ui/core/InvisibleMessage.js#L108
<img width="817" alt="2022-05-26_23-08-29" src="https://user-images.githubusercontent.com/13098801/170517134-138a12f3-9abc-4d6b-9945-e4a8b3bde928.png">

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: {SAP SuccessFactors}
- Business impact: {...}

**Comment by terezamch** [comment]
Hello @SAP/ui5-webcomponents-team,

The reporter needs the announce method in the InvisibleMessage to be public. For all the details, please look into the description above.

Best regards,
Tereza
