### ISSUE TITLE
[SF][A11Y][Button]: some icon svg have role img in button

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents#5288]
### **Bug Description**
Hi Team,
When using icon property for ui5-button, some icon will render svg with role="img" and aria-label, witch will be announced when using screen reader.for example, ```<ui5-button icon="delete">remove item</ui5-button> ```will be announced "delete remove item".

### **Expected Behavior**
When using icon property for ui5-button, icon should render svg with role="presentation" and aria-hidden="true".

### **Steps to Reproduce**
1. open this [link](https://sap.github.io/ui5-webcomponents/playground/components/Button/)
2. check the button  with delete icon dom element using chrome dev tool.

### **Context**
- UI5 Web Components version: 1.3.1
- OS/Platform: all
- Browser: all
- Affected component: ui-button

### **Log Output / Stack Trace / 
Screenshots**
<img width="1406" alt="Screen Shot 2022-05-27 at 18 30 07" src="https://user-images.githubusercontent.com/78520316/170683808-ac2c3337-31af-46cc-b497-61cc1385fbab.png">

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SF
- Business impact: Medium

**Comment by terezamch** [comment]
Hello @SAP/ui5-webcomponents-topic-b,

The Button with icon and text should have role="presentation" and aria-hidden="true".

Could you please handle the issue?

Best regards,
Tereza

**Comment by unazko** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

By specification in the ui5-button with icon and text, the icon should be decorative, so only the text gets announced by the screen reader. There is nothing specific we do with the icons within the button though. Also there is no API for the icon, which
will allow us to set the icon as decorative. Instead there is a private property <code>accData</code>, which seems to have different set of parameters depending on the given icon. This influences if this icon will be recognized as decorative or not.

You could see here: https://sap.github.io/ui5-webcomponents/playground/components/Icon/
that from the first four icons some are decorative and some aren't, without any specific arguments supplied for that.

Currently I don't see how we could comply with the specification.
Any ideas or there should be an API developed for that?

Best Regards,
Boyan Rakilovski

**Comment by nnaydenow** [comment]
Hi @unazko,

You can use accessibleRole property of ui5-icon to set its role to decorative.

Regards,
Nayden
