### ISSUE TITLE
Cannot switch theme when bundled with parcel

### ISSUE THREAD

**Issue by killerfurbel** [SAP/ui5-webcomponents#5290]
### **Bug Description**

I created a bundle with parcel. Everything works fine, but I can't switch from the default theme sap_fiori_3 to any other theme.

### **Expected Behavior**

adding a `?sap-ui-theme=sap_fiori_3_dark` to the URL should switch to the dark theme

### **Steps to Reproduce**
1. [I created a code sandbox](https://codesandbox.io/s/parcel-test-etfuih)
2. just add `?sap-ui-theme=sap_fiori_3_dark` to the url on the right hand side
3. Check the DevTools Console: `Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '_')`

### **Isolated Example**
I couldn't use your template sandbox, because it fails on adding `import "@ui5/webcomponents/dist/Assets.js";` which is a prerequisite for using additional themes. I guess, this sandbox is not a container-sandbox?

However, I created a new sandbox (see above).

At first, I thought this is a parcel issue. However, I also created a `module.js` file with a similar JSON export. I can do an `await (import("./module.js")).default` without any issues. The code is in `main.js`, you just need to remove the comment in line 13 and run the bundling again (`node bundle.mjs`).

### **Context**
- UI5 Web Components version: 1.4.0
- OS/Platform: any
- Browser: Chrome
- Affected component: theme

### **Log Output / Stack Trace / Screenshots**
```
LocaleData.js:36 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '_')
    at ze (LocaleData.js:36:17)
    at async At (FontFace.css.js:4:11)
    at async Ft (FontFace.css.js:4:11)
    at async FontFace.css.js:4:11
```

![image](https://user-images.githubusercontent.com/8451067/170696582-89b13251-d782-4dd6-ad29-c13ce0231276.png)

As far as I can see, the `import()` is successful, but it doesn't contain a `default` export, instead the file is already returned by the `import()` directly. Therefore, `.default` is undefined leading to the error above ("cannot read properties of undefined (reading '_')").

### **Priority**
- [x] Low
- [ ] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by ilhan007** [comment]
Hello @killerfurbel thanks for reporting this.

I started from clear ground - the minimal codesandox setup. And, as you found out the assets import fails
```js
import "@ui5/webcomponents/dist/Assets.js";
```
with

```js 
TypeError
Cannot read properties of undefined (reading 'forEach')
```
It turns out that our JS module that includes JSON imports
```js
@ui5/webcomponents-theming/dist/generated/json-imports/Themes.js
```
was missing couple of ";" at the end of the methods and confused the parcel bundling.

After we added ";" everywhere needed, we released a preview version in NPM - 0.0.0-453158269
with theming working properly in codesandbox without additional effort.

Here is the codesandbox, consuming the preview version:
https://codesandbox.io/s/ui5-webcomponents-forked-8u7lb8

At some point the fix will be released along with the next stable version.

Best Regards,
ilhan
