### ISSUE TITLE
Select all checked even when there is no data. [Table]

### ISSUE THREAD

**Issue by szabadkai** [SAP/ui5-webcomponents#5294]
### **Bug Description**
In the table, when there isn't data to show. in multiselect mode the select all checkbox is ticked by default.

### **Expected Behavior**
For empty table checkbox should be unchecked or disabled

### **Steps to Reproduce**
![image](https://user-images.githubusercontent.com/5462129/170707679-b12f9dd1-117d-44e1-8d4e-c73462146a47.png)

### **Context**
- UI5 Web Components version: 1.3.2
- OS/Platform: MacOS
- Browser: chrome
- Affected component: Table

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: GoTo
- Business impact: looks weird

**Comment by terezamch** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

When a Table is in MultiSelect mode and there is no data, the "select all" checkbox can be checked. I am not sure what is the correct behaviour - should it be disabled, should the user be unable to check it or something else, but the currect behaviour seem wrong.

It can be reproduced in the [playground](https://sap.github.io/ui5-webcomponents/master/playground/components/Table/) when the table from "Table with No Data" example has mode="MultiSelect" or in the following [codesandbox](https://codesandbox.io/s/ui5-webcomponents-forked-4fc5y1?file=/index.html).

Best regards,
Tereza
