### ISSUE TITLE
Side Navigation with expandable item, bundled with Angular 13 doesn't display properly at first load in Firefox

### ISSUE THREAD

**Issue by ixiler** [SAP/ui5-webcomponents#5303]
### **Bug Description**
When displaying a <ui5-side-navigation> that has <ui5-side-navigation-item> with <ui5-side-navigation-sub-item>. The arrow that indicates that the <ui5-side-navigation-item> is expandable and the  <ui5-side-navigation-sub-item> of expanded such items are not displayed initially. They are only displayed after clicking on an item.

### **Expected Behavior**
The expandable arrow is displayed on first load as well as any expanded <ui5-side-navigation-item>.

### **Steps to Reproduce**
1. Open the provided reproduction in Firefox (use the Open in New Window functionality)
2. Observe the visualisation of the side navigation doesn't include an arrow and subitems for the navigation item.
3. Click on the item.
4. Observe that the arrow and subitems are visualised

### **Isolated Example**
The problem is reproduced when using the web components with Angular 13 so the provided reproduction is in [stackblitz](https://stackblitz.com/edit/angular-ivy-kltosp?file=src/app/app.component.ts) 

### **Context**
- UI5 Web Components version: {1.4.0}
- OS/Platform: {OS X}
- Browser: {Mozilla Firefox 100.0.2 (64-bit) }
- Affected component: {ui5-side-navigation}

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {SAP}
- Unit: {Automation Pilot}
- Business impact: {hindered Firefox users experience}

**Comment by PetyaMarkovaBogdanova** [comment]
Dear team,
can you, please, check this issue?
I can reproduce it also on Chrome Version 102.0.5005.61.

Regards,
Petya Markova.

**Comment by ixiler** [comment]
Hello, I have updated the reproduction to include the proposed workaround and the subitems still do not get displayed right away in Firefox.

**Comment by ixiler** [comment]
Hello, that bug is also present on Windows machines on all Browsers that we tested (Chrome, Edge, Firefox)
Are there any updates on that issue?

**Comment by kloyan** [comment]
Hello @ilhan007. The issue is still present even on the latest version 1.23.1. Do you have any plans to fix it soon? It makes this part of the component unusable for us...

Here's a link which reproduces it: https://stackblitz.com/edit/angular-ivy-txqtui

**Comment by nnaydenow** [comment]
Hi @kloyan, @ixiler,

Could you please check version 1.24.7 of the `@ui5` packages? I've updated it in the stackblitz provided by @kloyan and everything seems to be working as expected?

**Comment by ixiler** [comment]
Hi @nnaydenow,

The issue seems fixed in 1.24.7. 
Thank you!
