### ISSUE TITLE
How to hide valueStateText area from a control

### ISSUE THREAD

**Issue by saran85** [SAP/ui5-webcomponents#5313]
### **Bug Description**
1. How to hide valueStateText area from a control
2. I have a Combobox, whenever user selects "OPEN", it should show valueState as Error
3. This is working properly but no valueState Text required which I set as blank string i.e. valueStateText=" ",
4. that invalid Text is hidden but that space is still showing.
![image](https://user-images.githubusercontent.com/95576439/171655045-2b4ec538-1d6a-4824-ae0f-e069a5ea9faa.png)
![image](https://user-images.githubusercontent.com/95576439/171655098-b1e433e2-0d43-4e31-aee8-07583852fb33.png)
### **Expected Behavior**
so i need to hide the space of the valustate Message under the combobox.
![image](https://user-images.githubusercontent.com/95576439/171655519-6a0ad96c-ff3c-4ad8-8b34-aaffbfdb7de3.png)

### **Steps to Reproduce**
2. ...
6. ...

### **Isolated Example**
If possible, please provide an isolated example by forking [CodeSandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html).

### **Context**
- UI5 Web Components version: {...}
- OS/Platform: {...}
- Browser: {...}
- Affected component: {...}

### **Log Output / Stack Trace / Screenshots**
```
{...}
```
### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by PetyaMarkovaBogdanova** [comment]
Dear team,
can you, please, consult, if there is a way to remove the red label, showing "invalid entry" in ui5-multi-combobox with valueState = "Error", when no error text is presented.

Best regards,
Petya Markova.
(UI5 Web Components Dispatcher)

**Comment by niyap** [comment]
Hello @saran85,

As it was never implemented, we will handle it as a feature request not a bug.

Kind Regards,
Niya

**Comment by niyap** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

For the input components, currently there is no way to have value state without showing value state text. In openUI5 we have property "showValueStateMessage" for that purpose.
We have to evaluate whether it is possible to provide similar property in UI5 Web Components as well.

The feature request is regarding the ui5-combobox component.

Kind Regards,
Niya

**Comment by nikolay-kolarov** [comment]
Hi @saran85,

Could you please provide more info why you have this combination?
Why do you want to set the value state to error, without giving a clue to the users why it is in error state and how to be fixed?

Thanks,
Nikolay
