### ISSUE TITLE
[ui5-input] 'clear text' icon is misaligned vertically when the height of the ui5-input is changed to 24px

### ISSUE THREAD

**Issue by IvanKarlovich** [SAP/ui5-webcomponents#5314]
### **Bug Description**
When the height of ui5-input is changed to 24px (`height: 24px`), the 'clear text' icon becomes misaligned vertically. 

### **Expected Behavior**
The 'clear text' icon should stay aligned vertically by center when the size of the input is changed.

### **Steps to Reproduce**
1. Go to 'https://sap.github.io/ui5-webcomponents/playground/components/Input/?sap-ui-theme=sap_fiori_3&isrtl=false'
2. Find a sample input with 'clear text' icon. E.g. the very first sample.
3. Go to browser's DevTools and set the height of the corresponding ui5-input component to 24px (`height: 24px`).
4. Enter some text into the input.
5. Check how the 'clear text' icon looks in the ui5-input.

### **Isolated Example**
https://codesandbox.io/s/ui5-webcomponents-forked-ykz9te?file=/index.html

### **Context**
- UI5 Web Components version: 1.4.0
- OS/Platform: Win10
- Browser: Chrome
- Affected component: ui5-input

### **Log Output / Stack Trace / Screenshots**
![image](https://user-images.githubusercontent.com/11293959/171666945-e6f3c0dd-f6ba-4aec-872c-66fa0fe47f02.png)

### **Priority**
- [x] Low
- [ ] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by ilhan007** [comment]
Hello @IvanKarlovich thanks for reporting!

Do you really need to change the hight of the Input for your use-case or it's just testing and exploring the customization capabilities of the component. Could you give us some background?

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-rl it's questionable if this is a bug, but anyway you can explore ways to keep the icon centered when users set smaller or bigger height to the Input web component.

At first glance adding this might help (but I guess there are some cases to test):
```.css
.ui5-input-content {
  align-items: center
}
```

**Comment by IvanKarlovich** [comment]
> Hello @IvanKarlovich thanks for reporting!
> 
> Do you really need to change the hight of the Input for your use-case or it's just testing and exploring the customization capabilities of the component. Could you give us some background?

Hello, @ilhan007. Actually, we are using ui5-webcomponents at our project and the mockups we have from our UX team require that the height of the input components to be 24px.
