### ISSUE TITLE
ui5-rating-indicator: breaks in 1.4 when using scoping

### ISSUE THREAD

**Issue by winterkind** [SAP/ui5-webcomponents#5318]
### **Bug Description**
When using scoping, `ui5-rating-indicator` is broken in realease 1.4. It renders icons with the unscoped `ui5-icon`. E.g. when using scope "demo", a `ui5-rating-indicator-demo` will render `ui5-icon`, not `ui5-icon-demo`. The result is that the icons are invisible.

### **Expected Behavior**
The icons of the rating indicator should be visible even when using scoping.

### **Steps to Reproduce**
1. Go to https://svelte.dev/repl/e29f1159a3c5446c88c513e2ad51bffd?version=3.48.0
2. Wait a few seconds until everything is bundled and the example shows
3. You will see a button, an icon but no rating indicator. When inspecting the elements you will find that the rating indicator is there but the icons are all invisible because the rating indicator rendered them without the scope.

   I included a button because that is another component that renders a ui5-icon inside its shadow DOM. But there the scoped element name is used and it works.

### **Isolated Example**
https://svelte.dev/repl/e29f1159a3c5446c88c513e2ad51bffd?version=3.48.0

### **Context**
- UI5 Web Components version: 1.4.0
- OS/Platform: Win10
- Browser: Chrome
- Affected component: ui5-rating-indicator

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-rl  could you take a look - there is a linked PR adderssing the issue
