### ISSUE TITLE
[SF_ACC] Wrapping in ui5-multi-input suggestions and N-more popover

### ISSUE THREAD

**Issue by mdasari84** [SAP/ui5-webcomponents#5323]
### **Bug Description**
No tooltip to see the full token value when the token value is long on a small screen. Please refer to the attached screenshot.

### **Expected Behavior**
A tooltip to see the full value of the token when it is truncated

### **Steps to Reproduce**
1. Go to https://codesandbox.io/s/ui5-wc-multiinput-no-tooltip-rlgqkt?file=/src/index.js
2. Mouse hover on the token values

### **Isolated Example**
https://codesandbox.io/s/ui5-wc-multiinput-no-tooltip-rlgqkt?file=/src/index.js

### **Context**
- UI5 Web Components version: 1.3.x
- OS/Platform: Windows
- Browser: Chrome
- Affected component: MultiInput

### **Log Output / Stack Trace / Screenshots**
```
![MultiInput no tooltip](https://user-images.githubusercontent.com/84945056/171969376-3da79f93-f93b-421c-bc4b-07367bb8efa2.png)

```
### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SuccessFactors
- Business impact: {...}

**Comment by niyap** [comment]
Dear @SAP/ui5-webcomponents-topic-rl,

We have to discuss with the responsible team for StandardListItem whether is it feasible to introduce similar functionality like that in UI5: https://sapui5untested.int.sap.eu2.hana.ondemand.com/demokit/#/api/sap.m.StandardListItem "wrapping" and "wrapCharLimit" in order to be able to make the whole suggestion/selected item text visible and then to adopt it in ui5-multi-input web component.

Kind Regards,
Niya

**Comment by nikolay-kolarov** [comment]
Hello,

We have requested an enhancement of the list.
Once this is available, we can plan the adoption in the inputs.

Best Regards,
Nikolay

**Comment by hristop** [comment]
We have created internal BLI: BGSOFUIRILA-3636

**Comment by Okiana** [comment]
Hello @mdasari84,

The functionality could be expected with the next web components version - 1.18.0.

Kind Regards,
Evdokia
