### ISSUE TITLE
Support for \n (new line) in the Text web component.

### ISSUE THREAD

**Issue by mdasari84** [SAP/ui5-webcomponents#5330]
### **Feature Request Description**
Support for \n (new line) in the Text web component.

### **Proposed Solution**
We need something that SAPUI5 Text control already supports. 
Please check https://snippix.only.sap/#68876
![image](https://user-images.githubusercontent.com/84945056/172215893-bba4694b-f1b2-46c2-9a99-a22e033ab38d.png)

### **Proposed Alternatives**
No existing web component that supports \n

### **Additional Context**
Add other context or screenshots related to the feature request here.

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: SuccessFactors
- Business impact: {...}

**Comment by mdasari84** [comment]
hi @ilhan007 ,

Thanks for the reply!
We need to replace \n (new line) with <be> tags. I don't think "<ui5-label>Hello<br>World</ui5-label>" would be a proper solution. 

We are looking for something like https://sapui5.hana.ondemand.com/#/entity/sap.m.FormattedText/sample/sap.m.sample.FormattedText (SAPUI5) control which supports certain tags.

Thanks,
Madhu

**Comment by ilhan007** [comment]
Hello @mdasari84 
sorry but I can't entirely understand the need for this component. In OpenUI5 we have the FormattedText because app developers do not have access to the DOM and can't write HTML in XML views, but in your case you can add whatever tags needed directly in your page without restriction.

Maybe you can give more details about the use-case, why you need a component like the Formatted Text Control, where you will use it and for what, so that I can understand the better the need.

Best,
ilhan

**Comment by mdasari84** [comment]
hi @ilhan007 ,

Ok, got it.
We need something that supports \n in the text like https://snippix.only.sap/#68876.

"<ui5-label>Hello<br>World</ui5-label>" won't work because all \n needs to be replaced with <br> before rendering.

Thanks,
Madhu

**Comment by mdasari84** [comment]
@ilhan007, would you please provide an update. Thanks!!

**Comment by stoehr** [comment]
@mdasari84, if the requirement is simply to transform new-line characters within already encoded HTML, then something like `html.replace(/\n|\r\n?/g, '<br>')` would be a way to achieve the requirement.

**Comment by ilhan007** [comment]
Related to: https://github.com/SAP/ui5-webcomponents/issues/6788

**Comment by ilhan007** [comment]
Hello @mdasari84 is the request still relevant, does @stoehr's suggestion work for you?
