### ISSUE TITLE
[SF] AvatarGroup: not show Avatar when AvatarGroup in ResponsiveGridLayout

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents#5333]
**Describe the bug**
Avatar doesn't show when AvatarGroup in ResponsiveGridLayout

**Isolated Example**
https://codesandbox.io/s/avatargroup-notshow-nfmy1y?file=/src/App.js

**To Reproduce**
1. Go to 'https://codesandbox.io/s/avatargroup-notshow-nfmy1y?file=/src/App.js'
2. You will see Avatar will show in the left side of ResponsiveGridLayout, but not show in the right side.

**Expected behavior**
Avatar should show in both side.

**Screenshots**
<img width="755" alt="image" src="https://user-images.githubusercontent.com/13098801/172056631-b65a3243-8e40-4ebf-b231-8984b27766eb.png">

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.3.1
`@ui5/webcomponents-react` version:0.23.2
Operating System: MacOS
Browser: Chrome

**Additional context**
This issue was found in SAP SuccessFactors product development.

**Comment by niyap** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

There is a reproducible issue with the ui5-avatar-group web component. There is enough space to have some visible avatars but all have overflowed and are not visible.

Here is an isolated example: https://codesandbox.io/s/ui5-webcomponents-forked-09t9vb?file=/index.html

Could you please look over the issue?

Kind Regards,
Niya
