### ISSUE TITLE
Missing type definitions to use "Default string import for icons" in TypeScript

### ISSUE THREAD

**Issue by C3ntraX** [SAP/ui5-webcomponents#5335]
### **Bug Description**
I still cant use the named imports in 1.4 because the type definitions for typescript are missing. Its only working in JS.
So currently this feature is useless for typescript user. Please add support and maybe for the future add TypeScript test cases.

See #5122

### **Expected Behavior**
Use "Default string import for icons" in Typescript

### **Steps to Reproduce**
Use TypeScript.

### **Isolated Example**
Not needed

### **Context**
- UI5 Web Components version: {...}
- OS/Platform: {...}
- Browser: {...}
- Affected component: {...}

### **Log Output / Stack Trace / Screenshots**
```
{...}
```
### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by ilhan007** [comment]
related to: https://github.com/SAP/ui5-webcomponents/issues/4337

**Comment by ilhan007** [comment]
Hello @C3ntraX C3ntraX there is a snapshot version to add ts defs to icons - 0.0.0-cf50976ce

can you give it a try and let us know if now it works fine.

Here you can see a small example:
https://codesandbox.io/s/wcr-ts-template-forked-w9752k?file=/src/App.tsx

**Comment by C3ntraX** [comment]
Hello @ilhan007,

this snapshot works fine. Thanks!

**Comment by ilhan007** [comment]
Hello @C3ntraX thanks for testing, we have merged the related PR, the change will be released with 1.8.0 end of the month/start of Oct
