### ISSUE TITLE
ui5-menu-item - change height and font size

### ISSUE THREAD

**Issue by geokas7** [SAP/ui5-webcomponents#5337]
Hello,

We created a ui5-menu component with ui5-menu-items. We would like to change ui5-menu-item font-size and height in order to make it mobile responsible. We tried something like that:
<ui5-menu-item text="New File" style="font-size : 2em;" ></ui5-menu-item>
but it did not work. Could you provide any solution to this?

Best,
George

**Comment by niyap** [comment]
Hello @geokas7,

You have written "We tried something like that:" but the sample is missing.
Could you please adjust your description?

Thank you in advance!

Kind Regards,
Niya

**Comment by geokas7** [comment]
Hello,

We apologize for this typo. The example is:

<ui5-menu-item text="New Folder" id="newfolderElement" icon="dimension" style="font-size: 4em;" > </ui5-menu-item>

Best,
George

**Comment by niyap** [comment]
Hello @geokas7,

There is no way to change the font-size of the ui5-menu-item. The only way to achieve it is to adjust the font-style of all web components: https://sap.github.io/ui5-webcomponents/playground/customizing/theme/

Kind Regards,
Niya
