### ISSUE TITLE
[SF][BUG][UI5-Panel] The ui5-panel-header and ui5-panel-header-title Dom should be removed if the ui5-panel has no header

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents#5342]
I am from SuccessFactors Web Experience Shanghai team. 

**Bug description**
Website: [https://sap.github.io/ui5-webcomponents/playground/components/Panel/](https://sap.github.io/ui5-webcomponents/playground/components/Panel/)
For now,  header-text is not passed to ui5-panel, but ui5-panel-header and ui5-panel-header-title are still available in shadow dom. The ui5-panel-header and ui5-panel-header-title dom should be removed if the ui5-panel has no header

Expected Behavior:
The ui5-panel-header and ui5-panel-header-title Dom should be removed if the ui5-panel has no header

<img width="1293" alt="Screen Shot 2022-06-08 at 4 15 51 PM" src="https://user-images.githubusercontent.com/78520316/172570941-260088b9-8235-43b0-8217-4c1c8a036f8d.png">

**Comment by niyap** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

Currently, there is no way to remove the header from the ui5-panel. Even if header text is not set and there is no header presented, the header part is visualised empty. I checked in openUI5 and there it is possible to not have a header.
Could you please check whether is it expected to be able to not show the header part?

Thank you in advance!

Kind Regards,
Niya

**Comment by sfsf-xweb-sh** [comment]
Hi @niyap 

1. Because we use ui5-panel ( without header ) as container. ( like object section )
2. If ui5-panel has no header, the role="heading" will cause a11y issue

**Comment by nikolay-kolarov** [comment]
Hello @sfsf-xweb-sh,

Thanks for the info so far.
One additional question - then why do you need to use the panel at all? You want to have the styling or there is something else?
Doesn`t it make sense to use just a div in this case?

Thanks,
Nikolay

**Comment by sfsf-xweb-sh** [comment]
Hi @nikolay-kolarov 

This is recommended by UX team
We should use ui5-panel ( without header ) to do this
