### ISSUE TITLE
ui5-shellbar: use header semantic element

### ISSUE THREAD

**Issue by JarrettChan** [SAP/ui5-webcomponents#5348]
### **Bug Description**
Using `<div role="banner">` instead of `<header>` semantic element.
`<header>` is supported by modern browsers.
https://www.w3.org/TR/using-aria/#rule1

### **Expected Behavior**
Use `<header>` instead of `<div role="banner">`

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/ShellBar/
2. shadow root contains `<div role="banner">`

### **Context**
- UI5 Web Components version: 1.4.0
- OS/Platform: macOS 12.4
- Browser: Chrome 102.0.5005.61 (Official Build) (x86_64) 
- Affected component: ui5-shellbar

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### **Stakeholder Info** (if applicable)
- Organization: SuccessFactors

**Comment by niyap** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

Could you please check the proposed enhancement and analyse whether it is appropriate?

Thank you in advance!

Kind Regards,
Niya

**Comment by nikolay-kolarov** [comment]
Hello,

This is an enhancement request, but in the end there will be no difference for the mapping on the accessibility tree, as <header> equals to <dir role="banner">.
Therefore, there is no need to treat this with urgency, as it will not cause accessibility issue.

Best Regards,
Nikolay

**Comment by dobrinyonkov** [comment]
Internal reference: 5778

**Comment by JarrettChan** [comment]
https://github.com/SAP/ui5-webcomponents/pull/6146
