### ISSUE TITLE
Override List web component CSS 

### ISSUE THREAD

**Issue by mdasari84** [SAP/ui5-webcomponents#5349]
### **Bug Description**
Most of the application has 14px as the font size but List items have 16px. We would like to reduce it to 14px for the List items as well.

### **Expected Behavior**
Provide a way to override List web component font size

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/List/
2. Check the font size of the List items

### **Isolated Example**
If possible, please provide an isolated example by forking [CodeSandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html).

### **Context**
- UI5 Web Components version: 1.3
- OS/Platform: {...}
- Browser: {...}
- Affected component: List

### **Log Output / Stack Trace / Screenshots**
```
{...}
```
### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SuccessFactors
- Business impact: {...}

**Comment by ilhan007** [comment]
Hello @mdasari84 use the part="title", part="description" and part="additional-text" Shadow parts to set font-size 14px. Actually, only the list item title is bigger, the rest of the texts have 14px font-size.

If you are new to CSS Shadow Dom part selectors - read this [article](https://developer.mozilla.org/en-US/docs/Web/CSS/::part).

or basically you will need to add just this style:

```css
ui5-li::part(title) {
  /* Styles to apply to the `foo` part:  font-size: 14px*/
}
```

**Comment by mdasari84** [comment]
Thank you for the detailed explanation !!
