### ISSUE TITLE
[SF][DateTimePicker]: onBlur function will be excuted when open picker

### ISSUE THREAD

**Issue by yuyuCream** [SAP/ui5-webcomponents#5353]
**Describe the bug**
onBlur function will be excuted when open picker

**Isolated Example**
https://codesandbox.io/s/wispy-glitter-jszhex?file=/src/App.js

**To Reproduce**
1. Open date time picker
2. onblur function will be excuted and wrong value state wil be set to this component.

**Expected behavior**
Not invoke onBlur function when open picker for it's part of the component.

**Screenshots**
<img width="688" alt="image" src="https://user-images.githubusercontent.com/32004690/173036350-eb967937-5848-4b6f-a037-5bb463d73409.png">

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 14.0
`@ui5/webcomponents-react` version: 0.24.0
Operating System: mac
Browser: Chrome

**Additional context**
I am from SAP Successfactors. And issues are for b2211 released project.

**Comment by niyap** [comment]
Hello @yuyuCream,

As you can check in the documentation: https://sap.github.io/ui5-webcomponents/playground/components/DateTimePicker/ we do not support "blur" event, so in your use case it works by chance.

Kind Regards,
Niya
