### ISSUE TITLE
Not able to override the TreeItem CSS styles

### ISSUE THREAD

**Issue by mdasari84** [SAP/ui5-webcomponents#5359]
### **Bug Description**
Not able to override TreeItem CSS styles

### **Expected Behavior**
Should be able to override TreeItem CSS styles

### **Steps to Reproduce**
1. Go to https://codesandbox.io/s/ui5-webcomponents-tree-k0h6vf?file=/src/styles.css
2. I am trying to override the font size of the TreemItem. Please check styles.css.

### **Isolated Example**
If possible, please provide an isolated example by forking [CodeSandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html).

### **Context**
- UI5 Web Components version: 1.3.x
- OS/Platform: Windows
- Browser: Chrome
- Affected component: Tree

### **Log Output / Stack Trace / Screenshots**
```
{...}
```
### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SuccessFactors
- Business impact: {...}

**Comment by ilhan007** [comment]
Hello @mdasari84 

We had similar issue recently: https://github.com/SAP/ui5-webcomponents/issues/5346 and there we suggested using the available CSS Shadow parts. You can use the `title` part and overwrite the font-size.

BR,
ilhan

**Comment by mdasari84** [comment]
Hi @ilhan007 ,

Thanks for the quick response!
It doesn't work for me :(. Please check the example https://codesandbox.io/s/ui5-webcomponents-tree-k0h6vf?file=/src/styles.css

Thanks,
Madhu
