### ISSUE TITLE
[SF][ui5-avatar-group]AvatarGroup is shrunk even though there is enough space left

### ISSUE THREAD

**Issue by BennyHuang** [SAP/ui5-webcomponents#5360]
### **Bug Description**
The avatar group is shrunk even though there is enough space left.

### **Expected Behavior**
All the avatars in the group should be shown if there is enough space.

### **Steps to Reproduce**
There are 2 cases in our application
 **case 1**
<img width="1039" alt="image" src="https://user-images.githubusercontent.com/1995447/173464305-f82dae18-bc07-45ff-8bd2-4bc57e140041.png">
**case 2**
<img width="725" alt="image" src="https://user-images.githubusercontent.com/1995447/173466093-050eeb1d-f264-42de-9c00-ac272a0d6fb5.png">

### **Isolated Example**
It can be reproduced on https://codesandbox.io/s/avatargroup-shrunk-prvndz?file=/src/App.js
<img width="735" alt="image" src="https://user-images.githubusercontent.com/1995447/173465520-dcf8e0d2-d589-497e-95a7-78ec565e669c.png">

It can also be reproduced in full width window on https://prvndz.csb.app/

### **Context**
 - @ui5/webcomponents version: 1.3.1
 - @ui5/webcomponents-react version:0.23.0
 - Operating System: MacOS
 - Browser: Chrome

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SF

**Comment by dimovpetar** [comment]
Hello @SAP/ui5-webcomponents-topic-p ,
This is reproducible issue with the AvatarGroup. I was able to reproduce it on Windows with Chrome and Firefox.
Best regards,
Petar

**Comment by nnaydenow** [comment]
Hi @BennyHuang,

Issue is fixed with: #5357 

Regards,
Nayden
