### ISSUE TITLE
ComboBox: ComboBox truncation of text in ComboBoxItem is not visible

### ISSUE THREAD

**Issue by Arora05** [SAP/ui5-webcomponents#5362]
**ComboBox**
ComboBox truncation of text in ComboBoxItem is not visible.
Is there a way to get the tooltip on hover for text?

**Comment by dimovpetar** [comment]
Hello @Arora05 ,

Check this example: https://codesandbox.io/s/ui5-webcomponents-forked-j5wjpi?file=/index.html. Can you confirm that the issue you are describing is the same?

Best regards,
Petar

**Comment by Arora05** [comment]
Hello @dimovpetar, 
Yes, this is precisely what the bug is.
Thanks,
Kshitiz

**Comment by dimovpetar** [comment]
Hello @SAP/ui5-webcomponents-topic-rl ,

Long text is truncated inside ComboBoxItem, check out https://codesandbox.io/s/ui5-webcomponents-forked-j5wjpi?file=/index.html.
In OpenUI5 the suggestions popover is stretched to fit the text.

Best regards,
Petar
