### ISSUE TITLE
[SF][CheckBox][Fiori Next View]: Color of CheckBox Text

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents#5364]
Hi Colleague,

The color of CheckBox text is different to RadioButton text in Fiori Next theme(see screenshot), which is not acceptable from UX side. Here is the link of standard checkbox horizon design:https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2698913184 
Could you please help check it? 

Fiori Next View:
<img width="1062" alt="Screen Shot 2022-06-15 at 15 45 38" src="https://user-images.githubusercontent.com/78520316/173771946-d459d10c-3f54-40a2-b549-36a349b2b698.png">

In sap-ui-theme=sap_fiori_3 View, CheckBox text color is same with RadioButton.
<img width="643" alt="Screen Shot 2022-06-15 at 16 08 21" src="https://user-images.githubusercontent.com/78520316/173776441-a493869b-e096-4eb0-b07b-9ecf7ee4f05a.png">

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.4.0
`@ui5/webcomponents-react` version: 0.25.1

Thanks a lot!
Josephine Su

**Comment by dimovpetar** [comment]
Hello @SAP/ui5-webcomponents-topic-p ,

The value of CSS parameter `_ui5_checkbox_label_color` should be different in SAP Horizon, as far as I understood it should be `sapField_TextColor`. Currently it is `sapContent_LabelColor`.

Best regards,
Petar
