### ISSUE TITLE
Input -> SuggestionItem are not showing up correctly after async fetch of data

### ISSUE THREAD

**Issue by schempil** [SAP/ui5-webcomponents#5365]
### **Bug Description**
When I use the Input field field with `showSuggestions` with multiple `SuggestionItem` as children that are rendered depending on the data resulting out of an async call (fetching suggestion values from API) the rerendering stops working after the first time reliably. 
In our project we use [React Query](https://react-query.tanstack.com/) to fetch data from async sources. This results in the data being `undefined` while a query is loading.

I mocked an async behavior with the following codesandbox: https://codesandbox.io/s/wonderful-wright-713fgx

Just open it, type your first query (wait a few seconds) and adjust the input value and you will see once the data is not loading anymore, suggestionItems are correctly set in the state, but not showing up.

If you check the DOM with the dev tools, you can see the suggestion items are set up correctly, but not showing up. 

### **Expected Behavior**
The SuggestionItems should render correctly if there are SuggestionItems and will be visible.

### **Steps to Reproduce**
1. Go to https://codesandbox.io/s/wonderful-wright-713fgx
2. Enter query "Hello" in input field
3. Wait until `isLoading` shows `false`
4. See the suggestions (5) are showing up
5. Adjust query in input field to "Hello1"
6. Wait until `isLoading` shows `false`
7. See that the count of suggestions is set to `6` but now suggestions are showing up. Also check the DOM: There are 6 `ui5-suggestion-item` elements correctly positioned.

### **Isolated Example**
https://codesandbox.io/s/wonderful-wright-713fgx

### **Context**
- UI5 Web Components version: 1.4.0
- OS/Platform: Windows 10
- Browser: Google Chrome Version 102.0.5005.63 (Official Build) (64-bit)
- Affected component: https://sap.github.io/ui5-webcomponents/playground/components/Input/

### **Priority**
- [ ] Low
- [ ] Medium
- [X] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SAP SE
- Business impact: Application release date can be affected and postponed.

**Comment by dimovpetar** [comment]
Hello @SAP/ui5-webcomponents-topic-rl ,

The approach of adding suggestions here looks very similar to the [official sample](https://sap.github.io/ui5-webcomponents/playground/components/Input/), but implemented with React. However, there is something that is breaking it. Can you please check it?

Best regards,
Petar
