### ISSUE TITLE
Feature Request - Required ShortcutText property in MenuItem 

### ISSUE THREAD

**Issue by ShivamGuptaSap** [SAP/ui5-webcomponents#5369]
### **Feature Request Description**
In MenuItem we need a shortcutText property so that we can add shortcut texts along with the menu Item.

### **Proposed Solution**
Just like we have that property in Orca-React-UI

### **Additional Context**
Kindly refer to the screenshots:

Its Purpose:
![image](https://user-images.githubusercontent.com/107616257/174039259-06abb5e2-be26-4ee3-aa1d-ed6b4f34b336.png)

In Orca-React-UI they offer this:
![image](https://user-images.githubusercontent.com/107616257/174039091-7bd6f78a-2f99-402c-afb8-ffd5bf52accb.png)

### **Priority**
- [ ] Low
- [ ] Medium
- [ ] High
- [x] Very High

As we are in the middle of migrating the whole project "SAC Lite-Viewer" from Orca-React-UI to UI5-WebComponent for React. So we will be needing this feature on urgent basis.

### **Stakeholder Info** (if applicable)

- Organization: { SAP }
- Business impact: {...}

**Comment by dimovpetar** [comment]
Hello @SAP/ui5-webcomponents-topic-b ,

Take a look of this feature request for `shortcutText` property.

Best regards,
Petar

**Comment by scameron** [comment]
Hello @petyabegovska!  I just wanted to check in to see if you'd had a chance to look at this one yet.  Does it seem like something that might be possible?

**Comment by petyabegovska** [comment]
Hi @scameron,

Yes, it is possible technically, but I am waiting also for the UX/VD feedback.

One clarification question on your use case: Do you need to hide the text on mobile? (as there are no shortcuts there).

Best regards,
Petya

**Comment by scameron** [comment]
Sorry for the delay, @petyabegovska, I needed to double check with the team.  For our specific need, we will not be using the MenuItem control on mobile so we don't have any special requirement there.

But in general, I think what you're saying sounds correct, that it should probably be hideable for cases where shortcut keys don't make sense.  But our particular use case doesn't require this.

**Comment by ddrana** [comment]
Hi @petyabegovska , were you able to get any feedback from UX/VD team?

**Comment by scameron** [comment]
Hi @petyabegovska, just wanted to check in about this one again.  Does it seems like something that could be added to the component?
