### ISSUE TITLE
[SF][A11y][DatePicker] - When the date picker is opened, JAWS announces the entire calendar contents

### ISSUE THREAD

**Issue by 2bno1** [SAP/ui5-webcomponents#5379]
### **Bug Description**
Open the date picker -> observe all the contents of the date picker are announced.
![screenshot-1](https://user-images.githubusercontent.com/1751846/174509013-ee5cd084-7c84-4244-8712-c3e4c18054b0.png)

### **Expected Behavior**
Gregorian calendar modal dialog followed by the currently focused date is the expected announcement

### **Context**
- UI5 Web Components version: 1.4.0
- OS/Platform: macOS
- Browser: Chrome
- Affected component: uit-date-picker

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by unazko** [comment]
Hello @2bno1,

The is a known issue as reproducible via native HTML in here:
https://www.w3.org/TR/wai-aria-practices-1.1/examples/dialog-modal/dialog.html
Therefore we don't have a way to fix this issue.

Best Regards,
Boyan Rakilovski

**Comment by anuvenkatesh1** [comment]
@unazko Could you clarify if this is specifc to JAWS 2022 only or which version was used to reproduce this issue? We will document the same internally so we can avoid duplication of issues. 

Thanks
