### ISSUE TITLE
ui5-dialog with ui5-messagestrip inside announces entire content when opened

### ISSUE THREAD

**Issue by ee92** [SAP/ui5-webcomponents#5391]
### **Bug Description**
When a ui5-dialog is opened which has a ui5-messagestrip as its first element, the entire content of the dialog will be announced by screenreaders. 

### **Expected Behavior**
The dialog should not announce its entire content when opening, only the dialog title and the first focused element.

### **Steps to Reproduce**
0. Use screen reader (JAWS or NVDA)
1. Go to https://codesandbox.io/s/ui5-webcomponents-forked-ifp587
2. Open the first dialog
3. Notice it announces the dialog title and the first focused element as expected
4. Open the second dialog
5. Notice it announces the entire content of the dialog 

### **Isolated Example**
https://codesandbox.io/s/ui5-webcomponents-forked-ifp587

### **Context**
- UI5 Web Components version: 1.4.0
- Affected component: ui5-dialog, ui5-messagestrip

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### **Stakeholder Info**

- Organization: SuccessFactors

**Comment by nnaydenow** [comment]
Hi @ee92,

Could you please provide information which version of JAWS and NVDA use are using?

Regards,
Nayden

**Comment by ee92** [comment]
Using NVDA version 2022.1, which can be downloaded from https://www.nvaccess.org/download/

**Comment by Todor-ads** [comment]
Hi @ee92,
Could you also provide information on the version of JAWS you are using?

Regards,
Todor

**Comment by ee92** [comment]
This is reproducible with JAWS 2022

**Comment by ndeshev** [comment]
I was able to reproduce the described behavior with NVDA, but I'm not reproducing the issue with our recommended setup -  JAWS 2022 and Chrome. Could you please update it with the latest updates and resets its settings to the default ones. I'm closing the issue,  if you find the problem persists on your side reopen it and if you could  please provide a video with the exact steps to reproduce and speech output.
