### ISSUE TITLE
CLDR: Load 404 en json for CLDR， https://ui5.sap.com/1.60.2/resources/sap/ui/core/cldr/en.json 404

### ISSUE THREAD

**Issue by JackieWei** [SAP/ui5-webcomponents#5394]
**Describe the bug**
https://ui5.sap.com/1.60.2/resources/sap/ui/core/cldr/en.json is 404, and it's hardcoded in @ui5/webcomponent-base/diost/assets-registries/LocaleData.js, line 150, (version 0.23.x, 0,.25.x), which caused test case failed, and some case the runtime failed

**Isolated Example**
NO

**To Reproduce**
1. Run unit test
2. Show error CLDR loading failed

**Expected behavior**
Should not access 404 file

**Screenshots**

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.3.x, 1.4.x
`@ui5/webcomponents-react` version: 0.23.x, 0.25.x
Operating System: Windows
Browser: Chrome

**Additional context**

**Comment by wulinjie122** [comment]
@JackieWei @jan8080 Did you find any solution for this?
I am facing same issue when invoke below code, seems like importing additional assets doesn't works for me :
```javascript
import React from "react";
import "@ui5/webcomponents-localization/dist/LocaleData";
import "@ui5/webcomponents-localization/dist/features/calendar/Gregorian";
import { fetchCldr } from "@ui5/webcomponents-base/dist/asset-registries/LocaleData";
import getLocale from "@ui5/webcomponents-base/dist/locale/getLocale";

// fetch the cldr for timeformat
fetchCldr(getLocale().getLanguage(), getLocale().getRegion(), getLocale().getScript());
```

**Comment by pskelin** [comment]
@wulinjie122 check the link from the documentation I provided above. For the `@ui5/webcomponents-localization` package, the missing import is:
`import "@ui5/webcomponents-localization/dist/Assets.js"`
