### ISSUE TITLE
[SF] Provide class name switch to use browser default scrollbar

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents#5398]
### **Feature Request Description**
For SF product, we need to use browser default scrollbar. 
For sapui5 https://sapui5.hana.ondemand.com/resources/sap/ui/documentation/sdk/index.html?sap-ui-xx-sample-id=sap.m.sample.Dialog&sap-ui-xx-sample-origin=&sap-ui-xx-dk-origin=https%3A%2F%2Fsapui5.hana.ondemand.com&sap-ui-theme=sap_fiori_3 , they provide html root class name “sapUiNativeScrollbars” to use browser native scrollbar. I remember in previous ui5-wc version, there also has this class name switch. Would you please add this switch back?

### **Proposed Solution**
Add html root class name “sapUiNativeScrollbars” to use browser native scrollbar
<img width="1789" alt="image" src="https://user-images.githubusercontent.com/13098801/175014130-c5bb6cff-5107-4125-9f8c-c7d34fb4dbaa.png">

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: SAP SuccessFators
- Business impact: {...}

**Comment by nnaydenow** [comment]
Hi @GongRichard ,

We added new CSS style class `.ui5-content-native-scrollbars` which removes custom style of the scrollbar.

You can check the linked PR for more information how to use it.

Regards,
Nayden
