### ISSUE TITLE
A11y - role="group" given to <li> which is incorrect markup

### ISSUE THREAD

**Issue by hxempty** [SAP/ui5-webcomponents#5400]
### **Bug Description**
Observe role="group" is provided to 'li' tag around "Applicants" in the left panel
![screenshot-1](https://user-images.githubusercontent.com/34623782/175248607-e8c9051e-d7c9-42e0-a79a-f09e2c073583.png)
![screenshot-2](https://user-images.githubusercontent.com/34623782/175248689-1d44120f-7abb-4f3f-aac1-09f47859041a.png)

### **Expected Behavior**
role="group" is provided on the  ul tag only and not on li tag
### **Steps to Reproduce**
1.Go to https://qacand.hcm.ondemand.com/?mock#/assignment-detail/ao/6     (company=htASSM1101&username=QIMMKF&password=pwd) vpn should be switched to shanghai
2.click "Applicants" 

### **Context**
- UI5 Web Components version: {1.4.0}
- OS/Platform: {Windows 10}
- Browser: {Chrome}
- Affected component: {ui5-list}

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by tsanislavgatev** [comment]
Hello colleagues,

Can you please take a look at this case?
It can be reproduced in the List sample in Playground: https://sap.github.io/ui5-webcomponents/playground/components/List/

The group header list item has a role = group and roledescription = group header. I've checked in specification and ui5, and it has different behaviour. Can you please verify if this indeed is a bug and not wanted behaviour?

Best Regards,
Tsanislav

**Comment by hxempty** [comment]
> 
Hello colleagues,
I've checked,the component has the problem in ui5.
https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-list--with-group-header-list-item
![image](https://user-images.githubusercontent.com/34623782/176339165-029df45c-e467-4958-9a48-7f30325f2066.png)
Thanks ,
Sunny

**Comment by hxempty** [comment]
> Hello colleagues,
> 
> Can you please take a look at this case? It can be reproduced in the List sample in Playground: https://sap.github.io/ui5-webcomponents/playground/components/List/
> 
> The group header list item has a role = group and roledescription = group header. I've checked in specification and ui5, and it has different behaviour. Can you please verify if this indeed is a bug and not wanted behaviour?
> 
> Best Regards, Tsanislav



Hello colleagues,
I've checked,the component has the problem in ui5.
https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-list--with-group-header-list-item
![image](https://user-images.githubusercontent.com/34623782/176339165-029df45c-e467-4958-9a48-7f30325f2066.png)
Thanks ,
Sunny
