### ISSUE TITLE
Deselect date fields in ui5 web component

### ISSUE THREAD

**Issue by kundarsowjanya** [SAP/ui5-webcomponents#5402]
Hi,

I'm using UI5 web components,and I'm using  Date Range Picker 

https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-daterangepicker--default-story

but after selecting any date if I want to deselect so that date range value will be empty.

Is there any inbuilt functionality available?

Thanks

**Comment by tsanislavgatev** [comment]
Hello @kundarsowjanya ,

You can delete the value in the input and press enter or just focus out the input, this will set the value to empty and will undo any selection in the control.
There is on provided functionality for deselect using the popover.

Best Regards,
Tsanislav

**Comment by kundarsowjanya** [comment]
Hi @tsanislavgatev 

Thank you
