### ISSUE TITLE
How you can bind <ui5-input> value property when using origami in angular

### ISSUE THREAD

**Issue by nchondromatidis** [SAP/ui5-webcomponents#5407]
### **Issue Description**
I a using ui5 in angular, I followed the instructions, forms work with origami, but I cannot bind to some attributes, for example ui-5input.value does not work neither with [value]=... nor with [attr.value]=... I think there should be an example on how to accomplish that.

### **Issue Type**

- [ ] Documentation is unclear
- [ ] Documentation is incorrect
- [x] Documentation is missing
- [ ] Other

**Comment by ilhan007** [comment]
Hello @nchondromatidis did you try 
```html
<ui5-input [(ngModel)]="value" origami></ui5-input>
```
as suggested in the [docs](https://sap.github.io/ui5-webcomponents/playground/frameworks/angular/).

**Comment by nnaydenow** [comment]
Hi @nchondromatidis, 

Could you please share more about your use case?

**Comment by nnaydenow** [comment]
Hi,

I'm closing the issue since there is no response with more information about the issue.
