### ISSUE TITLE
[SF][ui5-carousel] Add a "displayCount" property

### ISSUE THREAD

**Issue by Neeeko** [SAP/ui5-webcomponents#5409]
### **Feature Request Description**
Currently, the ui5-carousel displays "dots" to represents each page unless there are more than 8 pages where it will display the count of pages, as per the Fiori Guidelines suggests

<img width="287" alt="Screen Shot 2022-06-24 at 2 46 37 PM" src="https://user-images.githubusercontent.com/7316793/175697148-50ca0270-00ca-4a18-9e7f-925eb2394976.png">
With count <= 8
<img width="271" alt="Screen Shot 2022-06-24 at 2 46 40 PM" src="https://user-images.githubusercontent.com/7316793/175697146-aa05cb32-f15b-443a-850f-f014f57d06c6.png">
With count > 8

However in our use case, displaying dots at one point then the count at another point would be confusing to the user, so **having the ability to only display the pagination as a count even if the amount of pages is less than 8 would be ideal**.

### **Proposed Solution**
Having a boolean property such as a `displayCount` that would be `false` by default but set to `true` would always display the page counts would definitely help!

```
<ui5-carousel display-count>
...
</ui5-carousel>
```

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: SuccessFactors

**Comment by nnaydenow** [comment]
Hello @sap/ui5-webcomponents-topic-rd,

Regarding https://experience.sap.com/fiori-design-web/carousel/#behavior-and-interaction ui5-carousel displays dots as pagination when its items are less than 8. Could you please check this feature request?

Regards,
Nayden

**Comment by olannyv** [comment]
Implementation BLI is created in Rodopi planning Jira #2921
