### ISSUE TITLE
clear input with vuejs not working

### ISSUE THREAD

**Issue by mehdijouan** [SAP/ui5-webcomponents#542]
**Describe the bug**
Hello, 

If I have a `ui5-input` with a binded value and that I set it to an empty string, nothing happens... But if I set it with any other value, it is reflected in the input

**To reproduce**
1. Go to [this code sandbox](https://codesandbox.io/embed/ui5-web-components-clear-issue-rd5b6)
1. change the input value => the text is updated correctly
2. click on `clear` => only the text is removed, the input still have the old value
3. click on `say Hy` => both the text and the input text are updated correctly

**Expected behavior**
Setting a binded value to an empty string should update the input text to this value.

**Context**
- UI5 Web Components version
- OS/Platform: mac
- Navigator: Chrome Version 75.0.3770.80 (Official Build) (64-bit)
- framework: vuejs

**Affected components** 
- input
- textArea

**Comment by mehdijouan** [comment]
Thanks for this quick fix! 
When could I expect a release containing the fix?

**Comment by MapTo0** [comment]
I personally would like to have this ASAP as I consider it as a major issue. I will update you for a concrete date tomorrow. I believe we can get a minor version in a few days.

**Comment by MapTo0** [comment]
We will try to have this fix released next week (hopefully Monday or Tuesday).
