### ISSUE TITLE
ui5-button text shadow in high contrast theme

### ISSUE THREAD

**Issue by ee92** [SAP/ui5-webcomponents#5420]
### **Bug Description**
When hovered the ui5-button text has a text-shadow in high contrast themes, which is not there in UI5.
UI5
<img width="85" alt="Screen Shot 2022-06-27 at 11 14 05 AM" src="https://user-images.githubusercontent.com/24360164/176008431-101b0cb1-fe8f-4959-90f4-78e20b1f838e.png">
ui5-webcomponents
<img width="107" alt="Screen Shot 2022-06-27 at 11 14 13 AM" src="https://user-images.githubusercontent.com/24360164/176008435-dadf9f42-71c2-4db7-9a2d-0b81cc252e86.png">

### **Expected Behavior**
Expect the ui5-button to have the same style as the UI5 button, with no text-shadow.

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/Button/?sap-ui-theme=sap_belize_hcw
2. Hover the first button
3. Notice the text-shadow
4. Compare to https://sapui5.hana.ondemand.com/#/entity/sap.m.Button/sample/sap.m.sample.Button (select Hight Contrast White theme) which has no text-shadow when hovered.

### **Context**
- UI5 Web Components version: 1.4.0
- Affected component: ui5-button

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### **Stakeholder Info** 

- Organization: SuccessFactors

**Comment by nnaydenow** [comment]
Hi @SAP/ui5-webcomponents-topic-b ,

Could you please check the issue? There is visual issue where text has shadow around it in all contrast themes except the ones for horizon theme.

Regards,
Nayden

**Comment by GongRichard** [comment]
Hi @ilhan007 ,
This issue also exists in theme sap_fiori_3_hcw https://sap.github.io/ui5-webcomponents/playground/components/Button/?sap-ui-theme=sap_fiori_3_hcw, please also fix it.
