### ISSUE TITLE
Form submission on ENTER

### ISSUE THREAD

**Issue by Bilal3120** [SAP/ui5-webcomponents#5427]
The form gets submitted and redirects to some unknown url when clicking ENTER with focus on any of its field. Can we have a property which prevents the form submission on ENTER key.

**To Reproduce**
1. Go to [Storybook](https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-form--default-story)
2. Enter some text in Sole Form Item field
3. Click ENTER
4. The form redirects to some error. This similar behaviour is happening in our application.

**UI5 Web Components for React Information**
`@ui5/webcomponents` 1.3.0
`@ui5/webcomponents-react` 0.23.0

**Comment by nnaydenow** [comment]
Hello @SAP/ui5-webcomponents-topic-core ,

Could you please check the issue? As you can see form is submitted even if the event is prevented. The issue is isolated: https://codesandbox.io/s/ui5-webcomponents-forked-wqgyss?file=/index.html

Regards,
Nayden

**Comment by Bilal3120** [comment]
Hello,
Could you please tell when can we expect this fix to be released. Like in which version of `ui5-webcomponents`.

Best regards,
Bilal Ahmed Pasha

**Comment by nnaydenow** [comment]
Hi @Bilal3120,

The fix (#5500) is available with version 1.6.0 (you can check its release note: https://github.com/SAP/ui5-webcomponents/releases/tag/v1.6.0)

Regards,
Nayden
