### ISSUE TITLE
[SF] Tree - selected and prevSelected arrays in selection-change event are the same when indeterminate state for checkbox is used

### ISSUE THREAD

**Issue by Vir-Mittal** [SAP/ui5-webcomponents#5430]
### **Bug Description**
When ui5-tree in mode MultiSelect is using indeterminate state for a parent TreeItem, and that checkbox is selected, the selected and prevSelected arrays in the fired selection-change event are the same.

### **Expected Behavior**
There should be a difference in the selected and prevSelected arrays so that the change can be determined.

### **Steps to Reproduce**
1. Go to 'https://codesandbox.io/s/ui5-webcomponents-treeitem-indeterminate-state-0gi7ri?file=/src/index.js'
2. Select the checkbox for Tree 1.1
3. The console output shows - 
<img width="728" alt="Screen Shot 2022-06-28 at 8 07 22 PM" src="https://user-images.githubusercontent.com/36656306/176342758-cfa4fe89-c8d3-43a1-af0c-f9adba654c95.png">

4. The checkbox for Tree 1.1 is now checked and the checkbox for Tree 1 is in the indeterminate state.
5. Select the checkbox for Tree 1
6. The console output shows - 
<img width="732" alt="Screen Shot 2022-06-28 at 8 07 45 PM" src="https://user-images.githubusercontent.com/36656306/176342827-6f7b33bf-ffb9-4070-a4dc-8fed72ce4fa5.png">

The two arrays are now the same, so the actual change cannot be determined.
This probably occurs because when a checked, indeterminate checkbox is clicked again, it remains in checked state instead of being unchecked, causing the previous and current selection to be the exact same. The expectation would either be that the checkbox should be unchecked when clicked again or the selection-change event has a way of handling this case for indeterminate checkboxes (like adding a property that indicates which TreeItem was clicked).

### **Isolated Example**
https://codesandbox.io/s/ui5-webcomponents-treeitem-indeterminate-state-0gi7ri?file=/src/index.js

### **Context**
- UI5 Web Components version: {1.4.0}

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by nnaydenow** [comment]
Hi @Vir-Mittal,

Since you are changing the selected state of Tree 1 this is expected. Since you have references to the items you can filter them by their indeterminate property to check which were really selected.

Regards,
Nayden

**Comment by Vir-Mittal** [comment]
Hi @nnaydenow ,

Thank you for your reply. I'm still not sure why this is the expected behaviour because if we see in this simpler sandbox without changing any states - 
https://codesandbox.io/s/ui5-webcomponents-treeitem-indeterminate-state-forked-15ntbc?file=/src/index.js

1) Initially the checkbox is selected and in the indeterminate state
2) When you click on the checkbox, the checkbox remains selected
3) The log shows the previously selected and currently selected arrays and they are the exact same
4) Both contain one item - the checkbox with selected and indeterminate value

Could you elaborate on what you mean by filtering the items by their indeterminate property to check which were really selected? Because as seen above, the indeterminate property does not change when the user clicks the checkbox and since the two arrays are the exact same, how would one determine what selection change actually occurred?

Thank you,
Vir

**Comment by nnaydenow** [comment]
Hi @Vir-Mittal,

To display an checkbox as partially selected you have to mark it as indeterminate and as select:
`<ui5-checkbox **indeterminate selected**></ui5-checkbox>`

If the checkbox has both properties set and the checkbox is clicked change event is fired because there is change in the component (its indeterminate property is removed and now it is selected). In that case checkbox will looks like: 
`<ui5-checkbox **selected**></ui5-checkbox>`

The behaviour in ui5-tree is the same as ui5-checkbox. You have partially selected tree node (some of its items are selected) and clicking the ui5-checkbox inside it means that you want to remove indeterminate state.

To check only selected items I suggest you to add just one filter function on selected items
`event.detail.selectedItems.filter((node) => !node.indeterminate)`

Regards,
Nayden

**Comment by Vir-Mittal** [comment]
Hi @nnaydenow ,

The change event works great with the ui5-checkbox:
Initially the checkbox is selected and has indeterminate state - 
<img width="725" alt="Screen Shot 2022-07-01 at 11 18 04 AM" src="https://user-images.githubusercontent.com/36656306/176949162-82bea649-4dec-4af1-81ce-fd6a70477d23.png">

Clicking the checkbox now removes the indeterminate state - 
<img width="723" alt="Screen Shot 2022-07-01 at 11 19 55 AM" src="https://user-images.githubusercontent.com/36656306/176949307-e047b396-22c1-43ee-bf69-bec6e0c22c0f.png">

However, the same (removal of indeterminate state) does not happen with the tree item - 
Initial indeterminate and selected tree item - 
<img width="725" alt="Screen Shot 2022-07-01 at 11 21 17 AM" src="https://user-images.githubusercontent.com/36656306/176949500-af338ec3-66c3-4152-ba79-0cc73afcdb84.png">

Clicking the tree item fires the selection-change event which has the prevSelected and selected arrays which both contain the identical item - 
<img width="734" alt="Screen Shot 2022-07-01 at 11 22 46 AM" src="https://user-images.githubusercontent.com/36656306/176949708-00302627-37b1-4a4b-a6e6-7c3683ffe3d5.png">

The indeterminate state is visually removed but the property is not being removed from the tree item element.

Sandbox - https://codesandbox.io/s/ui5-webcomponents-treeitem-indeterminate-state-vs-checkbox-6h946r?file=/src/index.js

**Comment by nnaydenow** [comment]
Hello @SAP/ui5-webcomponents-topic-p ,

Could you please check the issue?
