### ISSUE TITLE
 DateTimePicker not showing up 

### ISSUE THREAD

**Issue by kundarsowjanya** [SAP/ui5-webcomponents#5431]
Hi I'm using  DateTimePicker, with version 

   "@ui5/webcomponents": "1.2.3",
    "@ui5/webcomponents-fiori": "1.2.3",
    "@ui5/webcomponents-icons": "1.2.3",
    "@ui5/webcomponents-icons-tnt": "1.2.3",
    "@ui5/webcomponents-react": "0.22.4",
    "@ui5/webcomponents-react-base": "0.22.4",

but DateTimePicker in not showing up on screen,

Can anyone suggest me the solution please

**Comment by nnaydenow** [comment]
Hi @kundarsowjanya ,

Could you please provide an example? It seems that it works in: https://codesandbox.io/s/ui5-webcomponents-forked-t3y8yr?file=/src/index.js

**Comment by kundarsowjanya** [comment]
@nnaydenow  could you please check this 
https://github.com/SAP/ui5-webcomponents/issues/5433
