### ISSUE TITLE
[SF][A11y][AXE][ui5-list]AXE errors for checkbox in list item for ui5-list MultiSelect mode

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents#5437]
### **Bug Description**
AXE errors for checkbox in list item for ui5-list MultiSelect mode 

### **Expected Behavior**
No AXE error

### **Steps to Reproduce**
1. Go to 'https://sap.github.io/ui5-webcomponents/playground/components/List/'
2. run chrome browser axe plugin to scan the page
3. you will find there two axe errors which were related with checkbox in list item for ui5-list MultiSelect mode 

### **Context**
- UI5 Web Components version: {1.4.0}
- OS/Platform: {MacOS}
- Browser: {Chrome}
- Affected component: {ui5-list}

### **Log Output / Stack Trace / Screenshots**
Error1: Ensures ARIA attributes are allowed for an element's role
<img width="1780" alt="image" src="https://user-images.githubusercontent.com/13098801/176476529-4a4976ea-d886-4ab9-bf33-09fb37287dfe.png">

Error2: Ensures every ARIA toggle field has an accessible name
<img width="1777" alt="image" src="https://user-images.githubusercontent.com/13098801/176476798-c1114595-fd04-4ca6-a7d7-5371fc63fbc7.png">

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### **Stakeholder Info** (if applicable)

- Organization: {SAP SuccessFactors}

**Comment by nnaydenow** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

Could you please check the issue? Seems like there is aria-label attribute to ui5-checkbox but I think that it should be changed to accessible name.

Regards,
Nayden
