### ISSUE TITLE
[SF][A11y][AXE][ui5-panel]AXE error for ui5-panel header

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents#5438]
### **Bug Description**
AXE error for ui5-panel header

### **Expected Behavior**
A clear and concise description of what you expect to happen.

### **Steps to Reproduce**
1. Go to 'https://sap.github.io/ui5-webcomponents/playground/components/Panel/'
2. run chrome browser axe plugin to scan the page
3. you will find  axe error which was related with ui5-panel header

### **Context**
- UI5 Web Components version: {1.4.0}
- OS/Platform: {MacOS}
- Browser: {Chrome}
- Affected component: {ui5-panel}

### **Log Output / Stack Trace / Screenshots**
error: Ensures ARIA attributes are allowed for an element's role
<img width="1784" alt="image" src="https://user-images.githubusercontent.com/13098801/176478646-90f5d90f-893a-4c5b-878a-ec4f9fc43ad0.png">

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### **Stakeholder Info** (if applicable)

- Organization: {SAP SuccessFactors}

**Comment by nnaydenow** [comment]
Hello @SAP/ui5-webcomponents-topic-rd,

Could you please check the issue?

Regards,
Nayden

**Comment by ivoplashkov** [comment]
Hello,

We are working on a solution for this ticket, however we have some technical issues and we are unable to test the solution.

Thank you for your patience.
Best regards,
Ivaylo
