### ISSUE TITLE
MultiInput: Focus is lost after deleting all tokens

### ISSUE THREAD

**Issue by sparkypro** [SAP/ui5-webcomponents#5448]
**Describe the bug**
MultiInput, when all the tokens are deleted/removed via keyboard the focus is lost.

**UI Link**
https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-multiinput--default-story

**Steps to Reproduce**
1.  Add a single token to the MultiInput component.
2. Remove the token added to MultiInput via keyboard selection by hitting 'Delete' key.
3. Observe the focus disappears from the MultiInput component

**Expected behavior**
MultiInput, after deleting tokens from the components, the focus must be retained.

**UI5 Web Components for React Information**
`@ui5/webcomponents` version:1.4.0
`@ui5/webcomponents-react` version: 0.25.6
Operating System:Window10
Browser:Chrome

**Additional context**

**Comment by ilhan007** [comment]
Hello @sparkypro 
unfortunately, we don't support old versions, I would ask you to update to latest. 
Currently it's @ui5/webcomponents 1.4.0, but later today we will release @ui5/webcomponents 1.5.0. 
After that , in few days, a new @ui5/webcomponents-react version will come, based on @ui5/webcomponents 1.5.0. 

So, I suggest wait for this, consume the @ui5/webcomponent 1.5.0 and the latest from @ui5/webcomponents-react and  re-test. 

If you still have the issue, please put a comment and we will re-open the issue.

BR,
UI5 Web Components Team
ilhan

**Comment by ndeshev** [comment]
Hello @sparkypro, 

The issue is not reproducible in v. 1.4, when all tokens are deleted the focus is managed back to the input element.

Kind regards,
Nikolay
