### ISSUE TITLE
ui5-input: delete line or word does not work with typeahead

### ISSUE THREAD

**Issue by JarrettChan** [SAP/ui5-webcomponents#5450]
### **Bug Description**
When a suggestion is auto-filled into the input by "typeahead" feature, can not use `command-backspace` or `option-backspace` to delete the line or word.
The auto-filled highlighted section may flicker if repeatedly attempting to delete, but ultimately fails to delete.

### **Expected Behavior**
`command-backspace` and `option-backspace` should work.

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/Input/
2. "Input With Suggestions" country example
3. Type "arg" (Argentina), `command-backspace`

### **Context**
- UI5 Web Components version: 1.4.0
`S={version:"1.4.0",major:1,minor:4,patch:0,suffix:"",isNext:!1,buildTime:1654286018}`
- OS/Platform: macOS 12.4
- Browser: 102.0.5005.115 (Official Build) (x86_64) 
- Affected component: ui5-input

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### **Stakeholder Info (if applicable)**
 - Organization: SuccessFactors

**Comment by ndeshev** [comment]
Hello @SAP/ui5-webcomponents-topic-rl, please take a look if preventing of the default behaviour of the browser can be avoided.

Such shortcut handling exist in Chrome and Safari, in Firefox is not implemented.
