### ISSUE TITLE
View Settings dialog shows undefined on filter page

### ISSUE THREAD

**Issue by thisisjasmeet** [SAP/ui5-webcomponents#5451]
### **Bug Description**
1) go to https://sap.github.io/ui5-webcomponents-react/?path=/docs/modals-popovers-viewsettingsdialog--default-story
2) open settings dialog and swithc to filter section.
3) chose filter by option and click on cancel.
4) again open settings dialog.

Issue:- dialog title is undefined with no content displayed.
![image](https://user-images.githubusercontent.com/57886348/177115674-f1a5260b-4778-4b46-b901-3d097617fa34.png)

### **Context**
- UI5 Web Components version: 0.25.7
- OS/Platform: mac
- Browser: chrome
- Affected component: View settings dialog

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by ilhan007** [comment]
Hello 
@thisisjasmeet 

UI5 Web Components version: 0.25.7 is a very old version, could you try 1.4.0?

**Comment by thisisjasmeet** [comment]
Hi Ilhan,

I am using UI5 web components for React.

Yes, the issue is reproducible in 
https://codesandbox.io/s/ui5-webcomponents-forked-vczepd?file=/src/index.js

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-b  could you see the issue, it's reproducible in the [Playground](https://sap.github.io/ui5-webcomponents/main/playground/components/ViewSettingsDialog/)
