### ISSUE TITLE
geomap component request

### ISSUE THREAD

**Issue by seVladimirs** [SAP/ui5-webcomponents#5470]
### **Feature Request Description**
SAPUI5 does have a UI component for a map, is something similar is planned to be released?

**Comment by ilhan007** [comment]
Hello @seVladimirs we have an internal web component, which is not an open source
https://pages.github.tools.sap/sap-webcomponents/sap-geomap/dist/test-resources/pages/



Could you tell us more regarding your use-case? What are you going to use the map for, what is your programming model?

BR,
ilhan
UI5 Web Components Team

**Comment by seVladimirs** [comment]
Our use case is quite simple, our user can select different countries/regions and that selection should be visible on the map. For that we are using https://www.react-simple-maps.io/ but we were wondering if UI5 webcomponent have something in place.

**Comment by ilhan007** [comment]
Hello @seVladimirs 

Overall, it seems our [GeoMap](https://pages.github.tools.sap/sap-webcomponents/sap-geomap/dist/test-resources/pages/) web component will do the job. The thing is that it's not released into npm yet and it won't happen short-term for sure. 

However, there are other means to be used (although less convenient than installing from npm) and it depends on the type of the project you are working on.

Could you share some words about your project:
- is it a SAP project
- how it's called, etc. 
- do you have access to https://github.tools.sap/

If you don't want to share these details in GutHub, you can follow up via email - ilhan.myumyun@sap.com

**Comment by seVladimirs** [comment]
Hi, 

OK, thanks for the swift reply! Thanks for letting me know and also informing the open-source community about the plans.

However, we do have access to internal repositories, therefore let's move out our discussion from here. 

Feel free to close this issue, unless you want to close it once geomap is open-sourced.

**Comment by ilhan007** [comment]
We plan to keep the Geomap is an inner source component for now.
