### ISSUE TITLE
[a11y] ui5-shellbar: primary title h1 causing pages to have multiple h1 tag

### ISSUE THREAD

**Issue by pankajpandey01** [SAP/ui5-webcomponents#5473]
### **Bug Description**
primary title h1 causing pages to have multiple h1 tag

### **Expected Behavior**
primary title should not have any h1 tag (similar to ui5 shellbar) https://sapui5.hana.ondemand.com/sdk/#/api/sap.f.ShellBar%23overview

or they should be configurable as ui5 webcomponent title https://sap.github.io/ui5-webcomponents/playground/components/Title/

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/ShellBar/
2. inspect browser console.

### **Context**
- UI5 Web Components version: {1.5.0}
- OS/Platform: {All}
- Browser: {All}
- Affected component: {ui5-shellbar}

```
### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)
- Organization: {SuccessFactors}
- Business impact: {Accessibility}

**Comment by ndeshev** [comment]
Hello @SAP/ui5-webcomponents-topic-p, take a look of this feature request for configurable header levels

**Comment by dobrinyonkov** [comment]
Hello @pankajpandey01! As discussed, two H1 elements shouldn’t be an issue if located on different DOM level.
