### ISSUE TITLE
AnalyticalTable: Resizing bug of columns 

### ISSUE THREAD

**Issue by tunahan** [SAP/ui5-webcomponents#5476]
### **Bug Description**
The issue seems to occur on screen resolution which produces horizontal scroll bar on the table. And affects only the columns which are not visible without horizontal scrolling. Those columns can not be re-sized

### **Expected Behavior**
Columns can be re-sized regardless they are shown with or without horizontal scrolling.

### **Steps to Reproduce**
1. Go to codesandbox link.
2. Shrink the panel that contains AnalyticalTable untill horizontal scrool bar appears.
3. Try to resize one of the columns.

### **Isolated Example**
[CodeSandbox](https://codesandbox.io/s/quizzical-pateu-ow2t3f)

### **Context**
- UI5 Web Components version: Versions can be seen in codeSandbox. Besides, this bug can be spotted with these versions as well.
  -    "@ui5/webcomponents-fiori": "~1.1.2",
        "@ui5/webcomponents-icons": "~1.1.2",
        "@ui5/webcomponents-react": "^0.21.5",
- OS/Platform: MacOS / Windows.

- Browser: Can be seen in Chrome and Edge.

### **Log Output / Stack Trace / Screenshots**
[See the video attached.](https://user-images.githubusercontent.com/2466336/177736305-9e0d7f38-397c-402a-9547-8b48fa92c0a8.mov)

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by ndeshev** [comment]
Hello @tunahan the AnalyticalTable component is a react component. React UI5 Components have a separate repository - https://github.com/SAP/ui5-webcomponents-react 

You should report the issue there.

Regards,
Nikolay
