### ISSUE TITLE
[SF][ui5-link]: the click event handler is triggered twice

### ISSUE THREAD

**Issue by zhangliangyi** [SAP/ui5-webcomponents#5477]
### **Bug Description**
After 1.5.0 upgrade, I found the click event handler of ui5-link is triggered twice. Per my investigation, one is the expected CustomEvent, the other is a native event from browser.

### **Expected Behavior**
Before 1.5.0, it is triggered once as expected.

### **Isolated Example**
Please check https://codesandbox.io/s/ui5-webcomponents-forked-8h76xl

### **Context**
- UI5 Web Components version: 1.5.0
- OS/Platform: Mac OS
- Browser: Edge
- Affected component: ui5-link

### **Log Output / Stack Trace / Screenshots**
```
{...}
```
### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SF
- Business impact: Medium

**Comment by codefactor** [comment]
This is a pretty functionally impacting issue - Is there any update on this one?

**Comment by nnaydenow** [comment]
Hi @codefactor,

We've submitted fix that solving the issue. There was conflict with the native event that is resolved.

Regards,
Nayden

**Comment by jatinthaker** [comment]
@nnaydenow Nayden, when should we expect this fix? @codefactor when are we planning to uptake it?

**Comment by ilhan007** [comment]
Hi @jatinthaker with the next 1.7.0 release - end of the Aug.
https://github.com/SAP/ui5-webcomponents/projects?type=classic

**Comment by codefactor** [comment]
@jatinthaker we will take it in b2211, so 1.7 should be OK. In the meantime there is an identified work around in slack people can use if this is a blocked.

**Comment by jatinthaker** [comment]
Thanks @codefactor and @ilhan007.
