### ISSUE TITLE
Network Graph component request

### ISSUE THREAD

**Issue by tamiarah** [SAP/ui5-webcomponents#5483]
### **Feature Request Description**

The [network graph](https://sapui5.hana.ondemand.com/#/entity/sap.suite.ui.commons.networkgraph.Graph) is currently not available in the UI5 Web Components. We haven't found a similar open-source component and would like to ask, if this control is planned or if it is feasible as a candidate to be implemented. 

![image](https://user-images.githubusercontent.com/60143513/178000200-c7c05442-38a8-45c2-ab39-47f588617800.png)

### **Proposed Solution**
The network graph is available as UI5 Web Component. 

### **Proposed Alternatives**
A similar graph component would also be fine (with clickable nodes and lines).

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.
We require this component for one of our customer apps, which we are currently building with UI5 Web Components. 

### **Stakeholder Info** (if applicable)

- Organization: Product Engineering (Team PE IE&CA Cloud Innovation and Architecture)
- Business impact: -

**Comment by gmkv** [comment]
Hello @SAP/ui5-webcomponents-topic-core, please take a look at this feature request.

**Comment by ilhan007** [comment]
Hello @tamiarah unfortunately a component like this is not part of our plans and we won't provide it.
We focus on more basic/standard UI widgets.
