### ISSUE TITLE
TypeError when inserting a Date Range Picker input field

### ISSUE THREAD

**Issue by camilailges** [SAP/ui5-webcomponents#5489]
### **Bug Description**
Whenever I insert data on a Date Range Picker input field it throws a TypeError.

### **Expected Behavior**
It should filter and return the correct data.

### **Steps to Reproduce**
1. Insert a date on a Date Range Picker filter
2. Click outside the input field
3. Thows this error: `TypeError: Cannot read properties of null (reading 'getTime')`

### **Context**
- UI5 Web Components version: 1.4.0
- OS/Platform: Windows 10
- Browser: Chrome
- Affected component: Date Range Picker

### **Log Output / Stack Trace / Screenshots**
```
![image](https://user-images.githubusercontent.com/83407255/178291442-0b6f72c0-5e95-43bf-af69-be21a6b878b9.png)
![image](https://user-images.githubusercontent.com/83407255/178291476-f51d8d59-5f3f-4a8f-ae3f-aafb9b00fc8c.png)

{...}
```
### **Priority**
- [ ] Low
- [] Medium
- [ ] High
- [x ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by gmkv** [comment]
Hi @camilailges 
Can you provide a reproducible example code of the DateRangePicker throwing an error?
You can [fork this sample](https://stackblitz.com/edit/ui5-webcomponents-sample?file=index.html) if you like.

**Comment by stbodurov** [comment]
Hi @camilailges,

Just checking in if you could provide some additional context and a reproducible sample.

Regards,
Stanislav
