### ISSUE TITLE
[SF][0.26.1][a11y][Breadcrumbs]: breadcrumbs current page item not horizontal aligned with other items under HCW theme

### ISSUE THREAD

**Issue by ksblklu** [SAP/ui5-webcomponents#5492]
**Describe the bug**
In Windows system, breadcrumbs current page item is not horizontal aligned with other breadcrumb items under high contrast white mode

**To Reproduce**
1. In Windows, go to https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-breadcrumbs--default-story&globals=theme:sap_horizon_hcw
2. swith theme to sap_fiori_3_hcw / sap_horizon_hcw
3. See misalignment of breadcrumb current page item 
<img width="1202" alt="image" src="https://user-images.githubusercontent.com/27538066/178422631-cc710c1d-5573-4b1f-931e-cf02e159f1eb.png">

**Expected behavior**
Breadcrumb current page item should be vertical aligned with other items
<img width="914" alt="image" src="https://user-images.githubusercontent.com/27538066/178422940-3e66b260-1ef1-494e-b902-422ec648acae.png">

**Screenshots**

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.5.0
`@ui5/webcomponents-react` version: 0.26.1
Operating System: Windows
Browser: Chrome

**Comment by gmkv** [comment]
If you are having any issues loading codesandboxes, please message me.

**Comment by ksblklu** [comment]
> Hi @ksblklu , can I clarify is this the misalignment, that you are referring to? <img alt="image" width="874" src="https://user-images.githubusercontent.com/15124079/179193648-a42d402d-ba14-4c47-9589-1db584dad6e2.png">
> 
> Kind regards, Petya Markova. UI5 Web components developer

Yes, visually the current page item is higher than other items.
