### ISSUE TITLE
[SF][A11y][ui5-illustrated-message]: provide interface to customize head leveling of title

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents#5503]
### **Feature Request Description**
Now the head leveling of title is h2. For our cases, it's not h2. For example, show ui5-illustrated-message in dialog, the title should be h3.

### **Proposed Solution**
provide interface to customize head leveling of title

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: {SAP SuccessFactors}

**Comment by TeodorTaushanov** [comment]
Hello @SAP/ui5-webcomponents-topic-p, take a look of this feature request.

**Comment by dobrinyonkov** [comment]
Hello, this feature is needed. We can add new API (ex. property `titleLevel` or slot `title`).

**Comment by dobrinyonkov** [comment]
Internal reference: 5803
