### ISSUE TITLE
Axe reports issue for ui5-button 1.5.0 <svg> elements with an img role must have an alternative text

### ISSUE THREAD

**Issue by mydavidzhang** [SAP/ui5-webcomponents#5505]
### **Bug Description**
Axe reports issue for ui5-button "<svg> elements with an img role must have an alternative text"
Element source <svg class="ui5-icon-root" viewBox="0 0 512 512" focusable="false" preserveAspectRatio="xMidYMid meet" xmlns="http://www.w3.org/2000/svg" role="img">
NOTE: issue happens when button has only icon

### **Expected Behavior**
No Axe issue

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/Button/
2. run Axe plugin
3. See issue  "<svg> elements with an img role must have an alternative text"

### **Isolated Example**
https://sap.github.io/ui5-webcomponents/playground/components/Button/

### **Context**
- UI5 Web Components version: 1.5.0

### **Log Output / Stack Trace / Screenshots**
<img width="2014" alt="Screen Shot 2022-07-13 at 5 44 00 PM" src="https://user-images.githubusercontent.com/10460331/178861280-1606eb18-0424-4c73-8ae4-d165a7346a93.png">

### **Priority**

- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: Successfactors
- Business impact:

**Comment by unazko** [comment]
Hello @mydavidzhang,

Please do refer to the following incident: https://github.com/SAP/ui5-webcomponents/issues/5596
for the same issue. There is an answer there.

Best Regards,
Boyan Rakilovski
