### ISSUE TITLE
Dialog show in Dialog  problem

### ISSUE THREAD

**Issue by byk04712** [SAP/ui5-webcomponents#5506]
### **Bug Description**
`ui5-dialog` content show `ui5-dialog` , the z-index has some problem. 

![open dialog](https://user-images.githubusercontent.com/6211302/178890879-09e190ff-0801-4241-8343-8861f03f1f14.png)

![open dialog in parent dialog](https://user-images.githubusercontent.com/6211302/178890920-bb9e93a9-f7d7-45ac-841b-9e44c91ecdd9.png)

### **Expected Behavior**
child dialog content should show over up the parent dialog 

### **Steps to Reproduce**
1. Example here  [https://codesandbox.io/s/byc9e5](https://codesandbox.io/s/byc9e5)

**Comment by TeodorTaushanov** [comment]
Hi @byk04712, the https://codesandbox.io/s/byc9e5 is not working

**Comment by TeodorTaushanov** [comment]
Sorry @byk04712, the link is working.

**Comment by TeodorTaushanov** [comment]
Hi @byk04712,

You need to move the second dialog outside the first one:

 ```
     <Dialog ref={dialogRef1}>
        Dialog content
        <Button onClick={() => dialogRef2.current.show()}>
          Open child Dialog
        </Button>
      </Dialog>
      <Dialog ref={dialogRef2}>Dialog2 content</Dialog>
```

Best,
Teo

**Comment by byk04712** [comment]
> Hi @byk04712,
> 
> You need to move the second dialog outside the first one:
> 
> ```
>     <Dialog ref={dialogRef1}>
>        Dialog content
>        <Button onClick={() => dialogRef2.current.show()}>
>          Open child Dialog
>        </Button>
>      </Dialog>
>      <Dialog ref={dialogRef2}>Dialog2 content</Dialog>
> ```
> 
> Best, Teo

OK， thank you.
