### ISSUE TITLE
Dialog component dark theme

### ISSUE THREAD

**Issue by geokas7** [SAP/ui5-webcomponents#5510]
### **Issue Description**
A clear and concise description of the documentation issue.

### **Issue Type**

- [ ] Documentation is unclear
- [ ] Documentation is incorrect
- [ ] Documentation is missing
- [ ] Other

Hello,

We use dialog component. Is there a way to change the default theme to dark?

Best,
George

**Comment by TeodorTaushanov** [comment]
Hi @geokas7, 

Here you can find how to change the theme:
https://sap.github.io/ui5-webcomponents/playground/advanced/configuration/#script

Best,
Teo

**Comment by geokas7** [comment]
Hello,

Thank you for your reply. We try to customize the ui5-dialog appearance. Is there a way to change only the background color of the header (ui5-dialog) ?

Best,
George

**Comment by TeodorTaushanov** [comment]
Hi,

You can check:
https://github.com/SAP/ui5-webcomponents/blob/main/docs/3-customizing/01-theme.md

Best,
Teo
