### ISSUE TITLE
[SF][A11Y][Menu]: Provide interface to customize accessibleName for menu and menuItem

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents#5514]
### **Feature Request Description**
Hi Colleagues,
Please help add interface to customize aria-label. 
In OMP project, we use component Menu on landing page, when user clicks menuItem, it will navigate to another page. We need customize aria-label for screen reader to tell more information. 

### **Priority**
- [ ] Low
- [ ] Medium
- [X] High
- [ ] Very High

Thanks!
Josephine Su

**Comment by Todor-ads** [comment]
Hello @SAP/ui5-webcomponents-topic-b , take a look at this issue.

**Comment by sfsf-xweb-sh** [comment]
Hi @Todor-adsThis feature is requested before B2111 release. 
Please let me know if you have any plan. And

**Comment by unazko** [comment]
Hi @sfsf-xweb-sh,

We are currently working on it.
Expect updates soon.

Best Regards,
Boyan
