### ISSUE TITLE
MultiComboBoxGroupItem: internal `ui5-li-groupheader` ignores scoping

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#5521]
### **Bug Description**
When using scoping with the `ui5-mcb-group-item-demo` web component, the suffix is not passed to the underlying  `ui5-li-groupheader` component.

### **Expected Behavior**
Scoping should work with MultiComboBoxGroupItem.

### **Steps to Reproduce**
1. Go to [codeSandbox](https://codesandbox.io/s/ui5-webcomponents-forked-7qjmdh?file=/index.html)
2. See, that the `ui5-li-groupheader` is not rendered, as the scoping context is set to `"demo"` and the element is missing the respective suffix.

### **Isolated Example**
https://codesandbox.io/s/ui5-webcomponents-forked-7qjmdh?file=/index.html

### **Context**
- UI5 Web Components version: 1.5.0

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

### **Stakeholder Info** (if applicable)

- Organization: UI5 Web Components for React
- Business impact: It's currently not possible to use the MultiComboBoxGroupItem in our internal apps, as we use scoping there.

**Comment by Todor-ads** [comment]
Hello @SAP/ui5-webcomponents-core , can you, please, check this issue?
