### ISSUE TITLE
[ui5-table] Inlining columns don't always work on resize when min-width properties are not sorted descending

### ISSUE THREAD

**Issue by ixiler** [SAP/ui5-webcomponents#5522]
### **Bug Description**
Having 2 or more columns with **min-width** properties, that are not ordered descending from leftmost to rightmost column makes so that the columns aren't always inlined when they should on resize 

### **Expected Behavior**
The ordering of the columns and their **min-width** attribute values to not have effect on the behaviour and the columns to get inlined when the give **min-width** value is reached.

### **Steps to Reproduce**
1. Go to the [sandox](https://codesandbox.io/s/ui5-webcomponents-table-resize-reproduction-xeyx0v?file=/index.html)
2. Expand the browser window so that all the columns are expanded
3. Start to slowly shrink the window width
4. You should be able to observe only the Size column being inlined

If you shrink the window size fast the inlining works sometimes

### **Isolated Example**
[sandox](https://codesandbox.io/s/ui5-webcomponents-table-resize-reproduction-xeyx0v?file=/index.html)

### **Context**
- UI5 Web Components version: {1.5.0}
- OS/Platform: {OS X}
- Browser: {Chrome Version 103.0.5060.114 (Official Build) (x86_64)}
- Affected component: {ui5-table}

### **Log Output / Stack Trace / Screenshots**
![ezgif-4-fb0a5cdf7d](https://user-images.githubusercontent.com/50484241/179510624-365ed204-0701-4a45-9d7f-24a17ee58731.gif)

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

Stakeholder Info (if applicable)
Organization: {SAP}
Unit: {Automation Pilot}

**Comment by Todor-ads** [comment]
Hello @ixiler,
Thank you for sharing this finding. Is it possible to provide us with a real use case where this happens? 
When loading on different device (different screen resolution) this problem is not reproduced.

Regards,
Todor

**Comment by ixiler** [comment]
Hello @Todor-ads,
This might happen if a user is using 2 windows simultaneously on 1 screen and resizes them to fit his use case it is a standard feature in Windows operating system that isn't rarely used as far as I know.

Also it is reproducible in our UI currently, because we inline the rightmost columns first for one of our pages and that is an issue we faced by trying to use the provided inlining mechanics, it isn't fabricated just for the minimal reproduction that we have provided here.

Regards,
Teodor

**Comment by Todor-ads** [comment]
Hello @SAP/ui5-webcomponents-topic-rl , take a look at this issue.

**Comment by ndeshev** [comment]
Hello @ixiler,

We will take a look at the reported behavior.

For now I'm lowering the priority as it is a visual issue.
