### ISSUE TITLE
ui5-table-column demand-popin bold

### ISSUE THREAD

**Issue by geokas7** [SAP/ui5-webcomponents#5524]
### **Issue Description**
A clear and concise description of the documentation issue.

### **Issue Type**

- [ ] Documentation is unclear
- [ ] Documentation is incorrect
- [ ] Documentation is missing
- [ ] Other

Hello,

We created a table with some ui5-table-column with demand-popin. We would like to change the font-weight of popin-text as bold. Is there any way to do this? We can not find any distinct variable for this.

Best,
George

**Comment by geokas7** [comment]
Hello,

We created a table with some ui5-table-column with demand-popin. We would like to change the font-weight of popin-text (column name) as bold. Is there any way to do this? We can not find any distinct variable for this.

Best,
George

**Comment by niyap** [comment]
Hello @geokas7,

There is a slot introduced called 'popin-row' that can be used to achieve such a styling.

You can try in the following way:
ui5-table-row::part(popin-row) {
    font-weight: bold;
}

Kind Regards,
Niya
