### ISSUE TITLE
Text can be copied from disabled ui5-textarea

### ISSUE THREAD

**Issue by vladitasev** [SAP/ui5-webcomponents#5525]
1. Set "disabled" to a textarea
2. Select some text
3. Copy it

Expected: When a textarea is disabled, I shouldn't be able to select/copy text from it
Actual: I can do this

<img width="865" alt="image" src="https://user-images.githubusercontent.com/15844574/179682030-c59652f0-0809-4601-b3aa-393888908f3e.png">

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-rl could you take a look?

**Comment by niyap** [comment]
Hello Colleagues,

That is the expected behaviour as the same is presented in native HTML textarea without UI5 Web Components.
Here is an isolated sample: https://jsbin.com/gujasedube/1/edit?html,output

Kind Regards,
Niya
