### ISSUE TITLE
[SF][ViewSettingsDialog] - setConfirmedSettings lifecycle

### ISSUE THREAD

**Issue by rchrdchn** [SAP/ui5-webcomponents#5533]
### **Bug Description**
**ViewSettingsDialog** component doesn't get confirmed settings state from `setConfirmedSettings` on the first click/try.

### **Expected Behavior**
**ViewSettingsDialog** component should get confirmed settings state from `setConfirmedSettings` on the first click/try.

### **Steps to Reproduce**
1. Go to 'https://codesandbox.io/s/ui5-webcomponents-forked-0y7rpv?file=/src/index.js'
2. Click Open dialog button
3. Sort Order: **Descending** AND Sort By: **Name**
4. Click OK button
5. Click on link: Go to page (**/page**)
6. Click on link: Go back (**/index**)
7. Click Open dialog button
8. Expected: Sort Order: **Descending** AND Sort By: **Name**
9. Actual: Initial Sort Order and Sort By
10. Close and Open dialog again
11. Sorting is --> Sort Order: Descending AND Sort By: Name
12. Expected: Sort Order and Sort By to be coming from `setConfirmedSettings` object after going back from **/page** to **/index**

### **Isolated Example**
https://codesandbox.io/s/ui5-webcomponents-forked-0y7rpv?file=/src/index.js

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Functional issue - Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SuccessFactors

Ref: https://github.com/SAP/ui5-webcomponents/issues/4896
PR: https://github.com/SAP/ui5-webcomponents/pull/5222/files

**Comment by Todor-ads** [comment]
Hello @SAP/ui5-webcomponents-topic-b , take a look of this feature request.

**Comment by rchrdchn** [comment]
Hi team - following up on this issue. Any news?

**Comment by rchrdchn** [comment]
Hi team - following up on this issue. Any updates?

**Comment by Todor-ads** [comment]
Hello @rchrdchn,
Sorry for the late reply. We are working on fix the reported issue and we will update you with our findings as soon as possible.

Best Regards,
Todor

**Comment by jatinthaker** [comment]
@Todor-ads thanks for the note, any progress on this issue?

**Comment by stoehr** [comment]
Also @Todor-ads, isn't the issue a defect in https://github.com/SAP/ui5-webcomponents/issues/4896; and if so, then the `feature request` label on this issue is incorrect.

**Comment by tsanislavgatev** [comment]
Hello colleagues,

This is a feature request.
In a comment of mine in the issue you've shared.(https://github.com/SAP/ui5-webcomponents/issues/4896). I spoke about the lifecycle that we will support it after the first opening, this is because of the lifecycle of the event. You have agreed with it, but if this does not work as you expected, we can have a research and try to alter the current behaviour and implement something in addition to it, so it can be matching your expectations.

**Comment by rchrdchn** [comment]
hi @tsanislavgatev - could you share the status on this issue, please?

**Comment by rchrdchn** [comment]
Hi guys - following up here. Any news?

**Comment by akshilverma** [comment]
Hi @Todor-ads, I am also facing the same problem. Is there any fix scheduled for this problem? And if yes, what would be the expected timeline for the release of the fix?

**Comment by rchrdchn** [comment]
Following up on this issue @petyabegovska @Todor-ads - any advancements on this? It's been opened for almost a year.

**Comment by tsanislavgatev** [comment]
Hello @rchrdchn ,

Can you please give us exact explanation on what are your expectations and your usecase so we can add functionality that would help you. After your explanation we will focus on the specific behaviour that you request to make the implementation.

Please elaborate on this in this issue.

Best Regards,
Tsanislav

**Comment by tsanislavgatev** [comment]
As there is no answer in the last 6 months, I am closing this issue.

**Comment by rchrdchn** [comment]
Hi @tsanislavgatev - apologies for missing your previous message.

As mentioned above in the "Steps to Reproduce" section of the ticket, we are expecting the component to keep the state for `Sort Order` and `Sort By` after navigating to a different page and going back to the page where the `ViewSettingsDialog` is.

You can reproduce it with these steps below:

- Go to 'https://codesandbox.io/s/ui5-webcomponents-forked-0y7rpv?file=/src/index.js'
- Click Open dialog button
- Sort Order: Descending AND Sort By: Name
- Click OK button
- Click on link: Go to page (/page)
- Click on link: Go back (/index)
- Click Open dialog button
- **Expected**: Sort Order: Descending AND Sort By: Name
- **Actual**: Initial Sort Order and Sort By
- Close and Open dialog again
- Sorting is --> Sort Order: Descending AND Sort By: Name
- **Expected**: Sort Order and Sort By to be coming from setConfirmedSettings object after going back from /page to /index
