### ISSUE TITLE
[SF][A11Y][Input] - Input hover style does not match accessibility requirements

### ISSUE THREAD

**Issue by zijies1** [SAP/ui5-webcomponents#5535]
Hi UI5 team,

### Description
Input hover style does not match accessibility requirements

###  Expected Behavior
Input hover style should be visible under high contrast mode

### Steps to Reproduce
Go to ['https://codesandbox.io/s/ui5-webcomponents-forked-0y7rpv?file=/src/index.js'](https://sap.github.io/ui5-webcomponents/playground/components/Input/?sap-ui-theme=sap_horizon_hcb&isrtl=false)
Try to hover over any input demo element, no hover style will show up.

### Isolated Example
none

### Priority
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### Stakeholder Info (if applicable)
- Organization: SuccessFactors

Rondo Shen
Thank you!

**Comment by Todor-ads** [comment]
Hello @zijies1,
Thank you for sharing this finding. Тhe component meets the visual specification. Input field does not change its style at hover state in high contrast theme

Regards,
Todor

**Comment by zijies1** [comment]
ok, thank you for replying!
