### ISSUE TITLE
[SF] [MultiComboBox] - Support showSelectAll option

### ISSUE THREAD

**Issue by 2bno1** [SAP/ui5-webcomponents#5537]
### **Feature Request Description**
SAPUI5 Multi Combo Box supports `showSelectAll` option to allow show or hide select all functionality (https://sapui5.hana.ondemand.com/#/entity/sap.m.MultiComboBox/sample/sap.m.sample.MultiComboBoxSelectAll). While the equivalent UI5 WC Multi Combo Box does not have this option.

![Screen Shot 2022-07-20 at 14 14 58](https://user-images.githubusercontent.com/1751846/179910852-730e0ff0-f6b5-41b3-9524-e1b2fc75d6e9.png)

Also, per https://experience.sap.com/fiori-design-web/multi-combobox/#behavior-and-interaction, it states `If selecting all items is a common use case, you can also show a Select All [checkbox](https://experience.sap.com/fiori-design-web/checkbox/) at the top of the list (property: showSelectAll).`

This ticket is to request to adding `showSelectAll` option to Multi Combo Box.

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by hristop** [comment]
Internal BLI was created: FIORITECHP1-28884
