### ISSUE TITLE
SideNavigation: Collapsed mode: Please give an option to hide the item with the group name

### ISSUE THREAD

**Issue by st-zelenin** [SAP/ui5-webcomponents#5550]
**Is your feature request related to a problem? Please describe.**
When `SideNavigation` is in the collapsed state and the user clicks on a `SideNavigationItem` that has several `SideNavigationSubItem`s, the popover appears. The first item in this popover is the one that represents the `SideNavigationItem`, all the rest - that represent `SideNavigationSubItem`. Sometimes in the expanded mode this `SideNavigationItem` is nothing more than just a name of a group and it is not navigatable, so it makes sense to be able to hide it for the popover in the collapsed mode. Unfortunately I could not find a way to remove the `SideNavigationItem`'s item from the popover in the collapsed mode.

**Describe the solution you'd like**
Either to remove `SideNavigationItem` from the popover or to provide a prop like `hideFromPopover` for `SideNavigationItem`.

Besides this first item is styled in the same way as others, so the users do not see any difference between `SideNavigationSubItem` and `SideNavigationSubItem` in the popover.

**Describe alternatives you've considered**
I tried several approaches to hide it, but did not succeed.

**Comment by dimovpetar** [comment]
Hello @st-zelenin ,

This request is not compatible with the design of the SideNavigation. We have discussed it and decided not to implement it. Moreover, the main SideNavigationItem should be clickable both when expanded and collapsed.

Best regards,
Petar
