### ISSUE TITLE
Table: Multi select Responsiveness not working according to fiori guidelines

### ISSUE THREAD

**Issue by biancamattosn** [SAP/ui5-webcomponents#5555]
**Describe the bug**
Multi select Responsiveness not working according to fiori guidelines.
- Columns are not aligned
- When selecting a row, it is only selecting the first part of the row, and not the entire row

**Isolated Example**
Check storybook provided the same issue is hapenning there.
https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-table--default-story

**To Reproduce**
1. Go to table
2. Reduce size of screen

**Expected behavior**
The margin is not aligned and it is selecting only the first part of the row, and not the entire row

**Screenshots**
Here is the react web components behavior:
![image](https://user-images.githubusercontent.com/91496753/180450933-03cd0ae5-3419-45b0-97f9-a62150e4d5cd.png)

Here is the sample provided from the ui5
https://sapui5.hana.ondemand.com/#/entity/sap.m.Table/sample/sap.m.sample.TableMultiSelectMode
![image](https://user-images.githubusercontent.com/91496753/180451452-5b6dcb47-5fff-4ca2-a4c3-ecfdc9762e78.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.5.0
`@ui5/webcomponents-react` version: 0.26.0
Operating System: macOS
Browser: Chrome

**Comment by dimovpetar** [comment]
Hello @SAP/ui5-webcomponents-topic-rl ,

This issue is also reproducible on the UI5 Web Components Playground https://sap.github.io/ui5-webcomponents/playground/components/Table/. Looks like the selection background is applied only of the first `tr` element. For comparison check the sample in OpenUI5.

Best regards,
Petar

**Comment by niyap** [comment]
Hello @biancamattosn,

Thanks for sharing your findings!

Actually that is a limitation, which is described in our documentation: https://sap.github.io/ui5-webcomponents/playground/components/Table/
"Note: Currently, when a column is shown as a pop-in, the visual indication for selection is not presented over it."

Kind Regards,
Niya
