### ISSUE TITLE
Quotation mark missing in documentation about "Menu" button - really quick fix

### ISSUE THREAD

**Issue by ECasio** [SAP/ui5-webcomponents#5557]
### **Issue Description**
The "Menu" functionality is missing a " in the beginning for the import statement. It says:

import @ui5/webcomponents/dist/Menu.js";

same also later

import @ui5/webcomponents/dist/MenuItem.js";

it should be:
import **"**@ui5/webcomponents/dist/Menu.js";
import **"**@ui5/webcomponents/dist/MenuItem.js";

Have a look yourself: https://sap.github.io/ui5-webcomponents/playground/components/Menu/

### **Issue Type**

- [ ] Documentation is unclear
- [x] Documentation is incorrect
- [ ] Documentation is missing
- [ ] Other

**Comment by stbodurov** [comment]
Hi @SAP/ui5-webcomponents-topic-b,

There are a few missing opening quotes in the [Overview > ES6 module import](https://sap.github.io/ui5-webcomponents/playground/components/Menu/#:~:text=ES6%20Module%20Import-,import%20%40ui5,-/webcomponents/dist/Menu) sections of each Menu component. Could you take a look?

Regards,
Stanislav
