### ISSUE TITLE
Add 'open' attribute in Menu component

### ISSUE THREAD

**Issue by TinaC** [SAP/ui5-webcomponents#5558]
### **Feature Request Description**

When the user clicks the Menu button while the menu is opened, we want it to close
https://sap.github.io/ui5-webcomponents/playground/components/Menu/

Something like:
```js
const onButtonClick = () => {
  if (buttonRef.current.opened) {
    menuRef.current.close();
  } else {
    menuRef.current.showAt(buttonRef.current);
  }
};
```

### **Proposed Solution**

Add opened attribute so we can check whether we should close this menu

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### **Stakeholder Info** (if applicable)

- Organization: {JAM}

**Comment by petyabegovska** [comment]
Hi @TinaC and @ej612,

We will adopt "open" & "opener" methods from Popover, as described in https://github.com/SAP/ui5-webcomponents/issues/5095.

Best regards,
Petya
