### ISSUE TITLE
[SF_ACC] Dialog: box-shadow on footer

### ISSUE THREAD

**Issue by rchrdchn** [SAP/ui5-webcomponents#5561]
**Describe the bug**
There is a noticeable box-shadow on the Dialog's footer (bottom) when using it ~~with high contrast black and white~~ in general.

**Isolated Example**
https://sap.github.io/ui5-webcomponents-react/?path=/docs/modals-popovers-dialog--default-story&globals=theme:sap_fiori_3_hcb

**To Reproduce**
1. Go to 'https://sap.github.io/ui5-webcomponents-react/?path=/docs/modals-popovers-dialog--default-story&globals=theme:sap_fiori_3_hcb'
2. Click "Open Dialog" button
3. Notice the box-shadow on the footer

**Expected behavior**
No box-shadow on the Dialog's footer (bottom) when using it with high contrast black and white.

**Screenshots**
![SCR-20220722-k3b](https://user-images.githubusercontent.com/11576789/180571686-ac53c1b3-20ff-47f9-b775-f2d1891db809.png)
![SCR-20220722-k44](https://user-images.githubusercontent.com/11576789/180571693-b0b905a9-df6d-4b09-a47c-d32894ce18c8.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents-react` version: [0.26.2](https://github.com/SAP/ui5-webcomponents-react/compare/v0.26.1...v0.26.2)
Operating System: macOS
Browser: Chrome, Firefox, Safari

**Comment by dimovpetar** [comment]
Hello @MarcusNotheis , besides the issue of the combination of `ui5-bar` and `ui5-dialog`, the usage in the WebComponents for React playground is incorrect. There bar with design `Header` is placed in the footer.

**Comment by dimovpetar** [comment]
Hello @SAP/ui5-webcomponents-topic-rd ,

Please check how `ui5-bar` with design `Footer` can be used in the slot footer of `ui5-dialog`. It brings its own box-shadow/border at the moment.

Best regards,
Petar

**Comment by MarcusNotheis** [comment]
> the usage in the WebComponents for React playground is incorrect. There bar with design Header is placed in the footer.

The UI5 Web Components for React Playground is now adjusted to use the `Footer` Design of the Bar. Besides having the additonional box shadow, it looks like the resizing is going a bit crazy:

![2022-07-25_18-22-54 (2)](https://user-images.githubusercontent.com/8775211/180827842-19733b5f-87d9-4b5c-8c7f-f08e5ab92f79.gif)

**Comment by rchrdchn** [comment]
Hi team - following up on this issue. Any updates on this?

**Comment by LidiyaGeorgieva** [comment]
Hello @SAP/ui5-webcomponents-topic-b ,

Currently there are to issues - the one with the top border and the other with the resizing (causing movement of the button).

I see two solutions for the first one - removing the border with custom css by the user or adding one more value to "design" property of the Bar - for example "Transparent". What sounds more appropriate to you?

The second issue can be reproduced on the test page of the Bar component - just make the width of the viewport under 500px - the class "ui5-bar-root-shrinked" and the attribute "_shrinked" starts to show and hide in the DOM tree very fast.

Best Regards,
Lidiya

**Comment by rchrdchn** [comment]
Hi @nnaydenow - an issue seems to have come up after this fix (border top). See below.

![SCR-20220912-fm6](https://user-images.githubusercontent.com/11576789/189726973-5a98ae79-fab8-49dd-876c-2512da7f5a54.png)

![SCR-20220912-fng](https://user-images.githubusercontent.com/11576789/189726983-ea03d4d8-eb5b-466f-b903-2bee055868d0.png)

**Comment by nnaydenow** [comment]
hi @Todor-ads ,

could you please check because issue still persists?

**Comment by rchrdchn** [comment]
hi @nnaydenow @Todor-ads - what's the status on this issue? it's been a few months since the last update.

**Comment by rchrdchn** [comment]
Hi guys - following up here. Any news?

**Comment by rchrdchn** [comment]
This behavior happens in a general purpose Dialog, not only high contrast mode.

**Comment by Todor-ads** [comment]
Hello @SAP/ui5-webcomponents-topic-rd,
Can you look into this issue?
If a ui5-bar is used in the ui5-dialog, an additional border appears that can be removed by you are side

Best Regards,
Todor

**Comment by nnaydenow** [comment]
In addition to @Todor-ads,

Since the ui5-bar can't determine its parent, my proposal for a solution to this problem is to fix it inside the ui5-dialog. ui5-dialog knows whether it has a ui5-bar used in the footer slot and it can remove the ui5-bar's border.
