### ISSUE TITLE
Deleting input with the "delete" key does not update the (last) value on the input element

### ISSUE THREAD

**Issue by veith** [SAP/ui5-webcomponents#5562]
### **Bug Description**
When you delete the content of a "Input" with the delete key, the value ist not  "". It is the last letter or number which was on the component.

### **Expected Behavior**
The same result as if you would delete the content with the backspace key.

### **Steps to Reproduce**
1. Enter content in an input
2. Move the cursor before the first letter
3. Delete content with delete
4. Check the value of input.value

### **Isolated Example**
[CodeSandbox](https://codesandbox.io/s/ui5-webcomponents-forked-q2v5gl?file=/src/index.js).

### **Context**
- UI5 Web Components version: 1.4.0, 1.5.0, 1.6.0
- OS/Platform: Any
- Browser: Any
- Affected component: "Input"

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

- Business impact: Wrong data is sent to the server, because the UI suggest you an empty value but the data is not empty.

**Comment by dimovpetar** [comment]
Hello @SAP/ui5-webcomponents-topic-rl ,

This is reproducible issue with input of type "Number" (it is not reproducible with type "Text" for example). When you delete the value symbol by symbol using the DELETE key, the last symbol remains in the `value` property/attribute.

Best regards,
Petar

**Comment by elenastoyanovaa** [comment]
Hello,

Could you please re-test the issue with the latest main version? I think that we recently fixed the issue with the following PR:
https://github.com/SAP/ui5-webcomponents/pull/5671

What I tested is the following:
- https://sap.github.io/ui5-webcomponents/main/playground/components/Input/
- Set a type="Number" to the first input example.
- Type a number
- Move the cursor to the 1st position
- Press delete
Observed that the value gets updated.

Could you please check and close the issue if it is fixed?

Kind Regards,
Elena

**Comment by veith** [comment]
The "value" of the inner element (input) is correct **''**. The "value" of the ui5-input is not correct **'4'**.

**Comment by elenastoyanovaa** [comment]
Hello,

Version 1.6.0 was released in July https://github.com/SAP/ui5-webcomponents/releases/tag/v1.6.0 and the fix is from 4 days ago https://github.com/SAP/ui5-webcomponents/pull/5671 and it is still not released. This is why I sent a link to the main version of the components. It has all the latest fixes and features applied. 

Could you try to reproduce the issue using the steps I provided or adjusting the playground sample?

Kind Regards,
Elena

**Comment by veith** [comment]
Sorry, was a misunderstanding.

I tested it with #5671 locally and everything works as intended.
