### ISSUE TITLE
[SF][Safari][ui5-panel]: header focus style is not right in Safari for horizon theme

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents#5564]
### **Bug Description**
The header focus style of ui5-panel is not right in Safari for horizon theme.

### **Expected Behavior**
Should have border-radius for header focus style

### **Steps to Reproduce**
1. Use Safari to go to 'https://sap.github.io/ui5-webcomponents/playground/components/Panel/?sap-ui-theme=sap_horizon&isrtl=false'
2. The header focus style of ui5-panel is not right in Safari for horizon theme.

### **Context**
- UI5 Web Components version: {1.4.0}
- OS/Platform: {...}
- Browser: {Safari}
- Affected component: {...}

### **Log Output / Stack Trace / Screenshots**
<img width="1474" alt="2022-07-25_19-06-58" src="https://user-images.githubusercontent.com/13098801/180763655-ab1f7e11-39a5-4b7f-b044-a432328fe5e4.png">

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {SAP SuccessFactors}
- Business impact: {...}

**Comment by stbodurov** [comment]
Hi @SAP/ui5-webcomponents-topic-rl,

Looks like the `border-radius` CSS property of `ui5-panel`'s header is not being applied on Safari. This is reproducible in the samples: https://sap.github.io/ui5-webcomponents/playground/components/Panel/?sap-ui-theme=sap_horizon&isrtl=false

Could you take a look?

Regards,
Stanislav
