### ISSUE TITLE
[SF][ui5-table]: there is no bottom border of last data row for horizon theme

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents#5565]
### **Bug Description**
There is no bottom border of the last data row for horizon theme.

### **Expected Behavior**
Should have bottom border of the last data row.

### **Steps to Reproduce**
1. Go to 'https://sap.github.io/ui5-webcomponents/playground/components/Table/?sap-ui-theme=sap_horizon&isrtl=false'
2. There is no bottom border of last data row

### **Context**
- UI5 Web Components version: {1.4.0}
- OS/Platform: {...}
- Browser: {}
- Affected component: {...}

### **Log Output / Stack Trace / Screenshots**
<img width="1496" alt="2022-07-25_19-13-51" src="https://user-images.githubusercontent.com/13098801/180764737-50b827d7-c925-4a87-a9cd-31366d3c21e3.png">

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by stbodurov** [comment]
Hi @SAP/ui5-webcomponents-topic-rl,

Looks like the last table row does not have a bottom border in Horizon.

The UI5 analogue doesn't have one either: https://sapui5.hana.ondemand.com/1.104.1/#/entity/sap.m.Table/sample/sap.m.sample.TableBreadcrumb

Here are the styles that explicitly remove it in UI5:
https://github.com/SAP/openui5/blob/36ec485601d65419a0cf983ec190b8a78f11a605/src/themelib_sap_horizon/src/sap/m/themes/sap_horizon/Table.less#L37

I couldn't find this mentioned in the spec, but it seems to be intended. Could you take a look?

Regards,
Stanislav

**Comment by elenastoyanovaa** [comment]
Hello @GongRichard ,

The current visual specification does not say that a bottom border should be present. The UI5 Table also does not have a bottom border in Horizon. I have informed the responsive designer, but a decision of the matter will be made after a discussion between the designers and the UI5 table team. 

Can you please give us information why a bottom border should be present?

Kind Regards,
Elena

**Comment by GongRichard** [comment]
Hi @elenastoyanovaa,
You can check https://wiki.one.int.sap/wiki/display/visualcore/ResponsiveTable+%28Horizon%29+-+Specification, there has a bottom border.
Thanks,
Richard
