### ISSUE TITLE
limitation in the time component for different languages

### ISSUE THREAD

**Issue by aadi96-rolls** [SAP/ui5-webcomponents#5570]
### **Bug Description**
There is a limitation on the time component for languages with the UI5 component ui5 wheelslider. We are not able to localise the AM/PM in the respective locale due to this issue.

### **Expected Behavior**
The data within the component should be translated when we change the locale. 

### **Steps to Reproduce**
In the example as we see the box where the meridian is displayed we want this to be translated and currently we do not have the ability in the component which can be used for translating.
<img width="287" alt="Screen Shot 2022-07-26 at 9 46 37 AM" src="https://user-images.githubusercontent.com/32263757/180921821-1a68ec3c-4160-4a2c-990b-2bdd722f421c.png">

### **Isolated Example**
If possible, please provide an isolated example by forking [CodeSandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html).

### **Context**
- UI5 Web Components version: {...}
- OS/Platform: {...}
- Browser: {...}
- Affected component: {...}

### **Log Output / Stack Trace / Screenshots**
```
{...}
```
### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by MapTo0** [comment]
Dear @aadi96-rolls 

Could you be more specific with your feature request / issue and provide an example?

Regards,
Martin
