### ISSUE TITLE
[Feature Request][SF]: support the css part for the `ui5-busy-indicator-root`

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents#5574]
### **Feature Request Description**
hi, team,

Currently we used the below js for customized the ui5-busy-indicator-root css

```js
addCustomCSS(
  "ui5-busy-indicator",
  `
  :host(.container) .ui5-busy-indicator-root {
    width: 100%;
    height: 100%;
    display: block;
  }
  `
);
```
We think it's not elegant.  And there're so many other use cases for  customizing the ui5-busy-indicator-root css.

### **Proposed Solution**
So,  Can you please support the `ui5-busy-indicator-root ` as a css part for us. thus we can do the customize in css style.

```css
.xxx::part(root) {
  display: block;
}
```

### **Priority**
- [] Low
- [x] Medium
- [] High
- [] Very High

**Comment by stbodurov** [comment]
Hi @SAP/ui5-webcomponents-topic-rd,

Could you please take a look at this feature request for `ui5-busy-indicator`?

Regards,
Stanislav

**Comment by dimovpetar** [comment]
Hello @sfsf-xweb-sh ,

Can you share more about why you need this? With the `ui5-busy-indicator` you usually set the dimensions of your inner element, and the busy indicator automatically stretches on top of your element. Like this:
```html
<ui5-busy-indicator active>
    <div style="width: 400px; height: 200px; background-color: red;"></div>
</ui5-busy-indicator>
```
As stated in the [documentation](https://sap.github.io/ui5-webcomponents/playground/components/BusyIndicator/), the `ui5-busy-indicator` element itself is `inline-block` by default, so if you need to make it block element, you can do it like this:
```html
<ui5-busy-indicator active style="display: block;">
    <div style="width: 400px; height: 200px; background-color: red;"></div>
</ui5-busy-indicator>
```

Best regards,
Petar

**Comment by sfsf-xweb-sh** [comment]
hi, team

I want to reopen this tkt or we'll create a new one.


@dimovpetar 

in your mentioned  2 cases.

`<ui5-busy-indicator active style="display: block;">
    <div style="width: 400px; height: 200px; background-color: red;"></div>
</ui5-busy-indicator>` 

they has a same point that is the busy-indicator size is depend on the child content size right?

think about my case.

`
 <div style="width: 400px; height: 200px; background-color: red;">
    <ui5-busy-indicator active style="display: block, width: 100%, height: 100%">
        <div style="width: 20px; height: 20px; background-color: gray;"></div>
    </ui5-busy-indicator>
</div>
` 

how about this case. I think this case the busy-indicator will not correct.

and also I think it's the most use case.

Thanks

**Comment by dimovpetar** [comment]
Hello @sfsf-xweb-sh ,

There is nothing between the **`** signs, perhaps you couldn't post the example?
Can you please edit this codesandbox https://codesandbox.io/s/ui5-webcomponents-forked-uw18me?file=/index.html to demonstrate the problems you are facing?

Best regards,
Petar
