### ISSUE TITLE
Disable whole list and prevent user click item

### ISSUE THREAD

**Issue by wulinjie122** [SAP/ui5-webcomponents#5576]
### **Feature Request Description**
Hi Team, I am from successfactors, recently we have a feature which renders a list in chat window, but we want to disable entire list when user lost dialog session under certain conditions, this can prevent user clicking list item.

here is the design:
<img width="701" alt="2022-07-27 14-52-54" src="https://user-images.githubusercontent.com/6195114/181181224-dac39686-bcf8-4083-9c67-3d6975bde6d1.png">

### **Proposed Solution**
Can we achieve this by adding a grey overlay to dull the image and text when ui5-list was disabled?

### **Proposed Alternatives**
Currently we simply added some css on ui5-list to disable cursor, it would be better if ui5-list has an option to achieve this effect.

```css
pointer-events:none;
cursor:not-allowed;
```

### **Additional Context**
Add other context or screenshots related to the feature request here.

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: SuccessFactors
- Business impact: {...}

**Comment by stbodurov** [comment]
Hi @SAP/ui5-webcomponents-topic-p,

Could you take a look at this feature request? The requested functionality looks similar to `sap.ui.core.Control`' s `blocked` property, which is **deprecated** due to poor accessibilty support. However, in UI5 this property is inherited, so if this is even to be considered, perhaps it may need to be introduced centrally? Also involving @SAP/ui5-webcomponents-topic-core.

Regards,
Stanislav

**Comment by ilhan007** [comment]
Lowering the priority and removing the "High" prio label based on the recent SF prioritisation list we got.

Hello @wulinjie122 get in touch with your leads to adjust the priority.

**Comment by dobrinyonkov** [comment]
Hello, to be consistent with individual list items behavour - https://github.com/SAP/ui5-webcomponents/issues/5254#issuecomment-1237046253 - there are no plans for this functionality to be implemented for the whole list. 

Kind Regards,
Dobrin
