### ISSUE TITLE
Panel: Dropdown does not open/close when Enter key is pressed in Safari

### ISSUE THREAD

**Issue by gurkirpalgill** [SAP/ui5-webcomponents#5579]
**Describe the bug**
Using Safari, Tab to Countries Panel dropdown `>` and press Enter:
[Panel](https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-panel--with-custom-header)

Dropdown won't open.

**Expected behavior**
Dropdown should Expand/Collapse when pressing Enter key.

**Screenshots**
<img width="1409" alt="Screen Shot 2022-07-26 at 4 21 45 PM" src="https://user-images.githubusercontent.com/65705637/181128658-be6ec883-61cd-44cf-879b-406d833bb248.png">

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.6.0
`@ui5/webcomponents-react` version: 0.27.0
Browser: Safari

**Comment by stbodurov** [comment]
Hi @SAP/ui5-webcomponents-topic-rl,

Could you please take a look at this issue? Pressing Enter on `ui5-panel`'s button when using a custom header, quckly closes and opens the panel as if the click event is triggered twice.

It's reproducible on the sample mentioned by Marcus, https://sap.github.io/ui5-webcomponents/main/playground/components/Panel/

Regards,
Stanislav
