### ISSUE TITLE
[SF][ui5-input]: error thrown when use arrow key to change value in number type input

### ISSUE THREAD

**Issue by zhangliangyi** [SAP/ui5-webcomponents#5580]
### **Bug Description**
When using arrow up/down key to change the value in a number type input, error thrown in the console and `event.target.value` exposed in event handler is not up to date.

### **Expected Behavior**
The new value should be exposed via `event.target.value` correctly

### **Isolated Example**
https://codesandbox.io/s/ui5-webcomponents-forked-wh0jgc

### **Context**
- UI5 Web Components version: 1.5.0
- OS/Platform: MacOS
- Browser: Edge
- Affected component: ui5-input

### **Log Output / Stack Trace / Screenshots**
```
Uncaught TypeError: Cannot read properties of undefined (reading 'inputType')
    at Input._handleInput (bundle.esm.js:14020:55)
    at I.handleEvent (bundle.esm.js:7345:48)
_handleInput @ bundle.esm.js:14020
handleEvent @ bundle.esm.js:7345
```
https://github.com/SAP/ui5-webcomponents/blob/816edf048ddeb67bc6332d85d38bb93431a6b1fb/packages/main/src/Input.js#L999

The issue is not reproducible in Firefox.

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SF
- Business impact: {...}

**Comment by stbodurov** [comment]
Hi @SAP/ui5-webcomponents-topic-rl,

Could you take a look at this issue? Seems like when using arrow up/down, the input event has no eventType property, and `event.detail` is undefined too:

https://github.com/SAP/ui5-webcomponents/blob/816edf048ddeb67bc6332d85d38bb93431a6b1fb/packages/main/src/Input.js#L999

If you can't load the CodeSandbox, you can use the [Input type 'Number' sample](https://sap.github.io/ui5-webcomponents/playground/main/pages/Input/#input-required) to reproduce.

Regards,
Stanislav
