### ISSUE TITLE
[SF][ui5-menu] Menu throws an error in the console when hovering children

### ISSUE THREAD

**Issue by Neeeko** [SAP/ui5-webcomponents#5582]
### **Bug Description**
When hovering the "Sub Menu" of a ui5-menu with Sub-menu items, the following error is thrown to the console:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'hasChildren')
```

It doesn't seem to break the component behavior.

### **Expected Behavior**
No error should be thrown when using the component.

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/Menu/
2. Press the "Open Menu" button under the "Menu with Sub-menu items" example
3. Open the dev console
4. Move your curser over sub items multiple time, see the error in the console

### **Isolated Example**
![Screen Recording 2022-07-27 at 5 13 28 PM (1)](https://user-images.githubusercontent.com/7316793/181393994-ca839ece-6ed2-4ac3-a514-6922e28d4251.gif)

### **Context**
- UI5 Web Components version: 1.6.0
- OS/Platform: MacOS
- Browser: Chrome
- Affected component: ui5-menu

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SuccessFactors

**Comment by stbodurov** [comment]
Hi @SAP/ui5-webcomponents-topic-b,

Could you please take a look at this issue? When the mouseout and mouseover event handlers are invoked for subMenu items, the check for `item.hasChildren` throws an error, because `item` is undefined.

To reproduce, go to https://sap.github.io/ui5-webcomponents/main/playground/main/pages/Menu

Regards,
Stanislav
