### ISSUE TITLE
ui5-link: click event fires twice

### ISSUE THREAD

**Issue by ee92** [SAP/ui5-webcomponents#5588]
### **Bug Description**
When the ui5-link is clicked, the "click" event gets fired twice.

### **Expected Behavior**
Should only fire 1 "click" event per click

### **Steps to Reproduce**
1. Go to https://stackblitz.com/edit/js-fnto8y
2. click the link
3. check the console to see "link clicked" was printed twice

### **Context**
- UI5 Web Components version: 1.5.0
- OS/Platform: MacOS
- Browser: Chrome
- Affected component: ui5-link

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### **Stakeholder Info**

- Organization: SuccessFactors

**Comment by stbodurov** [comment]
Hi @ee92,

This issue is identical to #5477, hence I am closing it. You can track the status there.

Regards,
Stanislav
