### ISSUE TITLE
Implement Tree control

### ISSUE THREAD

**Issue by KAURHARM0** [SAP/ui5-webcomponents#559]
Can you please implement tree control as a web component?

**Comment by fifoosid** [comment]
Hello @KAURHARM0 

Thank you for this feature request. We will discuss it internally and will come back with a statement.

Best Regards,
Filip

**Comment by DesiMat** [comment]
Hi, we also need the Tree control for a project. Could you consider it sooner?

**Comment by tnurmi82** [comment]
Hi. I also came to this project specifically looking for a Tree.

I was hoping to find an alternative for the unfortunately buggy [fundamental-react TreeView](https://sap.github.io/fundamental-react/treeview)

Looks like I'll have to build some tree-like thing by combining Panel+Table...

**Comment by vladitasev** [comment]
Tree will be prioritized for the next major release (RC8)
You can track the progress here: https://github.com/SAP/ui5-webcomponents/issues/1550
