### ISSUE TITLE
[SF][A11Y][StandardListItem] - Need support for alternative text in StandardListItem image

### ISSUE THREAD

**Issue by zijies1** [SAP/ui5-webcomponents#5594]
### **Feature Request Description**
It seems that there are no feasible ways to pass an alternative text to the image element when using StandardListItem and there is no default value set neither, which is required to pass A11Y tests.

### **Proposed Solution**
Maybe we can add a new props value like imageAlt to StandardListItem or set a default value for the alt text of image element.

### **Additional Context**
<img width="1440" alt="Screen Shot 2022-08-01 at 09 45 14" src="https://user-images.githubusercontent.com/25004172/182057797-cf65b96f-d54d-41ad-a899-06591c36982a.png">

### **Priority**
- [ ] Low
- [ ] Medium
- [ ] High
- [x] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: SuccessFactors

Rondo Shen
Thank you!

**Comment by MapTo0** [comment]
Hello @SAP/ui5-webcomponents-topic-p 

Please have a look in that request.
I checked that in openui5 the avatar is in the API as an aggregation.
In our case it is a property.

* In case you expect to have more similar request, please consider adding slot instead of lots of properties.

Regards,
Martin

**Comment by dobrinyonkov** [comment]
Internal Reference: BGSOFUIPIRIN-6177

**Comment by dobrinyonkov** [comment]
Hi, this can be achiveived by using the `imageContent` slot: 

```html
<ui5-li> 
	<div slot="imageContent">
		<ui5-avatar accessible-name="Custom image accessible name">
			<img src="./img/woman_avatar_5.png" alt="Woman image">
		</ui5-avatar>
	</div>
        Avatar inside imageContent slot
</ui5-li>
```

Regards,
Dobrin
