### ISSUE TITLE
MulticomboBox : Event trigger on token delete from MulticomboBox

### ISSUE THREAD

**Issue by Arora05** [SAP/ui5-webcomponents#5598]
###MulticomboBox : Event trigger on token delete from MulticomboBox**
When I select an option from dropdown and the token is being shown on the MultiComboBox. Can we have something like https://sapui5.hana.ondemand.com/#/api/sap.m.MultiInput%23events/tokenUpdate event being trigger whenever I click on x icon of token

**Comment by MapTo0** [comment]
Hello @Arora05 

When you click the "X" icon of the token you are getting a `selection-change` event on which you can react.

Regards,
Martin

**Comment by Arora05** [comment]
Hello @MapTo0,
Can you tell me something which will block the deletion token or trigger the event using which we can block the deletion of token?

**Comment by MapTo0** [comment]
You want to prevent deletion of tokens? disabled the component multi combobox?

**Comment by Arora05** [comment]
Hello @MapTo0 , is this functionality possible to implement?
