### ISSUE TITLE
Add 'closeMenuOnClick' property to MenuItem component

### ISSUE THREAD

**Issue by ej612** [SAP/ui5-webcomponents#5600]
### **Feature Request Description**
The current behavior of the Menu component is that a click on a MenuItem will close the menu. This behavior isn't great for our use case, as we expect the user to want to select multiple items, meaning they would have to re-open the menu several times.

### **Proposed Solution**
Would it be possible to add something like a property "closeMenuOnClick" to MenuItem, which would take a boolean and allow us to tell the Menu whether a click on this menu item should close the menu or not?

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

### **Stakeholder Info**

- Organization: SAP
- Business impact: Confidential (please contact me for more info)

**Comment by MapTo0** [comment]
Dear @SAP/ui5-webcomponents-topic-b 

The request is to prevent closing of the menu when an item is clicked.
My suggestion is to provide `preventDefault` option to the event instead of a new property.

Could you please have a look and evaluate if this feature request should be implemented.

Regards,
Martin

**Comment by petyabegovska** [comment]
Hi @ej612,

When do you need the feature so that you can consume it in your release?

Best regards,
Petya

**Comment by petyabegovska** [comment]
Hi @ej612,

Can you show us your use case?
The control doesn't support multi selection and providing prevent default of the close action I assume that will not solve your problem.

Best regards,
Petya

**Comment by petyabegovska** [comment]
Hi,

"So my request is to provide an option for me to indicate to the menu that I don't want a click on a certain menu item to close the menu." This can be implemented but the menu doesn't have a selected state and doesn't have multiple selection, so the whole use case will not work.

You can try to use Button that opens a  ResponsivePopover with List inside, see the sample: https://codesandbox.io/s/nifty-nobel-lxgfl0?file=/index.html

Best regards,
Petya
