### ISSUE TITLE
Add "SearchField" Fiori component

### ISSUE THREAD

**Issue by ej612** [SAP/ui5-webcomponents#5604]
### **Feature Request Description**
Would it be possible to add an implementation of the [SearchField Fiori component](https://experience.sap.com/fiori-design-web/search)?
I have found a [duplicate of this request from 3 years ago](https://github.com/SAP/ui5-webcomponents/issues/259), in which it is suggested to use the Input component instead.
We have been asked explicitly to use SearchField instead of Input, as it keeps the user input history, which the Input control doesn't seem to do.

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### **Stakeholder Info**

- Organization: SAP
- Business impact: Confidential (please contact me for more info)

**Comment by MapTo0** [comment]
Dear @SAP/ui5-webcomponents-topic-rl 

I am forwarding this just to discuss it with POs.
The author claims to need the "input history" of the input when used as a search field.

Unfortunately, this feature is actually not really well handled across all browsers.
Furthermore, our input is in the shadow root, even the form support is not going to work it as expected by the request.

I also checked the OpenUI5's search field and it does not support that functionality (correct me if I am wrong?)

Regards,
Martin
