### ISSUE TITLE
ui5-dialog links are read twice by screen reader

### ISSUE THREAD

**Issue by kwxue** [SAP/ui5-webcomponents#5608]
### **Bug Description**
Screen reader reads link within anchor element of a ui5-dialog twice.

### **Expected Behavior**
The screen reader should only read the link once. 

On the ui5-dialog playground (https://sap.github.io/ui5-webcomponents/playground/components/Dialog/), if an anchor element is inserted into the DOM, the screen reader only declares the dialog and link once. However, this behavior isn't replicated in a sandbox environment.
![Screen Shot 2022-08-01 at 5 51 28 PM](https://user-images.githubusercontent.com/55603752/182268751-8ad0f18e-3ec8-4b6b-8548-c31141ac3bd2.png)
![Screen Shot 2022-08-01 at 5 51 42 PM](https://user-images.githubusercontent.com/55603752/182268739-9f8a8036-9c89-43a1-9539-9c4205d52438.png)

### **Steps to Reproduce**
1. Go to https://stackblitz.com/edit/js-yjiktr?file=index.js with NVDA screen reader and speech viewer running.
2. Tab focus the "Open Dialog" button.
3. Press enter
4. Should see the following, where the screenreader repeats the link and some other content. 
![Screen Shot 2022-08-01 at 5 40 11 PM](https://user-images.githubusercontent.com/55603752/182267732-91b92929-f266-4869-841f-e5bf839ba886.png)
![Screen Shot 2022-08-01 at 5 40 22 PM](https://user-images.githubusercontent.com/55603752/182267737-851b9f7d-2914-4355-9a59-d03de05a8dff.png)

### **Context**
- UI5 Web Components version: 1.6.0
- Affected component: ui5-dialog

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### **Stakeholder Info** (if applicable)
- Organization: SuccessFactors

**Comment by MapTo0** [comment]
Hello @kwxue 

This is due to the lack of `role="application"` attribute in your sample.
Once you place that attribute - the issue is not reproducible.

Regards,
Martin

**Comment by kwxue** [comment]
Hi Martin,

Is there a way to keep the non-repeating behavior with `role ='dialog'`? I tested adding `role ='dialog'` to one of the sample dialogs in the playground and it seems to not-repeat, but `role='dialog'` in the sandbox still persists with repeating.


Thanks,

Kyle
