### ISSUE TITLE
[SF] Bar: Button is "shaking" when displayed inside a Dialog

### ISSUE THREAD

**Issue by Neeeko** [SAP/ui5-webcomponents#5610]
**Describe the bug**
When displaying a button as the `endContent` of a Bar inside a Dialog, the button will "shake".
Unfortunately, since codesandbox is unreachable right now, I wasn't able to reproduce in ui5-webcomponents only so it might be unrelated to ui5-webcomponents-react.
![Screen Recording 2022-08-01 at 6 11 41 PM](https://user-images.githubusercontent.com/7316793/182270972-86bb1c68-9f0a-493b-b044-5d865279622a.gif)

**To Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents-react/?path=/docs/modals-popovers-dialog--default-story
2. Click "Open Dialog"
3. Observe this behavior on the Close button

**Expected behavior**
Button should stay at a fixed position.

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.6.0
`@ui5/webcomponents-react` version: 0.27.0
Operating System: MacOS
Browser: Chrome

**Comment by AndrianStoikov** [comment]
We see the same issue in RBSC.

**Comment by reqyou** [comment]
- seeing the same for `MessageBox`
- seems to depend on the resolution, because we see this issue only for the exact width of greater `1958`

**Comment by Todor-ads** [comment]
closed this as [completed](https://github.com/SAP/ui5-webcomponents/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) in #5678
