### ISSUE TITLE
FilterSelectionDialog: OnGrow is not always called

### ISSUE THREAD

**Issue by Saschl** [SAP/ui5-webcomponents#5617]
**Describe the bug**
When using ListGrowingMode.Scroll with the FilterSelectionDialog, the "growing" handler is not always called. It seems like it is dependent on the window size of the browser.

**Isolated Example**
https://codesandbox.io/s/relaxed-moon-c5qsfb?file=/src/App.js&resolutionWidth=1410&resolutionHeight=1220

**To Reproduce**
1. Go to the sample and open the developer mode and console.
3. Scroll down to the end of the list
4. No console output should be triggered when scrolling to the end of the list
5. Change the screen size in codesandbox to 1410x1230 and scroll down again.
6. "Growing" should be output to the console

**Expected behavior**
The event should also be fired when reaching the end of the list and not depend on screen size.

**Screenshots**
No event triggered: 
![image](https://user-images.githubusercontent.com/19493808/180435184-ebc5dbee-933e-400b-bb2a-f750764cff81.png)

Resolution changed, event works:
![image](https://user-images.githubusercontent.com/19493808/180435289-b1dbe030-79ad-4282-b5cb-fb8efa4a2d09.png)

**UI5 Web Components for React Information**

```
   "@ui5/webcomponents": "~1.5.0",

   "@ui5/webcomponents-fiori": "~1.5.0",

   "@ui5/webcomponents-react": "^0.26.0"
```
Operating System: Windows 10
Browser: Edge 103.0.1264.62

**Comment by ndeshev** [comment]
Hello, for me, when using plain UI5 WebComponents the event is fired every time, no matter of the resolutions. I was only able to reproduce it in the author's React example.
