### ISSUE TITLE
IllustratedMessage: The IllustratedMessage (No Data) messages text spell error

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents#5626]
**Describe the bug**
Hi, team
The IllustratedMessage (No Data) messages text spell error

**Expected behavior**
Expected messages: When there is, you'll see it here.

**Screenshots**
![image](https://user-images.githubusercontent.com/78520316/182743857-771f4793-33a8-4392-b7fb-a46af2b417a2.png)

**Comment by MapTo0** [comment]
Dear @SAP/ui5-webcomponents-topic-core 

Looks like an issue with translations.
example: https://jsbin.com/sufecerecu/edit?html,console

formatting function seems to strip the `'` signs coming from translations.

Regards,
Martin

**Comment by sfsf-xweb-sh** [comment]
hi, team 

thanks for quick action.

how about the release plan to this fix?

**Comment by nnaydenow** [comment]
Hi @sfsf-xweb-sh ,

Fix is part of next release (version 1.7.0).

Regards,
Nayden
