### ISSUE TITLE
Add TitleBar option for tables

### ISSUE THREAD

**Issue by pdbngo** [SAP/ui5-webcomponents#5632]
### **Feature Request Description**
The tables are currently missing a TitleBar option that allows us to input a label for the table and a toolbar, which serves as an entrypoint to table actions.

Reference: https://experience.sap.com/fiori-design-web/responsive-table/#components

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### **Stakeholder Info** (if applicable)

- Organization: SAP
- Business impact: Low

**Comment by MapTo0** [comment]
Dear @SAP/ui5-webcomponents-topic-rl 

This is a feature request for the table.

Regards,
Martin

**Comment by nikolay-kolarov** [comment]
Hello,

The ui5-table aim is to be quite simple component, close to the html <table> functionality.
You can use a ui5-bar to put the title and the buttons on top of the table. And then use the accessibleName or accessibleNameRef APIs of the ui5-table to reference the title.
If this does not solve you case, please reopen the issue and provide further details.

Best Regards,
Nikolay
