### ISSUE TITLE
Input: OnChange event not triggered after clearing the state

### ISSUE THREAD

**Issue by guedes4g** [SAP/ui5-webcomponents#5635]
**Describe the bug**
Input is not calling on change as expected. Read the steps and watch the gif for better understanding:

**Isolated Example**
Forgive me for not using the sanbox. It is currently being blocked by my firewall.
```js
import React, { useState } from 'react';
import { Button, Input } from '@ui5/webcomponents-react'

const App = () => {
  const [value, setState] = useState('');
  const handleChange = (e) => {
    setState(e.target.value);
  }
  return (
    <>
      <Button onClick={() => setState('')}>Clear</Button>
      <Input value={value} onChange={handleChange} />
      <p>{value}</p>
    </>
  );
};

export default App;
```

**To Reproduce**
1. Have an input field with some value eg. 'name@company.com' and copy to your clipboard
2. Programatically clear the value of the state of that given input field
3. Paste the value on your clipboard to the field again
4. See error (value is not updated, onchange is not triggered)

**Expected behavior**
After clearing and pasting the old value I expect the onChange to be triggered again

**Screenshots**
![recording](https://user-images.githubusercontent.com/29311988/182922515-ac5c9c30-61b0-4057-a655-2fc330575e86.gif)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.6.0
`@ui5/webcomponents-react` version: 0.27.1
Operating System: MacOS
Browser: Chrome (Version 103.0.5060.134 (Official Build) (x86_64))

**Comment by Lukas742** [comment]
Should be the same issue as described [here](https://github.com/SAP/ui5-webcomponents/issues/5490#issuecomment-1184915510).

**Comment by MapTo0** [comment]
Hello Team @SAP/ui5-webcomponents-topic-rl 

Issue introduced by latest refactoring of change event.
Example: https://jsbin.com/pobagobovo/1/edit?html,console,output

Regards,
Martin
