### ISSUE TITLE
Active Element of Row is undefined after removing this row via switch element

### ISSUE THREAD

**Issue by MFel0123** [SAP/ui5-webcomponents#5636]
### **Bug Description**
We use a switch element in each row of the table. This switch is used to set the regarding object in other state (from the business perspective). This is the reason why the row now will be deleted from the table.
The whole process is working fine for us.

But now I saw this error in the console when doing exactly this - using the switch and toggle:
![image](https://user-images.githubusercontent.com/62615376/183060096-1d1bc79d-297f-4bff-9e67-113e11c0e4e2.png)

The reason is that at first the switch is doing its task in the toggle method. Then the action is performed which leads to a new table where the row from the action is now missing.

But then it seems that it is not over with the event handling process: Now we are in the table row context again. The active element is gone and we get the error in the console.

Should you not just check whether the active element still exists before getting the attribute from it? I mean this line in the coding:
return this.getRootNode().activeElement.hasAttribute(attr);

The error in the console stops some of our tests in Cypress. So that is why we have an additional interests in this.
By the way: It seems that I do not have access to codesandbox.io. I hope that you can check this at first on your own.

### **Expected Behavior**
The error in the console should not the thrown. Internally it must be recognized that the row context is gone, somehow.

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by MapTo0** [comment]
Hey @MFel0123 

Could you provide a codesandbox example so we can speed up that?

Regards!
Martin

**Comment by MFel0123** [comment]
Hello Martin,
see my last comment:
> By the way: It seems that I do not have access to codesandbox.io. I hope that you can check this at first on your own.

I really have problems with codesandbox.io - it seems that our VPN is blocking it somehow.

The key to the problem could be: 
You trigger a switch action from within the table (in a certain row), an event is triggered for the switch element (but also for the whole row??), then controlled by the app it comes to a re-rendering of the table After this somehow the event handling should go on in the table row, but now the context (the active element) is gone, because of the re-rendering.

I try to find ways to hand over more information. But please try it yourself in the meantime.
Best Regards
Matthias

**Comment by ndeshev** [comment]
Hello @MFel0123

I think codesandbox is working fine now, if it's not for you, please try some other similar tool to provide a reproducible example.
