### ISSUE TITLE
Date pickers have white space below input

### ISSUE THREAD

**Issue by allen138** [SAP/ui5-webcomponents#5640]
### **Bug Description**
Hi team,

Please help to take a look as it appears there is some unnecessary white space below the date picker inputs. Please see:
![image](https://user-images.githubusercontent.com/38701667/183138199-5bfba01f-f451-4849-9073-b1acaa1df5ec.png)
![image](https://user-images.githubusercontent.com/38701667/183138292-3cc0798a-7726-43ca-ab1d-b3b97f484696.png)

Its not as apparent when the standard '--sapBackgroundColor', but when it is on a placemat with a darker hue it becomes very evident.  

Thanks,
Allen

### **Expected Behavior**
There should be no white space below that date picker input.

### **Steps to Reproduce**
1. Go to [ui5-webcomponents/playground/components/DatePicker/](https://sap.github.io/ui5-webcomponents/playground/components/DatePicker/)

### **Context**
- UI5 Web Components version: all (I'm using the latest 1.6)
- OS/Platform: All
- Browser: All
- Affected component: [ui5-date-picker, ui5-date-time-picker, ui5-date-range-picker]

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SF
- Business impact: Medium (We use this component extensively throughout the application)

**Comment by nnaydenow** [comment]
Hi @allen138,

issue in code review. I hope that it will be merged to the project until the end of the day.

Regards,
Nayden
