### ISSUE TITLE
[SF][a11y][ui5-date-picker] Date picker has horizontal scroll bar at 320px width responsive view

### ISSUE THREAD

**Issue by zhangliangyi** [SAP/ui5-webcomponents#5641]
### **Bug Description**
When `font-size` of body is set as 16px, the calendar dialog opened will have horizontal scroll bar at 320px width responsive view.

### **Expected Behavior**
Horizontal scroll bar should not be displayed.

### **Steps to Reproduce**
When `font-size` of body is set as 16px, per the css variable defined in
https://github.com/SAP/ui5-webcomponents/blob/4a3366a857cff77b9693529c5c8bc96fe148a011/packages/main/src/themes/base/sizes-parameters.css#L4

The calendar width will be 328px which causes the display of scroll bar

### **Isolated Example**
If possible, please provide an isolated example by forking [CodeSandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html).

### **Context**
- UI5 Web Components version: 1.6.0
- OS/Platform: MacOS
- Browser: Edge
- Affected component: ui5-date-picker

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SF
- Business impact: {...}

**Comment by nikolay-kolarov** [comment]
Hello @SAP/ui5-webcomponents-topic-b ,

Could you please have a look?

Thanks,
Nikolay

**Comment by unazko** [comment]
Hello @zhangliangyi,

Is there a specific reason for setting the font-size to 16px?

Best Regards,
Boyan Rakilovski

**Comment by zhangliangyi** [comment]
@unazko 
We are using 16px as the basis of rem is SF applications. Just wonder if there is any standard about that only `14px` font-size can be used as basis of rem in application with ui5-webcomponents?

**Comment by unazko** [comment]
Hi @zhangliangyi,

Apologies for the late response. I've got confused after many discussions on this topic.
There is no such standard indeed. We're going to fix the width of the calendar component now.

Best Regards,
Boyan
