### ISSUE TITLE
[SF][ui5-avatar-group][Chrome/Edge]: not show show more button in Chrome when AvatarGroup in ResponsiveGridLayout

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents#5643]
### **Bug Description**
ShowMore button doesn't show when AvatarGroup in ResponsiveGridLayout
This issue only exists in Chrome/Edge browser.
Please fix this issue in 1.7.0.

### **Steps to Reproduce**
1. Use Chrome to open 'https://github.wdf.sap.corp/pages/xweb/team-goal/app/?templateId=1&mock#/detail?id=21'
2. You will see ShowMore button will not show. 

PS: If you use Safari/Firefox, the ShowMore button will show. 

### **Context**
- UI5 Web Components version: {ui5-avatar-group}
- OS/Platform: {macOS}
- Browser: {Chrome}
- Affected component: {...}

### **Log Output / Stack Trace / Screenshots**
<img width="661" alt="image" src="https://user-images.githubusercontent.com/13098801/183445850-12e15efc-344e-4690-85e1-29a46b8a6607.png">

Expected behavior:
<img width="694" alt="image" src="https://user-images.githubusercontent.com/13098801/183446119-1ecaa17d-f95a-45dd-badf-5fcd0b24b2a3.png">

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by kskondov** [comment]
Hello @SAP/ui5-webcomponents-topic-p the AvatarGroup issue is reproducible on chrome

**Comment by jatinthaker** [comment]
What is the plan on fixing this issue? Priority of medium is ok. In agreement with Stoehr.

**Comment by stbodurov** [comment]
> What is the plan on fixing this issue? Priority of medium is ok. In agreement with Stoehr.

Hi @GongRichard, @jatinthaker we are currently processing the issue and you can expect an update soon.
