### ISSUE TITLE
[SF][a11y][ui5-icon] Provide accessibleNameRef in ui5-icon

### ISSUE THREAD

**Issue by zhangliangyi** [SAP/ui5-webcomponents#5651]
### **Feature Request Description**
To avoid duplicated accessible name values, please consider to provide `accessibleNameRef` property in `ui5-icon` component just like other components.

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: SF
- Business impact: {...}

**Comment by nikolay-kolarov** [comment]
Hi @zhangliangyi,

Have you tried using the accessibleName property and if yes, what is the reason/scenario why you need to accessibleNameRef in addition?

Thanks,
Nikolay

**Comment by zhangliangyi** [comment]
@nikolay-kolarov 
Yes, I am using the `accessibleName` property in my project right now. But in my case, I have multiple icons with same `accessibleName` in some page and QA team asked me to use `aria-labelledby` attribute to prevent repetitive accessible names.

**Comment by dobrinyonkov** [comment]
Internal reference: BGSOFUIPIRIN-5874

**Comment by zhangliangyi** [comment]
OK, I see. Thanks @dobrinyonkov 
Close this issue.

**Comment by dobrinyonkov** [comment]
As of now `accessible-name` property cover all use cases and there is no need for `accessible-name-ref` to be added.
