### ISSUE TITLE
Need different UI of page navigation btns on tab bar overflow

### ISSUE THREAD

**Issue by ShivamGuptaSap** [SAP/ui5-webcomponents#5652]
### **Feature Request Description**
In tab container we need a different UI for overflowButton [ arrow btns ] instead of a dropdown.

### **Proposed Solution**
Kindly give us a property in Tab Container so that we can switch between default dropdown to arrow buttons.

**Note:** On tap of the arrow icons it should just scroll but not select the tab.
If you have any query please let us know.

### **Additional Context**
Before clicking:

<img width="806" alt="Screenshot 2022-08-10 at 3 27 24 PM" src="https://user-images.githubusercontent.com/107616257/183874409-5af072fe-5037-402f-9199-1872128213d5.png">

After clicking:

<img width="793" alt="Screenshot 2022-08-10 at 3 27 35 PM" src="https://user-images.githubusercontent.com/107616257/183874496-e3cb799b-49bd-441c-b6c4-7e972c3d72ac.png">

### **Priority**
- [ ] Low
- [ ] Medium
- [ ] High
- [X] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: {SAP}
- Business impact: {SAC LWV}

**Comment by kskondov** [comment]
Hello @ShivamGuptaSap the ui5-tabcontainer implements the SAP Fiori design (https://experience.sap.com/fiori-design/) and follow the SAP Fiori Design Guidelines (https://experience.sap.com/fiori-design-web/) for a consistent UX.
We shouldn't add design requirements, which are not a part of the SAP Fiori design, as this can unnecessary complicates the user experience.
Best Regards,
Konstantin
