### ISSUE TITLE
[SF][ui5-menu-item]: provide interface to customize aria-label of ui5-menu-item

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents#5656]
### **Feature Request Description**
We have ui5-menu-item to open a new page, we need set aria-label to tell screen reader user a new page will be opened.
Now ui5-menu-item only can set item text and can't set accessibleName.

### **Proposed Solution**
Provide accessibleName property to set aria-label.
Please provide it in 1.6.X or 1.7.0.

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: {SAP SuccessFactors}
- Business impact: {...}

**Comment by unazko** [comment]
Hello @GongRichard,

Could you provide a snipped like the following: https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html
so we could see how you configured your ui5-menu-items to navigate to a new page and therefore test the accessibility aspects in this case.

Best Regards,
Boyan Rakilovski

**Comment by GongRichard** [comment]
@unazko ，
I can't open codesandbox page. You can check our app page https://github.wdf.sap.corp/pages/xweb/goalmanagementx/app.html?mock .
Click "Create Goal" button and menu will show.

**Comment by ilhan007** [comment]
Lowering the priority and removing the "High" prio label based on the recent SF prioritisation list we recently got.

Hello @GongRichard  get in touch with your leads to adjust the priority.
