### ISSUE TITLE
ComboBox: Change Events by Arrow Up and Arrow Down Keys should be marked as "not final"

### ISSUE THREAD

**Issue by MFel0123** [SAP/ui5-webcomponents#5659]
### **Feature Request Description**
This is a question and might also be a feature request:
In our case, when we select something using a Combobox we trigger a backend request. This is of course a step that has quite an impact. We want to avoid unnecessary service calls to the backend. So, we have to do this only when the user has finalized his/her selection via the combobox.

Now imagine a user that opens the select drop down box of the combobox and (for whatever reason) just used the arrow-up and arrow-down key just to move up and down in the list. This user is not selecting anything, but I guess, for each key stroke a backend request is triggered (as far as I know, because a change event is fired).

We would expect some kind of signal that indicates "event is final" that is set when the user really is doing a mouse click into a line, or a focus our or an enter click. So that the select drop down box vanishes and the selection is really made. Then we can really handle the event and fire our service call to the backend.

If I am wrong and there is already such a flag to identify the "final change events" - please let me know.

### **Proposed Solution**
A clear and concise description of the solution you would like to have.

### **Additional Context**
Add other context or screenshots related to the feature request here.

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by hristop** [comment]
Hi colleagues, 

As we agreed, we should align the behavior of the change event and it should behave as in OpenUI5. 

Best Regards,
Hristo

**Comment by ndeshev** [comment]
Hello @MFel0123, the firing of the change event is aligned with the OpenUI5 ComboBox behavior. In order to differentiate if the suggestions are still open or not you can check the ComboBox `open` property in the `change `event handler. It is not (yet) part of our public API but you can use it to determine if the suggestions popover is open while the change/selection-change events are fired. For example, let say that the Combobox element is referenced by the ComboBoxDOMRef variable:

```
if (ComboBoxDOMRef.open = true) {
    // Not final logic
} else {
   // Final logic
}
```

**Comment by 2bno1** [comment]
@ndeshev I encountered the same problem and the workaround above did not work for me.
The `change` event is fired immediately when the selected item is changed. That said, the `open` state of the `ComboBox` is always `true` when the `change` event is fired. So it never has the chance to go into `'Final change ' logic` branch.
```javascript
if (ComboBoxDOMRef.open) {
    // Not 'final change' logic
} else {
   // 'Final change' logic
}
```

**Comment by ndeshev** [comment]
Hello @2bno1, you are correct, my suggestion is not good. I will reopen this issue for additional consideration and discussions.

Hello @SAP/ui5-webcomponents-topic-rl, when the suggestion items is navigated with arrow up/down keys both `selection-change` and `change `events are being fired. It is the same way in UI5 classic.

We should look in more depth into the request that the change event is somehow marked as 'final' - when enter is pressed and the user is no longer navigating through the suggestions or clicked on an item. 

We should check why we consider an item selection in result of navigation suitable for `change `event as for example in a native input the change event is fired only on ENTER press or focus out.

**Comment by ivoplashkov** [comment]
Hello,

We have carefully analyzed your report and there are a few things we want to cover.

First of all the ComboBox is a component which has a **list of options**. While navigating in the list the selection is being changed , therefore we are firing both **_selection-change_** and **_change_** events. This is also stated in our documentation which you can find here - https://sap.github.io/ui5-webcomponents/playground/?path=/docs/main-combobox--docs.

In order for us to be able to cover the use case you have, we would need to introduce a new event, which would be fired only on "final" interaction, when the user selects an item via Enter or Item click, however this would be first discussed with our designers, since they might not agree with this approach.

Another proposal from our side would be for you to use **Input** instead of **ComboBox**. The Input consists of **list of suggestions**, instead of **options** and in that case, upon navigation through the suggestions, **_change_** event is not fired.

Please let us know if Input component would cover your use case or you want this behavior specifially for ComboBox so we can proceed with the feature request process?

Best regards,
Ivaylo

**Comment by 2bno1** [comment]
Hi @ivoplashkov 
In my use case, the list of options need to be expanded automatically without typing anything in the input box, which I think is not supported by `Input` component.

**Comment by ivoplashkov** [comment]
Hi @2bno1,

Thank you for the fast response.

This interaction for the `Input` component could be easily achieved on the application side. You can add an event listener on focus and you can open the picker by yourself. Check `openPicker` method in the documentation - https://sap.github.io/ui5-webcomponents/playground/?path=/docs/main-input--docs.

Please let me know if this would be enough for you.
Thank you in advance!

Best regards,
Ivaylo

**Comment by 2bno1** [comment]
@ivoplashkov Thanks for your proposal. We don't need the option list to be opened when the input box gets focused. We want it behavior like ComboBox:
1) For keyboard user, when the input box get focused, I can open this option list with "Arrow + Down"
2) For mouse user, I can open the option list by clicking the arrow down icon at right of input box
So enhancing `Input` may not be an idea solution as it introduce more accessibility issues.

**Comment by ivoplashkov** [comment]
Hello @2bno1,

Apologies for the delayed response. I was on a short vacation.

The tasks you've mentioned can be accomplished using our provided public APIs:

1. Achieving the Arrow+Down functionality is possible by attaching a handler to the keydown event and listening for the specific key combination.
2. The icon could be added as a slot in the `ui5-input `and you can call the `openPicker` method on click of the icon.

For enhancing accessibility, consider using the InvisibleMessage service. It enables announcements at specific moments. Further details are available here: [Accessibility docs](https://sap.github.io/ui5-webcomponents/playground/?path=/docs/docs-advanced-accessibility--docs).

If you still prefer to have this functionality directly integrated into the ComboBox, we can proceed by submitting a feature request.

Best regards,
Ivaylo

**Comment by 2bno1** [comment]
@ivoplashkov Thanks for your suggestion. However, I prefer to have this functionality from the library out of box, instead of customization based on the component, especially the customization is not that easy.
Thanks

**Comment by hristop** [comment]
Hi @MFel0123 ,

We had discussed this with our design colleagues and they would like to take a look into this request. 
Could you please create an E1 feature request and provide the number here for reference? 

Best Regards,
Hristo

**Comment by 2bno1** [comment]
@hristop Since @MFel0123 has no response, can you tell me how to create E1 feature request? I'll do it then.

Regards

**Comment by hristop** [comment]
@2bno1 I have posted the info in the internal channel.

**Comment by MFel0123** [comment]
Hello, sorry at first that I did not react. But I thought, this is a misunderstanding, since this issue is the feature request (just look at the header). It contains all information I can give. If you internally need another form of request, then please feel free to use the information form this already existing request. I have nothing more to add.

Kind Redards

**Comment by 2bno1** [comment]
> @2bno1 I have posted the info in the internal channel.

@hristop Here's the number of the ticket: FIORITECHE1-7817

Regards

**Comment by hristop** [comment]
Hi @2bno1, @MFel0123 

We have updated the firing of the change event and now it will be fired only when the interaction is finished, but not when navigating in the items with the arrow keys. 
https://github.com/SAP/ui5-webcomponents/pull/8711

Best Regards,
Hristo
