### ISSUE TITLE
ui5-badge: text color is incorrect in Horizon

### ISSUE THREAD

**Issue by gmkv** [SAP/ui5-webcomponents#5667]
### **Bug Description**
The text is black, and doesn't match the visual design at https://wiki.one.int.sap/wiki/pages/viewpage.action?pageId=2835439490.
I remember the text color was different when we implemented the Horizon theme.

### **Isolated Example**
https://sap.github.io/ui5-webcomponents/main/playground/main/pages/Badge/?sap-ui-theme=sap_horizon

### **Context**
- UI5 Web Components version: latest

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by gmkv** [comment]
The visual spec was also updated and we should remove `text-transform: uppercase`.

**Comment by LidiyaGeorgieva** [comment]
> The visual spec was also updated and we should remove `text-transform: uppercase`.

This change is not synced by the designers and could be not final. Will not be implemented for the moment.
