### ISSUE TITLE
[SF] Table - When the column header labels are very long, show them as truncated text instead of increasing the table header height to accommodate them

### ISSUE THREAD

**Issue by Vir-Mittal** [SAP/ui5-webcomponents#5672]
### **Feature Request Description**

Original issue for reference - https://github.com/SAP/ui5-webcomponents/issues/5268

Sandbox - 
https://codesandbox.io/s/table-with-long-column-header-labels-vdrofi?file=/src/App.js

For the Table component, when very long labels are used for the column headers and the screen width is large, the column headers are displayed as expected, taking up as much space as possible - 
<img width="1179" alt="Table long column labels with large width" src="https://user-images.githubusercontent.com/36656306/169902569-3f2583b6-7a70-49b8-937d-6c22e13c162e.png">

However, when the screen width is small, the table header height increases in order to accommodate the long labels - 
<img width="466" alt="Table long column labels with small width" src="https://user-images.githubusercontent.com/36656306/169902682-679fec67-69c9-4bca-acc9-90a1d9b4f7af.png">

Instead of increasing the column header height, would it be possible to show the long labels as truncated text instead, something like this - 
<img width="543" alt="Table columns labels with truncated text" src="https://user-images.githubusercontent.com/36656306/169902766-6d2e784e-8c5f-4d24-9924-43eb08b345ce.png">

This would be similar to how other components such as the Card Header show truncated text when the text is too long

### **Proposed Solution**
Instead of increasing the column header height, would it be possible to show the long labels as truncated text instead, something like this - 
<img width="543" alt="Table columns labels with truncated text" src="https://user-images.githubusercontent.com/36656306/169902766-6d2e784e-8c5f-4d24-9924-43eb08b345ce.png">

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: {SuccessFactors}

**Comment by unazko** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

Take a look of this feature request.

Best Regards,
Boyan

**Comment by nikolay-kolarov** [comment]
Hi @niyap ,

As discussed, I think this can be done with the current possibilities of the API.
Could you please have a look?

Thanks,
Nikolay

**Comment by nikolay-kolarov** [comment]
Hello @Vir-Mittal,

We had a look again in your request.
As discussed in the previous issue, this might cause accessibility problems. It is against the Fiori Guidelines and you must not use tooltips for this. Here is the link: https://experience.sap.com/fiori-design-web/using-tooltips/

So, we cannot accept such a feature request.

Still, as discussed you can do this at your own risk with custom code in the application, but we do not recommend it due to the reasoning above.

Thanks,
Nikolay

**Comment by jatinthaker** [comment]
SF will look into a custom implementation based on the guidance above. We can then circle back with UI5 WC to determine wider application. Will discuss further with Stefan and Stoehr.
