### ISSUE TITLE
[SF][ui5-list] we need to clear the previous focused item after list item changed.

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents#5675]
### **Bug Description**

hi, team 

inner the list component there is a variable `_previouslyFocusedItem` for record the previous focused Item. when tab to the list and we can get the correct previous focused Item.

But there is some thing wrong, if the list item is changed, see below diagram.

<img width="870" alt="image" src="https://user-images.githubusercontent.com/78520316/184817863-ee963d33-5196-432d-81b9-7169cd4b6010.png">

I think for this case we need to clear the  `_previouslyFocusedItem`. Or It will not focus the first new one.

https://github.com/SAP/ui5-webcomponents/blob/b89f91c0a2f8afb336f2269cc441566b3ebfdd2c/packages/main/src/List.js#L648

I think we need to add `this._previouslyFocusedItem = null;` in prepareListItems.

### **Context**
- UI5 Web Components version: 1.6.0
- OS/Platform: /
- Browser: /
- Affected component: ui5-list

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by unazko** [comment]
Hello @sfsf-xweb-sh,

Could you please provide a isolated sample like this one: https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html
so we would be able to reproduce the described issue.

Best Regards,
Boyan

**Comment by sfsf-xweb-sh** [comment]
hi, team

thanks for quick reply.

we have already a demo link. but it's inner link,  can we talk offline?

**Comment by sfsf-xweb-sh** [comment]
hi, team 

I have testing in my local, maybe it's our issue. 

And thanks for reply and your time.

I'll close this issue.
