### ISSUE TITLE
[SF] Select  - Add a grouping option similar to the grouping option in the MultiComboBox

### ISSUE THREAD

**Issue by Vir-Mittal** [SAP/ui5-webcomponents#5679]
### **Feature Request Description**
The select component currently does not allow for items to be seen as part of a particular group. It would be useful to have this option similar to what the multicombobox grouping does - 

https://sap.github.io/ui5-webcomponents/playground/components/MultiComboBox/

<img width="272" alt="Screen Shot 2022-08-16 at 4 04 17 PM" src="https://user-images.githubusercontent.com/36656306/185000377-cd7d6cd8-013a-4a53-85a9-29377d8d3103.png">

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: {SuccessFactors}
- Business impact: {...}

**Comment by unazko** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

take a look of this feature request.

Best Regards,
Boyan

**Comment by dobrinyonkov** [comment]
Hello @Vir-Mittal,

This feature request was reviewed by our UX team, but it was not approved.

Our recommendations are to use [multi-combo box with groups.](https://sap.github.io/ui5-webcomponents/playground/components/ComboBox/) or just [ComboBox](https://sap.github.io/ui5-webcomponents/playground/components/ComboBox/). [Select control](https://experience.sap.com/internal/fiori-design-web/select/) is designed users to select exclusively from a short list of options, usually [between 2 and 12 items](https://experience.sap.com/internal/fiori-design-web/which-selection-control-to-use/#selecting-a-single-value-or-option1). We don’t use select component if the users need to pick one item from a very large set of options. In this case we recommend to use [combo box](https://experience.sap.com/internal/fiori-design-web/combo-box/) or [multi-combo box](https://experience.sap.com/internal/fiori-design-web/multi-combobox/), depending on the use case.

Kind Regards,
Dobrin
