### ISSUE TITLE
TimePicker: Opposite Scrolling while selecting time

### ISSUE THREAD

**Issue by knandan15** [SAP/ui5-webcomponents#5681]
**TimePicker: Opposite Scrolling while selecting time**
Upon scrolling the mouse "UP", the hour/minute/second selected is in the opposite direction and vice-versa.

**Example (with Screenshot)**
![image](https://user-images.githubusercontent.com/48648230/185074359-5124ea96-01c6-42cf-92ec-80c9a767710f.png)

Here, 06 is selected, so there on top are 04 and 05. Now scroll with mouse **up** to get 03.

Expected to be selected next 05 when scrolling up, but it shows 07 instead. (opposite to direction of scrolling)

Please confirm if this is the standard behaviour of this component.

Thankyou

**Comment by unazko** [comment]
Hello @knandan15,

This described behavior is according the UX design.
Imagine that the selection square is static and we are only sliding the time line underneath.

Best Regards,
Boyan
