### ISSUE TITLE
Calendar: A property to set the first day of the week shown in the calendar

### ISSUE THREAD

**Issue by pppwr7** [SAP/ui5-webcomponents#5684]
**Is your feature request related to a problem? Please describe.**
Currently, Sunday is always shown as the first day of the week. Customers have requested for a feature to show Monday as the first day of the week.

**Describe the solution you'd like**
Ability to have the first day of the weeek as a configurable property.

**Additional context**
The feature is already provided in Fiori/sapui5 and customers are currently using it. Hence, have requested for the same feature here. refer property 'firstDayOfWeek' in https://sapui5.hana.ondemand.com/#/api/sap.ui.unified.Calendar%23controlProperties

**Comment by tiagoapmartins** [comment]
Please also add the property `nonWorkingDays` and the aggregations `disabledDates` and `specialDates` as they are necessary to implement some HR functionalities and without it we're forced to use a 3rd party component such as flatpickr.

**Comment by DMihaylova** [comment]
Hi @tiagoapmartins,

We just introduced the brand new Calendar Legend component and there are also special calendar dates introduced in the Calendar.
https://sap.github.io/ui5-webcomponents/nightly/playground/?path=/docs/main-calendar-legend--calendar-legend-overview

**Comment by petyabegovska** [comment]
Hello @DMihaylova,

The same request for setting the first day of the week came from Signavio. Please consider implementing CalendarWeekNumbering enum similar to UI5: https://openui5nightly.hana.ondemand.com/api/module:sap/base/i18n/date/CalendarWeekNumbering#overview

Best regards,
Petya

**Comment by tsanislavgatev** [comment]
Hello colleagues,

The feature of implementing the calendarWeekNumbering in Date related controls is merged: https://github.com/SAP/ui5-webcomponents/pull/9694

It will be available with 2.2.0 relase.

Best Regards,
Tsanislav
