### ISSUE TITLE
[SF][Link][A11y]add accessibleRole attribute to Link component

### ISSUE THREAD

**Issue by ksblklu** [SAP/ui5-webcomponents#5686]
### **Feature Request Description**
Hi Team
We noticed that ui5 now have `accessibleRole` attribute, which can set role="Button" to Link component, can we align this attribute in ui5 wc Link component? Ref: https://sapui5.hana.ondemand.com/?sap-ui-theme=sap_horizon#/api/sap.m.Link%23controlProperties
<img width="1678" alt="image" src="https://user-images.githubusercontent.com/27538066/185361204-81987774-93d6-4823-9859-89902048cb85.png">

### **Proposed Solution**
Link have accessibleRole attribute

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-b  setting the priority to **High** based on the latest stakeholders input and prioritization. Consider this request on some of your next takt planting meetings. Thank you in advance.

Best,
ilhan

**Comment by don-obrien** [comment]
@petyabegovska  Is it possible to get this in by Sept 15th.  This is a higher urgency fix for SFSF.   Thanks!

**Comment by petyabegovska** [comment]
Hi @ksblklu, @don-obrien 

The current takt is already planed.
We will try to take this in the next planning round which starts at 19th of September.

Best regards,
Petya
