### ISSUE TITLE
[SF][ui5-icon]: icon always used accessibleName as tooltip

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents#5690]
### **Bug Description**
icon always used accessibleName as tooltip instead of using title property
Please fix it in 1.7.0

### **Expected Behavior**
Should use the value defined in title property as tooltip.

### **Steps to Reproduce**
1. Go to 'https://github.wdf.sap.corp/pages/xweb/team-goal/app/?templateId=1&mock#/detail?id=2'
2. check the navigation icon in assignees table
3. the tooltip shows the value from accessibleName

### **Context**
- UI5 Web Components version: {1.6.0}
- OS/Platform: {...}
- Browser: {...}
- Affected component: {ui5-icon}

### **Log Output / Stack Trace / Screenshots**
<img width="743" alt="image" src="https://user-images.githubusercontent.com/13098801/185572200-c03ce243-051e-41ff-b7cc-1e48f7d5b238.png">

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {SAP SuccessFactors}
- Business impact: {...}

**Comment by unazko** [comment]
Hello @SAP/ui5-webcomponents-topic-b,

The issue is with an icon only ui5-button component. In this case the ui5-button uses its internal icon tooltip.
When we try to override ui5-button's title property and provide a custom tooltip it still uses its icon tooltip.

For example:
<code>
<ui5-button icon="download" title="Custom tooltip"></ui5-button>
</code>

We'll still get "download" tooltip instead of "Custom tooltip".

Best Regards,
Boyan

**Comment by unazko** [comment]
Hello @GongRichard,

Currently we are working on the following component enhancement
https://github.com/SAP/ui5-webcomponents/issues/5733
We are expecting to complete it in two weeks from now and this would resolve the described issue.

Best Regards,
Boyan

**Comment by ilhan007** [comment]
Hello @GongRichard the  issue been fixed and available since 1.12 with https://github.com/SAP/ui5-webcomponents/pull/6719
