### ISSUE TITLE
ui5-tab-container: implement background-design attribute

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents#5696]
### **Feature Request Description**
In our project we have the requirement to make the background of the `ui5-tab-container` transparent. In SAPUI5 this can be achieved by using the `backgroundDesign` property: https://ui5.sap.com/#/api/sap.m.TabContainer%23methods/setBackgroundDesign

### **Proposed Solution**
I would like to have a new attribute `background-design` on the `ui5-tab-container`, similar to what is already implemented for the `ui5-page` component: https://github.com/SAP/ui5-webcomponents/blob/52db67087dfbcd61770755b6220a73fe1fe0195a/packages/fiori/src/Page.js#L22-L40

### **Proposed Alternatives**
We could use the `content` CSS Shadow part to change the background color ourselves.

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: UI5 Web Components for React / SAP Industry and Customer Advisory

**Comment by unazko** [comment]
Hello @SAP/ui5-webcomponents-topic-rd,

take a look of this feature request.

Best Regards,
Boyan Rakilovski

**Comment by olannyv** [comment]
This feature request is valid and accepted 
Implementation BLI created : https://jira.tools.sap/browse/BGSOFUIRODOPI-2861
