### ISSUE TITLE
[SF][ui5-date-picker]: background color in readonly mode is not consistent with ui5-input

### ISSUE THREAD

**Issue by zhangliangyi** [SAP/ui5-webcomponents#5698]
### **Bug Description**
The background color of date picker in readonly mode is not consistent with the color what `ui5-input` has.

### **Expected Behavior**
The look and feel should be consistent.

### **Context**
- UI5 Web Components version: 1.6.0
- OS/Platform: MacOS
- Browser: Edge
- Affected component: ui5-date-picker

### **Log Output / Stack Trace / Screenshots**

input
![image](https://user-images.githubusercontent.com/1867889/185886737-00dc6342-2741-43d2-b96c-34c99e127813.png)

date-picker
![image](https://user-images.githubusercontent.com/1867889/185886588-2cf21140-a4bd-44dd-a821-d971a29cbc1c.png)

### **Priority**
- [x] Low
- [ ] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SF
- Business impact: {...}

**Comment by PetyaMarkovaBogdanova** [comment]
Dear team,
ca you, please, verify if there should be a consistence in the background color of ui5-datepicker and ui5-input in SAP Horizon theme, in the case of readonly mode.
Thank you!

Best regards,
Petya Markova.
(UI5 WC Dispatcher)
