### ISSUE TITLE
[SF][ui5-date-picker]: style in date-picker with value state is not consistent with ui5-input

### ISSUE THREAD

**Issue by zhangliangyi** [SAP/ui5-webcomponents#5699]
### **Bug Description**
The background of date-picker which has an `Error` value state is not consistent with `ui5-input`

### **Expected Behavior**
 The look and feel should consistent 

### **Context**
- UI5 Web Components version: 1.6.0
- OS/Platform: MacOS
- Browser: Edge
- Affected component: ui5-date-picker

### **Log Output / Stack Trace / Screenshots**

ui5-input
![image](https://user-images.githubusercontent.com/1867889/185887794-99a55145-6a36-44d7-91a0-763f3c495b96.png)

ui5-date-picker
![image](https://user-images.githubusercontent.com/1867889/185888037-5f6a3f89-af4e-48e0-8174-3b884dffb55a.png)

### **Priority**
- [x] Low
- [ ] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SF
- Business impact: {...}

**Comment by PetyaMarkovaBogdanova** [comment]
Hi colleagues,
can you, please, check if there is a couple of pixel misalignment in the design of the Error value state in ui5-datepicker (red bottom border) ?
Thank you!

Best regards,
Petya Markova.
(UI5 WC Dispatcher)
