### ISSUE TITLE
ui5-tab-container: implement fixed attribute on the sub-elements ui5-tab

### ISSUE THREAD

**Issue by Abneco** [SAP/ui5-webcomponents#5702]
### **Feature Request Description**
If I don't implement the fixed attribute, on ui5-tab-container, then all ui5-tabs become drop-down panels, but there are cases, where I would like some tabs to stay simple tab (fixed) and act like a simple button.

### **Proposed Solution**
implement fixed attribute on the sub-elements ui5-tab

````html
<ui5-tabcontainer class="full-width" collapsed>
    <ui5-tab text="TAB BTN SIMPLE" fixed>NO</ui5-tab>
    <ui5-tab text="TAB DROP DOWN">YES</ui5-tab>
    <ui5-tab text="TAB DROP DOWN">YES</ui5-tab>
    <ui5-tab text="TAB DROP DOWN">YES</ui5-tab>
    <ui5-tab text="TAB BTN SIMPLE" fixed>NO</ui5-tab>
    <ui5-tab text="TAB DROP DOWN">YES</ui5-tab>
    ...
</ui5-tabcontainer>
````

![image](https://user-images.githubusercontent.com/29584029/186090227-999a9b81-8f27-4344-9022-6b72b1d1f7f1.png)
![image](https://user-images.githubusercontent.com/29584029/186090273-d884b5d9-e18b-46f0-ba87-caaecf2ce33a.png)

In the example above, if I select tab 1 or 5, the element being fixed, the panels will not unfold.
Tab 1 and 5 would just work as a button and i will redirect to the appropriate url.

Then after as usual
According to the selected tab
I retrieve the event
````html
<ui5-tabcontainer collapsed (tab-select)="selected($event)">
````

````typescript
    selected($event: any) {
        this.tabSelected = $event.detail.tabIndex;
        console.log((this.tabSelected));
    }
````

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by PetyaMarkovaBogdanova** [comment]
Hi team,
can you, please, consider adding "fixed" property for ui5-tabcontainer control`s ui5-tab, which is acting as just static link?

Best regards,
Petya Markova.
(UI5 Web Components Dispatcher)

**Comment by Abneco** [comment]
no, I think I'm expressing myself badly, I translate with google translate...

first point, i only use ui5 web component.

second point, clarification of behavior:
a simple click on an item in tabcontainer, must be able to refer to a link rather than opening an empty tab.
on the other hand if a sub-elements is present display it.

This already exists, but it's not enough
![image](https://user-images.githubusercontent.com/29584029/188458202-7e112348-4fe6-4506-92c2-f5c2454cdce8.png)

some elements are therefore links and the latter are drop-downs

Proposed Solution
implement fixed attribute on the sub-elements ui5-tab
````html
<ui5-tabcontainer class="full-width" collapsed>
    <ui5-tab text="TAB HOME" fixed>NO</ui5-tab> <!-- does not unwind but is a simple link -->
    <ui5-tab text="TAB DROP DOWN (PRODUCT CAT 1)">YES</ui5-tab>
    <ui5-tab text="TAB DROP DOWN (PRODUCT CAT 2)">YES</ui5-tab>
    <ui5-tab text="TAB DROP DOWN (PRODUCT CAT 3)">YES</ui5-tab>
    <ui5-tab text="TAB ABOUT" fixed>NO</ui5-tab> <!-- does not unwind but is a simple link -->
    <ui5-tab text="TAB DROP DOWN (PRODUCT CAT 4)">YES</ui5-tab>
    ...
</ui5-tabcontainer>
````

If it's still not clear, don't hesitate to ask me.

**Comment by LidiyaGeorgieva** [comment]
Hello @Abneco ,

You use the tab container as a "navigation" section, which contains links, which is not what the component is designed for. 
We do not recommend such usage.
You can see tab-container's description in the [documentation](https://sap.github.io/ui5-webcomponents/playground/components/TabContainer/):
"The ui5-tabcontainer represents a collection of tabs with associated content. Navigation through the tabs changes the content display of the currently active content area. A tab can be labeled with text only, or icons with text."

But if you decide to use it like this there is a way you can achieve this "button like" tab with no content. There is no need of adding a new attribute to the component. You can use event.preventDefault:
https://codesandbox.io/s/tab-container-with-custom-logic-on-tab-select-2sps4b?file=/src/index.js
Test in a seperate window (to avoid CSP issues inside the codesandbox editor): https://2sps4b.csb.app/
Note: using event.preventDefault on the event tab-select is available with the release [v1.7.0](https://github.com/SAP/ui5-webcomponents/releases/tag/v1.7.0)

Regards,
Lidiya

**Comment by Abneco** [comment]
Hello @LidiyaGeorgieva,

It could work with event.preventDefault

but for now it only works for external links that don't need to be selected.

if I use an internal link on my site

I need to add select attribute
setAttribute('selected', true);

and ask the other element to clear the attribute in question
removeAttribute("selected");

it works but a problem persists,
I cannot control the selection of the drop-down menu using a method because it does not exist.

which means that if I am in a drop-down tab, and its state is expanded, then if I click on my link alone, an empty panel will be present.

demonstration in gif
![2022-09-07_09-04-22](https://user-images.githubusercontent.com/29584029/188811633-37197784-baca-4019-9abe-1785c3bd9023.gif)

**Comment by gmkv** [comment]
Hi @Abneco 

I am not sure what you also mean by "a drop-down tab" - I don't see any tabs containing other tabs (nested tabs) in the provided gif or sample code from above.
What do you intend to have as a "link" inside the Tab Container?
Could you provide a reproducible code sample for the situation you are describing? You could fork [this codesandbox](https://codesandbox.io/s/tab-container-with-custom-logic-on-tab-select-2sps4b?file=/src/index.js).

The intended design for the TabContainer is described in this [Fiori Design Guidelines page](https://experience.sap.com/fiori-design-web/icontabbar/). However, this UI element is not designed to have navigation which leads to other pages of an app - even internal links. It is designed so that each tab has content which is to be strictly displayed underneath the TabContainer. From what I have understood in this issue, you're trying to achieve some sort of a website navigation. This is probably why you found it difficult to "bend" the TabContainer to your use case, which is not exactly what it was designed for.
