### ISSUE TITLE
create Ui5-Dialog component dynamically via javascript

### ISSUE THREAD

**Issue by geokas7** [SAP/ui5-webcomponents#5707]
Hello,

I tried to create html code dynamically via javascript in order to create a dialog component (with the code below). I created the same code in html file (with pure html) and it works fine. However, it is important for my codebase to create it via the way bellow (via javascript). 

```
import "@ui5/webcomponents/dist/Dialog";

var storeButtonElement = document.querySelector('#storeButton'); //in html file

var dialogStoreConfirmElement=document.createElement('ui5-dialog');
dialogStoreConfirmElement.style="font-size: 1.5vh; background: #1E2B32;";
dialogStoreConfirmElement.id='popupConfirmDyn';
dialogStoreConfirmElement.headerText='popupConfirmDyn';

var dialogStoreConfirmTitleElement=document.createElement('div');
dialogStoreConfirmTitleElement.style="font-size: 2vh;  color:#FFFF";
dialogStoreConfirmTitleElement.innerHTML='Store the current workspace?';

dialogStoreConfirmElement.appendChild(dialogStoreConfirmTitleElement)

storeButtonElement.accessibilityAttributes = {
      hasPopup: "dialog",
      controls: dialogStoreConfirmElement.id
    }

storeButtonElement.addEventListener('click',function() {
        dialogStoreConfirmElement.show();
    });
```

When i click on button the console's output is:

```
terminal_bootstrap.js:296 Uncaught TypeError: dialogStoreConfirmElement.show is not a function
    at HTMLElement.<anonymous>
```

I would like to inform me if is there any way to solve this issue. I did not find any way in the documentation.

Best,
George

**Comment by ilhan007** [comment]
Hello @geokas7 which version of UI5 Web Components are you using and do you have a reproducible sample?

**Comment by hinzzx** [comment]
Hey @geokas7 ,

Would you try if adding `document.body.appendChild(dialogStoreConfirmElement);` right after 
`var dialogStoreConfirmElement = document.createElement('ui5-dialog');` solves the problem for you, since I tried to reproduce your code and got the same error, because the dialog is created, but its not added to the document body.

I hope this helps !

Kind Regards,
Stoyan
