### ISSUE TITLE
[SF][A11Y][Button]: Svg graphics for icon buttons not marked as presentational graphics

### ISSUE THREAD

**Issue by tandan0813** [SAP/ui5-webcomponents#5709]
Hi, collegue,
    When we run AXE on an `icon button`, then it will show an issue saying that <svg> elements with an img role must have an alternative text(attached screenshot for more details).
![image](https://user-images.githubusercontent.com/10113427/186350145-621b5306-94a9-43da-b632-222dbe7d5e02.png)

**Expected behavior**
Since these svg graphics within the Bookmark icon buttons are decorative, it can be marked as decorative with null/empty "alt".
Ref: https://www.w3.org/WAI/tutorials/images/decorative/
They are considered decorative because they are present within button tag and button already has meaningful accessible name.

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.6.0
`@ui5/webcomponents-react` version: 0.27.0
Operating System:
Browser: Chrome

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by ndeshev** [comment]
Hello @tandan0813 the alt attribute is specific to the image tag and not the svg. However, the AXE reported issue is valid and we are aware of it and currently working towards its solution. It is a duplicated issue so I'm closing this one.

Related to: #5687; #5733 #5596 #5505 #5733

**Comment by unazko** [comment]
Hello @tandan0813,

Please do refer to the following incident: https://github.com/SAP/ui5-webcomponents/issues/5596
for the same issue. There is an answer with recommendations for this use case..

Best Regards,
Boyan Rakilovski
