### ISSUE TITLE
sort and multiselect on ui5-table

### ISSUE THREAD

**Issue by mehdijouan** [SAP/ui5-webcomponents#571]
Hello,
I would like to use the `ui5-table` component but I'm facing two missing issues:

- Sort lines by columns
- Select one or more lines  

Do you have any advice or way for me to customize the `ui5-table` component in order to achieve that ?

**Comment by vladitasev** [comment]
Hello,

UI5 Web Components are supposed to be more general-purpose than OpenUI5 controls. The requested features are therefore deemed too custom to be part of the Table. 

1. MultiSelection - you can achieve this by creating a first column with checkboxes and then checking which ones the user has clicked.
2. Sorting - this feature is relevant only for data/analytical tables than are guaranteed to deal with numbers, and generally the data type of columns is known upfront. This is also something you can implement on your own by adding a sort icon in the column header, and manage its interaction manually (by rearranging the rows).

Regards,
Vladislav
