### ISSUE TITLE
Typo in IllustrationMessageType.NoEntries

### ISSUE THREAD

**Issue by samanr** [SAP/ui5-webcomponents#5713]
### **Bug Description**
Typo in IllustrationMessageType.NoEntries.
Missing Apostrophe in contraction for 'you'll'

### **Expected Behavior**
Message should be as follows: "When there are, you'll see them here."

### **Steps to Reproduce**
1. Use the IllustratedMessage component. 
2. In the name prop use the  IllustrationMessageType.NoEntries.
3. Observe the subtitle grey text is When there are, youll see them here.

### **Context**
- UI5 Web Components version:

- "@ui5/webcomponents": "^1.4.0",
-  "@ui5/webcomponents-fiori": "^1.4.0",
- "@ui5/webcomponents-icons": "^1.4.0",
- "@ui5/webcomponents-react": "^0.25.0",

- OS/Platform: MacOS
- Browser: Tested in Chrome
- Affected component: IllustratedMessage

### **Log Output / Stack Trace / Screenshots**
![Screen Shot 2022-08-24 at 10 57 42 AM](https://user-images.githubusercontent.com/22089053/186451956-db07ccb3-2cb0-49da-98f2-923be9dea414.png)

### **Priority**
- [x] Low
- [ ] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by samanr** [comment]
Moved this here: https://github.com/SAP/ui5-webcomponents-react/issues/3411

**Comment by Lukas742** [comment]
Hi @samanr 

As I explained in Slack, the component is developed by the UI5 Web Components team, so this is the right place for this issue. I still will keep it closed as I noticed that this is a duplicate to https://github.com/SAP/ui5-webcomponents/issues/5626.

If you have any questions please raise them in the linked issue. Thanks
