### ISSUE TITLE
[SF][Table] There is no right padding of content in pop-in cells when text direction is RTL

### ISSUE THREAD

**Issue by i323808** [SAP/ui5-webcomponents#5715]
### **Bug Description**
There is no right padding of content in pop-in cells when text direction is RTL.

### **Expected Behavior**
There is supposed to be right padding when text direction is RTL.

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/Table/?sap-ui-theme=sap_fiori_3&isrtl=true
2. Shrink the browser to make columns pop-in

### **Isolated Example**
https://sap.github.io/ui5-webcomponents/playground/components/Table/?sap-ui-theme=sap_fiori_3&isrtl=true

### **Context**
- UI5 Web Components version: 1.6.0
- OS/Platform: macOS Monterey
- Browser: Chrome Version 104.0.5112.79 (Official Build) (x86_64)
- Affected component: Table

### **Log Output / Stack Trace / Screenshots**
<img width="472" alt="no_right_padding_rtl" src="https://user-images.githubusercontent.com/30744017/186442719-7c8511a2-dcd5-4656-b436-6ad0146f3ebe.png">

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by PetyaMarkovaBogdanova** [comment]
Hi colleagues from @SAP/ui5-webcomponents-topic-rl,
can you, please, take a look where the missing right padding of **ui5-table** in RTL = 'true" mode is coming from?

Thank you!
Best regards,
Petya Markova.
(UI5 WC Dispatcher)
