### ISSUE TITLE
stableDomRef not working

### ISSUE THREAD

**Issue by kundarsowjanya** [SAP/ui5-webcomponents#5719]
Hi I'm using ShellBar component in UI5 but now after upgrade to latest version   stableDomRef is not working in shellBarItem component is there any alternative way?
```

<ShellBarItem
        icon="sys-help"
        data-testid="webassistant-button"
        stableDomRef="webassistant-button"
      />
```

Thanks

**Comment by ilhan007** [comment]
Hello @kundarsowjanya 

It was removed long ago, with this change https://github.com/SAP/ui5-webcomponents/pull/4210/

After the change, now you can simply call "getDomRef" on the web component instance and it will return the proper DOM reference.

**Comment by kundarsowjanya** [comment]
Could you please provide me the example of how to use getDomRef, I'm still getting error.
