### ISSUE TITLE
[SF][BUG][UI5 Table][ Within 2 weeks ] The UI5 table should follow Responsive table Fiori Design Guidance

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents#5731]
Dear UI5 team,

This is SuccessFactors Web Experience Shanghai team. 

Responsive Table Fiori Guidance
https://experience.sap.com/fiori-design-web/responsive-table/#horizontal-content-alignment

### **The UI5 table should follow Responsive table Fiori Design Guidance**
1. Dates and times should be right aligned in table, but now it is left aligned2. 
2. Other table content should follow Fiori Guidance

<img width="868" alt="Screen Shot 2022-08-26 at 12 13 26 PM" src="https://user-images.githubusercontent.com/78520316/186820992-b6e39aa8-60e4-420c-9c2a-0e6feeef96d5.png">

### **Expected Behavior**
1. Dates and times should be right aligned in table2. 
2. Other table content should follow Fiori Guidance
3. Both check and fix the Vertical Content Alignment and Horizontal Content Alignment

### **Reproduce Page**
https://sap.github.io/ui5-webcomponents/playground/components/Table/

**Comment by ndeshev** [comment]
Hello SuccessFactors Web Experience Shanghai team
The content of the cell is a slot for a custom content provided by the app developer. 
The table has no way to know what that would be.

We expose shadow parts for the table cell and table row that can be used to align and overall style the content as wanted by the developer.

Here - https://sap.github.io/ui5-webcomponents/playground/components/Table/ you can also read more information about the `ui5-table` and how it works.

Kind regards,
Nikolay
