### ISSUE TITLE
[ui5-button]: apply default tooltip over the button element instead of the inner icon element

### ISSUE THREAD

**Issue by unazko** [SAP/ui5-webcomponents#5733]
### **Feature Request Description**
The inner <code>ui5-button</code>'s icon should have a "presentation" role in all cases by specification.
Currently in the icon-only button scenario the <ui5-icon</code> has role "img".
In order to change the icon's role to "presentation we need to display the default tooltip over the <code>ui5-button</code>
element instead over the inner <code>ui5-icon</code> element.

### **Proposed Solution**
Get the <code>ui5-icon</code>'s accessible name in the button component logic and use it as a default <code>tooltip</code> attribute value.

![2022-08-26_13-45-38](https://user-images.githubusercontent.com/15860295/186887572-dcba7c5f-0772-4a03-bfa0-c13f5e0589bb.png)

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by unazko** [comment]
Hello @SAP/ui5-webcomponents-topic-b,

take a look on this component accessibility enhancement.

Best Regards,
Boyan

**Comment by ilhan007** [comment]
Hello @petyabegovska and @DMihaylova as we have one more week left for this milestone, please check if this is still feasible for 1.11.0, and move to 1.12.0 if not. Thank you!
