### ISSUE TITLE
Button: Color contrast issues in Horizon theme

### ISSUE THREAD

**Issue by sleric1024** [SAP/ui5-webcomponents#5735]
**Describe the bug**
Some component such as Button in Horizon theme do not meet minimum of 4.5:1 CC in default and focused states.
### Button Component
**Outline in focused case**
![image](https://user-images.githubusercontent.com/5724592/186895794-8a3f16c8-dca5-4dd0-b9d2-27b882c7e83b.png)

**Isolated Example**
Input
https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-input--with-suggestion-item

**Expected behavior**
Icons and visual focus outline are expected to meet minimum of 4.5:1 CC in default and focused states.
It may also occurs in other component as well. 

**Additional context**
Dear colleague, I am from SAP Successfactors, currently we are fixing a11y issue for b2211 release, and the issues we reported by central a11y team.

**Comment by PetyaMarkovaBogdanova** [comment]
Hi @sleric1024 ,
thank you for your contribution! Since Button and Input controls are maintained by different teams, can I, please, ask you to leave this issue context to remain for the Button only, and open a new one for the Input as well?
Thank you!

Best regards,
Petya Markova.
(UI5 WC Dispatcher)

**Comment by sleric1024** [comment]
@PetyaMarkovaBogdanova ， OK， thanks

**Comment by ndeshev** [comment]
Hello,

By specifications we support 4.5:1 contrast ratio for icons and text and 3:1 for other graphical objects and visual details, such as the focus outline. However, we could not apply this specifications for custom icons, specified by application.
