### ISSUE TITLE
Content in Side Navigation

### ISSUE THREAD

**Issue by joseserrano15** [SAP/ui5-webcomponents#5736]
Hello, I'm new using this library, currently I'm trying to use it with Angular and I have a question about ui5-side-navigation. How can I put the content? I read the documentation but I didn't find something about that.

Thanks.

![image](https://user-images.githubusercontent.com/68348356/186949287-bdd04c56-eea1-4934-ab74-56872b2e3dec.png)

![image](https://user-images.githubusercontent.com/68348356/186949506-cd6480ac-3ffc-4bca-8b23-5daf7de323c8.png)

**Comment by nnaydenow** [comment]
Hi @joseserrano15 ,

ui5-side-navigation doesn't have slot for page content. You should place it for example in flex container:

```
<ui5-shellbar></ui5-shellbar>
<div class="flex">
   <ui5-side-navigation></ui5-side-navigation>
   <div class="content"></div>
</div>
```
