### ISSUE TITLE
DateRangePicker: Entering a single date manually creates javascript errors and break component

### ISSUE THREAD

**Issue by joe-skrzypczak-fioneer** [SAP/ui5-webcomponents#5738]
**Describe the bug**
Entering a single date manually in a date range picker causes the component to break.

**Isolated Example**
Can be reproduced on the current sandbox (https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-daterangepicker--default-story)

**To Reproduce**
1. Navigate to https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-daterangepicker--default-story
2. Open the browser's debug tools and view console
3. Click on the date range picker component
4. Using the keyboard enter the valid single date JAN 20, 2022 and hit enter
5. You'll see the following stack trace in console: 
8795.fc2c3cff.iframe.bundle.js:2 Uncaught TypeError: Cannot read properties of null (reading 'getTime')
    at DateRangePicker._extractFirstTimestamp (8795.fc2c3cff.iframe.bundle.js:2:5608570)
    at DateRangePicker.normalizeValue (8795.fc2c3cff.iframe.bundle.js:2:5606355)
    at DateRangePicker._updateValueAndFireEvents (8795.fc2c3cff.iframe.bundle.js:2:5599141)
    at DateRangePicker._onInputChange (8795.fc2c3cff.iframe.bundle.js:2:5599833)
    at I.handleEvent (8795.fc2c3cff.iframe.bundle.js:2:9944337)
    at Input._fireEvent (8795.fc2c3cff.iframe.bundle.js:2:1042318)
    at Input.fireEvent (8795.fc2c3cff.iframe.bundle.js:2:1041934)
    at Input._handleChange (8795.fc2c3cff.iframe.bundle.js:2:5703899)
    at I.handleEvent (8795.fc2c3cff.iframe.bundle.js:2:9944337)

**Expected behavior**
Either a validation error is displayed or the entry is considered a valid single day range.

**Screenshots**
![image](https://user-images.githubusercontent.com/95598428/186984608-7cd76f8a-5b17-42d4-b93b-4775e67336dd.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: current version on playground
`@ui5/webcomponents-react` version: latest version on playground
Operating System: Windows
Browser: Chrome

**Additional context**

**Comment by ndeshev** [comment]
Hello @SAP/ui5-webcomponents-topic-b the issue is reproducible in v1.6 on https://sap.github.io/ui5-webcomponents/playground/components/DateRangePicker/ 

If you enter for example Mar 31, 2021 in the input and press 'ENTER' there is a JS error thrown.

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-b it's seems this is a valid case, that is handled in OpenUI5 as well,
in this case the range will be from that single date to null

Tested in the [Demo Kit](https://openui5nightly.hana.ondemand.com/entity/sap.m.DateRangeSelection/sample/sap.m.sample.DateRangeSelection) of OpenUI5
From: Wed Feb 17 2016 00:00:00 GMT+0200 (Eastern European Standard Time)
To: null
