### ISSUE TITLE
Dialog: wrong footer border color in Horizon HC Themes

### ISSUE THREAD

**Issue by EtienneWille** [SAP/ui5-webcomponents#5740]
### **Bug Description**
Wrong color output of var(--sapPageFooter_BorderColor) in Horizon High Contrast Themes. Results in e.g black footer border on a black background(invisible) in a Dialog.

### **Expected Behavior**
The variable "--sapPageFooter_BorderColor" should have the right color output for Horizon HC Themes.

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/Dialog/?sap-ui-theme=sap_horizon_hcb&isrtl=false
2. Click on Show Dialog Button
3. See missing border at the bottom of the dialog

### **Context**
- UI5 Web Components version: {latest}
- Affected component: {Dialog}

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

**Comment by ndeshev** [comment]
"Hello @SAP/ui5-webcomponents-topic-rd, could you please take a look at the issue, in SAP Horizon HCB the border is with black color and it is not visible on the black background.

**Comment by dimovpetar** [comment]
Hello @EtienneWille ,

This issue is fixed with https://github.com/SAP/ui5-webcomponents/pull/5762

Best regards,
Petar
