### ISSUE TITLE
Input: Color contrast issues in Horizon theme

### ISSUE THREAD

**Issue by sleric1024** [SAP/ui5-webcomponents#5741]
**Describe the bug**
Some component such as  Input in Horizon theme do not meet minimum of 4.5:1 CC in default and focused states.

### Input with Suggestion component
Icons in the drop down fail to meet 4.5:1 CC in both default and focused states
Outline fails to meet 4.5:1 against the light blue color when suggestion options are in focused state

**Isolated Example**

Input
https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-input--with-suggestion-item

**Expected behavior**
Icons and visual focus outline are expected to meet minimum of 4.5:1 CC in default and focused states.
It may also occurs in other component as well. 

**Additional context**
Dear colleague, I am from SAP Successfactors, currently we are fixing a11y issue for b2211 release, and the issues we reported by central a11y team.

**Comment by ndeshev** [comment]
Hi @sleric1024 

By specifications we support 4.5:1 contrast ratio for icons and text and 3:1 for other graphical objects and visual details, which I believe includes the focus outline. However, we could not apply this specifications for custom icons, specified by application.

In the example that you have included as link I do not find input with suggestions and icons in that suggestion items. In case of an issue please use the core UI5 WebComponents samples -  https://sap.github.io/ui5-webcomponents/playground/components
