### ISSUE TITLE
NotificationListGroupItem: Notification Popover is not aligned with Shellbar icon

### ISSUE THREAD

**Issue by viniciussdahmer** [SAP/ui5-webcomponents#5767]
**Describe the bug**
When clicking the bell icon on the Shellbar component, the NotificationListGroupItem component that opens as a popover is not properly aligned with the notification icon.

**To Reproduce**
1. Add the Shellbar component in a screen
2. Bind the NotificationListGroupItem to the shellbar notification
3. Click on the notification icon on the Shellbar
4. See the misaligned components

**Expected behavior**
The notification popover should be aligned to the notification icon on the shellbar.

**Screenshots**
![image](https://user-images.githubusercontent.com/30452636/187931655-e270a6fd-fb6f-4085-9d8f-66080263a35e.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.5.0
`@ui5/webcomponents-react` version: 0.26.0
Operating System: MacOS Monterey 12.5
Browser: Chrome

**Additional context**
Fiori Guideline: https://experience.sap.com/fiori-design-web/notification-center/#top

This is a request for our internal SAP project.

**Comment by ilhan007** [comment]
Hello @viniciussdahmer 

could you send us a reproducible example and also try out v1.6.0 as we only support the latest stable version.

Thank you!
ilhan

**Comment by ndeshev** [comment]
Hello @viniciussdahmer I've checked our samples and also can't reproduce the reported problem. Could you please provide more information as @ilhan007 asked above.

**Comment by viniciussdahmer** [comment]
> Hello @viniciussdahmer I've checked our samples and also can't reproduce the reported problem. Could you please provide more information as @ilhan007 asked above.

Hi guys,
Sure thing, here is a sandbox with an example using the latest version supported: https://codesandbox.io/s/funny-dawn-p5qtwn?file=/src/App.js

Apparently, the issue only happens when I define a width for the popover that opens when clicking on the notification icon. We received a recommendation from our UX team to use 505px for the popover dialog, so I am not sure if this is something that you guys expected to happen 🤔 

Let me know if there is anything else that I can help you with and thanks for the quick response!

**Comment by ndeshev** [comment]
Hello @viniciussdahmer if you add  `horizontalAlign="Right"` to the Popover everything looks fine.

Kind Regards,
Nikolay
