### ISSUE TITLE
Sugguest to add suffix/prefix to CSS parameters to avoid conflict on multiple runtimes with different versions

### ISSUE THREAD

**Issue by JackieWei** [SAP/ui5-webcomponents#5768]
### **Feature Request Description**
Hi All,
We are using micro frontend solution, which means we will have many different versions of UI5 web components instances in ONE page, sharing one set global variables. We use Proxy api to isolate the different instances, but there are one big issue on CSS parameters, especially for some new versions like 1.6.x.Because css parameters won't work under shadow root, so unlike other css and style tags, we need to append them directly to head and ALL mfe instances sharing the same one, so they will be conflict with each other. And actually we are facing such kind of problems. For example, 
![image](https://user-images.githubusercontent.com/437693/187870704-5b1fa600-d27b-45dc-8c4b-a2e805f681ed.png)

In other version of ui5 wc instance, the parameters are not exist.
![image](https://user-images.githubusercontent.com/437693/187870947-cddbb1ae-fde8-4cd6-b013-f82bf4a3c30f.png)
Those parameters only works in new version.

In previous version, some times we can reorder the CSS style tag under head to make newer version run, but in recently version of instances, we can't do that because in UI5 web component looks that it will directly update the styleSheet object, so then the incompatible versions are not possible to work together, and that is not the purpose we start using micro frontend

### **Proposed Solution**
Suggest to add suffix or prefix to CSS parameters, for example, --_ui5_list_item_icon_size changed to --_ui5_list_item_icon_size_1_6_1, so then the mfes will totally be isolated from each others
This FR is similar with another one I raised
https://github.com/SAP/ui5-webcomponents/issues/4561
Just make change to meet micro frontend architecture 

### **Proposed Alternatives**
No

### **Additional Context**
https://github.com/SAP/ui5-webcomponents/issues/4561

### **Priority**
- [ ] Low
- [] Medium
- [x ] High
- [ ] Very High

![image](https://user-images.githubusercontent.com/437693/187872705-7b2d04f1-6f09-4b34-973d-5119d680203e.png)
Those warnings are meaningless in micro frontend architecture. And currently 1.6 not compatible with 1.3, the menu will be broken
![image](https://user-images.githubusercontent.com/437693/187872985-b7dfc6a5-21ce-4630-9a30-760128818142.png)

### **Stakeholder Info** (if applicable)

- Organization: ---
- Business impact: ---

**Comment by ilhan007** [comment]
Hello @JackieWei we already started working on the topic as this request has been raised by several places. 

We might not fix it the way you suggest, but this is not so important as you will get a solution one way or another.
Once we have an update, we will post it here as well.

To set some expectations , I would say we will have a solution in Q3.

Thanks for your interest!
ilhan

**Comment by ilhan007** [comment]
Related to: https://github.com/SAP/ui5-webcomponents/issues/3781 and https://github.com/SAP/ui5-webcomponents/issues/4561

**Comment by ilhan007** [comment]
The issue with the CSS Variables clashing when multiple runtimes of UI5 Web Components are used will be tracked with this issue: https://github.com/SAP/ui5-webcomponents/issues/3781 and there is already a [change](PR in review: https://github.com/SAP/ui5-webcomponents/pull/5586) in review to address the problem.
