### ISSUE TITLE
Arrow icon not show in expanded navigation item

### ISSUE THREAD

**Issue by joseserrano15** [SAP/ui5-webcomponents#5770]
Hello, I have a problem with ui5-side-navigation-item when I put the expanded property, the arrow icon doesn't show when page loaded, its show only when I click it in the item.

Page loaded.
![image](https://user-images.githubusercontent.com/68348356/187937729-55721823-d86f-45d5-a8d2-6f3484778621.png)

After click.
![image](https://user-images.githubusercontent.com/68348356/187937817-f25196d0-e08a-428a-9df4-55e02ad159d6.png)

```
<ui5-side-navigation>
<ui5-side-navigation-item
  text="Agrupación de lotes"
  icon="business-suite/forklift" expanded>
  <ui5-side-navigation-sub-item text="From My Team"></ui5-side-navigation-sub-item>
  <ui5-side-navigation-sub-item text="From Other Teams"></ui5-side-navigation-sub-item>
</ui5-side-navigation-item>

<ui5-side-navigation-item text="Traspaso makila" icon="business-suite/outbound-delivery"></ui5-side-navigation-item>
</ui5-side-navigation>
```

Thanks for your help

**Comment by joseserrano15** [comment]
I only have a repo (https://github.com/joseserrano15/ui5) with the problem because I tried to reproduce it in CodeSandbox but it works fine there.

Is the first time that I used this components and how Angular is the framework that I know, I chose this option.

**Comment by ilhan007** [comment]
Hello @joseserrano15 I see, this is a duplicate issue of https://github.com/SAP/ui5-webcomponents/issues/5303
You can use it to track the progress as we are closing this one as duplciate.
