### ISSUE TITLE
illustrated-message: title heading level cannot be changed

### ISSUE THREAD

**Issue by ee92** [SAP/ui5-webcomponents#5772]
### **Bug Description**
The title of the illustrated-message component is always rendered by a h2 element, which is not always the right heading level for the context.

### **Expected Behavior**
It should be possible to control the heading level of the title.
An option would be to expose a slot for the title (already done for subtitle)

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/IllustratedMessage/ 
2. Go down to "Illustrated message in dialog" and click "Open Dialog"
3. The dialog title and the illustrated message title are both H2

### **Context**
- UI5 Web Components version: 1.6.0
- Affected component: illustrated-message

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### **Stakeholder Info** (if applicable)

- Organization: SuccessFactors
- Business impact: Accessibility

**Comment by ndeshev** [comment]
Hello @SAP/ui5-webcomponents-topic-p could you please evaluate this feature request. The author suggest an improvement for customizable header level title in `ui5-illustrated-message`

**Comment by dobrinyonkov** [comment]
Hi @ee92,

with #5611 a new slot `title` was introduced which can be used to set custom title level.

```html
<ui5-illustrated-message name="UnableToUpload">
    <ui5-title slot="title" level="H1">This is a slotted title</ui5-title>
</ui5-illustrated-message> 
```

Kind Regads,
Dobrin
