### ISSUE TITLE
UI5 Bar flickers when parent is about 250px -300px in width

### ISSUE THREAD

**Issue by veith** [SAP/ui5-webcomponents#5773]
### **Bug Description**
The bar switches between `_shrinked` and not `_shrinked` when the parent element reaches a specific width.

### **Expected Behavior**
No infinite loop for the resize.

### **Steps to Reproduce**
Resize the screen.

### **Isolated Example**
[CodeSandbox](https://codesandbox.io/s/ui5-dialog-error-forked-54sqhm?file=/index.html).
[Standalone](https://54sqhm.csb.app/)

### **Context**
- UI5 Web Components version: 1.6.0
- OS/Platform: MacOs
- Browser: Chrome, FireFox
- Affected component: Bar

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

**Comment by veith** [comment]
And on some sizes, this will also block the select to display the responsive popover (the options) from showing.

**Comment by Todor-ads** [comment]
Hi @veith,
We've submitted fix that solving the issue.
A problem is solved with this change: https://github.com/SAP/ui5-webcomponents/pull/5678
Best Regards,
Todor
