### ISSUE TITLE
ui5-avatar- should support up to three latin letters as initials

### ISSUE THREAD

**Issue by pankajpandey01** [SAP/ui5-webcomponents#5779]
### **Feature Request Description**
As per below Fiori3 design guidelines on Avatar. It should support up to three latin letters as initials.
https://experience.sap.com/fiori-design-web/avatar/#initials 

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### **Stakeholder Info** (if applicable)

- Organization: {SuccessFactors}
- Business impact: {User with middle name are not having middle name as part of initials. e.g. Marjolein van Veen, MvV}

**Comment by stoehr** [comment]
And FYI that even though https://experience.sap.com/fiori-design-web/avatar/#initials shows that 3 initials should be supported, but the [UI5 Classic's Avatar](https://sapui5.hana.ondemand.com/#/api/sap.m.Avatar) and [UI5 WC's Avatar](https://sap.github.io/ui5-webcomponents/playground/components/Avatar/) only supports 2 initials.

**Comment by dobrinyonkov** [comment]
Internal reference: BGSOFUIPIRIN-5871

**Comment by dobrinyonkov** [comment]
implemented with https://github.com/SAP/ui5-webcomponents/pull/5870
