### ISSUE TITLE
Object Page: ObjectPageSection responsiveness

### ISSUE THREAD

**Issue by biancamattosn** [SAP/ui5-webcomponents#5780]
**Describe the bug**
This issue is for SAP internal project.
When making screen size small a More button appears but it has a blue border but it shouldn't according to fiori guidelines.
https://experience.sap.com/fiori-design-web/work-list/#examples

**Isolated Example**
Check storybook the issue is happening there
https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-objectpage--default-story

**To Reproduce**
1. Inspect page and make it small
2. more button will appear with blue border

**Expected behavior**
The button should have no border

**Screenshots**
Issue:
![image](https://user-images.githubusercontent.com/91496753/188212309-65072fbd-92a1-435a-82d5-092a13a9f5f4.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.5.0
`@ui5/webcomponents-react` version: 0.26.0
Operating System: macos
Browser: chrome

**Additional context**
SAP internal project

**Comment by nnaydenow** [comment]
Hello @SAP/ui5-webcomponents-topic-rd ,

Could you please check this? In my opinion Fiori Guidelines is not updated to the latest tab container's spec.

Regards,
Nayden

**Comment by gmkv** [comment]
Hello,
The "More" button should indeed have a border outline.
@nnaydenow is correct - at the time of writing, the Fiori Guidelines page for the Tab container is not updated according to the latest visual design specification. You can find the most recent specification that shows that there should be a border around the "More" button on [this page](https://wiki.one.int.sap/wiki/pages/viewpage.action?pageId=2505855771).
