### ISSUE TITLE
[JAM][Workzone] We need an option/parameter for NOT loading fallback theme

### ISSUE THREAD

**Issue by pakcheong** [SAP/ui5-webcomponents#5783]
### **Feature Request Description**
When custom theme is used via `http://sap-ui-theme@custom-theme@https//my-theming-service-host` it is falling back to sap_fiori_3, simply because custom theme is not supported (a related issue is created [here](https://github.com/SAP/ui5-webcomponents/issues/5730)).

Therefore we would like to have an option/parameter for **NOT** falling back to the designated theme otherwise sap_fiori_3 is always loaded when custom theme is actually selected by customers. And the priority of the loaded fallback theme stylesheets is always higher than our stylesheets (screenshot attached below).

![image](https://user-images.githubusercontent.com/2498348/188570377-f14095d5-4847-4ed8-8072-d7c6ff9190b1.png)

Furthermore, we have loaded css variables file from theming service, that is why we do not need a fallback theme.

### **Proposed Solution**
Add a boolean `theme-fallback` option/parameter. By default it is true and it should be the same with today's logic. When it is false then **NO** fallback theme is loaded, and do **nothing**.
```
<script data-ui5-config type="application/json">
  {
    "compactSize": true,
    "language": "<%= I18n.locale %>",
    "theme": 'sap_horizon',
    "theme-fallback": false
  }
</script>
```

### **Additional Context**
In our product SAP Workzone, we already integrate with theming service, but when we pass custom theme to UI5 web component, it will fall back to sap_fiori_3

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: {SAP Workzone}
- Business impact: {User complains about theming fall back to sap_fiori_3 when using custom theme}

**Comment by LidiyaGeorgieva** [comment]
Hello @SAP/ui5-webcomponents-topic-p, take a look of this feature request.

**Comment by ilhan007** [comment]
Hello @pakcheong I already asked in the other [issue](https://github.com/SAP/ui5-webcomponents/issues/5730) but I will try here as well, even if we don't fallback to sap_fiori_3, we need to know the theme that your custom theme is based on to load some component specific variables related to metrics - paddings, sizes, border types which differ between themes. sap_fiori_3 based custom theme is completely different from sap_horizon based custom theme not only in terms of colors.
The colors will come from theming service that you have, but we still need to know the base theme to load additional stuff.

Do you know how to read this information from the theming service - to read what is the base theme that the custom theme is derived from?

**Comment by TinaC** [comment]
@ilhan007  There is a metadata file that includes the base theme info that can be returned from the theming service.

I checked my `/comsapuitheming.runtime/themeroot/v1/UI5/sap/ui/core/themes/tina_custom_quartzdark/custom.css`
There is an `Extends` property.
But for more definitive answer, you should consult theming service collages

```
    --sapThemeMetaData-UI5-sap-ui-core: {
        "Path": "UI5.sap/ui/core.tina_custom_quartzdark.custom", "PathPattern": "/%frameworkId%/%libId%/themes/%themeId%/%fileId%.css", "Extends": ["sap_fiori_3_dark","base"], "Engine": {
            "Name": "theming-engine", "Version": "1.71.0"
        }

        , "Version": {
            "Build": "1.106.0.20220930023637", "Source": "1.106.0"}
    }
```

**Comment by ilhan007** [comment]
Hello @TinaC thanks you for your input. Nevertheless, I think when we start supporting custom theming service as requested with https://github.com/SAP/ui5-webcomponents/issues/5730, the current issue can be closed as it the framework won't fallback and the custom theme will be set.

**Comment by TinaC** [comment]
Yes, I agree, this propose solution is just a workaround.

**Comment by ilhan007** [comment]
Hello @TinaC as we closed https://github.com/SAP/ui5-webcomponents/issues/5730 with a solution, we are also closing the current issue as no longer required. Later today, we will release 1.9.0, so you can try it out.
