### ISSUE TITLE
ui5-webcomponents Avatar - the component does not support numbers

### ISSUE THREAD

**Issue by Abneco** [SAP/ui5-webcomponents#5784]
Concerns the following component
https://sap.github.io/ui5-webcomponents/playground/components/Avatar/

### **Description**
the component being limited to one of the letters prevents us from using it for other simple purposes.

I would like to use it for step numbers.
And I find it silly to have to create a new component for that.

I propose to modify the following line to support numbers
node_modules/@ui5/webcomponents/dist/Avatar.js line 347 of version 1.7 of the validInitials method
`const validInitials = /^[a-zA-Z]{1,2}$/;`

I understand that this is not the initial bute of the component for you, but don't think this restriction is actually necessary.

**Comment by LidiyaGeorgieva** [comment]
Hello @SAP/ui5-webcomponents-topic-p, take a look of this feature request.

**Comment by dobrinyonkov** [comment]
Hello @Abneco,

Our UX team is informed and needs more information. 

>I would like to use it for step numbers.

This sounds like maybe you will use it inside some "Wizard" composition. 
Could you please give more details and context about your use case?

Thanks and Best Regards,
Dobrin

**Comment by Abneco** [comment]
Hello @dobrinyonkov

the wizard is often used with input data, from step to step...

Here I want to inform my users of the steps to follow, these steps are all displayed on the screen vertically in a timeline type component.

And if the customer needs oral help on the phone on a step, he gives me the number of the step at which he is blocked.


I made a little sketch

![image](https://user-images.githubusercontent.com/29584029/190167297-1e05c561-a10f-4332-bab2-c7ea42877cdf.png)

**Comment by dobrinyonkov** [comment]
Hi @Abneco,

This feature request was reviewed by our UX team, but it was not approved.

Avatar component goal is to display people/product initials or/and people/product images.  It cannot be used for any other different purposes/usage. If we expand the component features/usage then that component will become Avatar and something else, which will be difficult to support/maintain. The goal of our core controls is a component like Avatar to stay as simple and stick to his main usage as possible.

Kind Regards,
Dobrin
