### ISSUE TITLE
[SF][A11y][Dialog] - content is announced twice by JAWS

### ISSUE THREAD

**Issue by 2bno1** [SAP/ui5-webcomponents#5785]
### **Bug Description**
The content of dialog is announced duplicated by JAWS 2022.2207.

### **Expected Behavior**
The content of dialog is announced once.

### **Steps to Reproduce**
1. Go to https://codesandbox.io/s/ui5-dialog-accessible-name-mzn1c5?file=/index.html
2. Launch JAWS
3. Click "Open Dialog"
4. Observe the announcement of JAWS

### **Isolated Example**
https://codesandbox.io/s/ui5-dialog-accessible-name-mzn1c5?file=/index.html

### **Context**
- UI5 Web Components version: 1.7.0
- OS/Platform: macOS
- Browser: Chrome
- Affected component: Dialog

### **Log Output / Stack Trace / Screenshots**
<img width="1353" alt="Screen Shot 2022-09-06 at 22 43 23" src="https://user-images.githubusercontent.com/1751846/188667028-a549050f-bee3-45ea-a9cd-01d480c553e8.png">

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

**Comment by LidiyaGeorgieva** [comment]
Hello @2bno1 , I could not reproduce the issue.

The speech output, that I receive is:
"Open Dialog Button 
To activate press spacebar.
Confirmation This is a confirm message. hello dialog 
hello Link"

I'm testing with the example, provided by you, opened in new tab.
Windows OS
Chrome 104.0.5112.102 (Official Build) (64-bit)
Jaws 2022.2202.38

You marked "OS/Platform: macOS", but _"The JAWS screen reader is built specifically for Windows, and that's unlikely to change any time soon."_

Can you please retest and give more details on the way you are testing.

**Comment by 2bno1** [comment]
@LidiyaGeorgieva I tested this in a virtual machine of windows 10, with the JAWS 2022.2207.25.
Not sure if this is released to JAWS's version, can you try to test it with JAWS 2022.2207.25?
Thank you.

**Comment by tsanislavgatev** [comment]
Hello colleagues @SAP/ui5-webcomponents-topic-rd ,

Can you please take a look at this? With the version 2207.25 the content of the dialog is announced twice.

Best Regards,
Tsanislav

**Comment by don-obrien** [comment]
Missing SF_ACC label.  Can you please add it?

**Comment by TeodorTaushanov** [comment]
Hi,

This is a known JAWS 2022 issue.

Best,
Teo
