### ISSUE TITLE
[SF_ACC] ShellBarItems support aria attributes in shadowroot button

### ISSUE THREAD

**Issue by lormanlau** [SAP/ui5-webcomponents#5786]
### **Feature Request Description**
A clear and concise description of what feature is missing.
Is your feature request related to a problem? Please describe.

There is currently not a safe way of setting aria attributes into the shellbar items inner shadowroot button as the DOM can shift when adding a new shellbar item. Please help add a way to add aria attributes to the shadowroot button in shellbar items for accessibility. Current we would like aria-haspopup="menu".

### **Proposed Solution**
A clear and concise description of the solution you would like to have.
Add a buttonAriaAttributes property for us a pass a object to populate the aria attributes

### **Proposed Alternatives**
Add property aria-haspopup to write the button element.

### **Additional Context**
Add other context or screenshots related to the feature request here.

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: {SAP SuccessFactors}
- Business impact: {Medium}

**Comment by LidiyaGeorgieva** [comment]
Hello @SAP/ui5-webcomponents-topic-p, take a look of this feature request.

**Comment by dobrinyonkov** [comment]
Internal Reference: BGSOFUIPIRIN-5943
