### ISSUE TITLE
ui5-illustrated-message inside ui5-busyindicator inside ui5-dialog RTL issue

### ISSUE THREAD

**Issue by ee92** [SAP/ui5-webcomponents#5788]
### **Bug Description**
When a ui5-illustrated-message is inside a ui5-busyindicator which is inside a ui5-dialog, it causes a horizontal scrollbar in RTL mode.

### **Expected Behavior**
There should be no horizonal scrollbar

### **Steps to Reproduce**
1. Go to https://codesandbox.io/s/ui5-webcomponents-forked-x9ui4f
2. open the dialog
3. toggle the RTL
4. notice the dialog gets a horizontal scrollbar in RTL mode

### **Context**
- UI5 Web Components version: 1.7.0
- Affected component: ui5-illustrated-message / ui5-busyindicator / ui5-dialog

### **Stakeholder Info**

- Organization: SuccessFactors

Thanks for looking into it!

**Comment by LidiyaGeorgieva** [comment]
Hello @SAP/ui5-webcomponents-topic-p, please have a look at this issue. 
It is related to **ui5-illustrated-message** component and the position styles here: 

![image](https://user-images.githubusercontent.com/7242508/188922467-bcbafb70-5bd2-4b76-8d84-3adfa1b34637.png)

This can be seen in this isolated sample here: https://codesandbox.io/s/silly-sun-sjwk74
- press the button
- observe the horizontal scrollbar when in RTL
