### ISSUE TITLE
[SF][A11y]: Text spacing not applied to selected values and entered inputs into some components

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents#5792]
### **Bug Description**
Use Stylus chrome extension to apply text spacing and observe the text spacing isn't applied to the below components
1. ui5-combobox
<img width="1681" alt="image" src="https://user-images.githubusercontent.com/13098801/188836221-5121d420-e8b0-4ed0-9775-3eb82eb94e1f.png">

2. ui5-date-picker
<img width="1254" alt="image" src="https://user-images.githubusercontent.com/13098801/188836437-b78caaf0-c279-4c26-a2c7-04e4989fdb7b.png">

3. ui5-daterange-picker
<img width="793" alt="image" src="https://user-images.githubusercontent.com/13098801/188836543-113f049f-f190-4ac8-90a2-534452021e08.png">

4. ui5-datetime-picker
<img width="969" alt="image" src="https://user-images.githubusercontent.com/13098801/188836693-bfd57ab7-0fba-4ff0-a250-15ccdc97d69f.png">

5. ui5-input
<img width="1378" alt="image" src="https://user-images.githubusercontent.com/13098801/188836818-c0e3267f-ba47-4173-828d-cf98ed328793.png">

6. ui5-multi-combobox
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/13098801/188836972-b0a7aa09-d4ab-4f0d-9215-8b32d2c80a0a.png">

7. ui5-multi-input
<img width="1238" alt="image" src="https://user-images.githubusercontent.com/13098801/188837095-ce3f9188-16f9-4b1b-b27e-1abb1a6ac512.png">

8. ui5-select
<img width="1325" alt="image" src="https://user-images.githubusercontent.com/13098801/188837222-dc87ed81-ea77-4f87-b500-caa07ae04618.png">

9. ui5-step-input
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/13098801/188837595-c08d0d83-d98b-418a-b0ec-4bf973bbca51.png">

10. ui5-textarea
<img width="1049" alt="image" src="https://user-images.githubusercontent.com/13098801/188837729-60748699-d1a2-4d17-b621-c43d883a9a3a.png">

11. ui5-time-picker
<img width="774" alt="image" src="https://user-images.githubusercontent.com/13098801/188837857-f6c61373-c567-487f-bc80-f7b2a6c37247.png">

### **Expected Behavior**
Text spacing should be applied correctly to entered values. 

### **Context**
- UI5 Web Components version: {1.6.0}
- OS/Platform: {...}
- Browser: {Chore}
- Affected component: {...}

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {SAP SuccessFactors}
- Business impact: {...}

**Comment by LidiyaGeorgieva** [comment]
Hello @GongRichard ,

I tested the listed components with the following configuration:
<html>
<body>


/*{    line-height:1.5 !important;    letter-spacing:0.12em !important;    word-spacing:0.16em !Important;  }  
p {    margin-bottom:2em !important;  }



</body>
</html>
and I found only two controls that have issues:

1. ui5-combobox - text spacing applies correctly
2. ui5-date-picker - text spacing applies correctly
3. ui5-daterange-picker - text spacing applies correctly
4. ui5-datetime-picker - text spacing applies correctly
5. ui5-input - text spacing applies correctly
6. ui5-multi-combobox - text spacing applies correctly
7. ui5-multi-input - text spacing applies correctly
8. ui5-select - text spacing applies correctly
9. ui5-step-input - **issue that can be seen in sample "Step Input with min, max, step and valuePrecision"**
10. ui5-textarea - text spacing applies correctly
11. ui5-time-picker - **issue for the placeholder and the value**

Please retest and confirm.

Best Regards,
Lidiya

**Comment by GongRichard** [comment]
Hi @LidiyaGeorgieva,
I used your css configuration, it doesn't work. 
<img width="982" alt="image" src="https://user-images.githubusercontent.com/13098801/189012139-6f8a7a65-7ba8-4a61-9735-63202c047437.png">

<img width="1791" alt="image" src="https://user-images.githubusercontent.com/13098801/189012084-c96393d2-fc6e-41de-8c2c-52062e47429a.png">

Thanks,
Richard

**Comment by GongRichard** [comment]
Hi @LidiyaGeorgieva ,
Yes, you are right. I only tested by adding css in body tag. Now I applied the css to the wc html tag. Except ui5-step-input  and ui5-time-picker, others works well.
<img width="843" alt="image" src="https://user-images.githubusercontent.com/13098801/189013268-be4a72e4-23cd-4a1a-b6d9-7bffc89fd425.png">

Thanks,
Richard

**Comment by GongRichard** [comment]
Hi @LidiyaGeorgieva,
We use ui5-input inside a SF customized webcomponents, the css can't be applied to the input. Do you know the reason? 
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/13098801/189025016-532ae16b-8cd9-4db0-aac4-c789fcf236d5.png">
<img width="979" alt="image" src="https://user-images.githubusercontent.com/13098801/189025342-9c2e4a46-b786-4224-af7f-da7d2085ca03.png">

Thanks,
Richard

**Comment by LidiyaGeorgieva** [comment]
Hello @SAP/ui5-webcomponents-topic-b please take over.

For the following components have issues when text spacing is changed with Stylus chrome extension:
- ui5-step-input - issue that can be seen in sample "Step Input with min, max, step and valuePrecision"
- ui5-time-picker - issue for the placeholder and the value

Issues are not reproducible for openui5.

**Comment by LidiyaGeorgieva** [comment]
> Hi @LidiyaGeorgieva, We use ui5-input inside a SF customized webcomponents, the css can't be applied to the input. Do you know the reason? <img alt="image" width="1138" src="https://user-images.githubusercontent.com/13098801/189025016-532ae16b-8cd9-4db0-aac4-c789fcf236d5.png"> <img alt="image" width="979" src="https://user-images.githubusercontent.com/13098801/189025342-9c2e4a46-b786-4224-af7f-da7d2085ca03.png">
> 
> Thanks, Richard

Hello @GongRichard ,

We suspect the reason is the same as the reason for the reported issues - 
ui5-input is internal for the ui5-input-sf-goal-form (and for ui5-time-picker and ui5-step-input).
Hint for the fix can be searched in the ui5-date-picker (since it works as expected).
Most possibly some CSS styles for the Input should be set with value "inherit" in order the Input to receive the CSS styles from the outer control.

Best Regards,
Lidiya

**Comment by GongRichard** [comment]
Hi @LidiyaGeorgieva ,
Thanks a lot. I will try the solution as ui5-date-picker to see if can fix the issue.
Thanks,
Richard

**Comment by ilhan007** [comment]
Hello @GongRichard,
you said offline that you still have issues with the ComboBox, could you share them with us here?

**Comment by GongRichard** [comment]
I checked ui5-combobox’s style, line-height, letter-spacing and word-spacing were set to normal, whether they should were set to inherit? And for ui5-date-picker, ui5-daterange-picker, ui5-datetime-picker, ui5-input, ui5-multi-combobox, ui5-multi-input, ui5-step-input, ui5-textarea and ui5-time-picker, they have this same code issue.
<img width="1779" alt="image" src="https://user-images.githubusercontent.com/13098801/221794282-e9b06b58-cf04-46ee-afbd-c5c2e1781470.png">

**Comment by ilhan007** [comment]
Hi @unazko @LidiyaGeorgieva  could you check this new input by @GongRichard
