### ISSUE TITLE
ui5-dialog: add `accessibleRole` attribute

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents#5796]
### **Feature Request Description**
In UI5 Web Components for React, we're building a MessageBox on top of the `ui5-dialog`. 
In SAPUI5, all [`MessageBox`](https://ui5.sap.com/#/entity/sap.m.MessageBox/sample/sap.m.sample.MessageBox) controls have the accessible role `alertdialog`. In order to have a proper screen reader support, we'll need to set the `role` as well.

### **Proposed Solution**
Support the `accessibleRole` attribute which allows the user to set the internal `role` of the dialog.

### **Proposed Alternatives**
none

### **Additional Context**
We need this feature request to close our open MessageBox accessibility issues from SuccessFactors.

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

### **Stakeholder Info** (if applicable)

- Organization: UI5 Web Components for React / Required for SFSF
- Business impact: Need to fix bugs opened by the SFSF team

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-rd this is a new FR for the Dialog. Please have a look. 

Thank you!

**Comment by MarcusNotheis** [comment]
Hi colleagues,
is there any update on this feature request? We received an SFSF accessibility issue in UI5 Web Components for React and we would need to define the `accessibleRole` attribute on the dialog in order to fix it.

Reproducible Sample:
https://codesandbox.io/s/inspiring-neco-c0dh3v?file=/src/App.js

Only the Error and Warning Dialogs are announced as Modal, the other two states not.
The ticket author expects to have the modal announcement for dialog states.

Issue: https://github.com/SAP/ui5-webcomponents-react/issues/3431

**Comment by gmkv** [comment]
Solved by #6221
