### ISSUE TITLE
formatValue function on DatePicker / DateRangePicker and TimePicker is not defined on first render

### ISSUE THREAD

**Issue by ChewbaccaCookie** [SAP/ui5-webcomponents#5799]
### **Bug Description**
After initialization of a DatePicker / RangeDatePicker or TimePicker component, we try to use the _formatValue_ function of these components. The problem is, that this function is not always already defined. We're using these components in React and define a reference on these components to access this function. As far as this reference gets resolved we save it in a state for later usage. The problem is that the reference is already resolved, but the formatValue function is not registered at this time. For this reason, we have to wait recursively until this function exists.

With this code we solved the issue (But this is very hacky and is performance heavy):
```
    const dateFormatRef = useCallback((node: any) => {
        if (node !== null) {
            if (!node.formatValue) {
                setTimeout(() => dateFormatRef(node));
            } else {
                setNode(node);
            }
        }
    }, []);
```

### **Expected Behavior**
I would expect that the function is registered at the same time when the reference is resolved for this component.

```
    const dateFormatRef = useCallback((node: any) => {
        if (node !== null) {
            setNode(node);
        }
    }, []);
```

### **Steps to Reproduce**
View the example.

### **Isolated Example**
Example can be found here: https://codesandbox.io/s/heuristic-ride-whp3ku?file=/src/App.js

### **Context**
- UI5 Web Components version: latest
- OS/Platform: all
- Browser: all
- Affected component: DatePicker, DateRangePicker, TimePicker

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SAP SE

**Comment by LidiyaGeorgieva** [comment]
Hello @SAP/ui5-webcomponents-topic-b please have a look

**Comment by hinzzx** [comment]
Hi @ChewbaccaCookie ,

Could you provide a little bit more information about the use case ? This way we could help you solve the issue.

Best Regards,
Stoyan

**Comment by ChewbaccaCookie** [comment]
Hi @hinzzx ,
we're using the formatValue function, because we need to pass values formatted to the Time Picker / Date Picker ... components. Because of that we need this function to set the value of the components. The problem is, that the function is not available right after rendering the component. It needs some time before the formatValue function is bound to the component

**Comment by ilhan007** [comment]
It's rather related to react/ui5webcomps lifecycle rather than the components themselves. Forwarding to the 
@SAP/ui5-webcomponents-core team.

**Comment by ilhan007** [comment]
Hello @ChewbaccaCookie 
Indeed the custom element has not been upgraded at the point you are accessing it. The standard way is ti await its definition via: `await customElements.whenDefined("ui5-daterange-picker");`

Check out my fork
https://codesandbox.io/s/goofy-mestorf-d9zyg7?file=/src/App.js

```ts
const dateFormatRef = useCallback(async (node) => {
    if (node !== null) {
      // NODE IS FOUND
      console.log(node);

      await customElements.whenDefined("ui5-daterange-picker");

      if (!node.formatValue) {
        // BUT NO formatValue at this node
        alert("Node loaded, but no formatValue is found");
      } else {
        alert(
          "formatValue is found::" + node.formatValue(new Date("20 Apr 2018"))
        );
      }
    }
  }, []);
  ```

**Comment by ChewbaccaCookie** [comment]
Hi @ilhan007,
thank you for this solution.
