### ISSUE TITLE
[SF][ui5-multi-input] MultiInput should not display tokens remove button when in readonly mode

### ISSUE THREAD

**Issue by Neeeko** [SAP/ui5-webcomponents#5808]
### **Bug Description**
You recently introduced a fix to prevent the `token-delete` event from being fired when the `ui5-multi-input` is in `readonly` mode. See: https://github.com/SAP/ui5-webcomponents/commit/c8f417819a8628afeff2ca496a4d72335190463e#diff-a832beb19fa5004019447ba5a8dfaa7fcddce8b50b28e834080a7c575ffdab44R145

However, the `ui5-token` are still showing the `x` button (which is now useless), same for the "View More" popover which still displays a list in `Delete` mode.

### **Expected Behavior**
When ui5-multi-input is in `readonly` mode, it shouldn't display any `x` button neither in the Token nor in the "View More" popover list.
Although this button can be removed when using `readonly` property on the `ui5-token` itself, it will still appear in the "View More" popover list (see below codesandbox for an example)

### **Steps to Reproduce**
1. Go to https://codesandbox.io/s/ui5-webcomponents-forked-g4qw0e?file=/index.html
2. Notice that the `ui5-multi-input` has `readonly` property and some `ui5-token` too. Regardless of the value of this property, the "x" button is now useless in both the `ui5-token` and the "View More" popover.

### **Context**
- UI5 Web Components version: latest
- OS/Platform: MacOS
- Browser: Chrome
- Affected component: ui5-multi-input

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### **Stakeholder Info** (if applicable)

- Organization: SF

**Comment by tsanislavgatev** [comment]
Hello colleagues @SAP/ui5-webcomponents-topic-rl,

Can you please take a look at this issue?

Best Regards,
Tsani

**Comment by niyap** [comment]
Hello @Neeeko,

Thanks for sharing your findings!

We are familiar with the problem and there is an issue already created about that #4522.
We would therefore close this message. We will continue to process your inquiry under the number of the existing message. Please follow the progress there.

Kind Regards,
Niya
