### ISSUE TITLE
[SF][SF_ACC][Breadcrumb][expected within two weeks]Breadcrumb overflow popup cancel button position is incorrect in mobile mode

### ISSUE THREAD

**Issue by ksblklu** [SAP/ui5-webcomponents#5810]
**Describe the bug**
the cancel button position of breadcrumb overflow popup is incorrect in mobile mode

**To Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-dynamicpage--default-story&globals=theme:sap_horizon
2. Switch to mobile mode
3. click on the breadcrumb overflow ellipsis button
<img width="537" alt="image" src="https://user-images.githubusercontent.com/27538066/190099297-46bf7e0d-2057-4f72-8034-250e05a94ac5.png">

4. See the cancel button position of breadcrumb overflow popup is incorrect.
<img width="539" alt="image" src="https://user-images.githubusercontent.com/27538066/190099477-cf30c4a5-81ad-4484-b212-3f843d0b6ffb.png">

**Expected behavior**
The cancel button should be aligned at the footer center 

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.7.1
`@ui5/webcomponents-react` version: 0.28.1
Operating System: any
Browser: Chrome
### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by tsanislavgatev** [comment]
Hello colleagues @SAP/ui5-webcomponents-topic-p ,

Can you please take a look at this issue?

I've checked it in openui5 and it seems to be with X button in top right corner.

I am not sure if the suggested position is correct on our side, but you can verify it.

Best Regards,
Tsanislav
