### ISSUE TITLE
[SF_ACC][AXE][ui5-menu]: AXE Error - ARIA dialog and alertdialog nodes should have an accessible name

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents#5814]
### **Bug Description**
There has below axe error for menu.
ARIA dialog and alertdialog nodes should have an accessible name.

### **Expected Behavior**
Set aria-label of dialog.
Maybe also it's better to provide accessibleName interface to let app to define the aria-label text.

### **Steps to Reproduce**
1. Go to 'https://sap.github.io/ui5-webcomponents/playground/components/Menu/'
2. Run axe plugin to scan the page
3. You will see the error

### **Context**
- UI5 Web Components version: {1.7.1}
- OS/Platform: {...}
- Browser: {...}
- Affected component: {ui5-menu}

### **Log Output / Stack Trace / Screenshots**
<img width="1785" alt="image" src="https://user-images.githubusercontent.com/13098801/190319758-4e7dfd2a-4391-4d93-92fb-5a4557651c7e.png">

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {SAP SuccessFactors}
- Business impact: {...}

**Comment by tsanislavgatev** [comment]
Hello @GongRichard ,

Since 1.7.0 we have an API in the Menu for accessibleName, can you please check: https://sap.github.io/ui5-webcomponents/playground/components/Menu/

And update if this will help you apply the expected result?

Best Regards,
Tsanislav

**Comment by GongRichard** [comment]
Hi @tsanislavgatev ,
Only MenuItem defined accessibleName, there is no accessibleName defined for Menu.
Thanks,
Richard

**Comment by ilhan007** [comment]
Hello @GongRichard it's on the MenuItem, which is also described in the Menu's API reference page.

**Comment by GongRichard** [comment]
Hi @ilhan007,
As menu rendered as a popover, the popover also needs aria-label, otherwise there will have axe error. Please run the axe plugin to test the component, you will find the error. And please reopen this issue.
Thanks,
Richard

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-b could follow up on this?

**Comment by ilhan007** [comment]
Hello @tsanislavgatev the author still doesn't get aria-label” text on the “section.ui5-popu-root” DOM element, as far as I understood this is the acc issue in question.
Is it possible to add this via the newly added API (that is referenced as a solution and the issue has been closed with)?
