### ISSUE TITLE
Refactoring of SDK URL for the FontFace.css adds .org.com to 72Black

### ISSUE THREAD

**Issue by henriquemattos** [SAP/ui5-webcomponents#5820]
### **Bug Description**

https://github.com/SAP/ui5-webcomponents/blob/main/packages/base/src/css/FontFace.css#L65

https://github.com/SAP/ui5-webcomponents/commit/d6f7ad6b4a3ab25c0b01a2358d00e632cbfc8eb8#diff-7c03a34c79556ba51dab45ebe02f2aae3fcded0bb9c1f70b7d3f4e91817d77e4R65

### **Expected Behavior**
Only `.org` should appear in the ULR

### **Steps to Reproduce**
See the source above

### **Isolated Example**
-- 
### **Context**
- UI5 Web Components version: {...}
- OS/Platform: {...}
- Browser: {...}
- Affected component: {...}

### **Log Output / Stack Trace / Screenshots**
```
{...}
```
### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by henriquemattos** [comment]
I will open a PR

**Comment by ilhan007** [comment]
Fixed with: https://github.com/SAP/ui5-webcomponents/pull/5822
