### ISSUE TITLE
Missing property tooltip for List component

### ISSUE THREAD

**Issue by DanielCavemann** [SAP/ui5-webcomponents#5826]
**Is your feature request related to a problem? Please describe.**
Yes, basically when we use "List" component with the mode "Delete", the default tooltip is "Delete". However in our context we use the List to remove a value, not delete it. 

**Describe the solution you'd like**
Add a "tooltip" property to overload the default "delete" tooltip.

**Describe alternatives you've considered**
NA

**Additional context**
Unfortunately, we are forced to used List component cause the SAP Fiori standard.

**Comment by plamenivanov91** [comment]
Hello @ui5-webcomponents-topic-p ,

The reporter wants a way to set a custom tooltip to the 'X' button when the List is in 'Delete' mode.

Currently the tooltip defaults to 'Delete' but the user's use case is a bit different.

Could you please discuss if this feature request should be implemented?

Regards,
Plamen Ivanov

**Comment by dobrinyonkov** [comment]
Internal Reference: BGSOFUIPIRIN-5928
A slot named `deleteButton` will be created.
