### ISSUE TITLE
Dialog: wrong title border appearance in dialogs with various state properties in Quarz HC

### ISSUE THREAD

**Issue by EtienneWille** [SAP/ui5-webcomponents#5832]
### **Bug Description**
Wrong title border appearance in dialogs with various state properties only in Quarz HC themes.
<img width="378" alt="image" src="https://user-images.githubusercontent.com/109946790/191377402-5d95e7b1-11fe-48c7-beef-481704d3b1b7.png">
<img width="289" alt="image" src="https://user-images.githubusercontent.com/109946790/191377744-a90e5c5d-320f-416a-ad1e-ba4cf0392f18.png">

**There should be only the red border.**

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/Dialog/?sap-ui-theme=sap_fiori_3_hcb&isrtl=false
2. Go to dialogs with various state properties section.
3. See the examples

### **Context**
- UI5 Web Components version: {latest}
- Affected component: {Dialog}

### **Priority**
- [x] Low
- [ ] Medium
- [ ] High
- [ ] Very High

**Comment by plamenivanov91** [comment]
Hello @SAP/ui5-webcomponents-topic-rd ,

Could you please make sure that we show the correct `box-shadow` on `:host([state="Error"]) .ui5-popup-header-root` when we are at HCB and HCW sub-themes.

Regards,
Plamen Ivanov
