### ISSUE TITLE
[SF][Feature Request][Timeline][High - Expected WithIn Two week] Provide parameters for us to modified the css of title-text or subtitle-text in ui5-timeline-item

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents#5833]
Dear colleagues,
I am from SuccessFactors Web Experience Shanghai team.

**Feature Request Description**
[SF][Timeline] Provide parameters for us to modified the css of title-text or subtitle-text in ui5-timeline-item according our UX requirement.

Demo Page: [https://sap.github.io/ui5-webcomponents/playground/components/Timeline/](https://sap.github.io/ui5-webcomponents/playground/components/Timeline/)

**Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

**Comment by plamenivanov91** [comment]
Hello @SAP/ui5-webcomponents-topic-b ,

Could you please discuss the implementation of this feature request and whether or not it should be implemented?

Regards,
Plamen Ivanov

**Comment by petyabegovska** [comment]
Hello @sfsf-xweb-sh,

Can you give us more details on the UX requirement you need to achieve?

Best regards,
Petya

**Comment by ilhan007** [comment]
Hello @sfsf-xweb-sh 
the github issues states "Expected WithIn Two week" (let's put aside that FR planning, implementation and release in 10 working days is a bit unlikely), but there is no response in 8 days - I don't get the urgency?

Moreover, we follow a list of issues given by SF, including the most urgent issues (check the internal communication channel for more info on that), and this is not part of it. Perhaps you need to discuss it internally and add it to the list.
