### ISSUE TITLE
[SF][Input]: Input box behave incorrectly when using non-english language in Safari

### ISSUE THREAD

**Issue by tandan0813** [SAP/ui5-webcomponents#5838]
**Describe the bug**
When using Safari browser and using non-english language such as Chinese or Japanese, the `input` box behaves incorrectly. It will keep the letters that have already been made into words.

**To Reproduce**
1. Go to Safari browser
2. Use non-english input method
3. Type something into input box

**Screenshots**
<img width="637" alt="image" src="https://user-images.githubusercontent.com/10113427/191650322-5180d2f0-680a-4949-a380-01c5bf316361.png">

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.7.1
`@ui5/webcomponents-react` version: 0.28.2
Operating System:
Browser: Safari

**Comment by PetyaMarkovaBogdanova** [comment]
Hi @tandan0813 ,
unfortunately, I cannot reproduce the issue that you are describing.
Can you, please, provide a snippet with the usage of ui5-input component, that triggers the problem. Also if the issue is visible only in Safari, are you using some plugins like auto-corrector, that can be causing it?
Thank you!

Best regards,
Petya Markova.
(UI5 Web Components Dispatcher)

**Comment by tandan0813** [comment]
No, i didn't use any plugins and i just tried the following `Input` examples in Safari.
https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-input--default-story


![2022-09-26_10-28-31 (1)](https://user-images.githubusercontent.com/10113427/192182277-38b01d33-38db-45a2-b966-e32e42eaa610.gif)

**Comment by gmkv** [comment]
I could reproduce this issue:
1. Added Chinese as an input language to macOS
2. On each input element, type "a" then press Space.

https://codesandbox.io/s/ui5-webcomponents-forked-bd5q2o?file=/index.html

https://user-images.githubusercontent.com/22086365/192829450-4e95b965-24b0-4e2e-b56c-b05a7fc65df0.mov
