### ISSUE TITLE
[SF][ui5-tabcontainer] The Popup can't be closed after open by over flow More Button In Mobile Mode

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents#5854]
### **Bug Description**

The Popup can't be closed after open by over flow More Button 

### **Steps to Reproduce**
Below are the steps to reproduce this issue

step1: open the link https://sap.github.io/ui5-webcomponents/playground/components/TabContainer/
step2: change to the mobile mode by chrome dev tool
step3:  click the  over flow More Button 
step4: click the cancel button

![image](https://user-images.githubusercontent.com/78520316/192690371-6c0d209c-e52f-4ac0-8f86-71d179aaa2ed.png)
![image](https://user-images.githubusercontent.com/78520316/192690292-961d2395-3538-4c70-866b-69f3f3ad276a.png)

### **Isolated Example**
https://sap.github.io/ui5-webcomponents/playground/components/TabContainer/

### **Context**
- UI5 Web Components version: 1.7.1
- OS/Platform: {...}
- Browser: {...}
- Affected component: {...}

### **Log Output / Stack Trace / Screenshots**
```
{...}
```
### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by niyap** [comment]
Hello @SAP/ui5-webcomponents-topic-rd,

Please check the description of the issue. I tested it on real mobile device and it is reproducible both in the Playground and in the test page samples.

Could you please look over the issue?

Thank you in advance!

Kind Regards,
Niya
