### ISSUE TITLE
[Calendar] ACC - Month and year pickers missing announcement 

### ISSUE THREAD

**Issue by allen138** [SAP/ui5-webcomponents#5858]
### **Bug Description**
Hi team,

The calendar month and year picker are missing a description when they are opened. The SAPUI5 equivelant will announce, 'Month picker read only'. Similar for the year picker. This description makes it clear for blind users to understand where they are and how to proceed. Please see:

![image](https://user-images.githubusercontent.com/38701667/192827976-3d74dbef-b7dc-4cf2-86c4-ae406c2c41e0.png)
![image](https://user-images.githubusercontent.com/38701667/192827874-f19d0fc6-bc4f-4454-b3e3-7372aa4d6da9.png)

Thanks,
Allen

### **Expected Behavior**
Month picker should have an announcement: 'Month picker read only'
Year picker should have an announcement: 'Year picker read only'

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/Calendar/
2. Using jaws, select the year button in the calendar header. See the month picker opens.
3. Check the announcements and you may crosscheck them with https://openui5.hana.ondemand.com/entity/sap.ui.unified.Calendar/sample/sap.ui.unified.sample.CalendarSingleDaySelection

### **Context**
- UI5 Web Components version: 1.7.1
- OS/Platform: All
- Browser: Chrome (All)
- Affected component: Calendar

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SF
- Business impact: Medium

**Comment by niyap** [comment]
Hello @SAP/ui5-webcomponents-topic-b,

When the year picker within the calendar is accessed, the speech output is different in UI5 and in the WC. In UI5, it is announced "year picker" and in the WC such information is not announced.

Could you please check?

Thank you in advance!

Kind Regards,
Niya
