### ISSUE TITLE
data-ui5-theme-properties are loaded with a delay

### ISSUE THREAD

**Issue by ndeshev** [SAP/ui5-webcomponents#5861]
Hello,

Recently we observed strange behavior when we were trying to get css variable values in a component, like this:

`const padding = getComputedStyle(document.querySelector(":root")).getPropertyValue("--_ui5_textarea_padding");
`

This line will not return the computed style value in the `onBeforeRendering `method, unless the currently used theme is the default 'Fiori 3' one. 

If we try to get it on a later stage of the component lifecycle or after everything is loaded it is ok. 
Even if we put a breakpoint in `onBeforeRendering`  it is getting loaded. However, otherwise its not, so it seems there is a delay for some reason.

Seems like the second style block that is responsible for the component specific parameters is the one not loaded on time:
`document.querySelectorAll(`style[data-ui5-theme-properties]`)[1]
`

The first one with the global variables such as `--sapFontSize` is fine.

We also tried using the `ThemeLoaded `event, the result was the same. At the time when the handler is executed there are only the global vars loaded.

```
attachThemeLoaded((theme) => {
   console.log(getComputedStyle(document.querySelector(":root")).getPropertyValue("--_ui5_textarea_padding"));
   console.log(document.querySelectorAll(`style[data-ui5-theme-properties]`));

   console.log(theme);
});
```

It seems like no matter what theme is set, the library first loads all fiori_3 params and only after that the ones that are related to the currently used theme.

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by nnaydenow** [comment]
Depends where the variables are defined. If they are added to the custom element we have to `call getComputedStyles(this)`. If they are defined as css variables to the component css file they are going to be defined in the component shadow root so we have to check for them inside it.

It's expected first time variables to be undefined inside onBeforeRendering since they component shadow root is not rendered.

**Comment by ndeshev** [comment]
Hello @nnaydenow,

`If they are defined as css variables to the component css file they are going to be defined in the component shadow root so we have to check for them inside it.`

 the issue is for the global styles contained  within the second style tag in the header that has `data-ui5-theme-properties `attribute.  The first global styles block with that attribute is always loaded fine.

`It's expected first time variables to be undefined inside onBeforeRendering since they component shadow root is not rendered.`

This doesn't  seems to explain why the parameters are loaded for the default theme (Fiori 3) but not for the Horizon one.

**Comment by ndeshev** [comment]
@nnaydenow  the issue doesn't seem to be reproducible anymore, I tried to do it the same way that we did it back when this issue but there is no problem now.
