### ISSUE TITLE
Table: extend `::part()` support

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#5866]
### **Feature Request Description**
We (UI5 Web Components for React) are currently refactoring our [FilterBar](https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-filterbar--default-story) component ([PR](https://github.com/SAP/ui5-webcomponents-react/pull/2731)), there we're using the `ui5-table` inside the filter dialog. When implementing we noticed that we need to customize the web component on different levels and for this we're currently using the undocumented `addCustomCSS` function. Since this is not the recommended way, we would like to ask to add the `part` attribute to the following elements inside the shadow root of the component:

- https://github.com/SAP/ui5-webcomponents/blob/a8a4acdd7e919fb6ef32a8587748b82441a6379c/packages/main/src/Table.hbs#L1

- https://github.com/SAP/ui5-webcomponents/blob/a8a4acdd7e919fb6ef32a8587748b82441a6379c/packages/main/src/Table.hbs#L8

- https://github.com/SAP/ui5-webcomponents/blob/a8a4acdd7e919fb6ef32a8587748b82441a6379c/packages/main/src/Table.hbs#L9

- https://github.com/SAP/ui5-webcomponents/blob/a8a4acdd7e919fb6ef32a8587748b82441a6379c/packages/main/src/Table.hbs#L23

If you need more information, e.g. on what we're customizing, please let me know.

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: UI5 Web Components for React

**Comment by niyap** [comment]
Hello @Lukas742,

May I ask you to provide a sample or describe how do you use the ui5-table inside your FilterBar and what exactly you have to customise?

Thank you in advance!

Kind Regards,
Niya

**Comment by Lukas742** [comment]
Hi @niyap 

sure :) 

In the Group view of the filter dialog, we need to render tables without header.

<img width="626" alt="image" src="https://user-images.githubusercontent.com/9749730/193249310-ee91af74-98e9-4b4f-9d61-50686f922210.png">

screenshot was taken from [this SAPUI5 example](https://sapui5.hana.ondemand.com/#/entity/sap.ui.comp.smartfilterbar.SmartFilterBar/sample/sap.ui.comp.sample.smartfilterbar.example1)

 For this we needed to set the following variables:

- https://github.com/SAP/ui5-webcomponents/blob/a8a4acdd7e919fb6ef32a8587748b82441a6379c/packages/main/src/Table.hbs#L1
--> custom variables: `border-bottom: none;`

- https://github.com/SAP/ui5-webcomponents/blob/a8a4acdd7e919fb6ef32a8587748b82441a6379c/packages/main/src/Table.hbs#L8
--> custom variables: `border-collapse: unset;`

- https://github.com/SAP/ui5-webcomponents/blob/a8a4acdd7e919fb6ef32a8587748b82441a6379c/packages/main/src/Table.hbs#L9
--> custom variables: `visibility: collapse;`

In the list view of the dialog, the table should receive a "Clear All" button in the header ([see here](https://experience.sap.com/internal/fiori-design-web/responsive-table/#select)), since this is not yet available (I'll open a feature request for this later), we decided to omit the "Select All" checkbox, as otherwise required fields could also be unselected. (because #5662 is not yet available)
<img width="320" alt="image" src="https://user-images.githubusercontent.com/9749730/193235150-0515dad1-2247-478b-baa7-0533dcfd827b.png">
screenshot was taken from [this SAPUI5 example](https://sapui5.hana.ondemand.com/#/entity/sap.ui.comp.smartfilterbar.SmartFilterBar/sample/sap.ui.comp.sample.smartfilterbar.example1)

In the list view, no "Select All" checkbox should be shown, that's why we're hiding it there as well.

- https://github.com/SAP/ui5-webcomponents/blob/a8a4acdd7e919fb6ef32a8587748b82441a6379c/packages/main/src/Table.hbs#L23
--> custom variables: `visibility: hidden;`

**Comment by niyap** [comment]
Hello @Lukas742,

I checked the other requirement for the "clearAll" functionality.
Could you please specify for which of the initially described parts of the table you need part attribute as I am a little bit confused with your reply: "So, most of our implementation has to be refactored for the group view and we will then most probably also not need the custom css"
Please, specify which ones of the initial requirements are still valid.

Thank you in advance!

Kind Regards,
Niya

**Comment by Lukas742** [comment]
Sorry for the confusion. Now, we only need it for the checkbox. The rest is not applicable anymore, due to the change of the SAPUI5 implementation.

- https://github.com/SAP/ui5-webcomponents/blob/a8a4acdd7e919fb6ef32a8587748b82441a6379c/packages/main/src/Table.hbs#L23

**Comment by Lukas742** [comment]
As discussed internally, we are sticking with `addCustomCSS` to change the styles of the checkboxes until the clear-all functionality is available.

Closed.
