### ISSUE TITLE
Add `busy` property in Dialog component

### ISSUE THREAD

**Issue by TinaC** [SAP/ui5-webcomponents#5876]
### **Feature Request Description**
There is a busy state in table component:
https://sap.github.io/ui5-webcomponents/playground/components/Table/ 

But there is no busy state in Dialog component
https://sap.github.io/ui5-webcomponents/playground/components/Dialog/

We want to disable this dialog while loading data

### **Proposed Solution**

Add `busy` state

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: {JAM}
- Business impact: {}

**Comment by gmkv** [comment]
Hi @TinaC 
You can wrap the Dialog in a [Busy Indicator component](https://sap.github.io/ui5-webcomponents/playground/components/BusyIndicator/) to achieve this. Let me know if this works for you.

**Comment by TinaC** [comment]
Hi @gmkv 
But I need the whole content in the dialog disabled/unclickable, how busy indicator can do that for me?

**Comment by gmkv** [comment]
Hi @SAP/ui5-webcomponents-topic-rd 
This issue is about adding a busy property to the Dialog, but a Busy Indicator should be sufficient.
Could you have a look if wrapping a Dialog with a Busy Indicator still disables the Dialog as expected?

**Comment by dimovpetar** [comment]
Hello @TinaC ,

You can disable the content of the dialog following the standard way with using the `ui5-busy-indicator` component.
Please check if this works for you https://codesandbox.io/s/ui5-webcomponents-forked-0zgbjv?file=/index.html.

Best regards,
Petar
