### ISSUE TITLE
BarcodeScannerDialog.js

### ISSUE THREAD

**Issue by veith** [SAP/ui5-webcomponents#5884]
### **Bug Description**
Importing the BarcodeScannerDialog fails with following error message in the browser:

```
Uncaught SyntaxError: The requested module './../../../@zxing/library/umd/index.js' does not provide an export named 'BrowserMultiFormatReader' (at BarcodeScannerDialog.js:7:10)
```

When switching line 7 to following, everything works fine, the tests still green and the playground still working

`import { BrowserMultiFormatReader, NotFoundException } from "@zxing/library";`

### **Context**
- UI5 Web Components version: 1.8.0
- OS/Platform: MacOs
- Browser: Chrome, Edge, Safari, Firefox (all latest)
- Affected component: BarcodeScannerDialog
 
### **Priority**
- [ ] Low
- [ ] Medium
- [ ] High
- [x] Very High

### **Dev env**

```json
"devDependencies": {
    "@babel/preset-env": "^7.19.3",
    "@rollup/plugin-json": "^4.1.0",
    "@custom-elements-manifest/analyzer": "^0.6.4",
    "@open-wc/building-rollup": "^2.0.2",
    "@open-wc/eslint-config": "^8.0.2",
    "@open-wc/testing": "3.1.6",
    "@rollup/plugin-babel": "^5.3.1",
    "@rollup/plugin-node-resolve": "^14.1.0",
    "@web/dev-server": "^0.1.34",
    "@web/rollup-plugin-html": "^1.11.0",
    "@web/rollup-plugin-import-meta-assets": "^1.0.7",
    "@web/test-runner": "^0.14.0",
    "babel-plugin-template-html-minifier": "^4.1.0",
    "deepmerge": "^4.2.2",
    "eslint": "^8.24.0",
    "eslint-config-prettier": "^8.5.0",
    "koa-proxies": "^0.12.2",
    "lint-staged": "^13.0.3",
    "prettier": "^2.7.1",
    "rimraf": "^3.0.2",
    "rollup": "^2.58.0",
    "rollup-plugin-terser": "^7.0.2",
    "rollup-plugin-workbox": "^6.2.0",
    "rollup-plugin-copy": "^3.4.0"
  }
```

**Comment by veith** [comment]
Hi @gmkv It is a regular setup from https://open-wc.org/  , i hope this information is useful for you.

Maybe this issue is of interest for you https://github.com/modernweb-dev/web/issues/1954#issuecomment-1159793128

Do you need more infos?

**Comment by veith** [comment]
Tasev changed "line 7"  2 weeks ago, with commit 
886f11d287b26950bf7981d064814b1fa44ef212 refactor: use the UMD bundle for zxing (#5809)

**Comment by gmkv** [comment]
Thanks @veith!

**Comment by gmkv** [comment]
Hi @SAP/ui5-webcomponents-topic-core 
A recent change https://github.com/SAP/ui5-webcomponents/pull/5809 in the way the BarcodeScannerDialog imports its barcode reading module is breaking builds. Could you have a look?

**Comment by gmkv** [comment]
Reproducible example 
[barcodescannerdialog-error.zip](https://github.com/SAP/ui5-webcomponents/files/9707911/barcodescannerdialog-error.zip)
