### ISSUE TITLE
Popup open method unstable

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents#589]
**Describe the bug**

I think that the `open` method of the Popup Web Component is potentially unstable.
At some point, there is a method `createBLyBackStyle` called and this method is accessing the first stylesheet of the document.
In case this is an external stylesheet injected by "classical" SAPUI5, e.g. "https://sapui5.hana.ondemand.com/1.56.16/resources/sap/ui/core/themes/sap_belize/library.css" this method is crashing the the following error:
`Uncaught DOMException: Failed to execute 'insertRule' on 'CSSStyleSheet': Cannot access StyleSheet to insertRule`

https://github.com/SAP/ui5-webcomponents/blob/master/packages/main/src/Popup.js#L151

**To reproduce**
1. Take a "classical" UI5 app as basis
2. Add a popover web component
3. Open the popup

**Isolated example**
Please provide an isolated example if possibile, by forking [CodeSandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html)
As soon as I find the time I'll create an example.

**Expected behavior**
The popup should open and not crash with an DOMException

**Screenshots**
![image](https://user-images.githubusercontent.com/8775211/60100744-aa359580-975a-11e9-810d-96daf9661df2.png)

**Context**
- UI5 Web Components version: v0.13.1
- OS/Platform: macOS
- Browser *(if relevant)*: Chrome 75.0.3770.100

**Affected components** *(if known)*
- Popup
- Dialog

**Comment by fifoosid** [comment]
Closing the issue, as it was fixed.
