### ISSUE TITLE
Switch: add `required`

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#5897]
### **Feature Request Description**
For screen reader support we need to be able to mark every input-like component as required. For this we would need the `Switch` to accept the `required` property/attribute.

### **Proposed Solution**
Add `required` to the component's public properties/attributes.

### **Additional Context**
We need this for our [FilterBar](https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-filterbar--default-story) implementation. There it's possible to mark a filter as required and if a filter is required, it should also be read when focusing the input. 

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: UI5 Web Components for React

**Comment by gmkv** [comment]
Hi https://github.com/orgs/SAP/teams/ui5-webcomponents-topic-b
This is a feature request to add `required` to the Switch.
Would you have a look?

**Comment by DMihaylova** [comment]
Hello @Lukas742,

We're currently working on the item as it could be seen. We just wanted to be more familiar with your use case. We suppose that whenever the Switch has required property, the idea behind that is that it has to be checked by the user, right?

Thanks & Regards,
Diana

**Comment by Lukas742** [comment]
Hi @DMihaylova 

yup, since it is practically a checkbox, I think the "required" property should also behave like the one of a checkbox.
