### ISSUE TITLE
Avatar's rounded border does not sit flush to the content 

### ISSUE THREAD

**Issue by georgimkv** [SAP/ui5-webcomponents#5919]
### **Bug Description**
The visual specification states that the avatar has an optional border.
~~1. Is there a way to remove this optional border?~~ opened a feature request #5965
2. In the Horizon theme, that border is rounded, but the containing image inside is improperly clipped. Note the whitespace between the corners of the images and the border below.
~~3.  We have a sample with a List that internally uses Avatars, and there, the optional border looks odd:~~ https://sap.github.io/ui5-webcomponents/main/playground/components/Card/?sap-ui-theme=sap_horizon&isrtl=false 

### **Steps to Reproduce**
1. Go to ['the Avatar component page'](https://sap.github.io/ui5-webcomponents/main/playground/components/Avatar/) and zoom in.
2. Sample "Basic Avatar".
More noticeable on 2X screens.

### **Context**
- UI5 Web Components version: latest
- Browser: Chrome

### **Log Output / Stack Trace / Screenshots**
<img width="1500" alt="image" src="https://user-images.githubusercontent.com/22086365/195093013-fe8fee44-44ec-45b2-b1c0-724837bc9fe6.png">

### **Priority**
- [x] Low
- [ ] Medium
- [ ] High
- [ ] Very High

**Comment by Todor-ads** [comment]
Hi @SAP/ui5-webcomponents-topic-p 

This issue is about border in Horizon theme.
Could you please check?

Regards,
Todor

**Comment by plamenivanov91** [comment]
It seems that we have to make the border optional too. I will discuss this with my team.

**Comment by gmkv** [comment]
The reported issue in "...the Horizon theme, that border is rounded, but the containing image inside is improperly clipped. Note the whitespace between the corners of the images and the border below".
This is caused by differences in size, but identical values for border-radius.
Try to draw the border with box-shadow instead. You won't have any issues with making that look "border" rounded.

I will open a separate feature request for to make the border optional.

**Comment by gmkv** [comment]
Hi, I can still reproduce this issue. Please check https://sap.github.io/ui5-webcomponents/main/playground/components/Avatar/

<img width="335" alt="image" src="https://user-images.githubusercontent.com/22086365/207859160-4640c523-27b0-41b8-9e4e-3b5537442ca1.png">

**Comment by plamenivanov91** [comment]
No longer reproducible.
