### ISSUE TITLE
[Popup]: Clean up body style class on disconnect

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents#592]
**Is your feature request related to a problem? Please describe.**
When removing an open Popup with the `modal` property set or when removing an open Dialog from the DOM, the style class `sapUiBLyBack` is not removed from the `body` tag.
This is causing inconsistencies in our application.

**Describe the solution you'd like**
Implement the `disconnectedCallback` of the Web Components lifecycle in order to clean up the style.

**Describe alternatives you've considered**
None.

**Additional context**
Happy to submit a Pull Request if desired 😄

**Comment by fifoosid** [comment]
The issue was solved.

PS: Would like to hear feedback if the solution fits your use case.
