### ISSUE TITLE
lint misses yarn

### ISSUE THREAD

**Issue by ZsDeak-SAP** [SAP/ui5-webcomponents#5920]
### **Issue Description**
I have checked out the project, run `npm i` and then `npm run lint` as per the [guide](https://github.com/SAP/ui5-webcomponents/blob/main/docs/6-contributing/02-conventions-and-guidelines.md#javascript-coding-guidelines). I was missing yarn. After installing `yarn` it succeeded. package.json is missing yarn as dev dependency (although I see [the other guide](https://github.com/SAP/ui5-webcomponents/blob/main/docs/6-contributing/01-development-workflow.md) refers it). Since package.json could guarantee it being there just as well as the node version, in my opinion it's confusing to make an exception for these 2 tools. If the project needs a package it should be represented in the package.json.

### **Issue Type**

- [✅ ] Documentation is unclear
- [ ] Documentation is incorrect
- [ ] Documentation is missing
- [✅] Other

**Comment by kineticjs** [comment]
Hi @ZsDeak-SAP,

I see you are referencing the contributors section. You are correct that you need yarn, however, in https://github.com/SAP/ui5-webcomponents/blob/main/docs/6-contributing/01-development-workflow.md we see that yarn is expected as a **prerequisite** to install all project's dependencies in the first place (i.e. you checkout the sources, then execute **yarn** from the console to install, then **yarn start** to build and serve, nothing else).

Is there an issue if you follow the exact steps from https://github.com/SAP/ui5-webcomponents/blob/main/docs/6-contributing/01-development-workflow.md to setup the project as a contributor?

Regards,
Diana

**Comment by ZsDeak-SAP** [comment]
> (although I see [the other guide](https://github.com/SAP/ui5-webcomponents/blob/main/docs/6-contributing/01-development-workflow.md) refers it)

I noticed that part as well ☝️ , what I mean is why leave it to people's attention to details? It's rather a question of `guarantee the environment is set up correctly` with minimal effort on autimation ( simple package.json modification) vs `environment is set up correctly _if_ they followed the guide and installed the correct versions`. Leaving 0 chance to error is better than minimal chance, especially when it comes at a low price. \
I'm happy to open a PR for it, _if_ you agree as well.

**Comment by kineticjs** [comment]
Hi @ZsDeak-SAP,

I see you logic but I think the goal here is to use yarn, rather than npm as a package manager (for its advantages). So, for the setup and update of the dev environment in particular, you should never use npm install or npm update, but use yarn instead.

If you think that the lifecycle can be improved, feel free to propose a contribution but the PR may not be approved by the part of the team that is responsible and experienced with the issues around package management.

In all cases thank you for raising the question.

Regards,
Diana

**Comment by kineticjs** [comment]
Hi @ZsDeak-SAP,

I just made a quick search on the recommended practice to install yarn and e.g. [here ](https://www.digitalocean.com/community/tutorials/how-to-install-and-use-the-yarn-package-manager-for-node-js) I see recommended the same setup to first install yarn globally and then, for a particular project, use it to install all project's dependencies. That is, yarn is expected to be installed as a prerequisite.

Regards,
Diana

**Comment by ZsDeak-SAP** [comment]
@kineticjs thanks for the reply, I see your point thanks. 👍 \
The other part of the "issue" still stands though, Node version could be guaranteed instead of "[Node.js](https://nodejs.org/) (__version 14 or higher__)." in the guide. I'll open a PR on that, and the team can decide if they take it or leave it.
Thanks for your time!
