### ISSUE TITLE
[SF][ui5-tree]: provide custom tree item

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents#5921]
### **Feature Request Description**
Our design contains tree pagination function, so we want add a "Show More" button in the last tree item. And we want to only have checkbox on each node text and without checkbox for subtree root node.  So we need custom tree item to render the checkbox and need custom tree item to render "Show More" button for pagination.
If possible, please provide this feature in version 1.8.0.

### **Proposed Solution**
SAP Ui5 has custom tree item https://sapui5.hana.ondemand.com/#/entity/sap.m.CustomTreeItem/sample/sap.m.sample.CustomTreeItem, please also provide wc custom tree item to let app to customize the tree item.

### **Additional Context**
<img width="825" alt="image" src="https://user-images.githubusercontent.com/13098801/195128411-de6dce6f-81c2-43ec-92cf-a10b298534eb.png">

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: {SAP SuccessFactors}
- Business impact: {...}

**Comment by Todor-ads** [comment]
Hello @SAP/ui5-webcomponents-topic-p 
take a look of this feature request.

Regards,
Todor

**Comment by dobrinyonkov** [comment]
Internal Reference: BGSOFUIPIRIN-5936

**Comment by vladitasev** [comment]
Hello colleagues, 

I'd like to share a few thoughts about this requirement: first, I think it's a valid requirement, other stakeholders might have it too. However, there are some technical challenges due to the tree's current API

```html
<ui5-tree id="tree" no-data-text="No data" mode="MultiSelect" accessible-name="Tree with accessibleName">
		<ui5-tree-item expanded text="Tree 1" icon="paste" additional-text="Available" indeterminate selected additional-text-state="Information" accessible-name="Tree item with accessibleName">
			<ui5-tree-item expanded text="Tree 1.1" additional-text="Re-stock" additional-text-state="Error" indeterminate selected>
				<ui5-tree-item text="Tree 1.1.1" additional-text="Required" additional-text-state="Warning" selected></ui5-tree-item>
				<ui5-tree-item text="Tree 1.1.2" additional-text="Available" additional-text-state="Success"></ui5-tree-item>
			</ui5-tree-item>
		</ui5-tree-item>
</ui5-tree>
```

**Comment by dobrinyonkov** [comment]
Item was planned and work has started with the current sprint.

**Comment by akshilverma** [comment]
@dobrinyonkov Can you please provide a timeline on when this feature will be available? Our product is live and our customers are already asking for an implementation that requires us to use custom tree item

**Comment by dobrinyonkov** [comment]
Hi @akshilverma, https://github.com/SAP/ui5-webcomponents/pull/5962 is under code review and I expect it to be merged soon and be part of the next release.

**Comment by akshilverma** [comment]
@dobrinyonkov I see that the 1.10.0 release is not out yet with these changes. Can you give me a timeline on when this feature will be available?

**Comment by akshilverma** [comment]
Can anyone give me a timeline on when this feature will be available?

**Comment by akshilverma** [comment]
Hi @ilhan007, thanks for your response. We are using version 1.9 right now, so a patch in the current 1.9 would suffice for us.

**Comment by akshilverma** [comment]
Hi @ilhan007, I don't see a new patch released for 1.9. Are you still releasing the patch or did something happen?

**Comment by akshilverma** [comment]
Hi @ilhan007, any update on this?

**Comment by ilhan007** [comment]
1.9.2 and the latest 1.9.3 includes it 
<img width="827" alt="Screenshot 2022-12-22 at 10 42 01" src="https://user-images.githubusercontent.com/15702139/209093813-db0282bf-2361-4f6a-834a-11443f1edcef.png">
