### ISSUE TITLE
Inputs do not have margin with Horizon theme

### ISSUE THREAD

**Issue by allen138** [SAP/ui5-webcomponents#5941]
### **Bug Description**
Hi team,
When using the Horizon theme, there should be a `margin: 0.25rem 0` on the inputs. This applies for any inputs. When the webcomponent is placed next to either SAPUI5 sap.m.Input or a native input using fundamental styles which do correctly have this margin, this creates a misalignment. Please see:
![image](https://user-images.githubusercontent.com/38701667/195895402-b6cb0fb8-a257-4910-934d-2220faf109e8.png)

### **Expected Behavior**
When horizon theme is implemented, inputs should have a `margin: 0.25rem 0`. 

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/Input/?sap-ui-theme=sap_horizon&isrtl=false
2. Inspect the inputs and verify there is no margin. 
3. Go to https://openui5.hana.ondemand.com/entity/sap.m.Input/sample/sap.m.sample.InputTypes?sap-ui-theme=sap_horizon&isrtl=false
4. Inspect the inputs and see there is a `margin: 0.25rem 0`
5. Go to https://sap.github.io/fundamental-styles/?path=/docs/components-forms-input--primary&globals=theme:sap_horizon
6. Inspect the inputs and see there is a `margin: 0.25rem 0`

### **Context**
- UI5 Web Components version: main
- OS/Platform: All
- Browser: All
- Affected component: Inputs

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### **Stakeholder Info** (if applicable)

- Organization: SF
- Business impact: Medium

**Comment by kineticjs** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

The Horizon spec for the base input specifies margin: 0.25rem 0; but no such is given to ui5-input. Can you take the case for inspection.

Thanks,
Diana

**Comment by niyap** [comment]
Hello @allen138,

Thanks for sharing your findings!

We are already aware of the problem and there is an existing issue for that https://github.com/SAP/ui5-webcomponents/issues/5032
Please, track the progress there!

Kind Regards,
Niya
