### ISSUE TITLE
Card part is not exposed

### ISSUE THREAD

**Issue by reqyou** [SAP/ui5-webcomponents#5944]
### **Issue Description**
According to [https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-card--default-story](https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-card--default-story) `root` is an exposed part of `ui5-card` `Card` component. But it seems like `part` is not exposed.

### **Issue Type**

- [x] Documentation is unclear
- [x] Documentation is incorrect
- [ ] Documentation is missing
- [ ] Other

**Comment by kineticjs** [comment]
Hi @reqyou,

Please note that the documentation states that the root part of the ui5-card-header is exposed, rather than the the ui5-card:
"root - Used to style the root DOM element of the CardHeader"

On inspection I see that for the CardHeader, the part is indeed exposed.

Regards,
Diana

**Comment by reqyou** [comment]
Oh. So it should rather be `The **HeaderCard** exposes the following CSS Shadow Parts`. Thanks for the clarification.
