### ISSUE TITLE
Form support: native validation of required form input works only partially with ui5-webcomponents input

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#5949]
### **Bug Description**
When using ui5-webcomponents inputs inside a form, the validation of required inputs differs from native inputs.
- When pressing ENTER in an empty required input:
  - `input`: `submit` is not called and the native popover is displayed
  <img width="276" alt="image" src="https://user-images.githubusercontent.com/9749730/196391848-c75439cf-da43-4b58-93e2-4a27f5f404f9.png">

  - `ui5-input`: `submit` is called, but `checkValidity()` returns false, no popover is displayed
- When clicking a button to submit the form:
  - `button`: `click` is called, `form.checkValidity()` returns false, no `submit` event is called and a popover is displayed (the same applies for `<input type="submit">`)
  - `ui5-button`: `click` is called, `form.checkValidity()` returns false, the `submit` event is called, no popover is displayed

### **Expected Behavior**
The ui5 web components should be validated in the same way as the native elements.

### **Steps to Reproduce**
1. Go to [codeSandbox](https://codesandbox.io/s/ui5-webcomponents-forked-pgultj?file=/index.html)
2. Focus the `ui5-input` in the first form and press ENTER. 
3. See that the `submit` event is called and `checkValidity` of the form returns false
4. Focus the `input` in the first form and press ENTER.
5. See that the `click` event of the submit button is called and a popover is displayed, but the `submit` event is not executed.

___

6. Click the button of the first form.
7. See that the `click` event of the submit button is called and a popover is displayed, but the `submit` event is not executed.
8. Click the ui5-button of the second form.
9. See that `click` and `submit` is called and no popover is displayed.

### **Isolated Example**
https://codesandbox.io/s/ui5-webcomponents-forked-pgultj?file=/src/index.js

### **Context**
- UI5 Web Components version: 1.8.0

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by kineticjs** [comment]
Hi @SAP/ui5-webcomponents-team,

The InputElementsFormSupport triggers a "submit" event on a form with invalid input, even though the [spec ](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/submit_event) has the following note: 

"Trying to submit a form that does not pass [validation](https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation) triggers an [invalid](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/invalid_event) event. In this case, the validation prevents form submission, and thus **there is no submit event**. "

Please also check the code snippet from @Lukas742 

Can we modify InputElementsFormSupport  to comply with the spec?

Thanks,
Diana
