### ISSUE TITLE
Feature request for Tooltip Property in MenuItems with an icon

### ISSUE THREAD

**Issue by ShivamGuptaSap** [SAP/ui5-webcomponents#5950]
### **Feature Request Description**
In Menu, one of the MenuItem contains two icons and one of them is tooltip. 
Additionally, in Menu there is a requirement of just tooltip where we only need to just display the tooltip not the icon.
 
### **Proposed Solution**
So can we please add a tooltip property and with its icon as an extra optional property in MenuItem.

### **Additional Context**
Kindly refer to this screenshot for more clarity.

With Icon: 
 
<img width="515" alt="Screenshot 2022-10-18 at 3 40 07 PM" src="https://user-images.githubusercontent.com/107616257/196402222-c3d57d9c-908f-4109-a0bd-4febedec9f8a.png">

Without Icon:
<img width="417" alt="Screenshot 2022-11-15 at 1 25 33 PM" src="https://user-images.githubusercontent.com/107616257/201861610-25c52924-b0e3-4f7d-98e3-9421909e8359.png">

### **Priority**
- [ ] Low
- [ ] Medium
- [ ] High
- [X] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: {SAP}
- Business impact: {SAC}

**Comment by ShivamGuptaSap** [comment]
Hi @petyabegovska,
I've updated the screenshots to state the requirement for better clarity, Please feel free to reach out to me for any clarification. 
Regards,
Shivam

**Comment by scameron** [comment]
Hi @petyabegovska, just wanted to check in about this feature request.  Does it seem like something that might be feasible to be added?

**Comment by petyabegovska** [comment]
Hi @scameron,

I still cannot answer. We will need some more time to evaluate it.

Best regards,
Petya

**Comment by Nef10** [comment]
Hey, 
I just wanted to check for an update here. We ran into another use case in a different area of SAC where we want to use this as well. For accessibility and user experience reasons it is often helpful to add a tooltip to disabled buttons, to explain to the user why this particular action cannot be performed right now.
Thanks!

**Comment by scameron** [comment]
Hi @petyabegovska, it looks like we're going to need to use this approach somewhat soon in our project.  Do you think it's something that could be implemented on your side?

**Comment by petyabegovska** [comment]
Hi @scameron, we are working on solution to provide a custom menu item, which should cover several use case of SAC, but there are still discussions on it. @DMihaylova can provide more details on that topic.

**Comment by scameron** [comment]
Hi @DMihaylova, what are your thoughts on this?  Would it be something your team would be OK adding to the control?  This is a pattern we're being asked for by our UX and we'd like to use it in SAC in a few different scenarios.
