### ISSUE TITLE
Switch: event.preventDefault() does not prevent toggle in onChange

### ISSUE THREAD

**Issue by C3ntraX** [SAP/ui5-webcomponents#5953]
### **Bug Description**
The default behaviour of "onChange={e => e.preventDefault()}" does not prevent the user from toggle switch fields (and maybe other too).

### **Expected Behavior**
Its the default behaviour of common fields for (true/false) like switch. 
See the web api - https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault

Its the same problem as in #5210
Because I need a controlled state to ask/warn the user, if he want to change the value of the control. 
So I need to prevent user interaction. Disabling the control would not work

### **Steps to Reproduce**
1. Go to the Sandbox
2. Click the controls
3. The controls should not change the state. Because the "onChange" has preventDefault().

### **Isolated Example**
https://codesandbox.io/s/nice-lena-sxhlbp?file=/src/App.js

### **Context**
- UI5 Web Components version: {...}
- OS/Platform: {...}
- Browser: {...}
- Affected component: {...}

### **Log Output / Stack Trace / Screenshots**
```
{...}
```
### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: Versino AG
- Business impact:

**Comment by ilhan007** [comment]
Hello @C3ntraX 
we are going to split the issue into two - the current one will leave for the Switch and [this](https://github.com/SAP/ui5-webcomponents/issues/5957) newly created one - for the CheckBox. While the issues is the same for both components, the issue processing will be simplified when an issue is related to single component.

BR,
ilhan

**Comment by kineticjs** [comment]
Hi @SAP/ui5-webcomponents-topic-b,

Can we ensure that event.preventDefault() of the "change" event of the Switch does prevent the toggling of the value?
See also the pair issue https://github.com/SAP/ui5-webcomponents/issues/5957

Regards,
Diana
