### ISSUE TITLE
Date Picker does not open

### ISSUE THREAD

**Issue by mhisham744** [SAP/ui5-webcomponents#5956]
### **Bug Description**
When trying to open a datepicker, the popover does not open as expected

### **Steps to Reproduce**
1. Add DatePicker to your custom component
2. Try to open DatePicker

### **Isolated Example**
<DatePicker
                formatPattern="yyyy-MM-dd"
                onChange={(e: any) => {
                  setSelectedNumberDateFrom({
                    title: e?.detail?.value,
                    key: e?.detail?.value
                  });
                }}
                style={{ height: 40, ...spacing.sapUiSmallMarginTop, ...spacing.sapUiLargeMarginEnd }}
              />

### **Context**
- UI5 Web Components version: @inwo/core v9.0.2
- OS/Platform: MacOS
- Browser: Chrom
- Affected component: Intelligent Workplace @inwo/core v9.0.2

### **Log Output / Stack Trace / Screenshots**
```
DatePicker.js:768 Uncaught TypeError: Cannot read properties of undefined (reading 'close')
    at DatePicker.closePicker (DatePicker.js:768:1)
    at DatePicker.togglePicker (DatePicker.js:787:1)
    at EventPart.handleEvent (lit-html.ts:2085:1)

```
### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by kineticjs** [comment]
@mhisham744,

I am trying to reproduce the issue in a running sample, so far unsuccessfully.

Few questions, please:
1) are you able to reproduce the issue with standalone DatePicker, e.g. with the samples from https://sap.github.io/ui5-webcomponents/playground/components/DatePicker/
2) if you use keyboard to open the picker, what exactly is the key sequence?
3) do you have in your setup a programmatic call to the **openPicker** method?

    I'm asking those because the from the stacktrace I infer that the error occurs when we try to close the picker right **after** openPicker() is called BUT **before** the promise returned by openPicker() resolved. 
  That is, the error occurs when we are trying to close the picker before the async operation started with openPicker() completed.

So far I infer that the issue can happen if you either:
  - call the public openPicker method programmatically in addition to user interaction
  or
  - use key sequence (or other user interaction to open the picker) that leads to two subsequent calls to togglePicker right after another.

In case you are able to reproduce the issue with a standalone DatePicker it would be great to send us a running code sample with https://codesandbox.io/

Thanks,
Diana
