### ISSUE TITLE
A bug on ios, does not display the icons correctly, the icons are enlarged.

### ISSUE THREAD

**Issue by Abneco** [SAP/ui5-webcomponents#5961]
### **Bug Description**
a bug on ios, does not display the icons correctly, the icons are enlarged, the button or timeline components are no longer usable if icons are used.

I tested in a sanbox, and the problem is the same.
I am using angular and Ui5 web component pure.

### **Expected Behavior**
the bug must be fixed so that the icons are no longer huge on ios.

### **Steps to Reproduce**
1. run sandbox on ios !!!
2. if no problem, try to simply reload the page or use open sanbox button
3. the icons should look weird, like it's enlarged

![312235452_668454077947672_7906892307882914368_n](https://user-images.githubusercontent.com/29584029/196980449-e249b79f-8153-4f87-b341-78fa9f98b541.jpg)

### **Isolated Example**
codde : https://codesandbox.io/s/nervous-farrell-2zlorp?file=/src/app/app.module.ts
test : https://2zlorp.csb.app/

### **Context**
- UI5 Web Components version: 
    "@ui5/webcomponents": "^1.8",
    "@ui5/webcomponents-base": "^1.8",
    "@ui5/webcomponents-fiori": "^1.8",
    "@ui5/webcomponents-icons": "^1.8",
    "@ui5/webcomponents-icons-business-suite": "^1.8",
    "@ui5/webcomponents-icons-tnt": "^1.8",
    "@ui5/webcomponents-theme-base": "^1.0.0-rc.16",
    "@ui5/webcomponents-theming": "^1.8",
- OS/Platform: IOS 16.0.3
- Browser: SAFARI or CHROME or FIREFOX
- Affected component:
@ui5/webcomponents/dist/Button
@ui5/webcomponents-fiori/dist/Timeline
@ui5/webcomponents-fiori/dist/TimelineItem
@ui5/webcomponents/dist/Icon ??

**UI5 theme : sap_fiori_3**

### **Log Output / Stack Trace / Screenshots**
```
{...}
```
### **Priority**
- [ ] Low
- [] Medium
- [x] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High

**Comment by kineticjs** [comment]
Hi @SAP/ui5-webcomponents-topic-p,

We have a report for exceptionally enlanged icons on iOS with sap_fiori_3 that I was able to reproduce with iPad Pro, 12.9 inch screen. Can you have a look if this should be fixed in the icon itself?

Thanks,
Diana

**Comment by PetyaMarkovaBogdanova** [comment]
Hi @Abneco ,
thank you for the finding!
The issue has been fixed in the last version, which will be released soon, you can check out the release table [here](https://github.com/SAP/ui5-webcomponents/projects?type=classic).
Best regards,
Petya Markova.
(UI5 Developer)
