### ISSUE TITLE
[SF][DatePicker]: Error value state is not shown

### ISSUE THREAD

**Issue by yuyuCream** [SAP/ui5-webcomponents#5963]
### **Bug Description**
Value state is not set to Error although the input is not a valid date format.

### **Steps to Reproduce**
1. Input a string in date picker, value state will be set to Error
2. Select a date from datepicker, value state will set to None
3. Without tabbing to change focus, input a string which is same with that in step1, value state is still None
https://sap.github.io/ui5-webcomponents/main/playground/components/DatePicker/
BTW: If the value state in step2 is set to Error for some business logic, value state in step3 is still Error.

### **Screenshots**
<img width="1227" alt="image" src="https://user-images.githubusercontent.com/32004690/197097431-6ed03f7a-981c-45e8-8532-cbb0410ac7af.png">

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.7.1
`@ui5/webcomponents-react` version: 0.28.2
Operating System: mac
Browser: Chrome

**Additional context**
I am from SAP Successfactors. And issues are for b2305 released project.

**Comment by kineticjs** [comment]
Hi @SAP/ui5-webcomponents-topic-b,

The automatic validation of Date Picker is skipped in the last step of the scenario described in this issue. Please have a look.

Thanks,
Diana
