### ISSUE TITLE
MultiInput: `value-help` icon is not imported

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#5968]
### **Bug Description**
The icon used for the internal value help button is not imported.

### **Expected Behavior**
All internally used icons should be registered by the component itself.

### **Steps to Reproduce**
1. Go to [codeSandbox](https://codesandbox.io/s/ui5-webcomponents-forked-63ip6h?file=/index.html)
2. See that even with `show-value-help-icon` no icon is displayed

### **Isolated Example**
https://codesandbox.io/s/ui5-webcomponents-forked-63ip6h?file=/index.html

### **Context**
- UI5 Web Components version: 1.8.0

### **Log Output / Stack Trace / Screenshots**
```sh
Required icon is not registered. You can either import the icon as a module in order to use it e.g. "@ui5/webcomponents-icons/dist/value-help.js", or setup a JSON build step and import "@ui5/webcomponents-icons/dist/AllIcons.js". 
```
### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by MapTo0** [comment]
Dear Colleagues,

[value help icon is used but not imported ](https://github.com/SAP/ui5-webcomponents/blob/main/packages/main/src/MultiInput.hbs#L38)

Should be imported in the component file.

Workaround is to add  `import "@ui5/webcomponents-icons/dist/value-help.js";`
