### ISSUE TITLE
Select: popover is not scrollable if value state message is too large

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#5970]
### **Bug Description**
When `ui5-select` is used on the bottom of the page and a large valueStateMessage is applied, the content of the popover is not visible anymore and also cannot be accessed by scrolling.

<img width="265" alt="Screenshot 2022-10-25 at 14 17 27" src="https://user-images.githubusercontent.com/9749730/197770850-65bbbcdb-e178-4df2-a8a5-0b12cba401a7.png">

### **Steps to Reproduce**
1. Go to [codeSandbox](https://codesandbox.io/s/ui5-webcomponents-forked-wsufcf?file=/index.html)
2. Open the select popover
3. See that the list is hidden and cannot be accessed by scrolling.

### **Isolated Example**
https://codesandbox.io/s/ui5-webcomponents-forked-wsufcf?file=/index.html

### **Context**
- UI5 Web Components version: 1.8.0

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by MapTo0** [comment]
Hello @SAP/ui5-webcomponents-topic-rd 

The issue is that the header of the popover does not have scrolling when overlaps the content restriction.
Could be reproduced with the provided example: https://codesandbox.io/s/ui5-webcomponents-forked-wsufcf?file=/index.html

Regards,
Martin

**Comment by TeodorTaushanov** [comment]
Hi @SAP/ui5-webcomponents-topic-p,

In the `ui5-select` component the value state message is placed in the "header" slot of the select popover, but it should be placed in the "content" slot. 

Best,
Teo
