### ISSUE TITLE
Double apostrophe instead of single

### ISSUE THREAD

**Issue by dan-ros** [SAP/ui5-webcomponents#5974]
### **Bug Description**
A double apostrophe shows up for the NoData illustrated message:
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/22822509/198221533-eb649414-2c58-4909-a158-d9862bc57817.png)

### **Expected Behavior**
A single apostrophe should show

### **Steps to Reproduce**
In VueJS we have the following code:
```
        <!-- No data -->
        <ui5-illustrated-message
          v-else-if="
            !bIsLoading &&
            (!aOnboardedProjects || aOnboardedProjects.length === 0)
          "
          name="NoData"
          id="noOnboardedProjectMessage"
        >
          <div slot="subtitle">
            You can onboard projects
            <router-link :to="{ name: 'GardenerOnboardProject' }"
              >here</router-link
            >.
          </div>
        </ui5-illustrated-message>
```

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### **Stakeholder Info** (if applicable)

- Organization: BTP Core
- Business impact: {...}

**Comment by dan-ros** [comment]
@vladitasev provided the following additional information
![image](https://user-images.githubusercontent.com/22822509/198224143-d74bd60f-6ebf-40f4-ac26-be27a54c346c.png)

**Comment by nnaydenow** [comment]
Hi @dan-ros,

We've provided a fix to these some time ago #5655. Which version of web components you are using ?

**Comment by dan-ros** [comment]
We are using version 1.8.0. Just deleted and installed the node_modules again.

**Comment by dan-ros** [comment]
I noticed that on npm https://www.npmjs.com/package/@ui5/webcomponents the component is missing in the list:
![image](https://user-images.githubusercontent.com/22822509/198256371-b4ff852b-0452-404d-8945-07c11b590806.png)

While in your docs https://sap.github.io/ui5-webcomponents/playground/components it is listed:
![image](https://user-images.githubusercontent.com/22822509/198256832-ff332ab8-2436-4aa6-a1e4-c2a37a3267aa.png)

Could that have something to do with it?

**Comment by nnaydenow** [comment]
Hello @SAP/ui5-webcomponents-topic-p ,

Could you please check the message bundle texts of illustrated message?

For detailed information how i18n texts are processed you can check here: #5655
