### ISSUE TITLE
Typo in word `placeholder` for the `ui5-input`/search field on the ShellBar

### ISSUE THREAD

**Issue by henriquemattos** [SAP/ui5-webcomponents#5978]
### **Issue Description**
The example shows `placeholer`, and it should be `placeholder`.

### **Issue Type**

- [ ] Documentation is unclear
- [X] Documentation is incorrect
- [ ] Documentation is missing
- [ ] Other

**Comment by niyap** [comment]
Hello @henriquemattos,

Thanks for sharing your findings!
I noticed that you have a commit for the issue but may I ask you to create a pull request with that commit in order to be reviewed  by the responsible team?

Kind Regards,
Niya

**Comment by niyap** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

There is a typo in playground sample of the ShellBar. The reporter has a commit but there is no pull request created yet.
Could you please check and decide whether you will provide a fix or you will wait for the reporter to create a pull request?

Kind Regards,
Niya
