### ISSUE TITLE
ui5-button: wrong submit behaviour

### ISSUE THREAD

**Issue by nnaydenow** [SAP/ui5-webcomponents#6006]
Hello colleagues,

As you can see in [the example](https://codesandbox.io/s/ui5-webcomponents-forked-07cgby?file=/index.html), when the button is clicked first event that appears is the submit button of the form.

Compared to the native button behaviour this seems to be wrong.

For me correct order of events should be:
1. Click from ui5-button
2. Submit from form.

Could you please check this?

**Comment by xpr0gamers** [comment]
#6014

**Comment by nnaydenow** [comment]
We decided to not doing this change for the moment.

Regards,
Nayden
