### ISSUE TITLE
[SF_ACC][ui5-dynamic-side-content]: tab sequence is not right when sideContentPosition=Start

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents#6012]
### **Bug Description**
The tab sequence is not right when sideContentPosition was set to Start. The tab order will start from main content(right) to side content(left). 
**Please fix this issue in v1.10.0 release.**

### **Expected Behavior**
The tab order should start from side content(left) to  main content(right).

### **Steps to Reproduce**
1. Go to 'https://codesandbox.io/s/vigilant-violet-7f5mw8?file=/src/SideContentDialog.js'
2. resize content panel
3. click "Open Side Content Dialog" button
4. click tab key and you will find the tab order will start from main content(right) to side content(left). 

https://user-images.githubusercontent.com/13098801/199975138-4945a274-1eb6-4feb-9c08-d4691fc70605.mp4

### **Context**
- UI5 Web Components version: {1.8.0}
- OS/Platform: {}
- Browser: {...}
- Affected component: {ui5-dynamic-side-content}

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {SAP SuccessFactors}
- Business impact: {...}

**Comment by TeodorTaushanov** [comment]
Hi @SAP/ui5-webcomponents-topic-b, can you check this issue?
