### ISSUE TITLE
Documentation for Icon: Hint that tooltip text is taken from accessible-name

### ISSUE THREAD

**Issue by mhchem** [SAP/ui5-webcomponents#6017]
### **Issue Description**
At https://sap.github.io/ui5-webcomponents/playground/components/Icon/, please add a sentence to the show-tooltip section that a tooltip text must be provided via the accessible-name property (or include an example with tooltip to the page).

### **Issue Type**

- [x] Documentation is incomplete

**Comment by unazko** [comment]
Hello https://github.com/orgs/SAP/teams/ui5-webcomponents-topic-p,

As described by the reporter the documentation could be improved as it is not obvious that the tooltip text would come from the <code>accessible-name</code> property.  Also a sample is good to have.

Best Regards,
Boyan
