### ISSUE TITLE
Improve Icon's color options

### ISSUE THREAD

**Issue by mhchem** [SAP/ui5-webcomponents#6019]
### **Feature Request Description**
Make it easier to get icons with semantic colors (e.g. error, warning, neutral colors) that match the current theme.

### **Proposed Solution**
This could be achieved similar to the MessageStrip's `design="Warning"` property.

See https://sapui5.hana.ondemand.com/#/api/sap.ui.core.IconColor%23properties for semantic icon colors. 

### **Note**
The icons' current color is `color: var(--sapContent_NonInteractiveIconColor);`. It doesn't seem right that the inactive color is also used for icons that are `interactive="true"`.

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by unazko** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

Could you please take a look of this feature request.

Best Regards,
Boyan

**Comment by dobrinyonkov** [comment]
Internal Reference: BGSOFUIPIRIN-5996
