### ISSUE TITLE
[CLDR Error] DateFormat.getTimeInstance from "@ui5/webcomponents-localization/dist/DateFormat" will throw a CLDR error

### ISSUE THREAD

**Issue by zijies1** [SAP/ui5-webcomponents#6022]
### **Bug Description**
DateFormat.getTimeInstance will throw a CLDR error when the page is first loaded. More detailed description can be found in the 
Video. 

https://user-images.githubusercontent.com/25004172/200497128-0b95a48f-8848-4d2b-ad78-5bdfc6a76bab.mp4

### **Expected Behavior**
DateFormat.getTimeInstance should not throw CLDR errors when proper assets files are imported.
`import "@ui5/webcomponents-localization/dist/Assets-static.js"`

### **Steps to Reproduce**
1. open chrome and go to **https://hcm10preview.sapsf.com** and log in with companyId(**SC10MCRSVCTST**), userName(**adminb1**) and password(plz email to rondo.shen@sap.com to get the password)
2. type "hi" or anything in the chat bar in the middle of the page and click enter button, then the chat window will show and disappear in a short time.
![Screen Shot 2022-11-08 at 15 09 04](https://user-images.githubusercontent.com/25004172/200497839-29f47f69-0df8-48ee-8b94-4ed915757b8c.png)

3. please hard reload the page if you can not reproduce

### **Isolated Example**
If possible, please provide an isolated example by forking [CodeSandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html).

### **Context**
- UI5 Web Components version: 1.6.0/1.8.0
- OS/Platform: win 10
- Browser: chrome
- Affected component: Digital Assistant

### **Log Output / Stack Trace / Screenshots**
```
 Error: CLDR data for locale en is not loaded!
```
![Screen Shot 2022-11-08 at 15 01 17](https://user-images.githubusercontent.com/25004172/200496729-c03ffb0e-6373-46e7-bafd-562498f4a287.png)

### **Priority**
- [ ] Low
- [ ] Medium
- [ ] High
- [x] Very High

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SucessFactors
- Business impact: {...}

**Comment by zijies1** [comment]
It turns out it can be handled from our side by making sure CLDR data is fetched before dateFormat object is accessed.

**Comment by ilhan007** [comment]
Hello @zijies1 based on your comment it turns out to be more on the consumption side and it's fixed now. I am closing the issue, in case we can make something more, please let us know.

BR,
ilhan
