### ISSUE TITLE
No select event emitted on user interaction with MultiInput component

### ISSUE THREAD

**Issue by ukaj808** [SAP/ui5-webcomponents#6023]
### **Bug Description**
No 'select' event emitted from the MultiInput component when clicking into the component. It's worth noting that the select event IS emitted when hitting the spacebar key within the text field which is correctly stated in the documentation.

### **Expected Behavior**
According to the documentation, a select event is _"Fired when the the component is selected by user interaction with mouse"_

### **Steps to Reproduce**
1. Listen for the select event on the multi input component (  multiInput.addEventListener('select', () => console.log('select'));  )
2. Click into the component to trigger the 'select' event.

### **Context**
- UI5 Web Components version: ^1.9.0
- OS/Platform: Linux/Debian
- Browser: Firefox
- Affected component: MultiInput

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

**Comment by unazko** [comment]
Hello @ukaj808,

The <code>select</code> event is defined as an ui5-token semantic event and not as an ui5-multi-input semantic event.
That should be the reason why the given short snippet won't produce the expected results.

The documentation for the ui5-token API is displayed on the same page.

Best Regards,
Boyan
