### ISSUE TITLE
[SF_ACC] Confusing NVDA Announcement on Label Element

### ISSUE THREAD

**Issue by IrvinDelgado** [SAP/ui5-webcomponents#6031]
### **Bug Description**
When using NVDA on Chrome, `ui5-label` elements are announced as "clickable" although there is no click event

### **Expected Behavior**
To not announce "clickable"

### **Steps to Reproduce**
1. Go to '[webcomponent website](https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-list--default-story)'
2. Using NVDA using the Keyboard highlight the label element.
3. Notice on speech viewer that "clickable" is announced

### **Isolated Example**
If possible, please provide an isolated example by forking [CodeSandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html).

### **Context**
- UI5 Web Components version: v1.9.0
- OS/Platform: Windows 
- Browser: Chrome
- Affected component: Label

### **Log Output / Stack Trace / Screenshots**

<img width="471" alt="NVDA Issue" src="https://user-images.githubusercontent.com/62973847/200952241-361e2096-7a91-4657-bb6f-be9cf0d61089.png">

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SAP

**Comment by unazko** [comment]
Hello @SAP/ui5-webcomponents-topic-rd,

The reported issue could be reproduced via the following steps:
1) Open https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-label--default-story
2) Start NVDA and navigate via the arrow up/down keys to the "Usage" ui5-label under the "Label" title, or navigate the same way to the ui5-label with text "Label Text" under "Example"

Result:
The label text and "clickable" gets announced by NVDA.

The same issue isn't reproducible via JAWS.

There is nothing in the ui5-label DOM, which would indicate that the element is interactable at all. Didn't figure out what is the reason behind this "clickable" announcement. It seems to be screen reader related issue.

Best Regards,
Boyan

**Comment by TeodorTaushanov** [comment]
The issue is answered here https://github.com/SAP/ui5-webcomponents/issues/5601
