### ISSUE TITLE
TabContainer: `::part` support for header element

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#6035]
### **Feature Request Description**
Please add the `part` attribute to the header element of the TabContainer component.

https://github.com/SAP/ui5-webcomponents/blob/f1999bd231d97c65b87f0c4998a09f4a44685fe5/packages/main/src/TabContainer.hbs#L6-L9

### Context

When the TabContainer is used inside a container (e.g. the [ObjectPage](https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-objectpage--default-story)) and the responsive padding should be applied according to the container, we need to overwrite the internally used responsive padding as otherwise there will be discrepancies when e.g. a scrollbar is displayed.

#### Example:
In the ObjectPage implementation, we're setting the padding of the header and content area according to the width of the component, but the TabContainer sets the padding according to its own width. So when a scrollbar is displayed, the header and content section are taking that scrollbar into account, but the TabContainer doesn't, which results in different breakpoints for the padding. (To be more specific, the breakpoints are 0.75rem (12px in this case) apart which is the width of the scrollbar)

<img width="601" alt="image" src="https://user-images.githubusercontent.com/9749730/201655216-12f691b1-240f-4385-8fd0-6c2064bb145e.png">

### **Proposed Alternatives**
Currently we're using `addCustomCSS` to adjust the padding of the header of the TabContainer, but since this is not recommended we would like to use the part pseudo element.

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: UI5 Web Components for React

**Comment by ilhan007** [comment]
Hi @Lukas742 the part is introduced and will be included in the next releases (1.21.0 start of Jan)
