### ISSUE TITLE
Avatar: Icon does not render

### ISSUE THREAD

**Issue by C3ntraX** [SAP/ui5-webcomponents#6043]
**Describe the bug**
The icon property does not work anymore in version 1.9.1 (maybe earlier)

Could you provide a hotfix?

**Isolated Example**
https://codesandbox.io/s/vigilant-kare-6tpmyy?file=/package.json

**To Reproduce**

**Expected behavior**

**Screenshots**

**UI5 Web Components for React Information**
`@ui5/webcomponents` version:
`@ui5/webcomponents-react` version:
Operating System:
Browser:

**Additional context**

**Comment by dobrinyonkov** [comment]
Hi @C3ntraX,

you need to import the icons module as described here: 
https://sap.github.io/ui5-webcomponents/playground/getting-started/using-icons/

For example, adding `import "@ui5/webcomponents-icons/dist/AllIcons.js";` to the `index.js` file fixes your issue.

Best Regards,
Dobrin

**Comment by C3ntraX** [comment]
Hello @dobrinyonkov @ilhan007,

No this is not required anymore. I can import the icons separat as describred in #5122
This is also due to prevent the import of all icons in my webapp to reduce the bundlesize.

You have forgot to consider this in your new implementations?

**Comment by C3ntraX** [comment]
This is also not documented that you have to use `import "@ui5/webcomponents-icons/dist/AllIcons.js";`

`Important: It is strongly recommended that you only import the icons that your app is going to use. This will keep your bundle small. Generally, importing all icons is required only if you do not know in advance which icons you are going to need.`

**Comment by dobrinyonkov** [comment]
Hi @SAP/ui5-webcomponents-topic-p,

The avatar fallbacks to the default icon "employee" because it check for valid intitials even when initials are not set.
Perhaps, the check and the fallback should be ommitted if no initials are currently set.

In addition, we should make sure the "employee" icon is imported when we fallback to it, but that is not the casue for this issue.

Kind Regards,
Dobrin
