### ISSUE TITLE
Breadcrumbs: Text not vertically centered

### ISSUE THREAD

**Issue by ej612** [SAP/ui5-webcomponents#6047]
**Describe the bug**
Text on a BreadcrumbsItem isn't vertically centered, due to a `margin: 0px 0px 0.5rem;` style applied to the following element:
`<nav class="ui5-breadcrumbs-root" aria-label="Breadcrumb Trail">`

Is this the intended behavior? I was going to override the padding on my end, but thought this might be a bug.

**Screenshots**
![image](https://user-images.githubusercontent.com/110408767/201951435-e0914746-db65-451c-8dae-30860850a9a5.png)

**Isolated Example**
I have created a [sandbox](https://codesandbox.io/s/elegant-dhawan-3zczrb?file=/src/App.js).

**Expected behavior**
I would expect the text to be vertically centered, especially when there's a vertically-centered "delete" button right next to it.

Thanks a lot in advance!

**Comment by dobrinyonkov** [comment]
Hi @SAP/ui5-webcomponents-topic-p,

the breadcrumbs has margin bottom set to its root element. Could you please check with VD spec if that is expected?

**Note**: @ej612 the StandardListItem is meant to be used with only text content slotted inside the default slot. For custom content, the CustomListItem should be used. Its slot accepts and renders any type of html elements.

Kind Regards,
Dobrin

**Comment by PetyaMarkovaBogdanova** [comment]
Hi @ej612 ,
apologies for the delayed answer!
I checked with our VD designers and they agreed that the margin-bottom property of ui5-breadcrumbs is originally
designed to be 0.5rem for Belize theme and it is expected to not be different for Quartz and Horizon themes. Now the specs for the last ones are also updated.
I suggest you overwrite it on application level, when the ui5-breadcrumbs is being used in that configuration.
Best regards,
Petya Markova.
(UI5 Web Components developer)
