### ISSUE TITLE
MultiComboBox: Unable to delete token wider than input filed

### ISSUE THREAD

**Issue by MadSandwich** [SAP/ui5-webcomponents#6048]
**Describe the bug**
Unable to delete option if it's wide more than width of the frame

**Isolated Example**
*Code example - [codesandbox](https://codesandbox.io/s/charming-darkness-r98pgn?file=/src/App.js).*

**To Reproduce**
1. Add 'Very long name token' option to MultiComboBox
2. Try to delete added option

**Expected behavior**
Option can be deleted

**Screenshots**
![UZYjk1ioh8](https://user-images.githubusercontent.com/57759145/201982782-ad244a1f-0030-470e-a927-633db4f1a23a.gif)

**UI5 Web Components for React Information**
  MultiComboBox,
  MultiComboBoxGroupItem,
  MultiComboBoxItem,
Operating System:
Browser: chrome - 107.0.5304.107 (Official Build) (64-bit)

**Comment by dobrinyonkov** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

Could you please have a look into this issue?
Tokens wider than the width of the input can't be deleted with the mouse.

Kind Regards,
Dobrin
