### ISSUE TITLE
SF_ACC ui5-dialog Items are not focusable with keyboard in the dialog

### ISSUE THREAD

**Issue by bonniegso** [SAP/ui5-webcomponents#6066]
### **Bug Description**
In certain cases, DOM elements may be added dynamically to the dialogs that do not follow the order of "header", "content" and "footer". In such cases, focusable items such as buttons are left out of the focus loop in the dialog when they are defined before the header slot.

This functionality is required for ACC-270 - Full Input Channel Support (Keyboard, Mouse, Touch).

### **Expected Behavior**
It is our expectation that any focusable elements added to the dialog, regardless of what order they are placed in, should be included in the focus loop.

### **Steps to Reproduce**
1. Go to 'https://js-uctucd.stackblitz.io'
2. With your keyboard, open the dialog
3. Tab through the elements
4. Observe that the button at the top of the dialog is not focusable via keyboard

### **Isolated Example**
https://stackblitz.com/edit/js-uctucd

### **Context**
- UI5 Web Components version: 1.8.0
- OS/Platform: MacOS Monterey
- Browser: Google Chrome Version 106.0.5249.119
- Affected component: ui5-dialog

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

Ideally, we would like the fix in the next release of ui5-webcomponents v1.9.0.

### **Stakeholder Info** (if applicable)

- Organization: SAP SuccessFactors
- Business impact: Accessibility

**Comment by dobrinyonkov** [comment]
Hello @SAP/ui5-webcomponents-topic-rd,

any focusable elements added above the dialog header, don't receive focus when dialog is opened and tab order still starts from the header.

Could you please look into this issue?

Kind Regards,
Dobrin

**Comment by dobrinyonkov** [comment]
Hi @bonniegso,

The button is still rendered below the header. If you move it below the header slot it will still look the same and focus handling will work as expected. 
Could you please share more information about the use case and why is it necessary to define it above the header slot?

Kind Regards,
Dobrin

**Comment by gmkv** [comment]
Hi @bonniegso 
We will address this issue with an internal backlog item, reference 2929. 
For the time being, to avoid this bug today, define the markup for your header slot at the ui5-dialog component, before any other elements. Likewise for the footer, defined its slot at the very end of the markup for the ui5-dialog.
```html
<ui5-dialog id="draggable-dialog" accessible-name="Draggable" draggable>
	<div slot="header">Header</div>

	<p>Content</p>

	<div slot="footer">Footer</div>
</ui5-dialog>
```

**Comment by LidiyaGeorgieva** [comment]
Issue is fixed with the following pull request: https://github.com/SAP/ui5-webcomponents/pull/6388
