### ISSUE TITLE
[SF_ACC][1.8.0][Wizard] Steps are overlapping

### ISSUE THREAD

**Issue by i323808** [SAP/ui5-webcomponents#6067]
### **Bug Description**
Steps of Wizard are overlapping on small screens.
We found a workaround that is adding `overflow-x: clip` to `.ui5-wiz-step-root`, but the visual focus outline will be partial.

### **Expected Behavior**
Steps of Wizard should not overlap on any size screen.

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/Wizard/
2. Shrink the screen
3. Steps of Wizard are overlapping

### **Isolated Example**
https://sap.github.io/ui5-webcomponents/playground/components/Wizard/

### **Context**
- UI5 Web Components version: 1.8.0
- OS/Platform: macOS Monterey
- Browser: Chrome Version 106.0.5249.119 (Official Build) (x86_64)
- Affected component: Wizard

### **Log Output / Stack Trace / Screenshots**
<img width="684" alt="wizard_steps_overlap" src="https://user-images.githubusercontent.com/30744017/202609352-538b5db2-b6c9-49e6-b96f-f3e793ccfd68.png">

<img width="1064" alt="wizard_steps_outline" src="https://user-images.githubusercontent.com/30744017/202610034-869c2d3b-438d-4b81-b7c8-49bae10cbe56.png">

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by dobrinyonkov** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

this issue can be reproduced in the playground:
https://sap.github.io/ui5-webcomponents/main/playground/components/Wizard/

When the screen width is resized and shrunk, the steps in the Wizard are cut before they overlap in the popover.

Could you please look into this issue?

Kind Regards,
Dobrin

**Comment by hristop** [comment]
Hi,

As the steps are overlapping while resizing by just a small amount, we are considering this as visual issue and not an accessibility one, thus lowering the priority.

Best Regards,
Hristo
