### ISSUE TITLE
Input: with suggestion component in Horizon theme do not meet minimum of 4.5:1 CC in default and focused states.

### ISSUE THREAD

**Issue by sleric1024** [SAP/ui5-webcomponents#6068]
**Describe the bug**
Input with suggestion component in Horizon theme do not meet minimum of 4.5:1 CC in default and focused states.

Input with Suggestion component

- Icons in the drop down fail to meet 4.5:1 CC in both default and focused states
- Outline fails to meet 4.5:1 against the light blue color when suggestion options are in focused state

**Isolated Example**
Input
https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-input--with-suggestion-item

**Expected behavior**
Icons and visual focus outline are expected to meet minimum of 4.5:1 CC in default and focused states.
It may also occurs in other component as well.
UI5 Control: https://ui5.sap.com/#/entity/sap.m.Select/sample/sap.m.sample.SelectWithIcons
<img width="939" alt="image" src="https://user-images.githubusercontent.com/5724592/202715515-456a3d29-cba9-4702-a9b0-2e1d9ad625db.png">

**Additional context**
Dear colleague, I am from SAP Successfactors, currently we are fixing a11y issue for b2211 release, and the issues we reported by central a11y team.

**Comment by dobrinyonkov** [comment]
Hello @sleric1024, 

those icons are considered purely decorative. They have `aria-hiden="true"` and `role="presentation"`, therefore according to our accessibility standard they are included in the list of exceptions for ACC-261 - Minimum Contrast.

```
No minimum contrast/high contrast is required for texts, icons and visual details that are

- part of a disabled component of the user interface
- purely decorative
- logotype
- incidental to the main focus of an image or video.
```

Kind Regards,
Dobrin

**Comment by anuvenkatesh1** [comment]
Hi @dobrinyonkov 
In the context of our page, the icons used are "not decorative". They convey a meaning. Please see screenshot below
![image](https://user-images.githubusercontent.com/32471459/203103738-e0b97151-f360-45c7-976b-233ecf8203a6.png)

The "history", "filter" icons etc used here convey a meaning that user can search "from history", or "filter by" etc. Could you please reopen the ticket and consider this example where these icons are meaningful and must meet CC.

Thanks.
