### ISSUE TITLE
[SF] Add value-help-only mode to Input and Multi Input

### ISSUE THREAD

**Issue by QiuranHu** [SAP/ui5-webcomponents#6070]
### **Feature Request Description**
When we use Input and Multi Input with value help dialog, currently there is no way to make the native input box read-only and keep the style of an editable input. However, our use case requires user to select from list fetched from backend (data can be huge). So we need a value-help-only mode to set the native input box to read-only mode and only allow user to select through the value help dialog.

The value-help-only option is described in fiori design documentation. (https://experience.sap.com/fiori-design-web/input-field/#value-help)
![image](https://user-images.githubusercontent.com/55808904/202993024-2d983ced-60af-4205-85dc-8ee515da1684.png)

The value-help-only option is implemented in UI5. (https://sapui5.hana.ondemand.com/#/entity/sap.m.Input/sample/sap.m.sample.InputStates)
![image](https://user-images.githubusercontent.com/55808904/202993914-42bdb271-3be6-4831-abe1-2caaa644812e.png)

### **Proposed Solution**
Add a property to set the Input and Multi Input to be in value-help-only mode.

### **Proposed Alternatives**
If possible, let the developer be able to choose whether to show the value help dialog when the user clicks the input box. Because one of our use case needs to display a error message in the input box. In this case, when the user clicks the input box, we want to show the error message instead of opening the value help dialog.

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: SAP SuccessFactors
- Business impact: The Input and Multi Input with value help dialog will be used in our production code.

**Comment by niyap** [comment]
Hello @QiuranHu,

Duplicated with https://github.com/SAP/ui5-webcomponents/issues/5045 and https://github.com/SAP/ui5-webcomponents/issues/5245
Please check the comments for more details.
The feature is against usability and accessibility, so we cannot accept and implement it.

Kind Regards,
Niya
