### ISSUE TITLE
SideNavigation: onClick/OnAuxClick doesn't expose clicked item

### ISSUE THREAD

**Issue by tiagoapmartins** [SAP/ui5-webcomponents#6074]
**Describe the bug**
When listening to the onSelectionChange I am able to get the clicked item through event.detail.item and then I can access the dataset properties. However the onAuxClick and onClick event , I don't see a clear way to get the clicked item.

**Isolated Example**
[codesandbox](https://codesandbox.io/s/great-moon-ql8l9f?file=/src/App.js).

**Expected behavior**
I would get access to the event.detail.item the same as onSelectionChange.
This way I would be able to provide a way for users to open the clicked page in a new tab.

**UI5 Web Components for React Information**
`@ui5/webcomponents` version:  1.8.0
`@ui5/webcomponents-react` version:  1.3.1
Operating System: Windows 10
Browser: Chrome 107.0.5304.107

**Comment by niyap** [comment]
Hello @tiagoapmartins,

Actually, the only event defined for the SideNavigation component is `selection-change`. The `click` event comes from the browser and it is expected to be called the same way as it is called on native HTML element.

Kind Regards,
Niya
