### ISSUE TITLE
Research: base APIs (written in Typescript) used in components

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents#6080]
### **Description**
Research base APIs (written in Typescript) used in components to check if we miss use cases and if new types, interfaces should be created or changed.

"base" package APIs used in components to check:
- [x] ItemNavigation - (new interface Tabbable has been introduced, and components subject to item navigation must implement it - f.e. the BreadcrumbsItem, ProductSwitchItem, etc. - see this [PR](https://github.com/SAP/ui5-webcomponents/pull/6082), we made _getCurrentItem to return HTMLElement | undefined to simplify the return type) [PR](https://github.com/SAP/ui5-webcomponents/pull/6099)

- [x] I18nBundle - (fix return type of getI18nBundle and getI18nBundleSync to Promise {I18nBundle} and I18nBundle respectively - see this [PR](https://github.com/SAP/ui5-webcomponents/pull/6082))

- [x] AriaLabelHelper - (Checked in Link and Input for both public methods - getEffectiveAriaLabelText, getAssociatedLabelForTexts. It works as expected.)

- [x] Device - (all types except isOS return boolean type. Main usage of this util is in expressions, nevertheless "boolean" type of iOS is now ensured with this [fix](https://github.com/SAP/ui5-webcomponents/pull/6098) )

- [x] InvisibleMessage  - ("announce" method is checked in Select and Combobox, works with small change to use InvisibleMessageMode.Polite instead of directly passing "Polite")

- [x] TabbableElements - (checked in table and seems okey)

- [x] FocusableElements - Stoyan - (checked in the Popups, Dialog and Wizard and seems fine)
- - Added type `FocusableElementPromise` to `FocusableElements.ts`, and made `startFromContainer` param optional. 
( check [this PR](https://github.com/SAP/ui5-webcomponents/pull/6102))

- [x] PopupUtils - (checked in Popup and Popover and types seem fine)
- - PopupUtils#isClickInRect checked
- - PopupUtils#getNextZIndex checked
- - PopupUtils#getCurrentZIndex checked
- - PopupUtils#getFocusedElement checked
- - PopupUtils#getClosedPopupParent checked

- [x] locale/getLocale.js - (it's used together with getCachedLocaleDataInstance from @ui5/webcomponents-localization
and to completely verify it, we need to work on the localization package as well.

- [x] asset-registries/LocaleData (checked in DataComponentBase and TimePickerBase, no changes needed)

- [x] FormatSettings#getFirstDayOfWeek (checked in DayPicker, it has good return type, no changes needed)

- [x] isDefaultSlotProvided - (checked in Badge and Butonn and it seems fine, will provide return type of boolean)

- [x] ScrollEnablement - (Tested in Tokenizer and Carousel. Generic types should be removed from ScrollEnablement class because generic type is assigned to static field in the class and they can mismatch with the original type) https://github.com/SAP/ui5-webcomponents/pull/6115

- [x] ColorConversion - (Tested in ColorPicker and nothing was found. Just some exports and return types are adjusted [PR](https://github.com/SAP/ui5-webcomponents/pull/6112) 

- [x] debounce - (checked in table and seems okey)

- [x] slideDown, slideUp - Stoyan ( checked in TabContainer and Panel, no problems at all )

- [x] debounce, isElementInView - (checked in table and seems okey)

- [x] ManagedStyles - ( checked in Popup and seems okay );

- [x] MediaRange - Stoyan
- - `getCurrentRange` now always returns a result, because it fallbacks to the default `rangeSet`, previously it was returning `null`;
- - `initRangeSet` method now expects 2 params, instead of 3.
- - We completely changed the usage of the `initRangeSet`. For reference [check this PR](https://github.com/SAP/ui5-webcomponents/pull/6120)

- [X] getSlottedNodes (the "this" parameter "this: Record<string, Array<SlotValue>>" has been removed as it does not match with the callee "this", e.g. the UI5Element - see https://github.com/SAP/ui5-webcomponents/pull/6119)

- [x] delegate/ResizeHandler - (Checked in List and works okey)

- [ ] features/F6Navigation

- [x] config/AnimationMode

- [x] asset-registries/Illustrations - 
- - Migrated the `ui5-illustrated-message` component to TS.
- - Changed types, in the IllustrationProperties type.
- - Small refactor of `onBeforeRendering()`. For more check - [this PR](https://github.com/SAP/ui5-webcomponents/pull/6195)

- [x] Keys - Added explicit return type (https://github.com/SAP/ui5-webcomponents/pull/6130)

- [x] FeaturesRegistry

- [x] Render

- [x] util/getFileExtension

- [x] util/clamp

- [x] locale/getLocale

- [x] config/CalendarType

- [ ] util/Caret - Nayden

- [x] util/getActiveElement

- [x] util/getEffectiveContentDensity

- [x] renderer/executeTemplate

- [x] asset-registries/Icons

- [x] util/getEffectiveScrollbarStyle - (Checked in List and works okey)

- [x] util/getNormalizedTarget -(Checked in List and works okey)

- [x] config/Theme

**Comment by nnaydenow** [comment]
Integer type can't be used in Math object's functions because of incorrect type.
