### ISSUE TITLE
Feature Request: use decorators to develop UI5 Web Components

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents#6081]
### **Feature Request Description**
As TS is supported in UI5 Web Components, we would like to incorporate decorators for handling metadata - declaring properties, slots, events, etc., when developing web components. We will keep supporting the old format for everyone using vanilla JS for development, but also allow decorators when using TS.

### **Proposed Solution**
```ts
customElement("ui5-label")
class Label extends UI5Element {

    @property({ type: String })
    for = "";

    @property({ type: WrappingType, defaultValue: WrappingType.None })
    wrappingType = WrappingType.None;
	
}
```

Before:

```js
const metadata = {
	tag: "ui5-label",
	properties:  {
		 wrappingType: {
			type: WrappingType,
			defaultValue: WrappingType.None,
		},

		"for": {
			type: String,
		},
	}
};

class Label extends UI5Element {
    static get metadata() {
	return metadata;
    }
}
```

**Comment by C3ntraX** [comment]
Take a look.

Decorators are not future proof.

https://google.github.io/styleguide/tsguide.html#decorators

MobX moved away from decorators because of this.

**Comment by pskelin** [comment]
Decorators (as well as typescript support) is not mandatory when authoring a package. The metadata can still be described as a JSON, decorators just make authoring web components easier.

If we take this thinking to the extreme, then we should also stop using typescript as it is also not a browser standard. 

I think for our usage they are safe to use. We use them in the source code, but typescript transpiles them to JS function calls in the code we ship to NPM. If we decide to get rid of decorators in the code in the future, this will not be an incompatible change for the code we ship.

Finally in the TS guide you linked (thanks for sharing, will definitely look in detail), there is an exception for using decorators
```
Only use the decorators defined by frameworks:

Angular (e.g. @Component, @NgModule, etc.)
Polymer (e.g. @property)
```

Our usage falls in this category, so I don't see a reason against the way we use them.

**Comment by C3ntraX** [comment]
Yes, okay. 
This topic just reminded me that some frameworks have refrained from doing this and wanted to draw your attention to the fact that decorators are still experimental for TypeScript. 

I don't think extreme and that has nothing to do with TypeScript itself or the browser standard. My only concern was that if something is used that isn't future-proof, it can lead to a lot of extra work if it needs to be undone.

Btw. I like the ways you are going. Using more TypeScript is good. Its a way to prevent errors before they happen and thats really good. This is also one reason why my team decided to move away from the classic OpenUI5.

**Comment by ilhan007** [comment]
Closed with: https://github.com/SAP/ui5-webcomponents/pull/6072
