### ISSUE TITLE
List: Focus issue Navigating back to list

### ISSUE THREAD

**Issue by lateefsofi** [SAP/ui5-webcomponents#6086]
**Describe the bug**
We have 2 components and we have to render either 1 conditionally. In Component 1 we have list of items with details button. When user clicks that button, user will see Component 2. From Component 2, user can press back button to see Component 1.
We are able to move focus to correct element while navigating between Component 1 and Component 2 but there is 1 problem.
Generally we use arrow keys to navigate between List items, when there is any focusable element in the list(in our case) button, "Tab" key will move focus to button and from button "Shift + Tab" will move focus back to list item.
Now the problem is when we focus back from Component 2 to Component 1 button, "Shift + Tab" is moving focus to previous List item button rather than List item.

**Isolated Example**
https://codesandbox.io/s/quizzical-rumple-vefdry

**To Reproduce**
1. Go to https://codesandbox.io/s/quizzical-rumple-vefdry
2. Move down to list items, with arrow keys and press tab to move focus to right arrow button
3. Press enter, you will see "Focus Back to List" button
4. Press enter on "Focus Back to List" button, it will move focus to last focusable element in the list
5. Press "Shift + Tab", focus will move to previous list item button rather than Previous List item

**Expected behavior**
On press "Shift + Tab" focus should move to List Item rather than List Item button.

**Screenshots**
NA

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.8.0
`@ui5/webcomponents-react` version: 1.3.1
Operating System: Windows
Browser: Chrome

**Additional context**
NA

**Comment by niyap** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

Could you please check the issue?
It could be easily reproduced with the sample provided following the description by the reporter.

Kind Regards,
Niya
