### ISSUE TITLE
Popover not getting closed when focus is lost 

### ISSUE THREAD

**Issue by MapTo0** [SAP/ui5-webcomponents#6087]
### **Bug Description**
The popover is not getting closed when focus is moved to another window (e.g clicking in an iframe).

### **Expected Behavior**
Popover gets closed when focus is lost

### **Steps to Reproduce**
URL: https://codesandbox.io/s/red-meadow-2uip40

1. Open the Popover
2. Click on the iframe => not getting closed
3. Click somewhere else on the page => popover is closed.

### **Isolated Example**
URL: https://codesandbox.io/s/red-meadow-2uip40

### **Context**
- UI5 Web Components version: latest
- OS/Platform: any
- Browser: any
- Affected component: `ui5-popover` and all static area templates using popover (select, input, etc)

### **Log Output / Stack Trace / Screenshots**
```
{...}
```
### **Priority**
- [ ] Low
- [] Medium
- [x ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by niyap** [comment]
Hello @SAP/ui5-webcomponents-topic-rd,

Could you please look over the issue?

Kind Regards,
Niya
