### ISSUE TITLE
[SF][ResponsivePopover][1.9.1][Expect fixed in 1.11.0]ResponsivePopover blocked by mask when it is opened inside Dialog under mobile mode

### ISSUE THREAD

**Issue by ksblklu** [SAP/ui5-webcomponents#6089]
### **Bug Description**
ResponsivePopover blocked by mask when it is opened inside Dialog under mobile mode, and can't be closed independently.

### **Expected Behavior**
Under mobile mode, ResponsivePopover opened inside Dialog not blocked and could be closed correctly.

### **Steps to Reproduce**
1. Go to https://codesandbox.io/embed/interesting-firefly-6600uj
2. Switch browser to mobile mode
<img width="506" alt="image" src="https://user-images.githubusercontent.com/27538066/203712637-000d396e-68c2-4658-a769-fa1c1b3875db.png">

3. Click "open dialog" button, then click on "show popover button"
<img width="473" alt="image" src="https://user-images.githubusercontent.com/27538066/203713998-93be2de4-87f9-49a8-bf05-d9f3ca79c444.png">

4. See there is a grey mask blocking the whole ResponsivePopover dialog, and the ResponsivePopover cannot be closed by clicking "X" icon on the top-right.
<img width="451" alt="image" src="https://user-images.githubusercontent.com/27538066/203713875-db1a86ee-1c7d-4be8-8836-218586dbafa2.png">

### **Context**
- UI5 Web Components version: 1.9.1
- OS/Platform: Mac OS
- Browser: Chrome
- Affected component: ResponsivePopover

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** 

- Organization: SuccessFactors
- Business impact: {...}

**Comment by niyap** [comment]
Hello @SAP/ui5-webcomponents-topic-rd,

Could you please check the issue?
With the sample and description provided, I was able to reproduce the issue using Xcode Simulator.

Kind Regards,
Niya

**Comment by gmkv** [comment]
Hi @ksblklu 
We investigated a similar reported issue #6344 and concluded that it's best to avoid nesting Popups within one another.
Please see my [comment there](https://github.com/SAP/ui5-webcomponents/issues/6344#issuecomment-1408691573).
You won't lose any semantics or encounter accessibility concerns if you render the Popups on the same level, not nested.

To achieve this use in React, use the [Portals API](https://beta.reactjs.org/reference/react-dom/createPortal) when opening a Dialog or a Popover. 
I updated the docs to further advise this with #6384.

**Comment by ksblklu** [comment]
Hi @gmkv, thanks for the information.
