### ISSUE TITLE
[SF][Feature Request][Popover][Expected in ver.1.11.0]Enable changing the role of the Popover component

### ISSUE THREAD

**Issue by ksblklu** [SAP/ui5-webcomponents#6090]
### **Feature Request Description**
Hi team
Now the Popover component has default `role=dialog` internally. Since the popover can also contain actionable/non-actionable elements, settled "role=dialog" to `Popover` seems not be the best practice, `Popover` may also contain a list of buttons and should have a "menu" role.(See discussion [here](https://github.com/SAP/ui5-webcomponents-react/issues/3793)). So can we have `accessibleRole` property of `Popover` component, to customize the role of `Popover` and its derived components like `ResponsivePopover` etc. ?

### **Proposed Solution**
Enable changing the accessibleRole of Popover component.

### **Additional Context**
Add other context or screenshots related to the feature request here.

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: SuccesssFactors
- Business impact: {...}

**Comment by niyap** [comment]
Hello @SAP/ui5-webcomponents-topic-rd,

Could you please look at that feature request?

Thank you in advance!

Kind Regards,
Niya

**Comment by TeodorTaushanov** [comment]
_Popover may also contain a list of buttons and should have a "menu" role._

- The Popover cannot have buttons inside if its role is a "menu". If the role of the Popover is a "menu", it must contains elements with role="menuitem". 

https://www.w3.org/WAI/ARIA/apg/example-index/menu-button/menu-button-actions-active-descendant.html

In the overflow toolbar the correct role of the popover is "dialog".

Best,
Teo
