### ISSUE TITLE
Input: When selecting a suggestion, changing the query and reselecting the same SuggestionItem the input gets cleared

### ISSUE THREAD

**Issue by schempil** [SAP/ui5-webcomponents#6091]
**Describe the bug**
When using the Input component with suggestions based on the query in the input, I can select the suggestion, but after changing the query and selecting the same SuggestionItem the value in the input gets cleared.

**Isolated Example**
[sandbox](https://codesandbox.io/s/nameless-firefly-rb0m1e)

**To Reproduce**
See description in sandbox.

**Expected behavior**
I expect to show the correct value all the time after a SuggestionItem has been selected.

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.9.1
`@ui5/webcomponents-react` version: 1.5.0
Operating System: macOs Ventura 13.0.1
Browser: Google Chrome Version 107.0.5304.110 (Official Build) (arm64)

**Comment by kskondov** [comment]
Hello @SAP/ui5-webcomponents-topic-rl the issue can be reproduced in the provided sandbox. Can you please take a look at why the value of the input gets cleared.

Best Regards,
Konstantin
