### ISSUE TITLE
Wrong icon for 'fx'

### ISSUE THREAD

**Issue by ej612** [SAP/ui5-webcomponents#6103]
### **Bug Description**
According to the [UI5 Icon Explorer](https://sapui5.hana.ondemand.com/sdk/test-resources/sap/m/demokit/iconExplorer/webapp/index.html#/overview/SAP-icons/?tab=grid&icon=fx&search=fx), the symbol for 'fx' should be the following:

![Screen Shot 2022-11-28 at 12 07 49](https://user-images.githubusercontent.com/110408767/204263058-8b5278e8-5478-4377-b2e0-0f41072091d5.png)

However, the code
```
import "@ui5/webcomponents-icons/dist/fx";
<Icon name='fx'/>
```
produces the following icon:

![Screen Shot 2022-11-28 at 12 11 17](https://user-images.githubusercontent.com/110408767/204263697-f1c52b0e-76a7-438e-a7f5-928fb5bcf935.png)

Thanks a lot in advance!

### **Priority**
- [x] Low
- [ ] Medium
- [ ] High
- [ ] Very High

**Comment by pskelin** [comment]
The icons are now theme dependent. What you are looking at in the Icon Explorer is the `sap_horizon` theme. If you switch to `sap_fiori_3`, you will get the fx icon there as well:

https://sapui5.hana.ondemand.com/sdk/test-resources/sap/m/demokit/iconExplorer/webapp/index.html?sap-ui-theme=sap_fiori_3#/overview/SAP-icons/?tab=grid&icon=fx&search=fx

You need to set the theme in web components to `sap_horizon`, try the URL parameter `?sap-ui-theme=sap_horizon` or use the configuration options from the docs
https://github.com/SAP/ui5-webcomponents/blob/main/docs/2-advanced/01-configuration.md
