### ISSUE TITLE
SF_ACC - UI5-Tree keyboard access - component loses focus on expand/collapse

### ISSUE THREAD

**Issue by don-obrien** [SAP/ui5-webcomponents#6109]
### **Bug Description**
Ui5-Tree keyboard access
I have marked this as high priority because it relates to a customer issue, and also because the component is not accessible via keyboard without a painful workaround.  In LMS, this is used in a core feature, and needs addressing with priority.

when we press right/left arrows to expand/collapse a tree node, the focus is lost.   
in SAPUI5 it works fine, but in web component, the focus jumps away.  You have to navigate back to the tree to move up and down, and every time you expand/collapse, the focus jumps away from the tree node.
In some cases, it jumps outside the node, and In some cases, the cursor is still on the node, but the node is not selected anymore.
The issue can be see in the WC playground:
https://sap.github.io/ui5-webcomponents/playground/components/Tree/

This issue does not exist on the SAPUI5 Tree component.  Only found on WC version in v1.0.0-rc.8

### **Expected Behavior**
When I press the right/left arrow key to expand/collapse a tree node, my focus should remain on the tree node:.   
e.g. one example: after pressing right arrow to expand a node, user should be able to press the left arrow key and see the node collapse again
e.g. another example, after pressing right arrow to expand a node, user should be able to traverse the tree up and down without losing focus on the tree

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/Tree/
2. tab to the tree in the Basic Tree example and the focus will be on the 1st tree node
3. press the right arrow to expand the tree node
4. once it has expanded, Press the left arrow to collapse the node
5. ACTUAL BEHAVIOR, the tree node does not collapse.  focus is no longer on the tree node.  
6. PART 2:  Tab away from the tree and back again to focus on the expanded node.
7. Press the left arrow to collapse the focused node (now it will collapse)
8. Now I would expect the focus to remain on that node, but instead it is moved to the text "Basic Tree" outside the tree.

### **Isolated Example**
See above:
https://sap.github.io/ui5-webcomponents/playground/components/Tree/
### **Context**
- UI5 Web Components version: {v1.0.0-rc.8}
- OS/Platform: {windows}
- Browser: {chrome}
- Affected component: {UI5-Tree}

### **Log Output / Stack Trace / Screenshots**
```
{...}
```
### **Priority**
- [ ] Low
- [] Medium
- [x] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {SFSF}
- Business impact: {Customer issue, will be linked back to a JIRA for reference}

**Comment by dimovpetar** [comment]
Hello @don-obrien ,

I am not able to reproduce the issues on this page https://sap.github.io/ui5-webcomponents/playground/components/Tree/. The first node of the "Basic Tree" sample is already expanded. When I expand/collapse any node with left or right arrow the focus remains on that node.
I am testing on Window 10, Google Chrome 1.107.
Please provide more details.

Best regards,
Petar

**Comment by don-obrien** [comment]
Lukas figured out that it was a feature in chrome called carat browsing (F7 accesses it).   After changing that mode, I was no longer able to reproduce it.
