### ISSUE TITLE
[ShellBarItem]: Press event naming convention

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents#611]
With the latest release, all `press` handlers got renamed and are now `click` events.
Is there any special reason why the `ui5-shellbar-item` is still firing the `press` event? Or should that be renamed as well?

In addition to that, the `ui5-icon` is also still firing `press`, but this is already captured in #435.

**Comment by ilhan007** [comment]
ui5-icon press event is internal, please don`t use it or rely on it.
ui5-shellbar-item press event is renamed to itemClick
