### ISSUE TITLE
Avatar: icon cannot be effective

### ISSUE THREAD

**Issue by sleric1024** [SAP/ui5-webcomponents#6110]
**Describe the bug**
More than one Avatar rendered in one time, the icon props can not be effective.

**Isolated Example**
https://codesandbox.io/s/sharp-hertz-1vff9m?file=/src/App.js

**Expected behavior**
Avatar with cancel icon should render cancel icon
Avatar with employee icon should render employee icon

**Screenshots**
<img width="900" alt="Screenshot 2022-11-29 at 10 48 33" src="https://user-images.githubusercontent.com/5724592/204426617-c60d30d0-d16b-4da7-b657-02677bbf2ace.png">

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.9.1
`@ui5/webcomponents-react` version: 1.4.1
Operating System: MacOS
Browser: Chrome

**Additional context**
I am a web engineer from Successfactors.

**Comment by Lukas742** [comment]
I just realized this is a duplicate. I'll link this issue and codeSandbox to the original issue and close this one.

Duplicate #6101

**Comment by sleric1024** [comment]
@Lukas742 , it seems that the fix about https://github.com/SAP/ui5-webcomponents/issues/6101  is not been released into the version of 1.9.3

**Comment by Lukas742** [comment]
Hello @sleric1024 

since there is no mention of this in the change log, I wouldn't expect it to have been released yet. For more information please ask a member of the UI5 Web Components team, as I am only part of the UI5 Web Components for React team.

**Comment by ilhan007** [comment]
Hi @sleric1024 it's not, we will have 1.10.0 release by the end of the month that will include it. Is there urgent matter that we need to consider.

ilhan

**Comment by sleric1024** [comment]
Thanks @Lukas742 & @ilhan007  for your reply.
No urgent from our side. I just remind this and ask for the detail. Not a blocking issue. Since we will have Chinese holiday then, so the time could be just good by the end of this month.
