### ISSUE TITLE
[SAP] [Accessibility] [ShellBar] : Additional information announced

### ISSUE THREAD

**Issue by vraguna** [SAP/ui5-webcomponents#6111]
**Describe the bug**
The accessibility tester of our application has raised an issue that when the profile (shell bar popover icon) button is clicked, the accessibility tool reads the text twice.

Here is the texts
[application-name] - Google Chrome
[application-name] - Google Chrome dialog

I have performed the accessibility test for the Shell Bar component (ShellBar with customizable ShellBarItem) in the https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-shellbar--with-customizable-shell-bar-item and was able to reproduce the same behavior.

The below text was announced twice when the shell bar pop-over button is clicked

layouts-floorplans-shellbar--with-customizable-shell-bar-item.operatorstorybook-Google Chrome
layouts-floorplans-shellbar--with-customizable-shell-bar-item.operatorstorybook-Google Chrome Dialog

**Steps to reproduce the behavior:**
Open the screen reader tool - JAWS 2022.2206.9 ILM
Open Google Chrome
Go to the corresponding [example in the docs](https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-shellbar--with-customizable-shell-bar-item)
Click on the "Add" icon

**Screenshots:**

![image](https://user-images.githubusercontent.com/42251879/204327642-9a62b5f0-ff88-467a-a4b2-73b91a945411.png)

Expected Behavior:
The expectation is that it should announce the text just once. Please confirm if this is the correct behavior.

**Comment by dimovpetar** [comment]
Hello @ui5-webcomponents-topic-rd,

This is popover with static content, announced by JAWS in Virtual PC Cursor mode.
You can use this example to reproduce it: https://codesandbox.io/s/shellbaritem-popover-forked-gpcilr?file=/src/App.js
JAWS output:

> Shell Bar BannerRegion
Unlabeled 1 Button
To activate press Enter.
**React App - Google Chrome**
**React App - Google Chrome** dialog
Hello there! 

Notice that the title of the page and the browser name are read out, and are read out twice.
I couldn't find such known issue in the popover's wiki.

Best regards,
Petar

**Comment by vraguna** [comment]
Thanks @Lukas742 for forwarding this to the appropriate team.

@dimovpetar: Thanks for providing the example. I am not sure why this couldn't be re-produced in the popover's wiki. However, the issue is anyhow identified and added in the "Maintenance -Topic RD". Please keep us updated on its progress.

Best regards,
Vinod Kumar

**Comment by vraguna** [comment]
@dimovpetar Please let me know, when the issue will be fixed and delivered?

**Comment by TeodorTaushanov** [comment]
Hi @vraguna,

This issue is because of 2 know JAWS issues:

-  `<head><title>Dialog sap.m</title></head>`
<title> is read out when we focus on a <div> with a role dialog

- The content of the dialog is read twice automatically.


Best,
Teo

**Comment by vraguna** [comment]
@TeodorTaushanov 
Thanks for your response. Since you have mentioned that the issue is because of 2 known JAWS issues, can you please provide more information on where do you find these issue are JAWS related and is there any solution proposed by the tool's maintenance team?
Best regards,
Vinod

**Comment by TeodorTaushanov** [comment]
@vraguna, we have a SAP internal page with a list of known screen reader issues.  These 2 particular issues are not yet reported to the tool's maintenance team.
