### ISSUE TITLE
[ui5-li] Listitem is not supporting anchor tag

### ISSUE THREAD

**Issue by pankajpandey01** [SAP/ui5-webcomponents#6121]
### **Bug Description**
Our requirement is to have shellbar menu items behaves like a link. 
MenuItems ui5-li was partially supporting anchor tag prior to v1.9,  although we had to override css to allow slotted content to take all ui5-li space. 

Addition of event.preventDefault()  in below commit is preventing the link's click behavior.
https://github.com/SAP/ui5-webcomponents/commit/ed1efccc2190512dbafbaffd76f88471c0f3467e#diff-e4ddb3f422d410c0929d358d7123cf2b99bdfe7f9815b7c7700469536c3ccc92R298

### **Expected Behavior**
ui5-li should support anchor tag.

### **Steps to Reproduce**
1. Go to isolated example

### **Isolated Example**
https://codesandbox.io/s/ui5-webcomponents-forked-5j8i6w

### **Context**
- UI5 Web Components version: {1.9.0}
- OS/Platform: {All}
- Browser: {All}
- Affected component: {ui5-li}

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {SuccessFactors}
- Business impact: {High. User can not navigate to different page}

**Comment by dimovpetar** [comment]
Hello @ui5-webcomponents-topic-rd,

After https://github.com/SAP/ui5-webcomponents/commit/ed1efccc2190512dbafbaffd76f88471c0f3467e `<a>` elements inside StandardListItem are no longer working. The fix was needed to prevent immediate close of a dialog, opened after Enter keydown on a list item.

Best regards,
Petar
