### ISSUE TITLE
Icon not available for models

### ISSUE THREAD

**Issue by rv97** [SAP/ui5-webcomponents#6124]
### **Bug Description**
Our team (LWV-SAP Analytics Cloud) uses ui5-webcomponents. But we are not able to find any proper icon for **Models** in the [Icon Explorer](https://sapui5.hana.ondemand.com/sdk/test-resources/sap/m/demokit/iconExplorer/webapp/index.html#). Orca uses the same icon in the case of models.

### **Isolated Example**
Image of the icon to look like.
https://sap-my.sharepoint.com/:i:/p/vignesh_r02/EYBg1xO1fMJAtQaXnIN6uGkBC5_-wxRgCiFBNCt7H9QL6g?e=34QqR0

### **Context**
- UI5 Web Components version: 1.6.0
- OS/Platform: Web
- Browser: Chrome
- Affected component: Icons

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - Medium
- Accessibility issue - High
- Functional issue - Low
- Visual issue - High

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SAP Analytics Cloud
- Business impact: High - Not able to give the proper representation to the user.

**Comment by dimovpetar** [comment]
Hello @SAP/ui5-webcomponents-core ,

I couldn't find such icon in the SAP icons, SAP Fiori Tools icons or SAP Business Suite icons.
Please evaluate this feature request.

Best regards,
Petar

**Comment by dimovpetar** [comment]
Hello @rv97 ,

This icon already exists. Its name is "database". See it in the Icon Explorer app https://sapui5.hana.ondemand.com/sdk/test-resources/sap/m/demokit/iconExplorer/webapp/index.html?sap-ui-theme=sap_fiori_3#/overview/SAP-icons/?search=database&icon=database
The icon has different look in Horizon themes.

Best regards,
Petar

**Comment by rv97** [comment]
@dimovpetar Thanks for the info!. Will check it out!
