### ISSUE TITLE
Add shadow parts or "readonly" property for `ui5-range-slider`

### ISSUE THREAD

**Issue by vladitasev** [SAP/ui5-webcomponents#6125]
This feature is demanded by Ariba. The range slider component should have read-only state.

Either:
A) Consult with the design team whether this feature makes sense as a standard property for the component
B) Add shadow parts, similarly to Slider, so that users can implement the readonly CSS themselves.

Regards,
Vladi

**Comment by vladitasev** [comment]
@SAP/ui5-webcomponents-topic-rl Could you please take this issue with priority? At least the shadow parts implementation would be trivial. 

Regards,
Vladi

**Comment by niyap** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

Both the sap.m.Slider and ui5-slider do not support not editable(readonly) state. We have to discuss whether it is expected to have such a state or to provide a way to the users to be able to achieve that from their side.

Kind Regards,
Niya
