### ISSUE TITLE
Dynamically show sub-menu with busy indicator

### ISSUE THREAD

**Issue by rv97** [SAP/ui5-webcomponents#6131]
### **Feature Request Description**
Our team (LWV-SAP Analytics Cloud) uses ui5-webcomponents. We have a situation where on click of a menuItem, we have to show a sub-menu which is dynamic in nature and until that is shown, a busy indicator needs to be displayed.
Let me explain in detail. 
1. When I click on a menu Item, an async call happens.
2. Until the async call is in progress, I need to show a busy indicator.
3. Once the async call is finished, I need to show the menu Items based on the result of the async call.

I tried to do the same with current Menu and MenuItem. But it seems to be behaving weirdly. You can find the current issue here.
https://sap-my.sharepoint.com/:v:/p/vignesh_r02/EVqrMufbaMlOlDrM4uZp3XUBL2exhmNHPu95VUzpR_IIDw?e=DHsBpY

### **Proposed Solution**
We need to have a way to show the sub menu items with the busy indicator first and then the menuItems dynamically. Like this.
https://sap-my.sharepoint.com/:v:/p/vignesh_r02/EXjtACkDM8NBgTMtKkSSd_IBlv7VZFrlUl-0gNl1N1jhEA?e=TqIcll

### **Proposed Alternatives**
We have tried adding the Busy Indicator inside the MenuItem. But it does seem to render at random places and does not re-render when the actual data comes.

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: SAP Analytics Cloud
- Business impact: Will not able to release the feature because it depends on this dynamic loading of sub-menu.

**Comment by rv97** [comment]
Hey @dimovpetar,

Whatever the code you shared seems to do a different thing. I could see a menu button and a busy indicator in the bottom. That is not what I want. Let me try to explain much more in detail.

Lets take an example.
1. I have a dropdown menu called "Tools". When I click on this a menu opens with three items. (A. Stories, B. Bookmarks, C. Filters).
2. The first sub-menu "Stories" has another sub-menu. When I click on that I shows me a sub-menu of list of stories to the right of it.
3. But I do not know what all stories are there in the beginning. I need to render them dynamically. Only when I click on the "Stories" sub-menu, an async call happens which gives me a list of stories. The number of stories can be different each time based on the call.
4. So, if a user clicks on the "Stories", until the async call is finished, it should a sub-menu with busy indicator and when the actual data has come, it should re-render them immediately.

The following link shows what's the expectation.
https://sap-my.sharepoint.com/:v:/p/vignesh_r02/EXjtACkDM8NBgTMtKkSSd_IBlv7VZFrlUl-0gNl1N1jhEA?e=TqIcll

In the above link, when I click on the "Open Saved Bookmarks", it shows another sub-menu to the right of it with a busy indicator when the async call is happening and when the data is there, it renders them automatically.

**Comment by NHristov-sap** [comment]
Hi @rv97 ,

I am lowering the priority to Medium as this is not something that can be classified as Very High.
It seems this is a feature request, but first I am going to discuss this with the responsible Product Owner, and then will update this issue.

Best Regards,
Nikolay Hristov

**Comment by rv97** [comment]
Hi @NHristov-sap,

Thanks for the reply. Yes I raised it as a feature request because I tried multiple options and also checked with the webcomponents team in the slack channel. There seems to be no existing solution for this.
The reason I gave it a Very High was this is an important feature for us and without this dynamic menu working, we would not be able to proceed. Can you try considering to increase the priority of this?

Regards,
Vignesh R

**Comment by scameron** [comment]
Hi @NHristov-sap, @dimovpetar, were you able to have a chance to discuss this feature request?  Does it seem like something you'd be able to add?

**Comment by kskondov** [comment]
Hello @SAP/ui5-webcomponents-topic-b, can you pleas take another look of this feature request.

**Comment by Abanindra** [comment]
Hi @petyabegovska Can you please confirm the availability of the fix in the UI5WC4R version 1.12.0 (released on 22nd March): https://github.com/SAP/ui5-webcomponents-react/compare/v1.11.3...v1.12.0

**Comment by Abanindra** [comment]
Hi @petyabegovska 
 
I can see that the issue has been moved to UI5WC4R version 1.13.0 which is due in April end. Please do let us know if this issue can ben ported in one of the fix version on top of 1.12?

**Comment by ilhan007** [comment]
Hello @Abanindra the strategy is to only downport big fixes, not features. To consume new features the applications need to upgrade the ui5wc version, in this case to 1.13.0, that will be produced 30Apr or short after this date (if we decide to include one or two additional fixes in the release).

**Comment by Abanindra** [comment]
Hi @ilhan007 Thanks for the update, but I don't see the final release build of 1.13.0 which was due on 30th April. Do you know when the final release build of 1.13.0 will be available?

**Comment by ilhan007** [comment]
There are few changes that we want to add in the release, but we expect to have it by Friday.

**Comment by Abanindra** [comment]
Hi @ilhan007 Thanks for the update. I have one more query - Does UI5WC deploy a UI5WC4R release at the same time which is compatible with the UI5WC version. For example when WC 1.13 is out this Friday, will there also be a new WC4R release which supports WC 1.13? If yes what would be the compatible version of UI5WC4R?

**Comment by ilhan007** [comment]
@Abanindra as UI5WC4R  it's maintained in different team,  different repository, the projects are not released together, usually the release of UI5WC4R is done within day or two offset, sometimes happens in the same day.

**Comment by rv97** [comment]
Hello @ilhan007 @dimovpetar. I tried the busy indicator change which has been implemented. When i set the `busy` to be true as part of the `MenuItem`, the busy indicator shows up after 1000ms delay.

I have an issue here:
I am not able to fire any calls on click of the menu item if it has sub-menu. On click of the menu item, there is no `onClick` or `onMouseEnter` or any such listeners that is getting called. The sub-menu appears immediately on the hover. My requirement is, on click of the sub-menu, i need to fire a call to the backend and until the call is happening, the busy indicator should be shown. Once the call is done, it should automatically populate the sub-menu with the data from the backend.

Am i missing something here. Can you tell me how to do it?

FYI @Abanindra

**Comment by scameron** [comment]
It was @unazko who worked on the original fix, so maybe he can give some guidance here about the question above regarding correct usage.

**Comment by Abanindra** [comment]
Hi @unazko @ilhan007 @petyabegovska, Appreciate if one of you can take a look and suggest how to invoke the feature. Without this we are kind of block here.

**Comment by scameron** [comment]
@Abanindra, we're already in direct contact with @unazko and he's helping us work through this.

**Comment by unazko** [comment]
Hi @scameron, @rv97 and colleagues,

As we've discussed there is no event currently fired on opening/before opening a sub-menu. As a result the application developers could not trigger a get request for a given sub-menu's menu item's. An event should be provided on opening a sub-menu. A possible solution would be to expose the
`ui5-before-open`  event for the sub-menus.

Best regareds,
Boyan

**Comment by rv97** [comment]
Hello @unazko ,

I was trying out the change for dynamically loading the menu items for prompts. Until last week the documentation was properly updated and i started trying it out. Yesterday when i was stuck and wanted to check the documentation, it has been removed from the documentation. Now there is no reference to the dynamically loading the menu. Is there a possibility that there is some known issues?

Documentation Link: https://sap.github.io/ui5-webcomponents/playground/components/Menu/

FYI @scameron @Abanindra @dimovpetar @ilhan007 

Regards,
Vignesh R
