### ISSUE TITLE
[ui5-shellbar]- search cancel button is not adapting to locale.

### ISSUE THREAD

**Issue by pankajpandey01** [SAP/ui5-webcomponents#6143]
### **Bug Description**
[ui5-shellbar]- search "cancel" button is not adapting to locale. 

### **Expected Behavior**
[ui5-shellbar]- search "cancel" button should be translated based on locale.

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/ShellBar/
2. Change locale of page to ‘de_DE’
3. Minimize screen to mobile size
4. Click on search icon

### **Context**
- UI5 Web Components version: {1.9}
- OS/Platform: {All}
- Browser: {All}
- Affected component: {ui5-shellbar}

### **Log Output / Stack Trace / Screenshots**

<img width="1098" alt="Screen Shot 2022-12-05 at 6 42 55 PM" src="https://user-images.githubusercontent.com/67934622/205797287-877a5822-8176-4a9e-838c-b9cef236afcd.png">

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {SuccessFactors}
- Business impact: {i18n is impacted. There is live customer issue on this. }

**Comment by NHristov-sap** [comment]
Hello @ui5-webcomponents-topic-p,

Please check if the cancel button of the search box inside Shell Bar should translate (on mobile), and if yes, why it is not translated.

Best Regards,
Nikolay Hristov
