### ISSUE TITLE
Dialog: wrong display of the bottom border of the header with high contrast themes

### ISSUE THREAD

**Issue by ehn-sap** [SAP/ui5-webcomponents#6150]
**Describe the bug**
Using a high contrast theme, the bottom border of the header is not complete.

**Isolated Example**
[Sandbox](https://codesandbox.io/s/dialog-with-splitter-quartz-high-contrast-black-lrismo?file=/src/App.tsx)

**To Reproduce**
1. Set a high contrast theme
2. Create a dialog
3. See that the bottom border of the header looks uncomplete

**Expected behavior**
The bottom border of the header should seem as large as the dialog

**Screenshots**
![header](https://user-images.githubusercontent.com/112404107/205999139-7fce0064-be2c-4c70-9e54-8faf1983cbf7.PNG)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.9.1
`@ui5/webcomponents-react` version: 1.5.0
Operating System: Win11
Browser: Chrome

**Additional context**
It seems all high contrast themes reveal this issue.

**Comment by NHristov-sap** [comment]
Hello @ui5-webcomponents-topic-rd,

Please take a look on this case. I have checked Bar VD specification and it has background set (as specified).
This is reproducible in all HC themes (Fiori 3 and Horizon).

Best Regards,
Nikolay Hristov

**Comment by ehn-sap** [comment]
Thanks @Lukas742 , removing the padding of the header, it looks good now.

**Comment by LidiyaGeorgieva** [comment]
Hello @SAP/ui5-webcomponents-topic-b 

After consultation with the designers (mail thread forwarded) the bottom border of the Bar in the Contrast themes should be 2px (currently is 1px). Please fix this.

Best Regards,
Lidiya
