### ISSUE TITLE
How can I add collapse/expand animation to SideNavigation?

### ISSUE THREAD

**Issue by zybzzc** [SAP/ui5-webcomponents#6151]

**Comment by NHristov-sap** [comment]
Hello @ui5-webcomponents-topic-rd,

Can you answer to this question?

Best Regards,
Nikolay Hristov

**Comment by gmkv** [comment]
Hi @zybzzc 

The SideNavigation already has a built-in transition. You can see it by clicking on the button above the SideNavigation [in the first sample here](https://sap.github.io/ui5-webcomponents/playground/components/SideNavigation/).

If you want to customize the animation, you can [override the transition with CSS](
https://codesandbox.io/s/ui5-side-navigation-custom-collapse-expand-animation-mkyoz7?file=/src/style.css:99-131) by selecting the the Web Component element:
```css
ui5-side-navigation {
  transition: ease-in width 2s;
}
```
The property which changes during expand/collapse is `width`.

Let me know if that works for you.
