### ISSUE TITLE
[SF_ACC][AXE][ui5-panel][1.9.1]AXE Error: Panel with custom header's expand/ collapse button should conform to valid values

### ISSUE THREAD

**Issue by ksblklu** [SAP/ui5-webcomponents#6157]
### **Bug Description**
When ui5-panel have custom header, the collapse / expand button in panel header dose not have correct accessible name

### **Expected Behavior**
Expand / collapse button should not have axe error

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/Panel/
2. Run chrome axe tools.
3. See panel custom header collapse / expand button have critical axe error.
<img width="1698" alt="image" src="https://user-images.githubusercontent.com/27538066/206368463-6b3c3a2d-bd69-4e15-b2c8-576ff0e704ec.png">

### **Context**
- UI5 Web Components version: 1.9.1
- OS/Platform: Any
- Browser: Chrome
- Affected component: ui5-panel

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### **Stakeholder Info** (if applicable)

- Organization: SuccessFactors
- Business impact: Medium

**Comment by NHristov-sap** [comment]
Hello @ui5-webcomponents-topic-rl,

Please check why expand/collapse button in Panel when there is a custom header, does not have accessibleName.

Best Regards,
Nikolay Hristov
