### ISSUE TITLE
[SF_ACC][ui5-wizard][1.8.0] wizard step title is not truncated when it's overflow

### ISSUE THREAD

**Issue by 2bno1** [SAP/ui5-webcomponents#6174]
### **Bug Description**
When the wizard step title is too long and is overflow, it's not truncated.

### **Expected Behavior**
When the wizard step title is too long, it should be truncated.

### **Steps to Reproduce**
1. Go to https://lsrf1w.csb.app/
2. Narrow the width of the browser window until the step title of wizard overflow
3. Observe the step title

### **Isolated Example**
https://codesandbox.io/s/ui5-webcomponents-forked-lsrf1w?file=/index.html

### **Context**
- UI5 Web Components version: 1.8.0
- OS/Platform: macOS
- Browser: Chrome
- Affected component: ui5-wizard

### **Log Output / Stack Trace / Screenshots**
![Screenshot 2022-12-12 at 09 39 42](https://user-images.githubusercontent.com/1751846/206944385-f0f696ed-4feb-49f1-866b-67671220f24a.png)

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by plamenivanov91** [comment]
Hell @SAP/ui5-webcomponents-topic-rl,

It seems like the Title of the step in the Wizard is not getting truncated when there is not enough horizontal space for it.

Could you please look into it?

Regards,
Plamen Ivanov

**Comment by MapTo0** [comment]
related with: https://github.com/SAP/ui5-webcomponents/pull/6169

**Comment by 2bno1** [comment]
@ivoplashkov This issue is still reproducible. I updated https://codesandbox.io/s/ui5-webcomponents-forked-lsrf1w?file=/index.html with the latest stable version @ui5/webcomponents (1.11.0). You can have a try.
![Screenshot 2023-03-21 at 09 45 42](https://user-images.githubusercontent.com/1751846/226502115-a032167b-68ac-48d9-bbc1-c9af64c6e57d.png)

**Comment by ivoplashkov** [comment]
Hi,

I am re-opening the issue for further analysis.

Best regards,
Ivaylo

**Comment by hristop** [comment]
Hi,

We have created BLI with which this incident will be further processed: BGSOFUIRILA-3336

Best Regards,
Hristo

**Comment by 2bno1** [comment]
Hi Team
Any updates on this?

Best regards.

**Comment by hristop** [comment]
Hi @2bno1 ,

This issue was fixed with [7263](https://github.com/SAP/ui5-webcomponents/pull/7263). 

Best Regards,
Hristo
