### ISSUE TITLE
[SF][ui5-illustrated-message][1.9.1]IllustratedMessage Icon inside flexbox disappeared in some occasions

### ISSUE THREAD

**Issue by ksblklu** [SAP/ui5-webcomponents#6176]
### **Bug Description**
In some occasions, the icon of IllstratedMessage inside a flexbox disappeared.

### **Expected Behavior**
Message icon should render correctly

### **Steps to Reproduce**
1. Go to CodeSandbox: https://codesandbox.io/s/agitated-benz-9z46kr?file=/src/App.js
2. See the first Illustrated Message icon does not render, but the second Illustrated Message rendered the icon correctly.

<img width="1694" alt="image" src="https://user-images.githubusercontent.com/27538066/207010737-ed197009-122e-40c5-96b6-9e0a76388206.png">

### **Context**
- UI5 Web Components version: 1.9.1
- OS/Platform: Any
- Browser: Chrome
- Affected component: ui5-illustrated-message

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

### **Stakeholder Info** (if applicable)

- Organization: SAP SuccessFactors
- Business impact: High

**Comment by ksblklu** [comment]
Hi @plamenivanov91 

IllustratedMessage inside a flexbox is a common usage in our projects. Can IllustratedMessage support parent Flexbox?

Best Regards

**Comment by kskondov** [comment]
Hello @SAP/ui5-webcomponents-topic-p , 

Can you please take a look whether the IllustratedMessage support of parent Flexbox is relevant as proposed by @ksblklu 

Best Regards,
Konstantin

**Comment by dobrinyonkov** [comment]
Hello @ksblklu,

childs of flex elements will lose their width by definition, so you would need to add width to your 2 level flexed div: 
https://codesandbox.io/s/musing-chaum-ijw813?file=/src/App.js

Best Regards,
Dobrin
