### ISSUE TITLE
Icon not available - move control to bar

### ISSUE THREAD

**Issue by sneha-ajit** [SAP/ui5-webcomponents#6178]
### **Bug Description**
Our team (LWV-SAP Analytics Cloud) uses ui5-webcomponents. But we are not able to find any proper icon for move control to bar in the [Icon Explorer](https://sapui5.hana.ondemand.com/sdk/test-resources/sap/m/demokit/iconExplorer/webapp/index.html#). Orca uses the same icon in the filter bar.

### **Isolated Example**
Image of the expected icon
<img width="34" alt="move-control-to-bar" src="https://user-images.githubusercontent.com/120373717/207014925-7c9edc2a-cd58-4daa-b7a8-9a3c45e090f7.png">

### **Context**
UI5 Web Components version: 1.6.0
OS/Platform: Web
Browser: Chrome
Affected component: Icons

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

Organization: SAP Analytics Cloud
Business impact: High - Not able to give the proper representation to the user.

**Comment by plamenivanov91** [comment]
Hello @sneha-ajit ,

I'm not sure that I understand your issue.
What is the name of the expected icon and why you can't use it?
Can you give us code snippet with your use case?

Regards,
Plamen

**Comment by sneha-ajit** [comment]
https://experience.sap.com/internal/sap-analytics-cloud/fpa-icon-repository/ This is the icon repository used by Orca(SAP Analytics Cloud) and it has the icon move-control-to-bar. I am attaching screenshot of the icon again.
<img width="1728" alt="Screenshot 2022-12-13 at 1 53 18 PM" src="https://user-images.githubusercontent.com/120373717/207263730-849bd38e-54e2-4abb-9325-6af045baa6ff.png">


Orca(SAP Analytics Cloud) uses SAPUI5 and some of the icons used are from the link shared above.

Code snippet in Orca
 if (FT_FILTER_MENU) {
                this._oPinToSideButton = new ButtonToolbarItem({
                    tooltip: filterMessages.getText("STORY_FILTERS_OR_PROMPTS_PIN_TO_SIDE"),
                    icon: sap.ui.core.IconPool.getIconURI("move-control-to-bar", "fpa"),
                    press: () => {
                        const oContext = this.getDocumentContext();
                        if (oContext) {
                            const FilterContextConstants = require("service!sap.fpa.bi.filter.FilterContextConstants");
                            oContext.fireUIEvent(FilterContextConstants.UI_EVENTS.STORY_SWITCH_FILTERBAR, {
                                vertical: true
                            });
                        }
                    },
                }).addStyleClass("sapEPMUIFilterPinToSideIcon");

I am from the SAC Lightweight viewer team and we are using UI5 Webcomponent for React instead of SAP UI5, but we need to support all the features in Orca(SAP Analytics Cloud). I cannot find this icon in the link below. https://sapui5.hana.ondemand.com/sdk/test-resources/sap/m/demokit/iconExplorer/webapp/index.html#

**Comment by plamenivanov91** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

The reporter needs the icon called **move-control-to-bar** which is part Orca(SAP Analytics Cloud), but it's not existing in our Icon Package in web components.

I checked all of our supported icons in case the icon exists under a different name but this icon is not present. There are a lot of similar icons though.

Should we(UI5 WC) support this icon? And if so, can we add it?

I reduced the priority to "Medium", because I don't think it's preventing the App from work properly.

Regards,
Plamen

**Comment by dobrinyonkov** [comment]
Hello @SAP/ui5-webcomponents-topic-core, could you take over this new icon request?

Kind Regards,
Dobrin

**Comment by nnaydenow** [comment]
Hi @sneha-ajit,

Since the icons package that you've mentioned is not from our currently supported, so could please check if our solution for custom icons will work in your case? https://sap.github.io/ui5-webcomponents/playground/getting-started/using-icons/#custom-icon-collections

**Comment by sneha-ajit** [comment]
Yeah i am using custom icons. Thanks.
