### ISSUE TITLE
[SF_ACC][ui5-list][1.8.0] need add aria description to list

### ISSUE THREAD

**Issue by i323808** [SAP/ui5-webcomponents#6181]
### **Bug Description**
Currently we cannot add aria description to ui5-list.

### **Expected Behavior**
We need add aria description to ui5-list.

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/List/
2. There is no property for aria-description

### **Isolated Example**
If possible, please provide an isolated example by forking [CodeSandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html).

### **Context**
- UI5 Web Components version: 1.8.0
- OS/Platform: {...}
- Browser: {...}
- Affected component: {...}

### **Log Output / Stack Trace / Screenshots**
```
{...}
```
### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by plamenivanov91** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

The reporter wants to be able to configure the aria description to the **ui5-list** Web Component.

I noticed that the desired aria can't be configured on the **List** in the **OpenUI5** too.

I guess that the description is not supported for the List Web Component but can you confirm it ?

Regards,
Plamen Ivanov

**Comment by dobrinyonkov** [comment]
Hello @i323808,

The handling of descriptions is not that clear at this point due to limitation related to shadow DOM, so this should be handled carefully and centrally. For this we created https://github.com/SAP/ui5-webcomponents/issues/6445 where you could read detailed information related to the descriptions as well as track the process of implementation.

Thank you for reporting!

Dobrin
