### ISSUE TITLE
Menu: arrow navigation does not loop

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#6182]
### **Bug Description**
When pressing arrow up or down, the navigation should loop.

### **Expected Behavior**
- When pressing arrow-up at the beginning of the list, the focus should jump to the last item of the list.
- When pressing arrow-down at the end of the list, the focus should jump to the first item.

[SAPUI5 Menu:](https://ui5.sap.com/#/entity/sap.m.Menu/sample/sap.m.sample.Menu)

https://user-images.githubusercontent.com/9749730/207258850-b2ee2f9e-2474-4a6f-8f27-326a55546642.mp4

### **Steps to Reproduce**

1. Go to [playground](https://sap.github.io/ui5-webcomponents/playground/components/Menu/)
2. Try the expected behavior.
3. See that nothing happens when you press the respective arrow key at the beginning or end of the list.

### **Isolated Example**
https://sap.github.io/ui5-webcomponents/playground/components/Menu/

### **Context**
- UI5 Web Components version: 1.9.1

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by plamenivanov91** [comment]
Hello @SAP/ui5-webcomponents-topic-b,

Is it possible to achieve the same UX behavior as in OpenUI5?

Regards,
Plamen Ivanov

**Comment by Lukas742** [comment]
Hi team, 

I just contacted our central acc expert for keyboard handling and he told me that that the behavior of the SAPUI5/OPENUI5 `Menu` is not according to the guidelines, so you might consider keeping it like it is now. If you need more information please feel free to contact me internally.
