### ISSUE TITLE
[SF_ACC] TabContainer: tab expand buttons do not have discernible text

### ISSUE THREAD

**Issue by lv75** [SAP/ui5-webcomponents#6186]
According to the Axe DevTool, the 'tab-expand-buttons' of https://sap.github.io/ui5-webcomponents/playground/components/TabContainer/ must have discernible text.

![Screenshot 2022-12-13 at 4 23 29 PM](https://user-images.githubusercontent.com/8533257/207494224-554148e3-a6f7-491b-8182-7061bdcebd15.png)

And to solve this problem, at least (1) of the following needs to be fixed:
- Element does not have inner text that is visible to screen readers
- aria-label attribute does not exist or is empty
- aria-labelledby attribute does not exist, references elements that do not exist or references elements that are empty
- Element has an empty title attribute
- Element's default semantics were not overridden with role="none" or role="presentation"

----

Related Jira ticket: https://jira.successfactors.com/browse/WEF-37164

**Comment by plamenivanov91** [comment]
Hello @SAP/ui5-webcomponents-topic-rd,

This issue of the reporter can be reproduced easily with a quick scan of axe DevTools in Chrome.

There are a couple of possible solutions described in the reported error in the tool.

Can we fix this?

Regards,
Plamen Ivanov

**Comment by LidiyaGeorgieva** [comment]
Hello @lv75 ,

This issue is fixed 3 weeks ago.
You can see more information here: https://github.com/SAP/ui5-webcomponents/issues/6001

Best Regards,
Lidiya
