### ISSUE TITLE
IllustratedMessage: message error with double quotes

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents#6187]
**Describe the bug**
hi, team, for the IllustratedMessage component the message is incorrect.

**Isolated Example**
the example is comes from your official storybook.

https://sap.github.io/ui5-webcomponents-react/?path=/docs/user-feedback-illustratedmessage--default-story

Also the `BeforeSearch`, `NoData` has the same issue.

**To Reproduce**
1. Go to  https://sap.github.io/ui5-webcomponents-react/?path=/docs/user-feedback-illustratedmessage--default-story
2. select the IllustratedMessage name with `PageNotFound `
3. See message error with double quotes

**Expected behavior**
The message should be `Sorry, we can't find this page`

**Screenshots**
![image](https://user-images.githubusercontent.com/78520316/207498936-75d0de29-aad9-4a8e-bde2-0b9cacf9798e.png)
![image](https://user-images.githubusercontent.com/78520316/207500696-048ac345-782f-443d-9287-ea3573707056.png)
![image](https://user-images.githubusercontent.com/78520316/207500734-e4eac210-69db-4a02-a085-d647f4723c52.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.9.1
`@ui5/webcomponents-react` version: 1.6.0
Operating System:
Browser: Any

**Comment by nnaydenow** [comment]
Hi,

Issue is fixed with: #6041.
