### ISSUE TITLE
[SF_ACC]  Text spacing CSS not applied to menu button in Shell Bar component

### ISSUE THREAD

**Issue by ee92** [SAP/ui5-webcomponents#6212]
### **Bug Description**
Global CSS rules for text spacing should applied to all content on the page. The menu button in the Shell Bar is not affected by the following CSS rule:
```
* {
  line-height:1.5 !important;
  letter-spacing:0.12em !important;
  word-spacing:0.16em !Important;
}
```
![Screenshot 2022-12-19 at 8 24 03 AM](https://user-images.githubusercontent.com/24360164/208474527-59216a70-ccd3-4332-afcd-b878713ed6e5.png)

### **Expected Behavior**
Expect the menu button to inherit global CSS similar to how other components do. 
This is a previous issue for different components: https://github.com/SAP/ui5-webcomponents/issues/5792 

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/ShellBar/
2. Apply a global CSS rule like shown above
3. Notice the menu button text is not affected

### **Context**
- UI5 Web Components version: 1.9.0
- Affected component: ui5-shellbar

### **Priority**
- [x] Low
- [ ] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info**

- Organization: SuccessFactors

**Comment by ndeshev** [comment]
"Hello @SAP/ui5-webcomponents-topic-p, seems like the global styles with th `*`  could not be applied to the `ui5-shellbar`  primary-title button as the button has browser default text-spacing properties set. Maybe setting them to `inherit` could help, could you please take a look. 


Kind regards,
Nikolay
