### ISSUE TITLE
Mark abstract components

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#6220]
### **Issue Description**
We (UI5 Web Components for React) often receive issues regarding the styling of abstract components. To outline to app developers that an abstract component like the `SuggestionItem` is not stylable by standard means, we would need to know what component is abstract. We would like to receive this information via the `api.json` and therefore a appropriate JSDoc comment should be added (e.g. `@abstract`)

### **Issue Type**

- [ ] Documentation is unclear
- [ ] Documentation is incorrect
- [x] Documentation is missing
- [ ] Other

**Comment by ndeshev** [comment]
Hello @SAP/ui5-webcomponents-topic-core could you please evaluate this documentation improvement request. Thank you.

**Comment by nnaydenow** [comment]
Fixed with #6331
