### ISSUE TITLE
MultiComboBox: onSelectionChange returns wrong item

### ISSUE THREAD

**Issue by nicolas-kennemann-fioneer** [SAP/ui5-webcomponents#6222]
**Describe the bug**
When there's a group item and an item with the same `text` prop, typing the text and hitting enter returns the group item as argument to `onSelectionChange`. Additionally, the checkbox for the item (not group item) is still not checked afterwards.

**Isolated Example**
https://codesandbox.io/s/cranky-rain-2mzqhi

**To Reproduce**
1. Open the [codesandbox](https://codesandbox.io/s/cranky-rain-2mzqhi)
2. Type "Text" into the MultiComboBox
3. Hit Enter
4. Open the console: It says `group item` instead of `item`
5. Open the MultiComboBox's popover: The item's checkbox isn't checked

**Expected behavior**
Searching for an option inside the MultiComboBox skips group items

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.9.3
`@ui5/webcomponents-react` version: 1.7.0
Operating System: Windows
Browser: Firefox

**Comment by ndeshev** [comment]
Hello @SAP/ui5-webcomponents-topic-rl when there are grouping item and item with the same text and the autocompleted value is selected with 'Enter' the selection change emits the grouping item. Could you please take a look.
