### ISSUE TITLE
Can't translate the month's name to any other language in DatePicker

### ISSUE THREAD

**Issue by roshnijalan97new** [SAP/ui5-webcomponents#6223]
**Describe the bug**
Can't translate the month's name to any other language in DatePicker.
Months are given in English. If the user have the language as german and wants to see the months in that format. I am unable to translate the months in german.

**Isolated Example**
*Please provide an isolated example if possible by forking [this codesandbox](https://codesandbox.io/s/ui5-webcomponents-react-template-29l34).*
Ex: https://codesandbox.io/s/elated-euler-fnfsn8?file=/src/App.js:175-185
I

**To Reproduce**
1. Go to ' https://codesandbox.io/s/elated-euler-fnfsn8?file=/src/App.js:175-185'
2. Click on the 'calendar' icon.
 You will see the month is coming in English.

**Expected behavior**
I want to translate the month into german.

**Screenshots**
<img width="334" alt="Screenshot 2022-12-23 at 2 13 09 PM" src="https://user-images.githubusercontent.com/120740457/209303314-f7471865-e431-41ac-ad91-4528b561e8ea.png">

**UI5 Web Components for React Information**

**Additional context**

**Comment by ndeshev** [comment]
Hello @SAP/ui5-webcomponents-topic-b this is a feature request for customizable month titles (values), although I guess that will require the implementation of a custom web component could you please evaluate this feature request from your side.

**Comment by roshnijalan97new** [comment]
> '@ui5/webcomponents-react/dist/Assets'

Hi @MarcusNotheis, The fix given by you was working but it has stopped working now. Do you know any possible reason why it stopped working?

**Comment by MarcusNotheis** [comment]
> @MarcusNotheis This issue is coming in the internal SAP CIM project, Do you have any other fix for this?

@ilhan007 can you jump in here and help @roshnijalan97new out?
Thanks!

**Comment by roshnijalan97new** [comment]
@ilhan007  Please let me know if you are available today. We can conect.

**Comment by ilhan007** [comment]
Hello @roshnijalan97new 

Here are the months in German, this comes out of the box when you set the language to "de"
<img width="317" alt="Screenshot 2023-02-01 at 8 23 52" src="https://user-images.githubusercontent.com/15702139/215967384-9ad5a33f-db6a-46ef-b9be-43cf137c046d.png">

But as far I understood, you want to provide different, custom translation for the months, could you give us an example?
Is it the format that you want to change - "Dez' instead of "Dezember" or something like that, or you really need to provide another word. But I can't imagine that there is an use-case to display something else as the intention is to show the months.
Please provide more details to understand your use-case.

Apart of that, this is a feature request and the owner and responsible colleague @petyabegovska is already assigned.
The request will be processed according to the team's planning and capacity. If you think this is High priority, you need to give us more details on the urgency matter (for that I suggest contacting in internal channels as might contain internal data)

BR,
ilhan

**Comment by roshnijalan97new** [comment]
Hi @ilhan007, The set language () function is not working in our project. The function was working earlier but for the last 10-15 days it has stopped working. Right now we are okay with this solution but it is no more working.

**Comment by roshnijalan97new** [comment]
Hi @ilhan007, The versions used in our projects for the packages are as : 
   "@ui5/webcomponents": "1.9.2",
    "@ui5/webcomponents-base": "1.8.0",
    "@ui5/webcomponents-fiori": "1.8.0",
    "@ui5/webcomponents-react": "1.7.1",
    "@ui5/webcomponents-react-base": "^1.1.0",
 "react": "17.0.2",
"react-dom": "17.0.2",
Can you let me know if this issue is occurring due to some versions difference? I can see in the sandbox if I change the versions to this, it is causing error.

**Comment by ilhan007** [comment]
Hello @roshnijalan97new

you are supposed to use the same versions for the packages from **UI5 web Components** project
"@ui5/webcomponents": " ~1.10.0",
"@ui5/webcomponents-base": "~1.10.0",
"@ui5/webcomponents-fiori": "~1.10.0",
"@ui5/webcomponents-icons": "~1.10.0",
"@ui5/webcomponents-theming": "~1.10.0",
"@ui5/webcomponents-localization": "~1.10.0",

and the same versions for the packages from **UI5 web Components for React** project
"@ui5/webcomponents-react": "~1.10.0",
"@ui5/webcomponents-react-base": "~1.10.0",

Each of the project has its own release process and the version don't match, but the packages in the projects should have the exact version. Try with the @ latest of all dependencies and everything should work.

**Comment by roshnijalan97new** [comment]
Hi @ilhan007, I am getting an error after changing th versions while starting the react app:
_

> base-npm-1.8.0-8b8dd08dfa-7834a04da6.zip/node_modules/@ui5/webcomponents-react-base/dist/hooks/useI18nBundle.js 36:46
> Module parse failed: Unexpected token (36:46)
> File was processed with these loaders:
>  * ../../../.yarn/__virtual__/babel-loader-virtual-c149b03d43/0/cache/babel-loader-npm-8.1.0-141c45b960-fdbcae91cc.zip/node_modules/babel-loader/lib/index.js
> You may need an additional loader to handle the result of these loaders.
> |     };
> |   }, [bundleName]);
> >   return i18nContext.i18nBundles[bundleName] ?? defaultBundle;
> | };

_

**Comment by roshnijalan97new** [comment]
Hi @petyabegovska, Please mark this issue again as new. I marked it as completed by mistake.

**Comment by ilhan007** [comment]
@MarcusNotheis does the error that @roshnijalan97new mentioned above sounds familiar to you

**Comment by MarcusNotheis** [comment]
Not at all to be honest. @roshnijalan97new can you share some details about your setup? Do you use `create-react-app`, `next` or a custom setup?

**Comment by roshnijalan97new** [comment]
> 

Hi @MarcusNotheis, and @ilhan007, If I am trying to change the version according to what you explained here, I am getting errors in other components in the app. Kindly refer the sandbox- https://codesandbox.io/s/elated-euler-fnfsn8?file=/src/App.tsx

**Comment by roshnijalan97new** [comment]
Hi @MarcusNotheis and @ilhan007, Please give some updates on this bug.

**Comment by MarcusNotheis** [comment]
> I am trying to change the version according to what you explained here, I am getting errors in other components in the app. Kindly refer the sandbox- https://codesandbox.io/s/elated-euler-fnfsn8?file=/src/App.tsx

UI5 Web Components for React 1.8.0 is not compatible with UI5 Web Components 1.8.0, you should also see a peer dependency warning in your console when installing dependencies locally.
The corresponding supported version for UI5 Web Components 1.8.0 would be UI5 Web Components React 1.1.0: https://codesandbox.io/s/flamboyant-bush-n4eg6q

**Comment by roshnijalan97new** [comment]
> I am trying to change the version according to what you explained here, I am getting errors in other components in the app. Kindly refer the sandbox- https://codesandbox.io/s/elated-euler-fnfsn8?file=/src/App.tsx
> 
> UI5 Web Components for React 1.8.0 is not compatible with UI5 Web Components 1.8.0, you should also see a peer dependency warning in your console when installing dependencies locally. The corresponding supported version for UI5 Web Components 1.8.0 would be UI5 Web Components React 1.1.0: https://codesandbox.io/s/flamboyant-bush-n4eg6q
Hi @MarcusNotheis, this helped solve the compatibility issue but the original problem that the month is not getting translated is not solved.

**Comment by MarcusNotheis** [comment]
Yes, my answer was only intended to solve the errors in the application due to the mismatching versions. Changing the translation would be in my opinion a feature request and I can't comment on that one as the component is not within my responsibility.

**Comment by roshnijalan97new** [comment]
Hi @MarcusNotheis, can you please let me know the due date by when I can expect the feature?

**Comment by ilhan007** [comment]
Hello @roshnijalan97new 

let's summarise what is the request now.

The first problem was
"The setLanguage () function is not working with the date picker in our project as previously...Right now we are okay with this solution but it is no more working."
This was resolved. I sent you a working codesandbox https://codesandbox.io/s/green-shape-gd2z90

This is the result when setLanguage("pt") is used
<img width="312" alt="Screenshot 2023-03-10 at 11 56 59" src="https://user-images.githubusercontent.com/15702139/224286018-b7af17e1-2293-40c9-96c4-40965fad5514.png">
<img width="326" alt="Screenshot 2023-03-10 at 11 57 12" src="https://user-images.githubusercontent.com/15702139/224286026-192f5e1f-9459-42e0-bb92-5ba212c316f7.png">

Now, a separate thing is to be able to define custom translations, if I understand correctly? 
Could you share what would like to change?

**Comment by roshnijalan97new** [comment]
HI @ilhan007, I can see it is working in the sandbox but it is not working in our project.

**Comment by DMihaylova** [comment]
Hi @MarcusNotheis,

Thanks to [ilhan007's example](https://codesandbox.io/s/green-shape-gd2z90) it could be seen that setLanguage now works with the Date Picker component.
It seems like there is an issue in the react project. Could you please assist?
From what I understand, it seems like the custom translations are not needed and this is the only issue here.

**Comment by MarcusNotheis** [comment]
Hi @DMihaylova,
I don't really know how to assist to be honest. @ilhan007's example is already using the React component, so I would assume that everything is also fine in the UI5 Web Components for React project (especially as we're just a wrapper around the UI5 Web Component in this case without any custom code).

**Comment by DMihaylova** [comment]
I'm closing this issue. Feel free to reopen if there's a problem in the component.
