### ISSUE TITLE
bug(docs): example code out of sync with its snippet

### ISSUE THREAD

**Issue by platon-rov** [SAP/ui5-webcomponents#6237]
### **Issue Description**

Code of example out of sync with its snippet for some examples.

![CleanShot 2023-01-02 at 20 32 40@2x](https://user-images.githubusercontent.com/20265336/210272336-333c2cbf-a8a9-440a-8401-796e1f6a5e2a.png)

*Note: It may be reasonable to have a code-sample component which will use the same code for the example and its snippet. This way, we avoid the possibility of having those two blocks out of sync.*

### **Issue Type**

- [x] Documentation is unclear
- [x] Documentation is incorrect
- [ ] Documentation is missing
- [ ] Other

**Comment by platon-rov** [comment]
An additional reason to fix this is that we, fundamental-team, are trying to parse samples to recreate them for ui5-webcomponents-ngx automatically. This is a blocker.

Taking `.snippet`s content isn't an option also, as for some example `<script>` placed outside of container.

![CleanShot 2023-01-02 at 20 50 42@2x](https://user-images.githubusercontent.com/20265336/210273350-dfca8133-f0dc-481a-8189-585cbc9a6dc0.png)

**Comment by mindarelus** [comment]
@platon-rov hi, can you make another issue for the second problem, because it's different component.

**Comment by mindarelus** [comment]
Hello @SAP/ui5-webcomponents-topic-p I am forwarding this issue to you, because in fact if the code is missing the snippet won't work.

**Comment by nnaydenow** [comment]
Hi @mindarelus ,

The issue should be handle by all teams, because they maintain there own samples in playground and they decide what to be displayed.

**Comment by platon-rov** [comment]
@mindarelus @nnaydenow idk if that ticket still makes sense as @vladitasev today told me that documenting approach is be under active rework and samples will be replaced with storybook stories.

**Comment by vladitasev** [comment]
Hi @platon-rov 

Yes, these samples will be removed in the near future and replaced. Therefore, I think we can close the issues for the time being.

BR,
Vladi
