### ISSUE TITLE
Cannot register ResizeHandler for element <ui5-segmented-button>

### ISSUE THREAD

**Issue by sltu** [SAP/ui5-webcomponents#6238]
### **Bug Description**

I get many "Cannot register ResizeHandler for element" warnings for: `<ui5-segmented-button>`

![image](https://user-images.githubusercontent.com/111493050/210326617-921f2d4c-68bd-4de0-b79a-0b4685f0eab6.png)

I use `<ui5-segmented-button>` inside `<ui5-table-cell>`

![image](https://user-images.githubusercontent.com/111493050/210326077-146853e9-969c-4e2e-86f5-81b3e28444ae.png)

In my implementation `<ui5-segmented-button>` component  is inside my own component `<r-order-buttons>` and this component is inside `<ui5-table-cell>`

![image](https://user-images.githubusercontent.com/111493050/210326182-30f33487-a246-4207-9c39-8d10d2e73551.png)

### **Expected Behavior**
A way to get rid of these warnings

### **Context**
- UI5 Web Components version: 1.9.1
- OS/Platform: Linux/Ubuntu 22.10
- Browser: Chrome, Firefox (the latest)
- Affected component: <ui5-segmented-button>

### **Priority**
- [x] Low
- [ ] Medium
- [ ] High
- [ ] Very High

**Comment by mindarelus** [comment]
@sltu hi, can you provide isolated code example where you reproduce this this warning.

**Comment by sltu** [comment]
I hope, codesandbox with my example will work for you
https://codesandbox.io/s/ui5-webcomponents-forked-e2o2uu?file=/src/order-buttons.js

![image](https://user-images.githubusercontent.com/111493050/210374798-32adfdac-6a85-411e-abe7-c1c2b3132a6c.png)

chrome
![image](https://user-images.githubusercontent.com/111493050/210374980-ec2e59a2-a0d4-41ad-bc56-987aa218f80a.png)

firefox
![image](https://user-images.githubusercontent.com/111493050/210375448-05cfaa0d-cf27-4705-89c8-4ee5ed88e470.png)

**Comment by hinzzx** [comment]
Hi @sltu ,

I used your sample and the error is present in version 1.9. However I updated the version to latest (v1.24.0) and the reported warning message is not here.

Could you please check if updating the ui5-webcomponents version to latest resolves the problem for you ? 

Regards,
Stoyan
