### ISSUE TITLE
Regarding "aria-valuenow" and "ui5-range-slider"

### ISSUE THREAD

**Issue by vladitasev** [SAP/ui5-webcomponents#6247]
Hello colleagues,

I had a report that using "ui5-range-slider" produces an error with the "Axe" ACC tool - it says that `aria-valuenow` must be set on the main `div`, rather than on the "handles", as it is in our component's case. Could you please investigate and come up with a statement on whether this is expected or not.

BR,
Vladi

**Comment by ndeshev** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,  could you please check the reported by the tool issue and if it could be adjusted.
