### ISSUE TITLE
Date Time Range Picker

### ISSUE THREAD

**Issue by tug-guenter** [SAP/ui5-webcomponents#6257]
### **Feature Request Description**
Create a LitElement (based on Lit 2.x), which handles two DateTime objects (JS Date handling date and time would be enough).

### **Proposed Solution**
Combine the already existing Date Range Picker with the Date Time Picker.

### **Proposed Alternatives**

@fooloomanzoo/datetime-picker would already handle this (but is outdated using Polymer 3 in the core)
see: [https://github.com/fooloomanzoo/datetime-picker](https://github.com/fooloomanzoo/datetime-picker)

Another solution is already being implemented in the brightspace UI:
d2l-input-date-time-range
see: [https://github.com/BrightspaceUI/core/blob/main/components/inputs/docs/input-date-time.md](https://github.com/BrightspaceUI/core/blob/main/components/inputs/docs/input-date-time.md)

### **Additional Context**

The control should also be configurable for the view like the Date Range Picker is, but extended with Features from the Date Time Picker.

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: UI5 Web Component users
- Business impact: might improve usecases for filtering on timeseries data

**Comment by kineticjs** [comment]
Hello @SAP/ui5-webcomponents-topic-b, please take a look of this feature request.

**Comment by DMihaylova** [comment]
Hi @tug-guenter,

Have you checked our redesigned ui5-datetime-picker where instead of wheelsliders, we now have a clock dial?
https://sap.github.io/ui5-webcomponents/nightly/components/DateTimePicker/

That could easily fit in the use cases from your screenshots - from <one instance of the date time picker> to <second instance of the date time picker>.

Regards,
Diana

**Comment by DMihaylova** [comment]
Hi @tug-guenter,

Since there has been no follow-up, I will close the issue for now.
Please feel free to reopen it if the proposed solution is not sufficient.

Wishing you a joyful holiday season and a Happy New Year! 🎄

Regards,
Diana
