### ISSUE TITLE
Tree: In Multiselect mode, all tree nodes are not showing checkbox

### ISSUE THREAD

**Issue by Ankitadoshi** [SAP/ui5-webcomponents#6265]
**Describe the bug**
In Tree Component, when we have mode as MultiSelect, checkboxes are not visible for all the child items. If the tree node is collapsed by default and we expand it, the child items do not have checkboxes.  If the tree node is expanded by default we are able to see the checkboxes for child nodes.

**Isolated Example**
https://sap.github.io/ui5-webcomponents-react/?path=/story/data-display-tree--default-story&args=mode:MultiSelect

**To Reproduce**
1. Go to 'https://sap.github.io/ui5-webcomponents-react/?path=/story/data-display-tree--default-story&args=mode:MultiSelect'
2. Expand 'Tree 2' tree item
3. Observe that the child items below it ('Tree 2.1', 'Tree 2.2') do not have checkboxes.
4. Expand 'Tree 2.1' tree item
5. Observe that the child items below it does not have checkbox('Tree 2.1.1', 'Tree 2.1.2')
6. Observe that 'Tree 1' is expanded by default and all its child items have checkbox

**Expected behavior**
In Tree, If mode is set to MultiSelect, all the tree nodes should have checkbox to select/unselect them.

**Screenshots**
<img width="1679" alt="Screenshot 2023-01-11 at 3 01 23 PM" src="https://user-images.githubusercontent.com/40891409/211769769-ea5efc04-e808-4b49-9c40-489f2d3bd14e.png">

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.9.3
`@ui5/webcomponents-react` version: 1.7.1
Operating System: macOS Ventura Version 13.1
Browser: Chrome

**Additional context**

**Comment by kineticjs** [comment]
Hi @ui5-webcomponents-topic-p,

This is an issue with ui5-tree reproducible with the latest version. It appears related to some recent refactoring of the structure:
See the initial description for details.
In debugging we see that the "mode" of the tree is not propagated to all tree-items: it is propagated only to those that are expanded (i.e. those that are rendered as underlying list-items)

**Comment by Ankitadoshi** [comment]
Hi @dobrinyonkov ,

Can you let us know in which version this will be available?

**Comment by Ankitadoshi** [comment]
Hi @dobrinyonkov ,
Please let us know the version in which this fix will be available.
Thanks,
Ankita

**Comment by ilhan007** [comment]
Hi @Ankitadoshi  It's in 1.10
