### ISSUE TITLE
[SF][ui5-upload-collection] The illustration of empty state is not consistent with Horizon design

### ISSUE THREAD

**Issue by i323808** [SAP/ui5-webcomponents#6271]
### **Feature Request Description**
According to https://wiki.one.int.sap/wiki/pages/viewpage.action?pageId=2698916049#UploadCollection/Set(Horizon)-UploadCollection(Horizon)%E2%80%93Header, the illustration of empty state should be sapIllus-Scene-Tent.

Current illustration:
<img width="1352" alt="UploadCollection_empty_state" src="https://user-images.githubusercontent.com/30744017/212289956-f883293b-d67a-4af8-9a8a-511cb7c5c2db.png">

Horizon design:
<img width="1112" alt="UploadCollection_empty_state_design" src="https://user-images.githubusercontent.com/30744017/212290030-5a7a9e05-6db9-45ac-9b74-29e2de480a34.png">

### **Proposed Solution**
A clear and concise description of the solution you would like to have.

### **Additional Context**
Add other context or screenshots related to the feature request here.

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by kineticjs** [comment]
Hi @SAP/ui5-webcomponents-topic-rd,
The spec for Horizon https://wiki.one.int.sap/wiki/pages/viewpage.action?pageId=2698916049#UploadCollection/Set(Horizon)-UploadCollection(Horizon)%E2%80%93Header specifies a theme-specific icon for the empty state. Do you plan to reflect this in the component?

**Comment by olannyv** [comment]
The Upload Collection rendering for empty states is not yet using the Illustrated Messages. 
It is valid and nice to have, just a matter of priority and capacity in the team .... 

@i323808 - what is the application or scenario where you need/expect illustrated messages?  
How would you rate the priority of having such?

**Comment by i323808** [comment]
Hi @olannyv ,

Thanks for your reply. 
We are using UploadCollection in "Apply for This Assignment" dialog of Opportunity Marketplace(SuccessFactors). We rolled out Horizon theme in the last release(b2211) and found the empty state of UploadCollection is different from other components which are using IllustratedMessage. Hopefully we can eliminate this UI inconsistency in the next release(b2305).

Thanks,
Jane

**Comment by olannyv** [comment]
Hi, @i323808 

I saw in the Spec three cases with specified Illustrated Message.
How about this (/) Success screen in your last answer - what is this "Great!" Illustrated Message?  

Daniel

**Comment by i323808** [comment]
Hi @olannyv ,

The "Success" dialog is another business  scenario which are using IllustratedMessage, so it's UI is inconsistent with the empty state of UploadCollection. The IllustratedMessage name of "Success" dialog is "BalloonSky".

BR,
Jane

**Comment by olannyv** [comment]
Implementation BLI BGSOFUIRODOPI-2946 created
Pending execution based on team capacity and priorities
