### ISSUE TITLE
[SF] The words in checkbox are broken

### ISSUE THREAD

**Issue by korgong** [SAP/ui5-webcomponents#6278]
### **The words in checkbox are broken when the value of wrappingType is Normal **
There are a few words in checkbox. By default, when the container or screen is small, The text will be truncated with an ellipsis. when the value of wrappingType is Normal, The text will wrap. The words will not be broken based on hyphenation. But now, the word is broken like screenshot below.
![current behaviour](https://raw.githubusercontent.com/korgong/img/main/current-behaviour.png)

### **Expected Behavior**
The text will wrap. The words will not be broken based on hyphenation.
![current behaviour](https://raw.githubusercontent.com/korgong/img/main/expected-behaviour.png)

### **Steps to Reproduce**
1. use checkbox component
2. set the value of wrappingType property to Normal
3. The words will not be broken based on hyphenation.

### **Context**
- UI5 Web Components version: {latest}
- OS/Platform: {mac os}
- Browser: {chrome}
- Affected component: {checkbox}

### **Priority**
- [ ] Low
- [] Medium
- [x] High
- [ ] Very High

**Comment by korgong** [comment]
![current-result](https://raw.githubusercontent.com/korgong/img/main/circle%20error.png)
As you can see, the words in the red circle do not appear on the same line. We want the word to appear on the same line or be displayed completely on the next line.

I noticed that in line 56 of this file(https://github.com/SAP/ui5-webcomponents/blob/main/packages/main/src/themes/CheckBox.css), The value of word-break is break-all. It causes a word to appear on different lines. Why not use word-break: break-word? Or some way to make sure a word doesn't wrap.

**Comment by ndeshev** [comment]
Hello @SAP/ui5-webcomponents-topic-p, could you please take a look at this feature request, the user want different type of multi-line wrapping, more specifically - non breaking words one.

**Comment by kieransukachevin** [comment]
Consider this PR to fix this issue: 
https://github.com/SAP/ui5-webcomponents/pull/6539

**Comment by korgong** [comment]
> 

Thank you so much for solving the issue.
