### ISSUE TITLE
[SF][Popover][Button]OnClick function of a Button will not be triggered by enter key when it is inside of a Popover

### ISSUE THREAD

**Issue by zijies1** [SAP/ui5-webcomponents#6281]
### **Bug Description**
The OnClick function bind to Button component will not be triggered by pressing enter key when the Button component is inside of a Popover component

### **Expected Behavior**
The OnClick function bind to Button component should be triggered by pressing enter key.

### **Steps to Reproduce**

https://user-images.githubusercontent.com/25004172/212674486-85c56081-66f3-47e4-8a1c-35a36e75c43f.mp4

### **Isolated Example**
https://codesandbox.io/s/buttonissueinpopover-pohdqp

### **Context**
- UI5 Web Components version: 1.9.1
- OS/Platform: MacOS
- Browser: Chrome
- Affected component: Popover, Button

### **Log Output / Stack Trace / Screenshots**
```
{...}
```
### **Priority**
- [ ] Low
- [] Medium
- [x] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SuccessFactors
- Business impact: {...}

**Comment by ndeshev** [comment]
Hello @zijies1 could you please try to reproduce the issue in plain UI5 WebComponents because I can't reproduce it in our samples - https://sap.github.io/ui5-webcomponents/playground/components/Popover/ - click on the first popover button and attach event listener on the `click `event of the "Subscribe" button and press 'enter' - the click event is fired.

**Comment by gmkv** [comment]
Hi @zijies1 
You must use the property `open` and `opener` to correctly show the Popover as described in the [docs here](https://sap.github.io/ui5-webcomponents-react/?path=/docs/modals-popovers-popover--default-story). 

https://codesandbox.io/s/buttonissueinpopover-forked-0x6qnk?file=/src/App.js
Setting `display: block` on the element looks like it works, but it's not documented to be the correct way to use the Popover.
