### ISSUE TITLE
Infra: improve release and changelog automation

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents#6289]
### **Feature Request Description**
Atomisation of Release process:
- use ui5-webcomponents-bot for release and release commit messages
- auto-generate change log and upload it to Github as  Github Release
- auto update package.json files and create release commit
- auto publish packages to npm

### **Proposed Solution**
A clear and concise description of the solution you would like to have.

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by MarcusNotheis** [comment]
In case you are interested, you can have a look at the [UI5 Web Components for React release workflow](https://github.com/SAP/ui5-webcomponents-react/blob/main/.github/workflows/release.yml) in case you need some inspiration :)

**Comment by ilhan007** [comment]
> UI5 Web Components for React release workflow

For sure, thank you!

**Comment by ilhan007** [comment]
Closing the issue with 3 new [actions](https://github.com/SAP/ui5-webcomponents/actions)  added, allowing everyone to release whatever kind of release, version needed from behalf of a ui5-webcomponents-bot technical user.

**Release,yaml** - general purpose action to release manually - patches, minors, etc.

**Release-auto-weekly.yaml** - action that is automatically triggered every thursday and creates pre-release (f.e 1.11.0-rc.0) https://github.com/SAP/ui5-webcomponents/commit/eea6709321e139bd0b699c910cfdab658ca44950

**Release-custom-tag.yaml** - action meant to create releases under specific tag (useful for downports under "sf" tag - 1.9.3 as @ sf tag) https://github.com/SAP/ui5-webcomponents/commit/c2e9525f1bfa4d8ca0c24eeb7f642567f5573634
<img width="207" alt="Screenshot 2023-02-08 at 8 02 49" src="https://user-images.githubusercontent.com/15702139/217447998-e971ceda-ef42-444d-a025-74e975cc593b.png">

**Note:** all actions
- creates GitHub release and uploads changelog, 
- creates git tag
- merge release commit
- publishes packages to NPM
