### ISSUE TITLE
Menu/MenuItem: style & className props not applied to popover

### ISSUE THREAD

**Issue by ej612** [SAP/ui5-webcomponents#6294]
We have a Menu like [this one](https://codesandbox.io/s/thirsty-leaf-e9dou5?file=/src/App.js).
When I try to style the MenuItem, either by setting the style property or by using clsx to set the className property, the applied styles show up fine on the `ui5-menu-item` element in the DOM:
![_pic1](https://user-images.githubusercontent.com/110408767/213152982-844a9322-ae81-450a-b5b4-f817cece951f.png)

However, this does not seem to actually be the menu item we later see in the Menu popover. The item in the popover is a `ui5-li` element and it doesn't inherit the styles:
![_pic2](https://user-images.githubusercontent.com/110408767/213153268-f20ae899-cf3f-40c8-a2d4-8be68f83ea4e.png)

Is this a bug? How would I go about applying a style to a MenuItem?

Edit for clarification: What we're trying to do is style the popover, not style the ui5-menu-item.
Let's say we have a menu with a single menu item, which says "Activate X". Activate is disabled by default, so no icon is set on the menu item. When clicking on it, activate is enabled and we display a checkmark icon on the menu item. This affects the indentation: With an icon, the menu item is wider to provide extra space needed for the icon. Without the icon, this space doesn't exist.
We have multiple menus, all of which have the extra space on the left because there is always an icon. If one of the menus suddenly doesn't have that extra space because the icon is temporarily hidden, it affects the look and feel. We therefore always want the extra space, even if there's no icon. We wanted to achieve this by always setting the icon and then setting its visibility=visible||hidden conditionally, through the icon shadow part of the menu item in the popover.
However, this is not possible because the ui5-menu-item doesn't forward the styles that are applied to it to its counterpart in the popover.
I hope this clears things up. If not, don't hesitate to get in touch.

Thanks a lot in advance!

**Comment by ndeshev** [comment]
Hello @SAP/ui5-webcomponents-topic-b, the user is trying to style the list items of the menu through the `ui5-menu-item` subcomponents but the styles are not inherited to the popover's `ui5-li` items. Is there a way how this could be achieved and if not could you provide one.

Kind regards,
Nikolay

**Comment by NHristov-sap** [comment]
Hello @ej612 ,

The issue happens because the ui5-menu-item copmponents are 'dummy' components that are not rendered directly but are replaced by ui5-li components internally. That's why setting style or class to ui5-menu-item does not reflect on the rendered result. So for now we do not have solution for this case.

Whe have plans for changes in menu/menuitems, and we will take your case into consideration.

Best Regards,
Nikolay Hristov

**Comment by jacky-12** [comment]
Hello, does anyone know if this issue has been fix? I can't find any follow up information about this. Thanks
