### ISSUE TITLE
table sample on codesandbox

### ISSUE THREAD

**Issue by fopsdev** [SAP/ui5-webcomponents#630]
**Describe the documentation issue**

- [ ] Documentation is unclear
- [ ] Documentation is incorrect
- [ X] Documentation is missing
- [ ] Other

**Description of the issue**
Was playing the with the nice playground in codesandbox.
It's stated somewhere that one just could import a new component and then use that component.
I did that with table (as you can see in index.js) and i copy pasted the html from the get started guide. But there is only a grey area instead of a table header i guess.

Since it somehow works i assume this is a documentation issue

Here goes my sandbox:
https://codesandbox.io/s/ui5-webcomponents-7ljuf?fontsize=14

Btw. thanks for creating those components! :)

**Comment by ilhan007** [comment]
Hello  @fopsdev  we reworked the slotting between versions `0.11.0` and `1.0.0-rc.2`
and performed incompatible changes. That`s why the columns are not displayed.

1. Without changing any code in the example,
just change the ui5webcomponents version to the latest `1.0.0-rc.2` as shown below.
(perhaps you would need to refresh several times so codesandbox perform the changes)

<img width="473" alt="Screenshot 2019-07-07 at 8 36 15" src="https://user-images.githubusercontent.com/15702139/60764439-6e6fc980-a092-11e9-9bb2-27388f53c931.png">

and you will get the following result (expand the browser width as I see there is popin enabled and on small screens some of the columns would not be visible)

<img width="776" alt="Screenshot 2019-07-07 at 8 36 20" src="https://user-images.githubusercontent.com/15702139/60764499-ca871d80-a093-11e9-9007-ecb89b98c95b.png">

2. Still, If you want to make the example work with 0.11.0, you have to perform the following changes:
- replace `slot="columns"` with `data-ui5-slot="columns"`
- the content of the <ui5-table-column> should have `data-ui5-slot="header"`

<img width="909" alt="Screenshot 2019-07-07 at 8 46 32" src="https://user-images.githubusercontent.com/15702139/60764512-218cf280-a094-11e9-8312-3b3a7bd1a404.png">

**Comment by pskelin** [comment]
@fopsdev The main example sandbox was also updated (with the button and switch adapted to the latest APIs).
https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html

You can fork it again or update the ui5-webcomponents dependency to 1.0.0-rc.2 like @ilhan007 suggested above.

Thanks for reporting this.
