### ISSUE TITLE
UI5 Web Components React Update Findings

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents#6300]
Hi colleagues,

I just had brief chat with @ilhan007  and I wanted to share my findings of updating UI5 Web Components React to to the latest Web Components snapshot here:

### Card / CardHeader
Some properties of the `CardHeader` are in the API Doc of the `Card`. I think the `@name` tag should rather contain `CardHeader` than `Card`. 
Affected Props: `interactive`, `status`, `subtitleText`, `titleText`
Affected Slots: `action`, `avatar`

https://github.com/SAP/ui5-webcomponents/blob/a5abf6ef5b7bf5192f9b0adca92e48846aa755f0/packages/main/src/CardHeader.ts#L72-L110
https://github.com/SAP/ui5-webcomponents/blob/a5abf6ef5b7bf5192f9b0adca92e48846aa755f0/packages/main/src/CardHeader.ts#L126-L144

### FilterItem
`@name` should be `values` not `value`
https://github.com/SAP/ui5-webcomponents/blob/a5abf6ef5b7bf5192f9b0adca92e48846aa755f0/packages/fiori/src/FilterItem.ts#L55

### StepInput
`value-state-message` slot is gone
https://github.com/SAP/ui5-webcomponents/blob/a5abf6ef5b7bf5192f9b0adca92e48846aa755f0/packages/main/src/StepInput.ts#L306

### SuggestionItem and SuggestionGroupItem
SuggestionItem does not have any attributes anymore, all attributes are now part of the SuggestionGroupItem.
Incorrect `@name` tag?
https://github.com/SAP/ui5-webcomponents/blob/1d11e483327aeb9b740f928f63155b03f4c0ec1f/packages/main/src/SuggestionItem.ts#L23-L119

### ViewSettingsDialog
`filterItems` slot is missing. Missing `@name` tag?
https://github.com/SAP/ui5-webcomponents/blob/main/packages/fiori/src/ViewSettingsDialog.ts#L238-L247

### Missing default slot in the `apidoc.json`
- [ ] DynamicSideContent
- [ ] GroupHeaderListItem 
- [ ] Link
- [ ] MessageStrip
- [ ] Panel
- [ ] StandardListItem does not have default slot but image-content?

**Comment by ilhan007** [comment]
- Card / CardHeader, FilterItem, StepInput, SuggestionItem and SuggestionGroupItem, ViewSettingsDialog are addressed with https://github.com/SAP/ui5-webcomponents/pull/6301

- The "Missing default slot" section  - to be investigated

**Comment by MarcusNotheis** [comment]
## Missing instance methods in api.json:
- [ ] ColorPalettePopover: `openPopover`, `showAt`
- [ ] Dialog: `applyFocus`, `show`, `close` and `isOpen`
- [ ] DynamicSideContent: `toggleContents`
- [ ] Input: `openPicker` (is now a property?)
- [ ] Menu: `showAt`, `close`
- [ ] MultiInput: `openPicker` (is now a property?)
- [ ] Popover: `applyFocus`, `show`, `close` and `isOpen`
- [ ] ResponsivePopover: `applyFocus`, `show`, `close` and `isOpen`
- [ ] TimePicker: `closePicker`, `formatValue`, `isOpen`, `isValid`, `openPicker`
- [ ] ViewSettingsDialog: `setConfirmedSettings`, `show`

## Missing read-only properties
- [ ] DateRangePicker - `startDateValue`, `endDateValue`
- [ ] FileUploader: `files`
- [ ] TimePicker: `dateValue`

## Missing slots
- [ ] Input: `icon`
- [ ] MultiInput: `icon`

**Comment by ilhan007** [comment]
Remaining issues:

- [ ] Dialog - show() has now a mandatory parameter 'preventInitialFocus'
- [ ] the Popover showAt has now also a required second parameter preventInitialFocus
- [ ] the step input is missing the valueStateMessage
