### ISSUE TITLE
[SF][ui5-date-picker][1.8.0] Cannot trigger onChange event after clean value sometimes

### ISSUE THREAD

**Issue by i323808** [SAP/ui5-webcomponents#6303]
### **Bug Description**
Cannot trigger onChange event after clean value sometimes.

### **Expected Behavior**
onChange event is supposed to be fired once the value is changed.

### **Steps to Reproduce**
1. Go to https://codesandbox.io/s/datepicker-not-trigger-onchange-after-clean-value-sometimes-8ciigj?file=/src/App.js
2. Pick up a date via the pop-up calendar
3. Press Backspace key to clean value
4. Focus out from the DatePicker component

### **Isolated Example**
https://codesandbox.io/s/datepicker-not-trigger-onchange-after-clean-value-sometimes-8ciigj?file=/src/App.js 

### **Context**
- UI5 Web Components version: 1.8.0
- OS/Platform: macOS Ventura 13.1
- Browser: Chrome Version 109.0.5414.87 (Official Build) (x86_64)
- Affected component: ui5-date-picker

### **Log Output / Stack Trace / Screenshots**
```
{...}
```
### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by ndeshev** [comment]
Hello Hello @SAP/ui5-webcomponents-topic-b, the change event is not getting fired if the value is selected from the picker and then deleted. Could you please take a look, thanks.

Kind regards,
Nikolay
