### ISSUE TITLE
Typescript: use TSDoc instead of JSDoc

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents#6306]
### **Feature Request Description**
Currently we are using JSDoc for all the project, but at the sam time everything is rewritten in TS. 
We already experienced issues when mixing JSDoc and TS, we also had to do additional processing to make things work and build component api docs properly. That's why we would like to research and try using TSDoc as we expect to have better integration with TS. 

### **Proposed Solution**
Use [TSDoc](https://tsdoc.org/) instead of JSDoc

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: internal
- Business impact: {...}

**Comment by nnaydenow** [comment]
We decide to use custom-elements-manifest as common solution for web components docs.
