### ISSUE TITLE
List component or example not working

### ISSUE THREAD

**Issue by jaqmol** [SAP/ui5-webcomponents#6312]
### **Bug Description**
The HTML code examples using ui5-list with ui5-li from [the UI5 WebComponents website](https://sap.github.io/ui5-webcomponents/playground/components/List/) do not work. So either there's an issue with the example or the List component.

### **Expected Behavior**
The documentation should show clearly how to use the List component properly, or the List component should work as expected.

### **Steps to Reproduce**
Follow the [getting started, first steps from the UI5 WebComponents website.](https://sap.github.io/ui5-webcomponents/playground/getting-started/first-steps/):

1. npm init vite
2. enter a project name
3. select Lit as framework
4. cd into project directory
5. npm i -D @ui5/webcomponents
6. npm i for good measure
7. open src/my-element.ts
8. import '@ui5/webcomponents/dist/List';
9. import '@ui5/webcomponents/dist/ListItem';
10. add one of the example from [the UI5 WebComponents website](https://sap.github.io/ui5-webcomponents/playground/components/List/)
11. run npm run dev
12. see that no list is rendered

### **Isolated Example**
[Here is an isolated example in CodeSandbox](https://codesandbox.io/s/ui5-webcomponents-forked-hbkylg?file=/index.html).

### **Context**
- UI5 Web Components version: newest
- OS/Platform: all
- Browser: all
- Affected component: List, ListItem

### **Log Output / Stack Trace / Screenshots**
![Screenshot from 2023-01-19 17-48-48](https://user-images.githubusercontent.com/720314/213505730-68983eab-927a-4ba1-8f6a-fffa7905c3ec.png)

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

### Stakeholder
Everyone who is evaluating WebComponents might get put off by this. Lists are one of the main building blocks of applications.

**Comment by ndeshev** [comment]
Hello @jaqmol you should import 

```
import "@ui5/webcomponents/dist/StandardListItem.js";
import "@ui5/webcomponents-icons/dist/AllIcons.js";
```

alongside the List.js, instead of ListItem.js. There is also an example with `List `and `StandartListItems `imports in the documentation.

**Comment by ilhan007** [comment]
Hello @jaqmol y
just to add some info on the icons.

Whenever you are using an **icon** asset (not referring to the Icon web component which is part of the @ui5/webcomponents package, but to the displayed svg itself), you need to install one of the following packages, depending on the icon you would like to use:

Currently there are 3 icons collection, available as 3 npm packages:
[@ui5/webcomponents-icons](https://www.npmjs.com/package/@ui5/webcomponents-icons) represents the "SAP-icons" collection and includes the following [icons](https://sdk.openui5.org/test-resources/sap/m/demokit/iconExplorer/webapp/index.html#/overview/SAP-icons).
[@ui5/webcomponents-icons-tnt](https://www.npmjs.com/package/@ui5/webcomponents-icons-tnt) represents the "tnt" collection and includes the following [icons](https://sdk.openui5.org/test-resources/sap/m/demokit/iconExplorer/webapp/index.html#/overview/SAP-icons-TNT).
[@ui5/webcomponents-icons-business-suite](https://www.npmjs.com/package/@ui5/webcomponents-icons-business-suite) represents the "business-suite" collection and includes the following [icons](https://ui5.sap.com/test-resources/sap/m/demokit/iconExplorer/webapp/index.html#/overview/BusinessSuiteInAppSymbols).


Then, 
either import the specific icon (in this case "employee")
`import "@ui5/webcomponents-icons/dist/employee.js"`

or make all the icons available for usage (they will be dynamically loaded on demand, so no bundle size issues)
`import "@ui5/webcomponents-icons/dist/AllIcons.js";`

**Comment by jaqmol** [comment]
Big thanks! Works like a charm!
