### ISSUE TITLE
ui5-select change event throws an error in IE11

### ISSUE THREAD

**Issue by pskelin** [SAP/ui5-webcomponents#633]
**Describe the bug**
Jan Birkenhagen [12:48 PM]
When I register a eventlistener to the change event of the ui5-select, it never gets fired because of an (caught) exception. It's a Syntax error " 'return' statement outside of function" in the minified webcomponents polyfill.

**Comment by drasojem** [comment]
The same bug exists for the ui5-multi-combobox change, but not the selectionChange event.

**Comment by vladitasev** [comment]
Hello,

We weren't able to reproduce this behavior. Please check one of the test pages:
https://sap.github.io/ui5-webcomponents/master/test-resources/sap/ui/webcomponents/main/pages/Select.html

Open in IE and change the selection of the first ui5-select, then check the console.

Regards,
Vladi

**Comment by drasojem** [comment]
Hi,
I was able to get my code running by importing your bundle.es5.js, that you use in your example instead of transpiling the code from NPM using the babel-loader from webpack. How do you generate these bunldes? I would like to find out what I'm doing wrong.

Regards,
Jan

**Comment by MapTo0** [comment]
Hello @drasojem 

1. We are using rollup for our internal bundling - https://github.com/SAP/ui5-webcomponents/blob/master/packages/main/rollup.config.js#L105-L126
2. The following rollup plugins https://github.com/SAP/ui5-webcomponents/blob/master/packages/main/rollup.config.js#L37-L82

I wrote a big answer some times ago for an Angular application - https://github.com/SAP/ui5-webcomponents/issues/160
Most of the paths are probably different but the approach should be the same.

If you have any questions feel free to contact us.
