### ISSUE TITLE
Dialog: nested dialogs aren't rendered correctly in React

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#6344]
### **Bug Description**
When `ui5-dialog`s are nested inside a React app, the inner dialog is - depending on the implementation - rendered behind the outer one, or behind the block layer.

### **Expected Behavior**
The inner dialog should receive a higher z-index then the outer one and should not be displayed behind the block layer.

### **Steps to Reproduce**
1. Go to [codeSandbox](https://codesandbox.io/s/morning-sun-ey7clr?file=/src/App.js)
2. See that the inner dialog is rendered behind the block layer.
3. Try out the different examples and see the behavior as explained in the comment above

### **Isolated Example**
https://codesandbox.io/s/morning-sun-ey7clr?file=/src/App.js

### **Context**
- UI5 Web Components version: 1.10.0

### Additional Information
- This issue was raised in Slack: https://openui5.slack.com/archives/CSQEJ2J04/p1674466252144459
- This does not happen with plain js: https://codesandbox.io/s/ui5-webcomponents-forked-m27tib?file=/index.html

**Comment by kskondov** [comment]
Hello team @SAP/ui5-webcomponents-topic-rd,

Can you please take a look at how to handle this React issue with nested dialogs?

Best Regards,
Konstantin

**Comment by gmkv** [comment]
On initial investigation, it looks like using the new React DOM API - createRoot - is causing this:
 - react 17 https://codesandbox.io/s/pensive-clarke-ejprgt-17-ejprgt?file=/src/index.js
 - react 18 old render api:https://codesandbox.io/s/upbeat-shaw-0gjwxf-18-old-reactdom-api-0gjwxf?file=/src/index.js
 - react 18 new render api: https://codesandbox.io/s/upbeat-shaw-0gjwxf-18-new-reactdom-api-forked-957ngh?file=/src/index.js

**Comment by Lukas742** [comment]
Thanks for the clarification @gmkv.
