### ISSUE TITLE
TimePicker: incorrect onChange event detail

### ISSUE THREAD

**Issue by codefactor** [SAP/ui5-webcomponents#6345]
**Describe the bug**
In a typescript project that uses `<TimePicker>` the onChange event has detail type as `never` which is not correct. It should be similar to the `<DatePicker>` which has type `{value: string, valid: boolean}` - this requires developers to cast the detail to a custom interface to pull the updated value, since there is no other way to get the current value (note that using `e.target.value` returns the previous value in some cases prior to the change event start). This is not ideal, since it requires custom code to cast and it doesn't provide intellisense to discover how to get the value after a change event. The DatePicker and DateTimePicker seem to have it defined correctly but TimePicker is different for some reason.

**Isolated Example**
https://codesandbox.io/s/happy-thunder-zd9hdk?file=/src/App.js

**To Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-timepicker--default-story
2. Observe the Ui5CustomEvent types under `onChange`

**Expected behavior**
The type should be `(event: Ui5CustomEvent<TimePickerDomRef, { value: string; valid: boolean; }>) => void`

**Screenshots**

**UI5 Web Components for React Information**
`@ui5/webcomponents` version:
`@ui5/webcomponents-react` version:
Operating System:
Browser:

**Additional context**

**Comment by kskondov** [comment]
Hello @SAP/ui5-webcomponents-topic-b,

Can you take a look at this issue with missing documentation and onChange event detail type?

Best Regards,
Konstantin

**Comment by codefactor** [comment]
Just to clarify my primary concern was the typescript types are wrong. Though I presume the documentation is autogenerated based on the types so likely fixing the types will also fix the documentation.
