### ISSUE TITLE
sap.m.SelectDialog should support two way binding

### ISSUE THREAD

**Issue by milbhatt3990** [SAP/ui5-webcomponents#635]
**Is your feature request related to a problem? Please describe.**
I am using sap.m.SelectDialog inside a popover. This popover shows a list of entries, where user can select/deselect them.
Since these entries can be thousands in number, we have kept the initial threshold like 50. So every time the user scrolls down, the next set of 50 records are loaded in the popover. Selected entries are stored in a model so that it can be loaded back when the user reopens the popover. Moreover, SELECTED count in popover gets updated as soon as the user selects more and more entries.

Now, suppose the user selects entries at position 2, position 35 and position 500 in the popover. The SELECTED count shows "Selected:3", which is correct. 

He closes the popover and reopens it again. Now he can ONLY see "_Selected:2"_. Why? Because third entry he did select is at position 500, while popover only loads first 50 records when it opens. User needs to scroll down 10 times to reach at position 500, and now he can see _"Selected:3"_. 
Even though model has these 3 entries stored, it cannot implement it on Select dialog due to one-way binding. It needs to wait until user scroll downs to that particular entry.

This happens because select control only supports one-way binding. There is no workaround available. The only solution is we remove threshold from control, but it adversely affects entire app performance since it takes a long time to load all entries all-together.

**Describe the solution you'd like**
sap.m.SelectDialog should support two-way binding.

**Describe alternatives you've considered**
We temporarily removed the threshold. So it works, but also affects app performance.

**Comment by ilhan007** [comment]
Hello @milbhatt3990 
you probably filed the issue here by mistake. 

You would want to create this issue in the openui5 repository: https://github.com/SAP/openui5 (for issues with  libraries such as: sap.m, sap.f, sap.tnt, etc.).

We do not provide a SelectDialog.
To understand the difference between ui5-webcomponents and ui5, you can read the Readme.md of the current repository. 

Best,
ilhan
