### ISSUE TITLE
[SF][ui5-avatar-group]AvatarGroup is shrunk even though there is enough space left

### ISSUE THREAD

**Issue by BennyHuang** [SAP/ui5-webcomponents#6355]
### **Bug Description**
The avatar group is shrunk even though there is enough space left. 

**We reported the same issue before https://github.com/SAP/ui5-webcomponents/issues/5360. It worked fine after the fix until we upgraded to the latest chrome 109**.

### **Expected Behavior**
All the avatars in the group should be shown if there is enough space.

### **Steps to Reproduce**
There are 2 cases in our application
 **case 1**
<img width="1039" alt="image" src="https://user-images.githubusercontent.com/1995447/173464305-f82dae18-bc07-45ff-8bd2-4bc57e140041.png">
**case 2**
<img width="725" alt="image" src="https://user-images.githubusercontent.com/1995447/173466093-050eeb1d-f264-42de-9c00-ac272a0d6fb5.png">

### **Isolated Example**
It can be reproduced on https://codesandbox.io/s/avatargroup-shrunk-forked-efp8r0?file=/src/App.js
<img width="715" alt="image" src="https://user-images.githubusercontent.com/1995447/214436534-06932513-ea85-4b02-8a11-649ab18acca0.png">

It can also be reproduced in full width window on https://efp8r0.csb.app/

### **Context**
 - @ui5/webcomponents version: 1.9.1
 - @ui5/webcomponents-react version:1.5.0
 - Operating System: MacOS
 - Browser: Chrome 109

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SF

**Comment by kskondov** [comment]
Hello @SAP/ui5-webcomponents-topic-p ,
This issue with the AvatarGroup is reproducible again with the latest Chrome version. Works fine on FireFox and Safari.
Best regards,
Konstantin

**Comment by BennyHuang** [comment]
Hi @PetyaMarkovaBogdanova, could you please expedite the fix and release a patch version for 1.9?  It is outstanding issue and customers are using actively in our demos. Thanks.

**Comment by ilhan007** [comment]
Hello @BennyHuang,  the fix has been downported as 1.9.4.

**Comment by BennyHuang** [comment]
Hi @ilhan007 after upgrading library from 1.9.1 to 1.9.4. I am seeing below error while running unit test. I believe it is introduced by https://github.com/SAP/ui5-webcomponents/pull/5962 released in 1.9.2. Could you help to check? Thanks

`    TypeError: Class extends value #<Object> is not a constructor or null

    > 1 | import {
        | ^
      2 |   ActionSheet,
      3 |   Avatar,
      4 |   AvatarGroup,

      at Object.<anonymous> (node_modules/@ui5/webcomponents/dist/TreeList.js:7:24)
      at Object.<anonymous> (node_modules/@ui5/webcomponents/dist/Tree.js:6:1)
      at Object.<anonymous> (node_modules/@ui5/webcomponents-fiori/dist/SideNavigation.js:6:1)
      at Object.<anonymous> (node_modules/@ui5/webcomponents-react/dist/webComponents/SideNavigation/index.js:1:1)
      at Object.<anonymous> (node_modules/@ui5/webcomponents-react/dist/webComponents/index.js:68:1)
      at Object.<anonymous> (node_modules/@ui5/webcomponents-react/dist/components/ActionSheet/index.js:22:1)
      at Object.<anonymous> (node_modules/@ui5/webcomponents-react/dist/index.js:2:1)
      at Object.<anonymous> (src/components/OKRItem/OKRItem.tsx:1:1)
      at Object.<anonymous> (src/components/OKRItem/index.ts:1:1)
      at Object.<anonymous> (src/components/OKRItem/__test__/OKRItem.test.tsx:6:1)`

**Comment by ilhan007** [comment]
Hello @BennyHuang I would need more details.

I found the the [PR](https://github.wdf.sap.corp/xweb/dynamic-teams/pull/635) for upgrading to 1.9.4 but I can't login to see the build details. We would need to see it together via the internal or at least point us to the failing test (test file in the repo and exact assert that is failing)

**Comment by BennyHuang** [comment]
@ilhan007 we are still seeing this issue after upgrading to 1.10.5. Can you please help to check and release to 1.10.x? We need to upgrade to 1.10.5 to take some fix. Thanks
