### ISSUE TITLE
SideNavigation: scoping breaks component in collapsed mode

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#6361]
### **Bug Description**
When scoping is applied to the `SideNavigation` component, the popover showing `SideNavigationSubItem`s in collapsed mode throws an error.

### **Expected Behavior**
The SideNavigation should work in the same way with and without scoping.

### **Steps to Reproduce**
1. Go to [codeSandbox](https://codesandbox.io/s/ui5-webcomponents-forked-08o7xd?file=/index.html)
2. Click on one of the SideNavigationItems having sub-items.
3. See that there is an error thrown.

### **Isolated Example**
https://codesandbox.io/s/ui5-webcomponents-forked-08o7xd?file=/index.html

### **Context**
- UI5 Web Components version: 1.10.3

### **Priority**
- [ ] Low
- [ ] Medium
- [ ] High
- [x] Very High

I marked it with a "Very High" priority, as this bug is preventing us from updating an internal application to the latest ui5wc version.

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: UI5 Web Components for React (MXP org)

**Comment by kskondov** [comment]
Hello @SAP/ui5-webcomponents-topic-rd ,
This issue with side navigation is reproducible with react, follow the steps described by the author, not reproducible with plain javascript.
Best Regards,
Konstantin

**Comment by Lukas742** [comment]
Hi @kskondov 

the linked codeSandbox uses plain javascript.

**Comment by dimovpetar** [comment]
Hello @SAP/ui5-webcomponents-core ,

With this PR https://github.com/SAP/ui5-webcomponents/commit/e0e13e11d26abbcb2746e4abd1c72d312212ebaf we replaced `ui5-list` with `ui5-side-navigation` inside [SideNavigationItemPopoverContent.hbs](https://github.com/SAP/ui5-webcomponents/commit/e0e13e11d26abbcb2746e4abd1c72d312212ebaf#diff-2c6908f137775f474771b864b1e56586132b0a5a49e236a8f775b3451939699d).
In normal circumstances this works fine. However, when you activate scoping, the `shadowRoot` of the SideNavigation becomes empty. This is where the errors come from.
On top, this is rendered inside the static area, which contributes to the problem. I tried to use SideNavigation in Popover without scoping and without static area and it worked.
So please check why the combination of Popover+SideNavigation+Static Area+Scoping doesn't work. If there is anything that we need to change, let us know.

Best regards,
Petar
