### ISSUE TITLE
Provide the ability to set legacy date calendar customizing

### ISSUE THREAD

**Issue by allen138** [SAP/ui5-webcomponents#6363]
### **Feature Request Description**
OpenUI5 allows the consumer to add a custom date mapping for Islamic calendar support. This can be done by getting the format settings and calling, `setLegacyDateCalendarCustomizing`. [sap/ui/core/Configuration.js#L2558](https://github.com/SAP/openui5/blob/1.108.2/src/sap.ui.core/src/sap/ui/core/Configuration.js#L2558) When the DateFormat tries to format/parse a date it will utilize the mapping here, [src/sap/ui/core/date/Islamic.js#L215](https://github.com/SAP/openui5/blob/1.108.2/src/sap.ui.core/src/sap/ui/core/date/Islamic.js#L215). Since UI5-webcomponent internally uses the `sap.ui.core.format.DateFormat`, we need the ability to add a custom date mapping to support Islamic calendar. Right now, when the formatter tries to get the customized mapping, it is hard coded to return an empty object. [localization/src/sap/ui/core/FormatSettings.ts#L11](https://github.com/SAP/ui5-webcomponents/blob/main/packages/localization/src/sap/ui/core/FormatSettings.ts#L11)

### **Proposed Solution**
Consumer should have a way to set a custom date mapping for Islamic calendar support.

### **Additional Context**
Islamic calendar could either be Hijri ('civil') or Umm-al-Qura which is astronomical based off of the sighting of the crescent moon. The Umm-al-Qura is the standardized calendar system used throughout most Saudi Arabia countries. The two systems can have a difference up to 3 days. Using a calendar mapping is vital to providing accurate Umm-al-Qura support.

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: SF
- Business impact: Medium

**Comment by kskondov** [comment]
Hello team @SAP/ui5-webcomponents-core ,
Can you please take a look at this feature request as it is regarding format settings and configuration.
Best Regards,
Konstantin
