### ISSUE TITLE
[SAP] [Accessibility] [ShellBar | DateRangePicker | AnalyticalTable] : No keyboard support

### ISSUE THREAD

**Issue by vraguna** [SAP/ui5-webcomponents#6370]
**Describe the bug**
There is no keyboard support for the subcomponent within the following main components

- The "Open Picker" in the DateRangePicker component
- The combo box in the AnalyticalTable component
- Clickable items within the ShellBar popover

The above components are not focusable using keyboard.

**Steps to reproduce the behavior:**

Open Google Chrome
Go to the corresponding examples 
[Open Picker](https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-daterangepicker--default-story)

![image](https://user-images.githubusercontent.com/42251879/214940598-2499a68e-8db0-4257-9203-8a89a54207b0.png)

[Combo box](https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-analyticaltable--plugin-use-on-column-resize)

![image](https://user-images.githubusercontent.com/42251879/214941287-81b0ba1b-843b-4633-8ded-5681af77aed6.png)

[Clickable Items in the popover](https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-shellbar--with-customizable-shell-bar-item)

![image](https://user-images.githubusercontent.com/42251879/214940628-afcb0335-e6e3-4978-bdea-47759ce63e46.png)

Click on the Keyboard tab to get the focus on each of the above components.

You can notice the sub components are not focusable.

Expected Behavior:
Clickable elements must be focusable

**Comment by Lukas742** [comment]
Hi @vraguna 

the `AnalyticalTable` is not a web-component. Also the component you marked in the screenshot is not a `ComboBox` but a `CheckBox`. If this issue is about this checkbox, it's not meant to be focusable as it's only considered a informative icon. If you focus the selection-cell, the appropriate description is read out by screen readers and by pressing Space/Enter you can select the row. If you're still feeling that this is not correctly implemented, please open an [issue](https://github.com/SAP/ui5-webcomponents-react/issues/new/choose) in our (ui5-webcomponents-react) repo, so we can track this better.

**Comment by kskondov** [comment]
Hello @vraguna,

You have reported issues for several components in one message. As different components may need to be processed by separate members of our Development Support this can lead to delays in the solution process.
By logging separate issues, each issue can be specifically assigned to the appropriate processor. In this way, the problems that you are experiencing can be dealt with more quickly.
I was able to reproduce the first issue with the date picker and will bring it up to our accessibility experts. If possible can you separate it in another issue.
For the AnalyticalTable the selection cell is accessible via the arrow keys and selection can be achieved as mentioned  by @Lukas742.
The third issue was not reproducible with the provided information and sample. Can you please if possible isolate it in a [code sandbox](https://codesandbox.io/) and open another issue regarding this specific web-component.

Best Regards,
Konstantin

**Comment by vraguna** [comment]
Thanks, @kskondov and @Lukas742 for the above comments. I have created a separate issue for each component as suggested.

**Comment by dobrinyonkov** [comment]
Thanks @vraguna, we will close this issue now. Let us know if you encounter any issues with those components.
