### ISSUE TITLE
Vue 4b missing vite config example

### ISSUE THREAD

**Issue by p-mathias** [SAP/ui5-webcomponents#6371]
### **Issue Description**
in chapter 4b is descripte how the webpack config need to be extend,
vue 3 project use vite as default builder,
so an example how to define the config this build would be nice.

### **Issue Type**

- [ ] Documentation is unclear
- [ ] Documentation is incorrect
- [x] Documentation is missing
- [ ] Other

https://github.com/SAP/ui5-webcomponents/blob/6453d49bdf07a2274f5c384d549fcf61e6eff82c/docs/4-frameworks/03-Vue.md?plain=1#L32-L49

**Comment by kskondov** [comment]
Hello @SAP/ui5-webcomponents-topic-core , can you please consider this request for extending the documentation?
Best Regards,
Konstantin

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-core 

It seems the Vue team provides a start up project create-vue on top vite - now the official recommendation when you start new Vue 3 projects. So, it makes sense to update or extend our vue app development section.

On first look, we can add an example with  vit config (currently we show-case webpack):

```js
// vite.config.js
module.exports = {
  vueCompilerOptions: {
    isCustomElement: tag => tag.startsWith('ui5-')
  }
}
```

We need to start up  vue 3.x project and give it a try.

Hello @p-mathias does the suggested vite config work for you?

**Comment by p-mathias** [comment]
the default vite.config.js without ts look like so:
```js
import { fileURLToPath, URL } from 'node:url'

import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    vue()
  ],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url)),
    },
  },
})
```

i changed to
```js
import { fileURLToPath, URL } from 'node:url'

import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    vue({
      template: {
        compilerOptions: { isCustomElement: (tag) => tag.startsWith('ui5-') },
      },
    }),
  ],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url)),
    },
  },
})
```

i also tested the steps mention here:
https://sap.github.io/ui5-webcomponents/playground/frameworks/vue/

that the most time  npm is used (which is fine) and in the end step yarn is not helpfull.

Also the information about "Two-Way Data Binding" is wrong in general, (maybe for sapui5 valid),
but in general it's work fine for custom components.

I find the way unnessary complex in compare to this approache here:
https://vuetifyjs.com/en/getting-started/installation/#manual-steps

specialy for the case that components no import is need any more.
