### ISSUE TITLE
tnt-github icon not available for import

### ISSUE THREAD

**Issue by sachinbhutani** [SAP/ui5-webcomponents#6376]
### **Bug Description**
according to the icons-tnt package, all icons listed here should be available 
https://sdk.openui5.org/test-resources/sap/m/demokit/iconExplorer/webapp/index.html#/overview/SAP-icons-TNT
Not able to import the github icon from tnt package as it's not included.

### **Expected Behavior**
A clear and concise description of what you expect to happen.

import "@ui5/webcomponents-icons-tnt/dist/github" does not work for https://sdk.openui5.org/test-resources/sap/m/demokit/iconExplorer/webapp/index.html#/overview/SAP-icons-TNT/?tab=grid&search=github&icon=github 

### **Steps to Reproduce**
1. create a new <ui5-icon name="tnt/github"> component with import "@ui5/webcomponents-icons-tnt/dist/github"

### **Isolated Example**
If possible, please provide an isolated example by forking [CodeSandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html).

### **Context**
- UI5 Web Components version: {...}
- OS/Platform: {...}
- Browser: {...}
- Affected component: {...}

### **Log Output / Stack Trace / Screenshots**
```
{...}
```
### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by dobrinyonkov** [comment]
Hello @SAP/ui5-webcomponents-core team,

importing the @ui5/webcomponents-icons-tnt/dist/github icon throws an error that can be seen here:
https://codesandbox.io/s/ui5-webcomponents-forked-noofyx?file=/src/index.js

The same icon works in openui5: https://jsbin.com/lulenecuxu/edit?html,output

Could please take a look into this issue?

Kind Regards,
Dobrin
