### ISSUE TITLE
Card: Remove shadow on hover

### ISSUE THREAD

**Issue by I347684** [SAP/ui5-webcomponents#6381]
**Describe the bug**
Hello, I'm trying to remove the box-shadow on hover and active from the Card.

So I should be able to overwrite this classes:

```
.ui5-card-root:active {
    box-shadow: var(--_ui5_card_box_shadow);
}

.ui5-card-root:hover {
    box-shadow: var(--_ui5_card_hover_box_shadow);
}
```

I tried the CSS Shadow Parts like this:

```
ui5-card::part(root):hover:active {
    box-shadow: none;
}
```

Create a sap.css file and imported the file in the App.tsx
import './sap.css'

Also tried to overwrite the css var and the class itself

`--sapContent_Shadow2: '0 0 0 0'`

```
.ui5-card-root:active {
    box-shadow: none
}

.ui5-card-root:hover {
    box-shadow: none
}
```

Nothing happens, the box shadow continue to be there on hover. Please advice.

**Comment by I347684** [comment]
@Lukas742 the card itself exposes a shadow in the class ui5-card-root:hover as you can see from the image. 

<img width="1765" alt="Screenshot 2023-01-30 at 13 57 30" src="https://user-images.githubusercontent.com/35697392/215497302-6bff3d24-493a-4cc6-9791-f272b3890178.png">

In the [documentation](https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-card--default-story) the last part mentions the Card Shadow Parts, "The Card exposes the following CSS Shadow Parts".

I tried to do this, as I mention in the previous comment, and no effect.

**Comment by Lukas742** [comment]
This is what I meant with "empty Shadow Parts" section. I didn't argue that the Card is a web-component thus containing a shadow-root. I only pointed out, that you read the description of the `CardHeader`, as the `Card` doesn't seem to have a `root` part or any part attribute at all.

<img width="1166" alt="image" src="https://user-images.githubusercontent.com/9749730/215528999-97fa634b-838b-401d-9cec-549d0969e318.png">

**Comment by Todor-ads** [comment]
Hello @SAP/ui5-webcomponents-topic-rd,
take a look at this issue.

Best Regards,
Todor

**Comment by LidiyaGeorgieva** [comment]
Hello @I347684 ,

We work on changes on the focus for Horizon theme when the card has no interactions.
If this is your case please follow the progress in Jira: FIORITECHE1-7015

If not - please describe what you need to achieve and we will review it as new Feature request.

Currently the only possible solution is to change "--sapContent_Shadow0" for active and "--sapContent_Shadow2" for hover, but this will affect not only Card component, but the other components, that use them. Also other themes can be affected. We do not recommend changing those parameters.

Best Regards,
Lidiya

**Comment by LidiyaGeorgieva** [comment]
Hello @I347684 , then I would suggest to wait for our changes.

**Comment by Abneco** [comment]
temporarily for those who want a half solution I have modified the variables as follows:

````css

    /* node_modules/@ui5/webcomponents-theming/dist/themes/sap_horizon/css_variables.css */
    --sapContent_Shadow0: 0 0 0.125rem 0 rgba(85,107,130,0.16), 0 0.125rem 0.25rem 0 rgba(85,107,130,0.16) !important;
    --sapContent_Shadow2: 0 0 0.125rem 0 rgba(85,107,130,0.16), 0 0.125rem 0.25rem 0 rgba(85,107,130,0.16) !important;

    /* or according to your preference */

    /* node_modules/@ui5/webcomponents-theming/dist/themes/sap_fiori_3/css_variables.css */
    --sapContent_Shadow0: 0 0 0 0.0625rem rgba(0, 0, 0, 0.1), 0 0.125rem 0.5rem 0 rgba(0, 0, 0, 0.1) !important;
    --sapContent_Shadow2: 0 0 0 0.0625rem rgba(0, 0, 0, 0.1), 0 0.125rem 0.5rem 0 rgba(0, 0, 0, 0.1) !important;

````

**Comment by gmkv** [comment]
@Abneco those variables are used in more components other than the card.
https://github.com/search?q=repo%3ASAP%2Fui5-webcomponents+--sapContent_Shadow0&type=code
https://github.com/search?q=repo%3ASAP%2Fui5-webcomponents+--sapContent_Shadow2&type=code

I wouldn't recommend to modifying them.

**Comment by gmkv** [comment]
Hi @I347684 
The card's hover states were updated. Now (at the time of writing this), the only time the card will have a box-shadow for hovering is when the CardHeader has the property `interactive` set to `true`. Please see #6962

This change will be available in the next release of this library.
