### ISSUE TITLE
Dialog: Remove overlapping additional Border 

### ISSUE THREAD

**Issue by reqyou** [SAP/ui5-webcomponents#6383]
**Describe the bug**
Invalid border in footer bar. In case a Bar (e.g. Footer Bar) is applied for Dialogs there should no additional border-top. 

Please also check the header. Here something similar may occur too. 

**Isolated Example**
[see your demo](https://sap.github.io/ui5-webcomponents-react/?path=/docs/modals-popovers-dialog--default-stor)

**To Reproduce**
1. Go to 'Open Dialog'
2. Check Border of Footer Component

**Expected behavior**
There should be no additional border for the Footer border in case a Bar is applied. 

**Screenshots**
![image](https://user-images.githubusercontent.com/101811919/215473807-ac5736e3-94fd-4262-acf3-0e7dedbfb77c.png)

**UI5 Web Components for React Information**
latest

**Additional context**

**Comment by reqyou** [comment]
Sorry that I posted it here, I just selected the wrong repo, wasn't intended. Thanks for forwarding it.

**Comment by Todor-ads** [comment]
Hello @SAP/ui5-webcomponents-topic-b,
Can you look into this issue?

Best Regards,
Todor

**Comment by rchrdchn** [comment]
Hi guys - I understand this is a duplicate issue. I have the same and it's been opened for over half a year. Could you provide any updates on it, please?

**Comment by tsanislavgatev** [comment]
Hello colleagues,

This issue is fixed in latest version.
It can be tested here: https://sap.github.io/ui5-webcomponents/playground/components/Dialog/

Best Regards,
Tsanislav
