### ISSUE TITLE
Adding child elements for Split Button

### ISSUE THREAD

**Issue by gb-githb** [SAP/ui5-webcomponents#6389]
### **Issue Description**
* Unclear on how to add child elements for Split Button 
* For SAPUI5 documentation , it shows how to add child elements https://ui5.sap.com/#/entity/sap.m.MenuButton/sample/sap.m.sample.MenuButton
* Whereas, for UI5 Web Component it does not cover the sample code for adding child element to Split Button https://sap.github.io/ui5-webcomponents/playground/components/SplitButton/
 
### **Issue Type**

- [x] Documentation is unclear
- [ ] Documentation is incorrect
- [x] Documentation is missing
- [ ] Other

**Comment by Todor-ads** [comment]
Hello @gb-githb,
Thanks for reporting!
A MenuButton will be added to the ui5-webcomponent soon, and then the provided examples will be expanded.
You can find information about MenuButton here - https://github.com/SAP/ui5-webcomponents/issues/1436

Best Regards,
Todor
