### ISSUE TITLE
[SF_ACC][ui5-input] Input placeholder does not ellipse properly when input is focused

### ISSUE THREAD

**Issue by lormanlau** [SAP/ui5-webcomponents#6393]
### **Bug Description**
When the placeholder of the input is very long and overflows the placeholder text will not ellipse when the input is focused

### **Expected Behavior**
A clear and concise description of what you expect to happen.
Input placeholder should stay ellipsed when the component is focused

### **Steps to Reproduce**
1. Create input with a long placeholder which overflows
2. verify that the placeholder text is ellipsed
3. click on or focus on the input
4. verify that the placeholder text is now not ellipsed

### **Context**
- UI5 Web Components version: {1.10.0}
- OS/Platform: {macOS}
- Browser: {Chrome}
- Affected component: {ui5 input}

### **Log Output / Stack Trace / Screenshots**
![Screenshot 2023-01-31 at 4 37 16 PM](https://user-images.githubusercontent.com/12117112/215919490-fdd0ac4c-4698-4afd-92f0-295317c5f733.png)
![Screenshot 2023-01-31 at 4 37 22 PM](https://user-images.githubusercontent.com/12117112/215919492-e105792d-eaff-4cfa-96ca-18a516448e80.png)

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SAP SuccessFactors
- Business impact: Medium

**Comment by Todor-ads** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,
take a look at this issue.

Best Regards,
Todor

**Comment by MapTo0** [comment]
Hello Colleagues,

This is a browser behaviour which we can not technically change.
Example with native input: https://jsbin.com/hiqeneviti/edit?html,output

Regards,
Martin
