### ISSUE TITLE
OpenUI5Support/openUI5 1.102.10 Incompatibilities : it fails in Invoking getThemeRoot

### ISSUE THREAD

**Issue by louologuem** [SAP/ui5-webcomponents#6404]
### **Bug Description**
In an application using `openUI5@1.102.10`, the usage of the UI5/webcomponent-react/ThemeProvider class leads to a failure in OpenUI5Support.
More precisely; the failing statement is `config.getThemeRoot()`

### **Expected Behavior**
`OpenUI5Support` (feature support unit) should initialize succesfully.

### **Isolated Example**
If possible, please provide an isolated example by forking [CodeSandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html).

### **Context**
- UI5 Web Components version: `1.9.3`
- OS/Platform: `*`
- Browser: `any`

Browser: Edge 109.0.1518.70
### **Log Output / Stack Trace / Screenshots**
```
{...}
```
### **Priority**
- [ ] Low
- [ ] Medium
- [X] High
- [ ] Very High

- Organization: SAP

**Comment by louologuem** [comment]
@Todor-ads ,
while waiting for the practical how-to-repeat, here are some screenshots of the callstack when the error occurs: 
![OpenUi5Support](https://user-images.githubusercontent.com/82609888/217560818-5dfd4cdf-e4ec-42b6-abe9-1a88a133b227.PNG)

![OpenUi5SupportIssue-callstack2](https://user-images.githubusercontent.com/82609888/217561530-f03b13e6-4b9e-439e-a032-f44257fe4538.PNG)

**Comment by niyap** [comment]
Hi @louologuem ,

Could you please provide us an isolated example in [CodeSandbox](https://codesandbox.io/) with your configuration and the reproducible issue and a step-by-step guide on how to reproduce the issue?

Regards,
Niya
