### ISSUE TITLE
Avatar color changes inside AvatarGroup vs Avatar standalone

### ISSUE THREAD

**Issue by evyatar11** [SAP/ui5-webcomponents#6405]
### **Bug Description**
On the default theme(sap-theme=sap_quartz) but also on all the other themes.
When rendering a standalone Avatar with a colorScheme='Accent6' the color is Blue.
When rendering an Avatar with the same props under AvatarGroup the color is changed to Orange.

### **Expected Behavior**
An Avatar with identical configurations should be rendered similarly as standalone and inside an AvatarGroup

### **Context**
- UI5 Web Components version: 1.10.3"
- Browser: Chrome

### **Priority**
- [x] Medium

Code example:

![image](https://user-images.githubusercontent.com/11410956/216298165-f0c9c4fa-9ac2-4ec0-9ff6-91212927a770.png)

Result in the UI:

![image](https://user-images.githubusercontent.com/11410956/216298391-1117f734-e1b0-42dc-93db-ab34ef62789b.png)

**Comment by Todor-ads** [comment]
Hello @evyatar11,
Thanks for reporting! Can you isolate the described scenario? I can't reproduce it

Best Regards,
Todor

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-p could you take a look of this issue - details in the previous comments.

**Comment by evyatar11** [comment]
Hi, I've tested it again with version 1.10.4(The version that should include the fix)and I still experience the same issue

**Comment by dobrinyonkov** [comment]
Hi @evyatar11, the fix seems not to be released with 1.10.4 but with [v1.11.0-rc.1](https://github.com/SAP/ui5-webcomponents/releases/tag/v1.11.0-rc.1) .
Can be seen working well here: https://codesandbox.io/s/ui5-webcomponents-forked-7uvmwr?file=/index.html

**Comment by i349810** [comment]
Hi @dobrinyonkov, thanks for clarifying!
Can you please update when this fix is expected to be released (RTC)?

**Comment by ilhan007** [comment]
Hello @i349810 by the end of the week, if all checks are green and no issues are found
