### ISSUE TITLE
ui5-tabcontainer - tab is selected in a collapsed tab container, ui5-tab "title" attribute doesn't work 

### ISSUE THREAD

**Issue by TeodorTaushanov** [SAP/ui5-webcomponents#6406]
### **Expected Behavior**
Expected Behavior  
- If you have a collapsed tab container, no tab should be selected 
- "title" attribute of ui5-tab should work 

### **Steps to Reproduce**
1. Go to https://codesandbox.io/s/ui5-webcomponents-forked-q23eqo
2. Collapse the tab container content
3. A tab is selected, but it shouldn't be
4. First tab doesn't have a tooltip

### **Priority**
- [x] Low
- [ ] Medium
- [ ] High
- [ ] Very High

**Comment by gmkv** [comment]
As first step we should mark the Tab and TabSeparator as `@abstract` to better illustrate that this element, should ideally, not receive inline styles or extra attributes, etc, like the title attribute. This comes from #6220.
After that, we could discuss how to provide the tooltips - rendering our own title attributes to the elements generated in TabInStrip.hbs and TabInOverflow.hbs - while preventing the title attribute being shown in the content, because that is where the Tab element is actually placed.

**Comment by TeodorTaushanov** [comment]
- If you have a collapsed tab container, no tab should be selected

We'll keep the selection indicator, when the content is collapsed, as we want tab selection, when  the control is always collapsed. In the OpenUI5 they is a different control for that.

**Comment by TeodorTaushanov** [comment]
Hi @blaesius,

OpenUI5 IconTabHeader control:
https://ui5.sap.com/#/entity/sap.m.IconTabHeader/sample/sap.m.sample.IconTabHeader

This functionality can be achieved in ui5 web components by:

`<ui5-tabcontainer collapsed fixed>`

https://codesandbox.io/s/ui5-webcomponents-forked-psue9q

Best,
Teo

**Comment by TeodorTaushanov** [comment]
For me this is an unnecessary complication and it will leads to confusion when exactly the selection is shown or not. 

Anyway if you think this will help for the control usability, reopen the issue an we'll improve this.

**Comment by blaesius** [comment]
If you can collapse and expand the Tab Container, the selection must only be visible while the Tab is expanded. The standalone Tab Container Header is a special use case and only for this use case the other behavior (having always the selection shown) can apply. This can either happen automatically or via a property.

As we are mixing multiple existing UI5 controls in this Web Component. To be consistent, we need to apply the same behavior for UI5 and WC. This means, if you can expand/collapse the Tab Container, the selection should only appear if the container is expanded (see https://ui5.sap.com/#/entity/sap.m.IconTabBar/sample/sap.m.sample.IconTabBarMulti)

Another solution would also be to remove the expand/collapse feature.

**Comment by TeodorTaushanov** [comment]
@blaesius, I would go for removing the expand/collapse via mouse/keyboard feature, but keep it as an API. So the ui5-tabcontainer will be always "fixed".

**Comment by blaesius** [comment]
Yes, that sounds good

**Comment by TeodorTaushanov** [comment]
Added to #4460 2.0 breaking changes list.
