### ISSUE TITLE
broken playground link

### ISSUE THREAD

**Issue by nicoschoenteich** [SAP/ui5-webcomponents#6407]
### **Issue Description**

Hi all, the link to the [playground link](https://sap.github.io/ui5-webcomponents/playground/getting-started/first-steps/playground/docs/) in the [getting started section](https://github.com/SAP/ui5-webcomponents/blob/main/docs/1-getting-started/01-first-steps.md#documentation) throws a 404. Best, Nico

### **Issue Type**

- [ ] Documentation is unclear
- [ ] Documentation is incorrect
- [ ] Documentation is missing
- [x] Other

**Comment by Todor-ads** [comment]
Hello @SAP/ui5-webcomponents-core,
could you please look at this issue with broken link to Playground?

Best Regards,
Todor

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-core 


Wee need to check all links in docs folder via Github (links to external resources, links to next chapter)

For example, if you go to https://github.com/SAP/ui5-webcomponents/blob/main/docs/1-getting-started/01-first-steps.md
and use the Next: [Importing UI5 Web Components](https://github.com/SAP/ui5-webcomponents/blob/main/docs/importing-components) - you will get page not found.

However, the links seems to be constructed this way for the purpose of the Playground. So if we just change the links to reference the corresponding file name, this will work here, but we will break the links in the docs when they are visited and read in the Playground. So, we need to fix them but also add post-processing for the purpose of the Playground
