### ISSUE TITLE
Getting an error while building an application on BTP with Honeycomb 

### ISSUE THREAD

**Issue by gb-githb** [SAP/ui5-webcomponents#6411]
### **Bug Description**
Getting an error while building an application on BTP with Honeycomb 

### **Expected Behavior**
Should build the application with Honeycomb

### **Steps to Reproduce**
NA

### **Isolated Example**
NA

### **Context**
- UI5 Web Components version: 1.10.3
- OS/Platform: Business Application Studio
- Browser: Chrome
- Affected component:  @sap-theming/theming-base-content
### **Log Output / Stack Trace / Screenshots**
Unable to build the application and its getting failed with message:
warn tarball tarball data for @sap-theming/theming-base-content@https://int.repositories.cloud.sap/artifactory/api/npm/build-snapshots-npm/@sap-theming/theming-base-content/-/theming-base-content-11.1.48.tgz (sha512-Q2rMoEN+6tjnfbhlQ2a+WybhAWj/0RuhWUb3vSzI/iwCkGPGtz3k8HhtU1jtmAPjRCiJQSEmiE2HMv3Av/7Y7Q==) **seems to be corrupted. Trying again.**

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SAP
- Business impact: High

**Comment by dobrinyonkov** [comment]
Hello @gb-githb, 

indeed, this looks like an issue with the @sap-theming dependency but we can't be sure. 
Could you please provide more context about this issue?
What is the build step, what script is it called, can this be reproduced locally or in any test environment we can access?

Thanks and Best Regards,
Dobrin

**Comment by gb-githb** [comment]
Hello @dobrinyonkov ,
 
I get to know Honeycomb supports 16 , so by decreasing the Node Version for Project , it has built successully.
Thanks a lot for the help !

- Brijesh Gandhi
