### ISSUE TITLE
[SF][MessageStrip]: Message strip cannot be closed

### ISSUE THREAD

**Issue by yuyuCream** [SAP/ui5-webcomponents#6422]
### **Bug Description**
Message strip cannot be disappeared after clicking close button.

### **Expected Behavior**
Message strip can be disappeared after clicking close button.

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-messagestrip--default-story
2. Click close button of messagestrip.

### **Context**
- UI5 Web Components version: 1.8.1
- OS/Platform: mac
- Browser: Chrome
- Affected component: Messagestrip

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

### **Additioncal Context** 
I am from SAP Successfactors. And issues are for b2305 released project.

**Comment by dobrinyonkov** [comment]
Hello @yuyuCream, 

the `ui5-message-strip` component only fires the `close` event and it is up to the application to remove the component from the DOM.

**Comment by yuyuCream** [comment]
Hi @dobrinyonkov  
In the [fiori guide](https://experience.sap.com/internal/fiori-design-web/message-strip/#interactive-behavior) , it mentioned that "Clicking the  Close button on the right-hand side hides the message strip." And the behavior of [messagestrip](https://sapui5.hana.ondemand.com/#/entity/sap.m.MessageStrip/sample/sap.m.sample.MessageStrip) component in sapui5 also follows the guide. I think it should be provided by ui5-webcomponents.

**Comment by dobrinyonkov** [comment]
Hi @SAP/ui5-webcomponents-topic-rl, this feature reqest is about the MessageStrip component. The user wants the `ui5-message-strip` to close automatically when the close button is pressed. 

Could you please take a look?

**Comment by MapTo0** [comment]
Hello Colleagues,

We have provided events to control whether the Message Strip should be closed or not.
Some users prefer to do other actions when the close button is clicked such as "Are you sure you want to close this?" like message, etc.

Therefore I would suggest you to follow the example we have provided in the playground how to implement that in your application: https://sap.github.io/ui5-webcomponents/playground/components/MessageStrip/

Regards,
Martin
