### ISSUE TITLE
Avatar: icon gets cut off

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents#6425]
### **Bug Description**
the "attachment" icon (possibly others), displayed in the Avatar, gets cut off.
<img width="408" alt="Screenshot 2023-02-06 at 12 07 40" src="https://user-images.githubusercontent.com/15702139/216944001-4b1bd9a9-e227-4ce9-99a1-3dc1e4f1f470.png">

### **Expected Behavior**
The entire icons should be visible

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/main/playground/components/Avatar/
2. set "attachment" icon to several Avatars
3. observe the result

### **Context**
- UI5 Web Components version: main branch
- OS/Platform: MacOS

- Browser: Chrome
<img width="344" alt="Screenshot 2023-02-06 at 12 09 05" src="https://user-images.githubusercontent.com/15702139/216944138-a417df9a-fec0-4935-8ebe-61e897dde671.png">
- Affected component: ui5-avatar

### **Log Output / Stack Trace / Screenshots**
```
{...}
```
### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-p could you take a look of the issue?

**Comment by dobrinyonkov** [comment]
Hi @ilhan007, It appears that the issue has been resolved and is no longer reproducible in the latest version. 
We haven't implemented any fixes from our end, so it's possible that the latest Chrome version has addressed the issue.
I will close this for now, reopen it if still reproducible on your machine.

<img width="478" alt="image" src="https://user-images.githubusercontent.com/22766569/230402168-7a52d1b2-09ea-499b-ae21-ac909ab8ba94.png">


<img width="365" alt="image" src="https://user-images.githubusercontent.com/22766569/230402213-4570de55-6a80-4de4-9ea7-fbdf82833c47.png">
