### ISSUE TITLE
Define width of inputs

### ISSUE THREAD

**Issue by vital487** [SAP/ui5-webcomponents#6427]
Hi,

I have a problem where I need to define a width to an input, but I cannot. It always has the same width.

I tried to wrap a div and set the width to it, but the input stays the same.

Is there a way, right now, to achieve this? If not, would it be possible to use the width set in the style prop?

Thank you.

**Comment by dobrinyonkov** [comment]
Hello @vital487 and @Lukas742,

the framework favors setting a custom width of the inputs elements via CSS overrides. I've tested most of them and they seem to work as expected. 
https://codesandbox.io/s/ui5-webcomponents-forked-j5v963?file=/index.html

If there is a element inside a shadow root, that also needs to be layout differently or it does not inherit the proper width of its parent this could be fixed or an API could be requested to expose the element publicly via CSS ::part.

As all of the components above work as expeceted, I will close this issue. 
Please, let us know if there are such issues with any of the components and reopen/comment on this issue with the reproduction steps.

Kind Regards.
Dobrin
