### ISSUE TITLE
Tree component to provide only child selection [No Checkbox on the parent]

### ISSUE THREAD

**Issue by saorabhkr** [SAP/ui5-webcomponents#6431]
**Is your feature request related to a problem? Please describe.**
We have a flavor of the Picker where the user would be able to search via parent and have only the children selected (with no checkboxes being shown for the parent rows) 
![image](https://user-images.githubusercontent.com/5204425/217026690-1a99f4c4-98c8-4a55-8b73-1256b3ee374e.png)

**Describe the solution you'd like**
Option to hide the checkbox on the parent rows. 

**Describe alternatives you've considered**
No alternates 

**Additional context**
https://sap.github.io/ui5-webcomponents-react/?path=/story/data-display-tree--default-story&args=mode:MultiSelect
SFSF

**Comment by dobrinyonkov** [comment]
Hello @saorabhkr,

this can now be done using the `ui5-tree-item-custom` and the `hideSelectionElement` property.
https://codesandbox.io/s/ui5-webcomponents-forked-tmp3wm?file=/index.html

Keep in mind that the content (the text) should be added with the `content` slot as shown in the above example.

Let us know if you encounter any issues.

Kind Regards,
Dobrin
