### ISSUE TITLE
[SF_ACC][ui5-table][ui5-table-column][ui5-table-cell]: provide interface to customize some a11y properties

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents#6432]
### **Feature Request Description**
SF has a design like below, table has a column to put chevrons which are decorative, so we want set the column hidden to the screen reader. And when clicking the table row, it will show the detail on the right. To convey to a screen reader user that the rows are clickable, we need add an aria-describedby to the table that says "Press ENTER on rows to view details" or something of that sort. 
<img width="1268" alt="image" src="https://user-images.githubusercontent.com/13098801/217153642-0ff5fe69-c91a-4626-8996-a0181b6384a5.png">

Looking at UI5 samples, the decorative chevron has been hidden from screen reader users.
![image](https://user-images.githubusercontent.com/13098801/217154078-a5301a2b-0830-481f-ba1c-de1dccba6dd0.png)

### **Proposed Solution**
provide aria-describedby interface on ui5-table
provide role and aria-hidden interface on ui5-table-column
provide role and aria-hidden interface on ui5-table-cell

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: {SAP SuccessFactors}
- Business impact: {...}

**Comment by dobrinyonkov** [comment]
Hi @GongRichard,

`aria-describedby` API is currently on our roadmap and it's being discussed in our teams. Work on this is expected to start soon.

About the second two API requests, they are not standard in the openui5 table control and not specified as part of the APIs.
What can be used here and IMO a better solution is to use the APIs of the icon - `ariaHidden` and `accessibleRole` to set the decorative state of the icon. 
Refer to the following example: https://codesandbox.io/s/ui5-webcomponents-forked-4y4uwj?file=/index.html

Can this be helpful with your use case?

**Comment by GongRichard** [comment]
Hi @dobrinyonkov,

We already set icon to ariaHidden. As we use a column with empty title to put the icons, so the screen reader can read out this column in virtual PC mode and it will make the screen reader user confuse. We need set the whole column to ariaHidden.
<img width="1273" alt="image" src="https://user-images.githubusercontent.com/13098801/217417075-a88120e4-dadf-4d8a-bd81-181923acf41d.png">

Thanks,
Richard

**Comment by dobrinyonkov** [comment]
Hi @GongRichard,

while not added by the UI5 framework you can still add aria-hidden="true" to the custom elements as they are DOM nodes and aria-hidden should work on them too. 
https://codesandbox.io/s/ui5-webcomponents-forked-4y4uwj?file=/index.html

I've tested this with JAWS and NVDA. While JAWS handles this OK and excludes the DOM nodes from the accessibility tree, NVDA seems to strugule and still reads "Blank/Clickable" for the hidden  elements.

I've tested this with other shadow dom elements and is the same. I've also added aria-hidden to the inner elements of the shadow root and still the elements were announced. I'm suspecting this could be an issue with NVDA related to aria-hidden not working as expected with webcomponents/shadow root/custom-elements, as other screen readers handle this OK.

I will investigate this further and provide more findings.
