### ISSUE TITLE
Input: Decimal Separator

### ISSUE THREAD

**Issue by vital487** [SAP/ui5-webcomponents#6434]
Hi,

I'm using the Input component to write numbers with decimal places. The problem is that the decimal separator is a "comma" and I need a "dot".

Is there a way to do this already? If not, can you please add a property for the decimal separator?

Also I tested with the "dot" and it clears the number in the input, which I think is strange. It could not write it, but clear everything does not make sense to me. Could this be changed too?

**Comment by dobrinyonkov** [comment]
Hello @vital487,

Currently, browsers honors the language of the HTML element in which the input resides. The "comma" / "dot" character is based on the locale code. Here you can find a list of countries using decimal comma or a decimal point - https://en.wikipedia.org/wiki/Decimal_separator#:~:text=Conventions%20worldwide

Please make sure you have set your browser to a locale which uses "dot" as decimal point.
Could you please extend this codesandbox https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html with your sample?

Also, the second issue about the deletion of the value is addresed here  https://github.com/SAP/ui5-webcomponents/issues/5983 and should be resolved by the team.

Kind Regards,
Dobrin

**Comment by vital487** [comment]
Hi @dobrinyonkov,

Thank you for your answer.
