### ISSUE TITLE
[SAP] [Accessibility] [StandardListItem] : No keyboard support

### ISSUE THREAD

**Issue by vraguna** [SAP/ui5-webcomponents#6440]
As @kskondov suggested in https://github.com/SAP/ui5-webcomponents/issues/6370, I am creating it as a separate issue with the example code.

**Describe the bug**
There is no keyboard support for the StandardListItem components defined inside the ShellBar popover.

**Steps to reproduce the behavior:**

1. Open Google Chrome
2. Go to the corresponding examples
[ui5-webcomponents-react](https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-shellbar--with-customizable-shell-bar-item)
[Code Sandbox](https://codesandbox.io/s/shellbaritem-popover-forked-g8znbe?file=/src/App.js)

![Snag_33ab0d](https://user-images.githubusercontent.com/42251879/217276783-46287763-e201-4264-9aca-3c4f372f2bf9.png)

3. Click on the Keyboard tab to get the focus on each of the components inside the popover

You can notice the components are not focusable.

**Expected Behavior:**
Clickable elements must be focusable

**Comment by dobrinyonkov** [comment]
Hi @vraguna, 

in order to use the list item components you will need to wrap them inside the `ui5-list` component.
Check this CodeSandbox for reference: https://codesandbox.io/s/shellbaritem-popover-forked-nmk4eq

Please, reopen this issue if you encounter any issues.

**Comment by vraguna** [comment]
Hi @dobrinyonkov 
Thanks for the solution. I have wrapped the components inside the ui5-list and the component gets a focus when the keyboard keys are used, however, clicking the components are not supported. After the component gets a focus, I clicked the "Enter" key to open a dialog but it doesn't work.

The components are focusable now,
![image](https://user-images.githubusercontent.com/42251879/217567670-a2c8543a-b108-4414-980a-a2ef284192d5.png)


The keyboard keys didn't support opening the dialog when the component is being clicked. In the below screenshot, it shows that the dialog is opened using the mouse but the expectation is that it should be opened by using the keyboard keys

![image](https://user-images.githubusercontent.com/42251879/217568307-a6d1ac0a-dab1-4f21-81ec-9aaedf170781.png)

**Comment by dobrinyonkov** [comment]
Hi @vraguna, I'm not really sure I understand. Are you using the `onItemClick` event of the `List`. This is being fired upon interaction with any of the list items by using mouse or keyboard. 

Please exnted the following example with your code and provide a steb-by-step guide on how to reproduce the issue.
https://codesandbox.io/s/shellbaritem-popover-forked-nmk4eq?file=/src/App.js

Regards,
Dobrin

**Comment by vraguna** [comment]
Hi @dobrinyonkov,

In our application code, we are using onClick event of the StandardListItem to open a dialog. I have modified the code here -
https://codesandbox.io/s/shellbaritem-popover-forked-3lw4fo?file=/src/App.js. 

**Steps to reproduce the issue:**
1. Go to https://codesandbox.io/s/shellbaritem-popover-forked-3lw4fo?file=/src/App.js. 
2. Open https://3lw4fo.csb.app/ in a different browser
3. Use the keyboard tab key to get the focus on "Add (+)" icon
4. Press "Enter" key and you will see the first list item is focused.
![image](https://user-images.githubusercontent.com/42251879/217649867-719f8323-ff91-43bb-904b-cc8853d945b6.png)
5. Try to open the dialog by clicking the "Enter" key. You will notice that there is no keyboard support
6. Try to open the dialog using the mouse. The dialog will be opened.

**Expected behavior:**
At step 5, the dialog must be opening by using the keyboard key.

**Comment by dobrinyonkov** [comment]
Hi @vraguna, 

onClick is just the native browser html click event. It is not manged by the ui5 framework. It is not fired when a keyboard keys are pressed. You should use the on key handlers for that: 

https://codesandbox.io/s/shellbaritem-popover-forked-q85ygn?file=/src/App.js
