### ISSUE TITLE
Source map: Webpack is compiling with warnings

### ISSUE THREAD

**Issue by steffenknoeller** [SAP/ui5-webcomponents#6446]
### **Bug Description**
In version "1.10.3", both folders "webcomponents-icons\src" and "webcomponents-theming\src" are missing.

Failed to parse source map from 'C:\github\CFND-SCP-Situations\sdm-related-situations-explorer\ui\node_modules\@ui5\webcomponents-icons\src\Assets.ts' file: Error: ENOENT: no such file or directory, open 'C:\github\CFND-SCP-Situations\sdm-related-situations-explorer\ui\node_modules\@ui5\webcomponents-icons\src\Assets.ts'

Failed to parse source map from 'C:\github\CFND-SCP-Situations\sdm-related-situations-explorer\ui\node_modules\@ui5\webcomponents-theming\src\Assets.ts' file: Error: ENOENT: no such file or directory, open 'C:\github\CFND-SCP-Situations\sdm-related-situations-explorer\ui\node_modules\@ui5\webcomponents-theming\src\Assets.ts'

### **Context**
- UI5 Web Components version: 1.10.3
- OS/Platform: *
- Browser: *
- Affected component: *

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### **Stakeholder Info**

- Organization: SAP

**Comment by dobrinyonkov** [comment]
Hi @steffenknoeller, could you please provide a minimal reproduction example/repo/[CodeSandbox](https://codesandbox.io/) with your configuration and a Step-by-step guide on how to reproduce the issue?

Regards,
Dobrin

**Comment by steffenknoeller** [comment]
The difference in version "1.10.3" is that "*.map" files are generated. I.e. there are places in these files that currently point to source files that have not been published to npm:

@ui5\webcomponents-theming\dist\Assets.js.map:
{"version":3,"file":"Assets.js","sourceRoot":"","sources":[**"../src/Assets.ts"**],"names":[],"mappings":"AAAA,mDAAmD;AACnD,OAAO,oCAAoC,CAAC"}

@ui5\webcomponents-icons\dist\Assets.js.map:
{"version":3,"file":"Assets.js","sourceRoot":"","sources":[**"../src/Assets.ts"**],"names":[],"mappings":"AAAA,OAAO,kCAAkC,CAAC"}

**Comment by dobrinyonkov** [comment]
Hi @steffenknoeller, 

Thanks for all the information provided. I'm having hard time to reproduce this issue. I've made this webpack-html-starter repo with ui5 1.10.3 (https://github.com/dobrinyonkov/webpack-html-start) and it seems to compile succesfully for both dev and prod configs. Components are also rendered correctly using the `Assets` util. 

I've also uploaded this to Codesandbox (https://codesandbox.io/p/sandbox/black-cache-941ok2?file=%2Fpackage.json). Preview is not available but you can change configs and run start/build commands in the terminal.

Please have a look and extend or give us an example with your config.

Thanks,
Dobrin

**Comment by steffenknoeller** [comment]
Hi @dobrinyonkov ,
To see the warnings, you need to extract the source maps from the UI5 web component source files.
This can be achieved by using the "source-map-loader": https://webpack.js.org/loaders/source-map-loader/
Best,
Steffen

**Comment by Felipe-GG** [comment]
I had a similar issue with version 1.11.0 and `ui5/webcomponents/src/generated/themes/*` files.
Example: 
```log
Failed to parse source map from '/Users/SAPID/Projects/lpx-abapcloudeditor-frontend/node_modules/@ui5/webcomponents/src/generated/themes/Tokenizer.css.ts' file: Error: ENOENT: no such file or directory, open '/Users/SAPID/Projects/lpx-abapcloudeditor-frontend/node_modules/@ui5/webcomponents/src/generated/themes/Tokenizer.css.ts'
```
