### ISSUE TITLE
A recent test consistently fails

### ISSUE THREAD

**Issue by vladitasev** [SAP/ui5-webcomponents#6448]
Hello colleagues,

I had to comment out a test that breaks the build consistently and has blocked new changes from being merged.
https://github.com/SAP/ui5-webcomponents/pull/6447

Please debug, and re-enable the test after you've discovered the root cause.

Regards,
Vladi

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-rl could you check this test failure

**Comment by ilhan007** [comment]
This test started failing as well: https://github.com/SAP/ui5-webcomponents/pull/6463

**Comment by ilhan007** [comment]
adding one more test to track: https://github.com/SAP/ui5-webcomponents/pull/6508
