### ISSUE TITLE
ShellBar search field inconsistent with Wiki

### ISSUE THREAD

**Issue by bpan4** [SAP/ui5-webcomponents#6455]
### **Bug Description**
UI5 ShellBar search field is inconsistent with ShellBar designs on the SAP wiki. Currently, the search field does not expand or display in the center of the ShellBar when the ShellBar is of size XL. The search field remains collapsed as an icon aligned to the right of the ShellBar.

### **Expected Behavior**
The search field should be expanded and displayed in the center of the ShellBar when the ShellBar has size XL.

### **Steps to Reproduce**

1. Please see https://codesandbox.io/s/ui5-webcomponents-forked-wr6q9y?file=/index.html
2. Adjust the width of the rendered browser
3. The search field does not expand and is not centered in the ShellBar even at large widths

### **Priority**
- [x] Low
- [ ] Medium
- [ ] High
- [ ] Very High

**Comment by dobrinyonkov** [comment]
Hi @bpan4, @JarrettChan the horizon design of the shellbar was discussed with the VD team and it was agreed that some of the changes cannot be implemented duo the nature of the webcomponents and specifically the shadow root limitations.

Kind Regards,
Dobrin
