### ISSUE TITLE
ui5-avatar: avatar is not supporting accented characters in initials 

### ISSUE THREAD

**Issue by pankajpandey01** [SAP/ui5-webcomponents#6457]
### **Feature Request Description**
ui5-avatar: avatar is not supporting accented characters in initials

### **Proposed Solution**
avatar should support accented characters as initials 

### **Additional Context**
This is needed to support initials for users who has accented character in their names.
For example: Initials **ĆŚ**  should be supported.

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: {SuccessFactors}
- Business impact: {Live customer issue}

**Comment by dobrinyonkov** [comment]
Hi @SAP/ui5-webcomponents-topic-p, the avatar indeed does not render accented characters such as - à, è, ì, ò, ù, À, È, Ì, Ò, Ù, etc.
