### ISSUE TITLE
ui5-select: clicking on currently selected item doesn't close drop-down

### ISSUE THREAD

**Issue by axel-xciv** [SAP/ui5-webcomponents#6460]
### **Bug Description**
Selecting a item in a dropdown, opening the dropdown again and selecting the same item, the dropdown does not close.
Only clicking outside the dropdown or selecting another option closes the dropdown

### **Expected Behavior**
Dropdown should close all the time. Also when selecting a item that is currently already selected.

### **Steps to Reproduce**
1. Open dropdown and select one item
2. Open dropdown again and select the same item

### **Isolated Example**
If possible, please provide an isolated example by forking [CodeSandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html).

### **Context**
- UI5 Web Components version: current
- OS/Platform: macOS (windows not tested)
- Browser: Chrome, Safari (potentially also others)
- Affected component: Select

### **Log Output / Stack Trace / Screenshots**
```
{...}
```
### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

**Comment by dobrinyonkov** [comment]
Hello @SAP/ui5-webcomponents-topic-p, take a loot at this issue. It seems that the dropdown is not closed when the selected value is clicked with the mouse.
