### ISSUE TITLE
CheckBox: add `part` attribute to root element

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#6461]
### **Feature Request Description**
In UI5 Web Components for React we received an [issue](https://github.com/SAP/ui5-webcomponents-react/issues/3732) regarding the CheckBox in our AnalyticalTable. For this we need to customize styles inside the shadow root (e.g. padding). 
Could you please add a `part` attribute to the [root](https://github.com/SAP/ui5-webcomponents/blob/72f1cce96c9c0de9dda7e48859a2de10f0908504/packages/main/src/CheckBox.hbs#L1-L18) element of the CheckBox component, so we don't have to use the internal `addCustomCSS` syntax?

### **Proposed Alternatives**
Currently we're using `addCustomCSS` to achieve this, but as it's an internal API, we would like to be able to access the element via the `::part` pseudo Element.

### **Stakeholder Info** (if applicable)

- Organization: UI5 Web Components for React

**Comment by dobrinyonkov** [comment]
Internal reference: BGSOFUIPIRIN-6075
