### ISSUE TITLE
Table - The style of divider line between header and content of the table is different when there is data and no data

### ISSUE THREAD

**Issue by kilgharsap** [SAP/ui5-webcomponents#6465]
**Describe the bug**
The style of divider line between header and content of the table is different when there is data and no data. The divider line is much thicker when there is no data

**Screenshots**
<img width="914" alt="Screenshot 2023-02-10 at 9 20 19 AM" src="https://user-images.githubusercontent.com/89424021/218156320-83645ead-d5e9-40cd-94c7-5cf50c917b2f.png">

**UI5 Web Components for React Information**
`@ui5/webcomponents` version:
`@ui5/webcomponents-react` version:
Operating System:
Browser:

**Additional context**

**Comment by s-todorova** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

Please check the image above. Per my analysis, the thicker line in the no data table comes from the following style: 
.ui5-table-no-data-row {
	...
	border-top: 1px solid var(--sapList_BorderColor);
}

Could you please check if that is the expected visualization?

Thank you in advance,
Siyana
