### ISSUE TITLE
Badge with icon vs. without icon misalignment 

### ISSUE THREAD

**Issue by kaistephanrichter** [SAP/ui5-webcomponents#6467]
### **Bug Description**
If ui5-badge are placed next to each other in a plain div, they are vertically misaligned when one badge contains an icon and the other doesn't.

<img width="400" alt="badge-alignment" src="https://user-images.githubusercontent.com/46745939/218311497-4e8a8eb6-8a2e-4a23-87ac-81f85ec689e2.png">

### **Expected Behavior**
All badged should be vertically aligned, no matter whether they contain an icon or not.

### **Steps to Reproduce**
I used this code in a plain page running on node.js using the latest version available on npm

```
  <div>
    <ui5-badge color-scheme="1">
      <ui5-icon name="accept" slot="icon"></ui5-icon>done
    </ui5-badge>
    <ui5-badge color-scheme="8">Badge</ui5-badge>
    <ui5-badge color-scheme="1">
      <ui5-icon name="accept" slot="icon"></ui5-icon>done
    </ui5-badge>
  </div>
```

### **Context**
- UI5 Web Components version:
  "dependencies": {
    "@sap-theming/theming-base-content": "11.1.48",
    "@ui5/webcomponents-base": "1.10.3"
  },
  "devDependencies": {
    "@ui5/webcomponents-tools": "1.10.3",
    "chromedriver": "109.0.0",
    "cssnano": "^4.1.11",
    "globby": "^13.1.1",
    "json-beautify": "^1.1.1",
    "nps": "^5.10.0",
    "postcss": "^8.4.5",
    "postcss-import": "^14.0.2",
    "resolve": "^1.20.0"
  },

- OS/Platform: MacOS
- Browser: Chrome, Safari
- Affected component: ui5-badge

### **Priority**

- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SAP Design
- Business impact: {...}

**Comment by s-todorova** [comment]
Hello @SAP/ui5-webcomponents-topic-rd,

The affected component is ui5-badge. When you have both a badge with an icon and a badge without next to each other (regardless if they are in a container), they are vertically misaligned, as shown in the image above.

The issue could be easily reproduced in our samples - https://sap.github.io/ui5-webcomponents/main/playground/main/pages/Badge/. You can reproduce it by removing the icon form one of the badges with an icon and text in the last sample from the "Badges" section. It is reproducible both on SAP Quartz and SAP Horizon themes.

Could you please take a look at this? Thank you in advance.
Kind regards,
Siyana
