### ISSUE TITLE
Page height - Add more info to the documentation

### ISSUE THREAD

**Issue by kaistephanrichter** [SAP/ui5-webcomponents#6468]
### **Issue Description**

When implementing the ui5-page often (not always) shows without height. 

I have been struggling a lot with that without understanding what the issue was as sometimes it did work and sometimes it didn't. In one issue, I read now that it is recommended to set both <html> and <body> to 100% (where it seems important to use the style attribute and not the height attribute, as this didn't work for me).

It would be great, if you would provide a bit more information about this in the documentation of the ui5-page as I believe that is something others might be struggling as well.

What is the best practice you recommend using the page. Where to set height and how to wrap it?

### **Issue Type**

- [x] Documentation is unclear
- [ ] Documentation is incorrect
- [ ] Documentation is missing
- [ ] Other

**Comment by niyap** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

Could please check and enhance the documentation of the ui5-page component?

Kind Regards,
Niya
