### ISSUE TITLE
TextArea: Cannot read properties of null (reading 'replace')

### ISSUE THREAD

**Issue by C3ntraX** [SAP/ui5-webcomponents#6472]
**Describe the bug**
If you reset the textarea with the value null, then you'll get the error: Cannot read properties of null (reading 'replace')

**Isolated Example**
https://codesandbox.io/s/silly-sid-9ut2y7?file=/src/App.js

**To Reproduce**
1. Go to the sandbox
2. Click on reset
4. See error in console

**Expected behavior**
Its important, that the value null is valid, because if you are using librarys that resets the values, then there be shouldn't thown an error.
My library is Formik, a very popular library

**Screenshots**

**UI5 Web Components for React Information**
`@ui5/webcomponents` version:
`@ui5/webcomponents-react` version:
Operating System:
Browser:

**Additional context**

**Comment by s-todorova** [comment]
Hello @C3ntraX ,

As you can see in the documentation here https://sap.github.io/ui5-webcomponents/main/playground/components/TextArea/,
the "value" property only accepts "string" and has a default value of empty string. Therefore, what you are trying to achieve is not possible by intention.

Best regards,
Siyana

**Comment by C3ntraX** [comment]
Its important, that the value null is valid, because if you are using librarys that resets the values, then there be shouldn't thown an error.
My library is Formik, a very popular library

**Comment by C3ntraX** [comment]
@s-todorova 

You you pls discuss this intern? Because other inputs like the Input accepts null.

@Lukas742 
This is an bug for with the library Formik, which sets the value to null.
