### ISSUE TITLE
Icon: add `part` attribute to root element

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#6474]
### **Feature Request Description**
In UI5 Web Components for React we received an issue regarding the expand/collapse icon in our AnalyticalTable. For this we need to customize styles inside the shadow root. For example even though I can add a padding around the component, the outline still is displayed around the icon, which is not desirable in this case.
Could you please add a part attribute to the [root](https://github.com/SAP/ui5-webcomponents/blob/08cd3610d20abd0e956e0487b217f954cb78120f/packages/main/src/Icon.hbs#L1-L17) element of the Icon component, so we don't have to use the internal addCustomCSS syntax?

### **Proposed Alternatives**
Currently we're using `addCustomCSS` to achieve this, but as it's an internal API, we would like to be able to access the element via the `::part` pseudo Element. 

#### Current icon style inside the AnalyticalTable (Fiori 3):
__Cozy:__
<img width="381" alt="image" src="https://user-images.githubusercontent.com/9749730/218458657-6990e3bb-be11-41ea-8d1a-b011ab656ceb.png">

__Compact:__
<img width="302" alt="image" src="https://user-images.githubusercontent.com/9749730/218458819-e4168b24-a7e4-4752-9471-e18a606d6ea0.png">

#### Updated style (via `addCustomCSS`):
__Cozy:__
<img width="600" alt="image" src="https://user-images.githubusercontent.com/9749730/218458304-e1e6e62c-c8f0-47b6-a64b-815091186529.png">

__Compact:__
<img width="378" alt="image" src="https://user-images.githubusercontent.com/9749730/218458497-d5594500-de79-44bb-9903-f3663b75c526.png">

### **Stakeholder Info** (if applicable)

- Organization: UI5 Web Components for React

**Comment by s-todorova** [comment]
Hello @SAP/ui5-webcomponents-topic-p, 

Could you please take a look of this feature request?
Thank you in advance!

Kind regards,
Siyana

**Comment by dobrinyonkov** [comment]
Internal Reference: BGSOFUIPIRIN-6075
Similar to: #6461
