### ISSUE TITLE
TextArea: Allow value null to prevent standard libarary to throw errors

### ISSUE THREAD

**Issue by C3ntraX** [SAP/ui5-webcomponents#6475]
### **Feature Request Description**
See #6472

Standard libarary throwing errors because the textarea value does not accept null.

### **Proposed Solution**
A clear and concise description of the solution you would like to have.

### **Additional Context**
Add other context or screenshots related to the feature request here.

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by C3ntraX** [comment]
The input value does accept null although the api states otherwise, but its was not noticed because the input does not throw an error.
https://sap.github.io/ui5-webcomponents/main/playground/components/Input/ 

Therefore it makes sense to update the api for the Input Element as well.

**Comment by s-todorova** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

This feature request is related to #6472. Could you please check the referenced issue and analyze whether it is espected to be able to set the ui5-textarea value to "null" ?

Kind regards,
Siyana
