### ISSUE TITLE
`<ui5-input>` no way to get scrollContainer prior to the first `suggestion-scroll` event

### ISSUE THREAD

**Issue by codefactor** [SAP/ui5-webcomponents#6486]
### **Feature Request Description**
The `<ui5-input>` element supports a `suggestion-scroll` event that provides the `scrollContainer` so that consumer can check if the list is scrolled to the bottom to do an infinite scrolling; however, after loading some input elements for the first time the consumer has no way of knowing if there is enough room to add more items. The feature is to 

### **Proposed Solution**
Expose a public function to get the scroll container such that we do not need to use the private API to get it like this:

```
  getScrollContainer() {
    return this.Suggestions?._getScrollContainer();
  }
```

### **Proposed Alternatives**
Count how many items are displayed and keep fetching items until a bare minimum count is returned which will gaurantee that the count of items will result in a scroll bar regardless of screen size.

### **Additional Context**
The input is a lazy search where the back-end can return thousands of result items, so we offer an infinite scroll. But if the user is doing the search and the first page of data has returned with enough room to render under the input element without giving any scroll bar, the "suggestion-scroll" event will never be fired - so we will never get any events that will trigger the code to load the next page of data (so only the first page is shown). 

An issue occurs when the input is placed near the top of the screen where the space below the input is large enough to render the entire first page of data, the "suggestion-scroll" event never fires so the second page of data is never requested. This leads to an inconsistency where the lazy loading works if the input is near the middle of the screen, but does not work when it is at the top.

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by niyap** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

Can you please take a look of this feature request?

Kind Regards,
Niya

**Comment by hristop** [comment]
Hi @codefactor ,

We have discussed the request with our architects and their advise is to reject this request. 
The reasoning is that we cannot guarantee that such an API will work in future and we do not want to couple the input with the scroll container in this way. 

Their proposal is to extend the ui5-input component and provide alternative of the whole picker in which you can control the scroll container and load items in a way suitable for your use case. 

Best Regards,
Hristo
