### ISSUE TITLE
TabContainer: Add property for the container to be fixed on the page like the header property for the Page component

### ISSUE THREAD

**Issue by C3ntraX** [SAP/ui5-webcomponents#6491]
### **Feature Request Description**
I need a property that makes it possible to treat the TabContainer like a page's header, so that the tabs bar doesn't disappear when scrolling, but is always visible.

The problem is that you have to select either a page or a tab container with tabs and then possibly a page within the tabs. On small screens where the tab has a long scroll bar, it is better for the user experience if the tab bar is always visible.

### **Proposed Solution**
Add a property for this solution.

### **Additional Context**
Add other context or screenshots related to the feature request here.

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by niyap** [comment]
Hello @SAP/ui5-webcomponents-topic-rd,

Could you please take a look of that feature request and analyse if it is feasible ?

Thank you in advance!

Kind Regards,
Niya

**Comment by gmkv** [comment]
Hi @C3ntraX 

This is achievable with CSS today. Set the TabContainer to a fixed width, for example the height of its parent element. The content will scroll if necessary. Optionally, you can customise the "content" of the TabContainer using CSS parts.

https://codesandbox.io/s/ui5-webcomponents-forked-4zdxjd

This way, the tab strip will always be visible, and the Tab's content will be scrollable.
I don't believe a new feature request is necessary here. Let me know what you think.

Regards,
Georgi

**Comment by C3ntraX** [comment]
Hello @gmkv,

so now we have a chain of problems with setting the height to 100vh. See: #6517
You cann't guarantee that the height of 100vh is working on all devices.

Regards,
C3ntraX

**Comment by gmkv** [comment]
Hi @C3ntraX 
I don't know what your use case is but the advices about the Page and TabContainer are still valid.
Have you tried to use `dvh` instead of `vh` for mobile?
Dynamic viewports units seem to be [supported well in the browsers](https://caniuse.com/mdn-css_types_length_viewport_percentage_units_dynamic) that this project [also supports](https://github.com/SAP/ui5-webcomponents#browser-support). 
I am not sure what you mean about compatibility with all devices, but I guess you mean that `100vh` becomes too large and the mobile browser's address bar end up obscuring part of the page.

I found this video by the Chrome developers which could be useful in understanding why dvh is better than vh. They explain about the different viewports which exist in mobile browsers. It may be useful to you too. https://www.youtube.com/watch?v=xl9R8aTOW_I&t=1411s

**Comment by C3ntraX** [comment]
Hello @gmkv 

yeah thx I didnt know about the `dvh` because its really new.
But this has some disadvantages. We are using Babel to compile the JavaScript down. I some Apps we need Chrome V75 which is not that problem with Babel.

With css I dont know how Babel or any other could compile the `dvh` part down to be used in Chrome V75.

Besides this, I read some blogs about `dvh` and the use. In this [Blog](https://dev.to/frehner/css-vh-dvh-lvh-svh-and-vw-units-27k4) they are telling me, that `dvh` has some other disadvantages:

`The sizes of the dynamic viewport-percentage units are not stable even while the viewport itself is unchanged. Using these units can cause content to resize e.g. while the user scrolls the page. Depending on usage, this can be disturbing to the user and/or costly in terms of performance.`

Some other problems are described in #6517 where you are not knowing the number of the fixed height because of paddings, margins and other things. 

If you could simply use the percentage height, this would the best solution overall. You have only one unit which is working on all browser for nerly all versions and does no problems. So while we are discussing here, some other people may have trouble with this framework too, because there are defined too many absolute css calculations which are messy to calculate and to fix.

It is not the case that it may working, but its really messy and buggy until you find a solution which would have been unnecessary if the developers hadn't been given so many restrictions

**Comment by C3ntraX** [comment]
FYI - chrome v75 is needed for SAP Business One webclient. Addons can open the webclient and we open our webapp in this browser. For this apps which uses the webclient, we are not able to only support the latest 1-2 chrome versions.

This is why Im a bit confused, why you are not supporting your products webviews. Or are you only support SAP S/4HANA?
