### ISSUE TITLE
StandardListItem: Icon doesn't update its aria-label

### ISSUE THREAD

**Issue by ej612** [SAP/ui5-webcomponents#6519]
**Describe the bug**
We have a StandardListItem, the icon of which we change programmatically depending on outside conditions.
The `ui5-icon` element created by the StandardListItem has an `svg` child, which has an `aria-label` attribute set on it, depending on the initial icon. In our case, the initial item is "add", so the `aria-label` is "Add".

So far, so good. If we change the icon to "less" now, however, the `aria-label` on the icon's child will not update and remain "Add".

**Isolated Example**
I made a [sandbox](https://codesandbox.io/s/agitated-austin-reii6j?file=/src/App.js).

Thanks a lot in advance!

**Comment by niyap** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

Please, check the description of the issue and the sample provided: https://codesandbox.io/s/agitated-austin-reii6j?file=/src/App.js
When the StandardListIcon is changed, its aria-label attribute value is not updated accordingly but remains with the tootip of the previously used icon.

Could you please look over?

Thank you in advance!

Kind Regards,
Niya
