### ISSUE TITLE
Implement a MessageToast functionality

### ISSUE THREAD

**Issue by ignipae** [SAP/ui5-webcomponents#652]
**Is your feature request related to a problem? Please describe.**
Within applications I really like to give visual feedback to the user when something was successful. Within SAPUI5, there is the MessageToast which is completely doing the trick, by providing an easy to use feature, which shows a text, which fades out automatically after a set amount of time (+ default value).

**Describe the solution you'd like**
I would like to see the MessageToast as a functionality within the ui5-webcomponents. I would expect to be able to provide a number of seconds (or maybe milliseconds) to define how long the toast will stay until it fades away. Of course a text needs to be provided for the content. 

Further a nice-2-have would be even to provide a type, which could be used to highlight if this is about a success, or a warning or such. (but thats nothing which has to be there initially)

**Describe alternatives you've considered**
An alternative would be to have the webcomponents dialog, which will give a success message to the end-user. But it has to be closed then manually, and its also taking too much space in my opinion.

Best regards,
Julian

**Comment by ignipae** [comment]
I am not sure if this is technically feasible with the webcomponents technology, but I still think that this would be a good functionality.

**Comment by MapTo0** [comment]
Hey @ignipae 

Currently we are quite busy with improving the current code base and making the base APIs better and we will probably not be able to scale to make this component in the near future.

We will inform you as soon as we got this planned and assigned to someone.

You can try to use the MessageStrip with some custom interaction in the meantime https://codesandbox.io/embed/frosty-voice-siviz

Regards,
Martin

Regards,
Martin

**Comment by ignipae** [comment]
Hi @MapTo0 
Thank you for your response. Thats totally understandable!
I will try to work with your suggested custom interaction. That looks already promising.

**Comment by ilhan007** [comment]
## MessageToast, ui5-message-toast

### properties
duration: Number | 3000 ms
opened: Boolean | false
placement: String | Placement.BottomCenter 
Available values: TopStart, TopCenter, TopEnd, MiddleStart, MiddleCenter, MiddleEnd, BottomStart, BottomCenter, BottomEnd;

### events (TBD)
openedChange or afterOpen + afterClose or visibilityChange

### methods
  open(): void // Opens the message toast.

**Comment by fifoosid** [comment]
Implemented via #1014
