### ISSUE TITLE
[SF] Label Dir Inconsistency

### ISSUE THREAD

**Issue by IrvinDelgado** [SAP/ui5-webcomponents#6524]
### **Bug Description**
When using `ui5-label` with `showColon` and `wrapping-type="Normal"` Then on RTL page the text is multi line even though in LTR the text is single line. 

### **Expected Behavior**
The Label Text should be same height on both LTR and RTL

### **Steps to Reproduce**
1. Go to [Sandbox](https://codesandbox.io/s/ui5-webcomponents-forked-shf7v5?file=/index.html)
2. Currently the text is "Label " (There is a space character)
3. View that currently "Label :" is single line
4. Click on the "change dir"
5. View that the Label is now Multi Line even though its only one word with a space

### **Isolated Example**
If possible, please provide an isolated example by forking [CodeSandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html).

### **Context**
- UI5 Web Components version: 1.10.0
- OS/Platform: Mac
- Browser: Chrome
- Affected component: Label

### **Log Output / Stack Trace / Screenshots**

![Screenshot 2023-02-16 at 4 09 30 PM](https://user-images.githubusercontent.com/62973847/219516229-b8c49f38-7e33-4fdb-9e54-fc2b4b10eb3a.png)

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by s-todorova** [comment]
Hello @SAP/ui5-webcomponents-topic-rd,

Please check out the attached example from the reporter. The issue is also reproducible on the Label's test page. The same Label with some text behaves differently with "rtl" and "ltr", when wrapping type is "Normal", if the label's value is one word ending with a space or consists of more than one word.

Could you please look over?
Kind regards,
Siyana
