### ISSUE TITLE
ui5-tab-container: broken example for the `allItems` property

### ISSUE THREAD

**Issue by kaistephanrichter** [SAP/ui5-webcomponents#6525]
### **Issue Description**
On the playground page for the ui5-tab-container, there is an embedded example for the `allItems` property in the description column. The intention seems to be that users can see how the the tabs in the allItems return array are ordered, but the code only shows empty tabs:

```
/**
	 * Returns all slotted tabs and their subTabs in a flattened array.
	 * The order of tabs is depth-first. For example, given the following slotted elements:
	 * <code>
	 * 	<ui5-tabcontainer>
	 * 		<ui5-tab id="First">
	 * 			...
	 * 			<ui5-tab slot="subTabs" id="Nested">...</ui5-tab>
	 * 		</ui5-tab>
	 * 		<ui5-tab id="Second">...</ui5-tab>
	 * 		<ui5-tab-separator id="sep"></ui5-tab-separator>
	 * 		<ui5-tab id="Third">...</ui5-tab>
	 * 	</ui5-tabcontainer>
	 * </code>
	 * Calling <code>allItems</code> on this TabContainer will return the instances in the following order:
	 * <code>[ ui5-tab#First, ui5-tab#Nested, ui5-tab#Second, ui5-tab-separator#sep, ui5-tab#Third ]</code>
	 * @public
	 * @readonly
	 * @returns {sap.ui.webc.main.ITab[]}
	 */
```

In the documentation, this looks like this. So there is no way to understand, which element has which ID.
<img width="740" alt="image" src="https://user-images.githubusercontent.com/46745939/219577293-cd2d2628-b704-4201-80ee-c522457adec3.png">

I'd suggest adding the Ids as texts on those tabs that are able to show them (not the separator of course) to allow people understand. Otherwise, just show the source code and not the render.

Suggested change:
```
	<ui5-tabcontainer>
		<ui5-tab id="First" text="First">
			<ui5-tab slot="subTabs" id="Nested" text="Nested"></ui5-tab>
		</ui5-tab>
		<ui5-tab id="Second" text="Second"></ui5-tab>
		<ui5-tab-separator id="sep"></ui5-tab-separator>
		<ui5-tab id="Third" text="Third"></ui5-tab>
	</ui5-tabcontainer>
```

### **Issue Type**

- [x] Documentation is unclear
- [ ] Documentation is incorrect
- [ ] Documentation is missing
- [ ] Other

**Comment by niyap** [comment]
Hello @SAP/ui5-webcomponents-topic-rd,

Could you please look over the issue? The documentation and especially the sample provided within the documentation is a little bit unclear.

Thank you in advance!

Kind Regards,
Niya
