### ISSUE TITLE
Page: Fixed height of 100vh does not show the footer on mobile device (emulator working)

### ISSUE THREAD

**Issue by C3ntraX** [SAP/ui5-webcomponents#6527]
### **Bug Description**
If you have a Page with content, then your adviced us to set a fixed height for the page. In many stackoverflow examples they always say that a fullscreen page can archived with height=100vh.

If you set the height to 100vh everything is working. The foorter is showing too, but as soon as you set open the Webapp with the page component and an footer on the mobile device, the footer is not sticked on the botten on the website, you need to scroll down and the footer is exactly 44px (Horizon) outsite of the page.

On emulator its working, I dont know why.

If you set everything to 100% height then the footer is showing and everything works. But this is not adviced but see here. Its part of a bigger problem: #6517

### **Expected Behavior**
The footer should always be shown on the page with the page as highest component and a  height of 100vh.

### **Steps to Reproduce**
1. Open the codesandbox on your mobile device directly (I prefer phone): https://cb19n5.csb.app/
2. The footer does not show up
3. scroll down until the list ends
4. the footer is visible again but not the header until you scroll up again

### **Isolated Example**
https://codesandbox.io/s/red-waterfall-cb19n5?file=/public/index.html

### **Context**
- UI5 Web Components version: {...}
- OS/Platform: {...}
- Browser: {...}
- Affected component: {...}

### **Log Output / Stack Trace / Screenshots**
```
{...}
```
### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by TeodorTaushanov** [comment]
Hi @SAP/ui5-webcomponents-topic-rl, can you check this issue? It is reproducible on a real phone device.

**Comment by ivoplashkov** [comment]
Hello @C3ntraX,

You have came upon an issue that is related to the calculations in the browser of the phone, not the actual component.
It's not recommended to use 100vh on mobile devices because of such issues, which I don't think are even planned to be solved. There are many ways you can overcome this, here is a [stackoferflow post](https://stackoverflow.com/questions/37112218/css3-100vh-not-constant-in-mobile-browser) that you may find helpful.

Hope this helps!
Best regards,
Ivaylo

**Comment by C3ntraX** [comment]
Hello @ivoplashkov 
To set the page to full height, it is recommend in a note to set thje page to a fixed height.

I search in many stackoverflow posts to set the page to 100% height and the solution is to set the page to 100vh or everything to 100%. But now you see the problem as well. Thanks!

Your page component is not working with a fixed height on all platforms, which means, its unusable in general.
This problem is related in many components and many discussions with you.

See: #6517 and #6491

I hope you can discuss this behaviour internal and give us (the actual users) a good solution which is working on all platforms and all components and combinations.
