### ISSUE TITLE
Implementation of Action Bar

### ISSUE THREAD

**Issue by ignipae** [SAP/ui5-webcomponents#653]
**Is your feature request related to a problem? Please describe.**
Within applications, I like to provide a unified look and feel of all the pages within an application.
For that I would like to have the [Fundamentals Action Bar](https://sap.github.io/fundamental/components/action-bar.html) as a webcomponent available.
With that, I could easily make sure, that I have a consistent design throughout my application.

**Describe the solution you'd like**
I would like to see an Action Bar webcomponent, which takes a title property, a subtitle and which has a slot for actions, which will be a set of buttons.
Further the Action Bar should have a slot for the back button. This way a developer can hand over whatever button is preferred. If the back button slot is not filled, the back button area should not be rendered.

**Describe alternatives you've considered**
An alternative is to use the fundamentals action bar directly.

**Additional context**
![image](https://user-images.githubusercontent.com/4704905/61273244-517d7980-a7a9-11e9-929d-87d99f34fb62.png)

**Comment by ilhan007** [comment]
@ignipae Thank you for your feature request.

Unfortunately, for the time being we will not invest time in providing layout components in the near future. We are focused on a lot of tasks to make our product ready for official public release (1.0.0).

For now, you can use the one you referenced or build your own HTML markup,
using the ui5WebComp as building blocks: ui5-icon, ui5-title, ui5-label and ui5-button(s)

Best,
ilhan
