### ISSUE TITLE
ui5-tree: 'header-text' attribute doesn't show

### ISSUE THREAD

**Issue by kaistephanrichter** [SAP/ui5-webcomponents#6534]
### **Bug Description**
The `header-text` attribute, according to the documentation should display a header text if the `header` slot isn't used but it doesn't seem to work.

In this Snippix example you see how I used the simple tree example from the playground and added header-text and footer-text. While the footer-text shows, the header-text doesn't seem to be rendered.

https://snippix.only.sap/snippets/126464

```
	<ui5-tree header-text="This is the Header Text" footer-text="This is the Footer Text">
        ...
	</ui5-tree>
```

![image](https://user-images.githubusercontent.com/46745939/219689437-edbd27d5-c66a-4a87-85b3-5dce1c983dab.png)

### **Expected Behavior**
The header text should become visible as documented. Ideally, with an additional header-level attribute, the style could be adjusted as well.

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SAP Design

**Comment by niyap** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

As described by the reporter, when the "header-text" of ui5-tree component is set and there is no header slot presented, its value is not visualised. The issue could be reproduced in the component's test page as well, if a sample is enhanced with that scenario.

Could you please look over?

Thank you in advance!

Kind Regards,
Niya
