### ISSUE TITLE
[SF_ACC] [Input] Violate AA/AAA contrast standard with sap_horizon_hcb/sap_horizon_hcw theming in disabled mode

### ISSUE THREAD

**Issue by 2bno1** [SAP/ui5-webcomponents#6544]
### **Bug Description**
Given the theme is sap_horizon_hcb (or sap_horizon_hcw) and the ui5-input is set to disabled, it violates AA/AAA contrast standard.

### **Expected Behavior**
The ui5-input should meet AA/AAA contrast standard.

### **Steps to Reproduce**
1. Go to https://dzc5k4.csb.app/
2. Test the contrast radio with [Color Contrast Analyzer](https://developer.paciellogroup.com/resources/contrastanalyser/)

### **Isolated Example**
https://codesandbox.io/s/ui5-webcomponents-forked-dzc5k4?file=/src/index.js

### **Context**
- UI5 Web Components version: 1.10.4
- OS/Platform: macOS
- Browser: Chrome
- Affected component: ui5-input

### **Log Output / Stack Trace / Screenshots**
![Screenshot 2023-02-20 at 14 43 40](https://user-images.githubusercontent.com/1751846/220032471-c239eb1c-3556-4188-9fdd-61ca1c2bb952.png)
![Screenshot 2023-02-20 at 14 42 04](https://user-images.githubusercontent.com/1751846/220032504-cf0e5917-49fd-4bc4-98cb-bd80af2a33c6.png)

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by TeodorTaushanov** [comment]
Hi @SAP/ui5-webcomponents-topic-rl, can you check this issue?

**Comment by niyap** [comment]
Hello @2bno1,

Actually the visualisation is by design. According to the Fiori Accessibility Guidelines, contrast ratio should not be measure for **disabled text and elements**

Kind Regards,
Niya
