### ISSUE TITLE
Missing Property Documentation for Calendar

### ISSUE THREAD

**Issue by ChewbaccaCookie** [SAP/ui5-webcomponents#6554]
### **Issue Description**
Hi,
the documentation for the Calendar component is incomplete. 
Only two properties are described, but a lot of more properties are accepted.

Thank you

### **Issue Type**

- [ ] Documentation is unclear
- [ ] Documentation is incorrect
- [x] Documentation is missing
- [ ] Other

**Comment by ilhan007** [comment]
Hello @ChewbaccaCookie, thank you for reporting. 

Yes, it's a known issue, you can use the "main" (not released) deployment https://sap.github.io/ui5-webcomponents/main/playground/components/Calendar/ for the time being. Soon we will fix that in the oficial  deployment.

**Comment by ilhan007** [comment]
It's now fixed in the stable docs
https://sap.github.io/ui5-webcomponents/playground/components/Calendar/

BR,
ilhan
