### ISSUE TITLE
nested TreeItem missing checkbox and styles if rendered collapsed and deeper than level2 

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#6571]
### **Bug Description**
This issue is almost the same as #6265, so if it's easier for you to track, you can close this one here and we can continue the discussion in the original issue.

TreeItems rendered in collapsed state and deeper than level 2, are not displaying their checkboxes and don't have the appropriate styles attached in "MultiSelect" `mode`.

### **Expected Behavior**
All TreeItems should behave in the same way, no matter the level they're rendered in.

### **Steps to Reproduce**
1. Go to [codeSandbox](https://codesandbox.io/s/ui5-webcomponents-forked-lqt9el?file=/index.html)
2. Keep on expanding sub tree items of "Level1: w/ checkbox --> init collapsed" until all are expanded
3. See that beginning from level3, no checkboxes are rendered and e.g. no pointer is shown as cursor when hovering.

### **Isolated Example**
1.10.4: https://codesandbox.io/s/ui5-webcomponents-forked-lqt9el
1.11.0-rc.2: https://codesandbox.io/s/ui5-webcomponents-forked-82xd3p

### **Context**
- UI5 Web Components version: 1.10.4 (also tested in 1.11.0-rc.2)

### **Priority**
- [ ] Low
- [ ] Medium
- [ ] High
- [x] Very High

I marked this issue with very high priority as we still cannot update our internal applications because of it. (I thought that it was fixed with [this PR](https://github.com/SAP/ui5-webcomponents/pull/6277), but unfortunately the fix only solved it for tree items on level 2)

### **Stakeholder Info** (if applicable)

- Organization: UI5 Web Components for React (MXP Org)
- Business impact: We still cannot update our internal applications because of this issue.

**Comment by TeodorTaushanov** [comment]
Hi @SAP/ui5-webcomponents-topic-p, can you check this issue?
