### ISSUE TITLE
ui5-shellbar: avatar not showing three letter initials when re-render.

### ISSUE THREAD

**Issue by pankajpandey01** [SAP/ui5-webcomponents#6585]
### **Bug Description**
ui5-shellbar: avatar not showing three initials when re-render. It is showing gender neutral image in this case.
In our application we need to re-render avatar to update UI.

### **Expected Behavior**
It should show three letter initials after re-render. 

### **Steps to Reproduce**
1. Go to 'https://codesandbox.io/s/ui5-webcomponents-forked-98iq2q?file=/index.html'
2. get `<ui5-avatar slot="profile" initials="RHB" ui5-avatar="" icon="employee"> </ui5-avatar>` in browser console.
3. call _render() on above DOM object.

See attached screenshot for more details.

### **Isolated Example**
https://codesandbox.io/s/ui5-webcomponents-forked-98iq2q?file=/index.html

### **Context**
- UI5 Web Components version: {1.10.3}
- OS/Platform: {All}
- Browser: {All}
- Affected component: {ui5-avatar/ui5-shellbar}

### **Log Output / Stack Trace / Screenshots**
![Screenshot 2023-02-24 at 11 18 53 AM](https://user-images.githubusercontent.com/67934622/221271770-75ecb3e9-f5c7-4820-b2c6-1cae7f8f5c4a.png)

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {SuccessFactors}

**Comment by NHristov-sap** [comment]
Hello @ui5-webcomponents-topic-p,

I am forwarding this issue to you, because it is reproducible. 
I see that there is an attempt to call private method _render(), but probably you can consult the requester how to achieve what is needed.
Btw, the issue is reproducible when ui5-avatar is placed in ui5-shellbar, but not with standalone ui5-avatar.

Best Regards,
Nikolay Hristov

**Comment by nnaydenow** [comment]
Issue seems to be reproducible in avatar only snippix: https://codesandbox.io/s/ui5-webcomponents-forked-6o4xi1?file=/index.html
