### ISSUE TITLE
[Feature request] List: make "selection-change"  preventable

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents#6589]
### **Feature Request Description**
As I developer, I would like to be able to prevent the"selection-change" event of the List to discard internal selection when certain criteria/validation is not met.
For more background and context see the origin issue: https://github.com/SAP/ui5-webcomponents/issues/4883

### **Proposed Solution**
There are several examples in other components that we already implemented this behaviour (the preventable events has `@allowPreventDefault` JSDoc tag set).The solution is based on the `fireEvent` return value, which indicates if the event has been prevented in the event handler.

As we need to be compatible we will have to fire the event at the same place with the same event details, but if prevented, we can reset the selection.

Reference implementations: https://github.com/SAP/ui5-webcomponents/issues/5638 https://github.com/SAP/ui5-webcomponents/pull/6553

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by ilhan007** [comment]
I can see that "item-click" can be prevented and as a consequence the "selection-change", so it's already possible to prevent the selection, but it's not quite complete.
Because in general the app developer would like to get the "selection-change", see the selection with the latest `selectedItems` and `previouslySelectedItems` and prevent it if needed.

**Comment by dobrinyonkov** [comment]
Internal reference: BGSOFUIPIRIN-6091

**Comment by ilhan007** [comment]
Hello @plamenivanov91 @dobrinyonkov Isn't this fixed with https://github.com/SAP/ui5-webcomponents/pull/7007

**Comment by plamenivanov91** [comment]
Hello @ilhan007 ,

Yes, it should be fixed.
