### ISSUE TITLE
Javascript CDN for UI5 Webcomponents

### ISSUE THREAD

**Issue by yogananda-muthaiah** [SAP/ui5-webcomponents#6590]
### **Feature Request Description**
we are looking for an urgent CDN javascript path for our upcoming project.

### **Proposed Solution**
CDN Javascript for UI5 Webcomponents

### **Priority**
- [ ] Low
- [] Medium
- [X] High
- [ ] Very High

**Comment by ilhan007** [comment]
Hi @yogananda-muthaiah, thank you for your interest in UI5 Web Components.

If you read the the[ First steps](https://sap.github.io/ui5-webcomponents/main/playground/getting-started/first-steps/) article, you already know that as stated:

"**Important**: There is no CDN for UI5 Web Components. Each application is expected to import and bundle only the components (and any other resources) it is going to use."
This has been decided long ago and we don't plan to provide CDN.

You can use the bundle that we use for our Playground, but it's discouraged and may change in near future:
```html
<script 
  type="module"
  src="https://sap.github.io/ui5-webcomponents/main/assets/js/ui5-webcomponents/bundle.esm.js">
</script>
```
As this link is not stable and may change in future, and If you insist on CDN like bundle that has everything in, it's better to create a bundle on your own:
- create a project we a single JS file
- import all the components and icons available in that file,
- use a build tool (rollup, webpack, vite) to resolve imports, bundle everything and produce a single file
- host that file somewhere
