### ISSUE TITLE
[TabContainer] Safari crashes when clicking on Tab if the tab contains Table

### ISSUE THREAD

**Issue by BennyHuang** [SAP/ui5-webcomponents#6591]
### **Bug Description**
Safari browser crashes when clicking on Tab if the tab contains Table

### **Expected Behavior**
Safari browser should crash.

### **Isolated Example**
It can be reproduced in https://codesandbox.io/s/boring-meadow-efzoe9?file=/src/App.js

### **Context**
- UI5 Web Components version: 1.10.3
- OS/Platform: MacOS Ventura 13.2
- Browser: Safari 16.3
- Affected component: TabContainer

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SF

**Comment by NHristov-sap** [comment]
Hello @ui5-webcomponents-topic-rd,

I am forwarding this issue to you, because it is reproducible.

Best Regards,
Nikolay Hristov

**Comment by gmkv** [comment]
This is probably be related to the **duplicate names** for the slots in the table and tab:
![image](https://user-images.githubusercontent.com/22086365/221790366-f6f8de93-72e3-4135-8a3f-4df712672735.png)

See related fix https://github.com/SAP/ui5-webcomponents/pull/5241

**Comment by niyap** [comment]
Hello @BennyHuang,

The issue is already reported #6570 so please track the progress there.
Related to #6570 

Kind Regards,
Niya
