### ISSUE TITLE
[SF_ACC][ui5-label][1.9.1] Colon symbols are not getting announced by screen reader

### ISSUE THREAD

**Issue by i323808** [SAP/ui5-webcomponents#6592]
### **Bug Description**
Colon symbols are not getting announced by screen reader.

### **Expected Behavior**
Colon symbols should get announced by screen reader as found in UI5 sample(https://sapui5.hana.ondemand.com/#/entity/sap.ui.layout.form.Form/sample/sap.ui.layout.sample.Form354).

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/Label/
2. Colon symbols are not getting announced when focus the form field

### **Isolated Example**
https://sap.github.io/ui5-webcomponents/playground/components/Label/

### **Context**
- UI5 Web Components version: 1.9.1
- OS/Platform: macOS Ventura 13.2.1
- Browser: Chrome
- Affected component: ui5-label

### **Log Output / Stack Trace / Screenshots**
https://user-images.githubusercontent.com/30744017/221504195-c35032b2-a7a4-47b1-b24b-f4c6ba8a1a39.mp4

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by NHristov-sap** [comment]
Hello @ui5-webcomponents-topic-rd,

Please check if the colon of the label should be announced by the SR...

Best Regards,
Nikolay Hristov

**Comment by TeodorTaushanov** [comment]
This question is answered here:
https://github.com/SAP/ui5-webcomponents/issues/6488#issuecomment-1495878231
