### ISSUE TITLE
Alignment for ProductSwitch and ProductSwitchItem

### ISSUE THREAD

**Issue by MetalCar** [SAP/ui5-webcomponents#6594]
### Is your feature request related to a problem?

I want to set the alignment for `ProductSwitchItems` in a `ProductSwitch`. Currently all `ProductSwitchItems` are left-aligned within the `ProductSwitch`-Container. Unfortunately there's no way to override this behaviour.

### Describe the solution you'd like

 So it would be nice to set the alignment with a property `alignment="left|center|right"` or something else.

**Comment by dobrinyonkov** [comment]
Hello @MetalCar,

Thanks for reporting this.
Alignment can already be achived by styling the custom element directly. 
See: https://codesandbox.io/s/ui5-webcomponents-forked-p6lc7l?file=/index.html

Please try it and let us know if you face any other issues.

Kind Regards,
Dobrin

**Comment by dobrinyonkov** [comment]
Hi @MetalCar with #6683 now merged you should be able to use the `justify-content` property on the custom element which will be inherited by the root element inside the shadow dom.

**Comment by MetalCar** [comment]
Hi @dobrinyonkov . Thank you for that quick response - i will try this on monday at work :)
