### ISSUE TITLE
UploadCollection: onItemDelete is not fired

### ISSUE THREAD

**Issue by rathlukas** [SAP/ui5-webcomponents#6595]
### Describe the bug

The onItemDelete event is not working.
The deleteButton Property on UploadCollectionItem is ignored as well.

### Isolated Example

https://codesandbox.io/s/frosty-bash-2zkhsi?file=/src/App.js

### Reproduction steps

1.
2.
3.
...

### Expected Behaviour

onItemDelete event handler is fired

### UI5 Web Components for React Version

1.9.1

### UI5 Web Components Version

1.10.5

### Browser

Chrome

### Operating System

Windows 11

**Comment by NHristov-sap** [comment]
Hello @ui5-webcomponents-topic-rd,

Please check/consult the reporter about the issue.
Duplicated with #6596.

Best Regards,
Nikolay Hristov

**Comment by rathlukas** [comment]
Hi, ah ok, I didn't know that the component has to be in the "Delete" mode.
Thanks this solved my problem.

best regards,
Lukas Rath
