### ISSUE TITLE
UploadCollectionItem: deleteButton Property is ignored

### ISSUE THREAD

**Issue by rathlukas** [SAP/ui5-webcomponents#6596]
### Describe the bug

The deleteButton Property is not rendered by UploadCollectionItem.

### Isolated Example

https://codesandbox.io/s/frosty-bash-2zkhsi?file=/src/App.js

### Reproduction steps

1.
2.
3.
...

### Expected Behaviour

deleteButton Property is rendered correctly.

### UI5 Web Components for React Version

1.9.1

### UI5 Web Components Version

1.10.5

### Browser

Chrome

### Operating System

Windows 11

**Comment by NHristov-sap** [comment]
Hello @ui5-webcomponents-topic-rd,

Please check/consult the reporter about the issue.
Duplicated with #6595.

Best Regards,
Nikolay Hristov

**Comment by dimovpetar** [comment]
Hello @rathlukas,

Although this slot is inherited from the ListItem, it is not supported by the UploadCollectionItem. We are discussing internally whether it is actually needed. Do you have a use case to show why is it meaningful for the UploadCollection?

Best regards,
Petar

**Comment by rathlukas** [comment]
Hi @dimovpetar,

actually no, it would have been just a workaround to get the delete button event, as I had problems with that:
https://github.com/SAP/ui5-webcomponents/issues/6595

Thanks and best regards,
Lukas
