### ISSUE TITLE
Travel-request Icon: Icon looks different compared to SAP-icons library

### ISSUE THREAD

**Issue by Brahmansh** [SAP/ui5-webcomponents#6601]
### **Bug Description**
travel-request icon looks different compared to SAP-icons library

### **Expected Behavior**
travel-request icon should look same in both UI5 WC and SAP-icons library.

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/Icon/
2. Edit any basic icon in the chrome developer tools and change its name to 'travel-request'
3. Compare it with travel-request icon in SAP-icons library https://sdk.openui5.org/test-resources/sap/m/demokit/iconExplorer/webapp/index.html#/overview/SAP-icons/?tab=grid&icon=travel-request&search=travel-request

### **Context**
- UI5 Web Components version: 1.10.0
- OS/Platform: MacOS
- Browser: Chrome
- Affected component: Icon

### **Log Output / Stack Trace / Screenshots**
UI5 WC screenshot -
<img width="660" alt="Screenshot 2023-02-27 at 3 29 47 PM" src="https://user-images.githubusercontent.com/8809747/221713631-411ae1b1-1635-47d7-8c73-1b1b925278e9.png">

Icons in SAP-icons library -
<img width="1791" alt="Screenshot 2023-02-27 at 3 24 59 PM" src="https://user-images.githubusercontent.com/8809747/221713684-383f0f42-1dd4-4b20-abe6-6492a9575131.png">

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by ilhan007** [comment]
Hello @Brahmansh

The update is done, just not released - take a look at the preview deployment:
https://sap.github.io/ui5-webcomponents/**main**/playground/components/Icon/

1.11.0 is coming in few days and it prings update of SAP-icon, SAP-TNT-icons and SAP-business-suit-icons

if you need it urgently - install the pre-release version 
https://github.com/SAP/ui5-webcomponents/releases/tag/v1.11.0-rc.1
