### ISSUE TITLE
Page: Content is not displaid correctly

### ISSUE THREAD

**Issue by cpf-hse** [SAP/ui5-webcomponents#6602]
### **Bug Description**
The default slot of the fiori page web component is not visible.

Src: https://codesandbox.io/s/ui5-webcomponents-forked-dbptui?file=/src/index.js

### **Expected Behavior**
Render it as shown in the playground.
https://sap.github.io/ui5-webcomponents/playground/components/Page/

### **Steps to Reproduce**
1. Go to [CodeSandbox](https://codesandbox.io/s/ui5-webcomponents-forked-dbptui?file=/src/index.js)
2. Check the example.

### **Isolated Example**
If possible, please provide an isolated example by forking [CodeSandbox](https://codesandbox.io/s/ui5-webcomponents-forked-dbptui?file=/src/index.js).

### **Context**
- UI5 Web Components version: 1.10.5
- OS/Platform: Windows 10
- Browser: Chrome Version 110.0.5481.178
- Affected component: Page

### **Log Output / Stack Trace / Screenshots**
<img width="392" alt="image" src="https://user-images.githubusercontent.com/103113173/221816037-b69394be-6be4-4c6a-87aa-6505ee3b8fb1.png">

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by NHristov-sap** [comment]
Hi @cpf-hse,

Page web component takes 100% of the height of the parent container, which in your case is HTML/BODY. As the parent have no height set, the Page is not displayed correctly.

If you set height of the NTML and BODY to 100% (see STYLE tag in the HEAD), everything works fine, you can see it here: https://codesandbox.io/s/ui5-webcomponents-forked-nbxtqj?file=/index.html

Best Regards,
Nikolay Hristov

**Comment by NHristov-sap** [comment]
Hi @cpf-hse ,

I will notify the responsible team about this.

Best Regards,
Nikolay Hristov

**Comment by NHristov-sap** [comment]
Hi @cpf-hse ,

I have contacted the team and they said that the update is already done, and will be available in the next version :)
https://github.com/SAP/ui5-webcomponents/pull/6476/files

Best Regards,
Nikolay Hristov
