### ISSUE TITLE
Non-Visible Interactive Item in FlexibleColumnLayout 

### ISSUE THREAD

**Issue by IrvinDelgado** [SAP/ui5-webcomponents#6610]
### **Bug Description**

The user is able to tab into items that are not visible. Note this only happens before the right panel is shown.

### **Expected Behavior**

I expect that if the items are not visible then they should not be accessible.

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-flexiblecolumnlayout--docs
2. Scroll All the way down to the section 'FlexibleColumnLayout with different columns'
3. Keep pressing <kbd>Tab</kbd> until the focus is on the first list item
4. <kbd>Tab</kbd> one more time and notice that the focus is not on the page anymore
5. Hit <kbd>Enter</kbd> Then notice that popup will show, notice the image below

### **Isolated Example**
If possible, please provide an isolated example by forking [CodeSandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html).

### **Context**
- UI5 Web Components version: 1.9.2
- OS/Platform: Mac
- Browser: Chrome
- Affected component: FlexibleColumnLayout

### **Log Output / Stack Trace / Screenshots**

<img width="1218" alt="Screenshot 2023-02-28 at 3 56 02 PM" src="https://user-images.githubusercontent.com/62973847/222014678-5068e3de-5a5f-4609-9d38-c6f848a7c4e9.png">

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by NHristov-sap** [comment]
Hello @ui5-webcomponents-topic-p,

To reproduce the issue, please follow the steps below:

1. Go to https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-flexiblecolumnlayout--docs
2. Scroll All the way down to the section 'FlexibleColumnLayout with different columns'
3. Keep pressing Tab until the focus is on the first list item
4. Tab one more time and notice that the focus is not on the page anymore
5. Hit Enter Then notice that popup will show

It seems that when you press Tab, the focus goes somewhere in the hidden area (probably detail area). Once the detail area is opened and then closed, the focus seems to work properly.

Please check.

Best Regards,
Nikolay Hristov
