### ISSUE TITLE
Date Range Picker Input Field can only be cleared when Focus has been moved out of the field before

### ISSUE THREAD

**Issue by MFel0123** [SAP/ui5-webcomponents#6613]
### **Bug Description**
We noticed that the date range picker field input value has to be cleared manually (by deleting the existing date range text and pressing ENTER). This only seems to work (change handler event has to be reached) when the focus is not in this field anymore. So you have to click somewhere else on the screen for example. Otherwise (if you set a date range, then stay in the date range picker input field, then clear it again) the change handler of the date range picker will not be reached and nothing changes on the UI.

### **Expected Behavior**
It should always be possible to clear the date range picker input field (no matter where the focus is).

### **Steps to Reproduce**
I prepared an isolated example. Please reproduce the steps here:
https://codesandbox.io/s/hungry-darkness-rkoj94?file=/src/app/app.component.html

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by NHristov-sap** [comment]
Hello @ui5-webcomponents-topic-p,

It seems that Date Range Picker doesn't recognize the value change, when value is selected by a picker, and then is cleared manually (deleted) without leaving the Picker's input field. This is demonstrated in a snippet below. The reproducing steps are in snippet too:

https://codesandbox.io/s/hungry-darkness-rkoj94?file=/src/app/app.component.html

Best Regards,
Nikolay Hristov

**Comment by tsanislavgatev** [comment]
@MFel0123 ,

The issue was fixed in the latest version. This can be tested in https://codesandbox.io/s/twilight-star-hml0lb

Best Regards,
Tsanislav
