### ISSUE TITLE
Bar: Footer Floater is not following fiori guidelines, it has a black boarder around it.

### ISSUE THREAD

**Issue by CauaS** [SAP/ui5-webcomponents#6620]
### Describe the bug

Fiori Guidelines shows a bar like following: https://sap.github.io/ui5-webcomponents-react/?path=/story/layouts-floorplans-bar--with-custom-elements&args=design:FloatingFooter
![image](https://user-images.githubusercontent.com/37887533/222166087-e2f7db6b-0678-4881-bb10-de853e054162.png)

Setting the property `design` as `FloatingFooter`, a black boarder appears around the bar, this black border in not accordingly to Fiori Guidelines https://experience.sap.com/fiori-design-web/footer-toolbar/#components
![image](https://user-images.githubusercontent.com/37887533/222166928-c378d4b8-43b4-48b5-b18e-0e6805af308a.png)

### Isolated Example

https://codesandbox.io/s/affectionate-robinson-fgr9r9?file=/src/App.js

### Reproduction steps

1.
2.
3.
...

### Expected Behaviour

The black board should not appear, only the shadow

### UI5 Web Components for React Version

1.8.1

### UI5 Web Components Version

1.10.5

### Browser

Chrome, Edge, Firefox, Safari

### Additional Context

This component, has a style constructed like this 
![image](https://user-images.githubusercontent.com/37887533/222172527-ef20145a-1dba-486a-b05d-3a05c03392af.png)

And has this var `--sapContent_Shadow1`
![image](https://user-images.githubusercontent.com/37887533/222173019-ab0d44e8-326f-449d-9b39-dd39f7202634.png)

This second part only is responsible for the shadow: `0 0.125rem 0.5rem 0 rgba(0, 0, 0, 0.3)`, the first is the one that applies the black border

**Comment by MarcusNotheis** [comment]
Thanks for reporting! I'll forward this issue to our UI5 Web Components Colleagues as the affected component is developed in their repository.

**Comment by hinzzx** [comment]
Hi @CauaS,

After check up with the latest VD Specifications, to me it seems like the Bar's parameters and their values are correct, as well as its looks according to them.

Best Regards,
Stoyan
