### ISSUE TITLE
[i18n] Hebrew translation not working

### ISSUE THREAD

**Issue by ej612** [SAP/ui5-webcomponents#6635]
### **Bug Description**
We have a `messagebundle_XY.properties` file for every supported language. The file for Hebrew is called `messagebundle_he.properties`.

So if I want to set the language to Hebrew, I do this:
```
import { setLanguage } from '@ui5/webcomponents-base/dist/config/Language.js';
setLanguage('he');
```

However, this doesn't work, and will fall back to the default English locale instead. I have done some debugging, and it turns out this is due to the fact that there are two IDs for Hebrew: An old one, 'iw', and a new one, 'he'.
`setLanguage('he')` above calls `fetchI18nBundle()` in `@ui5/webcomponents-base/dist/asset-registries/i18n.js`, which calls `normalizeLocale()`, which will map 'he' to 'iw' (`language` on line 81 is 'he', while `localeId` on line 83 is 'iw'):

![Untitled](https://user-images.githubusercontent.com/110408767/222673487-0e3d73b2-6296-4ae5-9851-7b3b2420b203.png)

Subsequently, the code will look for a `i18n\assets\i18n\messagebundle_iw.json` file. Ours, however, is called `messagebundle_he.json`, and the lookup will fail.

The mapping from 'he' to 'iw' is done in `M_ISO639_NEW_TO_OLD` in `packages/base/src/locale/normalizeLocale.ts`. We are on `@ui5/webcomponents` v1.9.3 and have the same problem with Indonesian, the ID of which is 'id' on our end but ends up being 'in' according to this map. I've seen that the mapping for Indonesian has since been removed from this map, so we shouldn't have this problem once we update.

I don't know why this mapping is done, but my ask is whether it's possible to also remove the mapping for Hebrew.

**Comment by NHristov-sap** [comment]
Hello @ui5-webcomponents-team,

Please look at this request as it requires changes in core functionality.

Best Regards,
Nikolay Hristov
