### ISSUE TITLE
[typescript]: use template literal types to avoid in most cases meaningless imports on user's side

### ISSUE THREAD

**Issue by g-cheishvili** [SAP/ui5-webcomponents#6636]
### **Feature Request Description**
Currently, the Enum types are used directly and that forces users, who use typescript, to import those enums and explicitly either transform the values onto the enums, or use enum properties.

### **Proposed Solution**
use in component classes template literal types.
so for example in case of the Button.design, it's type would be \`${ButtonDesign}\`, which is gonna result in union type of all the values from the enum. This way user will not have to import the enum

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: ui5-webcomponents-ngx
- Business impact: Gets in a way of reusing the types from ui5 team

**Comment by ilhan007** [comment]
Hello @g-cheishvili thank you for the suggestion, 

we think it's a good idea to use Union Types, as the enums should be exported and imported and at the same time static checks, autocompletions remain. We will still have the enums for the JSDoc, but we will use the string literal to produce the Union Types.

We will plan this and implement step by step for all enum occurrences.

Thank you,
ilhan
