### ISSUE TITLE
ui5-bar: padding/border issues when slotted as header/footer of Dialog or ResponsivePopover

### ISSUE THREAD

**Issue by codefactor** [SAP/ui5-webcomponents#6638]
### **Bug Description**
The UI5-bar when slotted as the header or footer of a Dialog or ResponsivePopover has an extra top border on the footer, and too much padding on the left/right sides of both header and footer.

### **Expected Behavior**
The Dialog or Bar should account for when using this combination of components. Do not render a second border/box-shadow on the footer, and don't add extra left/right padding. When there is text content in the Dialog and in the startContent of the Bar, that text content should align left perfectly.

### **Steps to Reproduce**
1. https://codesandbox.io/s/ui5-webcomponents-forked-2sflyw?file=/index.html
2. See the double border on the footer and the extra left/right padding

### **Isolated Example**
https://codesandbox.io/s/ui5-webcomponents-forked-2sflyw?file=/index.html

### **Context**
- UI5 Web Components version: latest
- OS/Platform: any
- Browser: any
- Affected component: bar, dialog

### **Log Output / Stack Trace / Screenshots**
```
{...}
```
### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-b  @SAP/ui5-webcomponents-topic-rd  this is a cross topic and it's about the `ui5-bar` usage in `ui5-dialog` and `ui5-responsive-popover` as a header/footer. In this case - there are some additional paddings and borders. If the ui5-bar is not supposed to be used in this use-case, please suggest alternative.
