### ISSUE TITLE
DateTimePicker, TimePicker

### ISSUE THREAD

**Issue by pylnata** [SAP/ui5-webcomponents#6647]
### Describe the bug

when I apply classname "ui5-content-density-compact" to div that wraps all app there is issue in DateTimePicker and TimePicker  with hours. It shows wrong position.
<img width="655" alt="Screenshot 2023-03-01 at 08 00 14" src="https://user-images.githubusercontent.com/33361478/222067111-52e1d4e5-c1ce-4476-96f0-49bdcd6256d9.png">

When I remove this class evrything is fine

### Reproduction steps

1.
2.
3.
...

### Expected Behaviour

Correct hours in component

### UI5 Web Components for React Version

1.9.0

### UI5 Web Components Version

1.10.4

### Browser

Chrome

**Comment by plamenivanov91** [comment]
Hello Hello @SAP/ui5-webcomponents-topic-b ,

According to the [documentation](https://github.com/SAP/ui5-webcomponents/blob/a9dde7f3a55dfb0a821555d51b0ffbbb51f23826/docs/2-advanced/02-RTL-and-compact-mode.md#compact-mode) we can add the **ui5-content-density-compact** class to a given component (not the body) and it should work as expected in its compact mode.

The issue that is reported is also reproducible with our internal samples.

Add the class as shown here:
`<ui5-datetime-picker id="dt" class="ui5-content-density-compact"></ui5-datetime-picker>`

Here is the result when we open it:
![Screenshot 2023-03-10 111845](https://user-images.githubusercontent.com/13866865/224276258-ceb115ff-ad43-4b4b-af83-35877acfe8ea.png)

Could you please look into it ?

Regards,
Plamen Ivanov
