### ISSUE TITLE
[Select]: Unable to force a Select value after a user picked one

### ISSUE THREAD

**Issue by davidmobbssap** [SAP/ui5-webcomponents#6648]
### Describe the bug

Hello,
I have a situation where I ask confirmation for a change in a Select dropdown. If I don't get confirmation I need to revert the Select value to the previous entry.
I am trying to achieve this by positioning the selected property on each of the Options to ensure that only the desired one has selected=true.
This does not work. Regardless of the selected values for the Options, the user's choice which I wanted to discard is in the Select dropdown.
Is this a bug ? Or am I doing it wrong ?
Thanks !
David.

### Isolated Example

https://codesandbox.io/s/busy-dhawan-nsu2u5

### Reproduction steps

1. Open the attached code sandbox.
2. Click on the dropdown to expand it
3. Pick value "Two (you should never be able to select this)"
...

### Expected Behaviour

The code should revert the dropdown to value "One (should always be selected)"
Instead, value "Two (you should never be able to select this)" is displayed.

### Screenshots or Videos

<img width="693" alt="image" src="https://user-images.githubusercontent.com/101794684/222467965-9c3e65ea-9319-4c80-be8d-c15b716b45ed.png">

### UI5 Web Components for React Version

1.10.3

### UI5 Web Components Version

1.8.0

### Browser

Edge

### Operating System

MacOS

**Comment by plamenivanov91** [comment]
Hello @SAP/ui5-webcomponents-topic-p ,

Take a look of this feature request.

Regards,
Plamen Ivanov

**Comment by dobrinyonkov** [comment]
Internal reference: BGSOFUIPIRIN-6091

**Comment by C3ntraX** [comment]
For React you could do somting like this as a workaround:

```
const prevProfile = selectedProfile;
flushSync(() => setSelectedProfile(profile));
try {
  // some error....
} catch (error) {
   flushSync(() => setSelectedProfile(prevProfile));
}
```
