### ISSUE TITLE
[typescript]: and api json

### ISSUE THREAD

**Issue by g-cheishvili** [SAP/ui5-webcomponents#6653]
### Bug Description

in API JSON enums are wrongfully declared as "classes"

example:

Look at the `sap.ui.webc.main.types.ButtonDesign` output in api.json

### Affected Component

everywhere, where Enum is used as a type

### Expected Behaviour

That's enum, so it should be named as such

### Steps to Reproduce

1.
2.
3.
...

### Priority

High

### UI5 Web Components Version

1.10.3

### Browser

Chrome

### Operating System

irrelevant

### Additional Context

This is needed for proper parsing of the api.json

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by plamenivanov91** [comment]
Hello @g-cheishvili ,

Can you give us the distribution where the mentioned api.json can be found and inspected?

Regards,
Plamen

**Comment by g-cheishvili** [comment]
> Hello @g-cheishvili ,
> 
> Can you give us the distribution where the mentioned api.json can be found and inspected?
> 
> Regards,
> Plamen

Build this project locally and look in dist

**Comment by ilhan007** [comment]
Hello @nnaydenow could you take a look, it's `class`, but should be `enum` I guess

```json
"kind": "class",
"name": "sap.ui.webc.main.types.AvatarShape",
 ```

**Comment by ilhan007** [comment]
Hi @g-cheishvili thank you for bringing this up, we will check it out, @nnaydenow  is already assigned to it.

BR,
ilhan

**Comment by nnaydenow** [comment]
Hi @g-cheishvili,

With #6658 enums will appear as kind: enum in api.json.

Regards,
Nayden
