### ISSUE TITLE
[ui5-avatar]: initials are not shown when icon attribute is provided

### ISSUE THREAD

**Issue by pankajpandey01** [SAP/ui5-webcomponents#6655]
### Bug Description

Scenario:
image slot: not provided
initials: provided
icon: provided

In above scenario, avatar is not showing initials, instead showing icons.

### Affected Component

ui5-avatar

### Expected Behaviour

Scenario:
image slot: not provided
initials: provided
icon: provided

In above scenario, avatar should shown initials.
Avatar render order should be image > initials > icon

### Isolated Example

https://codesandbox.io/s/ui5-webcomponents-forked-r3dgkg

### Steps to Reproduce

Please refer example.

### Priority

None

### UI5 Web Components Version

1.10.3

### Browser

Chrome, Edge, Firefox, Safari

### Additional Context

**Stakeholder Info** 

- Organization: {SuccessFactors}

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by yanaminkova** [comment]
Hello @pankajpandey01,

The icon is with higher rendering priority than the initials .
I would advise you to use only one of the attributes and not two at the same time. In your case, since you want to show initials, there is no need of the icon attribute. If the provided initials are not valid, the renderer will add fallback icon by itself.

Thanks and regards,
Yana

**Comment by pankajpandey01** [comment]
Hi @yanaminkova 
We want to show "person-placeholder" as fallback icon. Currently "employee" is shown as fallback from avatar component . Please suggest, how we can change default fallback icon?

**Comment by yanaminkova** [comment]
Hi @pankajpandey01,
For the moment, this is not possible, but I created a backlog item, so we will add this functionality.
Internal Reference: [BGSOFUIPIRIN-6092](https://jira.tools.sap/browse/BGSOFUIPIRIN-6092)

**Comment by yanaminkova** [comment]
Hi @pankajpandey01,

the functionality for setting custom fallback icon is already available.

Regards,
Yana
