### ISSUE TITLE
[Feature Request]: Create a codeeditor (Ace-based) component

### ISSUE THREAD

**Issue by vladitasev** [SAP/ui5-webcomponents#6656]
### Feature Request Description

Have a component similar to:
https://sapui5.hana.ondemand.com/sdk/#/api/sap.ui.codeeditor.CodeEditor%23overview

### Proposed Solution

N/A

### Priority

Medium

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ilhan007** [comment]
Ace editor could be used directly without a web component on top as not additional features (as theming, a11y) are specified.
