### ISSUE TITLE
[SF][A11y][Dialog] Resizable dialog, header getting focus its not announcing help text to resize the dialog.

### ISSUE THREAD

**Issue by saorabhkr** [SAP/ui5-webcomponents#6659]
### Describe the bug

Describe the bug:
Resizable dialog announcement is missing when focus is moved to the header.

### Isolated Example

https://sap.github.io/ui5-webcomponents-react/?path=/story/modals-popovers-dialog--default&args=resizable:!true

### Reproduction steps

Go to [Dialog Document Page](https://sap.github.io/ui5-webcomponents-react/?path=/story/modals-popovers-dialog--default&args=resizable:!true)
Click on 'Open Dialog' button
Inspect speech history of NVDA screen reader
See the announcement of Dialog, when focus is moved to header.
<img width="1344" alt="Screenshot 2023-03-07 at 12 09 25 PM" src="https://user-images.githubusercontent.com/5204425/223345066-84a06bd8-8a9a-4d38-ad97-ec6a8d071764.png">

### Expected Behaviour

When Dialog header gets the focus it should announce "Use Shift+Arrow keys to resize". 

Example is taken from SAPUI5 dialog, 

https://openui5.hana.ondemand.com/#/entity/sap.m.Dialog/sample/sap.m.sample.Dialog
<img width="1608" alt="Screenshot 2023-03-07 at 1 12 49 PM" src="https://user-images.githubusercontent.com/5204425/223356938-a8c80ec9-8153-43a4-bc46-619b114eb268.png">

### UI5 Web Components for React Version

1.8.1

### UI5 Web Components Version

1.10.4

### Browser

Chrome

### Operating System

MacOS 13.2.1 (22D68)

**Comment by plamenivanov91** [comment]
Hello Hello @SAP/ui5-webcomponents-topic-rd ,

Could you please investigate why the "**Use Shift+Arrow keys to resize**" is missing from the announcement when the header of the **resizable Dialog** is focused while NVDA screen reader is active?

Regards,
Plamen Ivanov

**Comment by s-todorova** [comment]
Hello @saorabhkr,

We have taken this into consideration and will have a BI planned for implementing this feature soon.
Thank you for bringing our attention to this.

Best regards,
Siyana

**Comment by olannyv** [comment]
Internal Jira BI-2988 is planned for the next monthly release
