### ISSUE TITLE
ComboBox

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents#666]
**Is your feature request related to a problem? Please describe.**
We have lots of applications with a e.g. a filter bar or a drop down field where the selection is either empty or exactly 1 item. In addition to that, we would need some kind of search/typeahead feature. Therefore we would like to use at ComboBox like the `sap.m.ComboBox` in "classic" UI5 

**Describe the solution you'd like**
Implement a `ComboBox` component or enhance the `MultiComboBox` with a `single-selection` (or any other better name ;)) prop.

**Describe alternatives you've considered**
None. Select is not working for us because it misses the search functionality.

**Additional context**

**Comment by vbersch** [comment]
Are there any plans to work on this in the near future? We would be really happy to have a ComboBox.

**Comment by vladitasev** [comment]
First version is released
