### ISSUE TITLE
[SF][ui5-busy-indicator]: Full height layout is broken by busy indicator

### ISSUE THREAD

**Issue by ee92** [SAP/ui5-webcomponents#6668]
### Bug Description

CSS property `height: 100%;` is not respected by the ui5-busy-indicator.

Using the busy indicator makes it impossible for the wrapped element to be 100% height of the parent.

### Affected Component

ui5-busy-indicator

### Expected Behaviour

The busy indicator should allow the child element to expand to fill 100% of the height of of the busy indicator component

### Isolated Example

https://codesandbox.io/s/ui5-webcomponents-forked-g96uv?file=/index.html

### Steps to Reproduce

1. Go to https://codesandbox.io/s/ui5-webcomponents-forked-g96uv?file=/index.html 
2. Notice that the element wrapped by the busy indicator is not expanding to 100% of the height like it would otherwise.

### Priority

High

### UI5 Web Components Version

1.10.0

### Browser

Chrome

### Additional Context

Organization: SuccessFactors

Business Impact: Unable to create layout when using busy indicator

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by plamenivanov91** [comment]
Hello @SAP/ui5-webcomponents-topic-p ,

The problem is easily fixed if we set **height** to **100%** of the **ui5-busy-indicator-root** element in the shadow DOM. But then the indicator itself is not centered according to its slotted element but rather to its parent.

In my opinion the current is behavior is the correct one. The indicator to be centered according to its slotted element and not its parent.

Could you please confirm this?

Regards,
Plamen Ivanov

**Comment by dobrinyonkov** [comment]
Hi @SAP/ui5-webcomponents-topic-rd,

could you please assist with this issue? Perpahps a `height: inherit;` on the root element would be nice to have.

Kind Regads,
Dobrin

**Comment by ee92** [comment]
@dobrinyonkov that solution works. It is a pretty big issue for us, so if it can be released soon that would be great. Thank you!

**Comment by C3ntraX** [comment]
What is with cases like this?

https://codesandbox.io/p/sandbox/condescending-sanne-f25rju?file=%2Fsrc%2FApp.tsx&selection=%5B%7B%22endColumn%22%3A21%2C%22endLineNumber%22%3A19%2C%22startColumn%22%3A21%2C%22startLineNumber%22%3A19%7D%5D

The button is not visible if the page is wrapped in a busyindicator?
I have huge problems with this ...

**Comment by LidiyaGeorgieva** [comment]
Hello @C3ntraX ,

The problem in your example is not the BusyIndicator.
If I delete it the button is still not visible.
The problem is that the page have dimensions: 48x0. 

If you think there is an issue in the ui5 components please open a separate github issue.

Best Regards,
Lidiya

**Comment by LidiyaGeorgieva** [comment]
Hello, @C3ntraX ,

Please open separate github issue for that problem.
If you think it is related to this one mention it in the description.

Best Regards,
Lidiya
