### ISSUE TITLE
[ShellBar]: After click on menuItem, onMenuItemClick gives error in FireFox browser

### ISSUE THREAD

**Issue by Rahishsaifi** [SAP/ui5-webcomponents#6679]
### Describe the bug

I am using ShellBar in the Project.
When I click on menuItem, Then onMenuItemClick function called, and breaks the UI in FireFox browser.
It is working fine is chrome and edge but only it breaks in Firefox browser.

TypeError: this.menuPopover is undefined

### Reproduction steps

1.
2.
3.
...

### Expected Behaviour

It should navigate to menu

### Screenshots or Videos

![Screenshot 2023-03-07 172229](https://user-images.githubusercontent.com/16429797/223414675-52e66c26-8b74-46a5-88d4-8d84ebb79952.png)
![Screenshot 2023-03-07 172332](https://user-images.githubusercontent.com/16429797/223414816-f4a80983-092c-45b8-a0e8-ef155034ad76.png)

### UI5 Web Components for React Version

"@ui5/webcomponents-react": "1.7.1"

### UI5 Web Components Version

  "@ui5/webcomponents": "1.9.2"

   ###All other version

    "@ui5/webcomponents": "1.9.2",
    "@ui5/webcomponents-base": "1.8.0",
    "@ui5/webcomponents-fiori": "1.8.0",
    "@ui5/webcomponents-icons": "1.8.0",
    "@ui5/webcomponents-react": "1.7.1",
    "@ui5/webcomponents-react-base": "^1.1.0",
    "luxon": "2.5.2",
    "react": "^17.0.2",
    "react-dom": "17.0.2",
    "react-helmet": "^6.1.0",
    "react-i18next": "11.16.9",
    "react-jss": "10.9.0",
    "react-router-dom": "^5.2.0",

### Browser

Firefox

### Operating System

Windows

**Comment by plamenivanov91** [comment]
Hello @Rahishsaifi ,

I tested the scenario and there are no exceptions / errors.

Here is my environment:
"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0" 

Could you please update your FF browser, hard clean the cache and try again?

Regards,
Plamen Ivanov

**Comment by Rahishsaifi** [comment]
I fixed by resize of window by css.
Thanks everyone
