### ISSUE TITLE
StepInput: Default alignment should be right

### ISSUE THREAD

**Issue by DMihaylova** [SAP/ui5-webcomponents#6687]
According to VD & UX the correct alignment should be on the right as it currently is in UI5.

UI5: https://ui5.sap.com/#/entity/sap.m.StepInput/sample/sap.m.sample.StepInput
Web Components: https://sap.github.io/ui5-webcomponents/playground/components/StepInput/

**Comment by plamenivanov91** [comment]
Hello @SAP/ui5-webcomponents-topic-b ,

As it's mentioned in our [Visual Spec](https://wiki.one.int.sap/wiki/pages/viewpage.action?pageId=2698915417) the default text alignment should be at the end / on the right.

Could you please fix this?

Regards,
Plamen Ivanov
