### ISSUE TITLE
[SplitButton]: sizes are not correct when icon is set without a content

### ISSUE THREAD

**Issue by MapTo0** [SAP/ui5-webcomponents#6688]
### Bug Description

Padding sizes are not correct when icon is set without a content of the `ui5-split-button`

<img width="117" alt="image" src="https://user-images.githubusercontent.com/5821279/224318882-b86a744c-743c-419a-befe-df265f4782c6.png">

### Affected Component

ui5-split-button

### Expected Behaviour

Paddings are correct as in UI5

<img width="125" alt="image" src="https://user-images.githubusercontent.com/5821279/224318979-faa5f13a-e251-4a7e-94d0-749bd85cad59.png">

### Isolated Example

https://codesandbox.io/s/elegant-morse-vw0kmp?file=/index.html

### Steps to Reproduce

1. Open the sandbox: https://codesandbox.io/s/elegant-morse-vw0kmp?file=/index.html

### Priority

Medium

### UI5 Web Components Version

latest

### Browser

Chrome, Edge, Firefox, Safari

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by plamenivanov91** [comment]
Hello @SAP/ui5-webcomponents-topic-b ,

If we use only icon (without text) in SplitButton, the icon is not centered according to its container as it's shown in the isolated sample.

Here is how the same scenario looks in OpenUI5:
![Screenshot 2023-03-10 153818](https://user-images.githubusercontent.com/13866865/224330942-f96ba2c2-8162-4fe7-9474-822b708b9ea0.png)

Could you please align the icon correctly?

Regards,
Plamen Ivanov
