### ISSUE TITLE
[typescript]: source maps missing for src/generated

### ISSUE THREAD

**Issue by vladitasev** [SAP/ui5-webcomponents#6711]
### Bug Description

Try: `npx create-react-app my-app --template @ui5/webcomponents-react-seed` and then run the app.

Notice the console warnings on the CLI.

### Steps to Reproduce

1.
2.
3.
...

### Priority

None

### UI5 Web Components Version

latest

### Browser

Chrome, Edge, Firefox, Safari

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ilhan007** [comment]
Could be related to the existing issue
https://github.com/SAP/ui5-webcomponents/issues/6446
