### ISSUE TITLE
Tree: conditional rendered `TreeItems` don't have checkboxes in "MultiSelect" mode

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#6726]
### Bug Description

When a `Tree` is conditionally rendering its children, then the checkbox for sub-items is not displayed.

### Expected Behaviour

Checkboxes should always be displayed, no matter on what level or when the TreeItem is rendered.

### Isolated Example

https://codesandbox.io/s/ui5-webcomponents-forked-162zdt?file=/src/index.js

### Steps to Reproduce

1. Expand the first node
2. See that the conditional rendered children don't have a checkbox.

### Priority

None

### UI5 Web Components Version

1.11.0

### Browser

Chrome, Edge, Firefox, Safari

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by s-todorova** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

In the provided example https://codesandbox.io/s/ui5-webcomponents-forked-162zdt?file=/src/index.js, it can be observed that a Tree in "MultiSelect" mode does not display the checkboxes for its conditionally rendered children.
Could you please take a look at this issue?

Best regards,
Siyana

**Comment by dobrinyonkov** [comment]
Hi @vladitasev, the List component is not being invalidated here when new (sub) items are added to the first item through the Tree. Could you check?

**Comment by vladitasev** [comment]
Hi @dobrinyonkov @Lukas742 @pskelin 

I spent quite some time on that and I decided to go with a workaround until I make up my mind how to address this on framework level. The change could be potentially huge, and would require extensive testing and might take some time. 

Therefore, I'd suggest we start with a workaround and remove it when the framework itself is adapted.

Regards,
Vladi
