### ISSUE TITLE
[Feature Request]: Illustrations should export their name as default export

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents#6735]
### Feature Request Description

When using illustrations, I would like to import the name the illustration via the default import instead of importing the loader without import specifier and then reference it by name later. This concept has already been introduced to icon imports as well.
This will give an better overview in the code which illustration is used.

### Proposed Solution

Illustrations should export their name as default export (like the icons).
The `Tnt` illustrations should contain the `Tnt` prefix in their exported names.

Examples:
```js
import noDataIllustration from "@ui5/webcomponents-fiori/dist/illustrations/NoData.js";
// noDataIllustration should be "NoData"

import sessionExpiredIllustration from "@ui5/webcomponents-fiori/dist/illustrations/tnt/SessionExpired.js";
// sessionExpiredIllustration should equal "TntSessionExpired"
```

### Additional Context

Icons PR for reference: https://github.com/SAP/ui5-webcomponents/pull/5207

### Priority

Medium

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by s-todorova** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

Could you please take a look of this feature request?

Siyana

**Comment by dobrinyonkov** [comment]
Hey @MarcusNotheis,

Just to be sure we are on the same page about the use case. Would you like the exported value to hold the name of the illusttration as string?


```js
import noDataIllustration from "@ui5/webcomponents-fiori/dist/illustrations/NoData.js";

console.log(noDataIllustration) // "NoData"

illustratedMessageEl.setAttribute("name", noDataIllustration)
```

Is the above similar to what you want to achive?

**Comment by MarcusNotheis** [comment]
Hi @dobrinyonkov,

yes exactly 🙂 
This would help to have a better overview which imported illustrations are actually used, and when removing/changing an illustration the IDE could automatically optimize imports and remove the old illustration.
