### ISSUE TITLE
[SF][A11y][ResponsivePopover]: setting accessible-role='tooltip' not work

### ISSUE THREAD

**Issue by 2bno1** [SAP/ui5-webcomponents#6737]
### Bug Description

Setting `accessible-name` of ui5-responsive-popover to `tooltip` does not take effect. It sill set `role` to `dialog` for the rendered dom.

### Affected Component

ResponsivePopover

### Expected Behaviour

It sets `role` to `tooltip` for the rendered dom.

### Isolated Example

https://codesandbox.io/s/ui5-webcomponents-responsive-popover-w2mx67?file=/src/index.js

### Steps to Reproduce

1. Open https://codesandbox.io/s/ui5-webcomponents-responsive-popover-w2mx67?file=/src/index.js
2. Click 'Open Pop Over' buttom
3. Observe the `role` attribute of the rendered dom

### Log Output, Stack Trace or Screenshots

![Screenshot 2023-03-20 at 13 55 38](https://user-images.githubusercontent.com/1751846/226265188-0742e4d9-b056-48e1-af98-9e8977f43466.png)

### Priority

Medium

### UI5 Web Components Version

1.11.0

### Browser

Chrome

### Operating System

macOS

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by 2bno1** [comment]
@s-todorova Yes, I corrected the title of the issue to `accessible-role`, thanks.
In my project scenario, I used ResponsivePopover to show a tooltip which is a little big long so native `tooltip` attribute is not quite appropriate. In this case, neither `dialog` nor `alertdialog` is appropriate. Instead, `tooltip` (https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tooltip_role) is a better choice.
So can you accept more `role` alternative, at least `tooltip`?

Thanks

**Comment by s-todorova** [comment]
Hello @SAP/ui5-webcomponents-topic-rd,

Could you take a look at this issue?

Siyana

**Comment by TeodorTaushanov** [comment]
Hi @2bno1,

In your case you can set accessible-role="None" and put a div with role="menu" inside:

```
 <ui5-popover accessible-role="None">
      <div role="menu">
        <div role="menuitem">item 1</div>
        <div role="menuitem">item 2</div>
      </div>
 </ui5-popover>
```

Best,
Teo

**Comment by TeodorTaushanov** [comment]
Hi @2bno1,

In your case you can set the popover accessible-role="None" and put a div with role="tooltip" inside the popover:

```
  <ui5-responsive-popover accessible-role="None">
      <div role="tooltip">
        Some tooltip
      </div>
    </ui5-responsive-popover>
```

Best,
Teo

**Comment by 2bno1** [comment]
@TeodorTaushanov Thanks for the workaround. However, I'm using `ResponsivePopover` of `@ui5/webcomponents-react` (https://github.com/SAP/ui5-webcomponents-react/blob/main/packages/main/src/webComponents/ResponsivePopover/index.tsx) which wraps `ui5-responsive-popover` of `@ui5/webcomponents`, and not able to customize the child dom element. So the workaround is not working for me.

**Comment by TeodorTaushanov** [comment]
Hi @2bno1,

Can you provide us some code example of your usage?

Best,
Teo

**Comment by 2bno1** [comment]
@TeodorTaushanov [Here](https://codesandbox.io/p/sandbox/musing-nightingale-dcjl8r?file=%2Fsrc%2FApp.tsx) is a code example.

Thanks

**Comment by TeodorTaushanov** [comment]
Hi @2bno1,

You can modify your code to:

```
<ResponsivePopover accessibleRole="None" ref={popoverRef}>
        <div role="tooltip">Content</div>
</ResponsivePopover>
```

[Example](https://codesandbox.io/p/sandbox/icy-wildflower-98yvks?file=%2Fsrc%2FApp.tsx&selection=%5B%7B%22endColumn%22%3A17%2C%22endLineNumber%22%3A9%2C%22startColumn%22%3A17%2C%22startLineNumber%22%3A9%7D%5D)

Best,
Teo
