### ISSUE TITLE
[Feature Request]: Public exports from base package

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents#6739]
### Feature Request Description

https://github.com/SAP/ui5-webcomponents/blob/bead2646325f86a6e5f136d48f8b04ec7983155c/packages/base/index.js

The `@ui5/webcomponents-base` package is currently exporting a `index.js` file with `export { UI5Element }` as only export.
I would suggest to use this `index.js` file as public API of the base package, all "deep" import paths should be treated as internals.

Exporting the public API via a single entrypoint will help to better support advanced bundling options like webpack module federation. In addition, the import statements for end-users are easier to write and understand.

### Proposed Solution

Based on the Usage in UI5 Web Components for React, I would suggest the following file content for `packages/base/index.js`:
```js
import { registerI18nLoader } from './dist/asset-registries/i18n.js';
import { attachBoot } from './dist/Boot.js';
import { setFetchDefaultLanguage, setLanguage } from './dist/config/Language.js';
import { getRTL } from './dist/config/RTL.js';
import { getTheme, setTheme } from './dist/config/Theme.js';
import {
  getEffectiveScopingSuffixForTag,
  setCustomElementsScopingRules,
  setCustomElementsScopingSuffix
} from './dist/CustomElementsScope.js';
import EventProvider from './dist/EventProvider.js';
import I18nBundle, { getI18nBundle } from './dist/i18nBundle.js';
import applyDirection from './dist/locale/applyDirection.js';
import { attachLanguageChange, detachLanguageChange } from './dist/locale/languageChange.js';
import MediaRange from './dist/MediaRange.js';
import { addCustomCSS, attachThemeLoaded, detachThemeLoaded } from './dist/Theming.js';
import UI5Element from './dist/UI5Element.js';
import { getRGBColor } from './dist/util/ColorConversion.js';

export default UI5Element;

export * from './dist/Device.js';
export {
  EventProvider,
  I18nBundle,
  MediaRange,
  UI5Element,
  addCustomCSS as internal_addCustomCSS,
  applyDirection,
  attachBoot,
  attachLanguageChange,
  attachThemeLoaded,
  detachLanguageChange,
  detachThemeLoaded,
  getEffectiveScopingSuffixForTag,
  getI18nBundle,
  getRGBColor,
  getRTL,
  getTheme,
  registerI18nLoader,
  setCustomElementsScopingRules,
  setCustomElementsScopingSuffix,
  setFetchDefaultLanguage,
  setLanguage,
  setTheme
};

```

`getRGBColor` is only used for testing purposes on our side, we can for sure omit this.

### Priority

None

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by s-todorova** [comment]
Hello @SAP/ui5-webcomponents-core,

Could you please take a look at this feature request?

Best regards,
Siyana
