### ISSUE TITLE
[build]: `ui5-shared-resources` element leads to invalid markup

### ISSUE THREAD

**Issue by tzimmermann** [SAP/ui5-webcomponents#6748]
### Bug Description

The global `<ui5-shared-resources>` element [created here](https://github.com/SAP/ui5-webcomponents/blob/2830c67034ff0af7bd65e78e4bdd065bb2ca7954/packages/base/src/getSharedResource.ts#L7) is appended dynamically as the first child to the HTML `<head>` element.

However, this produces markup that is invalid. If one saves this markup as raw HTML, and opens it in the browser again, the browser tries to "fix" it but in the process breaks the markup even more, moving `head` children into the `body` instead.

The effect is that we get character encoding errors during percy screenshot tests when using ui5/webcomponents like mentioned here: https://github.com/percy/cli/discussions/721#discussioncomment-1970828

### Expected Behaviour

The library should not create invalid markup.

- If custom elements are at all allowed in the `head` section (I didn't find a definitive answer to that), my assumption is that they somehow need to be defined beforehand.
- If custom elements are **not** allowed at all in the `head` section, then I assume they should be put in the `body` instead (or another way of page-global information sharing should be used).

### Steps to Reproduce

1. Open a page that uses `ui5/webcomponents-base`, for example https://sap.github.io/ui5-webcomponents/playground/components/Bar/ in the Chrome browser.
2. Open the Chrome dev tools switching to the "Elements" tab.
3. Observe that the markup contains `ui5-shared-resources` as the `head`'s first child, followed by all other usual head content like `meta` and `link` elements:
![image](https://user-images.githubusercontent.com/1227637/226556755-88b65594-83fa-4da4-9d90-e6520fcb0d45.png)
4. From the Chrome menu, select File - Save Page As... to store the raw HTML.
6. Open that HTML file in Chrome.
7. Open the Chrome dev tools switching to the "Elements" tab again. One can see that the markup is now mixed up:
![image](https://user-images.githubusercontent.com/1227637/226556515-8e571ab9-9e3f-4c93-a431-1170fe9ede59.png)

My explanation so far: The browser chokes on the `ui5-shared-resources` element, does not recognize it as a valid child of the `head` element. **Thus, the browser prematurely closes the `head` element and moves  `ui5-shared-resources` and all following elements into the `body`**.

### Priority

Medium

### UI5 Web Components Version

1.10.0

### Browser

Chrome

### Operating System

Mac OS 13.2.1

### Additional Context

https://validator.w3.org/nu/#textarea
https://stackoverflow.com/questions/65392061/are-html5-custom-elements-allowed-in-head

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by s-todorova** [comment]
Hello @SAP/ui5-webcomponents-topic-core,

The <ui5-shared-resources> element inside the <head> produces incorrect markup as explained above. When downloading a page that uses ui5, some tags are misplaced, such as <head> children inside the <body>, which leads to breaking the correct markup and causing character encoding errors.
The issue is reproducible via the steps described above both on the [playground](https://sap.github.io/ui5-webcomponents/playground/components/Bar/) and [test](https://sap.github.io/ui5-webcomponents/main/playground/main/pages/Input/) pages that use ui5/webcomponents-base.

Could you please take a look at this issue?

Best regards,
Siyana
