### ISSUE TITLE
[ui5-radio-button]: formControl origami binding does work

### ISSUE THREAD

**Issue by weihaolu** [SAP/ui5-webcomponents#6749]
### Bug Description

when trying to use ui5-radio-button with a form control and origami:
`<ui5-radio-button *ngFor="let opt of field.options; trackBy: trackByFn" [formControl]="control" origami>`
the form control is not updated at all. 

when clicking on a radio button formControl.setValue is not called => no validators executed and no subscriptions to the control are triggered

### Expected Behaviour

when trying to use ui5-radio-button with a form control and origami:
`<ui5-radio-button *ngFor="let opt of field.options; trackBy: trackByFn" [formControl]="control" origami>`
the form control will be updated accordingly

when clicking on a radio button formControl.setValue is called => validators are executed and subscriptions to the control are triggered

### Steps to Reproduce

1. Create a fromControl 
2. add a dummy validator to the formControl
3. Create ui5-radio-buttons
4. Pass the form control to every radio button with origami
5. set a breakpoint in the validator
6. click on a radio button

expected: you should land in the breakpoint
actual: breakpoint is not triggered since the events fired by the radio button do not trigger origami to update the form control
Furthermore basically the behavior should be equal to https://angular.io/api/forms/RadioControlValueAccessor

...

### Priority

Medium

### UI5 Web Components Version

1.10.5

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ilhan007** [comment]
Hello @weihaolu we are processing the issue, we did already one attempt to address it and released an experimental version that you could try out: `0.0.0-760fbb471` and to see if there is any difference (it's based on this PR https://github.com/SAP/ui5-webcomponents/pull/6774). Just change all "@ui5/*" deps version you have with ` 0.0.0-760fbb471` and try it out.

If this does not work, could you try to create the sample you are describing in a platform like this:
https://stackblitz.com/edit/angular-k666q7?file=src%2Fmain.ts (Angular TS template project - perhaps you can change the versions of angular you are using)

**Comment by weihaolu** [comment]
Hey Ilhan, thanks a lot for the fast support!
Unfortunately the fix does not fullly fix the binding problem. We saw that the formControl gets a boolean instead of the option value. as you can see here https://angular.io/api/forms/RadioControlValueAccessor the value of the input e.g.: "beef" "lamp" "fish" is passed to the formControl and then angular uses fireUncheck to uncheck the not selected radio buttons. also with this apporach the intial selected radio button can be set by passing the formControl with an intial value. in the angular example it would be "lamp"

**Comment by ilhan007** [comment]
Small sample, provided by @weihaolu 
https://angular-35au7l.stackblitz.io
https://stackblitz.com/edit/angular-35au7l?file=src/app/radioButtonComponent.ts

Interesting fact is that when there are two or more radio buttons and "origami" is set on all of them, just the first radio is displayed.

**Comment by ilhan007** [comment]
Hello @weihaolu you can now use the ui5-webcomponents-ngx project - an angular wrappers around the UI5 Web Compoenents e.g. UI5 Web Components for Angular https://ui5-webcomponents-ngx.netlify.app/?path=/docs/ui5-web-components-main-radiobutton--docs Version [0.3.0-rc.9](https://www.npmjs.com/package/@ui5/webcomponents-ngx/v/0.3.0-rc.9) is recommended. We start to invest more and more to productise the project which is already in very good shape.

Origami is basically dead util and we gave up on it and just recommend the ngx wrappers for Angular application development.
