### ISSUE TITLE
Avatar interactive property not working as expected

### ISSUE THREAD

**Issue by ooniki** [SAP/ui5-webcomponents#6752]
### Bug Description

Hello,

I am using webcomponents and it seems that  properties like interactive on Avatar doesnt not work as expected.
With false as value (default value) components is still clickable and it still raise an event.

### Affected Component

Avatar

### Expected Behaviour

not clickable and not raising click event

### Isolated Example

https://codesandbox.io/s/ui5-webcomponents-forked-13eml1

### Steps to Reproduce

1. Use avatar component
2. bind event
3. click on it
...

### Priority

None

### UI5 Web Components Version

latest

### Browser

Chrome

### Operating System

windows

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by s-todorova** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

The issue of an avatar being active when an event is bound, despite not having the interactive property set, is reproducible on the given [example](https://codesandbox.io/s/ui5-webcomponents-forked-13eml1?file=/index.html:207-532). However, it does not reproduce on the Avatar's [test page](https://sap.github.io/ui5-webcomponents/main/playground/main/pages/Avatar/).

Could you please take a look at this?

Best regards,
Siyana

**Comment by ooniki** [comment]
> Hello @SAP/ui5-webcomponents-topic-p,
> 
> The issue of an avatar being active when an event is bound, despite not having the interactive property set, is reproducible on the given [example](https://codesandbox.io/s/ui5-webcomponents-forked-13eml1?file=/index.html:207-532). However, it does not reproduce on the Avatar's [test page](https://sap.github.io/ui5-webcomponents/main/playground/main/pages/Avatar/).
> 
> Could you please take a look at this?
> 
> Best regards, Siyana

Hello,

Its because you are using 'ui5-click' event that is not referenced in your documentattion: https://sap.github.io/ui5-webcomponents/playground/components/Avatar/
Moreover, despite the fact that the event section is missing in this page, there is some lines that refer to a 'click' event
![image](https://user-images.githubusercontent.com/6315012/227009499-1748b598-08fb-48bd-a9e3-2d0de9a2516b.png)

Ooniki

**Comment by ash-uncover** [comment]
Hello, I observed the same issue on 'Icon' component

@s-todorova > thanks for the 'test page' links, the Icon test page doesnt expose the non interactive icon (allthough there seem to be an event listener, but again the non interactive one is registered on 'ui5-click', not on 'click' !). May be all this is just a mistake in the documentation ?


https://sap.github.io/ui5-webcomponents/playground/components/Icon/ 
>>
```
nonInteractiveIcon.addEventListener("ui5-click", function() {
  input.value = ++inputValue;
});

myInteractiveIcon.addEventListener("click", function() {
  input2.value = ++inputValue2;
});
```

**Comment by dobrinyonkov** [comment]
Hi @ash-uncover,

please be advised that the click event referred to is the native browser click event. As a matter of policy, we do not intend to intercept this event in any way. Our aim is to avoid any disruption to the default browser events that occur when HTML elements are clicked.

It is important to note that the interactive property of the avatar serves solely to illustrate its clickable nature, through the use of cursor pointers, focus styles, tabindex, and other similar features.

We suggest to not assign a click event when the avatar is meant to be static.

Best Regards,
Dobrin

**Comment by ash-uncover** [comment]
@dobrinyonkov > that make sense :)

Maybe you should still update the documentation with the 'ui5-click' event, the current state is confusing.
