### ISSUE TITLE
Tab Container - Focus Handling for desktop incorrect (ACC)

### ISSUE THREAD

**Issue by blaesius** [SAP/ui5-webcomponents#6762]
### Bug Description

Focus Handling for desktop incorrect (ACC)

### Affected Component

Tab Container

### Expected Behaviour

The Tab Container should have always a focus on desktop (not only after/with keyboard interaction).
Issue can be seen here:
https://sap.github.io/ui5-webcomponents/playground/components/TabContainer/

This is valid for all Web Components and not only the Tab Container. 

### Isolated Example

https://sap.github.io/ui5-webcomponents/playground/components/TabContainer/

### Steps to Reproduce

1. Click on a tab (no focus is applied, but should be)
2. Navigate via Keyboard, Focus is applied
3.
...

### Priority

High

### UI5 Web Components Version

1.11.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by pskelin** [comment]
There are still ongoing discussion about the correct behaviour
