### ISSUE TITLE
Tab Container - Mixed alignment of text

### ISSUE THREAD

**Issue by blaesius** [SAP/ui5-webcomponents#6764]
### Bug Description

Mixed alignment of text

### Expected Behaviour

Combination of tabs with count and without count leads to mixed alignment of text.
Text should always be bottom aligned, regardless if there is a count or not.
Count should always be top aligned (except for inline mode), regardless if there is a text or not.

### Steps to Reproduce

1.
2.
3.
...

### Log Output, Stack Trace or Screenshots

<img width="829" alt="image" src="https://user-images.githubusercontent.com/6813930/226916710-facfb45c-447a-4641-9810-681da284330b.png">

### Priority

Medium

### UI5 Web Components Version

1.11.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by olannyv** [comment]
This is to be fixed with internal BI -2986

**Comment by olannyv** [comment]
This is to be fixed with internal BI -2986

**Comment by LidiyaGeorgieva** [comment]
Internal BLI created for this issue -  BGSOFUIRODOPI-2986
