### ISSUE TITLE
Tab Container - Missing documentation for feature

### ISSUE THREAD

**Issue by blaesius** [SAP/ui5-webcomponents#6765]
### Bug Description

Missing documentation for feature

### Expected Behaviour

If you have the combination of a Tab with only count + text and other tabs including icons, the one with count + text is rendered differently (visually the count is shown bigger). This featuere is not documented at all. There should be either a sample + proper description that this behavior comes automatically or a property to explicetly enable this behavior is needed

### Steps to Reproduce

<ui5-tabcontainer class="full-width" fixed tabs-overflow-mode="StartAndEnd">
			<ui5-tab text="All" additional-text="40"></ui5-tab>
			<ui5-tab-separator></ui5-tab-separator>
			<ui5-tab icon="sales-order-item" text="Ordered" additional-text="3" selected></ui5-tab>
			<ui5-tab icon="shipping-status" text="Shipped" additional-text="16"></ui5-tab>
			<ui5-tab icon="supplier" text="Delivered" additional-text="21"></ui5-tab>
			<ui5-tab-separator></ui5-tab-separator>
			<ui5-tab icon="paid-leave" text="Paid" additional-text="34" design="Positive"></ui5-tab>
			<ui5-tab icon="unpaid-leave" text="Unpaid" additional-text="6" design="Negative"></ui5-tab>
		</ui5-tabcontainer>

### Log Output, Stack Trace or Screenshots

<img width="249" alt="image" src="https://user-images.githubusercontent.com/6813930/226917350-049a4493-169b-4c72-871b-44fa7062d55a.png">

### Priority

Medium

### UI5 Web Components Version

1.11.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by LidiyaGeorgieva** [comment]
Internal BLI created for this issue -  BGSOFUIRODOPI-2986
