### ISSUE TITLE
[SF][ui5-dialog/ui5-input]: Safari can not focus Input in Dialog

### ISSUE THREAD

**Issue by JarrettChan** [SAP/ui5-webcomponents#6768]
### Bug Description

Given: 
- Safari browser
- Input in Dialog

Observed:
- Clicking to focus Input will trigger Popup.forwardToLast()
- Tabbing can focus Input, but if Input renders something, will focus focustrap 
(or in our impl, focuses the last element)
- Initial focus can be lost to last focusable element (when using Dialog initial-focus)

It seems that the `<input>` is focusable, but the popup does not think it is focusable.

Reported in SF prod: 
ui5-webcomponents 1.7.1
Safari 15.5

Reproduced in SF QA: 
ui5-webcomponents 1.10.3
Safari Version 16.3 (18614.4.6.1.6)

Reproduced in playground
Safari Version 16.3 (18614.4.6.1.6)
(Not sure if related to having more focusable items, but the forwardToLast seems to be slow in the Basic Dialog example; clicking multiple times on an input freezes hover styling for some time)

### Affected Component

ui5-input

### Expected Behaviour

Initial focus should not go to last focusable element.
Able to focus Input in Dialog by click.
Re-render of Input should not cause Popup to focus last element. 

### Steps to Reproduce

1. https://sap.github.io/ui5-webcomponents/playground/components/Dialog/
2. `Basic Dialog` -> `Show Dialog`
Observe: initial focus shifted to "Register" button
3. click input
Observe: focused "Register" button
4. tab to "password" input (and type something)
Observe: showing "Invalid Entry" caused focus to be lost to `span.first-fe`

### Priority

High

### UI5 Web Components Version

1.7.1

### Browser

Safari

### Operating System

macOS 13.2.1 (22D68) - Safari Version 16.3 (18614.4.6.1.6) - 2/3 reproduced in playground

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by s-todorova** [comment]
Hello @JarrettChan,

I could not reproduce the issue you're describing on SauceLabs with Safari 16 and MacOS 13, and a colleague of mine could not reproduce it either on his MacOS machine with the same Safari version as you.

Could you please provide an isolated example of the issue? You can use [CodeSandbox](https://codesandbox.io/).

Best regards,
Siyana

**Comment by JarrettChan** [comment]
@s-todorova 
https://codesandbox.io/s/ui5-webcomponents-forked-kojrpc
This is similar to our implemented dialog. 
When I open the dialog in Safari, the focus is set to the last focusable element.
On mousedown, focus is set to the last focusable element.
Typing into the input triggers the suggestions and focus is set to the last focusable element.

**Comment by gmkv** [comment]
Hi @JarrettChan 
I couldn't reproduce this very easily.
On top of that, my Safari was recently updated to 16.4 (or Safari Technology Preview Release 167) and I haven't been able to reproduce the bug since.
Can you please check if you can still reproduce this?

**Comment by JarrettChan** [comment]
@gmkv 
I was able to reproduce in macOS 13.3.1 Safari Version 16.4 (18615.1.26.11.23)
ui5 webcomponents 1.11.0

https://user-images.githubusercontent.com/4755512/231264197-aff79ff4-5d14-4976-b481-8310ed2dcc20.mp4
