### ISSUE TITLE
Checkbox - “Hover” and “Down” state only on half of checkbox

### ISSUE THREAD

**Issue by blaesius** [SAP/ui5-webcomponents#6771]
### Bug Description

“Hover” and “Down” state only on half of checkbox

### Expected Behaviour

While interacting with checkbox, the “hover” and “down” state only appears when cursor is on box, not on text. If user can click on text to select and unselect the checkbox, the “hover” and “down” state should be shown as well (box + text should act as one control). 

### Isolated Example

https://sap.github.io/ui5-webcomponents/playground/components/CheckBox/

### Steps to Reproduce

1.
2.
3.
...

### Log Output, Stack Trace or Screenshots

<img width="750" alt="image" src="https://user-images.githubusercontent.com/6813930/227139005-83648ec4-d6fe-4d1d-a4d6-3d9be5fa08a2.png">

### Priority

Medium

### UI5 Web Components Version

1.11.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by s-todorova** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

The correct styles for hover and down state on the Checkbox do not get applied if the user clicks on the text, only if the box is being clicked. You can reproduce the issue on the Checkbox's [playground page](https://sap.github.io/ui5-webcomponents/playground/components/CheckBox/) - observe that if you hover/hold down the mouse on the box, the correct styles are applied (for example the white background of the box on hover), but if you try to do the same when clicking/hovering over the text, the styles remain unchanged.

Could you please take a look at this issue?

Best regards,
Siyana

**Comment by yanaminkova** [comment]
Hello @blaesius,

Thanks you for reporting!

We already have a backlog item and we are working on this issue.

Kind regards,
Yana
