### ISSUE TITLE
Switch - Hover State Shadow wrong aligned

### ISSUE THREAD

**Issue by blaesius** [SAP/ui5-webcomponents#6777]
### Bug Description

When in Hover State, the displayed Shadow/ Border is not aligned with the background.

### Expected Behaviour

See VD wiki for details

### Steps to Reproduce

1.
2.
3.
...

### Log Output, Stack Trace or Screenshots

![image](https://user-images.githubusercontent.com/6813930/227203857-310e734d-108f-46eb-b73b-c033383d068e.png)

### Priority

Medium

### UI5 Web Components Version

1.11.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by s-todorova** [comment]
Hello @SAP/ui5-webcomponents-topic-b,

There is a slight misalignment of the border of the Switch in Horizon theme. You can see it when you hover over a Switch in the first example on the [playground page](https://sap.github.io/ui5-webcomponents/main/playground/components/Switch/), as shown in the screenshot (you may need to zoom in to be able to see it).

Could you please take a look at this?

Best regards,
Siyana
