### ISSUE TITLE
Switch - Keyboard Interaction: “ESC” Key doesn’t work as expected (ACC)

### ISSUE THREAD

**Issue by blaesius** [SAP/ui5-webcomponents#6779]
### Bug Description

From ACC side it is described that the “ESC”-Key can be used to cancel triggering the action (in this case toggling the switch) when using “ESC” while “SPACE” is pressed. This doesn’t work for the web component.

### Isolated Example

https://sap.github.io/ui5-webcomponents/playground/components/Switch/

### Steps to Reproduce

1.
2.
3.
...

### Priority

Medium

### UI5 Web Components Version

1.11.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by nnaydenow** [comment]
Hi https://github.com/orgs/SAP/teams/ui5-webcomponents-topic-b,

Could you please check this? If click action is triggered by SPACE key user is not able to discard it by pressing SHIFT / ESCAPE key.

**Comment by unazko** [comment]
Hello @blaesius,

There was a discussion with the ACC experts if the ui5-switch click event should be cancelable.
It was decided that it is redundant for the click event to be cancable with ui5-switch and ui5-checkbox components
as it is easier to revert the action the follow up click.
That is not the case for the ui5-button as an action triggered for a button could not be reverted the same way.

Best regards,
Boyan
