### ISSUE TITLE
Button - Keyboard Interaction: “ESC” Key doesn’t work as expected (ACC)

### ISSUE THREAD

**Issue by blaesius** [SAP/ui5-webcomponents#6782]
### Bug Description

From ACC side it is described that the “ESC”-Key can be used to cancel triggering the action (in this case triggering the action) when using “ESC” while “SPACE” is pressed. This doesn’t work for the web component.

### Isolated Example

https://sap.github.io/ui5-webcomponents/playground/components/Button/

### Steps to Reproduce

1.
2.
3.
...

### Priority

Medium

### UI5 Web Components Version

1.11.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by s-todorova** [comment]
Hello @blaesius,

Could you please provide a recording of how exactly you encouter this problem? I am unable to reproduce this issue on the playground page, which you've linked as an example.

Thank you in advance!

Best regards,
Siyana

**Comment by blaesius** [comment]
Hi Siyana,

yes, no problem.

Just navigate via keyboard using the tab until you reach a button. Press 'space' and hold it (to execute the button action via keyboard). If you now press ESC (while holding space), the action should be cancelled. We have this behavior already in UI5, you can check it there as well.

Kind regards,
Janina

**Comment by nnaydenow** [comment]
Hi @SAP/ui5-webcomponents-topic-b,

Could you please check this? If click action is triggered by SPACE key user is not able to discard it by pressing SHIFT / ESCAPE key.
