### ISSUE TITLE
Multi Combo Box - Arrow button is not working on mobile.

### ISSUE THREAD

**Issue by blaesius** [SAP/ui5-webcomponents#6783]
### Bug Description

Touching on the arrow button on mobile does not work. Only hover effect is applicable.

### Isolated Example

https://sap.github.io/ui5-webcomponents/playground/components/MultiComboBox/

### Steps to Reproduce

1.
2.
3.
...

### Log Output, Stack Trace or Screenshots

<img width="255" alt="image" src="https://user-images.githubusercontent.com/6813930/227207996-4ca36c57-77dc-4139-9725-f3ecea8fe9e1.png">

### Priority

Medium

### UI5 Web Components Version

1.11.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ilhan007** [comment]
Hello @blaesius perhaps recording a video in our Playground how you perform the steps and reproduce the issue would be also good enough.

**Comment by hristop** [comment]
@ilhan007 , @s-todorova I was able to reproduce the issue on real device - iPhone 13 Pro Max. 

It is easily reproducible in the playground.

Best Regards,
Hristo

**Comment by niyap** [comment]
Hello @blaesius,

As I am not able to reproduce the issue, could you please check whether it is still reproducible with the latest version of the UI5 Web Components: https://sap.github.io/ui5-webcomponents/main/playground/components/MultiComboBox/
If it is still reproducible from your side, please provide a video or step by step description, how to reproduce it.

Thank you in advance!

Kind Regards,
Niya
