### ISSUE TITLE
Input - Focus on Read-Only Input needs an improvement

### ISSUE THREAD

**Issue by blaesius** [SAP/ui5-webcomponents#6784]
### Bug Description

The Focus on the Read-Only Input is not implemented correctly. It should be implemented inside the Input.

### Expected Behaviour

See VD wiki for details

### Isolated Example

https://sap.github.io/ui5-webcomponents/playground/components/Input/

### Steps to Reproduce

1.
2.
3.
...

### Log Output, Stack Trace or Screenshots

<img width="195" alt="image" src="https://user-images.githubusercontent.com/6813930/227209066-c6946e25-47eb-4e96-8c37-3f6bb1b8c3b3.png">

### Priority

Medium

### UI5 Web Components Version

1.11.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by niyap** [comment]
Hello @blaesius,

As that requirement has never been implemented, we will handle it as a feature request via BLI.

Kind Regards,
Niya

**Comment by hristop** [comment]
Hi @blaesius ,

I had talk with Dev and VD regarding this and it seems that currently the current implementation is the desired one and synced/approved by the VD. 

Can you please check again or clarify what exactly needs fixing?

Best Regards,
Hristo
