### ISSUE TITLE
Title - Title as a Link

### ISSUE THREAD

**Issue by blaesius** [SAP/ui5-webcomponents#6785]
### Bug Description

The title should be able to be set as a link while retaining most of the header style

### Expected Behaviour

<img width="370" alt="image" src="https://user-images.githubusercontent.com/6813930/227210254-df126a02-2c1b-4750-b237-e74a13636db0.png">

### Isolated Example

https://sap.github.io/ui5-webcomponents/playground/components/Title/

### Steps to Reproduce

1.
2.
3.
...

### Priority

Medium

### UI5 Web Components Version

1.11.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by LidiyaGeorgieva** [comment]
Internal BLI created for this issue -  2986

**Comment by LidiyaGeorgieva** [comment]
BLI 2989 is created
