### ISSUE TITLE
[Feature Request]: text component

### ISSUE THREAD

**Issue by weihaolu** [SAP/ui5-webcomponents#6788]
### Feature Request Description

currently there is no text component so that we have to use divs or p tags and custom css to ensure firoi themeing

### Proposed Solution

it would be great to have text component, so that we do not have to use custom css in order to ensure correct fiori themeing.

### Priority

None

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by s-todorova** [comment]
Hello @SAP/ui5-webcomponents-topic-core,

Could you please take a look at this feature request?

Best regards,
Siyana

**Comment by ilhan007** [comment]
In addition to the pure styling,  after digging into other text UI components, possible features to add and make the Text web component more useful would be:
- max lines (e.g wrapping to number of lines and truncating  from there)
- expandable text (e.g showing "Show more/less" link to show/hide the truncated part)
