### ISSUE TITLE
Avatar icon property default value is wrong

### ISSUE THREAD

**Issue by ooniki** [SAP/ui5-webcomponents#6789]
### Bug Description

Hello,

On the avatar component the default value of the property icon must be "" but its "employee"

Ooniki

### Affected Component

Avatar

### Expected Behaviour

no icon attribut or "" as default value

### Isolated Example

https://codesandbox.io/s/ui5-webcomponents-forked-tjw9t2?file=/index.html

### Steps to Reproduce

1. Use avatar
2. dont put icon property
3.
...

### Priority

None

### UI5 Web Components Version

1.11

### Browser

Chrome

### Operating System

Windows

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by nnaydenow** [comment]
Hello colleagues,

Even if empty string is set to icon attribute an icon will appear. Could you please check if this one is a bug or unclear documentation?

**Comment by yanaminkova** [comment]
Hello @ooniki,

If no icon, or an empty one is provided, there should be displayed default fallback icon and not an empty avatar.
For the moment, the default fallback icon is "employee", but we will implement functionality, which will allow it to be changed.

Internal Reference: BGSOFUIPIRIN-6092

Thanks and Best Regards,
Yana
