### ISSUE TITLE
Insert ui componente un ui-table

### ISSUE THREAD

**Issue by andresfelipe66** [SAP/ui5-webcomponents#679]
**Describe the documentation issue**

- [ ] Documentation is missing

**Description of the issue**
 I'm trying to find out how insert ui-input or ui-datepicker in a ui-table

![image](https://user-images.githubusercontent.com/20842185/61823347-47025600-ae21-11e9-9a5f-26b9b1273d36.png)

but the controls dont show in the table... ¿How is the correct way to use this kind of controls in ui-table?

![image](https://user-images.githubusercontent.com/20842185/61823330-3baf2a80-ae21-11e9-8bf5-4ef24d9172cc.png)

Thank you

**Comment by fifoosid** [comment]
Hi @andresfelipe66 

As I don't see your code I can't tell why it isn't working on your side, but here is a working example with input, datepicker and select in the table: https://codesandbox.io/s/ui5-webcomponents-y3oud
(As I can see codesandbox is currently down btw)

In my opinion you might have forgotten to import the input and the datepicker.

Best Regards,
Filip

**Comment by andresfelipe66** [comment]
Yes, I forgot to include the references in  app.module.ts in the angular project

Thanks you!!
