### ISSUE TITLE
[ui5-menu]: Title overlaps with submenu arrow

### ISSUE THREAD

**Issue by subint1994** [SAP/ui5-webcomponents#6795]
### Bug Description

Im using ui5-webcomponents-react Menu and MenuItem for a use case.
When the text in the Menu is longer, it gets overlapped with the arrow icon at the end when it has a sub menu.
<img width="241" alt="Screenshot 2023-03-22 at 2 14 05 PM" src="https://user-images.githubusercontent.com/34679598/227471370-030603ea-3406-49e7-ac42-a522c69475b2.png">

### Affected Component

UI5 Menu

### Expected Behaviour

There should be clear gap between the end of the menu title and submenu arrow on the right.

### Isolated Example

https://codesandbox.io/s/charming-river-vrz70g?file=/src/App.js

### Steps to Reproduce

1. Have some long text as a menu title 
2. Add submenus to this menu.
<img width="241" alt="Screenshot 2023-03-22 at 2 14 05 PM" src="https://user-images.githubusercontent.com/34679598/227472198-dd0da97b-b2a3-4d9f-a977-6d96eef2c65e.png">

### Priority

Medium

### UI5 Web Components Version

1.10.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by subint1994** [comment]
Hi @petyabegovska, 

In my use case, I need to show the entire text as in OpenUI5 for the Menu title with submenu items.

Also is it possible to show the entire text without truncation when there is additional text also?

Regards,
Subin

**Comment by petyabegovska** [comment]
Hi @subint1994,

Most probably we will need to refactor the control which will take time.
We will research the options and may fix first the overlapping.

Best regards,
Petya

**Comment by sneha-ajit** [comment]
@petyabegovska  We are also facing the same issue. Waiting for a fix.

**Comment by petyabegovska** [comment]
Hi @DMihaylova and @ui5-webcomponents-topic-b,

Can you fix the overlapping?
