### ISSUE TITLE
Tab: `stable-dom-ref` points to different element than `getDomRef()`

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#6796]
### Bug Description

When `getDomRef` is executed on a `ui5-tab` it points to the most outer element of the shadow-root of the `ui5-tab`, but when setting the `stable-dom-ref` attribute, the corresponding data-attribute (`data-ui5-stable`) is set on the element representing the tab inside the header of the shadow-root of the `TabContainer`. I'd guess that the `Tab` is missing the [`_getRealDomRef` function](https://github.com/SAP/ui5-webcomponents/blob/7fe6395d572f28c1ffacff1427fde48dc00f1e97/packages/base/src/UI5Element.ts#L738-L741) somewhere.

Additionally, I have a question about what is recommended to use. My understanding is that developers should use the `getDomRef` method instead of setting the `stable-dom-ref` attribute. Am I correct in this assumption?

### Expected Behaviour

The data-attribute and the `getDomRef` method should both be applied / point to the same element.

### Isolated Example

https://codesandbox.io/s/ui5-webcomponents-forked-phn6ir?file=/src/index.js

### Steps to Reproduce

1. Go to [codeSandbox](https://codesandbox.io/s/ui5-webcomponents-forked-phn6ir?file=/src/index.js)
2. Click on the first button that logs the output of the `getDomRef` method of a Tab.
3. See that the most outer element inside the shadow-root of the `ui5-tab` is logged.
4. Click on the second button that logs the element which has the `data-ui5-stable="tab1"` attribute
5. See that the element is inside the shadow-root of the `ui5-tabcontainer`

### Priority

None

### UI5 Web Components Version

1.11.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by nnaydenow** [comment]
Hi @Lukas742,

If I understand correctly what is the feature description you're right that people should use `getDomRef` instead of `stable-dom-ref` because it's unnecessary to be aware of how the element is selected. #4604.

Hello @SAP/ui5-webcomponents-topic-rd,

Could you please take process the issue?

**Comment by gmkv** [comment]
Hi @Lukas742 

There is a slight difference between what we call an abstract component and what the Tab is. An abstract component has a 
The Tab, as defined in the HTML, represents the content that will be shown inside the TabContainer.
Another representation of a Tab, is what gets drawn on the "tab strip" of the TabContainer. Those two items are shown in your example code.

Which element would you expect to receive when you call `getDomRef()`? 

It would remain more consistent by returning the content that is wrapped in a `<ui5-tab>`, which is the case now, or we could always return the tab element from the tab strip.
If we assume the latter, always returning the element from the tab strip, we would count on the app developer to still have access to their content from their own markup. Alternatively, we could add a second getter for the item in the tab strip. Something like `getDomRef` and a new `getTabInStripDomRef`. Let me know what you think.

**Comment by Lukas742** [comment]
Hi @gmkv 

thanks for the reply. 

If the `stable-dom-ref` API is still to be used, then in my opinion the `getDomRef` method should return the same item that the `data-ui5-stable` is applied to. If the `stable-dom-ref` id is no longer to be set manually, I would prefer option three (`getTabInStripDomRef`), since then it's the intended behavior of the `getDomRef` method, and changing it could be considered breaking.

I will also ask the colleagues who originally raised this question if they have any additional input, as they will most likely be able to describe their use case better.

**Comment by dimovpetar** [comment]
Hello @xqtion and @Lukas742 ,

At the moment we are preparing change to make the `getDomRef()` and the element with `stable-dom-ref` of the tab to be the same thing. Therefore, if you need the get the representation of the tab in the tab strip (tab container header), you should use the `getTabInStripDomRef` method. It is already public. Read the docs at https://sap.github.io/ui5-webcomponents/playground/components/TabContainer/

Best regards,
Petar
