### ISSUE TITLE
ui5-textarea - css style not defined

### ISSUE THREAD

**Issue by bonnieso** [SAP/ui5-webcomponents#6797]
### Bug Description

It appears this style `--_ui5_textarea_padding: .1875rem .5rem;` was removed via https://github.com/SAP/ui5-webcomponents/commit/d8137b7b6239e0695e34d62e7b0179babf7a747b#diff-804144e6978846de00695340bf85e6f8d23bdd59ffefd7a66e303c7b62039748L259 which causes issues on pages that load an older version of ui5 webcomponents along with a newer version that includes this change since the css variables defined in the older versions are overridden by values from the newer version. We are requesting to add this variable back in a newer version as well as maintain a standard for ensuring backend compatibility since it is common for multiple versions of ui5 webcomponents to be included on a given page.

### Affected Component

ui5-textarea

### Expected Behaviour

The css variable, --_ui5_textarea_padding, should not be undefined for pages using older versions of ui5-webcomponents alongside a newer version.

### Steps to Reproduce

1. Load a page with UI5 web components version 1.9.0 with UI5 web components version 1.10.3.
2. Include a ui5-textarea component.
3. Observe that text in the ui5-textarea component does not receive proper padding.

### Priority

None

### UI5 Web Components Version

1.9.0

### Browser

Chrome, Edge, Firefox, Safari

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ilhan007** [comment]
Hello @bonnieso the missing CSS var ` --_ui5_textarea_padding` has been added as patch in 1.10.7. So you can upgrade from 1.9 to 1.10.7 and the `--_ui5_textarea_padding` should not be missing any more.
