### ISSUE TITLE
[Feature Request]: CSS variables should support scoping similar to tag scoping

### ISSUE THREAD

**Issue by codefactor** [SAP/ui5-webcomponents#6806]
### Feature Request Description

The CSS Variables output by a UI5 core should support scoping, rather than always overriding the CSS variables from older UI5 cores that have previously written variables to the page. As UI5 is getting new versions, we see backwards incompatibilities introduced often enough to warrant concern.

### Proposed Solution

Suppose we have a widget that has a scope for all Web Components like "-widget" - so now the web components will output like this:
```html
<ui5-text-widget ui5-text>text</ui5-text-widget>
```
The `ui5-text` is an extra attribute on the web component so that CSS rules can be written to select the webcomponent without dynamically generating the CSS selectors to also include the namespace suffix.

What if we also added the namespace too, like this?
```html
<ui5-text-widget ui5-text widget>text</ui5-text-widget>
```
Then when it comes time to write the CSS variables, the CSS variables would be written such that they select only web components that have this namespace.
```css
[widget] {
	--_ui5_textarea_padding_top: 0.125rem;
	--_ui5_textarea_padding_bottom: 0.125rem;
	--_ui5_textarea_padding_left: 0.5rem;
	--_ui5_textarea_padding_right: 0.5rem;
}
```
Additional thoughts:
1. The namespace attribute might need a prefix like `ui5_ns_widget` or something like that to avoid issues if the namespace was `"ui5-text"` or something like that.
2. Perhaps the namespacing of CSS variables would be specified independently of the web component tag suffix - so that if a widget which does namespace the web component tags wanted to avoid namespacing the CSS variables, they could do that.

### Proposed Alternatives

Attempt to keep backwards compatibility for CSS variables, at least within the major version (1.X) and not breaking compatibility without upgrading the major version (e.g. upgrade to 2.X when breaking compatibility). Possibly the minor version (e.g. 1.10.x) but the meaning of a minor version increase has not been so well-defined and so we have many cases where some apps will upgrade to a higher minor version while other apps/widgets do not need to upgrade. Examples of a backwards incompatible change are: 1) delete any CSS variable, even if current version no longer uses it, 2) change the value of any existing CSS variable.

### Additional Context

CSS Variables output by a UI5 web component core are not scoped, and the are shared across all running versions of web component core. Recently there was an enhancement that would allow a core to only override the current CSS variables when the current core detects that it's version is higher than the previous one that originally wrote the CSS variables on the page. This works well when the UI5 web components don't introduce backwards incompatibility; however, backwards incompatibilities are unavoidable.

Here is one recent example:
Version 1.9 has `_ui5_textarea_padding` but version 1.10 has `_ui5_textarea_padding_top` and 3 others for right/bottom/left - in other words a UI5 variable was REMOVED - which is not a backwards compatible change.

There might be other cases - such as a private CSS variable might change the value from 0 to 1rem. Right now we're trying to investigate another CSS variable `_ui5_step_input_padding` which might have changed in 1.11 but we're not sure yet about it and will comment more on it later.

For background - In SuccessFactors, we have something called a "Widget Framework" - which can load "self-contained" experiences on any page. These widgets are built to include their own copies of Web Components that have a scope limited to this widget. This is done in an effort to avoid one huge mono-repository where every application/widget is built with one central package.json defining the ui5-webcomponent version. This gives us a much better "horizontal scaling" that allows us to have small single purpose repositories to deliver new functionality.

We would like our widget framework to be able to load the UI5 web components with their own copy of CSS variables that do not conflict with other UI5 frameworks being loaded in parallel.

### Priority

Medium

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ilhan007** [comment]
Hello @codefactor thank you for your Feature request, we discussed once again the topic and came up with the following proposal: https://github.com/SAP/ui5-webcomponents/issues/6876 that we believe will resolve your issues regarding the CSS Vars

Closing this issue, as the other one will be used for processing/tracking.
