### ISSUE TITLE
[SF_ACC][Feature Request]: Enable changing the role of Popover to "menu"

### ISSUE THREAD

**Issue by ksblklu** [SAP/ui5-webcomponents#6810]
### Feature Request Description

Hi team
In https://github.com/SAP/ui5-webcomponents/issues/6090, we discussed about enable changing the role of the `Popover` component from "dialog" to "menu". 
Our accessibility team recently conducted usability tests with real blind users, as soon as they heard the role "dialog", they expected an actual dialog with a title and a close button to close it. But visually we were able to see the overflow popover of `Toolbar` was actually an action sheet menu that opened from the ellipsis button. Hence we wanted the role be changed to menu. Currently the `accessibleRole` of `Popover` can only be "dialog" or "alertdialog", "menu" role is not working.

### Proposed Solution

Enable changing the accessibleRole of "Popover" to "menu".

### Priority

Medium

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by TeodorTaushanov** [comment]
Hi @ksblklu,

You can set the ui5 popover accessible-role to "None" and put your menu as a content of the popover.

```
  <ui5-popover accessible-role="None">
      <div role="menu">
        <div role="menuitem">item 1</div>
        <div role="menuitem">item 2</div>
      </div>
    </ui5-popover>
```

Please note that in the "menu pattern":
https://www.w3.org/WAI/ARIA/apg/patterns/menubar/

You can put inside the "menu" div only element with role:
- menuitem
- menuitemcheckbox
- menuitemradio

Best,
Teo
