### ISSUE TITLE
[SF_ACC][ui5-select][v0.8.0] Upon expanding the list box, focus is on the first list item, but the name of the first list item  not read

### ISSUE THREAD

**Issue by devduttpradhan** [SAP/ui5-webcomponents#6816]
### Bug Description

Upon expanding the list box, focus is on the first list item. But the name of the first list item not read. Only announcing expanded without focused list item name.
Upon further accessing with arrow keys, the focused list items are read.

### Affected Component

ui5-select

### Expected Behaviour

Upon expanding the list box, first focused list item  should be read.

### Isolated Example

https://sap.github.io/ui5-webcomponents/playground/components/Select/

### Steps to Reproduce

1. Go to https://sap.github.io/ui5-webcomponents/playground/components/Select/
2. Expand the list item from select box
3. Observe the announcement using jaws
...

### Log Output, Stack Trace or Screenshots

![image](https://user-images.githubusercontent.com/129252644/228433478-8eb146a8-85a7-4efb-b92a-e9782e8f251a.png)

### Priority

Medium

### UI5 Web Components Version

0.8.0

### Browser

Chrome

### Operating System

Widows

### Additional Context

Organization: {...}
Business impact: {...}

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by unazko** [comment]
Hello ,

The described behavior is reproducible in the playground sample.

_Analysis:_
The <code>ui5-select</code> component has an <code><div role="combobox"></div></code> element and a when the popover is open we do have a list with <code><li role="listitem"></li></code> elements, which bear the screen reader references.
When the popover is opened the actual focus remains over the <code><ui5-select></ui5-select></code> element,
but a style based focus imitation gets drawn on the first <code><li role="listitem"></li></code> element.
As a result the screen reader doesn't reach the list items even though the component is drawn properly.

The difference between the <code>sap.m.Select</code> control and <code>ui5-select</code> component in this regard is only that the <code>sap.m.Select</code>'s element with role <code/>combobox</code> does have an <code>aria-activedescendant</code> attribute guiding the screen reader to the corresponding <code><li role="listitem"></li></code> in the popover.

Best regards,
Boyan
