### ISSUE TITLE
[SAP][Switch]: When text spacing setting is applied, toggle switch text 'Off' is not visible

### ISSUE THREAD

**Issue by rama1990br** [SAP/ui5-webcomponents#6817]
### Describe the bug

When text spacing settings are applied, the `textOff` text which is set to 'Off' is not fully visible and changes to an ellipsis.

Please follow the instructions in https://wiki.one.int.sap/wiki/display/Acc/ACC-283+Details#ACC283Details-TestMethods to add the test text spacing style sheet.

### Reproduction steps

This can be reproduced in the ui5-webcomponents-react storybook for `Switch` and ui5-webcomponents playground as seen in the screenshots given below

### Expected Behaviour

Text 'Off' and 'Yes' on toggle switch must be displayed when the text spacing settings are applied.

### Screenshots or Videos

<img width="1680" alt="text spacing for switch UI5 WC React" src="https://user-images.githubusercontent.com/32254036/228371128-91c67035-098e-4850-81cd-84bbe5ec68cc.png">

<img width="1680" alt="text spacing for Switch UI5 WC" src="https://user-images.githubusercontent.com/32254036/228370386-d9f4302e-73b2-4c17-9cd8-3c13cd5be01c.png">

### UI5 Web Components for React Version

Not sure

### UI5 Web Components Version

v0.8.0

### Browser

Chrome, Edge, Firefox, Safari

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by nnaydenow** [comment]
Hello,

Also changing the width of the component as mentioned to the documentation doesn't work.

**Comment by stoehr** [comment]
Please add the "SF" label to this issue.

**Comment by rama1990br** [comment]
Hi Team,
Can we please have an update on this ticket?

**Comment by rama1990br** [comment]
@NHristov-sap ,
Please confirm which version of ui5-webcomponents we need to update to in order to get these changes.

**Comment by petyabegovska** [comment]
Hi @rama1990br,

The fix will be part of the next stable release 1.14.0 and it's already part of the prerelease version [v1.14.0-rc.1](https://github.com/SAP/ui5-webcomponents/releases/tag/v1.14.0-rc.1).
 
Best regards,
Petya
