### ISSUE TITLE
[SAP][ViewSettingsDialog] : "Sort Order", "Sort By", "Filter By"labels are included in tab chain

### ISSUE THREAD

**Issue by vidyakore** [SAP/ui5-webcomponents#6830]
### Bug Description

In Component, ViewSettingsDialog labels "Sort Order", "Sort By", "Filter By" are included in tab chain,
as these are non actionable items on pressing tab focus should not go on label. 
And we are not able to control it as it is defined in ViewSettingsDialog component only.

### Expected Behaviour

focus should not go to labels on clicking of tab key.

Note:- This issue is raised by SAP internal Accessbility testing team BCP ticket No:- 2370008336

### Isolated Example

can be reproduced in -  https://sap.github.io/ui5-webcomponents/playground/components/ViewSettingsDialog/

### Steps to Reproduce

1. go to https://sap.github.io/ui5-webcomponents/playground/components/ViewSettingsDialog/
2. click on Open ViewSettingsDialog
3. dialog will be open up
4. Click on tab button
5. focus will go to label "Sort Order"
6. if we keep on clicking tab, it will go to other labels as well like "Sort By", "Filter By"

### Log Output, Stack Trace or Screenshots

<img width="936" alt="image" src="https://user-images.githubusercontent.com/56337652/228746056-0d679340-e6ec-499d-9a0a-11c646cd1b08.png">

### Priority

None

### UI5 Web Components Version

1.10.3

### Browser

Chrome

### Operating System

Windows

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by unazko** [comment]
Hello @vidyakore,

The ACC 272.1 standard implies that all interactive elements should maintain proper order according to their mental model in the application.
The "Sort Order",  "Sort By" and "Filter By" are not labels, but rather group header list items
and therefore they are reachable via keyboard. They are interactive elements as part of the navigation group.

As a conclusion the component behaves as designed and ACC standard 272.1 is not violated.
Therefore I'm closing the incident.

Best regards,
Boyan
