### ISSUE TITLE
[ui5-table]: Wrong row height in Safari browser

### ISSUE THREAD

**Issue by tonyhsap** [SAP/ui5-webcomponents#6843]
### Bug Description

The height of the ui5-table row is rendered too narrow in latest Safari browser.

Chrome:
![image](https://user-images.githubusercontent.com/95026863/229227912-34bbc1a1-4e14-4fba-bf9c-91d085bf101a.png)

Safari:
![image](https://user-images.githubusercontent.com/95026863/229227983-e2c9c963-b82e-44fd-bda6-5fd3e3d79af1.png)

You can clearly see the difference.

### Expected Behaviour

Rows should be rendered with same height in all browsers.

### Isolated Example

https://sap.github.io/ui5-webcomponents/playground/components/Table/

### Steps to Reproduce

1. Visit https://sap.github.io/ui5-webcomponents/playground/components/Table/ with Chrome and Safari
2. Compare row height in both browsers

### Priority

Medium

### UI5 Web Components Version

1.11.0

### Browser

Safari

### Operating System

MacOS 13.2

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by unazko** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

I do not have a Safari browser at hand, but the issue is well described.
Could you please check it out.

Best regards,
Boyan
