### ISSUE TITLE
[Input]: Input with type number does not handle Euler's number 'e' correctly.

### ISSUE THREAD

**Issue by BennyHuang** [SAP/ui5-webcomponents#6844]
### Bug Description

Input with type number does not handle Euler's number 'e' correctly. The number e, also known as Euler's number, is a mathematical constant approximately equal to 2.71828.  We can type 'e', but the input box does not return the correct numeric value in the events.

### Isolated Example

https://codesandbox.io/s/cool-meadow-8qwn5k?file=/src/App.js

### Steps to Reproduce

It can be reproduced in https://codesandbox.io/s/cool-meadow-8qwn5k?file=/src/App.js

### Priority

None

### UI5 Web Components Version

1.10.6

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by unazko** [comment]
Hello @BennyHuang, @SAP/ui5-webcomponents-topic-rl,

We have the following documentation about the "Number" type:
"A text field for specifying a number. Brings up a number pad keyboard. Specifying an input type of \d* or [0-9]* is equivalent to using this type."
"This parameter is intended to be used with touch devices that use different soft keyboard layouts depending on the given input type."

Judging by this the number type is not meant to understand constants like the Euler's or others. Instead it's rather an improvement for mobile devices and the displayed keyboard there.

Users aren't allowed to type alphabetical input when "number" type is set. The "e" symbol is allowed though, which seems incorrect. The same behavior happens with a sap.m.Input control of the same type.

Best regards,
Boyan

**Comment by ndeshev** [comment]
Hello @BennyHuang,

The `ui5-input` component uses a native Input HTML element with `type="number"` which allows (validates) the "e" character because it represents exponents - he exponent is the number after the "e" - not for the Euler's 'e' constant value.

Kind regards,
Nikolay
