### ISSUE TITLE
[Feature Request]: Shellbar items cannot be given accessible names

### ISSUE THREAD

**Issue by g-cheishvili** [SAP/ui5-webcomponents#6853]
### Feature Request Description

This is a direct copy of a ticket from https://github.com/SAP/ui5-webcomponents-ngx/issues/49

### Proposed Solution

No idea

### Priority

Medium

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by JarrettChan** [comment]
With the current behavior, SuccessFactors uses text and title attributes of ui5-shellbar-item. Text is applied when the shellbar item is moved into the overflow dropdown menu. Title is applied as a title tooltip.
custom shellbar item processed https://github.com/SAP/ui5-webcomponents/blob/27c5304eec6b06919a65ff1f9a02163d9c54ed40/packages/fiori/src/ShellBar.ts#L1012-L1022
custom item title applied: https://github.com/SAP/ui5-webcomponents/blob/main/packages/fiori/src/ShellBar.hbs#L153
custom item text applied: https://github.com/SAP/ui5-webcomponents/blob/3efdc6cf7d14b37e714a3979a16ea4cbe498f85e/packages/fiori/src/ShellBar.hbs#L153
