### ISSUE TITLE
[Feature Request]: Progress indicators cannot be given accessible names

### ISSUE THREAD

**Issue by g-cheishvili** [SAP/ui5-webcomponents#6854]
### Feature Request Description

This is a direct copy of a ticket from https://github.com/SAP/ui5-webcomponents-ngx/issues/50

### Proposed Solution

No idea

### Priority

Medium

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by yanaminkova** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

Could you please have a look at this feature request?

Best regards,
Yana

**Comment by dobrinyonkov** [comment]
Internal Reference: BGSOFUIPIRIN-6147
