### ISSUE TITLE
[Popup]: forwardToLast incorrect element

### ISSUE THREAD

**Issue by JarrettChan** [SAP/ui5-webcomponents#6858]
### Bug Description

Upgrading to 1.11.0 from 1.10.x, shift-tab invoking forwardToLast returned the first element in our usage of an extended Popup class.
There was a change in findFocusableElement.
https://github.com/SAP/ui5-webcomponents/compare/v1.10.0..v1.11.0#diff-531e9c3f6403190ca84ddaa9f621788b409999c0d6d9fedfe8fd47b38ba4fc4f

I'm having trouble debugging the exact issue, but the following code should probably decrement if `forward===false`
https://github.com/SAP/ui5-webcomponents/blob/cf56f1308160b0c10a0f366ef5e4df90036c4161/packages/base/src/util/FocusableElements.ts#L80

### Expected Behaviour

Modifying my local copy of FocusableElements.js
https://github.com/SAP/ui5-webcomponents/blob/cf56f1308160b0c10a0f366ef5e4df90036c4161/packages/base/src/util/FocusableElements.ts#L80
```            child = forward ? assignedElements[++currentIndex] : assignedElements[--currentIndex];```
...fixed the issue in my local dev server

### Priority

None

### UI5 Web Components Version

1.11.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by yanaminkova** [comment]
Hello @JarrettChan,

Thank you for sharing this finding!

Could you please provide an isolated example where the issue is reproducible?

Kind Regards,
Yana
