### ISSUE TITLE
[SF][ui5-avatar-group]In RTL, AvatarGroup is shrunk even though there is enough space left

### ISSUE THREAD

**Issue by BennyHuang** [SAP/ui5-webcomponents#6859]
### Bug Description

It is followup to https://github.com/SAP/ui5-webcomponents/issues/6355. The issue is fixed in LTR, but we found it is not fixed in RLT language. 

It is working correct in LTR
<img width="340" alt="image" src="https://user-images.githubusercontent.com/1995447/229629645-5d4246ab-73f7-42ef-9cb4-95b34ae6832e.png">
There is still some problem in RTL
<img width="352" alt="image" src="https://user-images.githubusercontent.com/1995447/229629899-65cc5c09-5d14-48c6-a10a-80d07e1c98f0.png">

### Affected Component

ui5-avatar-group

### Priority

None

### UI5 Web Components Version

1.10.6

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by yanaminkova** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

This is follow up to https://github.com/SAP/ui5-webcomponents/issues/6355.
The issue is fixed in LTR, but is still reproducible in RTL.
Could you please have a look?

Best regards,
Yana

**Comment by PetyaMarkovaBogdanova** [comment]
Hi @BennyHuang ,
I couldn't reproduce the issue, using our samples: https://sap.github.io/ui5-webcomponents/playground/components/AvatarGroup/?sap-ui-theme=sap_horizon&isrtl=true
Can you, please, attach a code example, as the one you provided for the previous issue is no longer available?
Thank you!
Regards,
Petya Markova.
(UI5 WC Developer)

**Comment by PetyaMarkovaBogdanova** [comment]
Hi @BennyHuang ,
can I, please, ask you to isolate the issue, so we can easily reproduce it, or I can consider it is not happening anymore?
Thank you!
Best regards,
Petya Markova.
