### ISSUE TITLE
[SF][Button][A11y]: Focus outline are expected to meet minimum of 4.5:1 CC in focused states

### ISSUE THREAD

**Issue by sleric1024** [SAP/ui5-webcomponents#6875]
### Describe the bug

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/5724592/230256952-47735a15-8b3b-461c-9827-ce33bc8f5f3e.png">
I am from SuccessFactors, in this release we have the A11y issue and confirmed with A11y Testing Expert.
The focusing outline for button component should meet the minimum of 4.5:1 CC in focused states.

### Isolated Example

https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-button--docs

### Reproduction steps

1.
2.
3.
...

### Expected Behaviour

Focus outline are expected to meet minimum of 4.5:1 CC in focused states

### UI5 Web Components for React Version

1.10.0

### UI5 Web Components Version

1.11.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by yanaminkova** [comment]
Hello @sleric1024 ,

Thank you for sharing!

According to the SAP Accessibility Standard in the Horizon themes, the focus indicator is visualized with outline which contrasts at least 3.0:1 to its background. This is sufficient to fulfill the color contrast requirement, as it is a graphical element. 

Thanks and Kind Regards,
Yana

**Comment by sleric1024** [comment]
@yanaminkova , thanks, I will update to my team.
