### ISSUE TITLE
[SF][Tree]: tree content indent is not right in RTL

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents#6892]
### Bug Description

tree content indent is not right in RTL.

in LTR:
<img width="1377" alt="image" src="https://user-images.githubusercontent.com/78520316/231037421-dd1e641d-d8eb-444c-a569-8d8059116ee4.png">

in RTL: the navigation-down-arrow icon has no indent
<img width="1376" alt="image" src="https://user-images.githubusercontent.com/78520316/231037533-8d7b3c57-abcc-4593-aa1c-1ab3501ea93b.png">

### Affected Component

Tree

### Expected Behaviour

tree content indent should be right in RTL.

### Steps to Reproduce

1. go to https://sap.github.io/ui5-webcomponents/playground/components/Tree/?sap-ui-theme=sap_horizon&isrtl=true
2. see tree content indent is not right in RTL.

### Priority

None

### UI5 Web Components Version

1.11.0

### Browser

Chrome

### Operating System

Mac OS

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ivoplashkov** [comment]
Hello,

The issue is reproduced as described.
Could you please have a look why the indent is incorrect in RTL?

Best regards,
Ivaylo
