### ISSUE TITLE
[SAP][RadioButton]: Focus is not present on initial selection of radio button.

### ISSUE THREAD

**Issue by chiragSAP** [SAP/ui5-webcomponents#6895]
### Describe the bug

When a user selects a radio button or a radio button is selected by default, it does not have an outline to represent that the button is focused. 

### Isolated Example

https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-radiobutton--docs

### Reproduction steps

1. Click on radio button
2. use arrow keys to navigate among radio buttons 
3. Outline is present to highlight the focused button

### Expected Behaviour

Outline around the button should be present for initial as well as default selection.

### Screenshots or Videos

https://user-images.githubusercontent.com/129057796/231126634-f0bc6332-8654-4ec9-a291-b85f8c4d7ec6.mp4

### UI5 Web Components for React Version

1.10.3

### UI5 Web Components Version

1.10.3

### Browser

Chrome

### Operating System

Windows

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ivoplashkov** [comment]
Hello colleagues,

There seems to be an issue with the initial focus of the ui5-radio-button.
The issue could be reproduced in the playground.
I have checked how the control behaves in UI5 and there seems to be no such issue, therefore I am forwarding this to you.

Best regards,
Ivaylo

**Comment by gmkv** [comment]
This issue is regarding the [usage of `focus-visible`](https://github.com/SAP/ui5-webcomponents/pull/6084) in some components.
Related to #6762
There is still an ongoing discussion about whether we should keep using focus-visible to draw the focus.

**Comment by Vivek-Vishal** [comment]
@gmkv - any updates on this issue ? It has been open for quite a while.
Regards, Vivek

**Comment by chiragSAP** [comment]
Hi @boghyon ,
The issue was raised to resolve an accessibility issue found while consuming radio buttons. Focus was not visible on the initially selected radio button.
The respective a11y guideline for the same is ACC-271.1
