### ISSUE TITLE
Avatar: missing `accessibleName` announcement

### ISSUE THREAD

**Issue by nipun0212** [SAP/ui5-webcomponents#6896]
### Describe the bug

The Avatar component in the UI5 Web Components React library does not appear to be reading the accessibleName property, which is used to provide an accessible name for the component

### Reproduction steps

Navigate to the Avatar component in the UI5 Web Components React documentation: https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-avatar--docs
Use a screen reader to read the content of the Avatar component.
Notice that the accessible name property is not being read by the screen reader.

### Expected Behaviour

The Avatar component should read the accessible name property when using a screen reader, providing an accessible name for the component and making it easier for users who rely on assistive technologies to understand its purpose and function.

### UI5 Web Components for React Version

1.13.0

### UI5 Web Components Version

1.12.0

### Browser

Chrome

### Operating System

MAC OSx

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ivoplashkov** [comment]
Hello colleagues,

As described above, the aria-label for accessible-name is missing in case of ui5-avatar with initials.
Could you please have a look?

Best regards,
Ivaylo
