### ISSUE TITLE
Layout and Responsive with ui5 Components

### ISSUE THREAD

**Issue by andresfelipe66** [SAP/ui5-webcomponents#691]
**Describe the documentation issue**

- [X ] Other

**Description of the issue**

I'm exploring Fiori fundamentals, in the Page you could find information about Layout and page organization here: https://sap.github.io/fundamental/foundation/grid.html

What do you recomend for Layout with this ui5 Components? 

Thank you

**Comment by fifoosid** [comment]
Hello @andresfelipe66 

UI5 Web Components provide building blocks as button, input, messagestrip, list and many others.
In the near future we don't plan to provide layouts, but for layout of UI5 Web Components in application can be used CSS.

Best regards,
Filip

**Comment by andresfelipe66** [comment]
Hi @fifoosid 

Thanks for the answer... I'l use bootstrap (https://getbootstrap.com/docs/4.3/layout/grid/)

Do you think that is the correct option or what do you recommend ?

Thanks

**Comment by ilhan007** [comment]
Hello @andresfelipe66 , it's up to you. You can use pure CSS to the layout, you can use a library (such as bootstrap) to do it. There is no right or wrong answer. The ui5 web components are custom HTML elements, you can treat them as divs, spans, etc.
