### ISSUE TITLE
TableRow: navigated cell is always displayed

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#6914]
### Bug Description

The "navigated" cell is always displayed with a width of 3px, even though it's not used.

<img width="879" alt="image" src="https://user-images.githubusercontent.com/9749730/231705510-4de4c2f8-0afe-4912-8569-1649658a593e.png">

"navigated" cell marked in red

### Affected Component

TableRow

### Expected Behaviour

The cell to indicate previous navigation should only be displayed (have a width > 0) if it's actually used. I'm not sure how SAPUI5 is handling this, but there the indicator cell only seems to be present when necessary. If I'm missing something here please let me know, but at the moment I don't see an option (except for manipulating internal CSS) to omit this cell in the web component.

[SAPUI5 Table navigated example](https://sapui5.hana.ondemand.com/#/entity/sap.m.Table/sample/sap.m.sample.TableNavigated):
<img width="706" alt="image" src="https://user-images.githubusercontent.com/9749730/231704488-2034f6d7-af8d-4939-b846-edc467f71e07.png">

[SAPUI5 Basic example](https://sapui5.hana.ondemand.com/#/entity/sap.m.Table/sample/sap.m.sample.Table):
<img width="708" alt="image" src="https://user-images.githubusercontent.com/9749730/231704933-59dd0f09-0fd8-443c-bea5-d774e8114723.png">

### Isolated Example

https://codesandbox.io/s/ui5-webcomponents-forked-yj452v?file=/src/index.js

### Steps to Reproduce

1. Go to [codeSandbox](https://codesandbox.io/s/ui5-webcomponents-forked-yj452v?file=/src/index.js)
2. See that the "navigated" cell of each row has a width of 3px

### Priority

Low

### UI5 Web Components Version

1.12.1

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ivoplashkov** [comment]
Hello @Lukas742,

Thank you for reporting this issue.

The idea behind this behavior is that the addition of the new cell would cause the entire table to move or shift, which can be visually jarring or confusing for the user.
I can see that this is the case in UI5.

If you still consider this to be an issue for you, I will forward this to the responsible team for evaluation.

Best regards,
Ivaylo

**Comment by Lukas742** [comment]
Hi @ivoplashkov 

I see, thanks for the clarification. I hadn't noticed before that the cell in the navigation example is initially displayed with a width of 0 and only when the user triggers an interaction, all "navigated" cells get the width. 

In my opinion, it's better to always display the cell than to move the content, but since I'm not a UX/A11Y expert, I'm not sure what would be the better approach here. For me the issue can be closed, but maybe it's worth to consult an expert.

**Comment by ivoplashkov** [comment]
Hi again,

I am closing the issue, since we also consider this to be the right behavior.

Best regards,
Ivaylo
