### ISSUE TITLE
Modal: Open modals cause TypeScript error in CRA-App - ResizeObserver loop limit exceeded

### ISSUE THREAD

**Issue by C3ntraX** [SAP/ui5-webcomponents#6924]
### Describe the bug

Every time when I open a modal in react, the error "ResizeObserver loop limit exceeded" pops up.

This causes not a bug in production, but is really annoying in development and I cant disable to show this error message.
Im using the latest version of CRA.

I already tryed to make a codesandbox in vite but the error is not showing up there. This is because vite dont show compilation errors in browser.

I dont have the error in all apps. In older versions of UI5Webcomponents this bug does not apper.

I'm really desperate because there is no ENV variable in CRA to no longer display the error.

I don't know how to reproduce this bug effectively. I should add a codesandbox in CRA if it helps you, but codesandbox does has problems to load the dependencies, do you have a working example for CRA? I know you switched to vite but many users are using CRA and I also dont want to switch, because I had several problems with vite.

I already tested the following envs for CRA:
ESLINT_NO_DEV_ERRORS=false
DISABLE_ESLINT_PLUGIN=false
TSC_COMPILE_ON_ERROR=false

### Reproduction steps

1.
2.
3.
...

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/44802503/232873031-f35c7655-6d93-4985-853a-54cc1bda8238.png)

### UI5 Web Components for React Version

1.13.0

### UI5 Web Components Version

Provided by UI5 Web Components for React Version

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by vladitasev** [comment]
Hello,

We've had that several times in the past. It is not a "true error" in a sense that it does not appear in the browser's console as most other errors, but still some tools (f.e. testing frameworks, compilers) can complain about this.

It does not cause code malfunction or UI bugs, so can be safely ignored.

I can see that @gmkv is working on a fix. We tried that same fix maybe a year ago, but it made some tests unstable. But if tests pass now, let's merge it and get rid of the error.

Regards,
Vladi
