### ISSUE TITLE
[Feature Request]: Require an auto adjustable width for Select and ComboBox dropdowns

### ISSUE THREAD

**Issue by ShivamGuptaSap** [SAP/ui5-webcomponents#6939]
### Feature Request Description

Require an "auto adjustable width" property for Select and ComboBox dropdown Components 

It should resize according to the width of the text upto certain max width 
i.e. 
Min width: should depend on the dropdown text.
Max width: should be upto certain rem.

Screenshots:

Min Width example:
<img width="217" alt="Screenshot 2023-04-20 at 1 31 40 PM" src="https://user-images.githubusercontent.com/107616257/233301675-58a4c427-2d9c-4f84-b2c2-3fb9cf91cb85.png">

Max Width example: 
<img width="243" alt="Screenshot 2023-04-20 at 1 36 41 PM" src="https://user-images.githubusercontent.com/107616257/233301830-326c8a2a-fb44-4ad4-866f-9b907f40fe49.png">

### Proposed Solution

You can provide an "autoAdjustWidth" property to "Select Component" and "ComboBox Component"
which will automatically adjust the width of the dropdown based on the text length. 

### Priority

High

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by hristop** [comment]
Hi @ShivamGuptaSap ,

Currently there is no such concept in Fiori design system. 
After looking into this feature request and synchronising it with the owners of the Select and the ComboBox and evaluating the technical and design requirements we have decided that we will not implement this feature. 

Best Regards,
Hristo
