### ISSUE TITLE
[ui5-input]: mobile suggestion popover input double border

### ISSUE THREAD

**Issue by JarrettChan** [SAP/ui5-webcomponents#6943]
### Bug Description

The ui5-input embedded in the `div.input-root-phone` is shown with a double border
`div.input-root-phone` has its own border in Fiori 3 and its own focus outline in Fiori 3 / Horizon.
ui5-input has a margin `_ui5_input_margin_top_bottom` and does not fit well inside of the `div.input-root-phone`

In Fiori 3 there is a double border and when focused there is double focus outline
![Fiori 3 example](https://user-images.githubusercontent.com/4755512/233456691-e1d1b05e-c1c1-4f03-9403-625314394e69.png)

In Horizon there is a double border when focused
![Horizon example](https://user-images.githubusercontent.com/4755512/233456655-e6cff3ee-ae65-4f07-b7f3-0d499896a287.png)

### Expected Behaviour

There shouldn't be a double border for the input in the mobile suggestion popover

### Steps to Reproduce

1. chrome mobile emulation
2. https://sap.github.io/ui5-webcomponents/playground/components/Input/
3. tap Input with Suggestions
4. Compare mobile popover in "Quartz Light" and "Morning Horizon (Light)"

### Priority

None

### UI5 Web Components Version

1.11.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by LidiyaGeorgieva** [comment]
Hello @SAP/ui5-webcomponents-topic-rl  the reported issue is reproducible. Please take over.
