### ISSUE TITLE
[SF][Carousel]: Navigation button of carousel is not vertically centered when page indicator is hidden

### ISSUE THREAD

**Issue by Jasonl157** [SAP/ui5-webcomponents#6954]
### Describe the bug

[SF][Carousel]: Navigation button of carousel is not vertically centered when page indicator is hidden

### Isolated Example

https://codesandbox.io/s/silly-stallman-fppkqf?file=/src/App.js

### Reproduction steps

1. Open https://codesandbox.io/s/silly-stallman-fppkqf?file=/src/App.js
2. Move your mouse on carousel component. then you will see the navigation button

### Expected Behaviour

Navigation button should be vertically centered

### Screenshots or Videos

<img width="729" alt="image" src="https://user-images.githubusercontent.com/131832797/234441158-1305159a-6176-4d16-9124-1ea2ea19d243.png">

Expected:
<img width="732" alt="image" src="https://user-images.githubusercontent.com/131832797/234441867-e210277f-e809-4ad2-bc5e-33313b1f99c2.png">

### UI5 Web Components for React Version

1.13.1

### UI5 Web Components Version

1.12.2

### Browser

Chrome

### Operating System

Mac

### Additional Context

I am from SAP SuccessFactors. Issues are for b2311 released project.

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by tsanislavgatev** [comment]
Hello colleagues,

Can you please take a look at this issue?
Here you can find a [codeSandbox](https://codesandbox.io/s/ui5-webcomponents-forked-z0x91l?file=/index.html) showing this behavior using only plain js with UI5WC.

Best Regards,
Tsanislav
