### ISSUE TITLE
[SF][ui5-illustrated-message] IllustratedMessage vertical responsiveness

### ISSUE THREAD

**Issue by ksblklu** [SAP/ui5-webcomponents#6960]
### Bug Description

IllustratedMessage not correctly resized with container height changing

### Affected Component

ui5-illustrated-message

### Expected Behaviour

IllustratedMessage should have vertical responsiveness, refer to https://sapui5.hana.ondemand.com/?sap-ui-theme=sap_horizon#/entity/sap.m.IllustratedMessage/sample/sap.m.sample.IllustratedMessageEVR

### Isolated Example

https://codesandbox.io/p/sandbox/autumn-meadow-ywezdx?file=%2Fsrc%2FApp.tsx&selection=%5B%7B%22endColumn%22%3A40%2C%22endLineNumber%22%3A14%2C%22startColumn%22%3A40%2C%22startLineNumber%22%3A14%7D%5D

### Steps to Reproduce

1. Go to [codesandbox](https://codesandbox.io/p/sandbox/autumn-meadow-ywezdx?file=%2Fsrc%2FApp.tsx&selection=%5B%7B%22endColumn%22%3A40%2C%22endLineNumber%22%3A14%2C%22startColumn%22%3A40%2C%22startLineNumber%22%3A14%7D%5D)
2. Referring to fiori visual design, illustrated message should have both vertical & horizontal responsiveness. In above example, the container height is set to "400px", and  the message should have "Dialog" size, but still displayed as large size.

<img width="1687" alt="image" src="https://user-images.githubusercontent.com/27538066/234799854-8627b75b-5b13-48f6-a437-53224599772a.png">

3. Seems currently illustrated message only support horizontal responsiveness

### Priority

Medium

### UI5 Web Components Version

1.13.0

### Browser

Chrome

### Operating System

MacOS

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by tsanislavgatev** [comment]
Hello colleauges,

Can you please check this issue?

Best Regards,
Tsanislav

**Comment by ilhan007** [comment]
Hello @ksblklu 
thank you for the descriptive information.

I just want to inform you that the link to the visual design wiki is considered sensitive information. Also, the first screenshot from the design wiki also shows more than needed (if it was cropped to show the CSS vars it would have been great).
We don't insist on taking action now, although editing the description would be great,
 but please consider this for at least new issues in future.
 
 Thank you,
 ilhan
 UI5 Web Components team

**Comment by ksblklu** [comment]
> Hello @ksblklu thank you for the descriptive information.
> 
> I just want to inform you that the link to the visual design wiki is considered sensitive information. Also, the first screenshot from the design wiki also shows more than needed (if it was cropped to show the CSS vars it would have been great). We don't insist on taking action now, although editing the description would be great, but please consider this for at least new issues in future.
> 
> Thank you, ilhan UI5 Web Components team

Hi @ilhan007 
Thanks for your reminder, I just removed the design wiki screenshot.

**Comment by PetyaMarkovaBogdanova** [comment]
Hi @ksblklu ,
since the case is already reported and moved to our planning board for evaluation in #6492,
I am closing this one as a duplicate.
You can subscribe and follow the progress there.

Best regards,
Petya Markova.
(UI5 WC Developer)
