### ISSUE TITLE
[ui5-multi-combobox]: Close icon doesn't work on mobile with grouping of items

### ISSUE THREAD

**Issue by petyabegovska** [SAP/ui5-webcomponents#6961]
### Bug Description

In the sample 'MultiComboBox with Grouping of items', when you open the selection dialog, it can't be closed with the "x" button in the upper right corner. 
![image](https://user-images.githubusercontent.com/8136099/234803072-f8b0fcab-594f-45e6-b9f3-53dda9566a27.png)

### Affected Component

ui5-multi-combobox

### Expected Behaviour

"x" icon close the dialog on mobile.

### Steps to Reproduce

1. Open playground: https://sap.github.io/ui5-webcomponents/playground/components/MultiComboBox/
2. Scroll to the sample: MultiComboBox with Grouping of Items
3. Click on the dropdown arrow to show the list
4.  Click the "x" button in the upper right corner
...

### Priority

None

### UI5 Web Components Version

Latest playground + main

### Browser

Chrome, Safari

### Operating System

iOS 16.3.1

### Additional Context

iPhone 12 Pro Max

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by didip1000** [comment]
Hi team, 

Can you please look at the following issue? It's reproducible on mobile, and you get the following console error when the **close** button is pressed:
_caught TypeError: Cannot set property selected of #<vu> which has only a getter_

Thanks,
Diana
