### ISSUE TITLE
Native/Auto Html form Submition

### ISSUE THREAD

**Issue by aammfe** [SAP/ui5-webcomponents#6963]
Hello!
Great component library.
I would like to know how we can submit forms using Native/Auto Form Submission using these controls.

I have UI5MultiComboBox in a form, with other HTML native inputs (it's an old form). but upon submission neither ComboBox is validated nor its value is added to the submitted form.

like it's not even in the form.

we are not using any framework, just using plan Vanalia Js,  I was under the influence that it would be just plug-and-play.
 or I'm missing something?

**Comment by ilhan007** [comment]
Hello @aammfe, 
the form support is like an add-on feature that needs to be imported in addition.

```js
import "@ui5/webcomponents/dist/features/InputElementsFormSupport.js"
```

Could you try this out.

**Comment by aammfe** [comment]
there is more or less no effect of doing this thing, 
I have attached the code in zip . 
to run it
1- `npm run`
2- `npm run start` // parcel will open index.html
here you can see there is no effect of importing `@ui5/webcomponents/dist/features/InputElementsFormSupport.js`

There is another issue I'm facing when we build using `npm run build` I'm facing the following error 

```
npm run build 

> ui5-webcomponents-starter@1.0.0 build
> parcel build src/index.html

🚨  /home/abdul/projects/ui5-webcomponents-starter/node_modules/@ui5/webcomponents-base/dist/util/AriaLabelHelper.js: Unexpected token: punc (.)
    at Z.get (/home/abdul/projects/ui5-webcomponents-starter/node_modules/parcel-bundler/node_modules/terser/dist/bundle.min.js:1:525)
```


[ui5-webcomponents-starter.zip](https://github.com/SAP/ui5-webcomponents/files/11351024/ui5-webcomponents-starter.zip)

**Comment by ilhan007** [comment]
Hello @aammfe  it should have worked but my colleagues found out that the support is not fully implemented, the MultiComboBox does not provide "name" property that can be used, as for example in the ComboBox.

So, I will forward the issue to the MultiComboBox owners to plan and add the required functionality.

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-rl could you take a look, it seems Form Support is not fully implemented for the MultiComboBox,  although the component " triggers form submit on Enter ("this.FormSupport.triggerFormSubmit(this)"), but I guess it needs "name" property as in the ComBobox.

**Comment by IlianaB** [comment]
Hello @SAP/ui5-webcomponents-topic-rl , 
please take a look at this feature request. It seems like it is for ComboBox and MultiComboBox.
Such a "name" property is implemented in the Input and Select.

Regards,
Iliana

**Comment by hristop** [comment]
Hi @aammfe ,

Can you please clarify what is expected as result when the form is submitted? 
Do you expect only the value of the multi-combobox or you would expect that the already tokenised values are also sent. If the second option is desired, can you provide further clarification how the data is expected. 

Best Regards,
Hristo
