### ISSUE TITLE
Angular Reactive Forms Support 

### ISSUE THREAD

**Issue by urielrodriguezusma** [SAP/ui5-webcomponents#697]
HI
1) I'm trying to use Reactive Forms in angular with ui5-input control this way
`  <ui5-input formControlName="userName"></ui5-input>`

But I receive an exception 
![errorUI](https://user-images.githubusercontent.com/36137028/61963079-87341680-af90-11e9-9539-705dc7a38cbb.png)

However, if I use a normal input with html works perfectly. Is it possible that I need to import some extra module?

2) How can I use the two way data binding? I Install the package and imported OrigamiFormsModule but it doesn't work. Maybe I'm making a mistake.

3) Finally How Can I apply the style sap-ui-compactSize in angular's project.

Thanks for your help.

**Comment by MapTo0** [comment]
Hello @urielrodriguezusma 

We are currently working on improving the two way databinding of the components. Follow: https://github.com/SAP/ui5-webcomponents/issues/651

Currently you can add a `ngDefaultControl` attribute to the ui5-input and it will enable you to use it for two way databinding. Please give a try to that solution for your points 1 and 2

3. You can change the compact setting using the configuration script placed in your index.html

``` html
<script data-id='sap-ui-config' type="application/json">
	{
		"compactSize": true
	}
</script>
```

**IMPORTANT:** The configuration script attribute will be changed in the next release

~~`data-id='sap-ui-config'`~~  => `data-ui5-config`

``` html
<script data-ui5-config type="application/json">
	{
		"compactSize": true
	}
</script>
```

Please check the proposed solution and if they work we can duplicate this and follow https://github.com/SAP/ui5-webcomponents/issues/651

**Comment by fifoosid** [comment]
Hi @urielrodriguezusma,

About Reactive forms support:
#706 is in master now and will be available in the next release.

I am closing the issue as all your questions have been answered. In future when you have a couple of problems, please open separate issues for each problem that you have 😊 

Best regards,
Filip
