### ISSUE TITLE
Just above breakpointSize=S (~715px width), right-container margin-inline-start covers overflow button & profile button

### ISSUE THREAD

**Issue by SkylarLK9998** [SAP/ui5-webcomponents#6972]
ui5-shellbar

Expected Behaviour
The Profile Picture icon does not clip regardless of resize.

Isolated Example
https://codesandbox.io/s/ui5-webcomponents-forked-shellbar-pm2vek?file=/src/index.js

Steps to Reproduce
1. Navigate to https://codesandbox.io/s/ui5-webcomponents-forked-shellbar-pm2vek?file=/src/index.js
2. Resize screen to at or bellow breakpoint size 720px width and watch the Avatar clip/disappear behind the margin

Log Output, Stack Trace or Screenshots
![Screenshot 2023-05-01 at 10 42 18 AM (2)](https://user
![Screenshot 2023-05-01 at 10 37 45 AM](https://user-images.githubusercontent.com/22405235/235499507-9ead161a-783e-4462-adfd-7bf84da60afc.png)
-images.githubusercontent.com/22405235/235499491-980ffb99-4a78-4d2e-8253-16fa6966938c.png)

UI5 Web Components Version
latest

Browser
Chrome v111, v112

Operating System
MAC OS, OSx, Windows 11

Additional Context
No response

Declaration
 I’m not disclosing any internal or sensitive information.

Tag SFSF

**Comment by IlianaB** [comment]
Hello @SAP/ui5-webcomponents-topic-p I am forwarding this issue to you, because in some cases when primary title of shellbar is too long and the screen size is below S breakpoint, the profile picture is getting overlapped/cut.
