### ISSUE TITLE
[ui5-combobox]: Item selection from list cause multiple selections if text is repeated

### ISSUE THREAD

**Issue by subint1994** [SAP/ui5-webcomponents#6978]
### Bug Description

Im using ui5-webcomponents-react ComboBox for showing a dropdown with grouping. However, if there are items with same name in two different groups, and when I'm selecting the item from one group, the item in the other group is also shown as selected with a highlight.

<img width="217" alt="Screenshot 2023-05-03 at 1 30 10 PM" src="https://user-images.githubusercontent.com/34679598/235861577-ab8d89bb-b95e-497b-8515-4630ae793642.png">
<img width="216" alt="Screenshot 2023-05-03 at 1 30 17 PM" src="https://user-images.githubusercontent.com/34679598/235861595-ae343963-0d07-4ddc-9e5d-6debb1da4e39.png">

### Affected Component

UI5 ComboBox

### Expected Behaviour

Selection should be unique even if text is repeated.

### Isolated Example

https://codesandbox.io/s/combo-box-key-forked-8i88fn?file=/src/App.js

### Steps to Reproduce

1. Have some data with unique ID and repeating text for the combo box data.
2. Click on one of the repeating text.

<img width="217" alt="Screenshot 2023-05-03 at 1 30 10 PM" src="https://user-images.githubusercontent.com/34679598/235861673-c7e52f53-70c7-420f-80c2-4789a726146c.png">

<img width="216" alt="Screenshot 2023-05-03 at 1 30 17 PM" src="https://user-images.githubusercontent.com/34679598/235861689-037911b6-831b-4ec1-ac0e-5bb82cace55b.png">

### Priority

None

### UI5 Web Components Version

1.10.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by IlianaB** [comment]
Hello @SAP/ui5-webcomponents-topic-rl I am forwarding this issue to you, because when there are more than one ComboBoxItems with same text in different groups, if one of them is selected, all of them appear to be highlighted, which seems confusing: https://codesandbox.io/s/ui5-webcomponents-forked-uneszn?file=/index.html (I cannot see grouping in the provided above sample).

Regards,
Iliana
