### ISSUE TITLE
Sidebar with Fiori Style

### ISSUE THREAD

**Issue by andresfelipe66** [SAP/ui5-webcomponents#698]
**Describe the documentation issue**
- [X ] Documentation is missing

**Description of the issue**
How can I implement the side bar with Fiori Style, do you have component for that or what do you recommend?

I Like to implement something like that: 

https://sapui5.hana.ondemand.com/test-resources/sap/tnt/demokit/toolpageapp/webapp/index.html

Thanks !

**Comment by ilhan007** [comment]
Hello @andresfelipe66 the list of the available components are here:
https://sap.github.io/ui5-webcomponents/playground/

We don't provide layout components and will not build such at least in the next few months. I noticed that you are asking for a lot of layout components. 

If you want to have so many layout components, maybe it's good idea to use openui5.
https://github.com/SAP/openui5

If you are willing to write CSS to build your layouts, keep going with the ui5 webcomponents. We have a ui5-shellbar to serve as too bar, but for the side bar, you have to do it on your own  and perhaps you can  put ui5-list with ui-li items inside. 
But, achieving the dark background with white list item text color will be challenging with the latest released version. We did a major css refactoring, which is not yet released, allowing to change the lis items background and color easier. This refactoring will be part of the next release and will allow achieving the required dark style of the side bar.

Best,
ilhan
