### ISSUE TITLE
[component name | framework | build | icons | theming | localization | i18n | typescript]:

### ISSUE THREAD

**Issue by clarenceWan** [SAP/ui5-webcomponents#6980]
### Bug Description

Not able to run Unit Test for custom WebComponent

### Expected Behaviour

Auto Generated tests should execute successfully.

### Steps to Reproduce

1. create a custom package using _npm init @ui5/webcomponents-package_
2. _npm install_ in the package directory
3. npm run build
4. npm run test

### Priority

High

### UI5 Web Components Version

1.12.2

### Browser

Chrome

### Operating System

Mac

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ilhan007** [comment]
Hello @clarenceWan this PR should resolve the issue with the `test` command
https://github.com/SAP/ui5-webcomponents/pull/6976
