### ISSUE TITLE
DateTimePicker: Initial time values starts with wrong time

### ISSUE THREAD

**Issue by C3ntraX** [SAP/ui5-webcomponents#6992]
### Describe the bug

See the gif.

In mobile view, the hour starts with 0 until you click on the hour field the hour refreshes and shows the correct hour.

### Reproduction steps

1.
2.
3.
...

### Screenshots or Videos

![GIF 05 05 2023 14-54-50](https://user-images.githubusercontent.com/44802503/236463032-dd6fef22-69a2-4d94-b2f5-2113f75a2b9c.gif)

### UI5 Web Components for React Version

~1.14.0

### UI5 Web Components Version

~1.12.2

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by tsanislavgatev** [comment]
fixed with https://github.com/SAP/ui5-webcomponents/pull/7967
