### ISSUE TITLE
DateTimePicker: valueState error with valueStateMessage not shown

### ISSUE THREAD

**Issue by C3ntraX** [SAP/ui5-webcomponents#6993]
### Describe the bug

If you select a date/time which causes the valueState turn to error and select another invalid time, then the valuestate will disapper, but should keep the error state.

The errorstates will be overwritten, somehow.

### Isolated Example

https://codesandbox.io/p/sandbox/thirsty-borg-hrq99v?file=%2Fsrc%2FDateTimePicker.tsx%3A29%2C13

### Reproduction steps

1. Select a time above the current time which is invalid
2. See: Errormessages appears
3. Select another time above the current time which is invalid
4.  Errormessage disappers
...

### Screenshots or Videos

![GIF 05 05 2023 14-43-33](https://user-images.githubusercontent.com/44802503/236460692-de6cc6ff-5f67-4a5f-9095-cf2ea8849b97.gif)

### UI5 Web Components for React Version

~1.14.0

### UI5 Web Components Version

~1.12.2

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @C3ntraX and colleagues,

some additional information:

This is happening because the internal state of the web component is updated, but since the React lifecycle doesn't know about this, the React state stays the same (`"Error"`), so when updating a second time with a faulty entry React still "thinks" that the `"Error"` state is applied and therefore doesn't fire another update. 
You can find a workaround for it in [this codeSandbox](https://codesandbox.io/p/sandbox/stupefied-thompson-c5x6fi?file=%2Fsrc%2FDateTimePicker.tsx).

This behavior is similar to the one I described [here (#4883)](https://github.com/SAP/ui5-webcomponents/issues/4883). To fully control the component, all internal state updates need to either implement a way for developers to hook into (without the need for an observer) or, better yet in my opinion, find a way to prevent them.

**Comment by C3ntraX** [comment]
Hi @Lukas742,

I don't really know whats happening, why the internal state updates to "None" or something and ignores my "Error" state.
What's important for me is the fact, that I shouldn't use this workaround in regular usecases, because its really complicated for regular use cases.
Your idea of a "hook/event" that fires when the internal state changes is good but only in combination with event.preventDefault() or some other possibility to prevent the new errorstate and only accept my errorstate.

Some simple solution should be implemented.

**Comment by Okiana** [comment]
Hello @SAP/ui5-webcomponents-topic-b,

The issue is reproducible in the codeSandbox sample which is provided. 
What I've found out is that in the _updateValueState function of the DatePicker there is a strange behavior.
The second time when  the value is changed again to not valid one the logic goes throw the if and else if in the same time and the value state is first updated to error  and then to none.

Could you please look over this issue?

Kind regards,
Evdokia

**Comment by C3ntraX** [comment]
Hello @hinzzx,

I linked the wrong codesandbox-link somehow.

Please use this instead

https://codesandbox.io/p/sandbox/sparkling-feather-hewfdm?file=%2Fsrc%2FDateTimePicker.tsx%3A40%2C25

I will update the bugdescription link as well.

**Comment by hinzzx** [comment]
Hi @C3ntraX,

I could not reproduce the issue with the new snippet link https://codesandbox.io/p/sandbox/sparkling-feather-hewfdm?file=%2Fsrc%2FDateTimePicker.tsx%3A40%2C25

Could you please check if the issue is still relevant ?

Best Regards,
Stoyan

**Comment by C3ntraX** [comment]
Hi @hinzzx 

the error is still present.

https://codesandbox.io/p/sandbox/thirsty-borg-hrq99v?file=%2Fsrc%2FDateTimePicker.tsx%3A29%2C13

Step 1: Choose a time after the current time - this will cause `valueState=ValueState.Error`
Step 2: See that an errorstate appears
Step 3: Repeat step 1. `valueState=ValueState.Error` from step 1 will keep the state.
Step 4: See that the errorstate disappears

**Comment by hinzzx** [comment]
Hi @C3ntraX,

Following your steps I am not able to reproduce the issue, could you please tell me if I am doing something wrong, following the steps ?

Video:
https://github.com/SAP/ui5-webcomponents/assets/88034608/4ce349fd-ff6e-42a3-90ee-e3ec7e27e96b

**Comment by hinzzx** [comment]
Hi @C3ntraX,

I am still not able to reproduce the problem. Could you please, tell me if I am doing something wrong in the steps of the reproduction ? Thank you in advance !

Video:
https://github.com/SAP/ui5-webcomponents/assets/88034608/8d114ad6-805c-4939-ba37-81e1543d0499

**Comment by C3ntraX** [comment]
Hi @hinzzx,

your did step 3 wrong:
Step 1: Choose a time after the current time - this will cause valueState=ValueState.Error

Dont change the date, only change the time to be later than your current time. 
In the first try you did it correctly and you saw the error, but you didn't repeat the same step.
You instead choosed a time lower than the current time and a date other than the current date.

**Comment by C3ntraX** [comment]
![GIF 30 05 2023 15-12-59](https://github.com/SAP/ui5-webcomponents/assets/44802503/7182c98f-175a-4fd5-816e-aaba2f4ad674)

**Comment by C3ntraX** [comment]
Hello @hinzzx,

I updated my codesandbox to be in english.
Your internal language is now always `en` and dayJs is by default `en`.  This will fix the issue in #7022 
If your maxDate is working like in my gif (comment) above, where only the current date and the the dates lower than the current date is allowed, then you should able to reproduce the issue.

**Comment by C3ntraX** [comment]
Hey @hinzzx,

I hope you can reproduce it now?

**Comment by hinzzx** [comment]
Hi @C3ntraX,

Yes, the issue is now reproducible, thank you!

I will now start investigating for a possible solution.

**Comment by hinzzx** [comment]
Hi @C3ntraX ,

We have a fix for the ui5-webcomponents, but in order for you to adapt/consume it, you would have to set the valueState like this:

![image](https://github.com/SAP/ui5-webcomponents/assets/88034608/09f45e47-de12-4b58-ad7d-ffd9a56d3c41)

Would that solution work for you ? 😊

Best Regards,
Stoyan

**Comment by C3ntraX** [comment]
Hi @hinzzx,

interesting, I already had a similar solution you offer me, but I thought its has either to be documented and need examples or you should fix it, like the API describes it.

I mean, for me I already had a workaroud but I want that other people to not have the same problems like me.

What do you think?

Btw. this was my solution

```
onChange={(e) => {
        // Date valid, now check time
        let valid = true;
        const currentValue = dayjs(e.detail.value, dayjsFormatPattern);
        if (e.detail.valid) {
           if (!maxTime || currentValue.isBefore(maxTime(), "second")) {
              setErrorMsg("");
           } else {
              valid = false;
              setErrorMsg(`Invalid time. Please select a time below ${maxTime().format("HH:mm:ss")}`);
           }
        } else {
           valid = false;
           setErrorMsg("Invalid entry");
        }
        if (!valid) {
           e.target.setAttribute("value-state", "Error");
        }
        handleChange?.(currentValue, valid);
     }}

```

**Comment by yuyuCream** [comment]
Hi @hinzzx 
I have the same issue. When will you fix this issue in new version of webcomponents?
