### ISSUE TITLE
[Feature Request] [Topic RL] Update the visual design to the latest Horizon spec

### ISSUE THREAD

**Issue by petyabegovska** [SAP/ui5-webcomponents#7002]
### Feature Request Description

The Horizon theme specification has been updated based on stakeholder feedback. Implement the visual design and link the relevant PRs.

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

### **Components**
- [x] Combo Box - **P1-27431**
- [x] Input - **P1-27431**
- [x] ~~Message Strip~~ - _No visual changes required_
- [x] Multi Combo Box - **P1-27431**
- [x] Multi Input - **P1-27431**
- [x] Token - **P1-27500**
- [x] Panel - **P1-27471**
- [x] ~~Rating Indicator~~ - _No visual changes required_
- [x] Range Slider - **P1-27519**
- [x] Slider - **P1-27518**
- [x] ~~Table~~ - _No visual changes required_
- [x] Text Area - **P1-27516**
- [x] ~~Toast~~ - _No visual changes required_
- [x] ~~Wizard~~ - _No visual changes required_
- [x] ~~Page~~ - _No visual changes required_

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by petyabegovska** [comment]
Hello @SAP/ui5-webcomponents-topic-rl  you can relate your PRs to the current issue (related to: #issue_num) so we can keep track the progress.

**Comment by hristop** [comment]
The Slider and RangeSlider will have to wait until the adoption of the new theme parameter values. 
Only then we can update the two components.

**Comment by hristop** [comment]
Range/Slider components were updated
