### ISSUE TITLE
List | UI5 Web components: Simple list cursor should not be pointer

### ISSUE THREAD

**Issue by andrea-island** [SAP/ui5-webcomponents#7010]
### Bug Description

When a list does not have any actions, like select, etc. the cursor should not be a pointer as it's confusing for users if there is an action there.

### Affected Component

List

### Expected Behaviour

Regular arrow cursor instead of pointer

### Isolated Example

https://sap.github.io/ui5-webcomponents/playground/components/List/

### Steps to Reproduce

1. The first example in the storybook link I provided above
2.
3.
...

### Priority

Medium

### UI5 Web Components Version

Latest

### Browser

Chrome

### Operating System

MacOS

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by niyap** [comment]
Hello @andrea-island,

Thanks for sharing your findings!

By default, the list item type is "Active": https://sap.github.io/ui5-webcomponents/playground/components/List/ 
When "Active" it is expected to have pointer as a cursor. If you change the list item type to "Inactive" or "Detail" you will notice that the cursor is the default one. The cursor used depends on the List "mode" and the list item "type"
In the first example, which you point in the description of the issue, the default list item type is used, so the cursor is the expected one.

Kind Regards,
Niya
