### ISSUE TITLE
[Feature Request]: List should have growingButtonText and growingButtonSubText properties

### ISSUE THREAD

**Issue by Vir-Mittal** [SAP/ui5-webcomponents#7028]
### Feature Request Description

List component should have growingButtonText and growingButtonSubText properties similar to the Table component

### Proposed Solution

Add growingButtonText and growingButtonSubText properties

### Priority

Medium

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by petyabegovska** [comment]
Hi @Vir-Mittal,

Can you provide a little bit more information on your use case and if possible stakeholder information? 

Thanks and best regards,
Petya

**Comment by Vir-Mittal** [comment]
Hi,

Stakeholder - SuccessFactors
Our use case is that we have are displaying a list of comments and the list can have more than 20 comments. Initially though, we went to only load 5 of these comments and display the "more" growing button at the bottom of the list. The growingButtonText and growingButtonSubText properties would allow us to show the user how many more comments can be loaded. For example - "More [5/34]"

**Comment by dobrinyonkov** [comment]
Internal Reference: BGSOFUIPIRIN-6470

**Comment by yanaminkova** [comment]
Unlike the ui5-table, according to the design specification of the ui5-list, the component does not have designated space for the text of the growingButtonSubText property. Therefore, only the growingButtonText property will be implemented.
