### ISSUE TITLE
[SF_ACC][Feature Request][IllustratedMessage]: Enable arialTitleLevel property of IllustratedMessage

### ISSUE THREAD

**Issue by ksblklu** [SAP/ui5-webcomponents#7037]
### Feature Request Description

Hi team

We use `IllustratedMessage` widely in our project. For accessibility guidelines, the aria-level of IllustratedMessage needs to be customized in different scenarios. Now standard `ui5-illustrated-message` title has fixed `H2` level, but when we use `title` slot to change the aria-level of IllustratedMessage title, the slotted title loses its responsive style. So can we support an `arialTitleLevel` property, to customize the aria-level of illustratedMessage title and also keep its responsiveness?

Best Regards

### Proposed Solution

Refer to SAPUI5: https://sapui5.hana.ondemand.com/?sap-ui-theme=sap_horizon#/api/sap.m.IllustratedMessage%23overview,
expect an `ariaTitleLevel` property for IllustratedMessage:
<img width="1667" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/27538066/ede8b3d5-4c52-4ad8-b7cd-be18d4b88c96">

### Priority

Medium

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by dimovpetar** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

Take a look of this feature request. The author would like to benefit from the responsive IllustratedMessage title styles, just wants different title level.

Best regards,
Petar

**Comment by ksblklu** [comment]
Hi @dobrinyonkov 
Yes we can change the style and aria-level of the title in our customized slot, but the original illustratedMessage title has an responsive style(different font-size&margin under different sizes) which disappeared in slotted title. Heres an example of it: https://codesandbox.io/p/sandbox/frosty-firefly-phqyqi?file=%2Fsrc%2FApp.tsx%3A28%2C40
<img width="1617" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/27538066/4260d588-b30e-4e03-ba20-a1c21e22edd2">
<img width="1678" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/27538066/59553a1f-482f-449c-b32b-b6fe958ca31c">

**Comment by dobrinyonkov** [comment]
Internal reference: BGSOFUIPIRIN-6156

**Comment by ksblklu** [comment]
Hi @dobrinyonkov
