### ISSUE TITLE
[ui5-label]: showColon is not language-dependent

### ISSUE THREAD

**Issue by mhchem** [SAP/ui5-webcomponents#7048]
### Bug Description

The effect of showColon is not language-dependent ...

### Affected Component

ui5-label

### Expected Behaviour

... but should be.

### Steps to Reproduce

Set your browser to prefer English and open https://sap.github.io/ui5-webcomponents/playground/components/Label/ and (for reference)  https://sapui5.hana.ondemand.com/#/entity/sap.m.Label/sample/sap.m.sample.LabelProperties.
Observe the colons are behind each label.
Set your browser to prefer French and refresh the pages.
Observe that the colons for web components NOT are separated by whitespace from the last word, but they are for UI5.

See also https://github.com/SAP/ui5-webcomponents/issues/3531#issuecomment-885571016

### Priority

Low

### UI5 Web Components Version

latest

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by gmkv** [comment]
Hi @SAP/ui5-webcomponents-topic-rd 
Let's add the Chinese and French special cases of the colon.

**Comment by dimovpetar** [comment]
Hello @mhchem ,

With #7090 the colon symbol is made language-dependent. Thanks for reporting this :)

Best regards,
Petar
