### ISSUE TITLE
[Feature Request]: Support autofocus attribute for ui5-input

### ISSUE THREAD

**Issue by TinaC** [SAP/ui5-webcomponents#7053]
### Feature Request Description

For accessibility reason, we want to focus the first input in the dialog.
https://stackoverflow.com/a/47067561/5238583 

### Proposed Solution

Since there is a HTML attribute that can do it, can we pass that to the Input component?
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autofocus
https://www.w3schools.com/tags/att_input_autofocus.asp
https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_autofocus

```
<ui5-input autofocus></ui5-input>
```

### Priority

None

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by dimovpetar** [comment]
Hello @TinaC ,

The Dialog component has `initialFocus` property, which can be set to the ID of the input element you want. Have you tried it?
https://sap.github.io/ui5-webcomponents/playground/components/Dialog/

Best regards,
Petar

**Comment by TinaC** [comment]
Yes, it's working! Thanks for the solution
