### ISSUE TITLE
[ui5-shellbar]: RTL input is always min-width

### ISSUE THREAD

**Issue by JarrettChan** [SAP/ui5-webcomponents#7065]
### Bug Description

When Shellbar is rendered in RTL and has an embedded Input, the Input is always min-width regardless of the width of the Shellbar.

As far as I can recall, this has always been an issue.

### Affected Component

ui5-shellbar

### Expected Behaviour

Input width should expand and shrink similar to LTR embedded input

### Isolated Example

https://codesandbox.io/s/ui5-webcomponents-forked-shellbar-mlj4cz

### Steps to Reproduce

1. Use a locale that sets RTL direction
2. Show the embedded Input in a Shellbar
3. Observe: Input is always min-width

### Log Output, Stack Trace or Screenshots

![image](https://github.com/SAP/ui5-webcomponents/assets/4755512/489825da-82bd-47e0-b7a9-63f2001ea123)

### Priority

Medium

### UI5 Web Components Version

1.11

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by dimovpetar** [comment]
Hello @SAP/ui5-webcomponents-topic-p ,

This is a reproducible layout issue in the ShellBar component.

Best regards,
Petar
