### ISSUE TITLE
[Wizard, WizardSteps] Tab Bar Behavior 

### ISSUE THREAD

**Issue by FirstOrangutan** [SAP/ui5-webcomponents#7067]
### Is your feature request related to a problem?

This request is related to a customer feedback we have received. We at [SAP PRP (public url)](https://help.sap.com/docs/PRP) use UI5 webcomponents for our Market Unit, react based UI application. This request is specifically about Wizard component. If we refer to Fiori Design Guideline for Wizard, it mentions two modes a Wizard - 

1. Anchor Bar / One Page Behavior - Steps are arranged as tabs horizontally on top. _Clicking a step navigates to the respective step on the page._
2. Tab Bar - Similar to Anchor Bar . _Clicking a tab displays the respective subpage._

[Public Link to the design guideline](https://experience.sap.com/fiori-design-web/wizard/#structure)

Traditional JavaScript based UI5 Wizard control enables that through property:

`renderMode: sap.m.WizardRenderMode.Page ` 

[Here is a link to a sample/demo ](https://sapui5.hana.ondemand.com/sdk/#/entity/sap.m.Wizard/sample/sap.m.sample.WizardSingleStep)

As of v1.15.1 - there is no such property to set this behavior in ui5-webcomponents. Therefore, our implementation of the wizard defaults to Anchor Bar/One Page Behavior. One of our customer has requested the Tab Bar functionality.

### Describe the solution you'd like

A new property in component Wizard (something like renderMode) to accept Page or Scroll -  [reference](https://sapui5.hana.ondemand.com/sdk/#/api/sap.m.WizardRenderMode)

### Describe alternatives you've considered

We have considered implementing the Page behavior directly in our implementation, but if there is a possibility that this will be provided by the component, that will be ideal because we will not have to de-implement it later. 

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by petyabegovska** [comment]
The feature looks similar to: #3777.

**Comment by ilhan007** [comment]
Hello @FirstOrangutan the request has been implemented, there is a new `contentLayout` property with 2 possible values - SingleSteps and MultipleSteps. When you set `SingleSteps`, you get the Page mode, that you asked for.

The feature is released with 1.14.0

BR,
ilhan
