### ISSUE TITLE
[ui5-menu]: Missing delay for sub menus (direct mouse movement)

### ISSUE THREAD

**Issue by mhchem** [SAP/ui5-webcomponents#7078]
### Bug Description

When moving the mouse to a sub menu item, the sub menu often closes before the mouse can reach it.

<img width="364" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/16336692/c314b5d5-4ec7-41ea-b4ed-ff9472015bc5">

### Affected Component

Menu

### Expected Behaviour

Implement a tiny delay to make it possible to move the mouse in a direct line to the sub menu.
https://sapui5.hana.ondemand.com/#/entity/sap.m.Menu/sample/sap.m.sample.Menu would be a good example.

### Isolated Example

https://sap.github.io/ui5-webcomponents/playground/components/Menu/

### Steps to Reproduce

1. In "Menu with Sub-menu items" click "Open Menu"
2. Hover mouse cursor over "Open"
3. In a straight line, move the mouse to "Open from Cloud"

### Priority

None

### UI5 Web Components Version

latest

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by petyabegovska** [comment]
Hi @SAP/ui5-webcomponents-topic-b,

The issue is reproducible, please check with UX this behaviour. 
Note: [sap.m.Menu](https://openui5nightly.hana.ondemand.com/entity/sap.m.Menu) behaves as the reporter expects.

Best regards,
Petya
