### ISSUE TITLE
@ui5/webcomponents-base/dist/sap/base/security/sanitizeHTML Issue with font-weight

### ISSUE THREAD

**Issue by Michael-Yang-01** [SAP/ui5-webcomponents#7080]
### Bug Description

Dear ui5 developer,
We are using the @ui5/webcomponents-base/dist/sap/base/security/sanitizeHTML to sanitize our string in our product and found an issue for this function with style 'font-weight:900'. 
The root cause shoud be the @ui5\webcomponents-base\dist\sap\ui\thirdparty\caja-html-sanitizer.js#L1234 will replace the number string '900' with '' before checking the correct policy for font-weight related cssSchema.
This function works well with non-number style like 'font-weight: bold', 'font-weight: bolder', etc.

### Affected Component

webcomponents-base

### Expected Behaviour

const { default: fnSanitizeHTML } = require('@ui5/webcomponents-base/dist/sap/base/security/sanitizeHTML');
const result = fnSanitizeHTML(`<p><span style="font-weight: 900">test</span> text</p>`);
expect(result).toEqual(`<p><span style="font-weight: 900">test</span> text</p>`);

### Steps to Reproduce

1.
2.
3.
...

### Priority

None

### UI5 Web Components Version

1.10.3

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by nnaydenow** [comment]
Hi @Michael-Yang-01,

We are using sanitezeHTML module from OpenUI5 project. I've opened issue in their project for the problem and you can track the progress there https://github.com/SAP/openui5/issues/3771. Once the issue is fixed from their side we will update to version with their fix and will close this issue.

**Comment by nnaydenow** [comment]
Hi @Michael-Yang-01,

Issue is going to be fixed with #7339

**Comment by nnaydenow** [comment]
Hi @Michael-Yang-01,

The PR is merged and it will be available for consumption with next release.

BR,
Nayden
