### ISSUE TITLE
[ui5-upload-collection]: the delete button is always there even if the mode is not "Delete"

### ISSUE THREAD

**Issue by yaosheng79** [SAP/ui5-webcomponents#7085]
### Bug Description

The delete button is always visible on each ui5-upload-collection-item, even the mode is set to "None"

Please hide the delete button for non-"delete" mode to avoid any misunderstanding.

<img width="948" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/9492648/19e69ab8-17ee-4780-9710-c608eba92bd1">

### Steps to Reproduce

1.
2.
3.
...

### Priority

None

### UI5 Web Components Version

latest

### Browser

Chrome, Edge, Firefox, Safari

### Organization

MDK

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by tsanislavgatev** [comment]
Hello colleagues,

Can you please check this issue?

It's reproducible here https://sap.github.io/ui5-webcomponents/playground/components/UploadCollection/

Best Regards,
Tsanislav

**Comment by dimovpetar** [comment]
Hello @yaosheng79 ,

The delete button is controlled by the `hideDeleteButton` property of the items. The `mode=Delete` setting of UploadCollection is ignored. The `hideDeleteButton` property is not marked as public by mistake. I'm preparing a pull request that will fix this and also make the docs more clear.

Best regards,
Petar

**Comment by yaosheng79** [comment]
I think the `mode=Delete` setting is not really ignored. Because I noticed that if mode is set to `None`, although the delete button is visible, clicking on it will not trigger the `item-delete` event.

that event will be triggered only if node is set to "Delete"

**Comment by dimovpetar** [comment]
Hello @yaosheng79 ,

You are right. This will be fixed with https://github.com/SAP/ui5-webcomponents/pull/7106

Best regards,
Petar
