### ISSUE TITLE
Screen breaks after migrating from Nexus to SAP common repositories

### ISSUE THREAD

**Issue by Bilal3120** [SAP/ui5-webcomponents#7087]
### Bug Description

Issue after migrating NPM UI repositories from Nexus to SAP common repository.

### Affected Component

SAP PRP

### Expected Behaviour

The screen should not break with lit-html error.

### Log Output, Stack Trace or Screenshots

<img width="1792" alt="Screenshot 2023-05-24 at 6 48 53 PM" src="https://github.com/SAP/ui5-webcomponents/assets/93638146/0388deb5-0300-4122-afb0-7fc6b6e5d9f0">

### Priority

Very High

### UI5 Web Components Version

1.13.3

### Browser

Chrome

### Organization

SAP

### Declaration

- [x] I’m not disclosing any internal or sensitive information.

**Comment by ilhan007** [comment]
Hello @Bilal3120 thank you for reporting this to us.

Could you also provide more information, how to reproduce it - sample or link to app + steps that we need to follow.

**Comment by Bilal3120** [comment]
Steps to reproduce:
1. Login to [https://app.sit2.prp-stage-eu.eurekacloud.io/login?application=prp](https://app.sit2.prp-stage-eu.eurekacloud.io/login?application=prp)
2. Click on Business Configurations -> Manage Configuration Profiles
3. Here the application is breaking

**Comment by ilhan007** [comment]
Hello @Bilal3120 , thank you, I am able to see the error, we will continue further analysis.

**Comment by Bilal3120** [comment]
After updating @eureka/ui-managers to version 1.2.7-41, everything is working as expected. So closing the ticket.

Thanks and regards,
Bilal Ahmed Pasha
