### ISSUE TITLE
Progress Indicator - Wrong information Icon

### ISSUE THREAD

**Issue by blaesius** [SAP/ui5-webcomponents#7092]
### Bug Description

For the progress Indicator with Information State icon, the icon looks slightly different as it should be.

### Affected Component

ui5-progress-indicator

### Expected Behaviour

![image](https://github.com/SAP/ui5-webcomponents/assets/6813930/37f49363-2a78-4ddb-b4ad-1bd3563c9ba7)

### Isolated Example

https://sap.github.io/ui5-webcomponents/playground/components/ProgressIndicator/

### Steps to Reproduce

1. Go to section Progress Indicator with Value State
2. Check the last one which has the information icon next to it
3.
...

### Priority

Medium

### UI5 Web Components Version

1.13

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Todor-ads** [comment]
Hello @SAP/ui5-webcomponents-topic-p,
Could you please check this issue? The problem is also reproduced in https://sap.github.io/ui5-webcomponents/playground/components/ProgressIndicator/

Regards,
Todor
