### ISSUE TITLE
Switch - Text switch wrong Visual Design

### ISSUE THREAD

**Issue by blaesius** [SAP/ui5-webcomponents#7094]
### Bug Description

The text switch is not using the correct VD parameters. 
https://sap.github.io/ui5-webcomponents/playground/components/Switch/?sap-ui-theme=sap_horizon&isrtl=false

Please check the corresponding wiki.

### Affected Component

ui5-switch

### Expected Behaviour

![image](https://github.com/SAP/ui5-webcomponents/assets/6813930/f0193c04-c4a2-40d1-8aad-8eb6c9f2c12b)

### Isolated Example

https://sap.github.io/ui5-webcomponents/playground/components/Switch/?sap-ui-theme=sap_horizon&isrtl=false

### Steps to Reproduce

1.
2.
3.
...

### Priority

Medium

### UI5 Web Components Version

1.13

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Todor-ads** [comment]
Hello https://github.com/orgs/SAP/teams/ui5-webcomponents-topic-b ,

Please check the detailed description of the issue provided by the reporter. It can be easily reproduced in : https://sap.github.io/ui5-webcomponents/playground/components/Switch/?sap-ui-theme=sap_horizon&isrtl=false

Could you please look over?

Thank you in advance!

Kind Regards,
Todor
