### ISSUE TITLE
Menu - Focus and Hover Behavior not correct

### ISSUE THREAD

**Issue by blaesius** [SAP/ui5-webcomponents#7097]
### Bug Description

The focus is not right, it shouldn't follow the mouse cursor (only the hover effects should be there while hovering over the menu items). Only the first focusable element should keep the focus line (and the regular background, when it is not hovered).

### Affected Component

ui5-menu

### Expected Behaviour

![image](https://github.com/SAP/ui5-webcomponents/assets/6813930/8295347b-1f3c-4906-84f7-cb990269f9f6)

### Isolated Example

https://sap.github.io/ui5-webcomponents/playground/components/Menu/

### Steps to Reproduce

1.
2.
3.
...

### Priority

Medium

### UI5 Web Components Version

1.13

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Todor-ads** [comment]
Hello https://github.com/orgs/SAP/teams/ui5-webcomponents-topic-b ,

Please check the detailed description of the issue provided by the reporter. It can be easily reproduced in : https://sap.github.io/ui5-webcomponents/playground/components/Menu/

Could you please look over?

Thank you in advance!

Kind Regards,
Todor

**Comment by blaesius** [comment]
Hi @hinzzx,

the design should be as described above (different focus and hover behavior as we have it in all controls). If it is the same in UI5, this just means that both implementations should be corrected.

Kind regards,
Janina
