### ISSUE TITLE
Carousel - Focus missing

### ISSUE THREAD

**Issue by blaesius** [SAP/ui5-webcomponents#7098]
### Bug Description

The focus of the Carousel doesn’t appear when you click on it

### Affected Component

ui5-carousel

### Expected Behaviour

![image](https://github.com/SAP/ui5-webcomponents/assets/6813930/91e88d33-22b2-4ea5-9c82-62df72c34b85)

### Isolated Example

https://sap.github.io/ui5-webcomponents/playground/components/Carousel/

### Steps to Reproduce

1.
2.
3.
...

### Priority

Medium

### UI5 Web Components Version

1.13

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by PetyaMarkovaBogdanova** [comment]
Hi team, can you confirm that ui5-carousel should receive focus on click and why it is not visually applying?
Thank you!
Kind regards,
Petya Markova.
(UI5 WC Dispatcher)

**Comment by gmkv** [comment]
This issue is regarding the https://github.com/SAP/ui5-webcomponents/pull/6084 in some components.
Related to https://github.com/SAP/ui5-webcomponents/issues/6762
There is still an ongoing discussion about whether we should keep using focus-visible to draw the focus.
