### ISSUE TITLE
Range Slider - Wrong hover effect

### ISSUE THREAD

**Issue by blaesius** [SAP/ui5-webcomponents#7100]
### Bug Description

The Hover effect is not implemented correctly. The expectation is that when the user hovers on only one of the thumbs, it hovers only the one thumb that it is hovered. The other one stays in its regular state. 

### Affected Component

ui5-range-slider

### Expected Behaviour

![image](https://github.com/SAP/ui5-webcomponents/assets/6813930/531bc0b0-a824-4804-a668-e644a30e82b8)

### Isolated Example

https://sap.github.io/ui5-webcomponents/playground/components/RangeSlider/

### Steps to Reproduce

1.
2.
3.
...

### Priority

Medium

### UI5 Web Components Version

1.13

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by PetyaMarkovaBogdanova** [comment]
Hi team,
can you, please, align the hover effect on a single knob of ui5-range-slider to take effect only on itself when targeted.
Thank you!
Kind regards,
Petya Markova.
(UI5 WC Dispatcher)

**Comment by niyap** [comment]
Hello @blaesius,

Thanks for sharing your findings!

We will handle that enhancement via backlog item: BGSOFUIRILA-3637.

Kind Regards,
Niya
