### ISSUE TITLE
Slider - Slider with Input field missing

### ISSUE THREAD

**Issue by blaesius** [SAP/ui5-webcomponents#7102]
### Bug Description

The slider can use input fields (instead of text fields), (sap.m.Input), that give the user the possibility of inputting precise values.  The value of input fields could be changed. 
•After entering the new value, both handle and input field move together directly at the new position
•On hover, on focus and when being edited the input fields change their visual status to active
•The input field sits on top-center of the handle and it is inseparable from the handle. They always move together

### Affected Component

ui5-slider

### Expected Behaviour

![image](https://github.com/SAP/ui5-webcomponents/assets/6813930/e804305e-f895-4544-aa20-4214afc01aa9)

### Isolated Example

https://sap.github.io/ui5-webcomponents/playground/components/Slider/

### Steps to Reproduce

1.
2.
3.
...

### Priority

Medium

### UI5 Web Components Version

1.13

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by PetyaMarkovaBogdanova** [comment]
Hello @blaesius ,
can you, please, provide a sample of how are you using slider functionality with inputted value?
Thank you!
Best regards,
Petya Markova.
(UI5 WC Dispatcher)

**Comment by petyabegovska** [comment]
Hi @PetyaMarkovaBogdanova,

@blaesius is from SAP Design and I suppose that she is referring to the same use case that we have sample in OpenUI5:
https://openui5nightly.hana.ondemand.com/entity/sap.m.Slider/sample/sap.m.sample.Slider, see sample Slider with input field.
- Setting the property showAdvancedTooltip shows an input field above the handle
- Setting the property inputsAsTooltips enables the user to enter a specific value in the handle's tooltip.

@hristop, is there an equivalent to this behaviour in the Web Components Slider? 

Best regards,
Petya

**Comment by petyabegovska** [comment]
Hi @blaesius,

Update: This functionality is not implemented in the ui5-slider yet, so I will forward it to the responsible team as a feature request, not a bug.

Best regards,
Petya

**Comment by hristop** [comment]
Internal BLI was created: BGSOFUIRILA-3690

**Comment by hristop** [comment]
Hi all,

You can checkout the new feature in the documentation page here: https://sap.github.io/ui5-webcomponents/nightly/components/Slider/#editabletooltip
Closed with: #9547 

Best Regards,
Hristo
