### ISSUE TITLE
Table - "No Data Text" row not spanning full width

### ISSUE THREAD

**Issue by kaistephanrichter** [SAP/ui5-webcomponents#7105]
### Bug Description

The no data text row content are is not spanning the full width of the table while the border does. This results in the row being inset and not aligned with the right border of the table. The following example was taken form the respective example in the documentation page.

![image](https://github.com/SAP/ui5-webcomponents/assets/46745939/dbd65a74-f985-4ace-a727-91450f4a7619)

### Affected Component

ui5-table

### Expected Behaviour

The row content should be stretched to the right border of the table.

### Isolated Example

https://sap.github.io/ui5-webcomponents/playground/components/Table/

### Steps to Reproduce

Just go to the documentation page and review the "no data text" example.

### Priority

None

### UI5 Web Components Version

Latest

### Browser

Chrome, Safari

### Operating System

Mac OS

### Organization

SAP Design

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by petyabegovska** [comment]
Hi @SAP/ui5-webcomponents-topic-rl,

The issue is reproducible in the playground sample: Table with No Data.

Best regards,
Petya

**Comment by Todor-ads** [comment]
Hello https://github.com/orgs/SAP/teams/ui5-webcomponents-topic-rl ,

Please check the detailed description of the issue provided by the reporter. It can be easily reproduced in :
https://sap.github.io/ui5-webcomponents/playground/components/Table/

Could you please look over?

Thank you in advance!

Kind Regards,
Todor
