### ISSUE TITLE
ui5-shellbar: secondary title alignment

### ISSUE THREAD

**Issue by goodefroi** [SAP/ui5-webcomponents#7107]
### Bug Description

The `secondary-title` text of `ui5-shellbar` should be left-aligned but is horizontally centered as of version `1.13.2`.

This can be seen in some of the [official documentation samples](https://sap.github.io/ui5-webcomponents/playground/components/ShellBar/).

### Affected Component

ui5-shellbar

### Expected Behaviour

Secondary title should be left-aligned as e.g. displayed on [experience.sap.com](https://experience.sap.com/fiori-design-web/shell-bar/#exception-flexible-column-layout) or in the [UI5 samples](https://sapui5.hana.ondemand.com/#/entity/sap.f.ShellBar/sample/sap.f.sample.ShellBar).

### Priority

Low

### UI5 Web Components Version

1.13.2+

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Todor-ads** [comment]
Hello https://github.com/orgs/SAP/teams/ui5-webcomponents-topic-p ,

Please check the detailed description of the issue provided by the reporter.

Could you please look over?

Thank you in advance!

Kind Regards,
Todor
