### ISSUE TITLE
[MultiComboBox]: Can't change the token length when clicked on Token.

### ISSUE THREAD

**Issue by roshnijalan97new** [SAP/ui5-webcomponents#7110]
### Bug Description

Steps:
1) Go to https://codesandbox.io/s/compassionate-sammet-qixm38?file=/src/App.js.

2) From the drop-down select the first item.
<img width="373" alt="Screenshot 2023-05-29 at 9 13 10 AM" src="https://github.com/SAP/ui5-webcomponents/assets/120740457/ba8d241e-f017-4734-ba6c-20209ec862db">

3) It will be shortened and selected.
![image](https://github.com/SAP/ui5-webcomponents/assets/120740457/f1c3444c-f20b-4c4e-9ec2-e6d1e5b57fb0)

4) Try clicking on the token.
![image](https://github.com/SAP/ui5-webcomponents/assets/120740457/a0f0ce18-3a84-4e5d-9509-ac26f864c222)

### Affected Component

MultiComboBox

### Expected Behaviour

The text length should be increased to its original size when user click on the shortened text.

### Steps to Reproduce

1.
2.
3.
...

### Priority

Medium

### UI5 Web Components Version

1.9.3

### Browser

Chrome

### Operating System

Mac Os

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by PetyaMarkovaBogdanova** [comment]
Hi @roshnijalan97new ,
I saw in the provided example, that the truncation comes from implemented custom logic.
Can you, please, provide an example with the problem happening with a simple ui5-multi-combobox control usage.
Thank you!

Best regards,
Petya Markova.
(UI5 WC Dispatcher)

**Comment by roshnijalan97new** [comment]
Hi @PetyaMarkovaBogdanova, I want to implement functionality such that on clicking the truncated selected item, It should expand and show the entire content.

**Comment by roshnijalan97new** [comment]
The string "Item 1 is here. Please click on it to expand" is truncated to "Item ...".
<img width="398" alt="Screenshot 2023-05-29 at 9 14 47 AM" src="https://github.com/SAP/ui5-webcomponents/assets/120740457/d2d5371b-9dfc-4d12-b8c6-aa995662c79c">
on clicking the truncated token it should expand back to its original size and show details as "Item 1 is here. Please click on it to expand"

**Comment by PetyaMarkovaBogdanova** [comment]
Hi team,
can you, please, consult about if the desired functionality could be achieved with MultiComboBox.
Thank you!
Best regards,
Petya Markova.
(UI5 WC Dispatcher)

**Comment by hristop** [comment]
Hi @roshnijalan97new ,

We are currently working on this concept (#5229). 
What I noticed in your sample is that you are programatically setting the text of the first multi combo box item to be substring of the longer string. This case will not be supported with our implementation - you should either leave the truncation to the component or do everything (truncation / expansion) yourself. 

Best Regards,
Hristo
