### ISSUE TITLE
Page: Bad performance - content flicker

### ISSUE THREAD

**Issue by C3ntraX** [SAP/ui5-webcomponents#7120]
### Describe the bug

The content-padding of the page component is really bad. 
If you are using multiple pages and switch betweeen them, the content is flickering extremly.

See the gif and the codesandbox.

Im using the `Table` component but its also with all other components.

### Isolated Example

https://codesandbox.io/p/sandbox/page-bad-performance-e1810k?file=%2Fsrc%2FApp.tsx%3A42%2C16

### Reproduction steps

1.
2.
3.
...

### Screenshots or Videos

The gif wasnt able to capture every flicker. Use the codesandbox instead but the flicker is for every page change.

![GIF 30 05 2023 14-09-58](https://github.com/SAP/ui5-webcomponents-react/assets/44802503/92311da6-71c4-4ebc-bac8-c71ee7551d6c)

### UI5 Web Components for React Version

1.15.1

### UI5 Web Components Version

1.13.0

### Browser

Chrome

### Operating System

Windows

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by C3ntraX** [comment]
Other examples. Every pages is flickering (Not all visible in GIF)

![GIF 30 05 2023 15-06-56](https://github.com/SAP/ui5-webcomponents/assets/44802503/90679367-8710-4bab-830e-180f8334819d)

@Lukas742 
As soon as Im using a native React `Page` implementation there is no flickering.

**Comment by C3ntraX** [comment]
Here is a `Table` header withouth the Page component:

![GIF 30 05 2023 15-12-59](https://github.com/SAP/ui5-webcomponents/assets/44802503/d9f53b7f-20d1-4ec2-bcb1-bca30deeefc2)

**Comment by PetyaMarkovaBogdanova** [comment]
Hi team,
can you, please, check where this flickering is coming from?
It can be reproduce with replacing the Page with an ordinary div element (https://codesandbox.io/p/sandbox/page-bad-performance-forked-srsllj?file=%2Fsrc%2FApp.tsx%3A41%2C9)
and by replacing the ui5-table with simple table. (https://codesandbox.io/p/sandbox/page-bad-performance-forked-n2swhb?file=%2Fsrc%2FApp.tsx%3A33%2C41)

Kind regards,
Petya Markova.
(UI5 WC Dispatcher)

**Comment by MapTo0** [comment]
Hey @C3ntraX 

Could you please check if the issue is resolved with version 2.0?

Best Regards!
Martin
