### ISSUE TITLE
[Feature Request]: SF_ACC ui5-shellbar Expanded state of Search Field should not be read if user did not take action to expand content

### ISSUE THREAD

**Issue by bonniegso** [SAP/ui5-webcomponents#7123]
### Feature Request Description

This is the original feature request #5818 provides the property showSearchField for consumption. However, the original accessibility issue is still not resolved since "expanded" is still read when the search button is focused so we are opening this new feature request to address this issue.

The issue that needs to be fixed is that "Search button expanded" is read upon focus of the search button in the shell bar. When the search input is visible by default, this causes confusion because the user did not take any action to expand the search input.

### Proposed Solution

Ideally, the solution would be to implement the search button as a toggle button https://sap.github.io/ui5-webcomponents/playground/components/ToggleButton/ so that "pressed" and "unpressed" states are read instead of "expanded" and "collapsed" since it is usually expected that expanded content has some sort of text or menu.

### Proposed Alternatives

If the above is not possible, then a way to customize or set the aria-expanded value or customize the aria label for the search button would also suffice.

### Organization

SAP SuccessFactors

### Additional Context

Steps to reproduction:

Go to https://stackblitz.com/edit/js-6v9yvk?file=index.js,index.html.
Turn on JAWS screen reader
Navigate to the search button on the first example of the shell bar using your keyboard
Observe that "Search button expanded" is read

### Priority

Medium

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by PetyaMarkovaBogdanova** [comment]
Dear team,
can you, please, evaluate this feature request regarding ui5-shellbar?
Thank you!
Kind regards,
Petya Markova.
(UI5 WC Dispatcher)

**Comment by yanaminkova** [comment]
Internal Reference: BGSOFUIPIRIN-6573
