### ISSUE TITLE
[MultiComboBox] Add selectionFinish event

### ISSUE THREAD

**Issue by vbersch** [SAP/ui5-webcomponents#713]
**Describe the solution you'd like**
So far the MultiComboBox has the selectionChange event, which fires as soon as you select an item.
It would be great to have an event which only fires after the selection is complete (the Modal containing the selectionItems loses focus)

The event should contain all items that were added/removed as well as all selected items.

**Comment by MapTo0** [comment]
Hey @vbersch 

`SelectionFinish` sounds strange to me as the selection is actually never finished for the end user - you can always change it no matter if the Popover is open or no.

in OpenUI5 we have similar functionality - an event fired after the picker (popover) is closed, would this be enough for you? `afterPickerClose` or something like that.

**Comment by vbersch** [comment]
Hi Martin,

Yes, thats exactly the event I meant. I don´t have preferences on how to call it.
It´s called `selectionFinish` in ui5 though.
