### ISSUE TITLE
[framework]: add linting to *.stories.ts files

### ISSUE THREAD

**Issue by gmkv** [SAP/ui5-webcomponents#7135]
### Bug Description

Enable linting in all of the storybook stories

### Priority

Medium

### UI5 Web Components Version

latest

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by gmkv** [comment]
Hi @SAP/ui5-webcomponents-topic-core 
Would you take a look at this request?

**Comment by ilhan007** [comment]
Hello colleagues @SAP/ui5-webcomponents-topic-p this could be also topic in your domain

**Comment by dobrinyonkov** [comment]
New playground is live.
