### ISSUE TITLE
[SegmentedButton]: Visual design is broken

### ISSUE THREAD

**Issue by petyabegovska** [SAP/ui5-webcomponents#7141]
### Bug Description

Hi @SAP/ui5-webcomponents-topic-b, 
 
SegmentedButton doensn't follow the visual design and looks really bad- please refer to the VD wiki page.
Left and right borders are cut, but inner borders are shown.

<img width="631" alt="Screenshot 2023-06-02 at 12 38 14" src="https://github.com/SAP/ui5-webcomponents/assets/8136099/618f3279-fd30-4170-b3c4-a168e53b0709">

Morning and evening horizon themes are impacted.

### Affected Component

ui5-segmented-button

### Expected Behaviour

Segmented Button looks as per VD.

### Steps to Reproduce

Open playground sample: https://sap.github.io/ui5-webcomponents/main/playground/components/SegmentedButton/

### Priority

Medium

### UI5 Web Components Version

Latest playground + main

### Browser

Chrome

### Operating System

MacOS Ventura

### Organization

SAP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by petyabegovska** [comment]
Update: SplitButton is also broken: https://sap.github.io/ui5-webcomponents/main/playground/components/SplitButton/

**Comment by nnaydenow** [comment]
Hi @petyabegovska,

Seems that the --sapButtonBorderColor parameter value is changed with https://github.com/SAP/theming-base-content/commit/3757ee0517109796d066ecc6c19b35113f4d07da and it's not regression from our side.

**Comment by petyabegovska** [comment]
@sapButtonBorderColor parameter has been reverted and should come with the next theming-content 11.4.3 or 11.5.0.
