### ISSUE TITLE
[popover]: arrow is not centered when close to the border/with large text

### ISSUE THREAD

**Issue by rvsia** [SAP/ui5-webcomponents#7152]
### Bug Description

The arrow of popover is not centered to the middle of target when it's close to the border of the screen or when there is a larger content

1) close to the border

![Snímek obrazovky 2023-06-06 v 9 05 33](https://github.com/SAP/ui5-webcomponents/assets/32869456/fd4c3887-36cb-441d-827a-20f4db4c3f73)

2) large content

![Snímek obrazovky 2023-06-06 v 9 08 03](https://github.com/SAP/ui5-webcomponents/assets/32869456/e3535060-77fe-46b3-854e-53bba5a46a38)

As we use only a small target for the popover, it looks really bad in our product

![Snímek obrazovky 2023-06-06 v 9 20 27](https://github.com/SAP/ui5-webcomponents/assets/32869456/ccde6f7e-b8cb-461b-97c7-206fb8cc6d2e)

### Affected Component

popover

### Expected Behaviour

Popover arrow is centered to the 

### Isolated Example

https://sap.github.io/ui5-webcomponents-react/?path=/docs/modals-popovers-popover--docs

### Steps to Reproduce

1. open webcompoments react popover page
2. modify content of the popover using inspect 

### Log Output, Stack Trace or Screenshots

see above

### Priority

Medium

### UI5 Web Components Version

^1.13.2

### Browser

Edge

### Operating System

MacOS

### Organization

SAP Signavio

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by elenastoyanovaa** [comment]
Hello @SAP/ui5-webcomponents-topic-rd ,

When the opener target is small and the popover does not have enough space the calculation of the arrow result in a unpleasant visualisation. 

Steps to reproduce:
- Open the playground sample of the popover
- Change the button text to something small
- Change the placement type of the popover to bottom
<img width="272" alt="Screenshot 2023-06-07 at 21 48 47" src="https://github.com/SAP/ui5-webcomponents/assets/11913394/6bb1a4e4-5528-4d68-9a97-b2e395a21272">

Can you check?

Kind Regards,
Elena

**Comment by gmkv** [comment]
Reproducible sample: https://codesandbox.io/s/ui5-webcomponents-forked-zsq4hr?file=/index.html
