### ISSUE TITLE
[ui5-shellbar]: primary title truncated

### ISSUE THREAD

**Issue by JarrettChan** [SAP/ui5-webcomponents#7153]
### Bug Description

#6982 set left container shrink factor and grow factor to 1
When there is no co-pilot the above change allows primary title to truncate too much.
Where before there was only truncation for long titles, now the whole title can be hidden at certain widths and shellbarItems content.

### Affected Component

ui5-shellbar

### Expected Behaviour

Primary title should not be unnecessarily truncated at smaller widths without co-pilot

### Steps to Reproduce

1. https://sap.github.io/ui5-webcomponents/playground/components/ShellBar/
2. remove `show-co-pilot` attribute from ui5-shellbar example
3. shrink window width

### Log Output, Stack Trace or Screenshots

![Screenshot 2023-06-06 at 12 51 17 PM](https://github.com/SAP/ui5-webcomponents/assets/4755512/42740bec-5df7-41c0-a8bc-56abeb72a560)
![Screenshot 2023-06-06 at 12 54 48 PM](https://github.com/SAP/ui5-webcomponents/assets/4755512/60991516-eaa6-4d7d-9b17-3ed858f22c54)

### Priority

None

### UI5 Web Components Version

1.13.3

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by elenastoyanovaa** [comment]
Hello @SAP/ui5-webcomponents-topic-p ,

Even though there is enough space sometimes the title of the shellbar truncates.

Steps to reproduce:
1. Open the playground sample of the shellbar
2. Remove the show-co-pilot attribute
3. Shrink the window
4. Observe that the title gets truncated even though space is present
<img width="740" alt="Screenshot 2023-06-08 at 8 04 37" src="https://github.com/SAP/ui5-webcomponents/assets/11913394/6e5d2711-1a71-4fd9-bde7-6aac76777861">

Could you please check it out?

Kind Regards,
Elena
Github Dispatcher
