### ISSUE TITLE
[SideNavigationItem]: selected item can be clicked on, but no pointer shown

### ISSUE THREAD

**Issue by rvsia** [SAP/ui5-webcomponents#7156]
### Bug Description

When a side navigation item is selected, there is no longer any `pointer` cursor, but it is still possible to click on the item

![image](https://github.com/SAP/ui5-webcomponents/assets/32869456/ce0f1635-39f4-4f5e-add7-5c9a3922bd71)

### Affected Component

SideNavigationItem

### Expected Behaviour

Selected item still should show `cursor` pointer. some `disabled` property should hide the cursor and disable onClick action.

![image](https://github.com/SAP/ui5-webcomponents/assets/32869456/5991ae5d-d924-48ca-b4a9-495cf0f05809)

### Isolated Example

https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-sidenavigation--docs#example

### Steps to Reproduce

1. Open example
2. You can repeatedly click on selected item

### Priority

Medium

### UI5 Web Components Version

^1.13.2

### Browser

Edge

### Operating System

MacOs

### Additional Context

In our application, we have nested navigation, so users can use the current selected item to go back to the root page.

### Organization

SAP Signavio

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by gmkv** [comment]
Hi @rvsia 
I noticed you mentioned that you expect there to be a `disabled` property which can turn off the cursor and the onClick firing.
Would you please open a separate feature request for this if you need to disable these items?
You can do so by [following this link.](https://github.com/SAP/ui5-webcomponents/issues/new?assignees=&labels=&projects=&template=feature_request.yml&title=%5BFeature+Request%5D%3A)

**Comment by rvsia** [comment]
@gmkv No, we do not need this. It's just a suggestion how to properly introduce no-pointer state. 😊
