### ISSUE TITLE
Charting Webcomponents

### ISSUE THREAD

**Issue by svenruppert** [SAP/ui5-webcomponents#716]
For apps, charting is a nice add on. There are free charts available,
but It would be perfect if the charts would follow the same UI Guidelines as all other components. 

Cheers Sven

**Comment by MapTo0** [comment]
Hello @svenruppert,

We are currently focused on shaping APIs of basic components and improving our base package.

If you need charts and you are using React you can check out what our colleagues are building https://github.com/SAP/ui5-webcomponents-react

Anyway, I believe in the future we might provide such a library but it will probably not be part of the main package.

**Comment by svenruppert** [comment]
@MapTo0 thx for feedback.

**Comment by alex-zhang** [comment]
@MapTo0  hi,  ui5-webcomponents-react  is company-level library? and can we use it in company product?

**Comment by ilhan007** [comment]
Hello @alex-zhang yes it's developed at SAP and the responsible team works closely with us.

Hello @svenruppert 
unfortunately, charts are not part of our Roadmap we don't envision charts in the foreseeable future.
