### ISSUE TITLE
[ui5-side-navigation]: Extra padding in release 1.14.0

### ISSUE THREAD

**Issue by kozubikmichal** [SAP/ui5-webcomponents#7160]
### Bug Description

With new version of UI5 Web Components (1.14.0) there is extra padding on the left side of the Side Navigation.
This change
- Adds more whitespace into the page with no use
- Leads to incorrect alignment with the Collapse/Expand switch in Shell Bar
- Leaves less space for the navigation items texts

### Affected Component

Side Navigation

### Expected Behaviour

Padding is the same as in previous version (or at least configurable)

### Isolated Example

https://sap.github.io/ui5-webcomponents/playground/components/SideNavigation/

### Steps to Reproduce

1. Open the page
2. See the Side Navigation in expanded state
3. Compare with previous version

### Log Output, Stack Trace or Screenshots

<img width="275" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/26189327/3287c0ad-bb7c-4221-b25f-ddb5726b3e2f">

### Priority

None

### UI5 Web Components Version

1.14.0

### Browser

Chrome

### Operating System

MacOS

### Organization

SAP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by elenastoyanovaa** [comment]
Hello @SAP/ui5-webcomponents-topic-rd ,

There is an extra space at the start of each side navigation item. It is not a padding, but a division element coming from the ui5-tree-item reserved perhaps for the arrow down icon of the tree item (ui5-li-tree-toggle-box). It makes sense to be present in the tree item as it visually aligns items with and without sub trees. But is it expected to be there for the side navigation items as it takes a certain amount of space?

Kind Regards,
Elena
Github Dispatcher
