### ISSUE TITLE
[Select | Storybook]: Select popover stays detached from its input when you scroll the page

### ISSUE THREAD

**Issue by petyabegovska** [SAP/ui5-webcomponents#7173]
### Bug Description

Hello colleagues,

There is an issue with the ui5-select component when the popover is opened and you start scrolling the page.
The popover is slower than the scroll and stays detached from its input for a moment that is clearly visible.

### Affected Component

ui5-select

### Expected Behaviour

When the user scroll the page, the input and popover parts are not detached. See https://sap.github.io/ui5-webcomponents/playground/components/Select/ 

### Isolated Example

https://sap.github.io/ui5-webcomponents/main/_playground/?path=/docs/main-select--docs

### Steps to Reproduce

1. Open ui5-select Storybook sample (docs section as scroll should be available)
2. Open the ui5-select popover
3. Start scrolling the page slowly
4. See that the popover stays detached for a visible moment of time
...

### Log Output, Stack Trace or Screenshots

https://github.com/SAP/ui5-webcomponents/assets/8136099/9f149561-8c74-4201-a8bd-d133443ca1f3

### Priority

Medium

### UI5 Web Components Version

main

### Browser

Chrome, Safari

### Operating System

MacOS

### Additional Context

The issue is not reproducible in the Playground, but only in Storybook.

### Organization

SAP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by LidiyaGeorgieva** [comment]
Hello @petyabegovska 

There is a open internal backlog item for this. It is under number 2993.

Best Regards,
Lidiya
