### ISSUE TITLE
[Feature Request]: OpenUI5Support synchronize z-index

### ISSUE THREAD

**Issue by JarrettChan** [SAP/ui5-webcomponents#7175]
### Feature Request Description

We have a consistency issue with PopupUtils::getNextZIndex with using OpenUI5Support among multiple ui5wc cores.
There are some modules with OpenUI5Support enabled and others that have not been updated to use it, and when they separately open popovers/dialogs on the page they are not synchronized.

### Proposed Solution

Enabling OpenUI5Support can set a flag into shared resources to indicate to all ui5wc cores to use openui5 to get z-index.

### Proposed Alternatives

Having all portable components optionally include OpenUI5Support.

### Priority

Medium

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ilhan007** [comment]
Hello  @JarrettChan we have merge a small change on the OpenUI5Support usage within the framework to make it completely safe when enabled even if OpenUI5 is not actually loaded. The fix will be available with 1.15 coming in few days. However, I doubt that the case that is fixed is something that you rely one. If you currently don't set a theme root via the `setThemeRoot` API, then OpenUI5Support is perfectly fine to be imported in all previous versions as well.
