### ISSUE TITLE
[OpenUi5Support]: Depends on not released Theming API

### ISSUE THREAD

**Issue by pzamzow** [SAP/ui5-webcomponents#7199]
### Bug Description

With the changes introduced by https://github.com/SAP/ui5-webcomponents/pull/7174 the OpenUi5Support depends on the Theming API. This API is not yet released and not available in the latest released version as of now (1.115.0). 

At the moment `@ui5/webcomponents-base` (>=1.14.2) requires a nightly build of OpenUI5 (>1.115.0).

### Affected Component

OpenUi5Support

### Expected Behaviour

Such change should not be part of a new patch version. Either it is implemented in a backward compatible way or users should be made aware of this in the release notes.

### Steps to Reproduce

Use OpenUi5Support (>=1.14.2) with a UI5 version (<=1.115.0)

### Log Output, Stack Trace or Screenshots

GET https://sapui5.hana.ondemand.com/1.108.18/resources/sap/ui/core/Theming.js 404

### Priority

High

### UI5 Web Components Version

1.14.2

### Browser

Chrome

### Operating System

MacOS

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by gmkv** [comment]
Hi @SAP/ui5-webcomponents-topic-core 
Would you take a look at this issue regarding the OpenUI5 dependency of this library?

**Comment by ilhan007** [comment]
Hello @pzamzow 

thank you for reporting we prepared a fix, and immediately after merging it we are going to release a patch - 1.14.3 that you can consume.

One thing that I want to ask you for is if you could share the name of your project, or the name of your organisation just for our knowledge. It seem you are using OpenUI5 and UI5 Web Components together in a mixed use-case and it's good to know the project/org name.

**Comment by ilhan007** [comment]
Released with 1.14.3.
