### ISSUE TITLE
[F6Navigation | UI5WC]: Fast Navigation does not work as expected in the Learning Home Page

### ISSUE THREAD

**Issue by rama1990br** [SAP/ui5-webcomponents#7201]
### Bug Description

Fast navigation via F6 is not working as expected in Learning Home Page.

As seen in the screenshot below, `data-sap-ui-fastnavgroup` attribute has been added to four divs which represent four different sections on the page. However, pressing F6 skips the first two sections and only focuses on the card in the third section, and pressing F6 again results in skipping of the fourth section.

<img width="1679" alt="Screenshot 2023-06-14 at 10 57 42 PM" src="https://github.com/SAP/ui5-webcomponents/assets/32254036/615407c0-8c7f-48a2-af54-81d541de9fbc">

### Expected Behaviour

The expectation is that each of the four sections should receive focus on pressing F6 successively, since the implementation of all the four sections is similar.

### Steps to Reproduce

1. Log in to qacand (credentials provided in #sap-tech-ui5-wc-sfsf channel)
2. Click on the module picker and click on Learning
3. After being redirected to the learning home page, toggle the switch for "New Learning Experience" on the top-right. 
4. Execute fast navigation by pressing F6 successively and observe that the focus goes to the logo, then the banner carousel and then to "Recommended by Others" section after skipping "Required Assignments" and "Latest Bookmarks" sections. Pressing F6 again leads the focus to go back to the logo after skipping "label.AIRecommendations" section.

Link to the code where F6 is implemented for this page: https://github.wdf.sap.corp/xweb/homepage4/blob/master/src/components/HomepageSection/HomepageSection.js#L183

I wasn't able to reproduce this in the code sandbox since a lot of custom components are also being used in this page.

### Log Output, Stack Trace or Screenshots

<img width="1679" alt="Screenshot 2023-06-14 at 10 57 42 PM" src="https://github.com/SAP/ui5-webcomponents/assets/32254036/971fa9ac-22b3-4c7c-9e47-58d60d515ccd">

### Priority

None

### UI5 Web Components Version

1.9.3

### Browser

Chrome, Edge, Firefox, Safari

### Organization

SAP SuccessFactors

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by nnaydenow** [comment]
As we discussed internally the F6 navigation was reworked with version 1.11.0 and the issue seems to not be reproducible there. I'm closing the issue.
