### ISSUE TITLE
DynamicSideContent: Improve Storybook samples

### ISSUE THREAD

**Issue by DMihaylova** [SAP/ui5-webcomponents#7209]
Currently in Storybook there are two samples where DynamicSideContent has:
- main content and side content below
- side content and main content below
However these samples don't show the main advantage of the control which is that the main and side content could be placed right next to each other - f.e. the main on the left and side on the right and the opposite.
There is a property that maybe controls that - sideContentFallDown.

**Comment by dobrinyonkov** [comment]
Hello @SAP/ui5-webcomponents-topic-b, a fix to this problem will be merged with #7183. You can close this incident.
