### ISSUE TITLE
[Feature Request]: update @ui5/webcomponents-icons to use latest 5.05 & v4.17 icons

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents#7210]
### Feature Request Description

New icons versions have been released on 14.06.2023 and as usual we have to update to get the latest icons updates + new icons that are introduced:
- xe30c: time-off 
- xe30d: add-calendar
- xe30e: currency
- xe2a0: bell-2 (filled bell)
- xe2a1: accessibility
- xe2a2: high-priority

### Proposed Solution

Generate new svgs based on the newest fonts and integrate them into the  @ui5/webcomponents-icons package

### Organization

SFSF, UI5

### Priority

Medium

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by gmkv** [comment]
@ilhan007 Is there an article with the icon update process somewhere?

**Comment by ilhan007** [comment]
yes - https://github.wdf.sap.corp/ui5-webcomponents/woff-to-svg
