### ISSUE TITLE
[UI5 Shellbar | localization ]: Overflow shellbar popover items not translated

### ISSUE THREAD

**Issue by lormanlau** [SAP/ui5-webcomponents#7211]
### Bug Description

The search string is raw here:
https://github.com/SAP/ui5-webcomponents/blob/820a5a86974df2bafdfab7b64e762eee819bd4ca/packages/fiori/src/ShellBar.ts#L990
https://github.com/SAP/ui5-webcomponents/blob/820a5a86974df2bafdfab7b64e762eee819bd4ca/packages/fiori/src/ShellBarPopover.hbs#L28

Title is translated:
https://github.com/SAP/ui5-webcomponents/blob/820a5a86974df2bafdfab7b64e762eee819bd4ca/packages/fiori/src/ShellBar.ts#L1293

### Affected Component

Shell Bar

### Expected Behaviour

The default shellbar items in the overflow popover is expected to have translated text.

### Isolated Example

https://codesandbox.io/s/ui5-webcomponents-forked-shellbar-hpbelx

### Steps to Reproduce

1. Hover over the default shell bar item and observe the Search button title is translated
2. resize the browser window so that the overflow of the shellbar menu can appear
3. Observe that the Search and Notifications menu item text is not translated

### Log Output, Stack Trace or Screenshots

![Screenshot 2023-06-15 at 2 42 29 PM](https://github.com/SAP/ui5-webcomponents/assets/12117112/6b9311bc-f8d7-432e-a8ba-d9c29d0fd78f)
![Screenshot 2023-06-15 at 2 42 43 PM](https://github.com/SAP/ui5-webcomponents/assets/12117112/239d70ca-7445-46b1-81d6-6cabc1bed303)
![Screenshot 2023-06-15 at 2 42 51 PM](https://github.com/SAP/ui5-webcomponents/assets/12117112/7acf3537-9d80-465f-a908-2b385152d17c)

### Priority

None

### UI5 Web Components Version

1.11.0+

### Browser

Chrome

### Operating System

MacOS

### Organization

SAP SuccessFactors

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by gmkv** [comment]
Hi @SAP/ui5-webcomponents-topic-p
There are some items in the Shellbar that are not translated.
1. Open https://codesandbox.io/s/ui5-webcomponents-forked-shellbar-9fg3y5
2. Open the overflow.
3. The language is set to German, but the Search and Notifications items are not translated.
Would you have a look?
