### ISSUE TITLE
[ui5-input]: the width of InputBox and the SuggestionBox is not the same

### ISSUE THREAD

**Issue by yzy415** [SAP/ui5-webcomponents#7213]
### Bug Description

The width of InputBox and the SuggestionBox is not the same.  
It disobeys the guideline of the Input Field.
You can check the internal fiori-design-web guideline for the requirement.

### Affected Component

ui5-input

### Expected Behaviour

By default, the width of the suggestion box is the same as the width of the input field.

### Isolated Example

https://sap.github.io/ui5-webcomponents/playground/components/Input/

### Steps to Reproduce

1. go to https://sap.github.io/ui5-webcomponents/playground/components/Input/
2. type something into the box of "Input With Suggestions"
3. you'll find that the suggestion box width is a little bit larger than the one of the input box. (it'll be more obvious when size of input box is smaller)
<img width="264" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/53516646/77db5594-e6fe-4e61-8815-43496322b21f">

### Priority

Very High

### UI5 Web Components Version

1.14.3

### Browser

Chrome

### Additional Context

I'm from SF

### Organization

SF

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by hristop** [comment]
Hi @yzy415 ,

As per design, if there is not enough width to show the full text of the suggestions, the list will expand so that there is no truncation in the suggestion items. 

Best Regards,
Hristo

**Comment by yzy415** [comment]
> Hi @yzy415 ,
> 
> As per design, if there is not enough width to show the full text of the suggestions, the list will expand so that there is no truncation in the suggestion items.
> 
> Best Regards, Hristo

Hi Hristop,  should the design also follow the guideline? and is that ok to share the design in slack or teams to let my team know?

**Comment by petyabegovska** [comment]
Hi @yzy415,

I shared the design in Slack. By design the min size should always follow the Input field.

Best regard,
Petya

**Comment by hristop** [comment]
Hi @yzy415 , @petyabegovska ,

The min width of the suggestions is something that was discussed with VD / UX design and currently works as expected. 

There are two rules that concern the min width of the input's suggestions: 
* The min width of the suggestions will match the input's width in case the max suggestion text does not exceed that width
* The min width of the suggestions will extend beyond the width of the input in case the above rule is not met

We have prepared a BLI via which we will handle this case: BGSOFUIRILA-3645

Best Regards,
Hristo
