### ISSUE TITLE
[Checkbox]: double clicking checkbox selects text in other element sometimes

### ISSUE THREAD

**Issue by QiuranHu** [SAP/ui5-webcomponents#7236]
### Bug Description

Double clicking checkbox selects text in other element sometimes.

To reproduce, go to the demo page for checkbox (https://sap.github.io/ui5-webcomponents/playground/components/CheckBox/).

Go to "CheckBox with indeterminate" section, and double click "French" checkbox. Check if "<" in code section is selected.

<img width="281" alt="Screenshot 2023-06-21 at 11 08 43" src="https://github.com/SAP/ui5-webcomponents/assets/55808904/4695db46-de0e-4b29-a38d-7c59eb3ba366">

### Affected Component

Checkbox

### Priority

Low

### UI5 Web Components Version

1.13.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by unazko** [comment]
Hello @SAP/ui5-webcomponents-topic-p,
```

_onmousedown(e: MouseEvent) {
    e.preventDefault();
}
```
The issue is reproducible as described and could the upper code fixes it.

Best regards,
Boyan
