### ISSUE TITLE
[Input]: Dispatching input event does not trigger onInput or onChange

### ISSUE THREAD

**Issue by C3ntraX** [SAP/ui5-webcomponents#7241]
### Bug Description

I want to trigger an input event via dispatchEvent to set new input data (scanner input).

I simulate the same behavior seen with normal HTML input and it works, but not here.

To simulate the input, I first focus on the event. This way I can wait for a scanner input via prefixes and postfixes (like ? and !).
If these pre and postfixes are triggered via onBeforeInput then I cancel the event.
When the scanner is done inputting, I remove the pre- and postfixes and dispatch an onInput event.

This is how the UI5Input element fires the onInput event. The input is still focused (which shouldn't make a difference).
Now the problem: when you press enter or focus out, the onChange event doesn't fire, which breaks my app since I only validate onChange (in terms of performance).

The onChange does even not fire if you focus the field again and focus out.
The onInput event also does not fire.

For information: In React is the onBlur event equvalent to the onChange event in ui5 (Because of the focusout)

### Affected Component

Input

### Expected Behaviour

onChange event should trigger when you dispatch an onInput event and focus out.

In version 1.8.0 is was working like a charm, but not now anymore.

### Isolated Example

https://codesandbox.io/p/sandbox/sharp-heyrovsky-yc6l9h?file=%2Fsrc%2FApp.tsx%3A15%2C5

### Steps to Reproduce

1. Open the logs
2. See that the onInput event was fired
3. Now focus out of the field
4. See that no onChange event will fire
5. Focus in and out and nothing happens
6. Compare this with the native input and see the differences with focus in/out and when events are fired

### Log Output, Stack Trace or Screenshots

Native input:
First 3 lines if the browser loads an you tab out. The others works when you focus in and out
![image](https://github.com/SAP/ui5-webcomponents/assets/44802503/6d023cb2-67dd-4e81-bb3c-55ff87585727)

UI5 Input:
![image](https://github.com/SAP/ui5-webcomponents/assets/44802503/ba8899ec-bf84-4b5f-86d5-1209b7032c04)

No onBlur/onChange happens on focus out

### Priority

None

### UI5 Web Components Version

1.14.0

### Browser

Chrome

### Operating System

Windows

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by C3ntraX** [comment]
The goal is to simulate the same behaviour with dispatchEvent

Im facing the issue, when Im typing something in the input, the onInput triggers, then I press tab or enter and the onChange event triggers.

If you focus an input and then dispatch an input event, I would expect, that the onChange event will trigger, but that is not the case. This causes an issue in my application, because if I manually press an key or dispatch that event for it, it should result in the same result.

**Comment by unazko** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,


Could you have a look and advice how to simulate a change interaction programatically.

Best regards,
Boyan

**Comment by C3ntraX** [comment]
Hello @unazko,

here is a simplified example:

https://codesandbox.io/p/sandbox/nifty-lovelace-qpq4wj?file=%2Fsrc%2FApp.tsx%3A74%2C16

You see: 

1. First input: I type in the first input, this will trigger all event (onInput, onChange).
2. Second input: I sumulate keystrokes with a scanner `?123!` => this will input `123`. Then I dispatch the same event again (beforeInput) but I have no chance to trigger your custom events. I even dispatched the event on the root input but this don't worked. In version 1.8 I could trigger all events, what changed? How I can trigger the same events like in the first input? I think you blocked something I don't know about, its maybe a bug or I did something wrong.

**Comment by C3ntraX** [comment]
Okay I further investigated in this issue. It seems that only the exact events I dispatch will trigger. If I dispatch `input` then the input will trigger.

The problem is, the entire eventbubbling in canceled. No bubbling. I think because of this the `input` does not trigger (but it should (after `beforeInput`)? 
But you also do not check if the variable changed in the input when I press tab or focus out. The native `change` would trigger on each keystroke (which is overwritten and is different in your library) but your `change` does not trigger. Your change is comparable to the `blur` event (focus out).

But the bigger problem is, you overwrite the onInput and onChange events for the native input which makes it even worse, I have no change to react to the normal event bubbling behaviour of native elements.

The normal behaviour of the bubbling is:

`beforeInput`  => ? => `input` => ? => `change` => ?  => `blur`

Can you check, why the `change` event does not fire when I dispatch `input`?
Can you check, why the `beforeInput` event does not bubble to the `input` event`?

Can you check if there is a way to listen for events in the native input? Maybe rename them? (Lower prio, due to the bad API access in react)

**Comment by ndeshev** [comment]
Hello @C3ntraX,

I'm not sure what is the issue here, the `ui5-input` behaves as a native input. 

If you dispatch an input event of a vanilla input element (without React and no ui5-webcomponents libraries) and focus out of it won't fire change. 
Moreover, the `ui5-input ` component listens for both `input `and `change `events and  always reacts to them by default. 

If I did not understand the described issue correctly reopen the ticket with a code sample with isolated ui5-webcomponents input without react and its equivalent case with native input element.

**Comment by C3ntraX** [comment]
Why you are closing the issue? Its not resolved .... 👎 

> Moreover, the ui5-input component listens for both input and change events and always reacts to them by default by dispatching their UI5 equivalents - ui5-input and ui5-change

Your `change` is not equivalent with the native `change` .... they are really different, because your `change` fires only on focusout and enter and the native `change` is more like your `input`.

You can only compare you `change` event to the `blur` event because the blur event fires also on focusout.

But thats the problem, the `blur` event does not fire for enter press. So if I listen for the blur event then I cant listen for an enter press. And since your `change` event does not fire on focusout if I dispatch an `input` event, then I cant use this event.

The problem really is that the `blur` event does not fire on enter and your `change` event does not fire if I diespatch the `input` thats a real problem and its **not solved.**

**Comment by ndeshev** [comment]
Hello,
Like I said, please provide isolated samples where the change event of the native input and the `ui5-input` behave differently when you dispatch an input event and focus out of the element.

Kind Regards,
Niki

**Comment by pskelin** [comment]
Hi @C3ntraX ,

the way you are trying to use events is not quite correct. Events are fired by the browser in response to user interaction. If you fire events programatically, this does not cause the same effect as the actual user input. Here is an explanation I found from a previous MDN documentation:

> Note: manually firing an event does not generate the default action associated with that event. For example, manually firing a key event does not cause that letter to appear in a focused text input. In the case of UI events, this is important for security reasons, as it prevents scripts from simulating user actions that interact with the browser itself.

https://stackoverflow.com/a/45460233

When you call `.preventDefault()` on all keystrokes in `beforeinput`, the native input element has essentially seen no user input and has no reason to fire a `change` event, regardless of the fact that you fire an `input` event by yourself and that you set a value through the value property.

I would suggest one of the following approaches
1. Don't call `preventDefault()` on the actual characters that are coming from the barcode scanner. Just prevent default for the prefix and suffix so they don't appear in the input, but leave the actual keystrokes of the scanner. Then the `change` event will be fired when leaving the input. The downside is that you will get an input event for each keystroke and not just one input event like you try to do in the sample.
2. In addition to filtering the prefix and suffix, you could fire custom events like "scanstart" and `scanend`. I see some libraries doing this, and it is way more clear than the native `input` and `change` events. `scanend` will be the equivalent of the `input` event you are trying to achieve in the sample, the `change` event will remain when the user leaves the input or commits the value by pressing enter.

I hope that helps you.
