### ISSUE TITLE
[Button]: Button submits ignores language

### ISSUE THREAD

**Issue by C3ntraX** [SAP/ui5-webcomponents#7242]
### Bug Description

If you use a Button with submits in a Form then the language will taken from window.navigator instead of the language set to the ui-library.

### Expected Behaviour

Language in the valuehelper should taken from the ui-libarary via setLanguage or in the config (index.html).

But I dont know if this is possible?

### Steps to Reproduce

1.
2.
3.
...

### Log Output, Stack Trace or Screenshots

![image](https://github.com/SAP/ui5-webcomponents/assets/44802503/380fcdda-3a73-4388-a2b2-0a1d49e874ed)

### Priority

None

### UI5 Web Components Version

1.14.2

### Browser

Chrome

### Operating System

Windows

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by unazko** [comment]
Hello @C3ntraX,

Could you provide an example like the following:
https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html

Is the issue reproducible in the playground:
https://sap.github.io/ui5-webcomponents/playground/components

Best regards,
Boyan

**Comment by C3ntraX** [comment]
Here: https://codesandbox.io/s/ui5-webcomponents-forked-dfzqrm?file=/src/index.js:0-397

index.js - setLanguage("de"); 

Use a different language then navigator.language then you will see the problem.

**Comment by unazko** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

The language setter doesn't take any effect.
After we press enter keyboard key into the input field we could see the required message in english:
https://codesandbox.io/s/ui5-webcomponents-forked-twx5n6?file=/index.html

Best regards,
Boyan

**Comment by elenastoyanovaa** [comment]
Hello,

This is the default browser popup and we do not have any influence on it. For this we have a value state available in the input and applications could use it to create value state texts for the users or use the default ones. In this case the applications can translate the text filled in the value state message, or in the case of the default values of the value states the messages will be translated automatically.

Kind Regards,
Elena
