### ISSUE TITLE
[Button]: Button changes depending on the browser

### ISSUE THREAD

**Issue by soniaklaudia** [SAP/ui5-webcomponents#7259]
### Describe the bug

The button component varies depending on which browser you are using.

When using Firefox, the spacing between letters decreases.

### Reproduction steps

1. Open https://sapui5.hana.ondemand.com/#/entity/sap.m.Button/sample/sap.m.sample.Button

### Expected Behaviour

Same render of button in both browsers.

![edge](https://github.com/SAP/ui5-webcomponents-react/assets/137898177/d13664ca-48f1-4003-a02b-f5f66c1c2429)
![firefox](https://github.com/SAP/ui5-webcomponents-react/assets/137898177/a534e541-132b-4ff6-a671-3f14564071a6)

### UI5 Web Components for React Version

1.114.0

### UI5 Web Components Version

v1.112

### Browser

Firefox

### Operating System

Windows

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by nnaydenow** [comment]
Hi @soniaklaudia,

Is it reproducible in https://sap.github.io/ui5-webcomponents/playground/components/Button/ otherwise issue seems to be related to OpenUI5 / SAPUI5 and we have to forward it to the correct GitHub project?

**Comment by kgogov** [comment]
Hello @soniaklaudia,

Thank you for reporting this issue.
I've actually tried to simulate this by opening the sample [link](https://sapui5.hana.ondemand.com/#/entity/sap.m.Button/sample/sap.m.sample.Button) in both Firefox and Chrome.
I saw no difference in the style of the button.

Could you please provide a working isolated example so we can trace the issue if occurs?

Here is my test screenshot:

![Screenshot 2023-06-28 at 17 40 02](https://github.com/SAP/ui5-webcomponents/assets/68374332/f0959db3-dcde-4b3d-ad3a-39b9c371949a)
