### ISSUE TITLE
Panel: headerLevel has no effect on header text size 

### ISSUE THREAD

**Issue by Damien9222** [SAP/ui5-webcomponents#7260]
### Describe the bug

The modification of the property headerLevel  (H1, ..., H6) has no effect on the header size text (defined in property headerText).
In the documentation, the property's definition is : "Defines the "aria-level" of component heading, set by the headerText."

### Isolated Example

reproduced in the doc sample: 

### Reproduction steps

In webcomponents-react documentation (https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-panel--docs), go to the example; By default, the parameter headerLevel is set to H2:
1. In the property list, modify the headerLevel property to H6
2. See in the example the "Panel" text header size ( headertText) did not change while it should be smaller
3. Modify the headerLevel to H1 should change the header text "Panel" size but has no effect 

For comparison, the component Title (https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-title--docs) has the equivalent property named 'level' (H1 to H6). On this component, the property modification has an effect on the text size "Title Text".
(Same behavior in my componentor in codeSandBox)

### Expected Behaviour

The modification of the headerLevel property ( fron H1 to H6) must change the size of the headertText property.

### Screenshots or Videos

![Panel_headerLevel](https://github.com/SAP/ui5-webcomponents-react/assets/99638859/a69c1517-3ef9-4863-ad90-e6bf73df9a99)

### UI5 Web Components for React Version

1.16.0

### UI5 Web Components Version

1.14.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ilhan007** [comment]
@Damien9222  it's meant to only change the ARIA related attribute, not the design/size as this is not part of the component's design spec. The property is allowing the application developer to properly order all headings the app has on the page to have the correct Accessibility and screen reader announcements. 

So, it's not a bug, it's by design. Still, you can open a feature request as a new issue or use this one - edit the title and description to make it a feature request.

**Comment by Damien9222** [comment]
Thanks a lot for your answer.
I finally found a way to apply a font size to the title using the property header.
So, I can close this bug.

**Comment by Damien9222** [comment]
Thanks a lot for your answer.
I finally found a way to apply a font size to the title using the property header.
So, I can close this bug.
