### ISSUE TITLE
Button UI Name not read by Screen Reader within Table Row

### ISSUE THREAD

**Issue by adrianui5** [SAP/ui5-webcomponents#7273]
### Bug Description

Hello colleagues,

I have a follow-up to this ticket here: https://github.com/SAP/ui5-webcomponents/issues/6139.

We have discovered that by following the suggestion, the screen reader is reading out the type, but not the text of the button.

We are expecting the type of UI may also be announced along with the name of the button such as 'Add' when the table rows are accessed. That way, the screen reader users can understand what the button is doing.

Is this perhaps not considered in the implementation of the ui5 element? Or is this intended behavior?

Best,
Adrian

### Steps to Reproduce

1.
2.
3.
...

### Priority

None

### UI5 Web Components Version

1.13.3

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by kgogov** [comment]
Hello @adrianui5,

Thank you for reporting your issue to us.
I have reviewed the problem description and have thoroughly examined your statement. 
Using **Jaws 2023**, I have created a video demonstrating that the screen reader does, in fact, read out the text content of the button accurately.

https://github.com/SAP/ui5-webcomponents/assets/68374332/be840c5d-faf4-4124-8409-5fd190089940

![Jaws-2023-speech-history](https://github.com/SAP/ui5-webcomponents/assets/68374332/f66e7212-9a55-4b05-8cf2-36c4ebe3d63b)

To better assist you, could you please provide us with more information regarding the screen reader you are using when experiencing the issue? Thank you!

Regards,
Konstantin
GitHub Dispatcher
