### ISSUE TITLE
[Feature Request]:Control theming version that gets loaded

### ISSUE THREAD

**Issue by Prannoy-KV** [SAP/ui5-webcomponents#7277]
### Feature Request Description

ui5 webcomponents loads theming from theming base content library.
For various reasons, we would like to control the theming base content version that is being loaded.
I did not find a way to control the version. 

### Proposed Solution

I would like to control the version of the theming base content library in some way from the code.
So that I have a better control on how applications UI will be presented.

### Organization

SAP

### Priority

None

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by petyabegovska** [comment]
Hi @Prannoy-KV,

We will need more information about the use case to load a lower version of the theming base content in order to evaluate the request. Can you please provide more info what is meant by various reasons?

Best regards,
Petya

**Comment by Prannoy-KV** [comment]
Sure @scameron , I will go ahead and close the issue. Thank you @petyabegovska
