### ISSUE TITLE
[Documentation] The old documentation is not available anymore and the new one not correctly working

### ISSUE THREAD

**Issue by veith** [SAP/ui5-webcomponents#7286]
### **Issue Description**
The documentation page links to a storybook instead of the very good documentation you had before. 

The search does not work correctly. A search for "onEnterDOM" gives no results. On the old page it linked to "Deep dive and best practices".

Please make the storybook "optional" i.e. with a link on the start page. 

Nearly every documentation has errors
<img width="964" alt="Bildschirmfoto 2023-06-30 um 16 47 55" src="https://github.com/SAP/ui5-webcomponents/assets/606760/25479cf0-df88-4a6d-9850-7dd816412aa7">

<img width="1533" alt="Bildschirmfoto 2023-06-30 um 16 50 33" src="https://github.com/SAP/ui5-webcomponents/assets/606760/5fc873a9-978b-4d88-8ea5-1676814e093a">

**Comment by veith** [comment]
Switching between pages from "DOCS" takes more then 20s before you can scroll the content.

**Comment by dobrinyonkov** [comment]
Hi @veith, thanks for reporting those issues. 

Unfortunately, we will need some more information about the reproduction steps as all topics seems to load correctly and within a few seconds when I test the following url: https://sap.github.io/ui5-webcomponents/playground/

Please, guide us on how to  reach the errors from the screenshot.

Also, on what device and browser you're observing the performance issue (20 sec topic loading)?

Notes taken on the feedback about the search limitations, we will look further to improve it. 

Kind Regards,
Dobrin

**Comment by veith** [comment]
@dobrinyonkov I can not reproduce the errors anymore, everything is fast and works. Maybe i was opening the docs during a release?

The only thing that does not seem to work as expected, or should be improved is the search.
