### ISSUE TITLE
[TabContainer]:  Overflow buttons have no side margin

### ISSUE THREAD

**Issue by nathanbienfait** [SAP/ui5-webcomponents#7291]
### Bug Description

When using the TabContainer with overflow, the button on the left has no left-marin and the button on the right has no right-margin.

### Affected Component

TabContainer

### Expected Behaviour

It would be nice to have a small margin so that the buttons are not touching the edge of the tabContainer. Or maybe a part on the buttons so that we can put a custom style on the buttons

### Steps to Reproduce

1. Use a TabContainer with overflow

### Priority

Low

### UI5 Web Components Version

1.14.5

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ivoplashkov** [comment]
Hello @nathanbienfait,

I was not able to reproduce the issue you have described. There are paddings, depending on the screen width, on both side of the buttons as it is described in the visual specifications.

Could you please provide an isolated example in order for us to be able to examine the issue.

Thank you in advance!
Regards,
Ivaylo

**Comment by nathanbienfait** [comment]
Hello @ivoplashkov, 
I don't have isolated example.
But by opening the doc and reducing the browser size so that the tabs collapses you should reproduce easilly.
Doc link: [https://sap.github.io/ui5-webcomponents/playground/?path=/docs/main-tabcontainer--docs](https://sap.github.io/ui5-webcomponents/playground/?path=/docs/main-tabcontainer--docs)

![image](https://github.com/SAP/ui5-webcomponents/assets/26220418/cd044e2e-8d14-4451-9235-51d4e9f62176)
As you can see on the screen, the button is touching the right side

**Comment by ivoplashkov** [comment]
Hello team,

As described above, if we reduce the screen size enough, you may notice that there is no space between the button and the border.

Could you please check?
Best regards,
Ivaylo
