### ISSUE TITLE
[ui5-table]: there has a blank page when print table content more than one page

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents#7297]
### Bug Description

There has a blank page when print table content more than one page

### Affected Component

ui5-table

### Steps to Reproduce

1. open page https://sap.github.io/ui5-webcomponents/playground/iframe.html?id=main-table--growing-table-more-button&viewMode=story
2. click more button to show more than 36 rows
3. use browser print function to print the table 
4. you can see a blank page first and the bottom row was broken

### Log Output, Stack Trace or Screenshots

<img width="487" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/13098801/09c3dfa7-d05d-4600-9d51-72b7b4bddc3f">

### Priority

High

### UI5 Web Components Version

1.15.x

### Browser

Chrome, Edge

### Organization

SAP SuccessFactors

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ivoplashkov** [comment]
Hello colleagues,

The issue is reproducible as described above. 

Could you please check?
Regards,
Ivaylo

**Comment by hristop** [comment]
Hi @GongRichard ,

We believe that we have found the reason for this issue, however the fix will be available in the August release of the web the earliest. 
There is a workaround for the issue though, if you make add **style "display: block"** to the **ui5-table** element, the printing should be ok. 

Best Regards,
Hristo

**Comment by MapTo0** [comment]
Hello @GongRichard ,

The issue is Chromium specific and I have raised an issue in their project.
Lets see Chromium team statement on the topic and we will see how to proceed with that. 
As a workaround you have a few options.

1. Remove the margin of the body tag (recommended) https://jsbin.com/sofuhuvawo/1/edit?html,console
2. Set `display: block` to the `ui5-table` tag 

Best Regards,
Martin

**Comment by MapTo0** [comment]
Hello @GongRichard 

Chromium team closed the issue by saying that this is by Design and they are not willing to change it.
https://bugs.chromium.org/p/chromium/issues/detail?id=1468957

Did you try any of the approaches described above? Are these working solution for you?

Best Regards,
Martin

**Comment by GongRichard** [comment]
Hi @MapTo0,

I have tried workaround, it works well.

Thanks,
Richard

**Comment by MapTo0** [comment]
Since a major refactoring of the Table component is ongoing I would suggest we stay with the workaround for now. (Its not a workaround for the component, rather than a workaround for the browser functionality).

Best Regards,
Martin
