### ISSUE TITLE
[SF]Performance degradation after upgrading @ui5/webcomponents and @ui5/webcomponents-react

### ISSUE THREAD

**Issue by QiuranHu** [SAP/ui5-webcomponents#7303]
### Describe the bug

After upgrading @ui5/webcomponents and @ui5/webcomponents-react, we are observing severe performance degradation. Our use case is a table with initially 100 rows inside a dynamic page. After the upgrade, navigating to another page becomes much slower (about 1.5s). 

Versions before:
@ui5/webcomponents: 1.12.2
@ui5/webcomponents-react: 1.13.1

Versions after:
@ui5/webcomponents: 1.15.1
@ui5/webcomponents-react: 1.17.0

Please see the codesandboxes I attached below:
@ui5/webcomponents: 1.12.2 https://codesandbox.io/p/sandbox/confident-pike-gz7nyx?file=%2Fpackage.json%3A12%2C29-12%2C35
@ui5/webcomponents: 1.15.1 https://codesandbox.io/p/sandbox/zealous-joji-xfqgnn?file=%2Fpackage.json%3A1%2C1

Clicking the "Clear" button will hide the dynamic page. It's fast with @ui5/webcomponents: 1.12.2, but very slow with @ui5/webcomponents: 1.15.1 (about 1.5s).

@ui5/webcomponents: 1.12.2: 
<img width="1791" alt="Screenshot 2023-07-06 at 13 18 48" src="https://github.com/SAP/ui5-webcomponents-react/assets/55808904/5bccc13e-fdd2-4502-ad46-c0650c183329">

@ui5/webcomponents: 1.15.1:
<img width="1791" alt="Screenshot 2023-07-06 at 13 18 54" src="https://github.com/SAP/ui5-webcomponents-react/assets/55808904/f651fd0c-0a51-40b3-aa94-33685240d5c0">

### Screenshots or Videos

https://github.com/SAP/ui5-webcomponents-react/assets/55808904/b028aa55-cf4a-458b-be5c-ff9aae161a8b

### UI5 Web Components for React Version

1.17.0

### UI5 Web Components Version

1.15.1

### Browser

Chrome, Edge

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by pskelin** [comment]
Hi @Lukas742 ,

I suspect this is a codesandbox artefact, there is a some difference but I can't find out what exactly.

If I download your 1.13.3 example locally, it is fast. If I modify it to use 1.13.2 also locally, it has the same performance.

What I then tried is to fork your 1.13.2 codesandbox (which is fast) and update it to 1.13.3.
https://codesandbox.io/p/sandbox/lively-cloud-jpzk3m?file=%2Fpackage.json%3A16%2C5

This is now also fast in codesandbox.

Basically I see that your two samples used different forks:
1.13.2 (relaxed-hill) forked from (friendly-maria) - fast
1.13.3 (white-wave) forked from (delicate-framework) - slow
my fork:
1.13.3 (lively-cloud) forked from your 1.13.2 (relaxed-hill) - fast

In general, what I notice is that the timeline is the same, but calculation of the styles is much slower. In both of your versions, one particular "recalculate styles" block is applied on 60 nodes (so same workload) but takes 0.50 ms vs 7 ms. Somehow each style calculation is more than 10x slower and that is only visible on codesandbox, not locally.

**Comment by Lukas742** [comment]
Thanks @pskelin for investigating.

Note to myself: never test performance issues with codeSandbox only :smile:

Initially we thought this was connected to v1.14.0 of `@ui5/webcomponents` but then codeSandbox showed us this strange behavior in v.1.13.3 as well.

I now tested v1.14.0 locally and unfortunately it seems that the behavior is noticeable with this version. Is it the same for you or does my setup have something to do with it? 

Here's another video comparing v1.13.3 and v1.14.0 locally (again with 6x CPU throttle):

https://github.com/SAP/ui5-webcomponents/assets/9749730/6d128159-52d3-4bb9-af32-d859dab01c73

**Comment by QiuranHu** [comment]
Hi colleagues @Lukas742 @pskelin,

Thanks for investigating.

I tried v1.14.0 (with @ui5/webcomponents-react 1.16.0) locally in my own project and observed the same performance degradation (navigating to another page takes roughly 1.5s).

**Comment by pskelin** [comment]
posting an update, as the cause has been identified.

with https://github.com/SAP/ui5-webcomponents/pull/7044 CSS variables get applied to every web component which seems to be very slow in terms of propagating them. We are currently still discussing a solution and will provide an update.

**Comment by QiuranHu** [comment]
@pskelin Thanks for the update!

**Comment by QiuranHu** [comment]
Hi @pskelin, could we get an update on when this is being planned to be fixed? We have noticed a significant impact on our page performance after the update of the UI5 web component to 1.15.1. We would greatly appreciate it if the urgency of this matter could be escalated. Thanks!

**Comment by ilhan007** [comment]
Hello @QiuranHu the fix is now part of the preview [1.17.0-rc.1](https://github.com/SAP/ui5-webcomponents/compare/v1.17.0-rc.0...v1.17.0-rc.1) version

**Comment by QiuranHu** [comment]
I'll try it out today. Thank you!

Qiuran Hu

**Comment by QiuranHu** [comment]
The performance issue is fixed after upgrading to 1.17.0-rc.1. Thanks!
