### ISSUE TITLE
ui5-multi-input / ui5-token: rendering a multi-input with one token may throw error

### ISSUE THREAD

**Issue by winterkind** [SAP/ui5-webcomponents#7304]
### Bug Description

After upgradeing to release 1.15.1, it can happen that rendering a `ui5-multi-input` with exactly one `ui5-token` inside throws an exception: `Cannot read properties of undefined (reading 'querySelector')` thrown in `get textDom()` in `Token.js`.

This seems to be caused by a recent commit for release 15.0.0: https://github.com/SAP/ui5-webcomponents/commit/e9a75802205f52437380611487f456486f75705b. Through that change, the renderer for `ui5-multi-input` indirectly calls  `get textDom()` in `Token.js`. That getter assumes that the shadow DOM for the `ui5-token` was already rendered.

But it may happen that the renderer for `ui5-multi-input` runs before the one for `ui5-token`. We spent some time on finding a simple and reliable example to reproduce the error. See below.

**Note:** The commit mentioned above refers to `ui5-tokenizer` and relates to several components. We have not analyzed if the problem also impacts other components.

### Affected Component

ui5-multi-input

### Expected Behaviour

The components should not assume a certain sequence in which renderers are executed.

### Isolated Example

https://stackblitz.com/edit/vitejs-vite-mdghcu

### Steps to Reproduce

1. Open the above link to start the example in Stackblitz. Please give it a few seconds to start up. When it is ready, you will see some text, two buttons and one `ui5-multi-input` with a single `ui5-token` inside.
2. Click the button "Add One More". A single new `ui5-multi-input` with a single `ui5-token` will be created and rendered. No errors are thrown.
3. Click the button "Add Five More". Five new `ui5-multi-input` with a single `ui5-token` will be created but not all (mostly just the first one) will be rendered. Check the browser console for errors.

**Note:** This is not what we do in the application where we spotted this error. This is just the simplest reliable way we could find to reproduce the error in vanilla JS.

### Priority

High

### UI5 Web Components Version

1.15.1

### Browser

Chrome, Edge, Firefox

### Operating System

Win 11

### Additional Context

In our application, this error breaks a page that has several `ui5-multi-input` components with tokens inside. It breaks as soon one of the components has only one token inside.

While trying to build a reproducable example, we noted that certain browser extensions (uBlock in our case) can influence the example. Different errors appear or the example behaves differently. We assume that in the case of uBlock that is because it also uses DOM observers to react on node injections. That seems to potentially influence the sequence in which asynchronous code is executed. It is probably best to deactivate any such browser extension while trying the example.

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ivoplashkov** [comment]
Hello @winterkind,

Thank you for the explanation and the isolated example.
I am forwarding the issue to the repsponsible team for further processing.

Best regards,
Ivaylo
