### ISSUE TITLE
ui5-tabcontainer + ui5-table has some performance issue

### ISSUE THREAD

**Issue by Lukewxg** [SAP/ui5-webcomponents#7306]
### Bug Description

https://codesandbox.io/s/hopeful-ace-86mm6w?file=/src/App.js
When use ui5-tabcontainer, and in each of tabs it is a table which rows count > 10, when switch between tabs, the performance will become slow and sometime page will be frozen.

And if the ui5-tabcontainer is in a dialog, the performance will become more clear, and even if the table contains are dynamically created, even though we are using useState or useMemo , the performance is still much more poor.

Here is one more example which will make the performance issue more clear.
https://codesandbox.io/s/shy-monad-w7rq9w?file=/src/App.js

### Affected Component

ui5-tabcontainer, ui5-table

### Expected Behaviour

There should not delay when switch between tabs.

### Isolated Example

https://codesandbox.io/s/hopeful-ace-86mm6w?file=/src/App.js

### Steps to Reproduce

1. Open the example: https://codesandbox.io/s/hopeful-ace-86mm6w?file=/src/App.js
2. Click Tab Two
3. Then click Tab One
4. Repeat above 2 and 3 to switch the tabs quickly, will see the issue
5. Open the example: https://codesandbox.io/s/shy-monad-w7rq9w?file=/src/App.js
6. Click "Open Dialog" to open the dialog
7. Click Tab Two
8. Then click Tab One
9. Repeat above 7 and 8 to switch the tabs quickly, will see the issue more clearly
...

### Priority

High

### UI5 Web Components Version

lastest

### Browser

Chrome, Edge

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by s-todorova** [comment]
Hello @Lukewxg,

Based on my analysis, I am unable to reproduce your issue - on both provided examples, I do not see any noticeable delays when switching between the tabs or freezing of the page. Could you please provide a video recording showcasing the delays/freezes in question?

Best regards,
Siyana

**Comment by Lukewxg** [comment]
Hi Siyana,
Thanks for your quick response, please check the attachment.
The repro env is Windows11 Chrome.
And one tricky thing I found is in one of our office, I cannot get the issue repro with totally same env, but in another office or at home, I can easily get it reproduced.

https://github.com/SAP/ui5-webcomponents/assets/58862237/00763e4c-ddf1-4701-b54e-f0326d05fa9f

Thanks!
Luke Wen

**Comment by pskelin** [comment]
posting an update, as the cause has been identified.

with #7044 CSS variables get applied to every web component which seems to be very slow in terms of propagating them. We are currently still discussing a solution and will provide an update.

**Comment by Lukewxg** [comment]
Cool, Thanks for updating, will try in our project.
