### ISSUE TITLE
[CheckBox - FormSupport]: `required` doesn't trigger validation

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#7319]
### Bug Description

If a `ui5-checkbox` is used inside a `form` and `required` is applied, the form is submitted even though the checkbox hasn't been checked.

### Affected Component

ui5-checkbox

### Expected Behaviour

The form should not be submitted if it contains an unchecked checkbox with `required`, instead it should receive focus and the native validation popover should be displayed.

### Isolated Example

https://codesandbox.io/s/ui5-webcomponents-forked-266krn?file=/src/index.js

### Steps to Reproduce

1. Go to [codeSandbox](https://codesandbox.io/s/ui5-webcomponents-forked-266krn?file=/src/index.js)
2. Click on the first submit button (submits form with ui5-checkbox)
3. See that the form is submitted
4. Click on the second submit button (submits form with html checkbox)
5. See that the form is not submitted, the focus has changed to the checkbox and the validation popover is displayed. (expected)

### Log Output, Stack Trace or Screenshots

https://github.com/SAP/ui5-webcomponents/assets/9749730/5c6372e0-7d31-4c1c-a306-1e957d64f010

### Priority

None

### UI5 Web Components Version

1.15.1

### Browser

Chrome, Edge, Firefox, Safari

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by s-todorova** [comment]
Hello colleagues,

The issue described above of the ui5-checkbox required property not working correctly inside a form element can be reproduced via the given [example](https://codesandbox.io/s/ui5-webcomponents-forked-266krn?file=/src/index.js).

Could you please take a look at this?

Best regards,
Siyana
