### ISSUE TITLE
Page | Placement of home icon in footer is not proper design

### ISSUE THREAD

**Issue by Yibingg** [SAP/ui5-webcomponents#7326]
### **Issue Description**
In current documentation of page, the example shows a home icon inside of footer, which is not a proper design. Please remove the icon. For reference page specification (in Figma) and visual core (wiki) from design team can be used.

### **Issue Type**

- [ ] Example in Documentation is not proper design

**Comment by s-todorova** [comment]
Hello colleagues,

The [example](https://sap.github.io/ui5-webcomponents/playground/?path=/docs/fiori-page--docs) for Page component contains an unnecessary icon in the footer, which is not per spec according to the examples shown in the visual core wiki.
Could you please take a look at this?

Best regards,
Siyana
