### ISSUE TITLE
[component name | framework | build | icons | theming | localization | i18n | typescript]:

### ISSUE THREAD

**Issue by clarenceWan** [SAP/ui5-webcomponents#7328]
### Bug Description

Context:
We have built a custom web-component which is dependent on service calls to certain APIs, the result of which is displayed on the screens. 
These APIs require authentication, which we  rely on the underlying application using our web-component for them.

Issue: We need a way to test our custom web-component by mocking these APIs. In the current test setup that ui5-webcomponent has, we are not able to mock these API calls.

### Steps to Reproduce

1.
2.
3.
...

### Priority

High

### UI5 Web Components Version

1.15.1

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ilhan007** [comment]
Hi @clarenceWan 

as we spoke the wdio.[mock API]( [mock AP](https://webdriver.io/docs/api/browser/mock/)) requires some additional configuration as stated in the wdio docs, the mock API requires setting the [automation protocol](https://webdriver.io/docs/automationProtocols) to `devtools`

```js
// `wdio.config.js`
const wdio = require("@ui5/webcomponents-tools/components-package/wdio.js"); // eslint-disable-line

wdio.config.automationProtocol: 'devtools';

module.exports = wdio;
```

Then,
you will be able to use the [mock API](https://webdriver.io/docs/api/browser/mock/) within the tests (*.spec.js)

```js
const assert = require("assert");

describe("my component tests", async () => {
	before(async () => {
		await browser.url("test/pages/index.html");
	});

	it("tests requesting users", async () => {
		const userListMock = await browser.mock('**' + '/users/list')
	});
});
```
The tests  are running in headless mode by default. THe headless mode can be turned off to see a browser opening, performing the defined tests in your .spec.js file.

```js
// `wdio.config.js`
const wdio = require("@ui5/webcomponents-tools/components-package/wdio.js"); // eslint-disable-line

wdio.config.automationProtocol: 'devtools';

wdio.config.capabilities[0]["goog:chromeOptions"].args = [
                '--disable-search-engine-choice-screen',
               // '--headless', // remove or comment to disable headless mode
                '--start-maximized',
                '--no-sandbox',
                '--disable-gpu',
                '--disable-infobars',
                '--disable-extensions',
                '--disable-dev-shm-usage',
 ];
            
module.exports = wdio;
```
