### ISSUE TITLE
Input FontSize zoom issue on Apple iPhone devices

### ISSUE THREAD

**Issue by hschaefer123** [SAP/ui5-webcomponents#7332]
### Bug Description

Fokus an input control on an Apple iPhone, 
the keyboard slides up and the input field get slightly zoomed.

This is intended by Apple for input fields, that are sized below 16px for a better UX.

The only known workarounds are 

1) Disallow zoom by meta viewport
```
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1">
```
2) Use input size with at least **16px**.

I am currently using VitePress and am i not allowed to set/overwrite the viewport meta to fix this behavior.

![image](https://github.com/SAP/ui5-webcomponents/assets/2110971/274af2d0-6358-4e98-9f66-b5e8cf693610)

As you can see in the screenshot, the whole ui gets zoomed to better enter value inside field.
After entering, the ui stays in the zoomed mode and a user manually have to pinch out the UI.
 

### Affected Component

Input

### Expected Behaviour

Do not break layout design by zooming input field.

Currently, only using an input size of 16px seems to be a valid solution for apple devices.

Since i am using the compact mode fpr the UI (even on mobile), this should not only be fixed for the cozy mode. 

### Isolated Example

https://btp.udina.de/tools/api-explorer.html

### Steps to Reproduce

Focus the search field and enter some data using the keyboard on an Apple iPhone.
The layout will be zoomed and shifted to input field.

### Priority

None

### UI5 Web Components Version

1.15.1

### Browser

Safari

### Operating System

Aapple iPhone 14 Pro

### Organization

UNIORG Group

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by didip1000** [comment]
Hey @SAP/ui5-webcomponents-topic-rl, 

Can you please take a look at this issue? It's reproducible in the example above, and in the playground samples.

Best, 
Diana

**Comment by niyap** [comment]
Hello @hschaefer123,

Thanks for sharing your findings!

The expected font-size from our side is 14px as implemented currently.
I have forwarded the request to the visual design team and they stated the following:
> Our 14 px default font size technically results in a bounding box of 16 px for key fonts in our font stack such as the 72, Arial, Helvetica. 

and

> Changing the default font size to 16 px, would technically result in a bounding box of 18 px for fonts such as the 72, Arial, Helvetica. 
The bread and butter controls then would be “off grid” / inconsistent with the browser base.

Therefore we can't change the current implementation.


Kind Regards,
Niya
