### ISSUE TITLE
Readme should show documentation for released version

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents#734]
**Describe the documentation issue**

- [ ] Documentation is unclear
- [X] Documentation is incorrect
- [ ] Documentation is missing
- [ ] Other

**Description of the issue**
A clear and concise description.
It looks like that the Readme is already showing some configuration settings for the next, unreleased version.
Example: Setting the Compact Size:
The Readme tells that it works this way:
```html
<script data-ui5-config type="application/json">
{
  "language": "en",
  "rtl": true
}
</script>
```
The currently released version (1.0.0-rc.2) is using the config instead:
```html
<script data-id="sap-ui-config" type="application/json">
{
  "compactSize": true
}
</script>
```
There was also an issue raised in the react wrapper project (SAP/ui5-webcomponents-react#91)

Is there change to merge upcoming changes to a `next` branch and show the most current version on master?

**Comment by fifoosid** [comment]
Hi @MarcusNotheis 

Recently we will update our playground and all of the docs would be available there, showing the info for the released version(and not the latest). Hope this works for you.

This is the PR, which will solve the issue: #751

Best regards,
Filip

**Comment by fifoosid** [comment]
The issue is resolved and the new playground will be available with our next release.
