### ISSUE TITLE
[MultiComboBox]: Unable to setAttribute "value-state" dynamically

### ISSUE THREAD

**Issue by anshul-031** [SAP/ui5-webcomponents#7344]
### Describe the bug

I am using a webcomponent "MultiComboBox" [](https://sap.github.io/ui5-webcomponents/playground/?path=/docs/main-multicombobox--docs)

I am trying to change the "value-state" attribute of MulticomboBox dynamically via typescript. But the "value-state" automatically refresh after 2-3 seconds. Ideally when I changed the attribute "value-state" via typescript, it should persist. but it's refreshed due to some bug. 

A video recording has been uploaded.

**Typescript code being used:**
const multiComboBoxElement = document.getElementById("editpane-value-input-field");
multiComboBoxElement.childNodes[0].textContent = "Duplicate Value not Allowed"
multiComboBoxElement.setAttribute(VALUE_STATE, ValueState.Error);

### Reproduction steps

1. Create an multicomboBox element using "value-state"= "None"
2. Try to change this attribute value via code to "Error".
3. The change effect would be visible for only 2-3 seconds. After that it would be refreshed to "None" from "Error".
...

### Screenshots or Videos

https://github.com/SAP/ui5-webcomponents-react/assets/18512766/b2317175-d9ed-4c76-9592-30dae7f24f84

### UI5 Web Components for React Version

1.17.0

### UI5 Web Components Version

1.15.1

### Browser

Chrome, Edge

### Operating System

Windows 11

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by didip1000** [comment]
Hey @SAP/ui5-webcomponents-topic-rl,

Can you please take a look at this issue? It's is reproducible in @Lukas742's sample.

Thanks,
Diana

**Comment by anshul-031** [comment]
Any expected timelines? When can we expect this development to be completed?

**Comment by ivoplashkov** [comment]
Hello,

The reason for the issue is that the FormSupport uses an Input instead of TextArea (which is multiline) and therefore the value is different.
Could you please provide an API for the FormSupport in order to cover this use case?

Thank you in advance!
Best regards,
Ivaylo

**Comment by ivoplashkov** [comment]
Hello,

Thank you for reporting this!

We are going to process this as a feature request, since this was never implemented yet.

Best regards,
Ivaylo

**Comment by hristop** [comment]
Internal BLI created: FIORITECHP1-28938

**Comment by hristop** [comment]
Hi @anshul-031 , 

Can you please clarify a bit further what you are trying to achieve, as I am not able to reproduce the issue you are facing. 
![2023-11-13_12-07-07 (1)](https://github.com/SAP/ui5-webcomponents/assets/14230119/191055dc-1484-47a9-b728-4ba53333ecbf)

When you set the state, upon validation, the state returns to the previously set one. 

Best Regards,
Hristo
