### ISSUE TITLE
[Feature Request]: combobox with n columns

### ISSUE THREAD

**Issue by gimler** [SAP/ui5-webcomponents#7346]
### Feature Request Description

We need to display multiple columns in a option for combobox.
Actually it is only possible to use addtional-text option.

Also a pre and post slot around the options would be great.

![ui5_combobox](https://github.com/SAP/ui5-webcomponents/assets/200904/dcdc5fa4-5c13-4bf0-b3de-d93114f9d602)

### Proposed Solution

Make it possible to use custom code for option. Example see other frameworks
https://quasar.dev/vue-components/select#customizing-menu-options

### Organization

SAP SE

### Priority

None

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by hristop** [comment]
Hi @gimler ,

We already have such request and there are discussions with the design team regarding this topic. 
As it was already requested with #6009 (and relates to #5128) I will close this one.

Best Regards,
Hristo
