### ISSUE TITLE
[Feature Request]: for ui5-input enable attributes: minlength, pattern, cursor (css prop), possibility to remove pop up for valueState error

### ISSUE THREAD

**Issue by MarinaGudym** [SAP/ui5-webcomponents#7351]
### Feature Request Description

Currently, `ui5-input`:
- does not support all attributes, e.g. [minlength](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#minlength) and [pattern](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#pattern)
- ignores css property [cursor](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor)
- always renders pop up under the component if valueState is set to error, information or warning even when valueStateMessage is not set

### Proposed Solution

The `ui5-input` supports minlength, pattern, and cursor (e.g. if input is disabled cursor can be set to `not-allowed`).

Also it would be great if it could be possible to control whether to show a pop up under the component that is shown when `valueState` is set to `Error`, `Information` or `Warning`.
For instance, you could add a toggle `showPopUp` which can be true by default.

Thank you.

### Organization

SAP Build Apps

### Priority

None

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by didip1000** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

Can you please take a look at this feature request?

Thanks, 
Diana

**Comment by hristop** [comment]
Hi @MarinaGudym ,

We believe that this requirement need to be synced with our design colleagues and specifications provided accordingly. 

Can you please create a design BLI and link provide **its number** here (Something like FIORITECHE1-XXXX)?  
The process to do so is described here: https://sap.sharepoint.com/sites/117628/SitePages/FfW%20New%20Design%20Requirements.aspx?OR=Teams-HL&CT=1654614264403

Best Regards,
Hristo
