### ISSUE TITLE
[Button]: Rendering Issues for Belize

### ISSUE THREAD

**Issue by mhchem** [SAP/ui5-webcomponents#7352]
### Describe the bug

We add WebComponent controls to an existing app that is still in Belize theme. The buttons deviate from the target design.

* Focus is too round
<img width="124" alt="image" src="https://github.com/SAP/ui5-webcomponents-react/assets/16336692/00aa672b-177a-4f51-8aac-93fe4f55e166">

* Pressed state has wrong focus color and text glow that should not exist
<img width="120" alt="image" src="https://github.com/SAP/ui5-webcomponents-react/assets/16336692/f46b8c20-72f1-4110-8154-0eb10ae9b20c">

* Emphasized Button has text glow that should not be there (in regular, hover, and pressed) and focus has wrong color.
![image](https://github.com/SAP/ui5-webcomponents-react/assets/16336692/db5229d1-4390-4042-9a6b-bfd9ea53076f)

### Isolated Example

https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-button--docs&globals=theme:sap_belize;contentDensity:Compact

### Expected Behaviour

Screenshots of reference implementation (UI5):
* ![image](https://github.com/SAP/ui5-webcomponents-react/assets/16336692/0e0f03ca-ab1a-4896-adc4-cb3dd5c2172b)
* ![image](https://github.com/SAP/ui5-webcomponents-react/assets/16336692/948ab968-4869-40ef-ad5c-22dec16fa987) (pressed)
* ![image](https://github.com/SAP/ui5-webcomponents-react/assets/16336692/e9bf4bf3-7d87-40d8-9a7e-211e4fe5a86f) (Emphasized)

You know where to find the visual specs, in the SAP intranet.

### UI5 Web Components for React Version

latest

### UI5 Web Components Version

latest

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by didip1000** [comment]
Hey @SAP/ui5-webcomponents-topic-b, 

Can you please look into this? The text shadow for active buttons in belize should be none, and border-radius for focused item should be 0 rem.

Thanks,
Diana

**Comment by ehn-sap** [comment]
Hello @SAP/ui5-webcomponents-topic-b 

Is there any news or schedule about that?

Thanks
