### ISSUE TITLE
[Dialog]: Buttons leave too much spacing on the right

### ISSUE THREAD

**Issue by mhchem** [SAP/ui5-webcomponents#7354]
### Describe the bug

Buttons leave too much spacing on the right. There should be 1rem, not 2 (in this size).

<img width="337" alt="image" src="https://github.com/SAP/ui5-webcomponents-react/assets/16336692/3019f935-b8b7-4181-b113-2a9f687df514">

https://sap.github.io/ui5-webcomponents-react/?path=/docs/modals-popovers-dialog--docs

### UI5 Web Components for React Version

latest

### UI5 Web Components Version

latest

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by didip1000** [comment]
Hello @SAP/ui5-webcomponents-topic-rd,

Can you look into this? It seems like the dialog footer and the bar in the slot are applying their own seperate padding.

Thanks,
Diana

**Comment by LidiyaGeorgieva** [comment]
@Lukas742 ,

When ui5-bar is used inside ui5-dialog there is need of additional styling from your side.
This is mentioned in this example (see the content of the dialog):
https://sap.github.io/ui5-webcomponents/nightly/playground/?path=/story/main-dialog--bar-in-dialog
It took me some time to find it, so there is need to be documented better. I will make one pull request for that.

Please add to your sample similar code to this and this will solve the issue:
#dialog::part(footer) {
    padding-inline: 0;
}

Best Regards,
Lidiya

**Comment by Lukas742** [comment]
Hi @LidiyaGeorgieva 

wouldn't this cause discrepancies with the responsive padding of the content and the header of the dialog? 
The inline start and end padding of the bar container is always `0.75rem`, while the responsive padding of the dialog is `3rem` when rendered in XL mode, for example.

**Comment by LidiyaGeorgieva** [comment]
Hi @Lukas742 ,

Yes, the responsive paddings are not still implemented for the ui5-bar, but sooner or later will be.

Best Regards,
Lidiya

**Comment by Lukas742** [comment]
Ok, we will adjust our examples then. Thanks :)

**Comment by LidiyaGeorgieva** [comment]
@Lukas742 I created a Feature Request for the responsive paddings for the ui5-bar: https://github.com/SAP/ui5-webcomponents/issues/7359

**Comment by LidiyaGeorgieva** [comment]
@Lukas742 I have merged my pull request. Could you please move this issue to your project "SAP/ui5-webcomponents-react"

**Comment by LidiyaGeorgieva** [comment]
Hello @mhchem ,

It looks like the sample is correct now.
I'm closing the issue.

Best Regards,
Lidiya
