### ISSUE TITLE
[Feature Request]: ui5-bar - implement responsive paddings

### ISSUE THREAD

**Issue by LidiyaGeorgieva** [SAP/ui5-webcomponents#7359]
### Feature Request Description

ui5-bar component does not implement responsive paddings concept and when used inside components that implement it it doesn't look good.
Example: ui5-dialog with ui5-bar.
This was noticed as part of processing of this issue: https://github.com/SAP/ui5-webcomponents/issues/7354

### Proposed Solution

ui5-bar to implement responsive paddings

### Priority

None

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by DMihaylova** [comment]
Internally tracked here: BGSOFUIBALKAN-7771
We'll update the progress here once we start working on it.
