### ISSUE TITLE
UI5-Input-webcomponents

### ISSUE THREAD

**Issue by gundaravikumar** [SAP/ui5-webcomponents#7366]
### Bug Description

Prior to the Horizon theming update, editable fields were shaded white, and non-editable fields were shaded gray. Under Horizon, this is reversed. We would like to revert the change back to previous design.

### Expected Behaviour

Under Horizon, Editable should be having white background and not-editable fields should be grayed out

Here is the current design and customers are opposing the design
![image](https://github.com/SAP/ui5-webcomponents/assets/140208505/a2c824f2-d35d-4a98-b716-71d3e5591e93)

### Steps to Reproduce

1.Open the UI5 Inut webcomponent  and observe the behavior

Issue: Editable field appears with graybackground and it appears as not editable.
Issue2: Non Editable field appears with white background. should be grayedout

### Priority

None

### UI5 Web Components Version

1.15.1

### Browser

Chrome

### Additional Context

Happens with any browser and its not specific to browser

![image](https://github.com/SAP/ui5-webcomponents/assets/140208505/fe1596c4-4de0-4982-a725-dadf4b3bfe88)

### Organization

SF

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by niyap** [comment]
Hello @gundaravikumar,

Thanks for sharing your findings!

The white background comes from the latest Horizon themes updates. From our side, everything is according to the specification and the correct parameter is used, so  we are waiting for parameters values update from design side and then the result will be the expected one.
As we are according to the specification and there is no issue, I am closing the incident.

Kind Regards,
Niya
