### ISSUE TITLE
Slider Documentation has no general description

### ISSUE THREAD

**Issue by veith** [SAP/ui5-webcomponents#7367]
### **Issue Description**
The [documentation](https://sap.github.io/ui5-webcomponents/playground/?path=/docs/main-slider--docs) for the slider just shows "Overview". This is because the `@tag-name` is already used in `SliderBase`.  The generated cem have both entries and autodoc picks the wrong.

Suggestion: remove the `tag-name` from the base class.

### **Issue Type**

- [ ] Documentation is unclear
- [ ] Documentation is incorrect
- [x] Documentation is missing
- [ ] Other

**Comment by IlianaB** [comment]
Hello @SAP/ui5-webcomponents-topic-rl I am forwarding this issue to you, because it seems Documentation Overview is missing for the Slider, due to tagname duplication with SliderBase.

Regards,
Iliana
