### ISSUE TITLE
[SF_ACC][ui5-list]: No unique accessible name provided for check boxes within the list

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents#7369]
### Bug Description

Check boxes within list do not have unique accessible name.
Repetitive accessible names are provided.

### Expected Behaviour

Accessible name provided for check boxes should be unique. Please include list item text to the accessible name of checkbox.

### Steps to Reproduce

1. Open page https://sap.github.io/ui5-webcomponents/playground/?path=/story/main-list--multi-selection
2. Turn ON Screen Reader JAWS and press keyboard shortcut as 'Insert+ctrl+X' and observe accessible names provided for all check boxes.

### Log Output, Stack Trace or Screenshots

<img width="1274" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/13098801/c2790407-f5dd-46d4-9a5d-8c4c2fb700fd">

### Priority

None

### UI5 Web Components Version

1.15.x

### Browser

Chrome, Edge

### Operating System

windows

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by IlianaB** [comment]
Hello @ui5-webcomponents-topic-p I am forwarding this issue to you, because it seems there are no unique accessible names, provided for checkboxes within list.

Regards,
Iliana

**Comment by yanaminkova** [comment]
Hello @GongRichard,

We already have this request, therefore I am closing this one.
You could track the progress here - https://github.com/SAP/ui5-webcomponents/issues/6861

Best regards,
Yana
