### ISSUE TITLE
[ui5-table]: row-click event doesn't work

### ISSUE THREAD

**Issue by nnaydenow** [SAP/ui5-webcomponents#7375]
### Bug Description

row-click event is not fired

### Affected Component

ui5-table

### Steps to Reproduce

1. https://sap.github.io/ui5-webcomponents/nightly/playground/main/pages/Table/
2. Click on any row inside Test row click table
3. ui5-row-click is not fired

### Priority

None

### UI5 Web Components Version

1.15.1

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ilhan007** [comment]
row-click fired when type is Active, seems this is intended
