### ISSUE TITLE
[theming]: Safari: multiple ui5wc cores can overwrite adoptedStyleSheets

### ISSUE THREAD

**Issue by JarrettChan** [SAP/ui5-webcomponents#7377]
### Bug Description

Safari using the spread operator to copy `document.adoptedStyleSheets` can sometimes return empty array. 
It could work one time then fail when the page is refreshed.
This breaks the ManagedStyles.ts impl when used among multiple ui5wc cores.

console.log(document.adoptedStyleSheets, [...document.adoptedStyleSheets], document.adoptedStyleSheets.slice())

Safari Version 16.5.2 (18615.2.9.11.10)
Using private browsing seems to sometimes avoid the issue.

### Expected Behaviour

Adding stylesheet should not fail to copy the existing stylesheets.

### Steps to Reproduce

1. https://sap.github.io/ui5-webcomponents/playground/?path=/story/fiori-shellbar--basic
2. Inspect iframe so console's document is the iframe document
3. `console.log(document.adoptedStyleSheets, [...document.adoptedStyleSheets])`
Observe: spread operator to copy adoptedStyleSheets returned empty array.

### Log Output, Stack Trace or Screenshots

```
> console.log(document.adoptedStyleSheets, [...document.adoptedStyleSheets])
[Log]  (2)
[CSSStyleSheet] (1)
[] (0)
```

```
// qa env with multiple ui5wc cores
// added numbered logpoints on every assignment to document.adoptedStyleSheets (`document.adoptedStyleSheet=` `document.adoptedStyleSheet =`)
[Log] 5, length 2
[Log] 5, length 3
[Log] 5, length 4
[Log] 5, length 5
[Log] 5, length 6
[Log] 3-after, length 7 // where I placed this log it also executed upon file load
[Log] 3, length 7
[Log] 3-after, length 1
```

### Priority

None

### UI5 Web Components Version

1.15.1

### Browser

Safari

### Additional Context

QA login information in #sap-tech-ui5-wc-sfsf
A specific page in our QA usually has the issue.

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by JarrettChan** [comment]
This issue is more likely to occur with multiple cores on the page, but I've seen the initial ui5wc theme load occasionally fail to copy `document.adoptedStyleSheets`.
When there is the issue, slice can still copy `document.adoptedStyleSheets`.

**Comment by nnaydenow** [comment]
Support of adoptedStyleSheet in Safari was introduced in the previous 16.4 version and seems there is a problem with this feature (https://bugs.webkit.org/show_bug.cgi?id=254844). As a possible workaround until Safari's team resolve the issue you can simply delete the adoptedStyleSheet array using following code: delete Document.prototype.adoptedStyleSheets (execute it as early as possible)

**Comment by ilhan007** [comment]
Hello @JarrettChan
