### ISSUE TITLE
[menu]: Using menu in test environments (Cypress, React Testing library) causes error

### ISSUE THREAD

**Issue by rvsia** [SAP/ui5-webcomponents#7386]
### Bug Description

Hello I am using Cypress to test webcomponents-react menu component

```jsx
        cy.get('[data-cy^="open-menu"]')
            .eq(0)
            .click() // open first menu 
        cy.get('[role="menuitem"]').eq(0).click({ force: true }) // clicks on the first item there
```

This causes following error to happen:

```jsx
TypeError
Cannot read properties of undefined (reading 'close')
Call Stack
 Menu._itemClick
  node_modules/@ui5/webcomponents/dist/Menu.js:351:31
 EventPart.handleEvent
  node_modules/lit-html/development/lit-html.js:1336:35
 List._fireEvent
  node_modules/@ui5/webcomponents-base/dist/UI5Element.js:702:44
 List.fireEvent
  node_modules/@ui5/webcomponents-base/dist/UI5Element.js:687:34
 List.onItemPress
  node_modules/@ui5/webcomponents/dist/List.js:523:19
 EventPart.handleEvent
  node_modules/lit-html/development/lit-html.js:1336:35
 StandardListItem._fireEvent
  node_modules/@ui5/webcomponents-base/dist/UI5Element.js:702:44
 StandardListItem.fireEvent
  node_modules/@ui5/webcomponents-base/dist/UI5Element.js:687:34
 StandardListItem.fireItemPress
  node_modules/@ui5/webcomponents/dist/ListItem.js:179:14
 StandardListItem._onclick
  node_modules/@ui5/webcomponents/dist/ListItem.js:143:14
```

it happens both in Cypress and React Testing Library (Jest) environment

### Affected Component

menu

### Expected Behaviour

No error should appear

### Steps to Reproduce

1. Create a menu component
2. In test environment click on one of the menu item
3. Error appears (in Cypress not always)

### Log Output, Stack Trace or Screenshots

TypeError
Cannot read properties of undefined (reading 'close')
Call Stack
 Menu._itemClick
  node_modules/@ui5/webcomponents/dist/Menu.js:351:31
 EventPart.handleEvent
  node_modules/lit-html/development/lit-html.js:1336:35
 List._fireEvent
  node_modules/@ui5/webcomponents-base/dist/UI5Element.js:702:44
 List.fireEvent
  node_modules/@ui5/webcomponents-base/dist/UI5Element.js:687:34
 List.onItemPress
  node_modules/@ui5/webcomponents/dist/List.js:523:19
 EventPart.handleEvent
  node_modules/lit-html/development/lit-html.js:1336:35
 StandardListItem._fireEvent
  node_modules/@ui5/webcomponents-base/dist/UI5Element.js:702:44
 StandardListItem.fireEvent
  node_modules/@ui5/webcomponents-base/dist/UI5Element.js:687:34
 StandardListItem.fireItemPress
  node_modules/@ui5/webcomponents/dist/ListItem.js:179:14
 StandardListItem._onclick
  node_modules/@ui5/webcomponents/dist/ListItem.js:143:14

### Priority

High

### UI5 Web Components Version

1.15.1

### Browser

Chrome

### Operating System

Test environment 

### Organization

SAP Signavio

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by IlianaB** [comment]
Hello @Lukas742 , @MarcusNotheis , could you please have a look?

Regards,
Iliana

**Comment by nnaydenow** [comment]
Hi @rvsia,

Seems like cypress is clicking the menu item when the popover is still not opened. We have attribute which says when the menu is opened and it will help with your case:

```js
    cy.get('ui5-menu')
      .should('have.attr', "open");
```

I'm also forwarding the issue to the team who maintain the component in order to check if this is an issue at all.

BR,
Nayden

**Comment by rvsia** [comment]
@nnaydenow 

Still the same results to me:

```jsx
        cy.get('ui5-menu').should('have.attr', 'open')
        cy.get('[role="menuitem"]')
            .eq(0)
            .click({ force: true })
```

>>>

```jsx
Cannot read properties of undefined (reading 'close')
```

**Comment by nnaydenow** [comment]
Hi @rvsia,

I'm using the following code and it works to me. Could you please check it?
```js
    cy.get("#btnOpenBasic").click();
    cy.get("#menuBasic").should("have.attr", "open");
    cy.get('[role="menuitem"]').eq(0).click({ force: true }); // clicks on the first item there
```

![image](https://github.com/SAP/ui5-webcomponents/assets/31909318/cbb2c847-0485-4b97-9f45-2ec0379fa1fb)

**Comment by rvsia** [comment]
@nnaydenow That's the same code I used in the comment before - just be aware, this is flaky, it's not failing all the time.

**Comment by tsanislavgatev** [comment]
Hello @rvsia ,

Can you please check again if it's still failing with release 2.0?

Best Regards,
Tsanislav

**Comment by rvsia** [comment]
@tsanislavgatev I can test once we migrate our product there, but as we are using the react version, it will probably take long time.

**Comment by ilhan007** [comment]
Hello @rvsia 

yes, UI5 Web Components For React does not have a release consuming the UI5 Web Components 2.0 yet. 

UI5 Web Components For React team prepares it at the moment, you can follow this issue on their 2.0 progress:

https://github.com/SAP/ui5-webcomponents-react/issues/3857

**Comment by tsanislavgatev** [comment]
Hi @rvsia ,

I saw that the update in ui5-webcomponents-react is done. Do we have any update on your end?

Best Regards,
Tsanislav

**Comment by rvsia** [comment]
@tsanislavgatev 

Hey, yes. We are migrating to version 2 and now it is possible to test Menu component without any issues!

Thanks!
