### ISSUE TITLE
Description of parts

### ISSUE THREAD

**Issue by veith** [SAP/ui5-webcomponents#7388]
### **Issue Description**
In the [documentation](https://sap.github.io/ui5-webcomponents/playground/?path=/docs/docs-customizing-styles--docs) is a good description of how to style parts. When i go to the component documentation, the parts are not documented.  

It would be nice to have the parts documented too.

### **Issue Type**

- [x] Feature request (nice to have)

**Comment by IlianaB** [comment]
Hello @veith,

Could you please help me understand this issue correctly? Is it about a specific component, missing description of the Shadow parts? I can see Shadow parts are described in many components, like button, checkbox, dialog, etc. For, example: https://sap.github.io/ui5-webcomponents/playground/?path=/docs/main-button--docs

Or are you suggesting a small CSS sample to be also added for each component, like it is in the documentation you referred to:
```
ui5-card-header::part(status) {
  color: red;
}
```

Regards,
Iliana

**Comment by IlianaB** [comment]
Hello @SAP/ui5-webcomponents-topic-p, take a look of this feature request for enhancing the customelements-manifest.json.

Regards,
Iliana

**Comment by ilhan007** [comment]
Hello @veith it makes sense to describe the available CSS Shadow parts in more prominent manner.
The request qualifies as a backlog item.
