### ISSUE TITLE
[VizFrame]: Issue with Donut Chart - Data Label Total Percentage is 100.1%

### ISSUE THREAD

**Issue by madhusree4594** [SAP/ui5-webcomponents#7392]
### Bug Description

I am using Donut Chart from VizFrame Charts to display the statuses of the system. By default, I have enabled to display data label, which will show the percentage of each status against total records. When I have tried to add up the percentage of all the statuses, it comes as 100.1%. Attaching the screenshot for reference. In the screenshot, total percentage is 35.5% + 32.3% + 32.3% = 100.1%. Is there any workaround to show as 36% + 32% + 32% = 100%

### Expected Behaviour

Always the total percentage should be 100%

### Steps to Reproduce

1.
2.
3.
...

### Log Output, Stack Trace or Screenshots

<img width="353" alt="2187683-image" src="https://github.com/SAP/ui5-webcomponents/assets/53636255/e590e64d-a677-4b1d-89dd-f3007acab077">

### Priority

Very High

### UI5 Web Components Version

1.116.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by nnaydenow** [comment]
Hi @madhusree4594,

We don't provide this component and by version you've mentioned seems that you wanted to raise an issue for OpenUI5 / SAPUI5. Since I'm not able to transfer your issue please reopen it in the correct repository: https://github.com/SAP/openui5

**Comment by madhusree4594** [comment]
Hi @nnaydenow,

I have created the same ticket in the mentioned repository https://github.com/SAP/openui5. But the ticket is closed with other reasons. Attaching the ticket here
https://github.com/SAP/openui5/issues/3812
