### ISSUE TITLE
[theming]: Color token value for 'sapButton_Selected_Hover_Background' is different than expected.

### ISSUE THREAD

**Issue by irfnkprc** [SAP/ui5-webcomponents#7394]
### Bug Description

When the theme 'sap_horizon' is selected, the variable 'sapButton_Selected_Hover_Background' should ideally be #E3F0FF, as defined in [sap_horizon theme](https://github.com/SAP/fundamental-styles/blob/cf4f0528e77eb27d94f981baf89de80db670fcb8/packages/styles/src/theming/sap_horizon/_css_variables.scss#L349). 
However, what we're observing on our test pages doesn't align with this. The 'sapButton_Selected_Hover_Background' is appearing differently than expected. (#FFFFFF)
[theming-base-content](https://github.com/SAP/theming-base-content/blob/master/content/Base/baseLib/sap_horizon/css_variables.css#L362)
There is an inconsistency between these two implementations.

### Log Output, Stack Trace or Screenshots

Here are the packages we used with their respective versions:

   "@ui5/webcomponents": "^1.14.3",
   "@ui5/webcomponents-fiori": "^1.14.3",
   "@ui5/webcomponents-react": "^1.16.3"

### Priority

Medium

### UI5 Web Components Version

1.14.3

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ilhan007** [comment]
Hello @irfnkprc thank you for pointing this out

We are not really responsible for the values these variables have, it's a different project, maintained by different team - we only consume them as all technologies claiming to implement the SAP Design, are supposed to as  https://github.com/SAP/theming-base-content/ is the source of truth of all SAP Design variables.

But, we are in close contact with SAP Design colleagues, so I will ask about the variable in question and get back to you - it could be that it's already planned to be updated in the next theming-base-content version.

**Comment by irfnkprc** [comment]
Hello @ilhan007 ,

Thank you for getting back to me with that update. It's good to know that the problem is recognized and is being given high priority. I'm looking forward to the next version with the updated variables.

Best regards,
Irfan

**Comment by nnaydenow** [comment]
Hi @irfnkprc,

We've updated the theme-base-content with the latest version (#7571) and now sapButton_Selected_Hover_Background results in #E3F0FF.

Regards,
Nayden
