### ISSUE TITLE
[ViewSettingsDialog]: filter options are not rendered

### ISSUE THREAD

**Issue by claudix** [SAP/ui5-webcomponents#7402]
### Bug Description

The filter options in `ViewSettingsDialog` are displayed blank and selecting them doesn't have any effect in the `confirm` event's details (`"filters":[]`).

### Affected Component

ViewSettingsDialog

### Expected Behaviour

The expected behaviour is the one shown in the [UI5 Web Components playground](https://sap.github.io/ui5-webcomponents/playground/?path=/docs/fiori-viewsettingsdialog--docs), i.e., displaying the filter options.

### Isolated Example

https://6ffcf6.csb.app/

### Steps to Reproduce

1. Go to [https://6ffcf6.csb.app/](https://6ffcf6.csb.app/)
2. Click on "Open ViewSettingsDialog" button.
3. Click on the filter button to change dialog's view to filter tab.
4. Click on any filter (e.g. "Position")
5. As you may see, the filter options only show a checkbox but no text. Also, if you check them all an click OK, the resulting dump of confirm event's details contains an empty filter array (`"filters":[]`)

### Log Output, Stack Trace or Screenshots

This is how the filter options are shown in the isolated example above:

![example](https://github.com/SAP/ui5-webcomponents/assets/5880835/80578dd9-0c2a-489b-a50b-7608dac189a2)

This is how the filter options are shown in the  [UI5 Web Components playground](https://sap.github.io/ui5-webcomponents/playground/?path=/docs/fiori-viewsettingsdialog--docs):

![good](https://github.com/SAP/ui5-webcomponents/assets/5880835/b0f15c53-c346-4a13-b535-a810ba53a156)

### Priority

High

### UI5 Web Components Version

1.15.1

### Browser

Chrome

### Operating System

Windows 10 Pro

### Additional Context

First time observed this issue while following the Getting Started guide. I set up a simple web app using Vite and noticed the component didn't work.

This issue has also been posted on StackOverflow: [https://stackoverflow.com/questions/76820715/filter-checkboxes-appear-blank-in-fioris-viewsettingsdialogs](https://stackoverflow.com/questions/76820715/filter-checkboxes-appear-blank-in-fioris-viewsettingsdialogs)

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by MapTo0** [comment]
Hello @claudix 

You need to import `import "@ui5/webcomponents-fiori/dist/FilterItemOption";` in your js files in order to use the `filter-item-option` component. 

Regards,
Martin

**Comment by claudix** [comment]
Oh, @MapTo0 , so sorry for the inconvenience. I actually read in the docs that if I wanted to use `filterItems` I had to `import "@ui5/webcomponents-fiori/dist/FilterItem"`, but I didn't find any reference to `import "@ui5/webcomponents-fiori/dist/FilterItemOption"` as well... I guess it's obvious, but I'm still a newbie in Web Components! xD.
