### ISSUE TITLE
[storybook]: styles override

### ISSUE THREAD

**Issue by LidiyaGeorgieva** [SAP/ui5-webcomponents#7406]
### Bug Description

When I open the "Docs" section the styles that are applied to the different samples with decorators are applied to all samples.
This produces issues and can be fixed only if iFrame is used.
Sample:  https://sap.github.io/ui5-webcomponents/nightly/playground/?path=/docs/main-card--docs
Issue is reported here - https://github.com/SAP/ui5-webcomponents/issues/7284 "card with table"
This issue is currently fixed, but in future most probably there will be more issues.

### Steps to Reproduce

1.
2.
3.
...

### Priority

None

### UI5 Web Components Version

main

### Browser

Chrome

### Operating System

Windоws

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by LidiyaGeorgieva** [comment]
Hi @SAP/ui5-webcomponents-topic-p,

The temporary fix I made has some bad side effects:
When I change the theme in the StoryBook it is not applied to the iFrame content.
Example with Evening Horizon:
![image](https://github.com/SAP/ui5-webcomponents/assets/7242508/eebe6024-e953-4c71-bf8a-5fd13d81a56a)
Link: https://sap.github.io/ui5-webcomponents/nightly/playground/?path=/docs/main-card--docs&globals=theme:Evening+Horizon

Best Regards,
Lidiya

**Comment by PetyaMarkovaBogdanova** [comment]
Hi @LidiyaGeorgieva ,
I am not sure if applying global styles for a reusable class, without using iframe is a good story writing approach, also
it seems like the iframe workaround indeed has some issues, as the described one with applying the global theme, direction, etc.

I think in the Card particular case (as I also researched is the general approach, working with decorators in stories) is adding a wrapper, holding the width style, as the card has default width: 100%:
<img width="323" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/15124079/12e2a05c-89f2-451a-8935-db636dbbe893">
I will continue researching on extending the iframe approach with access to globals, but for now this is my preposition. 

Best regards,
Petya Markova.
(UI5 WC Developer)

**Comment by ilhan007** [comment]
Hi colleagues, storybook has been replaced - the issue can be closed as not relevant any more.
