### ISSUE TITLE
[Feature Request]: Checkbox component - send component id when onChange event is triggered 

### ISSUE THREAD

**Issue by ajayk0** [SAP/ui5-webcomponents#7408]
### Feature Request Description

Currently, when a checkbox is clicked, the onclick event only returns the new state of the checkbox (i.e., checked or unchecked) without providing the ID of the specific checkbox that was altered. This prevents us from correctly identifying the checkbox. In order to identify the checkbox I would need the onClick event to send the ID of the checkbox.

### Proposed Solution

We request an enhancement to the Checkbox's onclick event , such that it returns not just the new value (checked or unchecked) but also the ID of the altered checkbox. 

### Proposed Alternatives

Provide an event similar to the underlying ui5 CheckBox component. 

### Organization

SAP Build Apps

### Priority

High

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by nnaydenow** [comment]
Hi @ajayk0,

Currently the ui5-checkbox component provides only change event and the click event is natively provided by the HTML element. If you want to extract the current checkbox information from the change event you can simply use the event target.

```js
myCheckbox.addEventListener("change", (e) => {
    console.log(e.target?.id)
})
```

Could you check if this enough information for you?
