### ISSUE TITLE
[Performance | Memory ]: registeredElements Set keeps ref of removed Elements

### ISSUE THREAD

**Issue by nathanbienfait** [SAP/ui5-webcomponents#7413]
### Bug Description

Hello,

In the file packages\base\src\Render.ts a Set named registeredElements (Line 10) seems to keep the reference of all ui5-webcompoenents in the UI to be able to update them in case of theme change or localization change.

But it seems that it also keeps reference of elements already removed from the UI, which prevents the garbage collector  from collecting them. Which causes memory leak.

When debugging this Set, I can see elements having the property _inDOM: false still stored inside.
![image](https://github.com/SAP/ui5-webcomponents/assets/26220418/7a916fad-53ee-4400-af45-efb1d80f439c)

Looking at the source code, in UI5Element.ts it seems that the only way to have this._inDOM to false is pasing through the function disconnectedCallback (Line 209) which is also supposed to remove the element from the Set calling cancelRender() (Line 228). But as show, some elements are still in the Set with the property _inDOM to false, so a problem with the cleaning of the Set seems to exist. Causing huge memory leaks.

### Affected Component

All

### Expected Behaviour

The set should not contain element with property _inDOM: false.

### Steps to Reproduce

Not sure how to reproduce, just using Webcomponents in my case causes this bug

### Priority

High

### UI5 Web Components Version

1.15.1

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by LidiyaGeorgieva** [comment]
Hello @SAP/ui5-webcomponents-team please have a look.

**Comment by nnaydenow** [comment]
Hi @nathanbienfait,

Sorry for the delayed response. I’m unable to reproduce the issue, and when I trace the code, it doesn't seem possible for the problem to exist. `_inDOM` is set to false once the component is disconnected from the DOM and is synchronously excluded from the registry.

It would be helpful if you could share your case (even if it’s internal, just contact me or a team member offline) so we can investigate the issue in more detail.
