### ISSUE TITLE
[Feature Request]: Expose TimeSelection 

### ISSUE THREAD

**Issue by clemai** [SAP/ui5-webcomponents#7414]
### Feature Request Description

Is there any chance to get the 'ui5-time-selection-clocks' or 'ui5-time-selection' component exposed as standard web components as well? If I looked correctly, these components are private right now.

Within our app, we are having a ui5-multi-input component with custom value help popover. Within this popover a date selection (via ui5-calendar) and a time selection shall be possible. 

### Proposed Solution

Like said in the description above, making one of the ui5-time-selection public would prevent us from rebuilding it.

### Organization

SAP SIX Technologies

### Priority

Medium

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by LidiyaGeorgieva** [comment]
Hello @SAP/ui5-webcomponents-topic-b, take a look of this feature request.

**Comment by tsanislavgatev** [comment]
Hello @clemai ,

Did you check the DateTimePicker control? https://sap.github.io/ui5-webcomponents/playground/?path=/docs/main-datetimepicker--docs
It serves a similar purpose to what you are trying to build?

I am currently not aware of plans related to releasing the time selection part as a stand alone public control.

Best Regards,
Tsanislav

**Comment by clemai** [comment]
Hi @tsanislavgatev ,

thanks for looking into it! Yes, I am aware of the DateTimePicker control and we already using it in other places. 

Why we still need the TimeSelection to be exposed is that we want have the DateTimePicker Popover content (Calendar + TimeSelection) wrapped into a TabContainer control within our own Popover, like the following structure:
```
<MultiInput />
<Popover>
  <TabContainer>
     <Tab>
        <Calendar>
        </Calendar>
        <TimeSelection>
        </TimeSelection>
     </Tab>
     <Tab>
        <CustomExtension />
     </Tab>
  </TabContainer>
</Popover>
```

Is exposing the whole DateTimePicker Popover content as separate control an option for you? 
Do you have a any idea or hint for me how build such a popover with the already exposed controls?

**Comment by tsanislavgatev** [comment]
Hello,

As we are still researching if there is a way to make the component public as it currently the time selection component is only a building part for the (Date)TimePicker. A proposal that we can make is to have the DateTimePickerPopover able to be opened by other things than the input, like button. If this proposal doesn't work, we can take it as feature request and continue with the discussions about making it public, which might take some time.

**Comment by clemai** [comment]
Hi, I've not seen your update and this topic is still relevant to us. 

Your proposal doesn't work for us, since we need to have this custom content (e.g. Tab Container) within the Popover.

Could you handle this topic as feature request then?
