### ISSUE TITLE
[Bar]: When using as Dialog Header with a state Border is incorrect

### ISSUE THREAD

**Issue by i832513** [SAP/ui5-webcomponents#7418]
### Bug Description

When we use a <ui5-bar> as the title of a Dialog, and we set a state on the Dialog, the border color of the header is incorrect.

As a work around we implemented a custom Bar React component that we use in place of the Bar, but we much prefer to use the Bar component instead.

### Affected Component

Bar

### Expected Behaviour

When the Bar is placed inside a Dialog as the custom header, the border on the Bar should not interrupt the border added by the Dialog itself.

### Isolated Example

https://codesandbox.io/s/ui5-webcomponents-forked-rt3dcy

### Steps to Reproduce

1. Have a Bar in a Dialog's header slot and make sure to set the state of the Dialog to "error"

### Log Output, Stack Trace or Screenshots

N/A

### Priority

Medium

### UI5 Web Components Version

1.16.0

### Browser

Chrome

### Additional Context

Dialog custom headers will almost universally use a Bar for the header.

### Organization

SuccessFactors

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by LidiyaGeorgieva** [comment]
Hello @SAP/ui5-webcomponents-topic-rd ,

The issue is reproducible and is related to the usage of ui5-bar in ui5-dialog.

Best Regards,
Lidiya

**Comment by s-todorova** [comment]
Hello @i832513,

The issue has been fixed with the linked PR and will be available with the next WC version 1.18.

Best regards,
Siyana
