### ISSUE TITLE
[Left Side Navigation]: Broken responsive behavior

### ISSUE THREAD

**Issue by doruskova** [SAP/ui5-webcomponents#7422]
### Describe the bug

When clicking on collapsed left side navigation menu item with subitems, getting broken empty page. 
This is happening only on MacOS Chrome browser. Same thing is happening in a documentation. 

### Reproduction steps

1. Collapse left side navigation panel
2. Click on nav item that can be expanded with a popover
3. See broken page with a whitespace (only in Chrome, MacOS)
...

### Expected Behaviour

As a user I expect to see a popover with additional sub-items in a left side nav. 

### Screenshots or Videos

https://github.com/SAP/ui5-webcomponents-react/assets/32618096/c8922835-d564-44d3-9381-861b87d4beba

### UI5 Web Components for React Version

v1.18.0

### UI5 Web Components Version

1.15.1

### Browser

Chrome

### Operating System

macOS Ventura 13.5 

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by LidiyaGeorgieva** [comment]
Hello @SAP/ui5-webcomponents-topic-rd
Please have a look at this issue.
In Chrome I can reproduce two behaviors that can be checked:
![image](https://github.com/SAP/ui5-webcomponents/assets/7242508/9435fa03-045a-4a28-9cc6-105ef6cea9fc)
![image](https://github.com/SAP/ui5-webcomponents/assets/7242508/f548c8d0-4937-41e2-af5a-1e1e478fd538)

Tested on Windows with Chrome.

Best Regards,
Lidiya

**Comment by LidiyaGeorgieva** [comment]
Internal BLI created 3099

**Comment by LidiyaGeorgieva** [comment]
@doruskova please issue should be fixed now.
