### ISSUE TITLE
Input - Positive state popover is missing

### ISSUE THREAD

**Issue by victorydsgn** [SAP/ui5-webcomponents#7428]
### Bug Description

Clicking in the input field does not open a message popover. 

### Affected Component

ui5-input

### Expected Behaviour

![Screenshot 2023-08-09 at 12 01 44](https://github.com/SAP/ui5-webcomponents/assets/141809681/3aa986f2-c4c1-4b7e-b837-48c56cad34cf)

### Steps to Reproduce

1.
2.
3.
...

### Priority

Medium

### UI5 Web Components Version

1.16.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by LidiyaGeorgieva** [comment]
Hello @victorydsgn ,

Please provide more information: 
- where do you test? Please give reproducible example.
- give more details why you expect this behavior. In what use case you expect it?

Best Regards,
Lidiya

**Comment by victorydsgn** [comment]
Hello @LidiyaGeorgieva, 

- I am testing it here: https://sap.github.io/ui5-webcomponents/playground/?path=/story/main-input--input-suggestions-value-state-message&args=valueState:Success

- All value states in the input have a popover with a message. When the user clicks in the input it should show up below it like in the screenshot above. The positive state should include it also.

Kind regards

**Comment by elenastoyanovaa** [comment]
Hello @victorydsgn ,

It has always been this way. It was a design decision that a default value state message is not that important for the user and should not be displayed. Please check the value state images here: https://experience.sap.com/fiori-design-web/input-field/

Kind Regards,
Elena
