### ISSUE TITLE
[Side Navigation]: Click on active nav item not triggered when navigation is collapsed 

### ISSUE THREAD

**Issue by doruskova** [SAP/ui5-webcomponents#7431]
### Bug Description

Click on the active tab doesn't do anything when the side panel is in collapsed mode.

### Affected Component

Side Navigation

### Expected Behaviour

As a user I want to have my navigation collapsed and click on the active item so that it can bring me back to the main page . 

### Steps to Reproduce

1. Collapse the side navigation
2. Go to the sub-item page (main page) 
3. Go to a detail's page of the sub-item
4. Click on the sub-item in the popover again to get the main page
5. Nothing happens after clicking on the item
...

### Log Output, Stack Trace or Screenshots

Not being able to click on the selected item to get the main object page. 

https://github.com/SAP/ui5-webcomponents/assets/32618096/21c1a0fc-be54-4c4c-8af4-6ecb20346302

### Priority

Medium

### UI5 Web Components Version

v1.18.0

### Browser

Chrome, Edge, Firefox, Safari

### Operating System

macOS Ventura 13.5 

### Organization

SAP Signavio

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by LidiyaGeorgieva** [comment]
Hello @SAP/ui5-webcomponents-topic-rd ,

Please check if this is part of the new interaction design, which will be implemented soon, or it is separate bug.

Best regards,
Lidiya

**Comment by LidiyaGeorgieva** [comment]
@doruskova ,
Just to clarify: the issue you report is that when you click on the selected sub item, nothing happens and the popover doesn't closes, wright?
If you click on the sub item, which is not selected, the popover closes and this is the expected behavior?

**Comment by doruskova** [comment]
@LidiyaGeorgieva I expect that the selected item is still clickable and takes me to the main page. Now, it's not clickable at all. But, our consultants expect that the link is available all the time. Not only once when the item or subitem is not selected.

**Comment by TeodorTaushanov** [comment]
This issue is fixed in the main branch with #7682
