### ISSUE TITLE
[TextArea]: cannot read properties of null on focus out

### ISSUE THREAD

**Issue by matheushahn** [SAP/ui5-webcomponents#7432]
### Bug Description

For some context, we have a [react virtualized list](http://bvaughn.github.io/react-virtualized/#/components/List) and when I click in one of the items I change the focus of the TextArea.

I debugged the onFocusOut event of the TextArea component and in our case, the relatedTarget is the list, which does not have a shadowRoot and is causing the following issue:
<img width="543" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/15281046/2f587153-9231-4dc6-9bc5-f98594e3cfcf">

This is the [line](https://github.com/SAP/ui5-webcomponents/blob/main/packages/main/src/TextArea.ts#L463) that is causing this issue.

### Expected Behaviour

Can you change this validation to check if the shadow root is present to avoid this issue?

### Priority

None

### UI5 Web Components Version

latest

### Browser

Chrome

### Organization

SAP Language Experience Lab

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by LidiyaGeorgieva** [comment]
Hello @matheushahn ,

Please isolate the issue in sample.
You can use this https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html as starting point.

Best Regards,
Lidiya

**Comment by matheushahn** [comment]
Hi @LidiyaGeorgieva,

Here is one example: https://codesandbox.io/s/ui5-webcomponents-forked-jmcvlk?file=/index.html
The steps to reproduce are:
1. Click in the text area to focus in the element
2. Click in the Blur button
3. You will see the issue
<img width="602" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/15281046/60a0f97b-5070-403a-9881-a46a86323452">

**Comment by LidiyaGeorgieva** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

Please have a look at this issue for Text Area component.

Best Regards,
Lidiya
