### ISSUE TITLE
[TextArea]: Form serialization doesn't work the same as for <textarea>

### ISSUE THREAD

**Issue by MetalCar** [SAP/ui5-webcomponents#7467]
### Describe the bug

The `<TextArea>` component that is provided by ui5 doesn't work like the html `<textarea>` when getting form data within a JS `FormData` object. On my local dev-environment i got also the problem, that my `<TextArea>` value doesn't has entered `\n`.

Please see my isolated example. You can spot the difference easily.

### Isolated Example

https://codesandbox.io/p/sandbox/festive-bassi-j2fx6y

### Reproduction steps

1. Enter in the example in every TextArea a value like
```
A
B
C
```
2. Click on save
3. Check in the Panels the output of the textareas

### Expected Behaviour

The second panel doesn't show any output. I expected that also the second panel shows my output like the others.

### UI5 Web Components for React Version

1.15.1 (local) - ~1.16.0 (in example)

### UI5 Web Components Version

1.13.3 (local) - ~1.18.0 (in example)

### Browser

Chrome, Edge, Firefox

### Operating System

Win11

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by dobrinyonkov** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

Please check why is the text area component ignoring the new lines (`/n`). 

A separated issue is created here for the runtime error: https://github.com/SAP/ui5-webcomponents/issues/7468

Kind Regards,
Dobrin

**Comment by ivoplashkov** [comment]
Hello @SAP/ui5-webcomponents-core ,

The reason for the issue is that the FormSupport uses an Input instead of TextArea (which is multiline) and therefore the value is different.
Could you please provide an API for the FormSupport in order to cover this use case?

Thank you in advance!
Best regards,
Ivaylo
