### ISSUE TITLE
[Panel]: I want to directly style the title

### ISSUE THREAD

**Issue by MetalCar** [SAP/ui5-webcomponents#7471]
### Is your feature request related to a problem?

I want to make the title text in the panel header little bit smaller than `TitleLevel.H6`. But there's no `H7` in HTML 😄 
I spotted a `part`-attribute on the whole header, but the `fontSize` cannot be overwritten.

### Describe the solution you'd like

I would like to use something like the following to style the title
```css
.MyPanelClassName::part(title) {}
```

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by dobrinyonkov** [comment]
Hi @SAP/ui5-webcomponents-topic-rl,

This is a feature request to export a CSS part of the header element to allow custom styles.
Could you please take a look?

Kind Regards,
Dobrin

**Comment by hristop** [comment]
Internal BLI was created: BGSOFUIRILA-3689

**Comment by elenastoyanovaa** [comment]
Hello @MetalCar ,

We have made a code adjustment so now you are able to use the header part to style the title as well.

Kind Regards,
Elena
