### ISSUE TITLE
theming: class="ui5-content-density-compact" doesn't work when used inside another web component

### ISSUE THREAD

**Issue by jcailan** [SAP/ui5-webcomponents#7472]
### Bug Description

I've been playing around with `class="ui5-content-density-compact"` because I wanted to make sure all my web components use `compact` and not the default `cozy`. I noticed that when the web component is directly added in the dom body, this attribute works perfectly fine, however, when it is used directly inside my own custom web component (template), it doesn't work anymore, because the root web component always picks up the default value from the HTML body.

in the screenshot below, you will see that (1) color palette, and (2) test button are all UI5 web components inside my custom web component called `riz-color`. Take particular attention to the inherited CSS styling on `:root` and it shows it's `cozy`! But then look at the class attribute of `ui5-color-palette-item` and `ui5-button` elements which are not being recognized.

<img width="1728" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/27951983/2bb74da0-a896-437d-b2f6-e06152170fcb">

If I add this attribute `class="ui5-content-density-compact"` in the HTML body, then the UI5 web components inside my web component will honor that setting, however, this approach is not possible to do in my use case which is for Custom Widgets in SAC. And since my use case is for custom widgets in SAC, I really need to have the compact density of UI5 web components.

### Steps to Reproduce

1. Clone this repo: https://github.com/jcailan/ui5-wc-content-density-issue
2. Do `npm install` and then run the app using `npm run dev`
3. Click on the `Open` button to display the UI5 web components mentioned above
...

### Priority

None

### UI5 Web Components Version

1.17.0-rc.1

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by dobrinyonkov** [comment]
Hi @jcailan, 

Try setting the `ui5-content-density-compact` class on your custom element `riz-color` as well. This should correctly propagate the compact styles.

Let us know if that works?

Kind Regards,
Dobrin

**Comment by jcailan** [comment]
Hi @dobrinyonkov,

Unfortunately, it didn't work either -- see the screenshot below as proof. 

So you acknowledge that this is a bug in your web component?

<img width="1728" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/27951983/fb542ff9-4474-477f-b19f-2f3d04fb6d2f">

**Comment by jcailan** [comment]
Hi @dobrinyonkov,

You're right -- it worked! This workaround will definitely work for my use case. However, do you acknowledge that this is a bug in the UI5 web component?

**Comment by nnaydenow** [comment]
Hi @jcailan,

It works for me even if I remove the workaround provided by Dobrin. I downloaded your example and everything seems to be correct.

I've also tried to reproduce it in codesandbox but it works as expected there too: https://codesandbox.io/s/ui5-webcomponents-forked-xnwrlk?file=/index.html

Could you please check if it's occurs due to some kind of caching?

Regards,
Nayden
