### ISSUE TITLE
[Feature Request]: Select  customizable options

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents#7478]
### Feature Request Description

As a developer, I would like to have custom select options to achieve specific design, that's not supported by the default SAP Design.
Currently, this is not possible as the available ui5-option component can only display text and can't slot custom mark up and adding styles don't take any effect as the ui5-option is only abstract component that is not actually rendered.

### Proposed Solution

Create new components `ui5-select-menu` that represents the Select's dropdown and can truly slot physical options + `ui5-select-menu-option` that allows entirely custom content and styling

### Organization

SAP Build Apps

### Priority

None

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by petyabegovska** [comment]
FIORITECHP1-28481
