### ISSUE TITLE
ui5-tree-item-custom content div width

### ISSUE THREAD

**Issue by Sergey-Shapovalov** [SAP/ui5-webcomponents#7483]
### Bug Description

When using the ui5-tree-item-custom component, the content slot elements are placed into the ui5-li-tree-text-wrapper div. In the earlier versions (at least in the 1.10 version) the wrapper div had a set of styles, including display: flex and width: 100%. It allowed to have the tree item content across the whole item, placing some elements to the right etc.

In the latest couple of versions the styling has disappeared. As a result, the item content is condensed in the left part of the item.

The old (correct) and new (incorrect) behaviors are displayed in the attached pictures. 

### Affected Component

ui5-tree-item-custom

### Expected Behaviour

It should be possible to use the whole width of the custom tree item to position custom content elements. Probably the ui5-li-tree-text-wrapper div styling should be returned.

### Isolated Example

https://codesandbox.io/s/ui5-webcomponents-forked-w8rth3

### Steps to Reproduce

1. Create a ui5-tree instance
2. Add one or more ui5-tree-item-custom items
3. Place a flex div into the content slot of the tree items, trying to display some content in the right part of the tree item.  

### Log Output, Stack Trace or Screenshots

The correct behavior:
![image](https://github.com/SAP/ui5-webcomponents/assets/6676473/c2866aee-503e-4cba-aa3c-0a8e8ad9510d)

The incorrect behavior:
![image](https://github.com/SAP/ui5-webcomponents/assets/6676473/99d0b53f-da6c-4009-a611-30fe714057b0)

### Priority

None

### UI5 Web Components Version

1.16.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by yanaminkova** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

Could you please have a look at this issue?
Maybe adding additionalText property to the ui5-tree-item-custom resolve this problem as well.

Thanks and Regards,
yana

**Comment by Sergey-Shapovalov** [comment]
I'm afraid the additionalText property wouldn't solve the issue. The whole idea of the custom tree item component is to allow user-defined layout. In my case the item layout includes several fixed-width right-aligned columns. And that used to work in earlier versions of UI5 Web Components.
