### ISSUE TITLE
[Feature Request]:  Enhance the secondaryCalendarType the ui5 configuration

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents#7500]
### Feature Request Description

hi, team

We want to  Enhance the `secondaryCalendarType`  the ui5 configuration.

```html
<script data-ui5-config type="application/json">
{
    "calendarType": "Islamic",
    "secondaryCalendarType": "Islamic"
}
</script>
```

**Background**:

We need to setup the `secondaryCalendarType`  in these components Calendar, DatePicker, DateRangePicker, DateTimePicker, etc  with high level configuration. Currently, the UI5 Web Components seems haven't supported that yet. 

So, We have to wrap these above components and add the default `secondaryCalendarType`  before use it. But we think it's a duplicated with a invasive way.  That's the reason why we have the requirement for enhancing it.

https://sap.github.io/ui5-webcomponents/playground/?path=/docs/docs-advanced-configuration--docs#calendartype

### Proposed Solution

support the 

```html
<script data-ui5-config type="application/json">
{
    "calendarType": "Islamic",
    "secondaryCalendarType": "Islamic"
}
</script>
```

### Organization

SFSF

### Additional Context

We  want to adopt this enhancement at the beginning of b2405.

### Priority

None

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ndeshev** [comment]
Hello @SAP/ui5-webcomponents-core,

Could you please look into this feature request for a global setting for secondary calendar type.

Kind regards,
Nikolay
