### ISSUE TITLE
Switch: "Off" Icon is misaligned in RTL direction 

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#7522]
### Bug Description

The "Off" icon is misaligned when used in right-to-left text direction in Horizon. If `textOff` is used with `Textual` design it looks good, only if an icon is rendered there (`Textual` without `textOff` or `Graphical` design), the issue can be observed.

![image](https://github.com/SAP/ui5-webcomponents/assets/9749730/9b9a40e4-85bc-4cba-86fb-e5db8e69304a)

### Affected Component

Switch

### Isolated Example

https://codesandbox.io/s/ui5-webcomponents-forked-52zjvj?file=/index.html

### Steps to Reproduce

1. Go to [codeSandbox](https://codesandbox.io/s/ui5-webcomponents-forked-52zjvj?file=/index.html)
2. See that the "Off" icons are misaligned

### Priority

None

### UI5 Web Components Version

1.16.0 (occurs in the latest snapshot (0.0.0-235d4ecde) as well)

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ndeshev** [comment]
Hello @sap/ui5-webcomponents-topic-b,  the `ui5-switch` icons are misaligned when used in RTL mode, could you please take a look.

Kind regards,
Nikolay
