### ISSUE TITLE
List with lengthy text getting truncated with ellipses and not showing tooltip to see complete text

### ISSUE THREAD

**Issue by Harshithagc18** [SAP/ui5-webcomponents#7524]
### Is your feature request related to a problem?

List with lengthy text getting truncated with ellipses and not showing a tooltip to see the complete text. In most cases, we have scenarios to show the complete text in the next line instead of showing it with an ellipse as it doesn't give complete information to the user.

![image](https://github.com/SAP/ui5-webcomponents-react/assets/105646889/55da78bb-9b9e-4ba7-936f-fc9c8037e81f)

### Describe the solution you'd like

It would be good to show the entire text accumulating in a new line instead of showing truncated text with ellipses.

![image](https://github.com/SAP/ui5-webcomponents-react/assets/105646889/e2307770-d0b5-41d6-adbc-49f9f308f0df)

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by dimovpetar** [comment]
Hello @SAP/ui5-webcomponents-topic-p, 

Take a look of this feature request for StandardListItem.

Best regards,
Petar

**Comment by plamenivanov91** [comment]
Hello @Harshithagc18 ,

I looked into the issue and it seems that the `ui-li` already has the `title` property which is used for tooltip.

So basically if you copy/paste your description text into the title attribute, you should have your desired tooltip.

Is this sufficient solution for you ?

Regards,
Plamen
