### ISSUE TITLE
[Feature Request]: Support large design to ObjectStatus

### ISSUE THREAD

**Issue by 2bno1** [SAP/ui5-webcomponents#7536]
### Feature Request Description

Per the Visual Core Doc (https://wiki.one.int.sap/wiki/pages/viewpage.action?pageId=2698914826), ObjectStatus should support "Large Design" in which icon and text are visually different from default.
<img width="1300" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/1751846/a7f9bf8f-5907-4116-b6c5-aefa58d7bc25">

### Proposed Solution

ObjectStatus supports "Large Design"

### Organization

SuccessFactors

### Priority

Medium

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ndeshev** [comment]
Hello @2bno1, there is no ObjectStatus UI5 Web Component yet, do you mean the sap.m.ObjectStatus in UI5 Classic? If so, you should create a pull request in OpenUI5 repository.

**Comment by 2bno1** [comment]
@ndeshev Sorry, I should create the ticket to @ui5/webcomponents-react.
