### ISSUE TITLE
[ui5-select-menu]: dropdown is misplaced when parent container is small in Firefox

### ISSUE THREAD

**Issue by blikblum** [SAP/ui5-webcomponents#7543]
### Bug Description

In firefox, when showing a select-menu dropdown in a parent container that does not have enough height, the dropdown is misplaced.

In chrome, works fine

### Affected Component

ui5-select-menu

### Expected Behaviour

The dropdown (select-menu) should show below select

### Isolated Example

https://sap.github.io/ui5-webcomponents/playground/?path=/docs/main-select--docs#custom-options

### Steps to Reproduce

1. In Firefox, go to https://sap.github.io/ui5-webcomponents/playground/?path=/docs/main-select--docs#custom-options
2. Try to open the dropdown
...

### Priority

None

### UI5 Web Components Version

1.17.0

### Browser

Firefox

### Operating System

Windows

### Additional Context

Works fine when parent have enough height: https://sap.github.io/ui5-webcomponents/playground/?path=/story/main-select--custom-options 

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by nnaydenow** [comment]
Hi @blikblum,

Thanks for reporting the issue! This was sample issue and it was fixed with https://github.com/SAP/ui5-webcomponents/pull/7553.

Regards,
Nayden
