### ISSUE TITLE
[input]: Incorrect background color in morning theme

### ISSUE THREAD

**Issue by Dolimont** [SAP/ui5-webcomponents#7546]
### Bug Description

Input components in morning theme are not using the right theme.
Here's the current L&F : 

![image](https://github.com/SAP/ui5-webcomponents/assets/28103058/ad1c7ca5-00c9-4092-9249-9199037d9f2d)

And here's the spec : 

![image](https://github.com/SAP/ui5-webcomponents/assets/28103058/2a132439-97df-4ca4-99eb-ec198a1e2e5f)

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by dimovpetar** [comment]
Hello @ui5-webcomponents-topic-rl,

Currently the background is grey, but white is expected. Please check https://sap.github.io/ui5-webcomponents/nightly/playground/?path=/story/main-input--basic.

Best regards,
Petar

**Comment by ivoplashkov** [comment]
Hello, 

We do not consider this to be an issue, as the Input is using the correct theme parameters.
The picture in the spec is kinda of blury, but if you compare it to the hover state you may notice it's "grey-ish".

Best regards,
Ivaylo
