### ISSUE TITLE
[Input][A11Y]: 1. count of suggestions is not correct when having SuggestionGroupItem, 2. speech for available suggestions is misleading

### ISSUE THREAD

**Issue by yzy415** [SAP/ui5-webcomponents#7552]
### Describe the bug

1. Currently, the count of SuggestionGroupItem will be included in the total count of the suggestion items. However, it's not true. As shown in the pic below, we only have 6 valuable suggestions separated into 2 groups. But the screen reader will read the count as 8.
2. The 'result' in '8 results available' is also not accurate enough because they are actually suggestions. In our situation, we use the suggested keywords to search for the results, and the count of suggestions will be most time inconsistent with the real results.  It will mislead users that there are 8 results after a search.

<img width="1231" alt="Pasted Graphic copy" src="https://github.com/SAP/ui5-webcomponents-react/assets/53516646/1394dd81-bf17-4346-96b5-9215944b0bcb">

### Isolated Example

https://sap.github.io/ui5-webcomponents-react/?path=/story/inputs-input--with-suggestion-item

### Reproduction steps

1. type anything
2. and the screen reader will speak like: '8 results available'

### Expected Behaviour

1. The count of SuggestionGroupItem should be excluded
2. '8 results available' should be replaced with '8 suggestions available'

### Screenshots or Videos

<img width="1231" alt="Pasted Graphic copy" src="https://github.com/SAP/ui5-webcomponents-react/assets/53516646/03dad610-9b92-416d-874b-297bcdb66f4a">

### UI5 Web Components for React Version

1.18.0

### UI5 Web Components Version

1.16.0

### Browser

Chrome

### Additional Context

I'm from SAP SF

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by dimovpetar** [comment]
Hello @ui5-webcomponents-topic-rl,

Please check out this issue.
Point 1 differs from OpenUI5, where the groups are not included into the total count.
For point 2, however, the ui5-input behaves the same in OpenUI5's.

Best regards,
Petar
