### ISSUE TITLE
[SF][A11Y][Switch]: Interactive Controls Must not Be Nested

### ISSUE THREAD

**Issue by rama1990br** [SAP/ui5-webcomponents#7554]
### Bug Description

Hi Team,
The following issue related to `ui5-switch` component is seen when running "axe Dev Tools" browser extension to scan the page to test a11y issues. Please take a look. Thanks!

<img width="1680" alt="Screenshot 2023-09-05 at 4 28 12 PM" src="https://github.com/SAP/ui5-webcomponents/assets/32254036/9b984620-c6b4-4e26-86ed-e15f6b3f62a3">

### Affected Component

Switch

### Expected Behaviour

We shouldn't be getting the above a11y error.

### Isolated Example

https://sap.github.io/ui5-webcomponents/nightly/playground/main/pages/Switch/?sap-ui-theme=sap_horizon

### Steps to Reproduce

1. Go to https://sap.github.io/ui5-webcomponents/nightly/playground/main/pages/Switch/?sap-ui-theme=sap_horizon 
2. Add chrome extension "axe devTools"
3. Scan the entire page

You can find more information on this issue here:
https://dequeuniversity.com/rules/axe/4.5/nested-interactive?application=axeAPI

### Priority

None

### UI5 Web Components Version

1.17.0

### Browser

Chrome

### Operating System

Mac OS Ventura 13.4.1

### Organization

SAP SuccessFactors

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by dimovpetar** [comment]
Hello @SAP/ui5-webcomponents-topic-b ,

Please take a look at this reproducible issue. It looks the same as https://github.com/SAP/ui5-webcomponents/issues/7419 

Best regards,
Petar

**Comment by rama1990br** [comment]
Hi @dimovpetar,
Can we please get an update on this ticket?

**Comment by tsanislavgatev** [comment]
Hello @rama1990br ,

Your issue is in the dev team that's working on switch and we will get back to you once we have more information.

Best Regards,
Tsanislav

**Comment by hinzzx** [comment]
Hello @rama1990br ,

I runned the Axe DevTool both locally and on the [dev samples page](https://sap.github.io/ui5-webcomponents/nightly/packages/main/test/pages/Switch.html), with **Best Practicses mode** **_On_** and **_Off_**, following standard **WCAG 2.1 AA** and the reported issue is no longer reproducible.

Best Regards,
Stoyan
