### ISSUE TITLE
[Breadcrumb Navigation]: The breadcrumb navigation feature does not appear to be rendering correctly in the Firefox browser, despite an adequate amount of available screen space.

### ISSUE THREAD

**Issue by shouryaa28** [SAP/ui5-webcomponents#7556]
### Bug Description

In our application, we have implemented dynamically created UI5 breadcrumbs to enhance user navigation. We have encountered an issue with this feature when it comes to the Firefox browser. Despite having sufficient amount of space, the UI5 breadcrumbs fail to display correctly in Firefox. This problem is not present in other browsers such as Edge and Chrome, where the functionality operates as expected.

This is the result in edge/chrome browser - 

![MicrosoftTeams-image (7)](https://github.com/SAP/ui5-webcomponents/assets/75392661/ed980c32-7521-49d6-8073-69414742478e)

And this is the result in firefox browser - 

<img width="870" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/75392661/74b841c7-6690-47d9-a9bc-d0bc9dcb3f61">

### Expected Behaviour

The behavior of Firefox browser should be like this : 
![image](https://github.com/SAP/ui5-webcomponents/assets/75392661/edd75d10-7b38-4312-9d9f-e6b6570ad633)

### Priority

None

### UI5 Web Components Version

1.15.1

### Browser

Firefox

### Additional Context

SAP Build Actions

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by dimovpetar** [comment]
Hello @shouryaa28 ,

I cannot see a difference between Chrome and Firefox in the official samples https://sap.github.io/ui5-webcomponents/playground/?path=/story/main-breadcrumbs--separator-style
Please provide an isolated example where we can reproduce the issue. For example in https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html 

Best regards,
Petar
