### ISSUE TITLE
Notification badge is partially hidden due to UI5 version upgrade

### ISSUE THREAD

**Issue by surjadeep** [SAP/ui5-webcomponents#7559]
### Bug Description

Notification badge is partially hidden when UI page is loading. Currently, the version of "@ui5/webcomponents", "@ui5/webcomponents-base", "@ui5/webcomponents-fiori", "@ui5/webcomponents-icons", and "@ui5/webcomponents-localization" is 1.14.5, and the version of "@ui5/webcomponents-react" and "@ui5/webcomponents-react-base" is 1.16.3. Before UI5 version upgrade, the versions are 1.13.3 and 1.15.1. After UI5 version upgrade <ShellBar> component's notification badge position has a little bit change, and it causes this issue.

In the screenshot below, the notification badge above the bell icon is partially hidden when UI page is loading, and there is a little bit space between notification badge and bell icon.
![image](https://github.com/SAP/ui5-webcomponents/assets/12830367/e6a73222-d479-4862-9581-afd85864b5e6)

### Affected Component

Loader, ShellBar, Badge

### Expected Behaviour

![image](https://github.com/SAP/ui5-webcomponents/assets/12830367/d10bcfed-9421-4377-9523-c7a82f583a9e)

### Steps to Reproduce

1.
2.
3.
...

### Priority

High

### UI5 Web Components Version

1.14.5

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by dimovpetar** [comment]
Hello @surjadeep ,

Is this the ShellBar component? Can you confirm that the same bug exists in this sample https://sap.github.io/ui5-webcomponents/playground/?path=/story/fiori-shellbar--search-and-notifications&globals=theme:Quartz+Light?

Best regards,
Petar

**Comment by surjadeep** [comment]
Hello @dimovpetar,

The issue occurs when a loader component is showing which blocks the notification badge in shellbar component.

Regards,
Surjadeep

**Comment by dimovpetar** [comment]
Hello @surjadeep ,

The issue might be coming from this loader that overlaps the ShellBar component. It is still not clear where exactly the issue comes from. Please provide detailed steps how to reproduce the issue. Ideally, provide an isolated example in [codesandbox](https://codesandbox.io/s/ui5-webcomponents-forked-0ucgkz?file=/index.html)

Best regards,
Petar

**Comment by surjadeep** [comment]
Hello @dimovpetar,

I have asked the dev team to provide the same, will attach here once I get it.

Regards,
Surjadeep
