### ISSUE TITLE
Drag & Drop into Tree & TreeTable components to change position of Leaf nodes

### ISSUE THREAD

**Issue by surjadeep** [SAP/ui5-webcomponents#7562]
### Feature Request Description

We would need ability to drag and drop into Tree and TreeTable component to change the position of leaf nodes.
This will enable us to assign / de-assign configuration activities with different business scenarios.

### Proposed Solution

User should be able to drag and drop desired leaf node entities in Tree and TreeTable components.

### Organization

CBC

### Priority

High

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by dimovpetar** [comment]
Hello @ui5-webcomponents-topic-p,

Please take a look at this feature request regarding Drag & Drop.

Best regards,
Petar

**Comment by dobrinyonkov** [comment]
Upon further look, there is a visual design which the tree component must address in order to support the Drag and Drop visual Fiori specifications. We will discuss this in our upcoming planning meeting.

**Comment by dobrinyonkov** [comment]
Internal BLI: BGSOFUIPIRIN-6357
