### ISSUE TITLE
[Input]: [Cannot enter space or Enter when the Input is rendered within the Tree]

### ISSUE THREAD

**Issue by jamesPodo** [SAP/ui5-webcomponents#7566]
### Describe the bug

cannot type space on input field when the Input is rendered in Tree.
There was a similar issue on Header Input with List.
https://github.com/SAP/ui5-webcomponents/issues/4049
Could you please fix the issue? Thank you!

### Reproduction steps

1.
2.
3.
...

### UI5 Web Components for React Version

1.16.0

### UI5 Web Components Version

1.14.0

### Browser

Chrome

### Operating System

Mac

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by NHristov-sap** [comment]
Hello @ui5-webcomponents-topic-rl,
I am forwarding this issue to you as the reported issue is reproducible. There is [solution proposal](https://codesandbox.io/s/ui5-webcomponents-forked-yqgjyx?file=/src/index.js) by @Lukas742 , but please check if this can be done in the component itself.

Best Regards,
Nikolay Hristov
