### ISSUE TITLE
[SF_ACC][Feature Request]: Enable configure the accessible name of custom panel header icon button

### ISSUE THREAD

**Issue by ksblklu** [SAP/ui5-webcomponents#7578]
### Feature Request Description

Hi team
When we have several panel with custom header on page, we expected unique accessible name for each panel header icon button. Currently the accessible name of panel header icon button is defined internally, hence we want to change each icon button's accessible name via panel property.

### Proposed Solution

Enable changing the accessible name of custom panel header icon button
<img width="1722" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/27538066/5207dad3-abba-4790-a6de-4ba9d3aa6bcc">

### Organization

SuccessFactors

### Priority

Medium

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by NHristov-sap** [comment]
Hello @SAP/ui5-webcomponents-topic-rl, 

Please take a look of this feature request.

Best Regards,
Nikolay Hristov
