### ISSUE TITLE
[ViewSettingsDialog | ui5-webcomponents] onConfirmEvent uses filter item text as key:

### ISSUE THREAD

**Issue by 22shubham22** [SAP/ui5-webcomponents#7579]
### Bug Description

Whenever filter items are selected inside ViewSettingsDialog and OK button is pressed an event is fired in which we see that there is key object pair , 

where key is -> text provided for filter item
object is -> an array of all the filter item options selected

We have give text as "Position" to the filter item -> 

<img width="262" alt="MicrosoftTeams-image (16)" src="https://github.com/SAP/ui5-webcomponents/assets/60786471/e30f48a8-cb10-45f9-8295-5cb0708082de">

and as you can see it appears in the view settings dialog 

<img width="181" alt="MicrosoftTeams-image (15)" src="https://github.com/SAP/ui5-webcomponents/assets/60786471/e84aa66b-aaa6-441d-bd34-c3e30a967ddc">

Now when we select, any of the filter item options : 

<img width="176" alt="MicrosoftTeams-image (17)" src="https://github.com/SAP/ui5-webcomponents/assets/60786471/f4c33dc1-85eb-4431-8821-28cc81a8d263">

and console log the event details :  

<img width="304" alt="MicrosoftTeams-image (19)" src="https://github.com/SAP/ui5-webcomponents/assets/60786471/263ff0b0-8676-40c5-afe3-3244dd56a36f">

<img width="83" alt="MicrosoftTeams-image (18)" src="https://github.com/SAP/ui5-webcomponents/assets/60786471/ac63d6ac-072e-47d2-a075-0f4d401d93d7">

So basically in our code if we want to pickup the filters we do it by : 

event.detail.filters[0]["Position"] ,
which seems fine if we just work with english , but in our project we support multiple languages, so when we change the language from english to french , then position gets translated to something else and then when pressed OK the event fired contain that translated text as key. 

So, event.detail.filters[0]["Position"] this would not work anymore if we try to pick filters from the event, because now the text is translated . 

Code Sandbox Link : https://codesandbox.io/s/ui5-webcomponents-forked-jxn5xt?file=/src/index.js

### Expected Behaviour

it'd be btter if the even generated would look for 'id' or 'key' as a first option rather than 'text'.

### Steps to Reproduce

1.
2.
3.
...

### Priority

Medium

### UI5 Web Components Version

1.15.1

### Browser

Chrome

### Additional Context

"@ui5/webcomponents": "1.15.1",
"@ui5/webcomponents-base": "1.15.1",
"@ui5/webcomponents-fiori": "1.15.1",
"@ui5/webcomponents-icons": "1.15.1",
"@ui5/webcomponents-icons-business-suite": "1.15.1",
"@ui5/webcomponents-localization": "1.15.1",
"@ui5/webcomponents-react": "1.17.3",
"@ui5/webcomponents-theming": "1.15.1",

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by NHristov-sap** [comment]
Hello @SAP/ui5-webcomponents-topic-b,

Please take a look of this feature request.

Best Regards,
Mikolay Hristov

**Comment by 22shubham22** [comment]
Hi @hinzzx , By when can we expect this to be done ?

**Comment by DMihaylova** [comment]
Hello, @22shubham22,

Thank you for the feedback!

We'll need to firstly discus it on our team refinement meeting and then prioritise it among the rest of the requests we have.
We'll update you here once those aspects get clear. Have in mind that we're currently overloaded and there may be delay.

Thanks & Regards,
Diana
