### ISSUE TITLE
Styles not loading correctly in Safari browser 

### ISSUE THREAD

**Issue by JonasDutzi** [SAP/ui5-webcomponents#7581]
### Bug Description

Hi colleagues,
in our application we make use of the ui5-webcomponents-react library to display a custom diagram. Currently we are facing an issue where the diagram does not load correctly in our deployed systems (so only after the react app was built for production) when opening the app in Safari browser (all other browsers like chromium-based and Firefox work). The issue is not consistently showing up so sometimes it works and sometimes not. In the browser console I found the following log in the case of where the ui5 styling was missing:
```Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'document.adoptedStyleSheets.find(function(e){return e._ui5StyleId===nt(t,r)}).replaceSync')```

I found in this github repo the code that might lead to this issue and therefore create this issue here: https://github.com/SAP/ui5-webcomponents/blob/0690e5142d10832584a4b485114280f0edd76424/packages/base/src/ManagedStyles.ts#L38

Do you have any idea why this issue occurs and how it can be fixed?

Best regards,
Jonas
 

### Steps to Reproduce

1.
2.
3.
...

### Priority

High

### UI5 Web Components Version

1.9.3

### Browser

Safari

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by nnaydenow** [comment]
Hi @JonasDutzi,

Our playground (https://sap.github.io/ui5-webcomponents/playground/?path=/docs/main-button--docs) uses the same logic but with newer version and the issue seems to not be reproducible.

Could you please try to prepare minimal reproducible example in our codesandbox skeleton (https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html) so we can investigate your issue?

Regards,
Nayden

**Comment by JonasDutzi** [comment]
Workaround suggested by @nnaydenow as long as https://bugs.webkit.org/show_bug.cgi?id=254844 is not included/fixed in Safari browser:

```
import { isSafari } from "@ui5/webcomponents-base/dist/Device";
if (isSafari()) {
    delete Document.prototype.adoptedStyleSheets;
}
```
Thanks for your help! :)
