### ISSUE TITLE
Input Suggestions are not working correctly when using custom elements scoping suffix

### ISSUE THREAD

**Issue by schempil** [SAP/ui5-webcomponents#7583]
### Bug Description

Showing suggestions for an input is not working correctly and without errors after setting an custom elements scoping suffix in our application.

### Affected Component

Input, SuggestionItem

### Expected Behaviour

I expect that also while using a custom elements scoping suffix the suggestion items are still working as before.

### Isolated Example

https://codesandbox.io/s/ui5-webcomponents-forked-g94wkj?file=/src/index.js

### Steps to Reproduce

1. Check the error in the provided sandbox example

### Log Output, Stack Trace or Screenshots

![image](https://github.com/SAP/ui5-webcomponents/assets/7802273/6185a8eb-4fd8-46c8-96dc-848030037f47)

### Priority

High

### UI5 Web Components Version

1.17.0

### Browser

Chrome

### Operating System

Mac OS

### Organization

SAP SE

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @schempil 

for reference I also include my findings I shared in [Slack](https://openui5.slack.com/archives/CSQEJ2J04/p1694609408715539) here as well:

The order of the side-effect imports is causing this issue. You have to make sure that the `features/InputSuggestions`  import is executed before the component import:

https://codesandbox.io/s/ui5-webcomponents-forked-nqy5c7?file=/src/index.js

**Comment by schempil** [comment]
Thanks @Lukas742!
This helped.

Does it make sense to document that in the docs? Or did I just miss the part? 😄

**Comment by NHristov-sap** [comment]
Hello @SAP/ui5-webcomponents-topic-rl, 

Please check and evaluate the proposal for documentation update on this topic/issue.

Best Regards,
Nikolay Hristov

**Comment by elenastoyanovaa** [comment]
Hello @schempil ,

Actually this is already documented here: https://sap.github.io/ui5-webcomponents/playground/?path=/docs/docs-getting-started-using-features--docs for the framework-level features, but it is the same for all of them in my opinion. The code related to suggestions is checking if the feature is registered in order to use it.

Kind Regards,
Elena
