### ISSUE TITLE
[SF_ACC][Feature Request]: Support changing the additional instruction of List

### ISSUE THREAD

**Issue by ksblklu** [SAP/ui5-webcomponents#7595]
### Feature Request Description

When List have only one list item, screenreader announced as "To move to an item press the Arrow keys", we expect the instruction text to be removed when there is only on list item.

1. Go to https://codesandbox.io/p/sandbox/goofy-lamport-yfytwd?file=/src/App.tsx:28,76
2. Use keyboard arrow key to navigate the list litems with JAWS
3. Observe the instruction label "To move to an item press the Arrow keys" was presented, but there is only one list item
<img width="1683" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/27538066/65d3bf36-ce43-455c-9c1a-08452d045790">

### Proposed Solution

Support remove list navigate instruction label "To move to an item press the Arrow keys" when there is only one item presented.

### Organization

SuccessFactors

### Priority

Medium

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by plamenivanov91** [comment]
Hello @SAP/ui5-webcomponents-topic-p, take a look of this feature request

**Comment by yanaminkova** [comment]
Hello @ksblklu,

This is expected screen reader behaviour and can`t be controlled from our side.

Regards,
Yana
