### ISSUE TITLE
[SF_ACC] [Input] Clear icon is being read as "Decline"

### ISSUE THREAD

**Issue by bonniegso** [SAP/ui5-webcomponents#7600]
### Bug Description

The clear icon on an Input component with show-clear-icon defined is being read as "Decline" by screen readers which is misleading to users since the button is meant for clearing the field. This is because the aria-label set on the close icon svg is set to "Decline". This can be resolved by either setting the aria-label to "Clear" or allowing this aria-label to be customizable by consumers.

### Affected Component

Input

### Expected Behaviour

The expected behavior is for the button to announce "Clear" on focus.

### Isolated Example

https://lgww49.csb.app/

### Steps to Reproduce

1. Turn on JAWS Screenreader
2. Open example in a browser
3. Type something into the input field
4. Using your keyboard navigate to the "x" button in the input field
5. Observe that "Decline" is read

### Priority

Medium

### UI5 Web Components Version

1.14.5

### Browser

Chrome

### Operating System

MacOS 13.5.2

### Organization

SAP SuccessFactors

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by plamenivanov91** [comment]
Hello @bonniegso ,

How exactly do you navigate to the clear button since it can't be focused?

Regards,
Plamen

**Comment by bonniegso** [comment]
Hi @plamenivanov91 ,

You can navigate to the button using virtual cursor mode on JAWS. You can toggle the virtual cursor by pressing Insert + Z. If using VoiceOver, you can access it via the Control + Option + Left/Right Key.

Best,
Bonnie

**Comment by elenastoyanovaa** [comment]
Hello @SAP/ui5-webcomponents-topic-rl ,

The accessible name of the clear icon should be changed to "Clear". Also the icon role should be changed to button.

Kind Regards,
Elena
