### ISSUE TITLE
[SF_ACC] [ComboBox]: Error value state is not announced when it's focused

### ISSUE THREAD

**Issue by 2bno1** [SAP/ui5-webcomponents#7602]
### Bug Description

When the focus move to the error value state, it is not announced.
I'm not able to recording. To reproduce this issue, you can use the sample in https://sap.github.io/ui5-webcomponents/playground/?path=/docs/main-combo-box--docs and set `valueState` prop to `Error`. And then open the pick list and move the focus to the error value state. Notice that nothing is announced when focus is moved onto the error value state.

<img width="281" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/1751846/8a364d78-6e8b-4c31-adff-7b5b5d84701c">

### Affected Component

ComboBox

### Expected Behaviour

The error value state message should be announced when it's get focused.

### UI5 Web Components Version

1.17.0

### Browser

Chrome

### Additional Context

Screen Reader: JAWS, 2023.2306.38

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by plamenivanov91** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

If you click on the error state message it gets read correctly, but if you end up on it while navigating with the arrow keys while the dropdown is opened - nothing is read.

Could you please take over?

Regards,
Plamen
