### ISSUE TITLE
Button: The button component is missing a way to add accessible role of link

### ISSUE THREAD

**Issue by ekeyur** [SAP/ui5-webcomponents#7612]
### Describe the bug

Many time buttons and links are used interchangeably, We need a way to add an accessible role of link to button if it actually behaves as a link.

### Reproduction steps

1.
2.
3.
...

### Expected Behaviour

Just need a way to add role of a link to the button component. 

### UI5 Web Components for React Version

1.17.3

### UI5 Web Components Version

1.15.1

### Browser

Chrome, Edge, Firefox, Safari

### Operating System

MAC OS

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by plamenivanov91** [comment]
Hello @SAP/ui5-webcomponents-topic-b,

The app developer would like to have the option to add an accessible role of link to button.

Is this feasible feature request? Can you please take over?

Regards,
Plamen Ivanov

**Comment by tsanislavgatev** [comment]
Hello colleagues,

This is a feature request. We have the same functionality in openui5.
Can you please check and evaluate this feature.

Best Regards,
Tsani

**Comment by ekeyur** [comment]
Can  this functionality  be implemented on ui5-webcomponents-react as well, since that is the library we are now using.

**Comment by Lukas742** [comment]
Hi @ekeyur 

since UI5 Web Components for React only wraps ui5 web components, all features and bug fixes will be available out of the box. When a new `@ui5/webcomponents` minor version is available, we will update our project (`@ui5/webcomponents-react`) timely to support the new version. (Usually this only a few days at most)
