### ISSUE TITLE
[SF][Wizard] native scrollbar styles not applied to Wizard component

### ISSUE THREAD

**Issue by ksblklu** [SAP/ui5-webcomponents#7617]
### Bug Description

class "ui5-content-native-scrollbars" not added to Wizard component root element

### Affected Component

Wizard

### Expected Behaviour

style "ui5-content-native-scrollbars" should be correctly added to Wizard component shadow root element

### Isolated Example

https://codesandbox.io/p/sandbox/suspicious-tesla-gvl8sv?file=/src/App.tsx:129,14

### Steps to Reproduce

1. Go to https://codesandbox.io/p/sandbox/suspicious-tesla-gvl8sv?file=/src/App.tsx:129,14
2. Inspect the wizard component root element, class "ui5-content-native-scrollbars" is not present
3. Inspect the List component root element, class "ui5-content-native-scrollbars" is present.
4. Wizard should have same behavior with list, when class "ui5-content-native-scrollbars" is added to the document body.
<img width="1703" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/27538066/db1c7721-55c1-4f7f-aeda-866457fbfd0a">
<img width="1715" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/27538066/27a8a9be-ecd6-464d-a72b-d10422dfb19e">

### Priority

Medium

### UI5 Web Components Version

1.17.0

### Browser

Chrome

### Operating System

MacOS

### Organization

SuccessFactors

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by elenastoyanovaa** [comment]
Hello @SAP/ui5-webcomponents-topic-rl ,

We should take in account, whether the "ui5-content-native-scrollbars" class is added to the root of a page using ui5-webcomponents and the wizard component. As far as I can see, we need to use the getEffectiveScrollbarStyle util in the wizard component. Please check TextArea for example implementation.

Kind Reagrds,
Elena
