### ISSUE TITLE
[ui5-rating-indicator]: a11y - JAWS announcement is misleading when readonly is true but disabled is false

### ISSUE THREAD

**Issue by I585157** [SAP/ui5-webcomponents#7619]
### Bug Description

[ui5-rating-indicator]: a11y - JAWS announcement is misleading for properties readonly is true and disabled is false
Actual behavior: when user tabs to the rating indicator the announcement ends with "to increase or decrease use the arrow keys"

### Affected Component

ui5-rating-indicator

### Expected Behaviour

When the rating indicator has the following property values (readOnly = true, disabled = false) set, the user should not hear an announcement about altering the rating indicator. 

### Isolated Example

https://sap.github.io/ui5-webcomponents/playground/?path=/docs/main-rating-indicator--docs

### Steps to Reproduce

1. Go to https://sap.github.io/ui5-webcomponents/playground/?path=/docs/main-rating-indicator--docs
2. Set the disabled property to false
3. Set the readOnly property to true
4. Start JAWS 2023
5. Tab to the rating indicator
...

### Priority

None

### UI5 Web Components Version

1.17.0

### Browser

Chrome

### Operating System

Mac OS

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by elenastoyanovaa** [comment]
Hello,

This is the expected behavior of the screen reader software and it is an automatic message coming from the role assigned. This is reproducible also with native element - just create an element with role="slider" and set aria-readonly="true" and you will see that this is read out exactly the same. Not related to web components.

Kind Regards,
Elena

**Comment by I585157** [comment]
@elenastoyanovaa, if the rating indicator component can be set to be readOnly and enabled would it be reasonable to request that the role of slider not be included on the element in this case given that the role, when the rating indicator is readOnly, produces the automatic message that is misleading?
