### ISSUE TITLE
Active/Selected state for ColorPaletteItem component

### ISSUE THREAD

**Issue by nodari-dev** [SAP/ui5-webcomponents#7622]
### Is your feature request related to a problem?

Hi, currently we are implementing ColorPaletteItem component into one of our pages and we found that this component does not have an active state. We want to click on it and make a active state persistent according to our business logic like this:
```javascript
const [isActive, setActive] = useState(false)

<ColorPaletteItem
    value={"red"}
    active={isActive}  // or selected={isActive}
/>
```

We checked design guidelines for ColorPalette and ColorPaletteItem, [see it here](https://wiki.one.int.sap/wiki/pages/viewpage.action?pageId=2698913198) (check States comparison section), and ColorPaletteItem has states:
 1. Focused 
 2. Selected

Currently only Focused state was implemented, so we the second as well

### Describe the solution you'd like

Implement Active/Selected state to show outline not only on focus

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by elenastoyanovaa** [comment]
Hello,

This is rather an issue with the textual information from the visual wiki, not a functionality of the components, which is not yet implemented. If you check the fiori guidelines https://experience.sap.com/fiori-design-web/color-palette/ it is clearly stated that the selected color is not visualized.

> Guidelines
Show the selected color in another place. The color palette does not visualize the selected color.

Kind Regards,
Elena
