### ISSUE TITLE
Calculation error in SliderBase results in no updated labels

### ISSUE THREAD

**Issue by veith** [SAP/ui5-webcomponents#7628]
### Bug Description

If you increment or decrement the `min` and `max`  value for the same amount, the result for `newNumberOfLabels` will always be the same. This results in no update of the labels. 

SliderBase.ts *line 631* in method `_createLabels`
```ts
const newNumberOfLabels = (this._effectiveMax - this._effectiveMin) / (step * labelInterval);

// If the required labels are already rendered
if (newNumberOfLabels === this._oldNumberOfLabels) {
	return;
}

this._oldNumberOfLabels = newNumberOfLabels;
```

Suggestion: remove the part which checks for a change (line 633-638) or add something like
 `this._effectiveMin === this._oldEffectiveMin` to the comparison.

### Affected Component

all components which uses SliderBase => RangeSlider, Slider

### Expected Behaviour

Changing the `min`, `max` value from `0, 100` to `100, 200` should recalculate the labels too.

### Steps to Reproduce

1. Set min to 0 and max to 100
2. Check the labels
3. Update min to 100 and max to 200
4. Labels for 0 and 100 are still rendered

### Priority

Low

### UI5 Web Components Version

all versions since commit 2b9008cd7b0a8e65f1e2a0f67501bab61c32b2d5 

### Browser

Chrome, Edge, Firefox, Safari

### Operating System

MacOs

### Additional Context

If a error  like this is undetected since 18.11.2020 the impact can not be that big.

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by elenastoyanovaa** [comment]
Hello @SAP/ui5-webcomponents-topic-rl ,

Can you please look over this issue? It is reproducible as described, we should rather check if the min and max values are changed, then if their difference is changed.

Steps:
1. Open: https://sap.github.io/ui5-webcomponents/playground/?path=/story/main-slider--tickmarks-label-tooltip
2. Open the console and select the slider.
3. Change the min and max to 0 and 100:
```
$0.min = 0;
$0.max = 100;
```
Then 
```
$0.min = 100;
$0.max = 200;
```

Result: the labels are not updated as newNumberOfLabels and this._oldNumberOfLabels have the same value.

Kind Regards,
Elena
