### ISSUE TITLE
Format the date data in the selected item.

### ISSUE THREAD

**Issue by khoannv12a4** [SAP/ui5-webcomponents#7630]
### **Issue Description**
How to format the date data in the selected item.
![Screenshot 2023-09-27 at 16 37 12](https://github.com/SAP/ui5-webcomponents/assets/118348147/4dc52a4d-4c66-4887-9409-0c259a8a9534)
Thanks.

**Comment by elenastoyanovaa** [comment]
Hello @khoannv12a4 ,

If you are talking about the date picker component you can read https://sap.github.io/ui5-webcomponents/playground/?path=/docs/main-datepicker--docs and the formatting chapter in the documentation. If your question is regarding a different component, please reopen the issue and state which one and provide us with other useful information like - sample to test, use case and etc.

Kind Regards,
Elena
