### ISSUE TITLE
ui5-table-rows grow taller and taller when resizing Firefox horizontally

### ISSUE THREAD

**Issue by brodo** [SAP/ui5-webcomponents#764]
**Describe the bug**
`ui5-table-row` grow taller and taller when resizing the browser horizontally. I encountered the same behavior when checking and unchecking a `ui5-checkbox` inside a `ui5-table-cell`.

**To reproduce**
1. Go to 'https://sap.github.io/ui5-webcomponents/playground/components/Table/'
2. Resize your browser window horizontally back and forth

**Expected behavior**
The `ui5-table-row` should not grow in size.

**Screenshots**
[GIF of the problem](https://imgur.com/WmgQQ0O)

**Context**
- UI5 Web Components version: 1.0.0-rc.2
- OS/Platform: Mac OS
- Browser: Firefox Developer Edition 70.0b2

**Affected components** 
`ui5-table-row`

This does not happen in Chrome or Safari.

**Comment by vladitasev** [comment]
Thanks for bringing this to our attention, we'll look into it

Regards,
Vladi

**Comment by MapTo0** [comment]
Hey @brodo 

This should be already fixed in the master branch.
Expect it available in the next npm release :)

Regards,
Martin

**Comment by MapTo0** [comment]
As this is already fixed, I am closing the issue. If you have any problems with the fix feel free to reopen.

Regards,
Martin
