### ISSUE TITLE
[ui5-shellbar]: Horizon High Contrast Height is Incorrect

### ISSUE THREAD

**Issue by JarrettChan** [SAP/ui5-webcomponents#7646]
### Bug Description

Shellbar height in Horizon high contrast is 2.75rem, which incorrectly matches to Quartz.

Affects:
- Horizon HCB
- Horizon HCW
- Horizon HCB EXP
- Horizon HCW EXP

### Affected Component

ui5-shellbar

### Expected Behaviour

Shellbar height in Horizon high contrast should be 3.25rem like Horizon / Horizon Dark

### Steps to Reproduce

1. https://sap.github.io/ui5-webcomponents/playground/?path=/story/fiori-shellbar--basic&globals=theme:Horizon+High+Contrast+Black
2. Inspect ui5-shellbar 
3. Observe height css property: `--_ui5-v1-17-2_shellbar_root_height: 2.75rem;`

### Priority

Medium

### UI5 Web Components Version

1.17.0

### Browser

Chrome

### Organization

SuccessFactors

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by gmkv** [comment]
Hi @SAP/ui5-webcomponents-topic-p 
The Shell Bar component has incorrect height in Horizon High Contrast themes.
Currently, the visual specification defines the height as 3.25rem in all Horizon themes.

Would you have a look?
