### ISSUE TITLE
[ui5-textarea]: scrollbar wrong visual appearance

### ISSUE THREAD

**Issue by nnaydenow** [SAP/ui5-webcomponents#7649]
### Bug Description

 The scrollbar is placed over the bottom border when long multiline text inside the `ui5-textarea` component is typed
<img width="904" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/31909318/956676f8-f998-4b3e-adf3-0501f7e93e64">

The expected behaviour is the same as in OpenUI5:
<img width="296" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/31909318/419315bf-a3b6-4b08-8d03-d809ab8c8510">

### Priority

None

### UI5 Web Components Version

1.17.2

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by hristop** [comment]
Internal BLI was created: BGSOFUIRILA-3704
