### ISSUE TITLE
[ui5-split-button]: Split button is not displayed correctly when having a wrapper

### ISSUE THREAD

**Issue by MapTo0** [SAP/ui5-webcomponents#7659]
### Bug Description

`ui5-split-button` is not correctly displayed when placed in a wrapper component and takes 100% of its width.

<img width="138" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/5821279/17b75352-4a35-4cc7-9505-1fd1b64dcf1d">

### Affected Component

ui5-split-button

### Isolated Example

https://jsbin.com/suxozavoka/edit?html,output

### Steps to Reproduce

Open the example.

### Priority

None

### UI5 Web Components Version

latest

### Browser

Chrome

### Declaration

- [x] I’m not disclosing any internal or sensitive information.

**Comment by gmkv** [comment]
Hi @SAP/ui5-webcomponents-topic-b 
The SplitButton has a visual issue when set to take 100% width of the container element.

Would you have a look?
