### ISSUE TITLE
Security issue | Upgrade  jquery-3.3.1.slim.min.js used in WheelSlider_Test_Page.html

### ISSUE THREAD

**Issue by athulvraj** [SAP/ui5-webcomponents#7669]
### Bug Description

Our security team has raised concerns on using jquery-3.3.1.slim.min.js in the below file
https://github.com/SAP/ui5-webcomponents/blob/main/packages/main/test/pages/WheelSlider_Test_Page.html

and suggests to upgrade to jquery - 3.5.0. 

Will you please help to fix this.

### Affected Component

WheelSlider_Test_Page.html

### Expected Behaviour

upgrade to jquery - 3.5.0. 

### Steps to Reproduce

1.Please navigate to https://github.com/SAP/ui5-webcomponents/blob/main/packages/main/test/pages/WheelSlider_Test_Page.html

2. See that  jquery-3.3.1.slim.min.js is used as a CDN.
3. Ticket is to upgrade it to latest version
...

### Priority

High

### UI5 Web Components Version

v1.18.0

### Browser

Chrome, Edge, Firefox, Safari

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by gmkv** [comment]
This outdated library is only used inside the internal test pages.
It does not get packaged in the delivered product.
