### ISSUE TITLE
[Popover]: sap.ui.webc.main.Popover does not close

### ISSUE THREAD

**Issue by swendlandt** [SAP/ui5-webcomponents#7675]
### Bug Description

This can be reproduce with the official sample of the control: https://sapui5.eu1.hana.ondemand.com/#/entity/sap.ui.webc.main.Popover/sample/sap.ui.webc.main.sample.Popover

 

When you click outside of the Popover, or click on the "Subscribe" Button in the Popover, the Popover should close but it doesn't. 

There is JS error in the console when you open the Popover, which might be related:

 

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'addOpenedPopover')
    at t._addOpenedPopup (Popover-dbg.js:139:28)
    at t._open (Popup-dbg.js:259:12)
    at t.showAt (Popover-dbg.js:132:19)
    at d.__callPublicMethod (WebComponent-dbg.js:399:41)
    at r.<computed> [as showAt] (WebComponentMetadata-dbg.js:108:19)
    at c.handleOpen (C.controller.js:11:13)
    at i.fireEvent (EventProvider-dbg.js:241:22)
    at h.fireEvent (Element-dbg.js:667:44)
    at c.fireClick (ManagedObjectMetadata-dbg.js:806:49)
    at w.fire (ManagedObjectMetadata-dbg.js:818:24)

> 

### Affected Component

Popover

### Expected Behaviour

The popover closes when you click outside it.

### Isolated Example

https://sapui5.eu1.hana.ondemand.com/#/entity/sap.ui.webc.main.Popover/sample/sap.ui.webc.main.sample.Popover

### Steps to Reproduce

1. Go to sample https://sapui5.eu1.hana.ondemand.com/#/entity/sap.ui.webc.main.Popover/sample/sap.ui.webc.main.sample.Popover
2. Click the button to open the popover
3. Click outside of the popover

### Priority

High

### UI5 Web Components Version

1.18.0

### Browser

Chrome

### Operating System

MacOS

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by gmkv** [comment]
Hi @swendlandt 
I'm trying to reproduce the described issue but I can't get it to break.
Can you tell me a bit more about the steps you take to make it fail?
Which version of Chrome are you using? If you clear the browser cache and load again, does it fail every time? It may be useful if you can attach a screen recording.

**Comment by swendlandt** [comment]
Hi @gmkv,

I had the issue even in two different browsers (Brave and Chrome). I checked in incognito mode and there it did not happen. After clearing my cache for the site the issue was completely gone. Not sure why it got into this state before, but from my side this issue can be closed.

**Comment by gmkv** [comment]
Not sure why this happened. And I haven't seen the UI5 DemoKit deployed on this "eu1" URL before. Usually best to use https://ui5.sap.com/ for the framework offering

**Comment by swendlandt** [comment]
I know it now: The issue was fixed with UI5 version 1.118.0 with this commit: https://github.com/SAP/openui5/commit/5b4bb83155b7cebc1028de0801cefebca492d97b

When I cleared the cache I probably got the new UI5 version somehow.
