### ISSUE TITLE
[Input][ComboBox]Ability to place icon at the beginning instead of the end

### ISSUE THREAD

**Issue by emilylian-sap** [SAP/ui5-webcomponents#7679]
### Is your feature request related to a problem?

We would like to place an icon at the beginning of the input field/combobox. Currently, ComboBox and Input have a property "icon" which allows us to place an icon at the end of the input. However, since the icon is inside a shadow root, the parent element is not able to override the styling to modify the position.

### Describe the solution you'd like

Add a new API to allow consumer to define the icon position.

### Describe alternatives you've considered

Expose the icon as a CSS Shadow Part so it be comes styleable.

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Todor-ads** [comment]
Hello @SAP/ui5-webcomponents-topic-rl, 
take a look of this feature request.

Best regards,
Todor

**Comment by hristop** [comment]
Hi @emilylian-sap ,

We will discuss your request with our UX / VD colleagues and get back to you with their feedback. 

Best Regards,
Hristo

**Comment by hristop** [comment]
Hi @emilylian-sap ,

After discussions with our UX / VD and architects, we will have to reject this requirement as we do not currently have design for such concept. 

Best Regards,
Hristo
