### ISSUE TITLE
[SF_ACC] [List] "Contains Deletable Items" not being announced when accessibleName is defined

### ISSUE THREAD

**Issue by bonniegso** [SAP/ui5-webcomponents#7690]
### Bug Description

When a List component with mode="Delete" also has an accessibleName property, "Contains Deletable Items" is not being announced when user enters the list.

### Affected Component

List

### Expected Behaviour

It is expected that "Contains Deletable Items" is read for a List with "Delete" mode defined when a user enters the list via keyboard using a screen reader.

### Isolated Example

https://codesandbox.io/s/sleepy-borg-m45kw6

### Steps to Reproduce

1. Turn on screen reader and navigate to the list using your keyboard
2. Observe that "Contains Deletable Items" is not read

### Priority

Medium

### UI5 Web Components Version

1.17.0

### Browser

Chrome

### Operating System

MacOS 14.0

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Todor-ads** [comment]
Hello https://github.com/orgs/SAP/teams/ui5-webcomponents-topic-p,
can you take a look at this issue?

Best Regards,
Todor

**Comment by plamenivanov91** [comment]
Hello @bonniegso,

The `"Contains Deletable Items"` text is perfectly readable by the screen reader with the provided snipix.

Start JAWS in VPC mode, select the input, then press the arrow button a few times to land on the List and you will hear the text.

I recorded a video to demonstrate it, but unfortunately the reader is not audible in the recorded video.

Regards,
Plamen Ivanov
