### ISSUE TITLE
[Feature Request]: Add attribute `noTypeahead` to `ui5-combobox`

### ISSUE THREAD

**Issue by Jianrong-Yu** [SAP/ui5-webcomponents#7691]
### Feature Request Description

In component `ui5-multi-combobox`, there is an attribute `noTypeahead`, when it's set to true, autocomplete will be disabled when user is typing in the input, we want the same attribute to be enabled in `ui5-combobox`.

### Proposed Solution

Implement the attribute `noTypeahead` on `ui5-combobox`.

### Organization

SAP Signavio

### Additional Context

We are using `ui5-multi-combobox` to pick an item which will load a big object automatically, if auto-complete on typing is enabled, the page will send multiple requests to load different objects when the user is typing.

Example:
![Recording 2023-10-10 at 20 07 22](https://github.com/SAP/ui5-webcomponents/assets/95995341/a58bc16b-0d6b-43ce-938d-d641ce3f2184)
The user wants to pick `Brazil`, but `Belgium` will be picked before `Brazil`.

### Priority

Medium

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Todor-ads** [comment]
Hello https://github.com/orgs/SAP/teams/ui5-webcomponents-topic-rl,
take a look of this feature request.

Best regards,
Todor
