### ISSUE TITLE
[Feature Request]: make it possible to open ui5-calendar at a certain date

### ISSUE THREAD

**Issue by vladitasev** [SAP/ui5-webcomponents#7693]
### Feature Request Description

Currently, if I have a `ui5-calendar` like this:

```html
	<ui5-calendar format-pattern="MM/dd/yyyy" calendar-type="Gregorian">
		<ui5-date value="01/20/2020"></ui5-date>
	</ui5-calendar>
```

when the user opens the calendar, they can't know that there is a selected date, because the component always opens at today's date.

Is this a bug or intended?

### Proposed Solution

If a bug, please make the calendar always open at the first/last selected date (as it is in OpenUI5 for example)
If it is not a bug, then the calendar must have some other API, f.e. `currentDate` that lets the user focus the calendar at a certain date.

Currently, a `timestamp` property exists that does exactly that, however this property:
1) is a timestamp, not a string
2) is protected

### Priority

High

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by nnaydenow** [comment]
Hi @SAP/ui5-webcomponents-topic-b,

Could you please take a look at that enhancement?

Regards,
Nayden

**Comment by vladitasev** [comment]
@unazko Could you please comment on how this issue will be resolved? Will there be a new property to center the calendar to a certain date, or will it do it based on the selection?

**Comment by unazko** [comment]
Hello colleagues,

The navigated and focused date could be based on the earliest selected date, even without adding a new public property.
If there is no selected date then today's date should be navigated on.
The keyboard handling experts have recommended adding a new property for the application developers to change the initially focused(navigated) date based on their preference.
This issue could be resolved as a bug and separately we could add a new navigation property to the component.
Also we should have in mind the the keyboard handling specification has been changed regarding the tab order for the calendar component. Now we have two scenarios:
- If calendar is embedded into the page then we follow the native browser tab order (month picker button, year picker button and finally the focus goes inside the calendar grid)
- If calendar is nested into a dialog (ui5-date-picker, ui5-datetime-picker, ui5-daterange-picker) then we have the same tab order as currently implemented (focus goes inside the calendar grid, month picker button and finally the year picker button)

Best regards,
Boyan
