### ISSUE TITLE
Incorrect Default Time in DateTimePicker

### ISSUE THREAD

**Issue by saran85** [SAP/ui5-webcomponents#7699]
### Bug Description

The DateTimePicker component in our UI5 web application is exhibiting unexpected behavior related to the default time when selecting a date. It consistently provides an incorrect default time instead of occasionally using the local time, which is causing usability and data entry issues for our users.

### Affected Component

DateTimePicker

### Expected Behaviour

When selecting a date, the DateTimePicker should automatically use the local time or, at the very least, display a time value that accurately corresponds to the selected date.

### Steps to Reproduce

1. Navigate to the DateTimePicker in the application.
2. Select a date by clicking on the calendar icon.
3. Observe that the DateTimePicker sets an incorrect default time.

### Log Output, Stack Trace or Screenshots

![image](https://github.com/SAP/ui5-webcomponents/assets/95576439/a491a4b8-4927-4909-b214-48a27c7a5244)
![image](https://github.com/SAP/ui5-webcomponents/assets/95576439/0b5b05f9-d14e-48a7-99b1-7507e05c239d)
![image](https://github.com/SAP/ui5-webcomponents/assets/95576439/6830dfc0-e09d-42d0-b3d9-da59d479dff9)

### Priority

Medium

### UI5 Web Components Version

1.17.0

### Browser

Chrome, Edge

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Todor-ads** [comment]
Hello @saran85,
Thank you for sharing this finding. I tried to reproduce the problem but failed. Is it possible to provide us with an isolated sample that reproduces the problem or a link to an application where we can see this behavior.

Regards,
Todor

**Comment by saran85** [comment]
> Hello @saran85, Thank you for sharing this finding. I tried to reproduce the problem but failed. Is it possible to provide us with an isolated sample that reproduces the problem or a link to an application where we can see this behavior.
> 
> Regards, Todor

https://codesandbox.io/s/hopeful-haze-n8vmjg?file=/src/FilterDateTimePicker.js

**Comment by niyap** [comment]
Hello @saran85,

Please adjust the provided CodeSandbox to show the reproducible issue. Currently, when I open it, the only thing that I see is "Hello CodeSandbox. Start editing to see some magic happen!"

Kind Regards,
Niya
