### ISSUE TITLE
[ui5-list/ui5-li]: radio buttons not visible on iPad mini

### ISSUE THREAD

**Issue by GertSchneider** [SAP/ui5-webcomponents#7700]
### Bug Description

The radio buttons of ui5-li entries in ui5-list mode="SingleSelectBegin" are not visible on an iPad mini (5. Generation) (iPadOS 16.1.1).

### Affected Component

ui5-list, ui5-li

### Expected Behaviour

It is expected, that the radio buttons are visible like on (all) other devices.

### Isolated Example

https://codesandbox.io/s/ui5-webcomponents-forked-2plxyx?file=/index.html

### Steps to Reproduce

1. Call the example above or call https://2plxyx.csb.app/ 
2. The radio buttons of the list entries are not visible.

### Priority

Medium

### UI5 Web Components Version

1.17.0

### Browser

Safari

### Operating System

iPadOS 16.1.1

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Todor-ads** [comment]
Hi @GertSchneider,
 I tried to reproduce the issue in iPhone 13 Pro (iOS 17.0.3) and browser simulators but failed. Can you confirm that the issue is still reproducible, and thus if it can be reproduced on a simulator?

**Comment by GertSchneider** [comment]
Hi @Todor-ads ,
I had sent the codesandbox example to the customer who confirmed the issue on this type of iPad. I haven't tested it on a simulator (since working on Windows).
Best regards, Gert

**Comment by yanaminkova** [comment]
Hello @GertSchneider ,

I tested both on iPad mini 5th generation and iPad air 2 (iPadOS 16.7) as well as on the browser simulators, but still I am not able to reproduce it. 
Can I kindly ask you to update your device to the latest version 17, because this is the supported one and then retest again?

Thanks and Regards,
Yana

**Comment by GertSchneider** [comment]
Hi Yana,
the customer has updated to iOS 17 and the problem no longer occurred. We can close the issue.
Thanks and best regards, Gert
