### ISSUE TITLE
[Feature Request]: make ui5-busyindicator more flexible in terms of text management

### ISSUE THREAD

**Issue by vladitasev** [SAP/ui5-webcomponents#7701]
### Feature Request Description

Make it possible to position the text above the animation, with arbitrary size and paddings.

### Proposed Solution

Make it possible to implement this design:

<img width="344" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/15844574/92124df8-db48-4f5a-842f-5faa051695b3">

### Priority

None

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by yanaminkova** [comment]
Hello @SAP/ui5-webcomponents-topic-rd, 

I am forwarding this feature request regarding ui5-busyindicator to you.
Could you please have a look at it?

Thanks and Kind regards,
Yana
