### ISSUE TITLE
[Feature Request]: Flexible Column Layout - allow min and max width attribute for columns.

### ISSUE THREAD

**Issue by gurkirpalgill** [SAP/ui5-webcomponents#7707]
### Feature Request Description

For the flexible column layout, We need to set css styles based on the screen sizes.  Right now we have to resort to using:

```
  addCustomCSS(
    "ui5-flexible-column-layout",
    `.ui5-fcl-column--start {
      width: 100%;
      min-width: 250px !important;
      max-width: 450px !important;
    }`
  );
```
This is not very flexible. We have requirements e.g.

![Screenshot 2023-10-13 at 10 57 16 AM](https://github.com/SAP/ui5-webcomponents/assets/65705637/240e9c04-f182-4e1a-ad62-6867543d28ef)

These styles can not be applied through shadow root except through addCustomCSS.

### Proposed Solution

Provide options through properties/attributes or a json file to set css styles e.g. minimum and maximum width for the columns which can be applicable through shadow root.

### Priority

Medium

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by yanaminkova** [comment]
Hello @gurkirpalgill,

We already have the following feature request - #7484

We will start working on it soon, and once it is ready the user should be able to customize the width of the columns
of the Flexible Column Layout by dragging the column separators. I guess, this would work for you.

If not, could you please give more detailed information why you need to set min and max width to the columns and please provide codesandbox, where we could see your exact use case.

Thanks and Regards,
Yana
