### ISSUE TITLE
[Calendar]: Secondary calendar labels reach outside of control

### ISSUE THREAD

**Issue by kaistephanrichter** [SAP/ui5-webcomponents#7712]
### Bug Description

If a secondary calendar is set like shown in the example in the documentation, the label of the secondary calendar can go beyond the borders of the control. 
Example: Primary Calendar Gregorian / Secondary Calendar Islamic: May / Shaw. - Dhu'l**-Q**, the last part of the islamic label is wrapping an therefore leaves the bounding box of the button:

![image](https://github.com/SAP/ui5-webcomponents/assets/46745939/07c02533-e906-4af6-9c7a-748c66928b29)

This should be solved by a different overflow behaviour or larger buttons (which would be possible here)

### Affected Component

Calendar

### Expected Behaviour

The label for the islamic calendar should either be truncated or if it wraps, the button should be higher. Maybe increasing the button size would be a good option whenever you have a secondary calendar defined?

### Isolated Example

https://sap.github.io/ui5-webcomponents/playground/?path=/docs/main-calendar--docs

### Steps to Reproduce

1. Open documentation on the Calendar page
2. Go to the last example with the secondary calendar
3. Open the month selection
...

### Priority

Medium

### UI5 Web Components Version

1.18.0

### Browser

Chrome, Safari

### Operating System

Mac OS

### Organization

SAP Design

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by petyabegovska** [comment]
Hello @SAP/ui5-webcomponents-topic-b,

Please check, the issue is reproducible in the latest playground: https://sap.github.io/ui5-webcomponents/nightly/playground/?path=/docs/main-calendar--docs

Best regards,
Petya
