### ISSUE TITLE
[Feature Request]: Support `autofocus` for Input component

### ISSUE THREAD

**Issue by mrCherry97** [SAP/ui5-webcomponents#7724]
### Feature Request Description

HTML supports the `autofocus` property, and it will be very useful to have.
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autofocus

### Proposed Solution

Add `autofocus` prop to the Input component.
For example, when I want to introduce CommandPallete displayed in the dialog, after clicking cmd+k or ctrl+k, the command palette will be opened and I want to have input focused not using the mouse.

### Organization

SAP Kyma

### Additional Context

We are currently moving our [product](https://github.com/kyma-project/busola) to UI5 and it is very necessary functionality for us.

### Priority

High

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by yanaminkova** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

Could you please have a look at this feature request regarding autofocus in ui5-input component.

Thanks and Kind regards,
Yana

**Comment by niyap** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

The feature request is regarding the "autofocus" HTML attribute. We have to discuss it with the responsible designers, if it is feasible to provide such a property for ui5-input web component.

Could you please look over?

Kind Regards,
Niya

**Comment by hristop** [comment]
Hi @mrCherry97 ,

Can you please clarify why you can't use the ".focus()" API (https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus)? 

Best Regards,
Hristo

**Comment by mrCherry97** [comment]
hi @hristop 
I need to autofocus input in the command palette, so when I click cmd + k the command palette will pop up, I don't want to use the mouse to click on input to write something. After opening I want to have focus on input. Previously we were using `fundamental-react` and there was flag `autofocus`, HTML has tag `autofocus` so I don't want to make workarounds for focusing this input. 
I have workaround, but it will be very useful to have it made properly by normal HTML flag `autofocus`.
```
  useEffect(() => {
    document.getElementById('command-palette-search')?.focus();
  }, []);
  ```

**Comment by hristop** [comment]
Hi @mrCherry97 ,

After internal discussions with our architects and accessibility experts, we came to the conclusion that introducing such property will result in hard to tackle ACC / UX issues, thus we will have to reject the requirement. 
We recommend using the existing API as you are already doing. 

Best Regards,
Hristo
