### ISSUE TITLE
Text Area

### ISSUE THREAD

**Issue by DesiMat** [SAP/ui5-webcomponents#7726]
### Bug Description

The popover of semantic states is being rendered with white line bellow. 

### Affected Component

Text Area

### Expected Behaviour

The white line is not part of the popover. See Visual design spec:
https://wiki.one.int.sap/wiki/pages/viewpage.action?pageId=2698914037

### Steps to Reproduce

1.
2.
3.
...

### Priority

None

### UI5 Web Components Version

v1.18.0

### Browser

Chrome

### Operating System

mac

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by yanaminkova** [comment]
Hello @DesiMat ,

Could you please provide example where the issue could be reproduced?
Also, please specify which theme is affected.

Thanks and Regards,
Yana

**Comment by yanaminkova** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

On both Morning and Evening Horizon themes, there are empty pixels bellow the semantic input messages of the Text Area component. 
Could be seen on the following screenshots:

![image](https://github.com/SAP/ui5-webcomponents/assets/32466553/3a3652d7-306d-4448-a682-77784641ac30)
![image](https://github.com/SAP/ui5-webcomponents/assets/32466553/8167e60f-7ea1-42df-a3e6-9c5a93efd6e5)

Also, it is easily reproducible in the storybook example of the Text Area, by simply setting the valueState property.
On both High contrast themes, it looks fine.

Could you please have a look at it?

Thanks and Kind regards,
Yana
