### ISSUE TITLE
[Feature Request]: Support readonly state for ui5-select component

### ISSUE THREAD

**Issue by petyabegovska** [SAP/ui5-webcomponents#7727]
### Feature Request Description

Provide a "readonly" property to ui5-select component in order to support the Read only state: The UI element is visible and focusable. The value can be recognized and selected, but not changed. 

Note: The property is available for other components like combobox, input, etc.

More about different states: https://experience.sap.com/fiori-design-web/ui-element-states/

### Proposed Solution

VD and UX design available, please follow up on them.

### Organization

SAP Process Automation

### Additional Context

The requested state is already part of SAP Design.

### Priority

Medium

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by dobrinyonkov** [comment]
Internal BLI: BGSOFUIPIRIN-6282

**Comment by ilhan007** [comment]
Hello @timogeib  the readonly state will be present with the next monthly release of ui5 web components 1.21.0 - start of Jan
and little later will be present in  the angular wrappers ui5-webcomponents-ngx (after upgrading the internal dependency to ui5 web components).

**Comment by timogeib** [comment]
Great job. Thank you alot for the quick work.
