### ISSUE TITLE
[Feature Request]: Ability to select all text when focusing ui5-input

### ISSUE THREAD

**Issue by petipp** [SAP/ui5-webcomponents#7742]
### Feature Request Description

In some scenarios a text input in a form is pre-populated with default text.  Since we know that users who want to change that text are likely to want to entirely replace it, a good UX pattern is to select the entire text value so that the user can easily replace it simply by typing.

The underlying [HTML input element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input) offers a `select()` method that allows the selection of the text.
If you were to use a native event handler, you could then use the event target and directly cause the selection of the text, something like the following:
```
    onFocus: event => event.target.select();
```

Unfortunately, `ui5-input` not only doesn't expose a similar method but it also wraps the event and encapsulates the underlying `input` which prevents consumers from calling its `select()` method.

### Proposed Solution

At least three possible solutions would be reasonable and totally acceptable
1. Expose a way to access the underlying Input from the `InputDomRef` instance provided as the target for the events exposed by `ui5-input`
2. Add a new `select()` method to `InputDomRef` that internally calls the `select()` method of the underlying `input`
3. Add a new autoselectOnFocus (boolean) parameter to `ui5-input` that automatically adds the appropriate event handler

### Proposed Alternatives

If there are any alternative ways to get access to this functionality in a **supported** way, this would also be totally fine.  Hacking things by making assumptions about the DOM structure (while it might work) seems to not fit that criterion.

### Organization

SAP

### Additional Context

Blocker for the replacement of Material UI elements with SAP UI5 web components

### Priority

Medium

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by niyap** [comment]
Hello @petipp,

We discussed your proposal with responsible designers and architects and we think that such enhancement is not needed.
First of all, if you focus the ui5-input via Tab, the text is selected (in the same way, as it works for the native input)
Also, selection via mouse could be easily achieved as well, just a double click within the ui5-input and last but not least, you can use keyboard shortcut (Ctrl/Cmd + A)

Kind Regards,
Niya
