### ISSUE TITLE
[ViewSettingsDialog]: ViewSettingsDialog is not honouring update in sortItems property

### ISSUE THREAD

**Issue by lateefsofi** [SAP/ui5-webcomponents#7752]
### Describe the bug

We have to sort columns of a table and columns of the table can be added and removed dynamically by the user.
In ViewSettingsDialog we have to show only those columns of the table which are currently visible.
example:
Lets say there are 6 columns(column1, ..., column6) in the table. User chooses "Column1, Column2 and Column3". On when we open ViewSettingsDialog, these fields are visible in it. Now when user clears previous selection and chooses "Column3, Column4 and Column5", ViewSettingsDialog still shows old selection "Column1, Column2 and Column3"

### Isolated Example

https://codesandbox.io/s/optimistic-hooks-5zs4ln?file=/src/App.js

### Reproduction steps

1. Navigate to https://codesandbox.io/s/optimistic-hooks-5zs4ln?file=/src/App.js
2. Click "Show Sort Dialog" button
3.  ViewSettingsDialog should open with initial set of fields which are also visible as tokens on the screen.
4. Click "Click to Update Sort Columns"
5. You will see fields are update on the screen
6. Now again click on "Show Sort Dialog" button
7. Issue: You will still see old values there
...

### Expected Behaviour

ViewSettingsDialog should be updated with the latest set of fields.

### UI5 Web Components for React Version

1.16.2

### UI5 Web Components Version

1.14.2

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by niyap** [comment]
Hello @SAP/ui5-webcomponents-topic-b,

The issue is regarding the ui5-view-settings-dialog web component.
It could be easily reproduced in that codeSandbox: https://codesandbox.io/s/ui5-webcomponents-forked-6l2mkn?file=/src/index.js Just follow the steps from the detailed description provided by Lukas.

Could you please look over?

Kind Regards,
Niya

**Comment by lateefsofi** [comment]
I have updated the latest version of ui5-webcomponents and ui5-webcomponents-react in https://codesandbox.io/s/angry-architecture-zd27r9?file=/package.json but I don't see this issue fixed.

**Comment by Lukas742** [comment]
Hi @lateefsofi 

there seems to be an additional issue with our wrapper and how it handles propagation of React `key`s. I've already opened a [PR](https://github.com/SAP/ui5-webcomponents-react/pull/5230) that should fix this issue.

Until it's merged and released, you can render the `SortItems` as `slot="sortItems` inside the component's `children`:
https://codesandbox.io/s/hopeful-ace-vjxw66?file=/src/App.js

___

Hi @tsanislavgatev 

> 8. Click on "Reset" inside the dialog
> 9. See that again SortItems 1-3 are displayed

This still seems to be the case, even with the latest version. Is this intended?

1. Got to [codeSandbox](https://codesandbox.io/s/ui5-webcomponents-forked-pdpyt4?file=/package.json)
2. Open dialog by clicking on the "open" button
3. See that SortItems 1-3 are displayed
4. Close the dialog and click on update
7. See that now SortItems 4-6 are displayed
8. __Select one of the updated items__
9. Click on "Reset" inside the dialog
10. See that again SortItems 1-3 are displayed

**Comment by tsanislavgatev** [comment]
@Lukas742 Reset would bring back the Initial settings. So yes, that would still be the case. If you check this: https://codesandbox.io/s/ui5-webcomponents-forked-6l2mkn?file=/src/index.js

You can observe the fixed behaviour, when you press the update button, you will have the updated state, but reset brings back the initial state.

**Comment by Lukas742** [comment]
Thanks for the reply @tsanislavgatev 

I just checked again and since this behavior is intended, I unfortunately found another issue:

> 1. Got to [codeSandbox](https://codesandbox.io/s/ui5-webcomponents-forked-pdpyt4?file=/package.json)
> 2. Open dialog by clicking on the "open" button
> 3. See that SortItems 1-3 are displayed
> 4. Close the dialog and click on update
> 5. See that now SortItems 4-6 are displayed
> 6. __Select one of the updated items__
> 7. Click on "Reset" inside the dialog
> 8. See that again SortItems 1-3 are displayed

9. Select on one of the SortItems
10. See that now SortItems 4-6 are displayed again

Also I find it odd, that there is no way to opt-out of this behavior (at least I didn't find a way to achieve this). So how would one be able to update the component to show only the initial SortItems? E.g. if the data changed when a user switches a view. Is this only possible by re-mounting the component?

**Comment by lateefsofi** [comment]
There is 1 more issue in this, once we select an column and update the list by clicking "Click to update sort columns", reset button gets disabled.
https://codesandbox.io/s/misty-voice-rf4h3x?file=/src/App.js

**Comment by Lukas742** [comment]
Hi @lateefsofi 

I've created another [issue](https://github.com/SAP/ui5-webcomponents/issues/7939) so the ui5-webcomponents team can track them better. Please feel free to add additional information.
