### ISSUE TITLE
[Popover] - InputSuggestionItems in Popover don't show correctly 

### ISSUE THREAD

**Issue by d3nergy** [SAP/ui5-webcomponents#776]
**Describe the bug**
When using an Input with suggestion-items inside a popover, the suggestion-items will be shown somewhere else or even don't.

**To reproduce**

Put input with suggestion-items inside Popover opened by a button.

**Isolated example**

https://codesandbox.io/s/ui5-webcomponents-5sn86?fontsize=14

**Expected behavior**

suggestion-items should be opened directly underneath the Input just like it was not inside another popover. Outer popover should not close on action.

**Screenshots**

<img width="343" alt="Bildschirmfoto 2019-09-13 um 13 38 16" src="https://user-images.githubusercontent.com/13339537/64859884-c5ae8f00-d62b-11e9-88b9-05018e2be812.png">

**Context**
- UI5 Web Components version : 1.0.0-rc.2
- OS/Platform: MAC OS
- Browser *(if relevant)*: Chrome
- Other information:

**Affected components** *(if known)*

<ui5-input>, <ui5-popover>

**Log output / Any errors** in the console
```
{...}
```

**Comment by MapTo0** [comment]
Hello @d3nergy 
Thanks for reporting!
I have an almost ready full refactoring of the Popups which will fix that issue.

Stay tuned!

Regards,
Martin
