### ISSUE TITLE
[ui5-tree-item]: Child items rendered as hovered (grey background)

### ISSUE THREAD

**Issue by kozubikmichal** [SAP/ui5-webcomponents#7766]
### Bug Description

Hi team,

in the current version `1.18.0`, the leaf level `ui5-tree-item` inside the `ui5-side-navigation` are rendered with grey background, which is the same look as when hovered, therefore there is no visual feedback for the user when hovering the element.

In version `1.16.0` (and `1.17.0` according to the SandBox) this was working fine.

Is this a desired change or a bug? From our perspective this is a bug as there's no visual feedback on hover anymore.

### Affected Component

Side Navigation

### Expected Behaviour

Leaf level items has no special background by default, only when hovered, active, focused or selected

### Isolated Example

https://codesandbox.io/s/ui5-webcomponents-ui5-tree-item-background-issue-2srtmr

### Steps to Reproduce

1. Render the Side Navigation component with nested items

### Log Output, Stack Trace or Screenshots

WebComponents Storybook (1.18.0)
![image](https://github.com/SAP/ui5-webcomponents/assets/26189327/7dddefd1-bee7-42b7-9b54-39d741f46458)

### Priority

None

### UI5 Web Components Version

1.18.0

### Browser

Chrome

### Operating System

MacOS

### Organization

SAP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by TeodorTaushanov** [comment]
This issue is fixed in the main branch with #7682. The fix will be available with version 1.20.
