### ISSUE TITLE
[menu]: when using Menu in Table on mobile devices app crashes

### ISSUE THREAD

**Issue by rvsia** [SAP/ui5-webcomponents#7767]
### Describe the bug

When using a Menu component in Table on mobile devices, the app is crashing:

```jsx
Error
Web component processed too many times this task, max allowed is: 10
▼ 2 stack frames were expanded.
    at RenderQueue.process (https://prk2z7.codesandbox.io/node_modules/
ui5/webcomponents-base/dist/RenderQueue.js:45:15
    at eval (https://prk2z7.codesandbox.io/node_modules/
ui5/webcomponents-base/dist/Render.js:84:34
```

### Isolated Example

https://codesandbox.io/s/smoosh-tdd-cywz6k

### Reproduction steps

1. Open the example
2. Open the preview in a new window
3. Set the window to responsive mode (simulate mobile devices)
4. Click on menu

### Expected Behaviour

Menu should be open

### Screenshots or Videos

![Kapture 2023-10-30 at 12 24 17](https://github.com/SAP/ui5-webcomponents-react/assets/32869456/6d4aab0d-e7f9-4025-a854-ca9d340c576a)
`
![image](https://github.com/SAP/ui5-webcomponents-react/assets/32869456/bd2ea3e4-b754-4616-b4cc-67f238efd15c)

### UI5 Web Components for React Version

latest

### UI5 Web Components Version

latest

### Browser

Chrome, Edge

### Operating System

MacOS

### Additional Context

* This will be probably a webcomponents issue but I do not know how to reproduce the issue there

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by rvsia** [comment]
@Lukas742 

> Also, it's not recommended rendering modals or popups inside other components.

Thank you for pointing this up, we forget to use the portal here as it is working well for us on normal screens. In other places where we encounter issues, we use Portal. 👍

**Comment by nnaydenow** [comment]
Hi @SAP/ui5-webcomponents-topic-b,

Could you please check this issue? It's reproducible with native ui5-webcomponets as well.
https://codesandbox.io/s/ui5-webcomponents-forked-k8fklj?file=/index.html

**Comment by TobiasKoehler01** [comment]
Hi colleagues,
we have unfortunately the same problem and using the menu in a live project and now need to hold back a new feature that uses the menu component. Any news on this?
