### ISSUE TITLE
[ComboBox, MultiComboBox]:  blur() does not work as expected

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents#7776]
### Bug Description

Need to call blur() to close options after options changed and loading is done
More information is required...

![image](https://github.com/SAP/ui5-webcomponents/assets/15702139/c44af1df-03dd-495e-bd06-f289e7aaf925)

### Affected Component

ui5-combo-box

### Steps to Reproduce

1.
2.
3.
...

### Priority

None

### UI5 Web Components Version

1.16.0

### Browser

Chrome

### Operating System

MacOS

### Organization

SAP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by timogeib** [comment]
setting isLoading to false will remove the after loading of options has finished, will remove the loading indicator as expected, BUT the optionlist is NOT rerendered to show updated options if the options are changed. How should the loading indicator be of any use, if I cannot update the options list after loading is done? Workaround is currently to force close of the optionslist by calling blur() and if the user reopens it, the options are up to date.

**Comment by MapTo0** [comment]
@ilhan007 I am taking over that one.

**Comment by MapTo0** [comment]
Hey @timogeib 

Is this issue with the ComboBox only or it is also valid for the Multi ComboBox component?

**Comment by timogeib** [comment]
@MapTo0 Hello Martin,
good point. For Multi-Combobox it does work, BUT Multi-ComboBox does NOT have the Loading Indicator, which is sad.
I added examples to https://github.tools.sap/I555913/ui5-webcomponents-sandbox

**Comment by timogeib** [comment]
@petyabegovska Is there any reason for having a loading indicator in ComboBox but not in Multi-Combobox?
