### ISSUE TITLE
[Select]: no `readonly` property

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents#7780]
### Feature Request Description

The request is created on behalf of SAP Build Process Automation and it's for adding a readonly property to the Select for a11y reasons.

### Proposed Solution

add new proeprty readonly

### Organization

SAP

### Priority

None

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by nnaydenow** [comment]
Duplicate of https://github.com/SAP/ui5-webcomponents/issues/7727

**Comment by ilhan007** [comment]
close as duplicated
