### ISSUE TITLE
[Table]: One columns always needs to be popped in for the layout to work in transformed mode

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents#7783]
### Bug Description

One columns always needs to be popped in for the layout to work in transformed mode.
More information to be added...
![image (1)](https://github.com/SAP/ui5-webcomponents/assets/15702139/5a59659c-214b-4223-86fb-d9255e342b44)

### Affected Component

ui5-table

### Steps to Reproduce

1.
2.
3.
...

### Priority

None

### UI5 Web Components Version

>=1.16.0

### Browser

Chrome

### Operating System

MacOS

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by timogeib** [comment]
duplicate with #7785

if all columns are popped in it looks like this. (Sandbox updated with example)
![image](https://github.com/SAP/ui5-webcomponents/assets/137267915/26f456f2-9175-4b19-b828-bc517b010718)

**Comment by nnaydenow** [comment]
Hi @timogeib,

Table provides a popin functionality for every column. However, by UX guidelines and implementation of the table, popin requires to keep at least one table column in table layout (without a popin). The intention is not to have all columns with popin activated. You can find more information about this guideline at: https://experience.sap.com/fiori-design-web/responsive-table/#responsiveness

Regards,
Nayden

**Comment by timogeib** [comment]
Yeah this does not work for us, as our customers build the table in an editor and we do not know what columns they put. So we cannot decide which column should be "the one" columns that will stay in the header on smaller screens. Giving the customer the ability to configure this will make the editor unnecessary complex. So we will stick with the workaround then to fix that layout error.
