### ISSUE TITLE
[Table]: layout issue when all columns pop out

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents#7785]
### Bug Description

When all columns are popped out, there is a layout error on the right side where a “navigation” element takes a lot of width.
More Information to be added.

### Affected Component

ui5-table

### Steps to Reproduce

1.
2.
3.
...

### Priority

None

### UI5 Web Components Version

>=1.16.0

### Browser

Chrome

### Operating System

MacOS

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by nnaydenow** [comment]
Hi @ilhan007 
Table provides a popin functionality for every column. However, by UX guidelines and implementation of the table, popin requires to keep at least one table column in table layout (without a popin). The intention is not to have all columns with popin activated. You can find more information about this guideline at: https://experience.sap.com/fiori-design-web/responsive-table/#responsiveness
