### ISSUE TITLE
SegmentedButton: Component crashes on empty children

### ISSUE THREAD

**Issue by codingfabi** [SAP/ui5-webcomponents#7788]
### Bug Description

When adding a segmented button to an app and leaving the children empty, the app crashes (see sandbox). 
I understand that rendering an empty segmented button does not make much sense, however I am trying to implement a usecase where I load the children dynamically. Thus, my app crashes when the children are not (yet) defined.

### Affected Component

SegmentedButton

### Expected Behaviour

I expect the SegmentedButton to not crash the app. 

### Isolated Example

https://codesandbox.io/s/ui5-webcomponents-forked-gvvjcz?file=/index.html

### Steps to Reproduce

1. Add SegmentedButton to an app. Leave the children empty. 
2. App crashes...

### Priority

Medium

### UI5 Web Components Version

1.18.0

### Browser

Chrome

### Organization

SAP - WebcomponentForReact

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ilhan007** [comment]
@SAP/ui5-webcomponents-topic-b add check and early return for the items length before normalizing selection
