### ISSUE TITLE
Input: Icons don't have tooltips

### ISSUE THREAD

**Issue by ej612** [SAP/ui5-webcomponents#7789]
### Describe the bug

We have an `Input` that we use as a search bar.
UX says that all icons need a tooltip. However, neither the search button (if it is considered a button at all, since the cursor doesn't change on mouseover) nor the clear icon have tooltips.

### Isolated Example

https://codesandbox.io/s/heuristic-bell-6p78rw?file=/src/App.jsx

### Reproduction steps

1. Open the attached sandbox
2. Hover over magnifying glass -> No tooltip appears
3. Enter some text
4. Hover over clear icon -> No tooltip appears

### Expected Behaviour

According to UX, all icons need to have tooltips.

Thanks a lot in advance!

**Comment by petyabegovska** [comment]
Hi @ej612,

This behaviour is intentional. After discussions with accessibility experts, SAP Design, and UI5, we have decided to remove the tooltips from buttons inside all input controls.

Best regards,
Petya
