### ISSUE TITLE
[SF][File Upload]: Mouse cursor was not displayed as clickable palm for mouseover

### ISSUE THREAD

**Issue by yuyuCream** [SAP/ui5-webcomponents#7794]
### Describe the bug

Mouse cursor was not displayed as clickable palm for mouseover

https://github.com/SAP/ui5-webcomponents-react/assets/32004690/b165c3e8-c804-456c-a13e-bd4ed7db1da7

### Reproduction steps

1. Navigate to [UI5 Web Components for React ](https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-fileuploader--docs)
2. Scroll to the bottom of the page
3. Hover on the "Upload File", then you can find that mouse cursor was not displayed as clickable palm 

### Expected Behaviour

Mouse cursor should be displayed as clickable palm when hover on the "File Upload"

### Screenshots or Videos

https://github.com/SAP/ui5-webcomponents-react/assets/32004690/23b34151-98d8-4c7c-8708-cac96766893a

### UI5 Web Components for React Version

1.21.2

### UI5 Web Components Version

1.21.2

### Browser

Chrome

### Operating System

mac

### Additional Context

I am from SAP Successfactors and this issue has resulted in several customer incidents.

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by nnaydenow** [comment]
Hi @SAP/ui5-webcomponents-topic-b,

Could you please process the issue? Issue is reproducible in the storybook samples of ui5-webcomponents.
