### ISSUE TITLE
Storybook: show component types as part of the documentation

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents#7796]
Show component types (and in future interfaces) as part of the documentation left-side navigation as follows:
- enums from main package as a folder called "types" inside "main"
- enums from fiori package as a folder called "types" inside "fiori"

When the user selects a single type, we will show a page with the following info:
Title, Overview, ES6 import, Table with the values and their description

For example:
 `enum ButtonDesign`

 `Overview`
 `Different predefined button types for the ui5-button`
 
  `ES6 import`
 `import @ui5/webcomponents/dist/types/ButtonDesign`
 
|Values | Description|
|---|---|
| ButtonDesign.Positive| positive type of button|

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-p can you consider this enhancement of Storybook docs?

**Comment by dobrinyonkov** [comment]
Internal Reference: BGSOFUIPIRIN-6355

**Comment by dobrinyonkov** [comment]
Storybook was superseded by docusaurus.
