### ISSUE TITLE
[DateTimePicker] Enhance Request

### ISSUE THREAD

**Issue by yuyuCream** [SAP/ui5-webcomponents#7802]
### Is your feature request related to a problem?

In CS20230006447358, customer mentioned that "The clock for setting up the time does not have any navigability, the scroll doesn't work so you have to go number by number to move the clock."

UI5 DateTimePicker
![image](https://github.com/SAP/ui5-webcomponents-react/assets/32004690/15f488e9-c085-474f-813d-bad10667f08a)
Web Component for React DateTimePicker
![image](https://github.com/SAP/ui5-webcomponents-react/assets/32004690/c31a3070-e88a-48d2-8a1a-33aa818a1e17)

### Describe the solution you'd like

Can you help to enhance the date time picker in ui5-webcomponent-react to match the look and functionality of the date-time picker in UI5?

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by tsanislavgatev** [comment]
Hello colleagues,

This is a feature request of using the new TimePicker desing in DateTimePicker component.

Best Regards,
Tsanislav

**Comment by DMihaylova** [comment]
Tracked internally as BGSOFUIBALKAN-7451.
