### ISSUE TITLE
[playground]: crashes when typing in HTML

### ISSUE THREAD

**Issue by georgimkv** [SAP/ui5-webcomponents#7805]
### Bug Description

https://sap.github.io/ui5-webcomponents/playground/?path=/story/main-tab-container--basic
If you write HTML into the textarea that corresponds to the default slot, the page will crash.
For example, writing out letter by letter the extra attribute `additional-text="some text"` into the HTML of some `<ui5-tab>` will crash the page. More precisely, as soon as the HTML becomes invalid, which is after the equals sign is typed, the web page becomes blank.
If you paste the whole code instead, it works. This is because the HTML inside the textarea is evaluated at every keystroke.

### Affected Component

playground

### Expected Behaviour

The page will become blank on invalid HTML.

### Priority

High

### UI5 Web Components Version

latest

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by dimovpetar** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

This seems like a generic issue in the playground. The input described by Georgi makes the whole playground crash. I would expect that this just makes the sample temporary broken or busy, until the user stops typing.

Best regards,
Petar

**Comment by dobrinyonkov** [comment]
blocked for now as new solution is in development

**Comment by dobrinyonkov** [comment]
Closing this as new docusaurus playground is implemented.
