### ISSUE TITLE
[Switch]: Rendering issue with Horizon High Contrast Black Theme while :focus

### ISSUE THREAD

**Issue by raynalje** [SAP/ui5-webcomponents#7806]
### Bug Description

Issue with ui5-switch component, with Horizon High Contrast Black Theme while :focus :
- a white circle is displayed
![image](https://github.com/SAP/ui5-webcomponents/assets/139451166/f4feccfb-64ea-418e-8b81-565b0d26fe9c)

The white line should be around the Switch: 
![image](https://github.com/SAP/ui5-webcomponents/assets/139451166/028b8263-4c7c-4470-9fbf-c7218d713ede)

### Affected Component

ui5-switch

### Expected Behaviour

The white line should be around the Switch while focusing the switch : 
![image](https://github.com/SAP/ui5-webcomponents/assets/139451166/028b8263-4c7c-4470-9fbf-c7218d713ede)

### Isolated Example

https://sap.github.io/ui5-webcomponents/playground/?path=/docs/main-switch--docs&globals=theme:Horizon+High+Contrast+Black

### Steps to Reproduce

1. Go on [ui5-webcomponents](https://sap.github.io/ui5-webcomponents/playground/?path=/docs/main-switch--docs&globals=theme:Horizon+High+Contrast+Black) playground
2. Set theme: Horizon High Contrast Black
3. Click and focus the switch
4. White circle appears
...

### Log Output, Stack Trace or Screenshots

![image](https://github.com/SAP/ui5-webcomponents/assets/139451166/f4feccfb-64ea-418e-8b81-565b0d26fe9c)

### Priority

Low

### UI5 Web Components Version

1.19.0

### Browser

Chrome

### Operating System

Windows 11

### Organization

SAP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by petyabegovska** [comment]
Hello @SAP/ui5-webcomponents-topic-b,

Please have a look. The issue is easily reproducible in Storybook.

Best regards,
Petya
