### ISSUE TITLE
SideNavigationItem Font Weight Issue in Horizon Theme

### ISSUE THREAD

**Issue by surjadeep** [SAP/ui5-webcomponents#7808]
### Bug Description

SideNavigationItem which does not have SideNavigationSubItem - still coming as "bold" in Horizon theme.
For not-so-important items which should not be highlighted... they are part of fixed items.

### Affected Component

SideNavigationItem

### Expected Behaviour

We want the control to manually set "not bold" for some SideNavigationItem based on requirement.

### Steps to Reproduce

1.
2.
3.
...

### Log Output, Stack Trace or Screenshots

<img width="1299" alt="Screenshot 2023-11-07 at 11 54 27 AM" src="https://github.com/SAP/ui5-webcomponents/assets/12830367/1b5de555-1fa7-4840-bb7d-6bf61f086be3">

### Priority

Medium

### UI5 Web Components Version

1.22.0

### Browser

Chrome

### Organization

CBC

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by petyabegovska** [comment]
Hello @SAP/ui5-webcomponents-topic-rd,

The current implementation is by design, but CBC colleagues have a use case for the side navigation items under the divider to not be bold. The component can provide a CSS Shadow Part, which will allow the needed flexibility.

Best regards,
Petya

**Comment by surjadeep** [comment]
Hello @gmkv,

I will check with the dev team and get back to you.

**Comment by surjadeep** [comment]
Hello @gmkv,

Sorry! for the late in reply.
In our use-case we are clustering the menus in the category/sub-category model. Hence, we are more focusing on individual entities and that's why we want these to be **bold**, not the top layer of it.
Hope this helps.

**Comment by surjadeep** [comment]
Hello @gmkv,

Any update after my last comment ?

**Comment by TeodorTaushanov** [comment]
Hi @surjadeep,

This issue is fixed since version 1.21:
https://sap.github.io/ui5-webcomponents/playground/?path=/story/fiori-side-navigation--tool-layout

Best,
Teo

**Comment by surjadeep** [comment]
Hello @TeodorTaushanov,

As discussed, please check the issue and let me know.

Regards,
Surjadeep

**Comment by TeodorTaushanov** [comment]
Hi @surjadeep,

With the next version (1.24) of ui5 web components, you will be able to re-style the items like:

`<ui5-side-navigation-item style="font-size: 15rem; font-weight: normal; " ...`

Best,
Teo
