### ISSUE TITLE
custom-element-manifest: add `reference` to the `type` object

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents#7822]
### Feature Request Description

In Web Components for React, we're currently exploring the `custom-element-manifest` for our wrapper generation.
In order to create proper interfaces, we would need an enhancement to the CEM so that the origin of an enum is part of the manifest.

Example:
The following snippet is an excerpt of `ui5-button` CEM:
```json
{
  "default": "\"Default\"",
  "deprecated": false,
  "fieldName": "design",
  "name": "design",
  "type": {
    "text": "ButtonDesign"
  },
  "description": "Defines the component design."
},
```
With this information we know that the `design` attribute is of type `ButtonDesign`, but we don't know where to import the enum from.

### Proposed Solution

To solve this issue, the CEM offers a `references` array as part of the type, where a name and a package can be specified: https://github.com/webcomponents/custom-elements-manifest/blob/efaf2fc1ca3dcd93e4f392e5d9c72840813ad5ea/schema.d.ts#L179-L183

With the new information, the CEM would now look like this:

```json
{
  "default": "\"Default\"",
  "deprecated": false,
  "fieldName": "design",
  "name": "design",
  "type": {
    "text": "ButtonDesign",
    "references": [
      { 
        "name": "ButtonDesign", 
        "package": "@ui5/webcomponents", 
        "module": "dist/types/ButtonDesign.js" 
      }
    ]
  },
  "description": "Defines the component design."
},
```

### Organization

UI5 Web Components for React

### Priority

None

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by petyabegovska** [comment]
Hi @MarcusNotheis,

This request will be resolved with issues #6958 and #7610, which we plan for UI5 Web Components version 1.120.0.

Best regards,
Petya
