### ISSUE TITLE
[DayPicker] Day names are overlapped in Portuguese

### ISSUE THREAD

**Issue by allen138** [SAP/ui5-webcomponents#7831]
### Bug Description

Hi team,

When user is using Portuguese lang, "pt_PT", the day names in the calendar pickers are overlapping. Please see:
![image](https://github.com/SAP/ui5-webcomponents/assets/38701667/d2723271-7d69-4621-acef-9882f39d3627)

The day names are using the 'ultraShortName', [DayPicker.hbs#L20](https://github.com/SAP/ui5-webcomponents/blob/1c211a17ab469fa56dca57e751f1cb9976e87c08/packages/main/src/DayPicker.hbs#L20), which is the abbreviated name, [DayPicker.ts#L359](https://github.com/SAP/ui5-webcomponents/blob/1c211a17ab469fa56dca57e751f1cb9976e87c08/packages/main/src/DayPicker.ts#L359). The abbreviated names are slightly shorter than the 'wide' names as seen here, [cldr/pt_PT.json#L1372-L1410](https://github.com/SAP/openui5/blob/master/src/sap.ui.core/src/sap/ui/core/cldr/pt_PT.json#L1372-L1410), but when I test the classic SAPUI5 pickers, they actually use the 'narrow' day names which is determined with this logic: [sap/ui/unified/calendar/MonthRenderer.js#L218-L222](https://github.com/SAP/openui5/blob/master/src/sap.ui.unified/src/sap/ui/unified/calendar/MonthRenderer.js#L218-L222)

Thanks,
Allen

### Affected Component

Day Picker

### Expected Behaviour

Day names should not overlap.

### Isolated Example

https://codesandbox.io/s/ui5-webcomponents-forked-k9jn4f?file=/src/index.js

### Steps to Reproduce

1. Open the calendar picker and see the day names are overlapping.

### Priority

Medium

### UI5 Web Components Version

main

### Browser

Chrome, Edge

### Operating System

All

### Organization

SF

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by tsanislavgatev** [comment]
Hello colleagues,

Can you please have a look at this issue?

It's reproducible in the provided sample.

Best Regards,
Tsanislav
