### ISSUE TITLE
[Disable for MultiComboBoxItem from MultiComboBox component]: Would be good to have opportunity to disable MultiComboBoxItem. 

### ISSUE THREAD

**Issue by sheva3666** [SAP/ui5-webcomponents#7840]
### Feature Request Description

Would be good to have opportunity to disable MultiComboBoxItem in MultiComboBox component. 

Example: 
We can have several filters in MultiComboBox and after click on some of them other filters can be not applicable. 
Would be good to have opportunity to disable them and not hide  from users. 
It will be better if user see disabled filters and he know that they are exist. 

### Proposed Solution

Provide property disabled. 

### Organization

Signavio

### Priority

Medium

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by IlianaB** [comment]
Hello @SAP/ui5-webcomponents-topic-rl ,
take a look of this feature request.

Regards,
Iliana

**Comment by hristop** [comment]
Hi @sheva3666 ,

We have had discussions regarding this in the past and for now all requests in that direction were rejected by the design team. 

Please consider raising a design request to the Central Design team if you want to raise the topic again. 

Best Regards,
Hristo
