### ISSUE TITLE
[Feature Request]: Support autocomplete attribute for Input

### ISSUE THREAD

**Issue by Roba1993** [SAP/ui5-webcomponents#7841]
### Feature Request Description

Support the `autocomplete` attribute for the `ui5-input` element. 
These are needed for autocomplete inputs from password managers.
e.g. https://developer.apple.com/documentation/security/password_autofill/enabling_password_autofill_on_an_html_input_element

### Proposed Solution

Add the attribute for the input element and forward to the inner component.

### Organization

Exolynk

### Priority

Medium

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by hristop** [comment]
Hi @Roba1993 ,

We will have to reject this feature request. 
We have done extensive research in the past and allowing the usage of this attribute leads to a lot of issues and inconsistencies. 

Some of, but not all of the major concerns are: 

**Security**
All the browsers sore this information in their own way being it on the local machine of the user or in the cloud. This creates the risk of sensitive data leaking out of the SAP application as there is no way of either the control or the browser to know which data is categorized as sensitive.

**Theming**
The popup / icon which indicates that there is option for the input field/s to be auto filled by the browser is dependent on the theme of the browser, not UI5. This can create some bizare looking popups / icons on the screen.

**Browser specific implementation**
The W3C standard for autocomplete can be interpreted and implemented in different way by each browser and can even change between browser versions, which is completely out of our control.

**Different / unpredictable behavior**
Each browser has its own way of showing this and the auto filling is behaving in different ways. Also it is not entirely clear when these popups/icons appear (the browser decides to activate the auto filling of the field/s).

**Different / No eventing**
There is difference in how the change event is fired in the different browsers and it can lead to big problems for control / app developers and users.

Best Regards,
Hristo

**Comment by Roba1993** [comment]
@hristop Thank you for the answer. 
It's fine I will create custom inputs, which will try to reflect the common style a bit.
