### ISSUE TITLE
[Table]: Table Loading indicator style issue. 

### ISSUE THREAD

**Issue by kotireddy-hub** [SAP/ui5-webcomponents#7848]
### Describe the bug

I am using the ui5 table component with growing and sticky header properties.
On the initial load of the table component, the busy indicator icon is getting cut off (PFA).
https://sap.github.io/ui5-webcomponents/playground/?path=/docs/main-table--docs

### Expected Behaviour

The loading indicator should be fully visible and aligned center in the table cell.

### Screenshots or Videos

![image](https://github.com/SAP/ui5-webcomponents-react/assets/52464386/5cdb4854-77f9-41a3-9545-cb4004027a8c)
![image](https://github.com/SAP/ui5-webcomponents-react/assets/52464386/831dafda-5b8f-4907-912e-e5a6d1e923cc)

### UI5 Web Components for React Version

"@ui5/webcomponents-react": "^1.21.0",

### UI5 Web Components Version

 "@ui5/webcomponents": "^1.18.0",

### Browser

Chrome

### Operating System

windows

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by IlianaB** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,
Please check this visual issue with the busy indicator in ui5-table.
The problem is reproducible as described by author, just set "busy" and "stickyColumnHeader" properties to "true".

Regards,
Iliana
