### ISSUE TITLE
Regression: Tab Container CSS "container-type: inline-size;" is breaking popover usage

### ISSUE THREAD

**Issue by ybesnehard** [SAP/ui5-webcomponents#7856]
### Bug Description

Tab Container now use the css property container-type: inline-size that break the fixed position inside its content (usage of popover for example)

### Affected Component

Tab Container

### Expected Behaviour

The Tab Container should not use container-type: inline-size that breaks the fixed position of components inside it

### Isolated Example

https://codesandbox.io/s/ui5-webcomponents-forked-dmwcp7?file=/index.html

### Steps to Reproduce

1. Open the sandbox
2. Click on the tab 1
3. Click on hello button
4. Popup is shown but not at the right position

### Log Output, Stack Trace or Screenshots

![image](https://github.com/SAP/ui5-webcomponents/assets/134484350/cd1d024f-5876-46d1-bd85-2aacd0b4bcdd)

### Priority

Very High

### UI5 Web Components Version

1.19.0

### Browser

Chrome

### Operating System

Windows

### Additional Context

For SAP Build Process Automation, we can't update to the 1.19.0 that have bug fixes we were expecting due to this regression of popover positioning inside the tab container

### Organization

SAP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by IlianaB** [comment]
Hello @SAP/ui5-webcomponents-topic-rd ,
This is a reproducible issue with the given codesandbox example. 
It seems the container-type: inline-size CSS style of TabContainer breaks the fixed position inside its content and as a result Popover is mispositioned. Please, have a look.

Regards,
Iliana

**Comment by TeodorTaushanov** [comment]
Hi @ybesnehard,

The positioning issue is fixed in the main branch. 

We recommend placing popup-like components (ui5-dialog and ui5-popover)
outside any other components. Preferably, the popup-like components should be placed
in an upper level HTML element. Otherwise, in some cases the parent HTML elements can break
the position and/or z-index management of the popup-like components.

Best,
Teo
