### ISSUE TITLE
[Feature Request][Custom Tree Item] Add an ability to focus only content part of Custom Tree item and support focus-visible

### ISSUE THREAD

**Issue by jamesPodo** [SAP/ui5-webcomponents#7858]
### Is your feature request related to a problem?

Due to the accessibility requirement for our product, we have tried to add focus outline to the Custom Tree Item. However, it actually focus the entire tree item not the content inside the custom tree item. Also it seems focus-visible css selector not supported on ui5wc custom tree item

### Describe the solution you'd like

Add a ability to create focus outline on only content part of custom tree item.
Support focus-visible to the Custom tree item

### Additional Context

[Organization] [SAP]
[Product] [SAC]

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by IlianaB** [comment]
Hello @SAP/ui5-webcomponents-topic-p, take a look of this feature request.

Regards,
Iliana

**Comment by kgogov** [comment]
Hello @jamesPodo,

Thank you for suggesting this feature!

Development has already started and it is part of a larger backlog item. You can track the progress here: #8320.

Therefore, I am closing this request.

Best regards,
Konstantin
