### ISSUE TITLE
[Input]: Value is not controllable from outside

### ISSUE THREAD

**Issue by vbersch** [SAP/ui5-webcomponents#786]
Hi,

We received the following bug in our webcomponents-react repo: SAP/ui5-webcomponents-react#134

**Describe the bug**
The inputs value can only be set initially. You can´t change it from outside programmatically afterwards.

**To reproduce**
https://codesandbox.io/embed/mutable-silence-34t4x

type in a negative number. You can see that the App component rerenders and logs the new value state, which is 5. However, the Input still shows the negative number you typed in initially.

**Comment by vladitasev** [comment]
Hi Viktor,

When I type a negative number, f.e. "-5" in the input, it gets changed to "5" and I get a console error:
browserfs.min.js:7 Uncaught TypeError: Cannot read property 'isReadOnly' of null
    at browserfs.min.js:7
    at Worker.<anonymous> (browserfs.min.js:7)
(not sure if the error is relevant at all, just noting)

Then when I try to set another negative number, nothing happens (the negative number stays). Is this the bug you're talking about?

I could not find anything wrong with the ui5-input, f.e. when I type in the console:

document.getElementsByTagName("ui5-input")[0].value = -30;
or
document.getElementsByTagName("ui5-input")[0].setAttribute("value", -50);

it works and the value is changed programmatically just fine.

Can you isolate the bug with just the webcomponent or it only happens with react?

Regards,
Vladi

**Comment by vbersch** [comment]
Hi Vladi,

Thank you for your response. You´re right, the input is perfectly fine.
The reason why it didn´t work, was React´s optimization in setting the internal state.
When the onChange handler fired, the react component set its internal state to 5. The next time onChange was called, the react component tries to set its state to 5 again. However, as the state already was 5, the React component does not rerender and therefore the ui5-input does not get an update.

You have to fully control the input from outside to achieve the desired behavior:
https://codesandbox.io/embed/mutable-silence-34t4x

best regards,
Viktor
