### ISSUE TITLE
Not Able To Identify Input Box (Enable vs Disable) in Horizon Evening

### ISSUE THREAD

**Issue by surjadeep** [SAP/ui5-webcomponents#7874]
### Bug Description

If we have an Input box inside the TabContainer component, there is not much difference between enabled and disabled fields as the background colour is similar and hence difficult to identify.

### Affected Component

Input

### Expected Behaviour

We should clearly identify enable and disable inout box

### Isolated Example

https://codesandbox.io/s/stoic-turing-fzwpgf?file=/src/App.js

### Steps to Reproduce

1.
2.
3.
...

### Priority

Medium

### UI5 Web Components Version

1.18.0

### Browser

Chrome

### Organization

CBC

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by MapTo0** [comment]
Hello @surjadeep 

This is the target design for the disabled input field based on our visual specification.
Anyway, I have forwarded the request to the design team. If they decide to change the implementation I will link this issue so you can track the progress.

Best Regards,
Martin
