### ISSUE TITLE
[Feature Request]: provide reusable CSS to apps built with web components

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents#7884]
### Feature Request Description

Provide reusable CSS to apps built with web components to address: 
- fonts, backgrounds, colours, margins, paddings - already available via `@sap-ui/common-css`
- UI5 Web Component patterns/layouts that can be created with styles without having a dedicated component (for example ToolPage) - not available - to be discussed where to put these styles
- UI5 Web Component customisations - not available - to be discussed where to put these styles

### Proposed Solution

Provide reusable css to applications built with UI5 Web Components to easily re-style components and build component patterns

### Priority

None

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by hristop** [comment]
@ilhan007 we have two requirements that are good candidates to be solved with common CSS, which will actually result in the same solution (whatever that may be) as both require one thing - possibility to style externally added icon in the input field (search, custom icon) with the same styles as the ones that we add (for example clear, value help icons)

#6132 
#7641

**Comment by olannyv** [comment]
I have a need to style so called "Tool Page" : as part of BTP defined UI5 TNT controls we do have sap.tnt.ToolPage, for which we lack Web Component's counterpart. Chances are that we can provide shared & reusable CSS that will simply provide what BTN spec requires (some paddings, rounded corners)
