### ISSUE TITLE
[UI5 Web Components 2.0] Changes suggestion list [Topic RD]

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents#7889]
### **Issue Description**
The goal is to gather a list with breaking changes that you are willing to do to improve/simplify the components API.

- list deprecated APIs within your components that should be removed with 2.0
- list APIs that we would like to improve and change before releasing 2.0

There is already this issue https://github.com/SAP/ui5-webcomponents/issues/4460 with changes we already identified, so first take a look of it - it could be that some of your suggestions are already proposed.

**Comment by TeodorTaushanov** [comment]
Remove Popover.modal property?

**Comment by TeodorTaushanov** [comment]
- [ ] **TabContainer#fixed** - remove after 2.0. It should be always fixed=true.
- [ ] **UploadCollection#mode** - reconsider the property. "Delete" mode is obsolete and not used by the component. Also the design is not clear if modes SingleSelect, SingleSelectBegin and SingleSelectEnd are needed. 
- [ ] **Badge#colorScheme** - change the default value from "1" to "7".
- [ ] **Popover#placementType** - change "placementType" to "placement".

**Comment by olannyv** [comment]
to be handled by team backlog -3203

**Comment by TeodorTaushanov** [comment]
Change PopoverHorizontalAlign Left/Right to Start/End? Also check PopoverPlacementType and PopoverVerticalAlign.

**Comment by dimovpetar** [comment]
Refactor `ITab` interface as follows:

- Rename `getTabInStripDomRef` to more generic term, that also fits the `TabSeparator`
- Replace `getElementInStrip`, `isInline`, `forcedMixedMode`, `forcedPosinset`, `forcedSetsize`, `forcedStyle`, and `isTopLevelTab` with injection mechanism, such that the `TabContainer` supplies this information to the `ITab`, and the `ITab` uses it as it likes.
```ts
interface ITab extends UI5Element {
	applyTabContainerInfo: ({
		elementInStrip: HTMLElement,
		forcedMixedMode: boolean,
		...
	}) => {
		this._elementInStrip = elementInStrip;
                this._forcedMixedMode = forcedMixedMode;
                ...
	}
}
```
- Remove `forcedLevel` from the interface, it is only used in the scope of the TabContainer

**Comment by s-todorova** [comment]
After a team meeting, the following API changes were decided:

- **RadioButton**: deprecate `get strokeWidth()` prior 2.0 and remove after 2.0 
- **CardHeader**: Remove `ICardHeader` interface – it is only used by Card component (may need to bring it back in the future if we extend the component to allow different CardHeader types)
- **UploadCollection**: Remove redundant `IUploadCollectionItem` interface
- **NotificationListGroupItem**: deprecate  `#showCounter`, `#showClose` properties prior 2.0 and remove after 2.0 
- **Popover**: 
  - Change enum values for `PopoverPlacementType` and `PopoverHorizontalAlign`: Left, Right, Top (?), Bottom (?) -> Start/Begin, End
  - Remove `#modal` and `#hide-backdrop` properties 
- **TabContainer**:
  - Remove `TabContainerBackgroundDesign` and use `BackgroundDesign` instead
  - Remove `TabContainer#fixed` and `TabContainer#show-overflow` properties
  - Rename `Tab#subTabs` to `Tab#Items`
  - Refactor `ITab` interface as described in the [comment](https://github.com/SAP/ui5-webcomponents/issues/7889#issuecomment-1931773802) above: Rename `getTabInStripDomRef` (name tbd - `getItemInStripDomRef` / `getElementInStripDomRef` )
- **Badge**: change `#design` and `#colorScheme` default values

The following changes are still up for discussion:
- **UploadCollection**: Additional meeting will be held do decide changes to `#mode` property - currently uses ListMode (to be [changed](https://github.com/SAP/ui5-webcomponents/issues/7887#issuecomment-1941577787)), but we want to get rid of Delete option for UploadCollection
- **NotificationAction**: possible deprecation as part of  BGSOFUIRODOPI-3226 (replacing actions button with menu) 
This and further changes will be decided during implementation of BIs related to the new Notifications concept.

**Comment by TeodorTaushanov** [comment]
Deprecate SideNavigationItem.wholeItemToggleable as it won't be needed after implementing SideNavigation single & two-click areas.

**Comment by ilhan007** [comment]
External Feedback

**ui5-card-header**:
- status: only available on the ui5-card-header, in other components, a similar text is set with the additional-text attribute. I would suggest replacing this and only using additional text for these texts that are a bit off…
- title-text and subtitle-text could also be called header-text as in many other components (e.g. ui5-dialog) and description as the subtitle doesn’t appear to be a subtitle rather a description.


**ui5-carousel**: 
- items-per-page: setting the number of items per page per size with individual attributes is very clumsy. I wonder if this could be solved either by a type that iterated the valid options or better by a string that represents an array like in lex-box or so: items-per-page=”1 1 2” which would then be parsed into the three values.

- page-indicator-style: would be a good candidate for the design attribute.


**ui5-tab-container**:
- fixed: being able to collapse a ui5-tab-container is a feature that is assumed to lead to confusion with users as a collapsed tab container has no way of clearly indicating that it is collapsed. We would prefer to discard this property. If this is not possible, calling it collapsible and making it an optional attribute with default set to false would be more in line with our expectation. This should then also be aligned with the ui5-panel.
- tab-layout: Could this not be done via the design attribute?
- tab-overflow-mode: these attributes are very specific while they are attributes of the tab container, they all contain tab in the name which seems unnecessary. An overflow attribute could also be used in other components.

**ui5-busy-indicator**
- size: this is current used as AvatarSize and BusyIndicatorSize with completely different values. The busyindicator accepts “Small”, “Medium”, “Large” while the sizes for the avatar range from “XS” to “XL”. This makes it hard to learn so I would suggest to use one way of defining sizes. Even if you continue using different types, the values could follow the same logic.  

Change: BusyIndicatorSize -> S, M, L
