### ISSUE TITLE
Color Palette should be able to have a selected value

### ISSUE THREAD

**Issue by ybesnehard** [SAP/ui5-webcomponents#7892]
### Feature Request Description

Today the color palette just display a list of color item, when opening the ColorPalettePopover the first item is always focused. We would like to be able to choose which ColorPaletteItem is selected

![image](https://github.com/SAP/ui5-webcomponents/assets/134484350/f4b5fe96-7998-4700-b5ea-89b46e6a47ea)

### Proposed Solution

For a ColorPalette, an item should be selectable

### Organization

SAP

### Additional Context

SAP Build Process Automation

### Priority

Medium

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by MapTo0** [comment]
Hello @ybesnehard,

Could you please be more specific on the requirement.
You expect the selected colour to be focused after opening or you want some special indication of the selected colour?

Best Regards,
Martin

**Comment by ybesnehard** [comment]
Hi @MapTo0 yes exactly, have it focused instead of the first item would be enough for us. 
Many Thanks,
Yannick

**Comment by MapTo0** [comment]
Hello @SAP/ui5-webcomponents-topic-b , 

Take a look of this feature request.
Keep in mind that the current behaviour is the same as OpenUI5's behaviour.
The requirement is to focus the selected color (if there is such) once the Popover is open.

Best Regards,
Martin

**Comment by DMihaylova** [comment]
Hello @ybesnehard,

We're already working on the item and you could track the progress in this item: https://github.com/SAP/ui5-webcomponents/issues/7073

Thanks & Regards,
Diana
