### ISSUE TITLE
Storybook: missing overview section for sub components

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents#7895]
### **Issue Description**
The overview information that was previously available is no longer displayed for sub-componets.

For example, see StandardListItem, CustomListItem, etc.

### **Issue Type**

- [ ] Documentation is unclear
- [ ] Documentation is incorrect
- [ X ] Documentation is missing
- [ ] Other

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-p could you take a look of this issue?

**Comment by dobrinyonkov** [comment]
Fixed with https://github.com/SAP/ui5-webcomponents/pull/8012
