### ISSUE TITLE
[Feature Request]: make use of the standard Popover API

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents#7897]
### Feature Request Description

The Popover API provides developers with a standard, consistent, flexible mechanism for displaying popover content on top of other page content.

https://developer.mozilla.org/en-US/docs/Web/API/Popover_API

Currently, we use the so called `static area` to overcome multiple issues caused by page styles resulting in popups misplacement.
The new Popover API deals with those issues. 

### Proposed Solution

Use the Popover API in our dropdown components - (Multi)ComboBox, Select, Suggestions, etc.

### Priority

None

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ilhan007** [comment]
The feature is available in all browsers, but Firefox (the topic is in progress). The BLI will wait for complete support before starting with the refactoring.

**Comment by boghyon** [comment]
`popopver` now enabled by default in FF 122: https://www.mozilla.org/en-US/firefox/122.0a1/releasenotes/#note-789883

**Comment by vasicvuk** [comment]
+1, the current implementation with Z-index causes a lot of problems for us, I tried overriding the behavior of dialog to hide static content and use popover within shadow dom, but unfortunately then validation errors were behind the dialog

**Comment by nnaydenow** [comment]
Adopted in: https://github.com/SAP/ui5-webcomponents/pull/8192
