### ISSUE TITLE
[Busy Indicator]: Theming Issue in Belize

### ISSUE THREAD

**Issue by mhchem** [SAP/ui5-webcomponents#7901]
### Bug Description

The Busy Indicator does not have the right appearance in the Belize theme.
This is very visible when having UI5 and UI5 Web Components in the same application.

### Steps to Reproduce

Compare
* https://sapui5.hana.ondemand.com/?sap-theme=sap_belize#/entity/sap.ui.webc.main.BusyIndicator/sample/sap.ui.webc.main.sample.BusyIndicator
* https://sapui5.hana.ondemand.com/?sap-theme=sap_belize#/entity/sap.m.BusyIndicator/sample/sap.m.sample.BusyIndicator

(Also, the sizes differ. And the animation differs slightly: With UI5, there is a moment when all 3 bubbles are the same size, but this does not happen for Web Components. But most important is the color difference.)

### Priority

None

### UI5 Web Components Version

Demo Kit 1.120

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by MapTo0** [comment]
Hi, Team,

Belize issue for the Busy Indicator, please have a look.

Regards,
Martin

**Comment by s-todorova** [comment]
Hello @mhchem,

The difference in color has been fixed. 

However, support for the Belize theme has been deprecated for ui5 and Web Components will soon follow. Therefore, after consideration it was decided that further adjustments to the animation/size difference would require more effort than appropriate, considering the upcoming deprecation of support for Belize theme.

We strongly suggest updating to Horizon theme.

Best regards,
Siyana
