### ISSUE TITLE
[Feature Request]: CheckBox display mode

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents#7911]
### Feature Request Description

The request is for adding a property and respective visual design as per the SAP Design spec for "display" mode.
The request comes from the SAP Brand LoB that would like to use the CheckBox in "display" mode in forms.

### Proposed Solution

Add property similar to the SAPUI5 CheckBox and implement the existing design as specified.

### Organization

SAP Brand

### Priority

None

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by dobrinyonkov** [comment]
Internal Reference: BGSOFUIPIRIN-6388
