### ISSUE TITLE
List: Blue selection overlapping with the text inside the cell of the list

### ISSUE THREAD

**Issue by DikshaHub** [SAP/ui5-webcomponents#7926]
### Describe the bug

In a list, on selection of any cell we get a blue box representing that a particular cell is selected. But there's a gap between the cell border and the blue box. Hence, when the resolution is high it overlaps with the text inside the cell. The text is unreadable. Please check the screenshot attached.

### Reproduction steps

The text "Enterprise Best Practices (B1)" inside the list is overlapping with the blue selection box. It's not readable. 

### Expected Behaviour

The text should not overlap with blue selection and hence be readable.

### Screenshots or Videos

![Blue selection overlapping](https://github.com/SAP/ui5-webcomponents-react/assets/66899235/be8bc53b-2087-4218-99b0-0629e282e0f8)

### UI5 Web Components for React Version

^1.16.3

### UI5 Web Components Version

^1.14

### Browser

Chrome

### Operating System

Mac

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by GerganaKremenska** [comment]
Hello @DikshaHub,

Can you adapt this [sandbox](https://codesandbox.io/s/ui5-webcomponents-forked-t9zryj?file=/index.html), to match your use case, as  I can not recreate the issue?
Is this a list or a Table? 

Best Regards,
Gergana

**Comment by DikshaHub** [comment]
Hi GerganaKremenska,
Its about List. 
Please refer for following example recreated in codeSandBox 

Isolated Example:
https://codesandbox.io/s/dynamicpage-flexiblecolumn-forked-5lg37d?file=/src/App.js

Reproduction Steps:
1. Click on second row of the list i.e. "List Item 2".
2. A blue box selection will appear for the second row.
3. Using "up arrow key" from the keyboard scroll to first row. i.e. "List Item 1 ASDTFSUHS OKOISGBXJMLBVYFTSGJA".
4. You can see the blue box selection overlapping with the text inside the cell. (attached screenshot) 

screenshot : ![image](https://github.com/SAP/ui5-webcomponents/assets/66899235/f68822f8-01ed-4dd6-89b9-6034376275f7)

Expected Behaviour: 
The text should not overlap with blue selection and hence be readable.

**Comment by DikshaHub** [comment]
Hey @Lukas742 , @GerganaKremenska and @nnaydenow when can I expect response on this issue ?
