### ISSUE TITLE
[TextArea]: growingMaxLines property only seems to work until a certain value

### ISSUE THREAD

**Issue by Vir-Mittal** [SAP/ui5-webcomponents#7930]
### Bug Description

For the tex area component, when we set the growing property to true and the growingMaxLines to a certain number, we expect that number of lines to be visible before a scrollbar shows up

For example - 
When growingMaxLines is 4, 4 lines are shown - 

<img width="1787" alt="Screenshot 2023-11-28 at 8 27 29 AM" src="https://github.com/SAP/ui5-webcomponents/assets/36656306/bc4f803e-6698-40f0-84fb-c5b27060f61e">

When its 7, 7 lines are shown - 

<img width="1792" alt="Screenshot 2023-11-28 at 8 27 44 AM" src="https://github.com/SAP/ui5-webcomponents/assets/36656306/a28ac2ca-2545-4277-9a9e-08dd969299a0">

But, when its 8 or any number greater than 8, still only 7 lines are shown - 

<img width="1790" alt="Screenshot 2023-11-28 at 8 28 04 AM" src="https://github.com/SAP/ui5-webcomponents/assets/36656306/6b6f19cd-e46d-4d73-a168-3b244091a103">

Tested using https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-textarea--docs

### Affected Component

TextArea

### Expected Behaviour

growingMaxLines property should work as expected

### Steps to Reproduce

1. Go to https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-textarea--docs
2. Input a large text in the text area
3. Change the growingMaxLines value

### Priority

None

### UI5 Web Components Version

1.19.0

### Browser

Chrome

### Operating System

MacOS

### Organization

SAP SuccessFactors

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by GerganaKremenska** [comment]
Hello @Vir-Mittal,

Can you retest the issue? 
As it is not reproducible now on: https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-textarea--docs

Or are there any steps different from setting "growing": true,  and changing the number of "growingMaxLines"?


Best Regards,
Gergana
