### ISSUE TITLE
[Carousel]: flickering on loading 

### ISSUE THREAD

**Issue by MaksimShakavin** [SAP/ui5-webcomponents#7931]
### Bug Description

The onResize method seems to be triggered following the initial rendering of the component. This leads to the width of carousel elements being set to zero after the first render, resulting in a flickering effect. This issue may not be immediately apparent due to the rapid rendering process, and the fact that in the provided storybook examples, the internal items are web-components, which do not display until they are defined. However, the problem becomes evident when the carousel item is a standard HTML element rather than a web-component.
![CarouselResize](https://github.com/SAP/ui5-webcomponents/assets/9590193/e6942e80-65f4-42cf-b539-b9efadea71bc)

### Affected Component

Carousel

### Expected Behaviour

Nothing flickers

### Steps to Reproduce

1. Go to carousel example page in storybook
2. Place debugger breakpoint in a "onAfterRendering" method.
...

### Priority

Medium

### UI5 Web Components Version

latest

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by dimovpetar** [comment]
Hello @MaksimShakavin ,

Please check this [CodeSandbox ](https://codesandbox.io/p/sandbox/ui5-webcomponents-forked-jhc7yp?file=%2Findex.html%3A16%2C28). It consists of `ui5-carousel` with `div` items that have red borders. Though I have configured 2 items per page, at the beginning all items are displayed one under the other. When the `ui5-carousel` is upgraded, they are displayed properly. Is the transition from 5 items one under the other to well displayed `ui5-carousel` with 2 items you are referring to?

Best regards,
Petar
