### ISSUE TITLE
Dialog: Is covered in the block layer and is unusable

### ISSUE THREAD

**Issue by jannislmml** [SAP/ui5-webcomponents#7938]
### Describe the bug

If you open a dialog, it is also covered by the block layer and you can no longer interact with it. I open the dialog via the onClick event of a button. Attached is a screenshot on which the problem can also be seen visually.

Please fix this ASAP. 
Thanks.

### Reproduction steps

1. Open a Dialog via Button
2. Try to interact with it

### Screenshots or Videos

![grafik](https://github.com/SAP/ui5-webcomponents-react/assets/123730310/414fb39c-d1be-4004-8028-19569c36b9db)

### UI5 Web Components for React Version

1.22.2

### UI5 Web Components Version

1.19.0

### Browser

Chrome

### Operating System

Windows 10

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ilhan007** [comment]
Hello @jannislmml not sure how to make progress without reproducible environment. 
Are you a SAP internal, can you contact us via the internal channels. Or, can we setup your project to investigate futher?

**Comment by pixel-fabian** [comment]
Hi,

we used to have a similar problem when using the ui5-dialog within Vue.js components and needed [vue teleport](https://vuejs.org/guide/built-ins/teleport.html). Maybe you could add a hint to [ui5-webcomponents info for vue](https://sap.github.io/ui5-webcomponents/playground/?path=/docs/docs-frameworks-vue--docs#additional-info)?

**Comment by MFel0123** [comment]
Hello colleagues,
we can confirm that we have the same problem in an angular environment. With 1.18.0 our ui5-dialog is working fine. The background is inactive (using the class ui5-block-layer). With the new ui5-webcomponents version 1.20.1 this is not working anymore: the background is inactive but the ui5-dialog as well. So it seems to be a central problem in ui5 web components.

Best Regards

**Comment by MFel0123** [comment]
Hello colleagues,
this issue is not solved. Please proceed working on it.

Kind Regards

**Comment by jannislmml** [comment]
This issue isnt fixed in version 1.22.0

**Comment by Andrei-Zaharescu** [comment]
Hi @ilhan007 - I've seen you reopened the ticket and therefore I sent you an invite the repo so that you can easily reproduce it. Maybe it helps. 

Steps: From the side navigation, under **Inventory** choose **Materials** and click on **Advanced filters** button (top right).

**Comment by nnaydenow** [comment]
Hi @Andrei-Zaharescu,

Is it possible to provide public isolated example since someone else might process the issue and it will be hard if we have to contact or ask permission for every processor. Thanks in advance.

**Comment by Andrei-Zaharescu** [comment]
Hi @nnaydenow,

I have created an example as requested: https://stackblitz.com/edit/stackblitz-starters-phmjcj?file=src%2Fapp%2Fside-navigation%2Fside-navigation.component.scss

Yet, while I was working on the simplified version I bumped into the root cause. It looks like it was related to some custom CSS. I use Fiori side navigation (https://sap.github.io/ui5-webcomponents/playground/?path=/story/fiori-side-navigation--tool-layout) and in the `tool-layout` CSS class I've added a property that caused this behaviour. 

I'm not a frontend expert so I let you guys to decide if this should still be open or not.

Thank you.

**Comment by nnaydenow** [comment]
Hi @SAP/ui5-webcomponents-topic-rd,

The issue author provided example where the issue is reproducible. Could you please take a look again?

**Comment by Andrei-Zaharescu** [comment]
Hi @TeodorTaushanov,

Thanks for the updates. Well, I can't do that as the `tool-layout` contains like everything. The `position: fixed` was used to remove that annoying scroll bounce but I've found another way.

**Comment by sathian-icd** [comment]
There is work around for this. Not sure if you can do this but this works tho

Add this when the dialog is opened :


      let ui5StaticAreaItem: any[] = this.document.querySelectorAll('ui5-static-area-item'); 
      ui5StaticAreaItem.forEach((element) => {
        if (element.shadowRoot) {
          let blockLayer = element.shadowRoot.querySelector('.ui5-block-layer');
          if(blockLayer!==null){
            blockLayer.style.display = 'none';
          }
        }
      })
  
  
  
  and add an another custom div to block layer behind the dialog to block and set z-index to 10 and other things required.
