### ISSUE TITLE
Czech characters are incorrectly displayed in the "72" font-family

### ISSUE THREAD

**Issue by rama1990br** [SAP/ui5-webcomponents#7948]
### Bug Description

Czech characters like “Č” and “Ĺ” are incorrectly displayed in React UI5-WebComponent based pages which use "72" `font-family`s like "72override", "72", "72full", "72-Bold", "72-Boldfull", etc, as shown in the attached screenshots.

### Steps to Reproduce

1. Log into the instance, the details of which are provided in #sap-tech-ui5-wc-sfsf channel [here](https://sap-successfactors.slack.com/archives/CTHEMAZ8C/p1701458185774639).
2. Search for "Čeněk Pěč" in the global search and see that the first character is not displayed properly 
3. Search for "Martina Tarageĺ" in the global search and see that the last character is not displayed properly

### Priority

None

### UI5 Web Components Version

1.18.0

### Browser

Chrome, Edge, Firefox, Safari

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by rama1990br** [comment]
Hi @ilhan007,
Is it possible to downport the fix for this to version 1.18.0?

**Comment by rama1990br** [comment]
Hi @ilhan007,
Is this fix part of 1.20 version as well? Cause I have bumped the version of ui5-webcomponents to 1.20.0 and I still see the issue in the homepage.

**Comment by ilhan007** [comment]
Hi @rama1990br , it's we have tested it with an input 
https://sap.github.io/ui5-webcomponents/playground/main/pages/FontFace/
<img width="305" alt="Screenshot 2023-12-08 at 9 37 25" src="https://github.com/SAP/ui5-webcomponents/assets/15702139/d95d46ce-e032-45bb-b70c-aa6e5a4367b6">
Could be that there are additional styles causing the issue. Do you experience the issue with regular ui5-input component?

**Comment by ilhan007** [comment]
As discussed offline, you confirmed - the issue is resolved on your side after update. Downports will follow in 1.17

**Comment by ilhan007** [comment]
Released with 1.17.3
