### ISSUE TITLE
[Select] Readonly property missing (specified in SAP visual specs)

### ISSUE THREAD

**Issue by sebkaim** [SAP/ui5-webcomponents#7958]
### Bug Description

**No readonly property**: 
There is no readonly property to make the Select readonly (which is specified though in SAP's visual specs for the select / input field

There is a property disabled but it does not render the component like a normal text and it's incorrect semantically.

### Affected Component

Select

### Expected Behaviour

A select should have a property to set it to readonly.

### Steps to Reproduce

1.
2.
3.
...

### Priority

Medium

### UI5 Web Components Version

1.10.0

### Browser

Chrome

### Operating System

Mac

### Organization

SAP Signavio

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ilhan007** [comment]
Hello @sebkaim the readonly state will be present with the next monthly release 1.21.0 - start of Jan

More on the feature enablement here: https://github.com/SAP/ui5-webcomponents/pull/7950

**Comment by sebkaim** [comment]
[like]  Kaim, Sebastian reacted to your message:
________________________________
