### ISSUE TITLE
[Feature Request] Combo Box / Multi Combo Box: Show placeholder even when readonly or disabled

### ISSUE THREAD

**Issue by sebkaim** [SAP/ui5-webcomponents#7959]
### Feature Request Description

If the readonly or disabled attribute is true, the placeholder will be gone even if the combobox is empty.

This leaves the user with an empty and disabled/readonly combox. If that comboxbox does not use a label, it is unclear for the user what to usually find in the combobox.

### Proposed Solution

Still show placeholder in case no value is selected and property disabled or read-only is true

### Organization

SAP Signavio

### Priority

Medium

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-rl 

this belongs to you, I think the placeholder is hidden as this how it's specified in the design specs and guidelines,

but nevertheless forwarding it to give your expert statement.

**Comment by hristop** [comment]
Hi @sebkaim ,

We have discussed this with our design colleagues and here is their answer: 

> "Placeholders in components such as inputs should be hidden in these cases (disabled, read-only) and only visible if you can type."

So, I am closing the issue. 

Best Regards,
Hristo

**Comment by sebkaim** [comment]
Thanks for involving other colleagues.

Instead of having a normative statement like "..should be hidden", it would be nice to hear _why_. This would increase the acceptance and trust in the central team's decisions by LoBs, especially since other frameworks and leading SaaS companies have that intended behaviour in place.

**Comment by hristop** [comment]
Hi @sebkaim ,

I appreciate the feedback. Here is what I got as an answer: 

> Hi here is a quick explanation - both are not editable. Placeholders make sense only for giving initial prompt to the user what to edit (choose an option of write something). This is also the explanation why empty components are not to be used in disabled and especially not in read only state. Read only is supposed to be fully readable and to be giving the opportunity to copy the text from it, but not to be used as blank space.

If you feel you need more info, the specific LoB design team can always contact the Central Design team and ask for such. 

Best Regards,
Hristo
