### ISSUE TITLE
[ui5-card]: Content is not scrollable with fixed height

### ISSUE THREAD

**Issue by kozubikmichal** [SAP/ui5-webcomponents#7962]
### Bug Description

When the card is set with fixed height (or to fit a container with a fixed height) and the content of the card is larger and the card, it's cut off and user is not able to see all of it, because the scrolling is not possible.

Unfortunately it can't be fixed on app level, because this is how the elements are setup inside the shadow dom of the web component itself. See the codesandbox for more info and possible fix/workaround

### Affected Component

Card

### Expected Behaviour

Content area is scrollable if the content is larger then the available space

### Isolated Example

https://codesandbox.io/p/sandbox/ui5-webcomponents-forked-8zcng3
https://codesandbox.io/s/ui5-webcomponents-cards-scroll-fpx9hn?file=/index.html

### Priority

None

### UI5 Web Components Version

1.20.0

### Browser

Chrome

### Organization

SAP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by unazko** [comment]
Hello @SAP/ui5-webcomponents-topic-rd,

The provided sample doesn't load at my side even in incognito mode.
Tried with different browsers than Chrome.

Also the Card.html page loads with errors at my side.

Couldn't reproduce for those reasons.
The issue description is clear though.

Best regards,
Boyan

**Comment by unazko** [comment]
Hello @SAP/ui5-webcomponents-topic-rd,

I was able to reproduce the issue in a local environment.
Copy the `ui5-card` html into the Card.html example.
You could see that the last list items are cut off and there is no scroll enabled.

Best regards,
Boyan

**Comment by s-todorova** [comment]
Hello @kozubikmichal ,

As per our guidelines, it is not advised to have scrolls inside ui5-card, therefore we cannot directly provide a fix for the issue described. Instead, we strongly recommend to let cards grow as needed, without restricting their height.

However, we have now provided a way to do so if you want by exposing the "root" and "content" CSS parts, so you can use those to achieve this as you see fit.

Best regards,
Siyana
