### ISSUE TITLE
[i18n] Can't set language en_US_sappsd

### ISSUE THREAD

**Issue by ej612** [SAP/ui5-webcomponents#7965]
### Bug Description

In our repo, we have a messagebundle_en_US_sappsd.properties, the keys of which look like this:
```
AVAILABLE_ITEMS=[[[Āʋąįĺąƃĺē Ĭţēɱş∙∙∙∙]]]
``` 
I recently learned that this is called "2Q" or "Pseudo-translation" and is used for finding hard-coded strings in the UI and to test whether the UI elements leave enough space for the respective translated strings in all languages.
 
I tried setting this language:
```
import { setLanguage } from '@ui5/webcomponents-base/dist/config/Language';
await setLanguage('en_US_sappsd')
```
This had no effect at all, all strings were still in default English.
Since there’s a properties file for it, I suppose there’s a way to activate this language somehow?

Thanks a lot in advance!

### Organization

SAP

**Comment by unazko** [comment]
Hello @SAP/ui5-webcomponents-topic-core,

I saw that there is already a linked pull request, which will fix this issue.
Labeling this issue as per process.

Best regards,
Boyan
