### ISSUE TITLE
[ui5-side-navigation]: Not customizable after upgrade to 1.20.0

### ISSUE THREAD

**Issue by kozubikmichal** [SAP/ui5-webcomponents#7982]
### Bug Description

After upgrade to the web components v1.20.0, we lost the customization options for the Side Navigation component, which introduced 2 issues in our product:

1. New version provides less space for the text and does not support changing of the width anymore -> some of our texts are now broken into multiple lines. Setting the `width` CSS property does not work (was working before this update)
2. Border radius cannot be changed again (was fixed it #7308, after upgrade it's not working anymore)

As working with the codesandbox is not good on SAP enrolled devices, feel free to contact me via corporate communication channels and I can provide you more details.

<img width="843" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/26189327/2c2c23b6-07c1-476e-93ff-ac8b8bdfdee9">

With highlighted element:
<img width="816" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/26189327/d8f025d3-dfad-461e-bd08-6f27a2511e5c">

### Affected Component

Side Navigation

### Expected Behaviour

1. Space for the texts should remain the same OR there should be an option how to adjust it (eg. `width` property)
2. Rounded corners should not be mandatory, as it was in previous version (`border-radius` property)

### Priority

Medium

### UI5 Web Components Version

1.20.0

### Browser

Chrome

### Organization

SAP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by unazko** [comment]
Hello @SAP/ui5-webcomponents-topic-rd,

Tested at the following URL:
https://sap.github.io/ui5-webcomponents/playground/?path=/story/fiori-side-navigation--basic

Indeed the `border-radius` and `width` aren't customizable.

Please have a look.

Best regards,
Boyan
