### ISSUE TITLE
Barcode Scanner Dialog problem after bad contente scan

### ISSUE THREAD

**Issue by joseserrano15** [SAP/ui5-webcomponents#7987]
### Bug Description

When scanning a barcode, the scanner sometimes does not read the correct content and only returns a random number. When this happens, when trying to open the scanner again, the dialog does not open and the scan-success event is automatically executed. in addition to throwing the following warning in the console 'Trying to play video that is already playing'. The number of warnings and events increases with each click (1..2..3..etc) and the camera on indicator (a small LED) stays on.

### Affected Component

Barcode Scanner Dialog 

### Expected Behaviour

The scanner should continue to operate if the correct content of the barcode is not read.

### Steps to Reproduce

1. Open the scan dialog and scan a barcode
2. The content of the barcode being scanned is not correct
3. Try to open the dialog again

### Log Output, Stack Trace or Screenshots

![image](https://github.com/SAP/ui5-webcomponents/assets/68348356/d0f90307-1e14-44fe-9080-833a7c71a8be)

Every time the button is pressed to open the dialog, one more warning is displayed as well as an automatic success event.

### Priority

Medium

### UI5 Web Components Version

1.16.0

### Browser

Chrome, Edge

### Operating System

Windows

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by PetyaMarkovaBogdanova** [comment]
Hi @joseserrano15 ,
thank you for your submission.
It will be too hard for us to reproduce it, since all our tests are returning correct results. Can you, please, send us a picture of the barcode that you use in or order to be scanned badly and also, did you manage to reproduce the issue with our samples or you used it inside your application? If so, can I see an example of how it is used, so we can get clear perspective on the problem. Thank you!

Best regards,
Petya Markova.
(UI5 WC Developer)

**Comment by joseserrano15** [comment]
Thanks for the help.

The problem occurs both in the documentation example (https://sap.github.io/ui5-webcomponents/playground/?path=/docs/fiori-barcode-scanner-dialog--docs) and in my own application (code attached).


```
<ui5-button design="Default"
                    icon="bar-code"
                    tooltip="Escanear"
                    (click)="startScan()">
</ui5-button>
        
startScan() {
    const diagScan = document.getElementById('diagScan')

    if (diagScan) {
      diagScan.show()

      diagScan.addEventListener('scan-success', e => {
        console.log(e)
        diagScan.close()
      })

      diagScan.addEventListener('scan-error', e => {
        console.error(e)
        diagScan.close()
      })
    }
  }        
```
 
This is the barcode, it is printed on a cardboard box.
![Barcode](https://github.com/SAP/ui5-webcomponents/assets/68348356/dc053e2f-e456-4098-a6fe-5d03cbaf3a2b)

As an additional fact, sometimes the correct information is obtained from the code and when this happens, operation is not affected. The problem only occurs when you get the random number when scanning and not the content of the code.

**Comment by PetyaMarkovaBogdanova** [comment]
Hi colleagues,
I couldn't reproduce the issue with many attempts. Can you, also, try to?
Thank you!

Best regards,
Petya Markova.
(UI5 WC Dispatcher)
