### ISSUE TITLE
MultiComboBox - Adding customizable search function

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#799]
**Describe the solution you'd like**
Right now the MultiComboBox has a default search that implements the startsWith function. 
It would be great to have an opportunity to add a custom search functions (e.g. contains, ignore case, etc.).

**Comment by vladitasev** [comment]
Check if it makes sense to allow the user to control this externally without adding a new function property.

**Comment by sunnyyadav100** [comment]
Can this feature support auto-complete? It will we nice it supports auto-complete and allow custom values to add.

**Comment by MapTo0** [comment]
Hello all,

Is the following API OK for you:

```
<ui5-multi-combobox filter="None" allow-custom-values>
  <ui5-mcb-item text="Item 1"></ui5-mcb-item>
  <ui5-mcb-item text="Item 2"></ui5-mcb-item>
  <ui5-mcb-item text="Item 3"></ui5-mcb-item>
</ui5-multi-combobox>
```

After that you can listen for `input` event and always define your items based on the `value` property.

Build in filters will be the following: `StartsWith, StartsWithPerTerm, Contains, None`

**Comment by Lukas742** [comment]
Hi @MapTo0 

looks good to me. Thanks a lot!
