### ISSUE TITLE
Incorrect Default Time in DateTimePicker 

### ISSUE THREAD

**Issue by rahish13** [SAP/ui5-webcomponents#7992]
### Bug Description

The DateTimePicker component in our UI5 web application is exhibiting unexpected behavior related to the default time when selecting a date. It consistently provides an incorrect default time instead of occasionally using the local time, which is causing usability and data entry issues for our users.

### Affected Component

DateTimePicker

### Expected Behaviour

When selecting a date, the DateTimePicker should automatically use the local time or, at the very least, display a time value that accurately corresponds to the selected date.

### Isolated Example

https://codesandbox.io/p/sandbox/unruffled-bose-clwcy8

### Steps to Reproduce

Navigate to the DateTimePicker in the application.
Select a date by clicking on the calendar icon.
Observe that the DateTimePicker sets an incorrect default time.

![image](https://github.com/SAP/ui5-webcomponents/assets/153607220/ecd5646c-5ac3-4d84-acb7-04223cfafd94)
![image](https://github.com/SAP/ui5-webcomponents/assets/153607220/c9b154fd-78a4-4b2d-abea-d47d1edbf1ca)

### Priority

High

### UI5 Web Components Version

1.17.0

### Browser

Edge

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by PetyaMarkovaBogdanova** [comment]
Hi colleagues,
can you, please, why the default time set is not correct in the sandbox sample.
I couldn't reproduce it with our storybook example, but inside the sandbox with the removing of "**data-ui5-compact-size**" the problem seems to be solved.

Best regards,
Petya Markova.

**Comment by rahish13** [comment]
We are using this "data-ui5-compact-size" in our code, so we cant remove this.

**Comment by rahish13** [comment]
Hi team i am waiting for your reply.

**Comment by rahish13** [comment]
Hi Team, it's been 5 days, no response from your side.

**Comment by petyabegovska** [comment]
Hello @rahish13, the team is investigating the issue and will reply you as soon as has findings.

Best regards,
Petya

**Comment by tsanislavgatev** [comment]
Hello @rahish13,

We are currently working on a fix of the issue.

Best Regards,
Tsanislav

**Comment by rahish13** [comment]
Hi Team in which version of ui5 you have fixed this?

**Comment by rahish13** [comment]
Hi Team in which version of ui5 you have fixed this?

**Comment by ilhan007** [comment]
@rahish13 in 1.22.0
