### ISSUE TITLE
Popover: footer is not positioned correctly if a height is applied

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#8009]
### Bug Description

The `Popover` and `ResponsivePopover` don't position the footer correctly if a `height` is applied to the popover. 

### Affected Component

probably all popover components

### Expected Behaviour

Even with fixed height, the footer should be positioned at the bottom of the popover.

### Isolated Example

https://codesandbox.io/s/ui5-webcomponents-forked-dsg8rl?file=/index.html

### Steps to Reproduce

1. Go to [codeSandbox](https://codesandbox.io/s/ui5-webcomponents-forked-dsg8rl?file=/index.html)
2. Open one of the popovers that have a fixed height
3. See that the footer is misaligned

### Log Output, Stack Trace or Screenshots

<img width="340" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/9749730/b5760d9a-0ba9-4613-8196-af90ec8aa6aa">

### Priority

None

### UI5 Web Components Version

1.20.1

### Browser

Chrome

### Organization

UI5 Web Components for React

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by PetyaMarkovaBogdanova** [comment]
Hi team,
can you, please, take a look at the position of ui5-responsive-popover, when height is set?
Best regards,
Petya Markova.
(UI5 WC Developer)
