### ISSUE TITLE
[Playground]: Cannot run Playground locally on Windows

### ISSUE THREAD

**Issue by dimovpetar** [SAP/ui5-webcomponents#8011]
### Bug Description

When I try to start the Playground locally, I get the following error:
`[Error: ENOENT: no such file or directory, open 'C:\xxx\ui5-webcomponents\packages\base\dist\api.json']`

### Steps to Reproduce

1. execute `yarn storybook` in `packages/playground`

### Priority

Medium

### UI5 Web Components Version

main branch

### Browser

Chrome

### Operating System

Windows 11

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by petyabegovska** [comment]
Hi  @dimovpetar,

Try `yarn start:playground` inside root folder. 

Best regards,
Petya
