### ISSUE TITLE
[Menu]: rootNode.getElementById is not a function

### ISSUE THREAD

**Issue by rvsia** [SAP/ui5-webcomponents#8017]
### Bug Description

When opening a menu that disappears the component fails:

We use menus in table that can be filtered:

1. users filter table > debounce function (200ms) is activated
2. clicks on menu item 
3. debounced function is finished > menu item is filtered out and the application crashes

### Affected Component

Menu, MenuItem

### Expected Behaviour

No fail

### Isolated Example

https://stackblitz.com/edit/stackblitz-starters-9mxyg9?file=src%2FApp.tsx

### Steps to Reproduce

1. Start typing `cc`
2. Right after click on `aaa` or `bbb` button (do it really fast!)
3. Application crashes

### Log Output, Stack Trace or Screenshots

Uncaught TypeError: rootNode.getElementById is not a function
    at Menu.onAfterRendering (Menu.js:131:1)
    at Menu._render (UI5Element.js:577:1)
    at renderImmediately (Render.js:31:1)
    at RenderQueue.process (RenderQueue.js:
49:1)
    at eval (Render.js:51:1)
    
 <img width="557" alt="Snímek obrazovky 2023-12-18 v 13 23 28" src="https://github.com/SAP/ui5-webcomponents/assets/32869456/5ed6983f-9020-448f-9343-5063fb4f9603">

![Kapture 2023-12-18 at 13 20 12](https://github.com/SAP/ui5-webcomponents/assets/32869456/8efac130-3ab7-401c-9b62-aef11dbfb0b4)

### Priority

None

### UI5 Web Components Version

latest

### Browser

Chrome, Edge

### Operating System

MacOS

### Organization

SAP Signavio

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-b could you take a look?

When the menu is detached from the DOM and onAfterRendering runs, rootNode is no longer the document and rootNode.getElementById does not exist, leading to the exception in question.

You can reproduce the issue with the provided sample,
or you can re-create it with pure web components by using a small timeout as shown bellow:

```html
<ui5-button id="buttonA">buttonA</ui5-button>

<ui5-menu id="menuWithoutOpener">
	<ui5-menu-item text="New File" icon="add-document"></ui5-menu-item>
</ui5-menu>
		
<script>
buttonA.addEventListener("click", () => {
		menuWithoutOpener.opener="buttonA";
		menuWithoutOpener.open = !menuWithoutOpener.open;

		setTimeout(() => {
			buttonA.remove();
			menuWithoutOpener.remove();
		}, 100)})
</script>
```

Clicking the button opens the menu,
-> then after a slight delay the opener and the menu are removed from the DOM
   ->  however, the Menu#onAfterRendering has been scheduled and runs
      -> and the code in question is reached, `getElementById` does not exist on the rootNode (as in this case, it's not the document, but the menu custom element itself, which does not have getElementById method)
         -> exception is thrown

**Comment by ilhan007** [comment]
Hello @rvsia we are currently working on the issue, you can track the progress in the following PR https://github.com/SAP/ui5-webcomponents/pull/8021 that will be reviewed (and eventually merged) in the upcoming days.

**Comment by rvsia** [comment]
@ilhan007 thank you for a quick update! 😊
