### ISSUE TITLE
[StepInput]: double clicking add or delete button selects text in other element

### ISSUE THREAD

**Issue by QiuranHu** [SAP/ui5-webcomponents#8026]
### Bug Description

Double clicking add or delete button selects text in other element

To reproduce, go to the demo page for StepInput (https://sap.github.io/ui5-webcomponents/playground/?path=/docs/main-stepinput--docs).

Double click the add button. Check if "show" text is selected.
<img width="1213" alt="Screenshot 2023-12-20 at 14 44 47" src="https://github.com/SAP/ui5-webcomponents/assets/55808904/02751724-fa7a-4ad4-b9f2-be1c7f72a5ca">

Also in edge browser when clicking very fast, only some clicks leads to an increase in value. Some clicks have no effect. Please see the video attached.
https://github.com/SAP/ui5-webcomponents/assets/55808904/e777037a-acc5-4540-899a-a7f8d3ffbef0

### Affected Component

StepInput

### Steps to Reproduce

1.
2.
3.
...

### Priority

Medium

### UI5 Web Components Version

1.17.4

### Browser

Edge

### Organization

SuccessFactors

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by QiuranHu** [comment]
Hi @hinzzx ,
Thanks for replying!
I checked ui5 and other component library that provides similar functionality (buttons for increment/decrement) and they do not have this issue. Please see [ui5](https://sapui5.hana.ondemand.com/sdk/#/entity/sap.m.StepInput/sample/sap.m.sample.StepInput), [material ui](https://mui.com/base-ui/react-number-input/) and [antd](https://ant.design/components/input-number).

 For this component, user might click the button multiple times in a short time frame. Double clicking the increment button should not select texts, because it hurts user experience. Also in edge, when you double click it, there will be a popup shown and further clicks will be blocked for a while.
![Screenshot 2024-03-06 at 11 28 48](https://github.com/SAP/ui5-webcomponents/assets/55808904/ac79296d-5b7c-4a1a-9245-7cc8008fefc2)

So I think we can try add a preventDefault when handling click event, like in this issue(https://github.com/SAP/ui5-webcomponents/issues/7236).

Qiuran Hu

**Comment by hinzzx** [comment]
Hi @QiuranHu,

Thank you for the input! In that case I will investigate it further, and am re-opening the incident.

BR,
Stoyan
