### ISSUE TITLE
[ui5-li]: remove _level property

### ISSUE THREAD

**Issue by pskelin** [SAP/ui5-webcomponents#8047]
### Bug Description

The ListItem class has a `_level` property that was introduced for private usage from the SideNavigationItemPopoverContent
Initial implementation https://github.com/SAP/ui5-webcomponents/pull/5877

The usage was later removed, but the property remained with the following change:
https://github.com/SAP/ui5-webcomponents/pull/6045

It seems safe to remove the property in the ListItem as it was introduced as private and has no other usages in the project.

### Affected Component

ui5-li

### UI5 Web Components Version

main

**Comment by NHristov-sap** [comment]
Hello @SAP/ui5-webcomponents-topic-p, 

please take a look of this request/improvement.

Best Regards,
Nikolay Hristov
