### ISSUE TITLE
[Tree]: invalid level and mode of child items dynamically added to items with level 2 or higher

### ISSUE THREAD

**Issue by holgerrath** [SAP/ui5-webcomponents#8048]
### Bug Description

When tree items are dynamically added to existing items with level 2 or higher using `item-toggle` event of the `Tree` component, the new items are missing the `level` and `_mode` attribute. 
So they end up being rendered as first items with no indentation and no mode (if  `mode` property is set on the `Tree` component). 
Toggling the first level parent item of the new items re-renders them with correct indentation and mode.

### Affected Component

Tree

### Expected Behaviour

When tree items are dynamically added to existing items with level 2 or higher they should be rendered with correct level indentation and correct mode as it is the case for dynamically added items to existing first level items. 

### Isolated Example

https://codesandbox.io/p/sandbox/ui5-webcomponents-forked-lg9k77

### Steps to Reproduce

1. open [code sandbox](https://codesandbox.io/p/sandbox/ui5-webcomponents-forked-lg9k77) based on [Dynamic Content](https://sap.github.io/ui5-webcomponents/playground/?path=/story/main-tree--dynamic-content) `Tree` playground
2. expand first level tree item with text `Has one children with dynamic children`
3. expand second level child item with text `Has children, but not yet loaded` to dynamically add its third level child item
4. the new added third level child is rendered as root item and is not showing the radio button for `SingleSelectBegin` mode as set on the parent `Tree` component
5. toggle expand state of the first level item with text `Has one children with dynamic children`
6. the dynamically added third level item is now rendered with correct indentation and mode
...

### Priority

Medium

### UI5 Web Components Version

v1.17.4

### Browser

Chrome

### Operating System

Mac

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by NHristov-sap** [comment]
Hello @ui5-webcomponents-topic-p,

The issue is reproducible, please take a look on it.

Best Regards,
Nikolay Hristov
