### ISSUE TITLE
[MultiInput]: set several tokens at once

### ISSUE THREAD

**Issue by arhigod** [SAP/ui5-webcomponents#8049]
### Bug Description

You can check the example https://codesandbox.io/p/sandbox/multiinput-c8cqq4
When I set several tokens at once, i see 
![image](https://github.com/SAP/ui5-webcomponents/assets/19529418/ee77e887-f328-466a-ba89-af1f9002e6d4)
Despite the fact that these tokens may fit perfectly into the Input field. 

Also, if I put focus on this input (or after re-render), the tokens will successfully expand and the display will become normal.
![image](https://github.com/SAP/ui5-webcomponents/assets/19529418/4c483017-7761-4ac1-a06a-865784430086)

PS. Looks like this is not fully fixed bug https://github.com/SAP/ui5-webcomponents/issues/6964

### Isolated Example

https://codesandbox.io/p/sandbox/multiinput-c8cqq4

### UI5 Web Components Version

1.19.0

### Browser

Chrome

**Comment by petyabegovska** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

Can you check? The problem is reproducible in the provided sandbox sample.

Best regards,
Petya
