### ISSUE TITLE
[ui5-table]: Table mode Scroll does not work after None mode is set once

### ISSUE THREAD

**Issue by eliatso** [SAP/ui5-webcomponents#8052]
### Bug Description

Hello,

I am reporting a bug regarding the Table `Scroll` mode.

We are setting the table mode to `NONE` if no load more is needed in the table. But, if it is, the table mode is set to `SCROLL`.
Basically, if the Table is initialized with `SCROLL` mode, the scrolling is working fine but once we set it to `NONE` then to `SCROLL` again, it will stop working.
It seems like the load more event is not detected. However, it works well with the Button mode (when we click on it, the load more is called).

Thanks in advance.

### Affected Component

Table

### Expected Behaviour

At initialization Table mode is `SCROLL` -> Scrolling works
Use filters on table so that Table mode is set to `NONE` -> No scrolling
Delete the filters and set Table mode to `SCROLL` again -> Scrolling works again

### Steps to Reproduce

1. Display a Table containing many items and some filters for the table -> Table mode set to `SCROLL` and scrolling is working
2. Filter on some category so that the table contains only a very few items -> set Table mode to `NONE` so no scrolling
3. Delete the filters, so all the table rows are displaying again -> Table mode set to `SCROLL` again but scrolling does not work anymore

### Priority

Medium

### UI5 Web Components Version

1.18.0

### Browser

Chrome, Edge, Firefox

### Declaration

- [x] I’m not disclosing any internal or sensitive information.

**Comment by NHristov-sap** [comment]
Hi @eliatso ,

Please provide live isolated example in [https://codesandbox.io/](https://codesandbox.io/) or similar that demonstrates the issue.

Best Regards,
Nikolay Hristov

**Comment by ilhan007** [comment]
Hi @eliatso you can start with this sample https://codesandbox.io/p/devbox/ui5-webcomponents-starter-k4l955 it already imports the Table (and other components) so you can quickly set up your use-case.

**Comment by eliatso** [comment]
Hello, sorry for the delay
You can have an example here: https://codesandbox.io/p/devbox/patient-dew-7k466y

Basically, I have created a Table with `Scroll` as growing mode by defaut

Once you click on `None` button, growing mode will be set to None
And if `Scroll` button, it will be set to Scroll

Please click on the `None` button first, the Table will be well set to None as growing mode
If you then click on `Scroll`, and try to scroll on the Table, it will not work

The setting with buttons seem to work fine, if you first click on `Scroll`, the scrolling will still work on the Table

Thank you

**Comment by yanaminkova** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

Please have a look at this issue regarding the `ui5-table` component and its `growing` behaviour.
You could find the descriptive steps how to reproduce in the previous comment.
Also, the same behaviour is reproducible in the following storybook example:
https://sap.github.io/ui5-webcomponents/playground/?path=/story/main-table--growing-table-scroll

Thanks and Kind regards,
Yana
