### ISSUE TITLE
[ui5-shellbar]: logo button Horizon style

### ISSUE THREAD

**Issue by JarrettChan** [SAP/ui5-webcomponents#8058]
### Bug Description

Per the Horizon VD wiki ShellBar specs
| Image Button (Logo) | Follows the button behaviour. |
|-|-|

1. The logo button is probably meant to be styled like a tertiary button, but there are a couple issues
    1. The logo button is rendered with square corners in default state.
    2. The logo button hover border and focus border overlap the logo instead of clipping it.
3. The logo is missing additional 0.25rem padding on the left/right to mitigate the Horizon rounded corners.

### Affected Component

ui5-shellbar

### Expected Behaviour

Add the 0 0.25rem padding to ::slotted([slot="logo"]) in Horizon
Address the hover border and focus border clipping
Logo button always have rounded corners in Horizon

### Steps to Reproduce

1. https://sap.github.io/ui5-webcomponents/playground/?path=/story/fiori-shellbar--basic
2. tab into the logo
3. Observe: focus border is overlapping the logo

### Priority

Medium

### UI5 Web Components Version

1.21.0

### Browser

Chrome

### Organization

SuccessFactors

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by petyabegovska** [comment]
Hi @JarrettChan, please don't put internal links as it is an external Github. You can replace the links of the Shell bar wiki page with: "Shellbar Horizon VD wiki" as a text.

Thanks and best regards,
Petya

**Comment by kgogov** [comment]
Hi @JarrettChan,

Thank you for reaching out.
Our team will look into your concerns and get back to you soon.

---

Hi @SAP/ui5-webcomponents-topic-p,

Based on the information provided by the reporter it appears that the logo button needs additional styles alignment.
You can observe the problem in this [sample](https://sap.github.io/ui5-webcomponents/playground/?path=/story/fiori-shellbar--basic).

Could you please take a look?

Best regards,
Konstantin
