### ISSUE TITLE
ui5-li-notification-group expand button

### ISSUE THREAD

**Issue by arifunlu** [SAP/ui5-webcomponents#8059]
### Bug Description

The expand-collapse button also changes its shape when expanded or collapsed.

### Steps to Reproduce

1.
2.
3.
...

### Priority

Medium

### UI5 Web Components Version

1.21.0

### Browser

Chrome

### Operating System

MacOS

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by kgogov** [comment]
Hi @arifunlu,

Thank you for bringing this issue to our attention.
To better assist you, please share a sample code via [CodeSandbox](https://codesandbox.io/) or a similar platform.

Best regards,
Konstantin

**Comment by kgogov** [comment]
Hi @arifunlu,

Thank you for reaching out.
Our team will look into your concern and get back to you soon.

---

Hello @SAP/ui5-webcomponents-topic-rd,

I've noticed a visual difference in the shape of a button when it's expanded/collapsed in a [live example](https://sap.github.io/ui5-webcomponents/playground/?path=/docs/fiori-notification-list-group-item-notification-action--docs) from our documentation. Could you please take a look?

Best regards,
Konstantin

<img width="238" alt="Screenshot 2024-01-09 at 14 41 50" src="https://github.com/SAP/ui5-webcomponents/assets/68374332/0d7852ab-e390-4726-9310-fffebd658da4">
<img width="280" alt="Screenshot 2024-01-09 at 14 42 00" src="https://github.com/SAP/ui5-webcomponents/assets/68374332/635051d8-584d-4010-8a46-4cf3899c0f33">
