### ISSUE TITLE
Allow opening BarcodeScannerDialog with 'open' property like Dialog

### ISSUE THREAD

**Issue by sadie100** [SAP/ui5-webcomponents#8072]
### Is your feature request related to a problem?

Dialog can be opened with 'open' property and is recommended since 0.22.0, as the document says : https://sap.github.io/ui5-webcomponents-react/?path=/docs/modals-popovers-dialog--docs

But BarcodeScannerDialog, which is new feature of 1.24.0, allows only ref to open the dialog.
It's not consistent, and is giving confession to old users.

### Describe the solution you'd like

Please add 'open' property in BarcodeScannerDialog and allows opening/closing the component using that property.

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by kgogov** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

Please, take a look at this feature request.

Best,
Konstantin

**Comment by dobrinyonkov** [comment]
Internal Reference: BGSOFUIPIRIN-6449
