### ISSUE TITLE
wrong `VersionInfo` published

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#8080]
### Bug Description

`VersionInfo` shows `version: "1.21.0-rc.5"` for the latest release (v1.21.0), which leads to wrong css variable transformation. https://unpkg.com/browse/@ui5/webcomponents-base@1.21.0/dist/generated/VersionInfo.js

In UI5 Web Components for React we haven't had any issues yet as all CSS variables are now transformed with this version, but it's probably safer to fix it before something breaks.

### Affected Component

all components using `_ui5` css vars

### Isolated Example

https://codesandbox.io/p/sandbox/ui5-webcomponents-forked-lg872v?file=%2Fsrc%2Findex.js%3A8%2C3

### Steps to Reproduce

1. Go to [unpkg](https://unpkg.com/browse/@ui5/webcomponents-base@1.21.0/dist/generated/VersionInfo.js)
2. See that the version info has the wrong version
3. Go to [codeSandbox](https://codesandbox.io/p/sandbox/ui5-webcomponents-forked-lg872v?file=%2Fsrc%2Findex.js%3A8%2C3)
4. See that the css var has been extended with the wrong version

### Priority

None

### UI5 Web Components Version

1.21.0

### Browser

Chrome, Edge, Firefox, Safari

### Organization

UI5 Web Components for React

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by kgogov** [comment]
Hello @SAP/ui5-webcomponents-topic-core,

Could you please check the described issue with the **VersionInfo** suffix?

Best regards,
Konstantin

**Comment by Lukas742** [comment]
The new release includes the wrong [VersionInfo](https://unpkg.com/browse/@ui5/webcomponents-base@1.22.0/dist/generated/VersionInfo.js) again, which prevents us from using it as now all internal CSS variables are scoped like this: `var(--_ui5-v1-22-0-rc-3_side_navigation_icon_color)`

**Comment by ilhan007** [comment]
Fixed with 1.23.0-rc.2 with the following change:
https://github.com/SAP/ui5-webcomponents/pull/8310


https://unpkg.com/browse/@ui5/webcomponents-base@1.23.0-rc.2/dist/generated/VersionInfo.js
