### ISSUE TITLE
[TextArea]: Large Text Inside Text Area Resizes the Page

### ISSUE THREAD

**Issue by m1trix** [SAP/ui5-webcomponents#8082]
### Bug Description

When a `ui5-textarea` is being used with the `growing` property set to `true` and the text within the component is taller than the textarea itself _(e.g. has a lot of lines)_ the text itself is cut-off by the border of the textarea but the height of the page gets increased as if the text itself is placed outside of the textarea.

### Details
Tested on [https://sap.github.io/ui5-webcomponents-react](https://sap.github.io/ui5-webcomponents-react/?path=/story/inputs-textarea--default-story&args=disabled:!false;growing:!true;growingMaxLines:5;rows:4;showExceededText:!false)

### Setup
* **rows** = 4
* **growing** = true
* **growingMaxLines** = 5
* **value** = _the numbers from 1 to 200, each on a new line_

It looks like that setting `growing=true` breaks the component.

### Affected Component

ui5-textarea

### Expected Behaviour

The page should not resize, similar to how a native `textarea` HTML component does not affect the page it is placed in, when its content's height exceeds its own height.

### Isolated Example

[Link to Code Sandbox](https://codesandbox.io/p/sandbox/ui5-webcomponents-forked-jdhsd9?file=%2Findex.html%3A11%2C14)

### Steps to Reproduce

1. Have a UI5 TextArea with **rows** = 4, **growing** = true, **growingMaxLines** = 5
2. Input a text that is taller than the page _(e.g. numbers from 1 to 500)_
3. Observe how the page itself gets extended in height.

### Log Output, Stack Trace or Screenshots

<img width="749" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/3427023/c4d04c5b-cbf3-4696-b980-f80b2ffed143">

### Priority

Medium

### UI5 Web Components Version

1.19.0

### Browser

Chrome

### Operating System

MacOS

### Organization

SAP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by kgogov** [comment]
Hello @m1trix,

Thanks for reaching out to us, our team will review your report shortly.

Best,
Konstantin

**Comment by kgogov** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

After reviewing the reported issue with the [ui5-textarea](https://sap.github.io/ui5-webcomponents/playground/?path=/story/main-text-area--basic) component, it seems that in this case, there is a problem with using the `growing` property. Please, refer to this [CodeSandbox](https://codesandbox.io/p/sandbox/ui5-webcomponents-forked-jdhsd9?file=%2Findex.html%3A11%2C14) the author has provided.

Could you take a look?

Best,
Konstantin
