### ISSUE TITLE
[SF][StepInput]: when entering a decimal for 2 times, the decimal is not converted to an integer

### ISSUE THREAD

**Issue by QiuranHu** [SAP/ui5-webcomponents#8086]
### Bug Description

In https://sap.github.io/ui5-webcomponents/playground/?path=/docs/main-stepinput--docs, first enter 1.1, press enter, then 1.1 will be converted to 1.
Then enter 1.2, press enter, 1.2 will not be converted.

### Affected Component

StepInput

### Steps to Reproduce

1.
2.
3.
...

### Log Output, Stack Trace or Screenshots

https://github.com/SAP/ui5-webcomponents/assets/55808904/cde8aa75-dd8a-445f-a40a-d33c01870d82

### Priority

None

### UI5 Web Components Version

1.18.0

### Browser

Edge

### Organization

SuccessFactors

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by kgogov** [comment]
Hello @QiuranHu,

Thanks for addressing this, our team will review your issue shortly.

Best,
Konstantin

**Comment by kgogov** [comment]
Hello @SAP/ui5-webcomponents-topic-b,

Please, take a look at the following issue regarding [ui5-step-input](https://sap.github.io/ui5-webcomponents/playground/?path=/story/main-stepinput--basic) component. For more information refer to the short video attached by the reporter in the description above.

Best,
Konstantin
