### ISSUE TITLE
[ui5-tree]: proxy the private `item-focused` event from the list

### ISSUE THREAD

**Issue by vladitasev** [SAP/ui5-webcomponents#8091]
### Feature Request Description

`ui5-tree` internally uses `ui5-list` (or rather `ui5-tree-list`). `ui5-list` has a private event called `item-focused` that is triggered any time the user navigates the list with the keyboard. This allows components that use the list internally to implement their own keyboard navigation.

However, components that internally use `ui5-tree` (for example a custom input that uses a tree as a suggestion list) cannot do this.

### Proposed Solution

Please put a `@ui5-item-focused=.....` binding on the `ui5-tree-list` in `Tree.hbs` and fire that same private event from `Tree.ts`

### Organization

Ariba

### Priority

Medium

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by kgogov** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

Please, take a look at the following request suggesting enhancements to ui5-tree component.

Best,
Konstantin

**Comment by dobrinyonkov** [comment]
Internal Refernce: BGSOFUIPIRIN-6451
