### ISSUE TITLE
[DateFormat | localization]: 'America/Santiago' timezone cannot select/save '09/03/2023'

### ISSUE THREAD

**Issue by allen138** [SAP/ui5-webcomponents#8101]
### Bug Description

Hi team,
openui5 had an issue within their DateFormatter causing user's to not be able to select certain dates from the date picker for certain timezone. Openui5 has fixed the issue via, [openui5/commit/8ec0e35c75](https://github.com/SAP/openui5/commit/8ec0e35c75a003b23550b74acc0b075aadd8704b) and [openui5/commit/d7acbfd2c](https://github.com/SAP/openui5/commit/d7acbfd2ce2f9f037c9f19589461adeffdd41ab2). So the ask here is to kindly upgrade the dev dependency in [packages/localization/package.json](https://github.com/SAP/ui5-webcomponents/blob/main/packages/localization/package.json#L32) to openui5 latest patch version 1.120.3 so the webcomponent date-picker components can consume this fix.
Thanks,
Allen

### Affected Component

Date Picker/Calendar Components

### Expected Behaviour

User in "America/Santiago' timezone should be able to select '09/03/2023' from the date picker. 

### Steps to Reproduce

1. Force the browsers timezone to be "America/Santiago". (Dev tools > more options "..." > more tools > sensors > override location and update the timezoneId.
2. Open Date Picker and try to select September 3rd 2023. Notice the date changes to the 2nd after selecting the 3rd.
3. Try to manually type the 3rd in the date picker input, and on focus out/blur you will see the value changes to the 2nd.

### Priority

None

### UI5 Web Components Version

main

### Browser

Chrome, Edge, Firefox, Safari

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ilhan007** [comment]
[Change](https://github.com/SAP/ui5-webcomponents/pull/8122) in main is merged and will be released with 1.22 (start of Feb)

**Comment by ilhan007** [comment]
1.14 downport

**Comment by ilhan007** [comment]
[1.14.7](https://github.com/SAP/ui5-webcomponents/releases/tag/v1.14.7) has been released
