### ISSUE TITLE
[Feature Request]: RadioButton display mode

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents#8104]
### Feature Request Description

The request is for adding a property and respective visual design as per the SAP Design spec for "display" mode.
The request is filed on behalf of SAP Brand LoB that would like to use the RadioButton in "display" mode in forms.

### Proposed Solution

Add property similar to the SAPUI5 RadioButton and implement the existing design as specified.

### Organization

SAP Brand

### Additional Context

**Preferred timeline to have the feature - Start/Mid February**

### Priority

Medium

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-rd could take and process, and plan this feature request?

**Comment by olannyv** [comment]
Ongoing discussion to adopt either the 'display mode'  VD spec from SAP Brand side, or the tekst-only approach we have in other technology stacks (UI5)

**Comment by PlutaKatarzyna** [comment]
Hi @olannyv , are there any plans in this topic already? Checkbox component already got "displayOnly" mode. Is there going to be the same mode for radio buttons?

**Comment by olannyv** [comment]
Hi PlutaKatarzyna 
It depends on if/when the accountable designers will be able to provide specifications.
Then I can plan it for implementation

**Comment by petyabegovska** [comment]
Hi @PlutaKatarzyna,

The current SAP design approach for Radio Button is text-only. Please open a feature request to SAP Design System (E1 Jira item), describing your use case, so that they can evaluate it and provide a display mode icon design.

Best regards,
Petya

**Comment by PlutaKatarzyna** [comment]
Hi @petyabegovska @ilhan007 ,
We created workaround for radio button display only state in UDEX library. As UI5 does not have a plan for implementing it, let just close this ticket.

Best Regards
Kate

**Comment by ilhan007** [comment]
As suggested, closing the issue - there is udex-radio-button component created.
