### ISSUE TITLE
Input suggestions with custom layout

### ISSUE THREAD

**Issue by vasicvuk** [SAP/ui5-webcomponents#8113]
### **Issue Description**

I am not sure if the feature exists,  but I could not find it in the documentation, I wanted to show input suggestions with some images and additional textual info, for example, the image of the user, first name last name, and email. Is something like this possible?

I see that `ui5-suggestion-item` has some optional fields such as `additionalText` and `image` but i was wondering it the custom item can be created.

### **Issue Type**

- [ ] Documentation is unclear
- [ ] Documentation is incorrect
- [X] Documentation is missing
- [ ] Other

**Comment by nnaydenow** [comment]
Hi @vasicvuk,

Currently ui5-input doesn't provide option to display custom items. If I correctly understand you, you want to achieve something similar:
![image](https://github.com/SAP/ui5-webcomponents/assets/31909318/25a3743e-21b3-4f28-a45f-a26272d40091)

Following example is achieved by using image, text and description property of ui-suggestion-item.

Does this fit for your case?

Regards,
Nayden

**Comment by vasicvuk** [comment]
Hi @nnaydenow, The issue I am having is that "text" property is really what will be the value of the input on selection, this in most cases is some number such as customer ID, and in displaying this is something that should not appear first, so that is why i wanted a custom view in the first place.

Maybe there is someother option to achieve different value (not the text one)?

**Comment by niyap** [comment]
Hello @SAP/ui5-webcomponents-topic-rl , 

Please, take a look of this feature request.

Thank you in advance!

Kind Regards,
Niya

**Comment by vasicvuk** [comment]
Also maybe splitting display value and value could resolve this?

**Comment by hristop** [comment]
Hi @vasicvuk ,

We already have such feature requirements for two separate feature requests:
* One is providing key-value functionality in the inputs: #7777 
* Second one is providing the possibility to create custom list item: #5128 

The first - which is closer to your last comment regarding the value and the displayed value we may be able to start working on soon depending on team capacity and priorities. 

The second one, which I believe is closer to your use case, will probably be worked on after the implementation of the popover API (we are currently waiting for FF to start supporting it officially). 

I will close this issue as the feature requests already exist, but if you feel that your need something different - please post a comment with explanation and we will reopen it. 

Best Regards,
Hristo

**Comment by vasicvuk** [comment]
Great :) Thanks for detailed response. Anyway FF started supporting popover api:

https://caniuse.com/?search=popover
