### ISSUE TITLE
Release another version to NPM

### ISSUE THREAD

**Issue by brodo** [SAP/ui5-webcomponents#812]
I would like to get the bugfixes which have been implemented in the last three months without needing to build this repo myself. A 1.0.0-rc.3 would be much appreciated.

**Comment by ilhan007** [comment]
We will do the release by end of this week, most probably on Thursday, 03 Oct

**Comment by brodo** [comment]
Awesome! Looking forward to it!

**Comment by ilhan007** [comment]
Just released!
