### ISSUE TITLE
Prevent JS exception in Toast's global event handler in case of missing `key`

### ISSUE THREAD

**Issue by tzimmermann** [SAP/ui5-webcomponents#8125]
Since we've upgraded our app from `@ui5/webcomponents@1.16.0` to `1.20.0`, we've been getting some errors logged in our sentry that look like this:
![image](https://github.com/SAP/ui5-webcomponents/assets/1227637/64246ed6-b1f5-4060-85ff-f9256a0a72cc)

We are not able to reproduce it yet, but the current assumption is that some browser quirk ([like this one](https://bugs.chromium.org/p/chromium/issues/detail?id=763559)) or some auto-fill feature generates KeyboardEvents with `undefined` as `key` sometimes.

Thus, it would be nice to add some optional chaining for the `key` field here, in order to prevent logging noise.
Especially since this is a global event handler (we are not even using any Toast component in our app) that gets called a lot.
https://github.com/SAP/ui5-webcomponents/blob/c99d0ecb10c903fb19fd06b3d6de2b5f80b4650e/packages/main/src/Toast.ts#L25

**Comment by niyap** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

Please check the handleGlobalKeydown method of ui5-toast web component. On android mobile device, there are cases when e.key returns undefined so e.key.toLowerCase() throws an error.

Could you please and enhance the condition?

Thank you in advance!

Kind Regards,
Niya
