### ISSUE TITLE
[ui5-side-navigation-item]: wrong text placement

### ISSUE THREAD

**Issue by nnaydenow** [SAP/ui5-webcomponents#8131]
### Bug Description

When first level item is selected and it is without icon the text is placed on the border of the element.

![image](https://github.com/SAP/ui5-webcomponents/assets/31909318/6a103a06-a840-4ce4-9722-99f07c9c427c)

### Steps to Reproduce

1.
2.
3.
...

### Priority

None

### UI5 Web Components Version

1.21.2

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by s-todorova** [comment]
Hi colleagues,

The issue has been fixed with PR #8154.

Best regards,
Siyana
