### ISSUE TITLE
[ui5-table]: load-more event not being fired

### ISSUE THREAD

**Issue by egor-sap** [SAP/ui5-webcomponents#8160]
### Bug Description

When using the ui5-table with "growing=Scroll", the "load-more" event is not fired unless there is a scroll event. 

### Affected Component

ui5-table

### Expected Behaviour

Expect the "load-more" event to be fired if the bottom of the table is in the viewport, even if there is no scroll bar.

Currently if the table has a fixed height, but not enough items to cause an overflow, there will be no scroll bar, and thus no way to trigger the "load-more" event.

### Isolated Example

https://codesandbox.io/p/sandbox/ui5-webcomponents-forked-ycc3sr?file=%2Findex.html%3A29%2C48

### Steps to Reproduce

1. Go to https://codesandbox.io/p/sandbox/ui5-webcomponents-forked-ycc3sr?file=%2Findex.html%3A29%2C48
2. Open the console and see there is no log for "load-more fired" and there is no scrollbar so the event can't be triggered

### Priority

Medium

### UI5 Web Components Version

1.19.0

### Browser

Chrome

### Organization

SuccessFactors

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by LidiyaGeorgieva** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,
I am forwarding this issue to you, because there is a question regarding Table component.
Regards,
Lidiya

**Comment by ilhan007** [comment]
@SAP/ui5-webcomponents-topic-rl also internal thread opened

**Comment by ivoplashkov** [comment]
Hello,

I've tried to reproduce the issue in the codesandbox as described by the reporter, but I was not able to. I've also reached to several colleagues on different OS and the event seems to be fired.
Could you please provide more information on Browser / OS combination and in what cases this event is not fired.

Thank you in advance!
Regards,
Ivaylo

**Comment by niyap** [comment]
Hello @egor-sap,

As discussed with Martin in the chat, we prevented the load-more event on initial rendering.

Kind Regards,
Niya
