### ISSUE TITLE
[ui5-toolbar-ITEMS]: events are not dispatched correctly with a prefix 

### ISSUE THREAD

**Issue by MapTo0** [SAP/ui5-webcomponents#8164]
### Bug Description

Hello Colleagues,

The events of all toolbar items are not dispatched correctly. Native events like Click work fine due to same mapping in the native word but custom events are not working the right way.

I see that there is already a test in the ToolbarSelect for that which is commented?
Please uncomment and fix the issue: https://github.com/SAP/ui5-webcomponents/blob/main/packages/main/test/specs/ToolbarSelect.spec.js#L35-L51

Since this is a blocker for our delivery I would consider that as a high / very high incident.
If you need more information regarding our use case feel free to contact me or Hristo Petrov.

### Affected Component

all ui5 toolbar items and elements extending them

### Expected Behaviour

ui5-change is fired

### Steps to Reproduce

https://github.com/SAP/ui5-webcomponents/blob/main/packages/main/test/specs/ToolbarSelect.spec.js#L35-L51

### Priority

None

### UI5 Web Components Version

latest

### Browser

Chrome, Edge, Firefox, Safari

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ilhan007** [comment]
@SAP/ui5-webcomponents-topic-p could you have a look and let us know if you need support from our side.
