### ISSUE TITLE
Document how to configure message bundle assets and how to internationalize an app

### ISSUE THREAD

**Issue by brodo** [SAP/ui5-webcomponents#817]
**Describe the documentation issue**

- [ ] Documentation is unclear
- [ ] Documentation is incorrect
- [x] Documentation is missing
- [ ] Other

**Description of the issue**
When using UI5 web components, I get warnings in the console:
```
Message bundle assets are not configured. Falling back to english texts.  You need to import @ui5/webcomponents/dist/json-imports/i18n.js with a build tool that supports JSON imports.
```

I imported `@ui5/webcomponents/dist/json-imports/i18n.js` using `rollup-plugin-json`.
Now I also get the message:

```
Inefficient bundling detected: consider bundling i18n imports as URLs instead of inlining them.
See rollup-plugin-url or webpack file-loader for more information.
Suggested pattern: "assets\/.*\.json"
```
I know this all has to do with internationalization. There should be documentation about how to configure message bundle assets and how to internationalize an app.

**Comment by ilhan007** [comment]
Hello @brodo 

Actually we have a lot of additional documentation  in the `ui5-webcomponents/docs` folder.

Regarding the i18n, about the warnings and how to configure i18n assets efficiently you read this part:
https://github.com/SAP/ui5-webcomponents/blob/master/docs/PublicModuleImports.md#3-internationalization

I hope this helps.

Best,
ilhan

**Comment by brodo** [comment]
Oh, sorry I did not see that. Thanks for the info!

**Comment by LuisValgoi** [comment]
Does anyone has any update on this?
I'm receiving this same error.

**Comment by ilhan007** [comment]
Hello @LuisValgoi did you try to import what is suggested in the warning.

**Comment by LuisValgoi** [comment]
@ilhan007 it redirects to a not found page.
https://github.com/SAP/ui5-webcomponents/blob/master/docs/PublicModuleImports.md#3-internationalization

**Comment by ilhan007** [comment]
Now the documentations can be read here:
https://sap.github.io/ui5-webcomponents/playground/docs/public-module-imports/#internationalization

**Comment by LuisValgoi** [comment]
@ilhan007 

like this?
![image](https://user-images.githubusercontent.com/8363610/74262986-b3b94100-4cdc-11ea-8f4d-65ce7e06fae7.png)

check the console for this case:
![image](https://user-images.githubusercontent.com/8363610/74263007-c03d9980-4cdc-11ea-9d23-9f8816bdb910.png)
