### ISSUE TITLE
[Feature Request]:Year/Month only selectors in DateRangePicker

### ISSUE THREAD

**Issue by subint7** [SAP/ui5-webcomponents#8177]
### Feature Request Description

In DatePicker, the calendar opened can be controlled by setting the `formatPattern`, for example if the pattern is set as `yyyy`, the calendar opened will only have `Years`. But in the DateRangePicker, this doesn't seems to happen. 
<img width="333" alt="Screenshot 2024-01-25 at 2 38 30 PM" src="https://github.com/SAP/ui5-webcomponents/assets/156891588/0cb67263-a37e-474a-abc8-7d87c9ea7e4e">
<img width="325" alt="Screenshot 2024-01-25 at 2 38 41 PM" src="https://github.com/SAP/ui5-webcomponents/assets/156891588/1f56a88f-57f2-4581-89ef-da62f5be64c0">

### Proposed Solution

DateRangePicker calendar should also be dependant on the `formatPattern` set.

### Priority

None

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by petyabegovska** [comment]
Hello @SAP/ui5-webcomponents-topic-b, @DMihaylova 

Please have a look at this feature request.

Best regards,
Petya
