### ISSUE TITLE
[SF_ACC][ui5-dialog]: CNTL + Arrow keys not working for draggable dialog

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents#8190]
### Bug Description

CNTL + Arrow keys are not working for draggable dialog to move the dialog.
Where is it documented for how to resize and move dialogs using the keyboard? We need to tell the customer.

### Expected Behaviour

CNTL + Arrow key should be working for draggable dialog to move the dialog.
You can ui5 page https://ui5.sap.com/#/entity/sap.m.Dialog/sample/sap.m.sample.Dialog, it works.

### Steps to Reproduce

1. open page https://sap.github.io/ui5-webcomponents/playground/?path=/story/main-dialog--draggable-and-resizable
2. Open the dialog
3. When the dialog is opened, the focus is on the dialog title bar by default. Use CNTL+arrow keys and can't move the dialog.

### Priority

Medium

### UI5 Web Components Version

1.21.x

### Browser

Chrome, Edge, Firefox, Safari

### Operating System

IOS

### Organization

SAP SuccessFactors

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by petyabegovska** [comment]
Hi @GongRichard,

When the focus is on the dialog title, you should use the [Arrow keys] to move the dialog:

- Left arrow key moves 1 rem to the left.
- Right arrow key moves dialog 1rem to the right. 
- Up arrow key moves dialog 1rem to the top.
- Down arrow key moves dialog 1rem to the bottom.

I will send you the Keyboard specification in Microsoft Teams.

Best regards,
Petya

**Comment by petyabegovska** [comment]
Follow up discussion will be triggered how we provide end user documentation similar to SAPUI5: https://help.sap.com/docs/SAPUI5/bc5a64aac808463baa95b4230f221716/144d377d68784689a9b21565dfa14065.html?version=1.96

**Comment by s-todorova** [comment]
Hi @GongRichard,

With [PR#8355](https://github.com/SAP/ui5-webcomponents/pull/8355), the keyboard navigation for Dialog component is now properly documented.

Best regards,
Siyana
