### ISSUE TITLE
Table: TableColumn with popin is not selected

### ISSUE THREAD

**Issue by mrCherry97** [SAP/ui5-webcomponents#8203]
### Describe the bug

As a user, I want to make one column a popin, and after selecting the row I want to have this popin also marked as selected.

### Reproduction steps

1. Create Table
2. Add `TableColumn` with popin prop 
3. Add `TableRow` and provide selected prop
4. Check UI

### Expected Behaviour

All row is selected like this (my requirement from UXes):
![image](https://github.com/SAP/ui5-webcomponents-react/assets/46759954/1d905a65-a6ea-45f2-895c-f84af31e31dc)

### Screenshots or Videos
Table looks like this:
![image](https://github.com/SAP/ui5-webcomponents-react/assets/46759954/b50f1c77-58ed-458c-9a20-53ad00c9bbca)

and after clicking on one of the row column layout is opened, but `TableColumn` with popin is not selected.
![image](https://github.com/SAP/ui5-webcomponents-react/assets/46759954/3393ae41-ad55-428e-ab2b-aad333f5b99e)

### UI5 Web Components for React Version

"@ui5/webcomponents-react": "~1.23.0",

### UI5 Web Components Version

"@ui5/webcomponents": "^1.20.0",

### Browser

Chrome

### Operating System

MacOS

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-rl it's about the ui5-table, and the fact that the popped in content does not have the propert selection background when the table row (that it's associated to) is selected

**Comment by ilhan007** [comment]
Possible steps:
1. Open the  pop-in  storybook sample
https://sap.github.io/ui5-webcomponents/playground/?path=/story/main-table--popin-display-inline

2. Choose Multiple selection mode

3. Shrink a bit (if needed) to ensure you have pop-in column

4. Select the first row

5. Observe the result (the selection is not covering the pop-in content)
<img width="918" alt="Screenshot 2024-01-30 at 16 20 04" src="https://github.com/SAP/ui5-webcomponents/assets/15702139/37de8c70-f906-47da-8b28-c1232943f34b">

**Comment by mrCherry97** [comment]
hi, @ilhan007 @Lukas742 
have you got any timebox planned for fixing this?

Best regards,
Mateusz

**Comment by ilhan007** [comment]
Hi @mrCherry97 the issue has been dispatched to the development team. Usually bugs don't have clear milestone, the team work on the open bugs given the priority, taking into account thing like - is it functional, is it only visual, is it security, is it accessibility issue, information of the impact/urgency within the issue description.
Please elaborate on the importance of the issue, so that the team can prioritize it.
Having said this, I will let @hristop to answer your question as the current owner.

**Comment by mrCherry97** [comment]
Thanks for your fast response @ilhan007,
for us, this topic is crucial, because we are planning to merge our changes around next week or 2 weeks, and it will be lovely if this will be fixed because it's very problematic and misleading for the user with a current view:
![image](https://github.com/SAP/ui5-webcomponents/assets/46759954/1fd54397-41a8-4d8a-ba69-d2791dcb6491)
for example here, the `Labels` column looks like it's not connected to selected resource, so from our perspective, this bug has a big impact on our app. If it's possible I need a +- timebox, because I need to plan if we want to continue working on this topic, or if we need to wait more time to release this (it would be lovely if we don't need to postpone the release of this feature).
Thanks!

**Comment by hristop** [comment]
Hi @mrCherry97 ,

We will try to find some time to look into the issue next week, but as it may need some sort of restructuring / refactoring of the table rows, I can't guarantee that this will be a quick fix. 

Best Regards,
Hristo

**Comment by mrCherry97** [comment]
Hi @hristop 

One more thing to this issue, `hover` also should work on whole row, because currently it looks like this and this is very misleading for the user:
![image](https://github.com/SAP/ui5-webcomponents/assets/46759954/7a989e0a-a936-42ac-a64a-f9efd6611dbc)

Thanks in advance!
Best regards
Mateusz

**Comment by MapTo0** [comment]
Dear reporter,

Merging: https://github.com/SAP/ui5-webcomponents/pull/8372

Will fix the highlighting after selection issue.
The rest will be part of the refactoring of the table component.

Regards!
Martin

**Comment by mrCherry97** [comment]
Hi @MapTo0 
when can we expect a release of this fix, and when you plan to refactor Table component?

Regards!
Mateusz

**Comment by simlin** [comment]
The new table is available since last week in an first experimental preview. The selection and also hover covers both the row and its popin there, see also https://sap.github.io/ui5-webcomponents/nightly/components/TableSelection/#basic-sample (enabling popins can be done via the property _overflow-mode="Popin"_).
