### ISSUE TITLE
[Feature Request]: Progress Indicator - point size adjustments

### ISSUE THREAD

**Issue by PlutaKatarzyna** [SAP/ui5-webcomponents#8213]
### UDEx components library 

We need possibility to overwrite ui5-progress-indicator "point" size (the dot at the beginning and the end of progress bar). 

Currently there is hardcoded value `0.25rem`, but what we need is `0.375rem`. In the following selector `.ui5-progress-indicator-remaining-bar::before, .ui5-progress-indicator-remaining-bar::after` there is hardcoded value of width and height. 

<img width="1696" alt="Screenshot 2024-01-31 at 12 10 38" src="https://github.com/SAP/ui5-webcomponents/assets/158282803/06247869-2c11-4d29-bd26-ae7736b2feea">

### Proposed Solution

Include possibility to overwrite values of point size by adding ui5 variable.

### Organization

SAP

### Priority

Medium

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by petyabegovska** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

Please have a look at this feature request.

Best regards,
Petya

**Comment by jdichev** [comment]
Hello @PlutaKatarzyna,

The value of 0.25rem is as per Horizon design specification. We'll raise query with our design colleagues and be back to you.

Best regards,
Jordan

**Comment by PlutaKatarzyna** [comment]
Hello @jdichev 
Thank you. With our designs we increase the bar height, which automatically require bigger dot size. Link for the designs if you need it: https://www.figma.com/file/OFEfvhyXJvYJ6MQZ30699m/v2.0-Brand-Digital-Design-System?type=design&node-id=5874%3A7&mode=design&t=6eiov43ejqJWF7Ay-1

**Comment by jdichev** [comment]
Hello @PlutaKatarzyna,
Thanks. We'll set aside some time to work on this in coming takt. Internal reference BGSOFUIPIRIN-6454.

**Comment by plamenivanov91** [comment]
Hello @PlutaKatarzyna ,

I merged [this](https://github.com/SAP/ui5-webcomponents/pull/8276) pull request where a new CSS part is introduced.

It's show how to achieve your target design in the commit message.

Regards,
Plamen Ivanov
