### ISSUE TITLE
[Button] Wrong font family in 1.0.0-rc.3

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents#822]
**Describe the bug**
Button has the wrong font-family.

**To reproduce**
1. Render a `ui5-button` from `v1.0.0-rc.3`.

**Isolated example**
Please provide an isolated example if possibile, by forking [CodeSandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html)
Code Sandbox not working with rc.3

**Expected behavior**
In `v1.0.0-rc.2` the font-family of the button was set in the `sapMBtn` class to `var(--sapUiFontFamily)`.
In `v1.0.0-rc.3`, the style class `ui5-button-root` is not setting any font-family information so the user agent stylesheet with `font: 400px 11 system-ui` is applied.

**Screenshots**
rc2:
![image](https://user-images.githubusercontent.com/8775211/66371757-7cd8c480-e9a4-11e9-979d-7ba7e4bcb9ba.png)

rc3:
![image](https://user-images.githubusercontent.com/8775211/66371780-9712a280-e9a4-11e9-8d9c-7975c290d59c.png)

**Context**
- UI5 Web Components version: 1.0.0-rc.3
- OS/Platform: macOS Mojave
- Browser *(if relevant)*: Chrome 77

**Affected components** *(if known)*
Button

**Comment by ilhan007** [comment]
Hello @MarcusNotheis 

I already sent you a mail about what we plan. Regarding this issue, we will address it this way:
Seems to work fine.

```css
.ui5-button-root {
   font: inherit;
}
```

**Comment by MarcusNotheis** [comment]
Hi @ilhan007,
sounds good! For the Web Components React we have applied a fix in the meantime: https://github.com/SAP/ui5-webcomponents-react/blob/chore/update-web-components/packages/main/src/webComponents/Button/index.tsx#L19-L25

Best regards,
Marcus
