### ISSUE TITLE
Playground is still showing rc.2 docs

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents#823]
**Describe the documentation issue**

- [ ] Documentation is unclear
- [x] Documentation is incorrect
- [ ] Documentation is missing
- [ ] Other

**Description of the issue**
The playground is still showing the rc.2 documentation.
According to the changelog, the multi combo box should now have an attribute `allow-custom-values` but it still shows `validate-input`
```md
ui5-multi-combobox: property validate-input is removed, use the property allow-custom-values, note built in validation is enabled by default.
```

**Comment by fifoosid** [comment]
Closing the issue as it has been resolved :smile:
