### ISSUE TITLE
SideNavigation: overflow behavior doesn't work

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#8242]
### Bug Description

The overflow behavior doesn't work, it just shows an empty popover. Furthermore the `overflow` icon is not imported by the component, so it just shows an empty item.

### Affected Component

SideNavigation

### Isolated Example

https://stackblitz.com/edit/github-permf7-o6sev6?file=index.html

### Steps to Reproduce

1. Go to [StackBlitz](https://stackblitz.com/edit/github-permf7-o6sev6?file=index.html)
2. Click on the empty item
3. See an empty popover

### Log Output, Stack Trace or Screenshots

<img width="315" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/9749730/e4979f93-4465-48fa-9cc1-9a5964505bf2">

### Priority

None

### UI5 Web Components Version

1.22.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by yanaminkova** [comment]
Hello @SAP/ui5-webcomponents-topic-rd,

Could you please have a look at this issue about the overflow functionality of the `ui5-side-navigation` component.

Thanks and Regards,
Yana

**Comment by dimovpetar** [comment]
Issue with missing overflow icon is resolved by https://github.com/SAP/ui5-webcomponents/pull/8736 in branches 2.0 and 1.24.
I have updated the StackBlitz sample https://stackblitz.com/edit/github-permf7-xhnkwr?file=package-lock.json,package.json,index.html.

**Comment by dimovpetar** [comment]
Hello @Lukas742 ,

Issue is fixed with #8948 in branch 2.0 and will be downported to 1.24 with https://github.com/SAP/ui5-webcomponents/pull/8954.

Best regards,
Petar
