### ISSUE TITLE
[ui5-card-header]: description doesn't truncate

### ISSUE THREAD

**Issue by nnaydenow** [SAP/ui5-webcomponents#8245]
### Bug Description

Hello colleagues,

If description is very long single word, it doesn't truncate.

### Affected Component

ui5-card-header

### Expected Behaviour

Expected behaviour is to truncate or to wrap somehow.

### Isolated Example

https://stackblitz.com/edit/js-acnae1?file=index.js,index.html

### UI5 Web Components Version

1.22.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by nnaydenow** [comment]
Hello @SAP/ui5-webcomponents-topic-rd,

Could you please check this issue?

**Comment by s-todorova** [comment]
Hi @nnaydenow ,

The issue has been fixed with https://github.com/SAP/ui5-webcomponents/pull/8247.

Best regards,
Siyana
