### ISSUE TITLE
[combobox]: Options are empty after typing

### ISSUE THREAD

**Issue by rvsia** [SAP/ui5-webcomponents#8267]
### Describe the bug

Combobox has this visual bug that options are empty after typing and expanding again

### Isolated Example

https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-combobox--docs

### Reproduction steps

1. Select something in combobox
2. Type and confirm
3. Expand combobox

### Expected Behaviour

All options are visible

### Screenshots or Videos

![Kapture 2024-02-09 at 15 52 54](https://github.com/SAP/ui5-webcomponents-react/assets/32869456/7f5b6cb5-1bf2-434f-b2ff-fa0230b05cb4)

### UI5 Web Components for React Version

latest

### UI5 Web Components Version

latest

### Browser

Edge

### Operating System

MacOS

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by nnaydenow** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

the issue is also reproducible in webcomponents project samples: https://sap.github.io/ui5-webcomponents/nightly/playground/?path=/docs/main-combo-box--combo-box-overview

Could you please check the issue?
