### ISSUE TITLE
Link to blog on landing page is broken: 404

### ISSUE THREAD

**Issue by maltehain** [SAP/ui5-webcomponents#8270]
It seems like [https:/blogs.sap.com](https://blogs.sap.com/) was integrated into https://community.sap.com (blogs.sap.com gets redirected to https://community.sap.com/t5/all-sap-community-blogs/ct-p/all-blogs). As a result of it the referenced blog link is not working anymore.

Steps to reproduce:
1. Open landing page https://sap.github.io/ui5-webcomponents/
2. Click on "Blog" button in the navigation bar
3. Receiving an 404 error
![image](https://github.com/SAP/ui5-webcomponents/assets/32959219/5d569c6c-ef2d-4d93-a348-c54c6c5b8e8f)

https://github.com/SAP/ui5-webcomponents/blob/6faf061266d7be95dee42be0e0db60331c423f88/packages/playground/docs/landing-page.html#L34

**Comment by nikoletavnv** [comment]
Hi @maltehain,
Thanks for noting that. I am assigning the issue to the corresponding team.
Best regards, 
Nikoleta

**Comment by nikoletavnv** [comment]
Hello @SAP/ui5-webcomponents-core, 
I am forwarding this issue to you, because it is related to the public blog url. 
Best regards, 
Nikoleta

**Comment by petyabegovska** [comment]
Thank you @maltehain for reporting this!
