### ISSUE TITLE
[ui5-side-navigation]: unwanted scrollbar appears

### ISSUE THREAD

**Issue by LidiyaGeorgieva** [SAP/ui5-webcomponents#8273]
### Bug Description

![image](https://github.com/SAP/ui5-webcomponents/assets/7242508/69b8ee38-388e-4b67-841a-ddc3abf4cdd6)

### Affected Component

ui5-side-navigation

### Expected Behaviour

Not to have scrollbar

### Isolated Example

https://sap.github.io/ui5-webcomponents/nightly/playground/fiori/pages/SideNavigationOnly/?sap-ui-theme=sap_horizon

### Steps to Reproduce

1. collapse the Side Navigation
2. click the "..." button
3. hover on last "Locations" item
4. popover opens and it has scrollbar

### Priority

Medium

### UI5 Web Components Version

main

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ivoplashkov** [comment]
Hello colleagues,

As discussed with @LidiyaGeorgieva, I am forwarding the issue to you.

Best regards,
Ivaylo

**Comment by LidiyaGeorgieva** [comment]
It is by design. No changes needed.
