### ISSUE TITLE
[TabContainer]: `TabLayout.Inline` shows `additionalText` twice

### ISSUE THREAD

**Issue by ej612** [SAP/ui5-webcomponents#8274]
Hi there!

### Describe the bug

It seems there's something wrong with the `TabContainer` component:

### Expected Behavior
+ with `TabLayout.Standard`: The `additionalText` is displayed above the `text`
+ with `TabLayout.Inline`: The `additionalText` is wrapped in parentheses and displayed to the right of the `text`

### Actual Behavior
+ with `TabLayout.Standard`: As expected
+ with `TabLayout.Inline`: The `additionalText` is displayed both above and to the right of the `text`

### Reproduction steps

1. Go to [the docs](https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-tabcontainer--docs)
2. In the "Properties" table, set `tabLayout` to `TabLayout.Inline`

### UI5 Web Components for React Version

1.25.1

### UI5 Web Components Version

1.22.0

### Browser

Chrome

**Comment by nikoletavnv** [comment]
Hi @SAP/ui5-webcomponents-topic-rd, 
Can you please check the above issue and tell if the additional text should be displayed duplicate times - above and next to the title in the tab item when layout is TabLayout.Inline? I looked at the documentation and it leaves me with the impression that in case of inline layout the additional text should only be displayed next to the title. 

Best regards, 
Nikoleta
