### ISSUE TITLE
MultiComboBox : Pasting content does not trigger internal state change

### ISSUE THREAD

**Issue by CoderCatA5** [SAP/ui5-webcomponents#8275]
### Bug Description

- Pasting content does not trigger the Filter Feature.
    - If a user triggers the onInput via typing . The items get filtered based on input .
    - However this is not the case when the user pastes the same string or a part of the string
    - eg. If the list of items `["Luck","LuckLuck","Item1","Item2","Object1","Object2"]` and he starts typing in `Luc` , The items `["Luck","LuckLuck"]` are filtered out. This is not consistent while pasting `Luc`.  
- Pasting content does not trigger state change
    - Incase a user adds a feature where he can add an element that does not exist in the list of items. He cannot paste some text and press enter.(My issue)
- Pasting content twice does not paste twice. (because the state has not been changed)

### Affected Component

MultiComboBox

### Expected Behaviour

- Pasting content should update the internal state
- Lets say i paste `Luck` then i paste `Lu` i want `LuckLu` to be displayed in the input ### field.
    - Currently the `Luck` is replaced by `Lu`.
- It should also filter the items accordingly.
- Enter Key press should be registered as an event to implement this 
    - Incase a user adds a feature where he can add an element that does not exist in the list of items. He cannot paste some text and press enter.(My issue)
    - If a user adds an element via paste that does not exist in the options. The he cant press enter and add it as a value . But if he adds a space after it . The Enter Key will fire an onChange input and the item is added . If the space is not added ,the Enter Key does not have a registered event . (Most likely because the internal state is not updated onPaste). 

### Isolated Example

https://stackblitz.com/edit/js-ykkom8?file=index.html

### Steps to Reproduce

1. Vist the StackBlitz at [Link](https://stackblitz.com/edit/js-ykkom8?file=index.html)
2. Have `Luck` in your clipboard
3. Paste it in the MultiComboBox - Notice it does not filter out the items and give an output
4. Paste again - The value `LuckLuck` is not displayed.
5. This behavior is present on [Storybook](https://sap.github.io/ui5-webcomponents/playground/?path=/docs/main-multi-combo-box--multi-combo-box-overview). When `allowCustomValues` is set to `true`

### Log Output, Stack Trace or Screenshots

https://github.com/SAP/ui5-webcomponents/assets/76586285/efa67520-4620-4c94-8289-14f045104d9b

### Priority

High

### UI5 Web Components Version

1.22.1

### Browser

Chrome

### Operating System

Windows

### Organization

SAP Labs India

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ivoplashkov** [comment]
Hello colleagues,

The issue is reproduced as described by the reporter, it can also be reproduced in our test page.
I don' t think this has been implemented yet, as we only have logic for tokenizing the value if pasted from a spreadsheet. I couldn't find a clear interaction guidelines on how exactly should the component behave upon pasting, but in UI5, once the value is pasted, the popover is opened and the suggestions are filtered as expected by the reporter.

Could you please have a look?
Best regards,
Ivaylo
