### ISSUE TITLE
[ui5-table] Sort and Filter?

### ISSUE THREAD

**Issue by fredt34** [SAP/ui5-webcomponents#8280]
I'm exploring the whole WebComponents framework for a new application (bun, elysia and htmx preferred). So far so good, but I can't find how to use basic features such as Sort and Filter for Table?

Moving and Resizing columns are also very common features now, how do I activate those?

**Comment by ivoplashkov** [comment]
Hello @fredt34,

Could you please create e new feature request, following the template we have provided in order for us to be able to process it accordingly?
On the Issues tab, click "New issue" and then choose "Feature request". Here is a screenshot:
<img width="1426" alt="Screenshot 2024-02-14 at 11 22 00" src="https://github.com/SAP/ui5-webcomponents/assets/23635149/2785ab17-9000-433a-a62e-9e74ff02146d">

Best regards,
Ivaylo
