### ISSUE TITLE
[tab-container]: In Inline mode we show the numbers in two places, instead of just one (brackets)

### ISSUE THREAD

**Issue by LidiyaGeorgieva** [SAP/ui5-webcomponents#8285]
### Bug Description

In Inline mode we show the numbers in two places, instead of just one (brackets).
![image](https://github.com/SAP/ui5-webcomponents/assets/7242508/c2c39b05-cc43-4ae9-9636-af1b2be3245c)

### Isolated Example

https://sap.github.io/ui5-webcomponents/nightly/playground/?path=/story/main-tab-container--inline-tab-layout

### Priority

Medium

### UI5 Web Components Version

main

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by LidiyaGeorgieva** [comment]
relates to: #8274

**Comment by olannyv** [comment]
Will be fixed with: https://github.com/SAP/ui5-webcomponents/issues/8274
