### ISSUE TITLE
CustomListItem - Input field inside a CustomListItem doesn't accept spacebar input

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#829]
**Describe the bug**
When using an Input Component inside a CustomListItem it's not possible to input a space.

**Isolated example**
https://codesandbox.io/s/ui5-webcomponents-fpo8g

**Expected behavior**
It should be possible to use an input field inside of a CustomListItem.

**Affected components** *(if known)*
CustomListItem
ListItem -> here the default key-press event is overwritten

**Comment by fifoosid** [comment]
Closing the issue as it is resolved in master branch

BR,
Filip

**Comment by ilhan007** [comment]
Hello @Lukas742 

We initially resolved the issue, but later we realised that we need better general solution that scales.

Sorry for that.

Best,
ilhan

**Comment by fifoosid** [comment]
Closing this issue as the problem is common for a couple of controls.

You can follow the progress here: #974
