### ISSUE TITLE
[Feature Request]: Highlight text within TextArea

### ISSUE THREAD

**Issue by ThiagoSzz** [SAP/ui5-webcomponents#8292]
### Feature Request Description

The idea is to visually highlight parts of text that match a regular expression. The highlight would be made by changing the background color of the substring that matches the specified condition to one of the accents available in the theming parameters.

Highlighting substrings in a sentence has a lot of use cases, like text annotation, field validation in a form, and many other specific use cases that might be suitable for applications.

More details and mocks can be seen below:

![image](https://github.com/SAP/ui5-webcomponents/assets/49589136/6d460a87-f590-4dc4-82a2-918ac028732f)

![image](https://github.com/SAP/ui5-webcomponents/assets/49589136/37449158-bc64-4f1f-86c9-f9fcf290d108)

One problem might appear when the color of the highlight passed as a prop to the component matches the color of a `ValueState`, like Information. One possible solution is described below:

![image](https://github.com/SAP/ui5-webcomponents/assets/49589136/efa1966a-9fd6-4fa9-a245-3cc89dd0bdd1)

It would be really great to have this feature. After doing some research around how to add text highlighting to a UI5 TextArea with the resources available at the moment, I found that all solutions converged on the need to replace the UI5 TextArea with another textarea component and use a library for highlighting. However, this solution might not be feasible for implementation in large projects that are heavily dependent on everything that comes with UI5's TextArea.

### Proposed Solution

The best possible solution, in my opinion, would be to have a separate component that accepts a UI5 TextArea to be passed as a prop or children. This component would have the props: `highlight-color` or `match-color` (the background color of the highlighted substrings), `condition` (the regular expression to match the substrings to be highlighted), `textarea` (a UI5 TextArea component).

Having the highlight appear in real time (as the user types something that matches the regex) would be great.

### Proposed Alternatives

Another possible solution is to have an [additional feature](https://sap.github.io/ui5-webcomponents/playground/?path=/docs/docs-getting-started-using-features--docs) that adds text highlighting capabilities to the UI5's TextArea component.

### Additional Context

A library that can be used in the implementation or as reference is [highlight-within-textarea](https://www.npmjs.com/package/highlight-within-textarea) (it's a JQuery plugin).

### Priority

None

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ivoplashkov** [comment]
Hello colleagues,

Could you please evaluate this feature request?

Best regards,
Ivaylo

**Comment by hristop** [comment]
Hi @ThiagoSzz ,

Thank you for contacting us with this requirement and the extensive explanation, however, we do not see this as part of the ui5-textarea component. 

This feature is more suitable for a rich-text editing component which renders html instead of simple textarea field. 

Best Regards,
Hristo
