### ISSUE TITLE
[Avatar]: Style issue of badge in Avatar component

### ISSUE THREAD

**Issue by zhangliangyi** [SAP/ui5-webcomponents#8298]
### Bug Description

The background and size of badge in Avatar component is not correct since 1.22.0
![image](https://github.com/SAP/ui5-webcomponents/assets/1867889/2045891d-b62f-40a9-a83b-1a1c0e1b3d94)

### Affected Component

Avatar

### Steps to Reproduce

1. Go to https://sap.github.io/ui5-webcomponents/playground/?path=/docs/main-avatar--avatar-overview
2. Scroll to `badge` slot
3. Check the display of the example in the slot definition

### Priority

Medium

### UI5 Web Components Version

1.22.0

### Browser

Edge

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by kskondov** [comment]
Hello @SAP/ui5-webcomponents-topic-p Can you please take a look at this issue in the "badge" slot example of the avatar component?

Best Regards

**Comment by dobrinyonkov** [comment]
This issue is now fixed by the ui5-tag component which adjusdted its color schemes to a new design specification.
https://sap.github.io/ui5-webcomponents/nightly/components/Avatar/#with-badge
![image](https://github.com/SAP/ui5-webcomponents/assets/22766569/57809852-e3e1-41c9-8981-2da621c62cda)
