### ISSUE TITLE
[ProgressIndicator]: [problem with z-index style when used in scrollable components like ObjectPage]

### ISSUE THREAD

**Issue by BloggingWithJan** [SAP/ui5-webcomponents#8303]
### Describe the bug

When using a `ProgressIndicator` in scrollable components like ObjectPage the style  z-index of the ProgressIndicator leads to problems

### Isolated Example

https://stackblitz.com/edit/github-fxxnbq?file=src%2FApp.tsx

### Reproduction steps

1. Scroll down

### Expected Behaviour

The ProgressIndicator is in the background. The ProgressIndicator is not visible/don't overlap the ObjectPageHeader.

### Screenshots or Videos

![image](https://github.com/SAP/ui5-webcomponents-react/assets/118006052/48e00255-cf54-4ca3-99ec-41072c34e989)
![image](https://github.com/SAP/ui5-webcomponents-react/assets/118006052/f1637c1b-6806-41af-84da-f31d50a811f7)

### UI5 Web Components for React Version

 "@ui5/webcomponents-react": "~1.25.0",

### UI5 Web Components Version

 "@ui5/webcomponents": "~1.22.0",

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by kskondov** [comment]
Hello, the issue is reproducible in the provided samples, the progress indicator goes over  other components when scrolling. @Lukas742 proposed a possible solution @SAP/ui5-webcomponents-topic-p  can you please take a look? 
Best Regards
