### ISSUE TITLE
[ui5-side-navigation]: broken story

### ISSUE THREAD

**Issue by nnaydenow** [SAP/ui5-webcomponents#8305]
### Bug Description

Storybook doesn't work

### Steps to Reproduce

https://sap.github.io/ui5-webcomponents/nightly/playground/?path=/story/fiori-side-navigation--basic

### Priority

None

### UI5 Web Components Version

1.22.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by s-todorova** [comment]
Hi @nnaydenow,

The issue has been fixed with [PR#8363](https://github.com/SAP/ui5-webcomponents/pull/8363).

Best regards,
Siyana
