### ISSUE TITLE
ui5-select: focus outline not presented over the selected option

### ISSUE THREAD

**Issue by niyap** [SAP/ui5-webcomponents#8308]
### Bug Description

Going through the options, changing the selected one, there is no visual focus outline presented.

### Affected Component

ui5-select

### Expected Behaviour

Focus outline is visible on the focused option.

### Isolated Example

https://sap.github.io/ui5-webcomponents/nightly/playground/main/pages/Select/

### Steps to Reproduce

1. Just check one random sample from the test page

### Priority

Medium

### UI5 Web Components Version

Latest

### Browser

Chrome

### Operating System

MacOS

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by plamenivanov91** [comment]
Issue is fixed in the 1.24 branch. It will be fixed in 2.0/main branch once the refactoring of the option is done.
