### ISSUE TITLE
[StandardListItem/CustomListItem]: Semantic highlight indicator

### ISSUE THREAD

**Issue by TinaAngeloski** [SAP/ui5-webcomponents#8317]
### Feature Request Description

The **StandardListItem** and **CustomListItem** should have a possibility for a semantic **highlight** indicator on the left side of the List Items.

### Proposed Solution

Same as in the [original UI5](https://ui5.sap.com/#/entity/sap.m.StandardListItem/sample/sap.m.sample.StandardListItemInfoStateInverted/code) components
and as described in the [Fiori Guidelines](https://experience.sap.com/fiori-design-web/list-overview/#highlight-items)

### Organization

SAP Signavio

### Priority

High

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ilhan007** [comment]
FYI @SAP/ui5-webcomponents-topic-p  @jdichev

**Comment by dobrinyonkov** [comment]
Internal Reference: BGSOFUIPIRIN-6488
