### ISSUE TITLE
[Feature Request]: CheckBox displayOnly icon size

### ISSUE THREAD

**Issue by PlutaKatarzyna** [SAP/ui5-webcomponents#8326]
### Feature Request Description

Recently added feature (v1.23.0-rc.2) - checkbox display only state has hardcoded icon size equals to 1rem. We need possibility of overwriting the icon size to 24px.

<img width="1200" alt="Screenshot 2024-02-21 at 14 16 11" src="https://github.com/SAP/ui5-webcomponents/assets/158282803/e4cc7865-85a5-4aa6-8c35-29e8638f555d">

### Proposed Solution

Add CSS variables to include possibility to overwrite ui5-icon inside ui5-checkbox component

### Proposed Alternatives

Add shadow parts into checkbox ui5-icon component

### Organization

SAP

### Additional Context

UDEx components

### Priority

None

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by dobrinyonkov** [comment]
Internal Reference: BGSOFUIPIRIN-6487
