### ISSUE TITLE
UI5ElementMetadata: Bring back events in metadata

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents#833]
Hi,

I saw that in the latest release (v1.0.0-rc.3), the merging of [metadata events](https://github.com/SAP/ui5-webcomponents/commit/b610aebb27e1ecc05af6fbdf6a56496668b6bdf3#diff-548f25b67c139e013bacfaea55add5bdL337-L339) and the [event getter](https://github.com/SAP/ui5-webcomponents/commit/b610aebb27e1ecc05af6fbdf6a56496668b6bdf3#diff-58949c6669040bf3ee7284d1e0aa6b9aL38-L41) was removed.

This change is breaking the Web Components for React wrapper because we are heavily relying in the events metadata.

## Example
The `Dialog` has no events defined, because events like `onBeforeClose` are defined in the `Popup`.
As the events are not merged any longer, the dialog metadata is not containing any events.
--> our wrapper can't bind them because they are "invisible" for us

Is there a specific reason why this logic was removed and can you bring it back?

Thanks,
Marcus

**Comment by ilhan007** [comment]
Hello @Marcus,

no specific reason other than it was not used internally and we did not aware that you depend on it, sorry for that, we will get the events info in the metadata.

Best,
ilhan

**Comment by MarcusNotheis** [comment]
perfect, thanks!
Do you already have an estimate when you want to release a version with events again?
