### ISSUE TITLE
Setting showClearIcon or showSelectAll does not reflect in the samples

### ISSUE THREAD

**Issue by hristop** [SAP/ui5-webcomponents#8330]
### **Issue Description**
The newly provided features "showClearIcon" and "showSelectAll" are not working in the samples

When editing the properties in the samples for the ui5-multi-combobox or ui5-input, does not matter, the changes are not reflected and neither select all, not clear icon is shown.

### **Issue Type**

- [ ] Documentation is unclear
- [ ] Documentation is incorrect
- [ ] Documentation is missing
- [x] Other

**Comment by ilhan007** [comment]
fyi The samples are present:
https://sap.github.io/ui5-webcomponents/preview/components/MultiComboBox/#select-all-items
https://sap.github.io/ui5-webcomponents/preview/components/MultiComboBox/#clear-icon
https://sap.github.io/ui5-webcomponents/preview/components/ComboBox/#clear-icon
https://sap.github.io/ui5-webcomponents/preview/components/Input#clear-icon

**Comment by jarrekk** [comment]
@ilhan007 the links are unavailable, any update for this issue? The `showClearIcon` and `showSelectAll` in [document](https://sap.github.io/ui5-webcomponents/playground/?path=/docs/main-multi-combo-box--multi-combo-box-overview) are still not working.

**Comment by petyabegovska** [comment]
Hi @jarrekk,

Here are the updated URLs:

https://sap.github.io/ui5-webcomponents/nightly/components/MultiComboBox/#select-all-items
https://sap.github.io/ui5-webcomponents/nightly/components/MultiComboBox/#clear-icon
https://sap.github.io/ui5-webcomponents/nightly/components/ComboBox/#clear-icon
https://sap.github.io/ui5-webcomponents/nightly/components/Input#clear-icon

Best regards,
Petya
