### ISSUE TITLE
[a11y]  [Dialog] For Dailog component dailog accessible name is not gettting announced in voice over in iphone

### ISSUE THREAD

**Issue by yoganjan** [SAP/ui5-webcomponents#8332]
### Bug Description

For the dialog component , When header slot is defined , the name of the dialog is not getting announced in the Voice Over in iPhone.

Voice Over just announces as Web Dialog

Note: 
When header slot is not added and Header Text slot is defined , then voice over is announcing the header title 

### Affected Component

Dialog

### Expected Behaviour

Voice Over should announce the dialog header title as well 

### Steps to Reproduce

1. Open https://sap.github.io/ui5-webcomponents-react/?path=/docs/modals-popovers-dialog--docs
2. Define header slot  with title component for Dialog
3. Turn on voice over in iphone
4. Observe that the Voice Over not announcing the title for the dialog header
...

### Priority

None

### UI5 Web Components Version

1.24.0

### Browser

Chrome

### Operating System

IPhone

### Organization

SAP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by kskondov** [comment]
Hello @SAP/ui5-webcomponents-topic-rd this seems like a Voice Over issue but can you please investigate further

**Comment by dimovpetar** [comment]
Hello @yoganjan ,

Do you still reproduce this issue?. Please check this example https://stackblitz.com/edit/js-ypqawr?file=index.js,index.html and edit it if it's missing something needed to reproduce it.

Best regards,
Petar
