### ISSUE TITLE
[UI5-Card]: The hovering behavior is not being properly honored in UI5 cards

### ISSUE THREAD

**Issue by bhoomika4567** [SAP/ui5-webcomponents#8339]
### Bug Description

The current implementation of the 'ui5-card' lacks a consistent hover effect across the entire card, unlike the behavior observed in 'ui5-list'. While the header section of the card displays a grey hover effect when using 'ui5-card-header', the same behavior is expected to be extended to the entire card for better user interface.

### Affected Component

ui5-card

### Expected Behaviour

When you hover over a ui5-card, the whole card should turn grey. Currently, it only happens in the header part. The request is to make the entire card show a grey hover effect for a more uniform user experience.

### Isolated Example

https://sap.github.io/ui5-webcomponents/playground/?path=/docs/main-card-card-header--card-header-overview

### Steps to Reproduce

To replicate the issue:
1) Hover over the card.
2) Observe that the grey hovering effect is only visible in the header section of the card, while the rest of the card retains its original appearance.

### Log Output, Stack Trace or Screenshots

Current Behavior: 
<img width="300" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/141990663/a7eced7c-df00-4090-b84d-8e915cc1ce47">

Changes Expected :
<img width="690" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/141990663/cab6a66e-6927-4474-8d0e-e167647f93fb">

### Priority

Medium

### UI5 Web Components Version

1.18.0

### Browser

Chrome

### Operating System

Windows 11

### Additional Context

https://wiki.one.int.sap/wiki/pages/viewpage.action?spaceKey=visualcore&title=Card+%28Horizon%29+-+Card+Anatomy

### Organization

SAP LABS INDIA

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by kskondov** [comment]
Hello @bhoomika4567 as the feature is still under discussion and this design is yet to be confirmed I am closing this issue
