### ISSUE TITLE
[UI5 Web Components 2.0] General guidance for API revision from accessibility perspective

### ISSUE THREAD

**Issue by nikolay-kolarov** [SAP/ui5-webcomponents#8353]
### **Motivation and Goal**
The goal is to create a central general guidance for the accessibility API in order to achieve consistency across the components and clean-up differences

### **Expected Output**
1. Make the analysis and create documentation with general guidance and recommendation how the accessibility related API needs to be implemented (which can be used also for future reference).
2. Prepare and create the follow-up issues for team execution in order to have clarity and clear guidance.

#### General topics
1. title – must be renamed to tooltip and made public, where relevant
3. ariaHasPopup & ariaHaspopup – we have inconsistencies in the naming that needs to be solved. Can be moved to accessibleAttributes.
4. accessibleName, accessibleNameRef, accessibleAttributes & accessibleRoleDescription - inconsistencies in default values and types needs to be solved

#### **Component specific info**
1.	Avatar & AvatarGroup - ariaHasPopup (protected) - see ariaHaspopup section above
2.	Icon  - ariaHidden (private) – remove the property, add an internal method (to be used by our components) to apply the aria-hidden attribute in the shadow dom only
3.	Label - for – we need to rename it, as this an attribute relevant for the native HTML element label
5.	Link - title – see title section above
6.	ListItem
                title – see title section above
                role & accessibleRole – only accessibleRole should remain. Maybe think of a enum as a type
                ariaHasPopup – see ariaHaspopup section above
7.	SideNavigationItemBase
                title – see title section above

**Comment by ilhan007** [comment]
Related to: https://github.com/SAP/ui5-webcomponents/issues/4460

**Comment by hristop** [comment]
Internal BLI created: BGSOFUIRILA-3820

**Comment by dobrinyonkov** [comment]
I believe this item can be closed now since the new API addressing all teams components is merged https://github.com/SAP/ui5-webcomponents/pull/8810.

**Comment by ilhan007** [comment]
If this [article](https://sap.github.io/ui5-webcomponents/docs/advanced/accessibility/) is up to date and does not require any changes, this can be closed
