### ISSUE TITLE
 [Breadcrumb Navigation]: The breadcrumb navigation feature does not appear to be rendering correctly in the Firefox browser, despite an adequate amount of available screen space.

### ISSUE THREAD

**Issue by shouryaa28** [SAP/ui5-webcomponents#8360]
### Bug Description

In our application, we have implemented dynamically created UI5 breadcrumbs to enhance user navigation. We have encountered an issue with this feature when it comes to the Firefox browser. Despite having sufficient amount of space, the UI5 breadcrumbs fail to display correctly in Firefox. This problem is not present in other browsers such as Edge and Chrome, where the functionality operates as expected.

This is the result in edge/chrome browser -

![image](https://github.com/SAP/ui5-webcomponents/assets/75392661/57bc2c59-ede7-41bf-af95-bbbe1f8a2999)

And this is the result in firefox browser -

![image](https://github.com/SAP/ui5-webcomponents/assets/75392661/41636ea6-ef35-4bda-bce1-bcf998585ec6)

### Affected Component

Web components in Firefox browser.

### Expected Behaviour

The behavior of Firefox browser should be like this :

![image](https://github.com/SAP/ui5-webcomponents/assets/75392661/8d51aca6-dc3a-4ce0-b654-2bf0b84b4fbe)

### Isolated Example

https://github.com/akshilverma/ui5-wc-breadcrumbs-test

### Steps to Reproduce

1. Clone the repository given in the isolated example.
2. Run the commands - npm install and then npm start.
3. Run it on firefox browser. 

### Priority

High

### UI5 Web Components Version

1.22.0

### Browser

Firefox

### Additional Context

SAP Build Actions

### Organization

SAP Labs

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by hinzzx** [comment]
Hello colleagues,

Please have look at this issue. It is easily reproducible by cloning the provided repository, running -> npm install -> npm start, and then observing the behavior in Firefox browser.

This is how it looks like in **Chrome**(_on my machine_):

![image](https://github.com/SAP/ui5-webcomponents/assets/88034608/5226304c-cc9a-45a0-91c0-a39b002ccded)

On **Firefox**(_on my machine_)

![image](https://github.com/SAP/ui5-webcomponents/assets/88034608/535e1421-2673-415b-8043-941c4444d3a7)

Best Regards,
Stoyan

**Comment by plamenivanov91** [comment]
Hello @shouryaa28,

Here is a code snippet where I set up a similar to your scenario and there are no issues with both Chrome and Mozilla:
[Code snippet](https://stackblitz.com/edit/js-ksuhbh?file=index.html)

Please make sure to use the latest version of both browsers and clear their cache.

If the issue persists, investigate the container in which you are trying to add the Breadcrumbs component. Some containers might render differently depending on the browser.

Regards,
Plamen Ivanov
