### ISSUE TITLE
[Feature Request]: be able to limit the height of the ui5-select popover

### ISSUE THREAD

**Issue by didbolf** [SAP/ui5-webcomponents#8364]
### Feature Request Description

Hi Team, would it be possible to have a way to limit the number of visible elements of the ui5-select popover?

### Proposed Solution

You could add a visibleItems property to the select for example

### Organization

SAP

### Additional Context

SAP SBPA

### Priority

Medium

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by dobrinyonkov** [comment]
Hi, @didbolf,
Thanks for your feature request!
This seems as duplicate of https://github.com/SAP/ui5-webcomponents/issues/4503. 
Let us know if your use case is somehow different. 

Regards,
Dobrin
