### ISSUE TITLE
[framework/documentation] custom-elements.json does not contain attributes

### ISSUE THREAD

**Issue by veith** [SAP/ui5-webcomponents#8392]
### Bug Description

The `dist/custom-elements.json` does not have a  `"attributes": []` section on any component. 
This information is needed to know if an attribute can be set declaratively via HTML and must not be set via JS.

This causes our linters which checks against the `dist/custom-elements.json` to trigger an error.

![Screenshot 2024-03-05 at 11 10 19](https://github.com/SAP/ui5-webcomponents/assets/606760/d6ff2327-e826-4efc-b133-836d3493b7b7)

Even the examples in the [playground](https://sap.github.io/ui5-webcomponents/playground/?path=/docs/main-button--button-overview) tells us to use the attributes, but the documentation says indirectly that you should use `accessibleName` via Js. This is very inconvenient.

### Affected Component

All documented components with attributes

### Expected Behaviour

Everything which can be passed declaratively should be listed in the attributes section of the custom-elements.json, like it was before 1.22.0

### Isolated Example

https://sap.github.io/ui5-webcomponents/playground/?path=/docs/main-button--button-overview

### Priority

Medium

### UI5 Web Components Version

1.22.0

### Browser

Chrome

### Operating System

any

### Additional Context

As a workaround, it is possible to map every member which is a field of type bool, string or something that results in a string to the attributes section.

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by nnaydenow** [comment]
Hi @veith,

Thanks for reporting this! I've linked a PR and I would ask you to check if it's working as expected.

**Comment by veith** [comment]
@nnaydenow 
I have run `GenerateAPI` and used the custom-elements.json. The attributes are working as expected.

Thank you for the good work.
