### ISSUE TITLE
Broken link in accessibility docs

### ISSUE THREAD

**Issue by swendlandt** [SAP/ui5-webcomponents#8393]
### **Issue Description**
In https://sap.github.io/ui5-webcomponents/playground/?path=/docs/docs-advanced-accessibility--docs#invisible-messaging there is a link to [Dynamic MessageStrip Generator Sample](https://sap.github.io/ui5-webcomponents/nightly/playground/?path=/docs/main-messagestrip--docs) which does not work anymore.

### **Issue Type**

- [ ] Documentation is unclear
- [x] Documentation is incorrect
- [ ] Documentation is missing
- [ ] Other

**Comment by IlianaB** [comment]
Hello @ui5-webcomponents-topic-p , I am forwarding this issue to you, because the link for Dynamic MessageStrip Generator Sample in Accessibility Docs is broken.
