### ISSUE TITLE
Error with <ui5-table-row> on UI5 Webcomponent - VueJS integration

### ISSUE THREAD

**Issue by macismail2003** [SAP/ui5-webcomponents#84]
Hi,

I am using Vue JS integration. As soon as I try to use ui5-table-row or ui5-table-cell, it throws below error.
ui5-table-column works ok

![image](https://user-images.githubusercontent.com/11865978/53228880-93543900-36bd-11e9-854a-a836f872651e.png)

My code here

![image](https://user-images.githubusercontent.com/11865978/53229116-50469580-36be-11e9-9c90-b493389b4869.png)

Thank you,
Seyed Ismail.

**Comment by MapTo0** [comment]
Hello @macismail2003 

Could you please try to give a slot to the rolls and cells (since v 0.7.1. giving it to cells wont be necessary.

`<ui5-table-row data-ui5-slot="rows">`
        `<ui5-table-cell data-ui5-slot="cells">`

**Comment by macismail2003** [comment]
Hi Martin,

I tried. something like this, still the same error.

![image](https://user-images.githubusercontent.com/11865978/53231562-31e39880-36c4-11e9-8fd2-e092b2c13f2a.png)

Thanks,
Seyed Ismail.

**Comment by MapTo0** [comment]
Could you please use `data-ui5-slot` instead of `slot`?  We are internally managing the `slot` API.

**Comment by macismail2003** [comment]
Thank you. When I use this,

![image](https://user-images.githubusercontent.com/11865978/53232071-45dbca00-36c5-11e9-8381-959e6e40fb2a.png)

I am getting this error!

![image](https://user-images.githubusercontent.com/11865978/53232094-52f8b900-36c5-11e9-9bd5-828065958265.png)

**Comment by MapTo0** [comment]
Please check this [source](https://glitch.com/edit/#!/charming-taste?path=public/index.html:23:0)
The count of columns and cells should be equal.

Here it is running: [demo](https://charming-taste.glitch.me/)

**Comment by macismail2003** [comment]
Thank you so much. It works after data-ui5-slot is removed for the <span>

![image](https://user-images.githubusercontent.com/11865978/53294434-aaac3700-3821-11e9-994f-0e4d91cd7a25.png)

Thank you, issue resolved. 

Seyed Ismail.
