### ISSUE TITLE
[Table - MultiSelectMode | UI5 | HCW | Safari]: On Table Selection in safari browser the row color is turning black & all the content becomes unreadable

### ISSUE THREAD

**Issue by achuth2912** [SAP/ui5-webcomponents#8404]
### Bug Description

The Table Multi select component on High Contrast White (HCW) mode, while we select the table rows the row back ground is becoming black ideally the back ground color must be #5c93ff for HCW mode when we select a row for the table.

### Affected Component

Table - MultiSelectMode

### Expected Behaviour

Ideally the background color must be #5c93ff for HCW mode when we select a row for the table.

### Steps to Reproduce

on UI5 Demo kit We can select the Table - MultiSelectMode & enable the HCW mode to reproduce this issue.
Attaching the Screen shot for reference.

<img width="1728" alt="Screenshot 2024-03-07 at 1 47 09 PM" src="https://github.com/SAP/ui5-webcomponents/assets/71249041/c592f41e-dd68-4b4d-b290-cc9172cc9c1d">

### Priority

Medium

### UI5 Web Components Version

1.20.0

### Browser

Safari

### Organization

SAP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by IlianaB** [comment]
Hello @achuth2912 ,

This is ui5 webcomponents project. What I see from your screenshot is [openui5 ](https://github.com/SAP/openui5)
Please, create an Issue it the respective repository.
Also, please share more details there, as I am not able to reproduce the issue. On 1.120 version the color of selected table row is exactly #5c93ff.

Regards,
Iliana
