### ISSUE TITLE
[SF][A11y][ui5-time-picker] Icon on time picker component needs a tooltip

### ISSUE THREAD

**Issue by bonnieso** [SAP/ui5-webcomponents#8408]
### Bug Description

The icon on the ui5-time-picker component lacks a tooltip which is needed to provide users with a description of the icon/button since there is no textual label for the button.

### Affected Component

ui5-time-picker

### Expected Behaviour

Upon hovering of the icon/button on the time picker component, a descriptive tooltip should appear.

### Steps to Reproduce

1. Go to https://sap.github.io/ui5-webcomponents/playground/?path=/docs/main-timepicker--time-picker-overview
2. Hover over the clock icon on a time picker example
3. Observe that no tooltip displays

### Priority

None

### UI5 Web Components Version

1.23.0

### Browser

Chrome, Edge, Firefox, Safari

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by tsanislavgatev** [comment]
Hello @bonnieso, 

After consultation with our ACC expert, we came to conclusion that by specification we should not have tooltip for buttons in inputs that are showing value help.
Some of the reasons are: 
- It's not done in other locations / OS / design systems (with only a few exceptions), and even not in pure HTML
- There is a tooltip on input level (although not recommended), which could get in conflict
- One day we would need to bring up this additional tooltip with the keyboard; for the icons do not have focus-position (and also shall not have one), this would not be very intuitive.

Based on that I am closing this issue.

Best Regards,
Tsanislav
