### ISSUE TITLE
MultiComboBox (TypeScript): incompatible `togglePopover` type

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#8417]
### Bug Description

After updating TypeScript to version `5.4.2` our build fails with the following TypeScript error:

```
node_modules/@ui5/webcomponents/dist/MultiComboBox.d.ts:257:5 - error TS2416: Property 'togglePopover' in type 'MultiComboBox' is not assignable to the same property in base type 'UI5Element'.
  Type '() => void' is not assignable to type '(force?: boolean) => boolean'.
    Type 'void' is not assignable to type 'boolean'.

257     togglePopover(): void;

```

It seems that the type for `togglePopover` of the `MultiComboBox` (See [here](https://unpkg.com/browse/@ui5/webcomponents@1.23.1/dist/MultiComboBox.d.ts) - line 257) is not compatible with the [togglePopover HTMLElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/togglePopover) method. (See [here](https://unpkg.com/browse/typescript@5.4.2/lib/lib.dom.d.ts) - line 10147)

### Priority

None

### UI5 Web Components Version

1.23.1

### Browser

Chrome

### Additional Context

TypeScript Version: 5.4.2

### Organization

UI5WCR

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ndeshev** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

We should rename our method, as there is now a native one with the same name.

Kind regards,
Nikolay
