### ISSUE TITLE
[ui5-multi-combobox] 'change' event not fired on focusout

### ISSUE THREAD

**Issue by ash-uncover** [SAP/ui5-webcomponents#8431]
### Bug Description

Since 1.22 the 'change' event is not fired anymore when focusing out of the ui-multi-combobox.

### Affected Component

ui5-multi-combobox

### Expected Behaviour

Change event is fired on focus out when the content of the multi-combobox has changed, as indicated in the documentation

### Isolated Example

https://codesandbox.io/p/sandbox/keen-galileo-sfg9hg?file=%2Findex.html%3A5%2C29

### Steps to Reproduce

1. Open sample
2. Change the value and press enter > an alert is displayed
3. Change the value and focus out > no alert

### Priority

Very High

### UI5 Web Components Version

1.22.0 1.23.1

### Browser

Chrome, Edge

### Additional Context

Blocker for adoption on SAP SBPA since 1.22.0

We have tests covering 100% of the properties & events of the ui5-webcomponents and we detected several regression in 1.22.0, this problem is one of them.

### Organization

SAP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ndeshev** [comment]
Hello @ash-uncover.

The `change `event is being fired when the user types in a value and press ENTER or focus out the component after that.
The `ui5-multi-combobox` listens for the `change `event of its native input to fire its own. When an item is selected with mouse the `selection-change` event is fired. You should listen to it. 

It only make sense to listen for `change` event in the `ui5-multi-combobox` if its `allowCustomValues` property is set to true.

Regards,
Nikolay

**Comment by ash-uncover** [comment]
Got your point, still the behavior has changed since 1.22 :)
We will update our tests and codeline accordingly but please dont change behavior of components !
