### ISSUE TITLE
[Feature Request][Timeline/TimelineItem]: expose `title` property to show truncated text 

### ISSUE THREAD

**Issue by hinzzx** [SAP/ui5-webcomponents#8439]
### Feature Request Description

Currently there is no way of showing the complete text of a Timeline item, if it is being truncated.
The client would like to be able to use `title` property in our control in order for the user to be able to see the complete text on mouse over.

### Proposed Solution

Expose `title` property.

### Priority

Medium

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by DMihaylova** [comment]
This feature request is no longer valid, as agreed in the linked issue.
