### ISSUE TITLE
[build]: Unable to build project using the latest version of the framework

### ISSUE THREAD

**Issue by tiagoapmartins** [SAP/ui5-webcomponents#8463]
### Bug Description

I'm unable to build my project upon updating to the latest version.
  ```
  "@ui5/webcomponents": "1.23.1",
  "@ui5/webcomponents-base": "1.23.1",
  "@ui5/webcomponents-fiori": "1.23.1",
  "@ui5/webcomponents-icons": "1.23.1",
  "@ui5/webcomponents-react": "1.26.0",
```

I get the following error:
```
x Build failed in 7.22s
error during build:
RollupError: Could not resolve "./dist/asset-registries/util/getIconCollectionsByTheme.js" from "node_modules/@ui5/webcomponents-base/index.js"
file: C:/Users/tiago/****-REPOS/***_Internal/****-********-ui5-frontend/node_modules/@ui5/webcomponents-base/index.js
    at getRollupError (file:///C:/Users/tiago/****-REPOS/***_Internal/****-********-ui5-frontend/node_modules/rollup/dist/es/shared/parseAst.js:376:41)
    at error (file:///C:/Users/tiago/****-REPOS/***_Internal/****-********-ui5-frontend/node_modules/rollup/dist/es/shared/parseAst.js:372:42)
    at ModuleLoader.handleInvalidResolvedId (file:///C:/Users/tiago/****-REPOS/***_Internal/****-********-ui5-frontend/node_modules/rollup/dist/es/shared/node-entry.js:18891:24)
    at file:///C:/Users/tiago/****-REPOS/***_Internal/****-********-ui5-frontend/node_modules/rollup/dist/es/shared/node-entry.js:18851:26
```

### Steps to Reproduce

1.
2.
3.
...

### Priority

None

### UI5 Web Components Version

1.23.1

### Browser

Chrome

### Operating System

Windows 11 Home 10.0.22631 Build 22631

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by pskelin** [comment]
Do you have a new import like this?
```ts
import UI5Element from "@ui5/webcomponents-base";
```

or is it only the update of the version?

There is a wrong import name, but it should only happen if you have the above import

**Comment by tiagoapmartins** [comment]
Hi @pskelin thank you for the prompt reply.
I'm referencing the `@ui5/webcomponents-base` package a few times to grab some utilities.
Mostly the following (they are references pulled from multiple files so please don't mind the duplicates):
```
import { setTheme, getTheme } from '@ui5/webcomponents-base/dist/config/Theme';
import { attachThemeLoaded, detachThemeLoaded } from '@ui5/webcomponents-base/dist/theming/ThemeLoaded.js';
import { isPhone } from '@ui5/webcomponents-base/dist/Device.js';
import { isPhone } from '@ui5/webcomponents-base';
import { setLanguage } from '@ui5/webcomponents-base/dist/config/Language.js';
```

**Comment by pskelin** [comment]
Thanks for the confirmation @tiagoapmartins ,
this is the line that hits the error case
```
import { isPhone } from '@ui5/webcomponents-base';
```

Can you please replace it as a workaround with the full path until the fix is released? You can keep using it after the next release.

all imports from the `@ui5/webcomponents-base` have a corresponding module which you can see here:
https://github.com/SAP/ui5-webcomponents/blob/2dff60fdb131802d532defc210c121ac04e8110d/packages/base/index.js

Please let me know if there are further issues.

**Comment by tiagoapmartins** [comment]
Changing that import did indeed fix the issue.
Thank you very much @pskelin!
