### ISSUE TITLE
[side-navigation-item]: when sidebar is collapsed popover content is not displayed completely with tool-layout

### ISSUE THREAD

**Issue by sachinbhutani** [SAP/ui5-webcomponents#8478]
### Bug Description

Popover displayed for side navigation items is hidden behind the content in tool layout

### Affected Component

side-navigation-item

### Expected Behaviour

popover should be displayed over the other content

### Isolated Example

https://sap.github.io/ui5-webcomponents/playground/?path=/story/fiori-side-navigation--tool-layout

### Steps to Reproduce

1. Collapse the sidebar
2. Hover over any sidebar navigation item 
3. The popover is not displayed completely 
...

### Log Output, Stack Trace or Screenshots

![image](https://github.com/SAP/ui5-webcomponents/assets/6120010/4454eed8-7099-4b7d-abd4-29df862406a5)

### Priority

None

### UI5 Web Components Version

1.23.1

### Browser

Edge

### Operating System

Windows

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by petyabegovska** [comment]
Hi @SAP/ui5-webcomponents-topic-rd,

Please check whether component or sample issue.

The issue is reproducible on other browsers as well, not Edge specific.

Best regards,
Petya

**Comment by TeodorTaushanov** [comment]
Hi,

The example is fixed 
https://sap.github.io/ui5-webcomponents/nightly/components/fiori/SideNavigation/#sidenavigation-in-tool-layout

Best,
Teo
