### ISSUE TITLE
[Button]: Focus wrong in Belize

### ISSUE THREAD

**Issue by mhchem** [SAP/ui5-webcomponents#8480]
### Bug Description

In the Belize theme, the focus of emphasized buttons is wrong. It should be a dotted line.
<img width="154" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/16336692/51408dbe-a4f7-4f9c-8fd7-161a4f592fdb">
This applies to the focus and focus+pressed state.
https://jsfiddle.net/ubm6gkoy/

### Affected Component

Button

### Expected Behaviour

A dotted line according to the visual specs

<img width="113" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/16336692/bd353ed3-24e4-4a4b-91fb-ce0f4c1a2f9d">

[Demo Kit](https://sapui5.hana.ondemand.com/resources/sap/ui/documentation/sdk/index.html?sap-ui-xx-sample-id=sap.m.sample.Button&sap-ui-xx-sample-lib=sap.m&sap-ui-xx-sample-origin=.&sap-ui-xx-dk-origin=https%3A%2F%2Fsapui5.hana.ondemand.com&sap-ui-theme=sap_belize&sap-ui-rtl=false&sap-ui-density=sapUiSizeCompact)

### Priority

None

### UI5 Web Components Version

latest

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ilhan007** [comment]
Hello @mhchem,
unfortunately as stated in the [docs](https://sap.github.io/ui5-webcomponents/nightly/docs/advanced/configuration) we don't support Belize any more.

<img width="1105" alt="Screenshot 2024-03-20 at 16 29 13" src="https://github.com/SAP/ui5-webcomponents/assets/15702139/50bf9052-aaa4-4958-ac57-4b26c9fe4f3c">

We hope that you can switch to Quartz or Horizon theme families, that provide better user experience according to user research results.

However, one thing that you can try (if you are using Belize only) is to overwrite the border style of the focus with:

```css
ui5-button[focused]::part(button)::before {
    border-style: dotted;
}
```

**Comment by ilhan007** [comment]
Hello colleagues @SAP/ui5-webcomponents-topic-b could you try to do fix the focus in Belize, it should be dotted as described in the issue. Probably extracting a variable for Belize should do the job, but please test Quartz and Horizon to make sure we won't break them, while fixing this.
