### ISSUE TITLE
[IllustratedMessage]: Layout problems

### ISSUE THREAD

**Issue by ej612** [SAP/ui5-webcomponents#8490]
### Bug Description

In v1.23.1, there seems to be something wrong with the `IllustratedMessage`:

![illustrated1](https://github.com/SAP/ui5-webcomponents/assets/110408767/16c731ac-badb-4a32-be71-fdf4d7361393)

`size={IllustrationMessageSize.Dot}` doesn't seem to work right, either:
![illustrated2](https://github.com/SAP/ui5-webcomponents/assets/110408767/f13325b9-9996-445b-92fe-4eadd38d00a1)

### Isolated Example
+ Open [this StackBlitz template](https://stackblitz.com/github/SAP/ui5-webcomponents-react/tree/main/templates/vite-ts?file=src%2FApp.tsx) made by the `@ui5/webcomponents-react` team
+ Paste this code into `App.tsx`:
```tsx
import {
  Dialog,
  IllustratedMessage,
  IllustrationMessageSize,
} from '@ui5/webcomponents-react';
import '@ui5/webcomponents-fiori/dist/illustrations/EmptyList.js';

function App() {
  return (
    <Dialog
      open={true}
      resizable={true}
      draggable={true}
      style={{
        height: '600px',
      }}
    >
      <IllustratedMessage
        name="EmptyList"
        titleText={'Your selection is empty.'}
        subtitleText={'Select items from the list.'}
        size={IllustrationMessageSize.Spot}
      />
    </Dialog>
  );
}

export default App;
```

Possibly related to #5852.

### UI5 Web Components Version

1.23.1

### Browser

Chrome

**Comment by ilhan007** [comment]
Hi @SAP/ui5-webcomponents-topic-p could you follow up.
related issue https://github.com/SAP/ui5-webcomponents/issues/5852

**Comment by plamenivanov91** [comment]
> Side note: The story '[With A Dialog](https://sap.github.io/ui5-webcomponents/playground/?path=/story/fiori-illustrated-message--with-a-dialog)' doesn't work in Firefox. When I click on the button, nothing happens and I have this error in the console: ![image](https://private-user-images.githubusercontent.com/110408767/314583237-e58ef28b-6497-4c81-a00e-356e4db6beef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MzEzOTAsIm5iZiI6MTcxMTYzMTA5MCwicGF0aCI6Ii8xMTA0MDg3NjcvMzE0NTgzMjM3LWU1OGVmMjhiLTY0OTctNGM4MS1hMDBlLTM1NmU0ZGI2YmVlZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOFQxMzA0NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YjlmNTE4NjYzMDVjNWIwYzg5YTA3ZGVhNDQxMjA5ODdlNmViMDlkMmE2NjA5NjZmZDdhNGVkMGZkYmE2ZGQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.m0sGYQoeh38BwKKGKJX7VFoZLmvKyXQPIOY8HVtAzvM)

Hello @ej612 ,

The sample works perfectly fine on the latest Firefox browser
![Screenshot 2024-03-28 155316](https://github.com/SAP/ui5-webcomponents/assets/13866865/f0e27040-6320-4112-9a2a-7b0405a428a4)

I'll look into the rest of the issue now.

Regards,
Plamen Ivanov
