### ISSUE TITLE
Method in DatePicker to get Date instead of string

### ISSUE THREAD

**Issue by marinho** [SAP/ui5-webcomponents#85]
**Is your feature request related to a problem? Please describe.**
DatePicker control adopts a similar API as a standard `HTMLInputElement`, with attribute `value` as a string with inputed date following format provided by `format-pattern`.

Problem is that we often need a `Date` object instead of a string, as each locale has a particular format, so, string will force us to verify current locale and parse it into an object.

**Describe the solution you'd like**
A method such as `getDateValue` in the control, which will return a Date object instead of string.

**Describe alternatives you've considered**
If that solution is problematic, providing `getFormat` as part of official API should  be helpful, at least.

**Additional context**
Version: 0.7.0

**Comment by a-z-ivanov** [comment]
getFormat is better, because you could parse and format, not just parse.

**Comment by marinho** [comment]
well, `getFormat` isn't better, as it requires more repetitive work on the implementation side, but it could be helpful sometimes if made public. So, having both would be cool
