### ISSUE TITLE
Switch QUnit tests to WDIO

### ISSUE THREAD

**Issue by pskelin** [SAP/ui5-webcomponents#850]
Tasks:
- [x] rewrite all component tests with the WDIO runner
- [x] remove the jest and qunit runner

Qunit files:
- [x] Badge
- [x] Calendar
- [x] Card
- [x] DatePicker
- [x] DayPicker
- [x] Dialog
- [x] Input
- [x] Label
- [x] Link
- [x] List
- [x] ListItem
- [x] Panel
- [x] Popover
- [x] RadioButton
- [x] TabContainer
- [x] TextArea
- [x] Title

**Comment by ilhan007** [comment]
- [] Badge
- [] Calendar
- [] Card
- [] DatePicker
- [] DayPicker
- [] Dialog
- [] Input
- [] Label
- [] Link
- [] List
- [] ListItem
- [] Panel
- [] Popover
- [] RadioButton
- [] TabContainer
- [] TextArea
- [] Title

**Comment by vladitasev** [comment]
WDIO is a test framework, using jasmine-like syntax. Please see the API here:
https://webdriver.io/docs/api.html

Please note the methods:
https://webdriver.io/docs/api/element/shadow$.html
and
https://webdriver.io/docs/api/element/shadow$$.html
in particular.

The goal of the task is to go through the QUnit tests and check which ones of them are worth keeping (are meaningful, are not duplicates of something that is already tested with the respective WDIO test for the same component). Then rewrite them in the WDIO syntax.

A couple of words about the WDIO tests. They are found here:
https://github.com/SAP/ui5-webcomponents/tree/master/packages/main/test/specs

and most of them start by navigating the browser to a test page, such as:
browser.url("http://localhost:8080/test-resources/pages/CheckBox.html");

These test pages are found here:
https://github.com/SAP/ui5-webcomponents/tree/master/packages/main/test/pages

Then the tests perform operations on the given pages.

**Comment by fifoosid** [comment]
Everything is implemented.
