### ISSUE TITLE
Select with Select Menu trigger Dialog after-close event

### ISSUE THREAD

**Issue by ooniki** [SAP/ui5-webcomponents#8500]
### Bug Description

I use Select With Select Menu and Select Menu Option inside a Dialog
When the Select is closed after a selection it trigger the Dialog after-close event.

### Affected Component

Select SelectMenu SelectMenuOption Dialog

### Expected Behaviour

no trigger of Dialog after-close event

### Isolated Example

https://stackblitz.com/edit/js-9pgnax?file=index.js,index.html,style.css

### Steps to Reproduce

1. Click on Open dialog Button
2. Click on the second Select to open it
3. Select Argentina Option
4. Check the console, the message come from Dialog after-close event

The first Select is a "classic" Select, this one dont trigger the event.

### Priority

Medium

### UI5 Web Components Version

1.20.1

### Browser

Chrome

### Operating System

windows

### Organization

SAP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by plamenivanov91** [comment]
Issue is fixed in the 1.24 code line. The issue won't occur on the main branch, once the Select's refactoring is complete.
