### ISSUE TITLE
Link: component has invisible border which causes misalignment

### ISSUE THREAD

**Issue by star4beam** [SAP/ui5-webcomponents#8512]
### Describe the bug

- Link component has invisibile border which leads to the horizonal missalignment of the text.

### Isolated Example

https://stackblitz.com/edit/github-ckyvrs-khgfqu?file=src%2FApp.tsx

### Expected Behaviour

1. Link component should not have any border.
2. In case there additional styling applied to highlight focus or other states, they should not affect dimensions of the component.
- Instead they should be implemented using outline or box-shadow or in any other non-intrusive way.

### Screenshots or Videos

**Current behaviour**

<img width="101" alt="Screenshot 2024-03-22 at 12 26 59" src="https://github.com/SAP/ui5-webcomponents-react/assets/18405013/be926a3f-b5b5-44e0-9efd-f3381d728da9">

**Expected behaviour**

<img width="158" alt="Screenshot 2024-03-22 at 12 31 36" src="https://github.com/SAP/ui5-webcomponents-react/assets/18405013/8cb784d5-6043-4626-9cdd-c98339638b9d">

### UI5 Web Components for React Version

1.25.1

### UI5 Web Components Version

1.22.0

### Browser

Chrome

### Organization

SAP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by petyabegovska** [comment]
Hello @SAP/ui5-webcomponents-topic-b,

Please check.

Best regards,
Petya
