### ISSUE TITLE
ui5-select should handle screen overflow

### ISSUE THREAD

**Issue by vicb** [SAP/ui5-webcomponents#853]
**Describe the bug**
When there are too many options in a `<ui5-select>` so that they don't all fit on the screen, there is no way to select an hidden option (other than keyboard navigation)

**Isolated example**
https://codesandbox.io/s/ui5-webcomponents-l6r4v

**Expected behavior**
Provide a way to access hidden options (down arrow, ...)

**Affected components** *(if known)*
ui5-select

**Comment by ilhan007** [comment]
Although issue is visible with the the ui5-select, most probably it`s in the ui5-popover, that is internally used by the ui5-select.

**Comment by d3nergy** [comment]
I have the same issue, to many Options sets the popover height higher than the screen.
Event though it has overflow:auto there has to be a maxHeight to make that work.
I suggest to insert a maxHeight prop that can be passed to the component.

**Comment by vicb** [comment]
Thanks !
