### ISSUE TITLE
[DateRangePicker]: Missing CLDR

### ISSUE THREAD

**Issue by IrvinDelgado** [SAP/ui5-webcomponents#8535]
### Bug Description

There is a request to https://sdk.openui5.org/1.103.0/resources/sap/ui/core/cldr/en.json which has status code 404 (missing disk cache). Which then breaks DateRangePicker and makes it not appear.

ui5-webcomponents is using https://github.com/SAP/ui5-webcomponents/blob/main/packages/base/src/asset-registries/LocaleData.ts#L153
Checked available SAPUI5 versions here https://ui5.sap.com/versionoverview.html
Then checked package here https://ui5.sap.com/1.103.0/versioninfo.html which seems to show missing.

### Affected Component

DateRangePicker

### Expected Behaviour

Would expect the call to return correctly with status code 200.

### Steps to Reproduce

1. Follow the following link https://sdk.openui5.org/1.103.0/resources/sap/ui/core/cldr/en.json
2. For some users it will resolve to a 404.

Note: Not easily reproducible just happens to some customers. 

### Log Output, Stack Trace or Screenshots

![image (1)](https://github.com/SAP/ui5-webcomponents/assets/62973847/3b1b9c37-3c27-4e06-8250-bdb97b2627cf)
![Screenshot 2024-03-25 at 1 45 18 PM](https://github.com/SAP/ui5-webcomponents/assets/62973847/c002fee2-694c-42fe-9b87-17a345f331c9)

### Priority

Medium

### UI5 Web Components Version

1.7.1

### Browser

Chrome

### Operating System

openSUSE Leap 42.1

### Organization

WEF San Ramon

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by petyabegovska** [comment]
Hi @IrvinDelgado,

Fixed in main to use  https://sdk.openui5.org/1.120.5/resources/sap/ui/core/cldr/en.json.

Best regards,
Petya

**Comment by stephen-schmith** [comment]
@petyabegovska This issue is impacting multiple product areas in SF - do you know when 1.24.0 will be available? Or could the fix be backported to a previous version?

**Comment by petyabegovska** [comment]
Hi @stephen-schmith,

Sorry for the late reply. 1.24.0 has been available since 2024-04-04:[1.24.0](https://github.com/SAP/ui5-webcomponents/compare/v1.24.0-rc.4...v1.23.0) (2024-04-04) 

Best regards,
Petya
