### ISSUE TITLE
`showClearIcon` and `showSelectAll` are not working in Multi-Combo Box

### ISSUE THREAD

**Issue by jarrekk** [SAP/ui5-webcomponents#8537]
### **Issue Description**
A clear and concise description of the documentation issue.

### **Issue Type**

- [ ] Documentation is unclear
- [x] Documentation is incorrect
- [ ] Documentation is missing
- [ ] Other

When I change these two attributes in the [sample](https://sap.github.io/ui5-webcomponents/playground/?path=/docs/main-multi-combo-box--multi-combo-box-overview), there is no change.

Refer to #8330.

**Comment by petyabegovska** [comment]
Hi @jarrekk,

Here are the links to the samples in the new documention:
 
https://sap.github.io/ui5-webcomponents/nightly/components/MultiComboBox/#select-all-items
https://sap.github.io/ui5-webcomponents/nightly/components/MultiComboBox/#clear-icon
https://sap.github.io/ui5-webcomponents/nightly/components/ComboBox/#clear-icon
https://sap.github.io/ui5-webcomponents/nightly/components/Input#clear-icon

Best regards,
Petya

**Comment by jarrekk** [comment]
Thanks for the quick reply!
