### ISSUE TITLE
[Radio Button] Not emitting "change" event in a group

### ISSUE THREAD

**Issue by PlutaKatarzyna** [SAP/ui5-webcomponents#8546]
### Bug Description

When there are radio buttons grouped by "name" attribute, and different radio buttons are clicked, there is "change" event emitted only when radio button changes state to "true'. When radio button changed state to "false" it does not emit the event.

### Affected Component

ui5-radio-button

### Expected Behaviour

When clicking on different radio buttons in the same group, "change" event should be emitted when radio button switch state to true, but also when it switch state to false.

### Isolated Example

https://sap.github.io/ui5-webcomponents/playground/?path=/docs/main-radio-button--radio-button-overview

### Steps to Reproduce

1. Have at least 2 ui5-radio-button components on page, with the same "name" attribute for grouping 
2. Add "change" event listener for all of them 
3. Click on any radio button and see that event is firing -> value changed to true
4. Click on second radio button -> one event is emitted -> when value was changed to true
5. Previous radio button changed state to false, but it did not emit event.

### Log Output, Stack Trace or Screenshots

https://github.com/SAP/ui5-webcomponents/assets/158282803/cb48ff7b-d48b-494e-b006-954776343df5

### Priority

None

### UI5 Web Components Version

1.21.0-rc.2

### Browser

Chrome

### Operating System

iOS

### Organization

SAP / UDEx components team

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by unazko** [comment]
Hello @SAP/ui5-webcomponents-topic-rd,

Steps to reproduce:
1) Open: https://sap.github.io/ui5-webcomponents/playground/?path=/docs/main-radio-button--radio-button-overview
2) Execute in console:
```js
document.getElementById("root-inner")
	.querySelectorAll("& > ui5-radio-button")
	.forEach((radio) => {
		radio.addEventListener("change", (e) => {
			console.warn(e);
		})
	});
```
3) Click around over the first radio button group

**Observed:**
- Change event is fired only to indicated the newly checked radio button from the group.

**Expected**
- Change event to be fired for the newly checked radio button and for the previously checked(currently unchecked) radio button

Not sure whether this is a issue or not as 
for comparison the change event is fired only once with a native radio button group:
https://jsfiddle.net/unazko/h5nap8vo/2/

Best regards,
Boyan

**Comment by TeodorTaushanov** [comment]
Hi @PlutaKatarzyna,

The events should be fired only as a result of user interaction and only one radio button is "clicked". That's why only one event is fired.

As @unazko mentioned the native <input type="radio"> behave in the same way:
https://jsfiddle.net/unazko/h5nap8vo/2/

Best,
Teo
