### ISSUE TITLE
Tree Item: If text is more than available space then only a portion of the text is visible to the user

### ISSUE THREAD

**Issue by lateefsofi** [SAP/ui5-webcomponents#8551]
### Bug Description

If text is more than available space then only a portion of the text is visible to the user 
At least it should have shown tooltip for such cases

### Affected Component

Tree Item, it looks the same problem with other components as well like List

### Expected Behaviour

Tree Item should either display entire text even if it goes beyond the available space or show the tool tip so that use can see entire text.

### Isolated Example

https://stackblitz.com/edit/js-3t6vcn?file=index.js,index.html

### Steps to Reproduce

1. Navigate to https://stackblitz.com/edit/js-3t6vcn?file=index.js,index.html
2. Check the first tree element

### Priority

Medium

### UI5 Web Components Version

1.20.1

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by nnaydenow** [comment]
Hello @lateefsofi,

If you take a look at the code here: [TreeItemBase.ts](https://github.com/SAP/ui5-webcomponents/blob/main/packages/main/src/TreeItemBase.ts#L87), you'll notice that TreeItems are extending the ListItem class. Starting from version 1.23, the ListItem class includes the tooltip property. This means that TreeItems will inherit this property as well, which should address the issue you're encountering.

**Comment by lateefsofi** [comment]
@nnaydenow I updated the version of webcomponenst to 1.23.1 https://stackblitz.com/edit/js-3t6vcn?file=index.js,index.html,package.json, but I don't see tooltip.

**Comment by nnaydenow** [comment]
Hi @lateefsofi,

To display the tooltip you have to add it to the ui5-tree-item as in the example:
```html
    <ui5-tree-item
      text="The List component allows displaying a list of items, advanced keyboard handling support for navigating between items, and predefined modes to improve the development efficiency."
      tooltip="The List component allows displaying a list of items, advanced keyboard handling support for navigating between items, and predefined modes to improve the development efficiency."
      expanded="true"
      icon="paste"
    >
    ```
    
   I've tested it in your example it everything works correctly. Could you please confirm that this solution works for you?
   
   Regards,
   Nayden

**Comment by lateefsofi** [comment]
Hi @nnaydenow 
I don't see tooltip coming up.
Thanks,
Lateef

**Comment by petyabegovska** [comment]
Hi @lateefsofi,

I updated the dependency to 1.23.1 and now it shows the tooltip. See the screenshot:
<img width="1737" alt="Screenshot 2024-03-28 at 8 18 06" src="https://github.com/SAP/ui5-webcomponents/assets/8136099/be7d32a5-59be-43c2-b08b-606a7f8ffaa6">

Best regards,
Petya
