### ISSUE TITLE
FileUploader: incorrect "drag and drop" area

### ISSUE THREAD

**Issue by nodari-dev** [SAP/ui5-webcomponents#8572]
### Describe the bug

Component area for "drag and drop" is not correct, so user needs to find a specific spot to upload a file

### Reproduction steps

1. Drag and drop file into FileUploader 
2. File will be opened in another tab (in my case it was a json file)

### Expected Behaviour

"drag and drop" should be working for the whole area of FileUploader component

### Screenshots or Videos

![bug-ezgif com-optimize](https://github.com/SAP/ui5-webcomponents-react/assets/32438959/c5d43c25-2c0b-49e6-93b9-ed3137334910)

### UI5 Web Components for React Version

1.23.0 and higher

### UI5 Web Components Version

1.21.0 and higher

### Browser

Chrome, Safari

### Operating System

Mac OS

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by unazko** [comment]
Hello @SAP/ui5-webcomponents-topic-b,

The inner input type "file" is transparent and has smaller size than the visual input and browse button.
The drag and drop operation works over the input type file element.

Best regards,
Boyan
