### ISSUE TITLE
[Slider]: Support disable for certain values

### ISSUE THREAD

**Issue by saurabhmehta13** [SAP/ui5-webcomponents#8573]
### Feature Request Description

Currently, setting the disable property for the slider component disables the entire component. However, we have a new requirement that necessitates the ability to disable specific values within the slider rather than the entire component.

For instance, consider a scenario where the slider is utilized for rating purposes. If the rating value is set to 3, it's highly unlikely that the user would choose a lower value such as 1. Therefore, we require functionality to selectively disable certain values within the slider to prevent users from selecting them again.

### Proposed Solution

Support a new property say `disabledValues` where consumer can pass one or more disabled values

### Organization

SAP Labs

### Priority

High

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by unazko** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

Please take a look at this feature request.

Best regards,
Boyan

**Comment by hristop** [comment]
Hi @saurabhmehta13 

After discussions with our design team, this feature request should go through the inner source process. Can you please create BLI to Central Design and put the number of the E1 here for reference?

Best Regards,
Hristo
