### ISSUE TITLE
[SF_ACC] [List] "Contains Deletable Items" is only being announced once when accessibleName is defined

### ISSUE THREAD

**Issue by bonnieso** [SAP/ui5-webcomponents#8575]
### Bug Description

When a List component with mode="Delete" also has an accessibleName property, "Contains Deletable Items" is only being announced once when user enters the list.

### Affected Component

List

### Expected Behaviour

It is expected that "Contains Deletable Items" is read for a List with "Delete" mode defined whenever a user enters the list via keyboard using a screen reader, not just the first time the user enters the list.

### Isolated Example

https://codesandbox.io/s/sleepy-borg-m45kw6

### Steps to Reproduce

1. Turn on screen reader and navigate to the list using your keyboard
2. Observe that "Contains Deletable Items" is not read

### Priority

Medium

### UI5 Web Components Version

1.23.0

### Browser

Chrome

### Operating System

MacOS 14.3.1

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by unazko** [comment]
Hello @bonnieso,

The `accessibleName` property effect is to add an `aria-label` attribute to the `<ul role="list"></ul>` element.
This aria-label attribute will be part of the accessibility semantics of the list and will only be announced initially when
the user navigates to the list.

For comparison here is the following [example](https://ui5.sap.com/#/entity/sap.m.List/sample/sap.m.sample.ListCounter).
Here we have a "Products" title for the list and this title is referenced through a `aria-labelledby` attribute.
The title is expected to only be announced once stating the current context the user is in.
If there is no context change (user navigates between the list items) the labels won't be announced.

Best regards,
Boyan
