### ISSUE TITLE
ui5-shellbar keyboard navigation broken

### ISSUE THREAD

**Issue by pskelin** [SAP/ui5-webcomponents#860]
**Describe the bug**
When an icon in the shellbar is selected, navigating with the arrows doesn't work

**To reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/test-resources/sap/ui/webcomponents/main/pages/ShellBar.html
2. Select an icon that doesn't open a popover
3. Navigate with arrow keys - doesn't work

**Isolated example**
Here is a working example with 1.0.0-rc.2
https://codesandbox.io/s/ui5-webcomponents-i2lmz?fontsize=14

**Expected behavior**
focused icon should change with arrow keys

**Context**
- UI5 Web Components version: 1.0.0-rc.4

**Affected components** *(if known)*
ui5-shellbar

**Comment by MapTo0** [comment]
Spec:

![image](https://user-images.githubusercontent.com/5821279/68194998-bc53fa00-ffbe-11e9-91d4-16d6c3226458.png)

Navigation with arrows should not be implemented.
