### ISSUE TITLE
SplitButton: Low contrast in "disabled" state

### ISSUE THREAD

**Issue by EduardTrutsyk** [SAP/ui5-webcomponents#8615]
### Describe the bug

SplitButton has low contrast in disabled state and not consistent with regular button.

### Isolated Example

https://stackblitz.com/edit/github-dav6yu?file=src%2FApp.tsx

### Reproduction steps

1. set prop "design" to "Emphasized"
2. set prop "disabled" to "disabled"

### Expected Behaviour

<img width="224" alt="image" src="https://github.com/SAP/ui5-webcomponents-react/assets/5457280/b93fb196-a6b3-44ae-b4f3-e1ecec01fcbf">

### Screenshots or Videos

<img width="224" alt="image" src="https://github.com/SAP/ui5-webcomponents-react/assets/5457280/16ff11a9-a021-426b-b3da-accefc56b232">

<img width="237" alt="image" src="https://github.com/SAP/ui5-webcomponents-react/assets/5457280/eb97f8d9-3938-4b4e-9ddb-6cf8bdf2c4c5">

### UI5 Web Components for React Version

1.26.1

### UI5 Web Components Version

1.23.1

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by dobrinyonkov** [comment]
Hello @SAP/ui5-webcomponents-topic-b,

SplitButton has differenent styles for its disabled state compared to the regural button when design is Emphasized.
You can test this in the following example: 
https://stackblitz.com/edit/js-8acqxv?file=index.js,index.html

In the SplitButtons's VD speciftication I couldn't find a section about the disabled state.
Could you please check with the design team and align the implementation accordingly?

Kind Regards,
Dobrin
