### ISSUE TITLE
[Feature Request]: Add Menu Button component like in SAP UI5

### ISSUE THREAD

**Issue by Vir-Mittal** [SAP/ui5-webcomponents#8625]
### Feature Request Description

SAP UI5 has a component called Menu Button - https://openui5nightly.hana.ondemand.com/entity/sap.m.MenuButton/sample/sap.m.sample.MenuButton/code

This supports showing text/icon along with a dropdown icon to open a menu - 

<img width="142" alt="Screenshot 2024-04-03 at 2 14 10 PM" src="https://github.com/SAP/ui5-webcomponents/assets/36656306/d63dd5d1-3548-4d4e-9ebb-66603848e2bd">

This is currently not available in the webcomponents library

### Proposed Solution

Add the component to the library

### Organization

SuccessFactors

### Priority

High

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ilhan007** [comment]
Hello @Vir-Mittal  We have SplitButton and Menu component that can be used like this https://sap.github.io/ui5-webcomponents/nightly/components/SplitButton#opening-menu. Would that cover your use-case?

**Comment by Vir-Mittal** [comment]
Hi @ilhan007 thank you for your reply. I checked with our PM and UX and they are pushing for this new component because the SplitButton component does not cover the expected use-case (The SplitButotn has a vertical divider line in the middle)

**Comment by tsanislavgatev** [comment]
Hello @Vir-Mittal ,

Can you also check https://sap.github.io/ui5-webcomponents/nightly/components/Menu/ , the same can be achieved with a Button? You can use a ui5-button with icon or ui5-split-button, depending on the use case you want? 
Is there a specific reason why is a MenuButton needed, if the same thing can be achieved with ui5-button or ui5-split-button? 

Best Regards,
Tsanislav

**Comment by Vir-Mittal** [comment]
Hi @tsanislavgatev we tried using both those components - 
With ui5-button we can get something like - 
<img width="59" alt="Screenshot 2024-04-23 at 10 51 57 AM" src="https://github.com/SAP/ui5-webcomponents/assets/36656306/60f81a04-a57e-4a40-8338-5730051667a5">

With split button we can get - 
<img width="109" alt="Screenshot 2024-04-23 at 10 52 43 AM" src="https://github.com/SAP/ui5-webcomponents/assets/36656306/ee1b9190-f0c0-4c42-9448-ba164b921e00">

But what our UX wants is something like - 
<img width="239" alt="Screenshot 2024-04-23 at 10 52 59 AM" src="https://github.com/SAP/ui5-webcomponents/assets/36656306/905178c1-c861-431d-badc-1faa9b64a27e">

This third button type we are unable to get using the current webcomponent library

Thanks,
Vir

**Comment by tsanislavgatev** [comment]
Hello @Vir-Mittal 
Can you please check [this sample](https://sap.github.io/ui5-webcomponents/nightly/play/#eyJpbmRleC5odG1sIjp7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuPCFET0NUWVBFIGh0bWw-XG48aHRtbCBsYW5nPVwiZW5cIj5cblxuXG5cbjxoZWFkPlxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG4gICAgPC9zdHlsZT5cblxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG4gICAgICAjYnRuT3BlbkJhc2ljIFt1aTUtaWNvbl0ge1xuICAgICAgICBjb2xvcjogaW5oZXJpdDtcbiAgICAgIH1cbiAgICA8L3N0eWxlPlxuXG4gICAgPG1ldGEgY2hhcnNldD1cIlVURi04XCI-XG4gICAgPG1ldGEgbmFtZT1cInZpZXdwb3J0XCIgY29udGVudD1cIndpZHRoPWRldmljZS13aWR0aCwgaW5pdGlhbC1zY2FsZT0xLjBcIj5cbiAgICA8dGl0bGU-U2FtcGxlPC90aXRsZT5cbjwvaGVhZD5cblxuPGJvZHkgc3R5bGU9XCJiYWNrZ3JvdW5kLWNvbG9yOiB2YXIoLS1zYXBCYWNrZ3JvdW5kQ29sb3IpOyBoZWlnaHQ6IDM1MHB4XCI-XG4gICAgPCEtLSBwbGF5Z3JvdW5kLWZvbGQtZW5kIC0tPlxuXG4gICAgPHVpNS1idXR0b24gaWQ9XCJidG5PcGVuQmFzaWNcIiBpY29uPVwic2xpbS1hcnJvdy1kb3duXCIgaWNvbi1lbmQ-XG4gICAgPHVpNS1pY29uIG5hbWU9XCJhaVwiPjwvdWk1LWljb24-PC91aTUtYnV0dG9uPiA8YnI-XG5cbiAgICA8dWk1LW1lbnUgaGVhZGVyLXRleHQ9XCJCYXNpYyBNZW51IHdpdGggSXRlbXNcIiBpZD1cIm1lbnVCYXNpY1wiPlxuICAgICAgICA8dWk1LW1lbnUtaXRlbSB0ZXh0PVwiTmV3IEZpbGVcIiBpY29uPVwiYWRkLWRvY3VtZW50XCI-PC91aTUtbWVudS1pdGVtPlxuICAgICAgICA8dWk1LW1lbnUtaXRlbSB0ZXh0PVwiTmV3IEZvbGRlclwiIGljb249XCJhZGQtZm9sZGVyXCIgZGlzYWJsZWQ-PC91aTUtbWVudS1pdGVtPlxuICAgICAgICA8dWk1LW1lbnUtaXRlbSB0ZXh0PVwiT3BlblwiIGljb249XCJvcGVuLWZvbGRlclwiIHN0YXJ0cy1zZWN0aW9uPjwvdWk1LW1lbnUtaXRlbT5cbiAgICAgICAgPHVpNS1tZW51LWl0ZW0gdGV4dD1cIkNsb3NlXCI-PC91aTUtbWVudS1pdGVtPlxuICAgICAgICA8dWk1LW1lbnUtaXRlbSB0ZXh0PVwiUHJlZmVyZW5jZXNcIiBpY29uPVwiYWN0aW9uLXNldHRpbmdzXCIgc3RhcnRzLXNlY3Rpb24-PC91aTUtbWVudS1pdGVtPlxuICAgICAgICA8dWk1LW1lbnUtaXRlbSB0ZXh0PVwiRXhpdFwiIGljb249XCJqb3VybmV5LWFycml2ZVwiPjwvdWk1LW1lbnUtaXRlbT5cbiAgICA8L3VpNS1tZW51PlxuICAgIDwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuICAgIDxzY3JpcHQgdHlwZT1cIm1vZHVsZVwiIHNyYz1cIm1haW4uanNcIj48L3NjcmlwdD5cbjwvYm9keT5cblxuPC9odG1sPlxuPCEtLSBwbGF5Z3JvdW5kLWZvbGQtZW5kIC0tPlxuIn0sIm1haW4uanMiOnsibmFtZSI6Im1haW4uanMiLCJjb250ZW50IjoiLyogcGxheWdyb3VuZC1oaWRlICovXG5pbXBvcnQgXCIuL3BsYXlncm91bmQtc3VwcG9ydC5qc1wiO1xuLyogcGxheWdyb3VuZC1oaWRlLWVuZCAqL1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzL2Rpc3QvTWVudS5qc1wiO1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzL2Rpc3QvTWVudUl0ZW0uanNcIjtcblxuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzLWljb25zL2Rpc3QvYWRkLWRvY3VtZW50LmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMtaWNvbnMvZGlzdC9hZGQtZm9sZGVyLmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMtaWNvbnMvZGlzdC9vcGVuLWZvbGRlci5qc1wiO1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzLWljb25zL2Rpc3Qvc2F2ZS5qc1wiO1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzLWljb25zL2Rpc3QvYWkuanNcIjtcbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy1pY29ucy9kaXN0L3VwbG9hZC10by1jbG91ZC5qc1wiO1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzLWljb25zL2Rpc3QvYWN0aW9uLXNldHRpbmdzLmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMtaWNvbnMvZGlzdC9qb3VybmV5LWFycml2ZS5qc1wiO1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzLWljb25zL2Rpc3Qvc2xpbS1hcnJvdy1kb3duLmpzXCI7XG5cbmNvbnN0IGJ0bk9wZW5CYXNpYyA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKFwiYnRuT3BlbkJhc2ljXCIpO1xuY29uc3QgbWVudUJhc2ljID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoXCJtZW51QmFzaWNcIik7XG5cbmJ0bk9wZW5CYXNpYy5hZGRFdmVudExpc3RlbmVyKFwiY2xpY2tcIiwgZnVuY3Rpb24oZXZlbnQpIHtcbiAgICBtZW51QmFzaWMuc2hvd0F0KGJ0bk9wZW5CYXNpYyk7XG59KTsifX0)

Best Regards,
Tsanislav

**Comment by Vir-Mittal** [comment]
Hi @tsanislavgatev that works perfectly for us, thank you!

**Comment by ej612** [comment]
Hi @tsanislavgatev,

I'm finding myself in the same situation and in need of a `MenuButton` component. Unfortunately, the sample you linked to is no longer available. Could you add it to the docs?

Thanks!

**Comment by pskelin** [comment]
@ej612 all samples are broken and will be fixed by #12721 

in the mean time, I have manually extracted the sample from above:
[MenuButton](https://ui5.github.io/webcomponents/play/#eNrtVU1v2zAM_SuqT0lRxaddUjcY2mVAgW3toZcBvigW06i1JUOS84Ei_32k_BGnXbsY23FIDjbJ90jKj9RLpLSE7WTlizyavkRaFBBN-8aLKDPag_ZoTs44Z2Uudo_WVFrypckl43yW6uTsy93Nw8_7OSMQGtpfsgIh8Z3hP3F-lwO9nE-18aOphKXSIMfsBW1SOaKeMm00XKJhT_jAF_xLYzOQPDO5sVzIp8r5o1iWxC3__3T_NF0SNx8RHxdG7lhwXaXRQmTPjRQC05SthR1x7kR53bluyDO-ZK8jHmDrG18aUR-_UxcH3Sgs1J9U6hNfVN4bzZSkCry-K0FfC6eyNGIKtYpWl6uCC2vNhkuz0Y2DuGYtCRkYqR3DhcICkrg1N491mhlLFnZ2SF6ArhgdB1jusQOEh-TsOzk2yq_YrYfCUU4qkOLb6gxWCvZN1bM-N1eIZg3zD9iwryqHQ2dCSmwpqzDUd0V3uD8w4XmCPeZatjYUjFjkIE-npA4OZNTbgc15Yb3jDjKvugM9gfMmNw6G9HVvYQkWdAau11jIitm9V_rR_UU9863yB94nU1kNO1KWWr9XZmd6T9K1nHF-M6tKz_yuJA0WRlbhQzub0atQevLkQo46kJZsTNNXz-GHsxLtL2oG77a9rd6Z-jtdFaWxnqXRJO7xuaokcygBV0J83k-2UhJCsvM41R3-MzYeb2CRGbRoJHcxisrHNBgtz0nBND8t4ENImNYG2B-ME7K9htbKHQjsaX4g0ok1DK1SDQRUZW6E5N7wLDeVHJrueIYGoo8nZejhHG_vgxQoxLP-8mRXrPvoj-DnOdDj9e5Wjl5vWbxlGoJuJX-I7i3uccjep5ugZuZrDP6GBdNSR0CWq-w5jS7YstLh8EZAEfV93LFNSDRX3lbhpk31fhzt978AQexhEQ)

**Comment by tsanislavgatev** [comment]
I am closing this issue as the sample was provided and fixed samples already have one example.
