### ISSUE TITLE
[SegmentedButton] Displays items vertically

### ISSUE THREAD

**Issue by ej612** [SAP/ui5-webcomponents#8628]
### Bug Description

Hi there!

In 1.23.2, the `SegmentedButton` seems to have changed:
In 1.23.1 (and previous releases), the items are displayed next to each other ([SandBox](https://stackblitz.com/edit/github-8kknqc-warofm?file=src%2FApp.tsx)).
In 1.23.2, the items are displayed on top of each other ([SandBox](https://stackblitz.com/edit/github-8kknqc?file=src%2FApp.tsx)).

![segmented_button](https://github.com/SAP/ui5-webcomponents/assets/110408767/a9d6cec9-7adb-4e70-9b8a-566a930118aa)

I couldn't find anything in the changelog that would explain this, which makes me think it might be a bug.

### UI5 Web Components Version

1.23.2

### Browser

Chrome

**Comment by dobrinyonkov** [comment]
Hello @SAP/ui5-webcomponents-topic-core,

This seems like an issue with the scoping of the CSS variables.
The `SegmentedButton` is using the `getScopedVarName` in its `onBeforeRendering` hook to set a css var `--_ui5_segmented_btn_items_count` dynamically and calculate the `min-width` for the container later in the CSS file.

It seems that the `getScopedVarName` registered the css var as: 
--_ui5-v**1-23-1**_segmented_btn_items_count 
(which seems incorrect as the version is actually 1.23.2),

but when later used in the css of the segmented button it resolved to: 
--_ui5-v**1-23-2**_segmented_btn_items_count 
(which seems to be the right scoping).

Could you please have a look?

Regards,
Dobrin

**Comment by ilhan007** [comment]
Hi @ej612 
the 1.23.2 has not been properly built, we are working on new patch, we will update you shortly

**Comment by ilhan007** [comment]
Hi @ej612 can you try 1.23.3
