### ISSUE TITLE
[ui5-step-input] height and margins are not corerct

### ISSUE THREAD

**Issue by MapTo0** [SAP/ui5-webcomponents#8667]
### Bug Description

Hello colleagues,

The size and margins of the step input host element should be the same as other inputs.
When having a line with all inputs all should be centered.

https://tinyurl.com/yez9nx6j

### Expected Behaviour

all inputs are on the same line

### Isolated Example

https://tinyurl.com/yez9nx6j

### Steps to Reproduce

1. Open https://tinyurl.com/yez9nx6j

### Priority

Medium

### UI5 Web Components Version

latest

### Browser

Chrome, Edge, Firefox, Safari

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by dobrinyonkov** [comment]
Hello @SAP/ui5-webcomponents-topic-b,

Coud you please check the styles of the step input? Its hight needs to be aligned with the other input components. 

Kind Regarsd,
Dobrin
