### ISSUE TITLE
Wizard: Screen readers reads wizard as "wizard progress bar"

### ISSUE THREAD

**Issue by samanr** [SAP/ui5-webcomponents#8673]
### Describe the bug

When using JAWS and NVDA screen readers with the focus on wizard component,  it reads as "wizard region wizard progress bar" instead of only wizard. The progress bar can be misleading or rather confusing for the users because of ProgressIndicator component.

### Isolated Example

https://stackblitz.com/edit/github-mseb8i?file=src%2FApp.tsx

### Reproduction steps

1. Add a Wizard and 2 wizard steps
2. Use JAWS 2023 or NVDA screen reader
3. Focus on the first step of the wizard.

### Expected Behaviour

As the wizard given in the form is not a progress bar, it is advised to remove it as it provided ambiguity to the screen reader users 

### Screenshots or Videos

<img width="466" alt="Screenshot 2024-04-05 at 12 05 35 PM" src="https://github.com/SAP/ui5-webcomponents-react/assets/22089053/295648ce-69c4-47de-bd2c-1b356da7c4a7">
-a953-256ea0b5974a">

### UI5 Web Components for React Version

1.20.0

### UI5 Web Components Version

1.18.0

### Browser

Chrome

### Operating System

Windows

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by petyabegovska** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

Can you validate with your ACC expert? Currently, the component is implemented correctly as per the ACC specification with aria-label = "Wizard Progress Bar" on <nav> but the author finds it confusing with the progress indicator.

Best regards,
Petya

**Comment by ivoplashkov** [comment]
Hello @samanr,

Thank you for reaching out!

We have discussed this with our ACC experts and came to a conclusion that this is the expected behavior and according to the specifications. It's announcing "Progress bar" as the Wizard navigator shows the progress the user has achieved while navigating through the steps. We do not consider this to be misleading.

Best regards,
Ivaylo
