### ISSUE TITLE
SAP Logo has been removed from the public Assets

### ISSUE THREAD

**Issue by Rabuske** [SAP/ui5-webcomponents#8689]
### Bug Description

Hello, my team uses ui5 web components to develop internal applications for SAP. We noticed that since a couple of weeks ago, the SAP log has been missing from the shell bar because the asset has been removed from https://sap.github.io/ui5-webcomponents/assets/images/sap-logo-svg.svg.

Perhaps we should not have relied on external assets for this, but currently all applications are displaying a broken image. 
Is it possible to restore these assets? 

![image](https://github.com/SAP/ui5-webcomponents/assets/10622097/ae1ec55f-b4ee-4194-83aa-9e0580d4eae0)

### Affected Component

Shell bar

### Expected Behaviour

The SAP Logo should be loaded from the assets.

### Steps to Reproduce

1. Follow the documentation for the shell bar (https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-shellbar--docs)
2. Check that the logo will not be displayed correctly

### Priority

High

### UI5 Web Components Version

Any version that uses the above-mentioned asset

### Browser

Chrome

### Additional Context

The docs is broken as well: https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-shellbar--docs

### Organization

SAP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ilhan007** [comment]
Yes, It's best to use your own assets and not rely on our URLs.
The logo is now deployed to https://sap.github.io/ui5-webcomponents/images/sap-logo-svg.svg
