### ISSUE TITLE
SideNavigationItem: click event is triggered twice.

### ISSUE THREAD

**Issue by sachinbhutani** [SAP/ui5-webcomponents#8692]
### Bug Description

Side navigation item click event is triggered twice, due to which function like toggling sidebar using sidebar navigation item is not possible.

### Affected Component

ui5-side-navigation-item

### Expected Behaviour

click event should be triggered only once 

### Isolated Example

https://sap.github.io/ui5-webcomponents/nightly/play/#eyJpbmRleC5odG1sIjp7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuPCFET0NUWVBFIGh0bWw-XG48aHRtbCBsYW5nPVwiZW5cIj5cblxuXG5cbjxoZWFkPlxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG4gICAgPC9zdHlsZT5cblxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG4gICAgPC9zdHlsZT5cblxuICAgIDxtZXRhIGNoYXJzZXQ9XCJVVEYtOFwiPlxuICAgIDxtZXRhIG5hbWU9XCJ2aWV3cG9ydFwiIGNvbnRlbnQ9XCJ3aWR0aD1kZXZpY2Utd2lkdGgsIGluaXRpYWwtc2NhbGU9MS4wXCI-XG4gICAgPHRpdGxlPlNhbXBsZTwvdGl0bGU-XG4gICAgPGxpbmsgcmVsPVwic3R5bGVzaGVldFwiIGhyZWY9XCIuL21haW4uY3NzXCI-XG48L2hlYWQ-XG5cbjxib2R5IHN0eWxlPVwiYmFja2dyb3VuZC1jb2xvcjogdmFyKC0tc2FwQmFja2dyb3VuZENvbG9yKVwiPlxuICAgIDwhLS0gcGxheWdyb3VuZC1mb2xkLWVuZCAtLT5cblxuXG4gICAgPGRpdiBjbGFzcz1cInRvb2wtbGF5b3V0XCI-XG4gICAgICAgIDx1aTUtc2hlbGxiYXIgcHJpbWFyeS10aXRsZT1cIlByb2R1Y3QgTmFtZVwiIHNlY29uZGFyeS10aXRsZT1cIlNlY29uZCBUaXRsZVwiIG5vdGlmaWNhdGlvbnMtY291bnQ9XCIxXCJcbiAgICAgICAgICAgIHNob3ctbm90aWZpY2F0aW9ucz5cbiAgICAgICAgICAgIDxpbWcgc2xvdD1cImxvZ29cIiBzcmM9XCJodHRwczovL3NhcC5naXRodWIuaW8vdWk1LXdlYmNvbXBvbmVudHMvbmlnaHRseS9pbWFnZXMvc2FwLWxvZ28tc3ZnLnN2Z1wiIC8-XG4gICAgICAgICAgICA8dWk1LWlucHV0IHNsb3Q9XCJzZWFyY2hGaWVsZFwiPjwvdWk1LWlucHV0PlxuICAgICAgICAgICAgPHVpNS1hdmF0YXIgc2xvdD1cInByb2ZpbGVcIj5cbiAgICAgICAgICAgICAgICA8aW1nIHNyYz1cImh0dHBzOi8vc2FwLmdpdGh1Yi5pby91aTUtd2ViY29tcG9uZW50cy9uaWdodGx5L2ltYWdlcy9hdmF0YXJzL3dvbWFuX2F2YXRhcl81LnBuZ1wiIC8-XG4gICAgICAgICAgICA8L3VpNS1hdmF0YXI-XG4gICAgICAgICAgICA8dWk1LXNoZWxsYmFyLWl0ZW0gaWNvbj1cInNvdXJjZS1jb2RlXCIgdGV4dD1cIlNldHRpbmdzXCIgdGl0bGU9XCJTZXR0aW5nc1wiPjwvdWk1LXNoZWxsYmFyLWl0ZW0-XG4gICAgICAgICAgICA8dWk1LXNoZWxsYmFyLWl0ZW0gaWNvbj1cImJhY2tncm91bmRcIiB0ZXh0PVwiU2V0dGluZ3NcIiB0aXRsZT1cIlNldHRpbmdzXCI-PC91aTUtc2hlbGxiYXItaXRlbT5cbiAgICAgICAgICAgIDx1aTUtc2hlbGxiYXItaXRlbSBpY29uPVwiYWN0aXZpdHktYXNzaWduZWQtdG8tZ29hbFwiIHRleHQ9XCJTZXR0aW5nc1wiIHRpdGxlPVwiU2V0dGluZ3NcIj48L3VpNS1zaGVsbGJhci1pdGVtPlxuICAgICAgICAgICAgPHVpNS1zaGVsbGJhci1pdGVtIGljb249XCJhY3Rpb24tc2V0dGluZ3NcIiB0ZXh0PVwiU2V0dGluZ3NcIiB0aXRsZT1cIlNldHRpbmdzXCI-PC91aTUtc2hlbGxiYXItaXRlbT5cbiAgICAgICAgPC91aTUtc2hlbGxiYXI-XG4gICAgICAgIDx1aTUtc2lkZS1uYXZpZ2F0aW9uPlxuICAgICAgICAgICAgPHVpNS1zaWRlLW5hdmlnYXRpb24taXRlbSB0ZXh0PVwiVG9nZ2xlIE1lXCIgaWNvbj1cIm1lbnVcIiBpZD1cInRvZ2dsZVwiPjwvdWk1LXNpZGUtbmF2aWdhdGlvbi1pdGVtPlxuICAgICAgICAgICAgPHVpNS1zaWRlLW5hdmlnYXRpb24taXRlbSB0ZXh0PVwiUGVvcGxlXCIgZXhwYW5kZWQgaWNvbj1cImdyb3VwXCI-XG4gICAgICAgICAgICAgICAgPHVpNS1zaWRlLW5hdmlnYXRpb24tc3ViLWl0ZW0gdGV4dD1cIkZyb20gTXkgVGVhbVwiPjwvdWk1LXNpZGUtbmF2aWdhdGlvbi1zdWItaXRlbT5cbiAgICAgICAgICAgICAgICA8dWk1LXNpZGUtbmF2aWdhdGlvbi1zdWItaXRlbSB0ZXh0PVwiRnJvbSBPdGhlciBUZWFtXCI-PC91aTUtc2lkZS1uYXZpZ2F0aW9uLXN1Yi1pdGVtPlxuICAgICAgICAgICAgPC91aTUtc2lkZS1uYXZpZ2F0aW9uLWl0ZW0-XG4gICAgICAgICAgICA8dWk1LXNpZGUtbmF2aWdhdGlvbi1pdGVtIHRleHQ9XCJMb2NhdGlvbnNcIiBpY29uPVwibG9jYXRlLW1lXCIgc2VsZWN0ZWQ-PC91aTUtc2lkZS1uYXZpZ2F0aW9uLWl0ZW0-XG4gICAgICAgICAgICA8dWk1LXNpZGUtbmF2aWdhdGlvbi1pdGVtIHRleHQ9XCJFdmVudHNcIiBpY29uPVwiY2FsZW5kYXJcIj5cbiAgICAgICAgICAgICAgICA8dWk1LXNpZGUtbmF2aWdhdGlvbi1zdWItaXRlbSB0ZXh0PVwiTG9jYWxcIj48L3VpNS1zaWRlLW5hdmlnYXRpb24tc3ViLWl0ZW0-XG4gICAgICAgICAgICAgICAgPHVpNS1zaWRlLW5hdmlnYXRpb24tc3ViLWl0ZW0gdGV4dD1cIk90aGVyc1wiPjwvdWk1LXNpZGUtbmF2aWdhdGlvbi1zdWItaXRlbT5cbiAgICAgICAgICAgICAgICA8dWk1LXNpZGUtbmF2aWdhdGlvbi1zdWItaXRlbSB0ZXh0PVwiRXh0ZXJuYWwgTGlua1wiIGhyZWY9XCJodHRwczovL3NhcC5jb21cIiB0YXJnZXQ9XCJfYmxhbmtcIj5cblx0XHRcdFx0PC91aTUtc2lkZS1uYXZpZ2F0aW9uLXN1Yi1pdGVtPlxuICAgICAgICAgICAgPC91aTUtc2lkZS1uYXZpZ2F0aW9uLWl0ZW0-XG5cdFx0XHQ8dWk1LXNpZGUtbmF2aWdhdGlvbi1pdGVtIHNsb3Q9XCJmaXhlZEl0ZW1zXCIgdGV4dD1cIlVzZWZ1bCBMaW5rc1wiIGljb249XCJjaGFpbi1saW5rXCI-XG5cdFx0XHRcdDx1aTUtc2lkZS1uYXZpZ2F0aW9uLXN1Yi1pdGVtIHRleHQ9XCJFeHRlcm5hbCBMaW5rXCIgaHJlZj1cImh0dHBzOi8vc2FwLmNvbVwiIHRhcmdldD1cIl9ibGFua1wiPlxuXHRcdFx0XHQ8L3VpNS1zaWRlLW5hdmlnYXRpb24tc3ViLWl0ZW0-XG5cdFx0XHQ8L3VpNS1zaWRlLW5hdmlnYXRpb24taXRlbT5cblx0XHRcdDx1aTUtc2lkZS1uYXZpZ2F0aW9uLWl0ZW0gc2xvdD1cImZpeGVkSXRlbXNcIiB0ZXh0PVwiSGlzdG9yeVwiIGljb249XCJoaXN0b3J5XCIgPlxuXHRcdFx0PC91aTUtc2lkZS1uYXZpZ2F0aW9uLWl0ZW0-XG4gICAgICAgIDwvdWk1LXNpZGUtbmF2aWdhdGlvbj5cbiAgICAgICAgPGRpdiBjbGFzcz1cImNvbnRlbnRcIj48L2Rpdj5cbiAgICA8L2Rpdj5cbiAgICA8IS0tIHBsYXlncm91bmQtZm9sZCAtLT5cbiAgICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCJtYWluLmpzXCI-PC9zY3JpcHQ-XG48L2JvZHk-XG5cbjwvaHRtbD5cbjwhLS0gcGxheWdyb3VuZC1mb2xkLWVuZCAtLT5cbiJ9LCJtYWluLmpzIjp7Im5hbWUiOiJtYWluLmpzIiwiY29udGVudCI6Ii8qIHBsYXlncm91bmQtaGlkZSAqL1xuaW1wb3J0IFwiLi9wbGF5Z3JvdW5kLXN1cHBvcnQuanNcIjtcbi8qIHBsYXlncm91bmQtaGlkZS1lbmQgKi9cbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L0J1dHRvbi5qc1wiO1xuXG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMtZmlvcmkvZGlzdC9TaWRlTmF2aWdhdGlvbi5qc1wiO1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzLWZpb3JpL2Rpc3QvU2lkZU5hdmlnYXRpb25JdGVtLmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMtZmlvcmkvZGlzdC9TaWRlTmF2aWdhdGlvblN1Ykl0ZW0uanNcIjtcbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy1maW9yaS9kaXN0L1NoZWxsQmFyLmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMtZmlvcmkvZGlzdC9TaGVsbEJhckl0ZW0uanNcIjtcblxuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzLWljb25zL2Rpc3QvaG9tZS5qc1wiO1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzLWljb25zL2Rpc3QvZ3JvdXAuanNcIjtcbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy1pY29ucy9kaXN0L21lbnUuanNcIjtcbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy1pY29ucy9kaXN0L2xvY2F0ZS1tZS5qc1wiO1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzLWljb25zL2Rpc3QvY2FsZW5kYXIuanNcIjtcbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy1pY29ucy9kaXN0L2hpc3RvcnkuanNcIjtcbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy1pY29ucy9kaXN0L3NvdXJjZS1jb2RlLmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMtaWNvbnMvZGlzdC9iYWNrZ3JvdW5kLmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMtaWNvbnMvZGlzdC9hY3Rpdml0eS1hc3NpZ25lZC10by1nb2FsLmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMtaWNvbnMvZGlzdC9hY3Rpb24tc2V0dGluZ3MuanNcIjtcbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy1pY29ucy9kaXN0L2NoYWluLWxpbmsuanNcIjtcblxudmFyIHNpZGVuYXYgPSBkb2N1bWVudC5xdWVyeVNlbGVjdG9yKFwidWk1LXNpZGUtbmF2aWdhdGlvblwiKTtcbmRvY3VtZW50LmdldEVsZW1lbnRCeUlkKFwidG9nZ2xlXCIpLmFkZEV2ZW50TGlzdGVuZXIoXCJjbGlja1wiLCAoKSA9PiB7XG4gICBjb25zb2xlLmxvZyhcIlNpZGVOYXYgaXRlbSBDbGljayBFdmVudCB0cmlnZ2VyZWRcIik7XG4gICAgc2lkZW5hdi50b2dnbGVBdHRyaWJ1dGUoXCJjb2xsYXBzZWRcIik7XG59KTsifSwibWFpbi5jc3MiOnsibmFtZSI6Im1haW4uY3NzIiwiY29udGVudCI6InVpNS1zaWRlLW5hdmlnYXRpb24ge1xuICAgIGhlaWdodDogNjAwcHg7XG59XG5cbnVpNS1zaGVsbGJhcjo6cGFydChyb290KSB7XG4gICAgcGFkZGluZy1pbmxpbmUtc3RhcnQ6IDAuNzVyZW07XG4gICAgcGFkZGluZy1pbmxpbmUtZW5kOiAxLjI1cmVtO1xuICAgIGJvcmRlci1yYWRpdXM6IDAuNXJlbTtcbiAgICBib3gtc2hhZG93OlxuICAgICAgICAwIDAgMC4xMjVyZW0gMCBjb2xvci1taXgoaW4gc3JnYiwgdmFyKC0tc2FwQ29udGVudF9TaGFkb3dDb2xvcikgMTYlLCB0cmFuc3BhcmVudCksXG4gICAgICAgIDAgMC41cmVtIDFyZW0gMCBjb2xvci1taXgoaW4gc3JnYiwgdmFyKC0tc2FwQ29udGVudF9TaGFkb3dDb2xvcikgMTYlLCB0cmFuc3BhcmVudCk7XG59XG5cbi50b29sLWxheW91dCB7XG4gICAgcGFkZGluZzogMC41cmVtIDAuNXJlbSAwIDAuNXJlbTtcbiAgICBiYWNrZ3JvdW5kOiBjb2xvci1taXgoaW4gc3JnYiwgYmxhY2sgNCUsIHZhcigtLXNhcEJhY2tncm91bmRDb2xvcikpO1xuICAgIGRpc3BsYXk6IGdyaWQ7XG4gICAgZ2FwOiAwLjVyZW07XG4gICAgZ3JpZC10ZW1wbGF0ZS1yb3dzOiBhdXRvIDFmcjtcbiAgICBncmlkLXRlbXBsYXRlLWNvbHVtbnM6IGF1dG8gMWZyO1xufVxuXG51aTUtc2hlbGxiYXIge1xuICAgIGdyaWQtY29sdW1uOiAxIC8gc3BhbiAyO1xuICAgIGdyaWQtcm93OiAxIC8gMjtcbn1cblxuLmNvbnRlbnQge1xuICAgIHBvc2l0aW9uOiByZWxhdGl2ZTtcbiAgICBiYWNrZ3JvdW5kOiB2YXIoLS1zYXBCYWNrZ3JvdW5kQ29sb3IpO1xuICAgIGJvcmRlci1yYWRpdXM6IDAuNXJlbSAwLjVyZW0gMCAwO1xuICAgIGJveC1zaGFkb3c6XG4gICAgICAgIDAgMCAwLjEyNXJlbSAwIGNvbG9yLW1peChpbiBzcmdiLCB2YXIoLS1zYXBDb250ZW50X1NoYWRvd0NvbG9yKSAxNiUsIHRyYW5zcGFyZW50KSxcbiAgICAgICAgMCAwLjVyZW0gMXJlbSAwIGNvbG9yLW1peChpbiBzcmdiLCB2YXIoLS1zYXBDb250ZW50X1NoYWRvd0NvbG9yKSAxNiUsIHRyYW5zcGFyZW50KTtcbn0ifX0

### Steps to Reproduce

1. click on "Toggle Me" option in the side navigation and check console log. 
2. Sidebar is not getting toggled as toggle is called twice due to two click events.

### Priority

None

### UI5 Web Components Version

1.24.0

### Browser

Edge

### Operating System

Windows 11

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by niyap** [comment]
Hello @SAP/ui5-webcomponents-topic-rd,

Using the provided sample, the "click" event is fired twice as described.
If we listen for "ui5-click", then it is fired only once and the side navigation is collapsed as expected.

Could you please check the issue?

Kind Regards,
Niya
