### ISSUE TITLE
BarcodeScannerDialog: add `close` event

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#8695]
### Feature Request Description

With v1.24.0 the `open` property was introduced and the `show` and `close` methods were deprecated. 

In React it's common to fully control a component, but since there are no events exposed if the dialog is closed, this is not possible.

E.g.:
- Go to [StackBlitz](https://stackblitz.com/edit/github-j6dzzf?file=src%2FApp.tsx,package.json)
- Open the `BarcodeScannerDialog` by clicking the respective button (React state `open` is set to `true`)
- Close the dialog by pressing ESC or the "Cancel" button
- Since there is no (public) way to register to a "close" event, the `open` state stays `true`.

So if I didn't miss something, the dialog is currently not usable without deviating from the standard of how to control components in React, or using deprecated methods.

On a side note, your [example](https://sap.github.io/ui5-webcomponents/components/fiori/BarcodeScannerDialog) still uses the deprecated methods.

### Proposed Solution

Expose the close events of the `Dialog` or add a custom close event specific to this component.

### Organization

UI5WCR

### Priority

None

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by petyabegovska** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

Please check the request and also update the sample not to use deprecated api.

Best regards,
Petya

**Comment by vladitasev** [comment]
Hi @Lukas742 
We've added a `close` event and we've also refactored the component to use completely declarative APIs: https://github.com/SAP/ui5-webcomponents/pull/8760.

Should be easier for you overall - just bind the `open` property and listen for the `close` event

Regards,
Vladi
