### ISSUE TITLE
[SF][A11y][ui5-card-header]: Need customize heading level

### ISSUE THREAD

**Issue by i323808** [SAP/ui5-webcomponents#8697]
### Bug Description

The heading level is hard-coded as level 3. We need customize the heading level according to the heading hierarchy of the whole page. For instance, the card title level should be 4 instead of 3 on our page.
<img width="854" alt="card_header_level" src="https://github.com/SAP/ui5-webcomponents/assets/30744017/28b30b91-6f75-4bc3-bd34-763451b46665">

### Expected Behaviour

The heading level of CardHeader is supposed to be configurable.

### Steps to Reproduce

1.
2.
3.
...

### Priority

Medium

### UI5 Web Components Version

1.24.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by niyap** [comment]
Hello @SAP/ui5-webcomponents-topic-rd,

Could you please check that feature request?
The reporter wants a customisable card header title level in order to achieve desired  hierarchy of his whole application without duplicate levels as well as jumps between them.

Thank you in advance!

Kind Regards,
Niya

**Comment by olannyv** [comment]
Hi, @i323808 
According to the Inner Source Design process, this is a "New Feature Request" (that is to create on Jira item) 
Please file in one as described here (I will provide the link in the chat)

**Comment by GerganaKremenska** [comment]
Hello @i323808,

Since there is no action on our side util design is provided i am closing the issue.

Best Regards,
Gergana
