### ISSUE TITLE
[ui5-multicombobox]: incorrect valuestate behavior + focus handling

### ISSUE THREAD

**Issue by ivoplashkov** [SAP/ui5-webcomponents#8701]
### Bug Description

There is an issue with the valueState popover:

1. When the user navigates to a multicombobox with valuestate popover using Tab and Shift + Tab, you may notice that at some point there are two Popover opened and the focus goes the Popover, which is unexpected. Please refer to the video:

https://github.com/SAP/ui5-webcomponents/assets/23635149/8bc89e11-4b41-4c24-b87a-2e15655038ba

 

### Expected Behaviour

Only one Popover is opened at a time and the focus, should not go the popover if there is no focusable item.

### Priority

None

### UI5 Web Components Version

2.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ndeshev** [comment]
I am no longer able to reproduce the problem, I'm closing the issue.
