### ISSUE TITLE
[ui5-split-button]: component breaks if container has fixed height

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#8705]
### Bug Description

When the `SplitButton` is mounted inside an container with a fixed height, it spreads to the available height, which results in breaking the layout of the component.

Setting `height: auto;` fixes the issue, but imo this shouldn't be necessary.

### Affected Component

SplitButton

### Expected Behaviour

The SplitButton should keep its dimensions if not defined otherwise.

### Isolated Example

https://stackblitz.com/edit/js-atedm9?file=index.html

### Steps to Reproduce

1. Go to [StackBlitz](https://stackblitz.com/edit/js-atedm9?file=index.html)
2. See that the first SplitButton looks broken

### Priority

None

### UI5 Web Components Version

1.24.0

### Browser

Chrome

### Organization

MXP & UI5WCR

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by niyap** [comment]
Hello @SAP/ui5-webcomponents-topic-b,

Could you please check the description and provided sample and analyse whether that result is expected when setting height: auto to the SplitButton when placed within a container with bigger and fixed height?

Thank you in advance!

Kind Regards,
Niya
