### ISSUE TITLE
[SF][MultiInput]: Backspace does not work when the property set with type="Number" or "Email"

### ISSUE THREAD

**Issue by AuroArea** [SAP/ui5-webcomponents#8712]
### Describe the bug

The MultiInput component for UI5 React, does not work for Backspace key, when the property type=Number or type=Email is used.

### Reproduction steps

1. Go to documentation page - https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-multiinput--docs
2. In the example section, select the input box and try pressing Backspace button, we can see that the tokens are focussed, so that they can be removed.
3. Now change the dropdown value of the property "type" from Text to "Number" and repeat the above step for backspace, nothing happens. 
4. Tokens are not selected/focussed to take any action

### Expected Behaviour

Backspace behaviour should work same for all the "type" properties like it works for type="Text".

### UI5 Web Components for React Version

1.27.0

### UI5 Web Components Version

Latest

### Browser

Chrome

### Organization

SAP Successfactors

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by niyap** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

Could you please take a look of that findings?
If we have MultiInput with type="Number" or "Email" (with the other types it works as expected), the keyboard navigation does not work as expected.
Please, check the sample: https://sap.github.io/ui5-webcomponents/components/MultiInput (Add/Remove Tokens). Add some tokens and change the type property to Number or Email. Try to delete the tokens via Backspace -> nothing happens.
Thank you in advance!

Kind Regards,
Niya
