### ISSUE TITLE
Accessibility features for Menu Items

### ISSUE THREAD

**Issue by maddel** [SAP/ui5-webcomponents#8715]
### Feature Request Description

Within Work Zone we will use the Menu Web Component (for React) to show a context menu.

We have Menu Items that show a shortcut for some actions. To announce the shortcut we need the aria-shortcuts attribute on the focussed menu item (shadow dom) LI element.
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-keyshortcuts

Additionally some Menu Items will need more specific role as they act as a checkbox or radiobutton (not in screenshot)
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/menuitemcheckbox_role
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/menuitemradio_role

<img width="393" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/7780341/7485c8e4-a607-43eb-8d9f-f6984b0f4a40">

### Proposed Solution

Add additional attibute to maintain the aria-shortcut on Menu Item
Add additional attribute role (defaults to menuitem as today) to also maintain the menuitemcheckbox and menuitemradio values.

### Proposed Alternatives

As modification of shadow dom elements is not possible and the focus is not set on the menuitem (tag) itselft there is no know alternative to achieve the ACC behavior that is expected.

### Organization

SAP

### Priority

None

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by petyabegovska** [comment]
Hello @SAP/ui5-webcomponents-topic-b,

Please have a look at this feature request.

Best regards,
Petya

**Comment by DMihaylova** [comment]
Hi @maddel,

The request is now internally logged as BGSOFUIBALKAN-8194, and we'll promptly notify you once it's been addressed.

Thanks & Regards,
Diana

**Comment by DMihaylova** [comment]
Fixed by https://github.com/SAP/ui5-webcomponents/pull/9333
