### ISSUE TITLE
ui5-side-navigation: the ui5-navigation-menu doesn't open in collapsed mode

### ISSUE THREAD

**Issue by unazko** [SAP/ui5-webcomponents#8739]
### Bug Description

The ui5-navigation menu doesn't open in collapsed mode the first time due to an error in the console.
There is no opener element set according to the error.
Additionally on a second try to open the submenu it opens, but it takes the whole available space and there are no menu items
displayed.

In order to reproduce the issue please open the following URL on locale machine:
1) http://localhost:8080/packages/fiori/test/pages/SideNavigationOnly.html
2) Press the collapsed checkbox
3) Press the three dot button in the side navigation

Observe the error in the console:
![SideNavigation](https://github.com/SAP/ui5-webcomponents/assets/15860295/df80a370-83db-403f-a6c6-aec957c1a9c0)

4) Press the three dot button again:
![NavigationMenu](https://github.com/SAP/ui5-webcomponents/assets/15860295/1ce50ced-e0b8-451b-a422-58066a270dc5)

Observe that it takes the whole available space and there are no menu items displayed.

### Affected Component

ui5-side-navigation

### Expected Behaviour

The expected behavior would be to open a navigation menu with properly displayed items on a first try.

### Steps to Reproduce

1) http://localhost:8080/packages/fiori/test/pages/SideNavigationOnly.html
2) Press the collapsed checkbox
3) Press the three dot button in the side navigation
4) Press the three dot button again

### Priority

None

### UI5 Web Components Version

latest

### Browser

Chrome

### Operating System

Windows

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by unazko** [comment]
Hello @SAP/ui5-webcomponents-topic-rd,

Please checkout this issue for the `ui5-side-navigation` component.

Best regards,
Boyan

**Comment by dimovpetar** [comment]
Hello @unazko,

Width issue is fixed with https://github.com/SAP/ui5-webcomponents/pull/8940.
Error is fixed with https://github.com/SAP/ui5-webcomponents/pull/8812.

Best regards,
Petar
