### ISSUE TITLE
ui5-menu-item: icon is not displayed when component is scoped.

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#8745]
### Bug Description

If custom element scoping is applied, the icon of the `MenuItem` is not displayed. 

Please let me know if there's a workaround we can use, because this is currently blocking updating ui5wc to the latest version in our app.

### Steps to Reproduce

1. Go to [StackBlitz](https://stackblitz.com/edit/js-zwean6?file=index.js,index.html)
2. Open the Menu
3. See that there are no icons displayed

### Priority

High

### UI5 Web Components Version

1.24.0

### Browser

Chrome, Edge, Firefox, Safari

### Organization

MXP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by niyap** [comment]
Hello @SAP/ui5-webcomponents-topic-b,

The issue could be easily reproduced with the sample provided by Lukas.
Could you please look over and analyse why the icons are not visible when custom element is used?

Thank you in advance!

Kind Regards,
Niya

**Comment by Lukas742** [comment]
I've created a PR that should fix the issue.
