### ISSUE TITLE
[Rich-Text-Editor]: Text entered is not passed to the consumer if input by paste

### ISSUE THREAD

**Issue by saurabhmehta02** [SAP/ui5-webcomponents#8754]
### Bug Description

If we copy-paste simple text say "Hello SAP" (without double quotes) in the rich-text-editor component, the value is not passed to the consumer through onInput event.
However it works fine if simple text is entered by typing instead of copy-paste.

Also, if we copy-paste rich text in the rich-text-editor component, the onInput event is getting invoked so issue is only when simple text is entered by paste.

### Affected Component

Rich-Text-Editor

### Expected Behaviour

The simple text entered using copy paste should be available through onInput event

### Priority

High

### UI5 Web Components Version

0.6.0

### Browser

Chrome, Edge, Firefox, Safari

### Organization

SAP Labs

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by hristop** [comment]
Hi @saurabhmehta02 ,

Can you move this to the correct project, please? 

Best Regards,
Hristo

**Comment by saurabhmehta02** [comment]
Closing this defect, will raise new defect in the correct project.
