### ISSUE TITLE
[ui5-dialog]: Small icon when dialog title is too long

### ISSUE THREAD

**Issue by kozubikmichal** [SAP/ui5-webcomponents#8762]
### Bug Description

When the dialog title gets truncated because of it's length, the status icon in the dialog header is shrinked

### Affected Component

ui5-dialog

### Expected Behaviour

Icon stays the same size no matter how long the dialog title is.

### Isolated Example

https://stackblitz.com/edit/js-1ndywy?file=index.html

### Steps to Reproduce

1. Open the first dialog with short title - icon size is normal
2. Open the second dialog with long title - icon is shrinked

### Log Output, Stack Trace or Screenshots

![image](https://github.com/SAP/ui5-webcomponents/assets/26189327/fd9da79d-b3d4-4768-b641-d753bb98fe52)

### Priority

None

### UI5 Web Components Version

1.24.0

### Browser

Chrome

### Organization

SAP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by dimovpetar** [comment]
Hello @SAP/ui5-webcomponents-topic-rd ,

`flex-shrink: 0` on the icon would help here.

Best regards,
Petar
