### ISSUE TITLE
ui5-menu: runtime error

### ISSUE THREAD

**Issue by vladitasev** [SAP/ui5-webcomponents#8764]
### Bug Description

1.Run the project locally

2. Click "Open Menu" -> Open -> Open Locally -> Open from C

3. There is a runtime error

<img width="874" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/15844574/010274ac-0b18-446f-9207-0814921f8622">

### Steps to Reproduce

1.
2.
3.
...

### Priority

High

### UI5 Web Components Version

2.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by vladitasev** [comment]
@unazko @tsanislavgatev Please have a look

I debugged a bit. When the error occurs:
<img width="643" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/15844574/b22c9149-4ef8-48b5-b5bf-7731baf99e39">

I manually followed the DOM and found out that:
<img width="897" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/15844574/cf29d4b1-3b61-4400-ab45-42eaa4047b03">

**Comment by unazko** [comment]
Hello @vladitasev,

This issue only happens as the busy state of the `ui5-menu-item` is broken after changing the names of the `busy` and `busyDelay` to "loading" and "loadingDelay" in the `ui5-list`.  I suspect that we open the sub-menu from the current item. Later the same item gets re-rendered after two additional items are being added.

The same issue isn't reproducible via the following PR: https://github.com/SAP/ui5-webcomponents/pull/8722
I'll take only the needed part from the PR as this is a refactoring.

Best regards,
Boyan

**Comment by vladitasev** [comment]
Thanks for the quick fix! I've approved the PR. 

When the colleagues merged the change to `ui5-list` (renaming of these properties) all menu tests were still passing, meaning there's no test covering the usage of this property. This is something to be improved in the future.
