### ISSUE TITLE
[ui5-upload-collection-item]: Hide (or not show) progress bar and information

### ISSUE THREAD

**Issue by henriquemattos** [SAP/ui5-webcomponents#8771]
### Bug Description

Hi, team. I'm using the `<ui5-upload-collection>` to create a browser-based gallery, in combination with `<ui5-media-gallery>`, and since this is a client feature, there's little to no latency in selecting/dropping files to upload and showing them in the gallery, making the progress area completely useless. I can hide the buttons retry and terminate, but I can't hide the whole progress area. Would it be possible to have a boolean `showProgress`?

### Affected Component

ui5-upload-collection-item

### Expected Behaviour

Progress area is not displayed when developer does not need it.

### Steps to Reproduce

1.
2.
3.
...

### Priority

Low

### UI5 Web Components Version

1.20

### Browser

Chrome, Edge, Firefox, Safari

### Organization

SAP Event Ticketing

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by dimovpetar** [comment]
Hello @ui5-webcomponents-topic-rd,

Documentation of `uploadState` property could be improved. Currently, it only mentions "Error" and "Uploading" states and nothing about "Ready" and "Complete".

Best regards,
Petar

**Comment by henriquemattos** [comment]
Thank you, team. That's very nice and helpful :) I appreciate the speed and direction of UI5WC, it helps a lot internally to move applications to Fiori compliance.
