### ISSUE TITLE
[ui5-side-navigation-item]: JAWS reads navigation item name twice if containing ui5-side-navigation-sub-item

### ISSUE THREAD

**Issue by f16r** [SAP/ui5-webcomponents#8784]
### Bug Description

JAWS reads navigation item name twice if ui5-side-navigation-item is containing ui5-side-navigation-sub-item.

Example from documentation:
![image](https://github.com/SAP/ui5-webcomponents/assets/37051913/9945add9-3eaf-4d1d-bc99-e7ff4baf288f)
https://sap.github.io/ui5-webcomponents/components/fiori/SideNavigation/

### Affected Component

ui5-side-navigation-item

### Expected Behaviour

Navigation Item name is only read once.

### Priority

Medium

### UI5 Web Components Version

1.24.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by dimovpetar** [comment]
Hello @ui5-webcomponents-topic-rd,

Looks like JAWS reads the `aria-label` of the group while the focus is on the root item. Most likely a JAWS issue, but please double check it.

Best regards,
Petar
