### ISSUE TITLE
[ui5-side-navigation-item]: JAWS reads "selected" on every item on focus

### ISSUE THREAD

**Issue by f16r** [SAP/ui5-webcomponents#8790]
### Bug Description

I do understand that the actual selected item will be announced with "Current Page" but it is misleading that JAWS reads "selected" on every navigation item that reaches focus.

![image](https://github.com/SAP/ui5-webcomponents/assets/37051913/fee1fd0b-ebe7-44f2-8f5d-28731289e02e)
https://sap.github.io/ui5-webcomponents/components/fiori/SideNavigation/

### Affected Component

ui5-side-navigation

### Expected Behaviour

E.g. "To navigate press enter" instead of "selected" if the navigation item is not for the current page.

### Priority

Medium

### UI5 Web Components Version

1.24.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by dimovpetar** [comment]
Hello @f16r,

This seems like a JAWS issue. The same can be observed at this example https://www.w3.org/WAI/ARIA/apg/patterns/treeview/examples/treeview-navigation/#ex_label
I have reported this issue to Freedom Scientific with https://github.com/FreedomScientific/standards-support/issues/824. Please track the progress there.

Best regards,
Petar

**Comment by f16r** [comment]
@dimovpetar will you reopen this issue after the latest feedback in https://github.com/FreedomScientific/standards-support/issues/824?

**Comment by dimovpetar** [comment]
Hello @f16r,

We are still investigating what is the correct behavior. I am reopening the ticket.

Best regards,
Petar

**Comment by dimovpetar** [comment]
Hello @f16r,

This issue is fixed in the main branch and will be downported to 1.24 with https://github.com/SAP/ui5-webcomponents/pull/9037.

Best regards,
Petar
