### ISSUE TITLE
ShellBar: How to use an Icon for having a back button

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents#884]
**Describe the bug**
The `onPress`/`onClick` event has been removed from the `Icon` component.
After this change, we are unable to use the "back/home button" in the ShellBar - or we would have to use a button which looks somehow strange.

**To reproduce**
1. Render a ShellBar
2. Put an Icon in the icon slot
3. Try to click it --> No click event
4. place a transparent button as icon - looks strange (please see code sandbox example)

I know that I could add a listener for the `click` event to the icon although it is not officially supported. This approach isn't working for `ui5-webcomponents-react` because we are relying on the component metadata.

**Isolated example**
https://codesandbox.io/s/ui5-webcomponents-7s58p?fontsize=14

**Expected behavior**
I see three options:
1. Add a click event to the `Icon` again.
2. Fix styling when using a `Button` as icon
3. Use another component?

**Screenshots**
![image](https://user-images.githubusercontent.com/8775211/67466687-c6353f00-f647-11e9-98ac-50cbfd86b018.png)

**Context**
- UI5 Web Components version: 1.0.0-rc.4
- OS/Platform: macOS Catalina

**Affected components** *(if known)*
- ShellBar
- Icon

**Comment by pskelin** [comment]
Thanks a lot for the repro @MarcusNotheis !

Just for your information, the icon has a click event (the DOM one), so you can still use it and it is dispatched (I checked by using `addEventListener("click", ...)`), and the shell bar is styling this icon appropriately.

However, the icon does not have an outline, cannot be focused via keyboard or mouse and does not fire `click` on enter and space as the button does. We will address this separately, just wanted to let you know you can still use the DOM event `click` in the mean time.

**Comment by MapTo0** [comment]
Btw - In order to focus the icon - add `tabindex="0"` to the slotted `ui5-icon` and outline should be visible.
