### ISSUE TITLE
ui5-combobox-item: `getDomRef()` returns undefined

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#8841]
### Bug Description

When calling the `getDomRef` method of an ComboBoxItem, it doesn't return the element inside the shadow root, but `undefined`.

### Affected Component

ComboBoxItem

### Isolated Example

https://stackblitz.com/edit/js-k4ebjr?file=index.js,index.html

### Steps to Reproduce

1. Go to [StackBlitz](https://stackblitz.com/edit/js-k4ebjr?file=index.js,index.html)
2. Click on the "Log getDomRef()" button
3. See that only for the MultiComboBoxItem the correct value is returned

### Priority

None

### UI5 Web Components Version

1.24.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by NHristov-sap** [comment]
Hello @ui5-webcomponents-topic-rl,

Can you please check if the abstract ComboBoxItem should have DOM ref or not. If it should, please check why it is undefined.

Best Regards,
Nikolay Hristov
UI5 WebComponents Dispatcher
