### ISSUE TITLE
ui5-popover documentation missing

### ISSUE THREAD

**Issue by ignipae** [SAP/ui5-webcomponents#885]
**Describe the documentation issue**

- [ ] Documentation is unclear
- [ ] Documentation is incorrect
- [x] Documentation is missing
- [ ] Other

**Description of the issue**
I wanted to report that there is no documentation available for the ui5-popover.

I found myself in the position of thinking that this webcomponent does not exist but then I found the package for that:
https://github.com/SAP/ui5-webcomponents/blob/master/packages/main/src/Popover.js

:)

**Comment by vladitasev** [comment]
Hey, thanks for noticing!
We'll get into it
