### ISSUE TITLE
[ui5-cell ui5-button]: A disabled button as last element in the tab chain will prevent focus to first element in the tab chain 

### ISSUE THREAD

**Issue by f16r** [SAP/ui5-webcomponents#8852]
### Bug Description

 A disabled button inside a table cell as last element in the tab chain will prevent to move focus to first element in the tab chain. 

### Affected Component

ui5-cell ui5-button

### Expected Behaviour

Moving focus to the first element in the tab chain should be possible without marking a disabled button explicitly with tabIndex -1

### Isolated Example

https://codesandbox.io/p/sandbox/ui5-webcomponents-playground-forked-q9dqxj?file=%2Findex.html

### Steps to Reproduce

1. Go to isolated example
2. Click on last row to focus the row
3. Click tab -> tabbing is stuck
4. Workaround: Set tabIndex on button explicitly to -1. Tabbing is not stuck anymore (expected behaviour)

### Priority

Medium

### UI5 Web Components Version

1.24.0

### Browser

Chrome

### Organization

CBC

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by NHristov-sap** [comment]
Hello @ui5-webcomponents-topic-b,

I am forwarding this issue to you, because the issue is reproducible and the solution proposed by the reporter seems to be valid. Please check and fix.

Best Regards,
Nikolay Hristov
UI5 WebComponents Dispatcher
