### ISSUE TITLE
[ DatePicker ]: Race condition leads to missing CLDR data

### ISSUE THREAD

**Issue by stephen-schmith** [SAP/ui5-webcomponents#8868]
### Bug Description

As a follow-up to https://github.com/SAP/ui5-webcomponents/issues/8535, we are still seeing the missing CLDR data error even after upgrading to ui5-webcomponents 1.24.0.

When the user tries to open the `DatePicker` calendar, we see the attached exception. However, our app is already importing the CLDR assets durning startup like this:

`import "@ui5/webcomponents-react/dist/Assets";`

This issue was reproducible in 1.23.0 as well. With 1.22.0 we do not have any issues with missing CLDR data. Unfortunately, the issue is somewhat intermittent, and I can't reproduce it on sandbox.io or similar platforms, but I do understand why it's happening.

From the debugging I've done, there seems to be a race condition inside `asset-registries/LocaleData.ts` where the function `getLocaleData` attempts to read from `localeDataMap` before the function `fetchCldr` actually sets the locale data: https://github.com/SAP/ui5-webcomponents/blob/372d27d9db9afd40ffaf85cbfab61f10284063c3/packages/base/src/asset-registries/LocaleData.ts#L137

To be clear, the `fetchCldr` call does eventually succeed and retrieve the CLDR data, but this happens after `getLocaleData` is called, so we see the exception. To work around this issue, I can preload the CLDR data in advance of rendering the date picker by calling the following framework code:

```
import { fetchCldr } from "@ui5/webcomponents-base/dist/asset-registries/LocaleData";
import getLocale from "@ui5/webcomponents-base/dist/locale/getLocale";

const locale = getLocale();
fetchCldr(locale.getLanguage(), locale.getRegion(), locale.getScript());
```

However, this seems like it should be unnecessary. Could the ui5-webcomponent code be updated to include a guardrail that enables `fetchCldr` to finish before `getLocaleData` tries to read `localeDataMap`? 

### Affected Component

DatePicker

### Expected Behaviour

The calendar should open without issues, as it does under 1.22.0.

### Steps to Reproduce

1. Open the DatePicker calendar.

### Log Output, Stack Trace or Screenshots

<img width="592" alt="Screenshot 2024-04-26 at 3 46 37 PM" src="https://github.com/SAP/ui5-webcomponents/assets/110258073/b99a4bbd-9235-4918-b89e-0d34672470b7">

### Priority

None

### UI5 Web Components Version

1.24.0

### Browser

Chrome, Edge, Firefox, Safari

### Operating System

macOS

### Additional Context

Impact is to SAP SuccessFactors Learning. We haven't been able to upgrade past 1.22.0 until I found the workaround mentioned in this ticket.

### Organization

SAP SuccessFactors

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by PetyaMarkovaBogdanova** [comment]
Hi @stephen-schmith ,
thank you for your deep analysis on the issue.
Unfortunately I couldn't reproduce the console error, using our basic UI5 sample of [ui5-date-picker](https://sap.github.io/ui5-webcomponents/play/#eyJpbmRleC5odG1sIjp7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuPCFET0NUWVBFIGh0bWw-XG48aHRtbCBsYW5nPVwiZW5cIj5cblxuXG48aGVhZD5cbiAgICBcbiAgICA8c3R5bGU-XG4gICAgICAqOm5vdCg6ZGVmaW5lZCkge1xuICAgICAgICBkaXNwbGF5OiBub25lO1xuICAgICAgfVxuICAgIDwvc3R5bGU-XG5cbiAgICA8bWV0YSBjaGFyc2V0PVwiVVRGLThcIj5cbiAgICA8bWV0YSBuYW1lPVwidmlld3BvcnRcIiBjb250ZW50PVwid2lkdGg9ZGV2aWNlLXdpZHRoLCBpbml0aWFsLXNjYWxlPTEuMFwiPlxuICAgIDx0aXRsZT5TYW1wbGU8L3RpdGxlPlxuPC9oZWFkPlxuXG48Ym9keSBzdHlsZT1cImJhY2tncm91bmQtY29sb3I6IHZhcigtLXNhcEJhY2tncm91bmRDb2xvcik7IGhlaWdodDogNDUwcHg7XCI-XG4gICAgPCEtLSBwbGF5Z3JvdW5kLWZvbGQtZW5kIC0tPlxuXG4gICAgPHVpNS1kYXRlLXBpY2tlcj5cbiAgICA8L3VpNS1kYXRlLXBpY2tlcj5cbiAgICA8IS0tIHBsYXlncm91bmQtZm9sZCAtLT5cbiAgICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCJtYWluLmpzXCI-PC9zY3JpcHQ-XG48L2JvZHk-XG5cbjwvaHRtbD5cbjwhLS0gcGxheWdyb3VuZC1mb2xkLWVuZCAtLT5cbiJ9LCJtYWluLmpzIjp7Im5hbWUiOiJtYWluLmpzIiwiY29udGVudCI6Ii8qIHBsYXlncm91bmQtaGlkZSAqL1xuaW1wb3J0IFwiLi9wbGF5Z3JvdW5kLXN1cHBvcnQuanNcIjtcbi8qIHBsYXlncm91bmQtaGlkZS1lbmQgKi9cbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L0RhdGVQaWNrZXIuanNcIjsifX0).

Can you, please, compose a draft or example of the exact setup of your application, so we can get the chance to debug the behaviour that you are kindly describing, maybe using https://codesandbox.io/ ?
Thank you!
Best regards,
Petya Markova.
(UI5 Web Components Dispatcher)

**Comment by stephen-schmith** [comment]
@PetyaMarkovaBogdanova Let me keep debugging and see if I can find out what's leading to this scenario. Somehow the call to fetchCldr is triggered too late, but I can't reproduce it in a simple stackblitz environment. It must be some specific edge case in our code.

**Comment by petyabegovska** [comment]
Hi @stephen-schmith,

Did you manage to fix the issue?

**Comment by stephen-schmith** [comment]
@petyabegovska - No, we're still preloading the CLDR assets during startup to work around it. But I don't think that's a huge problem, at least.
