### ISSUE TITLE
Tree Component : Accessibility issues with reading Tree component data using JAWS/NVDA screen reader software

### ISSUE THREAD

**Issue by manishcharsap** [SAP/ui5-webcomponents#8889]
### Bug Description

When accessing Tree component additional information is being read out to the user which is not display into UI.

### Affected Component

Tree

### Expected Behaviour

Only relevant information about the UI should be communicated to the user. Additional information should be avoided.

### Isolated Example

https://t4h73v.csb.app/

### Steps to Reproduce

1. Open JAWS/NVDA screen reader software.
2. Go to the Tree component using tab key.

![Issue-PTB38913(JAWS)](https://github.com/SAP/ui5-webcomponents/assets/103047215/02d5b66b-5f97-48a5-9650-fd66bf1c8fe5)

### Priority

None

### UI5 Web Components Version

1.17.0

### Browser

Chrome, Edge, Firefox, Safari

### Organization

SAP Labs India

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by PetyaMarkovaBogdanova** [comment]
HI colleagues,
can you, please, check the aria attributes, that has been applied to tree item, that are redundant. Thank you!

Best regards,
Petya Markova.
(UI5 Dispatcher)

**Comment by C5362575** [comment]
Hi @PetyaMarkovaBogdanova 

As per the suggested solution, we have removed the aria attributes. Please keep this issue open till our changes are merged, and tested.

**Comment by C5362575** [comment]
Hi @PetyaMarkovaBogdanova even after we removed the aria attributes, this issue still persists. Please fix this issue at web component level. All required details are already shared

**Comment by PetyaMarkovaBogdanova** [comment]
Hi @C5362575 ,
sorry for the confusion, my memo was actually aimed for the team, that is responsible for the List component, to make a resume for them on what is wrong.
Anyway, we are already working on the fix from our side and you will be notified when it is merged.
Best regards,
Petya Markova.
(UI5 Web Component developer)

**Comment by yanaminkova** [comment]
Hello @manishcharsap,

Please accept my apologies for the delayed response.

Unfortunately, I was unable to open the link you provided, so I conducted a test using the [ui5-tree sample.](https://sap.github.io/ui5-webcomponents/nightly/play/#eyJpbmRleC5odG1sIjp7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxyXG48IURPQ1RZUEUgaHRtbD5cclxuPGh0bWwgbGFuZz1cImVuXCI-XHJcblxyXG5cbjxoZWFkPlxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG4gICAgPC9zdHlsZT5cblxyXG4gICAgPG1ldGEgY2hhcnNldD1cIlVURi04XCI-XHJcbiAgICA8bWV0YSBuYW1lPVwidmlld3BvcnRcIiBjb250ZW50PVwid2lkdGg9ZGV2aWNlLXdpZHRoLCBpbml0aWFsLXNjYWxlPTEuMFwiPlxyXG4gICAgPHRpdGxlPlNhbXBsZTwvdGl0bGU-XHJcbjwvaGVhZD5cclxuXHJcbjxib2R5IHN0eWxlPVwiYmFja2dyb3VuZC1jb2xvcjogdmFyKC0tc2FwQmFja2dyb3VuZENvbG9yKVwiPlxyXG4gICAgPCEtLSBwbGF5Z3JvdW5kLWZvbGQtZW5kIC0tPlxyXG4gICAgPHVpNS10cmVlIGlkPVwidHJlZVwiIG5vLWRhdGEtdGV4dD1cIk5vIGRhdGFcIiBtb2RlPVwiTXVsdGlTZWxlY3RcIiBhY2Nlc3NpYmxlLW5hbWU9XCJUcmVlIHdpdGggYWNjZXNzaWJsZU5hbWVcIj5cclxuXHJcbiAgICAgICAgPHVpNS10cmVlLWl0ZW0gbW92YWJsZSB0ZXh0PVwiVHJlZSAxXCIgaWNvbj1cInBhc3RlXCIgYWRkaXRpb25hbC10ZXh0PVwiQXZhaWxhYmxlXCIgaW5kZXRlcm1pbmF0ZSBzZWxlY3RlZCBhZGRpdGlvbmFsLXRleHQtc3RhdGU9XCJJbmZvcm1hdGlvblwiIGFjY2Vzc2libGUtbmFtZT1cIlRyZWUgaXRlbSB3aXRoIGFjY2Vzc2libGVOYW1lXCI-XHJcbiAgICAgICAgICAgIDx1aTUtdGl0bGUgc2xvdD1cImNvbnRlbnRcIj5cclxuICAgICAgICAgICAgICAgIDx1aTUtbGFiZWw-VHJlZSAxPC91aTUtbGFiZWw-XHJcbiAgICAgICAgICAgICAgICA8dWk1LWxhYmVsPlRyZWUgMTwvdWk1LWxhYmVsPlxyXG4gICAgICAgICAgICA8L3VpNS10aXRsZT5cclxuXHJcbiAgICAgICAgICAgIDx1aTUtdHJlZS1pdGVtIG1vdmFibGUgZXhwYW5kZWQgdGV4dD1cIlRyZWUgMS4xXCIgYWRkaXRpb25hbC10ZXh0PVwiUmUtc3RvY2tcIiBhZGRpdGlvbmFsLXRleHQtc3RhdGU9XCJOZWdhdGl2ZVwiIGluZGV0ZXJtaW5hdGUgc2VsZWN0ZWQ-XHJcbiAgICAgICAgICAgICAgICA8dWk1LXRyZWUtaXRlbSBtb3ZhYmxlIHRleHQ9XCJUcmVlIDEuMS4xXCIgYWRkaXRpb25hbC10ZXh0PVwiUmVxdWlyZWRcIiBhZGRpdGlvbmFsLXRleHQtc3RhdGU9XCJDcml0aWNhbFwiIHNlbGVjdGVkPjwvdWk1LXRyZWUtaXRlbT5cclxuICAgICAgICAgICAgICAgIDx1aTUtdHJlZS1pdGVtIG1vdmFibGUgdGV4dD1cIlRyZWUgMS4xLjJcIiBhZGRpdGlvbmFsLXRleHQ9XCJBdmFpbGFibGVcIiBhZGRpdGlvbmFsLXRleHQtc3RhdGU9XCJQb3NpdGl2ZVwiPjwvdWk1LXRyZWUtaXRlbT5cclxuICAgICAgICAgICAgPC91aTUtdHJlZS1pdGVtPlxyXG4gICAgICAgIDwvdWk1LXRyZWUtaXRlbT5cclxuXHJcbiAgICAgICAgPHVpNS10cmVlLWl0ZW0gbW92YWJsZSBkYXRhLWFsbG93cy1uZXN0aW5nIHRleHQ9XCJUcmVlIDIoQWxsb3dzIE5lc3RpbmcpXCIgaWNvbj1cImNvcHlcIj5cclxuICAgICAgICAgICAgPHVpNS10cmVlLWl0ZW0gbW92YWJsZSBpZD1cImZpcnN0Q29sbGFwc2VkSXRlbVwiIHRleHQ9XCJUcmVlIDIuMVwiPlxyXG4gICAgICAgICAgICAgICAgPHVpNS10cmVlLWl0ZW0gbW92YWJsZSB0ZXh0PVwiVHJlZSAyLjEuMVwiPjwvdWk1LXRyZWUtaXRlbT5cclxuICAgICAgICAgICAgICAgIDx1aTUtdHJlZS1pdGVtIG1vdmFibGUgdGV4dD1cIlRyZWUgMi4xLjJcIj5cclxuICAgICAgICAgICAgICAgICAgICA8dWk1LXRyZWUtaXRlbSBtb3ZhYmxlIHRleHQ9XCJUcmVlIDIuMS4yLjFcIj48L3VpNS10cmVlLWl0ZW0-XHJcbiAgICAgICAgICAgICAgICAgICAgPHVpNS10cmVlLWl0ZW0gbW92YWJsZSB0ZXh0PVwiVHJlZSAyLjEuMi4yXCI-PC91aTUtdHJlZS1pdGVtPlxyXG4gICAgICAgICAgICAgICAgICAgIDx1aTUtdHJlZS1pdGVtIG1vdmFibGUgdGV4dD1cIlRyZWUgMi4xLjIuM1wiPjwvdWk1LXRyZWUtaXRlbT5cclxuICAgICAgICAgICAgICAgICAgICA8dWk1LXRyZWUtaXRlbSBtb3ZhYmxlIHRleHQ9XCJUcmVlIDIuMS4yLjVcIj48L3VpNS10cmVlLWl0ZW0-XHJcbiAgICAgICAgICAgICAgICA8L3VpNS10cmVlLWl0ZW0-XHJcbiAgICAgICAgICAgIDwvdWk1LXRyZWUtaXRlbT5cclxuICAgICAgICAgICAgPHVpNS10cmVlLWl0ZW0gbW92YWJsZSB0ZXh0PVwiVHJlZSAyLjJcIj48L3VpNS10cmVlLWl0ZW0-XHJcbiAgICAgICAgICAgIDx1aTUtdHJlZS1pdGVtIG1vdmFibGUgdGV4dD1cIlRyZWUgMi4zXCI-PC91aTUtdHJlZS1pdGVtPlxyXG4gICAgICAgIDwvdWk1LXRyZWUtaXRlbT5cclxuXHJcbiAgICAgICAgPHVpNS10cmVlLWl0ZW0gbW92YWJsZSB0ZXh0PVwiVHJlZSAzIChubyBpY29uKVwiPlxyXG4gICAgICAgIDwvdWk1LXRyZWUtaXRlbT5cclxuXHJcbiAgICA8L3VpNS10cmVlPlxyXG5cclxuICAgIDwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxyXG4gICAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwibWFpbi5qc1wiPjwvc2NyaXB0PlxyXG48L2JvZHk-XHJcblxyXG48L2h0bWw-XHJcbjwhLS0gcGxheWdyb3VuZC1mb2xkLWVuZCAtLT5cclxuIn0sIm1haW4uanMiOnsibmFtZSI6Im1haW4uanMiLCJjb250ZW50IjoiLyogcGxheWdyb3VuZC1oaWRlICovXG5pbXBvcnQgXCIuL3BsYXlncm91bmQtc3VwcG9ydC5qc1wiO1xuLyogcGxheWdyb3VuZC1oaWRlLWVuZCAqL1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzL2Rpc3QvVHJlZS5qc1wiO1xyXG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMvZGlzdC9UcmVlSXRlbS5qc1wiO1xyXG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMvZGlzdC9UaXRsZS5qc1wiO1xyXG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMvZGlzdC9MYWJlbC5qc1wiO1xyXG5pbXBvcnQgTW92ZVBsYWNlbWVudCBmcm9tIFwiQHVpNS93ZWJjb21wb25lbnRzLWJhc2UvZGlzdC90eXBlcy9Nb3ZlUGxhY2VtZW50LmpzXCI7XHJcblxyXG5jb25zdCB0cmVlID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoXCJ0cmVlXCIpO1xyXG5jb25zdCBoYW5kbGVCZWZvcmVJdGVtTW92ZSA9IChlKSA9PiB7XHJcbiAgICBjb25zdCB7IGRlc3RpbmF0aW9uLCBzb3VyY2UgfSA9IGUuZGV0YWlsO1xyXG5cclxuICAgIGlmIChkZXN0aW5hdGlvbi5wbGFjZW1lbnQgPT09IFwiQmVmb3JlXCIgfHwgZGVzdGluYXRpb24ucGxhY2VtZW50ID09PSBcIkFmdGVyXCIpIHtcclxuICAgICAgICBlLnByZXZlbnREZWZhdWx0KCk7XHJcbiAgICB9XHJcblxyXG4gICAgaWYgKGRlc3RpbmF0aW9uLnBsYWNlbWVudCA9PT0gXCJPblwiICYmIFwiYWxsb3dzTmVzdGluZ1wiIGluIGRlc3RpbmF0aW9uLmVsZW1lbnQuZGF0YXNldCkge1xyXG4gICAgICAgIGUucHJldmVudERlZmF1bHQoKTtcclxuICAgIH1cclxuXHJcbiAgICBjb25zb2xlLmxvZyhgTW92aW5nIFwiJHtzb3VyY2UuZWxlbWVudC50ZXh0fVwiICR7ZGVzdGluYXRpb24ucGxhY2VtZW50LnRvTG93ZXJDYXNlKCl9IFwiJHtkZXN0aW5hdGlvbi5lbGVtZW50LnRleHR9XCJgKTtcclxufTtcclxuXHJcbmNvbnN0IGhhbmRsZU1vdmVPdmVyID0gKGUpID0-IHtcclxuICAgIGNvbnN0IHsgZGVzdGluYXRpb24sIHNvdXJjZSB9ID0gZS5kZXRhaWw7XHJcblxyXG4gICAgaWYgKCF0cmVlLmNvbnRhaW5zKHNvdXJjZS5lbGVtZW50KSkge1xyXG4gICAgICAgIHJldHVybjtcclxuICAgIH1cclxuXHJcbiAgICBoYW5kbGVCZWZvcmVJdGVtTW92ZShlKTtcclxufTtcclxuXHJcbmNvbnN0IGhhbmRsZU1vdmUgPSAoZSkgPT4ge1xyXG4gICAgY29uc3QgeyBkZXN0aW5hdGlvbiwgc291cmNlIH0gPSBlLmRldGFpbDtcclxuXHJcbiAgICBzd2l0Y2ggKGRlc3RpbmF0aW9uLnBsYWNlbWVudCkge1xyXG4gICAgICAgIGNhc2UgTW92ZVBsYWNlbWVudC5CZWZvcmU6XHJcbiAgICAgICAgICAgIGRlc3RpbmF0aW9uLmVsZW1lbnQuYmVmb3JlKHNvdXJjZS5lbGVtZW50KTtcclxuICAgICAgICAgICAgYnJlYWs7XHJcbiAgICAgICAgY2FzZSBNb3ZlUGxhY2VtZW50LkFmdGVyOlxyXG4gICAgICAgICAgICBkZXN0aW5hdGlvbi5lbGVtZW50LmFmdGVyKHNvdXJjZS5lbGVtZW50KTtcclxuICAgICAgICAgICAgYnJlYWs7XHJcbiAgICAgICAgY2FzZSBNb3ZlUGxhY2VtZW50Lk9uOlxyXG4gICAgICAgICAgICBkZXN0aW5hdGlvbi5lbGVtZW50LnByZXBlbmQoc291cmNlLmVsZW1lbnQpO1xyXG4gICAgICAgICAgICBicmVhaztcclxuICAgIH1cclxufTtcclxuXHJcbnRyZWUuYWRkRXZlbnRMaXN0ZW5lcihcIm1vdmUtb3ZlclwiLCBoYW5kbGVNb3ZlT3Zlcik7XHJcbnRyZWUuYWRkRXZlbnRMaXN0ZW5lcihcIm1vdmVcIiwgaGFuZGxlTW92ZSk7In19)

In my test, I couldn't reproduce the issue, and the component functioned as expected.

When focusing on the tree items, the additional information being announced (which is not visible in the UI) includes the states of the tree items, such as "closed" and "selected/not selected." This behavior aligns with our accessibility specifications.

Could you please test again using the latest version of JAWS and let us know if you still encounter any unexpected announcements?

Thank you and kind regards,
Yana
