### ISSUE TITLE
All UI Element_ UIs is adapted for OS themes.

### ISSUE THREAD

**Issue by c5369706** [SAP/ui5-webcomponents#8890]
### Bug Description

Observed Behavior: The application is adapted to the operating system themes on selecting ** the ‘Aquatic, Desert, Dusk and Night sky’ themes in the operating system settings.

 

Expected Behavior: ** The application should not be adapted to the operating system themes on selecting ** the ‘Aquatic, Desert, Dusk and Night sky’ themes in the operating system settings.

 ** 

[{*}“Note: The issue reported above persists throughout application. Hence, it should be corrected for all the occurrences.”]{*}

### Affected Component

@ui5/webcomponents-base/dist/config/Theme

### Expected Behaviour

Expected Behavior: ** The application should not be adapted to the operating system themes on selecting ** the ‘Aquatic, Desert, Dusk and Night sky’ themes in the operating system settings.

### Steps to Reproduce

Screen Flow:

1. Issue: Application is adapting to the OS theme.
2. Reproducing Method:
3. Open the application in various OS themes (e.g., light mode, dark mode).
4. Observe how the application's appearance changes according to the OS theme.
5. Current Behavior:
6. The application's UI elements change appearance based on the OS theme.

### Log Output, Stack Trace or Screenshots

https://github.com/SAP/ui5-webcomponents/assets/168708496/696cdc63-1f59-44b6-b60c-6a8111e56c81

### Priority

Medium

### UI5 Web Components Version

1.17.0

### Browser

Chrome

### Operating System

Windows

### Organization

SAP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by PetyaMarkovaBogdanova** [comment]
Hi @c5369706 ,
unfortunately we cannot control this behaviour on  web components level.
In order to avoid it, you need to add this CSS styles to your application:
`html, body {
    forced-color-adjust: none;
  }`

_Note that, there is a known issue, regarding that property and you may need to also add a background-color to your html element._

I hope you find that helpful.
Best regards,
Petya Markova.
(UI5 Dispatcher)

**Comment by c5369706** [comment]
Thanks for supporting on this.
