### ISSUE TITLE
Carousel: Carousel items of set min-width overlap for certain screen widths

### ISSUE THREAD

**Issue by pppwr7** [SAP/ui5-webcomponents#8895]
### Describe the bug

We have a scenario where in cards are to be shown as items in Carousel. These cards have a specific width set. So, when the screen width changes, the card width does not change and the items in the carousel overlap. The first item is also partially cut off from the display.

### Isolated Example

https://stackblitz.com/edit/github-pgrxks?file=src%2FApp.tsx

### Reproduction steps

please check attached screenshot

### Expected Behaviour

The items in the carousel should be displayed completely starting from left to right. The first item should not be cut off while displaying as we dont have any option to navigate to left to see the full item. The last item in the display could be cutoff as we can navigate to the right to see it properly.

### Screenshots or Videos

![image](https://github.com/SAP/ui5-webcomponents-react/assets/90389521/f9bd1300-5070-4590-b6b7-1b8296df25bc)

### UI5 Web Components for React Version

latest

### UI5 Web Components Version

latest

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by PetyaMarkovaBogdanova** [comment]
Hi @pppwr7,
unfortunately that default behaviour of ui5-carousel. It shows/hides certain items, based on the configuration, it is not sliding the parts of the scrolling container. For now we don't plan on adjusting it to what you described. You should should rather use responsive widths for the elements, or write some media queries for them based on the screen size.
Best regards,
Petya Markova.
(UI5 Dispatcher)
