### ISSUE TITLE
Additional reading for elements used in Dialog Footer 

### ISSUE THREAD

**Issue by C5362575** [SAP/ui5-webcomponents#8901]
### Bug Description

 When accessing the elements in footer of the Dialog for example a button, the information is being read out as "Header Toolbar" which is incorrect. As here the element is added in the Footer. This reading is being done by screen readers like Screen Reader: JAWS Version 2024.2312.53

### Affected Component

Dialog

### Expected Behaviour

 When the UI element is accessed from Footer of Dialog using screen readers, then correct information must be communicated to the user. For our scenario elements present in the Footer should read under "Footer toolbar" section and not "Header toolbar"

### Steps to Reproduce

Navigate to the Footer section of Dialog while the screen reader is reading the content only relevant information about the UI should be communicated to the user. Additional information should be avoided.

### Priority

Medium

### UI5 Web Components Version

1.19.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by niyap** [comment]
Hello @C5362575,

Could you please provide a link to an isolated example if possible by forking [this stackblitz](https://stackblitz.com/edit/js-vsrpnb?file=index.js,index.html)?

I checked the samples in our playground and I was not able to reproduce the issue: https://sap.github.io/ui5-webcomponents/components/Dialog/

Thank you in advance!

Kind Regards,
Niya

**Comment by C5362575** [comment]
Hi @niyap  Please find forked modified  (https://stackblitz.com/edit/js-rdhenh?file=index.html)  Dialog component which has a footer as well . When the UI element is accessed from the Footer of Dialog using screen readers, then correct information must be communicated to the user. For our scenario elements present in the Footer should read under "Footer toolbar" section and not "Header toolbar"

@niyap  can you also confirm which screen reader are you using for testing purpose

**Comment by GerganaKremenska** [comment]
Hello @C5362575,

I have retested with the fork you provided and there is no mention of  "Header toolbar". 
Jaws version 2024.2312.53

Please refer to the attached screenshot which is showing speech output of the screen reader.
![Screenshot 2024-05-15 at 13 49 40](https://github.com/SAP/ui5-webcomponents/assets/22882174/cb2c59ce-c718-4521-89ae-c65b664bd1fe)

Can you provide more guidance on how to reproduce it?

Best Regards,
Gergana

**Comment by C5362575** [comment]
Hi @GerganaKremenska  there is a version mismatch, we have  **"@ui5/webcomponents": "1.17.0"** in our app but in code sandbox we have   **"@ui5/webcomponents": "1.20.1"**

can you please change the version in code sandbox and test it again

**Comment by GerganaKremenska** [comment]
Hello @C5362575 ,

I have retested with "@ui5/webcomponents": "1.17.0" - [stackblitz](https://stackblitz.com/edit/js-nwvq4e?file=package.json,index.html)

Here is the result and stil i do not see the issue.
<img width="1787" alt="Screenshot 2024-05-17 at 8 12 50" src="https://github.com/SAP/ui5-webcomponents/assets/22882174/ba6f38da-68b4-4eed-ae4b-eea9e6a9cea9">


Please provide your speech history. Or more information on how to reproduce the issue.

Best Regards,
Gergana
