### ISSUE TITLE
[ui5-mulitiinput] Free input delete doesn't work properly

### ISSUE THREAD

**Issue by clemai** [SAP/ui5-webcomponents#8905]
### Bug Description

Under specific circumstances it's not possible to delete the free text within the Multiinput component.

### Affected Component

ui5-multiinput

### Expected Behaviour

I would expect that I am always able to delete selected text via pressing the backspace key.

### Isolated Example

https://sap.github.io/ui5-webcomponents/components/MultiInput/

### Steps to Reproduce

1. Type any text as free input
2. Select the complete text via mouse or double click or 'CMD + A'.
3. Press the backspace key.

The last token is focused, but text stays in the input. The issue only occurs when there is at least one token.

### Priority

Medium

### UI5 Web Components Version

1.24.0

### Browser

Chrome

### Operating System

Mac

### Organization

SAP SIX Technologies

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by niyap** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

When we have ui5-multi-input with tokens and text, if we select the text via Ctrl/Cmd + A and try to delete it via backspace - the text is not deleted but the focus is moved to the last token instead.
https://sap.github.io/ui5-webcomponents/components/MultiInput/ -  the first sample is appropriate for testing.

Could you please look over?
Thank you in advance!

Kind Regards,
Niya
