### ISSUE TITLE
[ui5-multi-combobox | a11y]: Irrelevant & wrong information are read out

### ISSUE THREAD

**Issue by f16r** [SAP/ui5-webcomponents#8908]
### Bug Description

A: After pressing Arrow Down Key "No Tokens" gets announced again (Irrelevant information)
B: After removing one item "Contains 1 token" gets announced even though there are no tokens (Wrong Information)

### Affected Component

ui5-multi-combobox

### Expected Behaviour

A: "No Tokens" is not read
B: "Contains 0 token"

### Isolated Example

https://sap.github.io/ui5-webcomponents/play/#eyJpbmRleC5odG1sIjp7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuPCFET0NUWVBFIGh0bWw-XG48aHRtbCBsYW5nPVwiZW5cIj5cblxuXG5cbjxoZWFkPlxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG4gICAgPC9zdHlsZT5cblxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG4gICAgPC9zdHlsZT5cblxuICAgIDxtZXRhIGNoYXJzZXQ9XCJVVEYtOFwiPlxuICAgIDxtZXRhIG5hbWU9XCJ2aWV3cG9ydFwiIGNvbnRlbnQ9XCJ3aWR0aD1kZXZpY2Utd2lkdGgsIGluaXRpYWwtc2NhbGU9MS4wXCI-XG4gICAgPHRpdGxlPlNhbXBsZTwvdGl0bGU-XG48L2hlYWQ-XG5cbjxib2R5IHN0eWxlPVwiYmFja2dyb3VuZC1jb2xvcjogdmFyKC0tc2FwQmFja2dyb3VuZENvbG9yKTsgaGVpZ2h0OiAzNTBweDtcIj5cbiAgICA8IS0tIHBsYXlncm91bmQtZm9sZC1lbmQgLS0-XG5cbiAgICA8dWk1LW11bHRpLWNvbWJvYm94IHBsYWNlaG9sZGVyPVwiVHlwZSB5b3VyIHZhbHVlXCI-XG4gICAgICAgIDx1aTUtbWNiLWl0ZW0gdGV4dD1cIkFsYmFuaWFcIj48L3VpNS1tY2ItaXRlbT5cbiAgICAgICAgPHVpNS1tY2ItaXRlbSB0ZXh0PVwiQXJnZW50aW5hXCI-PC91aTUtbWNiLWl0ZW0-XG4gICAgICAgIDx1aTUtbWNiLWl0ZW0gdGV4dD1cIkJ1bGdhcmlhXCI-PC91aTUtbWNiLWl0ZW0-XG4gICAgICAgIDx1aTUtbWNiLWl0ZW0gdGV4dD1cIkRlbm1hcmtcIj48L3VpNS1tY2ItaXRlbT5cbiAgICAgICAgPHVpNS1tY2ItaXRlbSB0ZXh0PVwiRW5nbGFuZFwiPjwvdWk1LW1jYi1pdGVtPlxuICAgICAgICA8dWk1LW1jYi1pdGVtIHRleHQ9XCJHZXJtYW55XCI-PC91aTUtbWNiLWl0ZW0-XG4gICAgICAgIDx1aTUtbWNiLWl0ZW0gdGV4dD1cIlBoaWxpcHBpbmVzXCI-PC91aTUtbWNiLWl0ZW0-XG4gICAgICAgIDx1aTUtbWNiLWl0ZW0gdGV4dD1cIlBvcnR1Z2FsXCI-PC91aTUtbWNiLWl0ZW0-XG4gICAgICAgIDx1aTUtbWNiLWl0ZW0gdGV4dD1cIlRoZSBVbml0ZWQgS2luZ2RvbSBvZiBHcmVhdCBCcml0YWluIGFuZCBOb3J0aGVybiBJcmVsYW5kXCI-PC91aTUtbWNiLWl0ZW0-XG4gICAgPC91aTUtbXVsdGktY29tYm9ib3g-XG4gICAgPCEtLSBwbGF5Z3JvdW5kLWZvbGQgLS0-XG4gICAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwibWFpbi5qc1wiPjwvc2NyaXB0PlxuPC9ib2R5PlxuXG48L2h0bWw-XG48IS0tIHBsYXlncm91bmQtZm9sZC1lbmQgLS0-XG4gICAgICAifSwibWFpbi5qcyI6eyJuYW1lIjoibWFpbi5qcyIsImNvbnRlbnQiOiIvKiBwbGF5Z3JvdW5kLWhpZGUgKi9cbmltcG9ydCBcIi4vcGxheWdyb3VuZC1zdXBwb3J0LmpzXCI7XG4vKiBwbGF5Z3JvdW5kLWhpZGUtZW5kICovXG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMvZGlzdC9NdWx0aUNvbWJvQm94LmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMvZGlzdC9NdWx0aUNvbWJvQm94SXRlbS5qc1wiOyJ9fQ

### Steps to Reproduce

A: Irrelevant information:
1. Press "Arrow Down" Key to focus first element in the list -> "No Tokens"

B: Wrong information:
1. Press "Arrow Down" Key to focus first element in the list (Albania)
2. Press "Enter" Key to select the focused element (Albania)
3. Press "Arrow Left" Key to select previously added element (Albania)
4. Press "Delete" to remove Albania -> "Contains 1 token" 

### Log Output, Stack Trace or Screenshots

![image](https://github.com/SAP/ui5-webcomponents/assets/37051913/3edfd396-84a4-460b-8199-4777da3ec2cb)

### Priority

Medium

### UI5 Web Components Version

1.24.0

### Browser

Chrome

### Additional Context

JAWS version: 2023.2307.37

### Organization

CBC

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by nikoletavnv** [comment]
The bug is also reproduceable in 2.0.0-rc.6
