### ISSUE TITLE
[Tree]: Space is not working

### ISSUE THREAD

**Issue by pop1989bb** [SAP/ui5-webcomponents#8915]
### Bug Description

In your [documentation](https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-tree--docs) you write _[SPACE] - Selects the currently focused item upon keyup._
This isn't working or I don't get it the right way what the "selects the currently focused item" means. And if I am using the custom tree element the space isn't reaching for example an input field which is placed into the custom tree element.

### Affected Component

Tree

### Expected Behaviour

The

### Steps to Reproduce

1. Select an tree item within the tree
2. Press enter
3. Wonder what should happen

### Priority

Medium

### UI5 Web Components Version

1.26.3

### Browser

Chrome, Firefox

### Operating System

Windows 11

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by niyap** [comment]
Hello @pop1989bb,

Could you please provide an isolated example if possible by forking [this stackblitz](https://stackblitz.com/edit/js-vsrpnb?file=index.js,index.html)?

Kind Regards,
Niya

**Comment by nnaydenow** [comment]
Hi @pop1989bb,

As you can see in the keyboard interaction section (https://sap.github.io/ui5-webcomponents/components/Tree/#keyboard-handling), the `Space` and the `Enter` key should select the current focused item when `mode` property is in use (e.g. mode is set to some kind of selection).
