### ISSUE TITLE
[Feature Request]: Enable/disable padding configurable on ui5-button

### ISSUE THREAD

**Issue by slin-sap** [SAP/ui5-webcomponents#8917]
### Feature Request Description

ui5-button already supports setting size of icon: #1327

But if the icon size is large, icon is cut off in an icon button as shown in this screenshot:

![Screenshot 2024-05-08 at 7 32 11 AM](https://github.com/SAP/ui5-webcomponents/assets/98066146/2b746202-4f1d-4f04-bec3-f11fa29d1f46)

### Proposed Solution

This is because ui5-button applies horizontal padding. I have tried to overwrite the css variable in our app. But the variable name is specific to UI5 version. It is better to support disable padding from webc API.

This problem can be solved if padding can be optionally turned off. 

![Screenshot 2024-05-08 at 7 27 46 AM](https://github.com/SAP/ui5-webcomponents/assets/98066146/4199f1f3-6165-41a9-bef6-d56db9ecdaf0)

![Screenshot 2024-05-08 at 7 30 03 AM](https://github.com/SAP/ui5-webcomponents/assets/98066146/3264d852-889d-40a7-b6ee-7ddf7fb3aa44)

### Organization

UX Engineering

### Priority

Medium

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by niyap** [comment]
Hello @SAP/ui5-webcomponents-topic-b ,

Could you please take a look of that feature request?

Thank you in advance!

Kind Regards,
Niya

**Comment by ilhan007** [comment]
Hello @slin-sap 

there is a [CSS shadow part](https://developer.mozilla.org/en-US/docs/Web/CSS/::part) attribute available, called "button".

The part can be used:
```css
ui5-button::part(button) {
  padding: /* */
}
```

**Comment by slin-sap** [comment]
Hi @ilhan007 

Thanks! This solution works for me. I will close this issue.

**Comment by ilhan007** [comment]
Here we have a nice docs about the styling of UI5 Web Components taht could be also useful:
https://sap.github.io/ui5-webcomponents/docs/customizing/styles/
