### ISSUE TITLE
[Feature Request]:  Provide an option to have horizontal line under the Wizard step title

### ISSUE THREAD

**Issue by gurkirpalgill** [SAP/ui5-webcomponents#8923]
### Feature Request Description

Currently Wizard does not provide an option to show horizontal line under the wizard step title.

### Proposed Solution

We need an option to show horizontal line under the Wizard Step title. See attached screen shot
![Screenshot 2024-05-08 at 5 38 49 PM](https://github.com/SAP/ui5-webcomponents/assets/65705637/2ca8a282-1ae6-4809-9db3-fbf81d42006b)

### Priority

Medium

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by hristop** [comment]
Hi @gurkirpalgill ,

We will check this request with our design team and will let you know the outcome. 

Best Regards,
Hristo

**Comment by hristop** [comment]
Hi @gurkirpalgill ,

I have created an internal design BLI: FIORITECHE1-8245, once it is done or we need more info, we will let you know.

Best Regards,
Hristo

**Comment by hristop** [comment]
Hi @gurkirpalgill ,

The design team has rejected this requirement. 
If you feel that they should reconsider and again look into your request, please provide the following information (provided it is not internal):

# What is the problem?
# Who needs this feature and who are the experts?
# Can you explain the validity of this requirement (customer feedback or research results that underpin the validity of the requirement)?
# Who are the users?
# What is the context? Can you show examples of screens, application flows or use cases that provide more information on where this requirement could play a role in?

Best Regards,
Hristo
