### ISSUE TITLE
Incorrect Default Time in DateTimePicker

### ISSUE THREAD

**Issue by saran85** [SAP/ui5-webcomponents#8966]
### Bug Description

The DateTimePicker component in our UI5 web application is exhibiting unexpected behavior related to the default time when selecting a date. It consistently provides an incorrect default time instead of occasionally using the local time, which is causing usability and data entry issues for our users.  please refer previous ticket https://github.com/SAP/ui5-webcomponents/issues/7992 . The issue persists even after updating to the new version.

### Affected Component

DateTimePicker

### Expected Behaviour

When selecting a date, the DateTimePicker should automatically use the local time or, at the very least, display a time value that accurately corresponds to the selected date.

### Isolated Example

https://codesandbox.io/p/sandbox/datetimepicker-rn4z43

### Steps to Reproduce

Navigate to the DateTimePicker in the application.
Select a date by clicking on the calendar icon.
Observe that the DateTimePicker sets an incorrect default time.
![image](https://github.com/SAP/ui5-webcomponents/assets/95576439/6f961402-a282-4585-a0fa-33939add8485)

### Priority

High

### UI5 Web Components Version

1.17.0

### Browser

Chrome, Edge

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by GerganaKremenska** [comment]
Hello @saran85, 

The example you provided is with version 1.17, I have updated the [example](https://codesandbox.io/p/sandbox/datetimepicker-forked-27kzpw?file=%2Fpublic%2Findex.html%3A20%2C28) to 1.22(which includes the fix) and it seems, okay to me.

![Screenshot 2024-05-15 at 10 15 47](https://github.com/SAP/ui5-webcomponents/assets/22882174/82e60260-9649-44bc-9e88-0dfe2673e5fb)


Can you please retest and get back to us? 

Best Regards,
Gergana
