### ISSUE TITLE
[Illustrative Message Component]: description (body text) using wrong color parameter

### ISSUE THREAD

**Issue by ShirSAP** [SAP/ui5-webcomponents#8984]
### Bug Description

Today the description (body text) is using "--sapContent_LabelColor" color parameter.

### Affected Component

https://sap.github.io/ui5-webcomponents-react/?path=/docs/user-feedback-illustratedmessage--docs

### Expected Behaviour

we should use "color: --sap_TextColor;" instead.
This is specified in the following wiki: https://wiki.one.int.sap/wiki/pages/viewpage.action?pageId=3139378128

### Steps to Reproduce

1.
2.
3.
...

### Priority

Low

### UI5 Web Components Version

1.18.0

### Browser

Chrome

### Operating System

OS

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by GerganaKremenska** [comment]
Hello @ui5-webcomponents-topic-p I am forwarding this issue to you,
 because there is a diviation from the parameter given in the VD specifcation and the one set to the description text of the illustrated message.

Best Regards,
Gergana

**Comment by ilhan007** [comment]
Hello @ShirSAP the issue has been fixed 
and will be available with:
1.24.X - start of June
2.0.0-rc.X - start of June
