### ISSUE TITLE
[Select]: The vertical scrollbar remains static when navigating using the keyboard in the list

### ISSUE THREAD

**Issue by thefabfabdew** [SAP/ui5-webcomponents#8987]
### Describe the bug

The scrollbar remains inactive when navigating by name the list

### Isolated Example

https://codesandbox.io/p/devbox/headless-wave-mjcqtw?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clw91wqav00073j6g0fb7j5t2%2522%252C%2522sizes%2522%253A%255B70.67385444743935%252C29.326145552560646%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clw91wqau00023j6gw2c2fk09%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clw91wqav00043j6gagk7io8z%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clw91wqav00063j6gzjgu5n1z%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40.84212085499315%252C59.15787914500685%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clw91wqau00023j6gw2c2fk09%2522%253A%257B%2522id%2522%253A%2522clw91wqau00023j6gw2c2fk09%2522%252C%2522activeTabId%2522%253A%2522clw92ralc001q3j6gjl54hwpe%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clw91wqau00013j6g48s42yyu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clw92q1t8004q3j6gsyx5p5xp%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fassets%252Freact.svg%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.codesandbox%252Ftasks.json%2522%252C%2522id%2522%253A%2522clw92ralc001q3j6gjl54hwpe%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clw91wqav00063j6gzjgu5n1z%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clw91wqav00053j6gbhgxf0zm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clw91wqav00063j6gzjgu5n1z%2522%252C%2522activeTabId%2522%253A%2522clw91wqav00053j6gbhgxf0zm%2522%257D%252C%2522clw91wqav00043j6gagk7io8z%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clw91wqav00033j6gpnfby6ey%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clw91wqav00043j6gagk7io8z%2522%252C%2522activeTabId%2522%253A%2522clw91wqav00033j6gpnfby6ey%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Reproduction steps

1. Open the select
2. Select a name (ex : 0BICS_CUST_DIM_MASTE)
3. Expand the list : the focus is on the previous selected hierarchy
4. From the keyboard, type "n", "z", the name starting with this letter appears in the field 
 ==> it has no impact on the vertical scrollbar

### Expected Behaviour

The vertical scrollbar is synchronized when navigating by name the list

### Screenshots or Videos

https://github.com/SAP/ui5-webcomponents-react/assets/162131252/cdd401cf-aa49-4646-8dc2-8f6c3e6b5099

### UI5 Web Components for React Version

1.26.2

### UI5 Web Components Version

1.23.3

### Browser

Chrome, Edge

### Operating System

Windows

### Organization

SAP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by nnaydenow** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

Could you please check the issue?

**Comment by thefabfabdew** [comment]
> Hi @thefabfabdew
> 
> Thanks for reporting! I'll forward this issue to our UI5 Web Components Colleagues as the affected component is developed in their repository.
> 
> Also please note that we moved to [StackBlitz](https://stackblitz.com/github/SAP/ui5-webcomponents-react/tree/main/templates/vite-ts?file=src%2FApp.tsx) as our preferred web IDE/sandbox as it's not possible anymore to edit codeSandboxes with a free plan.
> 
> Hi colleagues,
> 
> here you can find a simplified example without our wrapper or React: https://stackblitz.com/edit/js-k5glgr?file=index.js

Thanks for taking care of this, I notified my team about StackBlitz. Best regards
