### ISSUE TITLE
ManagedStyles on chrome mobile emulator throws error "Invalid runtime index supplied" on v1.120

### ISSUE THREAD

**Issue by anna-yujeong** [SAP/ui5-webcomponents#8989]
### Bug Description

When initializing Dialog/Icon, there is a console error "Invalid runtime index supplied"
![error](https://github.com/SAP/ui5-webcomponents/assets/170034228/33486a4d-fd35-4a77-bdf1-dfb4874b5f6b)

This seems like caused by in updateStyle in ManagedStyles.ts the chrome mobile device emulator falls to the else block - where `const styleRuntimeIndex = style.getAttribute("data-ui5-runtime-index") || undefined;` returns "undefined" as literal string rather than type undefined. This then goes to shouldUpdate method and tries to parseInt, which returns NaN, where it is checked by compareRuntimes in Runtimes.js and eventually throw the error.

We don't see the console error on web settings (so without the emulator on) since it goes to the else if block `const stylesheetTheme = stylesheet._ui5Theme;` which returns undefined (not as string), which returns true on shouldUpdate
 
Web (non-Safari):
<img width="1459" alt="web" src="https://github.com/SAP/ui5-webcomponents/assets/170034228/e589bf5d-f1f9-4372-859e-582610454f03">

Mobile (chrome emulator) or Safari:
<img width="1377" alt="mobile" src="https://github.com/SAP/ui5-webcomponents/assets/170034228/30931bf4-b2a5-49fa-a120-c785568171af">

file: https://github.com/SAP/ui5-webcomponents/blob/v1.20.0/packages/base/src/ManagedStyles.ts

### Affected Component

Dialog/Icon

### Expected Behaviour

Should also handle the case where runtimeIndex in shouldUpdate in ManagedStyles comes in as literal string "undefined" 
Should not throw error

### Steps to Reproduce

1. with the specified version, initialize Dialog/Icon
2. set "data-ui5-runtime-index" attribute to "undefined" or anything else that is not type integer or undefined 
3. during initialization, in console there is error "Invalid runtime index supplied"

### Priority

High

### UI5 Web Components Version

openui5 1.120.1, webcomponents 1.23.3

### Browser

Chrome, Edge, Safari

### Organization

SAP Cloud

### Declaration

- [ ] I’m not disclosing any internal or sensitive information.

**Comment by GerganaKremenska** [comment]
@anna-yujeong, 

Could you please provide a link to an isolated example if possible by forking [this stackblitz](https://stackblitz.com/edit/js-vsrpnb?file=index.js,index.html)?
And detailed steps to reproduce.

Best Regards,
Gergana

**Comment by anna-yujeong** [comment]
hi @GerganaKremenska, thank you for the reply. 

I find it hard to provide an isolated example with just defining components since it seems more of on the Runtime side, and to simulate this i will need access to define different runtimes. Could you please let me know if there is any way to do this? Or, would there be by any chance on your side to test shouldUpdate method in ManagedStyles.ts if it can handle a non-integer and not an undefined? The problem seems to me is that it tries to parseInt a string and throws an error.

I recently found this since we did a ui5 version upgrade from 1.14.0 to 1.23.3 last week, and I see there are differences in ManagedStyles.ts between those two versions.

https://github.com/SAP/ui5-webcomponents/blob/v1.14.0/packages/base/src/ManagedStyles.ts
https://github.com/SAP/ui5-webcomponents/blob/v1.23.3/packages/base/src/ManagedStyles.ts


Thank you for your help,

Anna

**Comment by nnaydenow** [comment]
Hi @anna-yujeong,

I saw that you participate in SAP organization. Could you please provide more details offline so we can process issue?

**Comment by anna-yujeong** [comment]
Hi @nnaydenow , I sent a message on Teams. Please let me know if you didn't get the message, thank you.

**Comment by nnaydenow** [comment]
Hi @anna-yujeong,

As we discussed offline I'm waiting response from your side and until them I'm putting the issue in author action state.
