### ISSUE TITLE
[ui5-select]: options doesn't have focus

### ISSUE THREAD

**Issue by nnaydenow** [SAP/ui5-webcomponents#8999]
### Bug Description

When the picker is open, the currently selected `ui5-option` doesn't have option but only selected state.

![image](https://github.com/SAP/ui5-webcomponents/assets/31909318/3dc578d5-94f2-4740-922e-6fa448ea74e3)

### Affected Component

ui5-select

### Expected Behaviour

Focus to be visible when the picker is open.

### Steps to Reproduce

https://sap.github.io/ui5-webcomponents/nightly/components/Select/#basic-sample

### Priority

None

### UI5 Web Components Version

latest

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by kgogov** [comment]
Hi @nnaydenow,
I checked the reported issue, but it looks like the component actually has focus styles. Could you confirm if things are ok on your side too? Thanks!

[Select (nightly)](https://sap.github.io/ui5-webcomponents/nightly/components/Select/#basic-sample)
[Select (v1)](https://sap.github.io/ui5-webcomponents/components/Select/#options-with-additional-text)
