### ISSUE TITLE
SegmentedButton: Accessibility issue ARIA input fields must have an accessible name

### ISSUE THREAD

**Issue by achuth2912** [SAP/ui5-webcomponents#9011]
### Describe the bug

When we run a axe dev tools for SegmentedButton component we are having a accessibility issue reported saying the component must have accessible name for the aria input fileds.

### Isolated Example

https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-segmentedbutton--docs

### Reproduction steps

1.
2.
3.
...

### Expected Behaviour

We need to ensures every ARIA input field has an accessible name

### Screenshots or Videos

<img width="1728" alt="Screenshot 2024-05-20 at 10 58 26 AM" src="https://github.com/SAP/ui5-webcomponents-react/assets/71249041/db7614b8-d6bc-4bc5-9c3c-ae66acd80f80">

### UI5 Web Components for React Version

1.28.1

### UI5 Web Components Version

1.24.0

### Browser

Chrome

### Operating System

Mac OS

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Todor-ads** [comment]
Hello @SAP/ui5-webcomponents-topic-b,
Could you please look into this issue?

Regards,
Todor

**Comment by unazko** [comment]
Hello @achuth2912,

The described issue in the `ui5-segmented-button` component is actually a sample issue.
By UX guidelines the application developers have to provide an external label or an `accessibleName` to the `ui5-segmented-button` element. 
Additionally in case the `ui5-segmented-button-item` is icon-only then a `tooltip` is also required.
Please use the related PR: https://github.com/SAP/ui5-webcomponents/pull/9809 as a reference on how those API could be used by the application developers, in order not to have the described AXE tool issues.

Best regards,
Boyan
