### ISSUE TITLE
upgrading to a version > 1.22

### ISSUE THREAD

**Issue by saran85** [SAP/ui5-webcomponents#9016]
### Bug Description

Upgrading to version 1.22 anticipated some dependencies; the packages themselves are the source of this problem.
FYI:
SyntaxError: C:\Petrobras_Project\ppbr-monorepo\.yarn\cache\@ui5-webcomponents-localization-npm-1.22.0-ef56372211-b596751246.zip\node_modules\@ui5\webcomponents-localization\dist\sap\base\i18n\LanguageTag.js: Class private methods are not enabled.

### Affected Component

DateTimePicker

### Expected Behaviour

Expectung without class dependancy upgrade the new version

### Steps to Reproduce

during the test coverage the issue is reflect.(yarn test)
![image](https://github.com/SAP/ui5-webcomponents/assets/95576439/b6585dc3-ffaa-4ba1-b42a-f11f8675ffad)

### Priority

High

### UI5 Web Components Version

1.22.0

### Browser

Edge

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Todor-ads** [comment]
Hello @saran85 , 
could you provide me with details on how to reproduce this error? Are you using a framework? If there are any other specific details, it would also be helpful for us in quickly locating a potential problem and resolving it.

Regards,
Todor
