### ISSUE TITLE
[Feature Request][ListItemBase]: Change selected property to private

### ISSUE THREAD

**Issue by dobrinyonkov** [SAP/ui5-webcomponents#9022]
### Feature Request Description

The selected property is currently defined in ListItemBase.ts. Since ui5-li-notification and ui5-li-notification-group inherit from ListItemBase, the selected property appears in these components even though it is not used by them.

To improve the design and maintainability of the code, it would be more appropriate to **move the selected property as public to ListItem, where it is actually utilized.** 
**We need to keep it private in the ListItemBase for the Select and suggestion Input, Combobx, ect.**

### Proposed Solution

Relocate the public selected property from ListItemBase.ts to ListItem.ts.

### Priority

Medium

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by MapTo0** [comment]
Can we somehow leave the selected styles on a listitem base leve, since it is used by all components, but remove it from the API?

**Comment by ilhan007** [comment]
This is done @dobrinyonkov
