### ISSUE TITLE
React integration broken in Edge/IE11

### ISSUE THREAD

**Issue by RubenStoesser** [SAP/ui5-webcomponents#903]
**Describe the bug**
Using ui5-webcomponents in React is broken in Edge & IE11. This can also be seen in your sample application for React (https://sap.github.io/ui5-webcomponents-sample-react/)

**To reproduce**
1. Go to https://sap.github.io/ui5-webcomponents-sample-react/ in Edge or IE11
2. In Edge the page only loads text content. In IE11 the page does not load at all.

**Isolated example**
https://sap.github.io/ui5-webcomponents-sample-react/

**Expected behavior**
With provided polyfills the web components should also work in Edge & IE11

**Context**
- UI5 Web Components version: 1.0.0-rc.4
- OS/Platform: Windows
- Browser *(if relevant)*: Edge / IE11

**Log output / Any errors** in the console
Edge:
```
SCRIPT5002: SCRIPT5002: Invalid operand to 'instanceof': Function expected
```

IE11:
```
'WeakSet' is undefined 
1.c257bb27.chunk.js (1,9874)
```

**Comment by MapTo0** [comment]
Hello @RubenStoesser 

We are aware that the app is not working and we have an issue reported long time ago https://github.com/SAP/ui5-webcomponents-sample-react/issues/4

Unfortunately, we haven't done it yet 😞. Anyway feel free to check https://github.com/SAP/ui5-webcomponents/issues/160 (it is quite old and some paths might be wrong but the idea is the same). In case you decide to look deeper into the issue, any contributions are welcome!

To demo our components on IE, feel free to use the playground: https://sap.github.io/ui5-webcomponents/playground/

Regards!
