### ISSUE TITLE
[Table]: Table Column Label is displayed in bolder in Safari than in Chrome

### ISSUE THREAD

**Issue by lenafi5cher** [SAP/ui5-webcomponents#9046]
### Describe the bug

Similar to this [issue](https://github.com/SAP/ui5-webcomponents/issues/8361), now the Labels for the TableColumns appear a lot bolder in Safari than in Chrome.

### Reproduction steps

1. Open the [Table docs](https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-table--docs#example) in Safari
2. Look at the example

### Expected Behaviour

Font size should be the same as shown in Chrome
![image](https://github.com/SAP/ui5-webcomponents-react/assets/165897616/efbba633-f1b4-4b9d-aa13-0b27a3f81e91)

### Screenshots or Videos

![image](https://github.com/SAP/ui5-webcomponents-react/assets/165897616/fec4f9ec-ddba-4e89-a1c7-833aadf5fcc5)

### UI5 Web Components for React Version

v1.28.1

### UI5 Web Components Version

v1.24.0

### Browser

Safari

### Organization

SAP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Todor-ads** [comment]
Hello @SAP/ui5-webcomponents-topic-rl ,
Could you please look into this issue? The problem reproduces following the described steps.

Regards,
Todor

**Comment by nnaydenow** [comment]
Fixed the issue for version 1.24 with https://github.com/SAP/ui5-webcomponents/pull/9418 and it will be available with the next patch. For version 2.0 and table inside `@ui5/webcomponents-compat` is fixed with https://github.com/SAP/ui5-webcomponents/pull/9417
