### ISSUE TITLE
[Calendar]: [a11y] Role not inside the required context

### ISSUE THREAD

**Issue by ok** [SAP/ui5-webcomponents#9068]
### Bug Description

a11y testing tool reports "Role not inside the required context" in view when selecting calendar year.

![image](https://github.com/SAP/ui5-webcomponents/assets/54379826/478c386b-3257-4e47-b9d7-49f5abd57db6)

### Affected Component

Calendar

### Steps to Reproduce

1. Run a11y testing tool 
2. navigate to view for selecting calendar year

### Priority

Medium

### UI5 Web Components Version

1.24

### Browser

Chrome

### Operating System

Windows 10/11

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by plamenivanov91** [comment]
Hello @SAP/ui5-webcomponents-topic-b,

Could you please look into this accessibility issue?

Regards,
Plamen Ivanov
