### ISSUE TITLE
Wizard: onStepChange is called to early for large wizard content

### ISSUE THREAD

**Issue by ChewbaccaCookie** [SAP/ui5-webcomponents#9083]
### Describe the bug

If the wizard content gets to large in a step, the `onStepChange` callback is executed to early. This is a problem especially if you use the SIngleStep content layout, because the component will switch to the next step, before the user can scroll to the bottom.

### Isolated Example

https://stackblitz.com/edit/github-rn2kg4?file=src%2FApp.tsx

### Reproduction steps

1. Create a big content in a wizard step
2. Set the contentLayout to singleStep
3. Scroll down to the bottom

### Expected Behaviour

That the user can scroll to the bottom, without switching the step. Especially in the SingleStep content layout.

### Screenshots or Videos

https://github.com/SAP/ui5-webcomponents-react/assets/15861250/df3a1428-0b92-4951-adde-2cd37defb33a

### UI5 Web Components for React Version

1.24.3

### UI5 Web Components Version

1.28.0

### Browser

Chrome, Edge, Firefox, Safari

### Organization

SAP T&I

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by plamenivanov91** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

The Wizard goes to its next page when scrolled to bottom.

I couldn't reproduce it locally, but it's easily reproducible with the provided snippet which uses 1.24.

Is this expected behavior ?

Regards,
Plamen Ivanov

**Comment by ksblklu02** [comment]
Hi @plamenivanov91 
Do we have any updates on this issue?
