### ISSUE TITLE
[SF_ACC][FileUploader]: Input change did not trigger the onChange callback

### ISSUE THREAD

**Issue by ksblklu02** [SAP/ui5-webcomponents#9091]
### Bug Description

When use tabbing to the fileuploader input and type text, the `onChange` function of the FileUploader is not triggered.

### Affected Component

ui5-file-uploader

### Expected Behaviour

When use tabbing to the FileUploader input and type in text, the `onChange` function of the FileUploader should be triggered correctly.

### Isolated Example

https://stackblitz.com/edit/github-utmbsj?file=src%2FApp.tsx

### Steps to Reproduce

1. Go to https://stackblitz.com/edit/github-utmbsj?file=src%2FApp.tsx
2. Click "open dialog" button
3. Tabbing to the file uploader input and type in text
4.  Observe the onChange callback of the uploader is not triggered.

### Priority

Medium

### UI5 Web Components Version

1.24.0

### Browser

Chrome

### Operating System

Mac OS

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by plamenivanov91** [comment]
Hello @SAP/ui5-webcomponents-topic-b,

The reporter complains that the `change` event is not fired when typing in the file uploader's input field.

I believe the change event is supposed to be fired only when applying a valid path, and not on any typed character. Thus the event is fired when needed.

Can you please confirm this?

Regards,
Plamen Ivanov

**Comment by unazko** [comment]
Hello @ksblklu02,

@plamenivanov91 has a point.
It shouldn't be possible to place the focus into the `ui5-file-uploader` input field and type in it
similar to how the native input `type="file"` behaves.
We should correct this as typed values into the input field couldn't represent a local system file path.

I'm closing the incident as there another one for the tab interaction with the `ui5-file-uploader`:
https://github.com/SAP/ui5-webcomponents/issues/9090

Also please refer to the following documentation about the content slot:
https://sap.github.io/ui5-webcomponents/components/FileUploader/#slots
It is not recommended to not use an interactive element into the content slot as then the `ui5-file-uploader` component won't be reachable via keyboard.

Best regards,
Boyan
