### ISSUE TITLE
[Feature Request]: Render content of all steps when open Wizard

### ISSUE THREAD

**Issue by i323808** [SAP/ui5-webcomponents#9105]
### Feature Request Description

Our form has many fields grouped in 3 steps. Now user can import data from other modules to fill the whole form at once. So we need render all fields but the selected step is still Step 1 when open Wizard. Looks like below screen-shot.
<img width="912" alt="wizard" src="https://github.com/SAP/ui5-webcomponents/assets/30744017/14968bc5-a93c-4b62-a701-ed1017ff447f">

### Proposed Solution

1. Content of all steps are rendered when open Wizard, then user will see all data imported from other modules at once, instead of clicking Next to render Step 2, 3....
2. The selected step is still Step 1.

### Priority

None

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by hristop** [comment]
@i323808 ,

Why would you use Wizard then? Why not render the whole content in a page? 

Best Regards,
Hristo

**Comment by i323808** [comment]
Hi Hristo,

We are using Wizard because the form has many fields and we group these fields in 3 steps. User can fill them step by step. Now there is a new feature, user can import data from other module and fill the whole form at once. So we hope render the whole form in a page and let user know all fields are filled and he can click Save button directly.

BR,
Jane

**Comment by hristop** [comment]
Hi Jane, 

If you use the sample from the playground, you can simply remove the "disabled" attribute of the steps and then all steps will be rendered. Isn't this what you are trying to achieve:
https://sap.github.io/ui5-webcomponents/nightly/play/#eyJpbmRleC5odG1sIjp7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuPCFET0NUWVBFIGh0bWw-XG48aHRtbCBsYW5nPVwiZW5cIj5cblxuXG5cbjxoZWFkPlxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG4gICAgPC9zdHlsZT5cblxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG4gICAgPC9zdHlsZT5cblxuICAgIDxtZXRhIGNoYXJzZXQ9XCJVVEYtOFwiPlxuICAgIDxtZXRhIG5hbWU9XCJ2aWV3cG9ydFwiIGNvbnRlbnQ9XCJ3aWR0aD1kZXZpY2Utd2lkdGgsIGluaXRpYWwtc2NhbGU9MS4wXCI-XG4gICAgPHRpdGxlPlNhbXBsZTwvdGl0bGU-XG48L2hlYWQ-XG5cbjxib2R5IHN0eWxlPVwiYmFja2dyb3VuZC1jb2xvcjogdmFyKC0tc2FwQmFja2dyb3VuZENvbG9yKTsgaGVpZ2h0OiA1MDBweFwiPlxuICAgIDwhLS0gcGxheWdyb3VuZC1mb2xkLWVuZCAtLT5cblxuICAgIDwhLS0gPGRpdiBzdHlsZT1cImhlaWdodDogNzAwcHg7XCI-IC0tPlxuICAgIDx1aTUtd2l6YXJkIGlkPVwid2l6XCI-XG4gICAgICAgIDx1aTUtd2l6YXJkLXN0ZXAgaWNvbj1cInByb2R1Y3RcIiB0aXRsZS10ZXh0PVwiUHJvZHVjdCB0eXBlXCIgc2VsZWN0ZWQ9XCJcIj5cbiAgICAgICAgICAgIDxkaXYgc3R5bGU9XCJkaXNwbGF5OiBmbGV4OyBtaW4taGVpZ2h0OiAyMDBweDsgZmxleC1kaXJlY3Rpb246IGNvbHVtbjtcIj5cbiAgICAgICAgICAgICAgICA8dWk1LXRpdGxlPjEuIFByb2R1Y3QgVHlwZTwvdWk1LXRpdGxlPjxiciAvPlxuICAgICAgICAgICAgICAgIDx1aTUtbWVzc2FnZS1zdHJpcD5cbiAgICAgICAgICAgICAgICAgICAgVGhlIFdpemFyZCBjb250cm9sIGlzIHN1cHBvc2VkIHRvIGJyZWFrIGRvd24gbGFyZ2UgdGFza3MsIGludG8gc21hbGxlciBzdGVwcywgZWFzaWVyIGZvciB0aGUgdXNlciB0b1xuICAgICAgICAgICAgICAgICAgICB3b3JrIHdpdGguXG4gICAgICAgICAgICAgICAgPC91aTUtbWVzc2FnZS1zdHJpcD48YnIgLz5cbiAgICAgICAgICAgICAgICA8dWk1LWxhYmVsPlNlZCBmZXJtZW50dW0sIG1pIGV0IHRyaXN0aXF1ZSB1bGxhbWNvcnBlciwgc2FwaWVuIHNhcGllbiBmYXVjaWJ1c1xuICAgICAgICAgICAgICAgICAgICBzZW0sIHF1aXMgcHJldGl1bSBuaWJoIGxvcmVtIG1hbGVzdWFkYSBkaWFtLiBOdWxsYSBxdWlzIGFyY3UgYWxpcXVldCwgZmV1Z2lhdCBtYXNzYSBzZW1wZXIsIHZvbHV0cGF0XG4gICAgICAgICAgICAgICAgICAgIGRpYW0uIE5hbSB2aXRhZSBhbnRlIHBvc3VlcmUsIG1vbGVzdGllIG5lcXVlIHNpdCBhbWV0LCBkYXBpYnVzIHZlbGl0LiBNYWVjZW5hcyBlbGVpZmVuZCB0ZW1wb3JcbiAgICAgICAgICAgICAgICAgICAgbG9yZW0uIE1hdXJpcyB2aXRhZSBlbGVtZW50dW0gbWksIHNlZCBlbGVpZmVuZCBsaWd1bGEuIE51bGxhIHRlbXBvciB2dWxwdXRhdGUgZG9sb3IsIG5lYyBkaWduaXNzaW1cbiAgICAgICAgICAgICAgICAgICAgcXVhbSBjb252YWxsaXMgdXQuIFByYWVzZW50IHZpdGFlIGNvbW1vZG8gZmVsaXMsIHV0IGlhY3VsaXMgZmVsaXMuIEZ1c2NlIHF1aXMgZWxlaWZlbmQgc2FwaWVuLCBlZ2V0XG4gICAgICAgICAgICAgICAgICAgIGZhY2lsaXNpcyBuaWJoLiBTdXNwZW5kaXNzZSBlc3QgdmVsaXQsIHNjZWxlcmlzcXVlIHV0IGNvbW1vZG8gZWdldCwgZGlnbmlzc2ltIHF1aXMgbWV0dXMuIENyYXNcbiAgICAgICAgICAgICAgICAgICAgZmF1Y2lidXMgY29uc2VxdWF0IGdyYXZpZGEuIEN1cmFiaXR1ciB2aXRhZSBxdWFtIGZlbGlzLiBQaGFzZWxsdXMgYWMgbGVvIGVsZWlmZW5kLCBjb21tb2RvIHRvcnRvclxuICAgICAgICAgICAgICAgICAgICBldCwgdmFyaXVzIHF1YW0uIEFsaXF1YW0gZXJhdCB2b2x1dHBhdC5cbiAgICAgICAgICAgICAgICA8L3VpNS1sYWJlbD5cbiAgICAgICAgICAgIDwvZGl2PlxuICAgICAgICAgICAgPHVpNS1idXR0b24gaWQ9XCJ3aXotdG9TdGVwMlwiIGhpZGRlbiBkZXNpZ249XCJFbXBoYXNpemVkXCI-U3RlcCAyPC91aTUtYnV0dG9uPlxuICAgICAgICA8L3VpNS13aXphcmQtc3RlcD5cbiAgICAgICAgPHVpNS13aXphcmQtc3RlcCBpY29uPVwiaGludFwiIHRpdGxlLXRleHQ9XCJQcm9kdWN0IEluZm9ybWF0aW9uXCI-XG4gICAgICAgICAgICA8ZGl2IHN0eWxlPVwiZGlzcGxheTogZmxleDtmbGV4LWRpcmVjdGlvbjogY29sdW1uXCI-XG4gICAgICAgICAgICAgICAgPHVpNS10aXRsZT4yLiBQcm9kdWN0IEluZm9ybWF0aW9uPC91aTUtdGl0bGU-PGJyIC8-XG4gICAgICAgICAgICAgICAgPHVpNS1sYWJlbD5cbiAgICAgICAgICAgICAgICAgICAgSW50ZWdlciBwZWxsZW50ZXNxdWUgbGVvIHNpdCBhbWV0IGR1aSB2ZWhpY3VsYSwgcXVpcyB1bGxhbWNvcnBlciBlc3QgcHVsdmluYXIuIE5hbSBpbiBsaWJlcm8gc2VtLlxuICAgICAgICAgICAgICAgICAgICBTdXNwZW5kaXNzZSBhcmN1IG1ldHVzLCBtb2xlc3RpZSBhIHR1cnBpcyBhLCBtb2xlc3RpZSBhbGlxdWV0IGR1aS4gRG9uZWMgcHBlbGxlbnRlc3F1ZSBsZW8gc2l0IGFtZXRcbiAgICAgICAgICAgICAgICAgICAgZHVpIHZlaGljdWxhLCBxdWlzIHVsbGFtY29ycGVyIGVzdCBwdWx2aW5hci4gTmFtIGluIGxpYmVybyBzZW0uIFN1c3BlbmRpc3NlIGFyY3UgbWV0dXMsIG1vbGVzdGllIGFcbiAgICAgICAgICAgICAgICAgICAgdHVycGlzIGEsIG1vbGVzdGllIGFsaXF1ZXQgZHVpLiBEb25lYyBwdWx2aW5hciwgc2FwaWVuIGNvcnBlciBldSwgcG9zdWVyZSBtYWxlc3VhZGEgbmlzbC4gSW50ZWdlclxuICAgICAgICAgICAgICAgICAgICBwZWxsZW50ZXNxdWUgbGVvIHNpdCBhbWV0IGR1aSB2ZWhpY3VsYSwgcXVpcyB1bGxhbWNvcnBlciBlc3QgcHVsdmluYXIuIE5hbSBpbiBsaWJlcm8gc2VtLlxuICAgICAgICAgICAgICAgICAgICBTdXNwZW5kaXNzZSBhcmN1IG1ldHVzLCBtb2xlc3RpZSBhIHR1cnBpcyBhLCBtb2xlc3RpZSBhbGlxdWV0IGR1aS4gRG9uZWMgcHVsdmluYXIsIHNhcGllblxuICAgICAgICAgICAgICAgIDwvdWk1LWxhYmVsPlxuICAgICAgICAgICAgICAgIDxkaXYgc3R5bGU9XCJkaXNwbGF5OiBmbGV4OyBmbGV4LWRpcmVjdGlvbjogY29sdW1uO1wiPlxuICAgICAgICAgICAgICAgICAgICA8ZGl2XG4gICAgICAgICAgICAgICAgICAgICAgICBzdHlsZT1cImRpc3BsYXk6IGZsZXg7IGZsZXgtZGlyZWN0aW9uOiByb3c7IGp1c3RpZnktY29udGVudDogZmxleC1lbmQ7IGFsaWduLWl0ZW1zOiBjZW50ZXI7IG1hcmdpbi10b3A6IDFyZW1cIj5cbiAgICAgICAgICAgICAgICAgICAgICAgIDx1aTUtbGFiZWw-TmFtZTwvdWk1LWxhYmVsPlxuICAgICAgICAgICAgICAgICAgICAgICAgPHVpNS1pbnB1dCBwbGFjZWhvbGRlcj1cInByb2R1Y3QgbmFtZS4uLlwiPjwvdWk1LWlucHV0PlxuICAgICAgICAgICAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgICAgICAgICAgICAgPGRpdlxuICAgICAgICAgICAgICAgICAgICAgICAgc3R5bGU9XCJkaXNwbGF5OiBmbGV4OyBmbGV4LWRpcmVjdGlvbjogcm93OyBtYXJnaW4tdG9wOiAxcmVtOyBqdXN0aWZ5LWNvbnRlbnQ6IGZsZXgtZW5kOyBhbGlnbi1pdGVtczogY2VudGVyO1wiPlxuICAgICAgICAgICAgICAgICAgICAgICAgPHVpNS1sYWJlbD5XZWlnaHQ8L3VpNS1sYWJlbD5cbiAgICAgICAgICAgICAgICAgICAgICAgIDx1aTUtaW5wdXQgdmFsdWU9XCIzLjY1XCI-PC91aTUtaW5wdXQ-XG4gICAgICAgICAgICAgICAgICAgIDwvZGl2PlxuICAgICAgICAgICAgICAgICAgICA8ZGl2XG4gICAgICAgICAgICAgICAgICAgICAgICBzdHlsZT1cImRpc3BsYXk6IGZsZXg7IGZsZXgtZGlyZWN0aW9uOiByb3c7IG1hcmdpbi10b3A6IDFyZW07IGp1c3RpZnktY29udGVudDogZmxleC1lbmQ7IGFsaWduLWl0ZW1zOiBjZW50ZXI7XCI-XG4gICAgICAgICAgICAgICAgICAgICAgICA8dWk1LWxhYmVsPk1hbmlmYWN0dXJlcjwvdWk1LWxhYmVsPlxuICAgICAgICAgICAgICAgICAgICAgICAgPHVpNS1zZWxlY3Q-XG4gICAgICAgICAgICAgICAgICAgICAgICAgICAgPHVpNS1vcHRpb24gc2VsZWN0ZWQ9XCJcIj5BcHBsZTwvdWk1LW9wdGlvbj5cbiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8dWk1LW9wdGlvbj5TYW1zdW5nPC91aTUtb3B0aW9uPlxuICAgICAgICAgICAgICAgICAgICAgICAgICAgIDx1aTUtb3B0aW9uPkh1YXdlaTwvdWk1LW9wdGlvbj5cbiAgICAgICAgICAgICAgICAgICAgICAgIDwvdWk1LXNlbGVjdD5cbiAgICAgICAgICAgICAgICAgICAgPC9kaXY-XG4gICAgICAgICAgICAgICAgICAgIDxkaXZcbiAgICAgICAgICAgICAgICAgICAgICAgIHN0eWxlPVwiZGlzcGxheTogZmxleDsgZmxleC1kaXJlY3Rpb246IHJvdzsgbWFyZ2luLXRvcDogMXJlbTsganVzdGlmeS1jb250ZW50OiBmbGV4LWVuZDsgYWxpZ24taXRlbXM6IGNlbnRlcjtcIj5cbiAgICAgICAgICAgICAgICAgICAgICAgIDx1aTUtbGFiZWw-NSB5ZWFycyBndWFyYW50ZWUgaW5jbHVkZWQ8L3VpNS1sYWJlbD5cbiAgICAgICAgICAgICAgICAgICAgICAgIDx1aTUtc3dpdGNoIGlkPVwid2l6LXN3XCI-PC91aTUtc3dpdGNoPlxuICAgICAgICAgICAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgICAgIDwvZGl2PlxuICAgICAgICAgICAgPHVpNS1idXR0b24gaWQ9XCJ3aXotdG9TdGVwM1wiIGhpZGRlbiBkZXNpZ249XCJFbXBoYXNpemVkXCIgPlN0ZXAgMzwvdWk1LWJ1dHRvbj5cbiAgICAgICAgPC91aTUtd2l6YXJkLXN0ZXA-XG4gICAgICAgIDx1aTUtd2l6YXJkLXN0ZXAgaWNvbj1cImFjdGlvbi1zZXR0aW5nc1wiIHRpdGxlLXRleHQ9XCJPcHRpb25zXCI-XG4gICAgICAgICAgICA8ZGl2IHN0eWxlPVwiZGlzcGxheTogZmxleDsgZmxleC1kaXJlY3Rpb246IGNvbHVtbjtcIj5cbiAgICAgICAgICAgICAgICA8dWk1LXRpdGxlPjMuIE9wdGlvbnM8L3VpNS10aXRsZT48YnIgLz5cbiAgICAgICAgICAgICAgICA8dWk1LWxhYmVsPlxuICAgICAgICAgICAgICAgICAgICBJbnRlZ2VyIHBlbGxlbnRlc3F1ZSBsZW8gc2l0IGFtZXQgZHVpIHZlaGljdWxhLCBxdWlzIHVsbGFtY29ycGVyIGVzdCBwdWx2aW5hci4gTmFtIGluIGxpYmVybyBzZW0uXG4gICAgICAgICAgICAgICAgICAgIFN1c3BlbmRpc3NlIGFyY3UgbWV0dXMsIG1vbGVzdGllIGEgdHVycGlzIGEsIG1vbGVzdGllIGFsaXF1ZXQgZHVpLiBEb25lYyBwcGVsbGVudGVzcXVlIGxlbyBzaXQgYW1ldFxuICAgICAgICAgICAgICAgICAgICBkdWkgdmVoaWN1bGEsIHF1aXMgdWxsYW1jb3JwZXIgZXN0IHB1bHZpbmFyLiBOYW0gaW4gbGliZXJvIHNlbS4gU3VzcGVuZGlzc2UgYXJjdSBtZXR1cywgbW9sZXN0aWUgYVxuICAgICAgICAgICAgICAgICAgICB0dXJwaXMgYSwgbW9sZXN0aWUgYWxpcXVldCBkdWkuIERvbmVjIHB1bHZpbmFyLCBzYXBpZW4gY29ycGVyIGV1LCBwb3N1ZXJlIG1hbGVzdWFkYSBuaXNsLiBJbnRlZ2VyXG4gICAgICAgICAgICAgICAgICAgIHBlbGxlbnRlc3F1ZSBsZW8gc2l0IGFtZXQgZHVpIHZlaGljdWxhLCBxdWlzIHVsbGFtY29ycGVyIGVzdCBwdWx2aW5hci4gTmFtIGluIGxpYmVybyBzZW0uXG4gICAgICAgICAgICAgICAgICAgIFN1c3BlbmRpc3NlIGFyY3UgbWV0dXMsIG1vbGVzdGllIGEgdHVycGlzIGEsIG1vbGVzdGllIGFsaXF1ZXQgZHVpLiBEb25lYyBwdWx2aW5hciwgc2FwaWVuXG4gICAgICAgICAgICAgICAgPC91aTUtbGFiZWw-XG4gICAgICAgICAgICAgICAgPHVpNS1tZXNzYWdlLXN0cmlwPlxuICAgICAgICAgICAgICAgICAgICBUaGUgV2l6YXJkIGNvbnRyb2wgaXMgc3VwcG9zZWQgdG8gYnJlYWsgZG93biBsYXJnZSB0YXNrcywgaW50byBzbWFsbGVyIHN0ZXBzLCBlYXNpZXIgZm9yIHRoZSB1c2VyIHRvXG4gICAgICAgICAgICAgICAgICAgIHdvcmsgd2l0aC5cbiAgICAgICAgICAgICAgICA8L3VpNS1tZXNzYWdlLXN0cmlwPjxiciAvPlxuICAgICAgICAgICAgICAgIDxkaXYgc3R5bGU9XCJkaXNwbGF5OiBmbGV4OyBmbGV4LWRpcmVjdGlvbjogY29sdW1uO1wiPlxuICAgICAgICAgICAgICAgICAgICA8ZGl2XG4gICAgICAgICAgICAgICAgICAgICAgICBzdHlsZT1cImRpc3BsYXk6IGZsZXg7IGZsZXgtZGlyZWN0aW9uOiByb3c7IGp1c3RpZnktY29udGVudDogZmxleC1lbmQ7IGFsaWduLWl0ZW1zOiBjZW50ZXI7IG1hcmdpbi10b3A6IDFyZW1cIj5cbiAgICAgICAgICAgICAgICAgICAgICAgIDx1aTUtbGFiZWw-TWFuaWZhY3R1cmUgZGF0ZTwvdWk1LWxhYmVsPlxuICAgICAgICAgICAgICAgICAgICAgICAgPHVpNS1kYXRlLXBpY2tlciBpZD1cIndpei1kcFwiPjwvdWk1LWRhdGUtcGlja2VyPlxuICAgICAgICAgICAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgICAgIDwvZGl2PlxuICAgICAgICAgICAgPHVpNS1idXR0b24gaWQ9XCJ3aXotZmluYWxpemVcIiBkZXNpZ249XCJFbXBoYXNpemVkXCI-RmluYWxpemU8L3VpNS1idXR0b24-XG4gICAgICAgIDwvdWk1LXdpemFyZC1zdGVwPlxuICAgIDwvdWk1LXdpemFyZD5cbiAgICA8IS0tIDwvZGl2PiAtLT5cbiAgICA8IS0tIHBsYXlncm91bmQtZm9sZCAtLT5cbiAgICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCJtYWluLmpzXCI-PC9zY3JpcHQ-XG48L2JvZHk-XG5cbjwvaHRtbD5cbjwhLS0gcGxheWdyb3VuZC1mb2xkLWVuZCAtLT5cbiJ9LCJtYWluLmpzIjp7Im5hbWUiOiJtYWluLmpzIiwiY29udGVudCI6Ii8qIHBsYXlncm91bmQtaGlkZSAqL1xuaW1wb3J0IFwiLi9wbGF5Z3JvdW5kLXN1cHBvcnQuanNcIjtcbi8qIHBsYXlncm91bmQtaGlkZS1lbmQgKi9cbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L1RpdGxlLmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMvZGlzdC9NZXNzYWdlU3RyaXAuanNcIjtcbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L0xhYmVsLmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMvZGlzdC9CdXR0b24uanNcIjtcbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L0lucHV0LmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMvZGlzdC9TZWxlY3QuanNcIjtcbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L09wdGlvbi5qc1wiO1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzL2Rpc3QvRGF0ZVBpY2tlci5qc1wiO1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzL2Rpc3QvU3dpdGNoLmpzXCI7XG5cbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy1maW9yaS9kaXN0L1dpemFyZC5qc1wiO1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzLWZpb3JpL2Rpc3QvV2l6YXJkU3RlcC5qc1wiO1xuXG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMtaWNvbnMvZGlzdC9wcm9kdWN0LmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMtaWNvbnMvZGlzdC9oaW50LmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMtaWNvbnMvZGlzdC9hY3Rpb24tc2V0dGluZ3MuanNcIjtcblxuY29uc3Qgd2l6YXJkV2l6ID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoXCJ3aXpcIik7XG5jb25zdCB3aXphcmRTdyA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKFwid2l6LXN3XCIpO1xuY29uc3Qgd2l6YXJkRHAgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZChcIndpei1kcFwiKTtcbmNvbnN0IHdpemFyZFRvU3RlcDIgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZChcIndpei10b1N0ZXAyXCIpO1xuY29uc3Qgd2l6YXJkVG9TdGVwMyA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKFwid2l6LXRvU3RlcDNcIik7XG5jb25zdCB3aXphcmRGaW5hbGl6ZSA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKFwid2l6LWZpbmFsaXplXCIpO1xuXG53aXphcmRXaXouYWRkRXZlbnRMaXN0ZW5lcihcInN0ZXAtY2hhbmdlXCIsIGZ1bmN0aW9uICgpIHtcbiAgICBjb25zb2xlLmxvZyhldmVudC5kZXRhaWwuc3RlcCk7XG59KTtcbndpemFyZFN3LmFkZEV2ZW50TGlzdGVuZXIoXCJjaGFuZ2VcIiwgZnVuY3Rpb24gKCkge1xuICAgIHdpemFyZFRvU3RlcDMucmVtb3ZlQXR0cmlidXRlKFwiaGlkZGVuXCIpO1xufSk7XG53aXphcmREcC5hZGRFdmVudExpc3RlbmVyKFwiY2hhbmdlXCIsIGZ1bmN0aW9uICgpIHtcbiAgICB3aXphcmRGaW5hbGl6ZS5yZW1vdmVBdHRyaWJ1dGUoXCJoaWRkZW5cIik7XG59KTtcblxud2l6YXJkVG9TdGVwMi5hZGRFdmVudExpc3RlbmVyKFwiY2xpY2tcIiwgZnVuY3Rpb24gKCkge1xuICAgIGRlc2VsZWN0QWxsKHdpemFyZFdpeik7XG4gICAgc2V0U3RlcCh3aXphcmRXaXosIDEpO1xuICAgIHdpemFyZFRvU3RlcDIuc2V0QXR0cmlidXRlKFwiaGlkZGVuXCIsIHRydWUpO1xufSk7XG53aXphcmRUb1N0ZXAzLmFkZEV2ZW50TGlzdGVuZXIoXCJjbGlja1wiLCBmdW5jdGlvbiAoKSB7XG4gICAgZGVzZWxlY3RBbGwod2l6YXJkV2l6KTtcbiAgICBzZXRTdGVwKHdpemFyZFdpeiwgMik7XG4gICAgd2l6YXJkVG9TdGVwMy5zZXRBdHRyaWJ1dGUoXCJoaWRkZW5cIiwgdHJ1ZSk7XG59KTtcbndpemFyZEZpbmFsaXplLmFkZEV2ZW50TGlzdGVuZXIoXCJjbGlja1wiLCBmdW5jdGlvbiAoKSB7XG4gICAgYWxlcnQoXCJEb25lIVwiKTtcbn0pO1xuXG5mdW5jdGlvbiBkZXNlbGVjdEFsbCh3aXphcmQpIHtcbiAgICBBcnJheS5mcm9tKHdpemFyZC5jaGlsZHJlbikuZm9yRWFjaChmdW5jdGlvbihzdGVwKSB7XG4gICAgICAgIHN0ZXAuc2VsZWN0ZWQgPSBmYWxzZTtcbiAgICB9KTtcbn1cbmZ1bmN0aW9uIHNldFN0ZXAod2l6YXJkLCBpZHgpIHtcbiAgICB2YXIgc3RlcCA9IGdldFN0ZXAod2l6YXJkLCBpZHgpO1xuICAgIHN0ZXAuc2VsZWN0ZWQgPSB0cnVlO1xuICAgIHN0ZXAuZGlzYWJsZWQgPSBmYWxzZTtcbn1cbmZ1bmN0aW9uIGdldFN0ZXAod2l6YXJkLCBpZHgpIHtcbiAgICByZXR1cm4gQXJyYXkuZnJvbSh3aXphcmQuY2hpbGRyZW4pW2lkeF07XG59In19


Best Regards,
Hristo

**Comment by i323808** [comment]
Hi Hristo,

That's exactly what our UX expected behavior. 

Thanks a million,
Jane

**Comment by hristop** [comment]
Hi Jane, 

I will close this issue then :) 

Best Regards,
Hristo
