### ISSUE TITLE
 Issue in sap.m.DatePicker

### ISSUE THREAD

**Issue by siyanadicheva** [SAP/ui5-webcomponents#9107]
### Bug Description

Hi,

When I click on the range in the header of the Calendar, the link is not working - nothing happens, it just focuses it.

Link to the issue: https://sap.github.io/ui5-webcomponents/playground/?path=/docs/main-calendar--calendar-overview

### Affected Component

sap.m.DatePicker

### Expected Behaviour

This is how it should look like:

<img width="433" alt="Screenshot 2024-03-07 at 12 27 56" src="https://github.com/SAP/ui5-webcomponents/assets/171549165/1b972ba2-95aa-47ae-9ad8-38b3ba572329">

### Steps to Reproduce

1.
2.
3.
...

### Priority

Medium

### UI5 Web Components Version

https://sap.github.io/ui5-webcomponents/playground/?path=/docs/main-calendar--calendar-overview

### Browser

Chrome

### Operating System

macOS

### Organization

SAP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by unazko** [comment]
Hello @siyanadicheva,

Currently year range selection (and view) is not supported for the `ui5-calendar` component.
We could fix the accessibility issue with the year button and then treat this incident as a feature request.

Best regards,
Boyan
