### ISSUE TITLE
[SF_ACC][Dialog]: Page contains more than one contentinfo landmark with multiple dialog opened

### ISSUE THREAD

**Issue by ksblklu02** [SAP/ui5-webcomponents#9113]
### Bug Description

The AXE dev tools reports error when multiple dialog with footer opened on the page.

### Affected Component

ui5-dialog

### Expected Behaviour

There shouldn't be axe issue when multiple dialog opened

### Isolated Example

https://stackblitz.com/edit/github-utmbsj-paehbn?file=src%2FApp.tsx

### Steps to Reproduce

1. Go to https://stackblitz.com/edit/github-utmbsj-paehbn?file=src%2FApp.tsx
2. Click "open dialog" button
3. Click "open second dialog" button
4. Run axe dev tools and see the issue is reported.

### Log Output, Stack Trace or Screenshots

<img width="1719" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/169342420/dc46e982-1b0a-4cb8-adcc-87c11b21edc0">

### Priority

None

### UI5 Web Components Version

1.24.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by niyap** [comment]
Hello @SAP/ui5-webcomponents-topic-rd,

Could you please check whether the issue reported from AXE tool is a real problem or it is expected?

Thank you in advance!

Kind Regards,
Niya

**Comment by GerganaKremenska** [comment]
Hello @ksblklu02,

Thank you for raising your issue.

A disscussion was  made for landmarks inside modal dialog within the [aria group](https://www.w3.org/2024/01/18-aria-minutes.html#t06).

According to the disccusion each dialog can be treated as a separate page, therefor this is not a real issue

Another thing to point out is that Axe tool complains only when you turn on Best Practices from the settings. 

As stated in [AXE official documentation](https://docs.deque.com/devtools-for-web/4/en/best-practice-and-experimental#testing-against-best-practices) : "Violations of Deque's best practice rules are NOT considered failures. More importantly, expert judgment is required to consider the appropriateness in the context of the application, site, or page goals. Sometimes the best practice accessibility technique isn't applicable or practical for resolving the specific issue."

Threrefore I am closing the incident.

Best Regards,
Gergana
