### ISSUE TITLE
ui5-step-input / 1.24.4

### ISSUE THREAD

**Issue by amaillard-sap** [SAP/ui5-webcomponents#9119]
### Bug Description

TypeError: Cannot read properties of null (reading 'value')

error raised from StepInput.js on

 if (this.value === Number(this.input.value)) {

(this.input is null)

### Affected Component

ui5-step-input

### Expected Behaviour

No error thrown (as it was in 1.23.3)

### Steps to Reproduce

We have wrappers around the web component that are setting the property on the element ; I cannot provide a isolated example to reproduce, but having some defensive code here could be enough.

### Priority

High

### UI5 Web Components Version

1.24.4

### Browser

Chrome

### Additional Context

SBPA is looking to upgrade to 1.24.4 ; our tests have detected regressions on the ui5-step-input.

### Organization

SAP-SBPA

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by niyap** [comment]
Hello @SAP/ui5-webcomponents-topic-b,

Could you please analyse the issue?
It probably comes from that change #8293 

Thank you in advance!

Kind Regards,
Niya
