### ISSUE TITLE
[ui5-combobox]: focus first item on suggestions popover open

### ISSUE THREAD

**Issue by ndeshev** [SAP/ui5-webcomponents#9124]
### Bug Description

When suggestions are opened with the keyboard shortcuts (F4 and ALT+ARROW DOWN) the focus should go to the first non-group header item

### Affected Component

ui5-combobox

### Priority

Medium

### UI5 Web Components Version

Nightly

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by niyap** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

Could you please analyse the problem and provide a fix?

Thank you in advance!

Kind Regards,
Niya

**Comment by nikoletavnv** [comment]
This bug will be fixed with the next stable latest version.

**Comment by nikoletavnv** [comment]
Fixed in main branch with https://github.com/SAP/ui5-webcomponents/pull/8842
