### ISSUE TITLE
ui5-icon alignment issue in Safari

### ISSUE THREAD

**Issue by RubenStoesser** [SAP/ui5-webcomponents#913]
**Describe the bug**
When reducing the size of a ui5-icon the alignment of the SVG within it's container breaks in Safari. The issue is not present in Chrome & Firefox.

Adding "vertical-align: top" to the SVG icon element seemingly fixes the issue and has no negative effect in Chrome & Firefox but I didn't thoroughly test this. 

**To reproduce**
1. Go to https://codesandbox.io/s/ui5-webcomponents-pbulf
2. Works in Chrome & FF, icon alignment wrong in Safari

**Isolated example**
https://codesandbox.io/s/ui5-webcomponents-pbulf

**Expected behavior**
Icon alignment should be consistent across browsers

**Screenshots**
Chrome:
![chrome-icon-bug](https://user-images.githubusercontent.com/50411630/68382934-fa832200-0154-11ea-9022-3b1806210dc9.jpg)
Safari:
![safari-icon-bug](https://user-images.githubusercontent.com/50411630/68382935-fa832200-0154-11ea-88e3-b2bfef36518e.jpg)

**Context**
- UI5 Web Components version: 1.0.0.rc-4
- OS/Platform: Mac OSX
- Browser: Safari 13.0.2

**Affected components** *(if known)*
Icon

**Comment by MapTo0** [comment]
I managed to workaround that by setting `line-height: 10px` I still have no idea why this happens in safari.  I will need some more time to debug.
