### ISSUE TITLE
[DragRegistry]: Regression- dataTransfer.effectAllowed is blocked to "move" due to code in DragRegistry.ts

### ISSUE THREAD

**Issue by nathanbienfait** [SAP/ui5-webcomponents#9131]
### Bug Description

The following line of code (line 14) in [DragRegistry.ts](https://github.com/SAP/ui5-webcomponents/blame/2d9a16b403d9457382eeb5d0d913b463e4c52c6a/packages/base/src/util/dragAndDrop/DragRegistry.ts#L14) is overwriting the dataTransfer.effectAllowed that could be set when using drag & drop events.
Setting it to 'move' on your side blocks the usage of other effects such as 'copy' for example.

This blocks the full usage of drag&drop capabilities for web-components.

Also causing feature regression on our usage of ui5-web-components

### Affected Component

All

### Expected Behaviour

the value dataTransfer.effectAllowed should not be set by the web-components

### Steps to Reproduce

1.
2.
3.
...

### Priority

Very High

### UI5 Web Components Version

v1.24.0-rc.1

### Browser

Chrome

### Organization

SAP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by tzimmermann** [comment]
Any plans to release this soon? Having this bug resolved is quite critical for us, because it broke a drag-and-drop functionality (completely outside of ui5 components).

**Comment by ilhan007** [comment]
Hi Thomas, as we talked offline, the patch has been published few days ago.
