### ISSUE TITLE
[ComboBox|: value state popover is not closed when focus goes out

### ISSUE THREAD

**Issue by TeodorTaushanov** [SAP/ui5-webcomponents#9132]
### Bug Description

ComboBox value state popover is not closed when focus goes out

### Steps to Reproduce

1. Open https://sap.github.io/ui5-webcomponents/nightly/packages/main/test/pages/ComboBox.html
2. Focus a combo box with error value state
3. Press TAB key
Value state popover stays open

### Priority

None

### UI5 Web Components Version

2.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by nikoletavnv** [comment]
This issue was fixed with

**Comment by nikoletavnv** [comment]
This issue was fixed with the following change: #8842
