### ISSUE TITLE
[Dialog] Resize corner has wrong orientation in RTL mode

### ISSUE THREAD

**Issue by ej612** [SAP/ui5-webcomponents#9133]
### Describe the bug

Hi there,

In normal left-to-right mode, the resize corner on a resizable dialog is displayed in the lower right corner. In Right-to-Left mode, it's displayed on the lower left corner. It therefore should (and used to) flip over horizontally to properly align.

Working (1.16.0):
![image](https://github.com/SAP/ui5-webcomponents-react/assets/110408767/ab790699-0a8e-47cb-badf-24dc6b77afbc)

Broken (1.26.2):
![image](https://github.com/SAP/ui5-webcomponents-react/assets/110408767/e5530fe2-7786-45b2-8624-1df2a308ee5d)

Thanks in advance!

### Isolated Example

https://stackblitz.com/edit/github-h7fbl3?file=src%2FApp.tsx

### UI5 Web Components for React Version

1.26.2

### UI5 Web Components Version

1.23.3

### Browser

Chrome

**Comment by niyap** [comment]
Hello @SAP/ui5-webcomponents-topic-rd,

When we have a resizable ui5-dialog in rtl mode, the resize icon is misaligned. 
Could you please analyse the issue?

Thank you in advance!

Kind Regards,
Niya

**Comment by LidiyaGeorgieva** [comment]
Hello @SAP/ui5-webcomponents-topic-core,
According to the documentation there should be no difference if we set dir="rtl" to the **html** or to the **body** element:
https://sap.github.io/ui5-webcomponents/docs/advanced/RTL-and-compact-mode/#setting-rtl
But there is - setting the dir="rtl" to the **html** element doesn't visualize the icons in RTL mode.
You can test this locally here: http://localhost:8080/packages/main/test/pages/Icon.html
![image](https://github.com/SAP/ui5-webcomponents/assets/7242508/7f5e6e84-ea7f-4834-9024-c3fa2e26c305)
![image](https://github.com/SAP/ui5-webcomponents/assets/7242508/67ef75bd-de8e-4c6d-b2c5-5fb6f1c2fd7c)

![image](https://github.com/SAP/ui5-webcomponents/assets/7242508/44adf611-7b16-482a-a2ed-1138755553af)
![image](https://github.com/SAP/ui5-webcomponents/assets/7242508/e32a5723-122e-4866-8458-bc1c94f4070d)

and LTR for reference:
![image](https://github.com/SAP/ui5-webcomponents/assets/7242508/d5fe8319-aa84-4fdd-858e-f26ccdee0aa3)


Could you please have a look?

Best Regards,
Lidiya

**Comment by nnaydenow** [comment]
Fixed with #9202 in 2.0 version and with #9211 in version latest 1.24
