### ISSUE TITLE
Shellbar: The logo should not be should as a button if there are no actions are to be performed on it

### ISSUE THREAD

**Issue by pppwr7** [SAP/ui5-webcomponents#9135]
### Is your feature request related to a problem?

Hi Colleagues,
We have a requirement that the SAP logo is to be shown in the shellbar. However, there would be not action performed on clicking on it. So, it should be shown as just an image which is non-interactable.

### Describe the solution you'd like

it should be shown as just an image which is non-interactable.

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by niyap** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

Could you please check and analyse that feature request?

Thank you in advance!

Kind Regards,
Niya

**Comment by pppwr7** [comment]
Hi Colleagues, Could you please let me know if there are any updates on this?

**Comment by dobrinyonkov** [comment]
Hi @pppwr7,

The `ui5-shellbar` is being redesigned according to a new UX and VD specification. The logo will no longer be interactive on its own; instead, it will be combined with the `primary-title` into a single interactive element. Additionally, a new "lean" mode  will be introduced, where this combined area will not be clickable. In this lean mode, the shellbar will have fewer features:

![image](https://github.com/SAP/ui5-webcomponents/assets/22766569/69204ca6-ee87-4543-b987-e4c9c71e78b5)

Essentially, the "lean" mode is shown in the second shellbar of the image above. **Let us know if that would meet your requirements**. If not, we kindly ask you to provide more details about your use case. 

Why do you need the Logo as static (non-clickable)? 
Do you offer other means to navigate back to your app's Home page? 
Perhaps, you have a page bar above the shellbar?

We will share those details with the design owners.

Thanks and Regards,
Dobrin

**Comment by pppwr7** [comment]
Hi Colleagues,

Apologies for the delayed reply.

Please let me know when the lean mode of the shell bar would be available to use.

As per our requirement, we don't have a home page. So, we don't need the logo to be clickable. We show a side navigation panel, listing a range of apps available. This panel could be opened using the startButton of shellbar. We also have other action buttons in  our shell bar. These are added using ShellBarItem control.

Please let me know if any further details is needed from our end.

Regards,
Priya
