### ISSUE TITLE
Icon color is not as designed

### ISSUE THREAD

**Issue by katapp** [SAP/ui5-webcomponents#9138]
Hi,

accordingly to the design guidelines
https://wiki.one.int.sap/wiki/pages/viewpage.action?pageId=2698916049

the file icon on the very left of a list item should be grey instead of black.
https://sap.github.io/ui5-webcomponents/components/fiori/UploadCollection/

Best regards
Kathrin

**Comment by niyap** [comment]
Hello @katapp,

The icon is ui5-icon which is set as a slot "thumbnail" of the ui5-upload-collection-item. You can control the color used as there is CSS part provided for such use cases: https://sap.github.io/ui5-webcomponents/components/Icon/#css-parts or using the "design" property of the ui5-icon setting its value to "Neutral" for example.

Kind Regards,
Niya

**Comment by katapp** [comment]
Hi Niya
thank you for the quick answer, that helped :)
Still, I think the default color should be grey instead of black as specified in the global fiori guidelines. Maybe you can discuss with your team. But the ticket can be closed.
Have a nice day, best regards, Kathrin
