### ISSUE TITLE
Combobox, multicombobox, select: user is unable to filter on both the text and additional text prop fields

### ISSUE THREAD

**Issue by pppwr7** [SAP/ui5-webcomponents#9142]
### Describe the bug

As per customer requirement, whenever user enters a letter in combobox input , he wants to the filtered suggestion dropdown shown to consider additional text data too. currently, the filtering happens only on id prop data.

### Isolated Example

https://stackblitz.com/edit/github-6zne66-fk2sbi?file=src%2FApp.tsx,package.json

### Reproduction steps

1. open the example above
2. in the dropdown input field, type 1
3. no suggestions are shown since 1 is not present as data in any of the id property. However, it is present as a additional text prop data.

### Expected Behaviour

additional text data should also be considered for filtering

### UI5 Web Components for React Version

latest

### UI5 Web Components Version

latest

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ilhan007** [comment]
Moving to RL board (it was in RD by mistake)
