### ISSUE TITLE
Tree (cursor got changed when hovering the tree item)

### ISSUE THREAD

**Issue by jamesPodo** [SAP/ui5-webcomponents#9146]
### Describe the bug

We've noticed that the cursor is changed to pointer when hovering the tree item after updating @ui5wc 1.23.3
@ui5wc-react 1.26.2 . The cursor was not changed on Tree with mode None previously. The issue can also be reproduced from https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-tree--docs
  

### Reproduction steps

1. Enter the above link on the browser
2. Try hovering the tree item
3. Notice the cursor is changed to pointer
4. change the mode from the properties tab (e.g. SingleSelection)
5. change back to None
6. Notice the issue is fix ( cursor is not changed on hovering)

### Expected Behaviour

The cursor should not change when hovering tree item on the Tree with mode None.

### UI5 Web Components for React Version

1.26.2

### UI5 Web Components Version

1.23.3

### Browser

Chrome

### Operating System

Mac

### Organization

SAP SE

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by niyap** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

Could you please analyse the issue? It can be easily reproduced in the sample provided by Lukas: [sample](https://sap.github.io/ui5-webcomponents/play/#eyJpbmRleC5odG1sIjp7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuPCFET0NUWVBFIGh0bWw-XG48aHRtbCBsYW5nPVwiZW5cIj5cblxuXG48aGVhZD5cbiAgICBcbiAgICA8c3R5bGU-XG4gICAgICAqOm5vdCg6ZGVmaW5lZCkge1xuICAgICAgICBkaXNwbGF5OiBub25lO1xuICAgICAgfVxuICAgIDwvc3R5bGU-XG5cbiAgICBcbiAgICA8c3R5bGU-XG4gICAgICAqOm5vdCg6ZGVmaW5lZCkge1xuICAgICAgICBkaXNwbGF5OiBub25lO1xuICAgICAgfVxuICAgIDwvc3R5bGU-XG5cbiAgICA8bWV0YSBjaGFyc2V0PVwiVVRGLThcIj5cbiAgICA8bWV0YSBuYW1lPVwidmlld3BvcnRcIiBjb250ZW50PVwid2lkdGg9ZGV2aWNlLXdpZHRoLCBpbml0aWFsLXNjYWxlPTEuMFwiPlxuICAgIDx0aXRsZT5TYW1wbGU8L3RpdGxlPlxuPC9oZWFkPlxuPGJvZHkgc3R5bGU9XCJiYWNrZ3JvdW5kLWNvbG9yOiB2YXIoLS1zYXBCYWNrZ3JvdW5kQ29sb3IpO1wiPlxuPCEtLSBwbGF5Z3JvdW5kLWZvbGQtZW5kIC0tPlxuXG4gIDxidXR0b24gaWQ9XCJidG5cIj5Ub2dnbGUgTW9kZTwvYnV0dG9uPlxuPHVpNS10cmVlIGlkPVwidHJlZVwiPlxuICAgIDx1aTUtdHJlZS1pdGVtIGV4cGFuZGVkIHRleHQ9XCJUcmVlIDFcIiBpY29uPVwicGFzdGVcIiBzZWxlY3RlZD5cblx0XHQ8dWk1LXRyZWUtaXRlbSBleHBhbmRlZCB0ZXh0PVwiVHJlZSAxLjFcIiBzZWxlY3RlZD5cblx0XHRcdDx1aTUtdHJlZS1pdGVtIHRleHQ9XCJUcmVlIDEuMS4xXCI-PC91aTUtdHJlZS1pdGVtPlxuXHRcdFx0PHVpNS10cmVlLWl0ZW0gdGV4dD1cIlRyZWUgMS4xLjJcIj48L3VpNS10cmVlLWl0ZW0-XG5cdFx0PC91aTUtdHJlZS1pdGVtPlxuXHQ8L3VpNS10cmVlLWl0ZW0-XG5cblx0PHVpNS10cmVlLWl0ZW0gdGV4dD1cIlRyZWUgMlwiIGljb249XCJjb3B5XCI-XG5cdFx0PHVpNS10cmVlLWl0ZW0gdGV4dD1cIlRyZWUgMi4xXCI-XG5cdFx0XHQ8dWk1LXRyZWUtaXRlbSB0ZXh0PVwiVHJlZSAyLjEuMVwiPjwvdWk1LXRyZWUtaXRlbT5cblxuXHRcdFx0PHVpNS10cmVlLWl0ZW0gdGV4dD1cIlRyZWUgMi4xLjJcIj5cblx0XHRcdFx0PHVpNS10cmVlLWl0ZW0gdGV4dD1cIlRyZWUgMi4xLjIuMVwiPjwvdWk1LXRyZWUtaXRlbT5cblx0XHRcdFx0PHVpNS10cmVlLWl0ZW0gdGV4dD1cIlRyZWUgMi4xLjIuMlwiPjwvdWk1LXRyZWUtaXRlbT5cblx0XHRcdFx0PHVpNS10cmVlLWl0ZW0gdGV4dD1cIlRyZWUgMi4xLjIuM1wiPjwvdWk1LXRyZWUtaXRlbT5cblx0XHRcdFx0PHVpNS10cmVlLWl0ZW0gdGV4dD1cIlRyZWUgMi4xLjIuNVwiPjwvdWk1LXRyZWUtaXRlbT5cblx0XHRcdDwvdWk1LXRyZWUtaXRlbT5cblx0XHQ8L3VpNS10cmVlLWl0ZW0-XG5cblx0XHQ8dWk1LXRyZWUtaXRlbSB0ZXh0PVwiVHJlZSAyLjJcIj48L3VpNS10cmVlLWl0ZW0-XG4gICAgPC91aTUtdHJlZS1pdGVtPlxuXG5cdDx1aTUtdHJlZS1pdGVtIGV4cGFuZGVkIHRleHQ9XCJUcmVlIDMgKG5vIGljb24pXCI-PC91aTUtdHJlZS1pdGVtPlxuPC91aTUtdHJlZT5cbjwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuICAgIDxzY3JpcHQgdHlwZT1cIm1vZHVsZVwiIHNyYz1cIm1haW4uanNcIj48L3NjcmlwdD5cbjwvYm9keT5cbjwvaHRtbD5cbjwhLS0gcGxheWdyb3VuZC1mb2xkLWVuZCAtLT5cblxuIn0sIm1haW4uanMiOnsibmFtZSI6Im1haW4uanMiLCJjb250ZW50IjoiLyogcGxheWdyb3VuZC1oaWRlICovXG5pbXBvcnQgXCIuL3BsYXlncm91bmQtc3VwcG9ydC5qc1wiO1xuLyogcGxheWdyb3VuZC1oaWRlLWVuZCAqL1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzL2Rpc3QvVHJlZS5qc1wiO1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzL2Rpc3QvVHJlZUl0ZW0uanNcIjtcblxuY29uc3QgdHJlZSA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCd0cmVlJyk7XG5kb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnYnRuJykuYWRkRXZlbnRMaXN0ZW5lcignY2xpY2snLCAoKSA9PiB7XG4gIGlmICh0cmVlLm1vZGUgPT09ICdOb25lJykge1xuICAgIHRyZWUubW9kZSA9ICdTaW5nbGVTZWxlY3QnO1xuICB9IGVsc2Uge1xuICAgIHRyZWUubW9kZSA9ICdOb25lJztcbiAgfVxufSk7XG5cbiJ9fQ)

Thank you in advance!

Kind Regards,
Niya
