### ISSUE TITLE
[ui5-multi-combobox] open properly is badly named

### ISSUE THREAD

**Issue by amaillard-sap** [SAP/ui5-webcomponents#9169]
### Bug Description

The 'open' property is named '_open' in the DOM

### Affected Component

MultiCombobox

### Expected Behaviour

The 'open' property should be named 'open'

### Isolated Example

Can be observed on the documentation (https://sap.github.io/ui5-webcomponents/playground/?path=/docs/main-multi-combo-box--multi-combo-box-overview)

### Steps to Reproduce

1. Create a MultiCombobox
2. Open it
3. Observe the element properties in the DOM

### Log Output, Stack Trace or Screenshots

![image](https://github.com/SAP/ui5-webcomponents/assets/163414545/45e6ea4f-3bd0-41af-a739-5ab7c5552a3a)

### Priority

Medium

### UI5 Web Components Version

1.24.4

### Browser

Chrome

### Organization

SBPA

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by nnaydenow** [comment]
Hi @amaillard-sap,

Property open is meant to be readonly which means that it doesn't have respective attribute. Readonly properties are meant to be used only in programatic way for example: `mcb.open`. Seems like the documentation should be adjusted and to display readonly property as such.

**Comment by nnaydenow** [comment]
Fixed with: https://github.com/SAP/ui5-webcomponents/pull/9278
