### ISSUE TITLE
[SegmentedButtonItem (2.0.0-rc.5)]: item is missing margin between icon and text

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#9172]
### Bug Description

This is a regression in v2.0.0-rc.5. The icon inside a SegmentedButtonItem doesn't include a margin anymore:

v1.24.4:
![image](https://github.com/SAP/ui5-webcomponents/assets/9749730/445625ca-0adb-4e2a-b1fb-d4ee892c0a00)
https://stackblitz.com/edit/github-9rdfm1?file=index.html,main.js,package.json

v2.0.0-rc.5:
![image](https://github.com/SAP/ui5-webcomponents/assets/9749730/71146009-bde5-430e-9a09-3458bdb5d08b)
https://stackblitz.com/edit/github-9rdfm1-f76m3t?file=index.html,main.js,package.json

### Affected Component

SegmentedButtonItem

### Isolated Example

https://stackblitz.com/edit/github-9rdfm1-f76m3t?file=index.html,main.js,package.json

### Steps to Reproduce

1. Go to [StackBlitz](https://stackblitz.com/edit/github-9rdfm1-f76m3t?file=index.html,main.js,package.json)
2. See that the icon is too close to the text of the button

### Priority

None

### UI5 Web Components Version

v2.0.0-rc.5

### Browser

Chrome

### Organization

UI5WCR

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-b I think it's a highly visible  visual degradation that needs to be fixed
