### ISSUE TITLE
[BarcodeScannerDialog (v2.0.0-rc.5)]: `close` event is not called and `open` not removed when closing via ESC

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#9177]
### Bug Description

This only happens with v2.0.0-rc.5. 
When closing the `BarcodeScannerDialog` via ESC press, the `close` event is not called and also the `open` attribute is not removed leading to an inaccessible state of the popover.

### Affected Component

BarcodeScannerDialog

### Isolated Example

https://stackblitz.com/edit/github-hkau5h?file=index.html,main.js,package.json

### Steps to Reproduce

1. Go to [StackBlitz](https://stackblitz.com/edit/github-hkau5h?file=index.html,main.js,package.json)
2. Open the browser's dev tools console
3. Open the dialog by pressing the button
4. Close the dialog by pressing the "Close" button --> `close` event is fired, `open` attribute removed
5. Open the dialog again
6. Close the dialog by pressing the "Escape" key --> `close` event isn't fired, `open` attribute persists

### Priority

None

### UI5 Web Components Version

UI5WCR

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-p it's a high importance issue related to the 2.0 refactoring
