### ISSUE TITLE
[MessageStrip (v2.0.0-rc.5)]: changing `design` from value-states to color-set doesn't remove the icon

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#9181]
### Bug Description

If the design property of a `MessageStrip` is changed from any value-state design to any color-set design, the default icon isn't removed.

### Affected Component

MessageStrip

### Isolated Example

https://stackblitz.com/edit/github-4hh5q2?file=package.json,index.html,main.js

### Steps to Reproduce

1. Go to [StackBlitz](https://stackblitz.com/edit/github-4hh5q2?file=package.json,index.html,main.js)
2. Click on the button to change the design of the first two MessageStrips
3. See that the icons of the MessageStrips aren't removed

### Priority

None

### UI5 Web Components Version

v2.0.0-rc.5

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-rl there is a wrong state of the component when setting not initially but later-on.


When the following state is set later-on, f.e. in a click handler:

```ts
document.getElementById('btn').addEventListener('click', () => {
  strip.design = 'ColorSet1';
  strip.colorScheme = '1';
});
```

The default icon remains:
<img width="487" alt="Screenshot 2024-06-12 at 13 13 54" src="https://github.com/SAP/ui5-webcomponents/assets/15702139/aea5558f-5166-4e53-b2c7-c173384a38ca">


The same is not displayed if we set the same props and values in the markup (` <ui5-message-strip design="ColorSet1" color-scheme="1"`):
<img width="481" alt="Screenshot 2024-06-12 at 13 13 58" src="https://github.com/SAP/ui5-webcomponents/assets/15702139/9bbb8c59-076d-4cf1-b60f-31669385814f">
