### ISSUE TITLE
[BarcodeScannerDialog]: camera stays active after dialog is closed

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#9186]
### Bug Description

The camera stays active even after closing the `BarcodeScannerDialog` in some cases. It seems to be related to how fast the dialog is closed after opening it. If I wait a few seconds, the camera is shut down as expected, but when immediately closing the dialog after opening it, it stays active until the respective page is refreshed.

https://github.com/SAP/ui5-webcomponents/assets/9749730/6afd5b2d-9ced-4456-957e-f7b40207adff

### Affected Component

BarcodeScannerDialog

### Isolated Example

https://stackblitz.com/edit/github-hkau5h-ffkx1b?file=index.html,main.js,package.json

### Steps to Reproduce

1. Go to [StackBlitz](https://stackblitz.com/edit/github-hkau5h-ffkx1b?file=index.html,main.js,package.json)
2. Open the dialog by pressing the button
3. Immediately close it again
4. See that the camera stays active even when switching tabs

### Priority

None

### UI5 Web Components Version

1.24.7

### Browser

Chrome

### Additional Context

Tested with:
- Chrome: Version 125.0.6422.142 (Official Build) (arm64)
- OS: macOS 14.5 (23F79)

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @kgogov @petyabegovska 

It turns out that there's an even more prominent bug, that can easily be reproduced. When closing the popover via ESC, the camera is never closed. Also the `open` state is not reset which makes reacting to `open` state changes impossible.

To reproduce the issue, you can use the example I posted above (I updated the dependencies to use the latest v1 version) or go to your [v1 playground](https://sap.github.io/ui5-webcomponents/v1/components/fiori/BarcodeScannerDialog/):
1. Open dialog
2. Close dialog
3. See that the camera stays open even though the dialog is closed
4. See that `open` is never removed (attr) or set to `false` (property)

**Comment by kgogov** [comment]
Hello @Lukas742,

Thank you for bringing this to our attention. We're actively working on resolving the issues with the camera not closing properly and the `open` state not resetting when the popover is closed via ESC. This is a priority for us, and we're committed to delivering a fix as soon as possible.

Additionally, we're excited to share that we’re introducing a new, more efficient method for capturing barcodes. This enhancement will not only address the current bugs but also improve the overall user experience with better barcode detection and scanning capabilities.

You can track our progress on this in the following pull request: [SAP/ui5-webcomponents#9646](https://github.com/SAP/ui5-webcomponents/pull/9646).

Best regards,
Konstantin

**Comment by kgogov** [comment]
Hello @Lukas742,

The merge request SAP/ui5-webcomponents#9646 has been successfully merged.
With these changes, the issue with the active camera should be resolved.

Best regards,
Konstantin
