### ISSUE TITLE
[SF][Feature Request]: Support maximumFileSize property to ui5-file-uploader component

### ISSUE THREAD

**Issue by ksblklu02** [SAP/ui5-webcomponents#9187]
### Feature Request Description

Hi Team
We have many scenarios that when upload file, we need to set the maximum file size limit to the file uploader. Can we support this feature from component side? SAP UI5 FileUploader reference: https://sapui5.hana.ondemand.com/?sap-ui-theme=sap_horizon#/api/sap.ui.unified.FileUploader 

### Proposed Solution

Support maximumFileSize property for fileuploader

### Organization

SAP SuccessFactors

### Priority

Medium

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by TeodorTaushanov** [comment]
Hi @SAP/ui5-webcomponents-topic-b, can you check this feature request?
