### ISSUE TITLE
[SF_ACC][ui5-date-picker]: AXE errors about the ui5-date-picker dialog

### ISSUE THREAD

**Issue by ksblklu02** [SAP/ui5-webcomponents#9189]
### Bug Description

AXE tool has identified some ARIA issues and accessible name on the calendar dialog
1.  Month select dialog & date select dialog:  ARIA dialog and alertdialog node should has an accessible name

<img width="1263" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/169342420/bed86f45-82e4-4403-a2a7-b4efbf0b6306">
<img width="1725" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/169342420/2b5a4e4a-e32c-4d9b-8469-2f07f496d080">

2. Elements with an ARIA role that require child roles contain them
<img width="1717" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/169342420/a63c4912-4956-4cc2-b6d0-d5c1e04ffd6b">

3. Different "open picker" button should have unique aria-label, associated with ui5-date-picker accessibleName

<img width="1720" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/169342420/982db763-5bba-4aff-aa17-841ca7ddda86">

### Affected Component

ui5-date-picker

### Expected Behaviour

1. There should not be AXE Errors
2. "Open picker" button should have aria-label associated with date picker accessibleName

### Isolated Example

https://stackblitz.com/edit/github-pzxshp

### Steps to Reproduce

1. Go to https://stackblitz.com/edit/github-pzxshp
2. Open date picker dialog
3. Run AXE Devtools
5. See there are some issues reported

### Priority

Medium

### UI5 Web Components Version

1.24.0

### Browser

Chrome

### Organization

SAP SuccessFactors

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by unazko** [comment]
Hello @SAP/ui5-webcomponents-topic-b,

There are AXE tool reports for the `ui5-date-picker` component.

Additionally there are already the following PRs that would fix some of the issues:
- https://github.com/SAP/ui5-webcomponents/pull/8693 related to issue 1 - needs a transport (We need to additionally check the alert dialog)
- https://github.com/SAP/ui5-webcomponents/pull/9125 transport done for issue 2

We need to discuss issue 3 with the accessibility experts.

Best regards,
Boyan

**Comment by unazko** [comment]
Hello @ksblklu02,

Transport for issue 1 into 1.24 is done:
https://github.com/SAP/ui5-webcomponents/pull/9221

Best regards,
Boyan

**Comment by unazko** [comment]
Hello @ksblklu02,

The fixes are already done for issue #1 and issue #2 from the report.
Regarding issue #3 we had a discussion among the accessibility expert group and I've got the following as feedback:
- The value help icon has press handler therefore it needs role `button` as specified.
- The value help icon is also hidden from the assistive technologies according to the specification and the following note in the standard: [aria-hidden]( https://www.w3.org/TR/wai-aria-1.2/#aria-hidden). We'll have a visual tooltip, but the redundant label won't be announced in this case as we do have a shortcut announcements to the input field.

AXE tool doesn't report a violation in relation to issue #3 and based on the upper explanations the component behaves as specified.

Best regards.
Boyan
