### ISSUE TITLE
[Feature Request]: Show value state message popover in readonly input fields

### ISSUE THREAD

**Issue by zhangliangyi** [SAP/ui5-webcomponents#9198]
### Feature Request Description

Hi team,
ui5 components right now do not show value state message in readonly fields. But we actually have some case that the readonly field value is calculated by some other fields in the page which still needs the value state message to indicate the calculated value is not correct.
We also received some SNOW tickets from customers about this.

### Proposed Solution

https://github.com/SAP/ui5-webcomponents/blob/a3fd2414b26497b010accd18a0805c2aec163338/packages/main/src/Input.ts#L1532

Maybe we can remove the readonly property check in this if statement to enable the value state message popover.

### Organization

SF

### Additional Context

The solution should be applied to all input fields, such as ui5-input, ui5-date-picker, ui5-select etc.

### Priority

Medium

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by TeodorTaushanov** [comment]
Hi @SAP/ui5-webcomponents-topic-rl, can you check this feature request?

**Comment by hristop** [comment]
Hi @zhangliangyi ,

As this is something that should go through Central Design first, can you please raise a design feature request in the E1 Jira and then post the BLI number here, so we can track it. 

Best Regards,
Hristo

**Comment by zhangliangyi** [comment]
Ok, will do it soon.

**Comment by zhangliangyi** [comment]
Per the feedback from central design team, they just recommend using message-strip or message-box in the issue above.
So close this issue, thanks.
