### ISSUE TITLE
[Dialog]: It's not possible to use CSS width:100%

### ISSUE THREAD

**Issue by mehdijouan** [SAP/ui5-webcomponents#920]
**Describe the bug**
The dialog component does not display a content with a 100% width component.
It seems pretty much the same (but for the height) of https://github.com/SAP/ui5-webcomponents/issues/889
**Isolated example**
https://codesandbox.io/s/vue-template-epsy5?fontsize=14

**Expected behavior**
The three content divs should be separated
**Context**
- UI5 Web Components version 1.0.0.rc4
- OS/Platform: macos
- Other information: use of bootstrap 

**Affected components** *(if known)*
Dialog

**Comment by iamuan** [comment]
How this issue is going on? I've met this issue too.
The content of dialog still does not include width: 100%.

I installed version 0.7.1 of @ui5/webcomponents-react.

**Comment by gnseo** [comment]
Anyone please have a look into the screenshot from https://github.com/SAP/ui5-webcomponents-react/issues/285.

The dialog content is under the shadow dom, so css style from outside can not be affected.
I just need following property for class ".ui5-dialog.content".
```css
.ui5-dialog-content {
  width: "100%";
}
```

**Comment by fifoosid** [comment]
Closing the issue as the PR is merged 😊
