### ISSUE TITLE
[SF][Feature Request][SuggestionItem] Add image fallback

### ISSUE THREAD

**Issue by Jasonl157** [SAP/ui5-webcomponents#9200]
### Is your feature request related to a problem?

Currently, we can add an image to `SuggestionItem` through the `image` property, but it doesn't provide fallback options like showing initials or icon if the image url is invalid.

<img width="202" alt="image" src="https://github.com/SAP/ui5-webcomponents-react/assets/131832797/f6b94126-c9a7-43f5-a12f-891f5d9719db">

### Describe the solution you'd like

Provide an image slot so we can use our own component that validates image url and provides fallback options

### Describe alternatives you've considered

Support image url validation and fallback options

### Organization

SF

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by TeodorTaushanov** [comment]
Hello @SAP/ui5-webcomponents-topic-rl, take a look of this feature request.

**Comment by hristop** [comment]
Hi colleagues, 

I think that this requirement is for the List. 

Best Regards,
Hristo

**Comment by dobrinyonkov** [comment]
This is being worked on via #2052
