### ISSUE TITLE
input: screen reader announces previous search data even when search field is cleared

### ISSUE THREAD

**Issue by achuth2912** [SAP/ui5-webcomponents#9206]
### Describe the bug

After deleting the search input text and access search field again, screen reader announces previous search data and its results.

### Isolated Example

https://sap.github.io/ui5-webcomponents-react/?path=/story/inputs-input--with-suggestion-item

### Reproduction steps

1. Turn ON JAWS and navigate to search field and enter input.
2. using down arrow key select the value from the dropdown list
3. Then clear the value inside the search filed , then focus back on the search field where the screen reader announces the previous results
...

### Expected Behaviour

Whenever search field is accessed, only its name, role and property should be read out as it is read when freshly accessed.
But previous search related information should not be read.

### Screenshots or Videos

https://github.com/SAP/ui5-webcomponents-react/assets/71249041/ada334b7-8554-4b1e-be7b-e9565e9ef9e8

### UI5 Web Components for React Version

1.28.1

### UI5 Web Components Version

1.24.0

### Browser

Chrome

### Operating System

Mac OS

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by kineticjs** [comment]
Hi @achuth2912,

Thank you for reporting this finding. Would you please also give us the version of JAWS that you use when reproducing the issue?

Thanks

**Comment by GerganaKremenska** [comment]
Hello @achuth2912, 

I have tested the Input with suggestions and i am not able to reproduce the issue.  
Please see the attached video and confirm that these are the correct steps.

https://github.com/SAP/ui5-webcomponents/assets/22882174/dfd257f6-acba-43c9-b55d-6e8c426c3cde

Also i  have added the speech out put of the Intput so it is visible that there is no announcment of selected value after returning to the input.

Veersion of JAWS 2024.2312.53
Provide your subversion, maybe there is some Jaws issue.

If some steps are missed to reproduce the issue, please provide them. 

"One more thing to highlight here, if you observe the attached recording when we clear the search there is one div with id="ui5wc_1-selectionText" this div contains some value like "List Item 3 of 6" this is being announced when you again start the search." - this is also not reproducable 

Awaiting your feedback. 

Best Regards,
Gergana
