### ISSUE TITLE
[Feature Request]: Calendar extended overstyling of internals

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents#9209]
### Feature Request Description

One behalf of our colleagues from SAP Marketing&IT, I am creating a request for extended overstyling for:
- calendar month and year views, in particular the font weight of the months/years cells
to make the months/years text bolder
- the hover text and border color for last item in selected range within the day picker
- the text color of items in selected range within the day picker

More details in the comments below.

### Proposed Solution

We need to check if we can expose some parts or variables to make this overstyling possible. Could be more difficult with parts as these are elements deeply nested and part of other internal web components like ui5-month-picker, ui5-year-picker, ui5-day-picker.

### Organization

SAP Marketing & IT (building UDeX web components)

### Priority

None

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ilhan007** [comment]
Hi colleagues,

@SAP/ui5-webcomponents-topic-b 

contact me if you need more information on this.

**Comment by ilhan007** [comment]
FYI @PlutaKatarzyna and as discussed please add the expected state.

**Comment by PlutaKatarzyna** [comment]
Hi @DMihaylova ,

- CSS varibale will be great for text color inside range items.
 
- As for the font weight of items in year/month selection - unfortunately I do not see css variable that you mentioned. Moreover I see that year/month items are not bold anymore. Actually they do not even have any "selected" indicator anymore:
<img width="424" alt="Screenshot 2024-06-24 at 11 08 30" src="https://github.com/SAP/ui5-webcomponents/assets/158282803/22fb4d40-eda1-478f-98bd-ab704d4370ee">
 
Not sure what happened and when did it happen, but apart from font-weight, we need a border it item is currently selected.


- For hover text and border color for last range item - on our designs there is different hover for item if it's inside a range. Also different start and end day of range, and middle day in range hover state.  Here is what we expect to have:
<img width="857" alt="Screenshot 2024-06-24 at 11 30 49" src="https://github.com/SAP/ui5-webcomponents/assets/158282803/760b82a5-20a2-44cb-b8e5-f2f8b8988d55">
This includes changing not only text color and background of hovered item, but also a border.


Best regards
Kate

**Comment by PlutaKatarzyna** [comment]
Hi @DMihaylova , any chance this can be downported also to version 1.24?
