### ISSUE TITLE
[SpecialCalendarDate]: not all types have a visual representation

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#9216]
### Bug Description

When adding a `SpecialCalendarDate` to the `Calendar` component the following public types don't change the visuals of a date:

```
None = "None",
Working = "Working",
NonWorking = "NonWorking",
```

### Affected Component

SpecialCalendarDate, Calendar

### Expected Behaviour

In my understanding, `Working` should make a non-working day such as Saturday look like a normal day and `NonWorking` the opposite.

### Isolated Example

https://stackblitz.com/edit/github-7d2xya?file=main.js,index.html

### Steps to Reproduce

1. Go to [StackBlitz](https://stackblitz.com/edit/github-7d2xya?file=main.js,index.html)
2. In the first example the first 7 days of the month should be marked as "NonWorking" days, but there's no difference to the default design.
3. The second example shows all `CalendarLegendItemType`, but it only shows a visual difference for Type01 - Type20

### Log Output, Stack Trace or Screenshots

<img width="342" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/9749730/1dcc0cc2-aa17-4fe3-9e7e-1984d14f75f3">

### Priority

None

### UI5 Web Components Version

1.24.4

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-b @hinzzx could you follow up : ))
