### ISSUE TITLE
MultiComboBox: A11y - Extra "blank" is read by JAWS screen reader on accessing the Multicombobox

### ISSUE THREAD

**Issue by abhijeet181088** [SAP/ui5-webcomponents#9219]
### Describe the bug

When MultiCombobox is accessed, an extra blank is read by the JAWS screen-reader. (screenshot atatched)

### Isolated Example

https://stackblitz.com/edit/github-lg4jzd-y1tslv?file=src%2FApp.tsx

### Reproduction steps

1. Go to stackblitz link provided
2. Switch on the JAWS screen-reader
3. Navigate to the MultiCombobox
4. An extra "blank" is read by the screen-reader
5.
...

### Expected Behaviour

Extra blank should not be read

### Screenshots or Videos

![MultiComboBox_Blank](https://github.com/SAP/ui5-webcomponents-react/assets/26282517/57dcf567-92a6-44b7-957d-b5b32231903e)

### UI5 Web Components for React Version

1.28.0

### UI5 Web Components Version

1.24.0

### Browser

Chrome, Edge

### Operating System

Windows

### Additional Context

Tested with JAWS

### Organization

SAP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ilhan007** [comment]
Hello colleagues, @SAP/ui5-webcomponents-topic-rl 
there is an extra blank reading  in MultiComboBox, at least in 1.24.x, could you check this a11y issue?

**Comment by elenastoyanovaa** [comment]
Hello,

This is an expected announcement of a input field, when the input field has no textual value inside. It could be easily reproduced in the aria best practice samples as well https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-autocomplete-both/

Even though there might be some tokens inside the multicombobox, they are not real textual values and are not considered part of the input field so this announcement is expected.
