### ISSUE TITLE
[Feature Request]: Date picker should match the width of input Element

### ISSUE THREAD

**Issue by gurkirpalgill** [SAP/ui5-webcomponents#9226]
### Feature Request Description

Date Picker out of the box has different width than the input element. We are using column layout to render form and Date Picker being another input has a different width ( see screenshot). Is there a specific reason it needs to have a different width?

### Proposed Solution

Make Date Picker width same as input element.
![Before_Change](https://github.com/SAP/ui5-webcomponents/assets/65705637/98713d37-72d9-49f3-ab15-ee6e3feefcfd)

### Priority

None

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ilhan007** [comment]
I guess this might has something to do with certain formats in certain locales that could be very long, but we will investigate and come up with a statement. Thank you @gurkirpalgill for raising it : )

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-b @DMihaylova can you check design wise what is the expected result.

Should the ui5-date-picker and ui5-input be with the same width, do we have something in the specs about that?

**Comment by tsanislavgatev** [comment]
Hello @gurkirpalgill ,

I've talked with the ui5-input team and by design the inputs with icons(buttons) inside have higher min-width, because of the combination of input and button.

If needed, you can overstyle the inputs width to match based on the one with highest width.

Best Regards,
Tsanislav
