### ISSUE TITLE
[Segmented Button Item]: Disabled item has focus, hover, pressed states visible

### ISSUE THREAD

**Issue by PlutaKatarzyna** [SAP/ui5-webcomponents#9236]
### Bug Description

When Segmented Button Item is `disabled`, you can see styles of focused, hover and pressed states. 
It does not emit click event. Issue is only visual.
<img width="162" alt="Screenshot 2024-06-18 at 09 06 06" src="https://github.com/SAP/ui5-webcomponents/assets/158282803/3a1b7448-8522-40dc-ba0c-21a27608b9bf">

### Affected Component

ui5-segmented-button-item

### Expected Behaviour

When button has disabled attributes, it does not show focus, pressed, hover states.

### Isolated Example

https://sap.github.io/ui5-webcomponents/components/SegmentedButton/

### Steps to Reproduce

1. Go to ui5 [Segmented Button documentation ](https://sap.github.io/ui5-webcomponents/components/SegmentedButton/)
2. Add `disabled` attribute into `ui5-segmented-button-item` element.
3. Hover and click on disabled item in the preview
4. You can see all states on disabled item

<img width="986" alt="Screenshot 2024-06-18 at 08 46 03" src="https://github.com/SAP/ui5-webcomponents/assets/158282803/ec8f8ac6-0a4a-4761-a3c7-91388fb7783d">

### Priority

Medium

### UI5 Web Components Version

1.24.1

### Browser

Chrome

### Operating System

MacOS

### Additional Context

UDEx Components library extends `ui5-segmented-button-item `component as `udex-control-button`. We are facing this issue there.

### Organization

SAP / UDEx components team

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ilhan007** [comment]
Hello colleagues, @SAP/ui5-webcomponents-topic-b 

the issue can be seen on the nightly deployment as well, setting disabled on segmented button item does not prevent any interactions - focus, hover, etc.
