### ISSUE TITLE
[build]:@ui5/webcomponents to the version later than 1.24.4, npm install would fail on step of patch-package

### ISSUE THREAD

**Issue by johnchen05** [SAP/ui5-webcomponents#9238]
### Bug Description

when we upgrade @ui5/webcomponents to the version later than 1.24.4, npm install would fail on step of patch-package as screenshot shown. 
this return fails our build, so we can not upgrade @ui5/webcomponents the the latest version. would you mind take a look?
![Image 2024-6-18 at 20 29](https://github.com/SAP/ui5-webcomponents/assets/43673963/85e44599-d95f-4ceb-9816-524695347a4b)

### Affected Component

@ui5/webcomponents

### Expected Behaviour

npm install successful

### Steps to Reproduce

1.
2.
3.
...

### Priority

None

### UI5 Web Components Version

1.24.4 -1.24.5

### Browser

Chrome

### Operating System

it can be reproducible in my local MacOS and jenkins VS(linux)

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ilhan007** [comment]
Hi @johnchen05 do you have your own patches on `@ui5/webcomponents`, because the error says that you might have patches on code (for `@ui5/webcomponents`) that's now different (as it was done for older version)?
