### ISSUE TITLE
[DateRangePicker]: Visually conveyed selected state for the dates in the date picker, not conveyed to screen reader users

### ISSUE THREAD

**Issue by ee92** [SAP/ui5-webcomponents#9241]
### Bug Description

As a user selects a date range, the inner dates are not read out as "selected" 

### Affected Component

ui5-daterange-picker

### Expected Behaviour

expect inner dates to be read out as "selected" 

### Steps to Reproduce

1. go to https://sap.github.io/ui5-webcomponents/components/DateRangePicker/
2. use any screen reader 
3. use keyboard to select date range
4. notice inner dates not read out as "selected" even though visually shown as selected

### Log Output, Stack Trace or Screenshots

![image](https://github.com/SAP/ui5-webcomponents/assets/24360164/2d527400-26f1-40ca-95fd-c08acf95db5f)

### Priority

Low

### UI5 Web Components Version

1.24.1

### Browser

Chrome

### Additional Context

Thank you

### Organization

SuccessFactors

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by hinzzx** [comment]
Hi @SAP/ui5-webcomponents-topic-b ,

Can you please take a look at this ? When selecting dates in date-range-picker the screen reader reads only the first and the last selected date, and not those which are inbetween them.

Regards,
Stoyan
