### ISSUE TITLE
[Feature Request]: Text add empty-indicator, render-whitespace and hyphenated attributes

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents#9244]
### Feature Request Description

We would like to replace the UI5 Web Components for React `Text` component with the `ui5-text` web component, but some features are missing which would make the transition harder for us.
This feature request is a follow up to address to open points from https://github.com/SAP/ui5-webcomponents/pull/8299

The `Text` should add support for the following attributes in my opinion:
- [ ] `emptyIndicator` (SAPUI5 uses the `emptyIndicatorMode` with the [EmptyIndicatorMode enum](https://ui5.sap.com/#/api/sap.m.EmptyIndicatorMode) for that)
- [ ] `renderWhitespace`
- [ ] `hyphenated` (SAPUI5 uses `wrappingType` [WrappingType](https://ui5.sap.com/#/api/sap.m.WrappingType) for that)

### Proposed Solution

Add those attributes to the `ui5-text`

### Proposed Alternatives

We can write some documentation in UI5 Web Components for React on how to achieve this desired behaviour by using CSS.

### Organization

UI5 Web Components for React

### Priority

Medium

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-rd  can you check the progress of the design specs, I think all the three features are planned and will be included in the specs, the questions is what is the state of the Text web component specs and can we add these or at least some of the features immediately?

**Comment by ilhan007** [comment]
Hello @MarcusNotheis  the team has added "emptyIndicatorMode" property (released with 2.2.0) and for the white spaces and hyphenation we only provided examples using a little CSS

https://sap.github.io/ui5-webcomponents/components/Text/#empty-indicator-mode
https://sap.github.io/ui5-webcomponents/components/Text/#hyphenation-with-custom-styling
https://sap.github.io/ui5-webcomponents/components/Text/#render-white-space-with-custom-styling
