### ISSUE TITLE
[Table]: cyclic import between `TableRow` and `Table`

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents#9247]
### Bug Description

We're just about to upgrade to the new `Table` component in 2.0.0-rc.6 and found that there is a cyclic import between the `Table` and the `TableRow`. As soon as the `TableRow` is imported, the application is crashing with the following error:
```
chunk-K4DDKURV.js?v=10bd6633:2540 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'define')
    at chunk-K4DDKURV.js?v=10bd6633:2540:70
    at Array.map (<anonymous>)
    at Table2.whenDependenciesDefined (chunk-K4DDKURV.js?v=10bd6633:2540:53)
    at Table2.define (chunk-K4DDKURV.js?v=10bd6633:2557:12)
```

As soon as the `TableRow` is removed again, the application is working fine.

### Affected Component

Table, TableRow

### Expected Behaviour

App should not crash

### Isolated Example

https://stackblitz.com/edit/github-ebd5kn?file=package.json,index.html,main.js%3AL4

### Steps to Reproduce

1. Open the stackblitz and see the error
2. If you remove the `TableRow` import and reload the page it's working fine

### Log Output, Stack Trace or Screenshots

```
chunk-K4DDKURV.js?v=10bd6633:2540 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'define')
    at chunk-K4DDKURV.js?v=10bd6633:2540:70
    at Array.map (<anonymous>)
    at Table2.whenDependenciesDefined (chunk-K4DDKURV.js?v=10bd6633:2540:53)
    at Table2.define (chunk-K4DDKURV.js?v=10bd6633:2557:12)
```

### Priority

High

### UI5 Web Components Version

2.0.0-rc.6

### Browser

Chrome, Edge

### Organization

UI5 Web Components for React

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by hinzzx** [comment]
Hi colleagues,

@SAP/ui5-webcomponents-topic-core , when importing TableRow, the app crashes. The issue is reproducible in the provided sample. When removing the `import '@ui5/webcomponents/dist/TableRow.js';` line upon page reload the table is rendered and the app is not crashing. Could you please take a look.

Regards,
Stoyan
