### ISSUE TITLE
[DynamicPage (v2.0.0-rc.6)]: outline recommended `font-size` of `heading` in docs

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#9253]
At the moment I don't think it's described clearly enough how to adjust the font-size of the `heading` to the recommended values. The relevant CSS variables can be found in the code examples, but it's probably worth mentioning them more clearly in the docs. E.g. in the description of the `heading` slot.

CSS Vars:
- expanded: `'var(--sapObjectHeader_Title_FontSize)'`
- collapsed: `'var(--sapObjectHeader_Title_SnappedFontSize)'`

**Comment by hinzzx** [comment]
Hey colleagues,

@SAP/ui5-webcomponents-topic-p, could you please take a look at this recommendation from our colleague, about enhancing the documentation of our DynamicPage component ? :)

Kind Regards,
Stoyan

**Comment by dobrinyonkov** [comment]
Internal Reference: BGSOFUIPIRIN-6587

**Comment by Lukas742** [comment]
Hi,
I've noticed that the information is now exposed in the documentation: https://sap.github.io/ui5-webcomponents/components/fiori/DynamicPageTitle/#heading

So, this issue can probably be closed, right?

**Comment by dobrinyonkov** [comment]
Hi @Lukas742 , that's correct, thanks for reminding!
