### ISSUE TITLE
[ViewSettingsDialog]: sort list is rendered without radio buttons on initial rendering

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents#9266]
### Bug Description

The sort list is rendered without radio buttons on initial rendering, but after you switch to filter items and go back - the radio buttons are displayed. See the attached video

https://github.com/SAP/ui5-webcomponents/assets/15702139/0a863015-c1b8-4f5c-acc5-911c55524ca7

### Steps to Reproduce

1.
2.
3.
...

### Priority

None

### UI5 Web Components Version

nightly

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-b could you check the described issue?

The initial state of the sort list looks wrong as at first there are no radio buttons displayed, but after you switch to filters and get back, the sort list starts displaying radio buttons.

**Comment by tsanislavgatev** [comment]
Hi colleagues @SAP/ui5-webcomponents-topic-p ,

Can you please check this issue? It's related to dynamically adding items to the group in the list.
A sample to reproduce -> [Link](https://sap.github.io/ui5-webcomponents/nightly/play/#eyJpbmRleC5odG1sIjp7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuPCFET0NUWVBFIGh0bWw-XG48aHRtbCBsYW5nPVwiZW5cIj5cblxuXG5cblxuPGhlYWQ-XG4gICAgXG4gICAgPHN0eWxlPlxuICAgICAgKjpub3QoOmRlZmluZWQpIHtcbiAgICAgICAgZGlzcGxheTogbm9uZTtcbiAgICAgIH1cbiAgICA8L3N0eWxlPlxuXG4gICAgXG4gICAgPHN0eWxlPlxuICAgICAgKjpub3QoOmRlZmluZWQpIHtcbiAgICAgICAgZGlzcGxheTogbm9uZTtcbiAgICAgIH1cbiAgICA8L3N0eWxlPlxuXG4gICAgXG4gICAgPHN0eWxlPlxuICAgICAgKjpub3QoOmRlZmluZWQpIHtcbiAgICAgICAgZGlzcGxheTogbm9uZTtcbiAgICAgIH1cbiAgICA8L3N0eWxlPlxuXG4gICAgPG1ldGEgY2hhcnNldD1cIlVURi04XCI-XG4gICAgPG1ldGEgbmFtZT1cInZpZXdwb3J0XCIgY29udGVudD1cIndpZHRoPWRldmljZS13aWR0aCwgaW5pdGlhbC1zY2FsZT0xLjBcIj5cbiAgICA8dGl0bGU-U2FtcGxlPC90aXRsZT5cbiAgICA8bGluayByZWw9XCJzdHlsZXNoZWV0XCIgaHJlZj1cIi4vbWFpbi5jc3NcIj5cbjwvaGVhZD5cblxuPGJvZHkgc3R5bGU9XCJiYWNrZ3JvdW5kLWNvbG9yOiB2YXIoLS1zYXBCYWNrZ3JvdW5kQ29sb3IpOyBoZWlnaHQ6IDQ1MHB4O1wiPlxuICAgIDwhLS0gcGxheWdyb3VuZC1mb2xkLWVuZCAtLT5cblxuICAgIDx1aTUtYnV0dG9uIGlkPVwiZGlhbG9nT3BlbmVyXCI-T3BlbiBEaWFsb2c8L3VpNS1idXR0b24-XG5cbiAgICA8dWk1LWRpYWxvZyBpZD1cImRpYWxvZ1wiPlxuICAgICAgICAgICAgPHVpNS1saXN0XG5cdFx0XHRzZWxlY3Rpb24tbW9kZT1cIlNpbmdsZVN0YXJ0XCI-XG5cdFx0XHQ8dWk1LWxpLWdyb3VwIGhlYWRlci10ZXh0PVwiZ3JvdXAgZHluYW1pY1wiPlxuXHRcdFx0PC91aTUtbGktZ3JvdXA-XG5cdFx0XHQ8dWk1LWxpLWdyb3VwIGhlYWRlci10ZXh0PVwiZ3JvdXAgc3RhdGljXCI-XG5cdFx0XHRcdDx1aTUtbGk-QWN0aXZlIGl0ZW0gLSBzdGF0aWM8L3VpNS1saT5cblx0XHRcdFx0PHVpNS1saT5BY3RpdmUgaXRlbSAtIHN0YXRpYzwvdWk1LWxpPlxuXHRcdFx0PC91aTUtbGktZ3JvdXA-XG5cdFx0PC91aTUtbGlzdD5cbiAgICA8L3VpNS1kaWFsb2c-XG4gICAgPCEtLSBwbGF5Z3JvdW5kLWZvbGQgLS0-XG4gICAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwibWFpbi5qc1wiPjwvc2NyaXB0PlxuPC9ib2R5PlxuXG48L2h0bWw-XG48IS0tIHBsYXlncm91bmQtZm9sZC1lbmQgLS0-XG4ifSwibWFpbi5qcyI6eyJuYW1lIjoibWFpbi5qcyIsImNvbnRlbnQiOiIvKiBwbGF5Z3JvdW5kLWhpZGUgKi9cbmltcG9ydCBcIi4vcGxheWdyb3VuZC1zdXBwb3J0LmpzXCI7XG4vKiBwbGF5Z3JvdW5kLWhpZGUtZW5kICovXG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMvZGlzdC9EaWFsb2cuanNcIjtcbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L0J1dHRvbi5qc1wiO1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzL2Rpc3QvSW5wdXQuanNcIjtcbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L0xpbmsuanNcIjtcbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L0xhYmVsLmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMvZGlzdC9MaXN0LmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMvZGlzdC9MaXN0SXRlbVN0YW5kYXJkLmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMvZGlzdC9MaXN0SXRlbUdyb3VwLmpzXCI7XG5cbnZhciBkaWFsb2dPcGVuZXIgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZChcImRpYWxvZ09wZW5lclwiKTtcbnZhciBkaWFsb2cgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZChcImRpYWxvZ1wiKTtcblxuZGlhbG9nT3BlbmVyLmFkZEV2ZW50TGlzdGVuZXIoXCJjbGlja1wiLCAoKSA9PiB7XG4gICAgZGlhbG9nLm9wZW4gPSB0cnVlO1xufSk7XG5cbmRpYWxvZy5hZGRFdmVudExpc3RlbmVyKFwib3BlblwiLCBmdW5jdGlvbihlKSB7XG4gICBlLnRhcmdldC5jb250ZW50WzBdLmNoaWxkcmVuWzBdLmlubmVySFRNTCA9IFwiPHVpNS1saT5hZGRlZCBkeW5hbWljPC91aTUtbGk-XCI7XG59KTsifSwibWFpbi5jc3MiOnsibmFtZSI6Im1haW4uY3NzIiwiY29udGVudCI6Ii5sb2dpbi1mb3JtIHtcbiAgICBkaXNwbGF5OiBmbGV4O1xuICAgIGZsZXgtZGlyZWN0aW9uOiBjb2x1bW47XG4gICAganVzdGlmeS1jb250ZW50OiBzcGFjZS1ldmVubHk7XG4gICAgYWxpZ24taXRlbXM6IGZsZXgtc3RhcnQ7XG4gICAgbWFyZ2luOiAzcmVtIDZyZW07XG59XG5cbi5sb2dpbi1mb3JtID4gZGl2IHtcbiAgICBkaXNwbGF5OiBncmlkO1xuICAgIHdpZHRoOiAxNXJlbTtcbiAgICBtYXJnaW4tYm90dG9tOiAuNXJlbTtcbn1cblxuQG1lZGlhKG1heC13aWR0aDogNjAwcHgpIHtcbiAgICAubG9naW4tZm9ybSB7XG4gICAgICAgIG1hcmdpbjogM3JlbSAxcmVtO1xuICAgIH1cbn0ifX0)

It does not pass the selection mode to the children when they are added dynamically or trough "each" loop in handlebars.

Best Regards,
Tsani
