### ISSUE TITLE
input: The should not be multiple tab stops for a Single ui component

### ISSUE THREAD

**Issue by pppwr7** [SAP/ui5-webcomponents#9303]
### Describe the bug

For Input field with interactive icon added, if the current focus is on the input field then on tab key press the focus moves to the interactive icon. As per the UX guideline, for any UI only 1 tab stop should be provided. This issue has been raised by the UX colleague.

### Isolated Example

https://stackblitz.com/edit/github-zbkxaj?file=src%2FApp.tsx

### Reproduction steps

1. open https://stackblitz.com/edit/github-zbkxaj?file=src%2FApp.tsx
2. keep the focus on input field
3. hit tab key and see that the icon as well as the input box is focused. Ideally, the control should move to next component away from the input field

### Expected Behaviour

should be focussed aut of the input field on tab press

### UI5 Web Components for React Version

latest

### UI5 Web Components Version

latest

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by kineticjs** [comment]
Hi @pppwr7 ,

Is it correct that you need the ui5-input allow the following behavior:
https://stackblitz.com/edit/github-zbkxaj-bpbemb?file=src%2FApp.tsx

I edited your original sample to make the icon non-interactive but the app is still notified when the user clicks on the icon. Is this basically the expected behavior?

Thanks

**Comment by pppwr7** [comment]
Hi [kineticjs](https://github.com/kineticjs), 
Thanks a lot for the reply. The behavior we are expecting is same as what happens in https://ui5.sap.com//#/entity/sap.m.SearchField/sample/sap.m.sample.SearchField. However, One thing I wanted to know was that if the icon is set as non-interactive then is there a way to reach the icon using keyboard keys other than tab key. How is the accessibility handled in case of this in https://ui5.sap.com//#/entity/sap.m.SearchField/sample/sap.m.sample.SearchField ?

**Comment by GerganaKremenska** [comment]
Hello @pppwr7, 

There is no way to reach the search icon trough keyboard, the search in Searchfield is triggered trough "Enter" key.
That is the alternitive keyboard action to acheive search.

If this anwsers your question, please close the issue.

Best Regards,
Gergana

**Comment by pppwr7** [comment]
Hi All, I removed the double focus issue by setting the interactive property to false. However, I also noticed that on hover over on the icon there not outline border shown like it does when you hover over f4 value help icon in multiinput field and dropdown arrow in dropdown like input field. Is there a way to fix this too?

**Comment by dimovpetar** [comment]
Hello @pppwr7 ,

There is no built-in solution for that, but you can use CSS to style the icon on hover based on your needs.
For example, you can do the following:
```css
.yourIcon:hover {
    box-shadow: var(--sapField_Hover_Shadow);
}
```

If this answers your question, please close the issue.

Best regards,
Petar
