### ISSUE TITLE
Button with Icon not displaying in ie11

### ISSUE THREAD

**Issue by JWandrocke** [SAP/ui5-webcomponents#932]
Using the UI5 Button with only a ICON show up correctly in all browsers except for ie11.

**To reproduce**
Add the button as below and view on ie11.

import { Button } from '@ui5/webcomponents-react/lib/Button'
import '@ui5/webcomponents/dist/icons/decline.js'
<Button
      style={{ marginRight: '0.35rem' }}
      disabled={false}
      icon='sap-icon://decline'
      design='Transparent'
      tooltip='Close'
      onClick={closeWindow}
 />

**Context**
- UI5 Web Components version v1.0.0-rc.4
- Browser ie11

**Comment by MapTo0** [comment]
Hello @JWandrocke,

We already fixed this issue with https://github.com/SAP/ui5-webcomponents/commit/20511c6dc2b7e03e52f5cbe66ba16e6b829b3316

You can workaround until we release next version by adding a few lines of code to your CSS:

```javascript
ui5-button ui5-icon.ui5-button-icon {
	height: 1rem;
	top: 0;
}
```

**Comment by JWandrocke** [comment]
Hi Martin

Thanks for the fast reply, I'll give your suggestion a try.

John Wandrocke
SAP Labs, Palo Alto
