### ISSUE TITLE
[Table]: Remove padding under last item of table

### ISSUE THREAD

**Issue by vicslavova** [SAP/ui5-webcomponents#9322]
### Bug Description

Tables look like they have a double border because of the border of the last item + the padding under it.

![image](https://github.com/SAP/ui5-webcomponents/assets/104071083/a8d438ee-011e-4a1d-97ef-317c09da2259)

Closeup:
<img width="411" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/104071083/0afd68cc-73d8-494a-8baa-cdec490d10b2">

### Expected Behaviour

There shouldn't be a padding under the last table item. This can also be seen in the Fiori Visual Guideline wiki.

### Steps to Reproduce

1.
2.
3.
...

### Priority

Medium

### UI5 Web Components Version

1.92

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ilhan007** [comment]
Hi @vicslavova do you find the padding in this basic [Table sample](https://sap.github.io/ui5-webcomponents/play/#eyJpbmRleC5odG1sIjp7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuPCFET0NUWVBFIGh0bWw-XG48aHRtbCBsYW5nPVwiZW5cIj5cblxuXG48aGVhZD5cbiAgICBcbiAgICA8c3R5bGU-XG4gICAgICAqOm5vdCg6ZGVmaW5lZCkge1xuICAgICAgICBkaXNwbGF5OiBub25lO1xuICAgICAgfVxuICAgIDwvc3R5bGU-XG5cbiAgICBcbiAgICA8c3R5bGU-XG4gICAgICAqOm5vdCg6ZGVmaW5lZCkge1xuICAgICAgICBkaXNwbGF5OiBub25lO1xuICAgICAgfVxuICAgIDwvc3R5bGU-XG5cbiAgICA8bWV0YSBjaGFyc2V0PVwiVVRGLThcIj5cbiAgICA8bWV0YSBuYW1lPVwidmlld3BvcnRcIiBjb250ZW50PVwid2lkdGg9ZGV2aWNlLXdpZHRoLCBpbml0aWFsLXNjYWxlPTEuMFwiPlxuICAgIDx0aXRsZT5TYW1wbGU8L3RpdGxlPlxuPC9oZWFkPlxuPGJvZHkgc3R5bGU9XCJiYWNrZ3JvdW5kLWNvbG9yOiB2YXIoLS1zYXBCYWNrZ3JvdW5kQ29sb3IpO1wiPlxuPCEtLSBwbGF5Z3JvdW5kLWZvbGQtZW5kIC0tPlxuXG48dWk1LXRhYmxlPlxuXG4gICAgPHVpNS10YWJsZS1jb2x1bW4gc2xvdD1cImNvbHVtbnNcIj5cbiAgICAgICAgPHNwYW4-UHJvZHVjdDwvc3Bhbj5cbiAgICA8L3VpNS10YWJsZS1jb2x1bW4-XG4gICAgPHVpNS10YWJsZS1jb2x1bW4gc2xvdD1cImNvbHVtbnNcIj5cbiAgICAgICAgPHNwYW4-U3VwcGxpZXI8L3NwYW4-XG4gICAgPC91aTUtdGFibGUtY29sdW1uPlxuICAgIDx1aTUtdGFibGUtY29sdW1uIHNsb3Q9XCJjb2x1bW5zXCI-XG4gICAgICAgIDxzcGFuPkRpbWVuc2lvbnM8L3NwYW4-XG4gICAgPC91aTUtdGFibGUtY29sdW1uPlxuICAgIDx1aTUtdGFibGUtY29sdW1uIHNsb3Q9XCJjb2x1bW5zXCI-XG4gICAgICAgIDxzcGFuPldlaWdodDwvc3Bhbj5cbiAgICA8L3VpNS10YWJsZS1jb2x1bW4-XG4gICAgPHVpNS10YWJsZS1jb2x1bW4gc2xvdD1cImNvbHVtbnNcIj5cbiAgICAgICAgPHNwYW4-UHJpY2U8L3NwYW4-XG4gICAgPC91aTUtdGFibGUtY29sdW1uPlxuXG4gICAgPHVpNS10YWJsZS1yb3c-XG4gICAgICAgIDx1aTUtdGFibGUtY2VsbD5cbiAgICAgICAgICAgIDxzcGFuPk5vdGVib29rIEJhc2ljIDE1PC9zcGFuPlxuICAgICAgICA8L3VpNS10YWJsZS1jZWxsPlxuICAgICAgICA8dWk1LXRhYmxlLWNlbGw-XG4gICAgICAgICAgICA8c3Bhbj5WZXJ5IEJlc3QgU2NyZWVuczwvc3Bhbj5cbiAgICAgICAgPC91aTUtdGFibGUtY2VsbD5cbiAgICAgICAgPHVpNS10YWJsZS1jZWxsPlxuICAgICAgICAgICAgPHNwYW4-MzAgeCAxOCB4IDNjbTwvc3Bhbj5cbiAgICAgICAgPC91aTUtdGFibGUtY2VsbD5cbiAgICAgICAgPHVpNS10YWJsZS1jZWxsPlxuICAgICAgICAgICAgPHNwYW4-NC4yPC9iPktHPC9zcGFuPlxuICAgICAgICA8L3VpNS10YWJsZS1jZWxsPlxuICAgICAgICA8dWk1LXRhYmxlLWNlbGw-XG4gICAgICAgICAgICA8c3Bhbj45NTY8L2I-RVVSPC9zcGFuPlxuICAgICAgICA8L3VpNS10YWJsZS1jZWxsPlxuICAgIDwvdWk1LXRhYmxlLXJvdz5cblxuICAgIDx1aTUtdGFibGUtcm93PlxuICAgICAgICA8dWk1LXRhYmxlLWNlbGw-XG4gICAgICAgICAgICA8c3Bhbj5pUGhvbmUgMTM8L3NwYW4-XG4gICAgICAgIDwvdWk1LXRhYmxlLWNlbGw-XG4gICAgICAgIDx1aTUtdGFibGUtY2VsbD5cbiAgICAgICAgICAgIDxzcGFuPkFwcGxlPC9zcGFuPlxuICAgICAgICA8L3VpNS10YWJsZS1jZWxsPlxuICAgICAgICA8dWk1LXRhYmxlLWNlbGw-XG4gICAgICAgICAgICA8c3Bhbj4xMCB4IDEyIHggM2NtPC9zcGFuPlxuICAgICAgICA8L3VpNS10YWJsZS1jZWxsPlxuICAgICAgICA8dWk1LXRhYmxlLWNlbGw-XG4gICAgICAgICAgICA8c3Bhbj4xNTA8L2I-Rzwvc3Bhbj5cbiAgICAgICAgPC91aTUtdGFibGUtY2VsbD5cbiAgICAgICAgPHVpNS10YWJsZS1jZWxsPlxuICAgICAgICAgICAgPHNwYW4-ODAwPC9iPkVVUjwvc3Bhbj5cbiAgICAgICAgPC91aTUtdGFibGUtY2VsbD5cbiAgICA8L3VpNS10YWJsZS1yb3c-XG5cbiAgICA8dWk1LXRhYmxlLXJvdz5cbiAgICAgICAgPHVpNS10YWJsZS1jZWxsPlxuICAgICAgICAgICAgPHNwYW4-aVBob25lIDQzPC9zcGFuPlxuICAgICAgICA8L3VpNS10YWJsZS1jZWxsPlxuICAgICAgICA8dWk1LXRhYmxlLWNlbGw-XG4gICAgICAgICAgICA8c3Bhbj5BcHBsZTwvc3Bhbj5cbiAgICAgICAgPC91aTUtdGFibGUtY2VsbD5cbiAgICAgICAgPHVpNS10YWJsZS1jZWxsPlxuICAgICAgICAgICAgPHNwYW4-MTIgeCAxMiB4IDNjbTwvc3Bhbj5cbiAgICAgICAgPC91aTUtdGFibGUtY2VsbD5cbiAgICAgICAgPHVpNS10YWJsZS1jZWxsPlxuICAgICAgICAgICAgPHNwYW4-MjUwPC9iPkc8L3NwYW4-XG4gICAgICAgIDwvdWk1LXRhYmxlLWNlbGw-XG4gICAgICAgIDx1aTUtdGFibGUtY2VsbD5cbiAgICAgICAgICAgIDxzcGFuPjEyMDA8L2I-RVVSPC9zcGFuPlxuICAgICAgICA8L3VpNS10YWJsZS1jZWxsPlxuICAgIDwvdWk1LXRhYmxlLXJvdz5cblxuPC91aTUtdGFibGU-XG48IS0tIHBsYXlncm91bmQtZm9sZCAtLT5cbiAgICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCJtYWluLmpzXCI-PC9zY3JpcHQ-XG48L2JvZHk-XG48L2h0bWw-XG48IS0tIHBsYXlncm91bmQtZm9sZC1lbmQgLS0-XG5cbiJ9LCJtYWluLmpzIjp7Im5hbWUiOiJtYWluLmpzIiwiY29udGVudCI6Ii8qIHBsYXlncm91bmQtaGlkZSAqL1xuaW1wb3J0IFwiLi9wbGF5Z3JvdW5kLXN1cHBvcnQuanNcIjtcbi8qIHBsYXlncm91bmQtaGlkZS1lbmQgKi9cbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L1RhYmxlLmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMvZGlzdC9UYWJsZVJvdy5qc1wiO1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzL2Rpc3QvVGFibGVDb2x1bW4uanNcIjtcbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L1RhYmxlQ2VsbC5qc1wiOyJ9fQ) from version 1.24. I could find a padding coming from the last TableRow.

By the way we don't have version 1.92 (maybe you meant 1.9.2 or?).


BR,
ilhan

**Comment by mrCherry97** [comment]
hi @ilhan007 
we want to use a Table inside the panel because our spec says that it needs to have rounded corners and additional things, so it will be lovely to have a property or some suggestion on how to easily fix that to not have the line in the last row in the Table.

Package version which we are using:
```
    "@ui5/webcomponents": "^1.24.0",
    "@ui5/webcomponents-base": "^1.24.0",
    "@ui5/webcomponents-fiori": "^1.24.0",
    "@ui5/webcomponents-react": "~1.28.1",
    "@ui5/webcomponents-react-base": "^1.28.1",
```
 Example of the implementation from the Kyma-dashboard:
```
    <Panel
      title={title}
      headerActions={!headerActionsEmpty && headerActions}
      data-testid={testid}
      disableMargin
      style={disableMargin ? {} : spacing.sapUiSmallMargin}
    >
      <Table
        className={`ui5-generic-list ${hasDetailsView ? 'cursor-pointer' : ''}`}
        onRowClick={e => {   }}
        columns={
          <HeaderRenderer
            entries={entries}
            actions={actions}
            headerRenderer={headerRenderer}
            disableHiding={disableHiding}
            displayArrow={displayArrow}
            noHideFields={noHideFields}
          />
        }
      >
        {renderTableBody()}
      </Table>
    </Panel>
```
Screenshot of the example:
![Screenshot 2024-07-01 at 13 15 01](https://github.com/SAP/ui5-webcomponents/assets/46759954/500716bb-b454-4107-9c9d-03fd3731b484)

Thank you so much for your attention and participation.

Best regards,
WM

**Comment by ilhan007** [comment]
I see, so it's not that the Table has padding under last row, this is just the space between the Table and the Panel, which is fine and expected. To remove the border of the last row I believe you can use pure css, targeting the last row:

```css
ui5-table ui5-table-row:last-child {
            border: none; /* Example style */
}
```

**Comment by mrCherry97** [comment]
hi @ilhan007 
I have checked your proposed solution, and it's not working. I tried to make it more specific with classNames etc, but still it's not working. If you have time and you want we can make a quick debugging meeting, I'll appreciate.

Best regards,
Mateusz

**Comment by mrCherry97** [comment]
😞

**Comment by chriskari** [comment]
Hey, we were able to remove the additional spacing after the last table item by adding this css to the table:
`display: block;`

**Comment by petyabegovska** [comment]
Hello @mrCherry97 and @vicslavova,

Can you confirm that the proposed solution by @chriskari is working for you and the issue could be closed?
