### ISSUE TITLE
[List]: focus loss after "load-more" event

### ISSUE THREAD

**Issue by ee92** [SAP/ui5-webcomponents#9329]
### Bug Description

There is no way to control the focus of the List items programatically. 

### Affected Component

List, CustomListItem

### Expected Behaviour

Expect to have ability to set the focus to the first newly loaded item.
Currently there doesn't seem to be a way to set the focus programatically.

### Isolated Example
[playground](https://sap.github.io/ui5-webcomponents/play/#eyJpbmRleC5odG1sIjp7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuPCFET0NUWVBFIGh0bWw-XG48aHRtbCBsYW5nPVwiZW5cIj5cblxuXG5cbjxoZWFkPlxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG4gICAgPC9zdHlsZT5cblxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG4gICAgPC9zdHlsZT5cblxuICAgIDxtZXRhIGNoYXJzZXQ9XCJVVEYtOFwiPlxuICAgIDxtZXRhIG5hbWU9XCJ2aWV3cG9ydFwiIGNvbnRlbnQ9XCJ3aWR0aD1kZXZpY2Utd2lkdGgsIGluaXRpYWwtc2NhbGU9MS4wXCI-XG4gICAgPHRpdGxlPlNhbXBsZTwvdGl0bGU-XG48L2hlYWQ-XG5cbjxib2R5IHN0eWxlPVwiYmFja2dyb3VuZC1jb2xvcjogdmFyKC0tc2FwQmFja2dyb3VuZENvbG9yKVwiPlxuICAgIDwhLS0gcGxheWdyb3VuZC1mb2xkLWVuZCAtLT5cblxuICAgIDx1aTUtbGlzdCBpZD1cImdyb3dpbmdMaXN0XCIgc3R5bGU9XCJoZWlnaHQ6IDMwMHB4XCIgZ3Jvd2luZz1cIkJ1dHRvblwiIGJ1c3ktZGVsYXk9XCIwXCI-XG4gICAgICAgIDx1aTUtbGkgaWNvbj1cIm51dHJpdGlvbi1hY3Rpdml0eVwiIGRlc2NyaXB0aW9uPVwiVHJvcGljYWwgcGxhbnQgd2l0aCBhbiBlZGlibGUgZnJ1aXRcIiBhZGRpdGlvbmFsLXRleHQ9XCJJbi1zdG9ja1wiXG4gICAgICAgICAgICBhZGRpdGlvbmFsLXRleHQtc3RhdGU9XCJTdWNjZXNzXCI-UGluZWFwcGxlPC91aTUtbGk-XG4gICAgICAgIDx1aTUtbGkgaWNvbj1cIm51dHJpdGlvbi1hY3Rpdml0eVwiIGRlc2NyaXB0aW9uPVwiT2NjdXJzIGJldHdlZW4gcmVkIGFuZCB5ZWxsb3dcIiBhZGRpdGlvbmFsLXRleHQ9XCJFeHBpcmVzXCJcbiAgICAgICAgICAgIGFkZGl0aW9uYWwtdGV4dC1zdGF0ZT1cIldhcm5pbmdcIj5PcmFuZ2U8L3VpNS1saT5cbiAgICAgICAgPHVpNS1saSBpY29uPVwibnV0cml0aW9uLWFjdGl2aXR5XCIgZGVzY3JpcHRpb249XCJUaGUgeWVsbG93IGxlbmd0aHkgZnJ1aXRcIiBhZGRpdGlvbmFsLXRleHQ9XCJSZS1zdG9ja1wiXG4gICAgICAgICAgICBhZGRpdGlvbmFsLXRleHQtc3RhdGU9XCJFcnJvclwiPkJhbmFuYTwvdWk1LWxpPlxuICAgICAgICA8dWk1LWxpIGljb249XCJudXRyaXRpb24tYWN0aXZpdHlcIiBkZXNjcmlwdGlvbj1cIlNtYWxsIGZydWl0IHRoYXQgY29tZXMgaW4gdmFyaW91cyBjb2xvcnMsIGluY2x1ZGluZyByZWQsIHB1cnBsZVwiIGFkZGl0aW9uYWwtdGV4dD1cIlJlLXN0b2NrXCJcbiAgICAgICAgICAgIGFkZGl0aW9uYWwtdGV4dC1zdGF0ZT1cIkluZm9ybWF0aW9uXCI-UGx1bTwvdWk1LWxpPlxuICAgICAgICA8dWk1LWxpIGljb249XCJudXRyaXRpb24tYWN0aXZpdHlcIiBkZXNjcmlwdGlvbj1cIiB0cm9waWNhbCBmcnVpdCBrbm93biBmb3IgaXRzIHN3ZWV0IGFuZCBqdWljeSBpbnRlcmlvclwiIGFkZGl0aW9uYWwtdGV4dD1cIlJlLXN0b2NrXCJcbiAgICAgICAgICAgIGFkZGl0aW9uYWwtdGV4dC1zdGF0ZT1cIkVycm9yXCI-TWFuZ288L3VpNS1saT5cbiAgICA8L3VpNS1saXN0PlxuICAgIDwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuICAgIDxzY3JpcHQgdHlwZT1cIm1vZHVsZVwiIHNyYz1cIm1haW4uanNcIj48L3NjcmlwdD5cbjwvYm9keT5cblxuPC9odG1sPlxuPCEtLSBwbGF5Z3JvdW5kLWZvbGQtZW5kIC0tPlxuIn0sIm1haW4uanMiOnsibmFtZSI6Im1haW4uanMiLCJjb250ZW50IjoiLyogcGxheWdyb3VuZC1oaWRlICovXG5pbXBvcnQgXCIuL3BsYXlncm91bmQtc3VwcG9ydC5qc1wiO1xuLyogcGxheWdyb3VuZC1oaWRlLWVuZCAqL1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzL2Rpc3QvTGlzdC5qc1wiO1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzL2Rpc3QvU3RhbmRhcmRMaXN0SXRlbS5qc1wiO1xuXG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMtaWNvbnMvZGlzdC9udXRyaXRpb24tYWN0aXZpdHkuanNcIjtcblxubGV0IGl0ZW1zTG9hZGVkID0gMDtcbmNvbnN0IGl0ZW1Ub0xvYWQgPSA1O1xuY29uc3QgZ3Jvd2luZ0xpc3QgPSBkb2N1bWVudC5xdWVyeVNlbGVjdG9yKFwiI2dyb3dpbmdMaXN0XCIpO1xuY29uc3QgbGlzdEl0ZW1UZW1wbGF0ZSA9IChpbmRleCkgPT4ge1xuICAgIHZhciBsaSA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoXCJ1aTUtbGlcIik7XG4gICAgbGkudGV4dENvbnRlbnQgPSBcIkZydWl0IG5hbWVcIjtcbiAgICBsaS5kZXNjcmlwdGlvbiA9IFwidGhlIGRlc2NyaXB0aW9uIGdvZXMgaGVyZSBcIiArIGluZGV4O1xuICAgIGxpLmFkZGl0aW9uYWxUZXh0ID0gXCJBdmFpbGFibGVcIjtcbiAgICBsaS5hZGRpdGlvbmFsVGV4dFN0YXRlID0gXCJTdWNjZXNzXCI7XG4gICAgbGkuaWNvbiA9IFwibnV0cml0aW9uLWFjdGl2aXR5XCI7XG4gICAgcmV0dXJuIGxpO1xufVxuXG5jb25zdCBpbnNlcnRJdGVtcyA9IChsaXN0KSA9PiB7XG4gICAgaWYgKGxpc3QuY2hpbGRyZW4ubGVuZ3RoID4gNikge1xuICBsaXN0Lmdyb3dpbmcgPSBcIk5vbmVcIjtcbiAgcmV0dXJuO1xufVxuICAgIGZvciAodmFyIGkgPSBpdGVtc0xvYWRlZDsgaSA8IGl0ZW1zTG9hZGVkICsgaXRlbVRvTG9hZDsgaSsrKSB7XG4gICAgICAgIGxpc3QuYXBwZW5kQ2hpbGQobGlzdEl0ZW1UZW1wbGF0ZShpKSk7XG4gICAgfVxuICAgIGl0ZW1zTG9hZGVkKz1pdGVtVG9Mb2FkO1xufVxuXG5ncm93aW5nTGlzdC5hZGRFdmVudExpc3RlbmVyKFwibG9hZC1tb3JlXCIsIChlKSA9PiB7XG4gICAgZ3Jvd2luZ0xpc3QuYnVzeSA9IHRydWU7XG4gICAgXG4gICAgc2V0VGltZW91dCgoKSA9PiB7XG4gICAgICAgIGluc2VydEl0ZW1zKGdyb3dpbmdMaXN0KTtcbiAgICAgICAgZ3Jvd2luZ0xpc3QuYnVzeSA9IGZhbHNlO1xuICAgIH0sIDE1MDApO1xufSk7In19)

### Steps to Reproduce

1. Go to playground for growing list (isolated example)
2. Click "More" button
3. Notice focus is lost after the "More" button disappears

### Priority

Medium

### UI5 Web Components Version

1.24.1

### Browser

Chrome

### Additional Context

Thank you

### Organization

SuccessFactors

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by kineticjs** [comment]
Hi @ee92,

Can you please test the following on your side:
Since the API allows you to access the `rows` slot, you can call e.g. `myTableElement.rows[0].focus()`  in the listener to the `ui5-load-more` event.
