### ISSUE TITLE
[input like]: remove cloneNode from valueStateMessage slot 

### ISSUE THREAD

**Issue by nnaydenow** [SAP/ui5-webcomponents#9347]
### Bug Description

Before, the `valueStateMessage` slot content had to be cloned because the content was rendered outside of the component in the `ui5-popover` inside `ui5-static-area`. With the integration of `Popover API`, the `ui5-popover` is placed inside the shadow root of the component, eliminating the need for the clone.

- [x] ui5-combobox https://github.com/SAP/ui5-webcomponents/pull/9384
- [x] ui5-file-uploader https://github.com/SAP/ui5-webcomponents/pull/9915
- [x] ui5-multi-combobox https://github.com/SAP/ui5-webcomponents/pull/9391
- [x] ui5-select https://github.com/SAP/ui5-webcomponents/pull/9654
- [x] ui5-textarea https://github.com/SAP/ui5-webcomponents/pull/9401/

### Affected Component

ui5-combobox, ui5-file-uploader, ui5-multi-combobox, ui5-select, ui5-textarea

### Expected Behaviour

Instead of node cloning use `<slot name="valueStateMessage"></slot>`

**Comment by nnaydenow** [comment]
Hello @SAP/ui5-webcomponents-topic-b, @SAP/ui5-webcomponents-topic-rl, @SAP/ui5-webcomponents-topic-p, @SAP/ui5-webcomponents-topic-rd,

Please take a look at this enhancement.

**Comment by dobrinyonkov** [comment]
Internal Reference: BGSOFUIPIRIN-6611
