### ISSUE TITLE
ui5-panel control attribute header-text

### ISSUE THREAD

**Issue by camilo2312** [SAP/ui5-webcomponents#939]
Hi guys 

When I try to put a property in the header-text attribute using angular, it is not possible to link it to a variable

![image](https://user-images.githubusercontent.com/42982644/68945986-cb396a00-077f-11ea-816b-511c1d0573cf.png)

How can we do that?

Thanks

**Comment by MapTo0** [comment]
Hello @camilo2312 

I am not really an Angular expert but you can check our sample app https://github.com/SAP/ui5-webcomponents-sample-angular/blob/0696fde73e512848856ea7fd9e4e330e73aae7e9/src/app/app.component.html#L9-L13

Can you try to do something like:

`[headerText]="expression"`

**Comment by fifoosid** [comment]
Hi @camilo2312 

You have two approaches to choose from:

1. As Martin proposed above: ```[headerText]="panelTitle"```
2. If you want to use the dashed syntax: ```[attr.header-text]="panelTitle"```

With both approaches, panelTitle should be declared variable.

Best regards,
Filip

**Comment by camilo2312** [comment]
Thanks for your help
