### ISSUE TITLE
ui5-step-input - valueStateChange event raise too many times

### ISSUE THREAD

**Issue by ash-uncover** [SAP/ui5-webcomponents#9422]
### Bug Description

The valueStateChange event is raised several times on stepInput when a valueStateMessage is displayed

### Affected Component

ui5-step-input

### Expected Behaviour

The valueStateChange should be raised only once

### Isolated Example

https://stackblitz.com/edit/js-brdjes?file=index.js,package.json,index.html

### Steps to Reproduce

1. Open stack blitz link
2. Go to the step input input
3. type '20' then press enter

in the console one can see that the event was logged twice

### Priority

Medium

### UI5 Web Components Version

1.24.1 and above (reproducible on 2.0.1=

### Browser

Chrome

### Operating System

windows

### Additional Context

Our unit test are failing since 1.24.1 du to this regression, this is a blocker for adoption on our side.

### Organization

SAP SBPA

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by GerganaKremenska** [comment]
Hello @ash-uncover, 

Tested on Windows 11 + Chrome Version 126.0.6478.127  and the event is fired once.

Please review attached video and  share if some steps are missed. 

https://github.com/SAP/ui5-webcomponents/assets/22882174/36f78a41-460f-46af-bd7c-0af82556085a



Best Regards,
Gergana
