### ISSUE TITLE
Throw a CLDR error when calling "new sap.ui.core.LocaleData(sap.ui.getCore().getConfiguration().getLocale());" using UI5-WC[component name | framework | build | icons | theming | localization | i18n | typescript]:

### ISSUE THREAD

**Issue by henrypolangcosSap** [SAP/ui5-webcomponents#9431]
### Bug Description

the real issue happens in the open UI5 wc, 
calling this ** var oLocaleData = new sap.ui.core.LocaleData(sap.ui.getCore().getConfiguration().getLocale());**
will throw the error below
please see   and video as the attachment 

**Error: CLDR data for locale en is not loaded!
    at f (main.6dd1bed7.js:2:1458624)
    at Object.loadResource (main.6dd1bed7.js:2:686334)
    at i (main.6dd1bed7.js:2:687812)
    at main.6dd1bed7.js:2:688175
    at new constructor (main.6dd1bed7.js:2:688270)
    at sap.extent.uilib.util.EditFormGeneratorHelper._getUIDateTimeFormat (EditFormGeneratorHelper.js?eval:2105:27)
    at <anonymous>:1:47**

This is similar to https://github.com/SAP/ui5-webcomponents/issues/4904

https://github.com/SAP/ui5-webcomponents/assets/174543909/1e679290-4f2d-43cc-a8d9-c32d6c794a0a

![issue in ui5 wc](https://github.com/SAP/ui5-webcomponents/assets/174543909/1e00a6e8-d9f6-412d-809e-b6731fd50a01)
![openUI5Legacy](https://github.com/SAP/ui5-webcomponents/assets/174543909/63cfa02a-89ea-4e65-a920-4c6d5fc6d170)

### Expected Behaviour

the call new sap.ui.core.LocaleData(sap.ui.getCore().getConfiguration().getLocale()); should execute without issue

### Steps to Reproduce

please reach out to me if you need assistance on reproducing the issue

### Priority

None

### UI5 Web Components Version

not sure about this, I can only say out release version is 2405p11e.20240703181305

### Browser

Chrome, Edge, Firefox, Safari

### Operating System

in my case, it's mac

### Additional Context

This is a high priority, It's impacting our customers ability to do their work, in this case processing 'edit work order information"

for the version, I checked from one of the css_variables

https://hcm2preview.sapsf.eu/verp/vmod_v1/ui/fundamental-styles/resources_1.3.0/@sap-theming/theming-base-content/content/Base/baseLib/sap_horizon/css_variables.cs
/**
* Copyright (c) 2012-2020 SAP SE or an SAP affiliate company. All rights reserved.
*
* Theming Engine 1.23031.0-20230411084230+27e6f6f536ddb18b247b5206b0ed9fd0ce09e297
* data:{"Path": "Base.baseLib.sap_horizon.css_variables", "PathPattern": "/%frameworkId%/%libId%/%themeId%/%fileId%.css", "Extends": ["baseTheme"], "Tags": ["Fiori_3","LightColorScheme"], "FallbackThemeId": "sap_fiori_3", "Engine": {"Name": "theming-engine", "Version": "1.23031.0-20230411084230+27e6f6f536ddb18b247b5206b0ed9fd0ce09e297"}, "Version": { "Build": "11.4.0.20230504085330", "Source": "11.4.0"}}
*/

### Organization

Success Factors

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by GerganaKremenska** [comment]
Hello @SAP/ui5-webcomponents-topic-core,

Can you take a look at this issue it is similar to [#4904](https://github.com/SAP/ui5-webcomponents/issues/4904)

Best Regards,
Gergana

**Comment by nnaydenow** [comment]
Hi @henrypolangcosSap,

As we talk offline, the version of web components that you are using is 1.19.1 which is using CLRD from cdn (https://sdk.openui5.org/1.103.0/resources/sap/ui/core/cldr/en.json) which is no longer available and its purpose was to be used in development environment only. To fix this please check following page: https://sap.github.io/ui5-webcomponents/v1/docs/getting-started/using-assets/

Regards,
Nayden
