### ISSUE TITLE
[Feature Request]: Provide filter function for Menu

### ISSUE THREAD

**Issue by bennylalala** [SAP/ui5-webcomponents#9433]
### Feature Request Description

We are looking for the possibility to have a filter function for the long menu.
<img width="1201" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/137315839/4be9cf76-6aef-4f50-9e7b-8ee42e85db18">

### Proposed Solution

Have input at the top of menu and fitler the menu item based on the input value.

### Organization

SF

### Priority

Medium

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by GerganaKremenska** [comment]
Hello @bennylalala,

Thank you for your request.

Can you provide a more ditailed description of your feature requesrt?

"Have input at the top of menu and fitler the menu item based on the input value."

When you mean by menu? Menu component or by menu you mean the dropdown under the input?

Here is a sample with input and suggestions that filter depending on the input - https://sap.github.io/ui5-webcomponents/nightly/components/Input/#input-with-suggestions
Also review all the other input(multiinput, mulitcombobox..) components maybe they will fit your needs.

Please let us know if some component needs to be extended or the exsisting ones will do.

Best Regards,
Gergana

**Comment by bennylalala** [comment]
Hi @GerganaKremenska we are looking for the enhancement on Menu component. Now it only accept MenuItem and Menu Separator as children. It would be great if it can take an Input component as child.

**Comment by GerganaKremenska** [comment]
Hello @SAP/ui5-webcomponents-topic-b , take a look of this feature request.
The stakeholder wants to add othere elements to the Menu component then MenuItem  and MenuSeparator, like na input, so the can filter the menuitems.

Best Rergads,
Gergana

**Comment by vladitasev** [comment]
Hello,

Could you please also consider using ComboBox for this kind of functionality? The Menu component is not meant to be used this way (have many items, scrolling, filtering, etc.). It's use case it to show a hierarchy of options that usually fit one screen, and allow the user to drill down.

What you're showing in the sample pictures looks literally like the ideal use case of a combo box. Would it work for you?

Regards,
Vladi

**Comment by petyabegovska** [comment]
Hi @bennylalala,

Did you the try the combo box component as Vladislav suggested?

Best regards,
Petya

**Comment by bennylalala** [comment]
@petyabegovska @vladitasev thanks. we tried different way and design to achieve the functions.
