### ISSUE TITLE
[framework | theming ]: UI5 Web component theme is overridden by windows OS high contrast theme

### ISSUE THREAD

**Issue by pankajpandey01** [SAP/ui5-webcomponents#9436]
### Bug Description

UI5 Web component theme is overridden by windows OS high contrast theme
Note: This issue is not present in sapui5 https://sapui5.netweaver.ondemand.com/sdk/#/controls. 

### Expected Behaviour

Expected behavior: If the application offers selectable themes in its user settings,  selected theme remain unmodified when the operating system setting is changed to light, dark, or any of the high contrast options.
Reference:  https://www.etsi.org/deliver/etsi_en/301500_301599/301549/03.02.01_60/en_301549v030201p.pdf (11.7 User Preferences)

### Steps to Reproduce

1. Set windows OS -> contrast themes -> Aquatic
2.  Go to https://sap.github.io/ui5-webcomponents/components/
3. change settings->theme

Observed that ui5-webcomponents  page uses OS theme. There is no effect of changing theme.

### Priority

None

### UI5 Web Components Version

2.0.1

### Browser

Chrome, Edge, Firefox, Safari

### Operating System

Windows 11

### Additional Context

This issue is not present in sapui5 https://sapui5.netweaver.ondemand.com/sdk/#/controls. 

### Organization

SuccessFactors

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by GerganaKremenska** [comment]
Hello @SAP/ui5-webcomponents-topic-core,

I am forwarding this issue to you as it is reproducible.
<img width="1771" alt="Screenshot 2024-07-10 at 8 16 08" src="https://github.com/SAP/ui5-webcomponents/assets/22882174/96766c29-f3f1-434f-932a-7f804c97573c">

But i am not sure that this is an issue, missing feature or desired outcome.

In sapui5 is achived with .sapUiBody{ forced-color-adjust: none; }

Please take over.

Best Regards,
Gergana

**Comment by ilhan007** [comment]
Hello @pankajpandey01 , 
thanks for reporting.

For the playground samples we will fix the unexpected color adjustments by setting:
```css
html {
   forced-color-adjust: none;
}
```

And, for the applications, built with UI5 Web Components, we will suggest setting the same `forced-color-adjust: none;` in their pages, as UI5 Web Components don't own the page. The SAPUI5 framework is doing it internally via `.sapUiBody{ forced-color-adjust: none; }`, but SAPUI5 is an application framework and it owns the entire page, while UI5 Web Components are the building-blocks of an application and this is out of its domain.


This is the related change: https://github.com/SAP/ui5-webcomponents/pull/10085
