### ISSUE TITLE
[Card]: Add "busy" property

### ISSUE THREAD

**Issue by lenafi5cher** [SAP/ui5-webcomponents#9437]
### Is your feature request related to a problem?

We use a lot of Cards in our application which does not have a built-in busy state. It was suggested that we wrap the busy state around the Card to manage this busy state. However, when we do that we run into the issue, that the busy indicator dimmed overlay is not adapted properly to the Card's rounded corners. This results in incoherent visual design.
![image](https://github.com/SAP/ui5-webcomponents-react/assets/165897616/15b6f31c-ef4f-4a8b-aa1c-ae366b7b731f)

We would need to write a custom css class and add it to every busy indicator that is wrapped around a card which would be better if managed managed centrally. Having a busy-property related to Card would also make it easier for developers not to forget busy state implementation.

### Describe the solution you'd like

Just like with Table and List, I'd like a "busy" property for the Card component which adds the necessary css to ensure the dimmed overlay has the same border radius as the Card.

### Organization

SAP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by GerganaKremenska** [comment]
Hello @SAP/ui5-webcomponents-topic-rd, take a look of this feature request.

Best Regards,
Gergana
