### ISSUE TITLE
Toolbar: the `click` event of Toolbar subcomponents is bubbling up, leading to duplicate `click` calls

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#9444]
### Bug Description

When registering a `click` event somewhere higher in the DOM tree than the `Toolbar` is mounted, the event is called twice if a subcomponent (`ToolbarButton`, `ToolbarSelect`, etc.) of the `Toolbar` is clicked.

### Affected Component

All subcomponents of the `Toolbar`.

### Expected Behaviour

If an event like `click` is fired internally, it shouldn't propagate outside of the web-component.

### Isolated Example

https://stackblitz.com/edit/github-nqkkqi?file=index.html,main.js

### Steps to Reproduce

1. Go to [StackBlitz](https://stackblitz.com/edit/github-nqkkqi?file=index.html,main.js)
2. Open console
3. Click on the Toolbar, but not on any subcomponent --> see that the `click` event registered to the `body` is fired once (expected)
4. Click on any subcomponent (e.g. on a `ToolbarButton`) --> see that the `click` event is fired twice

### Priority

High

### UI5 Web Components Version

2.0.1

### Browser

Chrome

### Organization

UI5WCR

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by nnaydenow** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

Could you please check the issue?
