### ISSUE TITLE
[Feature Request]: ui5-tokenizer - add the 'n-more' link to the tab chain when the tokenizer is collapsed

### ISSUE THREAD

**Issue by nikoletavnv** [SAP/ui5-webcomponents#9447]
### Feature Request Description

https://sap.github.io/ui5-webcomponents/nightly/packages/main/test/pages/Tokenizer.html

Tokenizer with n-more only is not reachable with keyboard and it is skipped from the tab chain. 

### Proposed Solution

Probably a gap in the design and should be discussed as it is a accessibility issue.

### Priority

Low

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ivoplashkov** [comment]
Hi,

This has been discussed with designers and they proposed that there should be no case where only nMore is shown, we need to provide a way to display atleast one token, whether it's truncated or not, which should be focusable.

Regards,
Ivaylo

**Comment by hristop** [comment]
Hi all,

I am closing this. As Ivaylo mentioned - there should be no case, where you are navigating with the keyboard and n-more is available. 
Upon focusing, the Tokenizer expands and all Tokens are reachable. 

Best Regards,
Hristo
