### ISSUE TITLE
[ui5-rating-indicator]: Page is scrolled when pressing SPACE on a readonly rating indicator

### ISSUE THREAD

**Issue by nikoletavnv** [SAP/ui5-webcomponents#9455]
### Bug Description

When space is pressed on a readonly rating indicator the page is scrolled.

NOTE: F6 navigation is turned on

### Affected Component

ui5-rating-indicator

### Isolated Example

https://sap.github.io/ui5-webcomponents/nightly/packages/main/test/pages/RatingIndicator.html

### Steps to Reproduce

1. Click on a readonly rating indicator 
2. Press SPACE
3. The page is scrolled

### Priority

Low

### UI5 Web Components Version

2.0.1

### Browser

Chrome

### Operating System

Windows

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ivoplashkov** [comment]
Hi,

Issue has been fixed with #9458. 

Regards,
Ivaylo
