### ISSUE TITLE
[DynamicSideContent]: [Problem when used with Wizard]

### ISSUE THREAD

**Issue by DamyanKolev** [SAP/ui5-webcomponents#9462]
### Describe the bug

DynamicSideContent does not work properly when it is a child component of the Wizard, the problem is that side content it always sits below the main content regardless of the resolution.

### Isolated Example

https://stackblitz.com/edit/github-6r86cw?file=src%2FApp.tsx

### Expected Behaviour

<img width="1278" alt="Expected_Behaviour" src="https://github.com/SAP/ui5-webcomponents-react/assets/65983543/90f561cc-a8aa-4756-b3b5-c885c776f896">

### UI5 Web Components for React Version

1.29.3

### UI5 Web Components Version

1.24.5

### Browser

Chrome, Edge

### Operating System

Windows

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by TeodorTaushanov** [comment]
Hi @SAP/ui5-webcomponents-topic-rl, can you check this issue?

**Comment by MapTo0** [comment]
Hello Colleagues,

Could you please change [this getter](https://github.com/SAP/ui5-webcomponents/blob/main/packages/fiori/src/DynamicSideContent.ts#L370)

You need to call `getBoundingClientRect().width` instead of `clientWidth`.
