### ISSUE TITLE
BusyIndicator: allow changing `display` type and `border-radius`

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#9465]
### Feature Request Description

In UI5WCR we're replacing all custom implementations of loading indicators with the BusyIndicator. In the process of this we noticed that we need to change the `display` type of the root element and the `border-radius`. 

Examples:

With `border-radius: 0` and `display: initial`:

<img width="1107" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/9749730/7b2de8ed-c147-4092-a06b-619dbe1730e0">

Default:

<img width="1353" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/9749730/5647a12b-6e12-44a0-b130-c64c03be397c">
<img width="49" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/9749730/534c5cd0-c819-40d7-b4d1-0a03735b99df">

### Proposed Solution

Offer a `part` attribute on the elements with the following classes:

- `.ui5-busy-indicator-root` ([code](https://github.com/SAP/ui5-webcomponents/blob/0480e58647972da53776232478498ab96c8720c4/packages/main/src/BusyIndicator.hbs#L1))
- `.ui5-busy-indicator-busy-area` ([code](https://github.com/SAP/ui5-webcomponents/blob/0480e58647972da53776232478498ab96c8720c4/packages/main/src/BusyIndicator.hbs#L3))

### Organization

UI5WCR

### Priority

None

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by dimovpetar** [comment]
By default, busy indicator should have rectangular corners. Your first issue will be resolved by https://github.com/SAP/ui5-webcomponents/issues/9465.
The second one that is related to nested `flex` element requires `min-width: 0` to be applied on your element. I will check if this can also be avoided.

**Comment by dimovpetar** [comment]
Hello @Lukas742 ,

`display: flex` on ` ui5-busy-indicator-root ` is needed to center the 3 circles, therefore It can't be removed.
Anyways, changing the `display` of such internal element is something that we should avoid. Can you provide isolated example, so that we can check what is the real problem here. It is hard to debug [this one](https://sap.github.io/ui5-webcomponents-react/nightly/?path=/story/data-display-analyticaltable--tree-table), because `display: initial` and `width`  of the analytical table body are always restored. 

Best regards,
Petar

**Comment by Lukas742** [comment]
Hi @dimovpetar 

Thanks for the support!
FYI: I'll be out of office for the upcoming two weeks. So I'll only get to creating an isolated example afterwards.

**Comment by Lukas742** [comment]
Hi @dimovpetar 

I couldn't isolate this issue using just CSS and HTML, so it's probably only related to our AnalyticalTable implementation. Our table sets many dimensions dynamically via JS and also uses elements positioned outside of the normal flow to enable e.g. row and column virtualization, different column scaling modes, row counting modes, etc.

Therefore, I no longer think it makes sense to support changing the `display` type, as our problem is too specific.

**Comment by dimovpetar** [comment]
Hello @Lukas742 ,

In this case I am closing this issue. You can set the border-radius on the host element now.

Best regards,
Petar
