### ISSUE TITLE
[Table]: row aria label not using gridcell content

### ISSUE THREAD

**Issue by ee92** [SAP/ui5-webcomponents#9473]
### Bug Description

the aria label of each row does not behave as expected
- text wrapped in a span or div will included correctly
- text with no wrapping element will read "Empty"
- rating indicator will read "" (empty string)
- icon button with accessible-name will read "" (empty string)

### Affected Component

Table, TableRow, TableCell

### Expected Behaviour

expect the gridcell contents to be used for the row label

(gridcell content is correct, row label is incorrect)
<img width="474" alt="image" src="https://github.com/user-attachments/assets/d83f2ba6-933c-4754-8dd1-2d6f8f1b63d9">

### Isolated Example

https://sap.github.io/ui5-webcomponents/v1/play/#eyJpbmRleC5odG1sIjp7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuPCFET0NUWVBFIGh0bWw-XG48aHRtbCBsYW5nPVwiZW5cIj5cblxuXG48aGVhZD5cbiAgICBcbiAgICA8c3R5bGU-XG4gICAgICAqOm5vdCg6ZGVmaW5lZCkge1xuICAgICAgICBkaXNwbGF5OiBub25lO1xuICAgICAgfVxuICAgIDwvc3R5bGU-XG5cbiAgICBcbiAgICA8c3R5bGU-XG4gICAgICAqOm5vdCg6ZGVmaW5lZCkge1xuICAgICAgICBkaXNwbGF5OiBub25lO1xuICAgICAgfVxuICAgIDwvc3R5bGU-XG5cbiAgICA8bWV0YSBjaGFyc2V0PVwiVVRGLThcIj5cbiAgICA8bWV0YSBuYW1lPVwidmlld3BvcnRcIiBjb250ZW50PVwid2lkdGg9ZGV2aWNlLXdpZHRoLCBpbml0aWFsLXNjYWxlPTEuMFwiPlxuICAgIDx0aXRsZT5TYW1wbGU8L3RpdGxlPlxuPC9oZWFkPlxuPGJvZHkgc3R5bGU9XCJiYWNrZ3JvdW5kLWNvbG9yOiB2YXIoLS1zYXBCYWNrZ3JvdW5kQ29sb3IpO1wiPlxuPCEtLSBwbGF5Z3JvdW5kLWZvbGQtZW5kIC0tPlxuXG48dWk1LXRhYmxlPlxuXG4gICAgPHVpNS10YWJsZS1jb2x1bW4gc2xvdD1cImNvbHVtbnNcIj5cbiAgICAgICAgPHNwYW4-c3Bhbjwvc3Bhbj5cbiAgICA8L3VpNS10YWJsZS1jb2x1bW4-XG4gICAgPHVpNS10YWJsZS1jb2x1bW4gc2xvdD1cImNvbHVtbnNcIj5cbiAgICAgICAgPHNwYW4-dGV4dDwvc3Bhbj5cbiAgICA8L3VpNS10YWJsZS1jb2x1bW4-XG4gICAgPHVpNS10YWJsZS1jb2x1bW4gc2xvdD1cImNvbHVtbnNcIj5cbiAgICAgICAgPHNwYW4-cmF0aW5nPC9zcGFuPlxuICAgIDwvdWk1LXRhYmxlLWNvbHVtbj5cbiAgICA8dWk1LXRhYmxlLWNvbHVtbiBzbG90PVwiY29sdW1uc1wiPlxuICAgICAgICA8c3Bhbj5idXR0b248L3NwYW4-XG4gICAgPC91aTUtdGFibGUtY29sdW1uPlxuXG4gICAgPHVpNS10YWJsZS1yb3c-XG4gICAgICAgIDx1aTUtdGFibGUtY2VsbD5cbiAgICAgICAgICAgIDxzcGFuPklOX1NQQU48L3NwYW4-XG4gICAgICAgIDwvdWk1LXRhYmxlLWNlbGw-XG4gICAgICAgIDx1aTUtdGFibGUtY2VsbD5cbiAgICAgICAgICAgIFBMQUlOX1RFWFRcbiAgICAgICAgPC91aTUtdGFibGUtY2VsbD5cbiAgICAgICAgPHVpNS10YWJsZS1jZWxsPlxuICAgICAgICAgICAgPHVpNS1yYXRpbmctaW5kaWNhdG9yIG1heD1cIjVcIiB2YWx1ZT1cIjNcIiBhY2Nlc3NpYmxlLW5hbWU9XCJSQVRJTkdcIi8-XG4gICAgICAgIDwvdWk1LXRhYmxlLWNlbGw-XG4gICAgICAgIDx1aTUtdGFibGUtY2VsbD5cbiAgICAgICAgICAgIDx1aTUtYnV0dG9uIGljb249XCJoZWFydFwiIGFjY2Vzc2libGUtbmFtZT1cIklDT05fQlVUVE9OXCI-PC91aTUtYnV0dG9uPlxuICAgICAgICA8L3VpNS10YWJsZS1jZWxsPlxuICAgIDwvdWk1LXRhYmxlLXJvdz5cblxuPC91aTUtdGFibGU-XG48IS0tIHBsYXlncm91bmQtZm9sZCAtLT5cbiAgICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCJtYWluLmpzXCI-PC9zY3JpcHQ-XG48L2JvZHk-XG48L2h0bWw-XG48IS0tIHBsYXlncm91bmQtZm9sZC1lbmQgLS0-XG5cbiJ9LCJtYWluLmpzIjp7Im5hbWUiOiJtYWluLmpzIiwiY29udGVudCI6Ii8qIHBsYXlncm91bmQtaGlkZSAqL1xuaW1wb3J0IFwiLi9wbGF5Z3JvdW5kLXN1cHBvcnQuanNcIjtcbi8qIHBsYXlncm91bmQtaGlkZS1lbmQgKi9cbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L1RhYmxlLmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMvZGlzdC9UYWJsZVJvdy5qc1wiO1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzL2Rpc3QvVGFibGVDb2x1bW4uanNcIjtcbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L1RhYmxlQ2VsbC5qc1wiO1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzL2Rpc3QvQnV0dG9uLmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMvZGlzdC9SYXRpbmdJbmRpY2F0b3IuanNcIjsifX0

### Steps to Reproduce

1. go to example and check the aria-label of the table row

### Priority

Medium

### UI5 Web Components Version

1.24.6

### Browser

Chrome

### Organization

SuccessFactors

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by TeodorTaushanov** [comment]
Hi @SAP/ui5-webcomponents-topic-core, can you check this issue?

**Comment by ilhan007** [comment]
Hi @ee92 

could test with the newly developed [Table](https://sap.github.io/ui5-webcomponents/nightly/play/#eyJpbmRleC5odG1sIjp7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuPCFET0NUWVBFIGh0bWw-XG48aHRtbCBsYW5nPVwiZW5cIj5cblxuXG5cblxuPGhlYWQ-XG4gICAgXG4gICAgPHN0eWxlPlxuICAgICAgKjpub3QoOmRlZmluZWQpIHtcbiAgICAgICAgZGlzcGxheTogbm9uZTtcbiAgICAgIH1cbiAgICA8L3N0eWxlPlxuXG4gICAgXG4gICAgPHN0eWxlPlxuICAgICAgKjpub3QoOmRlZmluZWQpIHtcbiAgICAgICAgZGlzcGxheTogbm9uZTtcbiAgICAgIH1cbiAgICA8L3N0eWxlPlxuXG4gICAgXG4gICAgPHN0eWxlPlxuICAgICAgKjpub3QoOmRlZmluZWQpIHtcbiAgICAgICAgZGlzcGxheTogbm9uZTtcbiAgICAgIH1cbiAgICA8L3N0eWxlPlxuXG4gICAgXG4gICAgPHN0eWxlPlxuICAgICAgKjpub3QoOmRlZmluZWQpIHtcbiAgICAgICAgZGlzcGxheTogbm9uZTtcbiAgICAgIH1cbiAgICA8L3N0eWxlPlxuXG4gICAgPG1ldGEgY2hhcnNldD1cIlVURi04XCI-XG4gICAgPG1ldGEgbmFtZT1cInZpZXdwb3J0XCIgY29udGVudD1cIndpZHRoPWRldmljZS13aWR0aCwgaW5pdGlhbC1zY2FsZT0xLjBcIj5cbiAgICA8dGl0bGU-U2FtcGxlPC90aXRsZT5cbjwvaGVhZD5cbjxib2R5IHN0eWxlPVwiYmFja2dyb3VuZC1jb2xvcjogdmFyKC0tc2FwQmFja2dyb3VuZENvbG9yKTtcIj5cbjwhLS0gcGxheWdyb3VuZC1mb2xkLWVuZCAtLT5cblxuPHVpNS10YWJsZT5cblxuICAgIDx1aTUtdGFibGUtaGVhZGVyLXJvdyBzbG90PVwiaGVhZGVyUm93XCI-XG4gICAgPHVpNS10YWJsZS1oZWFkZXItY2VsbD5cbiAgICAgICAgPHNwYW4-c3Bhbjwvc3Bhbj5cbiAgICA8L3VpNS10YWJsZS1oZWFkZXItY2VsbD5cblxuICAgICA8dWk1LXRhYmxlLWhlYWRlci1jZWxsPlxuICAgICAgICA8c3Bhbj50ZXh0PC9zcGFuPlxuICAgIDwvdWk1LXRhYmxlLWhlYWRlci1jZWxsPlxuXG4gICAgPHVpNS10YWJsZS1oZWFkZXItY2VsbD5cbiAgICAgICAgPHNwYW4-cmF0aW5nPC9zcGFuPlxuICAgIDwvdWk1LXRhYmxlLWhlYWRlci1jZWxsPlxuXG4gICAgPHVpNS10YWJsZS1oZWFkZXItY2VsbD5cbiAgICAgICAgPHNwYW4-YnV0dG9uPC9zcGFuPlxuICAgIDwvdWk1LXRhYmxlLWhlYWRlci1jZWxsPlxuXG4gIDwvdWk1LXRhYmxlLWhlYWRlci1yb3c-XG5cbiAgICA8dWk1LXRhYmxlLXJvdz5cbiAgICAgICAgPHVpNS10YWJsZS1jZWxsPlxuICAgICAgICAgICAgPHNwYW4-SU5fU1BBTjwvc3Bhbj5cbiAgICAgICAgPC91aTUtdGFibGUtY2VsbD5cbiAgICAgICAgPHVpNS10YWJsZS1jZWxsPlxuICAgICAgICAgICAgUExBSU5fVEVYVFxuICAgICAgICA8L3VpNS10YWJsZS1jZWxsPlxuICAgICAgICA8dWk1LXRhYmxlLWNlbGw-XG4gICAgICAgICAgICA8dWk1LXJhdGluZy1pbmRpY2F0b3IgbWF4PVwiNVwiIHZhbHVlPVwiM1wiIGFjY2Vzc2libGUtbmFtZT1cIlJBVElOR1wiLz5cbiAgICAgICAgPC91aTUtdGFibGUtY2VsbD5cbiAgICAgICAgPHVpNS10YWJsZS1jZWxsPlxuICAgICAgICAgICAgPHVpNS1idXR0b24gaWNvbj1cImhlYXJ0XCIgYWNjZXNzaWJsZS1uYW1lPVwiSUNPTl9CVVRUT05cIj48L3VpNS1idXR0b24-XG4gICAgICAgIDwvdWk1LXRhYmxlLWNlbGw-XG4gICAgPC91aTUtdGFibGUtcm93PlxuXG48L3VpNS10YWJsZT5cbjwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuICAgIDxzY3JpcHQgdHlwZT1cIm1vZHVsZVwiIHNyYz1cIm1haW4uanNcIj48L3NjcmlwdD5cbjwvYm9keT5cbjwvaHRtbD5cbjwhLS0gcGxheWdyb3VuZC1mb2xkLWVuZCAtLT5cblxuIn0sIm1haW4uanMiOnsibmFtZSI6Im1haW4uanMiLCJjb250ZW50IjoiLyogcGxheWdyb3VuZC1oaWRlICovXG5pbXBvcnQgXCIuL3BsYXlncm91bmQtc3VwcG9ydC5qc1wiO1xuLyogcGxheWdyb3VuZC1oaWRlLWVuZCAqL1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzL2Rpc3QvVGFibGUuanNcIjtcbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L1RhYmxlSGVhZGVyUm93LmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMvZGlzdC9UYWJsZUhlYWRlckNlbGwuanNcIjtcbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L0J1dHRvbi5qc1wiO1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzL2Rpc3QvUmF0aW5nSW5kaWNhdG9yLmpzXCI7In19), it's the same columns and content, but using the Table from version 2.

Sooner or later the the v2 Table will remain the one and main Table offering so it will be good to fix such things upfront and your feedback will be very helpful to polish it.
