### ISSUE TITLE
[List]: single select mode using incorrect roles

### ISSUE THREAD

**Issue by ee92** [SAP/ui5-webcomponents#9474]
### Bug Description

In single select mode, the list is still using "list" and "listitem" roles, which is not accurate

### Affected Component

List

### Expected Behaviour

This is visually a radio group, so the appropriate roles would be "radio-group" and "radio"

### Isolated Example

https://sap.github.io/ui5-webcomponents/v1/components/List/

### Steps to Reproduce

1. go to the single select mode list sample
2. inspect the element
3. notice it is using "list" and "listitem" roles

### Priority

Low

### UI5 Web Components Version

1.24.6

### Browser

Chrome

### Organization

SuccessFactors

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by TeodorTaushanov** [comment]
Hi @sap/ui5-webcomponents-topic-p, can you check this issue?

**Comment by plamenivanov91** [comment]
Hello @ee92 ,

The roles are currently correct and are aligned with our accessibility specification.

Even though visually, we have radio button, it's still a single select list, and not a radio button group.

Regards,
Plamen Ivanov
