### ISSUE TITLE
[ui5-responsive-popover]: Passing HTMLElement to `opener` via JavaScript results in string instead of DOM object

### ISSUE THREAD

**Issue by henriquemattos** [SAP/ui5-webcomponents#9493]
### Bug Description

While creating an element dynamically via JavaScript, I want to pass this element as the `opener` of `ui5-responsive-popover`, but the final result is `opener="[object SVGGElement]"`, and thus it throws a warning

> ⚠️  Valid opener id is required. It must be defined before opening the popover.

And an error

> ❌  Uncaught (in promise) TypeError: can't access property "getBoundingClientRect", this.getOpenerHTMLElement(...) is null

### Affected Component

ui5-responsive-popover

### Expected Behaviour

I expect that the HTMLElement is stored in the `opener` property of the JavaScript structure and not in the element's attribute as a string.

### Steps to Reproduce

1. Add an HTMLElement dynamically via JavaScript (or query one via document.querySelector)
2. Set this element to the popover's `opener` property
3.  Set the popover to `open = true` to dynamically open the component
4. See the JS failure

### Priority

High

### UI5 Web Components Version

2.0.1

### Browser

Chrome, Edge, Firefox, Safari

### Operating System

macOS

### Organization

SAP Event Ticketing

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by tsanislavgatev** [comment]
Hello @henriquemattos ,

Can you please check this [sample](https://sap.github.io/ui5-webcomponents/play/#eyJpbmRleC5odG1sIjp7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuPCFET0NUWVBFIGh0bWw-XG48aHRtbCBsYW5nPVwiZW5cIj5cblxuXG5cbjxoZWFkPlxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG4gICAgPC9zdHlsZT5cblxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG4gICAgPC9zdHlsZT5cblxuICAgIDxtZXRhIGNoYXJzZXQ9XCJVVEYtOFwiPlxuICAgIDxtZXRhIG5hbWU9XCJ2aWV3cG9ydFwiIGNvbnRlbnQ9XCJ3aWR0aD1kZXZpY2Utd2lkdGgsIGluaXRpYWwtc2NhbGU9MS4wXCI-XG4gICAgPHRpdGxlPlNhbXBsZTwvdGl0bGU-XG48L2hlYWQ-XG5cbjxib2R5IHN0eWxlPVwiYmFja2dyb3VuZC1jb2xvcjogdmFyKC0tc2FwQmFja2dyb3VuZENvbG9yKVwiPlxuICAgIDxzdHlsZT5cbiAgICAgICAgYm9keSB7XG4gICAgICAgICAgICBoZWlnaHQ6IDMwMHB4O1xuICAgICAgICB9XG5cbiAgICAgICAgLnBvcG92ZXItY29udGVudCB7XG4gICAgICAgICAgICBkaXNwbGF5OiBmbGV4O1xuICAgICAgICAgICAgZmxleC1kaXJlY3Rpb246IGNvbHVtbjtcbiAgICAgICAgICAgIGp1c3RpZnktY29udGVudDogY2VudGVyO1xuICAgICAgICB9XG5cbiAgICAgICAgLnBvcG92ZXItZm9vdGVyIHtcbiAgICAgICAgICAgIGRpc3BsYXk6IGZsZXg7XG4gICAgICAgICAgICBqdXN0aWZ5LWNvbnRlbnQ6IGZsZXgtZW5kO1xuICAgICAgICAgICAgd2lkdGg6IDEwMCU7XG4gICAgICAgICAgICBhbGlnbi1pdGVtczogY2VudGVyO1xuICAgICAgICAgICAgcGFkZGluZzogMC41cmVtIDA7XG4gICAgICAgIH1cbiAgICA8L3N0eWxlPlxuXG4gIDwhLS0gcGxheWdyb3VuZC1mb2xkLWVuZCAtLT5cblxuXG4gICAgPHVpNS1idXR0b24gaWQ9XCJidG5cIj5PcGVuIFJlc3BvbnNpdmVQb3BvdmVyPC91aTUtYnV0dG9uPlxuXG4gICAgPHVpNS1yZXNwb25zaXZlLXBvcG92ZXIgaGVhZGVyLXRleHQ9XCJOZXdzbGV0dGVyIHN1YnNjcmlwdGlvblwiPlxuIFxuICAgICAgICA8ZGl2IGNsYXNzPVwicG9wb3Zlci1jb250ZW50XCI-XG4gICAgICAgICAgICA8dWk1LWxhYmVsIGZvcj1cImVtYWlsSW5wdXRcIiByZXF1aXJlZCBzaG93LWNvbG9uPkVtYWlsPC91aTUtbGFiZWw-XG4gICAgICAgICAgICA8dWk1LWlucHV0IGlkPVwiZW1haWxJbnB1dFwiIHN0eWxlPVwibWluLXdpZHRoOiAxNTBweDtcIiBwbGFjZWhvbGRlcj1cIkVudGVyIEVtYWlsXCI-PC91aTUtaW5wdXQ-XG4gICAgICAgICAgICA8dWk1LWxhYmVsPk5vdGU6IElmIHlvdSBvcGVuIHRoZSBwYWdlIGluIG1vYmlsZSwgYSBkaWFsb2cgd291bGQgYmUgZGlzcGxheWVkLjwvdWk1LWxhYmVsPlxuICAgICAgICA8L2Rpdj5cblxuICAgICAgICA8ZGl2IHNsb3Q9XCJmb290ZXJcIiBjbGFzcz1cInBvcG92ZXItZm9vdGVyXCI-XG4gICAgICAgICAgICA8dWk1LWJ1dHRvbiBpZD1cImNsb3NlUG9wb3ZlckJ1dHRvblwiIGRlc2lnbj1cIkVtcGhhc2l6ZWRcIj5TdWJzY3JpYmU8L3VpNS1idXR0b24-XG4gICAgICAgIDwvZGl2PlxuXG4gICAgPC91aTUtcmVzcG9uc2l2ZS1wb3BvdmVyPlxuXG4gICAgPCEtLSBwbGF5Z3JvdW5kLWZvbGQgLS0-XG4gICAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwibWFpbi5qc1wiPjwvc2NyaXB0PlxuPC9ib2R5PlxuXG48L2h0bWw-XG48IS0tIHBsYXlncm91bmQtZm9sZC1lbmQgLS0-XG4ifSwibWFpbi5qcyI6eyJuYW1lIjoibWFpbi5qcyIsImNvbnRlbnQiOiIvKiBwbGF5Z3JvdW5kLWhpZGUgKi9cbmltcG9ydCBcIi4vcGxheWdyb3VuZC1zdXBwb3J0LmpzXCI7XG4vKiBwbGF5Z3JvdW5kLWhpZGUtZW5kICovXG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMvZGlzdC9SZXNwb25zaXZlUG9wb3Zlci5qc1wiO1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzL2Rpc3QvQnV0dG9uLmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMvZGlzdC9MYWJlbC5qc1wiO1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzL2Rpc3QvSW5wdXQuanNcIjtcblxuY29uc3QgYnRuID0gWy4uLmRvY3VtZW50LmdldEVsZW1lbnRzQnlUYWdOYW1lKFwidWk1LWJ1dHRvblwiKV1bMF07XG5jb25zdCByZXNwUG9wb3ZlciA9IFsuLi5kb2N1bWVudC5nZXRFbGVtZW50c0J5VGFnTmFtZShcInVpNS1yZXNwb25zaXZlLXBvcG92ZXJcIildWzBdO1xuXG5idG4uYWRkRXZlbnRMaXN0ZW5lcihcImNsaWNrXCIsICgpID0-IHtcbiAgICByZXNwUG9wb3Zlci5vcGVuZXIgPSBkb2N1bWVudC5xdWVyeVNlbGVjdG9yKFwiW3VpNS1idXR0b25dXCIpO1xuXHRyZXNwUG9wb3Zlci5vcGVuID0gIXJlc3BQb3BvdmVyLm9wZW47XG59KTsifX0)?

I currently can't reproduce the issue if i querySelector an element.
If there is another way, can you please provide a sample that shows the issue?

Best Regards,
Tsanislav

**Comment by ilhan007** [comment]
Probably same as https://github.com/SAP/ui5-webcomponents/issues/9482

**Comment by henriquemattos** [comment]
Hi, @tsanislavgatev . I could not find the error in your example or in the Playground. I will have to tweak my application a bit more to understand why `<g class="selectedObject textObject">` became `[object SVGGElement]`, in any case the solution so far to add a temporary ID to the object (and drop it later) works fine.

Thank you for investigating and for providing the example. ☺️
