### ISSUE TITLE
[ui5-multi-combo-box]: "Select all" checkbox container has no background

### ISSUE THREAD

**Issue by alexis39tt** [SAP/ui5-webcomponents#9495]
### Bug Description

When the `showSelectAll` property is set to true, the "Select all" checkbox appears (as expected). But if there are many items in the multi-combo-box and the list is scrollable, the "Select all" container is transparent and thus the scrolled items are visible under it

Screenshot attached
<img width="346" alt="Screenshot 2024-07-16 at 15 26 05" src="https://github.com/user-attachments/assets/6946ff42-65f5-4d45-81c9-68222c79ffed">

**Browser**
Chrome, Safari

**Operating System**
macOS Sonoma 14.5

**Additional Context**
None

**Organization**
None

**Declaration**

- [x] I’m not disclosing any internal or sensitive information.

### Affected Component

ui5-multi-combo-box

### Expected Behaviour

The background for the "Select all" checkbox container should be the same as for the list

### Isolated Example

n.a.

### Steps to Reproduce

1. Add a ui5-multi-combo-box with the property `showSelectAll` set to `true`
2. Add some ui5-multi-combo-box-item (15-20 should be enough) in it
3. Scroll the items when the list is open

### Log Output, Stack Trace or Screenshots

<img width="346" alt="Screenshot 2024-07-16 at 15 26 05" src="https://github.com/user-attachments/assets/17cb224e-2686-4e30-9122-ba6490c4664f">

### Priority

Low

### UI5 Web Components Version

2.0.1

### Browser

Chrome

### Operating System

macOS Sonoma 14.5

### Organization

SAP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by tsanislavgatev** [comment]
Hi colleagues,

Can you please check this issue?
It's reproducible on quartz light [here](https://sap.github.io/ui5-webcomponents/play/#eyJpbmRleC5odG1sIjp7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuPCFET0NUWVBFIGh0bWw-XG48aHRtbCBsYW5nPVwiZW5cIj5cblxuXG5cbjxoZWFkPlxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG4gICAgPC9zdHlsZT5cblxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG4gICAgPC9zdHlsZT5cblxuICAgIDxtZXRhIGNoYXJzZXQ9XCJVVEYtOFwiPlxuICAgIDxtZXRhIG5hbWU9XCJ2aWV3cG9ydFwiIGNvbnRlbnQ9XCJ3aWR0aD1kZXZpY2Utd2lkdGgsIGluaXRpYWwtc2NhbGU9MS4wXCI-XG4gICAgPHRpdGxlPlNhbXBsZTwvdGl0bGU-XG48L2hlYWQ-XG5cbjxib2R5IHN0eWxlPVwiYmFja2dyb3VuZC1jb2xvcjogdmFyKC0tc2FwQmFja2dyb3VuZENvbG9yKTsgaGVpZ2h0OiAzNTBweDtcIj5cbiAgICA8IS0tIHBsYXlncm91bmQtZm9sZC1lbmQgLS0-XG5cbiAgICA8dWk1LW11bHRpLWNvbWJvYm94IHBsYWNlaG9sZGVyPVwiVHlwZSB5b3VyIHZhbHVlXCIgc2hvdy1zZWxlY3QtYWxsPlxuICAgICAgICA8dWk1LW1jYi1pdGVtIHRleHQ9XCJBbGJhbmlhXCI-PC91aTUtbWNiLWl0ZW0-XG4gICAgICAgIDx1aTUtbWNiLWl0ZW0gIHRleHQ9XCJBcmdlbnRpbmFcIj48L3VpNS1tY2ItaXRlbT5cbiAgICAgICAgPHVpNS1tY2ItaXRlbSB0ZXh0PVwiQnVsZ2FyaWFcIj48L3VpNS1tY2ItaXRlbT5cbiAgICAgICAgPHVpNS1tY2ItaXRlbSB0ZXh0PVwiRGVubWFya1wiPjwvdWk1LW1jYi1pdGVtPlxuICAgICAgICA8dWk1LW1jYi1pdGVtIHRleHQ9XCJFbmdsYW5kXCI-PC91aTUtbWNiLWl0ZW0-XG4gICAgICAgIDx1aTUtbWNiLWl0ZW0gdGV4dD1cIkdlcm1hbnlcIj48L3VpNS1tY2ItaXRlbT5cbiAgICAgICAgPHVpNS1tY2ItaXRlbSB0ZXh0PVwiUGhpbGlwcGluZXNcIj48L3VpNS1tY2ItaXRlbT5cbiAgICAgICAgPHVpNS1tY2ItaXRlbSB0ZXh0PVwiUG9ydHVnYWxcIj48L3VpNS1tY2ItaXRlbT5cbiAgICAgICA8dWk1LW1jYi1pdGVtIHRleHQ9XCJBbGJhbmlhXCI-PC91aTUtbWNiLWl0ZW0-XG4gICAgICAgIDx1aTUtbWNiLWl0ZW0gIHRleHQ9XCJBcmdlbnRpbmFcIj48L3VpNS1tY2ItaXRlbT5cbiAgICAgICAgPHVpNS1tY2ItaXRlbSB0ZXh0PVwiQnVsZ2FyaWFcIj48L3VpNS1tY2ItaXRlbT5cbiAgICAgICAgPHVpNS1tY2ItaXRlbSB0ZXh0PVwiRGVubWFya1wiPjwvdWk1LW1jYi1pdGVtPlxuICAgICAgICA8dWk1LW1jYi1pdGVtIHRleHQ9XCJFbmdsYW5kXCI-PC91aTUtbWNiLWl0ZW0-XG4gICAgICAgIDx1aTUtbWNiLWl0ZW0gdGV4dD1cIkdlcm1hbnlcIj48L3VpNS1tY2ItaXRlbT5cbiAgICAgICAgPHVpNS1tY2ItaXRlbSB0ZXh0PVwiUGhpbGlwcGluZXNcIj48L3VpNS1tY2ItaXRlbT5cbiAgICAgICAgPHVpNS1tY2ItaXRlbSB0ZXh0PVwiUG9ydHVnYWxcIj48L3VpNS1tY2ItaXRlbT5cbiAgICAgICA8dWk1LW1jYi1pdGVtIHRleHQ9XCJBbGJhbmlhXCI-PC91aTUtbWNiLWl0ZW0-XG4gICAgICAgIDx1aTUtbWNiLWl0ZW0gIHRleHQ9XCJBcmdlbnRpbmFcIj48L3VpNS1tY2ItaXRlbT5cbiAgICAgICAgPHVpNS1tY2ItaXRlbSB0ZXh0PVwiQnVsZ2FyaWFcIj48L3VpNS1tY2ItaXRlbT5cbiAgICAgICAgPHVpNS1tY2ItaXRlbSB0ZXh0PVwiRGVubWFya1wiPjwvdWk1LW1jYi1pdGVtPlxuICAgICAgICA8dWk1LW1jYi1pdGVtIHRleHQ9XCJFbmdsYW5kXCI-PC91aTUtbWNiLWl0ZW0-XG4gICAgICAgIDx1aTUtbWNiLWl0ZW0gdGV4dD1cIkdlcm1hbnlcIj48L3VpNS1tY2ItaXRlbT5cbiAgICAgICAgPHVpNS1tY2ItaXRlbSB0ZXh0PVwiUGhpbGlwcGluZXNcIj48L3VpNS1tY2ItaXRlbT5cbiAgICAgICAgPHVpNS1tY2ItaXRlbSB0ZXh0PVwiUG9ydHVnYWxcIj48L3VpNS1tY2ItaXRlbT5cbiAgICAgICA8dWk1LW1jYi1pdGVtIHRleHQ9XCJBbGJhbmlhXCI-PC91aTUtbWNiLWl0ZW0-XG4gICAgICAgIDx1aTUtbWNiLWl0ZW0gIHRleHQ9XCJBcmdlbnRpbmFcIj48L3VpNS1tY2ItaXRlbT5cbiAgICAgICAgPHVpNS1tY2ItaXRlbSB0ZXh0PVwiQnVsZ2FyaWFcIj48L3VpNS1tY2ItaXRlbT5cbiAgICAgICAgPHVpNS1tY2ItaXRlbSB0ZXh0PVwiRGVubWFya1wiPjwvdWk1LW1jYi1pdGVtPlxuICAgICAgICA8dWk1LW1jYi1pdGVtIHRleHQ9XCJFbmdsYW5kXCI-PC91aTUtbWNiLWl0ZW0-XG4gICAgICAgIDx1aTUtbWNiLWl0ZW0gdGV4dD1cIkdlcm1hbnlcIj48L3VpNS1tY2ItaXRlbT5cbiAgICAgICAgPHVpNS1tY2ItaXRlbSB0ZXh0PVwiUGhpbGlwcGluZXNcIj48L3VpNS1tY2ItaXRlbT5cbiAgICAgICAgPHVpNS1tY2ItaXRlbSB0ZXh0PVwiUG9ydHVnYWxcIj48L3VpNS1tY2ItaXRlbT5cbiAgICAgICAgPHVpNS1tY2ItaXRlbSB0ZXh0PVwiVGhlIFVuaXRlZCBLaW5nZG9tIG9mIEdyZWF0IEJyaXRhaW4gYW5kIE5vcnRoZXJuIElyZWxhbmRcIj48L3VpNS1tY2ItaXRlbT5cbiAgICA8L3VpNS1tdWx0aS1jb21ib2JveD5cbiAgICA8IS0tIHBsYXlncm91bmQtZm9sZCAtLT5cbiAgICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCJtYWluLmpzXCI-PC9zY3JpcHQ-XG48L2JvZHk-XG5cbjwvaHRtbD5cbjwhLS0gcGxheWdyb3VuZC1mb2xkLWVuZCAtLT5cbiJ9LCJtYWluLmpzIjp7Im5hbWUiOiJtYWluLmpzIiwiY29udGVudCI6Ii8qIHBsYXlncm91bmQtaGlkZSAqL1xuaW1wb3J0IFwiLi9wbGF5Z3JvdW5kLXN1cHBvcnQuanNcIjtcbi8qIHBsYXlncm91bmQtaGlkZS1lbmQgKi9cbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L011bHRpQ29tYm9Cb3guanNcIjtcbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L011bHRpQ29tYm9Cb3hJdGVtLmpzXCI7In19). You need to scroll down the list when you open the popover.

Best Regards,
Tsani
