### ISSUE TITLE
[SF][ui5-multi-combobox]: Provide scroll event of ComboBoxPopover

### ISSUE THREAD

**Issue by i323808** [SAP/ui5-webcomponents#9505]
### Feature Request Description

Our combobox has many options and need load more options via API when the user scrolls the popover.

### Proposed Solution

Please provide an event which will be fired when the user scrolls the popover.

### Priority

Very High

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by tsanislavgatev** [comment]
Hi colleagues @SAP/ui5-webcomponents-topic-rl ,

Can you please check this case and advice / provide a way to handle the case? 

Best Regards,
Tsani

**Comment by hristop** [comment]
Hi @i323808 ,

Currently we lack the specification for such feature in the ComboBox control, so could you please contact your design responsible to get in touch with the Central Design Team and discuss it with them? 

In general, as per the guidance, the combo box should be used in cases with up to 200 items. For cases with more items, other mechanisms should be used. Please consider using input with value help dialog in which other form of filtering is implemented. 

Best Regards,
Hristo

**Comment by i323808** [comment]
Hi @hristop ,

Thanks for your suggestion. We discussed with our UX and decided to using input with value help dialog.

Thanks,
Jane

**Comment by hristop** [comment]
Hi @i323808 ,

Thanks for letting us know. I will close the issue in this case. 

Best Regards,
Hristo
