### ISSUE TITLE
[inputs]: Pressing "Enter" to accept a value does not close the suggestions dialog

### ISSUE THREAD

**Issue by nikoletavnv** [SAP/ui5-webcomponents#9523]
### Bug Description

Pressing the "Enter" button when entering a value in the suggestions dialog input does not confirm the changes and close the dialog. 

### Affected Component

ui5-input, ui5-multi-input, ui5-combobox, ui5-multi-combobox

### Expected Behaviour

"Enter" button should confirm changes and the close the suggestions dialog

### Steps to Reproduce

1. Use mobile emulator
2. Open page https://sap.github.io/ui5-webcomponents/nightly/packages/main/test/pages/Input.html
3. Start typing a text in the first input - suggestions dialog is opened
4. Press "Enter" when the focus is in the input
5. Nothing happens - dialog is still open. 
Note: For ui5-multi-input with suggestions,  new tokens are created when pressing "Enter" but the dialog remains open. 

### Priority

Low

### UI5 Web Components Version

2.0.1

### Browser

Chrome

### Operating System

Windows

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ivoplashkov** [comment]
Hello @nikoletavnv,

As discussed, this is the behaviour in UI5 as well, therefore we will close the issue for now, until we receive new suggestion for this behaviour.

Thank you and regards,
Ivaylo
