### ISSUE TITLE
[Table]: [the table. In High Contrast Black and High Contrast White theme table borders are getting overlapped.]

### ISSUE THREAD

**Issue by jadhavarjun** [SAP/ui5-webcomponents#9526]
### Describe the bug

the table. In **High contrast black and white** theme table borders within ‘Create’ dialog are getting overlapped. I have attached my application screenshot here where I am getting issue and also providing story book link where you can check the issue.

StoryBook Link: https://sap.github.io/ui5-webcomponents-react/?path=/story/data-display-table--default&globals=theme:sap_horizon_hcb

**Steps**
1. click on the given storybook link.
2. after opening you can click on header rows.
   here you can see selected in dotted border and it's overlapping already present horizontal line
   ![image](https://github.com/user-attachments/assets/e8583e92-2846-4990-8bd1-eaf917b66c2c)

I have attached application screenshot below where I am getting issue for your better understanding.
**### High contrast black theme**
![image](https://github.com/user-attachments/assets/ea39e6b0-22d1-4b45-8f61-179d4128f1b9)

**### High contrast white theme**
![image](https://github.com/user-attachments/assets/9e5c9be7-13bc-431f-8ecd-f6123fee5ba9)

Note: The above reported Issue persists for all such UI throughout the application. Hence it should be corrected for all the occurrences.

### Reproduction steps

1.
2.
3.
...

### Expected Behaviour

In every theme UIs should not get truncated or overlapped with each other.

### UI5 Web Components for React Version

^1.16.3

### UI5 Web Components Version

^1.14.0

### Browser

Chrome

### Operating System

Windows

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by tsanislavgatev** [comment]
Hi colleagues,

Can you take a look at the issue?

Best Regards,
Tsanislav

**Comment by jadhavarjun** [comment]
Hi @Lukas742, @tsanislavgatev,

I haven't got any response from last 2 weeks.
When can I expect a resolution for this issue? please.

**Comment by jadhavarjun** [comment]
HI @Lukas742 ,

When can I expect a resolution for this issue? please let me know.

**Comment by jadhavarjun** [comment]
Hi @Lukas742,
Does anyone working on this issue? Can I know the status?

**Comment by Lukas742** [comment]
Hi @jadhavarjun 

I'm not part of the UI5 Web Components team, so I'm not sure.

@tsanislavgatev @ilhan007 could you please help out here?

**Comment by nnaydenow** [comment]
Hi @jadhavarjun,

We are investigating the issue and the issue might require design specification alignment. I've addressed the issue and I'll ping ASAP when we have update.

**Comment by jadhavarjun** [comment]
Hi @nnaydenow ,

I looks like you've closed the issue, so I assume it's been resolved. Could you please let me know when the solution will be released and which version update, we need to install to see changes?

**Comment by nnaydenow** [comment]
Hi @jadhavarjun,

The fix could be tested here for version 2: https://sap.github.io/ui5-webcomponents/nightly/packages/compat/test/pages/Table.html?sap-ui-theme=sap_horizon_hcb

Same fix will be applied for version 1.24.x
