### ISSUE TITLE
[FlexibleColumnLayout]: missing import for icon "vertical-grip"

### ISSUE THREAD

**Issue by camelCaseChris** [SAP/ui5-webcomponents#9534]
### Bug Description

The FlexibleColumnLayout uses icon `vertical-grip` but does not import it. The result are several console errors and the icon is missing.

You can reproduce this in the basic sample of the component documention. Open https://sap.github.io/ui5-webcomponents/components/fiori/FlexibleColumnLayout/#basic-sample and open the console. You will see errors like "No loader registered for the SAP-icons-v5 icons collection. Probably you forgot to import the "AllIcons.js" module for the respective package." Also, when you select a supplier from the list so that the second column expands, you will see that the icon is missing in the column separator.

(PS: it seems strange that the error suggests using the AllIcons.js import. Is importing individual icons not the more usual use-case?)

### Affected Component

FlexibleColumnLayout

### Expected Behaviour

A component should import all icons it uses.

### Isolated Example

See bug description.

### Steps to Reproduce

See bug description.

### Priority

Medium

### UI5 Web Components Version

2.0.1

### Browser

Chrome, Firefox

### Operating System

Win11

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by kgogov** [comment]
Hello @camelCaseChris,

Thank you for sharing this finding.
I am forwarding this ticket to the responsible team, who will look into it and assist.

@SAP/ui5-webcomponents-topic-p, could you please look into this?

Regards,
Konstantin Gogov
UI5 Web Components GitHub Dispatcher

**Comment by kineticjs** [comment]
Hi colleagues,

This issue was recently fixed with https://github.com/SAP/ui5-webcomponents/commit/1be8d6c094827aeedcc6742a6aae81ce6cd2d966

**Comment by kineticjs** [comment]
@kgogov  pointed out offline that despite that the icon is now visualised (as we see from the nightly version: https://sap.github.io/ui5-webcomponents/nightly/components/fiori/FlexibleColumnLayout/ ) the additional issue with the console error is still there, so we will take this for further inspection.

**Comment by dobrinyonkov** [comment]
Closed by https://github.com/SAP/ui5-webcomponents/pull/9637
