### ISSUE TITLE
Typo in Table documentation

### ISSUE THREAD

**Issue by martindonadiosap** [SAP/ui5-webcomponents#9543]
### **Issue Description**
In the Info block, here https://sap.github.io/ui5-webcomponents/components/Table/ 

 For compatibility reasons, we moved the previous **Tabple**

### **Issue Type**

- [ ] Documentation is unclear
- [ ] Documentation is incorrect
- [ ] Documentation is missing
- [ X ] Other

**Comment by kgogov** [comment]
Hello @martindonadiosap,

Thank you for pointing out the typo!
We will correct it with #9548.

Best regards,
Konstantin Gogov
UI5 Web Components GitHub Dispatcher
