### ISSUE TITLE
[ui5-multi-combobox] Can't delete the tokens for grouping items

### ISSUE THREAD

**Issue by lyc489** [SAP/ui5-webcomponents#9544]
### Bug Description

Can't delete the tokens for grouping items

### Affected Component

ui5-multi-combobox

### Expected Behaviour

The token items can be deleted.

### Steps to Reproduce

Steps:
1. Go to https://sap.github.io/ui5-webcomponents/components/MultiComboBox/#items-grouping

2. Select one or more items from drop-down
<img width="459" alt="image" src="https://github.com/user-attachments/assets/a2e8662b-207d-4f74-90fa-f3f0285b9333">

3. Try deleting token but not working
<img width="245" alt="image" src="https://github.com/user-attachments/assets/e690d072-022e-47e5-9891-f83d3048cbdb">

### Priority

None

### UI5 Web Components Version

v.2.01

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by kgogov** [comment]
Hello @lyc489,

Thank you for sharing this finding.
I am forwarding this ticket to the responsible team, who will look into it and assist.

@SAP/ui5-webcomponents-topic-rl, could you please look into this?
It seems that you cannot delete tokens in the [ui5-multi-combobox](https://sap.github.io/ui5-webcomponents/components/MultiComboBox/) component when the items are **grouped**.
You can see an example of this issue in our [documentation](https://sap.github.io/ui5-webcomponents/components/MultiComboBox/#items-grouping).

Steps to reproduce:
1. Click on the combobox and select an item.
2. Try to delete the item using the Backspace key or by clicking the delete icon.

Regards,
Konstantin Gogov
UI5 Web Components GitHub Dispatcher
