### ISSUE TITLE
[Popover]: Property verticalAlign: "Stretch" align incorrectly

### ISSUE THREAD

**Issue by PlutaKatarzyna** [SAP/ui5-webcomponents#9552]
### Bug Description

UI5 Popover / Responsive Popover component property `verticalAlign` with value `"Stretch"` does not align correctly with the trigger. 
Popover itself align to the top, but show arrow as it was align center.
<img width="910" alt="Screenshot 2024-07-24 at 13 30 54" src="https://github.com/user-attachments/assets/f49bc214-af29-4ad6-867e-976608efa03b">

[Version 1.24 example](https://sap.github.io/ui5-webcomponents/v1/play/#eyJpbmRleC5odG1sIjp7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuPCFET0NUWVBFIGh0bWw-XG48aHRtbCBsYW5nPVwiZW5cIj5cblxuXG5cbjxoZWFkPlxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG4gICAgPC9zdHlsZT5cblxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG4gICAgPC9zdHlsZT5cblxuICAgIDxtZXRhIGNoYXJzZXQ9XCJVVEYtOFwiPlxuICAgIDxtZXRhIG5hbWU9XCJ2aWV3cG9ydFwiIGNvbnRlbnQ9XCJ3aWR0aD1kZXZpY2Utd2lkdGgsIGluaXRpYWwtc2NhbGU9MS4wXCI-XG4gICAgPHRpdGxlPlNhbXBsZTwvdGl0bGU-XG48L2hlYWQ-XG5cbjxib2R5IHN0eWxlPVwiYmFja2dyb3VuZC1jb2xvcjogdmFyKC0tc2FwQmFja2dyb3VuZENvbG9yKVwiPlxuICAgIDxzdHlsZT5cbiAgICAgICAgYm9keSB7XG4gICAgICAgICAgICBoZWlnaHQ6IDkwMHB4O1xuICAgICAgICB9XG5cbiAgICAgICAgLnBvcG92ZXItY29udGVudCB7XG4gICAgICAgICAgICBkaXNwbGF5OiBmbGV4O1xuICAgICAgICAgICAgZmxleC1kaXJlY3Rpb246IGNvbHVtbjtcbiAgICAgICAgICAgIGp1c3RpZnktY29udGVudDogY2VudGVyO1xuICAgICAgICB9XG5cbiAgICAgICAgLnBvcG92ZXItZm9vdGVyIHtcbiAgICAgICAgICAgIGRpc3BsYXk6IGZsZXg7XG4gICAgICAgICAgICBqdXN0aWZ5LWNvbnRlbnQ6IGZsZXgtZW5kO1xuICAgICAgICAgICAgd2lkdGg6IDEwMCU7XG4gICAgICAgICAgICBhbGlnbi1pdGVtczogY2VudGVyO1xuICAgICAgICAgICAgcGFkZGluZzogMC41cmVtIDA7XG4gICAgICAgIH1cbiAgICA8L3N0eWxlPlxuXG4gIDwhLS0gcGxheWdyb3VuZC1mb2xkLWVuZCAtLT5cblxuICA8cD4xIDwvcD48cD4yPC9wPjxwPjM8L3A-PHA-NDwvcD48cD41PC9wPlxuICAgIDx1aTUtYnV0dG9uIGlkPVwiYnRuXCI-T3BlbiBQb3BvdmVyPC91aTUtYnV0dG9uPlxuXG48dWk1LXBvcG92ZXIgcGxhY2VtZW50LXR5cGU9XCJSaWdodFwiIHZlcnRpY2FsLWFsaWduPVwiU3RyZXRjaFwiICBvcGVuZXI9XCJidG5cIiBoZWFkZXItdGV4dD1cIk5ld3NsZXR0ZXIgc3Vic2NyaXB0aW9uXCI-XG4gXG4gICAgPGRpdiBjbGFzcz1cInBvcG92ZXItY29udGVudFwiID5cbiAgICAgICAgPHVpNS1sYWJlbCBmb3I9XCJlbWFpbElucHV0XCIgcmVxdWlyZWQgc2hvdy1jb2xvbj5FbWFpbDwvdWk1LWxhYmVsPlxuICAgICAgICA8dWk1LWlucHV0IGlkPVwiZW1haWxJbnB1dFwiICBwbGFjZWhvbGRlcj1cIkVudGVyIEVtYWlsXCI-PC91aTUtaW5wdXQ-XG4gICAgICAgIDx1aTUtbGFiZWw-Tm90ZTogSWYgeW91IG9wZW4gdGhlIHBhZ2UgaW4gbW9iaWxlLCBhIGRpYWxvZyB3b3VsZCBiZSBkaXNwbGF5ZWQuPC91aTUtbGFiZWw-XG4gICAgPC9kaXY-XG5cbiAgICA8ZGl2IHNsb3Q9XCJmb290ZXJcIiBjbGFzcz1cInBvcG92ZXItZm9vdGVyXCI-XG4gICAgICAgIDx1aTUtYnV0dG9uIGlkPVwiY2xvc2VQb3BvdmVyQnV0dG9uXCIgZGVzaWduPVwiRW1waGFzaXplZFwiPlN1YnNjcmliZTwvdWk1LWJ1dHRvbj5cbiAgICA8L2Rpdj5cblxuPC91aTUtcG9wb3Zlcj5cblxuICAgIDwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuICAgIDxzY3JpcHQgdHlwZT1cIm1vZHVsZVwiIHNyYz1cIm1haW4uanNcIj48L3NjcmlwdD5cbjwvYm9keT5cblxuPC9odG1sPlxuPCEtLSBwbGF5Z3JvdW5kLWZvbGQtZW5kIC0tPlxuIn0sIm1haW4uanMiOnsibmFtZSI6Im1haW4uanMiLCJjb250ZW50IjoiLyogcGxheWdyb3VuZC1oaWRlICovXG5pbXBvcnQgXCIuL3BsYXlncm91bmQtc3VwcG9ydC5qc1wiO1xuLyogcGxheWdyb3VuZC1oaWRlLWVuZCAqL1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzL2Rpc3QvUG9wb3Zlci5qc1wiO1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzL2Rpc3QvQnV0dG9uLmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMvZGlzdC9MYWJlbC5qc1wiO1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzL2Rpc3QvSW5wdXQuanNcIjtcblxuY29uc3QgYnRuID0gWy4uLmRvY3VtZW50LmdldEVsZW1lbnRzQnlUYWdOYW1lKFwidWk1LWJ1dHRvblwiKV1bMF07XG5jb25zdCBwb3BvdmVyID0gWy4uLmRvY3VtZW50LmdldEVsZW1lbnRzQnlUYWdOYW1lKFwidWk1LXBvcG92ZXJcIildWzBdO1xuXG5idG4uYWRkRXZlbnRMaXN0ZW5lcihcImNsaWNrXCIsICgpID0-IHtcblx0cG9wb3Zlci5vcGVuID0gIXBvcG92ZXIub3Blbjtcbn0pOyJ9fQ)

[Version 2.0 example](https://sap.github.io/ui5-webcomponents/play/#eyJpbmRleC5odG1sIjp7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuPCFET0NUWVBFIGh0bWw-XG48aHRtbCBsYW5nPVwiZW5cIj5cblxuXG5cblxuXG5cbjxoZWFkPlxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG4gICAgPC9zdHlsZT5cblxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG4gICAgPC9zdHlsZT5cblxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG4gICAgPC9zdHlsZT5cblxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG4gICAgPC9zdHlsZT5cblxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG4gICAgPC9zdHlsZT5cblxuICAgIDxtZXRhIGNoYXJzZXQ9XCJVVEYtOFwiPlxuICAgIDxtZXRhIG5hbWU9XCJ2aWV3cG9ydFwiIGNvbnRlbnQ9XCJ3aWR0aD1kZXZpY2Utd2lkdGgsIGluaXRpYWwtc2NhbGU9MS4wXCI-XG4gICAgPHRpdGxlPlNhbXBsZTwvdGl0bGU-XG48L2hlYWQ-XG5cbjxib2R5IHN0eWxlPVwiYmFja2dyb3VuZC1jb2xvcjogdmFyKC0tc2FwQmFja2dyb3VuZENvbG9yKVwiPlxuICAgIDxzdHlsZT5cbiAgICAgICAgYm9keSB7XG4gICAgICAgICAgICBoZWlnaHQ6IDkwMHB4O1xuICAgICAgICB9XG5cbiAgICAgICAgLnBvcG92ZXItY29udGVudCB7XG4gICAgICAgICAgICBkaXNwbGF5OiBmbGV4O1xuICAgICAgICAgICAgZmxleC1kaXJlY3Rpb246IGNvbHVtbjtcbiAgICAgICAgICAgIGp1c3RpZnktY29udGVudDogY2VudGVyO1xuICAgICAgICB9XG5cbiAgICAgICAgLnBvcG92ZXItZm9vdGVyIHtcbiAgICAgICAgICAgIGRpc3BsYXk6IGZsZXg7XG4gICAgICAgICAgICBqdXN0aWZ5LWNvbnRlbnQ6IGZsZXgtZW5kO1xuICAgICAgICAgICAgd2lkdGg6IDEwMCU7XG4gICAgICAgICAgICBhbGlnbi1pdGVtczogY2VudGVyO1xuICAgICAgICAgICAgcGFkZGluZzogMC41cmVtIDA7XG4gICAgICAgIH1cbiAgICA8L3N0eWxlPlxuXG4gIDwhLS0gcGxheWdyb3VuZC1mb2xkLWVuZCAtLT5cblxuICA8cD4xIDwvcD48cD4yPC9wPjxwPjM8L3A-PHA-NDwvcD48cD41PC9wPlxuPHVpNS1idXR0b24gaWQ9XCJidG5cIj5PcGVuIFBvcG92ZXIgT3BlbiBQb3BvdmVyIE9wZW4gUG9wb3ZlcjwvdWk1LWJ1dHRvbj5cblxuPHVpNS1wb3BvdmVyIHBsYWNlbWVudC10eXBlPVwiUmlnaHRcIiB2ZXJ0aWNhbC1hbGlnbj1cIlN0cmV0Y2hcIiAgb3BlbmVyPVwiYnRuXCIgaGVhZGVyLXRleHQ9XCJOZXdzbGV0dGVyIHN1YnNjcmlwdGlvblwiPlxuIFxuICAgIDxkaXYgY2xhc3M9XCJwb3BvdmVyLWNvbnRlbnRcIiA-XG4gICAgICAgIDx1aTUtbGFiZWwgZm9yPVwiZW1haWxJbnB1dFwiIHJlcXVpcmVkIHNob3ctY29sb24-RW1haWw8L3VpNS1sYWJlbD5cbiAgICAgICAgPHVpNS1pbnB1dCBpZD1cImVtYWlsSW5wdXRcIiAgcGxhY2Vob2xkZXI9XCJFbnRlciBFbWFpbFwiPjwvdWk1LWlucHV0PlxuICAgICAgICA8dWk1LWxhYmVsPk5vdGU6IElmIHlvdSBvcGVuIHRoZSBwYWdlIGluIG1vYmlsZSwgYSBkaWFsb2cgd291bGQgYmUgZGlzcGxheWVkLjwvdWk1LWxhYmVsPlxuICAgIDwvZGl2PlxuXG4gICAgPGRpdiBzbG90PVwiZm9vdGVyXCIgY2xhc3M9XCJwb3BvdmVyLWZvb3RlclwiPlxuICAgICAgICA8dWk1LWJ1dHRvbiBpZD1cImNsb3NlUG9wb3ZlckJ1dHRvblwiIGRlc2lnbj1cIkVtcGhhc2l6ZWRcIj5TdWJzY3JpYmU8L3VpNS1idXR0b24-XG4gICAgPC9kaXY-XG5cbjwvdWk1LXBvcG92ZXI-XG5cbiAgICA8IS0tIHBsYXlncm91bmQtZm9sZCAtLT5cbiAgICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCJtYWluLmpzXCI-PC9zY3JpcHQ-XG48L2JvZHk-XG5cbjwvaHRtbD5cbjwhLS0gcGxheWdyb3VuZC1mb2xkLWVuZCAtLT5cbiJ9LCJtYWluLmpzIjp7Im5hbWUiOiJtYWluLmpzIiwiY29udGVudCI6Ii8qIHBsYXlncm91bmQtaGlkZSAqL1xuaW1wb3J0IFwiLi9wbGF5Z3JvdW5kLXN1cHBvcnQuanNcIjtcbi8qIHBsYXlncm91bmQtaGlkZS1lbmQgKi9cbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L1BvcG92ZXIuanNcIjtcbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L0J1dHRvbi5qc1wiO1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzL2Rpc3QvTGFiZWwuanNcIjtcbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L0lucHV0LmpzXCI7XG5cbmNvbnN0IGJ0biA9IFsuLi5kb2N1bWVudC5nZXRFbGVtZW50c0J5VGFnTmFtZShcInVpNS1idXR0b25cIildWzBdO1xuY29uc3QgcG9wb3ZlciA9IFsuLi5kb2N1bWVudC5nZXRFbGVtZW50c0J5VGFnTmFtZShcInVpNS1wb3BvdmVyXCIpXVswXTtcblxuYnRuLmFkZEV2ZW50TGlzdGVuZXIoXCJjbGlja1wiLCAoKSA9PiB7XG5cdHBvcG92ZXIub3BlbiA9ICFwb3BvdmVyLm9wZW47XG59KTsifX0)

### Affected Component

ui5-popover ui5-responsive-popover

### Expected Behaviour

- If trigger is bigger than popover itself, popover should align with top and bottom edges of the trigger.
- If trigger is smaller than popover itself, popover should either align to the top or center, but arrow pointer should point to the trigger

### Isolated Example

https://sap.github.io/ui5-webcomponents/play/#eyJpbmRleC5odG1sIjp7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuPCFET0NUWVBFIGh0bWw-XG48aHRtbCBsYW5nPVwiZW5cIj5cblxuXG5cblxuXG48aGVhZD5cbiAgICBcbiAgICA8c3R5bGU-XG4gICAgICAqOm5vdCg6ZGVmaW5lZCkge1xuICAgICAgICBkaXNwbGF5OiBub25lO1xuICAgICAgfVxuICAgIDwvc3R5bGU-XG5cbiAgICBcbiAgICA8c3R5bGU-XG4gICAgICAqOm5vdCg6ZGVmaW5lZCkge1xuICAgICAgICBkaXNwbGF5OiBub25lO1xuICAgICAgfVxuICAgIDwvc3R5bGU-XG5cbiAgICBcbiAgICA8c3R5bGU-XG4gICAgICAqOm5vdCg6ZGVmaW5lZCkge1xuICAgICAgICBkaXNwbGF5OiBub25lO1xuICAgICAgfVxuICAgIDwvc3R5bGU-XG5cbiAgICBcbiAgICA8c3R5bGU-XG4gICAgICAqOm5vdCg6ZGVmaW5lZCkge1xuICAgICAgICBkaXNwbGF5OiBub25lO1xuICAgICAgfVxuICAgIDwvc3R5bGU-XG5cbiAgICA8bWV0YSBjaGFyc2V0PVwiVVRGLThcIj5cbiAgICA8bWV0YSBuYW1lPVwidmlld3BvcnRcIiBjb250ZW50PVwid2lkdGg9ZGV2aWNlLXdpZHRoLCBpbml0aWFsLXNjYWxlPTEuMFwiPlxuICAgIDx0aXRsZT5TYW1wbGU8L3RpdGxlPlxuPC9oZWFkPlxuXG48Ym9keSBzdHlsZT1cImJhY2tncm91bmQtY29sb3I6IHZhcigtLXNhcEJhY2tncm91bmRDb2xvcilcIj5cbiAgICA8c3R5bGU-XG4gICAgICAgIGJvZHkge1xuICAgICAgICAgICAgaGVpZ2h0OiA5MDBweDtcbiAgICAgICAgfVxuXG4gICAgICAgIC5wb3BvdmVyLWNvbnRlbnQge1xuICAgICAgICAgICAgZGlzcGxheTogZmxleDtcbiAgICAgICAgICAgIGZsZXgtZGlyZWN0aW9uOiBjb2x1bW47XG4gICAgICAgICAgICBqdXN0aWZ5LWNvbnRlbnQ6IGNlbnRlcjtcbiAgICAgICAgfVxuXG4gICAgICAgIC5wb3BvdmVyLWZvb3RlciB7XG4gICAgICAgICAgICBkaXNwbGF5OiBmbGV4O1xuICAgICAgICAgICAganVzdGlmeS1jb250ZW50OiBmbGV4LWVuZDtcbiAgICAgICAgICAgIHdpZHRoOiAxMDAlO1xuICAgICAgICAgICAgYWxpZ24taXRlbXM6IGNlbnRlcjtcbiAgICAgICAgICAgIHBhZGRpbmc6IDAuNXJlbSAwO1xuICAgICAgICB9XG4gICAgPC9zdHlsZT5cblxuICA8IS0tIHBsYXlncm91bmQtZm9sZC1lbmQgLS0-XG5cbiAgPHA-MSA8L3A-PHA-MjwvcD48cD4zPC9wPjxwPjQ8L3A-PHA-NTwvcD5cbjx1aTUtYnV0dG9uIGlkPVwiYnRuXCI-T3BlbiBQb3BvdmVyIE9wZW4gUG9wb3ZlciBPcGVuIFBvcG92ZXI8L3VpNS1idXR0b24-XG5cbjx1aTUtcG9wb3ZlciBwbGFjZW1lbnQtdHlwZT1cIlJpZ2h0XCIgdmVydGljYWwtYWxpZ249XCJTdHJldGNoXCIgIG9wZW5lcj1cImJ0blwiIGhlYWRlci10ZXh0PVwiTmV3c2xldHRlciBzdWJzY3JpcHRpb25cIj5cbiBcbiAgICA8ZGl2IGNsYXNzPVwicG9wb3Zlci1jb250ZW50XCIgPlxuICAgICAgICA8dWk1LWxhYmVsIGZvcj1cImVtYWlsSW5wdXRcIiByZXF1aXJlZCBzaG93LWNvbG9uPkVtYWlsPC91aTUtbGFiZWw-XG4gICAgICAgIDx1aTUtaW5wdXQgaWQ9XCJlbWFpbElucHV0XCIgIHBsYWNlaG9sZGVyPVwiRW50ZXIgRW1haWxcIj48L3VpNS1pbnB1dD5cbiAgICAgICAgPHVpNS1sYWJlbD5Ob3RlOiBJZiB5b3Ugb3BlbiB0aGUgcGFnZSBpbiBtb2JpbGUsIGEgZGlhbG9nIHdvdWxkIGJlIGRpc3BsYXllZC48L3VpNS1sYWJlbD5cbiAgICA8L2Rpdj5cblxuICAgIDxkaXYgc2xvdD1cImZvb3RlclwiIGNsYXNzPVwicG9wb3Zlci1mb290ZXJcIj5cbiAgICAgICAgPHVpNS1idXR0b24gaWQ9XCJjbG9zZVBvcG92ZXJCdXR0b25cIiBkZXNpZ249XCJFbXBoYXNpemVkXCI-U3Vic2NyaWJlPC91aTUtYnV0dG9uPlxuICAgIDwvZGl2PlxuXG48L3VpNS1wb3BvdmVyPlxuXG4gICAgPCEtLSBwbGF5Z3JvdW5kLWZvbGQgLS0-XG4gICAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwibWFpbi5qc1wiPjwvc2NyaXB0PlxuPC9ib2R5PlxuXG48L2h0bWw-XG48IS0tIHBsYXlncm91bmQtZm9sZC1lbmQgLS0-XG4ifSwibWFpbi5qcyI6eyJuYW1lIjoibWFpbi5qcyIsImNvbnRlbnQiOiIvKiBwbGF5Z3JvdW5kLWhpZGUgKi9cbmltcG9ydCBcIi4vcGxheWdyb3VuZC1zdXBwb3J0LmpzXCI7XG4vKiBwbGF5Z3JvdW5kLWhpZGUtZW5kICovXG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMvZGlzdC9Qb3BvdmVyLmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMvZGlzdC9CdXR0b24uanNcIjtcbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L0xhYmVsLmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMvZGlzdC9JbnB1dC5qc1wiO1xuXG5jb25zdCBidG4gPSBbLi4uZG9jdW1lbnQuZ2V0RWxlbWVudHNCeVRhZ05hbWUoXCJ1aTUtYnV0dG9uXCIpXVswXTtcbmNvbnN0IHBvcG92ZXIgPSBbLi4uZG9jdW1lbnQuZ2V0RWxlbWVudHNCeVRhZ05hbWUoXCJ1aTUtcG9wb3ZlclwiKV1bMF07XG5cbmJ0bi5hZGRFdmVudExpc3RlbmVyKFwiY2xpY2tcIiwgKCkgPT4ge1xuXHRwb3BvdmVyLm9wZW4gPSAhcG9wb3Zlci5vcGVuO1xufSk7In19

### Steps to Reproduce

1. Create `ui5-popover` or `ui5-responsive-popover` element
2. Set following properties: `placement-type="Right" vertical-align="Stretch"`
3. Open popover

### Log Output, Stack Trace or Screenshots

<img width="1776" alt="Screenshot 2024-07-24 at 13 31 49" src="https://github.com/user-attachments/assets/92552f2e-9575-4ab7-994e-c8a9320e51e5">
<img width="1776" alt="Screenshot 2024-07-24 at 13 32 50" src="https://github.com/user-attachments/assets/bb66faac-b61e-4c4e-8e88-53296e954ce0">

### Priority

None

### UI5 Web Components Version

2.0.2 , 1.24.1

### Browser

Chrome

### Operating System

MacOS

### Organization

SAP / UDEx components team

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by kgogov** [comment]
Hello @PlutaKatarzyna,

Thank you for sharing this finding.
I am forwarding this ticket to the responsible team, who will look into it and assist.

@SAP/ui5-webcomponents-topic-rd, could you please look into this?

Regards,
Konstantin Gogov
UI5 Web Components GitHub Dispatcher
