### ISSUE TITLE
ui5-dynamic-page-title: unnecessary border if only one action bar is used

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents#9561]
### Bug Description

When using only one of the `actionsBar` or `navigationBar` in the `ui5-dynamic-page-title`, an unnecessary border is displayed

### Affected Component

ui5-dynamic-page-title

### Expected Behaviour

No unnecessary border

### Isolated Example

[UI5 Playground Link](https://sap.github.io/ui5-webcomponents/play/#eyJpbmRleC5odG1sIjp7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuPCFET0NUWVBFIGh0bWw-XG48aHRtbCBsYW5nPVwiZW5cIj5cblxuXG5cbjxoZWFkPlxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG4gICAgPC9zdHlsZT5cblxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG4gICAgPC9zdHlsZT5cblxuICAgIDxtZXRhIGNoYXJzZXQ9XCJVVEYtOFwiPlxuICAgIDxtZXRhIG5hbWU9XCJ2aWV3cG9ydFwiIGNvbnRlbnQ9XCJ3aWR0aD1kZXZpY2Utd2lkdGgsIGluaXRpYWwtc2NhbGU9MS4wXCI-XG4gICAgPHRpdGxlPlNhbXBsZTwvdGl0bGU-XG4gICAgPGxpbmsgcmVsPVwic3R5bGVzaGVldFwiIGhyZWY9XCIuL21haW4uY3NzXCI-XG48L2hlYWQ-XG5cbjxib2R5IHN0eWxlPVwiaGVpZ2h0OiA3MDBweDsgYmFja2dyb3VuZC1jb2xvcjogdmFyKC0tc2FwQmFja2dyb3VuZENvbG9yKVwiPlxuICAgIDwhLS0gcGxheWdyb3VuZC1mb2xkLWVuZCAtLT5cblxuICAgIDx1aTUtZHluYW1pYy1wYWdlIGlkPVwicGFnZVwiIHNob3ctZm9vdGVyPlxuXG4gICAgICAgIDx1aTUtZHluYW1pYy1wYWdlLXRpdGxlIHNsb3Q9XCJ0aXRsZUFyZWFcIj5cbiAgICAgICAgICAgIDx1aTUtYnJlYWRjcnVtYnMgc2xvdD1cImJyZWFkY3J1bWJzXCI-XG4gICAgICAgICAgICAgICAgPHVpNS1icmVhZGNydW1icy1pdGVtIGhyZWY9XCIjXCI-TWFuPC91aTUtYnJlYWRjcnVtYnMtaXRlbT5cbiAgICAgICAgICAgICAgICA8dWk1LWJyZWFkY3J1bWJzLWl0ZW0gaHJlZj1cIiNcIj5TaG9lczwvdWk1LWJyZWFkY3J1bWJzLWl0ZW0-XG4gICAgICAgICAgICAgICAgPHVpNS1icmVhZGNydW1icy1pdGVtIGhyZWY9XCIjXCI-UnVubmluZyBTaG9lczwvdWk1LWJyZWFkY3J1bWJzLWl0ZW0-XG4gICAgICAgICAgICA8L3VpNS1icmVhZGNydW1icz5cblxuICAgICAgICAgICAgPHVpNS10aXRsZSBzbG90PVwiaGVhZGluZ1wiPlNwZWNpYWwgUnVubmluZyBTaG9lPC91aTUtdGl0bGU-XG5cbiAgICAgICAgICAgIDxkaXYgc2xvdD1cInNuYXBwZWRIZWFkaW5nXCIgY2xhc3M9XCJzbmFwcGVkLXRpdGxlLWhlYWRpbmdcIj5cbiAgICAgICAgICAgICAgICA8dWk1LWF2YXRhciBzaGFwZT1cInNxdWFyZVwiIGljb249XCJsYXB0b3BcIiBjb2xvci1zY2hlbWU9XCJBY2NlbnQ1XCIgc2l6ZT1cIlNcIj48L3VpNS1hdmF0YXI-XG4gICAgICAgICAgICAgICAgPHVpNS10aXRsZSB3cmFwcGluZy10eXBlPVwiTm9uZVwiPlNwZWNpYWwgUnVubmluZyBTaG9lPC91aTUtdGl0bGU-XG4gICAgICAgICAgICA8L2Rpdj5cblxuICAgICAgICAgICAgPHAgc2xvdD1cInN1YmhlYWRpbmdcIiBjbGFzcz1cInRleHRcIj5QTy00ODg2NTwvcD5cbiAgICAgICAgICAgIDxwIHNsb3Q9XCJzbmFwcGVkU3ViaGVhZGluZ1wiIGNsYXNzPVwidGV4dFwiPlBPLTQ4ODY1PC9wPlxuXG4gICAgICAgICAgICA8dWk1LXRhZyBjb2xvci1zY2hlbWU9XCI3XCIgd3JhcHBpbmctdHlwZT1cIk5vbmVcIj5TcGVjaWFsIDE1Ny40TSBFVVI8L3VpNS10YWc-XG5cbiAgICAgICAgICAgIDx1aTUtdG9vbGJhciBpZD1cImFjdGlvbnNUb29sYmFyXCIgc2xvdD1cImFjdGlvbnNCYXJcIiBkZXNpZ249XCJUcmFuc3BhcmVudFwiPlxuICAgICAgICAgICAgICAgIDx1aTUtdG9vbGJhci1idXR0b24gdGV4dD1cIkNyZWF0ZVwiPjwvdWk1LXRvb2xiYXItYnV0dG9uPlxuICAgICAgICAgICAgICAgIDx1aTUtdG9vbGJhci1idXR0b24gaWQ9XCJlZGl0LWJ1dHRvblwiIGRlc2lnbj1cIlRyYW5zcGFyZW50XCIgdGV4dD1cIkVkaXRcIj48L3VpNS10b29sYmFyLWJ1dHRvbj5cbiAgICAgICAgICAgICAgICA8dWk1LXRvb2xiYXItYnV0dG9uIGRlc2lnbj1cIlRyYW5zcGFyZW50XCIgdGV4dD1cIlBhc3RlXCI-PC91aTUtdG9vbGJhci1idXR0b24-XG4gICAgICAgICAgICA8L3VpNS10b29sYmFyPlxuICAgICAgICA8L3VpNS1keW5hbWljLXBhZ2UtdGl0bGU-XG5cbiAgICAgICAgPHVpNS1keW5hbWljLXBhZ2UtaGVhZGVyIHNsb3Q9XCJoZWFkZXJBcmVhXCI-XG4gICAgICAgICAgICA8ZGl2IGNsYXNzPVwicHJvZHVjdC1pbmZvXCI-XG4gICAgICAgICAgICAgIGhlYWRlclxuICAgICAgICAgICAgPC9kaXY-XG4gICAgICAgIDwvdWk1LWR5bmFtaWMtcGFnZS1oZWFkZXI-XG5cbiAgICAgICAgPHNwYW4-SGVsbG8gV29ybGQ8L3NwYW4-XG5cbiAgICAgICAgPHVpNS1iYXIgc2xvdD1cImZvb3RlckFyZWFcIiBkZXNpZ249XCJGbG9hdGluZ0Zvb3RlclwiPlxuICAgICAgICAgICAgPHVpNS1idXR0b24gaWQ9XCJzYXZlLWVkaXRcIiBzbG90PVwiZW5kQ29udGVudFwiPlNhdmU8L3VpNS1idXR0b24-XG4gICAgICAgICAgICA8dWk1LWJ1dHRvbiBpZD1cImNhbmNlbC1lZGl0XCIgc2xvdD1cImVuZENvbnRlbnRcIj5DbG9zZTwvdWk1LWJ1dHRvbj5cbiAgICAgICAgPC91aTUtYmFyPlxuICAgIDwvdWk1LWR5bmFtaWMtcGFnZT5cbiAgICA8IS0tIHBsYXlncm91bmQtZm9sZCAtLT5cbiAgICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCJtYWluLmpzXCI-PC9zY3JpcHQ-XG48L2JvZHk-XG5cbjwvaHRtbD5cbjwhLS0gcGxheWdyb3VuZC1mb2xkLWVuZCAtLT4ifSwibWFpbi5qcyI6eyJuYW1lIjoibWFpbi5qcyIsImNvbnRlbnQiOiIvKiBwbGF5Z3JvdW5kLWhpZGUgKi9cbmltcG9ydCBcIi4vcGxheWdyb3VuZC1zdXBwb3J0LmpzXCI7XG4vKiBwbGF5Z3JvdW5kLWhpZGUtZW5kICovXG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMtZmlvcmkvZGlzdC9EeW5hbWljUGFnZS5qc1wiO1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzLWZpb3JpL2Rpc3QvRHluYW1pY1BhZ2VUaXRsZS5qc1wiO1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzLWZpb3JpL2Rpc3QvRHluYW1pY1BhZ2VIZWFkZXIuanNcIjtcblxuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzL2Rpc3QvQmFyLmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMvZGlzdC9MYWJlbC5qc1wiO1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzL2Rpc3QvVGFnLmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMvZGlzdC9CcmVhZGNydW1icy5qc1wiO1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzL2Rpc3QvQnJlYWRjcnVtYnNJdGVtLmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMvZGlzdC9UaXRsZS5qc1wiO1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzL2Rpc3QvVG9vbGJhci5qc1wiO1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzL2Rpc3QvVG9vbGJhckJ1dHRvbi5qc1wiO1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzL2Rpc3QvQXZhdGFyLmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMvZGlzdC9CdXR0b24uanNcIjtcbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L0xpc3QuanNcIjtcbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L0xpc3RJdGVtU3RhbmRhcmQuanNcIjtcbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L1NsaWRlci5qc1wiO1xuXG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMtaWNvbnMvZGlzdC9hY3Rpb24tc2V0dGluZ3MuanNcIjtcbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy1pY29ucy9kaXN0L3NoYXJlLmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMtaWNvbnMvZGlzdC9sYXB0b3AuanNcIjtcblxuXG5jb25zdCBkeW5hbWljUGFnZSA9IGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoXCJ1aTUtZHluYW1pYy1wYWdlXCIpO1xuY29uc3QgZWRpdEJ1dHRvbiA9IGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoXCIjZWRpdC1idXR0b25cIik7XG5cbmNvbnN0IGNhbmNlbEVkaXQgPSBkb2N1bWVudC5xdWVyeVNlbGVjdG9yKFwiI2NhbmNlbC1lZGl0XCIpO1xuY29uc3Qgc2F2ZUVkaXQgPSBkb2N1bWVudC5xdWVyeVNlbGVjdG9yKFwiI3NhdmUtZWRpdFwiKTtcblxuZWRpdEJ1dHRvbi5hZGRFdmVudExpc3RlbmVyKFwiY2xpY2tcIiwgKCkgPT4ge1xuICAgIGR5bmFtaWNQYWdlLnNldEF0dHJpYnV0ZShcInNob3ctZm9vdGVyXCIsIHRydWUpO1xufSk7XG5cbltzYXZlRWRpdCwgY2FuY2VsRWRpdF0uZm9yRWFjaChidXR0b24gPT4ge1xuICAgIGJ1dHRvbi5hZGRFdmVudExpc3RlbmVyKFwiY2xpY2tcIiwgKCkgPT4ge1xuICAgICAgICBkeW5hbWljUGFnZS5yZW1vdmVBdHRyaWJ1dGUoXCJzaG93LWZvb3RlclwiKTtcbiAgICB9KTtcbn0pOyJ9LCJtYWluLmNzcyI6eyJuYW1lIjoibWFpbi5jc3MiLCJjb250ZW50IjoiLnRleHQge1xuICAgIGRpc3BsYXk6IGlubGluZS1ibG9jaztcbiAgICBmb250LXNpemU6IHZhcigtLXNhcEZvbnRTaXplKTtcbiAgICBmb250LWZhbWlseTogdmFyKC0tc2FwRm9udEZhbWlseSk7XG4gICAgY29sb3I6IHZhcigtLXNhcFRleHRDb2xvcik7XG4gICAgbGluZS1oZWlnaHQ6IG5vcm1hbDtcbiAgICB3aGl0ZS1zcGFjZTogcHJlLWxpbmU7XG4gICAgd29yZC13cmFwOiBicmVhay13b3JkO1xuICAgIGN1cnNvcjogdGV4dDtcbiAgICBtYXJnaW46IDA7XG59XG5cbi5wcm9kdWN0LWluZm8ge1xuICAgIGRpc3BsYXk6IGZsZXg7XG4gICAgZmxleC13cmFwOiB3cmFwO1xufVxuXG4ucHJvZHVjdC1pbmZvIFt1aTUtYXZhdGFyXSxcbi5wcm9kdWN0LWluZm8gLnByb2R1Y3QtaW5mby1jZWxsIHtcbiAgICBtYXJnaW4tcmlnaHQ6IDJyZW07XG4gICAgbWFyZ2luLWJvdHRvbTogMXJlbTsgXG59XG5cbi5wcm9kdWN0LWluZm8tY2VsbCB7XG4gICAgZGlzcGxheTogZmxleDtcbiAgICBnYXA6IDVweDtcbiAgICBmbGV4LWRpcmVjdGlvbjogY29sdW1uO1xufVxuXG4ucHJvZHVjdC1kZXNjcmlwdGlvbiB7XG4gICAgZGlzcGxheTogaW5saW5lO1xuICAgIG1heC13aWR0aDogMzAwcHg7XG59XG5cbi5hdmFpbGFiaWxpdHkge1xuICAgZm9udC1zaXplOiAxLjJyZW07XG4gICBjb2xvcjogdmFyKC0tc2FwUG9zaXRpdmVUZXh0Q29sb3IpO1xufVxuXG4ucHJpY2Uge1xuICAgIGZvbnQtc2l6ZTogMS4ycmVtO1xuICAgIGNvbG9yOiB2YXIoLS1zYXBUZXh0Q29sb3IpO1xufVxuXG4uc25hcHBlZC10aXRsZS1oZWFkaW5nIHtcbiAgICBkaXNwbGF5OiBmbGV4O1xuICAgIGFsaWduLWl0ZW1zOiBjZW50ZXI7XG59XG4uc25hcHBlZC10aXRsZS1oZWFkaW5nIFt1aTUtYXZhdGFyXSB7XG4gICAgbWFyZ2luLXJpZ2h0OiAxcmVtO1xufVxuLnNuYXBwZWQtdGl0bGUtaGVhZGluZyBbdWk1LXRpdGxlXSB7XG4gICAgZm9udC1mYW1pbHk6IHZhcigtLXNhcE9iamVjdEhlYWRlcl9UaXRsZV9Gb250RmFtaWx5KTtcbiAgICBjb2xvcjogdmFyKC0tc2FwT2JqZWN0SGVhZGVyX1RpdGxlX1RleHRDb2xvcik7XG4gICAgcGFkZGluZzogMC4zMTI1cmVtIDAgMCAwO1xuICAgIGZvbnQtc2l6ZTogdmFyKC0tc2FwT2JqZWN0SGVhZGVyX1RpdGxlX1NuYXBwZWRGb250U2l6ZSk7XG4gICAgdGV4dC1vdmVyZmxvdzogZWxsaXBzaXM7XG4gICAgbWluLXdpZHRoOiAwO1xufSJ9fQ)

### Steps to Reproduce

1. Open the linked Playground
2. See the border

### Log Output, Stack Trace or Screenshots

<img width="257" alt="image" src="https://github.com/user-attachments/assets/dfb4d8db-fd44-44cf-8272-f9b0fb2c19cd">
<img width="1390" alt="image" src="https://github.com/user-attachments/assets/ff45ca66-3c68-417e-948c-000d0d0e3f86">

### Priority

Medium

### UI5 Web Components Version

2.0.1

### Browser

Chrome, Edge, Firefox, Safari

### Operating System

macOS

### Organization

UI5 Web Components for React

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by kgogov** [comment]
Hello @MarcusNotheis,

Thank you for sharing this finding.
I am forwarding this ticket to the responsible team, who will look into it and assist.

[@SAP/ui5-webcomponents-topic-p](https://github.com/orgs/SAP/teams/ui5-webcomponents-topic-p), could you please look into this?

Regards,
Konstantin Gogov
UI5 Web Components GitHub Dispatcher
