### ISSUE TITLE
[Feature request] Need char count to be included in the input field.

### ISSUE THREAD

**Issue by ashish-C5339954** [SAP/ui5-webcomponents#9564]
### Is your feature request related to a problem?

yes , whenever we are using input field and we want to show the char count also then we have to use icon element explicitly.

### Describe the solution you'd like

<img width="457" alt="image" src="https://github.com/user-attachments/assets/a458fcd1-4b19-4ca2-865e-9c2dc493fba6">

### Describe alternatives you've considered

   <FlexBox direction="Column">
          <DialogFormField
            label={t('NAME')}
            accessibleName={t('NAME')}
            name="profileName"
            as={InputField}
            maxlength={20}
            direction={'Column'}
            **icon={
              <Text style={{ fontSize: '0.8rem' }}>
                {charCountName}
                {'/20'}
              </Text>
            }**
            onInputHandler={onInputName}
            style={{ width: '60vw', marginBottom: '1rem' }}
            data-testid="profileName"
            required={true}
            disabled={formType === FormType.CREATE ? false : true}
            id='profileName'
          />
        **</FlexBox>``**
        
        in the above example we have to use icon to display the char count.

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by kgogov** [comment]
Hello @ashish-C5339954,

Thank you for submitting your feature request.
We appreciate your suggestion and will review it soon.

@SAP/ui5-webcomponents-topic-rl could you please look into this?

Regards,
Konstantin Gogov
SAPUI5 GitHub Dispatcher

**Comment by ashish-C5339954** [comment]
Hi @kgogov 
ideally while displaying the count same should be conveyed by the screen reader

**Comment by hristop** [comment]
Hi @ashish-C5339954 ,

Can you please let your responsible design team to sync the request with SAP Central Design and if a BLI is created, can you please post the E1 / Design number here? 

Best Regards,
Hristo
