### ISSUE TITLE
[Input :input component (third row) in custom filter is not speaking in speech history of JAWS 

### ISSUE THREAD

**Issue by balakrishnamanash** [SAP/ui5-webcomponents#9575]
### Bug Description

input component (third row) in custom filter is not speaking in speech history of JAWS 

### Expected Behaviour

Input component (third row) in custom filter has to speak in speech history of JAWS.

### Steps to Reproduce

1.
2.
3.
...

### Priority

None

### UI5 Web Components Version

^1.14.0

### Browser

Chrome

### Operating System

windows 11

### Additional Context

<img width="321" alt="image" src="https://github.com/user-attachments/assets/cf8b8f63-2120-421a-a304-423ddb32bc68">

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ivoplashkov** [comment]
Hello @balakrishnamanash ,

Thank you for reaching out!

Could you please provide an isolated example by forking [this stackblitz](https://stackblitz.com/edit/js-vsrpnb?file=index.js,index.html), where we can reproduce the issue and examine it.

Best regards,
Ivaylo

**Comment by balakrishnamanash** [comment]
<img width="668" alt="image" src="https://github.com/user-attachments/assets/f7e3444e-2c3f-4347-afd1-d23273a86fb1">
code added in stackblitz.

**Comment by balakrishnamanash** [comment]
last 3rd column  is not speaking in speech history of JAWS july 2024 version

**Comment by ivoplashkov** [comment]
Hello @balakrishnamanash,

Could you please provide the link for the stackblitz?

Thanks and regards,
Ivaylo

**Comment by ivoplashkov** [comment]
Hello colleagues,

I managed to find the stackblitz from the screenshot - https://stackblitz.com/edit/js-eux6au?file=index.html,App.js,index.js. This seems to be related to the React wrapper for webcomponents. As far I saw, the 3rd row which is not conveyed by the screen reader is a custom list item with no aria attributes attached to it at all.

Could you please have a look?
Thank you in advance!

Best regards,
Ivaylo

**Comment by jadhavarjun** [comment]
Hi @ivoplashkov,

I have tried using aria attributes but issue not resolving, Can you please help me with which aria attributes should I used so my issue got resolve. 
In above you mentioned isolated stack blitz link also have same issue in that also not able to read meaningful name by reader, Can you help me with which aria attribute should We used so our issue will got resolved, can you add same into satckblitz- ( https://stackblitz.com/edit/js-eux6au?file=index.html,App.js,index.js) link and send me back.

**Comment by Lukas742** [comment]
Hi @dimovpetar, @jadhavarjun 

as far as I can tell this is a duplicate of: https://github.com/SAP/ui5-webcomponents-react/issues/6132


@jadhavarjun, @balakrishnamanash in the linked issue a solution was provided, if this is not sufficient for your use-case, please add a __detailed__ description what result you would expect. Please do that in the linked issue, as it is most probably either related to your custom implementation, or to the `AnalyticalTable`, but not the `ui5-input` itself.

**Comment by yanaminkova** [comment]
Hello @balakrishnamanash,

It appears this issue is a duplicate of issue https://github.com/SAP/ui5-webcomponents-react/issues/6132 , which was resolved in version v1.29.6 with fix https://github.com/SAP/ui5-webcomponents-react/pull/6164

Could you please confirm if the issue is resolved on your end and if the fix is working as expected?

Thanks and Best regards,
Yana
