### ISSUE TITLE
[DateTimePicker]: Error on Time Wheel Mouseover

### ISSUE THREAD

**Issue by alexaytov** [SAP/ui5-webcomponents#9579]
### Bug Description

Error is logged when mousing over the time wheel in for the DateTimePicker component.
<img width="677" alt="Screenshot 2024-07-30 at 6 25 28" src="https://github.com/user-attachments/assets/ca7a89b8-3a11-47ce-ba6a-40dc29f40ff6">
<img width="1901" alt="Screenshot 2024-07-30 at 6 25 47" src="https://github.com/user-attachments/assets/3ff9eead-f0bf-49e2-9e68-367cc76bf5ac">

### Affected Component

DateTimePicker

### Expected Behaviour

No error to be logged

### Isolated Example

This happens on the example for the DateTimePicker - https://sap.github.io/ui5-webcomponents/components/DateTimePicker/

### Steps to Reproduce

1. Open the dialog
2. Open the console
3. Mouseover the time wheel

### Log Output, Stack Trace or Screenshots

TimePickerClock.js:542 Uncaught 
TypeError: Cannot read properties of undefined (reading 'radius')
    at TimePickerClock._onTouchMove (TimePickerClock.js:542:44)
    at z.handleEvent (lit-html.js:6:7169)

### Priority

Medium

### UI5 Web Components Version

2.0.1

### Browser

Chrome

### Operating System

Macos

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by nnaydenow** [comment]
Hi @hinzzx,

Could you please check if this issues is going to be resolved #9541 too?

**Comment by ivoplashkov** [comment]
Hello colleagues,

The issue is reproduced as described by the reported. Upon mouseovering the TimePickerClock, an exception is thrown in the console, because this._dimensionParameters is undefined. Could you please have a look?

Best regards,
Ivaylo
