### ISSUE TITLE
[@ui5/webcomponents/Input] error thrown when using arrow key to change value in number type input

### ISSUE THREAD

**Issue by sebschn01** [SAP/ui5-webcomponents#9588]
### Bug Description

When using ArrowKey.Up or ArrowKey.Down to change the value in number-type Input, an error is thrown:
```
TypeError: Cannot read properties of undefined (reading 'inputType')
    at Input._handleInput (Input.js:581:25)
    at z.handleEvent (lit-html.js:6:7169)
```

The same issue was reported and fixed with issue #5580 before. I suspect the conversion from .js to .ts re-introduced the issue.
Issue happens both for 1.24.7 and 2.0.1, and can also be seen in ui5/webcomponents-react

### Affected Component

Input

### Expected Behaviour

No error is thrown when changing value using Arrow keys

### Isolated Example

https://js-uugt19.stackblitz.io

### Steps to Reproduce

1. use https://js-uugt19.stackblitz.io or create an input in your playground using `<ui5-input value="Input" type="Number"></ui5-input>`
2. focus input
3. use arrow up or arrow down key to change value
4. see error in console

### Log Output, Stack Trace or Screenshots

```
TypeError: Cannot read properties of undefined (reading 'inputType')
    at Input._handleInput (Input.js:581:25)
    at z.handleEvent (lit-html.js:6:7169)
```

### Priority

Medium

### UI5 Web Components Version

1.24.7, 2.0.1

### Browser

Chrome, Edge

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ivoplashkov** [comment]
Hello colleagues,

The issue is reproduced as described by the reporter and indeed with the TS integration we have skipped the e.detail check in the _handleInput handler. Maybe we need an additional check e.g `const eventType: string = 
    (e && (e as InputEvent).inputType) ||
    (e && e.detail && (e.detail as InputEventDetail).inputType) ||
    "";
`

Best regards,
Ivaylo
