### ISSUE TITLE
Running / configuring tests

### ISSUE THREAD

**Issue by koeppel** [SAP/ui5-webcomponents#9604]
### **Issue Description**
When checking out the repository, installing dependencies and following the normal procedure. I'm not able to run any tests, I always face the same error message:
"This version of ChromeDriver only supports Chrome version 125 [0-0] Current browser version is 127.0.6533.73 with binary path [...]"

There is no clear documentation on where to setup the binary path or the Chrome version. I was also not able to find it in the coding.

After some research on the web I found out that @puppeteer/browsers should handle the installation of the ChromeDriver version. Could you please adopt the documentation / look into testing?

### **Issue Type**

- [X] Documentation is unclear
- [ ] Documentation is incorrect
- [X] Documentation is missing
- [ ] Other

**Comment by ivoplashkov** [comment]
Hello colleagues,

The reporter suggests that we need to enchance our documentation related to the tests execution. Could you please evaluate and decide whether we need to improve the documenation or not.

Best regards,
Ivaylo
