### ISSUE TITLE
TableRow: Type Property not having any impact

### ISSUE THREAD

**Issue by adrianui5** [SAP/ui5-webcomponents#9605]
### Describe the bug

I am using a `MultiSelect Table` containing `TableRows`. I would like to be able to disable some of the `TableRows` so that users cannot select them during the `MultiSelect`. Based on the documentation, I would expect that the type property (`Active`/`Inactive`) would do the job, however, it seems like it does not have any impact on the UI as all `TableRows` continue to be selectable (see example provided). Might also be the case that the type property does not have this purpose, but in that case I would like to ask if there is another way of disabling certain `TableRows`?

### Isolated Example

https://stackblitz.com/edit/github-ekiatg-kev186?file=src%2FApp.tsx

### Reproduction steps

1. Open the provided example.
2. Try to select each `TableRow`.
3. Verify that there is no difference between `Active` and `Inactive` `TableRows`.

### Expected Behaviour

Option to disable certain `TableRows` during the `MultiSelect`.

### UI5 Web Components for React Version

1.29.2

### UI5 Web Components Version

1.24.4

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by adrianui5** [comment]
Hi @ivoplashkov,

I understand the `Type` Property is not the correct Property to disable `TableRows `based on the information provided by @MarcusNotheis. However, as this disabling feature is important for our development, could you please let me know if there is any other property we could make use of for this purpose, or would I maybe need to create a `Feature Request` ticket?

Best regards,
Adrian

**Comment by ivoplashkov** [comment]
Hello colleagues,

Currently there seems to be no way to achieve a disabled TableRow through the API of the component. Could you please evaluate if this is something to be implemented.

Thank you in advance!
Best regards,
Ivaylo

**Comment by adrianui5** [comment]
Hi @ivoplashkov,

I have created a Feature Request ticket: https://github.com/SAP/ui5-webcomponents/issues/9627.
Thanks in advance,

Adrian

**Comment by ivoplashkov** [comment]
Hello, 

Since you have created a dedicated feature request, I will close this issue as completed and process the feature request instead.

Regards,
Ivaylo
