### ISSUE TITLE
[Select] Grid layout select options

### ISSUE THREAD

**Issue by 3bwong** [SAP/ui5-webcomponents#9613]
### Is your feature request related to a problem?

Currently, Select Options are shown in list only but in some occasions, we would like it to be in grid layout, so users can see all options when there is a long list or when there are images to visualize the selection. We tried SelectMenu(Option) but it can only customize the option content, not the popover layout.

### Describe the solution you'd like

![Screenshot 2024-07-31 at 10 55 11 PM](https://github.com/user-attachments/assets/d4320397-c98a-4c87-a4bd-c56250731a45)

### Organization

SAC

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ivoplashkov** [comment]
Hello colleagues,

Could you please have a look at this feature request and evaluate if this is something to consider implementing.
Thank you in advance!

Best regards,
Ivaylo

**Comment by dobrinyonkov** [comment]
Hello @3bwong,

this feature request should go through the inner source process. Could you please create a Jira item for Central Design and include the E1 reference number here? 
Let me know if you have questions!

Thanks and Best Regards,
Dobrin
