### ISSUE TITLE
Slider and Range Slider: Wrong Font and Wrong Handle Width

### ISSUE THREAD

**Issue by siyanadicheva** [SAP/ui5-webcomponents#9614]
### Bug Description

How it is now:
<img width="1131" alt="Screenshot 2024-08-01 at 8 29 23" src="https://github.com/user-attachments/assets/b446fcb5-e025-471d-bad6-986bd13b62a8">

The font of the numbers should be --sapFontSmallSize (72 font):
![Font](https://github.com/user-attachments/assets/288c7d05-1010-4169-bd30-ac21fdf2f62d)

The handles should be with width: 1.5rem in Compact and width: 2rem in Cozy:
![Compact](https://github.com/user-attachments/assets/6c0dfa05-c2e8-40bf-a418-a54db32c37d4)
![Cozy](https://github.com/user-attachments/assets/1130fe45-b26a-464c-b6c9-e030e308b10b)

Link to Visual Spec: https://wiki.one.int.sap/wiki/pages/viewpage.action?pageId=2698915260

The same applies for Range Slider.

### Affected Component

Slider and Range Slider

### Priority

None

### UI5 Web Components Version

https://sap.github.io/ui5-webcomponents/components/Slider/

### Browser

Chrome

### Operating System

iOS

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ivoplashkov** [comment]
Hello colleagues,

The width of the handles and fontsize of the labels of the Slider/RangeSlider seems to be incorrect according to the visual spec. Could you please have a look?

Best regards,
Ivaylo
