### ISSUE TITLE
[MultiComboBox]:  When Pressing Enter inside MultiComboBox to AutoComplete the Suggestion the Form is Submitted

### ISSUE THREAD

**Issue by alexaytov** [SAP/ui5-webcomponents#9624]
### Bug Description

When you have a multi combo box and you start typing a letter: ex 'A' an autocompletion pops up (ex: Argentina). In order to select the autocompletion I press enter. But instead of only the autocompletion to be selected the whole form is submitted.

### Affected Component

MultiComboBox

### Expected Behaviour

The form to not be submitted but only the suggestion to be selected

### Isolated Example

https://stackblitz.com/edit/js-kynzaf?file=index.js

### Steps to Reproduce

1. Open the dialog
2. Enter the letter A
3. Press enter
4. Observe the form is submitted in the console

### Priority

High

### UI5 Web Components Version

2.0.1

### Browser

Chrome

### Operating System

Macos

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ivoplashkov** [comment]
Hello colleagues,

The issue is reproduced as described by the reporter.

Best regards,
Ivaylo
