### ISSUE TITLE
[Feature Request]: Action List Item

### ISSUE THREAD

**Issue by 3bwong** [SAP/ui5-webcomponents#9647]
### Feature Request Description

Currently there is not any support with Action List Item like regular UI5. We would like to have the ability to add our own action list item apart from growing button.

### Proposed Solution

https://sapui5.hana.ondemand.com/sdk#/entity/sap.m.ActionListItem/sample/sap.m.sample.ActionListItem

### Organization

SAC

### Priority

None

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by dimovpetar** [comment]
Hello @ui5-webcomponents-topic-p,

Please check out this feature request for another list item.

Best regards,
Petar

**Comment by dobrinyonkov** [comment]
Hello @3bwong,

this feature request should go through the inner source process. Could you please create a Jira item for Central Design and include the E1 reference number here?
Let me know if you have questions!

Thanks and Best Regards,
Dobrin
