### ISSUE TITLE
[SF_ACC][ui5-breadcrumbs]: 'current page link' is not read out when last/current item is focused

### ISSUE THREAD

**Issue by i323808** [SAP/ui5-webcomponents#9648]
### Bug Description

Information such as 'current page link' is not read out when user focus the last/current item of breadcrumbs.

### Affected Component

ui5-breadcrumbs

### Expected Behaviour

'current page link' is supposed to be read out likes https://ui5.sap.com/#/entity/sap.m.Breadcrumbs/sample/sap.m.sample.Breadcrumbs. 

### Steps to Reproduce

1.
2.
3.
...

### Priority

None

### UI5 Web Components Version

1.24.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by dimovpetar** [comment]
Hello @ui5-webcomponents-topic-p,

This issue can be reproduced here https://sap.github.io/ui5-webcomponents/v1/components/Breadcrumbs/#basic-sample.

Best regards,
Petar
