### ISSUE TITLE
Upload collection retry button can't be used with keyboard (accessibility issue)

### ISSUE THREAD

**Issue by katapp** [SAP/ui5-webcomponents#9655]
Hi, 
In the web component upload collection 
https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-uploadcollection–docs
the retry button can't be used with the keyboard. But this is an accessibility standard.

Is this already known?

BR, Kathrin

**Comment by dimovpetar** [comment]
Hello @katapp ,

When you reach any upload collection item with retry button, you can go further with the `Tab` key. Have you tried it?
[Here ](https://sap.github.io/ui5-webcomponents/play/#eyJpbmRleC5odG1sIjp7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuPCFET0NUWVBFIGh0bWw-XG48aHRtbCBsYW5nPVwiZW5cIj5cblxuXG48aGVhZD5cbiAgICBcbiAgICA8c3R5bGU-XG4gICAgICAqOm5vdCg6ZGVmaW5lZCkge1xuICAgICAgICBkaXNwbGF5OiBub25lO1xuICAgICAgfVxuICAgIDwvc3R5bGU-XG5cbiAgICA8bWV0YSBjaGFyc2V0PVwiVVRGLThcIj5cbiAgICA8bWV0YSBuYW1lPVwidmlld3BvcnRcIiBjb250ZW50PVwid2lkdGg9ZGV2aWNlLXdpZHRoLCBpbml0aWFsLXNjYWxlPTEuMFwiPlxuICAgIDx0aXRsZT5TYW1wbGU8L3RpdGxlPlxuPC9oZWFkPlxuXG48Ym9keSBzdHlsZT1cImJhY2tncm91bmQtY29sb3I6IHZhcigtLXNhcEJhY2tncm91bmRDb2xvcilcIj5cbiAgICA8IS0tIHBsYXlncm91bmQtZm9sZC1lbmQgLS0-XG5cbiAgICA8dWk1LXVwbG9hZC1jb2xsZWN0aW9uPlxuICAgICAgICA8ZGl2IHNsb3Q9XCJoZWFkZXJcIiBjbGFzcz1cImhlYWRlclwiPlxuICAgICAgICAgICAgPHVpNS10aXRsZT5BdHRhY2htZW50cyAoMik8L3VpNS10aXRsZT5cbiAgICAgICAgPC9kaXY-XG5cbiAgICAgICAgPHVpNS11cGxvYWQtY29sbGVjdGlvbi1pdGVtIGZpbGUtbmFtZT1cIkxhcHRvcEhULTEwMDAuanBnXCIgdXBsb2FkLXN0YXRlPVwiQ29tcGxldGVcIj5cbiAgICAgICAgICAgIHVwbG9hZFN0YXRlPVwiQ29tcGxldGVcIlxuICAgICAgICAgICAgPGltZyBzcmM9XCJodHRwczovL3NhcC5naXRodWIuaW8vdWk1LXdlYmNvbXBvbmVudHMvaW1hZ2VzL0hULTEwMDAuanBnXCIgc2xvdD1cInRodW1ibmFpbFwiPlxuICAgICAgICA8L3VpNS11cGxvYWQtY29sbGVjdGlvbi1pdGVtPlxuXG4gICAgICAgIDx1aTUtdXBsb2FkLWNvbGxlY3Rpb24taXRlbSBmaWxlLW5hbWU9XCJMYXB0b3AuanBnXCIgdXBsb2FkLXN0YXRlPVwiVXBsb2FkaW5nXCIgdHlwZT1cIkFjdGl2ZVwiIHByb2dyZXNzPVwiMzdcIj5cbiAgICAgICAgICAgIHVwbG9hZFN0YXRlPVwiVXBsb2FkaW5nXCJcbiAgICAgICAgICAgIDxpbWcgc3JjPVwiaHR0cHM6Ly9zYXAuZ2l0aHViLmlvL3VpNS13ZWJjb21wb25lbnRzL2ltYWdlcy9IVC0xMDAwLmpwZ1wiIHNsb3Q9XCJ0aHVtYm5haWxcIj5cbiAgICAgICAgPC91aTUtdXBsb2FkLWNvbGxlY3Rpb24taXRlbT5cblxuICAgICAgICA8dWk1LXVwbG9hZC1jb2xsZWN0aW9uLWl0ZW0gZmlsZS1uYW1lPVwibGF0ZXN0LXJlcG9ydHMucGRmXCIgdXBsb2FkLXN0YXRlPVwiRXJyb3JcIiB0eXBlPVwiQWN0aXZlXCIgcHJvZ3Jlc3M9XCI1OVwiPlxuICAgICAgICAgICAgdXBsb2FkU3RhdGU9XCJFcnJvclwiXG4gICAgICAgICAgICA8dWk1LWljb24gbmFtZT1cImRvY3VtZW50LXRleHRcIiBzbG90PVwidGh1bWJuYWlsXCI-PC91aTUtaWNvbj5cbiAgICAgICAgPC91aTUtdXBsb2FkLWNvbGxlY3Rpb24taXRlbT5cblxuICAgICAgICA8dWk1LXVwbG9hZC1jb2xsZWN0aW9uLWl0ZW0gZmlsZS1uYW1lPVwiTm90ZXMudHh0XCIgdXBsb2FkLXN0YXRlPVwiUmVhZHlcIj5cbiAgICAgICAgICAgIHVwbG9hZFN0YXRlPVwiUmVhZHlcIiAoZGVmYXVsdClcbiAgICAgICAgICAgIDx1aTUtaWNvbiBuYW1lPVwiZG9jdW1lbnQtdGV4dFwiIHNsb3Q9XCJ0aHVtYm5haWxcIj48L3VpNS1pY29uPlxuICAgICAgICA8L3VpNS11cGxvYWQtY29sbGVjdGlvbi1pdGVtPlxuICAgIDwvdWk1LXVwbG9hZC1jb2xsZWN0aW9uPlxuICAgIDwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuICAgIDxzY3JpcHQgdHlwZT1cIm1vZHVsZVwiIHNyYz1cIm1haW4uanNcIj48L3NjcmlwdD5cbjwvYm9keT5cblxuPC9odG1sPlxuPCEtLSBwbGF5Z3JvdW5kLWZvbGQtZW5kIC0tPlxuIn0sIm1haW4uanMiOnsibmFtZSI6Im1haW4uanMiLCJjb250ZW50IjoiLyogcGxheWdyb3VuZC1oaWRlICovXG5pbXBvcnQgXCIuL3BsYXlncm91bmQtc3VwcG9ydC5qc1wiO1xuLyogcGxheWdyb3VuZC1oaWRlLWVuZCAqL1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzL2Rpc3QvVGl0bGUuanNcIjtcblxuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzLWZpb3JpL2Rpc3QvVXBsb2FkQ29sbGVjdGlvbi5qc1wiO1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzLWZpb3JpL2Rpc3QvVXBsb2FkQ29sbGVjdGlvbkl0ZW0uanNcIjtcblxuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzLWljb25zL2Rpc3QvZG9jdW1lbnQtdGV4dC5qc1wiO1xuXG52YXIgdXBsb2FkQ29sbGVjdGlvbiA9IGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoXCJ1aTUtdXBsb2FkLWNvbGxlY3Rpb25cIik7XG5cbnVwbG9hZENvbGxlY3Rpb24uYWRkRXZlbnRMaXN0ZW5lcihcInJldHJ5XCIsIGUgPT4ge1xuICAgIGFsZXJ0KFwiUmV0cnkgdXBsb2FkaW5nOiBcIiArIGUudGFyZ2V0LmZpbGVOYW1lKTtcbn0pO1xudXBsb2FkQ29sbGVjdGlvbi5hZGRFdmVudExpc3RlbmVyKFwidGVybWluYXRlXCIsIGUgPT4ge1xuICAgIGFsZXJ0KFwiVGVybWluYXRlIHVwbG9hZGluZyBvZjogXCIgKyBlLnRhcmdldC5maWxlTmFtZSk7XG59KTtcblxudXBsb2FkQ29sbGVjdGlvbi5hZGRFdmVudExpc3RlbmVyKFwidWk1LWl0ZW0tZGVsZXRlXCIsIGUgPT4ge1xuICAgIHVwbG9hZENvbGxlY3Rpb24ucmVtb3ZlQ2hpbGQoZS5kZXRhaWwuaXRlbSk7XG59KTsifX0)is a working example.

Best regards,
Petar

**Comment by katapp** [comment]
After checking with my dev colleague it is an issue in v1 of ui5/webcomponents, it was fixed in v2. The React wrapper library ui5/webcomponents-react does not have a stable version that supports v2 yet, but it is planned to be released in Q3 2024.
then will will wait for the release.
