### ISSUE TITLE
[SF_ACC][ui5-wizard]: Repetitive wizard step names are provided in the unique accessible names list

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents#9659]
### Bug Description

 Repetitive wizard step names are provided in the unique accessible names list

### Affected Component

ui5-wizard

### Expected Behaviour

Repetitive wizard step names should not be provided. Name of each wizard step can be provided once in the unique accessible names list.

### Steps to Reproduce

1. open [page](https://sap.github.io/ui5-webcomponents/v1/play/#eyJpbmRleC5odG1sIjp7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuPCFET0NUWVBFIGh0bWw-XG48aHRtbCBsYW5nPVwiZW5cIj5cblxuXG48aGVhZD5cbiAgICBcbiAgICA8c3R5bGU-XG4gICAgICAqOm5vdCg6ZGVmaW5lZCkge1xuICAgICAgICBkaXNwbGF5OiBub25lO1xuICAgICAgfVxuICAgIDwvc3R5bGU-XG5cbiAgICA8bWV0YSBjaGFyc2V0PVwiVVRGLThcIj5cbiAgICA8bWV0YSBuYW1lPVwidmlld3BvcnRcIiBjb250ZW50PVwid2lkdGg9ZGV2aWNlLXdpZHRoLCBpbml0aWFsLXNjYWxlPTEuMFwiPlxuICAgIDx0aXRsZT5TYW1wbGU8L3RpdGxlPlxuPC9oZWFkPlxuXG48Ym9keSBzdHlsZT1cImJhY2tncm91bmQtY29sb3I6IHZhcigtLXNhcEJhY2tncm91bmRDb2xvcik7IGhlaWdodDogNjAwcHg7XCI-XG4gICAgPCEtLSBwbGF5Z3JvdW5kLWZvbGQtZW5kIC0tPlxuXG4gICAgPHVpNS1kaWFsb2cgaWQ9XCJkaWFsb2dcIiBzdHJldGNoIGhlYWRlci1oZWFkaW5nPVwiV2l6YXJkXCI-XG4gICAgICAgIDx1aTUtd2l6YXJkIGlkPVwid2l6XCIgY29udGVudC1sYXlvdXQ9XCJTaW5nbGVTdGVwXCI-XG4gICAgICAgICAgICA8dWk1LXdpemFyZC1zdGVwIGljb249XCJwcm9kdWN0XCIgdGl0bGUtdGV4dD1cIlByb2R1Y3QgdHlwZVwiIHNlbGVjdGVkPVwiXCI-XG4gICAgICAgICAgICAgICAgPGRpdiBzdHlsZT1cImRpc3BsYXk6IGZsZXg7IG1pbi1oZWlnaHQ6IDIwMHB4OyBmbGV4LWRpcmVjdGlvbjogY29sdW1uO1wiPlxuICAgICAgICAgICAgICAgICAgICA8dWk1LXRpdGxlPjEuIFByb2R1Y3QgVHlwZTwvdWk1LXRpdGxlPjxiciAvPlxuICAgICAgICAgICAgICAgICAgICA8dWk1LW1lc3NhZ2Utc3RyaXA-XG4gICAgICAgICAgICAgICAgICAgICAgICBUaGUgV2l6YXJkIGNvbnRyb2wgaXMgc3VwcG9zZWQgdG8gYnJlYWsgZG93biBsYXJnZSB0YXNrcywgaW50byBzbWFsbGVyIHN0ZXBzLCBlYXNpZXIgZm9yIHRoZVxuICAgICAgICAgICAgICAgICAgICAgICAgdXNlciB0byB3b3JrIHdpdGguXG4gICAgICAgICAgICAgICAgICAgIDwvdWk1LW1lc3NhZ2Utc3RyaXA-PGJyIC8-XG4gICAgICAgICAgICAgICAgICAgIDx1aTUtbGFiZWwgd3JhcHBpbmctdHlwZT1cIk5vcm1hbFwiPlNlZCBmZXJtZW50dW0sIG1pIGV0IHRyaXN0aXF1ZSB1bGxhbWNvcnBlciwgc2FwaWVuIHNhcGllbiBmYXVjaWJ1c1xuICAgICAgICAgICAgICAgICAgICAgICAgc2VtLCBxdWlzIHByZXRpdW0gbmliaCBsb3JlbSBtYWxlc3VhZGEgZGlhbS4gTnVsbGEgcXVpcyBhcmN1IGFsaXF1ZXQsIGZldWdpYXQgbWFzc2Egc2VtcGVyLFxuICAgICAgICAgICAgICAgICAgICAgICAgdm9sdXRwYXQgZGlhbS4gTmFtIHZpdGFlIGFudGUgcG9zdWVyZSwgbW9sZXN0aWUgbmVxdWUgc2l0IGFtZXQsIGRhcGlidXMgdmVsaXQuIE1hZWNlbmFzIGVsZWlmZW5kXG4gICAgICAgICAgICAgICAgICAgICAgICB0ZW1wb3IgbG9yZW0uIE1hdXJpcyB2aXRhZSBlbGVtZW50dW0gbWksIHNlZCBlbGVpZmVuZCBsaWd1bGEuIE51bGxhIHRlbXBvciB2dWxwdXRhdGUgZG9sb3IsIG5lY1xuICAgICAgICAgICAgICAgICAgICAgICAgZGlnbmlzc2ltIHF1YW0gY29udmFsbGlzIHV0LiBQcmFlc2VudCB2aXRhZSBjb21tb2RvIGZlbGlzLCB1dCBpYWN1bGlzIGZlbGlzLiBGdXNjZSBxdWlzIGVsZWlmZW5kXG4gICAgICAgICAgICAgICAgICAgICAgICBzYXBpZW4sIGVnZXQgZmFjaWxpc2lzIG5pYmguIFN1c3BlbmRpc3NlIGVzdCB2ZWxpdCwgc2NlbGVyaXNxdWUgdXQgY29tbW9kbyBlZ2V0LCBkaWduaXNzaW0gcXVpc1xuICAgICAgICAgICAgICAgICAgICAgICAgbWV0dXMuIENyYXMgZmF1Y2lidXMgY29uc2VxdWF0IGdyYXZpZGEuIEN1cmFiaXR1ciB2aXRhZSBxdWFtIGZlbGlzLiBQaGFzZWxsdXMgYWMgbGVvIGVsZWlmZW5kLFxuICAgICAgICAgICAgICAgICAgICAgICAgY29tbW9kbyB0b3J0b3IgZXQsIHZhcml1cyBxdWFtLiBBbGlxdWFtIGVyYXQgdm9sdXRwYXQuXG4gICAgICAgICAgICAgICAgICAgIDwvdWk1LWxhYmVsPlxuICAgICAgICAgICAgICAgIDwvZGl2PlxuICAgICAgICAgICAgPC91aTUtd2l6YXJkLXN0ZXA-XG4gICAgICAgICAgICA8dWk1LXdpemFyZC1zdGVwIGljb249XCJoaW50XCIgdGl0bGUtdGV4dD1cIlByb2R1Y3QgSW5mb3JtYXRpb25cIiBkaXNhYmxlZD1cIlwiPlxuICAgICAgICAgICAgICAgIDxkaXYgc3R5bGU9XCJkaXNwbGF5OiBmbGV4O2ZsZXgtZGlyZWN0aW9uOiBjb2x1bW5cIj5cbiAgICAgICAgICAgICAgICAgICAgPHVpNS10aXRsZT4yLiBQcm9kdWN0IEluZm9ybWF0aW9uPC91aTUtdGl0bGU-PGJyIC8-XG4gICAgICAgICAgICAgICAgICAgIDx1aTUtbGFiZWwgd3JhcHBpbmctdHlwZT1cIk5vcm1hbFwiPlxuICAgICAgICAgICAgICAgICAgICAgICAgSW50ZWdlciBwZWxsZW50ZXNxdWUgbGVvIHNpdCBhbWV0IGR1aSB2ZWhpY3VsYSwgcXVpcyB1bGxhbWNvcnBlciBlc3QgcHVsdmluYXIuIE5hbSBpbiBsaWJlcm9cbiAgICAgICAgICAgICAgICAgICAgICAgIHNlbS4gU3VzcGVuZGlzc2UgYXJjdSBtZXR1cywgbW9sZXN0aWUgYSB0dXJwaXMgYSwgbW9sZXN0aWUgYWxpcXVldCBkdWkuIERvbmVjIHBwZWxsZW50ZXNxdWUgbGVvXG4gICAgICAgICAgICAgICAgICAgICAgICBzaXQgYW1ldCBkdWkgdmVoaWN1bGEsIHF1aXMgdWxsYW1jb3JwZXIgZXN0IHB1bHZpbmFyLiBOYW0gaW4gbGliZXJvIHNlbS4gU3VzcGVuZGlzc2UgYXJjdSBtZXR1cyxcbiAgICAgICAgICAgICAgICAgICAgICAgIG1vbGVzdGllIGEgdHVycGlzIGEsIG1vbGVzdGllIGFsaXF1ZXQgZHVpLiBEb25lYyBwdWx2aW5hciwgc2FwaWVuIGNvcnBlciBldSwgcG9zdWVyZSBtYWxlc3VhZGFcbiAgICAgICAgICAgICAgICAgICAgICAgIG5pc2wuIEludGVnZXIgcGVsbGVudGVzcXVlIGxlbyBzaXQgYW1ldCBkdWkgdmVoaWN1bGEsIHF1aXMgdWxsYW1jb3JwZXIgZXN0IHB1bHZpbmFyLiBOYW0gaW5cbiAgICAgICAgICAgICAgICAgICAgICAgIGxpYmVybyBzZW0uIFN1c3BlbmRpc3NlIGFyY3UgbWV0dXMsIG1vbGVzdGllIGEgdHVycGlzIGEsIG1vbGVzdGllIGFsaXF1ZXQgZHVpLiBEb25lYyBwdWx2aW5hcixcbiAgICAgICAgICAgICAgICAgICAgICAgIHNhcGllblxuICAgICAgICAgICAgICAgICAgICA8L3VpNS1sYWJlbD5cbiAgICAgICAgICAgICAgICAgICAgPGRpdiBzdHlsZT1cImRpc3BsYXk6IGZsZXg7IGZsZXgtZGlyZWN0aW9uOiBjb2x1bW47XCI-XG4gICAgICAgICAgICAgICAgICAgICAgICA8ZGl2XG4gICAgICAgICAgICAgICAgICAgICAgICAgICAgc3R5bGU9XCJkaXNwbGF5OiBmbGV4OyBmbGV4LWRpcmVjdGlvbjogcm93OyBqdXN0aWZ5LWNvbnRlbnQ6IGZsZXgtZW5kOyBhbGlnbi1pdGVtczogY2VudGVyOyBtYXJnaW4tdG9wOiAxcmVtXCI-XG4gICAgICAgICAgICAgICAgICAgICAgICAgICAgPHVpNS1sYWJlbD5OYW1lPC91aTUtbGFiZWw-XG4gICAgICAgICAgICAgICAgICAgICAgICAgICAgPHVpNS1pbnB1dCBwbGFjZWhvbGRlcj1cInByb2R1Y3QgbmFtZS4uLlwiPjwvdWk1LWlucHV0PlxuICAgICAgICAgICAgICAgICAgICAgICAgPC9kaXY-XG4gICAgICAgICAgICAgICAgICAgICAgICA8ZGl2XG4gICAgICAgICAgICAgICAgICAgICAgICAgICAgc3R5bGU9XCJkaXNwbGF5OiBmbGV4OyBmbGV4LWRpcmVjdGlvbjogcm93OyBtYXJnaW4tdG9wOiAxcmVtOyBqdXN0aWZ5LWNvbnRlbnQ6IGZsZXgtZW5kOyBhbGlnbi1pdGVtczogY2VudGVyO1wiPlxuICAgICAgICAgICAgICAgICAgICAgICAgICAgIDx1aTUtbGFiZWw-V2VpZ2h0PC91aTUtbGFiZWw-XG4gICAgICAgICAgICAgICAgICAgICAgICAgICAgPHVpNS1pbnB1dCB2YWx1ZT1cIjMuNjVcIj48L3VpNS1pbnB1dD5cbiAgICAgICAgICAgICAgICAgICAgICAgIDwvZGl2PlxuICAgICAgICAgICAgICAgICAgICAgICAgPGRpdlxuICAgICAgICAgICAgICAgICAgICAgICAgICAgIHN0eWxlPVwiZGlzcGxheTogZmxleDsgZmxleC1kaXJlY3Rpb246IHJvdzsgbWFyZ2luLXRvcDogMXJlbTsganVzdGlmeS1jb250ZW50OiBmbGV4LWVuZDsgYWxpZ24taXRlbXM6IGNlbnRlcjtcIj5cbiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8dWk1LWxhYmVsPk1hbmlmYWN0dXJlcjwvdWk1LWxhYmVsPlxuICAgICAgICAgICAgICAgICAgICAgICAgICAgIDx1aTUtc2VsZWN0PlxuICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8dWk1LW9wdGlvbiBzZWxlY3RlZD1cIlwiPkFwcGxlPC91aTUtb3B0aW9uPlxuICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8dWk1LW9wdGlvbj5TYW1zdW5nPC91aTUtb3B0aW9uPlxuICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8dWk1LW9wdGlvbj5IdWF3ZWk8L3VpNS1vcHRpb24-XG4gICAgICAgICAgICAgICAgICAgICAgICAgICAgPC91aTUtc2VsZWN0PlxuICAgICAgICAgICAgICAgICAgICAgICAgPC9kaXY-XG4gICAgICAgICAgICAgICAgICAgICAgICA8ZGl2XG4gICAgICAgICAgICAgICAgICAgICAgICAgICAgc3R5bGU9XCJkaXNwbGF5OiBmbGV4OyBmbGV4LWRpcmVjdGlvbjogcm93OyBtYXJnaW4tdG9wOiAxcmVtOyBqdXN0aWZ5LWNvbnRlbnQ6IGZsZXgtZW5kOyBhbGlnbi1pdGVtczogY2VudGVyO1wiPlxuICAgICAgICAgICAgICAgICAgICAgICAgICAgIDx1aTUtbGFiZWw-NSB5ZWFycyBndWFyYW50ZWUgaW5jbHVkZWQ8L3VpNS1sYWJlbD5cbiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8dWk1LXN3aXRjaCBpZD1cIndpei1zd1wiPjwvdWk1LXN3aXRjaD5cbiAgICAgICAgICAgICAgICAgICAgICAgIDwvZGl2PlxuICAgICAgICAgICAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgICAgIDwvdWk1LXdpemFyZC1zdGVwPlxuICAgICAgICAgICAgPHVpNS13aXphcmQtc3RlcCBpY29uPVwiYWN0aW9uLXNldHRpbmdzXCIgdGl0bGUtdGV4dD1cIk9wdGlvbnNcIiBkaXNhYmxlZD1cIlwiPlxuICAgICAgICAgICAgICAgIDxkaXYgc3R5bGU9XCJkaXNwbGF5OiBmbGV4OyBmbGV4LWRpcmVjdGlvbjogY29sdW1uO1wiPlxuICAgICAgICAgICAgICAgICAgICA8dWk1LXRpdGxlPjMuIE9wdGlvbnM8L3VpNS10aXRsZT48YnIgLz5cbiAgICAgICAgICAgICAgICAgICAgPHVpNS1sYWJlbCB3cmFwcGluZy10eXBlPVwiTm9ybWFsXCI-XG4gICAgICAgICAgICAgICAgICAgICAgICBJbnRlZ2VyIHBlbGxlbnRlc3F1ZSBsZW8gc2l0IGFtZXQgZHVpIHZlaGljdWxhLCBxdWlzIHVsbGFtY29ycGVyIGVzdCBwdWx2aW5hci4gTmFtIGluIGxpYmVyb1xuICAgICAgICAgICAgICAgICAgICAgICAgc2VtLiBTdXNwZW5kaXNzZSBhcmN1IG1ldHVzLCBtb2xlc3RpZSBhIHR1cnBpcyBhLCBtb2xlc3RpZSBhbGlxdWV0IGR1aS4gRG9uZWMgcHBlbGxlbnRlc3F1ZSBsZW9cbiAgICAgICAgICAgICAgICAgICAgICAgIHNpdCBhbWV0IGR1aSB2ZWhpY3VsYSwgcXVpcyB1bGxhbWNvcnBlciBlc3QgcHVsdmluYXIuIE5hbSBpbiBsaWJlcm8gc2VtLiBTdXNwZW5kaXNzZSBhcmN1IG1ldHVzLFxuICAgICAgICAgICAgICAgICAgICAgICAgbW9sZXN0aWUgYSB0dXJwaXMgYSwgbW9sZXN0aWUgYWxpcXVldCBkdWkuIERvbmVjIHB1bHZpbmFyLCBzYXBpZW4gY29ycGVyIGV1LCBwb3N1ZXJlIG1hbGVzdWFkYVxuICAgICAgICAgICAgICAgICAgICAgICAgbmlzbC4gSW50ZWdlciBwZWxsZW50ZXNxdWUgbGVvIHNpdCBhbWV0IGR1aSB2ZWhpY3VsYSwgcXVpcyB1bGxhbWNvcnBlciBlc3QgcHVsdmluYXIuIE5hbSBpblxuICAgICAgICAgICAgICAgICAgICAgICAgbGliZXJvIHNlbS4gU3VzcGVuZGlzc2UgYXJjdSBtZXR1cywgbW9sZXN0aWUgYSB0dXJwaXMgYSwgbW9sZXN0aWUgYWxpcXVldCBkdWkuIERvbmVjIHB1bHZpbmFyLFxuICAgICAgICAgICAgICAgICAgICAgICAgc2FwaWVuXG4gICAgICAgICAgICAgICAgICAgIDwvdWk1LWxhYmVsPlxuICAgICAgICAgICAgICAgICAgICA8dWk1LW1lc3NhZ2Utc3RyaXA-XG4gICAgICAgICAgICAgICAgICAgICAgICBUaGUgV2l6YXJkIGNvbnRyb2wgaXMgc3VwcG9zZWQgdG8gYnJlYWsgZG93biBsYXJnZSB0YXNrcywgaW50byBzbWFsbGVyIHN0ZXBzLCBlYXNpZXIgZm9yIHRoZVxuICAgICAgICAgICAgICAgICAgICAgICAgdXNlciB0byB3b3JrIHdpdGguXG4gICAgICAgICAgICAgICAgICAgIDwvdWk1LW1lc3NhZ2Utc3RyaXA-PGJyIC8-XG4gICAgICAgICAgICAgICAgICAgIDxkaXYgc3R5bGU9XCJkaXNwbGF5OiBmbGV4OyBmbGV4LWRpcmVjdGlvbjogY29sdW1uO1wiPlxuICAgICAgICAgICAgICAgICAgICAgICAgPGRpdlxuICAgICAgICAgICAgICAgICAgICAgICAgICAgIHN0eWxlPVwiZGlzcGxheTogZmxleDsgZmxleC1kaXJlY3Rpb246IHJvdzsganVzdGlmeS1jb250ZW50OiBmbGV4LWVuZDsgYWxpZ24taXRlbXM6IGNlbnRlcjsgbWFyZ2luLXRvcDogMXJlbVwiPlxuICAgICAgICAgICAgICAgICAgICAgICAgICAgIDx1aTUtbGFiZWw-TWFuaWZhY3R1cmUgZGF0ZTwvdWk1LWxhYmVsPlxuICAgICAgICAgICAgICAgICAgICAgICAgICAgIDx1aTUtZGF0ZS1waWNrZXIgaWQ9XCJ3aXotZHBcIj48L3VpNS1kYXRlLXBpY2tlcj5cbiAgICAgICAgICAgICAgICAgICAgICAgIDwvZGl2PlxuICAgICAgICAgICAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgICAgIDwvdWk1LXdpemFyZC1zdGVwPlxuICAgICAgICA8L3VpNS13aXphcmQ-XG4gICAgICAgIDx1aTUtYmFyIGlkPVwiZm9vdGVyXCIgc2xvdD1cImZvb3RlclwiIGRlc2lnbj1cIkZvb3RlclwiPlxuICAgICAgICAgICAgPHVpNS1idXR0b24gaWQ9XCJwcmV2QnV0dG9uXCIgZGVzaWduPVwiRW1waGFzaXplZFwiIHNsb3Q9XCJlbmRDb250ZW50XCI-UHJldmlvdXMgU3RlcDwvdWk1LWJ1dHRvbj5cbiAgICAgICAgICAgIDx1aTUtYnV0dG9uIGlkPVwibmV4dEJ1dHRvblwiIGRlc2lnbj1cIkVtcGhhc2l6ZWRcIiBzbG90PVwiZW5kQ29udGVudFwiPk5leHQgc3RlcDwvdWk1LWJ1dHRvbj5cbiAgICAgICAgICAgIDx1aTUtYnV0dG9uIGlkPVwid2l6LWZpbmFsaXplXCIgZGVzaWduPVwiRW1waGFzaXplZFwiIHNsb3Q9XCJlbmRDb250ZW50XCI-RmluYWxpemU8L3VpNS1idXR0b24-XG4gICAgICAgICAgICA8dWk1LWJ1dHRvbiBpZD1cImNhbmNlbFwiIGRlc2lnbj1cIlRyYW5zcGFyZW50XCIgc2xvdD1cImVuZENvbnRlbnRcIj5DYW5jZWw8L3VpNS1idXR0b24-XG4gICAgICAgIDwvdWk1LWJhcj5cbiAgICA8L3VpNS1kaWFsb2c-XG4gICAgPHVpNS1idXR0b24gaWQ9XCJidXR0b25cIj5PcGVuIGRpYWxvZzwvdWk1LWJ1dHRvbj5cbiAgICA8IS0tIHBsYXlncm91bmQtZm9sZCAtLT5cbiAgICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCJtYWluLmpzXCI-PC9zY3JpcHQ-XG48L2JvZHk-XG5cbjwvaHRtbD5cbjwhLS0gcGxheWdyb3VuZC1mb2xkLWVuZCAtLT5cbiJ9LCJtYWluLmpzIjp7Im5hbWUiOiJtYWluLmpzIiwiY29udGVudCI6Ii8qIHBsYXlncm91bmQtaGlkZSAqL1xuaW1wb3J0IFwiLi9wbGF5Z3JvdW5kLXN1cHBvcnQuanNcIjtcbi8qIHBsYXlncm91bmQtaGlkZS1lbmQgKi9cbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L1RpdGxlLmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMvZGlzdC9NZXNzYWdlU3RyaXAuanNcIjtcbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L0xhYmVsLmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMvZGlzdC9CdXR0b24uanNcIjtcbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L0lucHV0LmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMvZGlzdC9TZWxlY3QuanNcIjtcbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L09wdGlvbi5qc1wiO1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzL2Rpc3QvRGF0ZVBpY2tlci5qc1wiO1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzL2Rpc3QvU3dpdGNoLmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMvZGlzdC9EaWFsb2cuanNcIjtcblxuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzLWZpb3JpL2Rpc3QvV2l6YXJkLmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMtZmlvcmkvZGlzdC9XaXphcmRTdGVwLmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMtZmlvcmkvZGlzdC9CYXIuanNcIjtcblxuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzLWljb25zL2Rpc3QvcHJvZHVjdC5qc1wiO1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzLWljb25zL2Rpc3QvaGludC5qc1wiO1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzLWljb25zL2Rpc3QvYWN0aW9uLXNldHRpbmdzLmpzXCI7XG5cbmNvbnN0IGJ0bk9wZW5kaWFsb2cgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZChcImJ1dHRvblwiKTtcbmNvbnN0IGRpYWxvZyA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKFwiZGlhbG9nXCIpO1xuY29uc3QgbmV4dFN0ZXBCdXR0b24gPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZChcIm5leHRCdXR0b25cIik7XG5jb25zdCBwcmV2aW91c1N0ZXBCdXR0b24gPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZChcInByZXZCdXR0b25cIik7XG5jb25zdCBjYW5jZWxCdXR0b24gPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZChcImNhbmNlbFwiKTtcbmNvbnN0IHdpemFyZFdpeiA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKFwid2l6XCIpO1xuY29uc3Qgd2l6YXJkRmluYWxpemUgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZChcIndpei1maW5hbGl6ZVwiKTtcblxuY29uc3QgZGVzZWxlY3RBbGwgPSAod2l6YXJkKSA9PiB7XG4gICAgQXJyYXkuZnJvbSh3aXphcmQuY2hpbGRyZW4pLmZvckVhY2goKHN0ZXApID0-IHtcbiAgICAgICAgc3RlcC5zZWxlY3RlZCA9IGZhbHNlO1xuICAgIH0pO1xufVxuXG5jb25zdCBnZXRTdGVwID0gKHdpemFyZCwgaWR4KSA9PiB7XG4gICAgcmV0dXJuIEFycmF5LmZyb20od2l6YXJkLmNoaWxkcmVuKVtpZHhdO1xufVxuXG5jb25zdCBzZXROZXh0U3RlcCA9ICh3aXphcmQsIGN1cnJlbnRTdGVwSW5kZXgsIG5leHRTdGVwSW5kZXgpID0-IHtcbiAgICBjb25zdCBuZXh0U3RlcCA9IGdldFN0ZXAod2l6YXJkLCBuZXh0U3RlcEluZGV4KTtcbiAgICBjb25zdCBjdXJyZW50U3RlcCA9IGdldFN0ZXAod2l6YXJkLCBjdXJyZW50U3RlcEluZGV4KTtcblxuICAgIG5leHRTdGVwLnNlbGVjdGVkID0gdHJ1ZTtcbiAgICBjdXJyZW50U3RlcC5kaXNhYmxlZCA9IGZhbHNlO1xufVxuXG5jb25zdCBzZXRQcmV2aW91c1N0ZXAgPSAod2l6YXJkLCBjdXJyZW50U3RlcEluZGV4LCBwcmV2aW91c1N0ZXBJbmRleCkgPT4ge1xuICAgIGNvbnN0IHByZXZpb3VzU3RlcCA9IGdldFN0ZXAod2l6YXJkLCBwcmV2aW91c1N0ZXBJbmRleCk7XG4gICAgY29uc3QgY3VycmVudFN0ZXAgPSBnZXRTdGVwKHdpemFyZCwgY3VycmVudFN0ZXBJbmRleCk7XG5cbiAgICBwcmV2aW91c1N0ZXAuc2VsZWN0ZWQgPSB0cnVlO1xuICAgIGN1cnJlbnRTdGVwLmRpc2FibGVkID0gZmFsc2U7XG59XG5cbmNvbnN0IHNldEJ1dHRvblZpc2liaWxpdHkgPSAoaW5kZXgsIHRvdGFsSXRlbXMpID0-IHtcbiAgICBjb25zdCBuZXh0QnV0dG9uID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ25leHRCdXR0b24nKTtcbiAgICBjb25zdCBwcmV2QnV0dG9uID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ3ByZXZCdXR0b24nKTtcblxuICAgIGlmIChpbmRleCA9PT0gMCkge1xuICAgICAgICB3aXphcmRGaW5hbGl6ZS5zdHlsZS5kaXNwbGF5ID0gJ25vbmUnO1xuICAgICAgICBwcmV2QnV0dG9uLnN0eWxlLmRpc3BsYXkgPSAnbm9uZSc7XG4gICAgICAgIG5leHRCdXR0b24uc3R5bGUuZGlzcGxheSA9ICdibG9jayc7XG4gICAgfSBlbHNlIGlmIChpbmRleCA9PT0gdG90YWxJdGVtcyAtIDEpIHtcbiAgICAgICAgcHJldkJ1dHRvbi5zdHlsZS5kaXNwbGF5ID0gJ2Jsb2NrJztcbiAgICAgICAgd2l6YXJkRmluYWxpemUuc3R5bGUuZGlzcGxheSA9ICdibG9jayc7XG4gICAgICAgIG5leHRCdXR0b24uc3R5bGUuZGlzcGxheSA9ICdub25lJztcbiAgICB9IGVsc2Uge1xuICAgICAgICBwcmV2QnV0dG9uLnN0eWxlLmRpc3BsYXkgPSAnYmxvY2snO1xuICAgICAgICBuZXh0QnV0dG9uLnN0eWxlLmRpc3BsYXkgPSAnYmxvY2snO1xuICAgIH1cbn1cblxuYnRuT3BlbmRpYWxvZy5hZGRFdmVudExpc3RlbmVyKFwiY2xpY2tcIiwgKCkgPT4ge1xuICAgIGRpYWxvZy5zaG93KCk7XG4gICAgY29uc3QgaW5kZXggPSB3aXphcmRXaXouZ2V0U2VsZWN0ZWRTdGVwSW5kZXgoKTtcbiAgICBzZXRCdXR0b25WaXNpYmlsaXR5KGluZGV4LCB3aXphcmRXaXouY2hpbGRyZW4ubGVuZ3RoKTtcbn0pO1xuXG53aXphcmRXaXouYWRkRXZlbnRMaXN0ZW5lcihcInVpNS1zdGVwLWNoYW5nZVwiLCAoZXZlbnQpID0-IHtcbiAgICBjb25zdCBpbmRleCA9IHdpemFyZFdpei5nZXRTZWxlY3RlZFN0ZXBJbmRleCgpO1xuICAgIHNldEJ1dHRvblZpc2liaWxpdHkoaW5kZXgsIHdpemFyZFdpei5jaGlsZHJlbi5sZW5ndGgpXG59KTtcblxubmV4dFN0ZXBCdXR0b24uYWRkRXZlbnRMaXN0ZW5lcihcImNsaWNrXCIsICgpID0-IHtcbiAgICBjb25zdCBpbmRleCA9IHdpemFyZFdpei5nZXRTZWxlY3RlZFN0ZXBJbmRleCgpO1xuICAgIHNldE5leHRTdGVwKHdpemFyZFdpeiwgaW5kZXgsIGluZGV4ICsgMSk7XG4gICAgc2V0QnV0dG9uVmlzaWJpbGl0eShpbmRleCArIDEsIHdpemFyZFdpei5jaGlsZHJlbi5sZW5ndGgpXG59KTtcblxucHJldmlvdXNTdGVwQnV0dG9uLmFkZEV2ZW50TGlzdGVuZXIoXCJjbGlja1wiLCAoKSA9PiB7XG4gICAgY29uc3QgaW5kZXggPSB3aXphcmRXaXouZ2V0U2VsZWN0ZWRTdGVwSW5kZXgoKTtcbiAgICBkZXNlbGVjdEFsbCh3aXphcmRXaXopO1xuICAgIHNldFByZXZpb3VzU3RlcCh3aXphcmRXaXosIGluZGV4LCBpbmRleCAtIDEpO1xuICAgIHNldEJ1dHRvblZpc2liaWxpdHkoaW5kZXggLSAxLCB3aXphcmRXaXouY2hpbGRyZW4ubGVuZ3RoKVxufSk7XG5cbmNhbmNlbEJ1dHRvbi5hZGRFdmVudExpc3RlbmVyKFwiY2xpY2tcIiwgKCkgPT4ge1xuICAgIGRpYWxvZy5jbG9zZSgpO1xufSk7XG5cbndpemFyZEZpbmFsaXplLmFkZEV2ZW50TGlzdGVuZXIoXCJjbGlja1wiLCAoKSA9PiB7XG4gICAgYWxlcnQoXCJGaW5hbGl6ZVwiKTtcbiAgICBkaWFsb2cuY2xvc2UoKTtcbn0pOyJ9fQ)
2. open JAWS
3. click next step button to step 3
4. Use the keyboard shortcut 'Insert+F3' and you can select 'Divisions list'
5. Check the text and you will see repetitive wizard step names are provided

### Log Output, Stack Trace or Screenshots

<img width="1634" alt="image" src="https://github.com/user-attachments/assets/e04ff39d-1bb2-4ac7-bb4f-c34fff6054d0">

### Priority

Medium

### UI5 Web Components Version

1.24.x

### Browser

Chrome

### Organization

SAP SuccessFactors

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by dimovpetar** [comment]
Hello @ui5-webcomponents-topic-rl,

Please check out this issue with divisions list.

Best regards,
Petar

**Comment by elenastoyanovaa** [comment]
Hello @GongRichard ,

I have analysed the reported issue and my conclusion as the team accessibility expert is that this is not a real accessibility concern, but I will deep dive in the case in order to describe my thoughts on the matter.
The first point is that there is no issue or repetitive announcement with the screen reader. The title is each step is announced only once. The second point is that I also ran an accessibility automation tool (both AXE and Access Assistant) and no issue is found there as well.
The last point is that I do not see the real issue behind the fact that in the division list shown in jaws, there are multiple occurrences of the same titled division. A 'Division' in HTML represents all the `div` elements on a page, they could be hundreds of them and there is no restriction for them the have different html content. Those division in most cases do not have any semantic relationship between them and I do not see any logic to have restrictions for uniqueness.

If you still think that there is a real accessibility concern please describe it following the template in the Testing Accessibility section in our accessibility documentation
https://sap.github.io/ui5-webcomponents/nightly/docs/advanced/accessibility/#testing-accessibility
by providing Issue description and a Reference to the suspected violated accessibility requirement (e.g. Web Content Accessibility Guidelines WCAG 2.2, BITV 2.0, EN 301 549)

Kind Regards,
Elena
