### ISSUE TITLE
[ui5-list]: list items content overflows additional-text.

### ISSUE THREAD

**Issue by ivoplashkov** [SAP/ui5-webcomponents#9675]
### Bug Description

When we have a list-item with a wrapping-type="Normal", the content of the list-item overflows the additional-text.

### Affected Component

ui5-list

### Expected Behaviour

The list item's text should not overflow the additional-text.

### Isolated Example

https://stackblitz.com/edit/js-wbpcq5?file=index.html

### Steps to Reproduce

1. Open the isolated example and resize the window so that there isn’t enough space for the text

<img width="271" alt="Screenshot 2024-08-12 at 14 16 07" src="https://github.com/user-attachments/assets/06dceffa-3321-4017-8675-ceb5e397e488">

### Priority

Low

### UI5 Web Components Version

2.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by plamenivanov91** [comment]
Hello @ivoplashkov,

As part of the [WrappingType](https://sap.github.io/ui5-webcomponents/components/enums/WrappingType/) documentation, it's stated that if you want the text to truncate, you should apply "None" (default) as WrappingType value.

WrappingType "Normal" makes sure to wrap the words (render them one above other when there is not enough space). It is also strictly stated that "Normal" will not brake down words.

Unfortunately there is no third option in between where the words will wrap but also truncate.

In my opinion the behavior is correct. If you are unhappy with that statement, may be you can give as an idea what is expected to happen and we will make sure to discuss it with designers and PO.

Regards,
Plamen Ivanov
