### ISSUE TITLE
[List]: Trailing empty space if `growing="Scroll"`

### ISSUE THREAD

**Issue by ej612** [SAP/ui5-webcomponents#9688]
### Describe the bug

Hi there!

We have a list of standard list items, and we've set `growing="Scroll"`. This adds empty space to the bottom of the list (shown in red here):

![image](https://github.com/user-attachments/assets/7d58420c-af3a-4baf-805d-6784d76bfa77)

UX doesn't like that empty space.

Thanks a lot in advance!

Best regards

### Isolated Example

https://stackblitz.com/edit/github-wdbqbe?file=src%2FApp.tsx

### UI5 Web Components for React Version

~1.29.0

### UI5 Web Components Version

~1.24.0

### Browser

Chrome

**Comment by unazko** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

The issue is reproducible as @ej612 described via his sample:
https://stackblitz.com/edit/github-wdbqbe?file=src%2FApp.tsx
Couldn't observe similar behavior into the openui5 project.

Best regards,
Boyan

**Comment by plamenivanov91** [comment]
Hello @ej612 ,

This small empty space is required to determine if it's time to call/load new items. It is not present on growing="None".

If we remove it, the logic for loading additional items on growing="Scroll" becomes inconsistent.

I'd suggest to use growing="None" OR use growing="Scroll" but change it to "None" once all of your items are ready and loaded.

Regards,
Plamen Ivanov
