### ISSUE TITLE
Add Ui5CustomEvent for UploadCollectionItem on rename cancel click

### ISSUE THREAD

**Issue by tkeiner** [SAP/ui5-webcomponents#9704]
### Is your feature request related to a problem?

The UploadCollectionItem has a custom event that is fired when the attachment is renamed. However, there is no event for when the rename is cancelled. Currently I have to access the item via the querySelector and add an EventListener. This approach works but is not ideal.

### Describe the solution you'd like

It would be great if the web components could also provide a custom event in case the rename is cancelled.

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by tkeiner** [comment]
Hi @dimovpetar,
There is a use case for this, which is to extend the edit functionality of the upload collection item. In our case, it was to add an input field to allow users to add additional information, when the rename is active.

I understand that this is an edge case, and I understand that this approach may not align with the web component strategy. Also, our use case could be implemented by querying for the required button and adding a listener.
Having a dedicated event for the state of the rename (rename started, rename canceled, renamed) would have been nice to improve our code quality, which is the reason I opened the feature request.

Regards, Tobias

**Comment by dimovpetar** [comment]
Hello @tkeiner ,

Please edit this Stackblitz https://stackblitz.com/edit/js-vsrpnb?file=index.js,index.html to show your example. We will then evaluate your request.
Adding event listener to elements in the shadow root is not supported and most likely won't work in the future.

Best regards,
Petar

**Comment by tkeiner** [comment]
Would it be fine if I create a Stackblitz with ui5 web components for React? I am more comfortable with React.

**Comment by dimovpetar** [comment]
> Would it be fine if I create a Stackblitz with ui5 web components for React? I am more comfortable with React.

Sure, it's fine :)
