### ISSUE TITLE
[ui5-color-palette-popover] opener should be set syncronously to the internal RPO

### ISSUE THREAD

**Issue by MapTo0** [SAP/ui5-webcomponents#9708]
### Bug Description

Hello colleagues,

While using the color palette popover the two properties `open` and `opener` are forwarded to the internal RPO.
Base on the template the `open` is set before the `opener`.
https://github.com/SAP/ui5-webcomponents/blob/main/packages/main/src/ColorPalettePopover.hbs#L5-L6

in the context of RPO, the `open` property is set synchronously, which means that the opener is not yet set while `open` is called and a warning is logged in the console:

`Valid opener id is required. It must be defined before opening the popover.`  

My proposal is to swap `open` and `opener` order in the ColorPalettePopover's template.

Reproducible example: [here](https://sap.github.io/ui5-webcomponents/play/#eyJpbmRleC5odG1sIjp7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuPCFET0NUWVBFIGh0bWw-XG48aHRtbCBsYW5nPVwiZW5cIj5cblxuXG5cbjxoZWFkPlxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG4gICAgPC9zdHlsZT5cblxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG4gICAgPC9zdHlsZT5cblxuICAgIDxtZXRhIGNoYXJzZXQ9XCJVVEYtOFwiPlxuICAgIDxtZXRhIG5hbWU9XCJ2aWV3cG9ydFwiIGNvbnRlbnQ9XCJ3aWR0aD1kZXZpY2Utd2lkdGgsIGluaXRpYWwtc2NhbGU9MS4wXCI-XG4gICAgPHRpdGxlPlNhbXBsZTwvdGl0bGU-XG48L2hlYWQ-XG5cbjxib2R5IHN0eWxlPVwiYmFja2dyb3VuZC1jb2xvcjogdmFyKC0tc2FwQmFja2dyb3VuZENvbG9yKTsgaGVpZ2h0OiAzMDBweFwiPlxuICAgIDwhLS0gcGxheWdyb3VuZC1mb2xkLWVuZCAtLT5cblxuXG4gICAgPHVpNS1idXR0b24gaWQ9XCJjb2xvclBhbGV0dGVCdG5cIj5PcGVuIENvbG9yUGFsZXR0ZVBvcG92ZXI8L3VpNS1idXR0b24-XG4gIFxuICAgIDx1aTUtY29sb3ItcGFsZXR0ZS1wb3BvdmVyIGlkPVwiY29sb3JQYWxldHRlUG9wb3ZlclwiPlxuICAgICAgICA8dWk1LWNvbG9yLXBhbGV0dGUtaXRlbSB2YWx1ZT1cImxpZ2h0c2FsbW9uXCI-PC91aTUtY29sb3ItcGFsZXR0ZS1pdGVtPlxuICAgICAgICA8dWk1LWNvbG9yLXBhbGV0dGUtaXRlbSB2YWx1ZT1cImxpZ2h0cGlua1wiPjwvdWk1LWNvbG9yLXBhbGV0dGUtaXRlbT5cbiAgICAgICAgPHVpNS1jb2xvci1wYWxldHRlLWl0ZW0gdmFsdWU9XCJyZ2IoMjE2LDEyNCwxNzIpXCI-PC91aTUtY29sb3ItcGFsZXR0ZS1pdGVtPlxuICAgICAgICA8dWk1LWNvbG9yLXBhbGV0dGUtaXRlbSB2YWx1ZT1cIiM2YzY2NmRcIj48L3VpNS1jb2xvci1wYWxldHRlLWl0ZW0-XG4gICAgICAgIDx1aTUtY29sb3ItcGFsZXR0ZS1pdGVtIHZhbHVlPVwicmdiKDU1LDgxLDk1KVwiPjwvdWk1LWNvbG9yLXBhbGV0dGUtaXRlbT5cbiAgICAgICAgPHVpNS1jb2xvci1wYWxldHRlLWl0ZW0gdmFsdWU9XCIjMDA3MmJiXCI-PC91aTUtY29sb3ItcGFsZXR0ZS1pdGVtPlxuICAgICAgICA8dWk1LWNvbG9yLXBhbGV0dGUtaXRlbSB2YWx1ZT1cInBvd2RlcmJsdWVcIj48L3VpNS1jb2xvci1wYWxldHRlLWl0ZW0-XG4gICAgICAgIDx1aTUtY29sb3ItcGFsZXR0ZS1pdGVtIHZhbHVlPVwicmdiKDE0MywyMDEsNTgpXCI-PC91aTUtY29sb3ItcGFsZXR0ZS1pdGVtPlxuICAgICAgICA8dWk1LWNvbG9yLXBhbGV0dGUtaXRlbSB2YWx1ZT1cInJnYigxOTUsMTcyLDIwNilcIj48L3VpNS1jb2xvci1wYWxldHRlLWl0ZW0-XG4gICAgICAgIDx1aTUtY29sb3ItcGFsZXR0ZS1pdGVtIHZhbHVlPVwib3JhbmdlXCI-PC91aTUtY29sb3ItcGFsZXR0ZS1pdGVtPlxuICAgIDwvdWk1LWNvbG9yLXBhbGV0dGUtcG9wb3Zlcj5cbiAgICA8IS0tIHBsYXlncm91bmQtZm9sZCAtLT5cbiAgICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCJtYWluLmpzXCI-PC9zY3JpcHQ-XG48L2JvZHk-XG5cbjwvaHRtbD5cbjwhLS0gcGxheWdyb3VuZC1mb2xkLWVuZCAtLT5cbiJ9LCJtYWluLmpzIjp7Im5hbWUiOiJtYWluLmpzIiwiY29udGVudCI6Ii8qIHBsYXlncm91bmQtaGlkZSAqL1xuaW1wb3J0IFwiLi9wbGF5Z3JvdW5kLXN1cHBvcnQuanNcIjtcbi8qIHBsYXlncm91bmQtaGlkZS1lbmQgKi9cbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L0NvbG9yUGFsZXR0ZVBvcG92ZXIuanNcIjtcbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L0NvbG9yUGFsZXR0ZUl0ZW0uanNcIjtcbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L0J1dHRvbi5qc1wiO1xuXG5jb2xvclBhbGV0dGVCdG4uYWRkRXZlbnRMaXN0ZW5lcihcImNsaWNrXCIsICgpID0-IHtcbiAgXHRjb2xvclBhbGV0dGVQb3BvdmVyLm9wZW5lciA9IGNvbG9yUGFsZXR0ZUJ0blxuXHRjb2xvclBhbGV0dGVQb3BvdmVyLm9wZW4gPSAhY29sb3JQYWxldHRlUG9wb3Zlci5vcGVuO1xufSk7In19)

### Affected Component

ui5-color-palette-popover

### Isolated Example

https://sap.github.io/ui5-webcomponents/play/#eyJpbmRleC5odG1sIjp7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuPCFET0NUWVBFIGh0bWw-XG48aHRtbCBsYW5nPVwiZW5cIj5cblxuXG5cbjxoZWFkPlxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG4gICAgPC9zdHlsZT5cblxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG4gICAgPC9zdHlsZT5cblxuICAgIDxtZXRhIGNoYXJzZXQ9XCJVVEYtOFwiPlxuICAgIDxtZXRhIG5hbWU9XCJ2aWV3cG9ydFwiIGNvbnRlbnQ9XCJ3aWR0aD1kZXZpY2Utd2lkdGgsIGluaXRpYWwtc2NhbGU9MS4wXCI-XG4gICAgPHRpdGxlPlNhbXBsZTwvdGl0bGU-XG48L2hlYWQ-XG5cbjxib2R5IHN0eWxlPVwiYmFja2dyb3VuZC1jb2xvcjogdmFyKC0tc2FwQmFja2dyb3VuZENvbG9yKTsgaGVpZ2h0OiAzMDBweFwiPlxuICAgIDwhLS0gcGxheWdyb3VuZC1mb2xkLWVuZCAtLT5cblxuXG4gICAgPHVpNS1idXR0b24gaWQ9XCJjb2xvclBhbGV0dGVCdG5cIj5PcGVuIENvbG9yUGFsZXR0ZVBvcG92ZXI8L3VpNS1idXR0b24-XG4gIFxuICAgIDx1aTUtY29sb3ItcGFsZXR0ZS1wb3BvdmVyIGlkPVwiY29sb3JQYWxldHRlUG9wb3ZlclwiPlxuICAgICAgICA8dWk1LWNvbG9yLXBhbGV0dGUtaXRlbSB2YWx1ZT1cImxpZ2h0c2FsbW9uXCI-PC91aTUtY29sb3ItcGFsZXR0ZS1pdGVtPlxuICAgICAgICA8dWk1LWNvbG9yLXBhbGV0dGUtaXRlbSB2YWx1ZT1cImxpZ2h0cGlua1wiPjwvdWk1LWNvbG9yLXBhbGV0dGUtaXRlbT5cbiAgICAgICAgPHVpNS1jb2xvci1wYWxldHRlLWl0ZW0gdmFsdWU9XCJyZ2IoMjE2LDEyNCwxNzIpXCI-PC91aTUtY29sb3ItcGFsZXR0ZS1pdGVtPlxuICAgICAgICA8dWk1LWNvbG9yLXBhbGV0dGUtaXRlbSB2YWx1ZT1cIiM2YzY2NmRcIj48L3VpNS1jb2xvci1wYWxldHRlLWl0ZW0-XG4gICAgICAgIDx1aTUtY29sb3ItcGFsZXR0ZS1pdGVtIHZhbHVlPVwicmdiKDU1LDgxLDk1KVwiPjwvdWk1LWNvbG9yLXBhbGV0dGUtaXRlbT5cbiAgICAgICAgPHVpNS1jb2xvci1wYWxldHRlLWl0ZW0gdmFsdWU9XCIjMDA3MmJiXCI-PC91aTUtY29sb3ItcGFsZXR0ZS1pdGVtPlxuICAgICAgICA8dWk1LWNvbG9yLXBhbGV0dGUtaXRlbSB2YWx1ZT1cInBvd2RlcmJsdWVcIj48L3VpNS1jb2xvci1wYWxldHRlLWl0ZW0-XG4gICAgICAgIDx1aTUtY29sb3ItcGFsZXR0ZS1pdGVtIHZhbHVlPVwicmdiKDE0MywyMDEsNTgpXCI-PC91aTUtY29sb3ItcGFsZXR0ZS1pdGVtPlxuICAgICAgICA8dWk1LWNvbG9yLXBhbGV0dGUtaXRlbSB2YWx1ZT1cInJnYigxOTUsMTcyLDIwNilcIj48L3VpNS1jb2xvci1wYWxldHRlLWl0ZW0-XG4gICAgICAgIDx1aTUtY29sb3ItcGFsZXR0ZS1pdGVtIHZhbHVlPVwib3JhbmdlXCI-PC91aTUtY29sb3ItcGFsZXR0ZS1pdGVtPlxuICAgIDwvdWk1LWNvbG9yLXBhbGV0dGUtcG9wb3Zlcj5cbiAgICA8IS0tIHBsYXlncm91bmQtZm9sZCAtLT5cbiAgICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCJtYWluLmpzXCI-PC9zY3JpcHQ-XG48L2JvZHk-XG5cbjwvaHRtbD5cbjwhLS0gcGxheWdyb3VuZC1mb2xkLWVuZCAtLT5cbiJ9LCJtYWluLmpzIjp7Im5hbWUiOiJtYWluLmpzIiwiY29udGVudCI6Ii8qIHBsYXlncm91bmQtaGlkZSAqL1xuaW1wb3J0IFwiLi9wbGF5Z3JvdW5kLXN1cHBvcnQuanNcIjtcbi8qIHBsYXlncm91bmQtaGlkZS1lbmQgKi9cbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L0NvbG9yUGFsZXR0ZVBvcG92ZXIuanNcIjtcbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L0NvbG9yUGFsZXR0ZUl0ZW0uanNcIjtcbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L0J1dHRvbi5qc1wiO1xuXG5jb2xvclBhbGV0dGVCdG4uYWRkRXZlbnRMaXN0ZW5lcihcImNsaWNrXCIsICgpID0-IHtcbiAgXHRjb2xvclBhbGV0dGVQb3BvdmVyLm9wZW5lciA9IGNvbG9yUGFsZXR0ZUJ0blxuXHRjb2xvclBhbGV0dGVQb3BvdmVyLm9wZW4gPSAhY29sb3JQYWxldHRlUG9wb3Zlci5vcGVuO1xufSk7In19

### Steps to Reproduce

1. click on the opener button
2. Check console logs

### Priority

None

### UI5 Web Components Version

2.1.1

### Browser

Chrome, Edge, Firefox, Safari

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by yanaminkova** [comment]
Hello @SAP/ui5-webcomponents-topic-b ,

Could you please have a look at this issue regarding the `ui5-color-palette-popover`?

Thanks and Best regards,
Yana
