### ISSUE TITLE
[Feature Request]: allow setting the overlay programmatically for `BusyIndicator`

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#9723]
### Feature Request Description

In UI5WCR we're implementing some complex components like the `AnalyticalTable` and charts, that are now leveraging the `BusyIndicator`. Since these components do a lot of layouting themselves, rendering the BusyIndicator in the normal flow of the document proves problematic and would need a lot of tweaking to achieve the desired behavior. The easiest way to avoid this, is positioning the indicator above the elements, so outside of the normal flow. In this case, we don't need to set `children`, but still want the focus behavior and overlay color of the indicator. Currently we're adding a dummy element as child, but we'd like to avoid that.

https://stackblitz.com/edit/github-s8qe12?file=index.html,main.js,package.json

I'll add an example of our `AnalyticalTable` once this [PR](https://github.com/SAP/ui5-webcomponents-react/pull/6244) is merged and released.

Edit: Current implementation of the BusyIndicator in our AnalyticalTable: https://stackblitz.com/edit/ui5wcr-at-ar9ih4?file=src%2FApp.tsx

styles:
```css
  height: 100%;
  inset: 0px;
  position: absolute;
  z-index: 1;
```

### Proposed Solution

Add a way to enable the overlay color, even if there are no `children` rendered inside the component.

### Organization

UI5WCR

### Priority

None

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by yanaminkova** [comment]
Hello @SAP/ui5-webcomponents-topic-rd,

Could you please review this feature request regarding the `ui5-busy-indicator` component?

Thanks and Best regards,
Yana

**Comment by dimovpetar** [comment]
Hello @Lukas742 ,

Some components had exactly the same structure that you request. However, as it appeared that keyboard handling is completely wrong with such structure, we decided to refactor those components to use the `ui5-busy-indicator` as it is designed to be used. For instance, such changes are https://github.com/SAP/ui5-webcomponents/commit/fa37d92f30931a1ac38d6efadf4439ba3d3d555e and https://github.com/SAP/ui5-webcomponents/commit/b32adf50e6398f8677edcbcd9f7d80dafb55ae43.

I have edited your sample https://stackblitz.com/edit/github-s8qe12-rpezhf?file=index.html,main.js,package.json. Navigate both directions - using `Tab` and `Tab + Shift` keys, You will notice how the focusable elements inside your element are completely accessible via keyboard. Preventing it would require your own keyboard handling, which is almost all of the functionality that the BusyIndicator provides. 
Therefore, if you need only the visual part, without functionality, we can think for a solution in this direction. Ofcourse, I would recommend to use intended structure. What would you say?

Best regards,
Petar

**Comment by Lukas742** [comment]
Hi @dimovpetar 

Thanks for your reply!
Yes, visuals are our top priority. It would be ideal if accessibility features (like `role` and aria attributes) were included, but if necessary, we can handle those on our end.

I also tried the [Common CSS BusyIndicator class](https://sap.github.io/fundamental-styles/?path=/docs/common-css-busy-indicator--docs), but unfortunately, it lacks a backdrop ([example](https://stackblitz.com/edit/github-s8qe12-er3ggf?file=index.html,main.js,package.json)) as well.

Our main reason for using your BusyIndicator implementation is to maintain visual consistency between your components and ours, while avoiding reliance on internal CSS variables (e.g., `--_ui5_busy_indicator_block_layer`).

**Comment by dimovpetar** [comment]
****Hello,

Block layer styling requires just a background color and opacity - [here is how it can be achieved.](https://sap.github.io/ui5-webcomponents/play/#eyJpbmRleC5odG1sIjp7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuPCFET0NUWVBFIGh0bWw-XG48aHRtbCBsYW5nPVwiZW5cIj5cblxuXG5cblxuPGhlYWQ-XG4gICAgXG4gICAgPHN0eWxlPlxuICAgICAgKjpub3QoOmRlZmluZWQpIHtcbiAgICAgICAgZGlzcGxheTogbm9uZTtcbiAgICAgIH1cblxuICAgIGh0bWwge1xuICAgICAgZm9yY2VkLWNvbG9yLWFkanVzdDogbm9uZTtcbiAgICB9XG4gICAgPC9zdHlsZT5cblxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG5cbiAgICBodG1sIHtcbiAgICAgIGZvcmNlZC1jb2xvci1hZGp1c3Q6IG5vbmU7XG4gICAgfVxuICAgIDwvc3R5bGU-XG5cbiAgICBcbiAgICA8c3R5bGU-XG4gICAgICAqOm5vdCg6ZGVmaW5lZCkge1xuICAgICAgICBkaXNwbGF5OiBub25lO1xuICAgICAgfVxuXG4gICAgaHRtbCB7XG4gICAgICBmb3JjZWQtY29sb3ItYWRqdXN0OiBub25lO1xuICAgIH1cbiAgICA8L3N0eWxlPlxuXG4gICAgPG1ldGEgY2hhcnNldD1cIlVURi04XCI-XG4gICAgPG1ldGEgbmFtZT1cInZpZXdwb3J0XCIgY29udGVudD1cIndpZHRoPWRldmljZS13aWR0aCwgaW5pdGlhbC1zY2FsZT0xLjBcIj5cbiAgICA8dGl0bGU-U2FtcGxlPC90aXRsZT5cbjwvaGVhZD5cblxuPGJvZHkgc3R5bGU9XCJiYWNrZ3JvdW5kLWNvbG9yOiB2YXIoLS1zYXBCYWNrZ3JvdW5kQ29sb3IpXCI-XG4gICAgPCEtLSBwbGF5Z3JvdW5kLWZvbGQtZW5kIC0tPlxuXG4gICAgPHVpNS1idXN5LWluZGljYXRvciB0ZXh0PVwiTG9hZGluZyBkYXRhIGZyb20gYmFja2VuZCBzZXJ2ZXIuLlwiIGFjdGl2ZT5cbiAgICAgICAgPGRpdiBzdHlsZT1cImhlaWdodDogMjAwcHg7IHdpZHRoOiAyMDBweDtcIj48L2Rpdj5cbiAgICA8L3VpNS1idXN5LWluZGljYXRvcj5cbiAgICA8ZGl2IHN0eWxlPVwiYmFja2dyb3VuZDogdmFyKC0tc2FwQmxvY2tMYXllcl9CYWNrZ3JvdW5kKTsgb3BhY2l0eTogMC4yO1wiPlxuICAgICAgICA8ZGl2IHN0eWxlPVwiaGVpZ2h0OiAyMDBweDsgd2lkdGg6IDIwMHB4O1wiPlwiPC9kaXY-XG4gICAgPC9kaXY-XG5cbiAgICA8IS0tIHBsYXlncm91bmQtZm9sZCAtLT5cbiAgICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCJtYWluLmpzXCI-PC9zY3JpcHQ-XG48L2JvZHk-XG5cbjwvaHRtbD5cbjwhLS0gcGxheWdyb3VuZC1mb2xkLWVuZCAtLT5cbiJ9LCJtYWluLmpzIjp7Im5hbWUiOiJtYWluLmpzIiwiY29udGVudCI6Ii8qIHBsYXlncm91bmQtaGlkZSAqL1xuaW1wb3J0IFwiLi9wbGF5Z3JvdW5kLXN1cHBvcnQuanNcIjtcbi8qIHBsYXlncm91bmQtaGlkZS1lbmQgKi9cbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L0J1c3lJbmRpY2F0b3IuanNcIjtcbiJ9fQ). Very soon, there will also be a CSS parameter for opacity, provided by the theming library, so you won't have to care for the theme either.
All you would have to use would be `sapBlockLayer_Background` and `sapBlockLayer_Opacity`. Please give this a try. 

These are my arguments not to do this in the `ui5-busy-indicator`:

1. Comparing `ui5-busy-indicator` to provide styles only, vs using CSS variables, the latter wins
2. Comparing `ui5-busy-indicator` to provide styles and API to show block layer, without proper keyboard support, opens a backdoor for improper usage and application bugs

I am also open for a meeting to check what would cost to use `ui5-busy-indicator` in the AnalyticalTable as intended.

Best regards,
Petar

**Comment by Lukas742** [comment]
Hi @dimovpetar, implementing the BusyIndicator with CSS works for us. We’ll keep our current implementation until the opacity is available as a public CSS variable, so we won’t need to manage HC deltas ourselves.

Thanks a lot for your support!

From my side, this issue can be closed.
