### ISSUE TITLE
[SF][IllustratedMessage]: IllustratedMessage Icon not visible when rendered in Panel component

### ISSUE THREAD

**Issue by ksblklu02** [SAP/ui5-webcomponents#9724]
### Bug Description

IllustratedMessage Icon not visible when rendered in Panel component

### Affected Component

ui5-illustrated-message

### Expected Behaviour

Responsive icon should be visible when IllustratedMessage rendered

### Isolated Example

https://stackblitz.com/edit/github-pjgups?file=src%2FApp.tsx

### Steps to Reproduce

1. Go to https://stackblitz.com/edit/github-pjgups?file=src%2FApp.tsx 
2. See the message icon is not visible under the panel
<img width="843" alt="image" src="https://github.com/user-attachments/assets/6772a47e-b6e3-4b5b-a4a8-23c22bb07c9d">

### Priority

High

### UI5 Web Components Version

1.24.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by nnaydenow** [comment]
It is also reproducible without ui5-panel (https://stackblitz.com/edit/github-pjgups-bzfluh?file=src%2FApp.tsx) simply resize vertically the container where the illustration is placed.
