### ISSUE TITLE
ui5-list: "More" button text is not correctly positioned

### ISSUE THREAD

**Issue by LidiyaGeorgieva** [SAP/ui5-webcomponents#9725]
### Bug Description

![image](https://github.com/user-attachments/assets/938448f3-e709-4ce9-bc0c-47d80fe49353)

### Steps to Reproduce

1. open https://sap.github.io/ui5-webcomponents/nightly/components/List/#growing-on-button-press
2. scroll to see the "More" button

### Priority

Medium

### UI5 Web Components Version

main

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by yanaminkova** [comment]
Hello @SAP/ui5-webcomponents-topic-p  ,

Could you please have a look at this issue regarding the position of  "More" button inside the `ui5-list` component?

Could be reproduced in the following [sample.](https://sap.github.io/ui5-webcomponents/nightly/play/#eyJpbmRleC5odG1sIjp7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuPCFET0NUWVBFIGh0bWw-XG48aHRtbCBsYW5nPVwiZW5cIj5cblxuXG48aGVhZD5cbiAgICBcbiAgICA8c3R5bGU-XG4gICAgICAqOm5vdCg6ZGVmaW5lZCkge1xuICAgICAgICBkaXNwbGF5OiBub25lO1xuICAgICAgfVxuICAgIDwvc3R5bGU-XG5cbiAgICA8bWV0YSBjaGFyc2V0PVwiVVRGLThcIj5cbiAgICA8bWV0YSBuYW1lPVwidmlld3BvcnRcIiBjb250ZW50PVwid2lkdGg9ZGV2aWNlLXdpZHRoLCBpbml0aWFsLXNjYWxlPTEuMFwiPlxuICAgIDx0aXRsZT5TYW1wbGU8L3RpdGxlPlxuPC9oZWFkPlxuXG48Ym9keSBzdHlsZT1cImJhY2tncm91bmQtY29sb3I6IHZhcigtLXNhcEJhY2tncm91bmRDb2xvcilcIj5cbiAgICA8IS0tIHBsYXlncm91bmQtZm9sZC1lbmQgLS0-XG5cbiAgICA8dWk1LWxpc3QgaWQ9XCJncm93aW5nTGlzdFwiIHN0eWxlPVwiaGVpZ2h0OiAzMDBweFwiIGdyb3dpbmc9XCJCdXR0b25cIiBsb2FkaW5nLWRlbGF5PVwiMFwiPlxuICAgICAgICA8dWk1LWxpIGljb249XCJudXRyaXRpb24tYWN0aXZpdHlcIiBkZXNjcmlwdGlvbj1cIlRyb3BpY2FsIHBsYW50IHdpdGggYW4gZWRpYmxlIGZydWl0XCIgYWRkaXRpb25hbC10ZXh0PVwiSW4tc3RvY2tcIlxuICAgICAgICAgICAgYWRkaXRpb25hbC10ZXh0LXN0YXRlPVwiUG9zaXRpdmVcIj5QaW5lYXBwbGU8L3VpNS1saT5cbiAgICAgICAgPHVpNS1saSBpY29uPVwibnV0cml0aW9uLWFjdGl2aXR5XCIgZGVzY3JpcHRpb249XCJPY2N1cnMgYmV0d2VlbiByZWQgYW5kIHllbGxvd1wiIGFkZGl0aW9uYWwtdGV4dD1cIkV4cGlyZXNcIlxuICAgICAgICAgICAgYWRkaXRpb25hbC10ZXh0LXN0YXRlPVwiQ3JpdGljYWxcIj5PcmFuZ2U8L3VpNS1saT5cbiAgICAgICAgPHVpNS1saSBpY29uPVwibnV0cml0aW9uLWFjdGl2aXR5XCIgZGVzY3JpcHRpb249XCJUaGUgeWVsbG93IGxlbmd0aHkgZnJ1aXRcIiBhZGRpdGlvbmFsLXRleHQ9XCJSZS1zdG9ja1wiXG4gICAgICAgICAgICBhZGRpdGlvbmFsLXRleHQtc3RhdGU9XCJOZWdhdGl2ZVwiPkJhbmFuYTwvdWk1LWxpPlxuICAgICAgICA8dWk1LWxpIGljb249XCJudXRyaXRpb24tYWN0aXZpdHlcIiBkZXNjcmlwdGlvbj1cIlNtYWxsIGZydWl0IHRoYXQgY29tZXMgaW4gdmFyaW91cyBjb2xvcnMsIGluY2x1ZGluZyByZWQsIHB1cnBsZVwiIGFkZGl0aW9uYWwtdGV4dD1cIlJlLXN0b2NrXCJcbiAgICAgICAgICAgIGFkZGl0aW9uYWwtdGV4dC1zdGF0ZT1cIkluZm9ybWF0aW9uXCI-UGx1bTwvdWk1LWxpPlxuICAgICAgICA8dWk1LWxpIGljb249XCJudXRyaXRpb24tYWN0aXZpdHlcIiBkZXNjcmlwdGlvbj1cIiB0cm9waWNhbCBmcnVpdCBrbm93biBmb3IgaXRzIHN3ZWV0IGFuZCBqdWljeSBpbnRlcmlvclwiIGFkZGl0aW9uYWwtdGV4dD1cIlJlLXN0b2NrXCJcbiAgICAgICAgICAgIGFkZGl0aW9uYWwtdGV4dC1zdGF0ZT1cIk5lZ2F0aXZlXCI-TWFuZ288L3VpNS1saT5cbiAgICA8L3VpNS1saXN0PlxuICAgIDwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuICAgIDxzY3JpcHQgdHlwZT1cIm1vZHVsZVwiIHNyYz1cIm1haW4uanNcIj48L3NjcmlwdD5cbjwvYm9keT5cblxuPC9odG1sPlxuPCEtLSBwbGF5Z3JvdW5kLWZvbGQtZW5kIC0tPlxuIn0sIm1haW4uanMiOnsibmFtZSI6Im1haW4uanMiLCJjb250ZW50IjoiLyogcGxheWdyb3VuZC1oaWRlICovXG5pbXBvcnQgXCIuL3BsYXlncm91bmQtc3VwcG9ydC5qc1wiO1xuLyogcGxheWdyb3VuZC1oaWRlLWVuZCAqL1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzL2Rpc3QvTGlzdC5qc1wiO1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzL2Rpc3QvTGlzdEl0ZW1TdGFuZGFyZC5qc1wiO1xuXG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMtaWNvbnMvZGlzdC9udXRyaXRpb24tYWN0aXZpdHkuanNcIjtcblxubGV0IGl0ZW1zTG9hZGVkID0gMDtcbmNvbnN0IGl0ZW1Ub0xvYWQgPSA1O1xuY29uc3QgZ3Jvd2luZ0xpc3QgPSBkb2N1bWVudC5xdWVyeVNlbGVjdG9yKFwiI2dyb3dpbmdMaXN0XCIpO1xuY29uc3QgbGlzdEl0ZW1UZW1wbGF0ZSA9IChpbmRleCkgPT4ge1xuICAgIHZhciBsaSA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoXCJ1aTUtbGlcIik7XG4gICAgbGkudGV4dENvbnRlbnQgPSBcIkZydWl0IG5hbWVcIjtcbiAgICBsaS5kZXNjcmlwdGlvbiA9IFwidGhlIGRlc2NyaXB0aW9uIGdvZXMgaGVyZSBcIiArIGluZGV4O1xuICAgIGxpLmFkZGl0aW9uYWxUZXh0ID0gXCJBdmFpbGFibGVcIjtcbiAgICBsaS5hZGRpdGlvbmFsVGV4dFN0YXRlID0gXCJQb3NpdGl2ZVwiO1xuICAgIGxpLmljb24gPSBcIm51dHJpdGlvbi1hY3Rpdml0eVwiO1xuICAgIHJldHVybiBsaTtcbn1cblxuY29uc3QgaW5zZXJ0SXRlbXMgPSAobGlzdCkgPT4ge1xuICAgIGZvciAodmFyIGkgPSBpdGVtc0xvYWRlZDsgaSA8IGl0ZW1zTG9hZGVkICsgaXRlbVRvTG9hZDsgaSsrKSB7XG4gICAgICAgIGxpc3QuYXBwZW5kQ2hpbGQobGlzdEl0ZW1UZW1wbGF0ZShpKSk7XG4gICAgfVxuICAgIGl0ZW1zTG9hZGVkKz1pdGVtVG9Mb2FkO1xufVxuXG5ncm93aW5nTGlzdC5hZGRFdmVudExpc3RlbmVyKFwibG9hZC1tb3JlXCIsIChlKSA9PiB7XG4gICAgZ3Jvd2luZ0xpc3QubG9hZGluZyA9IHRydWU7XG4gICAgXG4gICAgc2V0VGltZW91dCgoKSA9PiB7XG4gICAgICAgIGluc2VydEl0ZW1zKGdyb3dpbmdMaXN0KTtcbiAgICAgICAgZ3Jvd2luZ0xpc3QubG9hZGluZyA9IGZhbHNlO1xuICAgIH0sIDE1MDApO1xufSk7In19)

Thanks and Best regards,
Yana
