### ISSUE TITLE
[ui5-menu]: no visual action states

### ISSUE THREAD

**Issue by nnaydenow** [SAP/ui5-webcomponents#9728]
### Bug Description

Missing hover / selected states when moving mouse over items

### Affected Component

ui5-menu

### Isolated Example

https://sap.github.io/ui5-webcomponents/components/Menu/#basic-sample

### Steps to Reproduce

1.
2.
3.
...

### Priority

None

### UI5 Web Components Version

nightly

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by yanaminkova** [comment]
Hello @SAP/ui5-webcomponents-topic-b ,

Could you please have a look at this issue regarding the missing hover/selected states when moving mouse over the `ui5-menu` items?

Thanks and Best regards,
Yana
