### ISSUE TITLE
[Slider]: Support custom label for Slider component

### ISSUE THREAD

**Issue by saurabhmehta02** [SAP/ui5-webcomponents#9730]
### Is your feature request related to a problem?

We need to enhance the current slider web component to allow for custom labels instead of displaying the default numeric value.
We are using Slider to represent ratings or scores, where numeric values (e.g., 1-5) are mapped to descriptive labels (e.g., 1 = "Beginner").
Instead of showing the numeric value on the slider, it should display the corresponding custom label (e.g., "Beginner" instead of "1").
For some customers, due to compliance reasons, displaying numeric values is not allowed.
The component should support hiding these numeric values and instead display custom labels that do not reveal the actual numbers.

### Describe the solution you'd like

The solution should introduce the ability for the slider component to accept and display custom labels.
Allow developers to define a mapping between slider values (e.g., 1-5) and custom labels (e.g., "Beginner", "Intermediate", "Advanced").

### Organization

SAP Labs

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by yanaminkova** [comment]
Hello @SAP/ui5-webcomponents-topic-rl  ,

Could you please review this feature request for adding support of custom labels to the `uir-slider` component?

Thanks and Best regards,
Yana

**Comment by hristop** [comment]
Hi @saurabhmehta02 ,

This feature was already requested here: #9058 so i will close this as a duplicate. 

Best Regards,
Hristo
