### ISSUE TITLE
[ui5-select]: fast navigation to options doesn't work after submit

### ISSUE THREAD

**Issue by nnaydenow** [SAP/ui5-webcomponents#9757]
### Bug Description

ui5-select provides option to navigate to specific option if the option's text starts with the respective typed text.

Pressing `Enter` key closes the popover and confirms the selection of the selected option but doesn't clear the typed characters. With that starting to type new word doesn't change selection. 

This affects some test execution since some of the tests doesn't reload the page and they are using the same select.

[Isolated example](https://sap.github.io/ui5-webcomponents/play/#eyJpbmRleC5odG1sIjp7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuPCFET0NUWVBFIGh0bWw-XG48aHRtbCBsYW5nPVwiZW5cIj5cblxuXG5cblxuXG48aGVhZD5cbiAgICBcbiAgICA8c3R5bGU-XG4gICAgICAqOm5vdCg6ZGVmaW5lZCkge1xuICAgICAgICBkaXNwbGF5OiBub25lO1xuICAgICAgfVxuICAgIDwvc3R5bGU-XG5cbiAgICBcbiAgICA8c3R5bGU-XG4gICAgICAqOm5vdCg6ZGVmaW5lZCkge1xuICAgICAgICBkaXNwbGF5OiBub25lO1xuICAgICAgfVxuICAgIDwvc3R5bGU-XG5cbiAgICBcbiAgICA8c3R5bGU-XG4gICAgICAqOm5vdCg6ZGVmaW5lZCkge1xuICAgICAgICBkaXNwbGF5OiBub25lO1xuICAgICAgfVxuICAgIDwvc3R5bGU-XG5cbiAgICBcbiAgICA8c3R5bGU-XG4gICAgICAqOm5vdCg6ZGVmaW5lZCkge1xuICAgICAgICBkaXNwbGF5OiBub25lO1xuICAgICAgfVxuICAgIDwvc3R5bGU-XG5cbiAgICBcbiAgICA8c3R5bGU-XG4gICAgICAqOm5vdCg6ZGVmaW5lZCkge1xuICAgICAgICBkaXNwbGF5OiBub25lO1xuICAgICAgfVxuICAgIDwvc3R5bGU-XG5cbiAgICA8bWV0YSBjaGFyc2V0PVwiVVRGLThcIj5cbiAgICA8bWV0YSBuYW1lPVwidmlld3BvcnRcIiBjb250ZW50PVwid2lkdGg9ZGV2aWNlLXdpZHRoLCBpbml0aWFsLXNjYWxlPTEuMFwiPlxuICAgIDx0aXRsZT5TYW1wbGU8L3RpdGxlPlxuPC9oZWFkPlxuPGJvZHkgc3R5bGU9XCJiYWNrZ3JvdW5kLWNvbG9yOiB2YXIoLS1zYXBCYWNrZ3JvdW5kQ29sb3IpO1wiPlxuPCEtLSBwbGF5Z3JvdW5kLWZvbGQtZW5kIC0tPlxuPGRpdiBzdHlsZT1cImhlaWdodDogMzAwcHg7XCI-XG48dWk1LXNlbGVjdD5cbiAgPHVpNS1vcHRpb24-QUFBQUFBPC91aTUtb3B0aW9uPlxuICA8dWk1LW9wdGlvbj5CQkJCQkI8L3VpNS1vcHRpb24-XG4gIDx1aTUtb3B0aW9uPkNDQ0NDQzwvdWk1LW9wdGlvbj5cbiAgPHVpNS1vcHRpb24-REREREREPC91aTUtb3B0aW9uPlxuPC91aTUtc2VsZWN0PlxuICA8L2Rpdj5cbjwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuICAgIDxzY3JpcHQgdHlwZT1cIm1vZHVsZVwiIHNyYz1cIm1haW4uanNcIj48L3NjcmlwdD5cbjwvYm9keT5cbjwvaHRtbD5cbjwhLS0gcGxheWdyb3VuZC1mb2xkLWVuZCAtLT5cblxuIn0sIm1haW4uanMiOnsibmFtZSI6Im1haW4uanMiLCJjb250ZW50IjoiLyogcGxheWdyb3VuZC1oaWRlICovXG5pbXBvcnQgXCIuL3BsYXlncm91bmQtc3VwcG9ydC5qc1wiO1xuLyogcGxheWdyb3VuZC1oaWRlLWVuZCAqL1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzL2Rpc3QvU2VsZWN0LmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMvZGlzdC9PcHRpb24uanNcIjtcbiJ9fQ)

### Expected Behaviour

If option is selected by `Enter` key and then new word is typed, the selection to be moved to the new word

### Steps to Reproduce

1. Open example
2. Open picker
3. Type a
4. Press enter right after typing a
5. When the picker is closed press one of the others letters: b/c/d
...

### Priority

None

### UI5 Web Components Version

nightly

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by elenastoyanovaa** [comment]
Hello @SAP/ui5-webcomponents-topic-p ,

The issue is reproducible, but the interaction should be done fast. Type a, then press Enter and immediately press b - the selection is not moved to the second item. If the same is performed slowly, the issue is not reproducible.

It is a relevant use case as the tests are failing due to the 1s timeout logic for clearing a `_typedChars`.

Kind Regards,
Elena
