### ISSUE TITLE
[input][password type][mobile]: input field had a delay when type is password

### ISSUE THREAD

**Issue by gaeun-gabie** [SAP/ui5-webcomponents#9760]
### Bug Description

Bug Description
component: https://sap.github.io/ui5-webcomponents-react/v1/?path=/docs/inputs-input--docs
when using mobile device, there is one or two seconds delay on showing dot icon in password input field.

![image](https://github.com/user-attachments/assets/f121f853-cf27-49a3-8034-a25dae51bba3)

### Affected Component

input

### Expected Behaviour

shouldn't have a delay

### Steps to Reproduce

1. enter the following link using mobile device (https://sap.github.io/ui5-webcomponents-react/v1/?path=/docs/inputs-input--docs)
2. change input type to password
3. start typing on the input text field
4. see the delay on showing the typed in characters
5. if you can't repro close the tab and open a new tab and repeat part 1 to 4

### Priority

Medium

### UI5 Web Components Version

version doesn't matter, can repro on the document (latest version)

### Browser

Safari

### Operating System

ios

### Organization

SAP Cloud

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by elenastoyanovaa** [comment]
Hello @gaeun-gabie ,

I have prepared a sample with native input and a ui5-input, both with type password: [sample](https://sap.github.io/ui5-webcomponents/play/#eyJpbmRleC5odG1sIjp7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuPCFET0NUWVBFIGh0bWw-XG48aHRtbCBsYW5nPVwiZW5cIj5cblxuXG5cbjxoZWFkPlxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG4gICAgPC9zdHlsZT5cblxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG4gICAgPC9zdHlsZT5cblxuICAgIDxtZXRhIGNoYXJzZXQ9XCJVVEYtOFwiPlxuICAgIDxtZXRhIG5hbWU9XCJ2aWV3cG9ydFwiIGNvbnRlbnQ9XCJ3aWR0aD1kZXZpY2Utd2lkdGgsIGluaXRpYWwtc2NhbGU9MS4wXCI-XG4gICAgPHRpdGxlPlNhbXBsZTwvdGl0bGU-XG48L2hlYWQ-XG5cbjxib2R5IHN0eWxlPVwiYmFja2dyb3VuZC1jb2xvcjogdmFyKC0tc2FwQmFja2dyb3VuZENvbG9yKVwiPlxuICAgIDwhLS0gcGxheWdyb3VuZC1mb2xkLWVuZCAtLT5cblxuICAgIDx1aTUtaW5wdXQgdHlwZT1cIlBhc3N3b3JkXCI-PC91aTUtaW5wdXQ-XG4gICAgPGlucHV0IHR5cGU9XCJwYXNzd29yZFwiPlxuICAgIDwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuICAgIDxzY3JpcHQgdHlwZT1cIm1vZHVsZVwiIHNyYz1cIm1haW4uanNcIj48L3NjcmlwdD5cbjwvYm9keT5cblxuPC9odG1sPlxuPCEtLSBwbGF5Z3JvdW5kLWZvbGQtZW5kIC0tPlxuIn0sIm1haW4uanMiOnsibmFtZSI6Im1haW4uanMiLCJjb250ZW50IjoiLyogcGxheWdyb3VuZC1oaWRlICovXG5pbXBvcnQgXCIuL3BsYXlncm91bmQtc3VwcG9ydC5qc1wiO1xuLyogcGxheWdyb3VuZC1oaWRlLWVuZCAqL1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzL2Rpc3QvSW5wdXQuanNcIjsifX0)
I do not see any delay or difference between the two input fields. The ui5-input behaves exactly the same as the native one. I am also unable to play the video you provided, but if the issue you are reporting is related to the fact that the last typed character is always shown, the same behavior is present in the native input field as well. 
I am closing the issue as a consultation, but if there is some other issue, please provide us with a sample or adjust the one I prepared + a video which could be played will be helpful as well.

Kind Regards,
Elena

**Comment by gaeun-gabie** [comment]
Hi @elenastoyanovaa,
I also tested with the provided sample, but wasn't able to see a delay.
So, the issue is that when I type in a character, the cursor moves to the right but then nothing shows up one the left side (it's adding just an empty space). But, after one second, dot appears.
I wasn't able to repro the issue in the sample that you provided, but the issue was reproducible in https://sap.github.io/ui5-webcomponents-react/v1/?path=/docs/inputs-input--docs

https://github.com/user-attachments/assets/f48c1eba-9571-4c6c-ae1c-644ec13d2fe8

**Comment by elenastoyanovaa** [comment]
Hello @MarcusNotheis @Lukas742 ,

It seems that this side effect is related to the react input component and the issue is not reproducible with plain input or ui5-input. Could you please transfer the issue?

Kind Regards,
Elena
