### ISSUE TITLE
[ui5-date-picker | vue :

### ISSUE THREAD

**Issue by malonmiming** [SAP/ui5-webcomponents#9761]
### Bug Description

I want to use "Date Picker" but I CAN'T use this.
I already tryed to import @ui5/webcomponents/dist/Assets.js in the "main.js" or "app.vue"

[error message]
LocaleData.ts:27 [LocaleData] Supported locale "ko" not configured, import the "Assets.js" module from the webcomponents package you are using.
Show 6 more frames

LocaleData.ts:98 Uncaught (in promise)
Error: CLDR data for locale ko is not loaded!
at getLocaleData (LocaleData.ts:98:9)
at Object.loadResource (LoaderExtensions.ts:10:9)
at getOrLoad (LocaleData.js:2520:55)
at getData (LocaleData.js:2572:13)
at new constructor (LocaleData.js:57:23)
at new LocaleData (LocaleData.ts:6:1)
at getCachedLocaleDataInstance (getCachedLocaleDataInstance.ts:9:21)
at get _primaryCalendarType (DateComponentBase.ts:98:22)
at HTMLElement.getFormat (DateComponentBase.ts:173:24)
at HTMLElement.isValid (DatePicker.ts:631:17)

### Affected Component

DatePicker

### Expected Behaviour

it doesn't work

### Steps to Reproduce

1.
2.
3.
...

### Priority

None

### UI5 Web Components Version

 "@ui5/webcomponents": "^2.1.1",     "@ui5/webcomponents-fiori": "^2.1.1",

### Browser

Chrome

### Operating System

window10

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by elenastoyanovaa** [comment]
Hello @malonmiming ,

I forked our sample repo with vue and I updated it to use ui5-webcomponents 2.1.1 and simplified it to import and use just a single ui5-datepicker and everything works correctly. You can check my forked repo:
https://github.com/elenastoyanovaa/ui5-webcomponents-sample-vue

Here is a link to the same repo, but integrated in stackblitz https://stackblitz.com/~/github.com/elenastoyanovaa/ui5-webcomponents-sample-vue

You can check out the official example application with ui5-webcomponents and Vue repo: https://github.com/elenastoyanovaa/ui5-webcomponents-sample-vue and adjust it according to your use case.

If you still think that there is a problem with our project, please provide us with a sample application and send it to us to analyze it or adjust the one I provided to you.

Kind Regards,
Elena
