### ISSUE TITLE
Feature Request [List & ListItemCustom]:  emit onFocus event when the the list item is focused

### ISSUE THREAD

**Issue by AlexYanSap** [SAP/ui5-webcomponents#9772]
### Bug Description

In our case,  some actions in the ListItemCustom will shown when the user hovers over the custom list item. It's natural for mouse users but keyboard users cannot see the same when they use the arrow key to focus on the list item. 

### Affected Component

List

### Expected Behaviour

onFocus event should be provided when the list item is focused and will help the keyboard user have the same experience as the mouse user.

### Isolated Example

https://sap.github.io/ui5-webcomponents/components/List/

### Steps to Reproduce

 v2.1.2 does not provide the onFocus event
<img width="466" alt="image" src="https://github.com/user-attachments/assets/06575e51-38b4-42d0-a703-6a10394a76cf">

### Priority

None

### UI5 Web Components Version

1.24.0, 2.1.2

### Browser

Chrome, Edge, Firefox, Safari

### Organization

SAP SF

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by elenastoyanovaa** [comment]
Hello,

You could simply attach to the focusin event.
Please check the sample I provided [Focus Example](https://sap.github.io/ui5-webcomponents/play/#eyJpbmRleC5odG1sIjp7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuPCFET0NUWVBFIGh0bWw-XG48aHRtbCBsYW5nPVwiZW5cIj5cblxuXG5cbjxoZWFkPlxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG4gICAgPC9zdHlsZT5cblxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG4gICAgPC9zdHlsZT5cblxuICAgIDxtZXRhIGNoYXJzZXQ9XCJVVEYtOFwiPlxuICAgIDxtZXRhIG5hbWU9XCJ2aWV3cG9ydFwiIGNvbnRlbnQ9XCJ3aWR0aD1kZXZpY2Utd2lkdGgsIGluaXRpYWwtc2NhbGU9MS4wXCI-XG4gICAgPHRpdGxlPlNhbXBsZTwvdGl0bGU-XG48L2hlYWQ-XG5cbjxib2R5IHN0eWxlPVwiYmFja2dyb3VuZC1jb2xvcjogdmFyKC0tc2FwQmFja2dyb3VuZENvbG9yKVwiPlxuICAgIDwhLS0gcGxheWdyb3VuZC1mb2xkLWVuZCAtLT5cblxuICAgIDx1aTUtbGlzdD5cbiAgICAgICAgPHVpNS1saSBvbmZvY3VzaW49XCJjb25zb2xlLmxvZygnZm9jdXMhJylcIiBpY29uPVwibnV0cml0aW9uLWFjdGl2aXR5XCIgZGVzY3JpcHRpb249XCJUcm9waWNhbCBwbGFudCB3aXRoIGFuIGVkaWJsZSBmcnVpdFwiIGFkZGl0aW9uYWwtdGV4dD1cIkluLXN0b2NrXCJcbiAgICAgICAgICAgIGFkZGl0aW9uYWwtdGV4dC1zdGF0ZT1cIlBvc2l0aXZlXCI-UGluZWFwcGxlPC91aTUtbGk-XG4gICAgICAgIDx1aTUtbGkgaWNvbj1cIm51dHJpdGlvbi1hY3Rpdml0eVwiIGRlc2NyaXB0aW9uPVwiT2NjdXJzIGJldHdlZW4gcmVkIGFuZCB5ZWxsb3dcIiBhZGRpdGlvbmFsLXRleHQ9XCJFeHBpcmVzXCJcbiAgICAgICAgICAgIGFkZGl0aW9uYWwtdGV4dC1zdGF0ZT1cIkNyaXRpY2FsXCI-T3JhbmdlPC91aTUtbGk-XG4gICAgICAgIDx1aTUtbGkgaWNvbj1cIm51dHJpdGlvbi1hY3Rpdml0eVwiIGRlc2NyaXB0aW9uPVwiVGhlIHllbGxvdyBsZW5ndGh5IGZydWl0XCIgYWRkaXRpb25hbC10ZXh0PVwiUmUtc3RvY2tcIlxuICAgICAgICAgICAgYWRkaXRpb25hbC10ZXh0LXN0YXRlPVwiSW5mb3JtYXRpb25cIj5CbHVlYmVycnk8L3VpNS1saT5cbiAgICAgICAgPHVpNS1saSBpY29uPVwibnV0cml0aW9uLWFjdGl2aXR5XCIgZGVzY3JpcHRpb249XCJUaGUgdHJvcGljYWwgc3RvbmUgZnJ1aXRcIiBhZGRpdGlvbmFsLXRleHQ9XCJSZS1zdG9ja1wiXG4gICAgICAgICAgICBhZGRpdGlvbmFsLXRleHQtc3RhdGU9XCJOZWdhdGl2ZVwiPk1hbmdvPC91aTUtbGk-XG4gICAgPC91aTUtbGlzdD5cbiAgICA8IS0tIHBsYXlncm91bmQtZm9sZCAtLT5cbiAgICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCJtYWluLmpzXCI-PC9zY3JpcHQ-XG48L2JvZHk-XG5cbjwvaHRtbD5cbjwhLS0gcGxheWdyb3VuZC1mb2xkLWVuZCAtLT5cbiJ9LCJtYWluLmpzIjp7Im5hbWUiOiJtYWluLmpzIiwiY29udGVudCI6Ii8qIHBsYXlncm91bmQtaGlkZSAqL1xuaW1wb3J0IFwiLi9wbGF5Z3JvdW5kLXN1cHBvcnQuanNcIjtcbi8qIHBsYXlncm91bmQtaGlkZS1lbmQgKi9cbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L0xpc3QuanNcIjtcbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L0xpc3RJdGVtU3RhbmRhcmQuanNcIjtcbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy1pY29ucy9kaXN0L251dHJpdGlvbi1hY3Rpdml0eS5qc1wiO1xuIn19)

Kind Regards,
Elena
