### ISSUE TITLE
[Wizard]: Stacked Wizard Steps not aligned properly

### ISSUE THREAD

**Issue by Neeeko** [SAP/ui5-webcomponents#9779]
### Describe the bug

It's not extremely visible (although it's there) in the sample, but more visible in our application.

In smaller screens, the Stacked (or non selected) steps are not properly horizontally aligned with the other steps numbers.

In the following example, here's how it looks like with a screen width of about 450px:
https://stackblitz.com/edit/github-rhfduk?file=src%2FApp.tsx
<img width="592" alt="Screenshot 2024-08-29 at 8 48 26 PM" src="https://github.com/user-attachments/assets/4f93fb30-4429-4321-96ea-774d2008a019">
<img width="482" alt="Screenshot 2024-08-29 at 8 49 21 PM" src="https://github.com/user-attachments/assets/11892f31-78fa-415f-ab27-78e9cf14ee94">

**Here's how it looks like in our application. It's way more visible.**
<img width="978" alt="Screenshot 2024-08-29 at 8 52 51 PM" src="https://github.com/user-attachments/assets/c916f1ea-4afe-455f-a20f-c06902928412">

I was unable to reproduce this issue in ui5-webcomponents playground.

### Isolated Example

https://stackblitz.com/edit/github-rhfduk?file=src%2FApp.tsx

### Reproduction steps

1. Go to https://stackblitz.com/edit/github-rhfduk?file=src%2FApp.tsx
2. Reduce the screen width to around 450px
3. Go to step 4
4. Notice the alignment issue

### Expected Behaviour

All step numbers should be properly aligned.

### UI5 Web Components for React Version

latest

### UI5 Web Components Version

latest

### Browser

Chrome, Edge, Firefox, Safari

### Organization

SuccessFactors

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by elenastoyanovaa** [comment]
Hello @SAP/ui5-webcomponents-topic-rl ,

Could you please take a look of this alignment issue of the ui5-wizard navigation area?

Kind Regards,
Elena

**Comment by Neeeko** [comment]
Hi, any update on this ticket? This misalignment is quite visible in our project. Thanks!
