### ISSUE TITLE
[Form]: Label of field always on top when setting another theme

### ISSUE THREAD

**Issue by langered** [SAP/ui5-webcomponents#9788]
### Describe the bug

When changing the theme (e.g. `sap_horizon_dark`) the label will always be displayed on top of its assosiated field.
It seems that it is not respecting the `labelSpan` configuration.
The documentation says, that if `12` is configured, the label is displayed above the field. For this example, I configured the size S to 4 to make sure it should never be the case.

When not changing the theme at all, everything works as expected.

### Isolated Example

https://stackblitz.com/edit/github-mezoel?file=src%2FApp.tsx

### Reproduction steps

1. Start the stackblitz examle
2. Look at the Form
3. Remove the line where the theme is set
4. See that everything works as expected

### Expected Behaviour

- I expect that the theme only changes the ui5 theme, not the behaviour of the Form formatting. The configuration of `labelSpan` should be respected.

### Screenshots or Videos

When theme is changed to `sap_horizon_dark`, the label is above the field:
<img width="1211" alt="image" src="https://github.com/user-attachments/assets/4ec84265-45a4-4a1d-9e93-9edf6dd692b3">

When no `setTheme` is executed, the form layout is correct and the label is next to the field:
<img width="1206" alt="image" src="https://github.com/user-attachments/assets/0fc82bbb-cc5c-44ea-bdb9-c7cc2111e8a3">

### UI5 Web Components for React Version

2.0.2

### UI5 Web Components Version

2.1.2

### Browser

Chrome, Safari

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by kskondov** [comment]
Hello @SAP/ui5-webcomponents-topic-core,

This issue is reproducible when changing themes ```labelSpan``` property is ignored and labels positions in the form component is changed.

Best Regards,
Konstantin

**Comment by ilhan007** [comment]
Hello @langered thanks for reporting, fix has been prepared.
