### ISSUE TITLE
[SF] [F6Navigation]: F6 fast navigation is not working as expected when there're multiple ui5 webcomponents (@ui5/webcomponents-base to be precise) bundles running in a page

### ISSUE THREAD

**Issue by 2bno1** [SAP/ui5-webcomponents#9795]
### Bug Description

Our page consists of several widgets. Each widgets is built on separate ui5 webcomponents. So finally there may be several ui5 webcomponents bundles running in one page.

In this case, fast navigation via F6 is not working as expected.

For example, there're 6 fast navigation groups in the page: G1, G2, ...G6 and there're two ui5 webcomponents bundles running.
For every F6 strike, it will skip one more navigation groups than normal, so the navigation sequence may be G1 -> G3 -> G5 -> G1 ...

### Affected Component

F6Navigation

### Expected Behaviour

The expected behavior is that for each F6 strike, it move to next fast navigation group: G1 -> G2 -> G3 ...

### Steps to Reproduce

It's a little difficult to provide a reproduced sample as we need to make multiple ui5 webcomponents bundles in one page.

### Priority

Medium

### UI5 Web Components Version

1.23.1

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by kskondov** [comment]
Hello @2bno1, 

Thanks for reporting the issue but with the information provided we will not be able to investigate and find a solution, so in order to speed up the processing of the issue please provide a sample.

Best Regards

**Comment by nnaydenow** [comment]
Hi @kskondov,

I've managed to reproduce the issue and I'll take it.
