### ISSUE TITLE
[popover]: arrow is visually broken when using placementType="Bottom"

### ISSUE THREAD

**Issue by ok** [SAP/ui5-webcomponents#9799]
### Bug Description

Visual look of arrow from 'ui5-popover-arrow' is broken when using `placementType="Bottom"`.

![Screenshot 2024-09-03 at 14 18 33](https://github.com/user-attachments/assets/86705c64-0c49-4147-a5fb-c234b6ce5e89)

### Affected Component

Popover

### Expected Behaviour

Visual style of ui5-popover-arrow should be clean looking and consistent for all configurations.

### Isolated Example

https://sap.github.io/ui5-webcomponents/components/Popover/

### Steps to Reproduce

1. visit official documentation at https://sap.github.io/ui5-webcomponents/components/Popover/#more-samples
2. in last sample, click _Open Popover to Bottom_.

### Log Output, Stack Trace or Screenshots

![Screenshot 2024-09-03 at 14 18 33](https://github.com/user-attachments/assets/1a866a03-846c-432f-b204-f5fb3ea044e3)

### Priority

Low

### UI5 Web Components Version

1.*, 2.*

### Browser

Chrome

### Operating System

Windows, macOS

### Organization

SAP / UDEx components team

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by PlutaKatarzyna** [comment]
Hi @ilhan007 , can this fix be downported into 1.24?
