### ISSUE TITLE
[Feature Request]: <ui5-side-navigation> for 3levels menu

### ISSUE THREAD

**Issue by malonmiming** [SAP/ui5-webcomponents#9801]
### Feature Request Description

Hello dear!

Many business screens typically use three levels of menu.
So, I want to use the "SideNavigation" with more than two levels. exactly 3levels.
I already tryed to add HTML element into the <ui5-side-navigation>. it was fail.

how can I do???
HELP ME!

Best Regards

### Proposed Solution

SideNavigation for 3levels

### Priority

High

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by TeodorTaushanov** [comment]
Hi @malonmiming,

ui5-side-navigation supports 3 levels of nesting - groups-items-sub items

You can check this example:
https://sap.github.io/ui5-webcomponents/components/fiori/SideNavigation/#basic-sample

Best,
Teo
