### ISSUE TITLE
[Input]: [Not reading input type after accessibleName is reading placeholder and placeholder name that is wrong behaviour]

### ISSUE THREAD

**Issue by jadhavarjun** [SAP/ui5-webcomponents#9802]
### Describe the bug

We have input field into the filter column, when we focus on that input field it should read accessibleName and input type for e.g here I am attaching the screenshot that expected behavior we want.
expected behavior:
![Screenshot 2024-08-23 092554](https://github.com/user-attachments/assets/a0c9e54a-3c9f-4236-8427-94c5fa3330d3)
In that above screenshot you can see JAWS reader reading input field accessible name and input type correctly and that works with only input type number and password for other input type for e.g text, string, URL is not working perfectly.
Here is I am attaching incorrect screenshot in that screenshot I have highlighted placeholder and placeholder name that in incorrect reading please fix that issue.
Incorrect reading screenshot:
![Screenshot 2024-08-23 091001](https://github.com/user-attachments/assets/7dcfbaa8-838e-4a05-b250-c6cbbaa3ac56)

Here is storybook link where you can test: https://sap.github.io/ui5-webcomponents-react/v1/?path=/story/inputs-input--default&args=type:URL;accessibleName:arjun;placeholder:arjun

Step:
1. Open the link and I have already entered accessibleNam="arjun" and placholder="arjun".
2. you can select input type is number and check with JAWS reader is reading correctly "arjun spin box edit" but when you select input type is text it will read like "arjun edit blank placeholder arjun Type in text." that placeholder arjun is inorrect.
3.Try with another input type and please fix this issue for all the type.

### Reproduction steps

1.
2.
3.
...

### UI5 Web Components for React Version

latest

### UI5 Web Components Version

latest

### Browser

Chrome

### Operating System

WIndows

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by kskondov** [comment]
Hello @ui5-webcomponents-topic-rl , 

Can you take a look of issue for incorrect reading for the input component with type text in version 1?

Best Regards,
Konstantin

**Comment by ndeshev** [comment]
Hello @jadhavarjun,


I can not reproduce the issue with JAWS on Windows OS, the type and the accessible name is being announced correctly.
