### ISSUE TITLE
Dynamic Page:  Accessibility issue with reading Pin Header button UI information read out twice / thrice

### ISSUE THREAD

**Issue by Vinayak1234** [SAP/ui5-webcomponents#9819]
### Accessibility Issue:
On activating ‘Pin Header’ button, the UI information is read out thrice on JAWS and twice on NVDA screen reader software to the end user.

### Affected Component

Dynamic Page

### Expected Behaviour

‘Pin Header’ button UI information should read out only once.

### Steps to Reproduce

1. Open JAWS/NVDA screen reader software.
2. Go to the Dynamic Page and toggle  Pin Header’ button.

### Log Output, Stack Trace or Screenshots

![image](https://github.com/user-attachments/assets/dce43042-06f8-4274-8937-65b7a010f5cd)

https://github.com/user-attachments/assets/c04dbe6b-d96d-468e-ac28-e9a87859d230

### Priority

None

### UI5 Web Components Version

1.23.1

### Browser

Chrome

### Operating System

Windows

### Organization

SAP Labs India

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by kskondov** [comment]
Hello @SAP/ui5-webcomponents-topic-p ,

Can you please take a look at this issue with the dynamic page component, where the pin header button is read more than once?

Best Regards,
Konstantin
