### ISSUE TITLE
[component: ui5-breadcrumbs | framework: Angular | build: 18.2.0 | typescript :5.5.2]: @for clause not working inside ui5-breadcrumbs

### ISSUE THREAD

**Issue by OnesimoMartins** [SAP/ui5-webcomponents#9829]
### Bug Description

HTML:
`<ui5-breadcrumbs>
  @for (c of crumbs;track c){
  <ui5-breadcrumbs-item  href="#"> {{c.text}}</ui5-breadcrumbs-item>
  }
</ui5-breadcrumbs>`

TS:
`
import "@ui5/webcomponents/dist/Breadcrumbs.js";
import "@ui5/webcomponents/dist/BreadcrumbsItem.js";

@Component({
  selector: 'app-breadcrumbs',
  standalone: true,
  templateUrl: './breadcrumbs.component.html',
  styleUrl: './breadcrumbs.component.css',
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class BreadcrumbsComponent implements OnInit, AfterViewInit {
  crumbs = [
    { text: 'products', href: '#' },
    { text: 'list', href: '#' }
  ];
}`

Then the console prints:
![Screenshot (56)](https://github.com/user-attachments/assets/f47f2374-80e0-4456-a99f-7f072fc12b83)

 I also tried to *ngFor directive.

but the breadcrumbs items aren`t rendered, can samoene help me please?

### Affected Component

ui5-breadcrumbs

### Expected Behaviour

expected to render all breadcrumbs items inside @for clause

### Steps to Reproduce

1.
2.
3.
...

### Priority

High

### UI5 Web Components Version

2.0.0

### Browser

Chrome, Edge

### Operating System

Windows 11

### Organization

ERPsAngola

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by nnaydenow** [comment]
Hi @OnesimoMartins,

Could you please provide example where you can reproduce the problem?

I've created a simple one and everything seems that works as expected: https://stackblitz.com/edit/stackblitz-starters-c9nmgk?file=src%2Fmain.ts

Regards,
Nayden
