### ISSUE TITLE
[List]: [Selection Mode Multiple] Unique and meaningful accessible names are not provided for list items

### ISSUE THREAD

**Issue by achuth2912** [SAP/ui5-webcomponents#9852]
### Describe the bug

When we use a list with multi selection of checkbox.
We are seeing an accessibility issue with JAWS shortcut (Ctrl + Insert + X) to open a list of Checkbox, we observe all checkbox have the same name where Unique and meaningful accessible names are not provided for list items.

But when we traverse through using a up & down arrow key JAWS announces the expected names.

### Isolated Example

https://sap.github.io/ui5-webcomponents-react/v2/?path=/story/data-display-list--default&args=headerText:List+with+ListItemStandard;selectionMode:Multiple;separators:All;growing:None

### Reproduction steps

1.
2.
3.
...

### Expected Behaviour

We need to have a meaningful accessible names for the checkbox when we launch JAWS shortcut (Ctrl + Insert + X) to open a list of Checkbox

### Screenshots or Videos

![image (2)](https://github.com/user-attachments/assets/75399d97-c437-40dd-becc-5754e8f8c744)

### UI5 Web Components for React Version

1.29.8

### UI5 Web Components Version

1.24.8

### Browser

Chrome

### Operating System

Windows

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by didip1000** [comment]
Hey @SAP/ui5-webcomponents-topic-p,

Can you check if there should be accessible names for the checkboxes in the list?

Thank you,
Diana P.

**Comment by yanaminkova** [comment]
Hello @achuth2912,

We already have this request, therefore I am closing this one.
You could track the progress here - https://github.com/SAP/ui5-webcomponents/issues/6861

Best regards,
Yana
