### ISSUE TITLE
[SideNavigation]: SideNavigation popover elements are below dynamic page header

### ISSUE THREAD

**Issue by skowrons** [SAP/ui5-webcomponents#9853]
### Describe the bug

If we have a collapsed side navigation the popover text will be under the dynamic page. The object page on the other hand works fine.

<img width="147" alt="Bildschirmfoto 2024-09-11 um 17 02 50" src="https://github.com/user-attachments/assets/f2c56a3c-0934-4b67-b3e3-cc32f5fe042f">

### Isolated Example

[Example
](https://stackblitz.com/edit/github-vbzeim?file=src%2FApp.tsx)

### UI5 Web Components for React Version

^2.1.0

### UI5 Web Components Version

^2.2.0

### Browser

Chrome

### Operating System

Mac OS

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by didip1000** [comment]
Hey @SAP/ui5-webcomponents-topic-p,

I'm sending the ticket to you because it looks like a regression caused by the fix mentioned above. Can you please take a look?

Thanks,
Diana P.

**Comment by PetyaMarkovaBogdanova** [comment]
Dear colleagues,
as discussed with @TeodorTaushanov I am moving the issue on your board to be discussed internally as a part of a feature discussion about ToolPage implementation.

**Comment by TeodorTaushanov** [comment]
Hello,

The SideNavigation component is intended for use within an `ui5-navigation-layout` component. While it can function independently, it is recommended to use it with the `ui5-navigation-layout` for optimal user experience.

https://sap.github.io/ui5-webcomponents/components/fiori/NavigationLayout/

In your particular example, you can try to set "z-index: 200" of the ui5-side-navigation.

Best,
Teo
