### ISSUE TITLE
[UploadCollectionItem]: [Delete icon does not display correctly in responsive mode]

### ISSUE THREAD

**Issue by gsgill2021** [SAP/ui5-webcomponents#9873]
### Describe the bug

In responsive mode when viewport width is 320px, delete icon wraps to next row. e.g. view this in responsive mode using dev tools.
https://sap.github.io/ui5-webcomponents-react/v1/iframe.html?globals=backgrounds.grid:!false&args=&id=inputs-uploadcollection--simulate-upload&viewMode=story

### Expected Behaviour

delete icon should stay on the same row. e.g.

![correct](https://github.com/user-attachments/assets/6e48680a-7c0f-449a-a9ce-b5e07dc79e03)

### Screenshots or Videos

![wrong](https://github.com/user-attachments/assets/c0428ef8-f4dd-4803-8567-161bdfd8f3fc)

### UI5 Web Components for React Version

1.28.0

### UI5 Web Components Version

1.24.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by didip1000** [comment]
Hello @SAP/ui5-webcomponents-topic-rd,

Can you take a look at this issue? The delete icon wrapping starts at 510 px.

Thank you,
Diana P

**Comment by LidiyaGeorgieva** [comment]
Hello @gsgill2021

This responsive behavior is by design.
![{3F77460F-16C8-45CC-B691-D52F990C3D3D}](https://github.com/user-attachments/assets/4aac9615-a8db-4395-9c09-6230bc556a92)


Best Regards,
Lidiya
