### ISSUE TITLE
[MessageStrip]: Close button tooltip message is not according to design and no accessibleName is present.

### ISSUE THREAD

**Issue by pankajpandey01** [SAP/ui5-webcomponents#9874]
### Describe the bug

Close button tooltip message is not according to design.
Same tooltip is shown for Design - "Information", "Positive", "Negative", "Warning
Tooltip: Information Bar Close
 
There is no accessibleName 

### Reproduction steps

1. Go to https://sap.github.io/ui5-webcomponents-react/v1/?path=/docs/data-display-messagestrip--docs
2. See close button tooltip of MessageStrip

### Expected Behaviour

Tooltip message should be according to design.
accessibleName should be present. (It is good to have same accessibleName as tooltip otherwise Screen Reader will read both tooltip and accessibleName which usually will have same meaning in this case)

### UI5 Web Components for React Version

1.29.3

### UI5 Web Components Version

1.24.7

### Browser

Chrome, Edge, Firefox, Safari

### Organization

SuccessFactors

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by IlianaB** [comment]
Hello @SAP/ui5-webcomponents-topic-rl , this inquiry looks more like a feature request. Please, consider if accessibleName is required here and/or the tooltip message should be different according to the "design" of the MessageStrip - "Information", "Positive", "Negative", "Warning" (currently, it is "Information Bar Close" for all designs).

Regards,
Iliana

**Comment by elenastoyanovaa** [comment]
Hello,

We will enrich the tooltip of the close button according to the spec, but in the specification there is no `accessibleName`. 
As these are to different requests I would like to ask you to follow the InnerSource process for design change and request the `accessibleName` separately. Please keep in mind that a use case should be provided.

In this issue we will process the enrichment of the tooltip - including the `design` in the tooltip value. We need to double check with the designers if we should add `Positive` or `Success` and etc, for the other types of `design`.

Kind Regards,
Elena

**Comment by hristop** [comment]
P1 BLI was created: FIORITECHP1-31872
