### ISSUE TITLE
[Input]: [state binded to value prop not getting reflected in UI]

### ISSUE THREAD

**Issue by aviral49** [SAP/ui5-webcomponents#9884]
### Describe the bug

Hi, We are using the Input component, we are binding the value prop to state variable. While handling the onInput event, setting the state based on some validation but its not getting reflected in the UI.
version: `"@ui5/webcomponents-react": "1.29.10",`
Attaching the sandbox link - https://stackblitz.com/edit/github-virvsk?file=src%2FTestInput.tsx,src%2FApp.tsx,package.json,src%2Fmain.tsx

### Isolated Example

https://stackblitz.com/edit/github-virvsk?file=src%2FTestInput.tsx,src%2FApp.tsx,package.json,src%2Fmain.tsx

### Reproduction steps

1. Enter numbers in Input field
2. Once the length is greater than 4, setting the state to current state
3. Current state is not reflected in the ui for the input field but can be seen in Label component.

### Expected Behaviour

On setting the state to any value, should get reflected in the UI.
In our case, on entering the 5th digit, it should reflect the current value in state variable to ui.

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/8d6c040e-7036-40bd-9912-4ccadf47f437)

### UI5 Web Components for React Version

1.29.10

### UI5 Web Components Version

1.24.9

### Browser

Chrome

### Organization

SAP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by IlianaB** [comment]
Hello @ui5-webcomponents-topic-rl , please have a look at this issue. It seems it is not possible to control the ui5-input by setting the value property inside the input event, while native input supports such behavior.

Regards,
Iliana

**Comment by aviral49** [comment]
Hi @IlianaB, did we make any progress on the bug ?
It is blocking our migration to ui5wcr for one of the services in SAP Analytics Cloud.
Could it be picked on priority ?

Thanks,
Aviral

**Comment by MapTo0** [comment]
Hello @aviral49 

Since react has some special handling for `input` tags explicitly we would need some more time to process that issue.

Best Regards,
Martin
