### ISSUE TITLE
[Popover | UDEx | 1.24.9]: Popover Arrow is misplaced when Box next to top/bottom

### ISSUE THREAD

**Issue by calmon** [SAP/ui5-webcomponents#9886]
### Bug Description

Popover Component Arrow is missplaced as soon as the box doesn't have enough space. 

### Affected Component

Popover

### Expected Behaviour

Expect: The Arrow is alligned to the mid of the button
Instead it's either bottom or top (depending the popup box is close to top/bottom), see screenshot

### Steps to Reproduce

1. Check out: https://sap.github.io/ui5-webcomponents/v1/components/Popover/
2. Give the button (id="btn") some margin-top: 50px
3. click the button

Expect: The Arrow is alligned to the mid of the button
Instead it's either bottom or top (depending the popup box is close to top/bottom), see screenshot

### Log Output, Stack Trace or Screenshots

![image](https://github.com/user-attachments/assets/a812c3ab-ab23-47a2-ba81-c33e0539ef57)

### Priority

None

### UI5 Web Components Version

1.24.9 but it's also in 2.2.0

### Browser

Chrome

### Operating System

MacOS

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by IlianaB** [comment]
Hello @ui5-webcomponents-topic-rd, please have a look at this issue. It seems the Popover arrow is misplaced, when you add to its opener margin-top or margin-bottom, which move it to close to the top/bottom of the container (as reported). For me, the arrow seems misplaced (not at the center) even without additional margins.

Regards,
Iliana

**Comment by PlutaKatarzyna** [comment]
@IlianaB @kskondov @petyabegovska this was done a while ago, but it was not downported into 1.24. Can it be downported or is this fix going to be available on 2.x version only?

**Comment by petyabegovska** [comment]
Hi @PlutaKatarzyna,

@kskondov will do the downport in the next days.

Best regards,
Petya
