### ISSUE TITLE
Slider is missing icon

### ISSUE THREAD

**Issue by brandon-sap** [SAP/ui5-webcomponents#9887]
### Bug Description

The slider component is showing a blank icon. There's a warning in the console:

Icon.ts:268 Icon name property is required 
<ui5-icon mode="Decorative" "direction-arrows"="" part="icon-slider" slider-icon="" ui5-icon="" design="Default" desktop=""></ui5-icon>

This happens in the documentation for the Slider component, too. Here's a link to the documentation that shows the bug:
https://sap.github.io/ui5-webcomponents/components/Slider/#basic-sample

Looking at the HTML for the icon (conveniently provided in the console warning) shows that maybe the name attribute got a little messed up, since there's an attribute "direction-arrows", when I think it should be name="direction-arrows".

### Affected Component

Slider

### Expected Behaviour

No warning in the console, the icon should show up on the handle like it does on the RangeSlider component.

### Isolated Example

https://sap.github.io/ui5-webcomponents/components/Slider/#basic-sample

### Steps to Reproduce

1. Open the documentation link
2. Observe a blank handle in the basic slider example

### Log Output, Stack Trace or Screenshots

Icon.ts:268 Icon name property is required 
<ui5-icon mode="Decorative" "direction-arrows"="" part="icon-slider" slider-icon="" ui5-icon="" design="Default" desktop=""></ui5-icon>

![{58D0FA7B-0B54-4086-9D34-7EE9C5F2B4DA}](https://github.com/user-attachments/assets/4cb8aad2-8950-44e6-88b5-30602a358db7)

![{53D4A62F-CF6C-490A-A5CD-E2D743DBA780}](https://github.com/user-attachments/assets/406a141d-66b9-4975-8927-32004607a59f)

### Priority

Low

### UI5 Web Components Version

2.2.0

### Browser

Chrome

### Operating System

Windows 11

### Organization

SAP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by nnaydenow** [comment]
Hello @sap/webcomponents-topic-rl,

Could you please check this issue?

As I saw the name attribute was removed with https://github.com/SAP/ui5-webcomponents/pull/9649/files#diff-99805288e28007558cae7e7369f03686d0c37f7d196b3b6115c03771c541cbdcR35 and only its value was left.

Regards,
Nayden
