### ISSUE TITLE
[Form]: Unable to use requestSubmit in v2

### ISSUE THREAD

**Issue by Nemin32** [SAP/ui5-webcomponents#9891]
### Describe the bug

Hello,

We've been using UI5 v1 in our project and have relied on the UI5 Form component acting as an actual HTML `<form>` component, which may be submitted using the `requestSubmit` method called on the form's ref. However, during our migration to v2, we experienced unusual fatal errors which we tracked down to `requestSubmit` being `undefined`.

From what we could find, the new `ui5-form` element doesn't support submitting with either the `requestSubmit` method, a `Button` component set to `type="Submit"`, or by calling `dispatchEvent`. Instead it relies on a call to `_internals.form.requestSubmit()` (see [here](https://github.com/SAP/ui5-webcomponents/blob/main/packages/base/src/features/InputElementsFormSupport.ts)) which also doesn't work, because the `_internals.form` elem remains `null`. This is also a problem, because we rely on React Hook Form, which needs a proper form to work.

This is currently blocking us from finishing the upgrade. The migration docs mention the Form element being a drop-in replacement to the v1 variant, so I would kindly ask for your help how to make the new component work with our workflow.

Thank you for your assistance.

### Reproduction steps

1. Navigate to [this example page](https://sap.github.io/ui5-webcomponents-react/v2/?path=/docs/knowledge-base-form-handling--docs)
2. Fill out the form
3. Click submit
4. Nothing happens.

### Expected Behaviour

The contents of the form are alerted out to the user, due to the `onSubmit` event firing.

### UI5 Web Components for React Version

2.1.0

### UI5 Web Components Version

2.2.0

### Browser

Firefox

### Operating System

MacOSX 15

### Organization

SAP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by IlianaB** [comment]
Hello @SAP/ui5-webcomponents-topic-core , please check out this issue about requestSubmit method not being supported for ui5-form.

Regards,
Iliana

**Comment by Nemin32** [comment]
Hi, thank you for the quick reply! @Lukas742 your workaround works great, we're able to proceed.

**Comment by nnaydenow** [comment]
Hi @Nemin32,

as @Lukas742 said the `ui5-form` component doesn't come with build in form html element inside it. It is used as layout component that arranges labels and form fields (like input fields) pairs into a specific number of columns.

Everyone is using forms in its own way so we left this to be handled separately with the solution that Lukas provided.

We will revise the description of the component to give more clear statement about this. 

Thanks!

Regards,
Nayden

**Comment by ilhan007** [comment]
Hi @Nemin32, @Lukas742 

The Form web component is a layout, it isn't a replacement for the form HTML element. The Form web component does not provide any APIs for form submission and this is now stated explicitly. 

What Lukas suggested above is the way to go.
