### ISSUE TITLE
[Button | React | 1.20.0 | icons | theming | localization | i18n | typescript]: Buttons_No Visible focus

### ISSUE THREAD

**Issue by durgaprasad1995** [SAP/ui5-webcomponents#9894]
### Bug Description

When we are using this theme **Quartz-light(sap_fiori_3)** the button visible focus is not clear when compare the other's

Visible focus indicator is not clearly visible for all emphasized buttons.

![image](https://github.com/user-attachments/assets/1a6a5c97-c855-4d49-83b2-5d044185b76c)

**Expected behavior**
Strong and clear visible focus should be provided for all the UI elements.

Plug and play here (https://sap.github.io/ui5-webcomponents-react/v2/?path=/docs/inputs-button--docs&globals=theme:sap_fiori_3)

### Affected Component

Button

### Expected Behaviour

Strong and clear visible focus should be provided for all the UI elements.

### Isolated Example

https://sap.github.io/ui5-webcomponents-react/v2/?path=/docs/inputs-button--docs&globals=theme:sap_fiori_3

### Steps to Reproduce

1.Go to https://sap.github.io/ui5-webcomponents-react/v2/?path=/docs/inputs-button--docs&globals=theme:sap_fiori_3
2. select the theme Quartz-light
3. select the button design Emphasized
4. then click on tab on the button(example) check the focus 
...

### Priority

High

### UI5 Web Components Version

1.20.0

### Browser

Chrome

### Operating System

windows

### Organization

SAP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by IlianaB** [comment]
Hello @durgaprasad1995 , 
could you please share some information, what do you mean by "compared to the others"? Focus of the Emphasized button with Quartz Light theme is implemented according to the specification - 0.0625rem dotted #fff color.

Regards,
Iliana

**Comment by IlianaB** [comment]
Hello @SAP/ui5-webcomponents-topic-b , you need to zoom too see actually there is a solid black border, set with styles:
:host([design="Emphasized"][desktop]) .ui5-button-root:focus-within::before, :host([design="Emphasized"]
That makes the focus not so clearly visible.

Regards,
Iliana

**Comment by durgaprasad1995** [comment]
> Hello @durgaprasad1995 , could you please share some information, what do you mean by "compared to the others"? Focus of the Emphasized button with Quartz Light theme is implemented according to the specification - 0.0625rem dotted #fff color.
> 
> Regards, Iliana

When compare to Other Theme for this theme (Quartz Light) focus is not very clear 

In our application looks like this 
![image](https://github.com/user-attachments/assets/85b0457a-04c0-44d8-811d-e00ff05169c8)

**Comment by IlianaB** [comment]
Hello @durgaprasad1995 ,
 thank you for sharing this with us! It wasn't very clear to me without zoom, but then I saw it. I believe the solid black border, seen through the dotted white one, should not be there. And because of it, the focus outline looks a little bit blurred.

Regards,
Iliana

**Comment by durgaprasad1995** [comment]
Hi @IlianaB any update on this

**Comment by DMihaylova** [comment]
Hi @durgaprasad1995,

Thank you for your patience!
We're checking it and syncs with designers are taking place.
We'll update you soon.

Regards,
Diana
