### ISSUE TITLE
[Button | Belize]: Button focus border color is different compared to previous versions

### ISSUE THREAD

**Issue by shubhamnazare** [SAP/ui5-webcomponents#9900]
### Bug Description

Button focus outline is different compared to previous version of UI5WC.

UI5WC 1.14.0 version has white line
![image](https://github.com/user-attachments/assets/b2aadbfb-0e22-44f5-a9dc-53ed0770673f)

After upgrading to UI5WC 1.24.8 version, it has black line

### Isolated Example

https://stackblitz.com/edit/github-jz3rcw?file=index.html

### Steps to Reproduce

1.
2.
3.
...

### Priority

None

### UI5 Web Components Version

1.24.8

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by IlianaB** [comment]
Hello @shubhamnazare ,
I have just checked the Visual Specification for the Emphasized button on Belize theme and it should indeed have a black dotted border. Seems like it was correctly aligned with the spec now.

Regards,
Iliana

**Comment by shubhamnazare** [comment]
Hi @IlianaB 
Could you please share the specification?

**Comment by IlianaB** [comment]
Hello @shubhamnazare ,
Unfortunately, there is no public visual spec. You can contact me internally.
As a reference you can see how OPENUI5 Button is implemented: https://ui5.sap.com//#/entity/sap.m.Button/sample/sap.m.sample.Button (change theme with Settings button above the Sample. You can also edit the Sample to have a Button with type="Emphasized").

Regards,
Iliana
