### ISSUE TITLE
Select close event handled in popover

### ISSUE THREAD

**Issue by brandon-sap** [SAP/ui5-webcomponents#9909]
### Bug Description

This one is a bit...intense. My apologies upfront.

Short description:
---
A select component inside of a popover will call that popover's close listener when it closes.

Longer description:
---
A select component has its own popover. So when a select is inside of a popover (or a dialog) and that select's popover closes, which fires a close event. The select's close event listener handles that event, along with the close event listener on the popover that was outside of the select. So there are 2 popovers. If both have event listeners on the close event, both of those listeners get called, even though the outer popover hasn't closed.

Sorry, I'm not sure there's a way to be concise with this one. It's pretty specific.

### Affected Component

Select

### Expected Behaviour

When a select component closes (say a user chooses one of the options, or presses esc and doesn't choose an option) the select's popover disappears and the close listener is called with the close event. A popover that contains that select shouldn't have its close handler called (it wasn't closed).

### Isolated Example

[Playground Example](https://sap.github.io/ui5-webcomponents/play/#eyJpbmRleC5odG1sIjp7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuPCFET0NUWVBFIGh0bWw-XG48aHRtbCBsYW5nPVwiZW5cIj5cblxuXG5cblxuPGhlYWQ-XG4gICAgXG4gICAgPHN0eWxlPlxuICAgICAgKjpub3QoOmRlZmluZWQpIHtcbiAgICAgICAgZGlzcGxheTogbm9uZTtcbiAgICAgIH1cbiAgICA8L3N0eWxlPlxuXG4gICAgXG4gICAgPHN0eWxlPlxuICAgICAgKjpub3QoOmRlZmluZWQpIHtcbiAgICAgICAgZGlzcGxheTogbm9uZTtcbiAgICAgIH1cbiAgICA8L3N0eWxlPlxuXG4gICAgXG4gICAgPHN0eWxlPlxuICAgICAgKjpub3QoOmRlZmluZWQpIHtcbiAgICAgICAgZGlzcGxheTogbm9uZTtcbiAgICAgIH1cbiAgICA8L3N0eWxlPlxuXG4gICAgXG4gICAgPHN0eWxlPlxuICAgICAgKjpub3QoOmRlZmluZWQpIHtcbiAgICAgICAgZGlzcGxheTogbm9uZTtcbiAgICAgIH1cbiAgICA8L3N0eWxlPlxuXG4gICAgPG1ldGEgY2hhcnNldD1cIlVURi04XCI-XG4gICAgPG1ldGEgbmFtZT1cInZpZXdwb3J0XCIgY29udGVudD1cIndpZHRoPWRldmljZS13aWR0aCwgaW5pdGlhbC1zY2FsZT0xLjBcIj5cbiAgICA8dGl0bGU-U2FtcGxlPC90aXRsZT5cbjwvaGVhZD5cbjxib2R5IHN0eWxlPVwiYmFja2dyb3VuZC1jb2xvcjogdmFyKC0tc2FwQmFja2dyb3VuZENvbG9yKTsgaGVpZ2h0OiAyNTBweFwiPlxuPCEtLSBwbGF5Z3JvdW5kLWZvbGQtZW5kIC0tPlxuXG5cbiAgPHVpNS1idXR0b24gaWQ9XCJidG4xXCI-YnRuMTwvdWk1LWJ1dHRvbj5cbiAgPHVpNS1wb3BvdmVyIGlkPVwicG9wMVwiIG9wZW5lcj1cImJ0bjFcIiBoZWFkZXItdGV4dD1cInBvcDFcIj5cbiAgICA8dWk1LXNlbGVjdCBpZD1cInNlbGVjdFwiPlxuICAgICAgICA8dWk1LW9wdGlvbiBpY29uPVwibGFwdG9wXCI-RGVza3RvcDwvdWk1LW9wdGlvbj5cbiAgICAgICAgPHVpNS1vcHRpb24gaWNvbj1cImlwYWRcIiBzZWxlY3RlZD5UYWJsZXQ8L3VpNS1vcHRpb24-XG4gICAgICAgIDx1aTUtb3B0aW9uIGljb249XCJpcGhvbmVcIj5QaG9uZTwvdWk1LW9wdGlvbj5cbiAgICA8L3VpNS1zZWxlY3Q-XG4gICAgPHVpNS1idXR0b24gaWQ9XCJidG4yXCI-YnRuMjwvdWk1LWJ1dHRvbj5cbiAgICA8dWk1LXBvcG92ZXIgaWQ9XCJwb3AyXCIgb3BlbmVyPVwiYnRuMlwiIGhlYWRlci10ZXh0PVwicG9wMlwiPlxuICAgICAgV2lsbCBJIGdlbmVyYXRlIGEgY2xvc2UgZXZlbnQgb24gcG9wMT9cbiAgICA8L3VpNS1wb3BvdmVyPlxuICA8L3VpNS1wb3BvdmVyPlxuXG48IS0tIHBsYXlncm91bmQtZm9sZCAtLT5cbiAgICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCJtYWluLmpzXCI-PC9zY3JpcHQ-XG48L2JvZHk-XG48L2h0bWw-XG48IS0tIHBsYXlncm91bmQtZm9sZC1lbmQgLS0-XG5cbiJ9LCJtYWluLmpzIjp7Im5hbWUiOiJtYWluLmpzIiwiY29udGVudCI6Ii8qIHBsYXlncm91bmQtaGlkZSAqL1xuaW1wb3J0IFwiLi9wbGF5Z3JvdW5kLXN1cHBvcnQuanNcIjtcbi8qIHBsYXlncm91bmQtaGlkZS1lbmQgKi9cbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L1NlbGVjdC5qc1wiO1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzL2Rpc3QvT3B0aW9uLmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMvZGlzdC9Qb3BvdmVyLmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMtaWNvbnMvZGlzdC9pcGFkLmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMtaWNvbnMvZGlzdC9pcGhvbmUuanNcIjtcbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy1pY29ucy9kaXN0L2xhcHRvcC5qc1wiO1xuXG5jb25zdCBidG4xID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoXCJidG4xXCIpO1xuY29uc3QgcG9wMSA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKFwicG9wMVwiKTtcbmNvbnN0IGJ0bjIgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZChcImJ0bjJcIik7XG5jb25zdCBwb3AyID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoXCJwb3AyXCIpO1xuY29uc3Qgc2VsZWN0ID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoXCJzZWxlY3RcIik7XG5cbnNlbGVjdC5hZGRFdmVudExpc3RlbmVyKFwiY2hhbmdlXCIsIChlKSA9PiB7XG4gIGNvbnNvbGUubG9nKFwiaXRlbSBzZWxlY3RlZFwiLCBlKTtcbn0pO1xuc2VsZWN0LmFkZEV2ZW50TGlzdGVuZXIoXCJjbG9zZVwiLCAoZSkgPT4ge1xuICBjb25zb2xlLmxvZyhcImNsb3NlIGV2ZW50IG9uIHNlbGVjdFwiLCBlKTtcbn0pO1xuXG5idG4xLmFkZEV2ZW50TGlzdGVuZXIoXCJjbGlja1wiLCAoKSA9PiB7XG5cdHBvcDEub3BlbiA9ICFwb3AxLm9wZW47XG59KTtcbmJ0bjIuYWRkRXZlbnRMaXN0ZW5lcihcImNsaWNrXCIsICgpID0-IHtcblx0cG9wMi5vcGVuID0gIXBvcDIub3Blbjtcbn0pO1xuXG5wb3AxLmFkZEV2ZW50TGlzdGVuZXIoXCJjbG9zZVwiLCAoZSkgPT4ge1xuICBjb25zb2xlLmxvZyhcImNsb3NlIGV2ZW50IG9uIHBvcDFcIiwgZS50YXJnZXQgPT09IGUuY3VycmVudFRhcmdldCk7XG59KTtcbnBvcDIuYWRkRXZlbnRMaXN0ZW5lcihcImNsb3NlXCIsIChlKSA9PiB7XG4gIGNvbnNvbGUubG9nKFwiY2xvc2UgZXZlbnQgb24gcG9wMlwiLCBlLnRhcmdldCA9PT0gZS5jdXJyZW50VGFyZ2V0KTtcbn0pO1xuIn19)

### Steps to Reproduce

1. Go to playground example above.
2. Open dev console.
3. The example has a button, btn1. Click it.
4. A popover appears (pop1) that contains a select and another button, btn2. Click btn2.
5. Another popover appears (pop2). Click back inside pop1. This will close pop2.
6. Observe an entry in the dev console: "close event on pop2 true" This is the counter example. The popover closes, calls its own close listener. This is the expected behavior for the select.
7. Click on the select. Its popover appears. Press the Esc key. This will close the select popover.
8. Observe 2 entries in the dev console: "close event on select <CustomEvent data>" and "close event on pop1 false"
9. Click outside of pop1 to make it close.
10. Observe an entry in the dev console: "close event on pop1 true"

Step 8 is where the problem is portrayed. The close handler for the select is the only one that should have fired. Instead, the close handler for pop1 was also fired, even though it didn't close.

Note: the true/false on the pop1 and pop2 close handlers is the way I've seen to be able to tell if the popover is actually the one being closed. Luckily, it seems to work. Otherwise, I'd still be looking for a workaround...

### Log Output, Stack Trace or Screenshots

From the Playground Example:
![image](https://github.com/user-attachments/assets/b3372df0-e94a-4236-9079-4af0b84d8db2)
![{2E57DDB1-65CE-4052-AFEF-8C0FFA8920BC}](https://github.com/user-attachments/assets/04ea3f63-b6d0-4b78-9614-f9fabebacb71)

### Priority

Low

### UI5 Web Components Version

2.2.0

### Browser

Chrome

### Operating System

Windows 11

### Organization

SAP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by IlianaB** [comment]
Hello @ui5-webcomponents-topic-rd , please have a look at this issue. It seems Popup fires close event , although the Popup is actually not closed. 

Regards,
Iliana

**Comment by brandon-sap** [comment]
I realized that I didn't specify it very well, that dialogs and popups both do this. In my application where I first saw this, it was actually a dialog with a select in it. I reproduced it with a popover, but both dialogs and popovers do this.

**Comment by kskondov** [comment]
Hello @SAP/ui5-webcomponents-topic-p, seems like the select fires a close event that should not bubble can you please take a look

**Comment by ilhan007** [comment]
Hi colleagues, @NakataCode 

The issue will be covered with this change https://github.com/SAP/ui5-webcomponents/pull/9944. It still in progress but close to finalising.
