### ISSUE TITLE
[ui5-notification-lit-group-item]: group header height should be shorter

### ISSUE THREAD

**Issue by LidiyaGeorgieva** [SAP/ui5-webcomponents#9911]
### Bug Description

group header should be shorter
![{C8787CDE-0F95-4ECA-AECA-2499530E2693}](https://github.com/user-attachments/assets/a10d5e74-fe00-4306-89fc-bd2d853ddc4b)

### Steps to Reproduce

1. open https://sap.github.io/ui5-webcomponents/nightly/components/fiori/NotificationList/#notification-list-with-group-items
2. collapse all groups
3. they don't look OK

### Priority

Low

### UI5 Web Components Version

main

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by IlianaB** [comment]
Hello @SAP/ui5-webcomponents-topic-rd  , please have a look at this issue. According to the VD spec, the height of the group header of notification list group should be 2.75rem.

Regards,
Iliana
