### ISSUE TITLE
ToggleButton toggle state visually conflicts with button focus in Horizon theme

### ISSUE THREAD

**Issue by brandon-sap** [SAP/ui5-webcomponents#9918]
### Bug Description

I'm sure the focus is done to spec. So maybe this can be filed against the spec?

A toggle button looks toggled when it isn't when it has focus. This can be very confusing to a user, especially if the user isn't completely familiar with horizon theme's focus.

The focus can also make a regular button look toggled.

### Affected Component

ToggleButton

### Expected Behaviour

When a button has focus, that it doesn't look toggled.

Or for the focus to not be so overpowering that it makes the toggled state unclear. See screenshots below.

### Isolated Example

https://sap.github.io/ui5-webcomponents/components/ToggleButton/#basic-sample

### Steps to Reproduce

1. Go to the documentation page for Button or ToggleButton (I provided the link for ToggleButton)
2. In Horizon theme, click a toggle button. It receives focus, which is a thick line around the inside border of the button. It's also now toggled, which is a faint change of the background color.
3. Click the toggle button again. It keeps focus, so the thick border remains, and the toggle state goes away, so the background is slightly changed back to non-toggled color.

For Buttons, do the same thing, except that there's no toggle state, but it looks like there's a toggle state due to the thick focus border. This is incredibly confusing, because you can't untoggle the button. It appears sticky and broken.

### Log Output, Stack Trace or Screenshots

Starting state, no focus, no toggle:
![image](https://github.com/user-attachments/assets/f5fdb351-0fd5-412e-a8a6-b0077a4976d4)

After first click, toggled and focused:
![{1D585235-B8F3-4D2D-A04F-AC43568DA612}](https://github.com/user-attachments/assets/596cfca0-5e4b-44fa-8789-db4485a50fb6)

After second click, no toggle, still focused:
![{8556566F-5B58-4BFF-B5D5-DFC6DB0A208E}](https://github.com/user-attachments/assets/53f457da-3f68-49cc-a890-e710f8653736)

This is the toggle state without focus:
![{6B52817F-86BD-4039-AF6A-C14CBB0B2633}](https://github.com/user-attachments/assets/afb3f24b-5204-49ce-8c0c-0f7c882e8d64)

### Priority

Low

### UI5 Web Components Version

2.2.0

### Browser

Chrome

### Operating System

Windows 11

### Additional Context

Ever since our switch to default Horizon, with each upgrade of this ui5 library in my project, this has been brought up as a bug to me in my project.

I've done nothing about it since I think it is for accessibility. But I'm finally creating this to bring it up. If we could get a feature, perhaps, to lessen the focus so it's not so overwhelming, that would be great. If this is part of the spec, then my question is: can I file this bug against the spec instead of here?

The application this is coming from is for content generation and its main feature is drag and drop. Keyboard navigation is useless in this scenario. So some accessibility features don't apply very well.

That said, I think that the visual conflict between button toggle state and focus is pretty clear. If you look at the screenshots, the last one is easily seen as a toggled button, and the first is easily not toggled. The middle two, however...well, it's simple to see that the focus is more prominent than the visual toggled state. Especially with the consideration of accessibility, which is what I think the dense focus is for, the focus clobbers the toggle button state. I can see it, but I can also see the default focus on buttons in normal HTML, too. If someone can't see that, and needs the heavy focus of horizon, then they are unlikely to be able to see the toggle state of the button under the thick focus line.

Hopefully that makes sense. That's why I think this case is important and a bug in the spec. The spec _defeats itself_ in this scenario. With so much focus on this accessibility, the spec has actually **harmed** accessibility, in this scenario.

### Organization

SAP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Valkanister** [comment]
Hello @SAP/ui5-webcomponents-topic-b, 
Please have a look at this requirement to better distinguish between Buttons and ToggleButtons in horizon. 

Kind regards

**Comment by DMihaylova** [comment]
Hi @brandon-sap,

Thank you for the feedback! I shared it to our design colleagues and here's what they explained to me:

"To fulfill the WCAG 2.2 standards for the focus, different criterias were considered for the final visual focus decision. The focus visualization needs to be consistent over all components, and this was a requirement from accessibility product standards. 
While defining the buttons visual design for Horizon, the team decided for the light blue background on the toggle button for better distinction between regular and toggle button, within their interactive states and with and without the focus. We also considered the interacted context and content environment of the toggle button, so the decision was deeply thought out."

In case you have objections, I see that you're internal so you could open a JIRA item as per the InnerSource process to our design colleagues :)

Regards,
Diana
