### ISSUE TITLE
[DocSite]: v1 documentation is not working

### ISSUE THREAD

**Issue by beejei** [SAP/ui5-webcomponents#9919]
### Bug Description

https://sap.github.io/ui5-webcomponents/v1/
is showing error page

### Steps to Reproduce

1. Open https://sap.github.io/ui5-webcomponents/v1/

### Priority

High

### UI5 Web Components Version

V1.x

### Browser

Edge

### Operating System

MacOS

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by nnaydenow** [comment]
Hi @beejei,

Thank you for the report! The playground is redeployed and now it's available.

Regards,
Nayden

**Comment by beejei** [comment]
@nnaydenow Thanks for your quick action!
