### ISSUE TITLE
[@ui5/webcomponents/Inputt]: error thrown when using number type input

### ISSUE THREAD

**Issue by malonmiming** [SAP/ui5-webcomponents#9921]
### Bug Description

[Issue 1]
When using focus input in number-type Input, an error is thrown:

`TypeError: Cannot read properties of undefined (reading 'inputType')
    at Input._handleInput (Input.js:581:25)
    at z.handleEvent (lit-html.js:6:7169)`

[Issue 2]
The English letter "e" can be entered in the input type number.

### Steps to Reproduce

1. <ui5-input value="Input" type="Number"></ui5-input>
2. focus input
3. see error in console
...
``

### Log Output, Stack Trace or Screenshots

TypeError: Cannot read properties of undefined (reading 'inputType')
    at Input._handleInput (Input.js:581:25)
    at z.handleEvent (lit-html.js:6:7169)

### Priority

None

### UI5 Web Components Version

 "@ui5/webcomponents": "^2.1.1",     "@ui5/webcomponents-fiori": "^2.1.1",

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by nnaydenow** [comment]
Hi @malonmiming,

I think that https://github.com/SAP/ui5-webcomponents/pull/9616 is fixing similar issue https://github.com/SAP/ui5-webcomponents/issues/9588. Could you please try to update application to version 2.2.0 or to check if the issue is reproducible in: https://sap.github.io/ui5-webcomponents/

Regards,
Nayden

**Comment by malonmiming** [comment]
HI @nnaydenow,

Thank you for your response!!!
I update application to version 2.2.0. and then the [Issue 1] was resolved, but the [issue 2] was not resolved.

Best Regards,
malonmiming

**Comment by nnaydenow** [comment]
Hi @malonmiming,

`e` is special symbol for input of type number with the idea to support numbers that contain epsilon symbol. Same symbol is supported in native input. There is restriction that the input might contain only 1 `e` symbol.

You can check following [example](https://sap.github.io/ui5-webcomponents/nightly/play/#eyJpbmRleC5odG1sIjp7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuPCFET0NUWVBFIGh0bWw-XG48aHRtbCBsYW5nPVwiZW5cIj5cblxuXG5cbjxoZWFkPlxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG4gICAgPC9zdHlsZT5cblxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG4gICAgPC9zdHlsZT5cblxuICAgIDxtZXRhIGNoYXJzZXQ9XCJVVEYtOFwiPlxuICAgIDxtZXRhIG5hbWU9XCJ2aWV3cG9ydFwiIGNvbnRlbnQ9XCJ3aWR0aD1kZXZpY2Utd2lkdGgsIGluaXRpYWwtc2NhbGU9MS4wXCI-XG4gICAgPHRpdGxlPlNhbXBsZTwvdGl0bGU-XG48L2hlYWQ-XG5cbjxib2R5IHN0eWxlPVwiYmFja2dyb3VuZC1jb2xvcjogdmFyKC0tc2FwQmFja2dyb3VuZENvbG9yKVwiPlxuICAgIDwhLS0gcGxheWdyb3VuZC1mb2xkLWVuZCAtLT5cblxuICAgIDx1aTUtaW5wdXQgdmFsdWU9XCIyLjIyMDQ0NjA0OTI1MDMxM2UtMTZcIiB0eXBlPVwiTnVtYmVyXCI-PC91aTUtaW5wdXQ-XG4gICAgPGlucHV0IHZhbHVlPVwiMi4yMjA0NDYwNDkyNTAzMTNlLTE2XCIgdHlwZT1cIm51bWJlclwiIC8-XG4gICAgPCEtLSBwbGF5Z3JvdW5kLWZvbGQgLS0-XG4gICAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwibWFpbi5qc1wiPjwvc2NyaXB0PlxuPC9ib2R5PlxuXG48L2h0bWw-XG48IS0tIHBsYXlncm91bmQtZm9sZC1lbmQgLS0-XG4ifSwibWFpbi5qcyI6eyJuYW1lIjoibWFpbi5qcyIsImNvbnRlbnQiOiIvKiBwbGF5Z3JvdW5kLWhpZGUgKi9cbmltcG9ydCBcIi4vcGxheWdyb3VuZC1zdXBwb3J0LmpzXCI7XG4vKiBwbGF5Z3JvdW5kLWhpZGUtZW5kICovXG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMvZGlzdC9JbnB1dC5qc1wiOyJ9fQ)
