### ISSUE TITLE
[Popover | 2.x]: get/set incompatible according to TS2380 reported by vite

### ISSUE THREAD

**Issue by gitgdako** [SAP/ui5-webcomponents#9927]
### Bug Description

webcomponents: 2.x
https://github.com/SAP/ui5-webcomponents/blob/main/packages/main/src/Popover.ts : 229
deployed to @ui5/webcomponents/dist/Popover.d.ts : 156

get opener has Retruntype undefined which set opener does not

```
set opener(value: HTMLElement | string)
...

get opener(): HTMLElement | string | undefined 
...
```

Vite (4.5.2) reports 
``` 
node_modules/@ui5/webcomponents/dist/Popover.d.ts:156:9 - error TS2380: The return type of a 'get' accessor must be assignable to its 'set' accessor type
  Type 'undefined' is not assignable to type 'string | HTMLElement'.

156     get opener(): HTMLElement | string | undefined;
            ~~~~~~
```

### Affected Component

Webcomponents 2.x

### Expected Behaviour

Building the dependency does not report given error

### Steps to Reproduce

1. webcomponents 2.x dependency
2. vite build

### Priority

Medium

### UI5 Web Components Version

2.x

### Browser

Chrome, Edge, Firefox, Safari

### Operating System

Windows 11

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by nnaydenow** [comment]
Hi @gitgdako,

I think that this is expected because opener might not be set. Could you share more details about your setup so we can observe the error since with our setup it's not reproducible.

Regards,
Nayden

**Comment by pskelin** [comment]
@gitgdako can you check your typescript version with `tsc -v` ? I was accidentally on a branch with TS 4.9 and got the same error. We have TS 5.2 in the project however, and it doesn't give the error.

Also in case you have a ^4.x for typescript in your package.json dependencies, could you please update it to ^5.x ? npm considers this a major release and won't update it, but typescript treats each .x version as a major release so an upgrade from 4.9 to 5.0 is ok.

**Comment by gitgdako** [comment]
Upgrading to TS 5.2 (from 4.9) solved the build error. Thank you for the support
