### ISSUE TITLE
[ObjectPage | React | localization | i18n | typescript]: Tab _Focus not following the command

### ISSUE THREAD

**Issue by durgaprasad1995** [SAP/ui5-webcomponents#9940]
### Bug Description

Tab focus is not switching to another tab on Scroll or Tab Select.
 

Expected Behavior:

The focused UI should looks like selected when keyboard focus is on 'Global ' tab.

![image](https://github.com/user-attachments/assets/fbd554af-9be8-4b98-a7ca-ee2853522539)

plug and play here https://sap.github.io/ui5-webcomponents-react/v1/?path=/docs/layouts-floorplans-objectpage--docs

our Project Screenshot
![image](https://github.com/user-attachments/assets/00862232-326f-4ca6-9d2b-99189575114f)

![image](https://github.com/user-attachments/assets/e613b6e8-5486-47fd-a189-0fc263184d67)

in the screenshot, if you see there is less space for contracts when I select contracts it's highlighting the qualification

### Expected Behaviour

The focused UI should looks like selected when keyboard focus is on 'Global ' tab.

### Steps to Reproduce

1.Go to this page  https://sap.github.io/ui5-webcomponents-react/v1/?path=/docs/layouts-floorplans-objectpage--docs
2.check any example select first tab then scroll slowly it should 
3.focus will stay on the first tab only 
...

### Priority

Medium

### UI5 Web Components Version

1.20.0

### Browser

Chrome

### Operating System

Windows

### Organization

SAP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Valkanister** [comment]
Hello @durgaprasad1995, 

Our target design does not move the focus on scrolling. What is changed is only the selection (i.e. the underline of the Anchor). 

Kind regards
