### ISSUE TITLE
[FileUploader]: [Cannot fire OnChange when reselect same file after resetting fileUploaderRef.current.value ]

### ISSUE THREAD

**Issue by kushalkaranjkar** [SAP/ui5-webcomponents#9947]
### Describe the bug

We have file uploader which is inside the dialog and has ref pass to it. 
If you select a file and then use FileUploaderRef to reset the value of FileUploader. And Then Again try to select same file, It won't fire fileUploader OnChange event ? 
e.g. fileUploaderRef.current.value = "abc.txt"
We have 'cancel' button on Dialog, and we are trying to reset value of fileUploader if user hit cancel. which is working as expected. But once cancel, if user reselect same file , onchange event won't fire and we cannot select same file.

Code Example: 

const skillsFileName = "abc.docx". 
 <FileUploader
              ref={fileUploaderRef}
              data-testid="resumeFileUploader"
              accept=".doc,.docx,.pdf,.txt,.rtf"
              onChange={onFileChange}
              disabled={busy}
              value={skillsFileName ? `"${skillsFileName}"` : ""}
            >
              <Button >BROWSE</Button>
   </FileUploader>

### Reproduction steps

1. Create FileUploader using following snippet
const skillsFileName = "abc.docx". 
 <FileUploader
              ref={fileUploaderRef}
              data-testid="resumeFileUploader"
              accept=".doc,.docx,.pdf,.txt,.rtf"
              onChange={onFileChange}
              disabled={busy}
              value={skillsFileName ? `"${skillsFileName}"` : ""}
            >
              <Button >BROWSE</Button>
   </FileUploader>
2. Upload a file -  e.g."abc.txt"
3. Upload another file  - "new_abc.txt"
4. reset fileUploader value using - fileUploaderRef.current.value = "abc.txt"
5. Again, try to upload previous file - "new_abc.txt" 

Issue == File Uploader onChange event don't get fire ? 
...

### Expected Behaviour

Even after fileUploaderRef.current.value is reset, previous file to upload should be allowed .

### Screenshots or Videos

https://github.com/user-attachments/assets/bca0c536-15c9-47c7-aa05-94a630d940ad

### UI5 Web Components for React Version

1.29

### UI5 Web Components Version

1.24

### Browser

Chrome

### Operating System

Mac

### Organization

SAP successfactors

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by LidiyaGeorgieva** [comment]
Hello @SAP/ui5-webcomponents-topic-b,

Please check if this issue is a bug or expected behavior.
It is reproducible on this sample: https://stackblitz.com/edit/github-1eft2j?file=index.html,main.js,package.json
Steps:
1. Upload some file
2. Press "reset" button
3. Try to upload previous file
Issue == File Uploader onChange event don't get fired

Best Regards,
Lidiya

**Comment by unazko** [comment]
Hello @kushalkaranjkar,

If you want to do a proper reset of the file selection you could try this:
https://stackblitz.com/edit/github-1eft2j-x6frby?file=main.js

By changing the `value` of the `ui5-file-uploader` you would only change the value in the input field.
The last selected file is still there:
`document.getElementById('fileUploader').shadowRoot.querySelector("input[type='file']").files`
That will print the `FileList` object which contains the currently selected files.
For that reason no change event gets fired when the same file gets selected again.

This `FileList` object is immutable. You could workaround it via the `DataTransfer` object like shown in the upper example.

Best regards,
Boyan

**Comment by kushalkaranjkar** [comment]
> Hello [@kushalkaranjkar](https://github.com/kushalkaranjkar),
> 
> If you want to do a proper reset of the file selection you could try this: https://stackblitz.com/edit/github-1eft2j-x6frby?file=main.js
> 
> By changing the `value` of the `ui5-file-uploader` you would only change the value in the input field. The last selected file is still there: `document.getElementById('fileUploader').shadowRoot.querySelector("input[type='file']").files` That will print the `FileList` object which contains the currently selected files. For that reason no change event gets fired when the same file gets selected again.
> 
> This `FileList` object is immutable. You could workaround it via the `DataTransfer` object like shown in the upper example.
> 
> Best regards, Boyan

Hi Unazko,
**Can your above solution work in the TypeScript react** ? If yes, can you please update example. 

I tried adding below code - 

   _const fileUploader = document.getElementById('fileUploader') as HTMLInputElement;
        if(fileUploader) {
          fileUploader.value = '';
          if(fileUploader.shadowRoot && fileUploader.shadowRoot?.querySelector("input[type='file']")){
            var fileUploaderInput = fileUploader.shadowRoot.querySelector("input[type='file']");
             fileUploaderInput = new DataTransfer().files;
          }
        }_
     
**But getting Type Error for "FileList" object for "fileUploaderInput".**

**Comment by kushalkaranjkar** [comment]
@unazko ,

I tried with the change but I see that in typescript code this not working. 
Its complaining that FilerUploaderInput in above code dont have 'files' property.

![Image](https://github.com/user-attachments/assets/6331623a-0ea7-47a7-9a01-9e309f8bd8c6)

`   if(fileUploader) {
          fileUploader.value = '';
           if(fileUploader.shadowRoot && fileUploader.shadowRoot?.querySelector("input[type='file']")){
             const fileUploaderInput = fileUploader.shadowRoot.querySelector("input[type='file']");
             if(fileUploaderInput != null) {
               fileUploaderInput.files = new DataTransfer().files;
             }
           }
        }`

**Comment by unazko** [comment]
Hi @kushalkaranjkar,

Your selector doesn't get the input type file field. If you successfully get the the input element there will be `files` property
representing a `FileList`.
