### ISSUE TITLE
[Dialog]: Change combobox selection will crash app

### ISSUE THREAD

**Issue by skowrons** [SAP/ui5-webcomponents#9957]
### Describe the bug

When we use a `ComboBox` inside a `Dialog` component it will crash the app after we change the selection again.

### Isolated Example

https://stackblitz.com/edit/github-fzbkcn?file=src%2FApp.tsx

### Reproduction steps

1. Open Dialog
2. Select something without search
3. Select some other thing
4. App will crash

### Expected Behaviour

App should not crash.

### UI5 Web Components for React Version

2.1.1

### UI5 Web Components Version

2.2.0

### Browser

Chrome

### Operating System

MacOS

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by LidiyaGeorgieva** [comment]
Hello @SAP/ui5-webcomponents-topic-core,

Please advice what could be the issue here?

I tested the following:
- on Firefox there is no crash, only on Chrome (I tested with Windows)
- I tried to isolate it with minimal code in the test page (of the Dialog for example) and its reproducible also there:
```
<ui5-dialog id="dialogForm" header-text="Dialog">
		<ui5-form>
			<ui5-form-item>
			  <ui5-combobox placeholder="Enter value">
				<ui5-cb-item text="Austria"></ui5-cb-item>
				<ui5-cb-item text="Bulgaria"></ui5-cb-item>
				<ui5-cb-item text="Germany"></ui5-cb-item>
			</ui5-combobox>
			</ui5-form-item>
		  </ui5-form>
	</ui5-dialog>
```
- if I delete the ui5-dialog or the ui5-form - the issue is not reproducible. Only this combination  of components cause the crash

Best Regards,
Lidiya

**Comment by skowrons** [comment]
We could reproduce this bug with another component (`DatePicker`) https://github.com/SAP/ui5-webcomponents-react/issues/6523
Maybe the root cause could be the new popover api that is used since v2.

**Comment by nnaydenow** [comment]
Hi @skowrons,

After update of Chrome browser from version 129.0.6668.100 to version 130.0.6723.59 the issue is no longer reproducible to me. Could you please recheck the issue since there is not clear sign for the problem on first issue and it might be a browser problem?

**Comment by skowrons** [comment]
Hi @nnaydenow,

Thank you for testing. We are also unable to reproduce the bug with Chrome version 130.x.x.x. I will proceed to close this issue, along with #10059.

Thanks again to everyone for your efforts and assistance!

**Comment by Saradasilvadev** [comment]
Hello team.

I still have the issue, I can reproduce it from edge Version 130.0.2849.52 from mac

**Comment by skowrons** [comment]
Hi @Saradasilvadev,

I believe the best approach would be to open a new issue detailing your problem—ideally with a StackBlitz example if possible—and reference this ticket for context.
