### ISSUE TITLE
[SF][SelectDialog]: onLoadMore event should not be fired when open the dialog

### ISSUE THREAD

**Issue by i323808** [SAP/ui5-webcomponents#9959]
### Describe the bug

The `onLoadMore` event is fired when open the dialog. It should only be fired when user scroll down the list.

### Isolated Example

https://stackblitz.com/edit/github-facwbh?file=src%2FApp.tsx

### Reproduction steps

1. open [https://stackblitz.com/edit/github-facwbh?file=src%2FApp.tsx](https://stackblitz.com/edit/github-facwbh?file=src%2FApp.tsx)
2. click 'open SelectDialog'
3. onLoadMore event is fired

### Expected Behaviour

The `onLoadMore` event should only be fired when user scroll down the list.

### UI5 Web Components for React Version

2.2.0

### UI5 Web Components Version

2.1.1

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by LidiyaGeorgieva** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

Please have a look. 
This is either a bug or documentation should be enhanced.

Best regards,
Lidiya
