### ISSUE TITLE
[Dynamic page]: Clicking on the 'Expand Header' button doesn't work every time

### ISSUE THREAD

**Issue by petyabegovska** [SAP/ui5-webcomponents#9961]
### Bug Description

Sometimes, when the header of the ui5-dynamic-page component is snapped and you click on the button: "Expand Header", the header doesn't expand. 

### Affected Component

ui5-dynamic-page

### Expected Behaviour

The header should expand every time you click on the button 'Expand Header'.

### Isolated Example

https://sap.github.io/ui5-webcomponents/nightly/components/fiori/DynamicPage/#basic-usage

### Steps to Reproduce

1. Open the sample: https://sap.github.io/ui5-webcomponents/nightly/components/fiori/DynamicPage/#basic-usage in Chrome browser.
2. Scroll the page so the header is snapped.
3. Click on the button "Expand Header" several times.

Note: The issue can be reproduced also with 'Open in playground' of the sample.

### Log Output, Stack Trace or Screenshots

https://github.com/user-attachments/assets/c9582724-7aaa-4503-a90f-39fda55dd61c

### Priority

Medium

### UI5 Web Components Version

Nightly

### Browser

Chrome

### Operating System

MacOS Sonoma

### Organization

SAP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by LidiyaGeorgieva** [comment]
Hello @SAP/ui5-webcomponents-topic-b, 

The issue is reproducible also in Windows. Please have a look.

Best Regards,
Lidiya
