### ISSUE TITLE
[Form]: update to latest UX specs

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents#9963]
### Feature Request Description

The Form spec has been updated with the following:

- Adding an extra third column to the label-input pair, playing an **"empty space"** role - label|input|empty space, for example **4:7:1 split** (currently the label/input parts of Form Item are taking the whole space 4:8 by default).
- The default value for column count in **XL** must be **3 columns** currently (currently it's 2 columns)
- The form **header text** must be **wrapping** (currently truncates)

### Organization

SAP Design

### Priority

Medium

### Privacy Policy

- [x] I’m not disclosing any internal or sensitive information.

**Comment by LidiyaGeorgieva** [comment]
Hello @SAP/ui5-webcomponents-topic-core,

There is a feature request for you.

Best Lidiya
