### ISSUE TITLE
[Feature Request]: ui5-select should support vue js v-model like native select

### ISSUE THREAD

**Issue by pskelin** [SAP/ui5-webcomponents#9971]
### Feature Request Description

with native select, it is possible to use it in vuejs like this:
```vue
<select v-model="select">
  <option value="a">A</option>
  <option value="b">B</option>
  <option value="c">C</option>
</select>
```

ui5-select requires a bit more code
```vue
<ui5-select @change="(e) => select = e.target.value" :value="select">
  <ui5-option value="a">A</ui5-option>
  <ui5-option value="b">B</ui5-option>
  <ui5-option value="c">C</ui5-option>
</ui5-select>
```

### Proposed Solution

If the ui5-select fires an `input` event whenever the `change` event is fired, the vue model binding will work out of the box making such code possible

```vue
<ui5-select v-model="select">
  <ui5-option value="a">A</ui5-option>
  <ui5-option value="b">B</ui5-option>
  <ui5-option value="c">C</ui5-option>
</ui5-select>

```

### Priority

None

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by LidiyaGeorgieva** [comment]
Hello @SAP/ui5-webcomponents-topic-p, take a look of this feature request.
