### ISSUE TITLE
[ui5-upload-collection]: drag and drop overlay is overflowing

### ISSUE THREAD

**Issue by tkeiner** [SAP/ui5-webcomponents#9975]
### Bug Description

If the collection height is small because only one attachment was uploaded, and then a file is dropped into the upload collection, the drag and drop overlay will overflow the component.

<img width="561" alt="image" src="https://github.com/user-attachments/assets/4af7da9b-23fb-4020-a829-3010cc2d3153">

### Affected Component

ui5-upload-collection

### Expected Behaviour

Icon and text should not overflow.

### Priority

None

### UI5 Web Components Version

2.2.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by LidiyaGeorgieva** [comment]
Hello @tkeiner ,

Please provide isolated reproducible example.
If I test on https://sap.github.io/ui5-webcomponents/nightly/components/fiori/UploadCollection/#drag-and-drop I could not reproduce the issue - the height is enough and there is no overflow.

Best Regards,
Lidiya

**Comment by tkeiner** [comment]
Hello @LidiyaGeorgieva,
sorry I could not attach a stackBlitz example, had some issue with it.

In order to replicate the bug, there needs to be only a single item in the collection. Like this:
```html
    <ui5-upload-collection>
        <ui5-upload-collection-item file-name="LaptopHT-1000.jpg" upload-state="Complete">
            uploadState="Complete"
            <img src="https://sap.github.io/ui5-webcomponents/nightly/images/HT-1000.jpg" slot="thumbnail">
        </ui5-upload-collection-item>
    </ui5-upload-collection>
```

I think in the example you provided the bug is not occuring because of the long description that breaks into a second line and by that increasing the height of the item. In https://sap.github.io/ui5-webcomponents/nightly/components/fiori/UploadCollection/#upload-states you can see that icon and text overflow if there is only one attachment.

Kind regards, Tobias

**Comment by LidiyaGeorgieva** [comment]
Hello Hello @SAP/ui5-webcomponents-topic-rd please have a look.
