### ISSUE TITLE
[Feature Request]: ui5-color-picker option to disable transparency

### ISSUE THREAD

**Issue by brandon-sap** [SAP/ui5-webcomponents#9979]
### Feature Request Description

The ability to disable transparency. Hide transparency controls in the user interface.

### Proposed Solution

Maybe something like a "hide-transparency" attribute.
<ui5-color-picker hide-transparency></ui5-color-picker>

![image](https://github.com/user-attachments/assets/a193c5be-b2d1-4d4d-afde-de3dc2e4fda8)

The left is how it looks by default, the right might be what it looks like when transparency is hidden. Doesn't really matter to me exactly how it looks, you guys can figure out a way to make it look good!

### Proposed Alternatives

Currently using a very outdated library. It's a great color picker, but it's so outdated that it's finally begun to cause us issues.

### Organization

SAP

### Additional Context

We need this for an email editor. Not all email clients support transparency (Outlook on Windows). Outlook simply ignores colors defined with rgba(). We could fallback to removing the alpha after the color has been picked, but that significantly changes the color!

Here is some HTML with some background color and 2 pieces of content with the same color other than transparency. It's displayed in Chrome on the left, and Outlook on the right. It's not email HTML, so Outlook doesn't render it well, but the color is the important thing. Notice the difference in the colors within Chrome. Simply removing the transparency is a significant change! (Especially since there's a light grey background). In Outlook, the rgba content has no color at all. You only see the grey background under that text.

![{8E85A653-5270-4C9F-8A68-1BD580ABE7B5}](https://github.com/user-attachments/assets/7afcd75e-60c5-490f-bd67-6cb428d7b648)

As a result, we must be able to hide/disable transparency in our color pickers. It's quite a shock to have your colors change this much!

We're not currently using this color picker, but it and the palette seem very nice, very similar to the one that we use, currently, so I'd love to switch! But this is a show stopper.

### Priority

Low

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by LidiyaGeorgieva** [comment]
Hello @SAP/ui5-webcomponents-topic-p, take a look of this feature request.

**Comment by DMihaylova** [comment]
Hi @brandon-sap,

Would it suit your needs if we implement in ui5-color-picker simplified mode as the one in UI5 Color Picker? https://ui5.sap.com/#/entity/sap.ui.unified.ColorPicker/sample/sap.ui.unified.sample.ColorPickerSimplified

If yes, could you please open E1 item as per the new design process? Let me know if assistance is needed ;)

Regards,
Diana

**Comment by brandon-sap** [comment]
I think that might work. I've asked stakeholders for feedback on it.
