### ISSUE TITLE
[Menu][MenuItem]: MenuItem font size has changed in ui5-webcomponents 1.24.11

### ISSUE THREAD

**Issue by shubhamnazare** [SAP/ui5-webcomponents#9986]
### Bug Description

After upgrading ui5-webcomponents to 1.24.11 and ui5-webcomponents-react to 1.29.11, the font size in menu looks larger.

before upgrade example: https://stackblitz.com/edit/vitejs-vite-jxd18i?file=src%2FApp.jsx,package.json
after upgrade example: https://stackblitz.com/edit/vitejs-vite-sscnqt?file=src%2FApp.jsx,package.json

### Affected Component

Menu, MenuItem

### Expected Behaviour

The font size should have been the same as before in ui5-webcomponents 1.23.3.

### Steps to Reproduce

1.
2.
3.
...

### Priority

Medium

### UI5 Web Components Version

1.24.11

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by hinzzx** [comment]
Hi @SAP/ui5-webcomponents-topic-b ,

It seems that a `font-size` CSS property is missing in the `ui5-menu-items`.

A possible solution would be, to add `font-size: var(--sapFontSize);` to the text in the `MenuListItem.css`;

Best Regards,
Stoyan

**Comment by shubhamnazare** [comment]
Hi @hinzzx could you please let me know the ETA on this and in which patch the fix will be available?

**Comment by shubhamnazare** [comment]
Hi @hinzzx 
Please let us know when this will be fixed as this is now high priority for us.

**Comment by hinzzx** [comment]
Hi @shubhamnazare ,

The bug is fixed and merged and will be available to be consumed the next week.

Best Regards,
Stoyan
