### ISSUE TITLE
[Feature Request]: Properties of type function

### ISSUE THREAD

**Issue by swendlandt** [SAP/ui5-webcomponents#9989]
### Feature Request Description

ui5-webcomponents define different types of properties: https://sap.github.io/ui5-webcomponents/docs/development/properties/#type

"function" is not one of them, but it could be helpful to pass callbacks to a custom web component. I am aware that in general custom events are preferable over callbacks for web components, but there are still use cases where callbacks make sense in my opinion, e.g. an asynchronous callback to fetch data.

### Proposed Solution

Provide a new type of property "function"

### Organization

SAP

### Priority

Medium

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by NHristov-sap** [comment]
Hello @SAP/ui5-webcomponents-topic-core , take a look of this feature request.

Best Regards,
Nikolay Hristov

**Comment by pskelin** [comment]
@swendlandt you don't strictly need a type other than `Boolean` and `Number` - they are used for converting from property to an attribute and vice versa. The remaining types are `String` which is 1:1 mapping with the attribute and the rest effectively set `{ noAttribute: true }`

For your usage, you can directly write
```ts
	@property({ noAttribute: true })
	callback?: () => void;
```

and then document what is the expected value of the property.
