### ISSUE TITLE
Bar's content disappears

### ISSUE THREAD

**Issue by LidiyaGeorgieva** [SAP/ui5-webcomponents#9995]
### Bug Description

Bar's content disappears when the bar is used inside Popover.
If the bar is without popover there is no bug.
If some other component is added after the bar (to test - uncomment the Message Strip in the sample) - there is no bug.

### Steps to Reproduce

1. Open [edited sample link](https://sap.github.io/ui5-webcomponents/nightly/play/#eyJpbmRleC5odG1sIjp7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuPCFET0NUWVBFIGh0bWw-XG48aHRtbCBsYW5nPVwiZW5cIj5cblxuXG5cbjxoZWFkPlxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG4gICAgPC9zdHlsZT5cblxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG4gICAgPC9zdHlsZT5cblxuICAgIDxtZXRhIGNoYXJzZXQ9XCJVVEYtOFwiPlxuICAgIDxtZXRhIG5hbWU9XCJ2aWV3cG9ydFwiIGNvbnRlbnQ9XCJ3aWR0aD1kZXZpY2Utd2lkdGgsIGluaXRpYWwtc2NhbGU9MS4wXCI-XG4gICAgPHRpdGxlPlNhbXBsZTwvdGl0bGU-XG48L2hlYWQ-XG5cbjxib2R5IHN0eWxlPVwiYmFja2dyb3VuZC1jb2xvcjogdmFyKC0tc2FwQmFja2dyb3VuZENvbG9yKVwiPlxuICAgIDxzdHlsZT5cbiAgICAgICAgYm9keSB7XG4gICAgICAgICAgICBoZWlnaHQ6IDMwMHB4O1xuICAgICAgICB9XG5cbiAgICAgICAgLnBvcG92ZXItY29udGVudCB7XG4gICAgICAgICAgICBkaXNwbGF5OiBmbGV4O1xuICAgICAgICAgICAgZmxleC1kaXJlY3Rpb246IGNvbHVtbjtcbiAgICAgICAgICAgIGp1c3RpZnktY29udGVudDogY2VudGVyO1xuICAgICAgICB9XG5cbiAgICAgICAgLnBvcG92ZXItZm9vdGVyIHtcbiAgICAgICAgICAgIGRpc3BsYXk6IGZsZXg7XG4gICAgICAgICAgICBqdXN0aWZ5LWNvbnRlbnQ6IGZsZXgtZW5kO1xuICAgICAgICAgICAgd2lkdGg6IDEwMCU7XG4gICAgICAgICAgICBhbGlnbi1pdGVtczogY2VudGVyO1xuICAgICAgICAgICAgcGFkZGluZzogMC41cmVtIDA7XG4gICAgICAgIH1cbiAgICA8L3N0eWxlPlxuXG4gIDwhLS0gcGxheWdyb3VuZC1mb2xkLWVuZCAtLT5cblxuXG4gICAgPHVpNS1idXR0b24gaWQ9XCJidG5cIj5PcGVuIFBvcG92ZXI8L3VpNS1idXR0b24-XG5cbiAgICA8dWk1LXBvcG92ZXIgb3BlbmVyPVwiYnRuXCIgaGVhZGVyLXRleHQ9XCJOZXdzbGV0dGVyIHN1YnNjcmlwdGlvblwiPlxuIFxuICAgICAgIDxkaXYgY2xhc3M9XCJub3RpZmljYXRpb25zUG9wb3ZlckhlYWRlclwiXG5cdFx0XHQgc2xvdD1cImhlYWRlclwiPlxuXHRcdFx0PHVpNS1iYXIgY2xhc3M9XCJub3RpZmljYXRpb25zUG9wb3ZlckJhclwiXG5cdFx0XHRcdFx0IGRlc2lnbj1cIkhlYWRlclwiPlxuXHRcdFx0XHQ8dWk1LXRpdGxlIGxldmVsPVwiSDVcIiBzbG90PVwic3RhcnRDb250ZW50XCI-Tm90aWZpY2F0aW9uczwvdWk1LXRpdGxlPlxuXHRcdFx0XHQ8dWk1LWJ1dHRvbiBpZD1cInNob3ctbWVzc2FnZS1zdHJpcFwiIGRlc2lnbj1cIkVtcGhhc2l6ZWRcIiBzbG90PVwiZW5kQ29udGVudFwiPlNob3cgTS4gU3RyaXA8L3VpNS1idXR0b24-XG5cdFx0XHRcdDx1aTUtYnV0dG9uIGRlc2lnbj1cIlRyYW5zcGFyZW50XCIgc2xvdD1cImVuZENvbnRlbnRcIj5DbGVhciBBbGw8L3VpNS1idXR0b24-XG5cdFx0XHRcdDx1aTUtYnV0dG9uIGRlc2lnbj1cIlRyYW5zcGFyZW50XCIgaWNvbj1cInNvcnRcIiB0b29sdGlwPVwiU29ydFwiIHNsb3Q9XCJlbmRDb250ZW50XCI-PC91aTUtYnV0dG9uPlxuXHRcdFx0XHQ8dWk1LWJ1dHRvbiBkZXNpZ249XCJUcmFuc3BhcmVudFwiIGljb249XCJhY3Rpb24tc2V0dGluZ3NcIiB0b29sdGlwPVwiR28gdG8gc2V0dGluZ3NcIiBzbG90PVwiZW5kQ29udGVudFwiPjwvdWk1LWJ1dHRvbj5cblx0XHRcdDwvdWk1LWJhcj5cblx0XHRcdDwhLS08dWk1LW1lc3NhZ2Utc3RyaXAgaWQ9XCJtZXNzYWdlLXN0cmlwLWVycm9yXCJcblx0XHRcdFx0XHRcdFx0ICAgY2xhc3M9XCJub3RpZmljYXRpb25zTWVzc2FnZVN0cmlwXCJcblx0XHRcdFx0XHRcdFx0ICAgZGVzaWduPVwiTmVnYXRpdmVcIj5Tb21ldGhpbmcgd2VudCB3cm9uZy5cbiAgICAgICAgICAgPC91aTUtbWVzc2FnZS1zdHJpcD4tLT5cblx0XHQ8L2Rpdj5cblxuICAgIDwvdWk1LXBvcG92ZXI-XG5cbiAgICA8IS0tIHBsYXlncm91bmQtZm9sZCAtLT5cbiAgICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCJtYWluLmpzXCI-PC9zY3JpcHQ-XG48L2JvZHk-XG5cbjwvaHRtbD5cbjwhLS0gcGxheWdyb3VuZC1mb2xkLWVuZCAtLT5cbiJ9LCJtYWluLmpzIjp7Im5hbWUiOiJtYWluLmpzIiwiY29udGVudCI6ImltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L0F2YXRhci5qc1wiO1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzL2Rpc3QvTGlzdC5qc1wiO1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzL2Rpc3QvUG9wb3Zlci5qc1wiO1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzL2Rpc3QvVGl0bGUuanNcIjtcbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L0J1dHRvbi5qc1wiO1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzL2Rpc3QvTWVudS5qc1wiO1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzL2Rpc3QvQmFyLmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMvZGlzdC9NZXNzYWdlU3RyaXAuanNcIjtcbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy1pY29ucy9kaXN0L2FjdGlvbi1zZXR0aW5ncy5qc1wiXG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMtaWNvbnMvZGlzdC9zb3J0LmpzXCJcbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy1maW9yaS9kaXN0L1NoZWxsQmFyLmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMtZmlvcmkvZGlzdC9Ob3RpZmljYXRpb25MaXN0LmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMtZmlvcmkvZGlzdC9Ob3RpZmljYXRpb25MaXN0R3JvdXBJdGVtLmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMtZmlvcmkvZGlzdC9Ob3RpZmljYXRpb25MaXN0SXRlbS5qc1wiO1xuXG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMtaWNvbnMvZGlzdC9lbXBsb3llZS5qc1wiO1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzLWljb25zL2Rpc3QvbWVzc2FnZS1lcnJvci5qc1wiO1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzLWljb25zL2Rpc3QvYWNjZXB0LmpzXCI7aW1wb3J0IFwiLi9wbGF5Z3JvdW5kLXN1cHBvcnQuanNcIjtcblxuXG5jb25zdCBidG4gPSBbLi4uZG9jdW1lbnQuZ2V0RWxlbWVudHNCeVRhZ05hbWUoXCJ1aTUtYnV0dG9uXCIpXVswXTtcbmNvbnN0IHBvcG92ZXIgPSBbLi4uZG9jdW1lbnQuZ2V0RWxlbWVudHNCeVRhZ05hbWUoXCJ1aTUtcG9wb3ZlclwiKV1bMF07XG5cbmJ0bi5hZGRFdmVudExpc3RlbmVyKFwiY2xpY2tcIiwgKCkgPT4ge1xuXHRwb3BvdmVyLm9wZW4gPSAhcG9wb3Zlci5vcGVuO1xufSk7In19)
2. Click on "Open Popover"
3. Observe how the bar content is shown for a sort time and then disappears

### Priority

High

### UI5 Web Components Version

main

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by NHristov-sap** [comment]
Hi @LidiyaGeorgieva ,

It seems that the ui5-bar takes all the available space of the header, which in this case is 0. I have tried to add `width: 100% ` to the div with `class="notificationsPopoverHeader"` and then the bar appears. Can you check if this width does not depend on Popover?

Best Regards,
Nikolay Hristov
