### ISSUE TITLE
[ToolbarButton]: `getDomRef` returns `undefined`

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#9996]
### Bug Description

When calling `getDomRef()` on a `ui5-toolbar-button` it always returns `undefined`.

This is a followup issue to this one: https://github.com/SAP/ui5-webcomponents/issues/9997

### Affected Component

ToolbarButton

### Expected Behaviour

It should return the DOM reference to the `ui5-button` inside the shadow root of the ui5-toolbar, as the ToolbarButton is an abstract component.

### Isolated Example

https://stackblitz.com/edit/github-k8annj?file=index.html,package.json,main.js

### Steps to Reproduce

1. Got to [StackBlitz](https://stackblitz.com/edit/github-k8annj?file=index.html,package.json,main.js)
2. Open dev tools
3. Press Log getDomRef button
4. See `undefined` in the console

### Priority

None

### UI5 Web Components Version

2.3.0

### Browser

Chrome, Edge, Firefox, Safari

### Organization

UI5WCR

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by NHristov-sap** [comment]
Hello @ui5-webcomponents-topic-p,

The reported issue is reproducible, that's why  I am forwarding this issue to you to take care of it.

Best Regards,
Nikolay Hristov
